### ISSUE TITLE
Why??

### ISSUE THREAD

**Issue by jonasman** [ParsePlatform/parse-server#1]
The blog post doesnt detail on why you are closing patse fown!!

**Comment by Aleyasen** [comment]
Good question!

**Comment by francocorreasosa** [comment]
@jonasman They need the servers for Facebook and all that bullshit.

**Comment by gfosco** [comment]
I don't think that is something we can get into here.

**Comment by enkhalifapro** [comment]
oh guys parse was very useful why did you do that ?

**Comment by jonasman** [comment]
Please be transparent.
If you are building something new and better let us know and we wont be mad at you :)

**Comment by francocorreasosa** [comment]
@gfosco Are you gonna update all SDK docs to the parse-server API?

**Comment by xorgy** [comment]
Because this is business. You cannot give everyone the same unicorn forever.
