### ISSUE TITLE
Setting Parse.serverURL

### ISSUE THREAD

**Issue by rravikot** [ParsePlatform/parse-server#10]
#Hello, here is my code
```
var ParseCloud = require('parse-cloud-express');
var ParseServer = require('parse-server').ParseServer;
var Parse = ParseCloud.Parse;

if (!process.env.DATABASE_URI) {
  console.log('DATABASE_URI not specified, falling back to localhost.');
}

var api = new ParseServer({
  databaseURI: process.env.DATABASE_URI || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + 'cloud/main.js',
  appId: 'appid',
  masterKey: 'masterkey',
  javascriptKey: 'javascriptkey'
});
// Client-keys like the javascript key or the .NET key are not necessary with parse-server
// If you wish you require them, you can set them as options in the initialization above:
// javascriptKey, restAPIKey, dotNetKey, clientKey


Parse.initialize('apikey', 'javascriptkey');
Parse.serverURL = 'http://localhost:3030/parse';

const pretty = new PrettyError();
const app = express();

// Serve the Parse API on the /parse URL prefix
var mountPath = process.env.PARSE_MOUNT || '/parse';
app.use(mountPath, api);

const server = new http.Server(app);
```

When I try to run this in my express app, I'm getting a proxy error. I am very new to express, could someone please help?

**Comment by wangmengyan95** [comment]
Hi @rravikot，you do not need `parse-cloud-express` for running cloud code. Check `cloud/main.js`, you can just edit your cloud code in that file.

**Comment by gfosco** [comment]
That could the issue here.  Please remove parse-cloud-express from the project and re-open if you have trouble.  Thanks.

**Comment by arkangelx** [comment]
Sign up / login doesn't work with Parse.serverURL.  
2016-04-26T11:41:56.004991+00:00 heroku[router]: at=info method=POST path="/parse/1/users" host=intense-hollows-60991.herokuapp.com request_id=cf67e258-bfd2-4b21-9537-878b4a30faf0 fwd="5.148.6.116" dyno=web.1 connect=2ms service=4ms status=403 bytes=466
