### ISSUE TITLE
New Facebook users are created with session data "action":"login" "authProvider":"password"

### ISSUE THREAD

**Issue by tamarinda** [ParsePlatform/parse-server#100]
Hi,

When registering with a new Facebook user, the entry in the _Session collection seems to be created with values:

`    "createdWith": {
        "action": "login",
        "authProvider": "password"
    },
` 
instead of 
`{"action":"login","authProvider":"facebook"}`

as it was in parse.com

Also the username of this new created user is empty, where before it was a hash. This gives problems when trying to login again with Facebook auth. 

I see in users.js `handleLogIn` that a session object is created with those `login` and `password` values, but I don't see that this method is called when signing up with facebook, so the issue should be somewhere else.
Any hints on where the issue might be?

Thanks!
Tamara

**Comment by gfosco** [comment]
* Also the username of this new created user is empty, where before it was a hash. This gives problems when trying to login again with Facebook auth.

What problem?  True, Parse used to set it to randomness.. and we can probably update that here.

The other main place to look is RestWrite.js, in the handleFacebookAuthData method.

**Comment by tamarinda** [comment]
@gfosco thanks for your answer. 

> This gives problems when trying to login again with Facebook auth.

I wasn't specifically meaning that the lack of username was the problem, it was additional info I thought might be relevant. What is giving

> problems when trying to login again with Facebook auth.

would be then the session being created with `"authprovider":"password"` only. Thanks for pointing me to the class, I'll look into that.

**Comment by flovilmart** [comment]
I'll update that in #241 as I'll need to generate username hashes as well.

**Comment by gfosco** [comment]
This should be changed now with the new auth provider structure.  If you have any problems, please create a new issue.  Thanks.
