### ISSUE TITLE
How to see server logs with pm2?

### ISSUE THREAD

**Issue by gilthonweapps** [ParsePlatform/parse-server#1003]
Hi,

I have installed parse-server locally on my Mac with MongoDB hosted on mLab for testing purpose.

My package.json is as follow:
```
{
  "name": "ParseServer",
  "version": "1.0.0",
  "description": "Home-made Parse Server",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "parse-server": "~2.1.0"
  },
  "scripts": {
    "start": "VERBOSE=1 node index.js"
  },
  "engines": {
    "node": ">=4.3"
  }
}
```

With "VERBOSE=1" and server launched with "node start index.js", I see all the queries in my terminal.

Now, if I launch the server with pm2 "pm2 start index.js -i 1 --name ParseServer" and then perform "pm2 logs", I don't see my queries.

So my question is, how can I see my queries when I use parse-server with pm2?

Thanks

**Comment by flovilmart** [comment]
This will depend on your provider, your pm2 configuration and other parameters. 
In a general note, you should not use pm2 (or nodemon or forever for that matter) if you don't know how to properly configure it.

**Comment by altagir** [comment]
create a file named env.json in your parse node directory....
edit and enter in it:

```
[{
    "name"        : "NameOfYourApp",
    "script"      : "./index.js",
    "instances"   : 2,
    "env": {
        "VERBOSE" : "1",
        "DEBUG"   : "apn"
    }
}]
```

now run with :
`pm2 start env.json`

source: https://github.com/Unitech/pm2/issues/83

regards
