### ISSUE TITLE
Admin Dashboard

### ISSUE THREAD

**Issue by jcguarinpenaranda** [ParsePlatform/parse-server#1005]
Hello, my question is how do you manage Parse Server after migration? 
Right now, if you connect to Parse.com, you would have an administration dashboard really easy to use and very useful. Withe Parse Server, as far as I know there is no administration dashboard.
Do you plan developing it, or copying the existing Parse.com dashboard source code in the future?

**Comment by bohemima** [comment]
The very same Dashboard (with not yet all features, yet..) is available - https://github.com/ParsePlatform/parse-dashboard/

**Comment by jcguarinpenaranda** [comment]
woow! didn't know it

Thank you

Juan Camilo Guarín Peñaranda
Estudiante de Ingeniería Multimedia y Emprendedor en tecnología
Universidad Autónoma de Occidente
Otherwise Studios: http://otherwise-studios.com
<http://mailstat.us/tr/t/pleg6bmaikkbgvuq/h/http://otherwise-studios.com/>

2016-03-12 17:08 GMT-05:00 Henrik <notifications@github.com>:

**Comment by jcguarinpenaranda** [comment]
wow! I didn't know

Thank you!
