### ISSUE TITLE
Query on Relation not working properly (notEqualTo & equalTo)

### ISSUE THREAD

**Issue by 432player** [ParsePlatform/parse-server#1007]
I'm trying to retrieve users in a relation that are not the  [PFUser currentUser] but for some reason since moving to the Parse-Server the result returns with the currentUser as well.
Might **notEqualTo** not working properly?

The query is as follow (the relation is of _User):
 PFRelation *relation = [someObject relationForKey:relationKey];
query = [relation query];
[query whereKey:@"objectId" notEqualTo:[PFUser currentUser].objectId];
[query findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) {
        if (!error) {
            //current user is contained in objects array
         }
}];

Apparently this is also happening if I want to check if a user is in a relation with **equalTo** 
PFRelation *relation = [self relationForKey:key];
PFQuery *query = [relation query];
[query whereKey:@"objectId" equalTo:object.objectId];
[query countObjectsInBackgroundWithBlock:^(int count, NSError *error) {
        completionBlock(count > 0, error);
}];

If a user exists this should have returned count = 1, but apparently this returns count = 6 which means the whereKey parameter is being ignored completely.

I just want to remind that this code exactly worked before the migration to Parse-Server. 
Any ideas? Did this happen to anyone?

**Comment by 432player** [comment]
This didn't work on version 2.1.4, update to the latest version (currently 2.1.6) and this will begin working again.
Thanks everyone who's working on this project and making it a real gem!

**Comment by lolobosse** [comment]
@432player Does it work on the newest version (2.2.4) for you? It doesn't look like on my config.

But I guess you have it with an array and I have it with `Relation` so maybe it is related.

I think I'll try to create a detailed issue for that.
