### ISSUE TITLE
The destination database was not empty.

### ISSUE THREAD

**Issue by kimhongyeon** [ParsePlatform/parse-server#1009]
I made a cluster of mLab.com and one app's DB had been migrated successful.
1. I added new DB for another app in my cluster.
2. I tried to migrate hosted parse DB to mLab DB.
3. But error was occured!!
4. Migration tool shown "The destination database was not empty.".

Help me...

**Comment by drew-gross** [comment]
Did you maybe use the DB that already had data in it? The migration tool won't migrate an app to a database that already has data in it. If that is not the case, please open a ticket on [parse.com/help](), as that is where do support for migration issues.

**Comment by StolenCouchGames** [comment]
I have the same issue We've made a new server after we tried transferring to another. Now I can't start the migration again.

**Comment by MostafaS** [comment]
I have the same issue , i've made everything ready on azure and the db is EMPTY , but getting this error

**Comment by sidan5** [comment]
Same issue here using mLab on AWS.

**Comment by christianpbrink** [comment]
Has anyone found a resolution to this issue?

**Comment by kimhongyeon** [comment]
I had resolved this issue. Only changed DB name...

**Comment by marcoblagoiev** [comment]
Same issue, I tried creating 3 different databases with no results...

**Comment by bill-lin** [comment]
I got same issue. However, after clear all collections from mLab, the problem went away :)

**Comment by pcegarra** [comment]
open mongo cli, show dbs -> use mydata -> db.dropDatabase()

**Comment by dariuxmx** [comment]
I resolved this issue, if you are setting with heroku, go to Mongo Add on to open the Database and erase all collections. Try again to migrate your database from Parse and vuala!

Regards
