### ISSUE TITLE
Old version app can't read new parse file in my S3 

### ISSUE THREAD

**Issue by kimhongyeon** [ParsePlatform/parse-server#1010]
I had migrated very successful an app.
The app is set S3Adapter and filekey of hosted parse.
The new test app use my parse-server and service app(current version of appstore) use hosted parse.com.

problem
The new test app can read old parse file(hosted parse.com) and new parse file(hosted my S3).
But current version of AppStore cannot read new parse file.
And dashboard of parse.com cannot read new parse file named ".bin". (old parse file is named "file")
When I clicked the file named ".bin" in dashboard of parse.com, my browser shown "access denied".
So I tried change CORS of my S3 to AllowedOrigin "*".
But same problem...
How can I do?

**Comment by gfosco** [comment]
It's a valid issue, but I don't think this is something we can address.  The users of the old app are hitting api.parse.com, which has no connection to your parse-server or your file adapter.  The way files are referenced in the database isn't something we can change, and you can't change the old app behavior, so this is an unfortunate symptom which will hopefully encourage your users to upgrade their app.
