### ISSUE TITLE
Parse Server loses MongoDB connection when MongoDB server is restarted

### ISSUE THREAD

**Issue by iOSDev33** [ParsePlatform/parse-server#1011]
I am running a parse-server on a Digital Ocean droplet in addition to a MongoDB server on a separate Digital Ocean droplet. When i reboot or restart the MongoDB server the connection between parse-server and MongoDB is lost and requires a stop and restart of the parse-server to get things back up and running. Not sure why thats happening and is there anything to prevent it from happening? I was hoping that if the MongoDB server was ever rebooted that once it was finished parse-server would just reconnect automatically. Thanks for all the awesome work you guys are doing!

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [x ] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x ] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
2 Digital Ocean Droplets

1 = Parse-Server running on Digital Ocean
2 = MongoDB running on Digital Ocean

#### Steps to reproduce
Reboot MongoDB server or Restart MongoDB from command line

#### Logs/Trace

**Comment by kenglou** [comment]
maybe you are not making your MongoDB replica set, so when the time you restart your MongoDB, the connection is dropped.

**Comment by iOSDev33** [comment]
Thank you! That was the problem!

**Comment by iOSDev33** [comment]
reopening because still having issues maintaining database connection after setting up a replication set. Heres what I am doing.

Step 1. Replication set up and running
Step 2. Kill the current Primary member
Step 3. Test connectivity and all seems to work.
Step 4. Restart the killed previous Primary
Step 5. Kill the current Primary member 
Step 6. Test connectivity and connection is now lost with Parse Server and requires a reboot.

Here is my sample format of the MongoDB connection URI:
mongodb://test:1234567@mongo0,mongo1,mongo2:27017/sample?replicaSet=sample

**Comment by flovilmart** [comment]
@iOSDev33 does it still occur with 2.2.4?

**Comment by drew-gross** [comment]
No response in many days, closing.

**Comment by kronos** [comment]
Same problem here. The version of parse-server is 2.2.10
