### ISSUE TITLE
matchesQuery on relation query always finds zero objects

### ISSUE THREAD

**Issue by jgaull** [ParsePlatform/parse-server#1014]
#### Environment Setup
parse-server 2.1.6, Heroku, MongoLab, iOS SDK 1.12.0

#### Steps to reproduce
```
var relationQuery = object.relation("relationKey").query();
var anotherQuery = new Parse.Query(Class);
anotherQuery.matchesQuery("key", relationQuery);
anotherQuery.find(); //Always finds 0 objects
```

This works correctly in hosted Parse. I also manually double-checked the db and can confirm this should find more than zero objects.

#### Logs/Trace
This error is showing up on the iOS side. May or may not be related:
` [Error]: Response status code was unacceptable: 403 (Code: 1, Version: 1.12.0)`

**Comment by Mahdi7s** [comment]
same problem here - parse server 2.1.6,
we have an android app that uses below methods in query and previously works(with hosted parse) but at this time non of them works correctly:
```
whereMatchesQuery
whereMatchesKeyInQuery
whereDoesNotMatchQuery
whereDoesNotMatchKeyInQuery
```

**Comment by flovilmart** [comment]
@jgaull please see that (gist)[https://gist.github.com/flovilmart/23b5ea6e9dd1c0a6e4e6] does that reflect your failing cases?

**Comment by jgaull** [comment]
Thanks @flovilmart! The only difference I can find is `relationQuery.equalTo('even', true);`. This can be found on lines 37 and 53. In my example the relation is used without adding any additional restrictions.

I will test today to see if adding a condition to my relation query makes it work.

**Comment by flovilmart** [comment]
@jgaull I added the restrictions to make sure I'd get the proper subset.
Maybe the bug is when no parameters are passed. I'll try it also

**Comment by jgaull** [comment]
@flovilmart I added `relationQuery.equalTo("booleanProperty", true)` and ensured that "booleanProperty" was set to true on every object in the relation. I got the same result: no objects found. Must be something else.

Thanks for the help! Let me know if you have an idea for something else to test.

**Comment by flovilmart** [comment]
uhm... Do you have ACL, class level permissions or anything else set? If you run the query as master, what does it do?

**Comment by jgaull** [comment]
ACL is default for _User object, public read and only the user has write. I am running the query as master using `useMasterKey()` in cloud code.

**Comment by flovilmart** [comment]
and the related objects are _Users ?

**Comment by jgaull** [comment]
Correct

**Comment by flovilmart** [comment]
I really can't reproduce the error. Can you dump me the _SCHEMA collection from mongoDB?

**Comment by flovilmart** [comment]
TBH, I'm out of ideas now, are you running it in Cloud Code? Parse.Cloud.useMasterKey() don't work, you have to pass {useMasterKey: true} to your `query.find()`. Does it help?

**Comment by jgaull** [comment]
Thanks @flovilmart! I tried {useMasterKey: true} and there was no change.

[Here is a link to my _SCHEMA dump](https://www.dropbox.com/s/9lhkdwx86enebfa/_SCHEMA.json?dl=0).

**Comment by flovilmart** [comment]
on which classes do you do your queries?

**Comment by jgaull** [comment]
Sorry, definitely should have included that info.

I'm using the "members" relation in Group to query for UserWeeklyStats in one place and Rides in another. Both find zero objects.

**Comment by flovilmart** [comment]
Does the relation query itself returns some values? Can you try to split the query in 2? relationQuery first, get the objects and do a containedIn? ThatMs tough as I can't reproduce the issue at all...

**Comment by jgaull** [comment]
I have tested splitting the query into two pieces. Both work independently as expected.

One thought I had was that, since this is my dev DB, some _Users have been deleted at various points during development. The relation probably still holds a reference to those deleted _Users. Is it possible that that's causing the query to break?

**Comment by flovilmart** [comment]
Tried deleting objects in the middle, and it behaves correctly, so the deletion doesn't seem to be the problem.

**Comment by flovilmart** [comment]
Can you set VERBOSE=1 on heroku (https://devcenter.heroku.com/articles/config-vars), and make a gist with the request logs ??

the interesting lines should be similar to:

```
GET /1/classes/AnOwner { 'user-agent': 'node-XMLHttpRequest, Parse/js1.7.1 (NodeJS 5.3.0)',
  accept: '*/*',
  'content-type': 'text/plain',
  host: 'localhost:8378',
  'content-length': '357',
  connection: 'close' } {
  "where": {
    "key": {
      "$inQuery": {
        "where": {
          "$relatedTo": {
            "object": {
              "__type": "Pointer",
              "className": "AnotherOwner",
              "objectId": "PBqgHRHCNd"
            },
            "key": "relationKey"
          },
          "even": true
        },
        "className": "AnObject"
      }
    }
  },
  "include": "key"
}
```

**Comment by flovilmart** [comment]
Does that look familiar? https://github.com/ParsePlatform/parse-server/issues/1036#issuecomment-196792097

**Comment by jgaull** [comment]
Thanks @flovilmart! I imported using the Parse migration tool from the beginning so I don't think I'm experiencing the same issue.

[Here is a gist with the log you asked for.](https://gist.github.com/jgaull/91a6cf0e5a20853b9c65)

**Comment by flovilmart** [comment]
I see that there is the startOfWeek parameter too in the query, does removing it solves the issue?

**Comment by jgaull** [comment]
Removing startOfWeek does not solve the issue. [This log is the query without startOfWeek](https://gist.github.com/jgaull/e08776594a223c706a64). [This log is a the same issue when querying for Ride objects](https://gist.github.com/jgaull/c3e30d35d3d7847e665e).

**Comment by flovilmart** [comment]
We identified the issue, and working on a fix.
in the meantime, you should be able to work around by fetching the object you're calling .relation('relationKey') on.

**Comment by jgaull** [comment]
Nice work! Thanks so much for your help!

**Comment by flovilmart** [comment]
You should thank @gfosco ! the was the brains :)

**Comment by awgeorge** [comment]
Any chance this has snuck back into 2.3.6? matchesKeyInQuery is always returning an empty set.

**Comment by flovilmart** [comment]
We usually don't remove tests, in order to prevent regressions. Can you open a new issue as it's been closed a while ago?

**Comment by dipeshparashar** [comment]
The same issue exists. MatchesQuery works in Swift but not in JS.  
[https://github.com/parse-community/parse-server/issues/6883](url)
