### ISSUE TITLE
Stripe with cloud code in Parse Server

### ISSUE THREAD

**Issue by ball1008** [ParsePlatform/parse-server#1015]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [x ] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [ x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [ x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
It is not clear if Parse server supports the Stripe integration that was available in hosted Parse.  The migration guide states "Use the official npm module" but it is not clear to me how to use covert my existing cloud code that used the Parse/Stripe integration.  Do you have documentation or links to examples?

**Comment by flovilmart** [comment]
Please refer to the official stripe SDK documentation: https://stripe.com/docs/api/node
