### ISSUE TITLE
Cloud code hook for user login

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/parse-server#1016]
I'm able to use beforeSave and afterSave for my Parse.User object so that I can use it to synchronise my existing user database through rest api to my new parse server application. What I'm trying to do is:

1. Allow user to user Parse Javascript sdk to login/register
2. To call my existing rest api to login/register 
3. To make the user data in parse server synchronized with my current backend database.

My question is how I can implement a function like beforeLogin?

**Comment by zhouhao27** [comment]
Of course, I can write cloud code for this. But then I can't use parse client sdk to login anymore.

**Comment by gfosco** [comment]
Looks like you could fork/edit `UsersRouter` to catch all the user-related calls, and as long as you still persist _User records and return what the client expects, the SDK should still work.  I think most of this logic will move to `UserController` eventually, making it easier to make & inject your own user behaviors.

Alternatively, you could use a combination... a cloud function to login, which returns a sessionToken, and then use the "become" method on the client to inflate that user object.
