### ISSUE TITLE
http://localhost:1337/parse 403 error?

### ISSUE THREAD

**Issue by ggamzzak** [ParsePlatform/parse-server#1017]
Hi~
I followed a Parse-Server, and completed.
And I tested that it passed a data by POST, GET.
This far no problems.

So, http://localhost:1337/parse URI responsed a 403 error in browser.
Is this expected?

Thanks for your attention.

**Comment by robert-wallis** [comment]
Yes, because your browser doesn't send the `X-Parse-Application-Id` header which is required to authenticate.  And `403` means that the app id that was sent (none) is unauthorized (forbidden).

**Comment by ggamzzak** [comment]
I got it. Thank you~
