### ISSUE TITLE
Cloud code live reload

### ISSUE THREAD

**Issue by rooswelt** [ParsePlatform/parse-server#1019]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [X ] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [X ] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [X ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#######
Is there a way to live reload cloud code without restarting entire parse server?

**Comment by flovilmart** [comment]
There is no way at the moment. Please submit a pull request if you feel that's a necessary feature

**Comment by MarsVard** [comment]
Anybody working on this?

**Comment by oallouch** [comment]
+1

**Comment by MarsVard** [comment]
@flovilmart can this issue be reopend so somebody with more knowledge about it can maybe see and fix it? or at least give some tips on how to fix this.

**Comment by flovilmart** [comment]
I'm not sure there is an actual fix without refactoring completely the way cloud code is run, by either forking processes or run it inside it's own VM. After that you'd have to implement a safe way to upload your cloud code files to the server(s) and reload the newly updated scripts from there. 

You can also use Parse Cloud Express and run cloud code on a separate server.

**Comment by MarsVard** [comment]
@flovilmart  Thanks for the clarification! I'll check out Parse Cloud Express.

How come reloading works in parse.com? does parse.com use a seperate server for Cloud Code?

**Comment by flovilmart** [comment]
Parse.com was written in go and was spawning a V8 for each cloud code request.

**Comment by difelice** [comment]
Just run server with `nodemon` "watching" the `cloud` folder:

```js
npx nodemon -w ./cloud parse-server
```
