### ISSUE TITLE
Using Node.php instead of Node.js

### ISSUE THREAD

**Issue by AstonBraham** [ParsePlatform/parse-server#102]
Hello everyone..

Please, Have anyone tried to run parse server on node.php (https://github.com/niutech/node.php) ?
I am about to buy a shared webhosting to try it... So if not I will leave feedback here

**Comment by matteocontrini** [comment]
What's that? ahah
Get a cheap VPS and use a serious installation of Node.js.

**Comment by poseidonsw** [comment]
you're better off getting set up on DigitalOcean then wasting your time trying to get a MongoDB and parse server running on a shared hosting site

**Comment by didierfranc** [comment]
You have great guides to be live in minutes at the bottom here https://github.com/ParsePlatform/parse-server/wiki
