### ISSUE TITLE
api.parse.com/1/users 401 (Unauthorized)

### ISSUE THREAD

**Issue by jitsingh89** [ParsePlatform/parse-server#1022]
I am not able to signup using parse user object.can anyone tell me how can i signup, i am writing code like this:-

function Signup(user_info){
    
      Parse.User.signUp(user_info.displayName, "ABC", { ACL: new Parse.ACL() }, {
      success: function(user) {
        console.log(user);
      },
      error: function(user, error) {
        console.log("error " +error);
      }
    });
    
  }

getting error:-

POST https://api.parse.com/1/users 401 (Unauthorized)

I have also initialize app with key and app id.

**Comment by flovilmart** [comment]
you should pass a dictionary to the signUp that at lease has:

{
username: 'username'
password: 'apassword'
}
