### ISSUE TITLE
Does analytics work in open source parse-server?

### ISSUE THREAD

**Issue by astanton** [ParsePlatform/parse-server#1024]
While I understand that the dashboard does not have the analytics engine running on it to create the nice views and reports, I was wondering if the actual PFAnalytic stuff still works from the SDK with the open source parse-server?  

I'm assuming under the hood it was just sending stuff to the mongoDB, and then the Analytics section in the dashboard just reported on those values in the database.

If my assumption is correct, can we still use PFAnalytic calls and then create our own reporting stuff based on the information thrown into the DB?

**Comment by noder199** [comment]
Nope, analytics not in parse-server.

**Comment by flovilmart** [comment]
I guess that answers the question!
