### ISSUE TITLE
Parse File Migration from Parse S3

### ISSUE THREAD

**Issue by viraj** [ParsePlatform/parse-server#103]
Hi Parse team,

I successfully migrated my app but I'm having difficult time accessing the PFFile. 

1. Are those PFFiles still on Parse ? Even after migration ?
2. If so how can we migrate those files ? Does it need to ?
3. If its not where are there and how can I access them ?

Need your help.

**Comment by skinp** [comment]
@viraj those files are still on Parse. The old PFFile objects you migrated will still point to the original files hosted on Parse.

We are currently working on tooling allowing you to migrate those files.

**Comment by viraj** [comment]
Thanks. Let us know when its ready.

**Comment by gfosco** [comment]
If you provide the File Key (from Parse dashboard), then parse-server can render the proper url key when ParseFile columns are included in query results.

**Comment by gfosco** [comment]
Continue discussion in #8.

**Comment by GuichiZhao** [comment]
Any updates related to file migration now?

**Comment by flovilmart** [comment]
@GuichiZhao check https://github.com/parse-server-modules/parse-files-utils

**Comment by GuichiZhao** [comment]
@flovilmart  Thanks

**Comment by apersaud** [comment]
If anyone else is looking for another Parse File to S3 migration tool, we made ours open source: https://github.com/modernistik/parse-file-migration 

If you are ok with Heroku, you can use the heroku deploy button provided and then delete the heroku instance once it has completed.

**Comment by flovilmart** [comment]
note that the parse-files-utils is leveraging mongodb directly and the file adapters too, so not S3 specific.
