### ISSUE TITLE
Cloud functions always connect to the online parse-db?

### ISSUE THREAD

**Issue by huang1196** [ParsePlatform/parse-server#1030]
I follow the guide "Deploy to AWS" and configure my own mlab database.
Everything seems ok when I test by:

`curl -X POST \ -H "X-Parse-Application-Id: APP_ID" \ -H "Content-Type: application/json" \ -d '{"score":1337,"playerName":"John Doe","cheatMode":false}' \ http://YOUR_EB_PARSE_SERVER_URL/parse/classes/GameScore  `

The doc successfully insert into my own mlab db.

But If I run the cloud functions, the server would read the database which is used by online-parse.
Write op also the same. How could I connect to my own database when I am using cloud func?

guide:https://mobile.awsblog.com/post/TxCD57GZLM2JR/How-to-set-up-Parse-Server-on-AWS-using-AWS-Elastic-Beanstalk

**Comment by flovilmart** [comment]
Are you still running CloudCode on parse.com?

**Comment by huang1196** [comment]
@flovilmart  yes. 
Does that matter?  I am thinking if I set databaseURI, the cloud code (in my local parse-server) should query the specific db.

**Comment by flovilmart** [comment]
did you migrate your database from parse to mlab?

**Comment by huang1196** [comment]
@flovilmart  not yet.

Can I build up my own parse-server and DB without migration? 
Firstly I set up my local parse-server, and than specify databaseURI. 

I can save “/classes/GameScore” successfully to my db. So I think the cloud code should also read this db.

**Comment by flovilmart** [comment]
You can definitely do that, but cloud code will have to be included on your parse server and not on parse.com

**Comment by huang1196** [comment]
@flovilmart 

I've copied the parse.com cloud code to my local parse-server. 

You mean that I should remove the cloud code on parse.com firstly?

Now I am calling my local server's cloud code and I can see logs. Everything is ok except that the query would read db on parse.com instead my local db. (But “/classes/GameScore” can saved into my local db). I am confused.

**Comment by huang1196** [comment]
@flovilmart Hi Thanks.

I think I know the problem. 

My local database is on the same server with local parse-server.  Due to some reasons, my local parse-server cannot connect to my local db. Then it will auto connect the db on parse.com (according to appid).

Now I build up local db on another instance, all things worked! 
Just change
` databaseURI: databaseUri || 'mongodb://test_admin:ppwwd@localhost:28017/test'`
to
` databaseURI: databaseUri || 'mongodb://test_admin:ppwwd@10.XX.XX.XX:28017/test'`

It worked!

But I still confused that why not just throw an connection error instead of connecting online db on parse.com
