### ISSUE TITLE
Link to "configure an app which connects to Parse Server" broken

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/parse-server#1033]
The url link to "configure an app which connects to Parse Server." broken in document.

**Comment by zhouhao27** [comment]
It's pointed to http://parse.local:3001/apps/quickstart#parse_data/mobile/ios. Should be http://parse.com/apps/quickstart#parse_data/mobile/ios

**Comment by drew-gross** [comment]
Could you be more specific about which document you are referring to?

**Comment by zhouhao27** [comment]
For push notification. I think the correct link should be:  http://parse.com/apps/quickstart#parse_data/mobile/ios

**Comment by drew-gross** [comment]
cc @hramos

**Comment by hramos** [comment]
Hey @zhouhao27, can you point to the actual document with a broken link? I don't see any references to parse.local in the parse.com quick start guides.

**Comment by hramos** [comment]
Found them at https://github.com/ParsePlatform/parse-server/wiki/Push. I've updated the wiki with the correct links. Thanks @zhouhao27!
