### ISSUE TITLE
Relational query returns 0 object on iOS SDK

### ISSUE THREAD

**Issue by vferdiansyah** [ParsePlatform/parse-server#1036]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [X] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [X] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Ubuntu 14.04 64 bit
Parse-Server 2.1.6

#### Steps to reproduce
I'm doing relational query to get opening hours of a restaurant where restaurant name matches certain keywords. When I'm querying it on my iOS app, it returns 0 object.

````
PFQuery *restaurantQuery = [PFQuery queryWithClassName:@"Restaurant"];
	[restaurantQuery whereKey:@"name" equalTo:self.selectedRestaurantName];
	
	PFQuery *hoursQuery = [PFQuery queryWithClassName:@"Hour"];
	[hoursQuery whereKey:@"restaurant" matchesKey:@"objectId" inQuery:restaurantQuery];
	[hoursQuery whereKey:@"days" equalTo:[NSString stringWithFormat:@"%ld", (long)[Utility getWeekday]]];
	
	[hoursQuery findObjectsInBackgroundWithBlock:^(NSArray * _Nullable objects, NSError * _Nullable error) {
		if (!error) {
			self.restaurantHours = [[NSArray alloc] initWithArray:objects];
		} else {
			NSLog(@"%@", error);
			self.restaurantHours = [[NSArray alloc] init];
		}
		
		[self.tableView reloadData];
	}];
````

But when I tried to query it using cURL, it returns the result that I needed.

`curl -X GET -H "X-Parse-Application-Id: myAppID" -H "X-Parse-REST-API-Key: myRESTKey" -G --data-urlencode 'where={"restaurant":{"$inQuery":{"where":{"name":"selectedRestaurantName"},"className":"Restaurant"}},"days":"3"}' https://my_url.com:1337/parse/classes/myClass`

**Comment by harrygt** [comment]
How did you migrate your data? We had this issue when we exported data from Parse and then imported into Mlab.com. The problem with that is that it formats the objects slightly differently. Not sure if you're running into the same issue here but maybe check the data migration?

**Comment by flovilmart** [comment]
@harrygt how different is the format? How did you solve your issue?

**Comment by harrygt** [comment]
Basically when we imported into mLab.com using this:
`mongoimport -h databaseURL -d databaseName -c PDF -u user -p password --jsonArray PDF.json`

We would get "parentInspection" as the name of the relationship to this PDF's parent Inspection. But in iOS this didn't work and would return 0 results. (it also wasn't clear we had to use --jsonArray, before using that mlab.com would just import everything into one document instead of individual objects). 

So we then just went ahead and used the Parse Migration button and let that complete. Now the parentInspection relationship is called '_p_parentInspection' and iOS works fully. 

So not sure why the _p_ is not added when importing using mongoimport but it is added when using the migration button on parse.com.

**Comment by flovilmart** [comment]
@harrygt so what you did was getting all the collections from parse through the export button, then importing the results with mongoimport right?

**Comment by harrygt** [comment]
Yep exactly. See the example I just added to previous comment.

**Comment by flovilmart** [comment]
Thanks! We have other issues related to that (like #1014) and you don't notice any error with relationalQueries like matchesQuery etc...?

**Comment by vferdiansyah** [comment]
@harrygt I migrated my data using Parse Migration button.

**Comment by flovilmart** [comment]
I'll close that one as it's a duplicate from #1014

**Comment by harrygt** [comment]
We seem to have no problems but if the file isn't found in a getDataInBackgroundWithBlock then we do get [Error]: Response status code was unacceptable: 404 (Code: 1, Version: 1.12.0). We are using AWS with S3Adaptor so not sure if that has anything to do with it but we only get that error code on files that were not uploaded to S3 during our testing.

**Comment by vferdiansyah** [comment]
@harrygt the thing is I don't get any errors at all so I'm not sure what went wrong.

**Comment by harrygt** [comment]
Maybe try:
`[hoursQuery whereKey:@"restaurant.name" equalTo:self.selectedRestaurantName];`
I'm sure you could do that which avoids the matching query? Other than that I am not entirely sure sorry!

**Comment by vferdiansyah** [comment]
@harrygt still not working but thanks a lot for your help!

**Comment by flovilmart** [comment]
What is restaurant? an pointer or just the objectId?

**Comment by harrygt** [comment]
Sorry I couldn't solve it! 

Maybe take a look at the data in mlab.com and see which way its formatted. Maybe that will help figure it out like this example:

mongoimport way:
`"parentInspection": { "__type": "Pointer", "className": "Inspection", "objectId": "PNLEniZswJ" }`
parse.com migration: 
`"_p_parentInspection": "Inspection$yGts7DGTry"`

**Comment by vferdiansyah** [comment]
@flovilmart restaurant is a pointer to an object in Restaurant class

**Comment by flovilmart** [comment]
if that's like that then :+1: 

```
[hoursQuery whereKey:@"restaurant" matchesKey:@"objectId" inQuery:restaurantQuery];
// should be 

[hoursQuery whereKey:@"restaurant" matchesQuery:restaurantQuery];

```

**Comment by vferdiansyah** [comment]
@flovilmart wow that solved it! Thanks a lot!
