### ISSUE TITLE
Problem save

### ISSUE THREAD

**Issue by RobertNNms** [ParsePlatform/parse-server#1038]
Hi,

I used a parser-server v2.1.5, parse-dashboard, Parse-SDK-iOS v1.12.0, and I have a problem with "Save". (see my simplified code below)
I need to save again because of the relationship, and I get an Error. Without save, I lose the relation.

Any idea?

Thanks

```
 PFObject *sale = [PFObject objectWithClassName:@"Sales"];    
 sale[JSON_KEY_CART_ORDERID] = datacenter.dataCart.lastOrderId;
 [sale setACL:defaultACL];
    
 BOOL saved = [sale save];
 if (saved) { // OK
    PFRelation *relProducts = [sale relationForKey:@"Products"];

    for (NSMutableDictionary *lineCart in arrCart) { 
        PFObject *myProduct = [[PFObject alloc] initWithClassName:@"myProduct"];        
        myProduct[JSON_KEY_DATE] = [NSDate date];        
        [myProduct setACL:defaultACL];
        
        saved = [myProduct save]; // OK
        if (saved) {
            [relProducts addObject:myProduct];
            
            PFRelation *relSales = [myProduct relationForKey:@"Sales"];
            [relSales addObject:sale];
            saved = [myProduct save]; **// Error**  
        }
    }
    saved = [sale save];** // Error  **
}

```

**Comment by flovilmart** [comment]
You mind sharing what the error is?

**Comment by RobertNNms** [comment]
For get error code, I need used "saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error)", and Error is :
"Error Domain=Parse Code=101 "Object not found." UserInfo={code=101, temporary=0, error=Object not found., NSLocalizedDescription=Object not found.}"

**Comment by flovilmart** [comment]
What is your default ACL? can the current user (if set) write into that object? It sure seems that because you're setting an ACL the second save is not working correctly

**Comment by RobertNNms** [comment]
I think, the second 'save' work (because my relation is saved -> I see in my Parse-Dashboard), but I get an error code.

My ACL:
[PFUser enableAutomaticUser];
 defaultACL = [PFACL ACL];
 defaultACL.publicReadAccess = YES;
 defaultACL.publicWriteAccess = NO;
 [PFACL setDefaultACL:defaultACL withAccessForCurrentUser:YES];

**Comment by flovilmart** [comment]
Is your currentUser saved/loggedin? Does it have an objectId?

**Comment by RobertNNms** [comment]
1/ Sorry, error of copy : 'salesBottle' replace by 'myProduct'

2/ Printing description of currentUser: (objectId is present)
<PFUser: 0x7fc8ebb13560, objectId: 6mHBeHUk57, localId: (null)> {
    ACL = "<PFACL: 0x7fc8eada7450>";
    email = "robertnnms@gmail.com";
}

**Comment by flovilmart** [comment]
You say there are 2 errors in your code, both errors are object not found?

**Comment by RobertNNms** [comment]
Yes...

**Comment by flovilmart** [comment]
I would need the logs to see what's really going on

**Comment by RobertNNms** [comment]
iOS ? Server ? How do I enable the logs?

**Comment by flovilmart** [comment]
server, start the server with the environment variable set: VERBOSE=1

**Comment by RobertNNms** [comment]
Ok, I have a logs. How can I send you the logs in private?

**Comment by flovilmart** [comment]
send it at my email florent [at] flovilmart.com

**Comment by RobertNNms** [comment]
Sent, thanks.

**Comment by flovilmart** [comment]
Closing now as your problem is completely unrelated to parse-server and lies in your client code.
