### ISSUE TITLE
OAuth example

### ISSUE THREAD

**Issue by oallouch** [ParsePlatform/parse-server#1039]
Hi,

I'm a little bit lost as how to implement a OAuth login (Facebook, Twitter, Google) in a js (cordova/react) app.
I asked for an example in the JS SDK repository without success.
https://github.com/ParsePlatform/Parse-SDK-JS/issues/222

How does all this work ? Or should I use a client lib like redux-auth ?

Thx a lot in advance,

Olivier Allouch

**Comment by flovilmart** [comment]
Please use stackoverflow for those questions. Issues reported here are for bugs and enhancements related to parse-server
