### ISSUE TITLE
Sending push from .Net client SDK

### ISSUE THREAD

**Issue by oyvindvol** [ParsePlatform/parse-server#1042]
I am using the Parse 1.7.0 Nuget package in my .Net parse client. Before migrating I sendt pushes from .Net code like this:

```
var push = new ParsePush {
                      Channels = new List<string> { "channel" },
                      Data = new Dictionary<string, object> {
                          { "alert", "alertText" },
                          { "badge", 1 },
                          { "sound", "default" }
                       }};
await push.SendAsync();
```

After migration I get this exception when sending push: ``unauthorized: master key is required``. Where do I put the master key for sending push notifications from .Net SDK?

**Comment by drew-gross** [comment]
Currently client push is not supported. You will need to create a cloud function to send the push, then call that from the client.

**Comment by oyvindvol** [comment]
Ok, thanks.
