### ISSUE TITLE
Query withinKilometers Causes Timeout Exception With Parse-Server

### ISSUE THREAD

**Issue by 432player** [ParsePlatform/parse-server#1043]
Using Parse the Query **withinKilometers** worked perfectly from IOS and Android.
After migrating to Parse-Server **withinKilometers** makes server non-respondent and stuck (timeout exception).

Apparently this issue is caused by wrong indexing in the MongoDB of the Geo Location field of the collection. Let's say I have an Object called Place and a field of location which is a PFGoePoint.
The location field in the MongoDB is indexed "2d" where apparently it should be "2dsphere".
BUT :)  we tried updating our field called location from "2d" to "2dsphere" but it didn't work for us. So for now we're filtering the distance of objects on the client side with hope this will somehow be fixed.

Here's a mongo shell script to to get your field working again with the Geo Location queries and Parse:
 db.Place.ensureIndex({ location: "2dsphere" });

We changed the index through the mongoDB page because we're not using the shell. But it should have given the same result.

Any help would be appreciated.

**Comment by hramos** [comment]
What version of MongoDB are you using and which engine?

**Comment by 432player** [comment]
Hi @hramos thanks for your reply.
we're running 3.0.9
I believe this should be the latest version.

**Comment by hramos** [comment]
For geoqueries you'll want to give MongoDB 3.2 a shot. For background, hosted Parse apps were served by both Mongo 2.6 and Mongo 3.0 depending on the type of query being handled.

**Comment by 432player** [comment]
Thanks @hramos unfortunately mLab is supporting at this point lower versions of MobgoDB.
<img width="910" alt="screen shot 2016-03-24 at 10 21 09" src="https://cloud.githubusercontent.com/assets/15979277/14011830/34cf10f4-f1aa-11e5-9302-6e94c8a92755.png">

We'll wait for when it does support. until then we'll perform the GeoQueries on the client side.
Thank you for your concern and help
Cheers

**Comment by Tux1** [comment]
Same issue with mongo 3.2. I need to build a "2dsphere" index before using `withinKilometer` and so on
