### ISSUE TITLE
Include key in cloud code fails to even return the property, let alone the full data of the pointer

### ISSUE THREAD

**Issue by kevflynn** [ParsePlatform/parse-server#1047]
Calling an 'include' constraint on a query from a cloud function as defined with: Parse.Cloud.define("discovery") - makes it so the included pointer does NOT get returned in the result. As in, the property doesn't exist on the returned result. Removing the 'include' constraint, the same objects return with the property, however without the data. Code sample, below.

Running a simple query:

    `var Member = Parse.Object.extend("Member");
    var query = new Parse.Query(Member);

    // If I comment out the include key constraints, the properties are 
    // returned without data. If I uncomment, the properties are not even included at     all.
    query.include("chat"); // chat is a relational pointer object, Chat
    query.include("user"); // user is a relation pointer object, Parse.User/PFUser

    return query.find().then(function(members){
        _.each(members, function(member){
            // Chat property doesn't even 
            if (member.get("chat")) {
                // Prints 100% of the time if I don't call include("chat");
                // But no data is attached. 
                console.log(member.get("chat").id);
            } else {
                // Prints 100% of the time if I don't call include("chat");
                // But no data is attached. 
                console.log("Member with no chat:? "+ member.id);
            }
        }); 
        return Parse.Promise.as(true);
    });`

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

**Comment by kevflynn** [comment]
FYI - this is still running in main Parse server environment, so I assume that's running the lastest version of Parse Server.

**Comment by flovilmart** [comment]
You're running on parse.com cloud code?

**Comment by gfosco** [comment]
@kevflynn Parse.com hosted applications do not run Parse Server.

These are "Pointer" columns?  Not relations...   This should work, if the user making the query has access to read the pointed-to objects.  You can override security by passing `{ useMasterKey: true }` into the `find()` call.   

Closing this as it is unrelated to parse-server.  Bug reports for hosted parse can still be opened through http://parse.com/help --  Thanks.

**Comment by kevflynn** [comment]
Thanks
