### ISSUE TITLE
Parse Communication Question

### ISSUE THREAD

**Issue by greggmojica** [ParsePlatform/parse-server#1048]
Hi Guys -
I know this isn't an issue, but I have a question I was hoping the community could provide their feedback on.

I've developed an app using parse (already migrated to parse server).  I'm looking to add a feature such that one user can send a push notification to another user and that push notification has a button ('yes' button and 'no' button). If the yes button is hit, it sends related data back to the original sender. 

Would this be possible with parse server and if so, how might I do about doing it? Thanks for all your help regarding this matter and great job to the parse team for open sourcing everything!

**Comment by flovilmart** [comment]
Thanks for the good words.

Unfortunately we can't really answer here, as this is an implementation detail specific to your needs. 
I believe you'll find better help on Stackoverflow than an issue for parse-server.

Good luck!
