### ISSUE TITLE
Push is not working

### ISSUE THREAD

**Issue by ggamzzak** [ParsePlatform/parse-server#1049]
My parse-server configuration.json:

```
{
  "databaseURI": "mongodb://----------------------------------------",
  "appId": "h-------------------------------------------------------2",
  "masterKey": "H--------------------------------------------------------",
  "push": {
    "android": {
      "senderId": "6--------------1",
      "apiKey": "A-----------------------------------------------w"
    }
  }
}
```

and, push test :

```
$ curl -X POST ................................. http://localhost:1337/parse/push
{"result":true}
```

parse-server log like this:

```
GCM request and response {"request":{"params" ............................
"results":[{"error":"MismatchSenderId"}]))
```

But My senderID / apiKey equal setting on parse.com.
And if curl target change to 'http://api.parse.com/1/push', push is working.
What is problem?

**Comment by 432player** [comment]
I think you need to register to GCM and got a Registration Id back.
We are using oneSignal and their PushAdapter instead of registering to GCM by ourselves..
They manage the registration and take care of the Registration Id/Token you get back when registering.
Their API is extremely limited (to our own needs) but is completely free!

**Comment by ggamzzak** [comment]
I'd skip 'Configure Client Apps' in push wiki chapter 3.
Now push is working nicely, Thanks~

**Comment by zhouhao27** [comment]
@ggamzzak How do you get parse-server log for GCM? Thanks

**Comment by ggamzzak** [comment]
@zhouhao27 Parse server start

# node /usr/bin/parse-server /usr/lib/node_modules/config-server.json --port 1337
Configuation loaded from /usr/lib/node_modules/config-server.json
databaseURI: mongodb://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
appId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
masterKey: ***REDACTED***
push: [object Object]
port: 1337
mountPath: /parse
maxUploadSize: 20mb
serverURL: http://localhost:1337/parse

========== here is logs ===========

**Comment by zhouhao27** [comment]
Thanks. I made it work.

**Comment by flovilmart** [comment]
There is no more logs for the push, but a collection named _PushStatus with the number of successes and failures per device type and also the totals
