### ISSUE TITLE
Updating cloud-code from 1.5 to 1.7

### ISSUE THREAD

**Issue by artonragsdale** [ParsePlatform/parse-server#1051]
Are there any guides or resources available for updating cloud-code from older versions of the javascript sdk to the required for parse-server version of 1.7.0?  I have a project with a fair amount of cloud code that was written for 1.5.0. Now when I try to deploy it using the latest version 1.7.1 I only receive a 'script error' message.

**Comment by drew-gross** [comment]
Check the release notes for the JavaScript SDK, they should describe any breaking changes.

**Comment by mahabubakram** [comment]
can you please show the error logs over here. As we have quite a bunch of function in cloud.

**Comment by artonragsdale** [comment]
I don't get any useful errors. This is what the cli returns when I try to deploy:

`Uploading source files
Finished uploading files
Deploy failed with error:
script error
Will retry in 0 seconds.

Uploading source files
Finished uploading files
Sorry, deploy failed again with same error.
Will retry in 1 seconds.

Uploading source files
Finished uploading files
script error
`

I did look at the release notes, but they are fairly vague and only go back to 1.6.4 so I'm not sure if there are any breaking changes before that. It would be great to have a document listing breaking changes from each version with examples of how code will need to be modified. I'll try to increase the version number in smaller increments to see if I can get any hints that way.

**Comment by artonragsdale** [comment]
Looks like it's really just the update to 1.7.0 that causes the issue.  Everything worked up to 1.6.14.

I'm guessing it has to do with the changes to Parse.Promise since that seems to be the most significant change. Where would be a good place to see examples of how promises should be formatted in 1.7?

**Comment by artonragsdale** [comment]
Well, I guess the real problem is that the CLI and I suppose hosted cloud code don't support 1.7.0.  When I run 'parse jssdk --all' it only lists up to 1.6.14.  I was trying to use the cli deploy to verify my cloud code before transitioning to parse-server but I guess that's not possible.

**Comment by drew-gross** [comment]
Thats is correct. Sorry I didn't realize earlier that you were trying to deploy to parse.com.
