### ISSUE TITLE
Parse Server sign up validations (Missing email, missing password, invalid email address, etc..)

### ISSUE THREAD

**Issue by realtimez** [ParsePlatform/parse-server#1055]
Is the parse server missing the sign up server validations such as invalid email, missing password, missing email, etc?

Thanks!

**Comment by flovilmart** [comment]
It all should be here

**Comment by 432player** [comment]
Make sure you have the latest parse-server as a depandancy..

**Comment by realtimez** [comment]
Hmmm, I have deployed it on AWS using the deployment button from:

https://github.com/ParsePlatform/parse-server-example

Do I need to deploy it differently to have the latest version?

btw: any way to check on aws the parse server version?

Thanks!

**Comment by 432player** [comment]
We deployed on heroku so we're not really sure how to check this on AWS.
If you have a deploy log then it should appear there somewhere.
If you deployed your first version the past few three days you should be with 2.1.6

**Comment by realtimez** [comment]
Yea I did it yesterday or couple of days ago, but from the 'deploy to aws' button, was pretty straight forward.

Under running-versions i see eb-parse-server-sample.parse-server-example.zip . 

Does it pick up the latest parse-server version from docker or something?

**Comment by realtimez** [comment]
Can confirm now:

1: Can create a user with no password.
2: No email format validation.

on 2.1.6.

**Comment by gfosco** [comment]
What are you using to create these users?

**Comment by gfosco** [comment]
These scenarios are all fully tested in `specs/ParseUser.spec.js`, so, something else is wrong.  Cannot reproduce.

**Comment by realtimez** [comment]
I'm using: PFUser signUpInBackgroundWithBlock
