### ISSUE TITLE
Support basic auth for REST API calls

### ISSUE THREAD

**Issue by papjohn24** [ParsePlatform/parse-server#1059]
Based on parse REST Api documentation you can make requests using basic HTTP authentication. For example:
https://myAppID:javascript-key=myJavaScriptKey@api.parse.com/1/classes/GameScore/Ed1nuqPvcm

This feature seems not to be working on parse-server

**Comment by flovilmart** [comment]
it's not implemented yet AFAIK. not sure if we can provide a timeline. PR are welcome.

**Comment by bigdoghung** [comment]
Any idea when the basic HTTP authentication might be added?

**Comment by drew-gross** [comment]
Thanks to @hmoqhim for adding this. It will be in the next version.

**Comment by bmhdev** [comment]
Is this working yet?  I get error:unauthorized

**Comment by flovilmart** [comment]
THis has landed 10 months ago: https://github.com/ParsePlatform/parse-server/pull/2574
