### ISSUE TITLE
Cannot access API

### ISSUE THREAD

**Issue by nitrag** [ParsePlatform/parse-server#1060]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

AWS Elastic Beanstalk v2.1.6 
Localhost v2.1.6
JS SDK 1.7.1
REST/cURL

#### Steps to reproduce

Any queries

#### Logs/Trace

[Screenshot](http://i.imgur.com/NbzbXBP.jpg)

Okay! Another "Cannot GET" error.

I have been using parse-server for over a month now so this isn't a newbie issue. I get the error on any and all API requests. "Cannot GET /1/classes/****" 403 Error. This all started (I noticed several hours later) after I got a message from Compose.io saying one of my Mongo servers restarted.

1. I've been testing parse-server locally and on AWS elastic beanstalk for weeksnow. Never seen this issue. I've reverted code back to a known working version.
2. I've deleted node_modules folder in parse-server-example and "npm install"
3. Parse Hosted API works. I've verified the connection strings match. I've verified username/password on the database. I've reverted database back 4+ days. New user/password.
4. The nodejs log is completely blank. VERBOSE=1
5.  My mount is /1 but when I goto http://localhost:1337 I should see a welcome message. It says " {"error":"unauthorized"}" instead. I didn't use to get this. 
6. Tested cURL with master key (see [here](http://i.imgur.com/NbzbXBP.jpg)) and it still fails. I've verified cURL keys work.
7. I've reverted parse-server to 2.1.5, and 2.1.4. No difference.
8. I've reset cloud code to default to make sure there are no errors there.

How can I get the nodejs to be even more descriptive/trace?

**Comment by nitrag** [comment]
Update: It now successfully deploys to Beanstalk and will run fine there. It is still failing locally. How can I completely start over/fresh? Deleting ./node_modules and re-running "npm install" does not fix the issue.

**Comment by gfosco** [comment]
`Cannot GET` means you're not hitting the right routes.  Likely, the default `/parse` is being used, but you are requesting `/1`.  It can be changed with the PARSE_MOUNT environment variable, but `/parse` is much nicer.

**Comment by nitrag** [comment]
/facepalm
Wow, hours and hours of troubleshooting only to find out that env:PARSE_MOUNT got corrupted/typo.

Thanks!
