### ISSUE TITLE
cache.js makes request.user not updated like Parse API

### ISSUE THREAD

**Issue by tobernguyen** [ParsePlatform/parse-server#1062]
Reproduce step:

1. Login by Facebook (with totally new user, never logged in before)
2. I have afterSave hook on _User to create `statistic` for user
3. Then for the current session, all request to cloud function on parse server will have `request.user` contain only basic information of _User, which missing `statistic` field the afterSave hook created.

The only way to make `request.user` updated is to log out and log in again.
This doesn't happen on Parse.com API.

**Comment by flovilmart** [comment]
Looks like a user caching issue here :)

**Comment by gfosco** [comment]
Definitely looks like we could update user cache when changes are made..  but two questions, why is this not being added in a beforeSave? and which method are you using to stop the afterSave from looping?

**Comment by gfosco** [comment]
Wrote a test case and fix for this. #1072

**Comment by tobernguyen** [comment]
@gfosco thanks for the fix. I couldn't use `beforeSave` because I need objectId of current user as created `statistic` object will need it to point back to current user. To stop afterSave from loop I will check by `if (! request.user.get('statistic'))` before do anything. 

This is so bad that we didn't have `afterCreate`. Do you have any plan to add it? It would be useful for so many case.

**Comment by gfosco** [comment]
Not sure anyone plans to implement afterCreate, but you can also check obj.existed() to only run code the first time.. I think that works in an afterSave too.
