### ISSUE TITLE
Unable to create account on Parse

### ISSUE THREAD

**Issue by Iqrafarrukh** [ParsePlatform/parse-server#1064]
I am trying to create an account on parse, but after I choose any of the available options I am redirected to the main page

**Comment by bohemima** [comment]
I'm guessing you mean at parse.com? As they are winding down the service it is not possible to create a new account anymore. You should use the standalone parse server and parse dashboard instead

**Comment by Iqrafarrukh** [comment]
can we convert our parse app to firebase easily?
