### ISSUE TITLE
How to manually edit user password from the MongoDB editor on MongoLab?

### ISSUE THREAD

**Issue by grassland-curing-cfa** [ParsePlatform/parse-server#1069]
I have successfully migrated my Parse hosted database to a MongoDB hosted on MongoLab. From the Parse hosted Dashboard I am still able to manually edit the data of the MongoDB hosted on MongoLab. I am able to manually edit the [password] field on the [_Use] class by typing a new password from the Dashboard. And this actually successfully updates the MongoDB on MongoLab. I can find the following attribute for a User row storing the [password] data as an example:
`"_hashed_password": "$2a$10$UnxBpaT0ih3aQ5c02KlHouN1MwWwks29U.I8Rl8kv2nyckiZ1e6iQ"`

The actual password was "123456". Obviously it has been encrypted by MongoDB internally and it means nothing (unreadable) to a human being. So I am wondering how we can continue manually editing users' passwords if required after Jan 2017 when all Parse hosted services are shut down including the Dashboard.

**Comment by gfosco** [comment]
We launched the dashboard too :) https://github.com/ParsePlatform/parse-dashboard

Follow the instructions and run it locally, this would be the easiest/best way to accomplish your request.

Alternatively, you can use the same crypto module we do and get the proper encrypted version to store in the database.  See `src/password.js`.
