### ISSUE TITLE
com.parse.ParseRequest$ParseRequestException: i/o failure

### ISSUE THREAD

**Issue by harshadaasai** [ParsePlatform/parse-server#1071]
This error occurs when i shifted Parse SDK from 1.10.0 to Parse SDK 1.13.0 :  

ParseUser.logInInBackground(username, password, new LogInCallback() {
                  @Override
                  public void done(ParseUser user, ParseException e) {
                      if (isActivityDestroyed()) {
                          return;
                      }
                   
                      if (user != null) {
                          
                          loginSuccess();

                      } else {
                          
                          if (e != null) {
                             
                              if (e.getCode() == ParseException.OBJECT_NOT_FOUND) {  
                              } else {
                                 //its going here 
                              }

                          }
                      }
                  }
              });

**Comment by harshadaasai** [comment]
ParseUser.logInInBackground(username, password, new LogInCallback() {
                  @Override
                  public void done(ParseUser user, ParseException e) {
                      if (isActivityDestroyed()) {
                          return;
                      }
                      Log.e("user "," "+user);

                      if (user != null) {
                          loadingFinish();
                          loginSuccess();

                      } else {
                          loadingFinish();
                          Log.e("e---- ",""+e);
                          if (e != null) {
                              debugLog(getString(R.string.com_parse_ui_login_warning_parse_login_failed) +
                                      e.toString());
                              if (e.getCode() == ParseException.OBJECT_NOT_FOUND) {
                                  if (config.getParseLoginInvalidCredentialsToastText() != null) {
                                      showToast(config.getParseLoginInvalidCredentialsToastText());
                                  } else {
                                      showToast(R.string.com_parse_ui_parse_login_invalid_credentials_toast);
                                  }
                                  passwordField.selectAll();
                                  passwordField.requestFocus();
                              } else {
                                  showToast(R.string.com_parse_ui_parse_login_failed_unknown_toast);
                              }

                          }
                      }
                  }
              });
          }

**Comment by hramos** [comment]
This appears to be a client SDK issue unrelated to Parse Server. Please look for the relevant repository on GitHub for this SDK and consider opening an issue there.

A list of Parse's open source repositories is available at [parseplatform.github.io](http://parseplatform.github.io)
