### ISSUE TITLE
Question about OneSignalPushAdapter

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/parse-server#1073]
I migrate my push notification to parse server. But I found a problem for android:

1. The new sdk (1.13.0) doesn't work for my existing code. I can't get the push notification any more.
2. New push will only support GCM for android which is not what I want because some of my clients are in China which I believe that the Google service is blocked.

That's why I'm seek of new solution. And I found OneSignalPushAdapter example in the document. My question is if I still can use the same Android/iOS Client SDK? Thanks.

**Comment by gfosco** [comment]
iOS should be fine, the adapter is for the actual delivery of notifications, should be transparent to the client registering for push.  Non-GCM Android will not work, though, unless PPNS gets implemented.  

PPNS spec: https://github.com/ParsePlatform/parse-server/wiki/PPNS-Protocol-Specification

**Comment by zhouhao27** [comment]
Thanks for your information. I'm able to get my ios application work in both parse.com or parse server. Is there any plan to implment PPNS for Android?
