### ISSUE TITLE
Email verification after Parse retired

### ISSUE THREAD

**Issue by Lexons** [ParsePlatform/parse-server#1079]
Create new account form or reset password form for example - that use parse to send mail to user after submit - from where those emails will send after Parse retired for old android and ios apps?

**Comment by felipemobile** [comment]
It's already implemented in the latest parse-server as experimental. You can use mailgun or sendgrid adapters.

https://github.com/ParsePlatform/parse-server/issues/1063#issuecomment-198128894

**Comment by Lexons** [comment]
For older applications from api.parse.com email verification will not work?

**Comment by felipemobile** [comment]
@Lexons I believe it will not work after January, 2017.
