### ISSUE TITLE
PFQuery whereKey:nearGeoPoint returning incorrect results

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/parse-server#1080]
For implementation related questions or technical support, please refer to the [stackoverflow](http://stackoverflow.com/questions/tagged/parse.com) community.

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [x ] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x ] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Parse Server 2.1.6 on Heroku
iOS Swift

#### Steps to reproduce
Hello, below is my query to find tag objects where a specific key exists "T\(tagObjectIDs[0])". I am limiting the search to within 2 kilometers. When I include the geopoint constraint, parse returns all results, not just the one where that key exists. But if I remove the geopoint constraint, I only get results where the key exists. I'm a little perplexed, it seems like the geopoint query constraint is my issue, just not sure if it's something on my end. Thank you very much!

EDIT: I did check to make sure the user location is there, as well as the proper key where I'm plugging it into whereKeyExists.

```
 let userGeo:PFGeoPoint = PFGeoPoint(location: userCurrentLocation)

            let singleQuery = PFQuery(className: "tags")
            singleQuery.whereKeyExists("T\(tagObjectIDs[0])")
            singleQuery.whereKey("geoPoint", nearGeoPoint: userGeo, withinKilometers: 2)

            singleQuery.findObjectsInBackgroundWithBlock({ (objects, error) -> Void in

             ...
            })
```

**Comment by drew-gross** [comment]
Hey, sorry about the late response, this issue must have slipped through the cracks. I've been trying to reproduce this bug and haven't been able to yet. Would you be able to come up with a complete test case that includes creating the objects and querying them?

**Comment by gateway** [comment]
@drew-gross not sure if you can see this link, we where asked to post it to FB Bug team, they claim its an issue with Mongo..

> The problem occurs when $exists is used along with a geo query. This is an issue with mongo and unfortunately we are not going to be able to provide a fix at this time.
> 
> The issue with mongo is being tracked here:
>  https://jira.mongodb.org/browse/SERVER-21011
> 
> If you are not using null values, you can possibly work around this by using "is not null" instead of "exists: true", which does not trigger the bug.
> 
> I would highly suggest you utilize this workaround as this will not be fixed on our side. We are sorry for the inconvenience this has caused but wish you the best.
> 
> Thanks,
> Mark

https://developers.facebook.com/bugs/1101702089874034

The word is out if thats true or not.. but we changed a bit of the query to do this instead

query.whereKey("photoComments", equalTo: NSNull())

not sure if its a hacky way but its working.

**Comment by drew-gross** [comment]
Cool, thanks for the link and workaround info.
