### ISSUE TITLE
Get "_Users" attributes via the "User" endpoint does not return "sessionToken"

### ISSUE THREAD

**Issue by grassland-curing-cfa** [ParsePlatform/parse-server#1085]
I have successfully migrated my Parse app to from Parse hosted platform to the "Heroku + MongoLab" stack.

When I tried the following Java code to connect my Heroku app to query a User's attribute/profile from the database through HttpURLConnection and Parse REST APIs.

```
        String strUrl = 'https://{MY_APP}.herokuapp.com/parse' + "/" + userObjectId;
        URL url = new URL(strUrl);
		HttpURLConnection connection = (HttpURLConnection) url.openConnection();

		connection.setRequestMethod("GET");
		connection.setRequestProperty("X-Parse-Application-Id", APP_ID);
		connection.setRequestProperty("X-Parse-Master-Key", MASTER_KEY);
		connection.setRequestProperty("Content-Type", "application/json");

		User user = new User();
		user.objectId = userObjectId;

		BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
		StringBuilder builder = new StringBuilder();
		String line = null;
		while ((line = reader.readLine()) != null) {
			builder.append(line).append("\n");
		}
		reader.close();

        if (connection.getResponseCode() == HttpURLConnection.HTTP_OK) {
                System.out.println(builder.toString());
        ... ...
        }
```

It returned every attribute in JSON about the user I queried except for "sessionToken".

However, when I tried call the "login" endpoint, it did return the "sessionToken".

Is it a bug or anything I made wrong?

**Comment by gfosco** [comment]
This is just how it works.  The user doesn't have the session token, it is from the _Session class, and one user can have many.  On login/signup, it is injected in the response.
