### ISSUE TITLE
Replacing Parse.User.become when using parse-facebook-user-session

### ISSUE THREAD

**Issue by mchun** [ParsePlatform/parse-server#1088]
Dunno if it should be a parse-server related issue or should be on https://github.com/ParsePlatform/parse-facebook-user-session

Anyway, self-hosted parse-server does not allow Parse.User.current() or Parse.User.become() on server side. So I tried to replace the following

```
  }).then(function(response) {
      maybeLog("Becoming Parse user...");
      return Parse.User.become(response.getSessionToken());

    }).then(function(user) {
      maybeLog("Saving Facebook data for user...");
      user.set("name", facebookData.name);
      return user.save();

    })
```
with
```
  }).then(function(response) {
      maybeLog("Becoming Parse user...");
      return Parse.Cloud.httpRequest({
        url: 'http://localhost:1337/parse/users/me',
        headers: {
          'X-Parse-Application-Id': 'myAppId',
          'X-Parse-REST-API-Key': 'myRestAPIKey',
          'X-Parse-Session-Token': response.getSessionToken()
        }
      });
    }).then(function(userData) {
      maybeLog("Saving Facebook data for user...");
      var user = Parse.Object.fromJSON(userData.data)
      user.set("name", facebookData.name);
      return user.save();

    })
```
But user cannot be saved with either one of the following error depending on whether I am doing a new sign up / login.
{"code":203,"message":"Account already exists for this email address"}
{"code":206,"message":"cannot modify user xIWzk3gZg0"}

Is there any work around here?

**Comment by gfosco** [comment]
If you want to save the change "as" that user, try passing the sessionToken to the save call: `user.save(null, { sessionToken: response.getSessionToken() });`  Or if you've validated this should happen, you could pass `useMasterKey: true` to override security.  I don't think you need to call `/me` or use Parse.Object.fromJSON for this.

**Comment by mchun** [comment]
Ooops, yes! You are right and I am feeling stupid now.
I thought Parse.User.become does all the login job. But there is a Parse.FacebookUtils.logIn({}) for that, and the returned 'response' is already a ParseUser. Thanks for your help, @gfosco !

And perhaps for some other beginners like me, the following is my modified working code:

```
    ...
    return Parse.FacebookUtils.logIn({
        id: response.data.id,
        access_token: accessToken,
        expiration_date: expiration
      });
    }).then(function(user) {
      req.session.user = user; // my way of doing server-side login, see issue 497
      req.session.token = user.getSessionToken(); 
      user.set("name", facebookData.name);
      user.set("fbid", facebookData.id);
      if (facebookData.email)
        user.set("email", facebookData.email);
      return user.save(null,{ useMasterKey: true });
    }).then(function(user) {
      maybeLog("Fetching ParseFacebookTokenRequest for " +
               req.query.state + "...");
    ......
```
