### ISSUE TITLE
VERBOSE=0 still causes verbose logging

### ISSUE THREAD

**Issue by jgaull** [ParsePlatform/parse-server#1094]
#### Environment Setup
Heroku + mLab Mongo DB + Parse Server 2.1.6 + cloud code

#### Steps to reproduce
Set VERBOSE=0 in Heroku config

deleting the VERBOSE config var disables verbose logging.

#### Logs/Trace
lots of verbosity

**Comment by gfosco** [comment]
A PR to force it to require a *truthy* value would be accepted, but I'm okay with this behavior... if it's set at all, it logs verbose.

**Comment by jgaull** [comment]
Okey dokey. Thanks!

**Comment by alexblack** [comment]
This got me too...

**Comment by tgreco** [comment]
This is still an issue
