### ISSUE TITLE
Will the parse-server be supported / improved or is this an unsupported release?

### ISSUE THREAD

**Issue by MJomaa** [ParsePlatform/parse-server#11]

**Comment by davidnuon** [comment]
+1

**Comment by nlutsenko** [comment]
Hey guys, just wanted to clear this out.
It definitely is going to be supported and improved, so no worries on this end.

**Comment by jaysonng** [comment]
So aside from us having to host ParseServer, anything glaring / features we need to know about would be missing from ParseBackend? 

Basically I'm wondering what else would be different.

**Comment by nlutsenko** [comment]
At the current moment, there are 2 large pieces missing at this stage:
- Web Dashboard
- Analytics
- Push

There might be other small things, like in-app purchase verification that I am missing from the list above, but the biggest ones are there.

This said, web dashboard is being worked on and using analytics or push via different open source project is relatively easy and straightforward.

**Comment by Harsha93** [comment]
+1

**Comment by hslightnin** [comment]
> This said, web dashboard is being worked on

Worked on in what way?

**Comment by jaysonng** [comment]
@nlutsenko thanks! appreciate this.

**Comment by joekur** [comment]
@nlutsenko to clarify - is there no intent to ever include push notifications in this?

**Comment by kingmatusevich** [comment]
@joekur push delivery is being discussed, but from the looks of it, and several comments from the Parse developers, either they or the community (probably a combination of both) will take care of adding notifications here. https://github.com/ParsePlatform/parse-server/issues/5

**Comment by gfosco** [comment]
We're working on it.
