### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by jashsayani** [ParsePlatform/parse-server#110]
A Dockerfile would be useful. It would make it easy to build a docker image and create a container. This would make it simpler to deploy the project as it would eliminate the need to setup the VM, install Nodejs, and install other dependencies.

The README could contain basic docker commands to build the image and run it.

**Comment by gfosco** [comment]
Open to reviewing a PR for this if it will help others.  There are already several docker images for it, some linked in the wiki.

**Comment by jashsayani** [comment]
Sure, I can write a Dockerfile and create a PR.

**Comment by jashsayani** [comment]
I have a PR: https://github.com/ParsePlatform/parse-server/pull/114
