### ISSUE TITLE
Cloud functions repeats after waiting too long - loses references to previous request.

### ISSUE THREAD

**Issue by omairvaiyani** [ParsePlatform/parse-server#1100]
I'm running a particularly long function ~5-10 minutes of async processing, after a few minutes, the same cloud function seems to be called again (undesired). The client which calls the cloud function in the first place is none-the-wiser about this - however, after the first instance finishes its processing and calls ```response.success```, the client still says it's pending the network request.  Only the subsequent instance of ```response``` closes the network request for the client (so long as the second instance finishes before a third one is created). 

Is this wait-and-retry built into parse-server or the parse-sdk-js library? 

Note, I'm running the server behind forever.js - so if you guys are confident that this behaviour is not normal for this library, I will take a look at forever.js documents - though looking at the logs, it doesn't seem to be the culprit.

Thanks!

**Comment by flovilmart** [comment]
yes, the client may be retrying, you should not run long running function like that as the server may not timeout correctly. Those long processing methods should be enqueued or processed separately.
