### ISSUE TITLE
Saved data in array

### ISSUE THREAD

**Issue by cyboolo** [ParsePlatform/parse-server#1101]
Hi

I just want to save simple JSON on parse object of type array:

```
var myVal = {"projet":myProjet,"token":token};
myVal = JSON.stringify(myVal);
```

I see on parse dashboard my saved data:
`
[" {\"projet\":\"zt5iqPU8Ex\",\"token\":\"xxxx-11432797634-114260xxx3-17726860081-917b228dc2\"}"]`

Why do I have these " and these \ added on my field ?

**Comment by flovilmart** [comment]
because you stringified your val, so it escapes the content of your JSON object

**Comment by cyboolo** [comment]
Yes but if I don't do that and send myVal directly on my cloud function it does not work

Thank you anyway

```
Parse.Cloud.define("slack_token", function(request, response) {
 
Parse.Cloud.useMasterKey();   
     
var token = request.params.A;
var myId = request.params.B;
     
////
var query = new Parse.Query(Parse.User);
     
    query.get(myId, {
    success: function(user) {
     
    user.addUnique("slack_token",token);
  
    user.save(null, {
    success: function(user) {
        response.success(user);
    },
     error: function(user, error) {
        response.error(error.code);   
    }
    }); 
         
    },
    error: function(object, error) {
     
    response.error(error);    
         
    }
    });
////
//Fin    
});
```

**Comment by flovilmart** [comment]
Parse.Cloud.useMasterKey is not available in parse-server;

you should pass { useMasterKey: true }

**Comment by cyboolo** [comment]
I did that change, thank you for that

Then I did not JSON.stringify myVal

myVal that is sended is then : [object Object]

and I get this answer parse_SDK.js:15 POST https://labcyboolo.herokuapp.com/parse/functions/slack_token 400 (Bad Request)

**Comment by flovilmart** [comment]
How do you call you cloud function?

**Comment by cyboolo** [comment]
Parse.Cloud.run('slack_token',{A:myVal,B:user.id},{
              
                  		success: function(result){...

**Comment by flovilmart** [comment]
So in the cloud functions, the param A is [object Object] ? or is it what is stored into the database?

**Comment by cyboolo** [comment]
Yes it is my console.log for var myVal = {"projet":myProjet,"token":token}; if I don't JSON.stringify myVal

if i JSON.stringify(myVal) it is saved and I have my array on parse dashboard:
 [" {\"projet\":\"zt5iqPU8Ex\",\"token\":\"xxxx-11432797634-114260xxx3-17726860081-917b228dc2\"}"]

if i don't JSON.stringify, my params A is [object Object] and I have the bad request response

**Comment by cyboolo** [comment]
And this code was working well when I was on parse.com

**Comment by flovilmart** [comment]
So do JSON.parse in your cloud code function if you send it as JSON.stringify

**Comment by cyboolo** [comment]
I think it comes from addUnique which accepts only string attribute...

**Comment by cyboolo** [comment]
Maybe it comes from addUnique I am using in my cloud function?
