### ISSUE TITLE
GCM Push is not working and no logs.

### ISSUE THREAD

**Issue by kimhongyeon** [ParsePlatform/parse-server#1104]
APNS push is working.
GCM push is not working and no logs.

In same environment, https://api.parse.com/1/push is very well.

What the ploblem.

#### Environment Setup
var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var app = express();

// Specify the connection string for your mongodb database
// and the location to your Parse cloud code
var api = new ParseServer({
  databaseURI: 'my',
  cloud: 'my', // Provide an absolute path
  appId: 'my',
  masterKey: 'my',
  clientKey: 'my',
  restAPIKey: 'my',
  javascriptKey: 'my',
  dotNetKey: 'my',
  fileKey:'my',
  push: {
    android: {
      senderId: '1235215235', // The Sender ID of GCM
      apiKey: 'myKey' // The Server API Key of GCM
    },
    ios: {
      pfx: '/push/apppro.p12', // Prod PFX or P12
      bundleId: 'com.my.myapp',
      production: true // Prod
    }
  },
  serverURL: 'http://localhost:1337/parse' // Don't forget to change to https if needed
});

// Serve the Parse API on the /parse URL prefix
app.use('/parse', api);

app.listen(1337, function() {
  console.log('parse start');
});

#### Steps to reproduce
curl -X POST \
    -H "X-Parse-Application-Id: appKey" \
    -H "X-Parse-Master-Key: masterKey" \
    -H "Content-Type: application/json" \
    -d '{
          "where": {
            "channels": {
              "$in": [
                "cha1",
                "cha2"
              ]
            }
          },
          "data": {
            "title": "The Shining",
            "alert": "message"
          }
        }'\   http://localhost/parse/push

#### Logs/Trace
APNS Connection 0 Notification transmitted to abcdefg
APNS Connection 0 Notification transmitted to abcdefg
APNS Connection 0 Notification transmitted to abcdefg
APNS Connection 0 Notification transmitted to abcdefg
APNS Connection 0 Notification transmitted to abcdefg
APNS Connection 0 Notification transmitted to abcdefg
APNS Connection 0 Disconnected
APNS Connection 0 Connected
APNS Connection 0 Notification transmitted to abcdefg
APNS Connection 0 Notification transmitted to abcdefg
APNS Connection 0 Notification transmitted to abcdefg
APNS Connection 0 Notification transmitted to abcdefg
APNS Connection 0 Disconnected
APNS Connection 0 Connected
APNS Connection 0 Notification transmitted to abcdefg
APNS Connection 0 Notification transmitted to abcdefg
APNS Connection 0 Notification transmitted to abcdefg

**Comment by abdox2** [comment]
I have the same issue. it was working fine but after updating to parse server 2.2.0 GCM stop working.

im using parse android 1.13.0

**Comment by tobernguyen** [comment]
Same issue with 2.2.0. Was working fine with 2.1.6

**Comment by abdox2** [comment]
No one look a this yet :( . i'm using 2.1.6 because this issue

**Comment by wangmengyan95** [comment]
I can take a look.

**Comment by wangmengyan95** [comment]
Found the case of the bug, in #1004, we delete the `pushId` from GCM payload, this field is not used for formal GCM payload, however, we use this info to deduplicate push notifications in Parse Android SDK. Without this field, the SDK can not work. I will add it back. cc @flovilmart @gfosco.

**Comment by vsching** [comment]
Hi, this is the open source version, but does this issue applies to parse.com server as well?
Recently my android push using parse.com just doesn't work anymore. Anybody experience the same thing?

**Comment by flovilmart** [comment]
Issues here don't apply to parse.com. Please don't report parse.com issues here but on https://parse.com/help

**Comment by vineetbindal** [comment]
I am facing this issue, I have tried and checked everything, My GCM keys, senderId, regenerating API keys, making sure that I am using server key on server, etc, still not working. How to fix it?
