### ISSUE TITLE
addUnique not working with object value

### ISSUE THREAD

**Issue by cyboolo** [ParsePlatform/parse-server#1105]
Hi

I can't make my cloud function working with addUnique:

myVal = {"a":"A","b":"B"};

myClass.addUnique("myArrayfield", myVal);

It gives me bad request response.

It only works if myVal is a string but I want to save a JSON object. Furthermore, if I try to stringify, it adds symbols in my expression.

**Comment by flovilmart** [comment]
was it working with parse.com?

**Comment by cyboolo** [comment]
Yes it was working before migration

**Comment by cyu** [comment]
I'm having this issue as well.  The error I'm getting is `{"code":107,"message":"bad atom: [object Object]"}`
