### ISSUE TITLE
Question on query !

### ISSUE THREAD

**Issue by flessard** [ParsePlatform/parse-server#1108]
There is a way to use query to find a object contain properties ? 
Is possible or need to be implemented ? 

Like this in mongo:
`db.getCollection('CollectionName').find({"status.delivered":1})`

**Comment by flovilmart** [comment]
Did do try [exits](http://www.parse.com/docs/js/api/classes/Parse.Query.html#methods_exists)

**Comment by gfosco** [comment]
I think this works:

```js
var query - new Parse.Query('ClassName');
query.equalTo('status.delivered', 1);
query.find().then((results) => {
  console.log(results);
}, (e) { console.log(e); });
```

**Comment by flessard** [comment]
Thanks @gfosco work fine :)
