### ISSUE TITLE
Any plans to Open-Source PPNS Server

### ISSUE THREAD

**Issue by mithleshjs** [ParsePlatform/parse-server#1113]
I don't know if it is the right place to ask this question, pardon me if I am wrong. The best thing about parse was that we could receive pus lh notifications on almost all phones and networks. But with PPNS gone, we are left with GCM which is too unreliable in some areas and other options are too expensive.

**Comment by davimacedo** [comment]
It is a good question. I think Parse could share with us your plans about what will still be open sourced (and when). It could help us to know in which we have to concentrate our efforts.

**Comment by flovilmart** [comment]
@mithleshjs GCM and APNS are implemented as of now, PR are welcome for windows devices. I don't believe there are any plans to open source solely PPNS. Plans are to upgrade APNS to the new HTTP/2 api as soon as nodejs handled it properly or to provide it through a separate adapter.

What do you see as unreliable with GCM? What areas you would wish to improve?

**Comment by gfosco** [comment]
We released the specification for the PPNS protocol here: https://github.com/ParsePlatform/parse-server/wiki/PPNS-Protocol-Specification

But it would likely require a community contribution, as it's not currently in development.

**Comment by flovilmart** [comment]
Like a port from go to node.js :)
