### ISSUE TITLE
problem ( BUG)

### ISSUE THREAD

**Issue by thamer898** [ParsePlatform/parse-server#1125]
Hello

When i try to update user data on table "user" and choose user.saveinbackground this error appaear
"com.parse.ParseRequest$ParseRequestException: cannot modify user " can you help me please to solve this issue ?

Regards

**Comment by mllobere** [comment]
You probably dont have the rights to modify a user. Try to modify the user you are logged in with, and see if that works. To modify another user, you probably want to use the MasterKey. The best approach to do that would be to create a cloud code function so you don't have to use the MasterKey on your client-side code.

**Comment by thamer898** [comment]
thank you @mllobere it work's .
