### ISSUE TITLE
Any document about how to use OAuth in client side?

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/parse-server#1129]
I read the document about OAuth in parse server. But could not find the corresponding document how to use OAuth in client side. Any idea? Thanks.

**Comment by oallouch** [comment]
I also ask for some doc without success.
This article looks outdated https://parse.com/tutorials/adding-third-party-authentication-to-your-web-app 
I use the js client SDK.
For all I can understand, you have to use a third party lib, like redux-auth (in my case) or hello.js and get a token, then you pass that token to parse-server (with the name of the provider), whose job is to return a Parse User.

**Comment by gfosco** [comment]
Looks like the client SDKs (at least javascript) support passing in your own authentication provider... Here's the simplest example from a test scenario: https://github.com/ParsePlatform/Parse-SDK-JS/blob/bb78dfb4248afcb457acbebb24f2dc583d7c14bd/src/__tests__/ParseUser-test.js#L576 The authenticate method would be your third party code to get the proper token, and it returns the authData object for that provider..

**Comment by oallouch** [comment]
Thx
With this and the source of ParseUser (https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/ParseUser.js) , we can manage something.

**Comment by zhouhao27** [comment]
@oallouch Any sample code? Thanks.

**Comment by oallouch** [comment]
Nope, not for now. I postponed this part to end of my project :)

**Comment by flovilmart** [comment]
Closing here as you opened on ParsePlatform/Parse-SDK-JS#246

**Comment by junal** [comment]
@flovilmart @oallouch Any one can provide client side i.e jQuery example for FB or Twitter? How can i get this Auth setup from server? An example will be greatly appreciated. 

Thanks

**Comment by flovilmart** [comment]
The Rest guide has full examples for cUrl that should be trivial to port to jQuery http://parseplatform.github.io/docs/rest/guide/
