### ISSUE TITLE
parse-server v2.2.0 is stable?

### ISSUE THREAD

**Issue by ggamzzak** [ParsePlatform/parse-server#1134]
My parse-server worked well at v2.1.6.
But I'm updated to v2.2.0 yesterday, and push is not working.
Parse-server start fine.

```
$ node /usr/bin/parse-server /usr/lib/node_modules/parse-server/configuration.json --port 1337
Configuation loaded from /usr/lib/node_modules/parse-server/configuration.json
serverURL: http://xxxxxxxxxxx:1337/parse
databaseURI: mongodb://xxxxxxxxxxxxxxxxxxxxxxxx/db
appId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
masterKey: ***REDACTED***
push: [object Object]
port: 1337
mountPath: /parse
maxUploadSize: 20mb

parse-server running on http://xxxxxxxxxx:1337/parse
```

But no print logs, both success and fail, why, why, why...T.T

**Comment by flovilmart** [comment]
What's the problem with the push? what provider are you using? APNS? GCM?

**Comment by ggamzzak** [comment]
No print logs...
In yesterday, All print log about APNS, GCM.

**Comment by ggamzzak** [comment]
I was setting each device and tested.
But no print log.

**Comment by flovilmart** [comment]
Logs have been removed from 2.2.0 as they were cluttering everything. Does the push gets sent? You should have a _PushStatus class added now

**Comment by ggamzzak** [comment]
Your answer is very helpful. thank you!
but push is not sent.
Im searching push status more at 1hour later

**Comment by flovilmart** [comment]
In the _PushStatus collection , your should have the number of success and failures, what does that collection look like?

**Comment by ggamzzak** [comment]
I checked _PushStatus collection. Send is success in log, and Installation collection is updated successfully.
But... I don't received push in my device. ㅜㅜ

a parts of logs...

`{ "_id" : ObjectId("xxxxxxxxxxxxxxxxxx"), "objectId" : "fsZ8vJGx0n", "pushTime" : "2016-03-22T15:20:53.667Z", "_created_at" : ISODate("2016-03-22T15:20:53.667Z"), "query" : "{\"userSno\":{\"$in\":[6554033]}}", "payload" : { "title" : "The Shining", "alert" : "All work and no play makes Jack a dull boy." }, "source" : "rest", "title" : null, "expiry" : null, "status" : "succeeded", "numSent" : 0, "pushHash" : "xxxxxxxxxxxxxxxxxx", "_wperm" : [ ], "_rperm" : [ ], "numFailed" : 0 }`

**Comment by ggamzzak** [comment]
Same query, host : api.parse.com/1/push
log...

`"payload" : "{\"alert\":\"All work and no play makes Jack a dull boy.\",\"title\":\"The Shining\"}", "status" : "succeeded", "numSent" : 28`

payload is different.
maybe it omits to wrap double quotation at payload values.
Well, I guess I just assumed...

**Comment by flovilmart** [comment]
the way it's store is not the problem, our spec seems to have mismatched as payload is a string on parse.com and not parse-server. I'll try to see what's going on, but that's for sure a problem in APNS.js.

**Comment by ggamzzak** [comment]
I don't know what I'll do...

**Comment by flovilmart** [comment]
@ggamzzak this is an open source project, you can help by finding where the bug and provide a pull request.

**Comment by ggamzzak** [comment]
@flovilmart Okay, I appreciate you help.
By the way, Is your push working well at latest version?

**Comment by flovilmart** [comment]
I'm not using parse-server in production yet. I'll try to have a deeper look at the bug some time
