### ISSUE TITLE
Parse.Cloud.afterSave for sending push notifications not working from Heroku server

### ISSUE THREAD

**Issue by bulkwebsolutions** [ParsePlatform/parse-server#1135]
I did the migration, from Parse to Heroku and everything went smooth. At this point I didn't have any cloud code or push notifications set up on Parse. When I was done with the migration I begin to implement cloud code to handle push notification every time I save a new text message, but the Parse.Cloud.afterSave method is not running. I know main.js is working because if I implement 

```js
Parse.Cloud.define('hello', function(req, res) {
  res.success('Hi');
});
```

I get "Hi" return to my console in Xcode, but for some reason Parse.Cloud.afterSave does nothing. I also know my Parse.Cloud.afterSave code is correct because it's that same code I use on another app through parse though. What am I missing?

Here in my index.js file:

```js
var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var path = require('path');

var databaseUri = process.env.DATABASE_URI || process.env.MONGOLAB_URI;

if (!databaseUri) {
  console.log('DATABASE_URI not specified, falling back to localhost.');
}

var api = new ParseServer({
  databaseURI: databaseUri || '',  
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || '', 
  masterKey: process.env.MASTER_KEY || '', 
  fileKey: 'XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX', // file key from parse
  serverURL: process.env.SERVER_URL || '',  

  push: {
    ios: {
      pfx: '/Users/alexcruz/Desktop/Certificates.p12', // The filename of private key and certificate in PFX or PKCS12 format from disk
      bundleId: 'com.daps.DapsPush', // The bundle identifier associate with your app
      production: false // Specifies which environment to connect to: Production (if true) or Sandbox
    }
  }
});

var app = express();

// Serve static assets from the /public folder
app.use('/public', express.static(path.join(__dirname, '/public')));

// Serve the Parse API on the /parse URL prefix
var mountPath = process.env.PARSE_MOUNT || '/parse';
app.use(mountPath, api);

// Parse Server plays nicely with the rest of your web routes
app.get('/', function(req, res) {
  res.status(200).send('Make sure to star the parse-server repo on GitHub!');
});

// There will be a test page available on the /test path of your server url
// Remove this before launching your app
app.get('/test', function(req, res) {
  res.sendFile(path.join(__dirname, '/public/test.html'));
});

var port = process.env.PORT || 1337;
var httpServer = require('http').createServer(app);
httpServer.listen(port, function() {
    console.log('parse-server-example running on port ' + port + '.');
});

// This will enable the Live Query real-time server
ParseServer.createLiveQueryServer(httpServer);
```

Here is my main.js file:

```
//Push Notification for messages that are received
Parse.Cloud.afterSave("MXTMessage", function(request) {
  var messageText = request.object.get('message');
  var usersReceived = request.object.get('receiver');
  var currentUser = Parse.User.current();
  var pushQuery = new Parse.Query(Parse.Installation);
      pushQuery.equalTo('user', usersReceived);
      pushQuery.notEqualTo('user', currentUser);
        Parse.Push.send({
            where: pushQuery, // Set our Installation query
            data: {
              alert: "New message: " + messageText
             }
            }, {
      success: function() {
      // Push was successful
          },
      error: function(error) {
        throw "Got an error " + error.code + " : " + error.message;
          }
            });
});
```

Thank you

**Comment by gfosco** [comment]
In node, there's no longer the concept of a 'current' user, since the server stays running while it processes many requests.  You'd need to update this code to get the user from `request.user` and send the push with the master key:

```
Parse.Cloud.afterSave("MXTMessage", function(request) {
  var messageText = request.object.get('message');
  var usersReceived = request.object.get('receiver');
  var pushQuery = new Parse.Query(Parse.Installation);
  pushQuery.equalTo('user', usersReceived);
  pushQuery.notEqualTo('user', request.user);
  Parse.Push.send({
    where: pushQuery, // Set our Installation query
    data: {
      alert: "New message: " + messageText
    }
  }, { useMasterKey: true}).then(() => {
      // Push was successful
      console.log('weeee!');
  }, (e) => {
      console.log(e);
  });
});
```

**Comment by bulkwebsolutions** [comment]
Hey buddy, thanks for the update. It's still not sending the pushes though. Any idea of what else can it be. I been wrestling with this for 3 days now.
@gfosco

**Comment by gfosco** [comment]
Need more info I guess... can you enable VERBOSE=1 environment variable, add some more logging, see if you can discover where this is going wrong...

**Comment by bulkwebsolutions** [comment]
How can I enable VERBOSE ? If I run the command Heroku log I'm getting
<img width="687" alt="screen shot 2016-03-22 at 6 57 21 pm" src="https://cloud.githubusercontent.com/assets/6269334/13970571/08aac338-f060-11e5-9e3a-315b49b96338.png">

**Comment by gfosco** [comment]
What does your index.js look like around line 31?... liveQuery should be inside the options block passed to ParseServer..

heroku env vars are set like: `heroku config:set VERBOSE=1`

**Comment by bulkwebsolutions** [comment]
Line 31 is: liveQuery: {

`var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',  //'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'vcvlqNruCCXx0ZMLej7NmAkyEuGUjkxljOvb6K4r', //vcvlqNruCCXx0ZMLej7NmAkyEuGUjkxljOvb6K4r
  masterKey: process.env.MASTER_KEY || 'iXOUjz99nb604t25CAQpjHtYZidmXAFPTB5LPbe1', //Add your master key here. Keep it secret! //iXOUjz99nb604t25CAQpjHtYZidmXAFPTB5LPbe1

  fileKey: '24fc72f0-55d0-4838-9a23-21663b4bd7b2', // file key from parse
  serverURL: process.env.SERVER_URL || 'http://daps.herokuapp.com/parse',  //http://daps.herokuapp.com/parse  // http://localhost:1337/parse Don't forget to change to https if needed

  push: {
    ios: {
      pfx: '/Users/alexcruz/Desktop/Certificates.p12', // The filename of private key and certificate in PFX or PKCS12 format from disk
      bundleId: 'com.daps.DapsPush', // The bundle identifier associate with your app
      production: false // Specifies which environment to connect to: Production (if true) or Sandbox
    }
  }

  liveQuery: {
    classNames: ["MXTMessage"] // List of classes to support for query subscriptions
  }

});`

**Comment by bulkwebsolutions** [comment]
Line 31 is: liveQuery: {

`var api = new ParseServer({
databaseURI: databaseUri || 'mongodb://localhost:27017/dev', //'mongodb://localhost:27017/dev',
cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
appId: process.env.APP_ID || 'xxxxxxxxxxxxxxxxx', 
masterKey: process.env.MASTER_KEY || 'xxxxxxxxxxxxxxxxx', 
fileKey: 'xxxxxxxxxxxxxxxxx', // file key from parse
serverURL: process.env.SERVER_URL || 'http://myapp.herokuapp.com/parse', 

push: {
ios: {
pfx: '/Users/alexcruz/Desktop/Certificates.p12', // The filename of private key and certificate in PFX or PKCS12 format from disk
bundleId: 'com.daps.DapsPush', // The bundle identifier associate with your app
production: false // Specifies which environment to connect to: Production (if true) or Sandbox
}
}

liveQuery: {
classNames: ["MXTMessage"] // List of classes to support for query subscriptions
}

});`

**Comment by bulkwebsolutions** [comment]
Line 31 is: liveQuery: {

`var api = new ParseServer({
databaseURI: databaseUri || 'mongodb://localhost:27017/dev', 
cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
appId: process.env.APP_ID || 'xxxxxxxxxxxxxxxxx',
masterKey: process.env.MASTER_KEY || 'xxxxxxxxxxxxxxxxx',
fileKey: 'xxxxxxxxxxxxxxxxx', // file key from parse
serverURL: process.env.SERVER_URL || 'http://myapp.herokuapp.com/parse',

push: {
ios: {
pfx: '/Users/alexcruz/Desktop/Certificates.p12', // The filename of private key and certificate in PFX or PKCS12 format from disk
bundleId: 'com.daps.DapsPush', // The bundle identifier associate with your app
production: false // Specifies which environment to connect to: Production (if true) or Sandbox
}
}

liveQuery: {
classNames: ["MXTMessage"] // List of classes to support for query subscriptions
}

});`

**Comment by gfosco** [comment]
You're missing the comma after the push config object... Easier to see when all properly indented, this is an object being passed to the ParseServer constructor.

```js
var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev', 
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'xxxxxxxxxxxxxxxxx',
  masterKey: process.env.MASTER_KEY || 'xxxxxxxxxxxxxxxxx',
  fileKey: 'xxxxxxxxxxxxxxxxx', // file key from parse
  serverURL: process.env.SERVER_URL || 'http://myapp.herokuapp.com/parse',
  push: {
    ios: {
      pfx: '/Users/alexcruz/Desktop/Certificates.p12',
      bundleId: 'com.daps.DapsPush',
      production: false
    }
  },
  liveQuery: {
    classNames: ["MXTMessage"] // List of classes to support for query subscriptions
  }
});
```

**Comment by bulkwebsolutions** [comment]
When I add breakpoints on devtools it stops at:

Parse.Cloud.afterSave("MXTMessage", function(request) {

I add additional breakpoints inside the afterSave method, and it just ignores them all.

**Comment by gfosco** [comment]
What else is in your cloud code file?... don't require or define Parse... it's a global.

**Comment by bulkwebsolutions** [comment]
```
This is all the code in the main.js

Parse.Cloud.afterSave("MXTMessage", function(request) {
  var messageText = request.object.get('message');
  var usersReceived = request.object.get('receiver');
  var pushQuery = new Parse.Query(Parse.Installation);
  pushQuery.equalTo('user', usersReceived);
  pushQuery.notEqualTo('user', request.user);
  Parse.Push.send({
    where: pushQuery, // Set our Installation query
    data: {
      alert: "New message: " + messageText
    }
  }, { useMasterKey: true}).then(() => {
      // Push was successful
      console.log('weeee!');
  }, (e) => {
      console.log(e);
  });
});
```

**Comment by gfosco** [comment]
any logs?...

**Comment by bulkwebsolutions** [comment]
Nope

**Comment by gfosco** [comment]
add a console log before each line in your afterSave.  where does it stop?

**Comment by bulkwebsolutions** [comment]
No where it doesn't go beyond  Parse.Cloud.afterSave("MXTMessage", function(request) {

and when I go to: http://localhost:1337/parse 

I get

{"error":"unauthorized"}

**Comment by gfosco** [comment]
How are you saving an MXTMessage object, which would trigger the afterSave?  

Yeah it is unauthorized because you don't pass in the appId header, it's not for browsing.

**Comment by bulkwebsolutions** [comment]
Oh ok,

Through an iOS app. When a user sends a text message, and the message object is saved to MXTMessage that's when I want to trigger the afterSave to send the receiver a notification.

**Comment by bulkwebsolutions** [comment]
The afterSave never gets called

**Comment by gfosco** [comment]
Please test and run this locally, on your machine, using a curl command to save an object.  See if you can get any more useful information from logs while it's running... the heroku logs get all out of order sometimes..

**Comment by bulkwebsolutions** [comment]
Running it locally and nothing. When I save a new object afterSave never gets called.
This is what the console in devtool outputs only

<img width="621" alt="screen shot 2016-03-22 at 9 17 06 pm" src="https://cloud.githubusercontent.com/assets/6269334/13972904/804b8c48-f073-11e5-88a4-3b0b66c7741e.png">

**Comment by bulkwebsolutions** [comment]
Every cURL command just returns {"error":"unauthorized"}

**Comment by bulkwebsolutions** [comment]
Damn buddy what you think might be the issue? I been looking around forums and theirs a few having the same issue.

**Comment by gfosco** [comment]
If you're getting unauthorized, you're not passing in the right appId.. should look like this:

```bash
curl -X POST \
  -H "X-Parse-Application-Id: whatever" \
  -d "{\"foo\":\"bar\"}" \
http://localhost:1337/parse/classes/TestObject
```

**Comment by bulkwebsolutions** [comment]
```
curl -X POST \
  -H "X-Parse-Application-Id: myAppID" \
  -d "{\"message\":\"bar\"}" \
http://localhost:1337/parse/classes/MXTMessage
```

{"code":105,"error":"invalid key name: {\"message\":\"bar\"}"}Alex-iMac:daps alex$ 

What am I doing wrong here @gfosco  ?

**Comment by bulkwebsolutions** [comment]
Also I know main.js is running because if I use to test

```
Parse.Cloud.define("test", function(request, response) {
      response.success('Hi There');
});
```
and call it in Objective-C
```

        [PFCloud callFunctionInBackground:@"test"
                       withParameters:nil
                                block:^(NSString *string, NSError *error) {
                                    if (!error) {
                                        NSLog(@"connected %@", string);
                                    }
                                }];
```

Works as expected, but afterSave does nothing.

**Comment by MattiaConfalonieri** [comment]
Same problem here Parse.Cloud.afterSave not called, do you solve the problem?

**Comment by MattiaConfalonieri** [comment]
pushQuery.notEqualTo('user', request.user); seems work well with ios client, but not work with the android client and the notification not fire... any idea?

**Comment by MattiaConfalonieri** [comment]
After some work, here my solution:
Let me know if also work for you..
```
Parse.Cloud.afterSave("MXTMessage", function(request) {
  var messageText = request.object.get('message');
  var usersReceived = request.object.get('receiver');
  var pushQuery = new Parse.Query(Parse.Installation);
  pushQuery.equalTo('user', usersReceived);
  **pushQuery.notEqualTo('installationId', request. installationId);**
  Parse.Push.send({
    where: pushQuery, // Set our Installation query
    data: {
      alert: "New message: " + messageText
    }
  }, { useMasterKey: true}).then(() => {
      // Push was successful
      console.log('weeee!');
  }, (e) => {
      console.log(e);
  });
});
```

**Comment by kanersan** [comment]
what is the value stored in usersReceived? Is it a userId string or something else?
