### ISSUE TITLE
Push notification throughput  concerns: Job queue implementation for push notifications

### ISSUE THREAD

**Issue by anilkbhatt** [ParsePlatform/parse-server#1140]
As part of evaluating replacement for the parse.com service,  I have been able to install parse server on my development box and successfully deliver push notifications to Android device. I'll soon try it for iOS devices.
We are currently evaluating using either a self hosted parse server or another third party push notification  for our push notifications.
We are very much inclined to use the parse server, but we have big concern about the scalability of push notifications. The wiki says it can't handle super high throughput. Do we have some numbers on how much  throughput the current implementation can handle? Is implementation of a job queue for push notifications on the roadmap?

**Comment by gateway** [comment]
I wonder if using a system like https://www.iron.io/ would work, my buddy is the CTO of the company and they have quite a nice message/worker que system that would offload potential bottle necks of keeping all the pending ios queued messages off the parse server.

**Comment by wangmengyan95** [comment]
Hi @anilkbhatt, the throughput highly depends on the performance of your server. From our experience, querying the installation from mongo is the most time-consuming part of the whole process. Probably you can start the load testing by querying the installation from your mongo and see how much throughput it can handle. After that, you can do the complete load testing with GCM and APNS. We will do the queue system but right now we do not have a timeline for that.

**Comment by general-tim** [comment]
Hi @anilkbhatt - Would you mind sharing how you were able to get push notifications working for Android? I have been struggling with it for the last few days. I am able to get push notifications working for an app on parse.com, but when I change the credentials to point to my hosted parse-server (v. 2.2.2), the push notification is not going through. I am concerned that my parse-server config might be missing something.

```javascript
var api = new ParseServer({
  databaseURI: databaseURI,
  cloud: '/var/parseapp/cloud/main.js',
  appId: appId,
  masterKey: masterKey,
  fileKey: fileKey,
  serverURL: serverURL,
  push: {
    android: {
      senderId: senderId,
      apiKey: apiKey
    }
  }
})
```

**Comment by anilkbhatt** [comment]
@general-tim I downloaded [parse-server-example](https://github.com/ParsePlatform/parse-server-example) and tweaked the code in index.js. I also followed the guide to integrate the latest android/iOS SDKs with the apps. For android, if you were using the generic parse gcm sender id, you will need to obtain your own gcm sender id and add it to the parse server pus config as well as to your app.
`
...
var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  //todo: Relace with production app id. Put it ino a config file
  appId: process.env.APP_ID || 'devAppId', 
  //todo: Relace with production master key . Put it ino a config file
  masterKey: process.env.MASTER_KEY || 'devMasterKey', //Add your master key here. Keep it secret! 
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',  // Don't forget to change to https if needed
  push: {
      android: {
        senderId: 'gcmSenderIdFromGoogleDevConsole', 
        apiKey: 'gcmCredentialsFromGoogleDevConsole' //TODO: Read from config file. Keep it secret. 
	
      },
	  ios: {
        pfx: 'certificates\\dev.p12',
        bundleId: 'com.your.bundleld',
        production: false
      }
   }

var alternateMountPath = '/1';
app.use(alternateMountPath, api);
...


`

**Comment by anilkbhatt** [comment]
@wangmengyan95 , thanks for the advice on how to start with load/performance testing. Good to know that you guys will be eventually implementing a job queue.  @gateway, thanks for the reference to a current possible implementation of job queue. Our current primary goal is to have a solution based on open source parese server , which is as much self reliant as possible.

**Comment by anilkbhatt** [comment]
@wangmengyan95 , I have a question about Parse Server's architecture as I haven't yet gotten a chance to peek through the implementation. Does parse server takes care of spawning new processes to take advantage of multi core processors  and/or to handle increased load throughput or do I beed to worry about implementing that myself or use a framework like PM2?

**Comment by hramos** [comment]
I am closing this out as we're trying to cut down on the number of non-issues. This will help us focus on the issues that are actively preventing people from migrating their production apps to Parse Server.

As an alternative, I suggest opening a new discussion at [Server Fault](http://serverfault.com/tags/parse), a Q&A site dedicated to "questions about managing information technology systems in a business environment".
