### ISSUE TITLE
April 28 - what does "de-prioritize traffic..." mean?

### ISSUE THREAD

**Issue by kiteflo** [ParsePlatform/parse-server#1145]
Dear Parse team,

what exactly does the following sentence mean?

**"If you haven't migrated your database by April 28, we will assume your app is low priority, and we will de-prioritize its traffic to focus on production apps."
**
Assuming we have an app with 400-600 API requests per day, using push notifications etc. - does it mean the application will simply stop working or requests might take longer? What exactly will be the impact?

We will entirely rebuild our app which is planned to Q3 so I'm wondering whether we can leave everything as is until we finished our rebuild or will app users be affected?

A quick realistic answer would help us a lot,
thanx from Switzerland,
Florian

**Comment by akki7017** [comment]
+1

**Comment by drew-gross** [comment]
If you have migrated your database to your own MongoDB, you will be fine, your apps will receive full priority. If you haven't migrated your database, you app will keep working, but requests might take longer or have a higher failure rate.
