### ISSUE TITLE
error: bad key in untransform: _auth_data_twitter Uncaught internal server error. bad key in untransform: _auth_data_twitter undefined

### ISSUE THREAD

**Issue by mkpazon** [ParsePlatform/parse-server#115]
* Works in Parse.com server but not in local parse-server.
* Using Android Parse SDK. 

**Client Request**
GET /parse/classes/Item { 'x-parse-app-display-version': '1.7.1',
  'x-parse-installation-id': '--------',
  'user-agent': 'Parse Android SDK 1.13.0 (com.bitbitbitbit.thefreebees.debug/19) API Level 23',
  connection: 'Keep-Alive',
  'accept-encoding': 'gzip',
  'x-parse-os-version': '6.0.1',
  'x-parse-app-build-version': '19',
  'content-type': 'application/json',
  'x-parse-client-key': '------',
  'x-parse-client-version': 'a1.13.0',
  host: '192.168.0.103:1337',
  'content-length': '298',
  'x-parse-session-token': '-----',
  'x-parse-application-id': '-----' } {
  "include": "photos,owner",
  "where": "{\"locationCoords\":{\"$nearSphere\":{\"__type\":\"GeoPoint\",\"latitude\":1.316943,\"longitude\":103.900841},\"$maxDistance\":0.0023544184586407157},\"title\":{\"$exists\":true},\"status\":\"AVAILABLE\",\"owner\":{\"$exists\":true}}",
  "count": "1"
}

**Parse-Server Response**
{"code":1,"message":"Internal server error."}

**Parse-Server logs:**
error: bad key in untransform: _auth_data_twitter
Uncaught internal server error. bad key in untransform: _auth_data_twitter undefined

**Comment by gfosco** [comment]
Yeah, we need to fix this.  We didn't implement Twitter login, but we shouldn't choke on the fields it used.

**Comment by flovilmart** [comment]
@mkpazon fixed with #247
