### ISSUE TITLE
ACL compatibility problem between parse.com and parse-server

### ISSUE THREAD

**Issue by carmenlau** [ParsePlatform/parse-server#1150]
During migration, it is difficult to avoid using parse.com server and self hosted parse-server at the same time. As per mentioned on issue https://github.com/ParsePlatform/parse-server/issues/167, `_acl` has migrated to new structure `_wperm` and `_rperm`. The data will be inconsistent if we run parse.com cloud code and parse-server at the same time. For example, if we update ACL in the new app, but ACL in the old app will remain unchanged. Or create a new object in new app, the ACL object will be empty in the existing parse.com cloud code.

**Comment by carmenlau** [comment]
After doing more test I found following behavior.

**parse.com**
Update: `_acl`, `_wperm` and `_rperm`
Read: `_acl`

**parse-server**
Update: `_wperm` and `_rperm`
Read: `_wperm` and `_rperm`

Not sure is it a good suggestion if we change parse-server to update acl both way (include `_acl`) to solve the compatibility problem? Or parse.com will change to read `_wperm` and `_rperm` in future?

@gfosco Regarding to your comment in #167, I think you can give some comments on this too. Any comments would be appreciated!

Thanks a lot!

**Comment by dvanwinkle** [comment]
I'm not sure if this should be added to this or made a separate issue, so, I apologize if this is the wrong place for this. It could be related, so, I'm defaulting to adding it to the Issue.

If you have Public Read/Write CLP's enabled and you use Pointer permissions, Parse.com server will still return the same as Public Read/Write, but, Parse Server will return only records that apply to the Pointer Permissions. This is most likely an edge case, but, I can see people wanting Public Read and only allow Write based off of an Pointer CLP. If this is unclear, I can try my best to help.

**Comment by flovilmart** [comment]
It seems to be a bug in the pointer permissions. I'll have a look later

**Comment by flovilmart** [comment]
Related to #1953

**Comment by flovilmart** [comment]
@carmenlau looking at the PR, I believe the original issue has been fixed. Feel free to reopen if it isn't the case
