### ISSUE TITLE
Throwing error in index.js line 335and multiple npm erros

### ISSUE THREAD

**Issue by vikas230428** [ParsePlatform/parse-server#1154]
Everytime I am trying to run command heroku open it shows "Application Error". and after I run heroku logs which shows multiple errors in Parse Server files here is the snapshot attached.

![screen shot 2016-03-23 at 7 27 36 pm](https://cloud.githubusercontent.com/assets/18031500/13987391/5862fca6-f12d-11e5-9084-bacb46c4d35f.png)

**Comment by flovilmart** [comment]
We're working on a fix, and will release today

**Comment by vikas230428** [comment]
Ok Thanks,
