### ISSUE TITLE
Unable to save objects with Master Key from PHP SDK

### ISSUE THREAD

**Issue by pbush25** [ParsePlatform/parse-server#1155]
This is a copy of a question on the PHP SDK, here: [#231](https://github.com/ParsePlatform/parse-php-sdk/issues/231)
#### Environment Setup
My environment is set up with my master key, running on Heroku with MongoDB. I am able to save objects fine from the iOS SDK, but when trying to save new objects in the PHP SDK, I get the error "unauthorized: master key required". 

PHP SDK is initialized:

> ParseClient::initialize('appId', 'restID', 'masterKey');

> ParseClient::setServerURL("myServerURL");

#### Steps to reproduce

> $parseTransaction = new ParseObject("Transaction");
> $parseTransaction->set("buyer", $buyer);
> .... //set some more things
> $parseTransaction->save(true);

**Comment by gfosco** [comment]
Can you run this locally, set the environment variable `VERBOSE=1` and capture the request/response made for this?

**Comment by pbush25** [comment]
I actually got this to work by using `ParseObject::create("Transaction")` and had no problems.
