### ISSUE TITLE
How to show errors for debugging?

### ISSUE THREAD

**Issue by khirr** [ParsePlatform/parse-server#1159]
#### Environment Setup
Ubuntu Server, VPS
CloudCode

#### Steps to reproduce
I create in CloudCode an afterSave script, but when I have an syntax error, it never shows, for example: 
console.lof("Error");
console.log("Error");

The first line is wrong write, with "lof" and the second one is never shown, it happens with any error.
How can I do to enable show all errors?

**Comment by kriztoph** [comment]
Try setting `VERBOSE` environment variable, `export VERBOSE=1`, and restart your app.

**Comment by khirr** [comment]
@kriztoph Yes, I've tried that but not log that kind of errors, just show requests, etc.

**Comment by StephaneP** [comment]
if your running this local and you really want to debug it try nodeinspector...or pure node debug, console.log (also, depending on the verboseness will not display) try console.error or console.warn (if warnings are on)

**Comment by flovilmart** [comment]
the syntax error would be caught in the PromiseRouter, and logged when running in VERBOSE since 2.2.4.

Otherwise we don't have a DEBUG flag, not more granular debug options. PR are welcome
