### ISSUE TITLE
Multiple apps on one server

### ISSUE THREAD

**Issue by samarthagarwal** [ParsePlatform/parse-server#116]
Hi. I am trying to have multiple apps on one single parse-server deployment. How is it possible?
Since each app will have different app ids, Is it still possible for apps to coincide?

**Comment by samarthagarwal** [comment]
Is connecting each app to a separate mongodb database, a good way to go?

**Comment by christianmarth** [comment]
I'm looking at doing the same thing, thinking will need to create a new database and instance of ParseServer for each app and map this to a different path, maybe something like this

```
var app1 = new ParseServer({
  databaseURI: 'mongodb://localhost:27017/app1',
  cloud: '/home/app1/cloud/main.js', // Provide an absolute path
  appId: 'myAppId',
  masterKey: 'mySecretMasterKey',
  fileKey: 'optionalFileKey'
});

// Serve the Parse API on the /parse URL prefix
app.use('/parse', app1);

var app2 = new ParseServer({
  databaseURI: 'mongodb://localhost:27017/app2',
  cloud: '/home/app2/cloud/main.js', // Provide an absolute path
  appId: 'myAppId',
  masterKey: 'mySecretMasterKey',
  fileKey: 'optionalFileKey'
});

// Serve the Parse API on the /parse URL prefix
app.use('/parse', app2);
```

**Comment by samarthagarwal** [comment]
So if the client SDK connects to the url `/parse`, which `parse-server` instance will actually work? I don't think we should mount both to the same endpoint.

**Comment by christianmarth** [comment]
Sorry, i meant also change the url so you have /app1 /app2

**Comment by samarthagarwal** [comment]
Do we have any open source dashboard like project that when used with parse-server can give us a Parse like dashboard? Is someone developing it? I am willing to write one myself.

**Comment by christianmarth** [comment]
Have a look at #3 

I'm interested in contributing to a dashboard as well, for most of my apps, I've just written a custom CRUD dashboard in Javascript

**Comment by gfosco** [comment]
Right now the main hurdle for multi-app support will be cloud code.  The middleware which creates Parse.Cloud.define/etc will need to be updated similarly to #139 to somehow support separate cloud code initialization.  Right now it's easy enough to run multiple from the database side... I'm going to close this for now but hope to see the server hosting multiple apps and cloud code in the not-too-distant future.

**Comment by jamiechapman** [comment]
@gfosco funnily enough I was playing around with the middleware which deals with the Cloud Code functions yesterday (fairly similar to #139).  

I managed to get the functions loaded up for different apps— but the brick wall in the end was the `handleCloudFunction` method inside `functions.js`.  It's providing difficult to get the current `appId` at this stage of the request; for some reason `req.body` at that stage appears to be empty (even though I don't think it should be as `bodyParser` should have parsed it as JSON like it would in `classes.js`) — thus exposing `_ApplicationId` and allowing me to select the right `Parse.Cloud` function.

The other issue is the `Parse` library itself appears to be a global variable, so `Parse.applicationId` only returns the last defined application — and I guess this probably has a knock-on effect within the Cloud Code itself (e.g. when issuing queries and such?).  So I guess that potentially would need some significant refactoring too?

**Comment by baluragala** [comment]
Does anyone has a workaround for multiple apps with different cloud codes? I have been trying to figure out a way to implement. any quick thoughts please?

**Comment by christianmarth** [comment]
Best solution currently is to just create two instances of parse server for now...

**Comment by kilabyte** [comment]
You can run the multi instance all in one index and use nodemon to manage the service when for when you makes changes or add another instance.

**Comment by bigdoghung** [comment]
Oddly, I have 100+ apps in my parse.com account. Does this mean these are all separate instances of Parse running?

**Comment by drew-gross** [comment]
No, parse.com was massively multi-tenant. And as a result, massively complicated. You'll still be able to run your 100 apps on one MongoDB, but you will need separate instances of Parse Server.

**Comment by bigdoghung** [comment]
If a separate instance, that means I need to mount each parse instance on its own unique port right? Does Parse offer any consulting services ? I've been struggling all week to get a second app created on my hosted parse server.

**Comment by drew-gross** [comment]
Yep, running each in it's own process and own it's own port should work. We don't have any consulting available, no.

**Comment by BrandenSandahl** [comment]
@drew-gross 
If I am running a parse app by defining a custom index.js style file with my settings and then npm forever-ing it to keep it going, could I potentially just define a whole bunch of different custom index files and run them all, or would there be a better way to do this? 

Hope that makes sense, 
Thanks.

**Comment by tinocosta84** [comment]
@BrandenSandahl I'm gonna try that, makes sense.

**Comment by aknoormohamed** [comment]
i will dynamically create parse server instance like back4app

**Comment by rmros** [comment]
use Cloud Code

**Comment by sowmiyas** [comment]
We are planning to have a single mongo db for all our apps by using the collectionPrefix field in parse server. How will this work once we export all data from parse to our own mongo? I am assuming that the export will create separate database for each app and collections will not have a prefix.

**Comment by georgesjam** [comment]
hello,
Can someone please clarify this for me. I am new to node and i am a bit lost.
Regarding running multiple apps...

I have on my ubuntu system. Parse-server installed in this directory **/the directory/myserver/**
The directory looks like this.
```
/the directory/myserver/node_modules
/the directory/myserver/package.json
/the directory/myserver/application0.js
/the directory/myserver/application1.js
/the directory/myserver/application2.js
```

and each application0.js, application1.js, application2.js 
is on different port. 1337, 1338, 1339
```
var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var app = express();

var api = new ParseServer({
  databaseURI: 'mongodb://localhost:27017/dev', // Connection string for your MongoDB database
  cloud: '/home/myApp/cloud/main.js', // Absolute path to your Cloud Code
  appId: 'myAppId',
  masterKey: 'myMasterKey', // Keep this key secret!
  fileKey: 'optionalFileKey',
  serverURL: 'http://localhost:1337/parse' // Don't forget to change to https if needed
});

// Serve the Parse API on the /parse URL prefix
app.use('/parse', api);

app.listen(1337, function() {
  console.log('parse-server-example running on port 1337.');
});
```

now if i run it this way, could this way be used 
to run multiple apps with cloud code ?
```
node application0.js
node application1.js
node application2.js
```

The only way (for now) to run true multiple apps without affecting cloud code and global variables 
is to run them like i did using different processes ?

**Comment by flovilmart** [comment]
That seeems correct!

**Comment by natario1** [comment]
Regarding last comments, has anyone managed to do this in a GAE environment?

I can run the second app in its own process and port (e.g. 8081), allow the port in `app.yaml` and in firewall rules, but I see no way to specify the port when requesting `myapp.appspot.com`. You end up at their load balancer, and it directs to instance:8080 by default. At least, that's what I think is happening 😠

**Comment by richjing** [comment]
I developed multiple apps parse server in the safe way(not that efficiency but should not having the concurrent issue in cloud code), and make it easy to setup, take a look on this [repo](https://github.com/richjing/multiple-apps-parse-server)

**Comment by kerbymart** [comment]
Hello, @flovilmart so it seems with @georgesjam solution it is possible to run multiple parse on one server?

**Comment by flovilmart** [comment]
Never said it was impossible, as long as you have each app isolated in it’s own process and a proxy to route to the right local port based on the application ID header. 

I see pm2 has been used to spawn/manage each server process, which is actually a good way of doing so. You could also use pure nginx reverse proxy, docker containers, swarm, containers etc... 

We won’t add multi app tenancy here as it doesn’t make sense, because of the plethora of options for doing so. 

Multi app tenancy could be added by isolating the cloud code process out of parses-server but the performance implications are too high to make it practicle.

**Comment by kerbymart** [comment]
@flovilmart anyway the lib/index.js (from https://github.com/parse-community/parse-server) looks totally different from the parse-server-example

**Comment by flovilmart** [comment]
What do you mean different? Parse-server-example is just an example usage of parse-server that I don’t recommend to use/fork. I personally use the CLI more and we should deprecate it in favor of the CLI.

**Comment by brianyyz** [comment]
@flovilmart can you give a couple of points on why you don't recommend using parse-server-example? I think many people use it as a springboard to get going with Parse and then never leave it.

**Comment by flovilmart** [comment]
yeah that's the main reason actually, it's kinda a mess and doesn't encourage a proper way of managing your code either.

The CLI is powerful enough to accomplish a standalone parse-server. I'm not sure what's the best way to manage it. We're investigating yeoman generators and there's also the bootstrap.sh script that literally sets up a parse server in less than 30 seconds. 

The CLI has the code to start the HTTP server, etc.. it may not fit every single use case, but it's easier to manage than the parse-server-example.

**Comment by misaghDroid** [comment]
I could not figure out how to run multiple app in one parse server instance. I have these code in my index.js but the problem last created app overwrite and every changes happens in the last db (db2).

`// Example express application adding the parse-server module to expose Parse
// compatible API routes.

var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var path = require('path');
var cors = require('cors');

//var databaseUri = 'mongodb://admin:papaadmin@localhost:27017/admin';;

//if (!databaseUri) {
  //console.log('DATABASE_URI not specified, falling back to localhost.');
//}

var apiApp1 = new ParseServer({
  databaseURI: 'mongodb://localhost:27017/db1',
  cloud: __dirname + '/cloud/app1/main.js',
  appId: 'rubika_yesno',
  masterKey: 'MasterYesNoPapataLab',
  restAPIKey: 'RestYesNoPapataLab',
serverURL: 'http://localhost:1337/parse/app1'
});
var apiApp2 = new ParseServer({
  databaseURI: 'mongodb://localhost:27017/db2',
  cloud: __dirname + '/cloud/app2/main.js',
  appId: 'rubika_millionaire',
  masterKey: 'MasterMillionairePapataLab',
  restAPIKey: 'RestMillionairePapataLab',
serverURL: 'http://localhost:1337/parse/app2'
});


// Client-keys like the javascript key or the .NET key are not necessary with parse-server
// If you wish you require them, you can set them as options in the initialization above:
// javascriptKey, restAPIKey, dotNetKey, clientKey

var app = express();
app.use(cors()); // Enable CORS

// Serve static assets from the /public folder
app.use('/public', express.static(path.join(__dirname, '/public')));

// Serve the Parse API on the /parse URL prefix
var mountPathApp1 = '/parse/app1';
var mountPathApp2 = '/parse/app2';
app.use(mountPathApp1, apiApp1);
app.use(mountPathApp2, apiApp2);

// Parse Server plays nicely with the rest of your web routes
app.get('/', function(req, res) {
  res.status(200).send('I dream of being a website.  Please star the parse-server repo on GitHub!');
});

// There will be a test page available on the /test path of your server url
// Remove this before launching your app
app.get('/test', function(req, res) {
  res.sendFile(path.join(__dirname, '/public/test.html'));
});

var port = process.env.PORT || 1337;
var httpServer = require('http').createServer(app);
httpServer.listen(port, function() {
    console.log('parse-server-example running on port ' + port + '.');
});

// This will enable the Live Query real-time server
ParseServer.createLiveQueryServer(httpServer);
`

**Comment by rameshkec85** [comment]
> take a look on this [repo](https://github.com/sailstech/multiple-apps-parse-server)
> 
> * run and manage multiple parse apps (instances) in a server and using a single port.
> * one code, one database, create a parse app in one second.
> * parse dashboard integrated, each app's manager can log into parse dashboard to manage their app.
> * one admin account in parse dashboard to manage all apps

Cloud functions are not working in this repo.
