### ISSUE TITLE
TypeError: ParseServer.createLiveQueryServer is not a function

### ISSUE THREAD

**Issue by vikas230428** [ParsePlatform/parse-server#1162]
I am getting multiple npm errors with this. Please review the snapshot
![screen shot 2016-03-23 at 11 17 49 pm](https://cloud.githubusercontent.com/assets/18031500/13995756/9113a1d6-f150-11e5-855b-3e23b0e2283d.png)

**Comment by drew-gross** [comment]
This issue is caused by a change in Babel. We'll be pushing version 2.2.2 today which will fix the problem. In the meantime, you can go back to version 2.2.0.

**Comment by RafaRuiz** [comment]
This is happening again to 2.2.25-beta1
