### ISSUE TITLE
Exposing authDataManager

### ISSUE THREAD

**Issue by steven-supersolid** [ParsePlatform/parse-server#1163]
I need to be able to check Facebook access tokens in my application code and currently have my own function to do this. However, the code is similar to that in authDataManager/facebook.js and does not have the mocking support offered by authDataManager. I'm considering copying some of this code across but thinking whether it makes sense to expose authDataManager in index.js instead.

My use case is: when a previously linked user logs in with a new account and supplies a valid access token then I want to retrieve the old account. Currently I validate the access token and then query on Facebook ID which I store as a property on _User

**Comment by flovilmart** [comment]
if you override { oauth : { facebook: { validateAuthData: function(authData, options) {} }}} that should work
in you index.js

**Comment by steven-supersolid** [comment]
That's what I'm doing in tests (same as in helper.js), however I'm not asking about using my own version of validateAuthData, but to use validateAuthData from inside parse-server in my application. Hope that makes sense!

**Comment by flovilmart** [comment]
oh right, yeah for now the long import paths are the solution. Not sure we wanna clutter index with more exports, or in that case, we'd move the ParseServer class to another file

**Comment by steven-supersolid** [comment]
Makes sense. I didn't try this before but do you mean something like this?

`var authDataManager = require('../node_modules/parse-server/lib/authDataManager');`

**Comment by flovilmart** [comment]
yup, should work like that, or `require('parse-server/lib/authDataManager')` if parse-server is a dep
