### ISSUE TITLE
Unity3D - Parse Mingration

### ISSUE THREAD

**Issue by kashif789us** [ParsePlatform/parse-server#1173]
I have a Unity3D game currently hosted on parse. I am in the process of migrating it to mongoDB and Heroku. I have followed this link [Parse Migration](https://learnappmaking.com/how-to-migrate-parse-app-parse-server-heroku-mongolab/)

Although its for iOS and I have tested it working on iOS, I am doing the same steps in Unity.

The code I am using in Unity3D is:

`ParseClient.Initialize(new ParseClient.Configuration {
            ApplicationId = "",
            Server = "",
            WindowsKey = ""
        });`

But nothing happens. If I initialize it like this on iOS, it works perfectly. But its not working on Unity. Any help would be greatly appreciated. Thank you

**Comment by steven-supersolid** [comment]
Which Unity SDK are you using? AFAIK there is no released Unity SDK that supports a custom server yet.

https://github.com/ParsePlatform/Parse-SDK-dotNET

**Comment by kashif789us** [comment]
I am using version 1.7.0. 

https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide 

In the above link you can see in .net section how its being initialized. I am doing like that as Unity SDK is based on .net.

**Comment by steven-supersolid** [comment]
I don't know if it is possible to initialize that way in Unity, instead ParseInitializeBehaviour is usually attached to the scene but that does not allow for passing custom config. https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/166

If you look in the source code for ParseInitializeBehaviour.Awake() can see that it is making an additional call after initializing ParseClient.

**Comment by kashif789us** [comment]
Yes ParseInitializeBehaviour does make a call to ParseClient. I am doing it myself without the need of calling ParseInitializeBehaviour. Is there a way to accomplish what I want to do?

**Comment by hramos** [comment]
This appears to be a client SDK issue unrelated to Parse Server. Please look for the relevant repository on GitHub for this SDK and consider opening an issue there.

A list of Parse's open source repositories is available at [parseplatform.github.io](http://parseplatform.github.io)
