### ISSUE TITLE
Extend wiki article on S3 file adapter with warning about effect of directAccess

### ISSUE THREAD

**Issue by mtrezza** [ParsePlatform/parse-server#1178]
#### Introduction
The [wiki article](https://github.com/ParsePlatform/parse-server/wiki/Configuring-File-Adapters#configuring-s3adapter) describes the configuration of S3 file adapter for file storage.

#### Motivation
The article describes it's parameter `directAccess`as follows:
> Whether reads are going directly to S3 or proxied through your Parse Server.

Although it is implicitly understandable, it does not explicitly mention that when setting this parameter to true, the uploaded file's ACL is set to be publicly readable. As this is a potential security issue, this effect should be more clearly mentioned.

#### Suggestion
1. Explicitly add a warning that activating "directAccess" effects in setting the uploaded file to be publicly accessible.
2. The parameter is currently described in two tables [here](https://github.com/ParsePlatform/parse-server/wiki/Configuring-File-Adapters#using-environment-variables) and [here](https://github.com/ParsePlatform/parse-server/wiki/Configuring-File-Adapters#s3adapter-constructor-options). To prevent redundancy and confusion the two tables should be combined to one.

**Comment by drew-gross** [comment]
I've updated the two tables. Removing the redundancy would be a bigger restructuring of the docs, maybe I will get to that later.
