### ISSUE TITLE
ParseFile upload with javasctipt creating Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by skavinvarnan** [ParsePlatform/parse-server#118]
When i tried to upload a file to parse-server using [this documentation](https://parse.com/docs/js/guide#files) its throwing an error Access-Control-Allow-Origin.

Digging more into the request and response i found that the below Response Header is missing out these 
Access-Control-Allow-Headers:*
Access-Control-Allow-Methods:GET,PUT,POST,DELETE,OPTIONS
Access-Control-Allow-Origin:*

I tried saving a ParseObject using [this documentation](https://parse.com/docs/js/guide#objects-saving-objects) In that response i do get the above Response Headers and everything works fine

Note: I tried to upload the ParseFile with the same code to Parse Main server and everything worked fine. I also got the Response Header as * for Access-Control-Allow-Headers and Methods

I found a comment in [files.js](https://github.com/ParsePlatform/parse-server/blob/master/files.js#L81)
// TODO: do we need to allow crossdomain and method override?

I think my problem will be solved when crossdomain is added

**Environment:**
node version: 4.2.4
parse-server version: 2.0.3

**Comment by samarthagarwal** [comment]
I solved it by using the following.
```
app.use(function(mountPath, res, next) {
    res.setHeader("Access-Control-Allow-Origin", "*");
    return next();
  });
```

**Comment by skavinvarnan** [comment]
@samarthagarwal 
Nice work.

But this can be used as a temporary solution. The exact solution would be adding a middleware Response Header in the files.js itself. 

I tried to give a solution but unable to understand the flow. 
But well aware that [middleware.js](https://github.com/ParsePlatform/parse-server/blob/master/middlewares.js) [crossdomain](https://github.com/ParsePlatform/parse-server/blob/master/middlewares.js#L132) should be added to [files.js](https://github.com/ParsePlatform/parse-server/blob/master/files.js) in [this route](https://github.com/ParsePlatform/parse-server/blob/master/files.js#L82)

**Comment by gfosco** [comment]
@skavinvarnan Would you like to submit a PR?

**Comment by vbabaria** [comment]
@samarthagarwal - Could you pls suggest file name and location to enable CORS?

thank you

**Comment by gfosco** [comment]
This should be working in #390 and will be in 2.1.3 (or you can pull master.)  Please open a new issue if you still have problems.  Thanks.
