### ISSUE TITLE
Push notifications not sent

### ISSUE THREAD

**Issue by firasalkafri** [ParsePlatform/parse-server#1182]
- [x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Nothing special

#### Steps to reproduce
Using Parse Android SDK 1.13.0 and parse-server version 2.2.2

#### Logs/Trace

**Parse Server Verbose trace:**

POST /parse/push { 'user-agent': 'node-XMLHttpRequest, Parse/js1.8.1 (NodeJS 5.8.0)',
  accept: '*/*',
  'content-type': 'text/plain',
  host: 'localhost:1337',
  'content-length': '311',
  connection: 'close' } {
  "channels": [
    "SOME_CHANNEL"
  ],
  "data": {
    "title": "dummy title",
    "message": "dummy message",
    "action": "ACTION",
    "senderId": "4zSfKw2T5b"
  }
}
response: {
  "response": {
    "result": true
  }
}
response: {
  "response": {
    "result": "sent"
  }
}

**DB Record**

{ "_id" : ObjectId("56f45b891eb3cdae4d74d160"), "objectId" : "WWfLEatYht", "pushTime" : "2016-03-24T21:26:33.921Z", "_created_at" : ISODate("2016-03-24T21:26:33.921Z"), "query" : "{\"channels\":{\"$in\":[\"SOME_CHANNEL\"]}}", "payload" : { "title" : "dummy title", "message" : "dummy message", "action" : "ACTION", "senderId" : "4zSfKw2T5b"}, "source" : "rest", "title" : null, "expiry" : null, "status" : **"succeeded", "numSent" : 0**, "pushHash" : "d1eeaba5cb95ce819c32efe295b2fe96", "_wperm" : [ ], "_rperm" : [ ], **"numFailed" : 0**}

Can't find anything in server logs even when VERBOSE is set to 1, where can I find GCM request and response?

Possible duplicate #1127

**Comment by wangmengyan95** [comment]
Please update parse-server to `2.2.2`. We have a  known issue #1104 and it has been fixed.

**Comment by firasalkafri** [comment]
@wangmengyan95 sorry I'm using 2.2.2 not 2.2.0

**Comment by jiawenzhang** [comment]
I was using 2.2.0 and having issues of sending GCM push, after upgrading to 2.2.2, push worked.

**Comment by firasalkafri** [comment]
@jiawenzhang I updated to 2.2.2 and produced the same issue, not logs or traces for any error.

**Comment by firasalkafri** [comment]
@flovilmart please any ideas? thoughts? comments? I can't even debug

**Comment by flovilmart** [comment]
We externalized the modules to simplify bug reports, please reopen here: https://github.com/parse-server-modules/parse-server-push-adapter

**Comment by flovilmart** [comment]
@wangmengyan95 added you as owner in the organization

**Comment by firasalkafri** [comment]
@flovilmart That's good news, would love to contribute there

**Comment by flovilmart** [comment]
we actually removed all adapters from the core parse-server to simplify contributions and bug reports
