### ISSUE TITLE
Destination not empty after 80% of data migration

### ISSUE THREAD

**Issue by ShipraShalini** [ParsePlatform/parse-server#1184]
I was trying to migrate Parse data to mlabs  and after around 80% of data transfer, it failed with error that 

> `The destination database was not empty`

Also the transfer rate keeps on decreasing, (even to 60 rows per second).

Please suggest what should be done to avoid this.

**Comment by drew-gross** [comment]
For issues with the migration process, please contact our support through [parse.com/help](http://parse.com/help)
