### ISSUE TITLE
Does self-host parse-server can support several push identifies

### ISSUE THREAD

**Issue by scorpion1750** [ParsePlatform/parse-server#1186]
I have a requirement that I need to push notifications with several bundleIds  of Apple and senderIds of google on a single app.I find it's possible on the Parse Dashboard ,but I can't implements of  this function on the open source you provided.

**Comment by bohemima** [comment]
It is possible, see the last configuration example here -> https://github.com/ParsePlatform/parse-server/wiki/Push#2-configure-parse-server
