### ISSUE TITLE
ParseFacebookUtils login fail with "ParseRequestException: Permission denied for this action."

### ISSUE THREAD

**Issue by thphuc** [ParsePlatform/parse-server#1192]
I try to login using ParseFacebookUtils.
Login with Facebook working and I can get Facebook name, but in the done() method, user is always null with exception: "ParseRequestException: Permission denied for this action."

- [x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Parse server on Heroku

#### Steps to reproduce
```
List<String> permissions = Arrays.asList("public_profile", "email");
ParseFacebookUtils.logInWithReadPermissionsInBackground(this, permissions, new LogInCallback() {
            @Override
            public void done(ParseUser user, ParseException err) {
                if (user == null) {
                    Toast.makeText(getApplicationContext(), "Login not successful", Toast.LENGTH_SHORT);
                } else if (user.isNew()) {
                    signUp();
                    ParseInstallation.getCurrentInstallation().put("user",       ParseUser.getCurrentUser().getObjectId());
                    ParseInstallation.getCurrentInstallation().saveInBackground();
                } else {
                    ParseInstallation.getCurrentInstallation().put("user", ParseUser.getCurrentUser().getObjectId());
                    ParseInstallation.getCurrentInstallation().saveInBackground();
                }
            }
        });
```

#### Logs/Trace
ParseRequestException: Permission denied for this action.

**Comment by techmohib011** [comment]
There seems to be a problem with parse-server as the permission denied exception comes from the _SCHEMA table on mlab. It goes away when you reset the _SCHEMA

**Comment by flovilmart** [comment]
Do you have CLP set on your Installation schema?

**Comment by flovilmart** [comment]
Any news on that?

**Comment by thphuc** [comment]
@flovilmart I had to reset the _SCHEMA collection to make it works.
@techmohib011 How is it going from your side?

**Comment by socialstats** [comment]
@thphuc how exactly did you reset the _SCHEMA collection? Was it simply deleting that collection and mLab recreating it? Or is there a better way of doing it?

**Comment by adamhellewellhq** [comment]
@thphuc how exactly did you reset the _SCHEMA collection? Was it simply deleting that collection and mLab recreating it? Or is there a better way of doing it?

**Comment by drew-gross** [comment]
No response in many days, closing.
