### ISSUE TITLE
Parse error logs?

### ISSUE THREAD

**Issue by NorthMcCormick** [ParsePlatform/parse-server#12]
I've got my server up and running with Heroku however upon authenticating my users I'm getting:

{
    "code": 1,
    "message": "Internal server error."
}

Also showing this in the Heroku Logs

Uncaught internal server error. bad obj: undefined undefined

I'm unable to locate any of the logs for node or parse though. Is there a location that they would be? I know traditionally this means that it's Parse's bug but since I've got it hosted I need to figure out what's going on.

Thanks!

**Comment by wangmengyan95** [comment]
Hi @NorthMcCormick, do you mind pasting
1. The full log of Heroku
2. The way you config your Parse Server

**Comment by wagnercsfilho** [comment]
I had this problem , but I decided upgrading the version of Expressjs

**Comment by NorthMcCormick** [comment]
@wangmengyan95 

Here's the log:

`2016-01-29T03:27:07.310178+00:00 heroku[router]: at=info method=GET path="/parse/login?username=NorthMcCormick&password=1111" host=redfit-beta.herokuapp.com request_id=68d2ce1f-4dcb-4159-b74b-f66a39d346c6 fwd="50.131.85.118" dyno=web.1 connect=1ms service=127ms status=500 bytes=390
2016-01-29T03:27:07.321004+00:00 app[web.1]: Uncaught internal server error. bad obj: undefined undefined`

Then for the config, I'm using a slightly modified version of the sample in the README

`var express = require('express');
var ParseServer = require('parse-server').ParseServer;

var app = express();

// Specify the connection string for your mongodb database
// and the location to your Parse cloud code
var api = new ParseServer({
	databaseURI: '-------',
	cloud: './cloud/main.js',//'/home/myApp/cloud/main.js', // Provide an absolute path
	appId: '-------',
	masterKey: '------',
	restAPIKey: '-------',
	//_production_appId: 'myAppId',
	//_production_masterKey: 'mySecretMasterKey',
	//_production_restAPIKey: 'myRESTAPIKey',
	//_fileKey: 'optionalFileKey'
});

// Serve the Parse API on the /parse URL prefix
try {
	app.use('/parse', api);
} catch(e) {
	console.log(e);
}

// Hello world
app.get('/', function(req, res) {
	res.status(200).send('Express is running here.');
});

var port = process.env.PORT || 1337;
app.listen(port, function() {
	console.log('parse-server-example running on port ' + port + '.');
});
`
Omitted my keys and database.

@wagnercsfilho I just attempted to upgrade my express as well but it didn't seem to change anything.

**Comment by gfosco** [comment]
I suggest removing the rest API key from the config.  If you set any keys, all requests require a key.

**Comment by NorthMcCormick** [comment]
@gfosco so where would I set it then? Via their migration docs it's an allowed thing and I'm sending it all with my request, I've been using parse for almost a year so I'm pretty familiar with how it *should* work.

**Comment by gfosco** [comment]
Check the readme, in parse-server the client keys are not required at all.  Can you launch with VERBOSE=1 as an environment variable and capture the data posted to /login from the logs?

**Comment by NorthMcCormick** [comment]
While not required, I am going to stick to using them as that added security measure for my software. My development environment isn't running locally so I'm to assume that I can't trust a no-key set up. I'm going to work on getting a local copy going later today. I'll also see if I can get VERBOSE working.

**Comment by NorthMcCormick** [comment]
Quick update: Deploying and working without the rest key, still does not solve the issue. I can't get Verbose to work but that's just me not being familiar with heroku.

**Comment by gfosco** [comment]
It's important to know that adding client keys does not add security, like literally none.  In parse-server, unlike hosted Parse, the rest api key has no additional permissions over a client key.  All of the client keys were public, so they essentially serve only to function as a 2 part app id, and you don't need that.  All you need is an app id, and a master key.

I'm going to close this, because it wasn't clear what the issue was.  I hope you can try the newest version (2.0.4) and see if it fixes things, or try to debug further and open a new issue with details.  Thanks.
