### ISSUE TITLE
Cannot add multiple relations to ParseRole

### ISSUE THREAD

**Issue by flavordaaave** [ParsePlatform/parse-server#1202]
#### Environment Setup
Parse Server 2.2.2

#### Steps to reproduce
I'm not 100% sure wether this is a bug or intended behavior, so please correct me if I'm wrong.

I've a huge cloud function to setup my initial roles. At [line 386](https://gist.github.com/flavordaaave/3b1b63e1a053647a0fc6#file-parse-cloud-define-setuproles-js-L386) I add 2 relations to the "customer" role ("admin" role AND "merchant" role).
But when looking at my DB (`_Join:roles:_Role` collection) after running the function, it seems that only the 1st relation between the "customer" and "admin" role has been set (`customerRole.getRoles().add(globAdminRole);`) but NOT the 2nd relation between "customer" and "merchant" role (`customerRole.getRoles().add(globMerchantRole);`) 

From what I understand when reading the [docs](https://parse.com/docs/js/api/classes/Parse.Relation.html#methods_add) I would assume that if I call the add() function twice it would add both relations.

(sidenote)
I could work around that for now by adding both relations as an array like this:
```
customerRole.getRoles().add([globAdminRole, globMerchantRole]);
```

**Comment by flovilmart** [comment]
Yeah this is an issue with the JS-SDK, use your workaround for now. cc: @andrewimm
