### ISSUE TITLE
How to update parse server on heroku?

### ISSUE THREAD

**Issue by andreiurzica** [ParsePlatform/parse-server#1203]
hello,
i created a heroku server using deploy to keroku button.
how can i update parse after that?
how can i see what parse version i'm running on heroku?

**Comment by pbush25** [comment]
You have to clone the repository to your local machine which Heroku explain in their command line docs, and then you can modify the package.json file to reflect the most recent version of Parse. Then once you commit that back to Heroku, it will build with the newest version.

**Comment by noder199** [comment]
Please follow the manual instructions before using the deploy button, it will make more sense.

**Comment by gsharpe** [comment]
You can update parse by installing the CLI tool, cloning the parse repository, and then deploying it to Heroku. It’s a pretty straightforward operation.

First you’ll need to figure out the git repository that underlies the “Deploy to Heroku” button. You can find instructions for doing this in the [Heroku Knowledge Base](https://kb.heroku.com/why-do-i-see-a-message-you-appear-to-have-cloned-an-empty-repository-when-using-heroku-git-clone). 

As a shortcut, if you used the Deploy button from the [Heroku devcenter](https://devcenter.heroku.com/articles/deploying-a-parse-server-to-heroku) your repository will be `https://github.com/ParsePlatform/parse-server-example`

From there, it’s pretty straightforward:

1. Download the [CLI tool](https://devcenter.heroku.com/articles/heroku-cli)
2. Clone the repository to your computer (this will get the latest version of Parse)
3. Push the repository back to Heroku

A guide to steps 2 & 3 is outlined quite nicely [here](https://kb.heroku.com/node-js-constant-hashtable-seeds-vulnerability-faq) and in a bit more detail [here]( https://devcenter.heroku.com/articles/getting-started-with-nodejs#prepare-the-app).

**Comment by Onwa1kenobi** [comment]
How do i do this if i manually pushed to Heroku without using the button?
