### ISSUE TITLE
Push Notification "Increment" badge feature

### ISSUE THREAD

**Issue by framp** [ParsePlatform/parse-server#1211]
From docs it seems like this isn't supported but this PR [939](https://github.com/ParsePlatform/parse-server/pull/983/files) seems to address it.

I don't have a iOS device to test it at the moment but I'd love to know if it's working or not.
Happy to step in and send a PR if it's not there.

Cheers

**Comment by flovilmart** [comment]
It's implemented, and should be working properly, as well as updating the badge value on Installation for iOS devices
