### ISSUE TITLE
resetPassword: Permission denied for this action.

### ISSUE THREAD

**Issue by andresgarza** [ParsePlatform/parse-server#1212]
- [x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

parse-server v2.2.2

#### Steps to reproduce

- Setup email adapter according to README instructions
- Request password reset email
- Click on link to go to choose_password page
- Attempt to submit password

#### Logs/Trace

No logs/errors on server by default, but by running the server locally, I was able to determine the `userController.updatePassword` in the `PublicAPIRouter` catches the `Permission denied for this action.` error and redirects back to the choose password page.

**Comment by flovilmart** [comment]
@carmenlau ?

**Comment by seryoni** [comment]
I was able to the reset password use case to work with SimpleMailgunAdapter. I did have to debug some of the internals though.

Setting the following arguments that must be passed to the ParseServer ctor solved all the permission denied stuff.

publicServerURL: process.env.PUBLIC_SERVER_URL || 'http://localhost:1337/parse'

appName: process.env.APP_NAME || '<your app name?'

emailAdapter: simpleMailgunAdapter

I set publicServerURL to be the same as serverURL. Didn't really understand the need for both but if you don't set the publicServerURL it all doesn't work.

**Comment by seryoni** [comment]
flovilmart already answered my question below on a different thread. Looks like the documentation on the main project thread got updated with more details.

**Comment by andresgarza** [comment]
@seryoni / @flovilmart I'm actually passing all those options, but I figured out what the actual problem was: it seems like the latest package in `NPM` was released before bunch of commits needed for the password reset to correctly work.

@flovilmart / @gfosco since the README already mentions how to setup email for password resets, could we release a new version of the npm package?
