### ISSUE TITLE
MismatchSenderId

### ISSUE THREAD

**Issue by fabuhelow** [ParsePlatform/parse-server#1215]
Hi,

I have tried to push new notification from my parse-server, but i have got the following error:

GCM request and response {"request":{"params":{"priority":"normal","data":{"time":"2016-03-27T13:15:43.556Z","push_id":"K8QBFFDDe1","data":"{\"title\":\"The Shining\",\"alert\":\"All work and no play makes Jack a dull boy.\"}"}}},"response":{"multicast_id":8205105798183603000,"success":0,"failure":2,"canonical_ids":0,"results":[{"error":"MismatchSenderId"},{"error":"**MismatchSenderId**"}]}}

I have checked my google sender id and API key and they are valid.

**My parse-server version is 2.2.2**

**Comment by flovilmart** [comment]
have you checked that: http://stackoverflow.com/questions/29163089/node-gcm-server-receive-error-mismatchsenderid

**Comment by flovilmart** [comment]
Also, the senderId is never used internally by the push adapter. You could remove that option from the configuration.  This seem solely related to an API key problem.

**Comment by fabuhelow** [comment]
@flovilmart  i have checked the url that you have send and also removed the senderId from my config. object but still got the same error

**Comment by flovilmart** [comment]
So I'm not sure what the issue is. We use node-gcm and I've run some tests and with a valid API key from Google cloud platform, I manage to get the push sent

**Comment by fabuhelow** [comment]
Thanks @flovilmart , Still need a help about this issue.

**Comment by flovilmart** [comment]
Can you try generate another API key ? Look at node-gcm documentation, I believe they have a debug mode you can enable with environment variables

**Comment by flovilmart** [comment]
Maybe related to #942

**Comment by weengo** [comment]
@fabuhelow, 2 things to check here:

1) If you're on android, confirm that the manifest file has your **sender Id**. My mistake was to put the api key on that value.
`<meta-data android:name="com.parse.push.gcm_sender_id" android:value="id:XXXXXX"/>`

2) On your google console, confirm that you're using the key of type Server, and not the Android type.

**Comment by flovilmart** [comment]
@fabuhelow did you get to the bottom of it? This is however not related to parse server but to https://github.com/parse-server-modules/parse-server-push-adapter

Would you reopen on the other repository if you still face problems?
