### ISSUE TITLE
NPM link fail

### ISSUE THREAD

**Issue by lastMove** [ParsePlatform/parse-server#1218]
I am trying to follow the Development guide. 

#### Environment Setup
Mac OS X El Capitan
NPM 2.14.20
Node.js v4.4.1

#### NPM LINK
"npm link parse-server path/to/cloned/repo" this command is not working for me.
I made : sudo npm link parse-server .

#### LOG
/Users/lastMove/Documents/Dev/parse-server/node_modules/parse-server -> /usr/local/lib/node_modules/parse-server -> /Users/lastMove/Documents/Dev/parse-server
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "link" "parse-server" "."
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20

npm ERR! May not delete: /Users/lastMove/Documents/Dev/parse-server/node_modules
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lastMove/Documents/Dev/parse-server/npm-debug.log

**Comment by flovilmart** [comment]
try `npm link path/to/cloned/repo`

**Comment by lastMove** [comment]
It works, thank you a lot.
