### ISSUE TITLE
Why we need to set the serverUrl?

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/parse-server#1221]
I'm wondering why we need to set the serverUrl in parse-server application? Why can't we just use relative path for this, for example, "/parse" instead?

The reason I ask this question is I'd like to deploy the parse server to a load balance server. There is no way for me to implement load balance if different app using different serverUrl. Any idea? Thanks.

**Comment by flovilmart** [comment]
serverURL should be a loopback URL so the server is able to use the Parse SDK on itself.

**Comment by zhouhao27** [comment]
Thanks. Does this mean I can always set serverUrl to something like http://localhost:1337?

**Comment by drew-gross** [comment]
Yep! As long as you are running your server on port 1337, that should work.

**Comment by zhouhao27** [comment]
This is a bit misleading because server should know it's own url. And there is a method in client with the same name **serverUrl**.

Thanks anyway.

**Comment by drew-gross** [comment]
Yeah. Ideally we would like to make some changes to the JS SDK that make it not need a server URL, but that isn't particularly easy. Maybe it will come later.
