### ISSUE TITLE
collectionPrefix & custom certificates are not available in the migration tool

### ISSUE THREAD

**Issue by natanrolnik** [ParsePlatform/parse-server#1224]
One of the good things that Parse-Server allows is `collectionPrefix`. It allows us using the same mongo database for different applications, thus reducing costs and overhead of maintaining different databases.

Another advantage of parse-server is that it allows using self-signed SSL certificates to encrypt connections between the server and the mongo instance.

The problem is that any of these are compatible with the current Parse.com migration tool:
1 - The ability to provide a `collectionPrefix` - so this way, both the hosted Parse and the parse-server, that will be reading from/writing to the database, will be able to work together until the shutdown;
2 - The option to provide a self-signed certificate so the connections to the mongo instance work correctly. (In my specific case, I purchased an SSL certificate, installed in the mongodb instance; connections to it work from command line but not from the migration tool - so I'm wondering if I should ignore SSL at all or keep trying to find the reason - for example, maybe hosted parse doesn't trust the certificate provider)

(I know this issue is not fully related to Parse-Server, but as it has to do with what's implemented here, and we hear directly and more from the Parse team, I preferred to open this issue)

**Comment by gfosco** [comment]
Yeah, this is one of those things that I agree with and it would be nice, but it's just not going to happen...  Personally I like being able to run multiple apps on the same server and database, but we're in the extreme minority, and there's no official interest in supporting this right now.

**Comment by natanrolnik** [comment]
:cry: but totally understand!
