### ISSUE TITLE
Indexes support

### ISSUE THREAD

**Issue by miav** [ParsePlatform/parse-server#123]
So, to be concise, I have no idea what this means in the migration guide:

> You need to manage your indexes yourself. Hosted Parse automatically adds indexes based on the incoming query stream.

but it **sounds very important**. Could support for this be provided? Is there anyone willing to work on it?

**Comment by jyoon17** [comment]
#36 might be helpful.

**Comment by miav** [comment]
Had not seen that. That looks like a **no**, but I wonder, if you:

- are shutting down
- have open sourced all your SDKs
- have open sourced the core server code of your service
- will probably open source the web dashboard
- are offering tools for a smooth-as-possible migration

..why not releasing something like that, which you already have and is so important? Not now maybe, but at least in the following months. Just curious guys, you are doing great work and I can see it's hard to make any promises.

It's just that lots of people will start to migrate 2, 3, 4, 5 months from now. Knowing that a certain feature (be it push or dashboard or indexes) will eventually be present in `parse-server` can make a difference in our decision process.

Little example: as a google cloud user I can either host a mongo instance on a Compute Engine cluster, or use an external service like MongoLab. While the first can be better for a number of reasons, MongoLab suggests indexes for you and so can be our choice if `parse-server` will never implement indexing... Knowing that it will / will not be featured is **very** important at this point.

**Comment by gfosco** [comment]
There is a chance of this being added, but cannot promise anything.  If anyone wants to work on it, that would be welcomed too.  Even a relatively naive auto-indexer would be valuable.

**Comment by dedene** [comment]
@gfosco Do you know if there are any recordings or slides available for this talk on Percona Live Amsterdam? 

https://www.percona.com/live/europe-amsterdam-2015/sessions/dynamic-indexing-half-million-apps-parse 

It might help in building a simple naive auto-indexer.
