### ISSUE TITLE
Parse server Dashboard

### ISSUE THREAD

**Issue by thamer898** [ParsePlatform/parse-server#1233]
Hello

How to start parse dashboard ?
![error](https://cloud.githubusercontent.com/assets/17239124/14091682/f9d16330-f541-11e5-93e3-22cbb7518b0a.PNG)

Regads

**Comment by gfosco** [comment]
Please see https://github.com/ParsePlatform/parse-dashboard

Not sure if you've run `npm install` properly, the real error message is cut off in your screenshot.

**Comment by thamer898** [comment]
Thank you very much @gfosco it work's .
