### ISSUE TITLE
Need advice on server deployment on AWS

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/parse-server#1237]
My parse server is running in my AWS EC2 instance. It works with a load balance although there is only one instance right now. There is an issue for me for the MongoDB database. Is there a way to setup a load balance for MongoDB in AWS? Or is there a way to setup MongoDB in RDS so that the load balance will be handled by AWS itself?

Need your advice. Thanks.

**Comment by andresgarza** [comment]
RDS is for relational databases only. I would recommend using a service such as mLab as deploying your own MongoDB instance is no trivial task. mLab itself can use AWS to host the database.

**Comment by gfosco** [comment]
Scalegrid.io seems to be a good choice for managing a mongo deployment inside AWS.  Going to close this, it's not really an issue with parse-server, could be handled elsewhere as a general mongo hosting question.  There is also an AWS guide https://aws.amazon.com/blogs/aws/mongodb-on-the-aws-cloud-new-quick-start-reference-deployment/
