### ISSUE TITLE
Sending push notification result in server shutdown.

### ISSUE THREAD

**Issue by scorpion1750** [ParsePlatform/parse-server#1240]
Hi,
I have meet  problems of push notification.My app have more than 20,0000 users.
1) When I am using  the test curl command to query my installations ,I received the reply is 'Empty reply from server'?
2)I check my server process finding out my parse-server had shut down.
3) I pushed a notification using curl command received "{result:true}",but my server shut down too.
4)Push to small amount of users could be find.
I think the performance of push notification is not good as well as the Parse Dashboard,maybe  some bugs result in the problem.I hope you can help me solve this problem.Thanks!

**Comment by drew-gross** [comment]
Can you help us with debugging this a little? Since it sounds like a performance problem, can you first try doing the exact same set of commands on an app with fewer users and see if it works? Also, if you are running on an infrastructure provider that makes this easy, can you try running the server on a more powerful instance and seeing if that helps? Finally, could you show us any logs that the server outputs as it shuts down, and also describe the machine your setup is running on? Amount of RAM, CPU, DB size, storage type, and so on.

**Comment by scorpion1750** [comment]
My server is on AWS instance type is t2.micro,database is mlab (M3 15GB,160GB).I pushed to about 12940 users yesterday, it seemed ok.I just tested again finding out that the running process's memory continue increasing and reach 100% percent finaly. I think this may be the reason causing this crash.
![b8b1a0c4-da01-4378-9c93-974b3a9cca42](https://cloud.githubusercontent.com/assets/17715928/14101464/4aba58e4-f5c7-11e5-9fb2-a3439692a519.png)

**Comment by scorpion1750** [comment]
I also tested on my Mac pro ,it  comes out the same result.But my pc has many free memory.
![cfc95dde-db2f-43c4-be92-7d51bc61a48a](https://cloud.githubusercontent.com/assets/17715928/14102058/07871522-f5cb-11e5-8283-50ddf12f10e3.png)

**Comment by flovilmart** [comment]
Yeah we may wanna use query cursors on that...

**Comment by gfosco** [comment]
There was another issue yesterday about memory usage.. there could be a leak somewhere.

**Comment by drew-gross** [comment]
Yah using cursors should help with push related perf issues.

**Comment by scorpion1750** [comment]
When will you improve the push performance?I have another question that I cann't find out the open counts from self host parse-server.

**Comment by flovilmart** [comment]
@scorpion1750 Pull requests are welcome!

**Comment by scorpion1750** [comment]
Ok,I will try.

**Comment by flovilmart** [comment]
Just to give your pointers:

1. the query is executed in the PushController.js, we may wanna use a cursor and to it by batch, sequential, parallel. 
2. the push is sent through parse-server-push-adapter, if you want to improve some queuing etc... PR there

important notes:

- GCM is limited to 1000 devices / send, 
- APN is a bit more complicated than that, as we use the binary interface that streams the push requests hopefully we'll be able to use the HTTP/2 API soon.

**Comment by scorpion1750** [comment]
I have another question How can I statistic the open rate of one push ?It  seems that the latest version have't implement this function yet.

**Comment by flovilmart** [comment]
@scorpion1750 I opened a PR https://github.com/parse-server-modules/parse-server-push-adapter on the push adapter to leverage APNS performance improvements. We're waiting for a good review before merging and distributing.

For the open rate push, we don't support that now as the analytics endpoint is not implemented. I suggest you use a mobile analytics platform like mix panel, segment and friends.

I'll also be closing it for now as we splitted the push adapter into it's own repository. Feel free to re-open if you feel it's not right.
