### ISSUE TITLE
FB login creates a new user if executed on a different server

### ISSUE THREAD

**Issue by markuswinkler** [ParsePlatform/parse-server#1241]
I am in the process of migrating and wanted the following setup:
- local parse server + local mongoDB for testing/debugging
- cloud parse server + cloud mongoDB for deployment

My iOS app uses facebook for login.
I noticed that when I dump my cloud database into my local database,
all user account are not recognized anymore, `PFFacebookUtils.logInInBackgroundWithReadPermissions` simply creates a new user.

I compared the `authData` field between the old and the new entry.
The FB user `id` is the same, but the `access_token` and `expiration_date` has changed.
Is there a way to lookup the id first and just update those fields two with new values?

Thanks!

**Comment by flovilmart** [comment]
The lookup is based on the Facebook user ID. I'm not sure here if the problem is not related to the way you transfer data across your cloud/client.
Note that we don't use the authData field in mongo but _auth_data_facebook

**Comment by markuswinkler** [comment]
Thanks, when I tried to replicate the error I found out the cause.
I exported my data from parse.com manually via the dashboard and some fields don't keep their original DB column names but instead are renamed to the dashboard column values.
e.g. _id becomes objectId, _auth_data_facebook becomes authData.
That's why the users didn't get recognized after export/import.

Do you know if there are any other fields that get renamed?
I was already pulling my hair out over the _id/objectId issue, because everything seems to work at first but then you run into very funny errors.

**Comment by drew-gross** [comment]
Check createdAt, updatedAt, and (for sessions) expiresAt. We recommend using the migration for better consistency.

**Comment by markuswinkler** [comment]
Thanks.
In my case I didn't have a choice since my provider users Mongo 3.2 and the migration only supports 3.0.
