### ISSUE TITLE
Feature request: make authData an array

### ISSUE THREAD

**Issue by markuswinkler** [ParsePlatform/parse-server#1243]
I am sorry if this is the wrong place, not sure where to post a feature request.

Details:
Right now it's not possible (as far as I know) to use different OAuth methods for the same user account.
I login with Facebook, a user is created. I login with Twitter, another user is created and so on.
Ideally it shouldn't matter what OAuth method (LinkedIn, Facebook, Twitter, ...) a user uses, they should all point to the same account. Amazon already does this with the Cognito service that returns the same  unique ID independent of the OAuth provider.
I am wondering if something similar could be implemented with parse server, maybe even by leveraging AWS Cognito.

**Comment by tanmays** [comment]
I'm pretty sure you can already link multiple social networks to the same user. Check the linking section of doc here: https://parse.com/docs/rest/guide#users-linking

Once you have linked, say a twitter account, submit a PUT request with FB authData and a valid user session token to link Facebook to the same Twitter based account.

I haven't tried it yet but if you use multiple oAuth in your app you should give it a try and see if it works as intended.

**Comment by flovilmart** [comment]
@tanmays could not have said it better.

**Comment by markuswinkler** [comment]
Great! :+1: 
Thank you @tanmays !
