### ISSUE TITLE
Can't change password server-side

### ISSUE THREAD

**Issue by douineauromain** [ParsePlatform/parse-server#1249]
#### Environment Setup
A Node.js app which call a distant parse-server instance.
Parse initialized with the MasterKey

#### Steps to reproduce
```
app.post("/changePassword, function (req, res) {	
        var res_user = req.body.user;
        var User = Parse.Object.extend("User");
        var query = new Parse.Query(User);
        query.get(res_user, {
            success: function(user) {
                var password1 = req.body.password || null;
                var password2 = req.body.password2 || null;
                if(!password2){
                    password2 = password1;
                }
                if(password1 != '' && password1 != null){
                    if(password1 === password2){
                        user.set("password", password1); 
                        user.save(null, {
                            success: function(user) {
                                _res(res, "Your password was updated");
                            },
                            error: function(error) {
                                res.error(error); //(Custom func I added to the res object)
                            }
                        }).then(function(){
                            //ok
                        });
                    } else {
                        res.error("Password are not equals !");
                    }
                } else {
                    res.error("Password is not valid !");
                }

            },
            error: function(object, error) {
                res.error(error);
            }
        });

    });	
```

#### Logs/Trace
It throw an error without any message while saving the user.
![image](https://cloud.githubusercontent.com/assets/8361263/14111165/f3b71412-f5c9-11e5-8e6a-8995e87345f5.png)

**Comment by gfosco** [comment]
Strange behavior but a few things look wrong... The request object passed in is `req` but you're accessing `request.params.user`.  The User class has a collection name of `_User`, and since you're not making the calls *as* the user, you should use the master key to make them.  Is request.params.user a string object id?  Have you validated that you're getting the correct values here (`req.params.user`, `req.body.password`, `req.body.password2` or should they all use req.params)? 

Commenting your intent would be useful. Instead of extending, just create a query with: `var query = new Parse.Query("_User");` and pass an options block, and here it is with promises and arrow functions:

```js
app.post("/changePassword, function (req, res) {
  // If a user id and password is provided, change the password
  // If both password fields are submitted, they must be equal
  var reqUser = req.params.user; 
  var reqPassword = req.params.password;
  var reqConfirm = req.params.password2;
  if (!reqUser || !reqPassword || reqPassword != reqConfirm) {
    res.error('Invalid parameters.');
    return;
  }

  var query = new Parse.Query('_User');
  query.get(reqUser, { useMasterKey: true }).then((user) => {
    user.set('password', reqPassword); 
    return user.save(null, { useMasterKey: true });
  }).then(() => {
    _res(res, 'Your password was updated');
  }, (obj, error) => {
    console.log('Failed save during /changePassword', error, obj);
    res.error('Failed to change password!');
  });
}); 
```

Add some additional logging as well, to the console,

**Comment by douineauromain** [comment]
Thanks for your fast response.

>  Is request.params.user a string object id? 
Yes it is.

> The request object passed in is req but you're accessing request.params.user
Sorry it's just a mistake when I edited my code after pasting it, the original code wasn't wrong.

I tested your code and...
It work nice ! :smiley: 

Thank you very much :+1:
