### ISSUE TITLE
Add-to-Wiki: Parse Migration Tool to PushBots

### ISSUE THREAD

**Issue by amrsobhy** [ParsePlatform/parse-server#125]
We (PushBots) have created an automatic migration tool to smooth transition. Would it be possible to add to your Wiki community links? Thanks
https://pushbots.com/parse

**Comment by christianmarth** [comment]
This seems like a third party service that is not related to parse-server.

**Comment by christianmarth** [comment]
Now that there's a push adapter in place, @amrsobhy you can look ar developing this for pushbots
