### ISSUE TITLE
canAddField does not respect master key

### ISSUE THREAD

**Issue by anatolydwnld** [ParsePlatform/parse-server#1257]
DatabaseController.canAddField does not check whether a request is issued with a master key before verifying CLPs. This is not consistent with all other DB ops(create/update/read/delete). Is it this way by design?

**Comment by flovilmart** [comment]
Is this causing a problem?

**Comment by anatolydwnld** [comment]
It causes 404s with "operation not permitted" on writes with the master key, which was surprising and difficult to debug.
