### ISSUE TITLE
Cloud Code Error Internal Server Error 1 using Mailgun 

### ISSUE THREAD

**Issue by greatis** [ParsePlatform/parse-server#1258]
I use Parse Server on the Google Cloud.
Migration works well.
I am able to read information from my classes, upload files.

1. My cloud hello function works well.
2. I made a simple Cloud.HttpRequest function.
It works.
3. Mailgun module gives me always "Internal Server Error", code 1 .
I use this module:
https://github.com/ParsePlatform/JavaScriptModulesTutorial

Parse.Cloud.define("sendMail", function(request, response) {
var Mailgun = require('/my path/mailgun.js');
Mailgun.initialize('my-domaun,'api-key');
var stext=request.params.text.replace(/\\n/g,'\n');
 
  console.log('text: '+stext);
  
Mailgun.sendEmail({
to: "my@email.com",
from: request.params.fromEmail,
subject: request.params.subject,
text: stext
},{
success: function(httpResponse) {
console.log(httpResponse);
response.success("Email sent!");
},
error: function(httpResponse) {
console.error(httpResponse);
response.error("Uh oh, something went wrong");
}
});
});

4. I cannot find a way to how to debug cloud code.
There is no saved cloud code log.
I cannot find the step by step instructions how to store log to file.
I think it is important to have a simple switch to activate the log.
Thanks.

**Comment by gfosco** [comment]
Check the logs from the server when this is executed.  It should be printing something out if it's hitting an internal server error.

**Comment by greatis** [comment]
I see no errors on Mailgun server.
Seems like this is my parse server error:
{"code":1,"error":"Internal Server Error"}

**Comment by gfosco** [comment]
I mean the logs from your parse-server instance.  Run it locally and test.  Often if the server responds with code 1, the server instance will have logged a stack trace to the console.

**Comment by flovilmart** [comment]
did you import mailgun with `require('parse-mailgun')`? If that's the case, it's not available in cloud code...

**Comment by greatis** [comment]
I use myMailModule-1.0.0.js 
I use the full path in require:
var Mailgun = require('/full path/myMailModule-1.0.0.js ');

**Comment by hramos** [comment]
It is not clear that this is an issue in Parse Server, as it concerns "third party" JavaScript code that is being pulled into Cloud Code. I recommend adding logs to your myMailModule-1.0.0.js file to see what Mailgun is responding with.

PS: I am aware that myMailModule.js is one of Parse's own JavaScript examples, but it was written with hosted Parse applications in mind.

**Comment by jforaker** [comment]
Fwiw, you need to use a third party Mailgun module such as https://github.com/bojand/mailgun-js (NOT anything Parse specific)

Then it is easy as this inside your cloud code function:

```javascript
var mailgun = require('mailgun-js')({apiKey: process.env.MAILGUN_KEY, domain: 'mg.yourapp.com'});

            var mail = {
                from: 'you@mail.com',
                to: toEmail,
                subject: subject,
                body: '',
                html: htmlBody
            };

            mailgun.messages().send(mail, function (sendError, body) {
                if (error) {
                    inspect(sendError, 'mailgun sendError');
                } else {
                    inspect(body, 'Successfully send RECEIPT email to "' + toEmail + '"');
                }
            });
```
