### ISSUE TITLE
Cannot GET /parse (Bad Request)

### ISSUE THREAD

**Issue by fraxool** [ParsePlatform/parse-server#126]
Hello,

I'm working on "connecting" my Parse PHP App to my parse-server and I get the error `Bad Request`. By printing the error message in the ParseClient.php class, I get `Cannot GET /parse`.

Here is my code to init my Parse configuration : 

```
ParseClient::initialize( $app_id, $rest_key, $master_key );	
ParseClient::setStorage( new ParseSessionStorage() );

// -- Check if the current user is logged in
$user = ParseUser::getCurrentUser();

if(!$user)
{
	if(isset($_GET["token"]))
	{		
		try {
			$user 		= ParseUser::become($_GET["token"]);
		} catch(ParseException $ex) {
			// The Message "Bad Request" is shown here...
			print_r($ex->getMessage());
		}
	}
}
```
And in my ParseClient.php class, I have replaced the default hostname by mine : 

`const HOST_NAME = 'http://url.com:1337/parse';`

But I always get this "Cannot GET /parse" error... Any idea?

Thanks,
Axel

EDIT : This issue can be closed. I fixed it and managed to make everything working by setting the HOST_NAME in my ParseClient.php file with the following : 

`const HOST_NAME = 'http://url.com:1337';`

AND the API_VERSION with : 

`parse`

... which finally appends "parse" to my parse-server URL.

**Comment by christianmarth** [comment]
Yes, that's correct, you need to set the HOST_NAME and API_VERSION constants as per

http://parseplatform.github.io/parse-php-sdk/classes/Parse.ParseClient.html#constant_HOST_NAME

**Comment by gfosco** [comment]
I need to update the PHP SDK to allow for this... My bad.   Follow on in #124.  Thanks.
