### ISSUE TITLE
Password Reset Issue...Link in the reset email not redirecting to change password.

### ISSUE THREAD

**Issue by djarunn** [ParsePlatform/parse-server#1260]
I am getting the email on resetting the password from mail gun, but on clicking the link response shows 
Cannot GET /apps/APP_ID/request_password_reset?token=<TOKEN>&username=<EMAIL>

#### Environment Setup
>I have Deployed the PARSE Server Example App on heroku. ( "parse-server": "~2.2.2")

>Modified the index.js properly to configure the SimpleMailGunAdapter.

#### Steps to reproduce
>Initiated Reset Password from android app
>Got the email for password reset with the link in this format:
https://xxx.herokuapp.com/apps/MyApplicationID/request_password_reset?token=<Token>&username=xxx%40gmail.com

> Clicking the link ,didn't redirect to choose password page, rather gives the response as 
Cannot GET Cannot GET /apps/<APP_ID>/request_password_reset?token=<TOKEN>&username=<EMAIL>

> I have tried adding the custom pages as well , but that didn't work.

Problem seems to be with routing, and being new to express I am unable to fix it.

Can someone please help.

**Comment by drew-gross** [comment]
This was fixed by #1253 which will go out in the next update.

**Comment by djarunn** [comment]
Hi Drew,

#1253 seems to be the issue with invalid token, but in my case token is
generated correctly.

The problem is with the express routing,its not fetching the reset URL.

Do I need to specify any additional route.
As in my index.js the only route is at the root ('/') that returns some
text when I hit the app URL.

Opening the link from reset email says "Cannot get <resetURL>"

Sorry for bothering you but I am struck at this point since many days.

Please let me know if the same issue is fixed in the new update or anything
else i need to add in my index.js for routes.

**Comment by drew-gross** [comment]
Ah, that is a different issue. I'll reopen this.

**Comment by flovilmart** [comment]
There is two `//` can you remove the trailing slash in publicServerURL and see how it goes?

**Comment by djarunn** [comment]
Hi @flovilmart  , actually there is a APP ID between the slashes ,Mardown removed the APPID .I have modified the issue text.

This is the exact link I got in my email for password reset

https://mhomestest.herokuapp.com/apps/MAb3cyK4CGg5dnmx0kaA9hWEvmZZSFPdgdzKs4qT/request_password_reset?token=VImkgUdbApqRRYyRgBf8JXsh8&username=djarunn.as%40gmail.com

I was wondering how the app would know the routing to the page ,as we have not specified explicitly anywhere in the index.js of Parse Server Example  ( PS : novice to express and node ,please excuse if sounds silly)

**Comment by drew-gross** [comment]
I think you need to make sure you include your mount point in your `publicServerURL`

**Comment by djarunn** [comment]
Drew I have included the mount point in heroku as '/parse':>
PARSE_MOUNT - /parse


Snippet from index.js app:>

// Serve the Parse API on the /parse URL prefix
var mountPath = process.env.PARSE_MOUNT || '/parse';
app.use(mountPath, api);

// Parse Server plays nicely with the rest of your web routes
app.get('/', function(req, res) {
  res.status(200).send('Make sure to star the parse-server repo on GitHub!');
});


>Its getting the root route ('/') properly and I am getting the text(Make sure to star the parse-server repo on GitHub!') on hitting homepage of my app.

**Comment by djarunn** [comment]
Thanks a lot Drew.

The problem was with variable "publicServerURL" .
It was set to my app domain :  http://testmigrate2.herokuapp.com

Rather it should be : http://testmigrate2.herokuapp.com/parse , as we have mounted the parse server on /parse path.

I am able to reset my password successfully.

**Comment by w3care25** [comment]
I am getting following error when trying to requestPasswordReset.
My Parse server version is : 1.0.0
{"level":"error","message":"Uncaught internal server error. [TypeError: promiseHandler(...).then is not a function] TypeError: promiseHandler(...).then is not a function\n at parse/node_modules/parse-server/lib/PromiseRouter.js:286:27\n

also email is not going.
