### ISSUE TITLE
"Parse.Cloud.afterSave(Parse.User ..."  can't modify or find current user

### ISSUE THREAD

**Issue by markuswinkler** [ParsePlatform/parse-server#1266]
I am running into a strange problem. The code below worked fine before migrating to parse-server.
Background: I need create an additional access token based on the user id (which is only available after the user is saved for the first time, not before)

```
Parse.Cloud.afterSave(Parse.User, function(request, response) {
    var userID = request.object.id;
    console.log("User after save");
    var token = request.object.get("token");
    if(token == null || token == "") {
        console.log("creating token");

        var query = new Parse.Query(Parse.User);
        query.equalTo("objectId", userID);
        query.limit(1);
        
        query.find().then(function(results) {
             if(results.length>0) {
                 var user = results[0];
                 user.set("token", tokenGenerator.createToken({uid: userID}))
                 user.save();
             }
         },
             function(error) {
                 reportError("Parse.Cloud.afterSave", "firebase token ("+error.code+")");
                 response.error("Error: Can't query for Installation objects.");
             });
    }
});
```
`results.length` always returns 0. It simply doesn't find the current user.
I tried hard coding the id, didn't work either (funny enough, the id of other users works).

I modified the code a little bit to bypass the query, doesn't work either:

```
Parse.Cloud.afterSave(Parse.User, function(request, response) {
    var userID = request.object.id;
    console.log("User after save");
    var token = request.object.get("token");
    if(firebaseToken == null || firebaseToken == "") {
        request.object.set("token",tokenGenerator.createToken({uid: userID}));
        request.object.save();
    }
});

```

Any help appreciated.

**Comment by gfosco** [comment]
You'll need to use the master key to find user records...

```js
query.find({ useMasterKey: true }).then(...);

obj.save(null, { useMasterKey: true }).then(...);
```

Saving the same object in an afterSave is not recommended, because you'll have to prevent against loops.

**Comment by markuswinkler** [comment]
Thanks! That did the trick! :) :+1: 

In this special case there is only one additional afterSave iteration since the value will be set by then, so I should be fine. However, I totally hear you. I added another condition, just in case the tokenGenerator returns "" as a token (that would indeed result in an infinite loop).

**Comment by cinder92** [comment]
@gfosco your fix is not working for me... i have this code

			```
let User = Parse.Object.extend("User");
			let newUser = new User();

			newUser.set("objectId",objBroadcaster.get("user").id);
			newUser.set("lastName",data.lastName);
			newUser.set("firstName",data.firstName);
			newUser.set("username",data.email);
			newUser.set("email",data.email);
			newUser.set("password",data.password);

			newUser.save(null, {useMasterKey:true})
			.then(response => {console.log(response)})
            .catch(error => {console.log(err)});
```

is never returning nothing... no error, no success. any advice? thanks

**Comment by flovilmart** [comment]
The issue was closed over a year ago, please open a new issue and provide logs when running with VERBOSE=1 for detailed logs
