### ISSUE TITLE
Does dashboard support file adapter?

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/parse-server#1272]
I followed the s3 file adapter setup and upload file through Dashboard. But it seems the file still saved into mongoDB instead of S3 bucket. Is this correct? Thanks.

**Comment by natanrolnik** [comment]
I think you should open this issue in the Dashboard repo:
https://github.com/ParsePlatform/parse-dashboard

**Comment by zhouhao27** [comment]
@natanrolnik Because I don't know it's the problem of parse server or dashboard.

**Comment by natanrolnik** [comment]
I see. So try using one of the SDKs to upload s file. If it's saved correctly in S3, then it's a dashboard bug. If not, it may be some configuration problem. Could you provide some information on how you initialize your S3 bucket?

**Comment by gfosco** [comment]
The dashboard just serves as a client, and would not have any way of using a different file adapter.  So, I assume you haven't correctly configured & enabled the file adapter, and uploading with the REST API would also send the file to mongo.  Once you get the S3 adapter running correctly, you'll be okay.  Let us know if not, thanks.  https://github.com/ParsePlatform/parse-server/wiki/Configuring-File-Adapters#configuring-s3adapter

**Comment by zhouhao27** [comment]
I config my s3 based on the document. And test with the following command:

```
curl -X POST \
  -H "X-Parse-Application-Id: myAppId" \
  -H "Content-Type: text/plain" \
  -d 'Hello, World!' \
  http://localhost:1337/parse/files/hello.txt
```

It returns:

> {"url":"http://localhost:1337/parse/files/myAppId/af5480f12aeaa449a3b424d4d8386670_hello.txt","name":"af5480f12aeaa449a3b424d4d8386670_hello.txt"}

It's not in my s3 bucket. My config for the parse server:

```
var S3Adapter = require('parse-server').S3Adapter

var api = new ParseServer({
  databaseURI:  config.dbUrl,
  cloud:        __dirname + '/cloud/main.js',
  appId:        config.appId,
  masterKey:    config.masterId, 
  clientKey:    'clientKey',
  serverURL:    config.serverUrl,
  fileAdapter: new S3Adapter(
    s3config.accessKey,
    s3config.secretKey,
    s3config.bucket,
    {directAccess: true,region:s3config.region}
  ),
```

Is there any log file for this so that I can debug what's wrong with it?

**Comment by flovilmart** [comment]
Tiny weeny bug in S3 adapter it seems, can you check the value of _directAccess in your adapter? I'll be checking some things around.

**Comment by flovilmart** [comment]
What version of Parse-Server are you using? Can you open another issue on https://github.com/parse-server-modules/parse-server-s3-adapter

**Comment by zhouhao27** [comment]
@flovilmart Thanks. I'm using the parse-server 2.2.4. I tested with AWS JS SDK without problem. That means my S3 setting is correct.

**Comment by zhouhao27** [comment]
My silly mistake. **fileAdapter** should be **filesAdapter**.
