### ISSUE TITLE
where i put appid ,masterKey in project and npm start not working....so plz help me

### ISSUE THREAD

**Issue by singh7889** [ParsePlatform/parse-server#128]

**Comment by christianmarth** [comment]
Can you please provide the error message you receive when you run `npm start`

**Comment by singh7889** [comment]
DATABASE_URI not specified, falling back to localhost.

**Comment by singh7889** [comment]
e:/parse-server-master
$ npm start
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12

npm ERR! missing script: start
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     G:\parse\parse-server-master\npm-debug.log

**Comment by iulianvarzaru** [comment]
You are missing the start script from the `package.json` file:

```
"scripts": {
    "start": "node index.js"
 }
```

Or simply do `node index.js` without npm.

**Comment by singh7889** [comment]
#iulianvarzaru 
its not working...
i am using parse-server-master.

**Comment by iulianvarzaru** [comment]
Actually it's working but you have to put your application Id as a header in the request. Try:

```
curl -X POST \
  -H "X-Parse-Application-Id: myAppId" \
  -H "Content-Type: application/json" \
  -d '{"score":1337,"playerName":"Sean Plott","cheatMode":false}' \
  http://localhost:1337/parse/classes/GameScore
```

**Comment by singh7889** [comment]
#Iulianvarzaru 

DATABASE_URI not specified, falling back to localhost.
parse-server-example running on port 1337.

In browser, if I go to "localhost:1337/parse", it gives me the following error. (localhost:1337 is fine)

{"error":"unauthorized"}

And this is my API setup. I did provide databaseURI but don't know why it is complaining that it is not specified.
var api = new ParseServer({
databaseURI: 'mongodb://localhost:27017/dev',
appId: 'xxx',
masterKey: 'yyy'
});

**Comment by singh7889** [comment]
curl -X GET \
  -H "X-Parse-Application-Id: XXX" \
  -H "X-Parse-Master-Key: YYYY" \
  http://localhost:1337/parse/classes/_User

we got error :---

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0cu                                                                                                                rl: (7) Failed to connect to localhost port 1337: Connection refused

**Comment by iulianvarzaru** [comment]
`Failed to connect to localhost port 1337: Connection refused`, is mongodb running on your server ?

**Comment by singh7889** [comment]
yes

**Comment by singh7889** [comment]
Yes , I got data in cmd but in browser  {"error":"unauthorized"} ...

**Comment by iulianvarzaru** [comment]
`{"error":"unauthorized"}` is thrown only when you don't provide the header keys inside your request. If you didn't setup any other keys like restApiKey or javascriptkey you just need to include your application id in the header. Maybe post here your server file so I can look into it.

**Comment by vineetbindal** [comment]
I am getting this error too "DATABASE_URI not specified, falling back to localhost". Where do I put the damn URI. Can anyone help please?

**Comment by iulianvarzaru** [comment]
This is not an error, it just says that there is no environment variable DATABASE_URI and that it's using the url from the server file.

**Comment by vineetbindal** [comment]
I Understand. But where do I put that variable. I tried in app.json. index.js and scalingo.json. none worked. 

index.js have this 

var api = new ParseServer({
  //databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  databaseURI: databaseUri || 'mongodb://buddyreminder:Buddyreminder01231!@ds059165.mongolab.com:59165/parse_buddyreminder',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'NjTVO3LsUaJ9QW8MEUDUSs3aYhqmAWq1ErCy9fBp',
  masterKey: process.env.MASTER_KEY || 'VT2yUOUo0BcWql8fR6Hv8OmRF9vnWWMC2sOUGWgR' //Add your master key here. Keep it secret!
});

**Comment by singh7889** [comment]
#vineetbindal 
 You put aapId and masterKey in index.js file and open terminal and run npm start then u got 

DATABASE_URI not specified, falling back to localhost.
parse-server-example running on port 1337.

then open new  terminal and  write 
curl -X GET \
  -H "X-Parse-Application-Id: XXXXXXXXXXXXRyem" \
  -H "X-Parse-Master-Key: XXXXXXXXXXXXXBWA" \
  http://localhost:1337/parse/classes/Game

then u got data for Game class

**Comment by vineetbindal** [comment]
@singh7889 . I understand that. The question is how do I fix "DATABASE_URI not specified, falling back to localhost." where do I specify "DATABASE_URI" so that it wont fall back to localhost. 


I know where to put application-id and master-key. Its documented pretty well. But nowhere it has been mentioned that where to put DATABASE_URI.

**Comment by vineetbindal** [comment]
Aanyone knows where can i define these values  : 
process.env.DATABASE_URI || process.env.MONGOLAB_URI;

**Comment by drew-gross** [comment]
You put them in `databaseURI` in the place where you initialize the parse-server

```
// Specify the connection string for your mongodb database
// and the location to your Parse cloud code
var api = new ParseServer({
  databaseURI: 'mongodb://localhost:27017/dev',
  cloud: '/home/myApp/cloud/main.js', // Provide an absolute path
  appId: 'myAppId',
  masterKey: '', //Add your master key here. Keep it secret!
  fileKey: 'optionalFileKey',
  serverURL: 'http://localhost:' + port + '/parse' // Don't forget to change to https if needed
});
```

**Comment by vineetbindal** [comment]
I am a little confused between using parse-server and pare-server-example. Can anyone help Are there any step by step instructions ?

**Comment by drew-gross** [comment]
That error is because you already have the parse server running on that port. You can't run two servers on the same port. Shut down your existing server, or pick another port.

**Comment by anushajp** [comment]
@iulianvarzaru 

I agree with your point.
I did not provide the header keys inside request. I don't know where to put these keys and where is header to include the app_id. Could you please help me on this?

**Comment by sidan5** [comment]
Have same issue with the error but found out that it is connected to the remote DB server...

**Comment by sanjibnarzary** [comment]
This may be a late reply but you can resolve it by setting environment variable. In windows set the DATABASE_URI
`C:\>set DATABASE_URI=mongodb://localhost:port/yourdb`
`C:\>npm start`

In linux also you can set the environment variable as following

`$DATABASE_URI=mongodb://localhost:port/yourdb`
`$export DATABASE_URI`
`$npm start`

The same environment variables are available in `app.yaml` file in the root directory.
