### ISSUE TITLE
FileAdapter Development Question

### ISSUE THREAD

**Issue by mcclaskiem** [ParsePlatform/parse-server#1285]
FileAdapter Development

I am currently writing an adapter for RackSpace Cloud files for a project and was wondering if we can simply pass a buffer through after `createFile` is called instead making another request with `getFileData` in order to return a buffer.

**Comment by flovilmart** [comment]
You can do pretty much what you want in the adapter, as long as the test passes what's described in https://github.com/parse-server-modules/parse-server-conformance-tests


See here https://github.com/parse-server-modules/parse-server-fs-adapter/blob/master/spec/test.spec.js for an example

**Comment by mcclaskiem** [comment]
So I am trying to save an object in `classHandle` which handles the file upload fine, then it is trying a `GET` on with a random image name locally which is returning a 404 and ultimately causing a bad request on the post to save the board. Do I need to change `getFileLocation` to return the rackspace URL?

**Comment by flovilmart** [comment]
Can we move he discussion to the conformance tests as it may help other users and it's not part of this repository anymore?
