### ISSUE TITLE
Unauthorized Save Object in Cloud Code

### ISSUE THREAD

**Issue by wagnercsfilho** [ParsePlatform/parse-server#13]
Hello everyone! I am unable to save an object in cloud code . I arrive in the method, but every time I save is return "code : 141 - unauthorized " . Are there any special permission to cloud code in parse server?

my code:

```
Parse.Cloud.define("invite", function(request, response) {
    var invite= new Parse.Object("Invite");
    invite.set("phone", request.params.phonenumber);
    invite.save(null, {
        success: function(newInvite) {           
                response.success("SMS sent!");
        },
        error: function(user, error) {
            response.error("Error: " + error.code + " " + error.message);
        }
    });
});
```

**Comment by gfosco** [comment]
Yes we should update the docs for this, when using Parse as a client, you need to update the server address.. 

Parse.serverURL = "https://.....";

**Comment by wagnercsfilho** [comment]
Ok , I'm running the local server with javascript sdk client perfectly, just not working manipulate objects in local cloud code . I will wait for the update documentation.

**Comment by gfosco** [comment]
In your case, at the top of the cloud code file, try:

```js
Parse.serverURL = 'http://localhost:1337/parse';
```

**Comment by wagnercsfilho** [comment]
It's working! thank you.

**Comment by kingmatusevich** [comment]
@gfosco this can be closed now.

**Comment by jiawenzhang** [comment]
Adding Parse.serverURL = 'https://fast-badlands-XXX.herokuapp.com/parse' at the top of the cloud/main.js does not work for me. Query in cloud code always return error: unauthorized

**Comment by drew-gross** [comment]
Instead of `Parse.Cloud.useMasterKey()` you need to pass `useMasterKey: true` to each query you are making. Setting the parse server url in your cloud code file is unnecessary.

**Comment by cloudrave** [comment]
I'm using `useMasterKey: true` as a query parameter in the following manner, and I'm still getting an `unauthorized` error message.  Is there something I'm missing?  This query works when I wrap it in a `Parse.Cloud.define` function.

The following is wrapped in a `Parse.Cloud.beforeSave("StudentFieldStudent", function(request, response) {...});` call.

    var StudentFieldStudent = Parse.Object.extend('StudentFieldStudent');
    var query = new Parse.Query(StudentFieldStudent);
    query.equalTo('student', student);   // `student` here is a Parse Object
    query.first({
       useMasterKey: true,
       success: function(object) {
            if (object) {
                response.error("A StudentFieldStudent with this `student` already exists.");
            } else {
                response.success();
            }
        },
        error: function(error) {
            response.error("Could not validate uniqueness for this StudentFieldStudent object.");
            console.log(error.message);    // This prints `unauthorized`
        }
    });

**Comment by cloudrave** [comment]
Apologies.  Thought I had followed the above advice already with the `serverURL`; apparently I did not....

Setting `serverURL` with the `new ParseServer({...})` function works perfectly.

[Ref 1](https://github.com/ParsePlatform/parse-server/issues/37)
[Ref 2](https://github.com/ParsePlatform/parse-server/pull/132)

**Comment by jiawenzhang** [comment]
I have to set serverURL **AND** useMasterKey to make query to work.

**Comment by abhirocks550** [comment]
I have used Bitnami  AMI image for parse server. I am trying to access main.js functions using curl request but i am getting {"error":"unauthorized"} error.

This is my curl request 
curl -X POST \
   -H "X-Parse-Application-Id: dsd****}" \
   -H "X-Parse-REST-API-Key: sdsd***" \
   -H "Content-Type: application/json" \
   -d '{}' \
   http://baseurlofaws/parse/functions/hello

Please help.

**Comment by jaydeep82** [comment]
Hi All,

I'm also facing similar issue while trying to update the User Object.

In console log, I can only see "before save" message and then after couple of seconds it shows error.

```
Parse.Cloud.define('updateUserData',function(request,response)
{    
    //var userObjectId = request.params.userId;
    var userObjectId = "BPAJJCNdR1";

    if(userObjectId == null){
        response.error("UserId should not be null");
    }
    
    var User = Parse.Object.extend("_User");
    var userQuery = new Parse.Query(User);
    
    userQuery.equalTo('objectId',userObjectId);
    
    userQuery.first({
        useMasterKey: true, 
        
        success:function(userData){
            
            console.log("before save");
            
            userData.set("status",2);
            userData.set("verificationCode", randomNumber);
            
            userData.save(null, { useMasterKey: true });
            
            console.log("after save");

        },
        error: function(error){
            console.log(error);
            response.error(error);
        }
    });
 

});
```

In heroku log, it shows Request timeout error.

```
2016-03-10T14:15:32.212544+00:00 heroku[router]: at=info method=POST path="/parse/classes/_User" host=grubhawker-dev2.herokuapp.com request_id=508de99b-3ac7-49d7-a295-9f7f8155b473 fwd="54.81.79.238" dyno=web.1 connect=1ms service=126ms status=200 bytes=1652
2016-03-10T14:15:32.223044+00:00 app[web.1]: before save
2016-03-10T14:16:02.001309+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/parse/functions/updateUserData" host=grubhawker-dev2.herokuapp.com request_id=5efb70e5-c942-4d65-a701-fb29f03763ef fwd="123.201.104.169" dyno=web.1 connect=1ms service=30000ms status=503 bytes=0

```

I'm able to call all other cloud function.

Could you assist me here ?

Thank you in advance !!

**Comment by chadpav** [comment]
My issue was related to the 'userMasterKey' requirement.  What I didn't understand was the .save() function needs this as a second argument.
`userData.save(null, { useMasterKey: true });`
not
`userData.save({ useMasterKey: true });`

Guess I need to read the method signatures for every call.
