### ISSUE TITLE
Parse Files In Heroku

### ISSUE THREAD

**Issue by dcdspace** [ParsePlatform/parse-server#130]
If I host Parse Server on Heroku, how should I handle the files? Can I put them directly in MongoLab or should I use AWS S3? I know the Parse team is working on migrating files but for new files what is the recommended path? Thanks

**Comment by philipheinser** [comment]
@dcdspace I think S3 is better suitable for files.

**Comment by skinp** [comment]
@dcdspace when migrating object from your Parse DB to MongoLab (or any other Mongo really), the file objects will continue to point to files hosted on Parse. We're working on tooling for migrating those files to a destination of your choice.

For now, new files will be written directly to your new Mongo DB (MongoLab). PR #113 adds support for storing those files in S3. This will be the recommended way of dealing with files for anything other than a dev app.

**Comment by gfosco** [comment]
Follow along in #113 and we'll be updating the docs after it lands.  S3 will definitely be recommended, and I'd like to see alternatives too.
