### ISSUE TITLE
What is the purpose of oauth?

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/parse-server#1300]
I thought **oauth** could be used for function like "Login with FB" etc. Is this true?

By looking through the source code of facebook.js, it seems to be used for **graphRequest** which is for logged in user. But where is the code to login? Or I misunderstand the function of **oauth**?

I know **oauth** will get the access token. But to get the access token, we need to login first, am I right?

**Comment by flovilmart** [comment]
The purpose is to provide alternate methods of authentication. OAuth is the primary target, but it can as well be something else. Anonymous is a good example. You could also implement Digits through that method.

The authentication credentials have to be** acquired by the client** and sent to the server. parse-server then validates that it supports that authentication method by looking in the oauth configuration and can perform **additional validation**, as checking that the access token is valid.

This implementation is intended to be lightweight and not provide the complex flow of server-side oauth authentication that required URL redirects etc... 


This is how you would setup parse-server for a custom authentication provider.

the provider has to implement: `validateAuthData(authData)` and return a Promise that resolves if the authData is valid.

On the client:

Acquire auth data for that provider and put it in a hash.
Use the linking/login features from the client SDK or the REST API to send to the server your hash:
```
{
authData: {
 myauth: {
   key: value,
   token: token,
  something: else,
  id: uniqueId // important, the ID in your auth system for late retrieval
 }
}
}
```

Upon reception, the server will lookup in it's configuration or the default providers for an oauth provider name `myauth`. Then will pass the content of `authData.myauth` to the `validateAuthData` function defined by your provider.

If the validation passes, the user can now login with this auth data

**Comment by oallouch** [comment]
To get the access token, you do it client-side using a lib, like [hello.js](https://adodson.com/hello.js/).
The only norm you have to respect is the object format, @flovilmart has just given you, that you pass to Parse.User.logInWith (for the js sdk).

**Comment by zhouhao27** [comment]
@oallouch So all the authentication will still be done in client side? Then the token will be passed to parse-server? The **oauth** is only used to attach the token to parse user. Am I right? Thanks.
