### ISSUE TITLE
Size of repo is shown empty, even after successfully deploying the Parse-Server-Example on Heroku

### ISSUE THREAD

**Issue by lovishdogra** [ParsePlatform/parse-server#1304]
I have depolyed the Parse-Server-Example to the heroku directly through the github and it is successfully deployed, but my Heroku App dashboard shows that the repo size is 0. Don't know why this is happening. I am attaching the screenshots.

<img width="511" alt="screen shot 2016-03-31 at 9 09 43 pm" src="https://cloud.githubusercontent.com/assets/5437942/14181802/39816ea8-f786-11e5-86ff-339f16a8b603.png">

<img width="470" alt="screen shot 2016-03-31 at 9 20 43 pm" src="https://cloud.githubusercontent.com/assets/5437942/14181882/925fc8bc-f786-11e5-9b6d-01c5d625cf69.png">

**Comment by drew-gross** [comment]
Does the server work? If so, this is probably a bug in Heroku. Either way, we can't support Heroku specific issue here.

**Comment by emrekhan** [comment]
Hi, i have same issue. Could you help me ? Thank you.

**Comment by lovishdogra** [comment]
@emrekhan 
You can handle this in another way using Heroku's Toolbelt. I made a contact to Heroku support regarding this but they are unable to resolve this.
Initially, I copy the repo in my mac.
Then, using Heroku's Toolbelt I create a new application and then push this repo to that new application.

**Comment by plaudev** [comment]
@lovishdogra, thank you for responding to @emrekhan which led me to finally getting my parse server set up on heroku!
