### ISSUE TITLE
Parse Server on Heroku logs many "H28 Client Connection Idle" warnings

### ISSUE THREAD

**Issue by mtrezza** [ParsePlatform/parse-server#1307]
With Parse Server deployed on Heroku I see quite a few warnings from the Heroku router: `H28 Client Connection Idle`. The server is the API endpoint for an iOS app.

According to Heroku [docs](https://devcenter.heroku.com/articles/error-codes#h28-client-connection-idle) this warning occurs when:

> The client did not send a full request and was terminated due to 55 seconds of inactivity. For example, the client indicated a Content-Length of 50 bytes which were not sent in time.

Can this possibly be an issue with the Parse iOS SDK?
Has anyone else experienced this?

**Update**:
I was able to track this down to a single request type to a specific class. So I guess this is just something in the app logic. I will further investigate this and update here.

**Comment by mtrezza** [comment]
Cause seemed to be a performance issue. Upscaled the dynos in Heroku and reduced the number of H28s.

**Comment by alexblack** [comment]
Hi @mtrezza, we're seeing this too and wondered if you had any more insights to share.

**Comment by mtrezza** [comment]
Hi @alexblack, I can't remember anymore but I'd first check cloud code, maybe even remove cloud code and see if you still have these errors.

**Comment by woodardj** [comment]
Hey @mtrezza — any chance you can elaborate? We see a lot of these as well, do you mean that the quantity of Cloud Code functions you have is causing issues? Or just disabling it altogether?

**Comment by mtrezza** [comment]
@woodardj all I found what it seemed to be a performance related issue. Upscaling the dynos in Heroku reduced the number of H28s.
