### ISSUE TITLE
Invalid File URL

### ISSUE THREAD

**Issue by kilabyte** [ParsePlatform/parse-server#1308]
After migration if i add a file via the upload on my instance of the parse dashboard it uploads successfully however the url it generates when i click on the file points to the localhost and not the api endpoint url. All my server urls configs in parse-server and in parse-dashboard DO NOT point to the localhost and point to the absolute api endpoint. The end of the url for the file location is correct. Below is the screen shot of the url and of course there is an error since safari can't resolve localhost on a remote machine.
![5202a390-f5a9-11e5-82cd-da5c4ddfab35](https://cloud.githubusercontent.com/assets/487948/14185105/3b399b7a-f72d-11e5-959b-a010fdd71388.png)

Tried it on a heroku (parse-server) install and still the same issue. Any ideas?

**Comment by flovilmart** [comment]
in that case please wait till 2.2.5 as it's gonna be fixed by #1287

**Comment by kilabyte** [comment]
Updated to 2.2.6 and still the same issue...

**Comment by drew-gross** [comment]
You'll also need to set your `publicServerURL`, can you check that setting and see if it works?

**Comment by kilabyte** [comment]
Working now. Thanks! The documentation wasn't clear as that option was under the email verification and password reset section and nothing in the file handling wiki or section
