### ISSUE TITLE
Local CloudCode server URL

### ISSUE THREAD

**Issue by r4zzz4k** [ParsePlatform/parse-server#131]
Seems like all Parse actions done within Cloud Code are against Parse.com apps and not against local Parse Server. When I started trying out Parse Server I've set all keys to corresponding keys of my Parse.com app. Now I've got 155 error in my trigger, which should not be happening as I don't see anything within parse-server repo to throw it. So looks like it was communicating with Parse.com. When I changed all keys to random string I started getting I/O errors in Android app.

Here is the code in `index.js`:
```js
// Initialize the node client SDK automatically
Parse.initialize(args.appId, args.javascriptKey || '', args.masterKey);
```

I wasn't able to find any way to provide server url in JS SDK. Am I missing something? Anyway, JS SDK initialized with Parse Server should probably be connected to localhost.

**Comment by gfosco** [comment]
Follow on in #132.
