### ISSUE TITLE
The default settings will override user settings

### ISSUE THREAD

**Issue by zqqq** [ParsePlatform/parse-server#1319]
`master/src/cli/parse-server.js` line 54

`options = Object.keys(definitions).reduce(function (options, key) {
  if (typeof program[key] !== 'undefined') {
    options[key] = program[key];
  }
  return options;
}, options);
`

E.g`"mountPath": "/mymountPath",`

`typeof program[key]` is defalut `/parse`

`options = Object.keys(definitions).reduce(function (options, key) {
  if (typeof program[key] !== 'undefined' &&  typeof options[key] == 'undefined') {
    options[key] = program[key];
  }
  return options;
}, options);`

**Comment by flovilmart** [comment]
I'll have a look! Thanks
