### ISSUE TITLE
Add a bit more precise doc on Push Notification Wiki

### ISSUE THREAD

**Issue by lolobosse** [ParsePlatform/parse-server#1320]
I lost half an hour with that because I didn't know how to put this `useMasterKey: true`, could be cool to update the docs with the #401 response of @gfosco ([here] (https://github.com/ParsePlatform/parse-server/issues/401#issuecomment-183767065)). 

**Something like this:**

```js
Parse.Push.send({
  where: query,
  data: {
    alert: 'Test',
    badge: 1,
    sound: 'default'
  }
}, {
  success: function() {
    console.log('##### PUSH OK');
  },
  error: function(error) {
    console.log('##### PUSH ERROR');
  },
  useMasterKey: true
});
```

**Instead of:**

```js
Parse.Push.send({
  where: { ... },
  data: { ... }
}, { useMasterKey: true });
```

Putting it [there](https://github.com/ParsePlatform/parse-server/wiki/Push#4-send-push-notifications) would be very cool! :smile:

**Comment by davimacedo** [comment]
Maybe it would be also good add an example of cloud code function to send push notifications. I have been indicating the one below to the guys who ask me one:
https://gist.github.com/brunopicinin/ac38aef5665aa3208c35

**Comment by flovilmart** [comment]
@lolobosse you should not use the old backbone style success, error callback but promises...

**Comment by lolobosse** [comment]
@flovilmart I'm ready to use anything as long as it is indicated in the docs :wink:

**Comment by drew-gross** [comment]
Done! Thanks for the suggestion!
