### ISSUE TITLE
Migration without revocable sessions

### ISSUE THREAD

**Issue by arturogutierrez** [ParsePlatform/parse-server#1322]
Hi there,

I know Parse-Server has **no support** for legacy sessions but I have a question, can I migrate **only my database** meanwhile I keep turned off the `Enable Revocable Sessions` in _Parse.com_? This way I will have more time to migrate my users to revocable sessions and, eventually, turn off the switch before to move to Parse-Server.

Thanks in advance

**Comment by drew-gross** [comment]
Yep, if you migrate your database to an external service, all requests to `api.parse.com` will be directed to your external database, which is still running the same codebase that supports lagacy sessions. This will give you  more time to migrate you app server.
