### ISSUE TITLE
Troubleshooting issues with sse4_crc32

### ISSUE THREAD

**Issue by flovilmart** [ParsePlatform/parse-server#1331]
We're going on trying to troubleshoot the issues with sse4_crc32 (a dependency injected by parse-server-gcd-adapter and gcloud)

from: https://github.com/GoogleCloudPlatform/gcloud-node/issues/1197#issuecomment-204638692

If you face issues deploying your code, and that this module seems to be the culplrit, please upload your npm-debug.log or any relevant stack trace.

Please also include the version of parse-server you're deploying as well as your server configuration, distribution etc...

Thanks!

**Comment by flovilmart** [comment]
@anandsuresh AWS Elastic Beanstalk, AMI 2016 
```
uname -r
4.1.17-22.30.amzn1.x86_64
```

https://gist.github.com/flovilmart/3bcb096ef70e28a71d62c49904e393e6

**Comment by flovilmart** [comment]
http://stackoverflow.com/questions/34084814/npm-error-when-deploying-nodejs-to-elastic-beanstalk

**Comment by anandsuresh** [comment]
@flovilmart I'm not well-versed with AWS or Amazon's offerings. Tried googling but couldn't find much on any free/OSS offerings for Elastic Beanstalk. I'm looking for a way to spin up an instance and dig deeper into the build process logs. Any suggestions/links that would point me in the right direction would be super helpful.

**Comment by flovilmart** [comment]
@anandsuresh somewhat this was related to that: https://github.com/ParsePlatform/parse-server/issues/1276

Seems that the issue at hands is not the package or anything but a memory pressure problem.

**Comment by anandsuresh** [comment]
@flovilmart Looking at the logs in that thread, it seems that the SSE4_CRC32 module is building successfully:
```
    CXX(target) Release/obj.target/crc32c_sse42/src/crc32c_sse42.o
    AR(target) Release/obj.target/crc32c_sse42.a
    COPY Release/crc32c_sse42.a
    CXX(target) Release/obj.target/sse4_crc32/src/crc32c.o
    SOLINK_MODULE(target) Release/obj.target/sse4_crc32.node
    COPY Release/sse4_crc32.node
  make: Leaving directory `/tmp/deployment/application/node_modules/parse-server/node_modules/parse-server-gcs-adapter/node_modules/gcloud/node_modules/hash-stream-validation/node_modules/fast-crc32c/node_modules/sse4_crc32/build'
```

However, the gist you posted seems to fail on SSE4_CRC32.

Also, very surprising that it is running into memory pressure on a machine with a gig of RAM, but if there is orchestration involved, then I can see that might be an issue. 

At this point, I'm going to go ahead and consider this issue resolved, unless you find something otherwise. Please feel free to shoot me an email/open an issue if you find something else.

**Comment by flovilmart** [comment]
Yeah that was my feeling too. We've seen high memory pressure during the build. So that don't seem to be related to your package. Thanks again for your time!

**Comment by drew-gross** [comment]
We are going to remove the GCS adapter from the repo, which will solve the issue for anyone not using the GCS adapter.
