### ISSUE TITLE
How to view backend on self hosted?

### ISSUE THREAD

**Issue by ViolentCrumble** [ParsePlatform/parse-server#1332]
Hi guys, The whole point of using parse was to have a simple backend to view and add data aswell as everything else.

So it's great that i was able to easily setup a parse server to heroku. but now how do i view that data?
I setup the example, , but how can i easily use the backend to make a new class? or quickly see if a command i just used worked...

I saw in a post they said i can still use the parse backend with my self hosted db, but no one has mentioned how?

**Comment by robert-wallis** [comment]
Parse Dashboard let's you have a view into your data https://github.com/ParsePlatform/parse-dashboard

And it's getting better very quickly.

**Comment by benitech** [comment]
you could also try the adminca.com dashboard for even easier setup, though it doesn't support push notifications yet.

**Comment by flovilmart** [comment]
Both answers are great! Closing now! :tada:
