### ISSUE TITLE
PFPurchase / In-App-Purchase Validation

### ISSUE THREAD

**Issue by Morbix** [ParsePlatform/parse-server#134]
The class PFPurchase from the client SDKs will keep working without the hosted Parse?

**Comment by gfosco** [comment]
In-app purchase validation is not implemented in parse-server and may reject activity to _Purchase entirely.  Open to reviewing any changes to this current behavior.

**Comment by Morbix** [comment]
@gfosco I am concern about the features, apparently, without remote connections like:
- addObserverForProduct:block:
- buyProduct:block:
- restore

I imagine that them will keep working even without a Parse Server running, right?

**Comment by gfosco** [comment]
I think this needs to be tested, as I'm not familiar with the inner workings of this area.  If those are just for contacting iTunes for IAP, and they don't involve API endpoints on Parse, then it should work... but the _Product table and PFPurchase functionality was explicitly not part of initial development for parse-server.

**Comment by nlutsenko** [comment]
As @gfosco said, the server side functionality to support `_Product` and `PFPurchase` as a result was not included in the initial development for parse-server.
This means that we can add this, it's more a question of priority at this point.

Apple API for validation of in-app-purchases is pretty lightweight and I bet there is a node module that already does it, so the implementation shouldn't take too long.

**Comment by flovilmart** [comment]
@nlutsenko, I could take care of that, I looked through the iOS code, but didn't see any validation process going on client side from the SDK, I guess it was all internal. Could you draft a quick spec on the inner workings of _Purchase or I could R/E from the SDK and current behaviors

**Comment by nlutsenko** [comment]
Will do the spec next week, sounds good...
In the meantime, so you are not blocked, take a look at `PFPurchase`/`PFProduct` and `PFPurchaseController`, that should give you an idea of what is going on.

**Comment by flovilmart** [comment]
Thanks!

**Comment by flovilmart** [comment]
so basically to be implemented it the server counterpart of:

```
NSDictionary *params = [[PFEncoder objectEncoder] encodeObject:@{ @"receipt" : appStoreReceipt,
                                                                      @"productIdentifier" : productIdentifier }];
    PFRESTCommand *command = [PFRESTCommand commandWithHTTPPath:@"validate_purchase"
                                                     httpMethod:PFHTTPRequestMethodPOST
                                                     parameters:params
                                                   sessionToken:sessionToken];

```

**Comment by flovilmart** [comment]
@nlutsenko I believe parse didn't do validation on iOS 6 auto renewable receipts as I don,t recall any setting for the `shared secret`  https://developer.apple.com/library/ios/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html#//apple_ref/doc/uid/TP40010573-CH104-SW1

The default validation is on the production servers, then if it returns a code 

`21007
This receipt is from the test environment, but it was sent to the production environment for verification.`

I send it to the sandbox. It creates a little overhead when testing but will prevent misconfiguration.

**Comment by gfosco** [comment]
Follow on in #515.. Brilliant work by @flovilmart

**Comment by valeryvoskobovich** [comment]
Hi all! I'm using the latest parse-server 2.2.15 on Heroku and I have some issues with in-app purchases validation. I assume the problem is related to file downloading after verifying purchase. S3 Adapter and fileKey are configured correctly for my instance. I see the following in heroku console: 

`at=error code=H12 desc="Request timeout" method=POST path="/parse/validate_purchase" host=mytestapp.herokuapp.com request_id=3d2ed6f9-d18b-4b8d-a8a2-addb60afe45c fwd="93.84.7.35" dyno=web.1 connect=0ms service=30257ms status=503 bytes=0
`

Response string in _taskDidFinish (PFURLSessionJSONDataTaskDelegate class) looks like this:

`<!DOCTYPE html>
    <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style type="text/css">
        html, body, iframe { margin: 0; padding: 0; height: 100%; }
        iframe { display: block; width: 100%; border: none; }
      </style>
    <title>Application Error</title>
    </head>
    <body>
      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">
        <p>Application Error</p>
      </iframe>
    </body>
    </html>`


Is anybody experiencing the same problem?
