### ISSUE TITLE
Email isn't set as username on signup

### ISSUE THREAD

**Issue by meilers** [ParsePlatform/parse-server#1340]
I'm running the latest Parse-Server (2.1.6) and Parse (1.6.12) on my AWS EB instance. I noticed that when the user signs up via the iOS or Android clients with signUpInBackground, the user's username becomes a random string (e.g. "username": "52927b5594f76b391cc6fbdcbe2da63c"), even though I set the user's username to be the email. 

Therefore, user's can't relogin because their email isn't associated to their username.

Here's a snippet of the Android code:

```
        ParseUser user = new ParseUser();

        if( ParseAnonymousUtils.isLinked(ParseUser.getCurrentUser()) ) {
            user = ParseUser.getCurrentUser();               // Sign Up current anonymous user
        }

        user.setUsername(email);
        user.setPassword(password);
        user.setEmail(email);
        user.put("firstName", firstName);
        user.put("lastName", lastName);

        user.signUpInBackground(new SignUpCallback() {
            public void done(ParseException e) {
                if (e == null) {
                    saveInstallation(new SaveCallback() {
                        @Override
                        public void done(ParseException e) {

                            if( callback != null ) {
                                callback.onSuccess();
                            }
                        }
                    });
                } else {
                    // Sign up didn't succeed. Look at the ParseException
                    // to figure out what went wrong
                    if( callback != null ) {
                        callback.onFailure(e.getMessage());
                    }
                }
            }
        });
```

Any ideas on why this is happening? Thanks!

**Comment by flovilmart** [comment]
The latest parse server is 2.2.4 ;) can you update and see if the issue is still here?

**Comment by meilers** [comment]
@flovilmart Sorry for the delay. Yes, I finally managed to update to 2.2.4 on AWS can I still see the same issue. The username is still generated and isn't given the email value I give it at sign up, both on iOS and Android.

**Comment by flovilmart** [comment]
Ok that's annoying, I'll have a look before next week

**Comment by meilers** [comment]
Ok thanks. I'll be downgrading to 2.0 in the meantime, because it's pretty critical to me that users can't log back in.

**Comment by flovilmart** [comment]
That's very very odd as this is properly covered by unit tests [here](https://github.com/ParsePlatform/parse-server/blob/master/spec/ParseUser.spec.js#L77).

Can you run the server with environment var `VERBOSE=1` and let us know the trace of requests/responses upon signup?

**Comment by meilers** [comment]
Here it is. Here are the headers for the request:

![screen shot 2016-04-03 at 1 27 11 pm](https://cloud.githubusercontent.com/assets/2792041/14233790/1c79d73e-f9a0-11e5-8b79-3392aa3d08e9.png)

And the JSON payload:
![screen shot 2016-04-03 at 1 27 19 pm](https://cloud.githubusercontent.com/assets/2792041/14233791/26aff5bc-f9a0-11e5-9d16-b5301ea63b2c.png)

And here are the headers for the response:

![screen shot 2016-04-03 at 1 27 26 pm](https://cloud.githubusercontent.com/assets/2792041/14233792/2f87fca2-f9a0-11e5-8d08-21061a77cb86.png)

And JSON:

![screen shot 2016-04-03 at 1 27 33 pm](https://cloud.githubusercontent.com/assets/2792041/14233793/367aeb3c-f9a0-11e5-98bf-7c1370f6cbd3.png)

**Comment by meilers** [comment]
Here is is. Here are the headers for sign up:

![1q](https://cloud.githubusercontent.com/assets/2792041/14233823/13d86e6e-f9a1-11e5-9071-8f8cd99d3524.png)

With JSON payload:
![screen shot 2016-04-03 at 1 24 48 pm](https://cloud.githubusercontent.com/assets/2792041/14233826/1ff1d3d4-f9a1-11e5-8102-7275d901dea7.png)

Here are the response headers:
![screen shot 2016-04-03 at 1 25 10 pm](https://cloud.githubusercontent.com/assets/2792041/14233828/2d08d892-f9a1-11e5-8e0d-4060c35607ef.png)

With JSON:
![screen shot 2016-04-03 at 1 25 30 pm](https://cloud.githubusercontent.com/assets/2792041/14233829/331764ba-f9a1-11e5-8c66-8db324bb7cab.png)

Now, when I do a login, right after (in between the user gets logged in anonymously because I log out), here is the request:
![1x](https://cloud.githubusercontent.com/assets/2792041/14233836/5908b6e2-f9a1-11e5-915d-01af4d435ff2.jpg)

With JSON:
![screen shot 2016-04-03 at 1 27 19 pm](https://cloud.githubusercontent.com/assets/2792041/14233837/5e7e119e-f9a1-11e5-822c-5dc00af28c79.png


And response:

![screen shot 2016-04-03 at 1 27 26 pm](https://cloud.githubusercontent.com/assets/2792041/14233843/83830e36-f9a1-11e5-944f-d7d4ba61a87d.png)

With JSON:
![screen shot 2016-04-03 at 1 27 33 pm](https://cloud.githubusercontent.com/assets/2792041/14233845/8804d44e-f9a1-11e5-8ae0-c66fe2031d95.png)

**Comment by flovilmart** [comment]
What does it look like in mongodb?

**Comment by meilers** [comment]
{
    "_id": "DpYUKuoTqx",
    "_rperm": [
        "DpYUKuoTqx",
        "*"
    ],
    "_wperm": [
        "DpYUKuoTqx"
    ],
    "username": "cf421f4bac640e6cdd582f036beee972",
    "_updated_at": {
        "$date": "2016-04-03T17:22:55.860Z"
    },
    "_created_at": {
        "$date": "2016-04-03T17:20:35.054Z"
    },
    "_auth_data_anonymous": null,
    "lastName": "Test",
    "firstName": "Test",
    "email": "test16@test.com",
    "_hashed_password": "$2a$10$usYnVR.Pn/A7Nc5ZPzpReOGfDTNUUwH9/FfKZh1XWRyD5Rjlh7FaG"
}

**Comment by flovilmart** [comment]
alright thx!

**Comment by flovilmart** [comment]
Do you have a beforeSave on _User?

**Comment by meilers** [comment]
No - should I?

**Comment by flovilmart** [comment]
nope, just to scratch out potential problems

**Comment by meilers** [comment]
Hmmm... I just noticed I do a saveEventually when I login anonymously (before sign up):

```
ParseAnonymousUtils.logIn(new LogInCallback() {
            @Override
            public void done(ParseUser user, ParseException e) {
                if (e == null) {
                    user.saveEventually();
                    saveInstallation(new SaveCallback() {
                        @Override
                        public void done(ParseException e) {
                    });
                } else {
                    // Sign up didn't succeed. Look at the ParseException
                    // to figure out what went wrong
                }
            }
        });
```

Could that be a problem?

**Comment by flovilmart** [comment]
yeah, that may be related as you may introduce a race condition here... ParseAnonymousUtils.logIn will save your user anyway

**Comment by meilers** [comment]
Weird it's working on older versions of Parse-Server though

**Comment by flovilmart** [comment]
we changed a few things over time, and may have introduce a problem. can you run your server with VERBOSE=1 so we have all the logs?

**Comment by meilers** [comment]
Yeah - AWS Beanstalk is slow today. I'm requesting the logs as we speak.

**Comment by flovilmart** [comment]
use `eb ssh`

**Comment by meilers** [comment]
ok i'm in with ssh. Where can I find the logs?

**Comment by flovilmart** [comment]
http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.logging.html

**Comment by meilers** [comment]
got it.

PUT /parse/classes/_User/DpYUKuoTqx { host: 'parse-server-birder.elasticbeanstalk.com',
  'x-real-ip': '10.164.111.163',
  'x-forwarded-for': '24.203.158.119, 10.164.111.163',
  'content-length': '165',
  'accept-encoding': 'gzip',
  'content-type': 'application/json',
  'user-agent': 'Parse Android SDK 1.13.0 (com.sobremesa.birdwatching/36) API Level 23',
  'x-parse-app-build-version': '36',
  'x-parse-app-display-version': '1.7',
  'x-parse-application-id': 'rGVFrDnJI3H4t1BqJg85Zn9zSkz7er5SRM8Ztwem',
  'x-parse-client-key': '6qtD4DAsITUEOCSdkVd50lYMj8NU536979hVrQcw',
  'x-parse-client-version': 'a1.13.0',
  'x-parse-installation-id': '6fffc9ca-eeca-4b3b-82b9-e8a70987f1db',
  'x-parse-os-version': '6.0.1',
  'x-parse-session-token': 'r:a9a539a5979e05f959fe6f28454a131d',
  'x-forwarded-port': '80',
  'x-forwarded-proto': 'http' } {
  "lastName": "Test",
  "firstName": "Test",
  "email": "test16@test.com",
  "password": "test",
  "username": "test16@test.com",
  "authData": {
    "anonymous": null
  },
  "objectId": "DpYUKuoTqx"
}
response: {
  "response": {
    "updatedAt": "2016-04-03T17:22:55.860Z"
  }
}

**Comment by meilers** [comment]
PUT /parse/classes/_User/DpYUKuoTqx { host: 'parse-server-birder.elasticbeanstalk.com',
  'x-real-ip': '10.164.111.163',
  'x-forwarded-for': '24.203.158.119, 10.164.111.163',
  'content-length': '165',
  'accept-encoding': 'gzip',
  'content-type': 'application/json',
  'user-agent': 'Parse Android SDK 1.13.0 (com.sobremesa.birdwatching/36) API Level 23',
  'x-parse-app-build-version': '36',
  'x-parse-app-display-version': '1.7',
  'x-parse-application-id': 'xxxxxxxxxxxxx',
  'x-parse-client-key': 'xxxxxxxxxxxxx',
  'x-parse-client-version': 'a1.13.0',
  'x-parse-installation-id': '6fffc9ca-eeca-4b3b-82b9-e8a70987f1db',
  'x-parse-os-version': '6.0.1',
  'x-parse-session-token': 'r:a9a539a5979e05f959fe6f28454a131d',
  'x-forwarded-port': '80',
  'x-forwarded-proto': 'http' } {
  "lastName": "Test",
  "firstName": "Test",
  "email": "test16@test.com",
  "password": "test",
  "username": "test16@test.com",
  "authData": {
    "anonymous": null
  },
  "objectId": "DpYUKuoTqx"
}
response: {
  "response": {
    "updatedAt": "2016-04-03T17:22:55.860Z"
  }
}

**Comment by meilers** [comment]
hmmm is verbose not working?

**Comment by flovilmart** [comment]
no calls before or after? this is what you get with VERBOSE

**Comment by meilers** [comment]
This what I have just before...
PUT /parse/classes/_Installation/YtmhOeQ1JO { host: 'parse-server-birder.elasticbeanstalk.com',
  'x-real-ip': '10.164.111.163',
  'x-forwarded-for': '24.203.158.119, 10.164.111.163',
  'content-length': '119',
  'accept-encoding': 'gzip',
  'content-type': 'application/json',
  'user-agent': 'Parse Android SDK 1.13.0 (com.sobremesa.birdwatching/36) API Level 23',
  'x-parse-app-build-version': '36',
  'x-parse-app-display-version': '1.7',
  'x-parse-application-id': 'xxxxxxxxx',
  'x-parse-client-key': 'xxxxxxxxx',
  'x-parse-client-version': 'a1.13.0',
  'x-parse-installation-id': '6fffc9ca-eeca-4b3b-82b9-e8a70987f1db',
  'x-parse-os-version': '6.0.1',
  'x-parse-session-token': 'r:a9a539a5979e05f959fe6f28454a131d',
  'x-forwarded-port': '80',
  'x-forwarded-proto': 'http' } {
  "userId": "DpYUKuoTqx",
  "user": {
    "__type": "Pointer",
    "className": "_User",
    "objectId": "DpYUKuoTqx"
  },
  "objectId": "YtmhOeQ1JO"
}
response: {
  "response": {
    "updatedAt": "2016-04-03T17:22:56.723Z"
  }
}

**Comment by flovilmart** [comment]
ok so if there is no other call on _User/DpYUKuoTqx that's really odd

**Comment by meilers** [comment]
Just noticed this. When I logout after signing up, and log in anonymously, it returns the same _User/DpYUKuoTqx:

error: ParseError { code: 101, message: 'Invalid username/password.' }
POST /parse/users { host: 'parse-server-birder.elasticbeanstalk.com',
  'x-real-ip': '10.164.111.163',
  'x-forwarded-for': '24.203.158.119, 10.164.111.163',
  'content-length': '72',
  'accept-encoding': 'gzip',
  'content-type': 'application/json',
  'user-agent': 'Parse Android SDK 1.13.0 (com.sobremesa.birdwatching/36) API Level 23',
  'x-parse-app-build-version': '36',
  'x-parse-app-display-version': '1.7',
  'x-parse-application-id': 'xxxxxxxx',
  'x-parse-client-key': 'xxxx',
  'x-parse-client-version': 'a1.13.0',
  'x-parse-installation-id': '6fffc9ca-eeca-4b3b-82b9-e8a70987f1db',
  'x-parse-os-version': '6.0.1',
  'x-forwarded-port': '80',
  'x-forwarded-proto': 'http' } {
  "authData": {
    "anonymous": {
      "id": "aaf2bbf0-a113-49b4-bbd2-a75f65ca54e5"
    }
  }
}
response: {
  "status": 201,
  "response": {
    "objectId": "DpYUKuoTqx",
    "createdAt": "2016-04-03T17:20:35.054Z",
    "sessionToken": "r:a9a539a5979e05f959fe6f28454a131d"
  },
  "location": "http://parse-server-birder.elasticbeanstalk.com/parse/users/DpYUKuoTqx"
}

Right after, there's the log in call that fails:

GET /parse/login { host: 'parse-server-birder.elasticbeanstalk.com',
  'x-real-ip': '10.164.111.163',
  'x-forwarded-for': '24.203.158.119, 10.164.111.163',
  'content-length': '64',
  'accept-encoding': 'gzip',
  'content-type': 'application/json',
  'user-agent': 'Parse Android SDK 1.13.0 (com.sobremesa.birdwatching/36) API Level 23',
  'x-parse-app-build-version': '36',
  'x-parse-app-display-version': '1.7',
  'x-parse-application-id': 'xxxxx',
  'x-parse-client-key': 'xxxxx',
  'x-parse-client-version': 'a1.13.0',
  'x-parse-installation-id': 'fd1c71a3-d441-47f3-a5d3-8accadd54cf7',
  'x-parse-os-version': '6.0',
  'x-forwarded-port': '80',
  'x-forwarded-proto': 'http' } {
  "username": "test15@test.com",
  "password": "test"
}

**Comment by flovilmart** [comment]
it's very odd that ```"anonymous": {
"id": "aaf2bbf0-a113-49b4-bbd2-a75f65ca54e5"
}``` returns your user.

**Comment by meilers** [comment]
Have you tested on your side? I tried with Parse-Server 2.2.4, and 2.1.6, and still the same issue. I also removed the "saveEventually", but it didn't help.

**Comment by meilers** [comment]
So I just tried deploying the app on Heroku instead of AWS... and now it works. SO INFURIATING. I have no idea why it had that behaviour on AWS. Sorry for wasting your time, and a huge thank you for your contribution to Parse. :)

**Comment by flovilmart** [comment]
no problem! here to help. That's odd what's happening on AWS. But if you can stick to heroku, you'll be better off for now, Elastic Beanstalk is not that *easy* to manage. ;)
