### ISSUE TITLE
Can't connect to remote parse server on iOS (local works)

### ISSUE THREAD

**Issue by markuswinkler** [ParsePlatform/parse-server#1341]
I have a rather strange issue, I can perfectly fine connect to my local parse-server instance but not to the remote one on iOS.
I always get this error upon facebook login:
```
[Error]: {
    code = 100;
    message = "XMLHttpRequest failed: \"Unable to connect to the Parse API\"";
} (Code: 141, Version: 1.13.0)
```

This are my connection settings, first one always works, second one always fails:
```
if SystemSettings.instance.localServer {
     let configuration = ParseClientConfiguration {
            $0.applicationId = ParseID
            $0.clientKey = ParseKey
            $0.server = "http://10.0.1.30:1337/parse"
     }
     Parse.initializeWithConfiguration(configuration)
} else {
     let configuration = ParseClientConfiguration {
            $0.applicationId = ParseID
            $0.clientKey = ParseKey
            $0.server = "http://xxxxxxxxxx.us-east-1.elasticbeanstalk.com/parse"
     }
    Parse.initializeWithConfiguration(configuration)
}           
```
Note: doesn't matter if the url ends with "parse/" or "parse".
Note 2: The elastic beanstalk environment is an exact mirror of the local installation.
Note 3: serverURL is set on both

To add insult to injury, parse dashboard works perfectly fine for BOTH settings.
A cURL test call also works perfectly fine.
This is really odd.

**Comment by flovilmart** [comment]
Can you access the API through CURL?

**Comment by markuswinkler** [comment]
Yes

**Comment by flovilmart** [comment]
Sorry, I just noticed you wrote that already. that's only affecting the Facebook login right? all other calls are working properly?

**Comment by markuswinkler** [comment]
well, I can't make any other call from inside the iOS without logging in first.

**Comment by flovilmart** [comment]
alright, that's odd indeed... Can you run the server in verbose? setting VERBOSE=1 and see if the call gets to it. Otherwise that may indicate a problem in the iOS SDK

**Comment by markuswinkler** [comment]
what's the cURL equivalent of that call? I think it really is a iOS issue since dashboard connects fine and I can do everything (modify entries and such).

**Comment by flovilmart** [comment]
Check the REST documentation here: https://www.parse.com/docs/rest/guide#users-linking-users

**Comment by markuswinkler** [comment]
Yes, that worked, returned the full user. Really strange.

**Comment by markuswinkler** [comment]
I was able to track it down a little bit further via
http://blog.parse.com/announcements/parse-debugging-tools-identify-client-side-issues-faster/

It's weird from the start.
e.g. the automatic parse query for installations at the beginning
`http://localhost:1337/parse/classes/_Installation`
works in iOS on localhost, fails right away on remote with error 400 before even logging in.
and if make the same call to the remote server via cURL it works.

Very simple test cloud functions that work on localhost and via cURL fail to execute on remote (internal server error).

**Comment by flovilmart** [comment]
Can your provide the server VERBOSE logs?

**Comment by markuswinkler** [comment]
**FOUND IT!!!!**
Elastic beanstalk uses a nginx reverse proxy to access parse. changing the server_url from
`http://localhost:1337/parse`
to
`http://localhost/parse`
did the trick!

That also explains why direct cURL calls worked and cloud code functions didn't.
The cloud code functions tried to query additional data from the sever and the internal requests always timed out since it couldn't reach the server, hence the weird errors.

**Comment by flovilmart** [comment]
alright :) nice!

**Comment by farshadj** [comment]
Nice. Changing http://localhost:1337/parse to http://localhost/parse did the trick.
