### ISSUE TITLE
Issue in the Migration process : "No reachable servers"

### ISSUE THREAD

**Issue by HamzaLJ** [ParsePlatform/parse-server#1345]
I've configured everything to migrate Parse to my own dedicated server, Parse-Server is running fine, Mongo-DB as well.
The only issue I am facing is that I receive an error in parse dashboard while trying to migrate "No reachable servers", it appears while trying to connect with the below link:

`mongodb://user:pass@5.5.5.12/appName`

Any ideas about what's happening?

**Comment by flovilmart** [comment]
Hi @HamzaLJ,

As this issue seems to be related to the migration process, I suggest you reach out to parse directly through their help page.

http://parse.com/help

Thanks!
