### ISSUE TITLE
remove optional adapters from default dependencies 

### ISSUE THREAD

**Issue by championswimmer** [ParsePlatform/parse-server#1359]
In extension of the discussion here https://github.com/ParsePlatform/parse-server/issues/761 
We should move out adapters like the GCS adapter or S3 adapter from parse's default dependencies. 

If I want to use a simple fs backed storage, I have no use downloading those adapters from npm. 

It can simply be mentioned on the Wiki https://github.com/ParsePlatform/parse-server/wiki/Configuring-File-Adapters#configuring-s3adapter that you need to add the adapter to your package.json.

**Comment by flovilmart** [comment]
there's a PR for that already
