### ISSUE TITLE
ParseFile save fails on parser-server after migration: Unable to encode an unsaved ParseFile

### ISSUE THREAD

**Issue by smanikandan14** [ParsePlatform/parse-server#136]
I am using parse-android SDK 1.13.0. I am able to upload file to parse's backend. 

But when i change my server endpoint to migrated end point, upload fails. 

```
{
	"code": 130,
	"error": "Invalid file upload."
}
```
I added console logs in file.js on parse-server i found the request.body is empty.

**Files.js processCreate req: [object Object] : {} : undefined**

```
var processCreate = function(req, res, next) {
console.log(" Files.js processCreate req:"+req+" : "+ JSON.stringify(req.body)+" : "+req.body.length
if (!req.body || !req.body.length) {
    next(new Parse.Error(Parse.Error.FILE_SAVE_ERROR,
         'Invalid file upload.'));
    return;
  }

```

Exception message shown on client side.
```
iIllegalStateException: Unable to encode an unsaved ParseFile
```

Seems to be an issue on the parse-server side. The request body is found empty. I reported this issue on parse-android-sdk. Since the sdk could upload to parse hosted backend. Suspect is on the parse-server side.

**Comment by smanikandan14** [comment]
Reported the same on parse-android-sdk. https://github.com/ParsePlatform/Parse-SDK-Android/issues/384

**Comment by smanikandan14** [comment]
@gfosco Sorry, just checking if this is a valid bug. I couldn't upload images to parse-server after migration. Any solutions appreciated.

**Comment by gfosco** [comment]
Will look at this within the next day or two, looks valid, will combine other issues to point here.

**Comment by jpmassena** [comment]
@smanikandan14, are you using OkHttp dependency on you app?

As soon as I added OkHttp, I started to have some problems with my parse-server:

- First all requests to parse-server crashed the app. The cause was that I was receiving or sending null Headers (parse-x-client-key or something similar) and ParseOkHttpClient (from the SDK) crashed.

- I added the clientKey to the app/server and that problem went away, but now I'm getting the same error as you do. I removed the OkHttp dependency and I'm able to upload files again.

So, the issue seems to be around the SDK, at least for me as I only have problems when using OkHttp dependency on my app.

**Comment by Spacelapp** [comment]
Got the same error after migration: [Error]: Invalid file upload. (Code: 130, Version: 1.12.0)
Any news on this @gfosco ?

**Comment by JoshR604** [comment]
I am using the .NET sdk and I get this error as well 'Invalid file upload' but I suspect the bug might be in the SDK as I can upload text files and images directly to my parse-server using cURL.

**Comment by JoshR604** [comment]
I have found a solution to my issue by explicitly setting the MIME type when uploading a ParseFile.

**Comment by flovilmart** [comment]
@gfosco idea on that, is that because we use a raw body parser and the content maybe encoded in another format depending on the client configuration (usually multipart/form-data with boundaries)

**Comment by oyvindvol** [comment]
I am using the .NET SDK to upload PFFiles (images), and also got the `invalid file upload` message. After setting MIME type explicitly in the PFFile like @JoshR604 said, I get this exception instead: `Exception of type 'Parse.ParseException' was thrown.` with no inner exception message.

When I change back to my old Parse.com-hosted server, it works fine.

**Comment by oyvindvol** [comment]
@JoshR604 Are you setting the MIME type in the ParseFile constructor? `new ParseFile("filename", data, 'image/png');` ?

**Comment by JoshR604** [comment]
@oyvindvol Yes, here is the code I am using:

var file = new ParseFile ("photo.jpg", data, "image/jpeg");
await file.SaveAsync ();
parseUser.Add ("photo", file);
await parseUser.SaveAsync ();

Also,  I am using the .NET sdk on Xamarin and have tested this code on iOS and Android.

**Comment by perriera** [comment]
I just discovered today that by default the migration feature of the new Parse dashboard only migrates your data. It does not migrate the contents of the ParseFile object itself. In my case I am storing jpg and png images inside a ParseFile. When I did the first mirgration the ParseFile objects migrated but they pointed towards the www.parsefss.com url. In my case I was able to by pass the need for the migration tool because I happened to have a backup/restore feature on my client's website. Where I was able to do a full backup while still on the Parse.com database. Then when I switched to my open source Parse Server with it's own MongoDB, I did a full restore. This caused the file uploading to store a brand new copy of the ParseFile images inside the MongoDB database. I was able to check this simply by doing a View Image with the browser. 

So it looks like all you have to do is something similar to this and you're ready to go!

I did a double check on my website before posting this comment. The open source Parse Server uploads, edits and deletes images just fine!

**Comment by jmk2142** [comment]
@perriera I had a similar question about Parse.Files on the old system. Apparently a file migration tool that will migrate your files to your new MongoDB is in the works. For now, configuring your server with a fileKey (from your Parse file key) will make your server point correctly to the old files that still reside on Parse's Amazon file store. New files created on your server using Parse.File will be stored on your own MongoDB and work just fine.

**Comment by oyvindvol** [comment]
@gfosco Do you know when you will look at this bug?

**Comment by perriera** [comment]
Yes, it's on my todo list to see what the exact characteristics of the
generated keys are for the open source Parse Server!


Perry Anderson

--------------------------------------------------------------

Unified Objects, Inc. <http://www.unifiedobjects.com/>

We build beautiful web and mobile apps! <http://hosting.unifiedobjects.com/>

--------------------------------------------------------------

perry@unifiedobjects.com

Tel: 844 440 7400
----------------------------------------
perry.anderson@gmail.com
Check out my professional profile and connect
with me on LinkedIn. http://lnkd.in/5TpErE
----------------------------------------

===================================

**Comment by oyvindvol** [comment]
@perriera That`s OK, but that was not really my problem.

The problem is that when uploading images from file upload via the .NET SDK we get the error `Invalid file upload.`. Someone resolved this by explicitly setting MIME type when creating the `ParseFile` object, but this didn`t solve it for me..

**Comment by perriera** [comment]
Keep me posted! Parse Server is open source now so it's going to be up to
the open source community to maintain it.

Cheers,

Perry


Perry Anderson

--------------------------------------------------------------

Unified Objects, Inc. <http://www.unifiedobjects.com/>

We build beautiful web and mobile apps! <http://hosting.unifiedobjects.com/>

--------------------------------------------------------------

perry@unifiedobjects.com

Tel: 844 440 7400
----------------------------------------
perry.anderson@gmail.com
Check out my professional profile and connect
with me on LinkedIn. http://lnkd.in/5TpErE
----------------------------------------

===================================

**Comment by cyboolo** [comment]
any news on file upload process? @gfosco

**Comment by nlutsenko** [comment]
Looks like we require the `Content-Type` for file uploads, which might not be sent at all times.
I am going to remove the restriction right now, so we no longer require the content-type on file uploads.

**Comment by oyvindvol** [comment]
@nlutsenko So, I updated my parse server to 2.1.2, and tried again uploading file from .NET SDK. Still get the same error `Invalid file upload, code 130`.

And this is how I create the file: `new ParseFile("file", imageData)`.

**Comment by nlutsenko** [comment]
The fix literally landed ~6 hours ago and 2.1.2 is about 3 days old at this point, meaning that it will be a part of 2.1.3. :grin:

**Comment by oyvindvol** [comment]
@nlutsenko Ah, I`m sorry :) Thanks!

**Comment by arrivaldwis** [comment]
did this bug already fixed? I'm still get the error "invalid file upload"

thanks

**Comment by oyvindvol** [comment]
It is not released yet, it will be part of parse-server 2.1.3.

**Comment by arrivaldwis** [comment]
@oyvindvol Ok, Thanks!

**Comment by vioside** [comment]
Just got this error message from iOS SDK

`[Error]: Could not store file. (Code: 130, Version: 1.12.0)`

Not sure if it's related to this same problem cause it was working and it stopped since I updated to version 2.1.3. I'm using the S3 adapter. Any ideas?

**Comment by nlutsenko** [comment]
@vioside, that sounds super strange. Any chance you can open a separate issue for it, also would be super helpful if you would specify there how you are configuring S3 storage.

**Comment by vioside** [comment]
@nlutsenko ok, issue created: #675  
Thanks!

**Comment by wavo89** [comment]
@perriera     

I am experiencing this issue with Parse-Server, though it was working fine with saving images hosted on the  www.parsefss.com domain, until today. I wonder if uploading through the parse.com file browser somehow caused it to not save the images from the application anymore. 

Are you able to share any resources on how to take the database and re-upload it (to mLab from Heroku in my case)? What you're saying is that by using this process it will save the files to with a domain pointing to our server and not the parse.com one?

**Comment by ribads** [comment]
What is the update on this.
Has this issue been resolved.

Still getting the error
Am on the android library version 1.13.0
and Parse-server version: 2.1.4

**Comment by wavo89** [comment]
This actually was happening because I maxed out the HDD on the mongodb host I use (mLab) . Didn't realize it bc I'm used to Parse. So that may help. You also in general want to try updating the parse-server SDK, for some other things that helped me. Good luck.

**Comment by ribads** [comment]
I was able to resolve the issue by adding a file content Type like this.
pFile = new ParseFile(data, "image/jpeg");

I would suggest that it should be updated on the documentations if contentType is a required field or ParseFile

**Comment by abbasdawood** [comment]
I am on the latest release of Parse Server (2.2.12), and I am still getting this (or a similar) error. Only now, the message changes to 

`ParseError {
cherokee-server-0   code: 130,
cherokee-server-0   message: 'Could not store file.InvalidParameterType: Expected params.ContentType to be a string' }`

The additional bits of `InvalidParameterType: Expected params.ContentType to be a string` is only seen once I modify parse-server/lib/routers/FileRouter.js line number 108, to include the error

Original line (in FileRouter.js): 
`next(new Parse.Error(Parse.Error.FILE_SAVE_ERROR, 'Could not store file.'));`

Modified to:
`next(new Parse.Error(Parse.Error.FILE_SAVE_ERROR, 'Could not store file.' + err));`

My Method that creates and tries to save the parsefile:
`var uploadToParse = function(filename, vendor) {
    var deferred = q.defer();

    var d;

    var Report = new Parse.Object.extend('Report');
    var report = new Report();

    fs.readFile('tmp/' + filename + '.csv', function(err, data) {
        if (!err) {
            d = data.toString('base64');
            var name = vendor + Date.now().toString();
            var file = new Parse.File(name + '.csv', { base64: d }, 'text/csv'); //Adding the MIME manually doesn't help either
            report.set('report', file);
            report.set('vendor', vendor);

            report.save().then(function(report) {
                console.log('Saved report with ID ' + report.id);
                deferred.resolve(report.id);
                fs.unlink('tmp/' + filename + '.csv');
                fs.unlink('tmp/' + filename + 'temp.json');
            }, function(error) {
                deferred.reject(error);
                console.log(error);
            });
        } else {
            deferred.reject({ message: 'CSV file not found' });
        }
    });

    return deferred.promise;
};`

**Comment by HananeAlSamrout** [comment]
hello, i am still getting this error in the latest version  (2.2.12): Error Domain=Parse Code=130 "Could not store file." UserInfo={code=130, temporary=0, error=Could not store file., NSLocalizedDescription=Could not store file.}

**Comment by abbasdawood** [comment]
Hi, can you share your S3Adapter config and initialization line from your code?

**Comment by HananeAlSamrout** [comment]
problem solved 👍 i had a problem in the s3 adapter

**Comment by roylo** [comment]
hi @HananeAlSamrout , I have the same issue here just like you. Can you share your s3 adapter setting to me?

**Comment by boparski** [comment]
@HananeAlSamrout Same here: what was the problem with the S3 adapter?

**Comment by wussup** [comment]
Still have error after migration with photo upload: "Invalid file upload". Use android-parse 1.13.1 and parse-server 2.3.2. Adding Content-Type "image/png" to new ParseFile do not solve problem.

Please help!

**Comment by FeleciaGenet** [comment]
Getting this error out of no where now. Was working fine yesterday. 

Error Domain=Parse Code=130 "Could not store file." UserInfo={code=130, temporary=0, error=Could not store file., NSLocalizedDescription=Could not store file.}

**Comment by mauriciord** [comment]
#3438 I'm having the same problem with GCS Adapter

**Comment by kittuvenkat** [comment]
@FeleciaGenet Did you get this resolved? I am facing this issue all of a sudden. Strangely I can upload images using IOS SDK but not working from Android. It doesn't matter if I use S3 adapter or default grid store adapter. I get 'Invalid file upload' error.

Parse-server: 2.3.2
Parse-android-sdk: 1.13.1

byte[] data = "Working at Parse is great!".getBytes();
        ParseFile file = new ParseFile("resume.txt", data);

        file.saveInBackground(new SaveCallback() {
            public void done(ParseException e) {
                if(e!=null){
                    Log.i("Image Error", e.getMessage());
                }
            }
        });

**Comment by kittuvenkat** [comment]
Solved the issue by declaring parse file as
ParseFile file = new ParseFile(data,"resume.txt");

lesson learned: Don't rely solely on documentation :)

**Comment by FeleciaGenet** [comment]
@kittuvenkat glad it worked out for you. 

For what it's worth, for me the issue was that I had truly run out of space on the new database. Once I upgraded my storage, the issue was resolved.

**Comment by NatanRolnik** [comment]
@kittuvenkat you are welcome to help the Parse community by opening a PR to the docs 😊
The repo is https://github.com/ParsePlatform/docs and the specific file that relates to `ParseFile` on Android is this one: https://github.com/ParsePlatform/docs/blob/gh-pages/_includes/android/files.md

**Comment by kittuvenkat** [comment]
@NatanRolnik Sure. I am fairly new to parse community but will contribute what I can. Thanks for the links.

**Comment by grantespo** [comment]
The "Could not store file." error is occuring for me too out of nowhere after it was working perfectly for months. I'm not sure what is causing this. How would I know if I needed to update my storage?

**Comment by zhydanovajulia** [comment]
I have the same problem. Yesterday was working fine.
