### ISSUE TITLE
Delete Handler in FilesRouter not being called on delete of Class

### ISSUE THREAD

**Issue by mcclaskiem** [ParsePlatform/parse-server#1360]
I currently have a Class with an image/file attached to it however, when deleting the object I am not seeing the `deleteHandler` called in FilesRouter.js. Is there something additional I need to do in order to notify the FilesRouter that a class has a file field attached to it?

**Comment by drew-gross** [comment]
Unfortunately, Parse Server has no way of knowing if there is another object referencing the same file, so it can't safely delete the file. We don't currently have any solution in place for clearing out unreferenced files in Parse Server.

**Comment by mcclaskiem** [comment]
Ok fair enough. So we need to manually call the deleteFile handler in our respective adapter at the same time we delete an object that contains it.

**Comment by drew-gross** [comment]
Yep, if your particular application has a one file -> one object constraint, that should do it.

**Comment by mcclaskiem** [comment]
Ok thank you
