### ISSUE TITLE
unable to get the email ....below is my index.js file

### ISSUE THREAD

**Issue by apurvaaggarwal** [ParsePlatform/parse-server#1371]
// Example express application adding the parse-server module to expose Parse
// compatible API routes.

var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var path = require('path');

var databaseUri = process.env.DATABASE_URI || process.env.MONGOLAB_URI;

if (!databaseUri) {
  console.log('DATABASE_URI not specified, falling back to localhost.');
}

var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/xxxx',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
  masterKey: process.env.MASTER_KEY || 'xxxxxxxxxxxxxxxxxxxxxxxxxx', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',  // Don't forget to change to https if needed
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  },
push: {
    android: {
      senderId: 'xxxx', // The Sender ID of GCM
      apiKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxx' // The Server API Key of GCM
}
    },
	verifyUserEmails:true,
	publicServerURL: 'http://166.xx.xx.xxx/parse',
	appName: 'appname blah blah',
	emailAdapter: {
    module: 'parse-server-simple-mailgun-adapter',
    options: {
      // The address that your emails come from
      fromAddress: myemail@gmail.com,
      // Your domain from mailgun.com
      domain: domain from mailgun,
      // Your API key from mailgun.com
      apiKey: api key from mailgun,
    }
  },
});
// Client-keys like the javascript key or the .NET key are not necessary with parse-server
// If you wish you require them, you can set them as options in the initialization above:
// javascriptKey, restAPIKey, dotNetKey, clientKey

var app = express();

// Serve static assets from the /public folder
app.use('/public', express.static(path.join(__dirname, '/public')));

// Serve the Parse API on the /parse URL prefix
var mountPath = process.env.PARSE_MOUNT || '/parse';
app.use(mountPath, api);

// Parse Server plays nicely with the rest of your web routes
app.get('/', function(req, res) {
  res.status(200).send('Make sure to star the parse-server repo on GitHub!');
});

// There will be a test page available on the /test path of your server url
// Remove this before launching your app
app.get('/test', function(req, res) {
  res.sendFile(path.join(__dirname, '/public/test.html'));
});

var port = process.env.PORT || 1337;
var httpServer = require('http').createServer(app);
httpServer.listen(port, function() {
    console.log('parse-server-example running on port ' + port + '.');
});

// This will enable the Live Query real-time server
ParseServer.createLiveQueryServer(httpServer);

**Comment by bohemima** [comment]
You did change out those keys to real ones?
Also, enable logging and copy relevant portions of the logs.

**Comment by apurvaaggarwal** [comment]
I have configured everything else...but have a doubt at a place " fromAddress : " . What should i fill here ?  I have configured my domain on mailgun

**Comment by tanmays** [comment]
It can be anything@<your-domain-here>.com
