### ISSUE TITLE
Bug: can access all installations via REST

### ISSUE THREAD

**Issue by markuswinkler** [ParsePlatform/parse-server#1372]
Based on this article (https://www.parse.com/questions/what-are-the-recommended-permissions-for-the-installations-class) a query for _Installation should only return your own installation object.

However, if I run this cURL call I can get all installation objects.
```
curl -X GET \
  -H "X-Parse-Application-Id: {validID}" \
  -H "Content-Type: application/json" \
  http://localhost:1337/parse/classes/_Installation
```
That request should always return empty (or with an error).

**Comment by estylehq** [comment]
Are you check security setting?

**Comment by flovilmart** [comment]
I believe you can lock it down with a CLP dis allowing public find, an allowing everything else

**Comment by flovilmart** [comment]
Just checked with Parse.com API, and I'm locking down the find operation on installation the same way we lock down the delete operation! Thanks for reporting that security issue

**Comment by markuswinkler** [comment]
Great! Thanks! :+1:
