### ISSUE TITLE
Cannot get back the full object from the relational field after saving an object

### ISSUE THREAD

**Issue by carmenlau** [ParsePlatform/parse-server#1377]
We set a complete object to object's relation field, but there is only id leave after saving. Following is the testing code and the output comparison between parse.com and parse-server.

**The testing cloud code:**
```
Parse.Cloud.define("testQuery", function(request, response) {
  var objectQuery = new Parse.Query(ObjectClass);
  var Object;

  objectQuery.include('user');
  objectQuery
  .get("_<object_id>_", {useMasterKey: true})
  .then(function(_object) {
    object = _object;
    object.set('user', request.user);
    console.log("1 ======> " + JSON.stringify(object.get("user")));
    console.log("1 ======> " + object.get("user").getUsername());
    return object.save(null, {useMasterKey: true});
  })
  .then(function() {
    console.log("2 ======> " + JSON.stringify(object.get("user")));
    console.log("2 ======> " + object.get("user").getUsername());
    response.success("");
  }, function(error) {
    response.error(error);
  });
});
```

**console log of parse.com:**
1 ======> {**< full user object >**}
1 ======> username
2 ======> {**< full user object >**}
2 ======> username

**console log of parse.com:**
1 ======> {**< full user object >**}
1 ======> username
2 ======> {"objectId":"**< user id >**"}
2 ======> undefined

**Comment by flovilmart** [comment]
Seems to be an issue in the JS SDK more than parse-server. cc: @andrewimm.

I suggest you open it on https://github.com/parseplatform/Parse-SDK-JS/issues

**Comment by carmenlau** [comment]
@flovilmart The problem that I mentioned happen in cloud code, not JS client. :P

**Comment by flovilmart** [comment]
yeah, but this is the JS client running Cloud Code...

**Comment by carmenlau** [comment]
I got what you mean! Will open issues there, thanks @flovilmart
