### ISSUE TITLE
Adopt a Code of Conduct

### ISSUE THREAD

**Issue by KristinaApplegate** [ParsePlatform/parse-server#138]
A [code of conduct](https://robots.thoughtbot.com/adding-a-code-of-conduct-to-open-source-projects) is a common practice to foster a kind, inclusive, cooperative, and harassment-free community. Adopting a code of conduct would demonstrate that new contributors will be welcomed and respected.

**Comment by gfosco** [comment]
Open Code of Conduct adopted, merged in #142 

Thanks. :+1:
