### ISSUE TITLE
self-hosted parse-server is slow on AWS

### ISSUE THREAD

**Issue by benishak** [ParsePlatform/parse-server#1381]
I'm trying to host my own parse-server on AWS
I have an EC2 t2.micro instance running with NGINX and GZip.

When doing requests to my mLab-hosted MongoDB I noticed that it is slow, I get the following result for the same requests
AWS-EU-Central vs PARSE vs AWS-US-East vs Heroku
2.5s vs 0.3s vs 1.4s vs 3.0s

On Heroku I'm not using NGINX

Does parse.com use CDN (AWS CloudFront) 

The Indexing could be also a reason for that, does Parse.com use advanced indexing or just basic indexing?

Thanks

**Comment by drew-gross** [comment]
Parse.com will add index for you based on the queries you issue. Parse Server does not do that, you will need to add indexes yourself.

**Comment by benishak** [comment]
@drew 
So do you think it is all about the indexing?  Not of the server configuration  (nginx .... )

**Comment by gfosco** [comment]
Is the parse.com app using the same mlab database?

**Comment by benishak** [comment]
@gfosco yes it is

**Comment by drew-gross** [comment]
There are a lot of potential reasons for performance issues. Parse Server may be executing different queries, there may be latency between your DB and Server, etc. If you can provide more details about what exactly is slow, that would be helpful.

**Comment by benishak** [comment]
@drew
I'm executing the same queries on the same DB.
The queries are just simple something like query.find() with equalto constraints (searching, filtrations)

I don't think is indexing problem because I'm using the same database, so if that database is indexed, so changing the parse server won't affect it.

**Comment by drew-gross** [comment]
Thats true, the indexes should be there. Is there any way you can look at your mLab to check how much time is being spent in mongoDB vs in Parse Server code? Also, can you check latency between your Parse Server and mLab db?

**Comment by blacha** [comment]
@benishak are you a logged in user? There are a number of excess queries being run when the user has roles.

#1383 should improve the role query performance, by quite a lot.

My suggestion would be to look at the real time mongo logging on your mlab database while you run the simple query to see exactly how many queries are run.
