### ISSUE TITLE
Question regarding Database Migration Guideline

### ISSUE THREAD

**Issue by kenglou** [ParsePlatform/parse-server#1393]
Not sure this should be ask here or not but I can't really have any other places to ask for.

Regarding to the Migration Guide, the Database migration should be done by 28th April 2016(that means end of this month). Basically I wish to know that according to the quote below:

> If you do not migrate your database by April 28, we will assume you do not consider the app's migration to be a high priority. Traffic to your app may be de-prioritized as we shift our focus to serving production apps that are being migrated according to our recommended schedule.

What is the meaning of "Traffic to your app may be de-prioritized"??? Currently my company is in tight schedule and we actually plan to start the database migration around June/July, and we still have Games that are running live now. Is that means we will be abandoned by parse and they won't gonna support us anymore?

Really hope that there will be a clarification on this.

Thank you.

**Comment by drew-gross** [comment]
It means that we will be focussing on supporting production apps that have already migrated. If you are working on migration but won't able to complete the migration by April 28th, reach out to our support team and tell them about your plans and we should be able to keep you prioritized.

**Comment by kenglou** [comment]
If Possible, may i know where I can find contact for Parse Support Team?

**Comment by jenisat** [comment]
@drew-gross @kenglou I'm in the same situation where we are working on another issue & won't make the April 28th date.  The link to the support page/facebook for developers throws an error page & the product page redirects to parse.com.  

Would appreciate addl information on the throttle / best contact details.  Thanks

**Comment by drew-gross** [comment]
http://parse.com/help

**Comment by jenisat** [comment]
thanks @drew-gross -  have tried the community options listed and the link for migration assistance on the help page. That's the link I referenced which says the link is broken or page removed and searching on developers.facebook redirects to the main parse page. Bit of a loop which doesn't provide answers ...

**Comment by drew-gross** [comment]
In that case you can also email migration@parse.com

**Comment by jenisat** [comment]
Done. Thanks @drew-gross
