### ISSUE TITLE
showing push error

### ISSUE THREAD

**Issue by apurvaaggarwal** [ParsePlatform/parse-server#1394]
Android Code:
    final Map<String, Object> params = new HashMap<>();
    params.put("message", message);
    params.put("userId", ParseUser.getCurrentUser().getObjectId());

    ParseCloud.callFunctionInBackground("sendPush", params,
            new FunctionCallback<String>() {
                @Override
                public void done(String result, com.parse.ParseException e) {
                    // TODO Auto-generated method stub

                    if (e == null) {
                        Toast.makeText(context, "HEHE", Toast.LENGTH_SHORT)
                                .show();
                        Log.d("ANNOUNCEMENT", "SUCCESS");
                    } else {
                        Toast.makeText(context, "FAilure " + e.toString(),
                                Toast.LENGTH_SHORT).show();

                        Log.d("ANNOUNCEMENT", "FAILURE" + e.toString());
                    }
                }
            });
///////////////////////////////////////////////
main.js
Parse.Cloud.define("sendPush", function(request, response) {

var sendUserId = request.params.userId;
    var msg = request.params.message;

var query = new Parse.Query(Parse.Installation);
query.equalTo('userId', sendUserId);

    Parse.Push.send({
            where: query,
            data: {
                    alert: msg,
                    sound: 'default'
            }
    }, {
            success: function() {
                    // Push was successful
                    response.success("Push sent");
            },
            error: function(error) {
                    // Handle error
                    response.error(error);
            },
            useMasterKey: true
    });
});
But not getting push
Here is the verbose //////
verbose: sending push to 1 installations
verbose: sent push! 0 success, 0 failures

**Comment by flovilmart** [comment]
What adapter are you using? Which devices are you sending to? Android, iOS? Can you get the _PushStatus object?

**Comment by apurvaaggarwal** [comment]
I am using parse push adapter; sending to android devices 

_PushStatus 

{ 
    "_id" : ObjectId("5704f607c87f874d22157520"), 
    "objectId" : "AJDiHp7HRu", 
    "pushTime" : "2016-04-06T11:41:59.478Z", 
    "_created_at" : ISODate("2016-04-06T11:41:59.478+0000"), 
    "query" : "{\"objectId\":\"rJvrh1s0BH\"}", 
    "payload" : {
        "alert" : "4", 
        "sound" : "default"
    }, 
    "source" : "rest", 
    "title" : null, 
    "expiry" : null, 
    "status" : "succeeded", 
    "numSent" : NumberInt(0), 
    "pushHash" : "01538e1dfb45c0adc1c4bd63365cf403", 
    "_wperm" : [

    ], 
    "_rperm" : [

    ], 
    "numFailed" : NumberInt(0)
}

**Comment by flovilmart** [comment]
I'll have a look

**Comment by apurvaaggarwal** [comment]
2.2.6

**Comment by flovilmart** [comment]
thanks

**Comment by flovilmart** [comment]
When running with VERBOSE=1, you should have that kind of logs:
```
verb parse-server-push-adapter GCM sending to 1 device
verb parse-server-push-adapter GCM GCM Response: {
verb parse-server-push-adapter GCM     "multicast_id": 8389764779291095000,
verb parse-server-push-adapter GCM     "success": 0,
verb parse-server-push-adapter GCM     "failure": 1,
verb parse-server-push-adapter GCM     "canonical_ids": 0,
verb parse-server-push-adapter GCM     "results": [
verb parse-server-push-adapter GCM         {
verb parse-server-push-adapter GCM             "error": "InvalidRegistration"
verb parse-server-push-adapter GCM         }
verb parse-server-push-adapter GCM     ]
verb parse-server-push-adapter GCM }
```
Can you please provide them?

**Comment by apurvaaggarwal** [comment]
verbose: POST /parse/push { 'user-agent': 'node-XMLHttpRequest, Parse/js1.8.1 (NodeJS 5.3.0)',
  accept: '*/*',
  'content-type': 'text/plain',
  host: '166.62.82.202:1337',
  'content-length': '278',
  connection: 'close' } {
  "where": {
    "objectId": "KQPONXtIjb"
  },
  "data": {
    "alert": "Hello",
    "sound": "default"
  }
}
verbose: {
  "response": {
    "result": true
  }
}
success
verbose: {
  "response": {
    "result": "Push sent "
  }
}
verbose: sending push to 1 installations
verbose: sent push! 0 success, 0 failures

**Comment by flovilmart** [comment]
Seems to be a misconfiguration in parse-server-push adapter, how did you set it up?

**Comment by apurvaaggarwal** [comment]
i have set it up in index.js

**Comment by flovilmart** [comment]
Would you care to show it?

**Comment by apurvaaggarwal** [comment]
![untitlednew](https://cloud.githubusercontent.com/assets/12373845/14325561/822ecd88-fc47-11e5-892d-ceaa7a33db59.png)

**Comment by flovilmart** [comment]
what's the version of parse-server-push-adapter? in `node_modules/parse-server-push-adapter/package.json`

**Comment by apurvaaggarwal** [comment]
1.0.4

**Comment by estylehq** [comment]
Is latest ',' in emailAdapter-apiKey line relate this bug?
```
options : {
    ....
    apiKey: 'YOUR_KEY' ,
}
```

**Comment by apurvaaggarwal** [comment]
@estylehq elborate please

**Comment by estylehq** [comment]
updated.

**Comment by apurvaaggarwal** [comment]
means in my index file i have remove the comma that i have instered at the end of the email adapter

**Comment by estylehq** [comment]
yeah. and end of push configuration too.

**Comment by apurvaaggarwal** [comment]
var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://myadreees:27017/test',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID ||'apkeykey',
  masterKey: process.env.MASTER_KEY || 'master', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || 'http://myadreees/parse',  // Don't forget to change to https if needed

verifyUserEmails:true,
publicServerURL:'http://myadreees:1337/parse',
appName: 'Trakie',
 emailAdapter:{
module: 'parse-server-simple-mailgun-adapter',
options:{
fromAddress:'',
domain:'',
apiKey:'',}},
  push: {
    android: {
      senderId:'',
      apiKey:''
}
    },
});



/??//// is this correct

**Comment by estylehq** [comment]
remove comma end of push.

**Comment by apurvaaggarwal** [comment]
var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://myadreees:27017/test',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID ||'apkeykey',
  masterKey: process.env.MASTER_KEY || 'master', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || 'http://myadreees/parse',  // Don't forget to change to https if needed

verifyUserEmails:true,
publicServerURL:'http://myadreees:1337/parse',
appName: 'Trakie',
 emailAdapter:{
module: 'parse-server-simple-mailgun-adapter',
options:{
fromAddress:'',
domain:'',
apiKey:'',}},
  push: {
    android: {
      senderId:'',
      apiKey:''
}
    }
});

**Comment by apurvaaggarwal** [comment]
Updated index.js but the error is still same

**Comment by flovilmart** [comment]
can you please format correctly your index.js configuration? It's impossible to see where your error is.... Also we have many users having a functional push setup.

**Comment by apurvaaggarwal** [comment]
i have reformated the code of index.js and can you tell me that if want to send push to a specfic user using the object id of that users

**Comment by flovilmart** [comment]
That question should be asked over stackoverlow, or any other forum. We're not here to provide support for your implementations.

**Comment by apurvaaggarwal** [comment]
ok will the client push enable in future use

**Comment by flovilmart** [comment]
I don't believe it will ever be enable as this is a very important security problem. Also, many users have worked around it by creating a cloud code function. Look through the issues, and other references, and you should be good to go. 

Coming back to your issue, can we have a properly formatted index.js?

**Comment by apurvaaggarwal** [comment]
yes i have formatted it here it is 
var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID ||'',
  masterKey: process.env.MASTER_KEY || '', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || 'http',  // Don't forget to change to https if needed

verifyUserEmails:true,
publicServerURL:'http:',
appName: 'Trakie',
 emailAdapter:{
module: 'parse-server-simple-mailgun-adapter',
options:{
fromAddress:'@gmail.com',
domain:'.mailgun.org',
apiKey:'key-',}},
  push: {
    android: {
      senderId:'',
      apiKey:''
}
    }
});

**Comment by flovilmart** [comment]
this is not formatted....


formatted is:

```
var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb',
  emailAdapter:{
    module: 'parse-server-simple-mailgun-adapter',
    options:{
      fromAddress:'@gmail.com',
      domain:'.mailgun.org',
      apiKey:'key-'
    }
  }
})
```

**Comment by apurvaaggarwal** [comment]
then  what about push notification

**Comment by flovilmart** [comment]
what do you mean?

**Comment by apurvaaggarwal** [comment]
in index,js we have to declare both push adapter , email adapter and server info(master key,app id,mongo db connection string) then the formateed code that have been provided in that where i would add push adapter

**Comment by flovilmart** [comment]
this was just an example, to show you how to properly format the code when you share it. Your shared file appear all flat, with multiple } on certain lines... I can't really say what's wrong in your configuration because it's just plain ugly and not readable

**Comment by apurvaaggarwal** [comment]
i have checked everything again but the problem is steill there 
here is my main,js file
Parse.Cloud.define("sendPush2", function(request, response) {

    var sendUserId = request.params.userId;
        var msg = request.params.message;

    

var query = new Parse.Query(Parse.User);
query.equalTo("ObjectId", id);

        Parse.Push.send({
           where : query,
                data: {
						 
                        alert: "msg"
                       
                }
        }, {
useMasterKey:true,
                success: function() {
                        // Push was successful
console.log("success");
                        response.success("Push sent ");
                },
                error: function(error) {
                        // Handle error
console.log("failed");                    
    response.error(error);
                }
           
        });
});

**Comment by flovilmart** [comment]
the query on push should be on installations not on users... That's why you're not getting anything...
