### ISSUE TITLE
403 (Forbidden)when trying to save a user via js sdk

### ISSUE THREAD

**Issue by code-bash** [ParsePlatform/parse-server#14]
I have everything setup correctly "so I say". 

Any ideas?

**Comment by gfosco** [comment]
Can you log out the exact error? Are you setting any client/JavaScript keys during initialization?

**Comment by code-bash** [comment]
I tried with just appID then I tried with JS and Client key as well. I had it working fine talking to Parse last week. I setup my server today and migrated my DB over from Parse. It seems when I try and add a user and the console shows parse-latest.js:8580 POST https://myserver.herokuapp.com/parse/users 403 (Forbidden). I will see if I can find more info maybe I am missing a step.

**Comment by gfosco** [comment]
It returns a status code 403, but what is the content of the response?  Check the logs too.

**Comment by rebelchris** [comment]
I also have user errors on Heroku, when i try to login or retrieve users i get  "Internal server error." with no other message part..

**Comment by gfosco** [comment]
Ok, excellent, thank you.  This means we have a bug to fix in transform.js to accept that key.

**Comment by gfosco** [comment]
Should be fixed by #44... Will tag a new release after a few other things get fixed.

**Comment by code-bash** [comment]
@gfosco @rebelchris  thanks I fell asleep last night before I could post the logs.

**Comment by kumargagan4** [comment]
@gfosco can you please do the same for the key '_type' because it is causing some issue with PFFile when I am saving an array of pffiles in a record it has three fields for _type , name and url.
but for _type it is showing error.

otherwise I need to remove this for 13.5k images stored in my db
