### ISSUE TITLE
Parse-server w/ panel example either as a BItnami stack or droplet, VM or similar.?

### ISSUE THREAD

**Issue by hjgabrielsen** [ParsePlatform/parse-server#1406]
Anyone like to share their (dummy/template) new-setup to community,? This will definately take the pain out of migrating .

Thanks in advance..

**Comment by hramos** [comment]
Have you seen [parse-server-example](/ParsePlatform/Parse-Server-Example)? It's a barebones Node+Express app that uses the Parse Server NPM and can be easily deployed.

**Comment by jasonhoch** [comment]
https://bitnami.com/stack/parse

One click installation from Bitnami

**Comment by drew-gross** [comment]
Thanks for the link @jasonhoch!

**Comment by mauriciord** [comment]
@jasonhoch I'm using Bitnami Stack, but comes with Parse Dashboard. How can i protect the panel ? Because if i access the Server URL, it will enter in the Dashboard.
Did you understand ?
Thank you

**Comment by jasonhoch** [comment]
@mauriciord , I am not aware that there is Parse Dashboard coming together. However, you may try this link to secure the account.
[https://github.com/ParsePlatform/parse-dashboard#configuring-basic-authentication]
