### ISSUE TITLE
Push/Parse Android App Data Migration Issue

### ISSUE THREAD

**Issue by fabuhelow** [ParsePlatform/parse-server#1408]
Hi,

I have created a new **parse-server** and migrate push notification users data to my new server, i have tried to send new notification but the the notification does not receive.

Any help please, and in case the migration not working on android devices why i should do it?

Thanks,

**Comment by flovilmart** [comment]
Start your server with VERBOSE=1, if running on heroku search for 'set environment variables heroku', on your local machine, that would be setting `VERBOSE=1 <command to start>`.

With verbose on, try to send a push again, and we'll get a better sense of what's going on

**Comment by fabuhelow** [comment]
Thanks @flovilmart  i have got the same error that i have mentioned before .. "**MismatchSenderId**"

 results: 
   [ { error: '**MismatchSenderId**' },
     { message_id: '0:1460030703713632%2fc90b0cf9fd7ecd' } ] }
verb parse-server-push-adapter GCM GCM Response: {
verb parse-server-push-adapter GCM     "multicast_id": 4984017450201891000,
verb parse-server-push-adapter GCM     "success": 0,
verb parse-server-push-adapter GCM     "failure": 1,
verb parse-server-push-adapter GCM     "canonical_ids": 0,
verb parse-server-push-adapter GCM     "results": [
verb parse-server-push-adapter GCM         {
verb parse-server-push-adapter GCM             "error": "**MismatchSenderId**"
verb parse-server-push-adapter GCM         }
verb parse-server-push-adapter GCM     ]
verb parse-server-push-adapter GCM }
verbose: sent push! 0 success, 1 failures

**Comment by flovilmart** [comment]
this is an error from GCM: http://stackoverflow.com/questions/20641393/gcm-error-codes
