### ISSUE TITLE
Through Data Pipeline, I am not able to import my parse data to dynamodb from s3, for parse migration using dynamodb. 

### ISSUE THREAD

**Issue by komalkk** [ParsePlatform/parse-server#1409]
I have migrated my existing parse app to AWS, now I need to use dynamodb for database in place of mongolab, I use datapipeline to import my parse json file data to dynamodb tables, datapipeline shows the status FINISHED, still there is no any import shows in dynamodb.
I use the json file format as given below -
{ "results": [
	{
        "appIdentifier": "..",
        "appName": "MyApp",
        "appVersion": "1.0",
        "badge": 0,
        "createdAt": "1450183514",
        "deviceToken": "...",
        "deviceType": "ios",
        "installationId": "...",
        "parseVersion": "...",
        "timeZone": "...",
        "updatedAt": "1450787375",
        "user": "..."
    },
    .....
]
}

I follow the pages -
https://calorious.wordpress.com/2016/02/14/episode-1-exporting-data-and-images-out-of-parse/
http://stackoverflow.com/questions/34161684/mongodb-to-dynamodb
please help me.

**Comment by flovilmart** [comment]
We don't support dynamoDB as a valid database for parse-server. Please use mongodb

**Comment by komalkk** [comment]
Thanks..

**Comment by flovilmart** [comment]
There is an open discussion about those external databases here #20 and we're actively working on the DB abstraction to help making database adapters for any kind of database.
