### ISSUE TITLE
REST Delete file error

### ISSUE THREAD

**Issue by umales** [ParsePlatform/parse-server#1411]
Hello, 

- [ x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x ] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

Parse server 2.2.6
mLAB

#### Steps to reproduce

Try to delete a file with cURL

> curl -X DELETE \
>   -H "X-Parse-Application-Id: myapp" \
>   -H "X-Parse-Master-Key: mymaster" \
>http://myAPP.herokuapp.com/parse/files/myAPP/bb92af56a083d9247196eff493d9a3cd_picture.jpg
> 

Then i got an error :  404 Not Found , Cannot DELETE /parse/files/myAPP/bb92af56a083d9247196eff493d9a3cd_picture.jpg

Thanks !

**Comment by flovilmart** [comment]
remove the myAPP and it should work.

**Comment by umales** [comment]
It works ! Thanks :)

**Comment by flovilmart** [comment]
We could add that endpoint as well but the appId is not really useful in that case as you pass it part of the headers

**Comment by AnChiChang** [comment]
I have the same problem, however, I had change URL like you mention without myApp, but still can't delete file. Can anyone help?

error code: [31merror[39m: Failed running cloud function removeFilesFromDB for user undefined with: 2016-11-04T12:49:09.024992+00:00 app[web.1]: Input: {"fileUrls":"http://myApp.herokuapp.com/parse/files/51ed8ec28d195030583e476afe52ce2c_file.bin"} 2016-11-04T12:49:09.024994+00:00 app[web.1]: Error: {"code":141,"message":"Error deleting files"} functionName=removeFilesFromDB, code=141, message=Error deleting files, fileUrls=http://myApp.herokuapp.com/parse/files/51ed8ec28d195030583e476afe52ce2c_file.bin, user=undefined 2016-11-04T12:49:09.025932+00:00 app[web.1]: [31merror[39m: Error generating response. ParseError { code: 141, message: 'Error deleting files' } code=141, message=Error deleting files
@flovilmart

**Comment by RaschidGithub** [comment]
Is it still possible to delte files this way?
I'm receiving `Cannot DELETE /PixiesPoultry/files/GsVo6TefWYw2iMRq4jj33xIU7hoGc5LuxiK60sm8/5ad7de3d4e4decaa108a3024fae82f7c_hqdefault.jpg` 

My request:

```
curl -X DELETE \
  http://localhost:1337/PixiesPoultry/files/GsVo6TefWYw2iMRq4jj33xIU7hoGc5LuxiK60sm8/5ad7de3d4e4decaa108a3024fae82f7c_hqdefault.jpg \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: ac16b301-c924-4a7c-8594-0f40d1ea764e' \
  -H 'X-Parse-Application-Id: GsVo6TefWYw2iMRq4jj33xIU7hoGc5LuxiK60sm8' \
  -H 'X-Parse-Master-Key: ****************' \
  -H 'cache-control: no-cache'
```

**Comment by RaschidGithub** [comment]
Never mind... I just changed the url to `http://localhost:1337/PixiesPoultry/files/5ad7de3d4e4decaa108a3024fae82f7c_hqdefault.jpg` and it worked.
