### ISSUE TITLE
Parse Server doesn't start with LiveQuery on Azure

### ISSUE THREAD

**Issue by Sofianebenabdallah** [ParsePlatform/parse-server#1426]
Hello,

I would like to try LiveQuery. I update package.json with :

```
{
  "name": "parse-server-example",
  "version": "1.0.0",
  "description": "An example Parse API server using the parse-server module",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/Azure/parse-server-example"
  },
  "license": "MIT",
  "dependencies": {
    "express": "~4.2.x",
    "kerberos": "~0.0.x",
    "parse": "^1.8.0",
    "parse-server": "~2.2.6",
    "parse-server-push-adapter": "^1.0.0"
  },
  "scripts": {
    "start": "node index.js"
  },
  "engines": {
    "node": ">=4.3"
  }
}

```
If I add these lines :
```
// Initialize a LiveQuery server instance, app is the express app of your Parse Server
var httpServer = require('http').createServer(app);
httpServer.listen(port);
var parseLiveQueryServer = ParseServer.createLiveQueryServer(httpServer);
```

Do I need add some other variable ??

**Comment by estylehq** [comment]
see this manual : https://github.com/ParsePlatform/parse-server/wiki/Parse-LiveQuery

**Comment by Sofianebenabdallah** [comment]
I read it. but it can't help me about my configuration. 

I have all information required.

**Comment by Sofianebenabdallah** [comment]
`httpServer.listen(port);`

this line create a trouble on my server.

**Comment by flovilmart** [comment]
What's your error?

**Comment by Sofianebenabdallah** [comment]
I need to do some tests, but I may resolve it :
I delete this code :

```
app.listen(port, function() {
    console.log('parse-server-example running on port ' + port + '.');
});
```

and replace with this code :

```
var port = process.env.PORT || 1337;
var httpServer = require('http').createServer(app);

httpServer.listen(port, function() {
    console.log('parse-server-example running on port ' + port + '.');
});

```

Parse is running.

**Comment by flovilmart** [comment]
You're listening 2 times on the same port I belive...

**Comment by Sofianebenabdallah** [comment]
right. the document don't ask to modify the port. Must I do it ?

**Comment by flovilmart** [comment]
I'm not sure. What's the error that you have??

**Comment by Sofianebenabdallah** [comment]
The logstream tell me nothing.

If I stop app.listen, parse server doesn’t work ?

Thank you

**Comment by emadehsan** [comment]
@Sofianebenabdallah 
remove `app.listen()` and add the LiveQuery configuration code.

    // Initialize a LiveQuery server instance, app is the express app of your Parse Server
    var httpServer = require('http').createServer(app);
    httpServer.listen(1337);
    var parseLiveQueryServer = ParseServer.createLiveQueryServer(httpServer);

 Following is the complete setup of Parse-Server with LiveQuery in same process. Feel free to copy-paste.

    var express = require('express');
    var ParseServer = require('parse-server').ParseServer;
    var app = express();
    
    var api = new ParseServer({
      databaseURI: 'mongodb://localhost:27017/parse', // Connection string for your MongoDB database
      cloud: '/home/username/project/cloud/main.js', // Absolute path to your Cloud Code
      appId: 'appId',
      masterKey: 'masterKey', // Keep this key secret!
      fileKey: 'optionalFileKey',
      serverURL: 'http://localhost:1337/parse', // Don't forget to change to https if needed
      liveQuery: {
        classNames: ['Test', 'TestAgain']
      }
    });
    
    // Serve the Parse API on the /parse URL prefix
    app.use('/parse', api);
    
    // app.listen(1337, function() {
    //   console.log('parse-server-example running on port 1337.');
    // });
    
    // Initialize a LiveQuery server instance, app is the express app of your Parse Server
    var httpServer = require('http').createServer(app);
    httpServer.listen(1337);
    var parseLiveQueryServer = ParseServer.createLiveQueryServer(httpServer);
