### ISSUE TITLE
GridStore - File Delete?

### ISSUE THREAD

**Issue by edvincandon** [ParsePlatform/parse-server#143]
There was no real straightforward way to delete files hosted on parse.com (only from the dashboard if I'm correct, and it would just search for unlinked files and delete them), is there or will there be any implementation for file deletion on parse-server? 

(thanks for the quick replies so far!)

**Comment by gfosco** [comment]
This would be useful... tagging up-for-grabs.  If someone implements this for GridStore, I think @skinp would be willing to update the S3 adapter.

**Comment by skinp** [comment]
yes, I'm happy to add this to S3Adapter once someone lays down foundation
for this in filesAdapter and GridStore

**Comment by nlutsenko** [comment]
Supported since  #354 is merged, should be available in the next release.
