### ISSUE TITLE
Can't get APP_ID and MASTER_KEY since Parse no longer allow new signup

### ISSUE THREAD

**Issue by jamesytl** [ParsePlatform/parse-server#1430]
I am new to Parse.com and currently I'm trying to setup a new parse server for my mobile application. I have followed the [tutorial](https://azure.microsoft.com/en-us/blog/azure-welcomes-parse-developers/) and created a new azure app service with a forked [parseServer](https://github.com/jamesytl/parse-server) 

Currently I'm lost at the step where I have to insert the app_id and master_key value because I am unable to create new account for Parse.com and from what I understand the only way to get App_id and Master_key is through the dashboard of Parse.com. Or must I host the parseServer locally first then only I can retrieve the values through there?

**Comment by flovilmart** [comment]
You can user whatever you want for those values. Keep in mind that the masterKey should remain secret and you should not use it in your client apps.

**Comment by jamesytl** [comment]
Ah I see so its self declare value. Sorry but I have another question. How about the mongodb connection string? Should I host the mongodb at azure as well?

**Comment by flovilmart** [comment]
You can host it on azure, I know Microsoft has a special thing for parse-server on azure https://azure.microsoft.com/en-us/blog/announcing-the-publication-of-parse-server-with-azure-managed-services/

**Comment by jamesytl** [comment]
I believe this is what I need. Thanks a lot for the help! Much appreciate
