### ISSUE TITLE
Feature Request: Dashboard-Modifiable Parse Server Config

### ISSUE THREAD

**Issue by mamaso** [ParsePlatform/parse-server#1431]
I'm interested in exposing some of the Parse Server configuration to the user through the dashboard.

For example, being able to set 'allowClientClassCreation', 'verbose', client keys, etc. from the dashboard would be a nice management experience.

I think that this could leverage the _GlobalConfig code or something similar.  If the settings exist in _GlobalConfig collection they would be loaded into the app configuration cache, overriding the configuration specified in code.

Any thoughts?

**Comment by flovilmart** [comment]
We're discussing it here: https://github.com/ParsePlatform/parse-server/pull/1418

**Comment by mamaso** [comment]
Ah, I missed that when scanning through the issues, apologies for the double post.  I'll close this up and add any relevant discussion to that thread.

I love the idea, I know that a lot of the customers using parse on Azure want as little to do with touching server code as possible.
