### ISSUE TITLE
Playing video with PFFile.url not working

### ISSUE THREAD

**Issue by Bragegs** [ParsePlatform/parse-server#1440]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
**Could not find solutions in related issues**
(Local mongodb, windows server, iisnode)
I am having issues playing a video stored as PFFile(name: "video.mov", data: data!). I can download the file on mac with chrome by accessing the PFFile.url. On safari I cant. If i save the video as PFFile(data, contentType: "video/mp4") I can't access it from chrome either. The video is stored to a  _User. It doesnt seem to download the url at all on ios-device.

PFFile.url for video.mov:
https://connect.picturate.org/parse/files/skaalforpokker/d543977b652bbdc3dcc217518bc3c343_video.mov

PFFile.url for video/mp4:
https://connect.picturate.org/parse/files/skaalforpokker/a2524c3cabb3174b0532930e13687a3f_file.mp4

(The video is taken in norwegian nature, 10 sec, 5.8 mb)
#### Steps to reproduce

Windows server url proxying to my serverurl: "localhost:1337/parse" which works with the simple-mailgun-adapter as well as push. DatabaseURI: dataBaseUriWithDevAccess || 'mongodb://localhost:27017/dev' 

(https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4 is used to test my IOS-code and works fine)

If i try to run the same code on my parse.com account it runs just fine and streams the video.

#### Logs/Trace
Verbose logs for storing and getting the _User object with the .mov file:

verbose: PUT /parse/classes/_User/emcCI3HCTk { connection: 'Keep-Alive',
  'content-type': 'application/json; charset=utf-8',
  accept: '*/*',
  'accept-encoding': 'gzip, deflate',
  'accept-language': 'nb-no',
  host: '10.0.0.69:1337',
  'max-forwards': '10',
  'user-agent': 'PictuRate/1 CFNetwork/758.3.15 Darwin/15.4.0',
  'x-parse-app-display-version': '1.0',
  'x-parse-application-id': 'skaalforpokker',
  'x-parse-os-version': '9.3.1 (13E238)',
  'x-parse-client-key': '(matching clientKey in index.js)',
  'x-parse-app-build-version': '1',
  'x-parse-session-token': 'r:f6e67f74fceb27484239ffb430480d64',
  'x-parse-client-version': 'i1.13.0',
  'x-parse-installation-id': '662f7819-8573-46b6-8a1a-4ccce215825e',
  'x-original-url': '/parse/classes/_User/emcCI3HCTk',
  'x-forwarded-for': '176.11.185.136:51016',
  'x-arr-ssl': '2048|256|C=US, O=GeoTrust Inc., CN=RapidSSL SHA256 CA|CN=connect
.picturate.org',
  'x-arr-log-id': 'f7e5a3ed-12e5-40ee-873f-100f3b0c7d7c',
  'content-length': '203' } {
  "backgroundImage": {
    "url": "https://connect.picturate.org/parse/files/skaalforpokker/d543977b652bbdc3dcc217518bc3c343_video.mov",
    "name": "d543977b652bbdc3dcc217518bc3c343_video.mov",
    "__type": "File"
  }
}
verbose: {
  "response": {
    "updatedAt": "2016-04-09T11:32:10.498Z"
  }
}
_______________________________________________
verbose: GET /parse/classes/_User/emcCI3HCTk { connection: 'Keep-Alive',
  accept: '*/*',
  'accept-encoding': 'gzip, deflate',
  'accept-language': 'nb-no',
  host: '10.0.0.69:1337',
  'max-forwards': '10',
  'user-agent': 'PictuRate/1 CFNetwork/758.3.15 Darwin/15.4.0',
  'x-parse-app-display-version': '1.0',
  'x-parse-application-id': 'skaalforpokker',
  'x-parse-os-version': '9.3.1 (13E238)',
  'x-parse-client-key': ''(matching clientKey in index.js)',
  'x-parse-app-build-version': '1',
  'x-parse-session-token': 'r:f6e67f74fceb27484239ffb430480d64',
  'x-parse-client-version': 'i1.13.0',
  'x-parse-installation-id': '662f7819-8573-46b6-8a1a-4ccce215825e',
  'x-original-url': '/parse/classes/_User/emcCI3HCTk',
  'x-forwarded-for': '176.11.185.136:51016',
  'x-arr-ssl': '2048|256|C=US, O=GeoTrust Inc., CN=RapidSSL SHA256 CA|CN=connect
.picturate.org',
  'x-arr-log-id': '56a6eb76-aca4-4c65-b899-3110b9056aeb' } {}
verbose: {
  "response": {
    "ACL": {
      "emcCI3HCTk": {
        "read": true,
        "write": true
      },
      "*": {
        "read": true
      }
    },
    "objectId": "emcCI3HCTk",
    "username": "testuser",
    "yearBorn": 1990,
    "email": "test@tes.com",
    "updatedAt": "2016-04-09T11:32:10.498Z",
    "createdAt": "2016-04-09T11:30:47.890Z",
    "backgroundImage": {
      "__type": "File",
      "name": "d543977b652bbdc3dcc217518bc3c343_video.mov",
      "url": "https://connect.picturate.org/parse/files/skaalforpokker/d543977b652bbdc3dcc217518bc3c343_video.mov"
    },
    "sessionToken": "r:f6e67f74fceb27484239ffb430480d64"
  }
}

**Comment by Bragegs** [comment]
I tried to get headers of requests from parse.com and myServer, this is with the same video:

myServer request header(not streaming on ios or safari):
https://www.dropbox.com/s/smqwmfxczxve036/myServer_request_header.png?dl=0

Parse.com request header(Wanted):
https://www.dropbox.com/s/bgsee8vr918f2qo/parse_com_request_header.png?dl=0

Hope the image-quality is good enough. The parse.com header has the octet-stream which my server does not. So I guess this is a issue with my windows server 2012 R2 and IIS rather than parse-server? Anyone with more knowledge than me want to confirm this?

**Comment by hieuvo** [comment]
I'm having same issue, AVPlayer can play files from my personal server normally, but it cannot play files from stored in Parse

**Comment by Tibabal** [comment]
Not exactly same issue for me, but may be related.

I can download / stream a PFFile without issue, but when trying to get a thumbnail at a certain time of a video, AVFoundation returns "bad server configuration".

Request :
method=GET path="pathToMyFile.mov" host=myHost request_id=requestId fwd="ipAddress" dyno=web.1 connect=0ms service=15ms status=200 bytes=161657

**Comment by Bragegs** [comment]
IOS wants partiall content responses, I made it work somehow and made a document about it on here:

[notehub - Parse-Server pffile-url stream with local mongodb](https://notehub.org/qukh9)

If anyone want to improve, please do!

**Comment by indiandragon** [comment]
@Bragegs You must submit a PR for your code. AFAIK your's is the only existing solution for streaming audio/video from parse-server hosted on heroku with mongo db backend.

**Comment by wooknight** [comment]
@indiandragon  - I have a heroku / mlab (mongodb) setup . How did you get your setup working?

**Comment by osvaldo1963** [comment]
use the url from pffile it will never work using pffile directly

**Comment by indiandragon** [comment]
@wooknight , sorry for the delayed reply. Later ParseServer versions fixed this issue. 

I'm using 2.6.3 currently.
