### ISSUE TITLE
Deploying cloud code for the first time

### ISSUE THREAD

**Issue by fletcher100** [ParsePlatform/parse-server#1453]
I had not used Cloud Code prior to migrating from parse, so how do I go about deploying this for the first time on parse server?  
Thanks

**Comment by noder199** [comment]
Edit the [main.js file in your cloud folder](https://github.com/ParsePlatform/parse-server-example/blob/master/cloud/main.js). Redeploy every time you make changes.

**Comment by fletcher100** [comment]
Cool thanks
