### ISSUE TITLE
Parse.com _PushStatus class stores objectId as _id

### ISSUE THREAD

**Issue by alanphoon** [ParsePlatform/parse-server#1457]
Parse.com stores the **objectId** as **_id** in the _PushStatus class. Can we have objectId populating as _id instead (or in parallel)?  Current DB class implementation breaks parse.com dashboard push history UI.  I am currently using parse.com for push history lookup. Thanks.

Current Implementation:

`{
    "_id": {
        "$oid": "570c2330eb89ae7146a0a72a"
    },
    "objectId": "iBJnjsW5OW",
...
    "numFailed": 0,
    "sentPerType": {
        "ios": 1
    }
}`

Parse.com Implementation:
`{
    "_id": "lhk9GrVlwv",
...
    "sentPerType": {
        "android": 32,
        "winphone": 0,
        "js": 0,
        "osx": 0,
        "ios": 33,
        "winrt": 0,
        "embedded": 0
    },
    "expansionDuration": 0.339376803
}`

**Comment by flovilmart** [comment]
I recently refactored that part, and the objectId should now be as expected. Can you try from the master branch?
