### ISSUE TITLE
Push Notification data payload may contain JSON,  stringify before inserting into _PushStatus collection?

### ISSUE THREAD

**Issue by alanphoon** [ParsePlatform/parse-server#1458]
Data payloads for push notifications may contain JSON. In this scenario, it can break the _PushStatus object for that push notification when being inserted into DB.

Before inserting into _PushStatus collection,  can we stringify the data payload?  i.e. payload: JSON.stringify(body.data)  Thanks.

**Comment by flovilmart** [comment]
@drew-gross this may imply an update on parse-dashboard.

**Comment by drew-gross** [comment]
Parse Dashboard currently doesn't do anything with push statuses, so probably not?

**Comment by flovilmart** [comment]
Alright! I'll make the change then.
