### ISSUE TITLE
After migrating database to mLab, will exporting data from Parse.com dashboard still work?

### ISSUE THREAD

**Issue by artisanglobal** [ParsePlatform/parse-server#1473]
After migrating database to mLab, will exporting data from Parse.com dashboard still work?

**Comment by drew-gross** [comment]
We haven't disabled that feature yet, but we might in the future. When you have direct access to your own database, there should be no need to export from Parse.com

**Comment by artisanglobal** [comment]
Thanks, I was mainly asking because I have some migration tools that work with the Parse JSON export format. I will need to export a few times after April 28th, but not for too long.
