### ISSUE TITLE
bCrypt is very slow, how to solve

### ISSUE THREAD

**Issue by lenew** [ParsePlatform/parse-server#1485]
User Login api is very slow due to bCrypt. About 4 queries per sec on Amazon EC2 single core machine.   Node prof tools shows that about 89% cpu cycles are used by bCrypt function "encipher".
Any good solution to this?

**Comment by framp** [comment]
bcrypt is slow by design

Maybe parse-server could offer some ENV_VARS to configure bcrypt?

**Comment by drew-gross** [comment]
Thats correct, this is by design. Tuning `bcrypt` might be a reasonable solution, but making it work with existing passwords would not be easy. It's not in our roadmap but we would welcome PRs!
