### ISSUE TITLE
Cloud Code Relation Field Query not working

### ISSUE THREAD

**Issue by kaldenficklin** [ParsePlatform/parse-server#1489]
Okay I wrote a cloud function when using the parse dashboard which worked fine. We then switched to a parse server on heroku. The following code works up until it hits Parse.Relation(role, 'users'). The admins.first() runs the success function but with no users returned. I'm 100% positive it's connected to the correct DB and there are users with the 'admin' role, and I am querying a user with 'admin' role, but it's not finding it and returns undefined. Is this an issue with the new Parse server setup?

```
Parse.Cloud.define('isAdmin', function(req, response){
  Parse.Cloud.useMasterKey();
  if(!req.params.username){
    response.error('no username');
  }

  var queryRole = new Parse.Query(Parse.Role);
  queryRole.equalTo('name','admin');

  queryRole.first({
    success: function(promise){
      var role = promise;
      var relation = new Parse.Relation(role, 'users');
      var admins = relation.query();
      admins.equalTo('username', req.user.get('username'));
      admins.first({
        success: function(u){
          var user = u;
          if(user) {
            response.success('User is admin')
          }
          else {
            response.error('User is not Admin')
          }
        },
        error: function(){
          response.error('Error on user lookup')
        }
      })
    },
    error: function(){
      response.error('Error on role lookup')
    }
  })
})
```

**Comment by drew-gross** [comment]
`Parse.Cloud.useMasterKey` can't be used in Parse Server. You'll need to pass `useMasterKey: true` option in your query.

**Comment by kaldenficklin** [comment]
I changed the code to the following and still get the same result, no user is found when running `Parse.Relation(role, 'users')` against the username.

    Parse.Cloud.define('isAdmin', function(req, response){
      if(!req.params.username){
        response.error('no username');
      }

      var queryRole = new Parse.Query(Parse.Role);
      queryRole.equalTo('name','companyAdmin');

      queryRole.first({ useMasterKey: true }).then(function(promise){
        var role = promise;
        var relation = new Parse.Relation(role, 'users');
        var admins = relation.query();
        admins.equalTo('username', req.user.get('username'));
        admins.first({ useMasterKey: true }).then(function(user){
          if(user){
            response.success(true)
          }
          else {
            response.success(false)
          }
        }, function(err){
          response.error('User is not an admin')
        })
      }, function(err){
        response.error(err)
      })
    })

**Comment by drew-gross** [comment]
OK, I will investigate. In the meantime, if you could include a snippet of code that demonstrates how you create the user, that would be quite helpful.

**Comment by kaldenficklin** [comment]
Here is a cloud function we wrote to assign the role to a user. We used this function before switching to a parse server and it was used on the user we are trying to authenticate.

    Parse.Cloud.define("assignRole", function(request, response) {
      //params: userID, roleName
      Parse.Cloud.useMasterKey();

      //fetch role
      var query = new Parse.Query(Parse.Role);
      query.equalTo("name", request.params.roleName);
      query.first({
        success: function(role) {
          //fetch existing user
          var query = new Parse.Query(Parse.User);
          query.equalTo("objectId", request.params.userID);
          query.first({
            success: function(user) {
              role.getUsers().add(user);
              role.save(null, {
                success: function() {
                  response.success("Success!");
                },
                error: function(error) {
                  response.error("Failed to save role: " + "Error: " + error.code + " " + error.message);
                }
              });
            },
            error: function(error) {
              response.error("Failed to fetch user: " + "Error: " + error.code + " " + error.message);
            }
          });
        },
        error: function(error) {
          response.error("Failed to fetch role: " + "Error: " + error.code + " " + error.message);
        }
      });
    });

**Comment by drew-gross** [comment]
I wrote a test case for this issue in #1511 and it passes. Can you take a look at the test case and see if you can make it fail?

**Comment by kaldenficklin** [comment]
Got it working, thanks for the help!
