### ISSUE TITLE
Session token is generated even if user and session table is locked down via CLP.

### ISSUE THREAD

**Issue by drew-gross** [ParsePlatform/parse-server#1497]
Steps to reproduce (in iOS SDK or Cloud Code):
1. Lockdown User table (and session table if you want.. doesn't change outcome) in Server v2.2.6 Dashboard v1.0.8
2. In iOS or Cloud Code, try to sign a new PFUser up (in Cloud Code, you can use .signUp or .save)
3. Get error response
4. Check dashboard
5. See a new session token

**Comment by drew-gross** [comment]
For this one as well, @skimgosu, can you check what happens in Parse.com?

**Comment by skimgosu** [comment]
Parse.com behaves normally.

Actually, this bug has been around for a long time, now that I remember/realize. I recall logging a user in (without logging out) a few times, and a session token would be created every time. I just checked with Parse.com and repeatedly logging in does not create multiple session tokens. It even throws this error if you spam the SDK :D
```
[Error]: Only one session is allowed per user/installation pair (Code: 137, Version: 1.13.0)
Optional(Error Domain=Parse Code=137 "Only one session is allowed per user/installation pair" UserInfo={code=137, temporary=0, error=Only one session is allowed per user/installation pair, NSLocalizedDescription=Only one session is allowed per user/installation pair})
```
