### ISSUE TITLE
Parse Webhosting

### ISSUE THREAD

**Issue by themichael123** [ParsePlatform/parse-server#150]
Hi Parse team, 

is it possible to use the Parse Webhosting functionality with parse-server e.g. querying mongo with "Parse.Object.extend("DB");" and then calling res.render ? 

Thanks

**Comment by gfosco** [comment]
Since parse-server runs along with Express, you can build full web applications in standard express, and use the Parse SDK to query and use Parse data in there..

**Comment by themichael123** [comment]
how is this possible ? Thank you in advance.

**Comment by themichael123** [comment]
The solution is on the heroku repo:

Parse.initialize('myAppId','unused');
Parse.serverURL = 'https://whatever.herokuapp.com';
