### ISSUE TITLE
Denial of Service attack on Parse Server

### ISSUE THREAD

**Issue by jasonhoch** [ParsePlatform/parse-server#1504]
How could we prevent the DDoS  for our self-hosted Parse Server through Parse API as mentioned in the post below?

http://stackoverflow.com/questions/28989601/denial-of-service-attack-on-parse-com-app?lq=1

**Comment by AppablePlatform** [comment]
DDoS is hard to prevent, and whatever restrictions you impose on the hax0rz will affect legitimate users, one way or another. Blacklisting IP address will possibly affect legit users, throttling will lock out/inhibit legit users, etc. The only things you can really do are ACLs/CLPs to protect your data and reactively increase server capacity if it happens by having alerts setup for when your service reaches certain thresholds. 

Facebook's normal traffic (inc all the bots) probably looks like DDoS anyways! They just have ultrasupermegaquantum servers I guess

**Comment by jasonhoch** [comment]
A legitimately logged in user with below code will bring the Parse Server down. Am I right?

```
function sendRequest(){

    var query = new Parse.Query(Parse.User);
    query.find({

        success: function(results) {
            console.log("Request sucessful");       
        },

        error: function(error) {
            console.log("Request error: " + error.code + " " + error.message);
        }
    });
}

setInterval(sendRequest, (1000 / hitsPerSecond));
```

**Comment by flovilmart** [comment]
Running a naked node server in production is not best practices IMHO. Preventing this kind of attack is notably hard in a distributed environment. 

I suggest in the meantime you use [HAProxy rate limiting](http://blog.serverfault.com/2010/08/26/1016491873/) or (nginx rate limiting)[http://nginx.org/en/docs/http/ngx_http_limit_req_module.html].

**Comment by ericmbarnard** [comment]
What prevents any site from being DoS'd/DDoS'd? You really can't without some sophisticated DNS and request managing services. A basic definition of DoS is simply overloading a service with more requests than it can handle - you can accomplish that in LOTS of ways - several of which have nothing to do with getting access to one of your Parse-Server keys. 

Outside of the DoS question, and more specifically to the key protection question, I feel like a lot of these types of questions are missing the concept of not allowing a user to access a page where your JS (or other SDK) Key is accessible until they've authenticated (like logging into your website before they go to a page where your JS key can be found).  If you protect the webpages where your keys can be accessed, then you've at least limited the population who has access to those (and hopefully you trust that population not to be destructive).  If a key is compromised, then you can change it. If a key is misused, then you should be able to at least trace down who is using it by their session/authentication information and take the necessary actions.

Now If you're building an open and public app (something that you don't want a login experience for) - and you're starting to see the potential dangers with that - welcome to the next level.  There's a reason so many sites have you create an account and login before using their services.  At the end of the day, I think there's a lot more "hoping we don't get attacked" then "preparing for being attacked".

**Comment by flovilmart** [comment]
@ericmbarnard very valid point!

This is where Class Level Permissions, Pointer Permissions and ACL come handy with parse server. As all the data is by default 'exposed', as you need the client to communicate with the backend, those security features ensures only the proper users/roles can access parts of your data/app.

This is also why, the masterKey should stay private at all times, and that you can safely regenerate it as it's only supposed to be used in a Server-to-Server environment.
