### ISSUE TITLE
Why Doesn't Parse-Server Have Rate Limiting?

### ISSUE THREAD

**Issue by noder199** [ParsePlatform/parse-server#1505]
I understand that technically rate limiting is possible via cloud code, but it would be great to have it built-in to parse-server. For instance, the setting could be described as: "If a user (or IP address) is submitting more than 1 request per __ seconds, then return an error."

Please look into this. Thanks.

**Comment by AppablePlatform** [comment]
Hacker could potentially lock out all your users then. The denial of service would be 100% achieved with that kind of feature.

**Comment by flovilmart** [comment]
You Can easily achieve this with haproxy as a load balancer.

**Comment by noder199** [comment]
@flovilmart Thanks, that is great to know! 

I am actually using Google App Engine but it looks like it [does not currently support rate limiting](https://code.google.com/p/googleappengine/issues/detail?id=6733). [Azure does ](https://azure.microsoft.com/en-us/documentation/articles/api-management-howto-product-with-rules/). Not sure about AWS Elastic Beanstalk.

I found out that for my particular scenario (a user creating tons of accounts), what I actually needed were dynamic IP address restrictions. Both [Azure ](https://azure.microsoft.com/en-us/blog/confirming-dynamic-ip-address-restrictions-in-windows-azure-web-sites/)and [AWS ](http://docs.aws.amazon.com/waf/latest/developerguide/tutorials-rate-based-blocking.html)support this.
