### ISSUE TITLE
error getting auth for sessionToken TypeError: Cannot read property 'iso' of undefined

### ISSUE THREAD

**Issue by cyu** [ParsePlatform/parse-server#1507]
#### Environment Setup
Server running on Heroku & MongoLab.  Built from Parse server example

#### Steps to reproduce
Making a request with a session token in the header.  Auth is trying to access an iso property on what I'm guessing is a Date object.  I'm thinking this has something to do with a missing polyfill, but I don't know what I need to get it working.

#### Logs/Trace
error: error getting auth for sessionToken TypeError: Cannot read property 'iso' of undefined
    at /app/node_modules/parse-server/lib/Auth.js:88:50
    at run (/app/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /app/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/app/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:14:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by cyu** [comment]
More information about this trace - I got this error after upgrading parse-server 2.1.4 to 2.2.6.  Also, it looks like it's happens to users where the session originated from an older parse-server (possibly even from Hosted Parse).

**Comment by drew-gross** [comment]
Would you be able to grab the _Session row from the DB for the user that is having issues and post it here?

**Comment by cyu** [comment]
@drew-gross Unfortunately I had to rollback the changes since it was a production system, and the first people that reported the problem fixed it by logging out and back in.  I haven't been able to repro on our development server.  I'll have to come up with another setup so I can test without affect our production users.

**Comment by steven-supersolid** [comment]
There was a bug in 2.2.6 where that error would be thrown if your session tokens did not have an expiration date. Fixed in commit https://github.com/ParsePlatform/parse-server/commit/1bd804693c45130dad141ddc24a2305935b0e11e
