### ISSUE TITLE
FilesAdapter for OpenStack Swift?

### ISSUE THREAD

**Issue by doender** [ParsePlatform/parse-server#151]
Would anybody be interested in this (just like there is now a S3Adapter)? If this is the case I would like to work on this. 

Does anybody have experience with the following NodeJS Swift libraries:

- https://github.com/edge-is/ceph-swift
- https://github.com/feedhenry/openstack-storage

?

**Comment by gfosco** [comment]
Going to close this issue for lack of activity.  It would be cool if you made an npm module openstack adapter people could use, and we'd link to it in the wiki.  :+1:

**Comment by gowridev** [comment]
I am interested in this work @doender  could you please guide me in this regard
