### ISSUE TITLE
Mandrill email adapter

### ISSUE THREAD

**Issue by davimacedo** [ParsePlatform/parse-server#1513]
I've just developed a simple Mandrill email adapter:
https://github.com/back4app/parse-server-mandrill-adapter

I suggest you add the link here:
https://github.com/ParsePlatform/parse-server#email-verification-and-password-reset

Credits to @drew-gross because I used https://github.com/ParsePlatform/parse-server-simple-mailgun-adapter as baseline :)

**Comment by drew-gross** [comment]
Done! Since the README is just a file in the repo, you can also submit PRs to add community links :)
