### ISSUE TITLE
Implementing https on parse server.

### ISSUE THREAD

**Issue by sunilzs** [ParsePlatform/parse-server#1515]
Now that parse is opensource, how do I ensure my connection to parse and my android app is encrypted? I'm not using heroku or any other hosting services. But I'm deploying the server on an actual server in my professor's lab.

Could someone please tell me the procedure for implementing encryption using SLL and https  between the parse server and my android app.

**Comment by shehabix** [comment]
that's quite easy, create a normal https server (nginx), and create a local proxy to your parse app

**Comment by shehabix** [comment]
IMO this question should go on SO but follow something like this:
https://www.digitalocean.com/community/tutorials/how-to-run-parse-server-on-ubuntu-14-04
Check the nginx section

**Comment by sunilzs** [comment]
@shehabix Thank you so much man. Highly Appreciate it.
