### ISSUE TITLE
Would Anonymous Users essentially get locked out of their accounts after sessionLength expires?

### ISSUE THREAD

**Issue by noder199** [ParsePlatform/parse-server#1517]
If a user has an anonymous account on my service (and they do not fill in required login information such as email/password), is it true that after the sessionLength expires, they would essentially have no way of getting back into their account? Since my app does not enforce users to fill in account information unless they have to, I could imagine a case where a user has an account for x amount of time, uses the app regularly, and then gets locked out. I guess the best way to handle this (assuming the user is active) is to regularly send push notifications to users with only, say, 3 months left in their session's length. 

A more ideal solution would be to check if a session token is 'active' (say, the user logged into it in the last 3 months) when a token reaches its expiration, and if that is true, then extend its expiration. If not, then continue with deletion.

**Comment by drew-gross** [comment]
My suggestion would be to try to find this out yourself, by setting session expiry to e.g. 5 seconds in your development environment and seeing what happens.

Also you can modify the `expiresAt` of a session token in a Cloud Code function by using master key, or disable session expiry completely.
