### ISSUE TITLE
possible to use replica set for databaseURI ?

### ISSUE THREAD

**Issue by themichael123** [ParsePlatform/parse-server#152]
Hi Parse team, 

is it possible to use a replica set for the databaseURI ?

Thanks.

**Comment by themichael123** [comment]
Solved. This is possible.

**Comment by adamontherun** [comment]
@themichael123 I'm getting an error when trying to use a replica set from MongoLabs. What did you do to solve?

**Comment by themichael123** [comment]
We use compose.io for the mongoDB hosting. You should however check if the URI is formatted correctly i.e. no email adresses as username no "<" or ">" in the password etc. We also had to initialize the parse server,set the password etc. Hence, make sure to double check if it is actually the DB URI causing the issues.

**Comment by themichael123** [comment]
@adamontherun have a look here: https://github.com/ParsePlatform/parse-server-example/issues/40
