### ISSUE TITLE
File on files.parse.com (instead of files.parsetfss.com) do not load.

### ISSUE THREAD

**Issue by barnaclejive** [ParsePlatform/parse-server#1521]
Images hosted on **files.parse.com** are assumed to be "new since migration" and thus the parse-server generates a url pointing at **my** parse-server instead of parse.com's S3 url. These are older images, I assume before parse.com switched to the **files.parsetfss.com** server.

Newer images (though before migration) point to **files.parsetfss.com** and load OK.

Newer images (after migration) point to my server and load OK.

Example:

**parse.com URL:** (created a long time ago on parse.com)
http://**files.parse.com**/9e30bab0-73bc-44a6-b468-9e105179430a/db70e289-a9ef-4e0d-ab34-f096c424de41-image_main.jpg

**parse-server URL:** (does not actually exist on my S3, this file existed before migration)
http://petfetch-server.herokuapp.com/parse/files/petfetch_appid_debug/db70e289-a9ef-4e0d-ab34-f096c424de41-image_main.jp

**parse.com and parser-server both generate the correct URL for this image:**
https://**files.parsetfss.com**/9e30bab0-73bc-44a6-b468-9e105179430a/tfss-95a01ef5-b669-4221-8afe-18384bef442f-image_main.jpg

- [x ] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [ x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [ x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Merged master 4/16/16

**Comment by barnaclejive** [comment]
There is another report of this mentioned in #8 

> Seems to be a problem in FilesController.js when Parse Server checks wether to use parsetfss.com or adapter for a file:
> if (filename.indexOf('tfss-') === 0) {..
> I have old files on Parse that do not begin with 'tfss-', and they are wrongly sent to adapter.
> Looks like Parse Server does:
> filename = randomHexString(32) + '_' + filename;
> on any new files, so I guess a fix would be to check for that underscore, since it would never match old files.

**Comment by drew-gross** [comment]
cc @skinp
