### ISSUE TITLE
Reset Password on Azure hosted Parse Server

### ISSUE THREAD

**Issue by jamesytl** [ParsePlatform/parse-server#1522]
The tutorial [here](https://github.com/ParsePlatform/parse-server#email-verification-and-password-reset) taught to initialize through javascript. My question is do we must initialize this through js only or is it possible through java? Because I have initialized my parse connection through java and wish that I could continue with it. 

```
        Parse.initialize(new Parse.Configuration.Builder(getApplicationContext()).applicationId("XXXX").server("http://XXXX.azurewebsites.net/parse/").build()
        );
```

**Comment by drew-gross** [comment]
That is for the initialization of Parse Server, which is done in JavaScript. Your clients can continue to use Java.
