### ISSUE TITLE
Push: TypeError: Cannot read property 'device' of undefined

### ISSUE THREAD

**Issue by markuswinkler** [ParsePlatform/parse-server#1526]
I get this error message every time I send a push message (via the onesignal adapter) on the console.
parse-server 2.2.7
Target is iOS only and to a (user) channel.
Could that be related to issue [#1245](https://github.com/ParsePlatform/parse-server/issues/1245)?
```
error: error while sending push TypeError: Cannot read property 'device' of undefined
    at /Users/markus/ParseServer/node_modules/parse-server/lib/pushStatusHandler.js:81:20
    at Array.reduce (native)
    at Object.complete (/Users/markus/ParseServer/node_modules/parse-server/lib/pushStatusHandler.js:79:15)
    at /Users/markus/ParseServer/node_modules/parse-server/lib/Controllers/PushController.js:130:27
    at run (/Users/markus/ParseServer/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /Users/markus/ParseServer/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/Users/markus/ParseServer/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:14:5)
    at _combinedTickCallback (node.js:376:9)
    at process._tickDomainCallback (node.js:431:11)
```

**Comment by flovilmart** [comment]
Seems that the one signal adapter don't implement the push status correctly. I'll make a fix over there.

**Comment by flovilmart** [comment]
On a second thought, I don't think we can get a proper status from one signal, the fix will just let it go through.

**Comment by markuswinkler** [comment]
ok.
the messages themselves get sent, there is just the error message afterwards.

**Comment by fasa23** [comment]
Make sure you are logged in to your server as root user, i had the same issue and then I realized I was logged in as a user I created with root privileges.

**Comment by coolnalu** [comment]
is there a temporal fix?
