### ISSUE TITLE
How to add a log entry?

### ISSUE THREAD

**Issue by markuswinkler** [ParsePlatform/parse-server#1529]
Is there a way to add a custom entry to the server logs (info/error)?
I see the parse logs in the dashboard but I can't figure out how to add my own entry there.

**Comment by drew-gross** [comment]
Currently that mostly has logs from the server itself, so we don't have good docs for how to do logging from Cloud Code. The default logger is Winston, if that helps. If you figure out and want to help, please submit some docs improvements!

**Comment by blacha** [comment]
It's pretty common to expose a logging object inside the request object

eg restify's ``request.log`` http://restify.com/#request-api 

Then inside of cloud code you could then use ``request.log.info( .. )``

For now, I wrap all my cloud functions in another another function which adds ``request.log`` that output's it logs into [logentries](https://logentries.com/).
