### ISSUE TITLE
Need of additional authentication method on Google Play, Game Center

### ISSUE THREAD

**Issue by hl4hck** [ParsePlatform/parse-server#1530]
I am a develper of games using Unity3D, and mostly depend on log-in authentication for Google Play Game Services and Apple Game Center while the parse-server/authDataManager provide various authentication methods.

Could you add the Google Play and Apple Game Center authentication method?

**Comment by drew-gross** [comment]
You can actually use custom authentication to implement that yourself. If you make a robust implementation and want it to be part of `parse-server`, you can submit it as a PR. Thats how most of the existing ones got there :)
