### ISSUE TITLE
How can I old image file migration?

### ISSUE THREAD

**Issue by json-park** [ParsePlatform/parse-server#1531]
Hello~

I was setup a Migration Sever on AWS 

and also include code what S3 file upload code like below

![default](https://cloud.githubusercontent.com/assets/16973070/14592992/1d06c6f0-0560-11e6-951f-8de42259c509.png)

However I don't know what old image file migration

![2](https://cloud.githubusercontent.com/assets/16973070/14593044/c485c962-0560-11e6-833b-bc055b07a93f.png)

How can I migration?

**Comment by drew-gross** [comment]
Use a `fileKey` as suggested in the migration guide and docs.
