### ISSUE TITLE
`{"message":"unauthorized"}` when using JS SDK with Parse-Server

### ISSUE THREAD

**Issue by mindgrub-jkliphouse** [ParsePlatform/parse-server#1539]
#### Environment Setup

My issue is very similar to [this one](https://github.com/ParsePlatform/parse-server/issues/407).  

I'm using "parse-server": "^2.2.7" with "parse": "^1.8.3".

I forked the Parse-Server-Example and everything works fine locally and on Heroku with the Rest API.  As soon as I try to use the javascript sdk I get `{"message":"unauthorized"}`.

I've tried with and without a javascriptKey, with or without initializing parse, with and without useMasterKey = true.

#### Steps to reproduce

This curl works:

```curl -X GET \
  -H "X-Parse-Application-Id: myAppId" \
  -H "Content-Type: application/json" \
  http://localhost:1337/parse/classes/_User```

But this query gets `{"message":"unauthorized"}`:

    ```var User = Parse.User; //also tried Parse.Object.extend("_User");

        var query = new Parse.Query(User);
        query.useMasterKey = true; //tried it like this or by passing an object into find
        query.find().then(function(result) {
            if(result != null) console.log(JSON.stringify(result));
            else renderInvalidLogin(res);
        },
        function(error) {
            console.log(JSON.stringify(error));
            renderInvalidLogin(res);
        });```

#### Logs/Trace

No logs to trace.  I'm really at a loss, I posted on SO 2 days and no comments or answers.  So I'm posting here.  Thanks!

**Comment by drew-gross** [comment]
You can enable logging using `verbose: true` in the configuration of your server. Please do that and then post any logs you see.

**Comment by mindgrub-jkliphouse** [comment]
I've done that and nothing changes.  No new logs, just {"message":"unauthorized"} returned from the error function of the above query.

**Comment by drew-gross** [comment]
In that case the error is probably not in Parse Server. Check your SDK initialization to make sure you the right server URL and keys.

**Comment by mindgrub-jkliphouse** [comment]
```Parse.initialize('myAppId', 'unused', 'myMasterKey');
Parse.serverURL = process.env.SERVER_URL || 'http://localhost:1337/parse';```

I'm not using a JS key.  Is this a good init?

**Comment by drew-gross** [comment]
As long as that URL, app ID, and master key are all actually correct, then yes that seems fine.

**Comment by mindgrub-jkliphouse** [comment]
The error is coming from middlewares.js.  The `req.body` contains the `_ApplicationId` but it never gets parsed at line 50 because `req.body` is a string.  

At line 57 `req.body._applicationId` is undefined and the invalidRequest is returned.

**Comment by drew-gross** [comment]
That shouldn't be the case. Can you post the JS SDK version you are using and the Parse Server version?

**Comment by sdf611097** [comment]
Have you try setup jskey on parse-server and init it in jssdk? 
This error usually cause by keys not matched

**Comment by mindgrub-jkliphouse** [comment]
I'm using "parse-server": "^2.2.7" with "parse": "^1.8.3".  I tried it with the jskey and still the same.

**Comment by mindgrub-jkliphouse** [comment]
Looks like the only way I can access is through the REST api. 

The Parse-Dashboard is unauthorized as well.

**Comment by drew-gross** [comment]
Those should work. How did you find out where the error is if you can't see any logs?

**Comment by mindgrub-jkliphouse** [comment]
I stepped through with the debugger ...

Well, the problem has been found.  The 'body-parser' middleware I was using seems to have been mangling the requests.  

The jssdk and parse-dashboard are working.

I appreciate your time.
