### ISSUE TITLE
Is parse-server reliable for a new project?

### ISSUE THREAD

**Issue by francocorreasosa** [ParsePlatform/parse-server#154]
Hi Parse Team and contributors,

I was planning to start a new project on Hosted Parse, but due the Parse shutdown I'm looking for other alternative. 

What do you think? May I use ParseServer?

Thanks

**Comment by christianmarth** [comment]
I'm currently in the process of migrating all my existing projects and clients to parse server.

For a new project I would recommend and still use the existing parse.com as the back as this will still be active for 12 months then migrate to parse server in around say April after some of the initial bugs have been ironed out and the web UI is added.

**Comment by francocorreasosa** [comment]
Thanks, I'm also migrating my projects into a own-hosted MongoDB Database, and I will keep Parse hosted till the bugs and WebUI is added. 

Thank you.

**Comment by gfosco** [comment]
We'll do our best to get this rock-solid as soon as possible.  I don't think that will take long at all.  Thanks for your patience and support!
