### ISSUE TITLE
Hiding app_id in SimpleMailgunAdapter 

### ISSUE THREAD

**Issue by Jinoooo** [ParsePlatform/parse-server#1546]
I was able to successfully migrate my app to AWS ELB.  Many thanks to Parse Team for making it possible!!
One issue I am facing now is the fact that SimpleMailAdapter will reveal the app_id in the url.
Is there any solution/alternative to hide the app_id like current MailAdapter in parse.com?

For comparison here is the confirm email address link from parse.com

> http://xyz.mycompany.com?link=%2Fapps%2Fmyapp--3%2Fverify_email&token=3TkfucuAJOivCT8oz4jrNpvg3&username=ooo%40mycompany.com

vs. the following from SimpleMailAdpater

> http://xyz.mycompany.com/parse/apps/APPLICATION_ID/verify_email?token=yu1rRBPYumEzhELpS8PXxZw0b&username=aws%40mycompany.com

Does the following provides some sort of security for the rest of the API Calls?  From doc. in github:  
> Client key options
> The client keys used with Parse are no longer necessary with Parse Server. If you wish to still require them, perhaps to be able to refuse access to older clients, you can set the keys at initialization time. Setting any of these keys will require all requests to provide one of the configured keys

- [x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup 
ParseServerExample in AWS ELB
"version": "1.4.0"

#### Steps to reproduce
Setup mailGun account
Config parseServer emailAdapter

#### Logs/Trace
The app_id is part of the url in the email generated by parse_server for both email validation & password reset.

**Comment by drew-gross** [comment]
Client keys are not necessary but an app ID is still necessary. App IDs are expected to be public and are typically distributed in your app's binary and can easily be seen with a network sniffer.

**Comment by Jinoooo** [comment]
Using https should make it harder to sniff the app-Id on mobile apps.
You don't want to provide a naked app-id that easily on email.   And I think that's why parse.com is not including app-id in the link.
There should be a way to remove the app-id!

**Comment by Jinoooo** [comment]
This would be an obvious security risk.  I don't want to advertise the app-id in an email.

**Comment by drew-gross** [comment]
No, the app ID is not a secret. There is no reason to hide it, and in fact it is impossible to hide it even if you are not using email verification.

**Comment by Jinoooo** [comment]
Just curios to know why/how parse.com is not exposing the app-id in verify email/reset-password.   Any ideas?

**Comment by drew-gross** [comment]
Parse.com uses the app slug instead. Some sort of identifier for the app is necessary, and there is no slug in Parse Server so we use the app id.

**Comment by Jinoooo** [comment]
Thanks Drew for clarification.

**Comment by drew-gross** [comment]
Client keys and app ids are somewhat redundant in Parse Server, you don't really need both. HTTPS is a very good idea though.

**Comment by awkvi** [comment]
A team member uses ParseServer for a hackathon and we just felt the app-id is not required in email link.  There are probably other ways via cloud code but here's a quick hack.

[Note per drew-gross: This does NOT secure parse.  Just a cosmetic that avoid naked app-id.]
[More on Security: https://docs.parseplatform.org/js/guide/#security]

2 files in ParseServer were changed:
lib/Config.js
lib/Routers/PublicAPIRouter.js

codes: 
1) https://github.com/awkvi/parse-server/blob/ffd2bd767a8379e99a99e892f13adb4b5e546a3d/src/Config.js
2) https://github.com/awkvi/parse-server/blob/5344c7a6b2d8d2c04a36ecd62f63766744c7e5a5/src/Routers/PublicAPIRouter.js

Summary of fix: (a) uses process.env.APP_ID instead, and replace :appId with config; (b) exclude APP_ID when stringify params. (c) show invalid_link if choose_password failed. 

Links in email after change:
1) Verify_Email
https://servername.domain.com/parse/apps/config/verify_email?token=BCaOufMeQgB25XcbKjRBS2rw&username=john%40domain.com
2) Reset_Password
https://servername.domain.com/parse/apps/config/request_password_reset?token=Dizv9Ot0hz84Xk3nkjaEyjdKT&username=jane%40domain.com
  
Did simple testing but could do more.  Let me know if you detect any bugs or security issues.
Not familiar to do a PR/CI.  If it's useful, please help to commit to branch so someone else can benefit :)

Regards
Tron - vi the best editor in single-user mode.
