### ISSUE TITLE
Invalid Link with password reset

### ISSUE THREAD

**Issue by ribads** [ParsePlatform/parse-server#1549]
I have been having issues with the emailAdapter. I have it configures using the maligun with my sample code as below

```
var api = new ParseServer({
    databaseURI: '',
    cloud: './cloud/main.js', // Provide an absolute path
    appId: 'XXXXXXXXXXXXX',
    masterKey: 'XXXXXXXXXXXXX',
    push: {...},
    fileKey: 'xxx-x-xx-xxx-xx-xxxx,
    serverURL: 'https://someserveron.herokuapp.com/parse',
    appName: 'mytoddlr',
    verifyUserEmails: true,
    publicServerURL: 'https://someserveron.herokuapp.com/parse',
    emailAdapter: {
        module: 'parse-server-simple-mailgun-adapter',
        options: {
             apiKey: 'key-some-key-value',
             domain: 'sandbox.mailgun.org',
             fromAddress: 'no-reply@domain.com'
             }
    }
});
```

The reset password email get sent get called but on clicking on the mail. All i get is a an invalid link result.
Same also for the account verification email that is sent to the user on signup.

I have been having this issues for the past couples of days now and i just tried testing with the v2.2.7 of the parse-server but still not luck.

Is my implementation wrong or is their something am missing.

**Comment by drew-gross** [comment]
Probably you are missing something. Make sure you aren't using any path rewriting anywhere. If you check that and still have issues, post the request body and response from the server when you click the link.

**Comment by ribads** [comment]
Thanks @drew-gross. Apparently, the error was cause by some path related issues.
Fixed it now. Thanks

**Comment by ksrajput** [comment]
@ribads , what you do for fix this error, im getting still same error

**Comment by ribads** [comment]
@ksrajput I was able to resolve the issues after realigning my URL i.e serverURL and publicServerURL.
Testing was a bit of a challenge. Apparently my password reset was sent locally referencing remote URI that wasn't live on the remote server.

**Comment by ksrajput** [comment]
@ribads thanks a lot buddy:)

**Comment by tanzeelrana** [comment]
I get this error after I enter the new password for some reason
