### ISSUE TITLE
Network connection fails on 4G LTE only

### ISSUE THREAD

**Issue by mustermania** [ParsePlatform/parse-server#1551]
We are migrating from api.parse.com to parse server hosted in AWS.  We have been QAing prior to submission and have one big bug we can't solve for.  On _user sign up and sign in tasks, on 4g LTE we frequently are getting Network connection failed or The request timed out messages in the console.  We have run the task and curl'd the server to get a hello world response when we experience the network connection errors; typically the server responds to our hello world request.  On wifi and 3g, we do not experience any problems.

Here is a 4G LTE log with username/password redacted:

[iOS_Console_mmusterman’s_iPhone_4G-sign-in-to-your-account.txt](https://github.com/ParsePlatform/parse-server/files/226375/iOS_Console_mmusterman.s_iPhone_4G-sign-in-to-your-account.txt)

Same task over wifi:
Apr 19 09:35:08 mmustermans-iPhone locationd[72] <Notice>: scan result, count, wait, 0, retry, 0, error
Apr 19 09:35:11 mmustermans-iPhone summitsync[486] <Warning>: Can't find keyplane that supports type 5 for keyboard iPhone-PortraitTruffle-PhonePad; using 452364516_PortraitTruffle_iPhone-Complex-Pad_Default
Apr 19 09:35:20 mmustermans-iPhone summitsync[486] <Warning>: Start Login with username redacted
Apr 19 09:35:20 mmustermans-iPhone summitsync[486] <Warning>: redacted/redacted
Apr 19 09:35:21 mmustermans-iPhone summitsync[486] <Warning>: Login success with username redacted
Apr 19 09:35:21 mmustermans-iPhone summitsync[486] <Warning>: Next => Log in chat with username  redacted

We've been all over SO, github, google groups trying to find a solution.  No luck, we've seen some people who have an issue with 4g and 3g.  However, for us, 3g is not a problem, only LTE.

Our env:
aws elastic beanstalk with elastic load balancer
node.js v4.3.0 t2.small instance running
mongodb v3.2.3 replica set on t2.small instance
latest parse sdk

devices we've tested:
iphone 6 ios 9.3.1
iphone 6+ ios 9.3.1
iphone 6S ios 9.2.1
iphone 6 ios 9.1
iphone 6+ ios 9.3.1
iphone 6S+ ios 9.3.1

Any help here would be great.

**Comment by drew-gross** [comment]
I'm not sure if we'll be able to help with this one. It looks like your request is timing out, but it's not clear why. Do you have any Parse Server logs?

**Comment by mustermania** [comment]
[nodejs.txt](https://github.com/ParsePlatform/parse-server/files/226809/nodejs.txt) this log contains both 4g and wifi test data.  Where ever there are errors, it is 4g, whereever no errors, it is wifi.  And whereever you see 'hello' the app was having poor load times, so we requested the server to respond with the word hello from command line to see if it was still running.

**Comment by drew-gross** [comment]
The log seems to show a connection timeout between your Parse Server and your database. Try connecting to a MongoDB that is closer to your Parse Server, or upgrading your hardware, or generally debugging the Parse Server <--> MongoDB interaction.

**Comment by mustermania** [comment]
we upgraded ec2 instance for the servers running parse server and so far, it seems to have solved.  it is very strange though, that for 9 days of testing, we never had a problem on 3G or wifi, but we had a 90%+ connection fail on LTE....

**Comment by drew-gross** [comment]
That does seem very strange to me. It could be that LTE is fast enough that requests come in quick succession to your Parse Server, thus causing it to be overloaded. If you discover any additional issues or do any profiling, please let us know.
