### ISSUE TITLE
Parse LiveQuery for Android 

### ISSUE THREAD

**Issue by xxzulaxx** [ParsePlatform/parse-server#1555]
Hello, 

Does anyone know when will Parse LiveQuery for Android be available?  It is one of the last items before i am done with migration.  If not soon, what are alternatives?

**Comment by flovilmart** [comment]
This is a question for the android repository https://github.com/ParsePlatform/Parse-SDK-Android

**Comment by TGIO** [comment]
follow this [issue](https://github.com/ParsePlatform/Parse-SDK-Android/issues/437) in corresponding repository
