### ISSUE TITLE
dynamically configure Parse instances

### ISSUE THREAD

**Issue by bigdoghung** [ParsePlatform/parse-server#1556]
Has anyone developed an API that would dynamically configure Parse instances?

**Comment by flovilmart** [comment]
this is not provided at the moment, but a PR would be welcome.

**Comment by bigdoghung** [comment]
Didn't Parse.com already have this available?

**Comment by drew-gross** [comment]
Yes but it also was substantially more complex and resource hungry as a result, and would have required many expensive servers to run a single app.
