### ISSUE TITLE
PFFile migration

### ISSUE THREAD

**Issue by Samigos** [ParsePlatform/parse-server#1557]
Hey everyone! Because I'm relatively new to parse and generally to servers-dbs, I really need your help!

I'm about to migrate my data to a new database and I heard that it's impossible to migrate existing files (photos in my case) from parse to another parse-server! Is that true? If not, how is it done?

Thanks in advance!

**Comment by drew-gross** [comment]
For now, your files can stay where they are and still be accessible by your own Parse Server, as long as you use the `fileKey`. Check the docs for how to do that.
