### ISSUE TITLE
select() constraint is not applied to included objects

### ISSUE THREAD

**Issue by rahilsharma** [ParsePlatform/parse-server#1567]
I am running this same query from parse.com and on my local parse server . 

```
var messageQuery = new Parse.Query("Message");
    messageQuery.descending("updatedAt");
    messageQuery.include("channelId");
    messageQuery.select("channelId");
    messageQuery.select("channelId.exchange");
```
Channeld is pointer field to my other document.
On parse.com server this query works and return result with only exchange field and on parse-server it selects complete channelId document and prints everything.

**Comment by rahilsharma** [comment]
Also select works when i am not expanding any pointer fields.

**Comment by hramos** [comment]
Can you include more information, such as example responses that clearly show the difference?

Please refer to [this issue](https://github.com/ParsePlatform/parse-server/issues/1271) for an example of a great bug report.

**Comment by MasaGon** [comment]
I got same issue with Parse Server, when migrating from Parse.com.

This works fine for getting whole sender fields of a message.

    var messageQuery = new Parse.Query(Message);
    messageQuery.descending('createdAt');
    messageQuery.limit(1);
    messageQuery.include(['sender']);
    messageQuery.select(['type', 'body', 'isRead', 'sender']);
    return messageQuery.first();

But if I restrict select parameter to 'sender.phone' from 'sender' like this,

    var messageQuery = new Parse.Query(Message);
    messageQuery.descending('createdAt');
    messageQuery.limit(1);
    messageQuery.include(['sender']);
    messageQuery.select(['type', 'body', 'isRead', 'sender.phone']);
    return messageQuery.first();

no sender information is acquired.

**Comment by Poordeveloper** [comment]
really a big issue, can only work around on cloud side instead now.

**Comment by Ishimilated** [comment]
I have the same problem. It worked great on parse.com, but not on the parse server.

**Comment by hramos** [comment]
It seems like the issue is clear at this point: the select() constraint on Parse Server only works for fields on the top level object. It seems like there's interest in replicating parse.com's select() behavior on Parse Server. If someone wants to send a PR to add this enhancement to Parse Server we can take a look.

**Comment by ossamaweb** [comment]
+1

**Comment by dbloembe** [comment]
I'm still having trouble with this same issue. Was this ever addressed?

**Comment by flovilmart** [comment]
@dbloembe please open a new issue with all relevant informations
