### ISSUE TITLE
[2.2.7] Logs path is absolute?

### ISSUE THREAD

**Issue by iStopped** [ParsePlatform/parse-server#1572]
I'm using the latest versione of Parse-Server and I keep getting this error:

```
Error: EACCES: permission denied, open '/logs/parse-server.info.2016-04-20'
    at Error (native)
``` 

It seems that the logs path is absolute and not relative to the project, and the logs are created in the absolute path /logs/. My Parse instance is running through foreverjs, maybe this helps?

**Comment by drew-gross** [comment]
It is. use __dirname in your config to construct an absolute path to a folder in your Parse Server project.

**Comment by iStopped** [comment]
Not fixed, I set the `logsFolder` parameter to the absolute path of my Parse instance but Parse still creates the /logs directory in the root of the file system.

**Comment by flovilmart** [comment]
Where do you deploy? What's the path to you logs folder? What's the behaviour locally?

**Comment by iStopped** [comment]
I'm using Parse with expressjs on a virtual machine running the latest Ubuntu LTS. The logs path is passed through the constructor of ParseServer. The configuration is attached, personal data is blacked out. As I said before the logsFolder is ignored and new logs are created at /logs (file system root).




<img width="515" alt="schermata 2016-04-21 alle 14 24 59" src="https://cloud.githubusercontent.com/assets/910971/14708766/3e84fde6-07cd-11e6-8bb5-ec2b0f505844.png">

**Comment by flovilmart** [comment]
I'll have a look

**Comment by iStopped** [comment]
Can you reopen this issue then?

**Comment by huang1196** [comment]
Maybe the logs folder is created by foreverjs.

I start my server by:

`forever start index.js -l /home/abc-user/logs/abc.log`

**Comment by iStopped** [comment]
Nope, here is the error with my instance running as www-data

`fs.js:794
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: EACCES: permission denied, mkdir '/logs'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at configureLogger (/var/www/xxxx/node_modules/parse-server/lib/logger.js:71:18)
    at Object.<anonymous> (/var/www/xxxx/node_modules/parse-server/lib/logger.js:80:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
error: Forever detected script exited with code: 1`
