### ISSUE TITLE
No Reachable Server Error when migrate our parse app using mongodb URI  

### ISSUE THREAD

**Issue by komalkk** [ParsePlatform/parse-server#1578]
I am using mongodb version 3.0.11 on ubuntu server, but when I migrate our existing parse app in aws for production, after installing mongodb on ubuntu server when click on migrate button after changing the mongodb uri with "mongodb://username:password@IP Address:27017/Database name" it shows the error
"No Reachable Server". 
I am using below link for migration - 
http://julienrenaux.fr/2016/01/29/complete-parse-server-migration-guide/
also please insure me that this link is good for production purpose using mongodb or any other is useful.

please help me for resolving the issue.

**Comment by benishak** [comment]
check security group, make sure that the ports are open in inbound connections

**Comment by hramos** [comment]
I'm closing out this issue as it is not related to Parse Server. For migration assistance, please visit https://parse.com/help#report

**Comment by komalkk** [comment]
Thanks, benishak 
Yes this issue is related to security group, I had connected the 27017 port to  EC2 security group, therefore I am not able to connect it and facing this error - "No Reachable Server".
after connecting the port 27017 to anywhere, I am able to connect and migrate the app.
