### ISSUE TITLE
File Upload destination, database, and server.

### ISSUE THREAD

**Issue by TAProgramming** [ParsePlatform/parse-server#158]
From what I gather, the current file upload facility in Parse Server saves a file to Hosted Parse (the same way it always has been), however work is underway for it to be saved to Amazon S3 (with the gridstore adapter #113 ).
This is while my database is hosted somewhere else (eg mongolab) and my instance of Parse server is hosted in another place (eg heroku).
The cost and workload of having 3 separate hosting paths to maintain is a little extreme for small businesses like mine.
I have seen that Google Datastore is a proposed option for database implementation in #20 .
What I would like to see is perhaps the option or capability of having my File Storage, NoSQL Database and Parse Server all on Google services (Cloud Storage, Datastore, App Engine) for example.
This minimises cost and hassle on my part as a client developer with limited backend experience.
How feasible is this to be implemented within the phasing out year?
Thanks. :)

**Comment by gfosco** [comment]
The default in parse-server is to store the files in GridStore, which is part of your Mongo installation.  See GridStore.js.  S3 has just been added as an adapter.  We welcome other file adapters to support other use cases.  I expect many to be added in the near future.
