### ISSUE TITLE
We were unable to commit your migration. Please try again.

### ISSUE THREAD

**Issue by wanhappy5** [ParsePlatform/parse-server#1594]
Dear Parse.com

I will to try migrate our database to new database server, in migrate is complete and the database server successfully created. but i try to finalize this can't because show
 "We were unable to commit your migration. Please try again."

this screenshot for the error, 
<img width="951" alt="screen shot 2016-04-22 at 7 18 20 pm" src="https://cloud.githubusercontent.com/assets/17872468/14741287/725c3b96-08bf-11e6-926f-e374824e15cf.png">
<img width="549" alt="screen shot 2016-04-22 at 7 18 10 pm" src="https://cloud.githubusercontent.com/assets/17872468/14741289/77a968b2-08bf-11e6-85c9-0e83bb8d8399.png">

i hope you can help me out.

Thank you

**Comment by drew-gross** [comment]
For issues with the migration process, please use [parse.com/help]()
