### ISSUE TITLE
User objects not exploded in cloud function params

### ISSUE THREAD

**Issue by codebreach** [ParsePlatform/parse-server#1598]
- [x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).
- [x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.
- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
localhost
node 3.6
mongo 3.0

#### Steps to reproduce
```js
Parse.User.extend({
  method: function() { return 'hello world'; }
});
Parse.Cloud.define('customFunction', function(request, response) {
  response.success(request.user.method());
}); 
```

When called with a valid session token,
`customFunction` will return `hello world` on Parse Cloud Code
`customFunction` will throw `TypeError: request.user.method is not a function` on parse-server

**Comment by aaronbannin** [comment]
Perhaps you need to init a User before calling request.user.method()?

**Comment by steven-supersolid** [comment]
We noticed this too but worked around it by either creating a new User with request.user.id or by querying the request.user. Not sure what the official stance is on this.

We extend as follows:
```
var User = Parse.Object.extend('_User', {
...
var query = new Parse.Query(User);
```

**Comment by codebreach** [comment]
I think the official stance should be to match the behavior on hosted Parse Cloud Code.

In that case `handleCloudFunction` can be updated to `user: new Parse.Object('_User', req.auth.user)`

I can make a PR if the owners can confirm the expected behavior

**Comment by steven-supersolid** [comment]
I recommend making the PR anyway as it will have higher visibility and get things going

**Comment by codebreach** [comment]
This might we WAI
I couldnt get this test to fail:
https://github.com/drinklynk/parse-server/commit/136ee6def5f5fff84b1554a307943d54429072c7

**Comment by drew-gross** [comment]
Yes, we are trying to match Parse.com behaviour in as many cases as we can. If you can submit a PR that gets us closer to Parse.com behaviour that would be much appreciated :)

**Comment by codebreach** [comment]
So I resolved this one and just wanted to make a note of it in case someone comes looking later.
The issue was that there were TWO instances of Parse that were in my `node_modules` one under root and one under `parse-server/node_modules`

might be useful to have a warning when this is happening
