### ISSUE TITLE
Future of parse-server?

### ISSUE THREAD

**Issue by yemaw** [ParsePlatform/parse-server#16]
Will Parse team going to actively maintain and develop Parse Server and Parse SDKs after 2017? Please let us know the details. This is very important for us to make decision, whether we should host Parse Server our-self or to change to another service.

**Comment by gfosco** [comment]
That is the plan.  I'll repost what I said in another issue:

The SDKs aren't going anywhere, ever, and will continue to be updated.. not only for bug fixes and security, but there are still some features in the works. Eventually, I believe we & the community will evolve the Parse server and client SDKs beyond what was previously capable with just Parse.

Adding: It doesn't have to be just us at Parse working on them.  I expect the community to be submitting things, and for us to collectively discuss and merge things.  Parse can grow now.
