### ISSUE TITLE
Where is the client code?

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/parse-server#160]
Where  is the client source code, for example, Javascript sdk code? I think the original client code is only connected to **Parse Server** in parse.com. Am I right?

**Comment by gfosco** [comment]
The SDKs are all open source and now allow changing the API server address.  

In JavaScript you can set for example:

```
Parse.serverURL = 'https://myapp.herokuapp.com/parse';
```

You can find the open source SDK repositories here:  https://github.com/ParsePlatform named Parse-SDK-***
