### ISSUE TITLE
getting message through heroku url "Make sure to star the parse-server repo on GitHub!" though for /parse "unauthorized". Is my app running fine?

### ISSUE THREAD

**Issue by saurabhkhare2004** [ParsePlatform/parse-server#1602]
I  am getting a message through heroku url "Make sure to star the parse-server repo on GitHub!" instead of " i dream of a website" though for /parse "unauthorized".  which is what is required. Is my app running fine? However this is am empty app and is just meant for test. Please respond.

Regards

**Comment by gateway** [comment]
This means your parse server is up and running..  I recommend going though these [videos](http://blog.parse.com/learn/parse-server-video-series-april-2016/), it might help out to what ever your question is.

**Comment by hramos** [comment]
Working as expected. This is actually a `parse-server-example` issue. It used to display the "I dream of being a website" message, but now it displays "Make sure to star the parse-server repo on GitHub!" instead.
