### ISSUE TITLE
Log each Cloud Code call in a way that is similar to hosted Parse.com

### ISSUE THREAD

**Issue by yuzeh** [ParsePlatform/parse-server#1603]
Is it currently available right now? If not, is there a plan to implement it?

**Comment by blacha** [comment]
Right now you will have to use your own logger and wrap your cloud calls.

I currently have it set up something like this

```javascript
function defineCloudFunc(name, func) {

Parse.cloud.define(name, function(req, res) {
    Log.info('Called Cloud code "' + name + '"');
    func(req, res)
}

}
```

We are still working on improving logging, There was a pull request just put into master about exposing the logging adapter  as ``request.log`` so you can use that to log inside of your cloud functions and triggers (beforeSave, afterSave etc..)

**Comment by yuzeh** [comment]
I did not think about this workaround. Cool!
