### ISSUE TITLE
Parse table relation column not showing after migration

### ISSUE THREAD

**Issue by vikas230428** [ParsePlatform/parse-server#1607]
The relation column which is being created in parse tables from PFRelation class is not showing anymore on mongodb after migration.

Kindly please provide any details how would that work or show?

**Comment by flovilmart** [comment]
Relations are stored in a Join table, not on the objects. Do you see tables starting with _Join?

**Comment by vikas230428** [comment]
Yes _Join with table  name shown but would that work as before with PFRelation class??

**Comment by flovilmart** [comment]
That's how it's always been
