### ISSUE TITLE
How to call cloud code from localhost parse server?

### ISSUE THREAD

**Issue by atom2ueki** [ParsePlatform/parse-server#161]
I'm migrating my cloud code to my localhost parse server, follow the guide copy cloud code to the cloud/main.js, but how can I call the defined function inside?
```
curl -X POST \
-H "X-Parse-Application-Id: myAppID" \
-H "X-Parse-REST-API-Key: myRestApiKey" \
-H "Content-Type: application/json" \
-d '{}' \
http://localhost:5000/parse/1/functions/hello
```

**Comment by gfosco** [comment]
Drop the /1/ and this should work.  /1 was the path on api.parse.com, but in parse-server the default is just /parse

`http://localhost:5000/parse/functions/hello`

**Comment by atom2ueki** [comment]
@gfosco I see, it works, thanks

**Comment by oyvindvol** [comment]
I am getting successful cloud function calls also when providing a wrong REST Api key. Is this supposed to happen?
