### ISSUE TITLE
Installing MongoRock on AWS

### ISSUE THREAD

**Issue by mayankverma** [ParsePlatform/parse-server#1611]
I am trying to install MongoRock on AWS by following instructions included here.
https://github.com/ParsePlatform/parse-server/wiki/MongoRocks

When I try to configure storage and use the command 

"**sudo mdadm —create /dev/md0 --level=stripe /dev/xvdb /dev/xvdc"**, I get error:
**mdadm: An option must be given to set the mode before a second device
       (/dev/md0) is listed**

When I add double dash (-) to create, 
"sudo mdadm **--**create /dev/md0 --level=stripe /dev/xvdb /dev/xvdc", I still get same error
**mdadm: An option must be given to set the mode before a second device
       (/dev/md0) is listed**

And after some googling, seems like "--raid-devices" is missing... so I added that
"**sudo mdadm --create /dev/md0 --level=stripe --raid-devices=2 /dev/xvdb /dev/xvdc**" and get this error.
**mdadm: cannot open /dev/xvdb: No such file or directory**

Anyone here has been successfully able to install mongoRock on aws?
Any help is appreciated... :)

**Comment by flovilmart** [comment]
Are those drives mounted?

**Comment by mayankverma** [comment]
ya for some reason it didnt.. I had to manually create the instance and add them...it worked after that.. 👍

**Comment by flovilmart** [comment]
alright then!
