### ISSUE TITLE
Parse-server 2.1.7 - request.user returns null/undefined

### ISSUE THREAD

**Issue by benishak** [ParsePlatform/parse-server#1619]
I have a cloud afterSave/ ... function that is being called by the user from the App, inside the function I call 

`var currentUser = request.user;`

but it returns undefined

On Parse.com I used `Parse.User.currrent()` which worked perfectly

**Comment by drew-gross** [comment]
We have lots of passing test cases that cover these features. Can you post some code that reliably reproduces your issue? Ideally as a test case we can add to our test suite.

**Comment by benishak** [comment]
in AfterSave
a User comment or like, the record is saved in the collection, afterSaving it, afterSave will read the record and send push notification ... etc, inside the afterSave I call `request.user` which returns null. the record contains a column called "fromUser" so right now i'm using `currentUser = request.object.get("fromUser");`

**Comment by benishak** [comment]
maybe `request.user` works only on the `_User` class ?

**Comment by hramos** [comment]
`request.user` will only point to a `_User` object when the function is triggered by an authenticated user.

Can you post some code that demonstrates the issue? 

Please refer to [this issue](https://github.com/ParsePlatform/parse-server/issues/1271) for an example of a great bug report.

**Comment by RafaRuiz** [comment]
Hi @hramos please take a look to #775. I wrote the whole code I'm using and still there's an issue
