### ISSUE TITLE
Best practice for running Parse Server in background on Ubuntu

### ISSUE THREAD

**Issue by christianmarth** [ParsePlatform/parse-server#162]
Looking for the best practice to run parse the express.js parse server in the background in Ubuntu using something like systemd, forever or mon

**Comment by gfosco** [comment]
I like `forever`

```
npm install -g forever
forever start index.js
forever restart index.js
forever stop index.js
forever logs
```

**Comment by duergner** [comment]
I normally use `supervisord` on ubuntu for easily starting services without the need to write custom start/stop scripts

**Comment by christianmarth** [comment]
`forever` is good although especially for development but in production If the server is restarted it won't start up the parse server instance... I'll have a look at `supervisord`

**Comment by iulianvarzaru** [comment]
You can also try [PM2](http://pm2.keymetrics.io/docs/usage/quick-start/), you can add it at startup and it can also handle reloading files after changing them.

**Comment by francocorreasosa** [comment]
I use PM2 in cluster mode. Totally recommend it :+1:

**Comment by drew-gross** [comment]
Closing as this is a week old and some solid solutions have been provided.
