### ISSUE TITLE
Saving Parse.File object gives 105 error with RevocableSession sessions enabled

### ISSUE THREAD

**Issue by nauman74** [ParsePlatform/parse-server#1621]
Hi, 

On Parse server 2.2.7, saving a Parse.File object using the latest Javascript SDK 1.6.14  is giving the following error: 105 Invalid key name: _RevocableSession.

This only happened after I enabled RevocableSessions in the javascript code with this line 
Parse.User.enableRevocableSession(). Using the legacy session mode I can save files without errors.

**Comment by drew-gross** [comment]
This is a known issue, it will be fixed in the next version.

**Comment by nauman74** [comment]
OK, thanks for the update
