### ISSUE TITLE
request.user = undefined after signing up  anonymous user

### ISSUE THREAD

**Issue by cyu** [ParsePlatform/parse-server#1623]
#### Environment Setup
Heroku + mLab Setup

#### Steps to reproduce
1) Login a user as anonymous
2) Sign Up anonymous user with username and password
3) Call a cloud function that references `request.user`.  The reference will be `undefined`

I was able to reproduce this in an example app and server:
- https://github.com/cyu/ParseAnonSignUpTest/blob/master/ParseAnonSignUpTest/AppDelegate.m
- https://github.com/cyu/parse-anon-signup-test

In the example, tap 'Create Anonymous User' to create the anonymous user.  After the anonymous user is created, the cloud function is called and executes successfully (see output in the log).  Next, enter a username and password in the text fields and tap 'Signup'.  The Signup executes successfully, but the cloud function returns undefined for the user.

#### Logs/Trace

```
2016-04-25 12:35:04.914 ParseAnonSignUpTest[81250:7698959] login successful: G8599pHNMW
2016-04-25 12:35:04.914 ParseAnonSignUpTest[81250:7698959] running cloud function
2016-04-25 12:35:05.002 ParseAnonSignUpTest[81250:7698959] cloud function result: Hi, [object Object]
2016-04-25 12:35:12.592 ParseAnonSignUpTest[81250:7698959] sign up succeeded
2016-04-25 12:35:12.592 ParseAnonSignUpTest[81250:7698959] running cloud function
2016-04-25 12:35:12.667 ParseAnonSignUpTest[81250:7698959] cloud function result: Hi, undefined
```

**Comment by drew-gross** [comment]
Which version of Parse Server are you using? There have been some bugfixes in recent versions.

**Comment by cyu** [comment]
@drew-gross v2.2.7

**Comment by cyu** [comment]
Reviewing the code it looks like a fix has been checked into master.  How would I go about building a package of what's in edge so I can test it?

**Comment by cyu** [comment]
I was able to figure how to run the edge parse server in my test and it looks like this issue still exists.  Doing my best to figure out what's going on in both the Node server and in the iOS SDK, it looks like the server is removing the session on any update (https://github.com/ParsePlatform/parse-server/blob/master/src/RestWrite.js#L332).

Looking at the clear session code, it looks like we only want to do this when the user resets their password, but instead it's happening on every user update (https://github.com/ParsePlatform/parse-server/blob/master/src/RestWrite.js#L423).  It also means I can workaround this issue by setting `revokeSessionOnPasswordReset` to `false`

**Comment by batkov** [comment]
Approved that I had such thing on 2.2.10 and iOS, and it is gone after I set revokeSessionOnPasswordReset to false.

Also it was not anonymous login, but normal relaunch of app with loginned user.

**Comment by drew-gross** [comment]
Sorry for the late response, I lost track of this bug after I went on vacation.

The lines you are pointing out don't delete the session, they only clear out the cache, so I don't think thats an issue.

To confirm, the issue seems to be that if you first sign up anonymously, then sign up the same user with username/password, the sessions get revoked (if `revokeSessionOnPasswordReset` is set) when you would expect them not to get revoked?

**Comment by cyu** [comment]
Reviewing the latest changes, I think my particular issue has been resolved.  I don't have time to test to confirm though.

**Comment by drew-gross** [comment]
OK, I'm going to close this then. If either of you have more problems, please open a new issue.
