### ISSUE TITLE
Is there a way to implement scheduled push?

### ISSUE THREAD

**Issue by baymitchell12** [ParsePlatform/parse-server#1628]
Scheduled push is crucial to many applications. I know that scheduled push is not currently supported on parse-server, but I am wondering if there is a way to implement it now OR when it might be supported (scheduled push implementation is listed under future improvements).

**Comment by hramos** [comment]
As with scheduled background jobs, the best way to implement scheduled push notifications on Parse Server is to use a cron job or your favorite scheduling npm.

**Comment by baymitchell12** [comment]
@hramos I have an application in which users must send other users information which they will be notified about in the future. The time intervals aren't always the same and users can send the information whenever they please. I don't think a scheduling npm is applicable considering that the time intervals are randomized and users can send the information at any time. This task was easily accomplished with **push_time** in cloud code but that isn't currently supported. Is there any other way or am I misinformed that a scheduling npm isn't applicable in this situation. (NOTE: I'm not running the server locally either. My parse-server is deployed on mLab.)

**Comment by AmbroiseCollon** [comment]
You can use [kue](https://github.com/Automattic/kue) to define specific scheduled jobs with any time interval you want. This is what I use.

**Comment by hramos** [comment]
@baymitchell12 mLab only hosts your database. Your Parse Server must be running elsewhere, where you should have at least the option to use kue like @AmbroiseCollon suggested.

**Comment by baymitchell12** [comment]
@hramos My server is a modified fork of the parse server example deployed through heroku with mLab hosting the database. So kue would be a viable option?

**Comment by hramos** [comment]
Yes, you can expand the Parse server example project to implement this functionality.

**Comment by thphuc** [comment]
@AmbroiseCollon Can you share me how to implement Kue with Parse-server? I am building a system where it will make auto payment each month to my users (on 28th of each month). I wrote a cloud code method in main.js to send out payment already, but I don't know how to integrate Kue to call that method.

**Comment by AmbroiseCollon** [comment]
Here is a draft. I don't have time to finish it right now. Do not hesitate to copy paste it and finish it for me or to write suggestions. It should put you on the right path at least. https://medium.com/@ambroisecollon/7754cd31d41e

**Comment by lucasputer** [comment]
@AmbroiseCollon Do you have any code available using kue? Can't get to get it to work.

**Comment by AmbroiseCollon** [comment]
index.js
```
var due = require('due')
var redisUrl = process.env.REDIS_URL || 'redis://boomquiz.jbxhzr.0001.euw1.cache.amazonaws.com:6379' 
kue.createQueue({ redis: redisUrl })
app.use('/kue', kue.app)
```
cloud file
```
// Access due api
var due = require('due')
var redisUrl = process.env.REDIS_URL || 'redis://boomquiz.jbxhzr.0001.euw1.cache.amazonaws.com:6379' // eslint-disable-line max-len
// Access the current queue
var jobs = kue.createQueue({ redis: redisUrl })

/**
 * Create the job for expiring round after 24h
*/
function createRoundExpiredJob(round) {
	jobs.create('roundExpired', {
		objectId: round.id
	})
	.removeOnComplete(true)
	.delay(round.createdAt.addADay())
	.save()
}
```
queue.js
```
var due = require('due')
var redisUrl = process.env.REDIS_URL || 'redis://boomquiz.jbxhzr.0001.euw1.cache.amazonaws.com:6379' // eslint-disable-line max-len
var jobs = kue.createQueue({ redis: redisUrl })

var push = require('./cloud/modules/push.js')

var Parse = require('parse/node')
Parse.initialize('b8eb79a0-b6d3-4e41-aa33-eaa9f71cf53f')
Parse.serverURL = 'https://boomquiz.mywebtailors.com/parse'

/**
 * Process the job for ending a round after 24h
*/
jobs.process('roundExpired', function (job, done) {
	// Your parse related code and when finished (in save callback for instance):
       done()
})
```
Procfile
```
web:    node index.js
worker: node queue.js
```

**Comment by lucasputer** [comment]
@AmbroiseCollon Thanks a lot!

**Comment by baymitchell12** [comment]
I have a requested parameter in my ./cloud/main.js that I need to use in the queue.js file. However, when I export the variable and <require('./cloud/main.js')> (in queue.js) I get the error that Parse is not defined in the main.js. Any help is appreciated!
