### ISSUE TITLE
[2.2.7] Failing to save PFFile

### ISSUE THREAD

**Issue by iStopped** [ParsePlatform/parse-server#1631]
#### Environment Setup
Virtual machine with Ubuntu LTS running parse-server 2.2.7

#### Steps to reproduce
Saving a PFFile from iOS result in timeout error or NSCocoaError code 3840
`Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}`

The PFFile contains a 1MB image file.

#### SOLVED
Nginx has a `client_max_body_size` parameter. It was too low.

**Comment by gfosco** [comment]
You'll need to do some additional troubleshooting, like checking the server logs (perhaps enabling verbose logging) to see what request/response transpired.   Getting a non json response usually means something is incorrectly configured.

**Comment by iStopped** [comment]
Verbose logging don't says anything. The stranger thing is that saving a PFFile in the User class works, but not on custom classes with PFFile. It sounds like the SDK can't handle the requests.

I'm using GridFS for saving files. I'll check again the logs.

**Comment by iStopped** [comment]
So, I dig a little further using WireShark and full verbose on ParseServer and it seems that the SDK actually sends the request and the TCP packets but the server don't get the request: nothing is logged in the logs about files.

**Comment by iStopped** [comment]
I've found the issues! My instance is running through nginx and I was unaware of `client_max_body_size `. I'm sorry about the trouble.
