### ISSUE TITLE
Can Command Line Tools use with parse-server

### ISSUE THREAD

**Issue by GongChen1107** [ParsePlatform/parse-server#1638]
I am doing function test with parse-server.I checked the Android SDK and Cloud Code and JaveScript SDK.I am not sure some functions is available  in the parse-server.Such as ,Command Line Tools ,Webhooks,

**Comment by drew-gross** [comment]
Command Line Tools are not necessary with `parse-server`. Webhooks are available in experimental mode. There are also some differences in how cloud code works in Parse Server that you can read about in the docs.
