### ISSUE TITLE
Validating Parse Application Id

### ISSUE THREAD

**Issue by ziyadparekh** [ParsePlatform/parse-server#164]
Is there functionality to validate an application id passed in through request headers? How are invalid Application IDs handled ? ie if someone submits a string that passes basic regex testing for an App ID, but that App ID doesn't actually point to a registered app, will the server throw an error? Or is validating application IDs out of the scope of this server ?

**Comment by gfosco** [comment]
It is taken from the header and must be a valid configured app.  You can see this in middlewares.js.  Behavior should be the same as API.parse.com in regards to sending an invalid id.
