### ISSUE TITLE
I'm getting "code":105,"error":"invalid key name:" when I do a POST in my server!

### ISSUE THREAD

**Issue by ckarmy** [ParsePlatform/parse-server#1641]
I really need help to implement a fix that solve my problem (similar to #68). I saw that in #105 there is a fix but in my parse-server I don't have any file called `classes.js`. How can I implement this?

Like @mkpazon say:

The problem seems to be due to JSON handling.
The client sends the following JSON in the body
{"where":"{\"status\":200,\"user\":{\"__type\":\"Pointer\",\"className\":\"_User\",\"objectId\":\"F2ozm6Hgew\"}}","count":"1","_method":"GET"}

but the parse-server returns an error.

Changing the above JSON to the following is successful
{"where": {"status":200,"user":{"__type":"Pointer","className":"_User","objectId":"F2ozm6Hgew"}},"count":"1","_method":"GET"}

**Comment by hramos** [comment]
What version of `parse-server` are you running?

Please refer to [this issue](https://github.com/ParsePlatform/parse-server/issues/1271) for an example of a great bug report.

Make sure these boxes are checked before submitting another issue -- thanks for reporting issues back to Parse Server!

- [ ] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [ ] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

**Comment by ckarmy** [comment]
@hramos I'm running 2.2.7 and I have all the prerequisites. Also I search many existing issues but I can't resolve this issue.

**Comment by ckarmy** [comment]
@hramos this is an example of my error:

verbose: POST /parse/classes/watchlist { 'x-real-ip': 'xxxxxxx',
  'x-forwarded-for': 'xxxxxx',
  'x-nginx-proxy': 'true',
  host: 'xxxxxx',
  connection: 'close',
  'content-length': '297',
  'value-type': 'application/json',
  'x-parse-application-id': 'xxxxxxxxxxxx',
  'user-agent': 'Dalvik/2.1.0 (Linux; U; Android 5.1.1; SM-G925I Build/LMY47X)',
  'accept-encoding': 'gzip',
  'content-type': 'application/x-www-form-urlencoded' } {
  "{\"user\":{\"__type\":\"Pointer\",\"className\":\"_User\",\"objectId\":\"LEjy9IlcYB\"},\"movieId\":\"10950\",\"MoviePoster\":\"https://image.tmdb.org/t/p/w600/gr0jLIUd5Os0RAFH9U5iZMpQ5cw.jpg\",\"MovieFrame\":\"https://image.tmdb.org/t/p/w600/mTN2pjZKWteb6B7WOGtrMx8FEpu.jpg\",\"MovieName\":\"Yo soy Sam\",\"MovieRelDate\":\"2001\"}": ""
}
verbose: error: code=105, message=invalid key name: {"user":{"__type":"Pointer","className":"_User","objectId":"LEjy9IlcYB"},"movieId":"10950","MoviePoster":"https://image.tmdb.org/t/p/w600/gr0jLIUd5Os0RAFH9U5iZMpQ5cw.jpg","MovieFrame":"https://image.tmdb.org/t/p/w600/mTN2pjZKWteb6B7WOGtrMx8FEpu.jpg","MovieName":"Yo soy Sam","MovieRelDate":"2001"}

**Comment by drew-gross** [comment]
Which version of the android SDK are you using, and what calls are you doing to make this request?

**Comment by ckarmy** [comment]
@drew-gross I use Fuse to make apps (https://www.fusetools.com). Fuse use this SDK:

* Android SDK platform-tools - 23.0.1
* Android SDK build-tools - 23.0.1
* Android 5.0.1 (API 21) - 2
* Android 4.4.2 (API 19) - 4
* Android Support Library - 23.2.1

And I use C# to make the HTTP request like this (this is converted to Java in the backend):

HttpMessageHandler AddToWatchL = new HttpMessageHandler();
var createRequ = AddToWatchL.CreateRequest("POST","https://xxxxxxx.com/parse/classes/watchlist");	
createRequ.SetHeader("Value-type", "application/json");
createRequ.SetHeader("X-Parse-Application-Id","xxxxxxxxxxx");
var PostData = "{\"user\":{\"__type\":\"Pointer\",\"className\":\"_User\",\"objectId\":\"LEjy9IlcYB\"},\"movieId\":\"10950\",\"MoviePoster\":\"https://image.tmdb.org/t/p/w600/gr0jLIUd5Os0RAFH9U5iZMpQ5cw.jpg\",\"MovieFrame\":\"https://image.tmdb.org/t/p/w600/mTN2pjZKWteb6B7WOGtrMx8FEpu.jpg\",\"MovieName\":\"Yo soy Sam\",\"MovieRelDate\":\"2001\"}";
createRequ.Done += resAddWatchList;
createRequ.SetTimeout(15000);
createRequ.Error += Error;
createRequ.Timeout += TimeOutM;
createRequ.GetResponseContentString();
createRequ.SetResponseType(HttpResponseType.String);
createRequ.SendAsync(PostData);

**Comment by drew-gross** [comment]
It looks like you are using the REST API, not the android SDK, and sending an invalid value. Did this work on api.parse.com? Can you try changing your code to submit the value that you said was working?

**Comment by hramos** [comment]
Don't escape the key names inside your `where` key when making a request to Parse.

This does not seem to be a Parse Server issue, as the server responds successfully when provided with a proper JSON payload (see original post).

**Comment by ckarmy** [comment]
@hramos What do you mean by `Don't escape the key names inside your where key when making a request to Parse.`?

@drew-gross Yes, this work on  api.parse.com. I have my app online with the same code and work perfect....

**Comment by ckarmy** [comment]
Sorry my mistake! I'm doing the HTTP request with `createRequ.SetHeader("Value-type", "application/json");` and the correct way is `createRequ.SetHeader("Content-Type", "application/json");`
