### ISSUE TITLE
Does Parse Server 2.2.7 support Parse.Cloud.useMasterKey()?

### ISSUE THREAD

**Issue by mmahmood** [ParsePlatform/parse-server#1646]
This is not a bug report. It's a question. The compatibility guide (https://github.com/ParsePlatform/Parse-Server/wiki/Compatibility-with-Hosted-Parse#Cloud-Code) says that Parse.Cloud.useMasterKey() is not available in Parse server cloud code. And I've been changing my code the whole day. I forgot it in one place, and tested it, and it works the way it does on Hosted Parse app on my local parse server. 

So is it available in this version of Parse server? I can't find any release notes either. So please let me know and save me the torture of going through all these changes and extensive testing. Thanks!

**Comment by drew-gross** [comment]
Parse.Cloud.useMasterKey() won't work in `parse-server` because it modifies global state and will interfere with other requests that are happening simultaneously. The fact that it worked in one place must have been a coincidence.
