### ISSUE TITLE
Create App without dashboard

### ISSUE THREAD

**Issue by TonGarcia** [ParsePlatform/parse-server#1648]
Hi. I've deployed my Parse Server on Heroku, but I can't set up the Dashboard because I don't have an App on my Parse Server. How can I create a Parse Server App to set it on __parse-dashboard-config.json__?

**Comment by drew-gross** [comment]
You need to follow the docs for `parse-server` and use the appId, URL, and master key that you create in your dashboard config.

**Comment by TonGarcia** [comment]
Hi Drew. So, whatever I add on config it will be  my credentials. Is it right? Anda what about multiple app for same parse-server?
Thank you so much for your answers.

**Comment by drew-gross** [comment]
Yep, those are the credentials. `parse-server` doesn't currently support multiple apps.
