### ISSUE TITLE
`validateEmailConfiguration` should be called when sending reset password email

### ISSUE THREAD

**Issue by natanrolnik** [ParsePlatform/parse-server#1649]
- [x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Parse Server 2.2.7 on Heroku

#### Steps to reproduce
- Configure an Email Adapter in index.js
- **Don't** configure app name and/or public server URL
- Request a reset password email via `requestPasswordReset`

#### Result
Users will receive an email with title "Password reset for **undefined**", and body:

"You requested to reset your password for **undefined**. Click here to reset it: **undefined**/apps/....."

#### Expected Result

[`validateEmailConfiguration`](https://github.com/ParsePlatform/parse-server/blob/d33dd68cc521e63be68a93ab1a00cfdb7a7d243d/src/Config.js#L75) or some variation of it should be called before sending reset password emails, to make sure that both app name and public server url were set correctly.

**Comment by drew-gross** [comment]
Yep that definitely should be called. Not sure when it stopped being called.

**Comment by drew-gross** [comment]
Actually this seems to be a different issue. I made a regression test in #1650 and it passes.

**Comment by natanrolnik** [comment]
The regression test you wrote doesn't really test what I mentioned here. I'll comment on the PR.

**Comment by damtsnkff** [comment]
@natanrolnik Did you solve it ? I'm facing the exact same problem. I tried with `parse-server:` `~2.2.7` and  `~2.2.2`

**Comment by damtsnkff** [comment]
@natanrolnik @drew-gross Ok that was a stupid mistake. I forgot the `publicServerURL`... and I was checking the wrong folder when debugging. Fixed for me.
