### ISSUE TITLE
Column name restrictions enforced on sub-object keys

### ISSUE THREAD

**Issue by sdf611097** [ParsePlatform/parse-server#165]
I just migrate the db to mongolab.

I start the parse server example. 

I try to query something with javascript sdk 1.7.0 on nodejs v4.2.4. 

Below is my javascript code.

var Parse = require('parse/node').Parse;
Parse.initialize("myAppId", "jsKey");
Parse.serverURL = 'http://localhost:1337/parse'

var clz = Parse.Object.extend('myClass');
var query = new Parse.Query(clz);
query.find().then(function(list){
    console.log(list.length);
},function(error){
    console.log(error);
});

One of my original class(size 4) will get  ParseError { code: 1, message: undefined }.

Others get all obj size (not original default limit 100)

I use original keys and with default parse api server endpoint.

It works, and get 4 and 100 as expected.

I found that query.limit default 100 is gone.
query.skip cannot exceed 10000 constraint is gone.
Could you also list all influence of the code? 
(In this case, query with 100 results must add query.limit(100); )
 
Only contains 'hello' cloud code.

**Comment by gfosco** [comment]
Would be interested in any details / debugging you can do about the class returning the undefined error.  It's possible to set the environment variable `VERBOSE=1` and it will log all input/output.

True, the limits are gone... We should probably re-enable the default limit 100, but the rest are no longer enforced because it was a constraint of running hundreds of thousands of apps as a service..

**Comment by sdf611097** [comment]
I cannot get any extra message.

me$ export VERBOSE=1
me$ echo $VERBOSE
1
me$ node test.js
ParseError { code: 1, message: undefined }


here is "npm list" result

├─┬ parse@1.7.0
│ ├─┬ babel-runtime@5.8.35
│ │ └── core-js@1.2.6
│ └── xmlhttprequest@1.8.0
├─┬ parse-server@2.0.3
│ ├─┬ bcrypt@0.8.5
│ │ ├── bindings@1.2.1
│ │ └── nan@2.0.5
│ ├─┬ body-parser@1.12.4
│ │ ├── bytes@1.0.0
│ │ ├── content-type@1.0.1
│ │ ├─┬ debug@2.2.0
│ │ │ └── ms@0.7.1
│ │ ├── depd@1.0.1
│ │ ├── iconv-lite@0.4.8
│ │ ├─┬ on-finished@2.2.1
│ │ │ └── ee-first@1.1.0
│ │ ├── qs@2.4.2
│ │ ├─┬ raw-body@2.0.2
│ │ │ └── bytes@2.1.0
│ │ └─┬ type-is@1.6.11
│ │   ├── media-typer@0.3.0
│ │   └─┬ mime-types@2.1.9
│ │     └── mime-db@1.21.0
│ ├── deepcopy@0.5.0
│ ├─┬ express@4.2.0
│ │ ├─┬ accepts@1.0.1
│ │ │ ├── mime@1.2.11
│ │ │ └── negotiator@0.4.9
│ │ ├── buffer-crc32@0.2.1
│ │ ├── cookie@0.1.2
│ │ ├── cookie-signature@1.0.3
│ │ ├── debug@0.8.1
│ │ ├── escape-html@1.0.1
│ │ ├── fresh@0.2.2
│ │ ├── merge-descriptors@0.0.2
│ │ ├── methods@1.0.0
│ │ ├── parseurl@1.0.1
│ │ ├── path-to-regexp@0.1.2
│ │ ├── qs@0.6.6
│ │ ├── range-parser@1.0.0
│ │ ├─┬ send@0.3.0
│ │ │ ├── debug@0.8.0
│ │ │ └── mime@1.2.11
│ │ ├── serve-static@1.1.0
│ │ ├─┬ type-is@1.1.0
│ │ │ └── mime@1.2.11
│ │ └── utils-merge@1.0.0
│ ├── hat@0.0.3
│ ├── mime@1.3.4
│ ├─┬ mongodb@2.0.55
│ │ ├── es6-promise@2.1.1
│ │ ├─┬ kerberos@0.0.18
│ │ │ └── nan@2.0.9
│ │ ├─┬ mongodb-core@1.2.31
│ │ │ └── bson@0.4.21
│ │ └─┬ readable-stream@1.0.31
│ │   ├── core-util-is@1.0.2
│ │   ├── inherits@2.0.1
│ │   ├── isarray@0.0.1
│ │   └── string_decoder@0.10.31
│ ├─┬ multer@0.1.8
│ │ ├─┬ busboy@0.2.12
│ │ │ ├─┬ dicer@0.2.5
│ │ │ │ └── streamsearch@0.1.2
│ │ │ └─┬ readable-stream@1.1.13
│ │ │   ├── core-util-is@1.0.2
│ │ │   ├── inherits@2.0.1
│ │ │   ├── isarray@0.0.1
│ │ │   └── string_decoder@0.10.31
│ │ ├── mkdirp@0.3.5
│ │ ├── qs@1.2.2
│ │ └─┬ type-is@1.5.7
│ │   ├── media-typer@0.3.0
│ │   └─┬ mime-types@2.0.14
│ │     └── mime-db@1.12.0
│ ├─┬ parse@1.6.14
│ │ ├─┬ babel-runtime@5.8.35
│ │ │ └── core-js@1.2.6
│ │ └── xmlhttprequest@1.8.0
│ └─┬ request@2.69.0
│   ├── aws-sign2@0.6.0
│   ├─┬ aws4@1.2.1
│   │ └── lru-cache@2.7.3
│   ├─┬ bl@1.0.1
│   │ └─┬ readable-stream@2.0.5
│   │   ├── core-util-is@1.0.2
│   │   ├── inherits@2.0.1
│   │   ├── isarray@0.0.1
│   │   ├── process-nextick-args@1.0.6
│   │   ├── string_decoder@0.10.31
│   │   └── util-deprecate@1.0.2
│   ├── caseless@0.11.0
│   ├─┬ combined-stream@1.0.5
│   │ └── delayed-stream@1.0.0
│   ├── extend@3.0.0
│   ├── forever-agent@0.6.1
│   ├─┬ form-data@1.0.0-rc3
│   │ └── async@1.5.2
│   ├─┬ har-validator@2.0.6
│   │ ├─┬ chalk@1.1.1
│   │ │ ├── ansi-styles@2.1.0
│   │ │ ├── escape-string-regexp@1.0.4
│   │ │ ├─┬ has-ansi@2.0.0
│   │ │ │ └── ansi-regex@2.0.0
│   │ │ ├─┬ strip-ansi@3.0.0
│   │ │ │ └── ansi-regex@2.0.0
│   │ │ └── supports-color@2.0.0
│   │ ├─┬ commander@2.9.0
│   │ │ └── graceful-readlink@1.0.1
│   │ ├─┬ is-my-json-valid@2.12.4
│   │ │ ├── generate-function@2.0.0
│   │ │ ├─┬ generate-object-property@1.2.0
│   │ │ │ └── is-property@1.0.2
│   │ │ ├── jsonpointer@2.0.0
│   │ │ └── xtend@4.0.1
│   │ └─┬ pinkie-promise@2.0.0
│   │   └── pinkie@2.0.2
│   ├─┬ hawk@3.1.3
│   │ ├── boom@2.10.1
│   │ ├── cryptiles@2.0.5
│   │ ├── hoek@2.16.3
│   │ └── sntp@1.0.9
│   ├─┬ http-signature@1.1.1
│   │ ├── assert-plus@0.2.0
│   │ ├─┬ jsprim@1.2.2
│   │ │ ├── extsprintf@1.0.2
│   │ │ ├── json-schema@0.2.2
│   │ │ └── verror@1.3.6
│   │ └─┬ sshpk@1.7.3
│   │   ├── asn1@0.2.3
│   │   ├── dashdash@1.12.2
│   │   ├── ecc-jsbn@0.1.1
│   │   ├── jodid25519@1.0.2
│   │   ├── jsbn@0.1.0
│   │   └── tweetnacl@0.13.3
│   ├── is-typedarray@1.0.0
│   ├── isstream@0.1.2
│   ├── json-stringify-safe@5.0.1
│   ├─┬ mime-types@2.1.9
│   │ └── mime-db@1.21.0
│   ├── node-uuid@1.4.7
│   ├── oauth-sign@0.8.1
│   ├── qs@6.0.2
│   ├── stringstream@0.0.5
│   ├── tough-cookie@2.2.1
│   └── tunnel-agent@0.4.2
└── underscore@1.8.3

**Comment by gfosco** [comment]
Take a look in your Mongo database for the ActionLink collection... do you really have objects with a key named _0 ?

**Comment by sdf611097** [comment]
Yes, I have a object with a key named _0 ( _Versions)

**Comment by gfosco** [comment]
Did you have this object in hosted Parse?... It's not a valid column name...

**Comment by sdf611097** [comment]
Column name does not start with _ 

{  
   "os":{  
      "_1":{  
      },
      "_2":{  
      }
   }
}

**Comment by gfosco** [comment]
Interesting.  Looks like we're enforcing the column name restriction on sub-objects.  I'll accept it as a bug and take a look soon.

**Comment by mahabubakram** [comment]
ALso I have found this problem with one of the key used for keeping twitter auth "_auth_data_twitter".

And it is saying bad  key in untransform: `_auth_data_twitter undefined`

**Comment by nlutsenko** [comment]
Yup, there are more like that. 
I am working on a fix, but it takes slightly more time than I thought it would.

**Comment by enjoyjeremy** [comment]
+1

**Comment by giano** [comment]
+1

**Comment by flovilmart** [comment]
@mahabubakram the _auth_data_twitter problem should be fixed with #247.

**Comment by giano** [comment]
Sorry, still here.

**Comment by flovilmart** [comment]
@giano just the _auth_data_twitter should be fixed, as well as other _auth_data_.... But not the other cases

**Comment by gfosco** [comment]
Still experiencing this with 2.1.2?

**Comment by sdf611097** [comment]
It's still failed in parse-server@2.1.2.

GET /parse/classes/ActionLink { 'user-agent': 'node-XMLHttpRequest, Parse/js1.7.1 (NodeJS 4.2.1)',
  accept: '*/*',
  'content-type': 'text/plain',
  host: 'zencirclectl.cloudapp.net:1337',
  'content-length': '174',
  connection: 'close' } {
  "where": {}
}
error: bad key in untransform: _0
Uncaught internal server error. bad key in untransform: _0 undefined

**Comment by flovilmart** [comment]
@gfosco found the culprit, the untransform is recursive, that's why we apply the same rules to nested objects as top-level.

**Comment by gfosco** [comment]
Nice, @flovilmart :+1:   Merged that, closing this.  @sdf611097 You can pull the master branch or wait for 2.1.3.  Let us know if you have any problems.  Thanks.
