### ISSUE TITLE
MongoRock instance restartability

### ISSUE THREAD

**Issue by mayankverma** [ParsePlatform/parse-server#1651]
I was able to successfully install mogorock and migrate the data for testing. But before I finalized, I wanted to see if rebooting machine, brings up everything fine. Seems like after reboot, the mongod does not start. 
Anyone experienced the same?
Do I have to configure and mount mdadm stuff again?

**Comment by skinp** [comment]
@mayankverma you need setup some sort of init script if you want the process to be started at boot. I suggest looking into whatever is recommended for your distribution. Some options are systemd, upstart, supervisord, runit, monit, ...

You'll most likely have to remount the volume too if it's not configured in fstab. I'm closing this issue as it's not directly related to parse-server.
