### ISSUE TITLE
"No reachable servers" when migration to self hosted server

### ISSUE THREAD

**Issue by w3care25** [ParsePlatform/parse-server#1663]
I am trying to migrate my app from parse to self hosted server.

But unable to migrate database when inserting mongodb database URI and start migration it shows **:"No Reachable Server"**

I am using mongoDb URI as follows: **_mongodb://user:password@IP-address:27017/parse_**

Any idea how to fix this ?

**Comment by bohemima** [comment]
Make it reachable on that address! :)

Make sure your mongodb is listening on the network interface and not only on the loopback interface (make sure you have authentication enforced before doing this)

**Comment by w3care25** [comment]
I have added my IP in bindIp option in mongoDB configuration file. but still getting same error.

Is there anything else to do to make it reachable?

**Comment by hramos** [comment]
I'm closing out this issue as it is not related to Parse Server. For migration assistance, please visit https://parse.com/help#report
