### ISSUE TITLE
Clients aren't allowed to perform the create operation on the role collection. (Code: 119, Version: 1.12.0)

### ISSUE THREAD

**Issue by hclviv** [ParsePlatform/parse-server#1671]
Hello Team,

I am struggling with an issue which is related with PFRole Parse SDK Ver 1.12.0. 

I have a parse app running on Parse server with iOS SDK 1.7.5 on PRODUCTION and in that app we are creating role from iOS app directly using PFRole, which is working fine.

But after migrating my Parse cloud app to Amazon + Mango DB and changed the Client iOS SDK to 1.12.0, I am getting issue and unable to create the PFRole. 

The same code was working properly with iOS SDK 1.7.5. Will you please help me out to fix this issue

**Comment by hramos** [comment]
Did you check your [class level permissions](https://github.com/ParsePlatform/parse-server/wiki/Compatibility-with-Hosted-Parse#class-level-permissions)?

**Comment by hclviv** [comment]
Request you to please more explain about class level permission. What I need to change in schema

**Comment by hclviv** [comment]
hi @hramos 

here is my class level permission (From MongoDB )for the Role-

{
    "_id": "_Role",
    "_metadata": {
        "class_permissions": {
            "get": {
                "*": true
            },
            "find": {
                "*": true
            },
            "update": {
                "*": true
            },
            "create": {
                "*": true
            },
            "delete": {
                "*": true
            },
            "addField": {
                "*": true
            },
            "readUserFields": [],
            "writeUserFields": []
        }
    },
    "role": "string",
    "roles": "relation<_Role>",
    "users": "relation<_User>",
    "name": "string",
    "organizationId": "string"
}

And from my iOS application I am trying to add the role like below:


        PFACL *roleACL = [PFACL ACL];
        [roleACL setPublicReadAccess:YES];
        [roleACL setPublicWriteAccess:YES];
        
        PFRole *roleAdmin = [PFRole roleWithName:roleNameAdmin acl:roleACL];
        [roleAdmin.users addObject:currentUser];
        [roleAdmin setValue:@"admin" forKey:@"role"];
        [roleAdmin setValue:orgId forKey:@"organizationId"];

will you please guide me what I am doing wring at Class level Permission.

**Comment by hclviv** [comment]
Hi @hramos 

Any guess ??

**Comment by xissburg** [comment]
+1
I have the same problem here. I tried to find where this error message is coming from but I didn't find this string in parse-server or in the iOS SDK source code. Why does this error even exist? What's the reason behind not allowing us to query roles from the client app? This is a necessity in my application.

**Comment by xissburg** [comment]
Oh here it is https://github.com/ParsePlatform/parse-server/blob/d33dd68cc521e63be68a93ab1a00cfdb7a7d243d/src/rest.js#L118

What is the point of `enforeRoleSecurity`? I don't want to enforce role security.

**Comment by xissburg** [comment]
Oh wait I think I don't have the latest version... this was actually removed here https://github.com/ParsePlatform/parse-server/commit/dd7fad8e96c93b933d4515fc2dc5c7aebaaff115#diff-62e69722264e5a578707565ff5fcf41c

**Comment by drorsun** [comment]
We have the same issue. Application gets:

> Clients aren't allowed to perform the find operation on the installation collection. (Code: 119, Version: 1.12.0)

**Comment by xissburg** [comment]
@drorsun Update your parse-server version.

**Comment by drorsun** [comment]
@xissburg I am on version 2.2.7 which is the latest

**Comment by brianyyz** [comment]
I am having the same issue as @drorsun and am also on v2.2.7. 
PFInstallation.currentInstallation().fetchInBackgroundWithBlock {......   returns error code 119.

**Comment by xissburg** [comment]
Check what your have in `enforeRoleSecurity` at node_modules/parse-server/lib/rest.js

**Comment by brianyyz** [comment]
@xissburg the function is:

// Disallowing access to the _Role collection except by master key
function enforceRoleSecurity(method, className, auth) {
  if (className === '_Installation' && !auth.isMaster) {
    if (method === 'delete' || method === 'find') {
      var error = 'Clients aren\'t allowed to perform the ' + method + ' operation on the installation collection.';
      throw new Parse.Error(Parse.Error.OPERATION_FORBIDDEN, error);
    }
  }
}

**Comment by drorsun** [comment]
@xissburg I also have the same code as @brianyyz does

**Comment by hclviv** [comment]
Guys,

I updated my Parse-Server version and also the latest iOS SDK.
I setup my installation locally and now everything is working fine the issue is resolved
