### ISSUE TITLE
Getting ERROR: ''clientKey' should not be nil.

### ISSUE THREAD

**Issue by candork** [ParsePlatform/parse-server#1672]
Hi Guys,

I have installed parse server on my mac and its running. Then on my app I get this error

> 2016-04-28 14:07:42.815 myapp[397:52215] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: ''clientKey' should not be nil.'
> *** First throw call stack:

Here is my app init
```
    [Parse initializeWithConfiguration:[ParseClientConfiguration configurationWithBlock:^(id<ParseMutableClientConfiguration> configuration) {
        configuration.applicationId = @"hidden";
        configuration.clientKey = @"";
        configuration.server = @"http://localhost:1337/parse";
    }]];
```

When I change configuration.clientKey to my old parse client key. It build but I get this error
```

[Error]: Could not connect to the server. (Code: 100, Version: 1.12.0)
[Error]: Network connection failed. Making attempt 2 after sleeping for 3.097124 seconds.
```

Here is the output of my pod install
```
 pod install
Updating local specs repositories

CocoaPods 1.0.0.beta.8 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Using AFNetworking (2.6.3)
Using Bolts (1.5.0)
Using FBAudienceNetwork (4.10.1)
Using FBSDKCoreKit (4.9.1)
Using FBSDKLoginKit (4.9.1)
Using FBSDKShareKit (4.9.1)
Using Flurry-iOS-SDK (7.3.0)
Using Google-Mobile-Ads-SDK (7.6.0)
Using MBProgressHUD (0.9.2)
Using Parse (1.12.0)
Using ParseCrashReporting (1.9.2)
Using ParseFacebookUtilsV4 (1.11.0)
Using ParseUI (1.1.7)
Using SCRecorder (2.6.1)
Using pop (1.0.8)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 13 dependencies from the Podfile and 15 total pods installed.

```

**Comment by hramos** [comment]
Update your iOS SDK to [1.13.0, which allows client keys to be nil](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/releases/tag/1.13.0).

For any issues concerning the iOS SDK, please open an issue in the [Parse-SDK-iOS-OSX repo](https://github.com/ParsePlatform/Parse-SDK-iOS-OSX).

**Comment by sidan5** [comment]
I'm using 1.14.2 and have this same issue...

**Comment by flovilmart** [comment]
Did you try not setting anything at all?

**Comment by guthook** [comment]
I am also using 1.14.2, setting nothing at all for clientKey, and getting the same crash. 

Tried clearing derived data, and deleting/reinstalling the app in question on Simulator. No luck.
