### ISSUE TITLE
Cloud Code Causing Server to Crash

### ISSUE THREAD

**Issue by jackintosh7** [ParsePlatform/parse-server#1675]
Hello, 

I'm trying to use Parse's [AnyPhone](https://github.com/ParsePlatform/AnyPhone) example on my parse server. The server runs fine, but as soon as I add the cloud code to the cloud directory, the server crashes.

I'm getting this error `2016-04-29T03:05:35.538222+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=app.herokuapp.com request_id=f18669e6-e255-46ea-a8bb-c409603984b8 fwd="24.189.195.105" dyno= connect= service= status=503 bytes=
2016-04-29T03:05:35.846438+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=app.herokuapp.com request_id=04e5ef78-45c9-40c8-ab8a-713e0eaa8790 fwd="24.189.195.105" dyno= connect= service= status=503 bytes=`

I read that I need to remove all lines containing MasterKey and CurrentUser, which I have done. 

Does anyone have any ideas?

**Comment by bohemima** [comment]
Run it locally with VERBOSE=1 and see if you get any more informative log output. This is most likely due to syntax-errors and is more suited at SO perhaps.

**Comment by gfosco** [comment]
Yeah I would run this locally so you could see the stack immediately.. Pretty sure you'll find the answer.
