### ISSUE TITLE
Feature request: Cloud Code live-reload?

### ISSUE THREAD

**Issue by DazChong** [ParsePlatform/parse-server#1676]
I start with a blank cloud code file, and spent sometime debugging why it doesnt work only found out that it loaded once upon Parse Server start.

Or perhaps mentioned it in documentation? It will be informative.

**Comment by kocyigityunus** [comment]
look at [nodemon](http://nodemon.io/). it can reload your node app with code changes.

**Comment by nil8tor** [comment]
We use [forever-webui](https://github.com/FGRibreau/forever-webui) which monitors node running via forever in an easy web browser view that monitors console output and allows for restarts nicely.

**Comment by DazChong** [comment]
@kocyigityunus @nil8tor , ah now I see. let node runner be handle by other module is better approach. Thanks for the info. Closing issue.
