### ISSUE TITLE
SSL and LiveQuery?

### ISSUE THREAD

**Issue by cheesykyle** [ParsePlatform/parse-server#1682]
I've secured my app with SSL and everything is working as expected, aside from LiveQueries. I'm accessing my parse-server from an SSL webpage as well and receive the following error from the web console:

`https://example.com/ was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://example.com/parse'. This request has been blocked; this endpoint must be available over WSS`

So I assume this is a simple matter of LiveQueries not creating a secure WebSocket connection and providing the correct protocol. Is this something that is being worked on, or how can I ensure I have access to the live query protocol behind ssl.

Thanks!

**Comment by drew-gross** [comment]
This seems to be a JS SDK issue. Tracking here: https://github.com/ParsePlatform/Parse-SDK-JS/issues/271
