### ISSUE TITLE
Unable to sign in with facebook on iOS

### ISSUE THREAD

**Issue by kashif789us** [ParsePlatform/parse-server#1684]
Hello guys. I have parse server running on aws beanstalk and mlab is used for mongodb. I am unable to sign in using facebook.

I am using SWIFT, here is the code snippet I am using

                
               PFFacebookUtils.logInInBackgroundWithReadPermissions(["public_profile","email"]) {
                (user: PFUser?, error: NSError?) -> Void in
                if let user = user {
                    if user.isNew {
                        print("User signed up and logged in through Facebook!")
                    }
                    else {
                        print("User logged in through Facebook!")
                    }
                }
                else {
                    print("Uh oh. The user cancelled the Facebook login.")
                }

I am getting both user and error nil. I googled it and found 2 things.

1. Add facebookAppIds : ['fbAppId'] to my index.js and I did
2. Add Environmental variable FACEBOOK_APP_ID and I did

Still I am facing the same issue. How to fix it?

**Comment by bohemima** [comment]
Start parse-server with VERBOSE=1 option and see if there are any hints in the log as to why it doesnt work.

**Comment by kashif789us** [comment]
I am sorry I am a beginner in this. How can I start with VERBOSE=1?

**Comment by kwstasna** [comment]
Could you provile the xCode logs of error? Because i had some of the same issue and i managed to fix it with debugging from xCode logs :)

**Comment by kashif789us** [comment]
What I did was login with FBSDKLoginManager, then I grabbed the fbAccessToken and then signed in with PFFacebookUtils.logInInBackgroundWithAccessToken and its working.

**Comment by dnadri** [comment]
@kashif789us I was in a very similar situation as you and what fixed it for me without this workaround was this:
In AppDelegate.swift, the `ParseClientConfiguration` must be initialized **BEFORE** the Parse Facebook Utils initialization in `didFinishLaunchingWithOptions`:

```
...
        // *** Initialize Parse. ***
        let config = ParseClientConfiguration(block: {
            (ParseMutableClientConfiguration) -> Void in
            ParseMutableClientConfiguration.applicationId = appKey;
            ParseMutableClientConfiguration.clientKey = clientKey;
            ParseMutableClientConfiguration.server = serverURL;
        });

        Parse.initializeWithConfiguration(config);

        // *NOTE: Putting the following line after after Parse.initializeWithConfiguration(config) fixed the issue
        // After this change, the user is no longer nil and does not print "Uh oh. The user cancelled the Facebook login.". Instead, it executes the `if let user = user` block
        PFFacebookUtils.initializeFacebookWithApplicationLaunchOptions(launchOptions)
...
```
