### ISSUE TITLE
Wrote the definitive guide for installing parse on Centos.

### ISSUE THREAD

**Issue by notanark** [ParsePlatform/parse-server#1685]
Where can I post it?

The problem with your guides are that they are all based on your setup on your machines using your flavor of linux.

I wrote a guide for people who like to compile their own software and distrust npm sources as that's how you get viruses.

Basically, a guide for real system administrators who can compile gcc by hand.

**Comment by gfosco** [comment]
Hi @notanark, sounds good to me...  If it was posted somewhere, like Medium or your own blog site, we'd happily link to it and tweet about it.  Can you post it?
