### ISSUE TITLE
Add Heroku button for easiest transition from parse.com

### ISSUE THREAD

**Issue by exalted** [ParsePlatform/parse-server#17]
I wish you could add a Heroku button to this project so that with a single click I could create my own parse.com instance on an heroku app and switch my apps to it with just changing the API url in my app somehow.

**Comment by exalted** [comment]
https://devcenter.heroku.com/articles/heroku-button

**Comment by gfosco** [comment]
This is actually being attempted here in the example server: https://github.com/ParsePlatform/parse-server-example/pull/8
