### ISSUE TITLE
Group chat for repository (Gitter)

### ISSUE THREAD

**Issue by igorshubovych** [ParsePlatform/parse-server#1700]
I noticed that a lot of tasks are created just to discuss or ask some question. It would be probably better to use group chat for that, something like Gitter or Slack. I think Gitter would be better, because it stores chat logs forever.

I checked that you were asked for having Gitter chat already in #566 and #1366.

Setting up channel in Gitter is pretty straightforward. Let me know if you need any help with it.

**Comment by nlutsenko** [comment]
Yolo! We have it, need to add it here... Hold tight.
