### ISSUE TITLE
Will parse server support email verifications?

### ISSUE THREAD

**Issue by drorsun** [ParsePlatform/parse-server#1707]
Will parse server support email confirmations/verifications that were supported by parse platform?

**Comment by ChrisGrant** [comment]
It already does. See the README https://github.com/ParsePlatform/parse-server#email-verification-and-password-reset

**Comment by zirinisp** [comment]
In my case it does not work. Can you please help me out. See the following link for more info.

http://stackoverflow.com/questions/39891896/parse-server-with-mailgun-adapter-how-can-i-get-verification-email-to-work
