### ISSUE TITLE
When does CloudCode job can work ?

### ISSUE THREAD

**Issue by GongChen1107** [ParsePlatform/parse-server#1708]
Hi,
I have a lot of functions using Cloud Code job function ,I am using parse-server version 2.2.6. I am going to  migrate cloud code to self host parse-server ,what can I do to deal with this problem.
Thanks!

**Comment by bohemima** [comment]
As suggested in the migration document you will want to move any background jobs to something else. The document is for example suggesting looking at kue. Or you could simply use a crontab or task scheduler depending on your OS.
