### ISSUE TITLE
Can we use es6 everywhere?

### ISSUE THREAD

**Issue by harisvsulaiman** [ParsePlatform/parse-server#171]
Since this is one of the repos with smaller codebase and a large community around it, this will turn out to be good resource to start learning es6. Especially for new comers to the whole js world,like me!

**Comment by maysale01** [comment]
I'm working on a fork that converts the repo to ES6 modules. As of right now, there are some issues with Parse.Query from `parse/node` that I'm debugging. The only ES6 feature that seems to be utilized by this repo is arrow functions. I think right now the testing setup needs to be revamped before any major changes are made.

**Comment by maysale01** [comment]
Got it all working, here's a good launching point: https://github.com/maysale01/parse-server/tree/es6-attempt2

**Comment by harisvsulaiman** [comment]
Thanks, 👍

**Comment by devyhia** [comment]
@maysale01 Any updates on this ES6 progress? Did the parse team add that?

**Comment by flovilmart** [comment]
Most of the internals are es6, but IMHO, given that native support will not come to node any time soon, I don't really see the point. Can you explain further the motivation?
