### ISSUE TITLE
Twitter Sign In Issue

### ISSUE THREAD

**Issue by falsalloum** [ParsePlatform/parse-server#1719]
Hi,
I can't login with twitter with using ParseTwitterUtils.
{"code":1,"message":"Internal server error."} (Code: 1, Version: 1.12.0)

typed in AppDelegate.m
[PFTwitterUtils initializeWithConsumerKey:@"xxxxxxxxxxxxxxxxxxxxx"
consumerSecret:@"xxxxxxxxxxxxxxxxxxxxx"];

I am using Heruko and in the settings of my app I inserted a new variable witha key OAUTH and variable :    twitter:  {
      consumer_key: "XXXXXXX",
      consumer_secret: "XXXXXX"
   }

facebook works perfectly. 

Can't figure out what I am doing wrong

**Comment by bohemima** [comment]
Run the parse-server with VERBOSE=1 and paste relevant lines from the output to help troubleshooting.

**Comment by sprabs** [comment]
@falsalloum: Did you ever resolve this issue? We are having trouble linking and unlinking our iOS client from Twitter via parse server right now. We are not seeing any issues through parse.com.

**Comment by flovilmart** [comment]
Double check your keys and secret on the server. It's been tested again today for another user.
