### ISSUE TITLE
Implement my own email adapter?

### ISSUE THREAD

**Issue by drorsun** [ParsePlatform/parse-server#1721]
Hi,
I am considering creating an email adapter to use AWS SES for email sending instead of using Mailgun.  If successful I'll put it back here for everyone to enjoy.

I am not sure where to start on parse-server code. 
Can someone provide at least rough guidelines on how emails work with parse-server, how to implement my own email adapter and how to write the call-back link that the user presses to verify the email?
At the very least - where can I have a look for the Mailgun example?
Thanks
Dror

**Comment by bohemima** [comment]
The Mailgun adapter lives here -> https://github.com/ParsePlatform/parse-server-simple-mailgun-adapter

Also, have a look at the "Interface" for Emailadapter, https://github.com/ParsePlatform/parse-server/blob/master/src/Adapters/Email/MailAdapter.js

Unfortunately I'm a bit unsure about the callbacks but I bet most of it can be figured out by staring at the repo long enough :)

**Comment by drorsun** [comment]
That's the lead I was looking for 👍 
Thanks!
