### ISSUE TITLE
S3 migration to our server

### ISSUE THREAD

**Issue by wanhappy5** [ParsePlatform/parse-server#1724]
Dear Parse,

Hi, i know the deadline for 
> July 28, 2016 - Finish setting up your self-hosted Parse Server and release a new app pointing to it. 

> 

how about your s3 service ? http://files.parsetfss.com/ 
the your s3 service shutting down ? because we already migrate the Parse server to our server. we see the s3 link still pointing to http://files.parsetfss.com/ . if your s3 service shutting down, can you give me the tutorial for migrating to own s3 server ? 

Thank you

**Comment by steven-supersolid** [comment]
At this point, there is only a discussion about plan for migrating existing files: https://github.com/ParsePlatform/parse-server/wiki/Files-Migration

In the meantime you can store new files on S3 so you won't have as much to migrate.

There is a high level overview here: http://blog.parse.com/announcements/hosting-files-on-parse-server/

More detail here: https://github.com/ParsePlatform/parse-server/wiki/Configuring-File-Adapters#configuring-s3adapter

Hope that helps

**Comment by hramos** [comment]
+1 to @steven-supersolid. See https://github.com/ParsePlatform/parse-server/issues/8 as well.
