### ISSUE TITLE
count = 1 is not work in installations

### ISSUE THREAD

**Issue by ssk7833** [ParsePlatform/parse-server#1726]
- [x] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.

- [x] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases

- [x] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.

#### Environment Setup

- Server: 
  - parse-server: 2.2.7
  - operating system: Windows 7
  - local
- Database: mongoDB 3.2.4 local

#### Steps to reproduce

    $ curl -X GET \ 
      -H "X-Parse-Application-Id: myAppId" \
      -H "X-Parse-Master-Key: myMasterKey" \
      http://localhost:1337/parse/installations/?count=1

This is what I got:

    {
      "results": [
        ...my installations...
      ]
    }

But what I expected is like current Parse REST API when I use the command below:

    $ curl -X GET \
      -H "X-Parse-Application-Id: myAppId" \
      -H "X-Parse-Master-Key: myMasterKey" \
      -H "X-Parse-REST-API-Key: myRestApiKey" \
      https://api.parse.com/1/installations/?count=1

It response with installations count like this:

    {
      "results": [
        ...my installations...
      ],
	  count: 5
    }

Is this a bug?

**Comment by sdf611097** [comment]
This issue seems have been solved by #1642. 
2.2.7 req.body may get {}, option is {}.

I found that query.count() in jsSDK at 2.2.7 is work.
It can work due to the url is different(close below shows).

curl -X GET \ 
  -H "X-Parse-Application-Id: myAppId" \
  -H "X-Parse-Master-Key: myMasterKey" \
  http://localhost:1337/parse/classes/_Installations/?count=1&limit=0


below test is failed at 2.2.7 but pass in latest commit

```
      var options = {
        url: config.serverURL+"/installations/?count=1&limit=0",
        headers: {
            'X-Parse-Application-Id': config.applicationId,
            'X-Parse-Master-Key': config.masterKey
        }
      }
      request(options, function (error, response, body) {
        if (!error && response.statusCode == 200) {
          var temp  = JSON.parse(body);
          expect(temp.count).toEqual(1);
        }else{
          console.log('err',error);
        }
      })
```

**Comment by drew-gross** [comment]
Closing as it seems like we have a solution ready for the next version of Parse Server

**Comment by ssk7833** [comment]
It works after updating to 2.2.8. Thanks.
