### ISSUE TITLE
your server is down

### ISSUE THREAD

**Issue by rexz0m** [ParsePlatform/parse-server#1727]
I just need it for 1 more hour!!! The server is down. Please help.

**Comment by bohemima** [comment]
Is this related to your locally hosted parse-server?

If you are refering to the hosted version this is not the place to report it but there was a outage earlier today according to https://status.parse.com/incidents/80mmfv10l1bv

**Comment by oallouch** [comment]
Another great example of the self-hosted parse-server goodness ! :)
