### ISSUE TITLE
Push notifications give 0 success, 0 failures

### ISSUE THREAD

**Issue by rogeriochaves** [ParsePlatform/parse-server#1731]
- [x] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.

- [x] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases

- [x] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.

#### Environment Setup

- Server: parse-server version 2.2.7, operating system: Mac OSX El Capitain, local
- Database: MongoDB 3

#### Steps to reproduce

- I'm trying to send an iOS push notification (haven't tested android yet), and it fails with no errors, here is my config:

```javascript
push: {
    android: {
      senderId: '[secret]',
      apiKey: '[secret]'
    },
    ios: [{
      pfx: __dirname + '/certs/Prod.p12',
      bundleId: '[secret]',
      production: true
    },
    {
      pfx: __dirname + '/certs/Dev.p12',
      bundleId: '[secret]',
      production: false
    }]
  }
```

I'm using this curl:

```
curl -X POST \
  -H "X-Parse-Application-Id: [secret]" \
  -H "X-Parse-Master-Key: [secret]" \
  -H "Content-Type: application/json" \
  -d '{
        "where": {
          "deviceType": "ios"
        },
        "data": {
          "alert": "Hello World!"
        }
      }' \
  http://localhost:1337/parse/push
```

And by enabling `VERBOSE=1` I'm getting:
```
verbose: POST /parse/push { host: 'localhost:1337',
  'user-agent': 'curl/7.43.0',
  accept: '*/*',
  'x-parse-application-id': '[secret]',
  'x-parse-master-key': '[secret]',
  'content-type': 'application/json',
  'content-length': '131' } {
  "where": {
    "deviceType": "ios"
  },
  "data": {
    "alert": "Hello World!"
  }
}
verbose: {
  "headers": {
    "X-Parse-Push-Status-Id": "z50b72vAxW"
  },
  "response": {
    "result": true
  }
}
verbose: sending push to 1 installations
verbose: sent push! 0 success, 0 failures
```

I don't know why my pushs aren't being sent, but this message should show either 1 success or 1 failure right?

**Comment by jgyeh** [comment]
Have you tried sending a test push notification through the parse dashboard?  We're also having issues with push notifications.  We couldn't get our in app pushes to deliver through the API or through the dashboard.  No errors, just pushes not being delivered.

**Comment by rogeriochaves** [comment]
@jgyeh yeah, also getting 0 deliveries from parse dashboard ):

![image](https://cloud.githubusercontent.com/assets/792201/15131844/e83a10aa-1629-11e6-886e-d95a3c51e72c.png)
![image](https://cloud.githubusercontent.com/assets/792201/15131826/b68236a0-1629-11e6-9391-2c41e2e5f693.png)
![image](https://cloud.githubusercontent.com/assets/792201/15131831/c04c94be-1629-11e6-99da-2fb1a10d80de.png)

**Comment by rogeriochaves** [comment]
After enabling the capability on xcode and copying the new swift code on parse.com tutorial it worked, thanks!

**Comment by aBuder** [comment]
Hi @rogeriochaves, 

how do you fix the problem? I have also the same problem, sent and deliver is 0, but push notifications are received on iOS device.

**Comment by rogeriochaves** [comment]
@aBuder sorry, I don't remember, it was a long time ago ):

**Comment by aBuder** [comment]
Can you share the code?
