### ISSUE TITLE
Loading Images Over HTTPS

### ISSUE THREAD

**Issue by matt-major** [ParsePlatform/parse-server#1732]
I'm using `parse-server` to back a Swift iOS application and I'm getting 404 errors when trying to load images from a class.

My server is running behind `https://` but the image URLs being produced are `http://`, resulting in a 404 being thrown in the logs when I attempt to load the image.

Can you please advise how I can get the URLs to correctly use `https://` instead?

**Comment by drew-gross** [comment]
Have you set your `publicServerURL` to be an `https` URL?

**Comment by eddieux** [comment]
AFAIK https for images is not supported yet, or did I miss something? I tried to set publicServerURL to https, but no joy, images are loaded with http only (Parse Server 2.2.7, Android SDK 1.13.0)

**Comment by matt-major** [comment]
@drew-gross seemed to stop the error, however the images still wouldn't work. I've now added a workaround that using the URL of the file and loading with `NSData(contentsOfURL: url)`.

Whilst not ideal, it resolves this issue.
