### ISSUE TITLE
Allow REST api to comply with jsonapi.org spec

### ISSUE THREAD

**Issue by jbockerstette** [ParsePlatform/parse-server#1734]
Parse server's current REST interface does not comply with jsonapi.org.

**Comment by flovilmart** [comment]
What would be your use case?

**Comment by jbockerstette** [comment]
Some end users require that you complie with this spec. This is a
requirement for a spec I am working on. They want a Rest api but it must
complie the jsonapi. Org spec.

**Comment by flovilmart** [comment]
Changing the format of the REST API would break all compatibility with existing clients so I don't think this is something we'll implement. But you're free to provide a pull request.
