### ISSUE TITLE
Pushes delayed

### ISSUE THREAD

**Issue by coxric** [ParsePlatform/parse-server#1736]
We have a couple of pushes that are in "pending" status for nearly an hour, but Parse reports that all systems are operational. How can we know if this is working properly? Normally the pushes send in a few seconds.

**Comment by jbredice** [comment]
Same issue for our apps.

**Comment by gfosco** [comment]
Please report issues with Parse.com through http://parse.com/help (find the bug icon)

**Comment by jbredice** [comment]
This icon?  It only gives options for github projects and the database migration tool via Facebook.  Don't see any option for Parse.com.

![screen shot 2016-05-09 at 2 28 24 pm](https://cloud.githubusercontent.com/assets/3240276/15128713/5877106c-15f2-11e6-8b84-49ebb6766b90.png)

**Comment by gfosco** [comment]
Choose "Other"

**Comment by jbredice** [comment]
Got it.  Thanks.
