### ISSUE TITLE
Parse Dashboard says Push Notifications Sent but Zero Pushes Sent (from campaign & API)

### ISSUE THREAD

**Issue by jgyeh** [ParsePlatform/parse-server#1737]
At 12:30 PM PST, our REST API triggered push notifications stopped being delivered.  

We tested sending push notifications through the dashboard as a test campaign.  In both cases (through the app/API and through the dashboard), the push notification is registered as successfully sent but 0 push notifications are actually sent.

**Comment by jgyeh** [comment]
Some push notifications are coming through now but being delayed by up to 10 minutes.  Crazy.

**Comment by philipkimmey** [comment]
We're seeing the same thing.

**Comment by jgyeh** [comment]
Looks like the issue has been resolved.  All push notifications are coming through now.

**Comment by drew-gross** [comment]
For issues with the api.parse.com, please use [parse.com/help](http://parse.com/help).

**Comment by adrianharris** [comment]
I know this is closed, but I was seeing this last night, and now I am seeing it intermittently this morning - behaviour includes:
- multiple pushes marked as pending in the Parse.com dashboard and not being received
- I can send a push (via API) one minute and it is sent fine with 1 push shown, then the next minute I send the exact same push and it isn't received yet is marked as sent, but with 0 pushes...
