### ISSUE TITLE
Want to deploy parse server on google cloud with Android Push only 

### ISSUE THREAD

**Issue by Himanshu4003** [ParsePlatform/parse-server#1741]
I have successfully deploy parse server demo from here for Google cloud 👍 

[Parse Server AppEngine](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/appengine/parse-server)
Now i have following code configuration in my server.js 

```Java
var parseServer = new ParseServer({
  databaseURI: nconf.get('DATABASE_URI') || 'mongodb://localhost:27017/dev',
  cloud: nconf.get('CLOUD_PATH') || __dirname + '/cloud/main.js',
  appId: nconf.get('APP_ID'),
  masterKey: nconf.get('MASTER_KEY'),
  fileKey: nconf.get('FILE_KEY'),
  serverURL: nconf.get('SERVER_URL'),
  push: {
      android: {
        senderId: 'mysenderId',
        apiKey: 'myserverkey'
      },
      ios: {
        pfx: '/file/path/to/XXX.p12',
        bundleId: '',
        production: false
      }
    }
});
```

But it give me following Error when i try to deploy it 

(gcloud.preview.app.deploy) Error Response: [13] Timed out when starting VMs.  It's possible that the application code is unhealthy.  (0/2 ready, 2 still deploying).

Does it due to ios JSON in my ParseServer Configuration  .If i want to configure for only android then how to do that ?

**Comment by bohemima** [comment]
This question is more suited for Stackoverflow but nonetheless, does it run locally? Any more specific errors in the logs? Definitely remove the ios-part of the configuration if you are not using it.

**Comment by Himanshu4003** [comment]
Yes i checked by running 

npm start

and it's working fine .

**Comment by bohemima** [comment]
Please read everything I wrote about logs and removing the ios-part also.

**Comment by Himanshu4003** [comment]
@bohemima  Thanks i remove ios part as it's have issue which cause to my deployment fail .
