### ISSUE TITLE
Migration Tool Issue (Parse to Azure - DocumentDB)

### ISSUE THREAD

**Issue by Treybro** [ParsePlatform/parse-server#1743]
I'm currently in the process of migrating a live production mobile application from Parse to Azure using the Migration Tool provided by the good folk at Parse, however I'm getting stuck on the "Sync Phase".

I'm getting all green lines indicating a successful transfer of the data, however when the migration tool is checking for any new writes, it fails with the following error:

["There was a problem with the migration."](http://i.stack.imgur.com/LqRMa.png)

Parse documentation doesn't have any information on the above, so I would appreciate your help!

I'm running my Azure server and Document DB instances on the S3 (Standard: Large) with Auto scaling, and the Document DB implementation is on Pricing Tier S3 (THROUGHPUT (RU/s) 2500)

**Comment by drew-gross** [comment]
For issues with the migration process, please use [parse.com/help](http://parse.com/help).
