### ISSUE TITLE
How to use multiple apps using PM2 and Nginx 

### ISSUE THREAD

**Issue by geekyfox90** [ParsePlatform/parse-server#1744]
Hello there !

I'm wondering on how I can migrate different apps to the same server, I'm using PM2 to ensure it's always running.

Here is my ecosystem file 

`{
  "apps" : [{
    "name"        : "parse-wrapper",
    "script"      : "/usr/bin/parse-server",
    "watch"       : true,
    "merge_logs"  : true,
    "cwd"         : "/home/parse",
    "env": {
      "PARSE_SERVER_CLOUD_CODE_MAIN": "/home/parse/cloud/main.js",
      "PARSE_SERVER_DATABASE_URI": "mongodb://parse:password@your_domain_name:27017/database_name?ssl=true",
      "PARSE_SERVER_APPLICATION_ID": "your_application_id",
      "PARSE_SERVER_MASTER_KEY": "your_master_key",
    }
  }]
}`

Shoud I use the same ecosystem file or should I create a new one and run ??

> PM2 start

How to configure the URL to different apps in Nginx 
```

        location /app1/ {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://localhost:1337/parse/;
                proxy_ssl_session_reuse off;
                proxy_set_header Host $http_host;
                proxy_redirect off;
        }
```

**Comment by drew-gross** [comment]
This seems to be specific to nginx and pm2. Please use this repr for reporting bugs in Parse Server.

**Comment by gregyoung14** [comment]
@geekyfox90 Have you gotten anywhere with this? I'm also trying to configure multiple parse apps behind nginx on pm2

**Comment by geekyfox90** [comment]
Hello @gregyoung14 ! Sorry for late response, but I haven't found nothing ! what about you ?
