### ISSUE TITLE
Incorrect documentation in wiki for S3 fileadapter AWS Policy Document configuration

### ISSUE THREAD

**Issue by jsdalton** [ParsePlatform/parse-server#1748]
These instructions present an example AWS Policy for use with the S3 file adapter:

https://github.com/ParsePlatform/parse-server/wiki/Configuring-File-Adapters#set-up-your-bucket-and-permissions

The problem is that the permissions granted in the "Resource" section are insufficient:

```
"Resource": [
  "arn:aws:s3:::BUCKET_NAME/*"
]
```

Specifically, the parse-server-s3-adapter module calls the createBucket() method of the AWS SDK. The permissions on the above ARN only give the policy the ability to create resources within the bucket, not to create the bucket itself.

To get things working you need to add an additional resource match:

```
"Resource": [
  "arn:aws:s3:::BUCKET_NAME",
  "arn:aws:s3:::BUCKET_NAME/*"
]
```

So this gives the client permission to create and/or remove the actual bucket, in addition to creating and working with resources under the bucket.

At least this is what I had to do in order to get things working!

**Comment by camwes** [comment]
@jsdalton the instructions say to create the bucket in the AWS console, is that also invalid?

**Comment by jsdalton** [comment]
@camwes You do need to create the bucket first (via the console, or however). The rest of the instructions are correct, save for those permissions on the Policy document

**Comment by flovilmart** [comment]
Thanks for reporting that! Just updated the wiki to match your suggestion
