### ISSUE TITLE
limit = 0 is not work in installations

### ISSUE THREAD

**Issue by ssk7833** [ParsePlatform/parse-server#1755]
- [x] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.

- [x] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases

- [x] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.

#### Environment Setup

- Server: 
  - parse-server: 2.2.9
  - operating system: Windows 7
  - local
- Database: mongoDB 3.2.4 local

#### Steps to reproduce

After count problem solved #1726, I want to get the count only so add the limit parameter, but it didn't work.

    $ curl -X GET \ 
      -H "X-Parse-Application-Id: myAppId" \
      -H "X-Parse-Master-Key: myMasterKey" \
      http://localhost:1337/parse/installations/?count=1&limit=0

This is what I got:

    {
      results: [
        ...my installations...
      ],
      count: 5
    }

But what I expected is like current Parse REST API when I use the command below:

    $ curl -X GET \
      -H "X-Parse-Application-Id: myAppId" \
      -H "X-Parse-Master-Key: myMasterKey" \
      -H "X-Parse-REST-API-Key: myRestApiKey" \
      https://api.parse.com/1/installations/?count=1&limit=0

It response with installations count like this:

    {
      results: [],
	  count: 5
    }

I tried that parameter like limit = 1 limit = 2 worked good, only 0 not.

**Comment by bohemima** [comment]
I think, since there is no upper limit on "limit" anymore, that 0 would mean "give me everything", try with -1? (Just guessing here)

**Comment by jeveloper** [comment]
Hey @ssk7833 , i thought it wasnt recommended to use mongo 3.2.X and must use 3.0 ? 
Can you confirm if parse server is fine using 3.2?

thank you

**Comment by ssk7833** [comment]
Yes, I'm using mongoDB 3.2.4.
My environment setup list is correct and it works good.

**Comment by drew-gross** [comment]
We only officially support Mongo 3.08 and 2.6.11, but the issues in Mongo 3.2.x are related to GeoPoints mostly, so if you aren't using GeoPoints, Mongo 3.2.x might mostly work. We won't be able to provide support or bugfixes for Mongo 3.2.x though.

**Comment by jeveloper** [comment]
Ahh good to know, i definitely use Geopoints
