### ISSUE TITLE
Server side validation?

### ISSUE THREAD

**Issue by Broham** [ParsePlatform/parse-server#1769]
Do I need to worry about setting up my own server side validation to prevent mongoDB injection when using Parse Server?  For instance, if I was running my MongoDB instance locally and wanted to update a record by `_id` (or some other field) I would typically confirm that the `_id` value was a string and not an object.

Do I need to do anything like this with Parse using a `beforeSave` trigger or is that all handled internally?

**Comment by drew-gross** [comment]
Parse Server will ensure that the data in each object matches the schema for the object. In the future, please use stackoverflow for implementation related questions, this repo is for bug reports and the development of Parse Server.
