### ISSUE TITLE
advanced targeting

### ISSUE THREAD

**Issue by iedux** [ParsePlatform/parse-server#1771]
When im trying to send a push to only one device through a device token it is sending a error like this:

**{"error":"Unexpected token }"}**

Can you help me to figure out , thanks, this is the curl im using

curl -X POST \
    -H "X-Parse-Application-Id: appIdNumber" \
    -H "X-Parse-Master-Key: MasterKeyNumber" \
    -H "Content-Type: application/json" \
    -d '{
          "where": {
            "deviceToken" : "erwrwerew.rwe......."
          },
          "data": {
            "title": "Hey",
            "alert": " hello",
          }
        }'\   http://hostname/parse/push

**Comment by drew-gross** [comment]
We have lots of passing test cases that cover these features. Can you post some code that reliably reproduces your issue? Ideally as a test case we can add to our test suite.

**Comment by iedux** [comment]
I just found my error, i was testing from command line and  i had to remove "\" and put all in one line. Thanks for the help. Really love parse server :D
