### ISSUE TITLE
Field `authData` is `(undefined)` in self-hosted Parse dashboard

### ISSUE THREAD

**Issue by mtrezza** [ParsePlatform/parse-server#1779]
#### Environment Setup
- Server: parse-server 2.2.9, parse-dashboard 1.0.11

#### Steps to reproduce
1. open class `User` in self-hosted parse dashboard
2. view user that has data in field `authData` -> field is of value `(undefined)` although in parse.com-hosted dashboard the authData is visible.

(I assume this is also a parse-server bug and not a dashboard bug since @drew-gross moved similar bugs from parse-dashboard to parse-server)

**Comment by drew-gross** [comment]
To help us debug this, can you include the exact request and response in Parse Server? (you can see this in the logs using `VERBOSE=1` environment variable)

Submitting a failing test case as a PR would also be extremely helpful.

**Comment by mtrezza** [comment]
I wasn't able to reproduce it anymore, maybe a mistake on my side. I'd suggest to close the issue for now, I'll reopen it if it happens again.

**Comment by mtrezza** [comment]
Just for reference, the bug occurred again on parse server 2.2.7. Updating to parse server 2.2.9 solved it.
