### ISSUE TITLE
Is migrating from Parse.com to self-hosted much simpler than docs make it seem?

### ISSUE THREAD

**Issue by jayboyd** [ParsePlatform/parse-server#1781]
This is a very basic question. I'm just migrating now from Parse.com, setting up Parse Server on my web host, and am slightly confused by the docs on doing this. Specifically, it *seems* after much reading and experimenting that the ONLY thing needed is to do 

1. _npm install parse-server_
2. Create a _parse-config.json_ file to minimally contain the app key and mongoDB URI
3. Start the server with _[path]/parse-server -- parse-config.json_

However the amount of docs explaining how to migrate, which never boils it down to these simple 3 steps, makes me concerned that I'm missing some bigger picture. 

One concrete question -- the docs state that the best way is to grab the parse-server-example repo as it "contains a working example built on an Express app". However, since the above 3 steps seem to work just fine, can I infer that the parse-server repo already contains the boilerplate for the Express app?

To be very clear, my question ultimately is: are the above 3 steps all that are necessary to move an existing Parse.com backend to another host, and if not, why not? What is the advantage of grabbing the example repo? 

If the answer is yes, I feel like many people would be served by simplifying the migration guides to include this as chapter 1, step 1. Everything about hosting on Heroku, mLab, etc. unnecessarily complicates the process, even if these are commonly desired setups. 

Thanks for any assistance.

**Comment by flovilmart** [comment]
@jayboyd you are right, for many use cases, this will be enough.

The is also the bootstrap.sh script that would create everything you need, step by step.
