### ISSUE TITLE
requestPasswordReset returns error 108

### ISSUE THREAD

**Issue by oproulx** [ParsePlatform/parse-server#1784]
I'm calling the following function
/parse/requestPasswordReset

But it returns:
{
  "code": 108,
  "error": "This path is not implemented yet."
}

I've installed the mailgun adapter (package.json)
  "parse-server-simple-mailgun-adapter":"1.0.0",

And configured it in the index.js
emailAdapter: {
      module: 'parse-server-simple-mailgun-adapter',
      options: {
        // The address that your emails come from
        fromAddress: 'me@mydomain.com',
        // Your domain from mailgun.com
        domain: 'mydomain.com',
        // Your API key from mailgun.com
        apiKey: 'key-XXXXXXX',
      }
    }

Any ideas?  Thanks!

**Comment by drew-gross** [comment]
You probably need a newer version of Parse Server

**Comment by oproulx** [comment]
I'll try that now...

**Comment by drew-gross** [comment]
Yep, you definitely need a newer version. 2.2.9  is the most recent.
