### ISSUE TITLE
Homepage Parse -> Push gives "500 error"

### ISSUE THREAD

**Issue by quizdomapp** [ParsePlatform/parse-server#1785]
When I go to Parse, page Push (https://www.parse.com/apps/quizdom/push_notifications), then a "500-Error" appears:

![image](https://cloud.githubusercontent.com/assets/11816996/15257169/b90d8114-194d-11e6-92c4-41b649c24229.png)

Sometimes, an it works, but the same error appears later upon clicking on "Campaign" or the "Send Push"-button.

Can you please check? We need to send a mass push asap :)

**Comment by drew-gross** [comment]
For issues with the parse.com service, please use [parse.com/help](http://parse.com/help).
