### ISSUE TITLE
Parse server is stopped while migrating the DB

### ISSUE THREAD

**Issue by JonathanKirknes** [ParsePlatform/parse-server#1791]
My Parse server is stopped while migrating the DB.
I followed migrating guide to deploy my own parse server on Amazon.
But I think it was failed.
So I terminated the server on Amazon EC2.
But I am getting this error when I try to open my parse app on Parse.com.

![screen shot 2016-05-14 at 4 10 19 pm](https://cloud.githubusercontent.com/assets/17483938/15268644/701c365c-19ee-11e6-8918-9ed5a0ed5255.png)

How can I restore my parse app on Parse.com.
I need to keep my Parse app working.
Please help me on this issue.

Thanks.

Jonathan

**Comment by drew-gross** [comment]
For issues with the parse.com service, please use [parse.com/help](http://parse.com/help).
