### ISSUE TITLE
I wonder be maintained what existing photo storage?

### ISSUE THREAD

**Issue by json-park** [ParsePlatform/parse-server#1799]
Hello!

I wonder be maintained what existing photo storage?

Can I use a existing photo url(http://files.parsetfss.com/3dcb99af-427a-4843-ac88-348e5ef82e6a/tfss-aa961d28-c68b-48af-a041-8b7dbda33e7b-1462960383389.jpg) when parse server ending?

Thank you.

**Comment by bohemima** [comment]
No, they will have to be migrated to use your own storage. Parse folks have said before there will be a plan for this.

**Comment by hramos** [comment]
See #8

**Comment by json-park** [comment]
Thank you @bohemima  @hramos  :)
