### ISSUE TITLE
Not receiving notifications in Android 6 (Marshmallow) after shifting to own Parse server

### ISSUE THREAD

**Issue by Lx980** [ParsePlatform/parse-server#1803]
I migrated to my own Parse server recently. Pushes seem to be working fine on all versions of android except for android 6!

**Comment by bohemima** [comment]
To help debug please run parse-server with environment variable VERBOSE set to 1 and paste relevant lines from the output here.

**Comment by flovilmart** [comment]
This would need to go on the https://github.com/parse-server-modules/parse-server-gcs-adapter

Thanks for reporting.
