### ISSUE TITLE
Parse.Cloud.useMasterKey has global effect

### ISSUE THREAD

**Issue by steven274** [ParsePlatform/parse-server#1805]
I have 2 cloud code function func1 with useMasterKey and func2 without it

First time I called func2, I got permission error. Then I call func1 and func2 again, all errors disappeared.

**Comment by oallouch** [comment]
https://github.com/ParsePlatform/parse-server/issues/37
https://github.com/ParsePlatform/parse-server/issues/1646

The search functionality on github is amazing :)
