### ISSUE TITLE
Logger errors with "file already exists" when running multiple instances of Parse Server on the same machine.

### ISSUE THREAD

**Issue by steven-supersolid** [ParsePlatform/parse-server#1806]
Running parse-server 2.2.7 on heroku using clustering via throng we sometimes see an error on server startup:

May 16 13:56:48 myappname app/web.5: > @ start /app 
May 16 13:56:48 myappname app/web.5: > node src/index.js 
May 16 13:56:49 myappname app/web.5: fs.js:794 
May 16 13:56:49 myappname app/web.5:   return binding.mkdir(pathModule._makeLong(path), 
May 16 13:56:49 myappname app/web.5:                  ^ 
May 16 13:56:49 myappname app/web.5: Error: EEXIST: file already exists, mkdir '/app/logs' 
May 16 13:56:49 myappname app/web.5:     at Error (native) 
May 16 13:56:49 myappname app/web.5:     at Object.fs.mkdirSync (fs.js:794:18) 
May 16 13:56:49 myappname app/web.5:     at configureLogger (/app/node_modules/parse-server/lib/logger.js:71:18) 
May 16 13:56:49 myappname app/web.5:     at Object.<anonymous> (/app/node_modules/parse-server/lib/logger.js:80:1) 
May 16 13:56:49 myappname app/web.5:     at Module._compile (module.js:409:26) 
May 16 13:56:49 myappname app/web.5:     at Object.Module._extensions..js (module.js:416:10) 
May 16 13:56:49 myappname app/web.5:     at Module.load (module.js:343:32) 
May 16 13:56:49 myappname app/web.5:     at Function.Module._load (module.js:300:12) 
May 16 13:56:49 myappname app/web.5:     at Module.require (module.js:353:17) 
May 16 13:56:49 myappname app/web.5:     at require (internal/module.js:12:17) 

Index.js looks like:
```
var throng = require('throng');
var WORKERS = process.env.WEB_CONCURRENCY || 1;

var start = function(id) {
	var express = require('express');
	var ParseServer = require('parse-server').ParseServer;
...
	var api = new ParseServer(config);

	app.use(mountPath, api);

	app.get('/', function(req, res) {
		res.status(200).send('OK');
	});

	app.listen(port, function() {
		console.log('worker ' + id + '/' + WORKERS + ' on port ' + port + ' for app ' + Parse.applicationId);
	});
};

throng(start, {
	workers: WORKERS,
	lifetime: Infinity
});

```

**Comment by drew-gross** [comment]
Thanks for the fix @steven-supersolid
