### ISSUE TITLE
Cloud Code Unable To Connect

### ISSUE THREAD

**Issue by seeya** [ParsePlatform/parse-server#1807]
I'm getting this error when I try to call a cloud function which uses Parse function. I'm not sure whether it's the masterkey that is causing this problem. Anyone manage to solve this? I've tried a lot of solutions but didn't work.
```
{
  "code": 141,
  "error": {
    "code": 100,
    "message": "XMLHttpRequest failed: \"Unable to connect to the Parse API\""
  }
}
```

**Comment by drew-gross** [comment]
This indicates a network issue. Make sure your internet is connected and you have set the Parse URLs correctly.

**Comment by seeya** [comment]
I've set the serverURL in this format
`serverURL:` http://{publicip}:port/parse 
Using the sdks I'm able to create new data. However not with the cloud code.

**Comment by drew-gross** [comment]
try `serverURL: http://localhost:port/parse`

**Comment by seeya** [comment]
I referred to the parse-server-example codes and I think I found the problem. 
I had 2 instances of ParseServer created in the same file which may have caused the problem.
Once I removed one, I was able to use the cloud code functions. 
Is there a way to run multiple instances of cloud code within the same express server?

**Comment by drew-gross** [comment]
Yep that would be the problem. Unfortunately there is no way to run multiple instances of cloud code on the save server, due to the use of global variables inside the Parse SDK.
