### ISSUE TITLE
"Error: mac verify failure" when pushing notification

### ISSUE THREAD

**Issue by barnaclejive** [ParsePlatform/parse-server#1809]
I am following the [parse-server Push quick start guide](https://github.com/ParsePlatform/parse-server/wiki/Push#quick-start). When I initiate a push via curl on my local machine, I am seeing a "mac verify failure" in the server node log. Are there aditional steps that are missing from the documentation to make this work?

```
curl -X POST \
    -H "X-Parse-Application-Id: myapp_id" \
    -H "X-Parse-Master-Key: myapp_masterkey" \
    -H "Content-Type: application/json" \
    -d '{
          "where": {
            "deviceType": {
              "$in": [
                "ios",
                "android"
              ]
            }
          },
          "data": {
            "title": "The Shining",
            "alert": "All work and no play makes Jack a dull boy."
          }
        }'\   http://myapp.us-east-1.elasticbeanstalk.com/parse/push
```

> parse-server-example running on port 8081.
> /var/app/current/node_modules/parse-server/lib/ParseServer.js:339
>             throw err;
>             ^
> 
> Error: mac verify failure
>     at Error (native)
>     at Object.createSecureContext (_tls_common.js:132:17)
>     at Object.TLSSocket._init.ssl.onclienthello.ssl.oncertcb.exports.connect (_tls_wrap.js:972:23)
>     at apnSocket (/var/app/current/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/lib/socket.js:56:19)
>     at Connection.<anonymous> (/var/app/current/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/lib/connection.js:199:17)
>     at _fulfilled (/var/app/current/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/node_modules/q/q.js:834:54)
>     at self.promiseDispatch.done (/var/app/current/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/node_modules/q/q.js:863:30)
>     at Promise.promise.promiseDispatch (/var/app/current/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/node_modules/q/q.js:796:13)
>     at /var/app/current/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/node_modules/q/q.js:604:44
>     at runSingle (/var/app/current/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/node_modules/q/q.js:137:13)

**Comment by shresthak** [comment]
https://github.com/parse-server-modules/parse-server-push-adapter/issues/15

**Comment by flovilmart** [comment]
Closing as answered on the push-adapter repo
