### ISSUE TITLE
Parse Server + App Engine + Datastore

### ISSUE THREAD

**Issue by otymartin** [ParsePlatform/parse-server#181]
Is Parse-Server compatible with Google Datastore I have to use MongoDB/MongoLab e.t.c.?

**Comment by pccrazy** [comment]
as parse suggested you will have to use  MongoDB/MongoLab.

**Comment by skinp** [comment]
@otymartin you will have to use MongoDB. There is plan to add support for other databases, you can follow along in #20. Note that for migrations, we only plan on supporting MongoDB.

**Comment by otymartin** [comment]
@skinp Thanks
