### ISSUE TITLE
Parse Deploy functionality

### ISSUE THREAD

**Issue by pixelbendr** [ParsePlatform/parse-server#1815]
Is there a way I can have the parse deploy live code changes functionality in a Heroku environment.

**Comment by bohemima** [comment]
Wouldn't that simply be a git push?

**Comment by pixelbendr** [comment]
Sorry, I meant 'parse develop' functionality. Just for a development environment. makes updates faster so I don't have to always git push the smallest code changes.

**Comment by bohemima** [comment]
I think you can use any kind of process manager to handle this, pm2, nodemon, etc. Also have a look at this repo's bin/dev-script

**Comment by pixelbendr** [comment]
ok. thank you for this.
