### ISSUE TITLE
beforeSave is not called when data type is incorrect

### ISSUE THREAD

**Issue by adampietrasiak** [ParsePlatform/parse-server#1816]
I have column in my collection with type of `array`.

But in some cases `string` is sent instead of array, so to take care of that I've created `beforeSave` callback that is checking exactly for that and if this is `string`, it'll be converted to `array` with that string

`if ( !object.get("weekday")  instanceOf Array ) object.set("weekday", [object.get("weekday")]);`

The point is, that if `string` is set, beforeSave is not even called, instead it instantly returns response error I've get error:

`schema mismatch for Goal.weekday; expected [object Object] but got String'`

I've tried to `console.log` something in the beginning of my `beforeSave` callback code but it's not called at all

Is there any way to have `beforeSave` callback that will be called BEFORE types of data are validated?

I think it's weird, because my beforeSave callback is made to fix some data types issues, but it's not allowed to be fired before data types are validated.

**Comment by drew-gross** [comment]
This is a bit of a weird edge case, but if it worked in Parse.com we should make it work in Parse Server. We'll look into it.

**Comment by drew-gross** [comment]
OK, I tried this on Parse.com and it didn't work. This is my Cloud Code on Parse.com:

````js
Parse.Cloud.beforeSave('Object', function(request, response) {
  request.object.set('shouldBeString', 'string' + request.object.get('shouldBeString'));
  response.success();
});
```

And my response when I try to save a number:
```json
{"code":111,"error":"invalid type for key shouldBeString, expected string, but got number"}
```

Can you post the the exact code you are using on Parse.com, that works?

**Comment by adampietrasiak** [comment]
My code was never tested on parse.com

Example you've posted shows exactly the same issue as I've got. You've got beforeSave hook that would convert some value to string, but it's not allowed to be fired, because at first your value was number. I'm pretty sure such validation should be made just before data is saved to database, not before "beforeSave" hooks are called.

**Comment by drew-gross** [comment]
We are aiming to not have any changed behaviour from Parse.com, so I don't think we are going to make this change. Imagine if someone ports their existing cloud code that relies on the data format being correct before it reaches the `beforeSave`, they could start getting corrupt data and their whole app could break. You'll have to fix your client code to send the right data type.

**Comment by adampietrasiak** [comment]
Thats quite limiting in my opinion. I think there should be some kind of flag, that would be disabled by default that would enable "breaking" changes.

If the flag would be disabled by default, then migration would not break any app from parse.com.

I feel what I've just wrote looks like overkill, so I'll just say again - thats quite limiting. Especially when it's open source now.

**Comment by drew-gross** [comment]
Coming a from a background of using strongly typed languages, I'm not really a fan of the "take whatever you get and coerce it to the right type" pattern anyway. Also, if you only have one field that you have to muck with the types of, and you enable this flag, you now have to check the types of every field, in case any of them are wrong too.

Besides, Is it really that hard to just do the coercion at the call site? I can't imagine it being more than 1-2 lines of code.

**Comment by adampietrasiak** [comment]
My case is converting natural language duration like "4 hours 20 minutes" to minutes count integer. In such case it would be very useful to have such beforeSave hook so I don't need to worry about converting it everywhere where it's saved.

**Comment by flovilmart** [comment]
What i Would do in that case, is store the string in a param and use the beforeSave to process it. You can delete the string of you don't need it. You can also store in in the target object, as 'originalString' and do your processing
