### ISSUE TITLE
unit testing for cloud code triggers (afterSave, beforeSave ... etc)?

### ISSUE THREAD

**Issue by benishak** [ParsePlatform/parse-server#1819]
I want to test if my code in `beforeSave` works fine or not

In my beforeSave I can increment or update same fields of the same object or even of a different object, for example if user like a post in my app, I can increment the `likeCount` in the `_User` class.

Is there a way to test such kind of code?

**Comment by drew-gross** [comment]
Now that Parse Server is open source, you can spin up a parse server in your tests and use it to do unit testing. Easy! For running mongodb in tests, check out `mongodb-runner`, which is what we use to test Parse Server itself.
