### ISSUE TITLE
Call REST API with Postman - 119 Permission denied for this action

### ISSUE THREAD

**Issue by mistre83** [ParsePlatform/parse-server#1822]
I've just setup today parse-server and parse-dashboard, so i have latest version of both.

I've created a new class and added a CLP to one existing User (created with Parse Javascript)

When now i try to make a POST with Postman (i didnt have tested it with CURL, but with VERBOSE=1 i see correct log - i think) i get the error 119 - Permission denied for this action.

The CPL on class has been set via parse-dashboard and i've added the user (the only user i have) to Read and Write. Looking directly on MongoDB the setup on metadata appears to be fine.

I'm sending my credential using Basic Auth with the username and password i've used to register the User.

If i try to remove the CLP, i can post without problems

EDIT:
If i try to use parse-dashboard API Console without using Master Key and without Run ass.. i get 119 - Permission Denied -> CORRECT

If i repeat the operation with the User set on CLP i can save the class -> CORRECT

If i try to specify an unexisting user (for example i provide User ABC that do not exists), i'm always able to save the data -> **NOT CORRECT, the user not exists and the user is not authorized by CLP**

**Comment by steven-supersolid** [comment]
Can you post the Postman parameters? Even better if you can test with CURL and post that.

Also would be useful to have the server log with VERBOSE set. Which version of parse-server is this with and are you running locally?

**Comment by drew-gross** [comment]
No response in many days, closing.
