### ISSUE TITLE
Parse App Migration breaks after 2 days & Database for multiple apps?

### ISSUE THREAD

**Issue by deada92** [ParsePlatform/parse-server#1828]
So I have started to Migrate some of my Apps data & I got few questions:

1. As far as I know is the last stage of migration responsable for syncing the Parse DB with my selfhosted one till I completly switch over. I have setup saturday Parse Server & MongoDB and started to update my App code. Today I have checked again & the migration process has crashes for some reason.  
I checked the JSON output of the migration endpoint and it was at stage 9. So my question: Is there a limit for the last stage in the process?

2. Can I host for multiple apps the database on one single instance? Because Parse Server is build to handle only one app I was hoping to save some money to have a single server instance for my databases.

I know its late with starting the migration process but I'm moving fast.. i hope atleast..

PS: I tried to post this on Parse.com/help but Facebook's report tool didnt let me select anything underneath Parse...

**Comment by drew-gross** [comment]
Looks like there is a bug in Facebook. Once it is fixed, please use [parse.com/help](http://parse.com/help).
