### ISSUE TITLE
ANDROID SDK , NO RESULT (bad json response)

### ISSUE THREAD

**Issue by pccrazy** [ParsePlatform/parse-server#183]
hello , 

i have successfully migrate the data from parse to mongodb using the tools from parse ,i also installed parse server locally and its running , i have tested a query in terminal its working. However , when i tried the android sdk the app didn't show any results it show an error which says bad json response
.
![screen shot 2016-02-02 at 2 02 13 pm](https://cloud.githubusercontent.com/assets/5598959/12746089/61e2b300-c9b6-11e5-942a-0f5b8959498c.png)

the result from the query

![screen shot 2016-02-02 at 2 02 27 pm](https://cloud.githubusercontent.com/assets/5598959/12746088/61e24776-c9b6-11e5-96a1-e5e4c4552426.png)

the shell script which a run to query 

![screen shot 2016-02-02 at 2 04 38 pm](https://cloud.githubusercontent.com/assets/5598959/12746087/61e22016-c9b6-11e5-8723-a67f4cbf07f9.png)

android configuration for local parse

![screen shot 2016-02-02 at 2 04 56 pm](https://cloud.githubusercontent.com/assets/5598959/12746086/61e097a0-c9b6-11e5-89e1-d195b64e7929.png)

the query (same as the shell)

![screen shot 2016-02-02 at 2 05 09 pm](https://cloud.githubusercontent.com/assets/5598959/12746085/61de63e0-c9b6-11e5-9588-99e69620e59e.png)

android manifest.

the error 

![screen shot 2016-02-02 at 8 47 58 pm](https://cloud.githubusercontent.com/assets/5598959/12756732/7c0f1ede-c9ee-11e5-98fd-5be8dca5ca5e.png)
![screen shot 2016-02-02 at 8 48 13 pm](https://cloud.githubusercontent.com/assets/5598959/12756734/7c403d16-c9ee-11e5-9a6a-c6fc67601c8d.png)

please help

**Comment by theolm** [comment]
i had the same problem. 
try to add '/' on the end of url (http://localhost:8080/parse/)

**Comment by gfosco** [comment]
@pccrazy Please try @theolm 's suggestion and let me know if that does not fix things.

**Comment by rciovati** [comment]
I don't think `localhost` is the correct hostname because it refers to the device on which the code is running.

If you are running your app in the Android emulator you should use `10.0.2.2` instead of `localhost`.

**Comment by gfosco** [comment]
That is a good point... hehe, I didn't realize he's running it on Android.

**Comment by pccrazy** [comment]
@gfosco @rciovati @theolm  thanks guys i will try it now , i will let you know what happens

**Comment by pccrazy** [comment]
@gfosco @rciovati @theolm hi guys i have tried it , it seems i am having issues with my localhost so i upload the app in google app engine then i just added / in the last last of url and it did work finally thank you too much i appreciate it 

here is an ex of google app engine url
https://<app id>.appspot.com/parse/

**Comment by abdallahnh** [comment]
for android the server link https://localhost:1337/parse/1/ 
this worked for me
