### ISSUE TITLE
[Question] is Parse Server using any memcache, global variable?

### ISSUE THREAD

**Issue by kenglou** [ParsePlatform/parse-server#1833]
as titled. Just curious as if I store some configuration on server, is that means everytime when i want to call cloudcode and I want to access the config, Parse Server will need to re-create the variable or fetch it from database in order to process the logic? This is important since we are planning to do some logic calculation online soon.

**Comment by drew-gross** [comment]
I'm not sure what you are asking here. Parse does not use memcache, but does have some global variables. If you are accessing your Parse Config from inside your Cloud Code, that is safe. If you have some other question, please clarify.

**Comment by kenglou** [comment]
Hi,

Thank for your information, Clarification for my questions:

1. It's to make sure that if every time i make a cloud function call, is Parse server will generate an instance that process that query, and shutdown once the query is completed? or Parse Server will reserved such instance for the next query?

2. If I make a List of array stored in Global Variable and when there is a query, the List of array will pop a variable to be fetched. will that variable accessible by all query?

Hopefully i make this clear, sorry for my poor english.

Thank you.

**Comment by drew-gross** [comment]
Parse Server stays running between queries. If you have a global variable in your cloud code, it will be accessed by all queries.

**Comment by kenglou** [comment]
That means Parse Server doesn't keep anything in between queries except we put it on global variables?

**Comment by drew-gross** [comment]
There is some caching built in, with a default TTL of 5 seconds. You can change that or disable caching entirely if you want.

**Comment by sambarboza** [comment]
@drew-gross how can it be changed? Thanks.

**Comment by flovilmart** [comment]
@sambarboza you can try setting `cacheAdapter: { ttl: 3600 }` in your initialization code for enabling a cache of 1h for roles and users
