### ISSUE TITLE
Can't "get" object even when the user has the right permissions

### ISSUE THREAD

**Issue by mmahmood** [ParsePlatform/parse-server#1835]
I  have two roles Admin and User and both of them have read permission (both get and find) on class A. I am logged in as a "User" in my iOS app. And I call the cloud function through the app to get some details related to A id x. But I get this error "Permission denied for this action."

Here's the code:
var query = new Parse.Query("A");
return query.get(x);

**Comment by drew-gross** [comment]
We have lots of passing test cases that cover these features. Can you post some code that reliably reproduces your issue? Ideally as a test case we can add to our test suite.

**Comment by mmahmood** [comment]
Found the issue. I had to pass session token in query params.

var token = request.user.getSessionToken();
var query = new Parse.Query("A");
return query.get(x_id, { sessionToken: token });
