### ISSUE TITLE
Parse node.js code security

### ISSUE THREAD

**Issue by stoufa88** [ParsePlatform/parse-server#1839]
I initialized parse with a MasterKey as in https://parse.com/docs/js/api/classes/Parse.html

`Parse.initialize("XXX", "", "XXX");`

but still getting permission denied for this action. This should bypass all the security rules on the server (The one I used is Class Level permission: Read Only)

Require with `var Parse = require('parse/node')`

Similar issue:
https://github.com/ParsePlatform/parse-server/issues/1822

**Comment by steven-supersolid** [comment]
Is this the same issue as #1822 or a new issue?
If it's the same then probably best to close this one.
If it's a new issue then please provide more details. Please see #1271 for an ideal issue report.

**Comment by drew-gross** [comment]
You still need to pass `useMasterKey: true` in your queries if you want to use the SDK with the master key.

**Comment by stoufa88** [comment]
**Clear**, thank you. 
I thought this goes in `Parse.initialiaze`. 
More details can be found here: https://parse.com/docs/js/api/classes/Parse.Query.html
