### ISSUE TITLE
[Questions] How to use Parse Server to allow anonymous user groups

### ISSUE THREAD

**Issue by tonymuu** [ParsePlatform/parse-server#1843]
I'm building an app that allows users to upload/view/download and interact with the images others have uploaded to the group. The app doesn't require register/log in at all. In order to join a group, the user only need to enter a string key which is distributed by the creator of each group.

I am really stuck right now as in how do I achieve this? I looked into Parse Server + Heroku, Firebase + App Engine, and AWS Mobile Hub, but I have no idea how to implement such features on each of these services. All help / suggestion are appreciated! :)

**Comment by drew-gross** [comment]
Parse Server has an anonymous users feature. Check the docs: https://www.parse.com/docs/ios/guide#users-anonymous-users
