### ISSUE TITLE
"I dream of being a website. Please star the parse-server repo on GitHub!" instead of "Please star the parse-server repo on GitHub!" and unauthorized from dashboard

### ISSUE THREAD

**Issue by Faisal-nfl** [ParsePlatform/parse-server#1848]
I deployed parse server on heroku, a week earlier when I installed similar parse server, I got messgae "Please star the parse-server repo on GitHub!"

But now with new installation it says 
"I dream of being a website. Please star the parse-server repo on GitHub!"

Why its different now and when I try to access it from dashboard it says

`Server not reachable: unauthorized`
I double checked the appID and masterKey
why its happening

**Comment by bohemima** [comment]
This is why the text is updates -> https://github.com/ParsePlatform/parse-server-example/commit/5c1a7bca62ed1884a7d63ebc02e418a1748f4956

Triple-check appId, masterKey, mountPath and serverURL and try again.

**Comment by Faisal-nfl** [comment]
I checked them again, they are same.
Is there a limit on length of keys, i am using almost 25 characters

**Comment by Faisal-nfl** [comment]
I cloned the app from heroku
Don't why but my keys were not added so changed it
Now working from local dashboard atleat
