### ISSUE TITLE
Is there a way to access MongoDB instance in cloud code.

### ISSUE THREAD

**Issue by xor22h** [ParsePlatform/parse-server#1859]
I wondering is it possible to get a mongodb collection instance in cloud code? On my particular case I would like to run db.collection.aggregate(); It would be nice to be able to have something like

```
new Parse.Object("SomeClass").getCollection().aggregate();
```

Before moving to open source we used deployd which had similar functionality;

**Comment by drew-gross** [comment]
Cloud Code can execute any javascript, so you can just use the mongo client directly.

**Comment by xor22h** [comment]
Yes, I know that. But I thought about way of getting already created instance so I don't have to create new inside cloud code with database credentials. But yes, that's an option.

**Comment by drew-gross** [comment]
No, thats currently not possible. We are working on making Parse be able to use other databases, and some of those changes will make it easier to share connections between Parse Server and Cloud Code, but that also means that we can't ensure there is always a mongo collection available. You can create a global connection for your cloud code, and use env vars for your DB credentials, then the only issue will be that you have 2 connections instead of 1.

**Comment by jenshandersson** [comment]
Is there now a way to access the mongo connection from Cloud Code? Right now I need to open a new connection and closing it on every requests when doing a native query. How would I go about to keep a persistent mongo connection in Cloud Code?

**Comment by flovilmart** [comment]
your cloud code is required only once, so you can easily maintain your connection.

**Comment by jenshandersson** [comment]
Ah stupid me... Thanks for the help @flovilmart, works like a charm! :)

**Comment by flovilmart** [comment]
Awesome!

**Comment by Code-Crash** [comment]
Hello @flovilmart ,

I want a MongoDB instance which is already created by Parse Server, is there any way to get that instance?

I tried debugging in Parse Instance on cloud code, but no luck.

Thanks.

**Comment by flovilmart** [comment]
there is no trivial way to access the parse-server instance from cloud code nor its internals. Perhaps @Tom-Fox1 or @acinader or @dplewis would like to make it easier.

**Comment by oallouch** [comment]
Hi,
What I usually do is:
```
	const Config = require('../node_modules/parse-server/lib/Config');

	const config = Config.get(Parse.applicationId);
	const mongoAdapter = config.database.adapter;
	await mongoAdapter.connect();
	const collection = await mongoAdapter.database.collection(className);
```

**Comment by Code-Crash** [comment]
@flovilmart Thanks for the explanation.

@oallouch, yes, I guess it will for the cloud code, thanks. :)

**Comment by gitNejc** [comment]
> Hi,
> What I usually do is:
> 
> ```
> 	const Config = require('../node_modules/parse-server/lib/Config');
> 
> 	const config = Config.get(Parse.applicationId);
> 	const mongoAdapter = config.database.adapter;
> 	await mongoAdapter.connect();
> 	const collection = await mongoAdapter.database.collection(className);
> ```

Hi there. This is working great.

I'm not really sure if I understand this correctly - line await mongoAdapter.connect(); is creating new connection to mongoDb?
How can I close this connection, can't manage to close it..?

Thanks!
Nejc

**Comment by gitNejc** [comment]
Is somebody using this approach? Is new connection to mongoDb being created in this case?
How can I close this connection, can't manage to close it..?

thx

**Comment by oallouch** [comment]
In MongoStorageAdapter :

```
connect() {
    if (this.connectionPromise) {
      return this.connectionPromise;
    }
    ...
    ...
```

So, it looks like it doesn't do anything if it's already connected.
And you don't have to manage its closing.
