### ISSUE TITLE
Run Cloud Code on another Server?

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/parse-server#186]
Since cloud code needs to be on the parse server this could really eat into the resources for the server depending on how many triggers or functions you are running.  I know from the parse cloud code you can run your own Heroku server with cloud code, would their be a way for us to fire up another Heroku instance and have the cloud code run on that instead of the same server as the Parse Server?

**Comment by pccrazy** [comment]
this is a very tough decision to make actually (google , amazon or Heroku )
Heroku  is a bit expensive than Amazon and google. 
what do you think ?

**Comment by jamiechapman** [comment]
Some eventual client SDK support for AWS lambda would be pretty awesome for executing cloud code functions.

**Comment by gateway** [comment]
Well, put it this way what ever cloud system your in, it would be nice to have another server that can handle the processing or what ever is happening under the hood since latency would be very low staying in the same provider.

**Comment by doender** [comment]
I currently have parse-server + mongodb deployed on an ubuntu vm at digital ocean (smallest size: 1 core, 512mb). If you share your benchmark script, I'd like to run the same test.

**Comment by gateway** [comment]
@doender please see this thread https://github.com/ParsePlatform/parse-server/issues/185#issuecomment-178800219

**Comment by flovilmart** [comment]
Check github.com/flovilmart/parse-anywhere

**Comment by gfosco** [comment]
Follow on in #500, this will be possible with webhooks.
