### ISSUE TITLE
Parse data browser very slow after migration to mLab

### ISSUE THREAD

**Issue by touchsoft** [ParsePlatform/parse-server#1860]
We have recently migrated the database for a Parse project to mLab (currently in sandbox, but will upgrade for production), while the server itself is still Parse.com. We used the suggested AWS hosting region(AWS East). It's a small database, only around 1.5k rows in the User table. 

The site and apps have become unusably slow however, and even the data browser in the Parse dashboard has become extremely slow, with the User table now taking around 20 seconds to load, whereas before when the db was Parse hosted, this time was only a fraction of a second. 

I would hope this is not a common experience and that we have missed something fundamental in the migration. Data I/O still seems to work following the migration, it's just the speed that has suffered. Below is an entry from the 'Slow Queries' area, with the queries themselves being from the Parse dashboard:

Class	Query	Count	Slow%	Median (ms)
_User	where:{} 	2	100.0%	18674.172

I would be most grateful for any suggestions - keen to upgrade to a paid tier, but the demo tier is a bit of a put off based on experience to now, and performance would need to increase at least twentyfold to be usable again.

**Comment by drew-gross** [comment]
For issues with the migration process, please use [parse.com/help](http://parse.com/help).

**Comment by navjotjova** [comment]
+1
