### ISSUE TITLE
Cloud Code Query not being called

### ISSUE THREAD

**Issue by dcdspace** [ParsePlatform/parse-server#1863]
This query will not work in Cloud Code. I am getting the "comment is new", but nothing inside the query block. For testing I have turned off all CLPs so that shouldn't be a problem. I am running the latest version of the server locally. 

```javascript
Parse.Cloud.afterSave("Comments", function(request) {
  if (!request.object.existed()) {
    console.log("comment is new");
    var Posts = Parse.Object.extend("Posts");
    var query = new Parse.Query(Posts);
    console.log("post id: " + request.object.get("post").id);
    query.get(request.object.get("post").id, {
      success: function(post) {
        post.increment("commentCount");
        post.save({ useMasterKey: true });
      },
      error: function(error) {
        console.log("Got an error " + error.code + " : " + error.message);
      },
      useMasterKey: true
    });

  }

});
```

After a few minutes I received this: 

`query error
ParseError {
  code: 107,
  message: 'Received an error with invalid JSON from Parse: <!DOCTYPE html>\n    <html>\n    <head>\n      <meta name="viewport" content="width=device-width, initial-scale=1">\n      <style type="text/css">\n        html, body, iframe { margin: 0; padding: 0; height: 100%; }\n        iframe { display: block; width: 100%; border: none; }\n      </style>\n    <title>Application Error</title>\n    </head>\n    <body>\n      <iframe src="//s3.amazonaws.com/heroku_pages/error.html">\n        <p>Application Error</p>\n      </iframe>\n    </body>\n    </html>' }`

**Comment by ml653** [comment]
Any luck?
