### ISSUE TITLE
Error When Uploading New Version

### ISSUE THREAD

**Issue by greggmojica** [ParsePlatform/parse-server#1865]
Every time I submit a new version of the parse-server to AWS Elastic Beanstalk, I get the following error. The server runs fine on localhost.

502 Bad Gateway 
nginx/1.8.1

Any ideas? I am completely at a loss.

**Comment by drew-gross** [comment]
502 error usually means your load balancer can't connect to your app, which is a problem with your AWS config. You might be able to find help on Server Fault.

**Comment by greggmojica** [comment]
I have tried. Can someone please help me here...?

**Comment by ashokgujju** [comment]
Hi @greggmojica  I'm also facing the same issue. did you find any solution?

**Comment by greggmojica** [comment]
I ended up changing the poet to 3000 in index.js
