### ISSUE TITLE
Can parse-server work with mongodb version 3.2.x ?

### ISSUE THREAD

**Issue by drorsun** [ParsePlatform/parse-server#1867]
For the migration to hosted parse we setup mongodb release 3.0.11.
Now we consider upgrading to 3.2.6.

Is open source parse tested with 3.2.x ?

**Comment by bohemima** [comment]
From what I've gathered Parse official stance is that if you don't use GeoQueries you are good to go

**Comment by drew-gross** [comment]
Actually @TylerBrock recently submitted some PRs, so all tests are now passing on MongoDB 3.2.6, including geo queries. However, api.parse.com doesn't have these fixes, so if you still have traffic going through api.parse.com, you should stay on 3.0.8 (or whatever you have right now that is working)
