### ISSUE TITLE
No Reachable Server when migrating from Parse to Heroku + MongoDB

### ISSUE THREAD

**Issue by Mamonaku** [ParsePlatform/parse-server#1870]
Hello Everyone,

I'm having troubles migrating form Parse to Heroku + MongoLabs. I've searched the bug db, together with SO.
I followed Heroku's https://devcenter.heroku.com/articles/deploying-a-parse-server-to-heroku tutorial.

I've checked that 
- [x] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.

- [x] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases

- [x] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.

#### Environment Setup

- Server: The parse server is the vanilla version  provided by Heroku. I've added the AP_ID and client keys
- Database: Mongo DB, vanilla version provided via the mLab add-on on Heroku

#### Steps to reproduce

- Can this issue be reproduced using the Parse Server REST API? YES.
1: follow https://devcenter.heroku.com/articles/deploying-a-parse-server-to-heroku
2: go to your app, click the link 'Migrate'. The error shows up, 100% of the time.
- The expected outcome is to have data migration from parse to MOngoDB completed.

#### Logs/Trace
There are no traces.

**Comment by Mamonaku** [comment]
For all intent and purposes, this was a test migration, using Heroku's sandbox environment.

**Comment by drew-gross** [comment]
For issues with the migration service, please use [parse.com/help](http://parse.com/help).

**Comment by Mamonaku** [comment]
For all intent and purposes, the problem arise from the url driver to MongoDB, when it enables ssl spport (ssl=true), this is an option suggested by Parse. SSL support doesn't come by default on mLab, and therefore, the migration fails.

**Comment by nsarafa** [comment]
@Mamonaku have you found a workaround for this? can't seem to find any clear documentation on configuring Heroku + mLab for SSL encryption

**Comment by Mamonaku** [comment]
Hi @nsarafa, 
with mLab, I didn't because this would have required another type of subscription that I wasn't sure about (basically, to have SSL active). I went for AWS + off-the-shelf mongodb + ParseServer + docker, that's in my view the best approach for my problem.
Note: Heroku + Mongo on AWS works fine, but the latency requirement (<20 ms) needs a paid subscription before running any sort of serious prototyping.
Not sure if it fits yours.
Cheers
-M
