### ISSUE TITLE
To check Parse.initialize is successful or not

### ISSUE THREAD

**Issue by Faisal-nfl** [ParsePlatform/parse-server#1873]
I am working on an ionic app with parse server. when I write

`Parse.initialize(...)
`I just want to make sure that it has initialized successfully.

Is there a way like

```
if(Parse.initialize(...))
{
   //alert Or log
}
```
OR any other way

**Comment by drew-gross** [comment]
Nope. Parse.initialize doesn't actually make any requests to your Parse Server so it can't know if was successful. As long as your server URL and keys are right, though, there isn't much that can go wrong on the SDK side.
