### ISSUE TITLE
How to run my self hosted parse server without port number in URL?

### ISSUE THREAD

**Issue by w3care25** [ParsePlatform/parse-server#1874]
I want to run my parse server run without port number in URL as below.

https://localhost/parse instead of https://localhost:1337/parse

here is my instance code.

var express = require('express'); 
var ParseServer = require('parse-server').ParseServer; 
var app = express(); var https = require('https'); 
var fs = require('fs'); 
var api = new ParseServer({ 
databaseURI: 'mongodb://user:****@127.0.0.1:27017/parse', 
cloud: 'cloud/main.js',
 appId: 'apid', 
masterKey: 'maskey', 
serverURL: 'localhost:1337/parse';, }); 
app.use('/parse', api); 
var privateKey = fs.readFileSync( 'ssl.key' ); 
var certificate = fs.readFileSync( 'ssl.crt' ); 
https.createServer({ key: privateKey, cert: certificate }, app).listen(1337);

What changes I need to do in my instance file to run my server as https://localhost/parse

**Comment by drew-gross** [comment]
You need to run on port 80. I recommend you don't do that for local development, you can do that once you deploy in production.

**Comment by w3care25** [comment]
apache is already using port 80 .
