### ISSUE TITLE
"Unable to connect to the Parse API"

### ISSUE THREAD

**Issue by david-koch-pro** [ParsePlatform/parse-server#1880]
```js
Parse.Cloud.define("iosPush", function(request, response) {

  // request has 2 parameters: params passed by the client and the authorized user                                                                                                                               
  var userId = request.params.userId;
  var messageText = request.params.text;

  var user = Parse.Object.extend("User");
  var userQuery = new Parse.Query(user);
  userQuery.equalTo("objectId", userId);
  userQuery.find({
      success: function(results) {
        var tempUser = results[0];
        var pushQuery = new Parse.Query(Parse.Installation);
        pushQuery.equalTo('user', tempUser);
        Parse.Push.send({
          where: pushQuery,
          data: {
            alert: messageText
          }
        }, {success: function() {
          response.success('success');
        }, error: function(error) {
          response.error(error.message);
        }, useMasterKey: true});
      },
      error: function(error) {
        response.error(error.message);
      }
  });
});
```

And result is "XMLHttpRequest failed: Unable to connect to the Parse API". I think this problem is related with server configuration.
How to resolve this issue?

**Comment by david-koch-pro** [comment]
I am trying to resolve this issue for 5 days but couldn't fix. I tried the followings.
- serverURL: 'http://localhost:1337/parse'  ---> 'http://localhost/parse'
- Added rest api key, javascript key
- Added push adapter
I am using Elastic Beanstalk as server. Please help me. I feel flat :(

**Comment by hramos** [comment]
Hey @david-koch-pro, as this appears to be a server configuration question that may be out of scope for this issue tracker, I suggest posting this as a question to Server Fault. We're using the Issue tracker for reproducible bugs and issues with Parse Server.

**Comment by david-koch-pro** [comment]
Thank you
