### ISSUE TITLE
Parse server is down seeing Error 500 

### ISSUE THREAD

**Issue by cicero66** [ParsePlatform/parse-server#1891]
Hello Parse Team,

Parse server is down. We are currently receiving the error: "the service is currently unavailable".

Best regards,
Alex 
CEO

![image](https://cloud.githubusercontent.com/assets/3442467/15501718/a53b320e-21b7-11e6-90a5-b5dc0eac6788.png)

**Comment by natanrolnik** [comment]
@cicero66 I assume this is Parse.com, correct?
If so: this repo is not the right place, as it relates to the nodejs, open source version of the parse server. 
Please close this issue and report the problem in the help page (link in the image you posted).
