### ISSUE TITLE
Parse-Server question about big data entries and queries

### ISSUE THREAD

**Issue by kwstasna** [ParsePlatform/parse-server#1892]
- [x] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.

- [x] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases

- [x] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.

#### Environment Setup

Parse-Server v2.2.10
Parse-Dashboard v1.0.12
CENTOS 7.2 x86_64
mongoDB v3.0.12

#### Question.
Hello.
I've been working around parse some months now and i wonder abour Parse-Server how many data it can handle???
My question is this one because i've never worked with mongodb and nodejs before so i guess it's pretty much a good place to ask this.

Lets say how many users can Parse-Server handle ? If we have over 1m users do i have to do anything at my server so it can handle big data queries?
Would you recommend RocksDB over MongoDB that i have installed now?
I'm asking because im a junior dev. and i want some help.
Thanks for your time!

**Comment by drew-gross** [comment]
Most of these questions are more appropriate for server fault. 1m users shouldn't be a problem, but it depends very much on how active your users are, what type of queries you are using, what hardware your server is running on, and so on.

RocksDB's best benefit is it's high compression, although you will also see perf benefits in other areas as well.
