### ISSUE TITLE
Replacement for scheduled jobs available?

### ISSUE THREAD

**Issue by duergner** [ParsePlatform/parse-server#19]
One part I'm missing beside the push support is how to migrate jobs over to a hosted solution. Can someone point me to the documentation / source for this if I missed it or are there already ideas / suggestions how that should be done?

**Comment by jamesyu** [comment]
So we don't have a jobs solution out of the box for parse-server, but there are plenty of open source job queues out there. A popular node one is kue: https://github.com/Automattic/kue

And, a lot of these are more powerful than Parse's original jobs feature, so I'd recommend looking into them.
