### ISSUE TITLE
Best way to log from cloud code?

### ISSUE THREAD

**Issue by jeveloper** [ParsePlatform/parse-server#1904]
This is a question.

I was reviewing a commit and notice there is winston used for logging.
https://github.com/ParsePlatform/parse-server/blob/fece2a4b47f1469c6371c39bca63df85276e7d5f/src/logger.js

What's the best way of logging from cloud_code/main.js , it used to be console.log or console.error, is there a way to get access to winston instance?

Thank you

**Comment by ndnguru** [comment]
you can do something like this:
```		
Parse.Cloud.define('someCouldCodeFunctionName',
	function(request, response) {
		console.log('This will log to the console');
		request.log.info("This will log to the file ", {user:request.user, params:request.params});
		
```

**Comment by jeveloper** [comment]
Thanks for the tip, i guess default setup doesnt expose logger then.

**Comment by sprabs** [comment]
Is this still valid, though? I'm pretty confused by the conversation on: https://github.com/ParsePlatform/parse-server/pull/2478

Looks like the logger setup in index.js is different now. I'm just trying to figure out how to make it work. Even with verbose set to true, I'm not seeing logs anymore with the latest parse-server code...
