### ISSUE TITLE
parse DB migration issues

### ISSUE THREAD

**Issue by digitechbox-admin** [ParsePlatform/parse-server#1905]
After successfully migrating the parse DB to mlab I see multiple issues. This is the scenario:

1) Import new records to malb using mongoimport
2) The records are seen on Mlab collection
3) Count increases on dashboard
4) Queries from app and dashboard fail to show new records.

Is this attached screen shot indicative of any issue?

Abha
<img width="770" alt="screenshot of the issue may 24 18-44-37" src="https://cloud.githubusercontent.com/assets/17908773/15525890/896e15c0-21e2-11e6-9965-f5f43b977592.png">

**Comment by drew-gross** [comment]
The most likely issue is that there is an issue with your data format. Check that you've used the correct format that Parse expects by comparing objects created though the Parse API to objects created by importing.

**Comment by hramos** [comment]
I'm closing out this issue as it is not related to Parse Server. For migration assistance, please visit https://parse.com/help#report
