### ISSUE TITLE
useMasterKey option is not documented for each query

### ISSUE THREAD

**Issue by adamserafini** [ParsePlatform/parse-server#1907]
According to the [docs](https://parse.com/docs/js/api/classes/Parse.Query.html#methods_each), `useMasterKey` option is not supported for `each` queries. Only the `success` and `failure` callbacks appear to be valid for the options object.

How should we accomplish `each` queries that useMasterKey?

**Comment by steven-supersolid** [comment]
It does work so the docs are omitting the fact that this is possible. You should be able to quickly verify this.

**Comment by frederoni** [comment]
There's a small change. Check out the `JavaScript and Cloud Code Tips` at
http://blog.parse.com/learn/parse-server-video-series-april-2016/
the master key part is at around 10min.

**Comment by adamserafini** [comment]
Thanks for letting me know: it does work as you say. I am leaving this ticket open as a documentation bug to fix the [docs](https://parse.com/docs/js/api/classes/Parse.Query.html#methods_each).

Happy to make a pull request with a fix to the docs if someone can point out where they are?

**Comment by steven-supersolid** [comment]
The docs are generated from source code and can be found in the JS project: https://github.com/ParsePlatform/Parse-SDK-JS

E.g.
https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/ParseQuery.js

**Comment by adamserafini** [comment]
Created a [PR](https://github.com/ParsePlatform/Parse-SDK-JS/pull/285).

Closing this now.
