### ISSUE TITLE
unable to find index for $geoNear query

### ISSUE THREAD

**Issue by stoffern** [ParsePlatform/parse-server#1913]
### Issue Description

I have 2 classes: Cars and CarShops ( CarShops has a GeoPoint "location" )
I want to query the database for nearest cars.
When i execute the query i get this error: 
**planner returned error: unable to find index for $geoNear query**

### Steps to reproduce

```
var userGeo = new Parse.GeoPoint({longitude:longitude, latitude:latitude});

var locationQuery = new Parse.Query("CarShops");
locationQuery.near("location", userGeo);
var query = new Parse.Query("Cars");
query.include("carshop");
query.matchesQuery("carshop", locationQuery);
query.find()
.then( res => {
	response = res;
})
```

**Comment by drew-gross** [comment]
Which version of mongodb and parse server are you using? We currently require 3.0.8 or 2.6.11 (support for 3.2.6 will be available soon)

**Comment by stoffern** [comment]
@drew-gross spot on! I was running 3.2.x after downgrading and putting new data into the db the geo queries started working :) thanks
