### ISSUE TITLE
Geolocation push 

### ISSUE THREAD

**Issue by Jamarsoft** [ParsePlatform/parse-server#1915]
I am looking to implement. Push notifications in my app which is now supported with parse server. 

However I need to do two things. 

1) filter by geolocation is this functionality within parse server as it was with parse.com 

2) the ability to send a push from within the app two all users within a range of geolocation 

I have found blogs detailing the steps but they relate to parse.com and not parse server. 

Thanks

**Comment by stoffern** [comment]
Parse.com and parse server is almost 100% the same.
Look at the Cloud code documentation and create a custom function to solve this.

**Comment by Jamarsoft** [comment]
Ah ok so I could create some custom cloud code that's called on an location update which fires push notifications. 

Ok that makes sense. 

Thanks

**Comment by stoffern** [comment]
No problem :)
