### ISSUE TITLE
ACL for requesting user won't allow Read

### ISSUE THREAD

**Issue by avielfedida** [ParsePlatform/parse-server#1917]
Hi everyone, I'm using version **2.2.10**,  I followed  [this](http://blog.parse.com/learn/engineering/parse-security-v-how-to-make-friends/) parse tutorial.

Where I got to the point where I have to execute something like:

`Parse.Cloud.run('friend', {"friendId": "w5VCkWYnap"})`

I've noticed that at the server, right about here:

```
roleQuery.first().then(function(role) {
        console.log(role); // Undefined?, WHAT!
        role.getUsers().add(userToFriend);
        return role.save();
    }).then(function() {
        response.success("Success!");    
    })
```
I get `undefined`, I've looked at the ACL and its fine, I execute `Parse.Cloude.run` via user that have  `ACL(Read/Write) ` for the object I'm trying to fetch, I even logged the `request.user.id` and its the id for the user that executes `Parse.Cloude.run`, so to rule out permissions I enabled for the role I was looking `Public(Read/Write)` **and its WORKING?!, I don't get undefined anymore, everything works, what?**, I don't know if something wasn't implemented yet or its just a bug, anyway if I was doing something wrong I'd be glad to know about it.

I haven't tested running the code from the client, the `roleQuery` is part of the cloud code script, moreover I haven't tested write but I believe its the same.

**Comment by JeremyPlease** [comment]
Requests made from Parse Cloud Code don't assume the session of the requesting user. See issue #1729.

So, your code would become:

```
var sessionToken = request.user.getSessionToken();
roleQuery.first({ sessionToken: sessionToken }).then(function(role) {
    role.getUsers().add(userToFriend);
    return role.save(null, { sessionToken: sessionToken });
}).then(function() {
    response.success("Success!");    
}, function(error) {
	response.error(error);
});
```

**Comment by hramos** [comment]
@JeremyPlease's suggestion looks good to me. Closing as this is not a Parse Server issue.
