### ISSUE TITLE
Run custom query directly from MongoDB but return results through parse-server

### ISSUE THREAD

**Issue by 5amfung** [ParsePlatform/parse-server#192]
I need to run some complex queries (with aggregate functions and etc) which are not supported by the SDK.  Perhaps I could construct my own query and send the query to mongo db directly from the cloud code using MongoClient.  Once I get the results back, I want to transform them to Parse.Object and return them to the js client.

Is the following the right place to start with?  Is it as simple as iterating the results and calling untransformObject()?  Is there anything hidden that I'm not aware of that this approach would unlikely to work?

https://github.com/ParsePlatform/parse-server/blob/master/ExportAdapter.js#L580-L586

Thanks.

**Comment by gfosco** [comment]
I'd say give it a shot... If you run in to problems, let me know. :+1:

**Comment by tarekskr** [comment]
Where you able to do this @5amfung ?

**Comment by chlebta** [comment]
@5amfung @tarekskr @gfosco 
Is there any help for this ?

I need to run a complexe query where I've to use join and count
