### ISSUE TITLE
How to debug from src/ instead of /bin

### ISSUE THREAD

**Issue by mistre83** [ParsePlatform/parse-server#1921]
Hi,
i'm very sorry to ask this, but i would like to know if you can help me on how to run parse-server in "debug" mode so i can use breakpoint to go forward.

I've tried in many was but every time with node-debugger i get the compiled code (from bin/) and not the source (the src/ code).

Sorry again if i ask this, but i would like to understand better how parse load config options.

If you can reply this, you can just close.

Thanks a lot

**Comment by drew-gross** [comment]
We use babel to transpile our code. If you insert a `debugger` statement into `src` and then `npm run build`, the `debugger` will show up in the compiled code.

**Comment by mistre83** [comment]
Thanks!

In this way however, i will see the code inside /bin and not in the /src right ?

I've just tested it now but is a little difficult to read the compiled code hehe :)

**Comment by drew-gross** [comment]
Yes, unfortunately that is true. There is a way to use source maps, but we haven't set it up yet. If you are familiar with babel/node, you might be able to set it up yourself.

**Comment by mistre83** [comment]
I will try to search on the net some examples on how to do it :)

Right now i say you many thanks!
