### ISSUE TITLE
Parse server stops responding to requests. Needs server restart to work again.

### ISSUE THREAD

**Issue by allanascano-otus** [ParsePlatform/parse-server#1927]
I deployed parse-server-example using the Deploy to AWS button. I also migrated my database to mLab. Everything works fine. I can retrieve,create,update records in mlab database using the android and javascript client libraries. I can also call cloud functions like mailgun and stripe.

But the server stops responding after X amount of time. I get HTTP 499 errors in access.log and looking at the nodejs.log (verbose = true), all of the request from the android library gets repeated 5 times with no response. The server still serves the html pages in public folder but accessing the server using the client library (android and javascript) returns nothing.

Restarting the server fixes the problem but again after X amount of time it stops responding again.

Any pointers will be much appreciated.

**Comment by huang1196** [comment]
It seems the same issue with #https://github.com/ParsePlatform/parse-server/issues/1878

**Comment by drew-gross** [comment]
I think this is the similar to #1855 which can be fixed by setting your `mongodb` version to `2.1.18`
