### ISSUE TITLE
Parse SDK and parse-server: missing documentation for node.js

### ISSUE THREAD

**Issue by neophob** [ParsePlatform/parse-server#1929]
Hi

I want to use parse-server in a nodejs express application. Are there any up to date documentations available for the nodejs version of the JS SDK? As the JS SDK documentation is for browser JS versions only, there are quite some differences when using nodejs like:
- `require('parse/node');` instead `require('parse');`
- no `Parse.User.current();` user

I have some issues with basic functions like:
- how do I logout an active session?
- how to verify if current session is valid?
- how do I prevent that the session table create a new entry for each login (old session entry is not deleted if the same user on the same machine login again)?

I use the parse-server hosting from nodechef.com (latest server and dashboard versions)

**Comment by drew-gross** [comment]
To logout a session, you just delete it from the `_Session` class. To verify if one is valid, you just make requests with it. If the requests succeed, it is valid (you could also query in the session class). You can't prevent a new session from being created on each login, as a new session on each login is pretty much the whole point of revocable sessions. You can periodically delete old sessions though, or delete all old sessions upon login.
