### ISSUE TITLE
api.parse.com is completely unusable for us

### ISSUE THREAD

**Issue by sprabs** [ParsePlatform/parse-server#1941]
It's not clear where to post this, but this has been a problem for us for almost 1.5 weeks now. I have tried filing bugs in other places, too, but they are being ignored. We are still paying for the Parse service, so this is a very terrible experience.

**Comment by bohemima** [comment]
Hopefully you did write a little more detailed "bug report" otherwise I understand the lack of answer.

 Now, this is however not the correct place to file bug reports for the hosted version of Parse.
