### ISSUE TITLE
Parse Server 2.2.10 not updating authData to latest on User save

### ISSUE THREAD

**Issue by gnu-lorien** [ParsePlatform/parse-server#1947]
### Issue Description

Parse Server 2.2.10 doesn't update authorization data when saved. There is some old access_token that keeps being assigned to my logged in user rather than the new one being provided. You can see in the following flow that I post a valid access token to the User class, and then I'm returned some other invalid access_token.
```
POST /parse/1/users { host: 'localhost:1337',
  'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
  'accept-language': 'en-US,en;q=0.5',
  'accept-encoding': 'gzip, deflate',
  referer: 'http://localhost:63342/yorick/public/index.html',
  'content-type': 'text/plain',
  'content-length': '470',
  origin: 'http://localhost:63342',
  connection: 'keep-alive',
  pragma: 'no-cache',
  'cache-control': 'no-cache' } {
  "authData": {
    "facebook": {
      "id": "REDACTED",
      "access_token": "EAAW1sZB8mZAsQBAMD1SEGzLUioe3mKmvaHCI2VBXKAnyaa8qZAifu4Xfqk0FUVoLF0RZCYpHsXkDiOdLBZBpd2Ys9ujXkpNmhPrj4kGUunJv0w3QXHSagZAO6gzBAhfXyh2qq7NXzzjGhFxy4mg2vJUjerHcztYqLfdJin1HNpHgZDZD",
      "expiration_date": "2016-05-29T20:59:35.335Z"
    }
  }
}
verbose: {
  "response": {
    "ACL": {
      "*": {
        "read": true
      },
      "8JgU9bwIix": {
        "read": true,
        "write": true
      }
    },
    "objectId": "8JgU9bwIix",
    "username": "devuser",
    "updatedAt": "2016-05-29T19:13:16.871Z",
    "createdAt": "2016-05-27T07:10:42.724Z",
    "admininterface": false,
    "storytellerinterface": false,
    "authData": {
      "facebook": {
        "id": "REDACTED",
        "access_token": "EAAW1sZB8mZAsQBAGXJZA0kWDyJLBY2yDOIqTou9iBuRLpwOHgw2LgRj6MnAtMZBuar0QeQo0HYLPoZB6p9filfffMtBbgRTSiI0LpLcfbZASzLRE8M6nPhf9pKB6840aZCe3fjQCwPbJcRgMeGsYJB4sP2Vvdbuo3ZA2T7gG2OpvXgZDZD",
        "expiration_date": "2016-05-27T09:00:17.948Z"
      }
    },
    "email": "andrew.sayman@gmail.com",
    "realname": "Andrew Sayman",
    "sessionToken": "r:1e86f0b8d0697e4afd11d78c6718ad75"
  },
  "location": "http://localhost:1337/parse/1/users/8JgU9bwIix"
}
```
I can't actually figure out where the old value is even being stored. It doesn't seem to be in my database anywhere. I've deleted all of the sessions. On the user object associated with this facebook ID I even manually forced it to a bad value ("aoeu"), but this other value keeps coming back.

In both the database and the javascript session this bad access_token is stored. This means I can't save any updates to the User object because the check against this bad token fails.

[FILL THIS OUT]

### Steps to reproduce

1. Log in a user using Facebook
2. Fetch the current user object
3. Save the user object

#### Expected Results

User object is updated with new and valid data

#### Actual Outcome

Auth data is old and bad, so the object fails to save and I'm now not properly authenticated on the server side

### Environment Setup

- **Server**
  - parse-server version: 2.2.10
  - Operating System:     Windows 10, Debian 7.10, Ubuntu 14.04.4 LTS
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost, remote on Digital Ocean, remote on Nitrous.io

- **Database**
  - MongoDB version: 3.2
  - Storage engine:  Default
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Localhost, remote on Digital Ocean (Debian 7.10), localhost on Nitrous.io

### Logs/Trace
```
POST /parse/1/users { host: 'localhost:1337',
  'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
  'accept-language': 'en-US,en;q=0.5',
  'accept-encoding': 'gzip, deflate',
  referer: 'http://localhost:63342/yorick/public/index.html',
  'content-type': 'text/plain',
  'content-length': '470',
  origin: 'http://localhost:63342',
  connection: 'keep-alive',
  pragma: 'no-cache',
  'cache-control': 'no-cache' } {
  "authData": {
    "facebook": {
      "id": "REDACTED",
      "access_token": "EAAW1sZB8mZAsQBAMD1SEGzLUioe3mKmvaHCI2VBXKAnyaa8qZAifu4Xfqk0FUVoLF0RZCYpHsXkDiOdLBZBpd2Ys9ujXkpNmhPrj4kGUunJv0w3QXHSagZAO6gzBAhfXyh2qq7NXzzjGhFxy4mg2vJUjerHcztYqLfdJin1HNpHgZDZD",
      "expiration_date": "2016-05-29T20:59:35.335Z"
    }
  }
}
verbose: {
  "response": {
    "ACL": {
      "*": {
        "read": true
      },
      "8JgU9bwIix": {
        "read": true,
        "write": true
      }
    },
    "objectId": "8JgU9bwIix",
    "username": "devuser",
    "updatedAt": "2016-05-29T19:13:16.871Z",
    "createdAt": "2016-05-27T07:10:42.724Z",
    "admininterface": false,
    "storytellerinterface": false,
    "authData": {
      "facebook": {
        "id": "REDACTED",
        "access_token": "EAAW1sZB8mZAsQBAGXJZA0kWDyJLBY2yDOIqTou9iBuRLpwOHgw2LgRj6MnAtMZBuar0QeQo0HYLPoZB6p9filfffMtBbgRTSiI0LpLcfbZASzLRE8M6nPhf9pKB6840aZCe3fjQCwPbJcRgMeGsYJB4sP2Vvdbuo3ZA2T7gG2OpvXgZDZD",
        "expiration_date": "2016-05-27T09:00:17.948Z"
      }
    },
    "email": "andrew.sayman@gmail.com",
    "realname": "Andrew Sayman",
    "sessionToken": "r:1e86f0b8d0697e4afd11d78c6718ad75"
  },
  "location": "http://localhost:1337/parse/1/users/8JgU9bwIix"
}
```

**Comment by dcdspace** [comment]
I also am experiencing this issue, so my workaround was manually setting the `authData` object of the returned User with the new token. If I don't do this, I got the error `Google auth is invalid for this user.`.

Did you submit a PR?

**Comment by dcdspace** [comment]
@gnu-lorien did you just start having this issue or has it always been a problem?

**Comment by gnu-lorien** [comment]
I only recently started using third party authentication, so there was no way for me to have had this problem before.

I don't have a fix for this that integrates with Parse properly. I'm using 1.5.0 and I couldn't figure out on the server end *why* this was happening, so I just worked around it in my code in commit https://github.com/gnu-lorien/yorick/commit/b31f9aec0570914274a6a68205dd5e7044abcb59

**Comment by all-iver** [comment]
I am having this problem too, I think.  When I try to save data I get "Facebook auth is invalid for this user".  Parse let me log out and in as many times as I wanted, and even delete the user and re-create it, but whenever I tried to save data from the app I'd get that error.  The only thing that made it go away was deleting the user in Parse, removing the app from my Facebook user, and re-creating the Parse user via Facebook login.

Now I can't figure out how to replicate the issue in order to be able to test and make sure users won't run into this when I migrate them.

App config looks like this (do we really need to specify the app id twice?):

```
    facebookAppIds: 'my-app-id',
    oauth: {
        facebook: {
            appIds: 'my-app-id'
        }
    },
```

**Comment by dcdspace** [comment]
I think the issue is that when you send a POST request to `/users` and provide `authData`, it checks to see if a user object exists with that id. The token is only updated when you first create the user which I think is a bug and should be updated every time you authenticate the user with a new token. 

I use Google Oauth and got the same issue of "Google Auth is invalid for this user" when trying to save because it was attempting to verify the old token. My fix was manually setting the authData to the new token before saving, but this ideally should automatically be done from the server. 

Also one thing I'm curious about is why we need to pass in Facebook app ids but not any other provider, such as Google. Thanks

**Comment by lemuelbarango** [comment]
Not sure if this issue has been resolved but I encountered the same issue with parseServer 2.1.10 and parse ios SDK 1.13 using google login. Saving the user throws an error "Google Auth is invalid for this user". Any help on how to resolve this will be appreciated.

**Comment by johanarnor** [comment]
We also had this problem (with 2.2.14) and solved it by creating two workarounds, one in the Javascript SDK and one in the Parse Server. Only one of the workarounds are needed and both should probably not be used at the same time.

### Javascript SDK
I changed [ParseUser](https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/ParseUser.js) to set the authData again after is "should have" been saved, as seen [here](https://gist.github.com/johanarnor/028a50f78a8c8bf0d58646b29a4318fa#file-parseuser-js-L1005). This persists the new authData in the server.

### Parse Server
I changed [RestWrite](https://github.com/ParsePlatform/parse-server/blob/master/src/RestWrite.js) to update the authData before returning it to the client, as seen [here](https://gist.github.com/johanarnor/aa5b88636298d22f897f1aacb7b5d5a0#file-restwrite-js-L297). This does however not persist the authData in the server, but the errors when logging in are gone.
