### ISSUE TITLE
Customize the 141 error code returned by response.error()

### ISSUE THREAD

**Issue by Talgoo** [ParsePlatform/parse-server#1950]
Hey all,

Is there a way to customize the 141 error code that comes back when doing a response.error()? 
Didn't find something helpful in the docs.

I have realized that I can use the message to store an object that includes a custom error code - but this workaround is not what I am trying to achieve. 
Just want to know if I can use my own error code **beside** the error object, like:

{
  "code": "my error code",
  "error":  {my error object}
}

Thanks a lot.

**Comment by JeremyPlease** [comment]
I've always wanted custom error codes from Cloud Code functions, so I just submitted PR #1955.

**Comment by Talgoo** [comment]
Nice man! Thanks!

**Comment by drew-gross** [comment]
I think this is a great idea. I'm going to close this to consolidate discussion in #1955.
