### ISSUE TITLE
"Parse Server" is losing the connection MongoDB after a short run.

### ISSUE THREAD

**Issue by phonggus** [ParsePlatform/parse-server#1952]
Hello,

I tried the command line "npm start" to run "parse server". but after a short period of a few minutes, the "parse server" can not tell "MongoDB" to get the data that I have to restart the "parse server". Which means I have to run back to the command line "npm start" again and it also lost the connection after a few minutes.

**Comment by giano** [comment]
See issue #1855 for this. 
Basically "freeze" your MongoDb version to 2.1.18 in package.json. 
They are working on it.
