### ISSUE TITLE
When can we expect a new Release?

### ISSUE THREAD

**Issue by shivangagarwal** [ParsePlatform/parse-server#1956]
Hi,

I know this is not an issue, but we are waiting on the latest release to move the parse-server to production. Can you let us know when the latest release will happen.

Shivang

**Comment by drew-gross** [comment]
Just pushed one a few minutes ago. Lots of bugfixes included!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.19](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.19)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)
