### ISSUE TITLE
Cannot Create Objects (Schema is Frozen)

### ISSUE THREAD

**Issue by Nightsd01** [ParsePlatform/parse-server#1957]
**Describe your issue in as much detail as possible.**
When launching parse-server, I cannot create new objects (on an empty MongoDB database installation). I get the following response whenever trying to save an object:

{"code":107,"error":"schema is frozen, cannot add: GameScore"}

**Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.**
1. I launch the server using test values for things like 'appId', 'masterKey', etc.

2. I launch the following CURL request:

curl -X POST
     -H "X-Parse-Application-Id: testId" 
     -H "Content-Type: application/json" 
     -d '{"score":1337,"playerName":"Sean Plott","cheatMode":false}' 
     http://localhost:1337/parse/classes/GameScore

**#### Expected Results**

Normally, I would get the following response:

{
  "objectId": "2ntvSpRGIK",
  "createdAt": "2016-03-11T23:51:48.050Z"
}

#### Actual Outcome

Instead, this is the error I get:

{"code":107,"error":"schema is frozen, cannot add: GameScore"}

### Environment Setup

- **Server**
  - parse-server version: 2.2.10
  - Operating System:    Ubuntu 14.04.2 LTS
  - Hardware:            AWS Ubuntu EC2 instance
  - Localhost or remote server? AWS - Problem occurs on both localhost (OS X) and AWS (Ubuntu 14.04.2)

- **Database**
  - MongoDB version: 3.2
  - Storage engine:  WiredTiger
  - Hardware:        It is a t2.micro EC2 instance (1 vCPU, 1GB RAM), however it also has the same issue on my OS X machine (32GB RAM, Intel Xeon e5-2630)
  - Localhost or remote server? Localhost (attempted both with local MongoDB instances, both on AWS and OS X)

**### Logs/Trace**

npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'start',
npm verb cli   '--databaseURI',
npm verb cli   'mongodb://localhost:27017/parseServer',
npm verb cli   '--verbose' ]
npm info using npm@3.8.9
npm info using node@v6.2.0
npm verb run-script [ 'prestart', 'start', 'poststart' ]
npm info lifecycle parse-server-example@1.4.0~prestart: parse-server-example@1.4.0
npm info lifecycle parse-server-example@1.4.0~start: parse-server-example@1.4.0

> parse-server-example@1.4.0 start /home/ubuntu/parse-server-example-master
> node index.js "mongodb://localhost:27017/parseServer"

**Comment by Nightsd01** [comment]
It looks like if I use the parse-dashboard, and I create the classes involved, it appears to work just fine! I would appreciate any further help here though since I haven't been able to get the parse-dashboard to correctly serve up on EC2. Thanks!

- Brad

**Comment by drew-gross** [comment]
Can you include the configuration you use to start your server?

**Comment by BrainDDump** [comment]
I had exactly the same issue and the only way to find out was eliminating all differences between the standard application (parse-server-example) and my own (there is a bunch of cloud code there), basically commented all cloud code related stuff. So than I started uncommenting importing + 1 file each iteration until I found the error! In my case it was the custom Array.prototype function. 
```
Array.prototype.getUnique = function() {
   var u = {}, a = [];
   for(var i = 0, l = this.length; i < l; ++i) {
      if(u.hasOwnProperty(this[i])) {
         continue;
      }
      a.push(this[i]);
      u[this[i]] = 1;
   }
   return a;
}
```

**Comment by Nightsd01** [comment]
Excellent! That completely fixed my issue. With that one little adjustment my Parse server is now running just as well as it did on Parse itself, everything works. Thank you **so** much BrainDDump. I really appreciate it.

**Comment by acegreen** [comment]
@Nightsd01 @BrainDDump so any Array.prototype will affect the login? How are they related. I have the following in my cloud code but not related to login.

    Array.prototype.randomElement = function () {
        return this[Math.floor(Math.random() * this.length)]
    }
