### ISSUE TITLE
Disable access for users with unverified email

### ISSUE THREAD

**Issue by chderen** [ParsePlatform/parse-server#1958]
Hi, 
can i disable login for users with emailVerified=false on the server-side?

Thanks

**Comment by flovilmart** [comment]
No you can't but a Pull Request would be welcome.

**Comment by FridaySG** [comment]
@chderen What you could do as an alternative is enable anonymous users in your app and query that particular user as a cloud code call using the master key. If the email is verified then you can perform the login inside the completion block of the called cloud function. 

Alternatively, you could even just log them out immediately with an error message if the email is not verified but that may be a dirtier method. If you need sample code for the cloud code method in the first solution I'd be happy to help.

**Comment by chderen** [comment]
@FridaySG @flovilmart  Thanks.
because some reasons i made a custom branch for parse-server with custom changes :(
the way i resolve my problem was by adding two lines to the source code at Routers/UserRouter.js line 92:

`if (user.emailVerified == false)
          throw new Parse.Error(Parse.Error.OBJECT_NOT_FOUND, 'User email is not verified');`

my thoughts are that the email verification on login is required.

**Comment by natanrolnik** [comment]
@flovilmart this was implemented in the recently merged #2175 - I think you can close it.
Chezki @chderen, it will probably be available in the next release, 2.2.16.

**Comment by chderen** [comment]
Thanks

**Comment by natanrolnik** [comment]
BTW, I guess you can close it also :)
