### ISSUE TITLE
Question Parse ObjectId vs. Database generated Id's

### ISSUE THREAD

**Issue by neophob** [ParsePlatform/parse-server#1965]
When I create a new table entry via parse, the new entry has an objectId with a format like `Cd241s7mfO`. As I batch imported data directly via mongoimport I saw that those data entries have a different format: `574cbacc4ad424042428ef01`

Question:
- does the objectId matter? can I run into troubles if parse server mixes those id formats?

**Comment by drew-gross** [comment]
We aren't currently aware of any issues with different object ID formats.

**Comment by pfiaux** [comment]
It looks like the objectIds from mongo db (generated by mongoimport) will create "Object not found" issues, this was also mentioned in https://github.com/ParsePlatform/parse-server/issues/2358.

This would mean that there is an issue with non plain string object ids.

**Comment by flovilmart** [comment]
Object ids should be plain strings, feel free to open a PR if you want to support the ObjectId format
