### ISSUE TITLE
warning: error while sending push RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by fabuhelow** [ParsePlatform/parse-server#1966]
Hi All,

I'm trying to push a new notification to "140,000" users and I have got the following exception:

`index-3 (out): info: warning: error while sending push RangeError: Maximum call stack size exceeded
index-3 (out):     at GCM.send (/parse-server-gcm/node_modules/parse-server-push-adapter/lib/GCM.js:51:42)
index-3 (out):     at _loop (/parse-server-gcm/node_modules/parse-server-push-adapter/lib/ParsePushAdapter.js:114:38)
index-3 (out):     at ParsePushAdapter.send (/parse-server-gcm/node_modules/parse-server-push-adapter/lib/ParsePushAdapter.js:120:9)
index-3 (out):     at PushController.sendToAdapter (/parse-server-gcm/node_modules/parse-server/lib/Controllers/PushController.js:171:27)
index-3 (out):     at /parse-server-gcm/node_modules/parse-server/lib/Controllers/PushController.js:128:23
index-3 (out):     at run (/parse-server-gcm/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
index-3 (out):     at /parse-server-gcm/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
index-3 (out):     at flush (/parse-server-gcm/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
index-3 (out):     at _combinedTickCallback (internal/process/next_tick.js:67:7)
index-3 (out):     at process._tickDomainCallback (internal/process/next_tick.js:122:9)`

**Server specifications:**

- PM2 Threads: 4
- Server CPU's : 4
- HDD Space: 8 GB, Used 3 GB, Free 5 GB
- RAM: 16 GB, Free 14 GB
- 

Any help about this issue ?

Thanks,

**Comment by flovilmart** [comment]
opened on the proper repository
