### ISSUE TITLE
App doesn't appear in Dashboard / Account

### ISSUE THREAD

**Issue by drorpoleg** [ParsePlatform/parse-server#1975]
### Issue Description

The "Account Overview" only shows 1 of my 2 apps. This makes it impossible for me to change the plan (request limit) for my 2nd app. The 2nd app does appear anywhere else on the dashboard. 

### Steps to reproduce

Click on "Account" under the upper-right corner menu. 

#### Expected Results

Display slider with rate limit for two apps (Hook and Otherz)

#### Actual Outcome

Display slider with rate limit for only one app (hook)

**Comment by hramos** [comment]
This appears to be a Parse.com issue, as Parse Server has no per-app request limits. You can report bugs for Parse.com apps at https://parse.com/help, though I advise migrating your apps as soon as possible as our support teams for Parse.com apps are focusing on issues that may prevent people from moving their data out.
