### ISSUE TITLE
Queries are slow?

### ISSUE THREAD

**Issue by Twizzlerfw** [ParsePlatform/parse-server#1978]
I am using AWS and mLab. I upgraded mLab to the first option but it did not make a difference, so that means that the open source parse server is slow. When I was on parse.com it was a lot faster so I am not sure what changed? If any one could help that would be great!

**Comment by drew-gross** [comment]
The hardware you use on AWS, and the indexes you have on your database also make a difference. If you can provide a profiling trace or database query (or series or database queries) that you think could be faster, that would be welcome, but "everything is slow" isn't really something we can debug.

**Comment by Twizzlerfw** [comment]
@drew-gross I have ran it on my computer on localhost and it was the same speed. Is this a issue many people face or is this just me.
