### ISSUE TITLE
Parse.Object.saveAll() not working

### ISSUE THREAD

**Issue by camdagr8** [ParsePlatform/parse-server#1981]
I have defined a cloud code function where I am doing a saveAll(). 

```
Parse.Cloud.define('create', function (request, response) {
    // Get the table
    var table = request.params['table'];
    if (_.isEmpty(table)) {
        response.error('table is a required parameter');
        return;
    }

    // Get the data
    var data = request.params['data'];
    if (_.isEmpty(data)) {
        response.error('data is a required parameter');
        return;
    }

	data = (_.isArray(data)) ? data : [data];

    // Create multiple objects based on the data aray
	var objs = [];
	for (var i = 0; i < data.length; i++) {
		var item = data[i];
		var obj = new Parse.Object(table);
		for (var prop in item) {
			obj.set(prop, item[prop]);
		}
		objs.push(obj);
	}

	// Do save all
	Parse.Object.saveAll(objs, {
		success: function (result) {
			response.success(result);
		},
		error: function (err) {
			response.error(err.message);
		}
	});
};
```

### Steps to reproduce

1. Call the Parse.Cloud function with the following data objects

```
var input = {
	table: 'MyTAble',
	data: [
		{name: 'Test'},
		{name: 'This'},
		{name: 'Out'}
	]
};

Parse.Cloud.run('create', input, {
	success: function (result) {
		console.log('Hurray! I has succeeded!!'); 
	},
	error: function (err) {
		console.log(err); 
	}
});

```
#### Expected Results
All objects added to table. 

#### Actual Outcome
Responsed with error:
`{code: 1}`

### Environment Setup

- **Server**
  - parse-server version: ~2.1.3
  - Operating System: node.js 4.3.x
  - Localhost or remote server?: Remote - IBM Bluemix

- **Database**
  - MongoDB version: 3.2.6
  - Storage engine:  mmapv1
  - Hardware:       not sure
  - Localhost or remote server?: IBM Compose

### Logs/Trace

No errors are being reported in the logs.

**Comment by camdagr8** [comment]
Update: It works if I do 2 or three objects at a time. So I'm guessing there's a limit to how many items can be batch processed?

If that is the case, what are the limitations?

**Comment by drew-gross** [comment]
There may be limitations in the size of the request. Check the server logs and there will probably be more info.

**Comment by camdagr8** [comment]
It was a relatively small request (133kb total). It was however 100 total Parse.Objects being saved. Doesn't seem like that should be too much.

**Comment by camdagr8** [comment]
OK, I'm going to close this issues. It seems that the only problem is with the error reporting on the function. I found a small issue with the data I was submitting. However Parse was not reporting any errors what so ever.

**Comment by ryanemax** [comment]
https://github.com/ParsePlatform/Parse-SDK-JS/issues/328

I'm confusing with the same issue when saveAll() about 70 Object, need help.
