### ISSUE TITLE
Local server deployed via HTTPS

### ISSUE THREAD

**Issue by mistre83** [ParsePlatform/parse-server#1983]
I've just setup parse server (and dashboard) in my local machine and i can access it via localhost or via IP address inside my network.
Now, i would like to publish it and access via https (i already have a DNS with my), but server and MonboDB will be hosted in "my machine".

There is some guide that show how to install parse server locally and publish it via HTTPS ?

I've seen many guides that show how to push it on Heroku etc...

I will need a container where i will install my server ? If yes, can someone tell me what container i can setup "locally" in order to do this ?

Thanks!

**Comment by drew-gross** [comment]
Running Parse Server behind HTTPS is no different than running any other service behind HTTPS. You can follow any guide that describes how to do that.

**Comment by mistre833** [comment]
But... for example in Tomcat i need to generate a certificate and setup it on a specific port. With Parse, how i can do that... ?
