### ISSUE TITLE
OneSignal Notification not work with android device...

### ISSUE THREAD

**Issue by MattiaConfalonieri** [ParsePlatform/parse-server#1984]
One signal push adapter seems not work with android device... 

I have a cloud code function that send Push .... if i use the standard push adapter no problem, but if i use the one signal adapter i have problem with android device... (iOS work well), one signal console say the push is sended but device no receive... Anybody have the same problem?

Please if you can help me is my last problem before release for migration...

**Comment by MattiaConfalonieri** [comment]
The problem is that for Android OneSignal adapter need OneSignal sdk installed.

**Comment by flovilmart** [comment]
Glad you found out!
