### ISSUE TITLE
Code 111:  schema mismatch for _User.updatedAt

### ISSUE THREAD

**Issue by michalumni** [ParsePlatform/parse-server#1990]
Hello am getting the following error, when porting parse to my own server, please assist.

{"code":111,"error":"schema mismatch for _User.updatedAt; expected [object Object] but got String"}

based on the following python put request, which worked perviously on the old parse server
    
r = requests.put('http://parseserver-e2x32-env.us-east-1.elasticbeanstalk.com/parse/users/' + user1["objectId"], data=json.dumps(user1), headers=headers)

**Comment by drew-gross** [comment]
To help us debug this, can you include the exact request and response in Parse Server? (you can see this in the logs using `VERBOSE=1` environment variable)

**Comment by otymartin** [comment]
@drew-gross 
I just started getting the same problem. Don't know if theres any correlation but it occured after i implemented push notifications with OneSignal push adapter - Which works but gave me problem #2044 

Im using the latest Parse-Server 2.2.12 running on Google App Engine Flexible environment.

I was trying to login and got the error
```[Error]: schema mismatch for _Session.user; expected Pointer but got String (Code: 111, Version: 1.13.0)
schema mismatch for _Session.user; expected Pointer but got String```

**Comment by drew-gross** [comment]
We just pushed a hotfix in Parse Server 2.2.13 which fixes the issue by pinning the version of `deepcopy` to 0.6.1.

Closing as the original issue hasn't been updated in awhile.

**Comment by otymartin** [comment]
@drew-gross nice - I had just redeployed my server which got it working again so never got down to diagnosing it.
