### ISSUE TITLE
Permission Denied CLP Role

### ISSUE THREAD

**Issue by dcdspace** [ParsePlatform/parse-server#1991]
I have a role named "admin" in which users of that role should be able to delete objects. I have created a CLP for that role to allow only admins to delete, but I am getting "Permission Denied For This Action". 

I have verified that the user is a member of the admin role, and that I am passing the session token properly by adding a user pointer CLP with delete permissions, and that works.

See the screenshot below of the CLP editor.
![screen shot 2016-06-05 at 7 16 59 pm](https://cloud.githubusercontent.com/assets/6096771/15808936/7d90e420-2b52-11e6-880c-6c347f9abb93.png)

**Comment by flovilmart** [comment]
I'll have a look.

**Comment by flovilmart** [comment]
Just added a test in the PR I'm working on, does that encompasses what you see?

**Comment by dcdspace** [comment]
Thank you and yes it does, essentially creating an admin role with a new user, and then having an object that can only be deleted by the admin role. Only issue is that admins cannot delete the object.

**Comment by flovilmart** [comment]
Seems that it works with the PR.

**Comment by dcdspace** [comment]
Any ideas? It is strange why it works with the user pointer but not with the role, when the same user is clearly part of the role (see screenshots). 
![screen shot 2016-06-05 at 10 56 27 pm](https://cloud.githubusercontent.com/assets/6096771/15810875/dea8163e-2b70-11e6-8c31-02fe17dfb3ec.png)
![screen shot 2016-06-05 at 10 56 39 pm](https://cloud.githubusercontent.com/assets/6096771/15810877/dead2b92-2b70-11e6-9365-c2895053beda.png)
![screen shot 2016-06-05 at 10 57 07 pm](https://cloud.githubusercontent.com/assets/6096771/15810876/deac9db2-2b70-11e6-8565-6dc7e2753c14.png)

**Comment by drew-gross** [comment]
Fixed by #1989

**Comment by dcdspace** [comment]
@flovilmart I just updated my server to 2.2.13 and am still experiencing the same issue. My workaround for now is to add the user ids as pointers in CLPs, but obviously that is not a long term solution. Thanks.

**Comment by thomascoope** [comment]
@dcdspace I'm experiencing the same issue.  Did you resolve this?
