### ISSUE TITLE
How to Debug Indexes

### ISSUE THREAD

**Issue by jgaull** [ParsePlatform/parse-server#1996]
My team and I are super happy with our parse-server hosted on Heroku! We're starting to move forward with new features. This means new queries and new indexes. I have two questions:

1. How can I view the output of `cursor.explain()` to debug my queries?
2. How does parse-server determine the order keys are added to queries? I've read that this is important. Is it the same order that I called functions like `equalTo()`, `greaterThan()`, `containedIn()`, etc?

Thanks for your help.

**Comment by fisterryan** [comment]
I would also like to know the answers to the questions above.

Thanks!

**Comment by drew-gross** [comment]
For now you will have to go into the mongo logs directly to find query explanations, as we don't expose these in Parse Server. The key order shouldn't matter.

**Comment by jgaull** [comment]
Thanks @drew-gross! I'll take a look.
