### ISSUE TITLE
Error on app startup

### ISSUE THREAD

**Issue by Dima564** [ParsePlatform/parse-server#1999]
I'm getting following error when I run "heroku logs" 

` app[web.1]: > node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --progress --watch

 app[web.1]: sh: 1: webpack: not found

 app[web.1]: > parse-dashboard@1.0.3 dashboard /app

 app[web.1]: 

 app[web.1]: npm ERR! errno ENOENT

 app[web.1]: npm ERR! syscall spawn

 app[web.1]: npm ERR! parse-dashboard@1.0.3 dashboard: `node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --progress --watch`

 app[web.1]: npm ERR! If you do, this is most likely a problem with the parse-dashboard package,

 app[web.1]: npm ERR! not with npm itself.

 app[web.1]: npm ERR! Tell the author that this fails on your system:

 app[web.1]: npm ERR!     node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --progress --watch

 app[web.1]: npm ERR! You can get information on how to open an issue for this project with:

 app[web.1]: npm ERR! spawn ENOENT

 app[web.1]: npm ERR! Failed at the parse-dashboard@1.0.3 dashboard script 'node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --progress --watch'.

 app[web.1]: npm ERR! 

 app[web.1]: npm ERR! Make sure you have the latest version of node.js and npm installed.

 app[web.1]: npm ERR! npm  v3.9.6

 app[web.1]: npm ERR! file sh

 app[web.1]: npm ERR! code ELIFECYCLE

 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:

 app[web.1]: npm ERR!     npm owner ls parse-dashboard

 app[web.1]: npm ERR!     npm bugs parse-dashboard

 app[web.1]: 

 app[web.1]: npm ERR! There is likely additional logging output above.

 app[web.1]: npm ERR! Please include the following file with any support request:

 app[web.1]: npm ERR!     /app/npm-debug.log

 heroku[web.1]: Process exited with status 1

 heroku[web.1]: State changed from starting to crashed`

**Comment by hramos** [comment]
The logs indicate you're running Parse Dashboard, not Parse Server. I suggest opening an issue over at [parse-dashboard](https://github.com/parseplatform/parse-dashboard) instead.
