### ISSUE TITLE
[General questions] Somebody is actually live with Parse Server?

### ISSUE THREAD

**Issue by MattiaConfalonieri** [ParsePlatform/parse-server#2004]
Hi, i have a general question for all of you.

Somebody is live and in production with Parse Server?

I am ready to release my app and start the users migration, i have just a couple of issue 
(like: old users don't see new users file)... everything appear stable and good.

But i am stopped by the fact that the last call for release is 28 july (in two months), i am looking for opinion... Thanks for share

**Comment by sdf611097** [comment]
https://github.com/ParsePlatform/parse-server/issues/1106

**Comment by drew-gross** [comment]
Thanks @sdf611097! Closing this.
