### ISSUE TITLE
_id to objectId

### ISSUE THREAD

**Issue by adriano-di-giovanni** [ParsePlatform/parse-server#2006]
Do you confirm we have to rename `objectId` to `_id` when we use the export function from parse dashboard to import data into our database? Do we need to do something else?

**Comment by drew-gross** [comment]
Yes, you need to do that, and also transform createdAt, updatedAt, ACL, and transform pointers by prefixing the key with `_p_` and changing the value to the target classname + "$" + target objectId. I recommend you import to a test DB first and make sure the imported data behaves as expected.

**Comment by davimacedo** [comment]
I suggest you import through cloud code instead of inserting directly in the mongo collection. You can see an example here:
https://gist.github.com/davimacedo/c7738203a2a616b48a22fdc7c00b37d2
