### ISSUE TITLE
New collections created through Robomongo do not show up on Parse Dashboard.

### ISSUE THREAD

**Issue by p-sun** [ParsePlatform/parse-server#2008]
I have an iOS App using Parse Server on Heroku. Reading or writing from my collections works well.

However, new collections created via Robomongo cannot be viewed via Parse Dashboard 1.0.13 because creating a collection outside the Parse Dashboard doesn't create the needed metadata, i.e. the _SCHEMA collection.

Steps to Reproduce:
1. Create new collection via Robomongo
2. New collection is not visible in Parse Dashboard

Thank you!

**Comment by drew-gross** [comment]
You can fix this by creating the class through the dashboard first, or by inserting the metadata manually.
