### ISSUE TITLE
Zombied parse.com migration, manual migration option

### ISSUE THREAD

**Issue by nncary** [ParsePlatform/parse-server#201]
My parse.com migration job is permanently stuck, where the migration page says its cancelled, but when I go to initiate a new job it says the old one is still running. Is there a way we can run this locally for those of us who just want to make sure we properly capture the schema.

**Comment by pungme** [comment]
@nncary  We have the same problem :-(

**Comment by skinp** [comment]
Hi @nncary and @pungme can you please visit https://parse.com/help and find the bug icon / "Something wrong?" section to start the bug reporting flow. As were tuning the migration workflow, it's much easier for us to track those issues individually. We'll need your app id and if you can find it, your migration job id (only new versions of the UI have this).

Closing as we prefer to track migration issues through the developer bug tool.
