### ISSUE TITLE
Secure _GLOBALCONFIG table

### ISSUE THREAD

**Issue by neophob** [ParsePlatform/parse-server#2011]
### Issue Description

The _GLOBALCONFIG table is used to save `Config` values when using Parse Dashboard. As I use the values stored in this table only in Cloud Code I would prevent access from users (like remove all CLP permissions). Currently its world readable:

```
  let query = new Parse.Query('_GlobalConfig');
  query.limit(4);
  return query.find({})
    .then(msg => {
      return msg;
    })
```

Result:
```
_GLOBALCONFIG table reads:
  [ ParseObject { _objCount: 11, className: '_GlobalConfig', id: '1' } ]

```

This issue also might affect the `_PushStatus` and `__JOBS__` tables.

### Environment Setup

- **Server**
  - parse-server version: 2.2.11

**Comment by drew-gross** [comment]
This is the intended behaviour, as Parse Config is designed to be used by the clients. If you want to submit a PR that allows you to have private config, we would gladly accept it!

**Comment by neophob** [comment]
Ok I see - what about the _PushStatus and __JOBS__ tables?

**Comment by drew-gross** [comment]
_PushStatus already requires the master key. Jobs is not in the _SCHEMA so it should be fine.
