### ISSUE TITLE
got "Internal server Error" when trying to query for _User 

### ISSUE THREAD

**Issue by pungme** [ParsePlatform/parse-server#202]
We've set up the parse-server with Heroku & MongoLab and migrate the user successfully. But when we try to query for User, we got the "Internal server error." message. 
    
```
    var User = Parse.Object.extend("_User");
    var query = new Parse.Query(User);
    query.find( ... ) 
```

Anyone could give us a hint ?

**Comment by natanrolnik** [comment]
I'm not sure it would make a big difference, but have you tried defining the `User` var this way:

`var User = Parse.User;`

**Comment by pungme** [comment]
Hi @natanrolnik thanks a lot for a reply. But unfortunately still got the same error. :-/

**Comment by gfosco** [comment]
Please run the server with the environment variable `VERBOSE=1` and capture any details you can.

**Comment by gfosco** [comment]
If you still have issues with the latest version, please open a new issue.  Thanks.
