### ISSUE TITLE
Parse.User.current not working? Do i use something else?

### ISSUE THREAD

**Issue by farhansyed9** [ParsePlatform/parse-server#2020]
here is what im doing, the app.post works for login, but when it goes to app.get, Parse.User.current is null

app.post('/login', function(req, res) {
  Parse.User.logIn(req.body.username, req.body.password, {
  success: function(user) {
    // Do stuff after successful login.
    console.log('user: ' + user);
    res.redirect('/home');
  },
  error: function(user, error) {
    // The login failed. Check error to see why.
    console.log('error login');
    res.redirect('/login');
  }
});

});

app.get('/home',function(req, res){

if (Parse.User.current()) {
      // No need to fetch the current user for querying Note objects.
  var currentUser = Parse.User.current();
  var sessionToken = currentUser.get('sessionToken');

  console.log(sessionToken);
    }
});

**Comment by drew-gross** [comment]
You'll need to switch to using an explicit session token in your queries if you make to make queries in cloud code as a specific user. See the migration guide: https://github.com/ParsePlatform/Parse-Server/wiki/Compatibility-with-Hosted-Parse#Cloud-Code

**Comment by farhansyed9** [comment]
Not trying to do cloud code, just logging in on a website

**Comment by drew-gross** [comment]
This repo is for issues in Parse Server, not for help building your app. That said, you can't use current user in a node environment. Imagine what would happen when one person hits the `login` endpoint, then then a second one hit the `login` endpoint, then the first one hit the `home` endpoint. Current user would still be set to the second user. This is why current user doesn't exist in node.

What you should do instead is store a session token on the client, and use that session token in your requests.

**Comment by farhansyed9** [comment]
is there some guide on this? i do have parse-express-cookie-sesion
