### ISSUE TITLE
How to change format of reset password link which users gets in their email ?

### ISSUE THREAD

**Issue by syampsijk** [ParsePlatform/parse-server#2036]
I am using parse server in digital ocean droplet.While i implement reset password.The user gets a link with my ip address of droplet ie 37.x.x.154  ,app key session token and gmail.Is there a way i could hide these .or atleast give a domain name instead of ip for eg link is like this

http://37.x.x.154:1337/parse/apps/appkey/request_password_reset?token=TntZjXMlIvfviWpw0re8y5Jmi&username=my%40gmail.com

could i change it atleast

http://myDomainName.com/parse/apps/appkey/request_password_reset?token=TntZjXMlIvfviWpw0re8y5Jmi&username=my%40gmail.com

I bought domain name,but how can i give port . It feels insecure and feels like vulnerable for attack on my server.

**Comment by bohemima** [comment]
You should simply set the severUrl to use your domain name and not the IP-address. You should also consider having your Parse-server terminated by nginx or something like it (and do use https for your nginx)

**Comment by syampsijk** [comment]
i have done it and works,but now in the email it gives me
http://domainname :portnumber/parse/app/appkey/sessiontoken/email 

is there any way to hide 
port number,
app key
path : parse/app 

in simple way . .

**Comment by drew-gross** [comment]
Parse Server only accepts links to the `/mount/app/key/...` endpoint. It's possible to get rid of it, but not easy. You would need to write a custom verification email generator, that uses the desired link, and then use a redirection somewhere (maybe nginx, or if you are mounting Parse Server on your own express app you can do the redirection there)

This isn't a common use case, so it's not very well documented. If you get this working successfully, please submit a documentation improvement so others can learn from what you've discovered!

Also, if you only need to hide the port number (this is what I would recommend), you can do that by using running your Parse Server on port 80, or redirecting in from port 80 to the port you are running on, and using `publicServerURL` setting in Parse Server, set to `https://YOUR_DOMAIN.com/YOUR_MOUNT``.
