### ISSUE TITLE
Error when trying to log in since updting to 2.2.12 

### ISSUE THREAD

**Issue by Kinzi** [ParsePlatform/parse-server#2037]
I just upgraded to 2.2.12 locally. Now, when I try to log in using js sdk 1.8.5 and `Parse.User.logIn(user, password, response)` I get this error:

```
code: 111, message: "schema mismatch for _Session.user; expected Pointer but got String"
```

I only updated parse-server and my setup worked perfectly with 2.2.9. 

Any ideas?

-EDIT-
With 2.2.10 I get this: `code: 111, message: "schema mismatch for _Session.user; expected [object Object] but got String"`

**Comment by kennygunie** [comment]
Me too, parse-server 2.2.12 with SDK iOS:
[Error]: schema mismatch for _Session.user; expected Pointer but got String (Code: 111, Version: 1.13.0)

**Comment by wilsonths** [comment]
Looks like the dependency deepcopy 0.6.2 causes the issue. A workaround is to fallback to deepcopy 0.61.

**Comment by kennygunie** [comment]
@wilsonths thank you ! => workarround npm install deepcopy@0.6.1

**Comment by Kinzi** [comment]
didn't work for me - also deepcopy already is 0.6.1 in parse's package.json

**Comment by andj207** [comment]
@wilsonths thank you! you've save my day

**Comment by SeenGhost** [comment]
Experiencing the same problem with iOS sdk, is there a work around for it??

**Comment by pan83** [comment]
Thank you, it works. To prevent similar problems in the future, may I ask how can we pin all the currently used dependency packages to ensure that we can rollback to a well tested deployment? We are using the parse-server-example project for our deployment on heroku.

**Comment by drew-gross** [comment]
https://docs.npmjs.com/cli/shrinkwrap
