### ISSUE TITLE
Proposal: pin all package versions.

### ISSUE THREAD

**Issue by drew-gross** [ParsePlatform/parse-server#2040]
We have now had 2 issues where a "patch" upgrade in a dependency broke Parse Server. Once when `mongodb` package updated from `2.1.18` to `2.1.19` and once when `deepcopy` package updated from `0.6.1` to `0.6.2`. We should consider pinning all dependencies to prevent issues like this in the future.

The downside is that Parse Server will be less able to share dependencies with other packages, causing an increase in code size.

Thoughts?

I'm going to enable https://greenkeeper.io/ either way, which will hopefully help with the issue.

**Comment by jadsonlourenco** [comment]
I fully agree with you, since the problem with mongodb package I followed your valuable advice: **npm shrinkwrap**, this should be standard, thus avoiding new problems of this kind - which takes our sleep.

**Comment by drew-gross** [comment]
Cool. Consensus in slack is to pin as well. I will make a PR.
