### ISSUE TITLE
Error iOS sdk version 1.13.0: schema mismatch for _Session.user; expected Pointer but got String

### ISSUE THREAD

**Issue by SeenGhost** [ParsePlatform/parse-server#2042]
Issue Description:

I'm having problems with signing in and sign up iOS sdk.

I setup parse server on heroku, tested it with: 

let testObject = PFObject(className: "TestObject")
testObject["foo"] = "bar"
testObject.saveInBackgroundWithBlock { (success: Bool, error: NSError?) -> Void in
  print("Object has been saved.")
}

and the object saved successfully to mLab.

Then when I tried to sign a user up or log a user in. I got an error: 

schema mismatch for _Session.user; expected Pointer but got String

There was an issue already posted but it was closed and was for the js SDK. how would one solve this for iOS sdk?

**Comment by drew-gross** [comment]
This was due to a breaking change in `deepcopy`. Upgrade to Parse Server version 2.2.13, or pin your `deepcopy` version to `0.6.1`.

**Comment by SeenGhost** [comment]
@drew-gross I usually download the ios sdk from this link https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/releases/tag/1.13.0, and it doesn't have iOS idk 2.2.13? may you please be so kind to provide the link to iOS sdk 2.2.13?

**Comment by drew-gross** [comment]
No your Parse Server, not your iOS SDK.
