### ISSUE TITLE
Getting multiple Push Notifications

### ISSUE THREAD

**Issue by LMUEC** [ParsePlatform/parse-server#2044]
### Issue Description

Testing my app using parse-server I get the same push notification 5 times. I already tried logging out and logging in to Facebook, deleting app data and uninstalling the app. I have never experienced this using parse.com.
Googling around a bit, it seems that the problem might be related to old GCM tokens.

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1. Use parse-server push (native)
2. Reinstall and restart app multiple times
3. Send push notification to device

#### Expected Results

Notifcation should be received once

#### Actual Outcome

Notification is received multiple times

### Environment Setup

- **Server**
  - parse-server version: 2.2.11
  - Heroku sandbox

- **Database**
  - mLab sandbox

-------

in database:
 "numSent": 1

-------

Might be related to:
https://github.com/ParsePlatform/parse-server/issues/2009

But I'm not switching user accounts.

Any ideas?

**Comment by otymartin** [comment]
Just started the same problem in the last 3 hours. Things were working fine

**Comment by MattiaConfalonieri** [comment]
I have the same problem with Parse server version 2.2.13 , how ca i fix that?

**Comment by kwstasna** [comment]
I get an error with GCM push notifications : 401
Although i get notifications in iOS, i dont get them in Android.
2 weeks ago it was working great!

**Comment by pinguineras** [comment]
im using the 2.2.13 version and experienced errors like that.

**Comment by hramos** [comment]
It would be useful to get a clear list of repro steps from everyone who has run into this, in order to make sure these are not different issues you are each running into.

**Comment by kwstasna** [comment]
I solved the issue by doing those steps.

1) made another GCM key
2) replaced it with the previous one inside index.js
3) restarted parse-server
4) waited 10minutes and then the push notifications were sent to android users (the ios users had no problem at all that's why it had something to do with GCM key i thought)

**Comment by flovilmart** [comment]
Let's close that one for now as @kwstasna provided a workaround. Not sure what's going on with GCM or what could cause push to be sent duplicated. If they are properly sent in iOS, that may be a problem with either the GCM configuration (as exposed in the workaround) or in the push adapter itself. If it happens to be the latter, please reopen the issue on https://github.com/parse-server-modules/parse-server-push-adapter
