### ISSUE TITLE
Sync New MongoDB uri with parse.com Dashboard

### ISSUE THREAD

**Issue by sanergulec** [ParsePlatform/parse-server#2050]
Hello,

I switched from sandbox in mongolab to dedicated cluster. So the database uri has been changed. I changed the uri in the parse server side and it is working. However, the parse.com dashboard is still showing the previous dashboard of the previous database uri. Is it possible to sync it with the new databse uri? Or was it a one time option?

**Comment by bohemima** [comment]
When finalised that's it, no going back.

**Comment by skinp** [comment]
My guess is this is probably some caching issue. Maybe @drew-gross knows more

**Comment by drew-gross** [comment]
No, dashboard.parse.com doesn't do any caching, it reads from api server every time.

You can change your mongo uri from the dashboard, which will cause all reads and writes to immediately start using that new URI. I recommend trying this with a dev app before doing it with your prod app.
