### ISSUE TITLE
Parse.Object.destroyAll doesn't work

### ISSUE THREAD

**Issue by markuswinkler** [ParsePlatform/parse-server#2055]
I ran into an interesting problem, it seems Parse.Object.destroyAll doesn't work.

There is also a beforeDelete Handler for that particular class which gets executed,
verified via console.log.
The destroy operation itself doesn't get executed (objects are still in the DB) and also the promise never returns a value and stalls therefore the cloud call.

Maybe my syntax is wrong?
Running parse server 2.2.13

See sample code below:

doesn't work:
```
        query.find({useMasterKey: true}).then(function (results) {
            if (results.length > 0) {
                return Parse.Object.destroyAll(results, {useMasterKey: true});
            } else {
                return Parse.Promise.resolve("");
            }
        }).then(function (results) { ....
```

works:
```
        query.find({useMasterKey: true}).then(function (results) {
            if (results.length > 0) {
                var aPromise = [];
                _.forEach(results,function(result) {
                    aPromise.push(result.destroy({useMasterKey: true}));
                });
                return aPromise;
            } else {
                return Parse.Promise.resolve("");
            }
        }).then(function (results) { ....
```

**Comment by drew-gross** [comment]
To help us debug this, can you include the exact request and response in Parse Server? (you can see this in the logs using `VERBOSE=1` environment variable)

**Comment by markuswinkler** [comment]
sure.

```
verbose: POST /parse/batch { 'user-agent': 'node-XMLHttpRequest, Parse/js1.8.5 (NodeJS 4.4.3)',
  accept: '*/*',
  'content-type': 'text/plain',
  host: '10.0.1.30.xip.io:1337',
  'content-length': '370',
  connection: 'close' } {
  "requests": [
    {
      "method": "DELETE",
      "path": "/parse/classes/Conversation/6VHIo8u4Io",
      "body": {}
    },
    {
      "method": "DELETE",
      "path": "/parse/classes/Conversation/SZpfTdVxfZ",
      "body": {}
    }
  ]
}
```

The interesting part is that if I remove the `beforeDelete` cloud code for `Conversation` destroyAll works again. That function calls Firebase via a promise, taking about 40-100ms.
Could it be that destroyAll somehow times out in contrast to separate destroy calls?

**Comment by markuswinkler** [comment]
thanks @drew-gross,  never mind, was totally my fault.

I wrote
`Parse.Cloud.beforeDelete("Conversation", function(request) {`
instead of the correct
`Parse.Cloud.beforeDelete("Conversation",` function(request, response) {`

ah well.
