### ISSUE TITLE
facebook login not working with parse-server hosted on AWS

### ISSUE THREAD

**Issue by nikolodien** [ParsePlatform/parse-server#2056]
I have the parse-server-example setup on AWS. I have been trying to add facebook login for a long time now. It doesn't seem to be working. Trying to test the `Parse.FacebookUtils` api. When I call the `logIn` function of the api, it does not return anything. Just waits for the server to return.

I have added the following property while instantiating the ParseServer,

`facebookAppIds: ["<myAppId>"]`

### Environment Setup

**Client**
 - react-native android application
 - parse version: 1.8.5  

**Server**
  - parse-server version: 2.2.12
  - remote server: AWS Elastic BeanStalk  

**Database**
  - MongoDB version: 3.0.x
  - remote server mLab

**Comment by sprabs** [comment]
Are you having any other issues with Elastic Beanstalk? We are noticing high latency and poor performance when doing reads/writes to classes on our mLab through the REST API.

**Comment by nikolodien** [comment]
No, I haven't seen other issues yet. I am able to create objects for other classes easily. I am not able to figure out what is wrong with the facebook authentication.

**Comment by nikolodien** [comment]
It seems to be working now. Couldn't determine exactly what was causing this though.
