### ISSUE TITLE
Permission denied after upgrading to parse-server@2.2.13

### ISSUE THREAD

**Issue by benishak** [ParsePlatform/parse-server#2058]
# Env
- Parse-Server 2.2.13
- MongoDB 3.0.11
- AWS (CentOS + NGINX)

# Problem
When trying to delete objects it doesn't work and get `Permission denied`. After downgrading to 2.2.9, it works fine

**Comment by FarmerKing** [comment]
looks similar to #2034

**Comment by flovilmart** [comment]
Can you try installing 2.2.14, the fix should have been integrated with that change.

Please reopen if the fix is not effective for your use case.

**Comment by benishak** [comment]
2.2.15 still not working

**Comment by flovilmart** [comment]
WHat are the CLP on the class?

**Comment by benishak** [comment]
Public Read Write

**Comment by flovilmart** [comment]
Can you provide the content of the schema for that class?

**Comment by flovilmart** [comment]
@benishak?

**Comment by benishak** [comment]
After enabling "add fields" it worked although it didnt create any new column

**Comment by flovilmart** [comment]
hmmm ok... that's odd... Should I close it now? If you want us to keep it open, can you please provide more context (like full schema, CLP, and objects) in order to reproduce and help drill down the error?

**Comment by benishak** [comment]
It is the standard User class of parse. CLP is public read write delete update

**Comment by flovilmart** [comment]
> If you want us to keep it open, can you please provide more context (like full schema, CLP, and objects) in order to reproduce and help drill down the error?

Can you provide the actual data? Closing till then.
