### ISSUE TITLE
Password reset works, but email verification does not work

### ISSUE THREAD

**Issue by Zookey** [ParsePlatform/parse-server#2069]
Hi,

I successfully migrate Parse server to Herouku and for email verification and password reset I am using Mailgun.

I managed to get email for password verification with link to reset password and it is working fine, but I do not get email for email verification.

What I could do about this? 
Here is code: http://pastebin.com/yNQ0z7Mn

**Comment by zirinisp** [comment]
I am having the same problem. Did you manage to find a solution on that. I have been trying to find a solution for almost a month without luck.
