### ISSUE TITLE
error: unauthorized

### ISSUE THREAD

**Issue by kartboy16** [ParsePlatform/parse-server#207]
Attempting to create generic TestObject. 
403 Error (Forbidden) 

Anybody else?

**Comment by pccrazy** [comment]
please attach screenshots of the code so we can help

**Comment by krhebbar** [comment]
@kartboy16 in node_modules/parse/lib/node/CoreManager.js make sure SERVER_URL pointing to your server.

**Comment by kartboy16** [comment]
FYI, I'm following the tutorial for deploying to Heroku on https://medium.com/@timothy_whiting/setting-up-your-own-parse-server-568ee921333a#.q6c8g9vd3 

Modified the index.js file: 
![_users_alexhung_sites_parse-server-example_index_js__retirementapp__ _brackets](https://cloud.githubusercontent.com/assets/4443907/12794438/e500ca16-ca69-11e5-9bc0-78c84baf01d8.png)

From my MeteorJS app: 
![client_templates_report_report_js__retirementapp__ _brackets](https://cloud.githubusercontent.com/assets/4443907/12794416/c4d7422e-ca69-11e5-9db5-06fbde494bc5.png)

403 Error (Forbidden)...

**Comment by verygreenboi** [comment]
I think you have to add "/" to the server url.

**Comment by kartboy16** [comment]
Grrrrrrr.  Was using the clientKey when I should have setup the javascriptKey.  New lesson, don't work on servers at 3AM without caffeine...
