### ISSUE TITLE
[Error]: temporary error. Code: 159 multiple times

### ISSUE THREAD

**Issue by CremaGames** [ParsePlatform/parse-server#2071]
Since yesterday I'm getting this error thousand of times. 

It just happen sometimes, but when it appears, is for a while.

I don't know what I should do with this, I'm not overpassing the petitions per second, and I am paying 150 req/second. I have read that error means Parse decides to don't accept that request, but since the service it's not free I don't think that is the case...

It's anything happening in the parse server side?

Regards.

**Comment by drew-gross** [comment]
For issues with the parse.com service, please use [parse.com/help](http://parse.com/help).
