### ISSUE TITLE
Guaranteed delivery and LiveQuery

### ISSUE THREAD

**Issue by wookiem** [ParsePlatform/parse-server#2077]
In considering LiveQuery for my React Native app, it would be highly useful if the LiveQuery Server maintained an undelivered message Queue.  That way, when my app resumes from suspended state, it can re-connect with LiveQuery Server and receive pending query results.  

Has this "guaranteed delivery" use-case been discussed at all?

**Comment by drew-gross** [comment]
My recommendation is to issue a regular query for objects updated after the time the app got suspended, and before it resumed. Guaranteed delivery would certainly be useful, but is a difficult problem to solve, and isn't on our roadmap.

**Comment by wookiem** [comment]
Thanks for your suggestion @drew-gross.  

I can see how this approach would identify added / modified Parse objects during the time interval.  Is there a way to construct a query to identify Parse objects that were deleted during the interval?

**Comment by drew-gross** [comment]
No, since the data is gone from the DB. One thing you could do in that case is to "soft-delete" object, by setting a "deleted=true" flag on them, then processing updates that set "deleted=true" as if they were deletes.

**Comment by wookiem** [comment]
Thanks @drew-gross.  That's a good suggestion.
