### ISSUE TITLE
error while trying to save ParseRole

### ISSUE THREAD

**Issue by slimshdy** [ParsePlatform/parse-server#208]
error thrown by parse-server while trying to delete parseRelation between Role and _User

this is the code I have executed in php: 
```
$role = get_role_by_name($data->roleName)[0];
 $role->getUsers()->remove($user);

try {
   $role->save(true);
}
catch (ParseException $ex) {
   echo "Error: " . $ex->getCode() . " " . $ex->getMessage()."<br/>";
}
```

and this is the error thrown by parse-server

![31897cb6-ca6a-11e5-9e8f-019bd341b0db](https://cloud.githubusercontent.com/assets/17044696/12843661/b97de47a-cbf2-11e5-84ce-5a777539c973.png)

Thanks in advance!

**Comment by gfosco** [comment]
can you run the server with VERBOSE=1 and capture the request?

**Comment by slimshdy** [comment]
![error verbose](https://cloud.githubusercontent.com/assets/17044696/12843526/ef10eeb2-cbf1-11e5-97e5-bf8d7ffe8260.png)

**Comment by gfosco** [comment]
Please re-open this if it still occurs in v2.1.2.
