### ISSUE TITLE
How to Migrate to AWS totally?

### ISSUE THREAD

**Issue by kenglou** [ParsePlatform/parse-server#21]
Hi,

I do have a question on migrating my old applications to own hosted AWS.
I'm really pretty new and inexperience in doing hosting server. I wish to know that what I should do if I want to host everything in AWS, including the MongoDB. Is that means I need to create a EC2 in AWS and install MongoDB into it, and port everything in parse server into the BeanStalk? I want to know the path of doing that so that I won't take the wrong road and we are in a hurry of development time now.

Besides that, i also quite concern on the cost of the AWS, if free tier in Parse is equivalent to how much in AWS(i believe this is hard to answer so just ignore it if you don't want to answer).

Thank you

**Comment by zhilut** [comment]
Yeah, it would be great that Parse could provide a script that could automatically. After all, there will be tons of developers who will migrate to AWS.

**Comment by duergner** [comment]
If you don't have experience in maintaining infrastructure you shouldn't do it - use a hosted solution.

Running it on IaaS means you need to take care of keeping the OS as well as all installed software up2date with regard to security fixes. Furthermore configuring and tuning both MongoDB as well as NodeJS installations is not trivial for production grade applications.

**Comment by Telemakhos** [comment]
You are mixing concepts. You don't really need to manage servers (EC2). With ElasticBeanstalk you can provide a multi-container dockerized app and upload it. It will scale and handle the load automatically for you.

http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker_ecs.html

**Comment by gfosco** [comment]
We'll be working with cloud providers and doing our best to produce and contribute to guides and projects to make running your own parse-server easy.  Stay tuned, as we always say.

**Comment by yz** [comment]
Please provide a detail guide to install/host parse server with mongodb on an existing AWS instance.

**Comment by kukkadapukarhtik** [comment]
when i try to update the object from terminal using commands for aws ,following error occurs
karthiks-MacBook-Air:~ karthikk$ curl -X POST \
> -H "X-Parse-Application-Id: {a9lfpqCsy4r46d2nzDMa0nefvU9kmbqr5fQQKFnB}" \
> H "Content-Type: application/json" \
> -H "Content-Type: application/json" \
> -d '{"name":"sainath"}' \ http://parseserver-f338g-env.us-east-1.elasticbeanstalk.com /parse/classes/Categories
curl: (6) Could not resolve host: H
curl: (6) Could not resolve host: Content-Type
curl: (1) Protocol " http" not supported or disabled in libcurl
curl: (3) <url> malformed

**Comment by kukkadapukarhtik** [comment]
Please provide a detail guide to install/host parse server on AWS instance.
