### ISSUE TITLE
Parse FIND Query with NEARBY constraint for a table of records close to 200K fails with I/O.

### ISSUE THREAD

**Issue by rahulsindhu** [ParsePlatform/parse-server#2100]
We are facing production issues with PARSE shared hosting for out application. Use cases:
1. Trying to FIND query for NEARBY records using ParseGeoLocation and few other CONTAIN-IN constraints.

2. Set the query limit to 20 or keep default record limit.

3. Issue is if there are valid records for the query but the count of those valid records are less than 20 or less than the limit field then we always get response as I/O error.

4. We have tested this use case by playing with LIMIT query fields. We somehow we could give Limit as correct record count then only we get the result. Played with RANGE as well between 10 KM to 800 KM. It always returns valid results in this case.

5. I/O returns after close to 30 seconds of we firing the query and this is causing a log delay for our customers to show results.
6. It's not possible to keep a Count for each location and for each constraint.

Need help on this. Please let me know if anything is not clear. Would like to know if it's a known issue or we doing something wrong.

**Comment by flovilmart** [comment]
@TylerBrock any idea on that? indexation problem?

**Comment by rahulsindhu** [comment]
Not sure. If it's indexation issue then why would it always works if we keep the LIMIT value equal to exact records count available for certain criteria.  (Happening only for NEARYBY constraint)

Looks for help from parse team. I wanted to create fresh indexes but looks like it's not possible for Parse Server as it's maintained internally.

This is giving us a headache as we are not able to show all records because we never get to see the last page of the records.

**Comment by rahulsindhu** [comment]
@flovilmart can you please help us get an update on this? I mean is this a known issue? Or what can we do to fix it.

**Comment by flovilmart** [comment]
You mentioned creating indexes, you can do it directly with MongoDB. That may help.

**Comment by rahulsindhu** [comment]
Can we do that on Shared Parse Server using Parse console? We have not migrated the app on Self Hosted Environment.

**Comment by flovilmart** [comment]
did you migrate your database?

**Comment by rahulsindhu** [comment]
Nope. Not yet. We are using parse.com for now. And facing issue on the same.

Our table has more than 200K records.

**Comment by flovilmart** [comment]
So you missed the deadline for migrating your database, that could explain why you're facing issues.

I recommend you migrate your app ASAP, and reopen the issue when you'll be migrated to parse-server.

We don't provide support here for parse.com apps, please use http://parse.com/help.
