### ISSUE TITLE
beforeSave on all objects, possible?

### ISSUE THREAD

**Issue by mistre83** [ParsePlatform/parse-server#2102]
Hi to all,
in my application i will have many collections, and one of this is a "recap" with the latest insert in the online collection.

Such as a Blog, a collection with Posts hold all post and a single blog instance have saved for example the latest 10 comments. 
When a new post come in, this will be saved in Posts and in "recap" with a FIFO strategy. In this way, i can get "immediately" the last 10 comments without make additional query.

So, to do this i will need a beforeSave function that "check" every collection (because my collection are many, and i dont want to write "the same code" for every one).

I can write a job to do this, but is asynchronous and will need to run very often..

**Comment by flovilmart** [comment]
It actually depends on your application imperatives. You could run them in afterSave, so you're not blocking saving the element itself. The job is a good strategy too.

**Comment by mistre83** [comment]
I've changed this implementing a Cloud function and it works great.
The only problem is that in local all works fine, but when i push on heroku i get a 141 error when i invoke it.

The error come when i make a query in my cloud.

```
Parse.Cloud.define("newMeasure", function(req, res) {
    var type = req.params.type,
        name = req.params.name,
        measure = req.params.measure,
        registered = req.params.registered;

    var MeasureObject = Parse.Object.extend(type);
    var Systems = Parse.Object.extend("systems");

    var measureObject = new MeasureObject();

    var systemQuery = new Parse.Query(Systems);
    systemQuery.equalTo("customer", "mycustomer");

    res.success('SAVED'); // RIGHT HERE, ALL WORKS

    // IF I COMMENT THE PREVIOUS LIKE AND INVOKE THE QUERY, I GET 141 ERROR....
    systemQuery.first()
        .then((result) => {
            res.success('SAVED');


    }).catch(e => res.error(e));
});
```

**Comment by mistre83** [comment]
I've changed this implementing a Cloud function and it works great.
The only problem is that in local all works fine, but when i push on heroku i get a 141 error when i invoke it.

I close this so.
