### ISSUE TITLE
"You cannot increment a non-number." when increment()

### ISSUE THREAD

**Issue by iForests** [ParsePlatform/parse-server#2115]
Hi, it might look like a Parse-Android-SDK issue, but I'm sure that this crash didn't happen when using `api.parse.com`, so I think it could be a parse-server issue. I can reproduce this issue by the following code (`myNum` is a Number field in User object):

```
ParseUser parseUser = ParseUser.getCurrentUser();

parseUser.increment("myNum", 1);
parseUser.saveInBackground();

parseUser.increment("myNum", -1);
parseUser.saveInBackground();

parseUser.increment("myNum", 1);
// ^^^^^ Crash here with java.lang.IllegalArgumentException: You cannot increment a non-number.
```

I'm using Parse-SDK-Android 1.13.1 & Parse-Server 2.2.12. 

I think the problem here is, when `myNum` becomes 0 after several increment() operations, the next increment() will fail. And it not only happens in ParseUser, but all ParseObject. Thanks.

**Comment by flovilmart** [comment]
This may well be an error with the Android SDK too. Can you please post the server logs of such operations running parse-server with VERBOSE=1 ?

**Comment by TylerBrock** [comment]
Yup, i'm seeing the same thing. I'll put up a test + fix.

**Comment by TylerBrock** [comment]
We see it come through like this, can't seem to write a test to reproduce it though. We are doing the increment for this object through the JS SDK.

```js
{
  '1':
   ParseError {
     code: 141,
     message:
      { name: 'HustleError',
        severity: 'error',
        code: 1001,
        message: 'validation failed',
        metadata:
         { model: 'ShortCodeKeyword',
errors: [ 'Request count has an incorrect type' ],
data:
 { creative: { objectId: '0PR5QPubfz' },
   shortCode: '33XXX',
   keyword: '<redacted>',
   requestCount: { __op: 'Increment', amount: 1 },
   createdAt: '2016-06-04T18:06:40.731Z',
   updatedAt: '2016-06-23T21:15:30.879Z',
   lastRequestTime: '2016-06-28T13:55:44.460Z',
   defaultResponse: '<redacted>.',
   ACL: { 'role:organization_N6tdgJhV7M': [Object] } } } } },
}
```

**Comment by flovilmart** [comment]
That would be the increment op that is unproperly parsed in some cases?

**Comment by TylerBrock** [comment]
Yeah most likely

**Comment by TylerBrock** [comment]
Oh, we have a validator on our ShortCodeKeyword classes the requires requestCount be a 'number', perhaps the JS sdk is receiving the op back in the response and freaking out.

**Comment by flovilmart** [comment]
That's highly possible. The internal validation should let an internal incrément go. I would suspect the increment op is not removed from the original data object and gets forwarded as is

**Comment by all-iver** [comment]
Possibly related?  https://github.com/ParsePlatform/Parse-SDK-Android/issues/472

**Comment by flovilmart** [comment]
@iForests can you please update to latest parse-server version (2.2.23) and reopen the issue if if still persists?
