### ISSUE TITLE
Migration already in progress. Error

### ISSUE THREAD

**Issue by pccrazy** [ParsePlatform/parse-server#212]
hello , 

i have tried to migrate the database to mongolab it worked the first time , then i decided to change the account of mongolab to the one that it is official by my company so i stopped the migration and i started a new one and this is what i get.

![screen shot 2016-02-03 at 5 09 14 pm](https://cloud.githubusercontent.com/assets/5598959/12783176/5999439c-ca99-11e5-8a85-e500a3f9e768.png)

**Comment by pungme** [comment]
+1 we have the same issue and now we can't do anything ... :-(

**Comment by nncary** [comment]
+1 having same issue

**Comment by REggar** [comment]
If you go through App Settings > General and click on the Migrate button you can begin the migration again.

**Comment by pccrazy** [comment]
@REggar i try it to click it 100 times the same issue

**Comment by REggar** [comment]
@pccrazy I had the same issue and when I came back the next day the Migrate button worked for me. Perhaps there's a delay until you can do it again, **or** I just got lucky.

**Comment by drew-gross** [comment]
Please report issues with the migration process through the bug reporting tool found at parse.com/help
