### ISSUE TITLE
password security - password in get login get request logged

### ISSUE THREAD

**Issue by jameslin101** [ParsePlatform/parse-server#2120]
I'm seeing this in my logs when I log with get request, running parse-server 2.2.12

at=info` method=GET path="/1/login?password=somepassword&username=someusername" host=someapp.herokuapp.com request_id=a8dae8fc-7c0a-4e2c-82de-493b168e2291 fwd="54.227.100.56" dyno=web.1 connect=0ms service=382ms status=200 bytes=1632

Am I sending the username and password wrong (without encryption?) If so what is the proper way to send the request?

**Comment by woodardj** [comment]
I haven't gotten to this part of our migration yet, but I would say that in general using "GET" as the verb for creating a session is not the correct way to go.

**Comment by jameslin101** [comment]
Does POST work?

**Comment by drew-gross** [comment]
This is the way that the SDKs log in and unfortunately changing that would break backwards compatibility. These seems to be the herkou logs that contain the password, which we have no control over.

**Comment by jameslin101** [comment]
Would it be worth adding a POST login for SDKs to work around this serious security flaw?
