### ISSUE TITLE
When adding 2 relations in a row, the second relation is not added successfully

### ISSUE THREAD

**Issue by refre5h** [ParsePlatform/parse-server#2121]
### Issue Description
When adding 2 relations in a row (one after the other, NOT both at the same time), the second relation is not added successfully. This happens in our iOS app, and confirmed in cloudcode.

Example: I add a friend in the app, this friend will be added to my "friends" relation in my user object. I then find another friend, add this new friend. This new friend will not be added to my "friends" relation, our app actually crashes. The sample snippet below shows how to replicate this case in the cloudcode.

### Steps to reproduce
1. add a relation
2. save the object
3. check db, the above relation is added
4. Add another relation
5. Save the object again
6. check db, the second relation is not added
```javascript
Parse.Cloud.define("addFriends", function(request, response) {
    var user = new Parse.Object("_User");
    user.id = "IMEIcGMzHK";
    var friend1 = new Parse.Object("_User");
    friend1.id = "zhukOmQMwZ";
    var friend2 = new Parse.Object("_User");
    friend2.id = "ycaor1Xqrq";

    var relation = user.relation("friends");
    relation.add(friend1);
    user.save(null, {useMasterKey:true}).then(function(updatedUser){
        // friend1 relation is successfully added
        var relation = updatedUser.relation("friends");
        relation.add(friend2);
        return updatedUser.save(null, {useMasterKey:true});
    }).then(function(user){
        //friend2 is not added
        response.success(user);
    }, function(error){
        response.error(error)
    })
})
```

#### Expected Results
Both relations should be added.

#### Actual Outcome
Only the first relation is added

### Environment Setup
- **Server**
  - parse-server version: ~2.2.10
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

### Logs/Trace
{"result":{"friends":{"__type":"Relation","className":"_User"},"updatedAt":"2016-06-21T22:51:37.938Z","objectId":"IMEIcGMzHK","__type":"Object","className":"_User"}}

**Comment by mtrezza** [comment]
I can confirm that, I was just about to post this issue.
Also in dashboard (parse.com and self-hosted) only the first relation is visible.

Adding two relations in a row results in two documents in the relation collection:
```
{
    "_id": {
        "$oid": "576a84e9735019d792505728"
    },
    "owningId": "O9Py2pnlsm",
    "relatedId": "IV9X3AfM8x"
}
{
    "_id": {
        "$oid": "576a8f21735019d792505732"
    },
    "owningId": "O9Py2pnlsm",
    "relatedId": "SGchom1GJa"
}
```

parse server 2.2.11
mongo-db 3.0.9

**Comment by mtrezza** [comment]
@refre5h When you say "check db, the second relation is not added", did you check via dashboard or by actually looking at the document in mongoDB?

Because it seems as if while the relation is added in the database, it is not visible in Parse Dashboard. A query however would recognize the relation and output the correct result, e.g.

`query.equalTo(aRelationField, aUserInTheRelationField);` would recognize the user.

**Comment by flovilmart** [comment]
This seems to be a problem with the JS SDK, can you provide the logs from parse-server by running VERBOSE=1 ?

**Comment by refre5h** [comment]
@mtrezza Actually in my case neither Parse Dashboard nor mongoDB shows the second relation entry.

@flovilmart See log below:
```
verbose: POST /parse/functions/addFriends { host: 'localhost:1337',
  'user-agent': 'curl/7.43.0',
  accept: '*/*',
  'x-parse-application-id': 'myAppId',
  'x-parse-rest-api-key': 'myRESTAPIKey' } {}
verbose: PUT /parse/classes/_User/IMEIcGMzHK { 'user-agent': 'node-XMLHttpRequest, Parse/js1.8.5 (NodeJS 4.3.1)',
  accept: '*/*',
  'content-type': 'text/plain',
  host: 'localhost:1337',
  'content-length': '265',
  connection: 'close' } {
  "friends": {
    "__op": "AddRelation",
    "objects": [
      {
        "__type": "Pointer",
        "className": "_User",
        "objectId": "zhukOmQMwZ"
      }
    ]
  }
}
verbose: {
  "response": {
    "updatedAt": "2016-06-23T23:50:43.509Z"
  }
}
verbose: PUT /parse/classes/_User/IMEIcGMzHK { 'user-agent': 'node-XMLHttpRequest, Parse/js1.8.5 (NodeJS 4.3.1)',
  accept: '*/*',
  'content-type': 'text/plain',
  host: 'localhost:1337',
  'content-length': '155',
  connection: 'close' } {}
verbose: {
  "response": {
    "updatedAt": "2016-06-23T23:50:44.938Z"
  }
}
verbose: {
  "response": {
    "result": {
      "friends": {
        "__type": "Relation",
        "className": "_User"
      },
      "updatedAt": "2016-06-23T23:50:44.938Z",
      "objectId": "IMEIcGMzHK",
      "__type": "Object",
      "className": "_User"
    }
  }
}
```

**Comment by flovilmart** [comment]
That seems to be a problem in the JS SDK.

**Comment by flovilmart** [comment]
Please open the issue

**Comment by flovilmart** [comment]
Thanks!
