### ISSUE TITLE
Parse server does not stream .mp4 PFFile to AVPlayer

### ISSUE THREAD

**Issue by dpaid** [ParsePlatform/parse-server#2127]
### Issue Description

Parse server hosted on AWS ElasticBeanStalk(deployed with AWS button) cannot stream .mp4 PFFile saved in mongodb on AWS EC2 (EBS) to iOS AVPlayer and Safari browser. 
Video plays on Chrome browser but does not play on my iOS app or Safari browser. 
Videos hosted on parse service play with no problem.

Error I get on iOS:
Error Domain=AVFoundationErrorDomain Code=-11850 "Operation Stopped" UserInfo={NSUnderlyingError=0x13fb86740 {Error Domain=NSOSStatusErrorDomain Code=-12939 "(null)"}, NSLocalizedFailureReason=The server is not correctly configured., NSLocalizedDescription=Operation Stopped}

Link to video:
[http://parseserver-fmp42-env.us-east-1.elasticbeanstalk.com/parse/files/1S22JRBPse4F5vXbpnvP666mbBAqruD6VxZrbRfi/11990ed054321d7aefba75f734896651_2016-06-20%2018-03-57%200000_LWyt213QSG.mp4](http://parseserver-fmp42-env.us-east-1.elasticbeanstalk.com/parse/files/1S22JRBPse4F5vXbpnvP666mbBAqruD6VxZrbRfi/11990ed054321d7aefba75f734896651_2016-06-20%2018-03-57%200000_LWyt213QSG.mp4)

### Environment Setup

- **Server**
  - parse-server version: 2.2.13
  - Localhost or remote server?: AWS

- **Database**
  - MongoDB version: 3.2.6
  - Storage engine: wiredTiger
  - Localhost or remote server?: AWS

**Comment by dpaid** [comment]
Using the S3 file adapter fixed it!

**Comment by indiandragon** [comment]
[Solved] The solution is given by @Bragegs here - https://github.com/ParsePlatform/parse-server/issues/1440#issuecomment-212815625 . In short, parse-server doesn't seem to be supporting streaming of audio/video and @Bragegs code enables it. I hope it get's PR and parse team looks into it.

**Comment by otymartin** [comment]
@dpaid  is video streaming fully working for you?
If so can you share some code snippets?

Thanks
