### ISSUE TITLE
How to implement file upload with parse server

### ISSUE THREAD

**Issue by cyboolo** [ParsePlatform/parse-server#213]
Hi

Could you help me to implement file upload with parse server on client side and on server side.

Before migration to parse server, on client side, I used:

`myDropzone.on("addedfile", function(myfile) { 
             
        if(myfile && (myfile.size<3000000)){
        
            var name = "avatar.png";
            var parseFile = new Parse.File(name,myfile);
        	
        	parseFile.save().then(function(){
                    
            Parse.Cloud.run("modify_avatar", {A:parseFile},{
                        success: function(reponse){
                         
                        //on cloud code I attached the file path to User class.    
                            
                        },
                        error: function(error){ console.log(error); }
                    });
            
           
                }, function(error){});
        	////
            }    
             
  		});`

That worked perfectly but now with parse server I do not know how to make it work.

I have my db on mongodb and deployed parse server on heroku. Everything is working fine except this file upload that I can't manage.

Thank you for your help.

**Comment by smanikandan14** [comment]
I have reported the issue https://github.com/ParsePlatform/parse-server/issues/136. Haven't got any response yet.

**Comment by gfosco** [comment]
We'll look at fixing this very soon, please follow on in #136.
