### ISSUE TITLE
Slowly receiving notifications

### ISSUE THREAD

**Issue by didoivanov** [ParsePlatform/parse-server#2132]
Hey guys,

We are having a big issue since today, our notifications stopped delivering to the devices, or deliver very very slow. I looked into Parse dashboard and saw that most of them are with "Sending" status.

https://www.dropbox.com/s/xylbvdp1igxowkk/Screenshot%202016-06-23%2019.28.25.png?dl=0

Any idea what could this be caused by?

Some info:
- We are using php to send the push and ios sdk for the app.
- Everything worked just fine, till today (nothing changed on the source point of view)
- All certificates are valid.
- Doesent work on ios (we dont use android so far)
- We were using a free account, and just upgraded but unfortunately nothing changed.

Thanks in advance!

**Comment by MattiaConfalonieri** [comment]
Same problem here, just from now... before that moment everything work great...

**Comment by Pelican43** [comment]
Same problem for two Apps .....

**Comment by MattiaConfalonieri** [comment]
Seem parse.com have problem in my case old user (on parse.com) have this problem

**Comment by CarlosLuisGomez** [comment]
Exactly same problem on ios and android.

**Comment by flovilmart** [comment]
Is that issue on parse.com?

**Comment by didoivanov** [comment]
yes

**Comment by flovilmart** [comment]
So I'll have to close that issue as this issue reporting system is for parse-server, the open source project, not support on parse.com.

Please use [http://parse.com/help](http://parse.com/help).

**Comment by didoivanov** [comment]
but there's no solution on parse.com/help it redirects to here...

**Comment by Pelican43** [comment]
I have a solution: Go on parse.com/help and click on "Contact Us", then "Which platform is affected by the bug?" select other.
Which app is this regarding? select no particular app.
And next, you'll redirect on facebook, you could report the "push notifications" issue.

**Comment by Pelican43** [comment]
Guys, come here to report and follow the issue: https://developers.facebook.com/bugs/1102065359852751/

**Comment by didoivanov** [comment]
Thanks!
Also here https://developers.facebook.com/bugs/1184736658212251/
