### ISSUE TITLE
Cloud code security -- general question

### ISSUE THREAD

**Issue by pawesome** [ParsePlatform/parse-server#2135]
In the docs I see that it is recommended to pass a sessionToken parameter to cloud code functions. 

Is this secure? 

Say a malicious user is sniffing traffic and accesses a session token, would they now have the ability to execute requests using this? (Maybe if the project were open source and they had access to the application key and the client key)

**Comment by flovilmart** [comment]
You want to have all traffic to your parse-server to be HTTPS. SessionTokens should be considered as passwords, therefore very sensitive.
