### ISSUE TITLE
PARSE_SERVER_FILES_ADAPTER syntax

### ISSUE THREAD

**Issue by bigdoghung** [ParsePlatform/parse-server#2140]
Is the syntax supposed to be

```
 "PARSE_SERVER_FILES_ADAPTER": "./Adapters/Files/S3Adapter.js" 
or
  "PARSE_SERVER_FILES_ADAPTER": "./Files/S3Adapter.js"
```

**Comment by flovilmart** [comment]
The S3 adapter was moved to it's own npm package, please see documentation here:

http://github.com/parse-server-modules/parse-server-s3-adapter/blob/master/README.md
