### ISSUE TITLE
Please give me back my data!

### ISSUE THREAD

**Issue by thestubborndev** [ParsePlatform/parse-server#2142]
Give me back the data of my 300k users app I lost without motive when migrating to Heroku. Waiting for a response.

**Comment by hramos** [comment]
I'm closing out this issue as it is not related to Parse Server. For migration assistance, please visit https://parse.com/help#report

**Comment by thestubborndev** [comment]
If I would be Parse I wouldn't bother so much about responsiblity after discontinuing my services.

Is this how you treat lovely developers? With contract loopholes?

Please give my data back: there are 300k users waiting.

Thx

**Comment by flovilmart** [comment]
if you would explain what happened when you migrated to heroku, i may be able to help. 

Was data lost when migrating away from parse? Did your database crash and lost all data?

**Comment by thestubborndev** [comment]
Exactly, I was moving out from Parse, but the transfer process didn't go as expected. I followed everything step exactly but at the end I didn't had data neither in Heroku or in Parse.

**Comment by flovilmart** [comment]
Where did you setup your database? What do you mean by didn't go as expected? Did you abort it? Did it fail mid-way? The parse.com/help may be your best chance here as the team responsible for parse.com migrations is not responsible for parse-server.

**Comment by thestubborndev** [comment]
I setup MongoDb on mLab (Heroku Addon).
Parse Migration was all green at the end, but most of the tables were missing. I didn't abort it, I waited until the Finalize button appeared and then clicked it.

ok for parse.com/help but I really need to solve this quickly.. do you have a forecast for this kind of problems?

**Comment by flovilmart** [comment]
Did you check the data consistency before hitting finalize? So not all the data is lost right?

**Comment by thestubborndev** [comment]
The most important is lost unluckily, the Recipe table. Only some tables (not useful and only for tracking purposes) transferred. I can't even recover that table in the Parse dashboard... :|

**Comment by flovilmart** [comment]
On that point, like Hector said, there is nothing much I can do on this side. 
So your recipe table was not missing at the time you migrated to mLab. Did you use the shared plan or a dedicated hosting?

**Comment by thestubborndev** [comment]
No it was not missing. Shared plan for mLab.

**Comment by flovilmart** [comment]
So that's a problem for mLab, not Parse. 

I know mLab provide daily backups on shared plans, you may wanna look with them and find a backup that contains your data.

**Comment by thestubborndev** [comment]
But if this (much probably) a bug in the migration tool, are you really sure I shouldn't deserve some time of backup copy for my table? Really you don't have it? Even an old JSON would be ok..

Will check with mLab too..

**Comment by flovilmart** [comment]
You just told me that before hitting finalize, your Recipe table was properly imported in mLab.

Also, when you decide to migrate your database and hit finalize, the data is migrated to the new provider.

And I can't say if the table is still saved somewhere as I don't work for Parse. I'm just a contributor, trying to help. 

In any case, given that your Recipe table was properly imported once to mlab, you should have a daily snapshot available from them.

**Comment by hramos** [comment]
@thestubborndev I closed out this issue specifically because the Parse Server repository is not the right place to discuss Parse.com data migrations, as this repository is managed by a community of collaborators. 

The Parse team has provided some additional information in the ticket you opened earlier today through the Parse.com Help page: https://developers.facebook.com/bugs/608100202693122/
