### ISSUE TITLE
Using includeKey from a client query, and then saving that object replaces the pointer

### ISSUE THREAD

**Issue by silvermana** [ParsePlatform/parse-server#215]
My client app is querying a root object and using includeKey to download objects there are pointers to.  The client app then modifies and saves the root object.  After the save, when I inspect my MongoDB one of the pointers has been replaced with the representation of that object.  This then causes errors when that root object is fetched again.  I did not have this issue when using Parse.com.

**Comment by gfosco** [comment]
There have been several changes to object transformations lately.  Can you please re-open if you're still experiencing this issue with 2.1.3+?  Thanks.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)
