### ISSUE TITLE
iOS Push notification doesn't play sound if sent as a text

### ISSUE THREAD

**Issue by andrew8712** [ParsePlatform/parse-server#2152]
### Issue Description

No sound played when I sent text Push notification through dashboard. This JSON plays sound as expected though:

```
{
   "aps" : {
      "alert" : {
         "body" : "Your message goes here"
      },
      "sound" : "default"
   }
}
```
The notification shows fine, it just doesn't play a sound.

### Environment Setup

- **Server**
  - parse-server version: 2.2.14 (same problem on 2.2.12).
  - parse-dashboard version: 1.0.14
  - Operating System:     Ubuntu 10.14
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): DigitalOcean

**Comment by flovilmart** [comment]
I'm not sure if the "sound": "default" parameter should be added when sending text only notifications. What was the behaviour on parse.com?

**Comment by andrew8712** [comment]
The sound played just fine on parse.com

**Comment by flovilmart** [comment]
Alright! Feel like making a pull request to add that?

**Comment by ranhsd** [comment]
I tested in on my local version of parse-server & parse-dashboard (installed on my local machine) and it works both text and sound. Can you please test in on a local version of parse ?

**Comment by flovilmart** [comment]
This is an issue on the dashboard if sound: default that should be set when crafting a text only payload.

**Comment by EricNetsch** [comment]
please add sound:default to the dashboard code. This is how it worked on hosted parse.com
