### ISSUE TITLE
LiveQuery build error = include of non-modular header inside framework module 'Bolts BFCancellationToken'

### ISSUE THREAD

**Issue by Samigos** [ParsePlatform/parse-server#2153]
### include of non-modular header inside framework module 'Bolts BFCancellationToken'

Hey everyone...

I just downloaded the Parse sample project, installed LiveQueries pod and nothing else. When I try to build it, it pops the two errors below.. What's wrong?

I'm using Xcode 7.3.1

![161be0ca-34d9-11e6-8656-aee006720e90](https://cloud.githubusercontent.com/assets/9467442/16362606/3c935a32-3bbc-11e6-939a-53c145ebc71a.png)

**Comment by flovilmart** [comment]
Please report in the iOS-OSX-SDK repository, as it's not related to parse-server
