### ISSUE TITLE
Can we use Socket.io in Parse Server?

### ISSUE THREAD

**Issue by partikles** [ParsePlatform/parse-server#2158]
We want to use Socket.io for our realtime app. We can't use Parse Live Query. Can we use socket.io in Parse Server?

**Comment by hramos** [comment]
I am closing this out as we're trying to cut down on the number of non-issues. This will help us focus on the issues that are actively preventing people from migrating their production apps to Parse Server.

As an alternative, I suggest opening a new discussion at [Server Fault](http://serverfault.com/tags/parse), a Q&A site dedicated to "questions about managing information technology systems in a business environment".
