### ISSUE TITLE
when starting parse it complains about not finding a database

### ISSUE THREAD

**Issue by gbtommasi** [ParsePlatform/parse-server#2160]
On Mac Os El Capitan, when starting parse with command:
parse-server --appId MYAPP --masterKey MYKEY
it gives this error. Mongoldb seems to be correctly running, though:

**/usr/local/lib/node_modules/parse-server/lib/ParseServer.js:239
      throw 'When using an explicit database adapter, you must also use and explicit filesAdapter.';
      ^
When using an explicit database adapter, you must also use and explicit filesAdapter.**

I am a newbie to parse, maybe I am missing something
thanks for the help

**Comment by vitalyos** [comment]
Hello @gbtommasi! I have the same problem on Ubuntu 16.04. Did you find any solution for this issue? What was your problem?

**Comment by gbtommasi** [comment]
Yea, you need to set the databaseURI property when starting parse, in my case it is: mongodb://localhost/test

hope it helps!

**Comment by vitalyos** [comment]
Thanks, databaseURI param solved my problem.

**Comment by ankarthik** [comment]
hey guys just wanted to confirm one thing
the databaseURI can be anything starting with **mongodb://** or will it be found in code or somewhere?

**Comment by vitalyos** [comment]
databaseURI must be a valid URI to an existing mongodb database
