### ISSUE TITLE
Uploading files to Google cloud storage with FileAdapter

### ISSUE THREAD

**Issue by notentered** [ParsePlatform/parse-server#2162]
Hello,

I'm trying to setup the GCS file adapter for parse (parse-server-gcs-adapter).

My config is:
```
var GCSAdapter = require('parse-server-gcs-adapter');
var gcsOptions = {
  "projectId": "MY_PROJECTID",
  "keyFilename": "MY_CERT_FILE.json",
  "bucket": "MY_BUCKET"
};

var gcsAdapter = new GCSAdapter(gcsOptions);

var psConfig = {
    "serverURL": "SERVER_URL",
    "verbose": true,
    "masterKey": "MASTER_KEY",
    "filesAdapter": gcsAdapter
}
new ParseServer( psConfig );
```

Now. Trying to upload file i got error:
`{code: 130, error: "Could not store file."}``

Debugging a little bit, I found that in FilesRouter.js we have:
```
      filesController.createFile(config, filename, req.body, contentType).then(function (result) {
        res.status(201);
        res.set('Location', result.url);
        res.json(result);
      }).catch(function (err) {
        next(new Parse.Error(Parse.Error.FILE_SAVE_ERROR, 'Could not store file.'));
      });
```

The error in `catch(function (err)...` is: __"Cannot assign to read only property 'authClient' of [object Object]"__

The exact configurations for the adapter is not important, because this error happens no matter of the values.

...and I really don't know what to do next. :)

**Comment by notentered** [comment]
After some more digging, it seems this is coming from google-auto-auth: https://github.com/stephenplusplus/google-auto-auth/issues/4

**Comment by mikesurowiec** [comment]
The GCS adapter doesn't take an object for its construction, you just pass the params in. Take a look at the File Adapters section in the wiki for more info - https://github.com/ParsePlatform/parse-server/wiki/Configuring-File-Adapters

**Comment by mauriciord** [comment]
Hey, this is happening with me, i've tried with `.json` and `.p12` files, but not working.
Trying to upload directly from Parse Dashboard, but 400 Bad Request.

![kapture 2017-01-26 at 18 25 31](https://cloud.githubusercontent.com/assets/1128701/22349053/2027d2e2-e3f5-11e6-90e7-83d5dc195308.gif)

I'm using as an instance:
```javascript
// ...
onst GCSAdapter = require('parse-server-gcs-adapter');

const gcsAdapter = new GCSAdapter(
    'xxxxxxxxxxxx', 
    '/opt/bitnami/apps/parse/htdocs/xxxxx.json', 
    'xxxxxxxxxxxx', {
        bucketPrefix: '',
        directAccess: true
    }
);

const api = new ParseServer({
    databaseURI: 'mongodb://thcm:Tc12345678tc@ds157187.mlab.com:57187/thcmapi', //'mongodb://root:qqk18kaI@127.0.0.1:27017/bitnami_parse',
    cloud: './node_modules/parse-server/lib/cloud-code/Parse.Cloud.js',
    appId: 'xxxxx',
    masterKey: 'xxxxxxx',
    fileKey: 'xxxxxxxx',
    serverURL: 'https://thoc.com.br/parse',
    filesAdapter: gcsAdapter
});
// ...
```

What can i do ?

**Comment by wookiem** [comment]
@mauriciord Did you ever get this working?

**Comment by flovilmart** [comment]
We're using it at the moment and we don't have any issue

**Comment by wookiem** [comment]
Good to know @flovilmart.  

My file uploading was working fine with default adapter.  My client is receiving status 400, bad request with response "{"code":130,"error":"Could not store file."}".
I suspect this may be related to my configuration of Google Cloud Storage itself.  

Here are the steps I did on that side after creating a project and bucket:
1) IAM & Admin -> Service accounts -> Create service account -> Select "Project Editor" role (select Furnish a new private key with JSON key type).  Any other configuration required on the GCS side?

2) Then in parse-server index.js (fyi, I'm running parse-server locally): 
```
var GCSAdapter = require('parse-server-gcs-adapter');
var gcsAdapter = new GCSAdapter(
	'<google cloud project>', // not the x-goog-project-id which is a number
	'<full path to downloaded json private key file>, 
	'gs://<google cloud storage bucket name>', 
	{
		bucketPrefix: '',
		directAccess: true
	}
);

var api = new ParseServer({
  databaseURI: process.env.MONGODB_URI,
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID,
  masterKey: process.env.MASTER_KEY,
  serverURL: process.env.SERVER_URL,  // Don't forget to change to https if needed
  filesAdapter: gcsAdapter,
  liveQuery: {
    classNames: ["Event"] // List of classes to support for query subscriptions
  },
  verifyUserEmails: true, 
  publicServerURL: process.env.SERVER_URL,
  appName: process.env.APP_NAME,
  emailAdapter: {
  	module: 'parse-server-simple-mailgun-adapter',
  	options: {
			fromAddress: process.env.MAILGUN_FROM_ADDRESS,
			domain: process.env.MAILGUN_DOMAIN,
			apiKey: process.env.MAILGUN_API_KEY
		}
	},
	push: {
      ios: {
      	pfx: path.join(__dirname, process.env.IOS_PUSH_PFX),
   			bundleId: process.env.IOS_BUNDLE_ID,
    		production: (process.env.IOS_APNS_PRODUCTION==="true") ? true : false
      }
    }
  });
```

I'm thinking it might be useful step to use `postman` to send an HTTP request to create a GCS file (i.e. take parse-server out of the equation).  Is there a sample POST message that I could construct that mimics the same POST request that parse-server issues?

**Comment by wookiem** [comment]
Ok, I figured out what I was doing wrong.  The bucket should not include the "gs://" prefix.

For other people who run into issues getting things working, I highly recommend using Google's OAuth 2.0 Playground located at [https://developers.google.com/oauthplayground/](https://developers.google.com/oauthplayground/)

From there you can:

1. Select & authorize APIs:
- Choose the "Cloud Storage JSON API v1"
- Choose "https://www.googleapis.com/auth/devstorage.read_write"
- Click "Authorize APIs" button
- Choose your google account to continue (and then Allow)

2. Exchange authorization code for tokens
- Click "Exchange authorization code for tokens"

3. Configure request to API

- Click HTTP Method and select `POST`
- Edit the request URI so that it is in the form of `https://www.googleapis.com/upload/storage/v1/b/<your bucket name>/o?uploadType=media&name=test`
- Click Content-Type and select `text/plain`
- Click Enter request body and enter `123`

4. Click "Send the request" and see whether your request works or not.
