### ISSUE TITLE
High response time when uploading files

### ISSUE THREAD

**Issue by mattstrong** [ParsePlatform/parse-server#2167]
I'm getting slow response times when uploading jpeg images of roughly 3mb to Parse Server in Heroku through the S3Adapter with directAccess set to true:

```
  filesAdapter: new S3Adapter(
    process.env.S3_ACCESS_KEY,
    process.env.S3_SECRET_KEY,
    process.env.S3_BUCKET,
    { 
      directAccess: true 
    }
  ),
```

#### Expected Results

Faster response times than over 6 seconds on average

#### Actual Outcome

NewRelic shows that it is not the upload to S3 itself that is the time sink, but the middleware (body-parser?). Does this mean that directAccess above set to true does not work? How do I make the upload faster?

![skjermbilde 2016-06-29 kl 09 20 04](https://cloud.githubusercontent.com/assets/19945514/16443754/d18021f0-3dda-11e6-8f3c-1832eefaa49c.png)

### Environment Setup

  - Heroku 4 Standard 1x Dynos
  - parse-server version: 2.2.12

**Comment by flovilmart** [comment]
@mattstrong this is probably your client that take a long time to transmit the file to the server. Did you try running that upload locally (from a local client to a local parse-server)? Please reopen the issue if it persists or if the results of the local upload is similar.
