### ISSUE TITLE
Requests timing out / npm install error

### ISSUE THREAD

**Issue by ryderjack** [ParsePlatform/parse-server#2169]
Requests are timing out using a local version of parse-server with mongolab. I've seen related issues that have been solved by updating either parse-server or returning to mongo version: 2.1.18. I've tried these and have seen an issue after npm install, the output has been pasted below - wondering if these are related?

After running npm install I get the following results and the problem persists.

Any ideas on this config error after running npm install? 

### Environment Setup

- **Server**
  - parse-server version: 2.2.13
  - Operating System:     El Capitan 10.11.5
  - Hardware:            Mac
  - Localhost or remote server? Localhost

- **Database**
  - MongoDB version: 2.1.18
  - Localhost or remote server? Localhost

```
Jacks-MacBook-3:node_modules jack$ npm install

> sse4_crc32@5.1.1 install /Users/jack/Desktop/parse-server-example/node_modules/sse4_crc32
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/anaconda/bin/python" is v3.4.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:14)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:821:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:469:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jack/Desktop/parse-server-example/node_modules/sse4_crc32
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:sse4_crc32@5.1.1 sse4_crc32@5.1.1 install: `node-gyp rebuild`
npm WARN install:sse4_crc32@5.1.1 Exit status 1
```

**Comment by zeustl** [comment]
Well the problem is obvious . 

Install & use another version of python ( 2.7 for example ). 

After installing python2.7 run 
```
npm config set python python2.7
```

**Comment by ryderjack** [comment]
@zeustl fixed that but still getting timeout with a saveInBackground call. Weirdly, changing to SaveEventually works fine..

**Comment by zeustl** [comment]
Take intro account the current limitations : https://parse.com/docs/cloudcode/guide#cloud-code-timeouts

If you need to do more intensive work , switch to jobs
