### ISSUE TITLE
Parse global

### ISSUE THREAD

**Issue by GuichiZhao** [ParsePlatform/parse-server#2176]
Parse use node `global` to population `Parse` object .
However ,I wonder why sometime it can work but sometime do not.
Firstly ,in index.js
```
var job=require("./lib/job");
Parse.Cloud.job=job(app)
```
In this case, the job system can works fine

However,I follow the similar trick
```
var define=require('./lib/define')()
Parse.Cloud.define=define
```
When I 
`console.log(Parse.Cloud.define.toString())`
In individual module
It still the old code ,rather than my wrapper code

If I
```
var define=require('../../lib/define')()
Parse.Cloud.define=define
```
In the individual module (instead of index.js)

It can work as expected, why this happen ?

**Comment by flovilmart** [comment]
If you need to inject some properties on Parse.Cloud object, I believe you should do it at the top of your files. Then node will cache the required module, so that has the same performance impact as calling it once.
