### ISSUE TITLE
Procfile question.

### ISSUE THREAD

**Issue by MattiaConfalonieri** [ParsePlatform/parse-server#2181]
Hi, i am trini to setup hirefire to manage web dynos scaling, hirefire ask me for "The name of the dyno-type as defined in your Profile", but i don't have a profile, how can create it and with i need ti write inside the profile?

Thanks very much for the help...

**Comment by skinp** [comment]
I suggest you with wither hirefire or heroku. I'm closing as this is not directly related to parse-server...
