### ISSUE TITLE
Error importing data from export: 'objectId is an invalid field name.'

### ISSUE THREAD

**Issue by doender** [ParsePlatform/parse-server#2184]
I want to import existing data into a new parse-server instance (without using the migration tool).
However, when creating an object with a sett objectId using the rest api I get:

`{u'code': 105, u'error': u'objectId is an invalid field name.'}`

Also, if I delete the object id, the updatedAt and createdAt dates are not respected (they are set to the current date). Is there another way to import existing data?

**Comment by hramos** [comment]
The `objectId` field cannot be set using the REST API. Have you tried importing the data into mongo directly?

**Comment by doender** [comment]
I have now exported and imported from mongodb using mongoexport and mongoimport. 
This seems to have worked. Is this the recommended approach?

**Comment by hramos** [comment]
For the time being, yes. Parse.com's Dashboard allowed JSON to be imported via the dashboard since you did not have direct access to the database. For Parse Server, you can import data directly into the mongo database, no need to go through the server.

**Comment by doender** [comment]
Thanks, seems to be solved this way.
