### ISSUE TITLE
dirty returns always true

### ISSUE THREAD

**Issue by benishak** [ParsePlatform/parse-server#2187]
# Env
Parse 2.2.15
Parse SDK 1.8.5

# Problem/reproduce
I try to create a User, save it, in BeforeSave I check if email has been changed

```
# in BeforeSave
if(user.dirty("email")){ 
      console.log(user.id) // undefined this object is totally new
      doSomethingwith(user.get("email") 
}
```

I also didn't try to modify the email

**Comment by benishak** [comment]
I just upgraded to 2.2.15 and still the same

**Comment by natanrolnik** [comment]
Hey @benishak , I've faced the same thing. The Parse JS SDK always returns `true` for `dirty()` if the object is new, if it has no I'd. Check here: https://github.com/ParsePlatform/Parse-SDK-JS/blob/cc077157aec33f95a661d87f51054402355a5cf6/src/ParseObject.js#L459
Depending on the version you had running on the hosted Parse.com, you may see the difference.

**Comment by flovilmart** [comment]
Thanks @natanrolnik, that seems to be the right answer. Let us know if the problem persists with existing objects.

**Comment by tealshift** [comment]
@flovilmart @benishak I don't understand the reasoning here. Why would a developer expect all keys to be dirty if the object is new? I recently wrote a condition in the _User beforeSave to authorize changes to a specific field and it resulted in the signup process breaking.

The API docs say nothing about this behavior:
> Boolean dirty( attr ) 
Returns true if this object has been modified since its last save/refresh. If an attribute is specified, it returns true only if that particular attribute has been modified since the last save/refresh.

**Comment by tealshift** [comment]
As a workaround, one may use:

`(request.object.dirtyKeys().indexOf(<myKey>) != -1)`

**Comment by benishak** [comment]
I remember I moved that logic to AfterSave which is actually the correct way to do it. In AfterSave the dirty returned false.

**Comment by tealshift** [comment]
@benishak Yep, that's because the object will have its `id` defined at that point. I maintain that the docs should reflect this specific case in beforeSave (assuming this behavior is still desired).

**Comment by oallouch** [comment]
Any news on this ? When we use dirty, we expect the property to exist if it returns true.

**Comment by oallouch** [comment]
I think dirty should be deprecated and a new method added.
For now I use :

```
function isModified(parseObj, propertyName) {
	if (parseObj.isNew()) {
		return parseObj.get(propertyName) != null; // dirty() always returns true there
	} else {
		return parseObj.dirty(propertyName);
	}
}

```

**Comment by flovilmart** [comment]
Feel free to open a PR

**Comment by oallouch** [comment]
To be honest, it scares me. Maybe I'll try one day :)

**Comment by flovilmart** [comment]
No need to be scared, also this is an closed issue, and I believe the behaviour is the expected one.

**Comment by oallouch** [comment]
Maybe I'll stick with my small utility functions that tell if it's got a new value or if it has been changed.
