### ISSUE TITLE
Using Parse SDKs with Parse Server

### ISSUE THREAD

**Issue by kickassQc** [ParsePlatform/parse-server#219]
Hi, i try to connect my unity project to my personal Parse server, and in the [website of Parse ](http://blog.parse.com/announcements/introducing-parse-server-and-the-database-migration-tool/) they said i just have to add this line with my server information but i get this error : 
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0117	'ParseClient' does not contain a definition for 'initialize'	Parse test selfhost.CSharp	C:\Users\Simon\Documents\Parse test selfhost\Assets\Parsenew.cs	10	Active

`    ParseClient.initialize(new ParseClient.Configuration
        {
            ApplicationId = "YOUR_APP_ID",
            ClientKey = "YOUR_APP_CLIENT_KEY",
            Server = "http://localhost:1337/parse"
        });`

**Comment by mghohoo** [comment]
get the latest version

**Comment by kickassQc** [comment]
I use the version provide on the website, 1.7.0, Do you have a more recent version ?

Envoyé de mon iPhone

**Comment by franzsilva** [comment]
Im also getting this issue with Parse.Android.

**Comment by franzsilva** [comment]
Ok found the mistake. 

On the documentation on the site it needs to be updated to Cap on the first Letter. 

ParseClient.Initialize 

:)
