### ISSUE TITLE
Parse LiveQuery with json config file

### ISSUE THREAD

**Issue by gilthonweapps** [ParsePlatform/parse-server#2196]
Hi,

So far, I have been using Parse Server with a JSON config file and PM2. Everything is running fine.
Now, I would like to activate LiveQuery for my server. 
Here is a portion of my config file:

> {
>   "serverURL": "http://localhost:1337/",
>   "mountPath": "/parse",
>   "databaseURI": "mongodb://localhost:27017/db",
>   "appId": "APPID",
>   "masterKey": "MASTERKEY",
>   "enableAnonymousUsers": true,
>   "allowClientClassCreation": false,
>   "verifyUserEmails": false,
>   "verbose": true,
>   "maxUploadSize": "100mb",
>   "liveQuery": {
>     "classNames": ["Class1", "Class2"]
>   }
> }

So, I have said to the server that my classes Class1 and Class2 are working with LiveQuery.
However, when I see in the wiki, I need to do 

> var parseLiveQueryServer = ParseServer.createLiveQueryServer(httpServer);

But as I only use a JSON config file to setup and start my server, how can I activate LiveQuery?

Thanks

**Comment by flovilmart** [comment]
Thanks for reporting it, this should be added to the CLI.

**Comment by gilthonweapps** [comment]
Thanks. Looking forward to it :) 👍

**Comment by flovilmart** [comment]
@gilthonweapps you can implement it, that should be pretty straightforward in [here](https://github.com/ParsePlatform/parse-server/blob/master/src/cli/parse-server.js#L68)
