### ISSUE TITLE
Feature Request: Implement the option to expire inactive sessions and to revoke a session on password changes

### ISSUE THREAD

**Issue by cherukumilli** [ParsePlatform/parse-server#2197]
Currently, there is no way to 
- expire inactive sessions
- revoke a session on password changes

As per the documentation at: https://github.com/ParsePlatform/parse-server/wiki/Compatibility-with-Hosted-Parse#session-features both of these features are available in `parse.com`.

Is the parse team planning to push these changes into parse server? It will be greatly appreciated if the parse team can open source this functionality as it is tried and tested.

@gfosco, @flovilmart, @drew-gross - thoughts?

Can this issue be tagged with a `discussion` label by the people who have `write` access to this repo?

**Comment by flovilmart** [comment]
Not sure we'd wanna to that for security reasons (the ability to hijack any user account that is not validated after a delay). But that's my opinion.

**Comment by cherukumilli** [comment]
@flovilmart 

I can take a shot at updating the documentation...

As the documentation that needs to be updated is in the project WiKi and I can't submit a pull request on the wiki...any idea, how I can update it?

**Comment by flovilmart** [comment]
uhh right...
can you fork the wiki?

**Comment by cherukumilli** [comment]
As per https://help.github.com/articles/about-github-wikis/

`By default, only collaborators on your repository can make changes to wikis, but you can configure this to be enabled for all users on public repositories.`

**Comment by flovilmart** [comment]
I'll check what I can do to open it or update the docs then.

**Comment by flovilmart** [comment]
Docs are updated
