### ISSUE TITLE
_email_verify_token never expires blocking new signups...

### ISSUE THREAD

**Issue by cherukumilli** [ParsePlatform/parse-server#2198]
Describe your issue in as much detail as possible.

The following are some cases where the parse-server blocks `new` user Sign Ups because the `_email_verify_token` never expires.

### Steps to reproduce

Scenario 1: User enters an email address with a typo during the signup process preventing another user from signing up.

1. App requires `username` to be the same as the `email address`

2. `User1` has an email address `johnsmith111@gmail.com`

3. `User2` has an email address `johnsmith1@gmail.com`

4. `User1` enters `johnsmith1@gmail.com` in the email address field during sign up
  - clearly a typo. User1 should have entered: `johnsmith111@gmail.com`
  - `User2` gets the email address verification
  - `User2` deletes the email as they did not initiate the signup

5. `User2` now tries to signup for the same service at a later time (lets say after 24 hours)
  - `User2` enters `johnsmith111@gmail.com` in the email field

#### Expected Results

- App should allow `User2` to sign up for the service

- Parse Server should `not` allow the user to reuse the email verification link after successfully signing up for the service

- Parse Server should delete the `_email_verify_token` if sign up succeeds.

#### Actual Outcome

- **App returns an ERROR saying that this `username` is taken**

- Parse Server allows the user to click on the email verification link as many times as they want `even` after the user has successfully signed up for the service

- Parse Server does not delete the `_email_verify_token` after Sign Up is successful.

### Potential solution

1. Parse Server should provide additional config variables like `allowEmailVerifyTokenToExpire` and `emailVerifyTokenValidityDuration`

2. Parse Server should default `emailVerifyTokenValidityDuration` to `1 year` for backward compatibility with existing apps
  - Developers should typically set this to 1 hour or 2 hours as a best practice

##### if `allowEmailVerifyTokenToExpire` and `verifyUserEmails` are set to `true` then

3. Parse Server should save `_email_verify_token_expires_at` in the _User class along with the `_email_verify_token` at `SignUp` time
  - `_email_verify_token_expires_at` = `currentTime` + `emailVerifyTokenValidityDuration`

4. If the user clicks on the email verification link `BEFORE` the `_email_verify_token_expires_at` then
  - update `emailVerified` to `true` in the `User` class (this code is already in place)
  - delete the `_email_verify_token` and `_email_verify_token_expires_at` fields for this user (new code)
  - respond back with a success (this code is already in place)

5. If the user clicks on the email verification link `AFTER` the `_email_verify_token_expires_at` then
  - respond back with an error: `email verification token expired.`
  - user can try again and create a new account

6. If the user completed `email verification` successfully but clicks on the link for second time then return an error message (i.e., fail gracefully)

7. Developer can also create a scheduled `clean up` job. This job can run periodically (say every 5 minutes) to do the following:
  - find users with 
    - `emailVerified` set to `false`  **(email not verified)**
    - and `_email_verify_token_expires_at` less than `current time` **(token expired)**
  -  delete the users found in the above step

### Environment Setup

- **Server**
  - parse-server version: 2.2.15
  - Operating System:     OSX
  - Hardware:             Macbook
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost

- **Database**
  - MongoDB version: 3.2.5
  - Storage engine:  N/A
  - Hardware:        Macbook
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Localhost

  - As you can see the email addresses are pretty similar to each other
  - There are many other cases where email addresses out there are similar to each other. for example: `johnsmith@gmail.com`, `john.smith@gmail.com`, `johnsmith@yahoo.com` and so on...
  - When email addresses are similar, there is chance for the users to type in the wrong email address during sign up (a honest typo)

**Comment by flovilmart** [comment]
I'm not sure about the expiration, that would may a user impersonate another one if the email is not verified. However deleting the verification token makes sense as it should be used only once.

**Comment by cherukumilli** [comment]
@flovilmart 
Email confirmation expiration is a `security feature` similar to the session expiration feature that is already implemented in parse-server. 

This new feature will be completely backward compatible. I think there is no downside to parse-server apps that are already up and running. They don't have to do any migrations, etc...

This will be a big plus for secure applications like the project I am currently working on. I will also solve the lost email verification link email, email impersonators blocking other users and others gracefully.

**Comment by flovilmart** [comment]
In that case, that should require the email to be verified for login (your previous PR) and be 'opt-in' not the default behavior when you enable email verification. What do you think?

**Comment by cherukumilli** [comment]
Yes. Totally agree. It should be completely opt-in. If the developer sets the `verifyUserEmails` to `true` then only the email verify token expiration should come into play. Otherwise, it will be business as usual.

**Comment by flovilmart** [comment]
That should be an additional flag actually. Without that, some users who don't check their emails or don't verify may be locked out....

**Comment by cherukumilli** [comment]
Got it.
How about an additional config variable called `allowEmailVerifyTokenToExpire` ?

Setting
`allowEmailVerifyTokenToExpire` to `true` will allow the email verify tokens to expire 
and setting it to `false` will skip verification of token expiration.

**Comment by flovilmart** [comment]
yes and an expiration duration maybe :)
