### ISSUE TITLE
Is there documentation on how to setup a NEW Parse project with Parse Server?

### ISSUE THREAD

**Issue by jaysonng** [ParsePlatform/parse-server#22]
Is there a guide for a blank new project where it shows how I can setup the backend settings like new user email templates, collaborators, etc. like how the webui did for Parse Backend? or would it be better to hold off and hope Parse WebUI comes out sooner than later?

I know the migration guide is there, but that guide is for existing projects. It doesn't tell me how to make new Keys that I would need like File Key, Master Key, Client Key, JavaScript Key, etc,

Any help would be appreciated.

**Comment by gfosco** [comment]
The email templates and collaborator functionality are not currently part of parse-server.  To make a new app, simply choose your own app id and master key and launch the server. Omit the file key and any javascript or client keys.

**Comment by jaysonng** [comment]
how about all the user related features like forgot password and confirm email?

**Comment by jaysonng** [comment]
also, to add, are these settings and templates in the near future plans for ParseServer? I assume these will be part of the WebUI discussion?

**Comment by Telemakhos** [comment]
> how about all the user related features like forgot password and confirm email?

We are talking about a normal Express/NodeJS app here, so you can easily add [transactional email via sendgrid](https://sendgrid.com/transactional-email) or any of the dozens of solutions out there (mandrill, mailgun, etc).

https://sendgrid.com/docs/Integrate/Code_Examples/nodejs.html

**Comment by jaysonng** [comment]
@telemakhos i see. thanks for the tip. looks like i need to read up on nodejs and Express. both of which I have no experience at yet.
