### ISSUE TITLE
Is it possible to support multiple push target?

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/parse-server#2202]
Is there a way to setup to support multiple push application in one parse server? For example, I have one server but want to p send push notification to multiple apps, like: com.company.app1, com.company.app2... ,etc ?

Thanks

**Comment by flovilmart** [comment]
As described here, you can set a configuration per bundle ID https://github.com/ParsePlatform/parse-server/wiki/Push#2-configure-parse-server

**Comment by jaimeagudo** [comment]
ATM the link is broken, have a look here https://github.com/parse-community/parse-server/issues/2188

**Comment by flovilmart** [comment]
See http://docs.parseplatform.org/parse-server/guide/#push-notifications
