### ISSUE TITLE
What happens after July 28th?

### ISSUE THREAD

**Issue by drorsun** [ParsePlatform/parse-server#2207]
The migration guide states  July 28th as a target date to migrate apps to a hosted parse server.
We have migrated one flavour of our apps to our hosted parse-server so far. We plan to migrate all users by the end of 2016.
What exactly will happen to our apps and users that are still configured to use parse.com services after July 28th?

Thanks in advance

**Comment by flovilmart** [comment]
Nothing will happen for parse-server after the 28th of july, or at least nothing bad. :)

Please use the https://parse.com/help for more informations about the future of your applications as this repository is maintained mostly by community contributors.
