### ISSUE TITLE
select keys doesn't save data on cache 

### ISSUE THREAD

**Issue by joaovq** [ParsePlatform/parse-server#2209]
Hey, 

I'm using the select keys method when retrieving data from the server. It works fine and finds the data I need but the problem is that somehow it doesn't save the data in cache with the pinAll method. So when I try to retrieve from the cache it says there is no data to retrieve. Here is the piece of code I'm talking about: 

`ParseQuery<ParseObject> query = ParseQuery.getQuery("Alambique");
        query.whereEqualTo("fabrica", FabricaRespositoryImpl.getFabrica());
        query.orderByAscending("nome");
        query.selectKeys(Arrays.asList("nome"));

        List<ParseObject> objects;
        try {
            objects = query.find();
            ParseObject.unpinAll(mLabel);
            ParseObject.pinAll(mLabel, objects);
            Log.e("Repository","Alambiques que deveriam ser salvos: " + objects.size());
        } catch (ParseException e) {
            return false;
        }`

Does anyone have any idea what the problem might be?

**Comment by flovilmart** [comment]
This is a problem with your client SDK, not parse-server. Please open on the relevant repository
