### ISSUE TITLE
how to make parse query response with  Expires  Cache-Control: max-age

### ISSUE THREAD

**Issue by Wolke** [ParsePlatform/parse-server#2211]
how to make parse query response with 
Expires  Cache-Control: max-age

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.
