### ISSUE TITLE
Cloud Code suggestion/question

### ISSUE THREAD

**Issue by kwstasna** [ParsePlatform/parse-server#2213]
Hello.
I would like to know if there is any possibility of making a Cloud Function to run each day at 1:00 PM.
I've searched through the documentations but i couldn't find anything about it.

I know it's not an issue about parse-server, but if we can't make a function to run each day at 1:00PM maybe it could be a good idea to make it happen.

Thanks a lot for your time!

**Comment by bohemima** [comment]
Simply set up a cron-job to curl/wget that function and you're good to go.

**Comment by steven-supersolid** [comment]
If you want to do this in code you can also try https://www.npmjs.com/package/node-schedule

**Comment by flovilmart** [comment]
We don't provide (yet) a job API / scheduler as it's very platform specific. As @steven-supersolid or @bohemima recumbent, there are multiple available options here to run regular jobs.
