### ISSUE TITLE
Date objects in cloud functions are not same as hosted parse

### ISSUE THREAD

**Issue by codebreach** [ParsePlatform/parse-server#2214]
I am calling a cloud function with parameters `{date: new Date()}`.

This is sent over the wire as:
```es6
{
  date: {
    __type: 'Date',
    iso: '1997-07-16T19:20:30+01:00'
  }
}
```

In the hosted parse function, the date object is untouched
```es6
Parse.Cloud.define('dateF', (request, response) => {
  console.log(request.params.date.iso);
  // Prints ISO date string
});
```

In parse-server the date object gets flattned to just the date string:
```es6
Parse.Cloud.define('dateF', (request, response) => {
  console.log(request.params.date);
  // Prints ISO date string
  // Date is now a string not an object
  console.log(request.params.date.iso);
  // ^ does not work
});
```

### Environment Setup

- **Server**
  - parse-server version: 2.2.15
  - Operating System:     Mac OS X
  - Hardware:             MBP
  - Localhost or remote server? Localhost

- **Database**
  - MongoDB version: 3.2.1
  - Storage engine:  Default
  - Hardware:        MBP
  - Localhost or remote server? Localhost

**Comment by codebreach** [comment]
Test failure:
https://github.com/drinklynk/parse-server/commit/b0d61f96585506f7940082525e34f2daa5373296

**Comment by flovilmart** [comment]
This seems to be related / opposite of https://github.com/ParsePlatform/parse-server/issues/1826

@drew-gross where should we go from here?

**Comment by drew-gross** [comment]
I think we should always be matching Parse.com behaviour, even if that behaviour is weird.

**Comment by flovilmart** [comment]
I'll add it to #2297
