### ISSUE TITLE
parse-server-gcs-adapter content type is blank

### ISSUE THREAD

**Issue by ranhsd** [ParsePlatform/parse-server#2217]
I configure google cloud storage in my parse-server. When i try to upload a new file i see this file in GCS bucket but the file content-type is blank.
after debugging it a bit i found that the file content-type is sent by the parse-server-gcs-adapter to google cloud storage nodejs module but the gcloud storage module ignore it. 

```
  options = options || {};

  var self = this;

  var gzip = options.gzip;

  var metadata = options.metadata || {};
  if (gzip) {
    metadata.contentEncoding = 'gzip';
  }
```

After investigate it a bit i found parse-server-gcs-adapter should wrap the contentType attribute inside a metadata object 
so instead of doing:

`  let params = {
    contentType: contentType || 'application/octet-stream'
  };`

you should do:

`  let params = {
    metadata: {
      contentType: contentType || 'application/octet-stream'
    }
  };`

the metadata can contain more info about the file like: content-encoding but the content-type is very important because the GCS bucket download the file instead of presenting it.

Can you please fix it? 

Thanks, 
Ran.

**Comment by flovilmart** [comment]
Please open on this repository https://github.com/parse-server-modules/parse-server-gcs-adapter

**Comment by Nisthar** [comment]
@ranhsd how to use it?
