### ISSUE TITLE
Why load all schemas during a request?

### ISSUE THREAD

**Issue by ziyadparekh** [ParsePlatform/parse-server#222]
https://github.com/ParsePlatform/parse-server/blob/master/Schema.js#L64

This will find all schemas from the _SCHEMA collection. Is there a reason to load all of them instead of the one that corresponds to the class name in the request ?

**Comment by ajamaica** [comment]
I think it is because it needs to print the json for the schema when the dashboard on the site was about to draw. If you see the actual website they print that same contents to a big template variable that the dashboard uses as base for making the data tables.

**Comment by drew-gross** [comment]
This definitely not ideal and it's something we will revisit as we continue to work on schemas.
