### ISSUE TITLE
What is the appropriate method of handling ACL while within Cloud Code?

### ISSUE THREAD

**Issue by MobileVet** [ParsePlatform/parse-server#2223]
### Issue Description

Using ACLs requires that a user is logged in to access various data.  However, Cloud Code does not really allow for a 'user'.  Attempting to 'become' a user with a passed in token produces a memory error.  This can be 'worked around' by calling enableUnsafeCurrentUser(), but is that appropriate?

How should ACL be handled when using Cloud Code?

### Steps to reproduce

  Parse.User.enableUnsafeCurrentUser();
  Parse.User.become(request.params.token).then(function(user) {
    // query requiring ACL
    var query = new Parse.Query("customObject");
    return query.find();
  }

#### Expected Results

query results

#### Actual Outcome

no results (if you leave out the 'unsafe' and 'become')

### Environment Setup

- **Server**
  - parse-server version: 2.2.15

**Comment by codebreach** [comment]
You should instead pass the sessionToken to `query.find`
So:
```es6
var query = new Parse.Query("customObject");
return query.find({sessionToken: request.params.token})
```

**Comment by MobileVet** [comment]
Thank you SO much.  Really appreciate that.

How long are the tokens valid?  Snag one and use it in the API Console?
