### ISSUE TITLE
How to configure "Content-Type" for file to be uploaded via S3Adapter?

### ISSUE THREAD

**Issue by grassland-curing-cfa** [ParsePlatform/parse-server#2224]
I have migrated my Parse hosted app to the stack of **Heroku (deployed from GitHub) + mlab + AWS S3**. The S3Adapter was set up well in the ParseServer constructor. File uploading worked well my S3 Bucket from the Parse-Dashboard deployed to Heroku.

The "Content-Type" for the uploaded file is "text/plain" by default. As there are a lot of files of mine that are PNG images, is it possible to configure the "Content-Type" to be "image/png" in the S3Adapter so that the browser is able to open the image straightaway instead of downloading as an ordinary file?

**Comment by blacha** [comment]
When you create a Parse.File you can specify what ContentType it is : 

```

**Comment by grassland-curing-cfa** [comment]
Thanks @blacha 
I am able to set up the ContentType through REST api.
