### ISSUE TITLE
Saving PFFile with ACLs

### ISSUE THREAD

**Issue by greggmojica** [ParsePlatform/parse-server#2229]
So I have a situation where I need a user to be able to upload a file (image) and then save it to an object, but the problem is that there are specific ACLs on the object that prevent a user from just uploading it. While all my other functions (which do not involved image/file uploads go through a cloud code function which uses the masterKey, I believe that I cannot pass a file to cloud code?).  If I am indeed correct about this and it is the case, then how would I go about resolving this?  Otherwise, what are the potential solutions available here? Thanks.

**Comment by flovilmart** [comment]
As this is an implementation question and not a problem related to parse-server, I'm gonna close this issue. Please use stackoverflow for that purpose

**Comment by greggmojica** [comment]
@flovilmart StackOverflow isn't the venue for this kind of question as it is a conceptual thing. Could you please provide some insight so I can resolve this?

**Comment by flovilmart** [comment]
I'd go with a 2nd object and a CloudCode beforeSave function.

```
// client side
let file = new Parse.File()
file.save().then(() => {
   let container = new Parse.Object('FileContainer');
   container.set('file', file)
   container.set('object', protectedObject)
   return container.save();
}).then(() => {
   return protectedObject.fetch();
}).then(() => {
// your protected object should have it's file
})

// cloud code:

Parse.Cloud.beforeSave('FileContainer', (req, res) => {
   let container = req.object;
   let object = container.get('object');
   let file = container.get('file');

   return obj.save({file: file}, {useMasterKey: true}).then(() => {
      res.success()
   })
});
```
