### ISSUE TITLE
Should we migrate files?

### ISSUE THREAD

**Issue by blackxored** [ParsePlatform/parse-server#223]
Should we migrating away files away from Parse's S3 bucket, or is this not necessary? If so, is there any written documentation on how to approach it?

**Comment by skinp** [comment]
At some point yes, you should migrate files away from Parse S3. We're working on a tool and documentation on how to do this. Stay tuned.

Any new files saved from running your own parse-server, are saved in your mongo instance or your own S3 bucket if you use the S3Adapter.

**Comment by kumargagan4** [comment]
Skip what needs to be done with s3adapter in this case

**Comment by kumargagan4** [comment]
Skinp@
