### ISSUE TITLE
ParseQuery always returns object of size 0.

### ISSUE THREAD

**Issue by EricSzla** [ParsePlatform/parse-server#2236]
I am trying to retrieve picture URL from parse server (stored as a string), originally I was trying to make a query using the Id, but also tried to hard code it using:
`parseQuery.whereEqualTo("firstName", "John");`
It always seems to go to the else statement of object.size() > 0 i.e. `Log.i("FD", "0002")`;

I think i've checked everything including:
- size of friendsList ( for the for loop )
- spelling, made sure that "Data", "firstName" and "John" are the same on Parse Server
- The value of friendsID.get(i)
- Tried to use findFirstInBackground instead (same issue)

Any idea what am I doing wrong, or what may be causing it ?
Thanks a lot.

### The code
```
public void pictureQuery() {
    friendsPic = new ArrayList<>();
    for (int i = 0; i < friendsList.length(); i++) {
        ParseQuery parseQuery = ParseQuery.getQuery("Data");
        parseQuery.whereEqualTo("firstName", "John");
        //parseQuery.whereEqualTo("userId",friendsID.get(i));
        parseQuery.findInBackground(new FindCallback<ParseObject>() {
            @Override
            public void done(List<ParseObject> objects, ParseException e) {
                if (e == null) {
                    if (objects.size() > 0) {
                        String link = objects.get(0).get("picUrl").toString();
                        Bitmap bitmap = null;
                        try {
                            bitmap = task.execute(link).get();
                            friendsPic.add(bitmap);
                        } catch (Exception e1) {
                            e1.printStackTrace();
                        }
                        Log.i("FDA, done", friendsPic.toString());
                    } else {
                        Log.i("FD", "0002");
                    }
                } else {
                    e.printStackTrace();
                }
            }
        });
    }

}
```

**Comment by drew-gross** [comment]
To help us debug this, can you include the exact request and response in Parse Server? (you can see this in the logs using `VERBOSE=1` environment variable)

**Comment by EricSzla** [comment]
Hey, thanks for the reply ! 
I have fixed the issue by deleting the class on parse server and by making a new one with the same name. 
Unfortunately I am unable to reproduce the issue this time, so I can't give you any more information about what exactly have happened.
