### ISSUE TITLE
parse-server doesn't try to reconnect to Mongo after losing connection

### ISSUE THREAD

**Issue by yuzeh** [ParsePlatform/parse-server#2239]
Describe your issue in as much detail as possible.

When my parse-server loses connection to Mongo, there is no attempt to reconnect.

The following stack trace happens whenever the server loses connection to my mongodb instance:

```
error: Uncaught internal server error. { [MongoError: no connection available for operation]
  name: 'MongoError',
  message: 'no connection available for operation',
  driver: true } MongoError: no connection available for operation
    at Function.MongoError.create (/home/dan/Dropbox (MTailor)/workspace/cloudcode/node_modules/parse-server/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)
    at Store.flush (/home/dan/Dropbox (MTailor)/workspace/cloudcode/node_modules/parse-server/node_modules/mongodb/lib/topology_base.js:68:43)
    at destroyHandler (/home/dan/Dropbox (MTailor)/workspace/cloudcode/node_modules/parse-server/node_modules/mongodb/lib/server.js:253:18)
    at g (events.js:260:16)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at Server.destroy (/home/dan/Dropbox (MTailor)/workspace/cloudcode/node_modules/parse-server/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1117:24)
    at reconnectServer (/home/dan/Dropbox (MTailor)/workspace/cloudcode/node_modules/parse-server/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:272:17)
    at null._onTimeout (/home/dan/Dropbox (MTailor)/workspace/cloudcode/node_modules/parse-server/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:254:11)
    at Timer.listOnTimeout (timers.js:92:15)
```

Subsequent requests to the parse-server fail with this message:
```
{"code":100,"message":"XMLHttpRequest failed: \"Unable to connect to the Parse API\""}
```

The only remedy is to restart the server.

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1. Start parse-server locally, pointed to a remote mongodb instance.
2. Disconnect your local machine from the internet.
3. Issue any REST API command that requires usage of mongodb.
4. Wait until the first stacktrace is printed in your logs.
5. Reconnect local machine to the internet.
6. Try issuing another request that requires mongodb.

#### Expected Results

Connection reobtained eventually.

#### Actual Outcome

It's been an hour. (A quick glance at the most recent code suggests there is no reconnect logic in parse-server).

### Environment Setup

- **Server**
  - parse-server version: 2.2.10
  - Operating System:     Ubuntu 12.04
  - Hardware:             Desktop
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: 3.0.10
  - Storage engine:  MMAPv1
  - Hardware:        N/A
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): remote (AWS via mLab)

**Comment by yuzeh** [comment]
Looks like the issue is that the mongodb driver by default gives up after 30 seconds with no successful connection to the server: http://mongodb.github.io/node-mongodb-native/2.1/api/Server.html

Has there been a discussion on best practices, operationally, for dealing with these sorts of issues? In our setup, we'd only find out about these issues after our Nginx frontend reports elevated timeout rates, but should there be a better way to report this within parse-server itself?

**Comment by yuzeh** [comment]
Closing because I just realized MongoDB options are configurable from parse-server. :smile_cat:

**Comment by dvanwinkle** [comment]
@yuzeh I'm having the same issue, what are the configuration parameters that helped you?

**Comment by yuzeh** [comment]
On 2.2.16:

```
  databaseOptions: {
    server: {
      reconnectInterval: 2000,
      reconnectTries: 300000,
    },
  },
```

On 2.2.17, I'd bump down reconnectTries to like 30 (if you want 60s of retrying) or 15 if you want 30s of retrying, etc. There was a bug in 2.2.16 that made reconnectTries not be interpreted in the right way.

But I'd still test this...

**Comment by Code-Crash** [comment]
@yuzeh Where should I write this databaseOptions?

**Comment by yuzeh** [comment]
When creating the parse-server, see: https://github.com/ParsePlatform/parse-server/blob/2fb4f8932424657bc6c26368c17f05ca623fe8ac/src/ParseServer.js#L108

**Comment by Code-Crash** [comment]
@yuzeh My Database connections is getting lost whenever I restart my server, I though this is session issue, but I think so it is not. After restart when I query the database, I'm not able to fetch results and there is no error.
