### ISSUE TITLE
Login with authData

### ISSUE THREAD

**Issue by kajensen** [ParsePlatform/parse-server#2240]
How would one login with authData with oauth token retrieved on the web client of a node js express app? For something like iOS this is simple to do with the logInWithAuthType() method, but how would one do the same directly server side?

Basically, I would like the same method available for javascript, but I wasn't sure if there was another way. Thanks

**Comment by acegreen** [comment]
This is not an issue, it's a SO question. At least until it's determined that it can't be done or needs to be

**Comment by flovilmart** [comment]
Server side Oauth token négociation is not handled by parse-server. We allow using tokens for validating a user identity against a provider like Facebook, twitter etc... 

You need to acquire a token by yourself, using a client library or a server library, then provide that token to your user and complete the login process using the helper functions provided by the client SDK or node SDK on the server.

**Comment by acegreen** [comment]
@flovilmart  on a side note, I would love it if you could take a look at this:

https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/954

Note: it may need to be moved to the parse-server repo issues
