### ISSUE TITLE
ObjectId not generated

### ISSUE THREAD

**Issue by scasaregola** [ParsePlatform/parse-server#2250]
Hello all, 

i have a locally instance parse server.
I try to create a new user, but it seems my parse server doesn't create object id.

Here is a example : 
Object create with the new server
`
{ "_id" : "bwbOBDuu7Y", "_rperm" : [ "`

Object from the data from parse.com

`{ "_id" : ObjectId("575ab851f58be03039c5fd91"), "`

The _id fields is not the same at all. 

I see this issue https://github.com/ParsePlatform/parse-server/issues/721 but i have no error in my log

Thx for your help

**Comment by flovilmart** [comment]
can you run with VERBOSE=1 to dig deeper in your errors?

**Comment by flovilmart** [comment]
Please update to latest version and reopen the issue if it persists
