### ISSUE TITLE
Parse Push Documentation Questions

### ISSUE THREAD

**Issue by StuartMorris0** [ParsePlatform/parse-server#2251]
Hello,

I am reviewing the wiki page for parse push and have a couple of questions:
https://github.com/ParsePlatform/Parse-Server/wiki/Push

> 
> However, there are a few caveats:
> Does not support super high throughput since it does not employ a job queue system

Please confirm what this means in a more detail? What amount of pushes could be sent until it is considered super high throughput?

Further to this, within the API section of the document:

> Here is the list of sending options we do not support yet:
> ...
> Increment badge under data for iOS badge number

Does this mean a push notification send to an iOS device from CloudCode(Parse Server) would not increment the badge number on the client device?

Thank you.

**Comment by sprabs** [comment]
increment should work fine. I think that information hasn't been updated in a while.

**Comment by StuartMorris0** [comment]
@sprabs Thanks, so what about the super high throughput?

**Comment by flovilmart** [comment]
The amount depends on your server hardware configuration. Think of it as a loop that goes through all the found devices and then try to deliver the push.

**Comment by StuartMorris0** [comment]
@flovilmart Thanks. I was reading it as it does not queue when sending a bunch of different pushes, but from what you are saying the issues are when sending from 1:many.

So just to be clear, we are looking for lets say 50,000 different users sending a push to one user each potentially within the same time block of 10 minutes. Would there be an issue there or would you recommend using a third party like One Signal and using their parse push adapter?

**Comment by flovilmart** [comment]
the bottleneck is on the installations query. So no matter what adapter you use, that may be problematic. if your query only returns 1 installation you should be fine IMHO. The best way to know is to closely monitor the logs and give it a go

**Comment by StuartMorris0** [comment]
@flovilmart Thanks that makes perfect sense. Is the issue with the installation query just the time it takes to return?

Furthermore what is actually meant by this statement "Does not support super high throughput since it does not employ a job queue system"

**Comment by flovilmart** [comment]
Complexity in time and space. Each push is delivered to APNS at once, consecutively, the more installations thé longer it takes

**Comment by StuartMorris0** [comment]
@flovilmart

**Comment by StuartMorris0** [comment]
@flovilmart Unless you want this open to update the wiki...

**Comment by sprabs** [comment]
@flovilmart What's the difference between the way pushes are delivered through parse server v. parse.com?

**Comment by sprabs** [comment]
@StuartMorris0 are you seeing issues with push notifications on Parse Server (in terms of compatibility with clients on parse.com)? 

I created this issue here that should affect everyone migrating: https://github.com/ParsePlatform/parse-server/issues/2275

**Comment by flovilmart** [comment]
@StuartMorris0 I'll be closing that one, as we have other issues open for improving the push notification batching, scheduling.
