### ISSUE TITLE
Weird excessive collections/tables created after database migration to mLab

### ISSUE THREAD

**Issue by grassland-curing-cfa** [ParsePlatform/parse-server#2267]
I have migrated and finalized my database from Parse to mLab,

A number of collections starting with "_" were created when I went to check my mLab hosted database that was transferred over.
![collections_mlab](https://cloud.githubusercontent.com/assets/17244571/16792084/4fb4a392-4908-11e6-9d69-cec0c05205e6.jpg)
.

I have no idea where those collections come from, especially "_Cardinality", "_dummy" and "_Index". Are those redundant collections and can I remove them from mLab?

Another question is about the "_Session" collection. It seems that two new items are added to this collection when a user is successfully logged in and a token is returned. Is it managed automatically by the Parse-Server or do we have to manage all sessions manually by ourselves?

**Comment by Abderezai** [comment]
I suggest to install the dashboard application and see if things look "normal". Parse and Heroku abstract a lot of details to simplify your backend management. Have you migrated your cloud code? If so then try viewing your code via dashboard.

**Comment by steven-supersolid** [comment]
I wouldn't remove any collections that start with _ unless you are 100% sure they are not used by parse-server, the open source dashboard or Parse.com dashboard. They are quite small so disk space should not be an issue. If you do figure it out what each does then it would be really useful if you could update the wiki.

One thing you could try is deploy a new app in an empty database and see what gets created when you run your app and when you run the dashboard.

I think only one _Session document should be created per user/device combo so may be worth looking in to why you have two as this could be a bug. Session handling is done by parse-server so as said above you only need to configure expiration settings.

**Comment by hramos** [comment]
I'm closing out this issue as it is not related to Parse Server. For migration tool issues assistance, please file a bug report at https://parse.com/help#report
