### ISSUE TITLE
Swift: Linking Facebook users with existing PFUsers Not Working on Parse Server

### ISSUE THREAD

**Issue by dnadri** [ParsePlatform/parse-server#2272]
### Issue Description

I'm trying to integrate the Facebook login/signup into my app to work alongside the standard login/signup with email. I am using Swift and have migrated to MongoDB + Parse Server (deployed on Heroku).

I've followed the [Parse iOS guide on Facebook Users](https://parse.com/docs/ios/guide#users-facebook-users). However, with Parse Server, the Facebook integration isn't working normally according to all the tutorials and documentation out there. I have already looked for a solution to this issue on Stackoverflow and others ([original SO post](http://stackoverflow.com/questions/38317999/swift-linking-facebook-users-with-existing-pfusers-not-working-on-parse-server)).

**1. How can I link existing `PFUser`s with their Facebook accounts when they log in with Facebook in the app?**  

I am using the Swift code from [this section of the guide](https://parse.com/docs/ios/guide#users-linking) to associate an existing `PFUser` to a Facebook account (see code below), however, this code is not executing and therefore is not linking a users existing account they created through the email sign up with their Facebook account which has the same email.

The `isLinkedWithUser` method seems to require that the user be logged in. However, when a user is signed out/just downloaded the app, the `PFUser.currentUser()` is `nil` because the user is not logged in. _Therefore, the `linkUserInBackground` method won't know which `PFUser` to link the Facebook account with_. I believe these methods are now useless at least this case because they are meant to link _after the fact_ (after they log in). But I don't want to create two users even if I handle this situation afterwards. 

**2. Is there a Cloud Code example or other Swift logic to accomplish this?**
**3. Has Parse addressed this issue? Should the developers use the official Facebook SDK for Facebook login? If so, how can they link existing `PFUser`s to their Facebook accounts during Facebook login?**

Thank you in advance for your time and patience. I greatly appreciate any help!

### Code

    func fbLoginButtonTapped() {

    let permissions = ["public_profile", "email"]
    PFFacebookUtils.logInInBackgroundWithReadPermissions(permissions, block: {
        (user: PFUser?, error: NSError?) -> Void in

        if let user = user {
            if user.isNew {
                print("User signed up and logged in through Facebook!")
            } else {
                print("User logged in through Facebook!")

                // This API doesn't seem to be working with Parse Server
                if !PFFacebookUtils.isLinkedWithUser(PFUser.currentUser()) {
                    PFFacebookUtils.linkUserInBackground(PFUser.currentUser(), withReadPermissions: nil, block: {
                        (succeeded: Bool?, error: NSError?) -> Void in
                        if error == nil {
                            print("Woohoo, the user is linked with Facebook!")
                        } else {
                            print("User is not linked with Facebook.")
                        }
                    })
                }

                dispatch_async(dispatch_get_main_queue(), { () -> Void in
                    let viewController = UIStoryboard(name: "Main", bundle: nil).instantiateViewControllerWithIdentifier("HomeNavigationController") as! UINavigationController
                    self.presentViewController(viewController, animated: true, completion: nil)
                })

            }
        } else {
            print("User cancelled the Facebook login.")
        }           

    }

#### Expected Results

Link an existing `PFUser` to a Facebook account during Facebook login.

#### Actual Outcome

No linking of Facebook user to existing PFUser even if the emails are the same. Two PFUsers with the same email exist, only the Facebook user has a randomly generated username (etc) because this part hasn't been implemented yet.

### Environment Setup

- **Server**
Parse Server deployed on Heroku.

- **Database**
mLab MongoDB.

**Comment by flovilmart** [comment]
Linking is reserved for usage when you have an existing user. This existing user can have signup with email (`signup`), or with twitter, or anonymous thought the `login` methods.

If you call `login` with Facebook or Twitter utils, that will discard the current user and effectively create a new user if it doesn't exist, based on the id provided by Facebook or twitter. If the user exists in the DB, based on the Facebook id or twitter id, this user will be logged in and available through `PFUser.currentUser()`.

For what you want to achieve, you have multiple options:

1. make sure the user is signed up through email before calling loginWithFacebook. If the user is logged in with the email, you can call link, in order to allow the user to use both authentication methods (Facebook and email). Repeat with twitter and other configured methods.

2. If users come into your app with a Facebook login, use the loginWithFacebook method and then prompt to set an email and a password and save that user.

3. if the user is effectively logged out and uses Facebook, then logs out and uses twitter, and you want to reconcile those accounts, you need to do it manually. That usually involves moving the authData from each account to a centralized on. Reset ACL's on all objects owned by the wrong accounts etc... And finally delete the users, and sessions. Next time the user will want to use your app, you want to have a mechanism to prompt for login again if you merged the authentication data on an account that is currently not logged in on the device. To sum up, that is a highly custom behaviour.

> Why don't we link on email automatically?
 Because the email without the password is unsafe and can't be trusted. An attacker with a valid Facebook account could impersonate any user, allowing them to link just by providing the email.

**Comment by dnadri** [comment]
@flovilmart I emailed you...

**Comment by dnadri** [comment]
@flovilmart Did you receive my email? I would like to clarify a few things in regards to this issue.

**Comment by flovilmart** [comment]
If there is more things to clarify, this discussion should happen on github and not in private.

**Comment by dnadri** [comment]
Thanks for getting back. @flovilmart, @drew-gross or anyone else familiar with this topic:

1. If linking is reserved for usage when you have an existing user, is there another way to link Facebook login users to their existing accounts created via email sign up when the existing user is **not** logged in?

2. > If you call login with Facebook or Twitter utils, that will discard the current user and effectively create a new user if it doesn't exist, based on the id provided by Facebook or twitter.

    By "doesn't exist", are you only referring to a Facebook account that doesn't exist? If so, what about a PFUser account that exists from email sign up? In this case, I believe you are saying that even if a user has created an account via email sign up, a new user will be created via Facebook login even if the email used with email sign up and Facebook login are the same, correct?
If so, this is not what I want to achieve. I **don't** want the `PFFacebookUtils.logInInBackgroundWithReadPermissions` call to create a new a new user if this is the case. This leads back to my first question (1.)

3. > make sure the user is signed up through email before calling loginWithFacebook.

    a) How does one make sure the user is signed up through email?
    b) By "loginWithFacebook", are you referring to the `PFFacebookUtils.logInInBackgroundWithReadPermissions` method? 

    c) 
    > If the user is logged in with the email, you can call link, in order to allow the user to use both authentication methods (Facebook and email).
    
    Correct, I understand that linking can be done after-the-fact (once user is logged in). However, my goal is to achieve linking before the user is logged in (when they are on the login/sign up page) of the app.

4. > If users come into your app with a Facebook login, use the loginWithFacebook method and then prompt to set an email and a password and save that user.

    One of the benefits of Facebook login is that users don't have to set an email and password - it uses their Facebook credentials to seamlessly verify and login users. I already have the user entering their email and password during regular email sign up.

5. > if the user is effectively logged out and uses Facebook, then logs out and uses twitter, and you want to reconcile those accounts, you need to do it manually.

**Note:** The app will not be using Twitter login integration. Only Facebook login integration, alongside regular email sign up.
Clarification: If the user has created an account before using regular email sign up, is logged out, and then uses Facebook the next time to login, I want to reconcile _those two Facebook and regular email accounts_. 
**How can I achieve _this_ manually?**

Example: Here's a screenshot of two users, Facebook login user (on top) and regular email sign up user (on bottom), with the same email (even though the Facebook user's `email` field is "(undefined)"...I did not implement code to set this information for Facebook users yet).
![facebookandemailuseraccounts](https://cloud.githubusercontent.com/assets/4001546/16853327/f43d7aca-49d9-11e6-87b4-30f961c28731.png)

**Summary:**
Ultimately, my goal is to have the following login/sign up flow when a user taps the Facebook login button _while logged out or for their first time ever:_
- If the user _is a new user_ (where no account with the given email exists - whether through email sign up _or_ Facebook login), sign up the user via Facebook login (create a new account);
- If the user is _**not** a new user_ (an account with the given email already exists - whether through email sign up _or_ Facebook login), log in the user via Facebook login. However, if the account which already exists was created through email sign up, link the existing email sign up account with the user's Facebook account that was just logged in with (or update the existing email sign up account with the user's Facebook profile information retrieved from a Graph request);
- Otherwise, cancel the login (do not create a new user). 

I am very thankful for your time and assistance in trying to resolve this issue.

**Comment by LamourBt** [comment]
@flovilmart my problem is that `logInInBackgroundWithReadPermissions` the callback `user:PFUser?` it is always nil so I am unable to save the user into Parse server. 

check it out my code here: https://gist.github.com/LamourBt/130e5d2479893fef8d83b45ede7655f2

Also when I don't check if the user.isNew, I have access to the user info but still was not successful to save it to Parse 

In parse-server (latest version), I tried to set up facebook app id in two different ways:
 `facebookAppIds: [process.env.FACEBOOK_APP_ID]`
second way: 
`oauth: {`
    `facebook: {`
             `appIds:[process.env.FACEBOOK_APP_ID] `
   `}`
` }`

**Comment by dnadri** [comment]
@flovilmart Would appreciate your response to my last comment when you get a chance. Thank you!

**Comment by flovilmart** [comment]
@dnadri I believe you should get your answer on stackoverflow as it's clearly not an issue with parse-server but an implementation detail.

We have no plan to implement this kind of feature anytime soon, but if you're willing to contribute a solution, feel free to open a pull request.

**Comment by acegreen** [comment]
@dnadri did you find a solution to this? If so, could you post it for reference?
