### ISSUE TITLE
Parse's Current Hosting Service Are Keep Reporting Errors

### ISSUE THREAD

**Issue by fans3210** [ParsePlatform/parse-server#2277]
We have began to use parse server for new mobile app. But we are still keeping the old mobile app which was developed a few years ago using parse hosting service. We hope it to work until next Jan. 

For the recent few months, I found that the old IOS app cannot even successfully send a simple query. Eg: For loading a user list, the app always failed to load the list. Sometimes when I was lucky enough, it might succeed. The error message I got is always something like:

{"code":141,"message":"{\"code\":105,\"message\":\"invalid field name: _t\"}"} (Code: 141, Version: 1.7.1)

{"code":141,"message":"{\"code\":105,\"message\":\"invalid field name: $err\"}"} (Code: 141, Version: 1.7.1)
I can confirm that the field name is valid because the app works well a few months ago. Is there any performance downgrade for the parse hosting service? I understand the situation but cannot help wondering why my old app doesn't work well since 1-2 months ago. There is also no blog or article discussed about the current status parse hosting service. I would be very appreciated if you could clear some of my doubts. Thanks.

**Comment by hramos** [comment]
Closing as this is not a Parse Server issue.

While the parse.com service will continue responding to requests until January 2017, all apps should have migrated to a self-hosted database three months ago (April 28), and should release an update that uses Parse Server or another service by July 28 (two weeks from today). The parse.com API server will be kept around until January to handle any stragglers (users that haven't updated their app to your new non-Parse.com version), but you shouldn't count on parse.com to handle your full production traffic once the July 28 deadline passes.
