### ISSUE TITLE
Push Open num is always N/A.

### ISSUE THREAD

**Issue by shiguofu2012** [ParsePlatform/parse-server#2278]
Push Open num is always N/A, 
![image](https://cloud.githubusercontent.com/assets/9302729/16831131/ccfeeec0-49d5-11e6-82bf-29560bf9f807.png)
So I update the record in mongodb, but nothing is changed.
![image](https://cloud.githubusercontent.com/assets/9302729/16831929/5d099732-49da-11e6-8dd8-4580bda5024f.png)
Do I modify the right column?

**Comment by mohammed1ali** [comment]
It may be because "Delivery reports are not supported"
Check as given [here](https://github.com/ParsePlatform/parse-server/wiki/Push#push-overview)

**Comment by hramos** [comment]
This doesn't look like a Parse Server issue. If you're using Parse Dashboard, open an issue at https://github.com/parseplatform/parse-dashboard.
