### ISSUE TITLE
oauth with Digits

### ISSUE THREAD

**Issue by ranhsd** [ParsePlatform/parse-server#2280]
Hi ,
 twitter Digits provide **password-free** login for mobile apps.  One of the coolest feature of parse-server is to allow users to login with 3rd party providers like: twitter, facebook, instegram etc. 
I just wanted to inform you that it is possible to use twitter oauth provider also with Digits. 
In order to test it please do the following: 
 
1. Configure twitter provider but use the consumer key and consumer secret of Digits taken from your fabric dashboard - [https://fabric.io](url)
2. Create a simple iOS client with the following code: 

```
    [[Digits sharedInstance] authenticateWithViewController:nil configuration:configuration completion:^(DGTSession *session, NSError *error) {
        if (error) {
            return;
        }
       
        [PFUser registerAuthenticationDelegate:self forAuthType:@"twitter"];

        
        [[PFUser logInWithAuthTypeInBackground:@"twitter" authData:@{@"auth_token" : session.authToken,@"auth_token_secret" : session.authTokenSecret,@"id" : session.userID}] continueWithBlock:^id _Nullable(BFTask<__kindof PFUser *> * _Nonnull task) {
            
            if (task.error){
                NSLog(@"error occured %@",task.error);
            }
            
            return nil;
        }];
```
        

The code above do the following: 

- authenticate the user (only by his phone number... no password is required)
- Register authentication delegate for the parse user
- Log in with twitter and send the token, secret token and id of the **Digit**  user.

The digit session also return the user phone number so you can also store the user phone number in the DB.

This way you can allow your users to login with their phone numbers only (password-free) 

BTW,  if you have multiple apps and you want to provide one login so user will not need to fill in his/her profile each time they signed up  you can use AWS **Cognito** for that. I tried it and it works great with Parse Server. 
More details about it can be found here: [http://docs.aws.amazon.com/cognito/latest/developerguide/twitter.html](url)

**Comment by flovilmart** [comment]
We could definitely add digit as an auth provider

**Comment by hasso92** [comment]
I have cloud Code functions that handle that, I can provide it once I'm
home, so far it's working with no issues at all.

Am Donnerstag, 14. Juli 2016 schrieb Florent Vilmart :

**Comment by ranhsd** [comment]
Hi @hasso92, 
Until now I use cloud for authenticate the users but I think it's better to use provider in order to go with the "standard way"

@flovilmart - we can use the same code line of the Twitter provider but change only the provider name to digits. In this way developers will be able to provide 2 authentication login , with digits or with Twitter... What do you think ?

**Comment by flovilmart** [comment]
@ranhsd I was thinking about that actually

**Comment by ranhsd** [comment]
@flovilmart - great solution .. I will test it and do a pull request (unless you already did it ;) )

**Comment by flovilmart** [comment]
go for it, test it  :)

**Comment by flovilmart** [comment]
Closing as it's been merged
