### ISSUE TITLE
LokiJS cache adapter

### ISSUE THREAD

**Issue by ranhsd** [ParsePlatform/parse-server#2285]
LokiJS provide document oriented in-memory database. 
I was thinking maybe parse-server can provide cache adapter that will use LokiJS to store and retrieve objects which are stored in-memory.  

The question is if the cache adapter is configurable (like email, push etc.) or not? I didn't find something about it in the Wiki but i think that technically it is possible.

**Comment by lifeisfunny** [comment]
Yes Its is Possible! However Cache Does make sense to put on the DataBase level instead on the the Server its self. otherwise memory allocation would be a huge issue

**Comment by lifeisfunny** [comment]
I was not aware that Parse Server now supporting App config  ,My bad(I am still trying to figure out why my push notification not working in the cloud code afterSave Block T_T).  
In that case that Does make sense 👍  
But its such a small data set , how big of performance increase are we talking about?

**Comment by ranhsd** [comment]
Yes it is small data set but think about apps with hundreds of thousands of users. each time the user open the app it is execute a request to download the app config (I assume that the config can be changed from time to time by the parse-server owner otherwise it has no meaning :) ) 
so instead of access the database it get the data from the cache. 
i totally agree that for apps which serve low amount of users it is not critical but for apps with a lot of users it is.

**Comment by lifeisfunny** [comment]
Would it make more sense to Create a version number of the config setup and cache it on device ??

**Comment by ranhsd** [comment]
yes it is and this is what i am doing in my app but also my app contains what's called "feature toggle" which allow me to turn on/off features according to the app config values. but app config is not the only reason we need cache there are more.

**Comment by lifeisfunny** [comment]
Interesting  !

**Comment by blacha** [comment]
The cache adaptor can be configured when you start the server, it is designed for short term caching of objects that are commonly queried from the database, ie objects that were queried multiple per request.

It is used primarily for user Sessions and Roles, It by default has a very short TTL (5 seconds).

The cache adaptor was designed to be eventually backed by Redis or Memecahced so multiple instances of ParseServer (Multiple machines running the same app sharing the same database) can all share the same cache, which would enable longer term caching (TTL of 1 minute or more).
The primary reason the cache TTL is soo low, is to prevent inconsistencies when a server modifies some user's session or role, the other servers will have at most 5 seconds of inconsistent data in their caches.

I don't think the cache adaptor really needs to be backed by something as sophisticated as LokiJS, as its generally easier and less error prone to go back to the DB for those more complicated queries.

But if you want to use it that way, the cache adaptor API  is found [here](https://github.com/ParsePlatform/parse-server/blob/master/src/Adapters/Cache/CacheAdapter.js)

Which can then be configured into ParseServer at startup:

```javascript
new ParseServer({ 
    appId: 'some-app',
    masterKey: 'some-master-key',
    cacheAdapter: YourLokiJSCacheAdapterHere
})
```

**Comment by lifeisfunny** [comment]
huh. Now I see.    I gonna take a look after this week when I publish my app.

**Comment by ranhsd** [comment]
@blacha thanks for the info. i will close this topic for now since i don't see a reason to implement it now.

**Comment by lifeisfunny** [comment]
@ranhsd  Don't give up yet  , I think there is other way to do it config cache after getting the data directly from mongoldb
