### ISSUE TITLE
includeKeys finds objects with "_id" such as "GXfPsUEViG", but not ObjectId("GXfPsUEViG”)

### ISSUE THREAD

**Issue by p-sun** [ParsePlatform/parse-server#2289]
With the iOS Parse CocoaPod, I can use **query.getFirstObjectInBackgroundWithBlock** to find objects by objectId, whether that "_id" is "GXfPsUEViG" or ObjectId("GXfPsUEViG”).

```
let query = PFQuery(className: "Address")
query.whereKey("objectId", equalTo: objectId)
query.getFirstObjectInBackgroundWithBlock { ... }
```

However, **query.includeKeys** only returns objects with objectId in the format of "GXfPsUEViG", but not ObjectId("GXfPsUEViG”).

### Environment Setup
**Client**
- CocoaPod: Parse 1.13.0

**Server**
- parse-server version: 2.2.13
- Operating System: OS X El Capitan
- Localhost or remote server: Heroku

**Database**
- MongoDB version: 3.0.9 
- Storage engine: MMAPv1
- Hardware: NUMA
- Localhost or remote server: mLab

**Comment by ranhsd** [comment]
If you want to fetch object by objectId it's better to use (in objective-c)

```
    PFQuery *q = [PFQuery queryWithClassName:@"SomeClassName"];
    [q includeKey:@"includeOtherClass"];
    [q getObjectInBackgroundWithId:@"{your_object_id}" block:^(PFObject * _Nullable object, NSError * _Nullable error) {
        
    }];
```

**Comment by hramos** [comment]
I noticed you were using an old version of Parse Server when you reported this issue. Can you take a look and see if this is still happening in the latest version?

**Comment by flovilmart** [comment]
I'M not sure why you would have native ObjectId("GXfPsUEViG”) mongo objects in your DB, all id's should be just plain strings.

**Comment by p-sun** [comment]
@flovilmart Parse creates objectId that are plain strings. RoboMongo and the mongoimport command creates objectId in the format of "_id" : ObjectId("56fd358732509beaf9fa7bdd").

**Comment by flovilmart** [comment]
There is no plan to support those ObjectId at the momen.as you're importing data without the SDK's, you may also face discrepancies in other data types like ACL etc... if you wanna keep using those importer you should probably force the objectId on them to be a string.

**Comment by p-sun** [comment]
getFirstObjectInBackgroundWithBlock supports those kind of ObjectId... Wouldn't it be nice to support it for consistency?

Yes, I did end up using that workaround for importing.

**Comment by flovilmart** [comment]
`getFirstObjectInBackground` Would support anything as there is no constraint on the objectId.
