### ISSUE TITLE
Cloud Code query not returning an instance of my subclass

### ISSUE THREAD

**Issue by bourquep** [ParsePlatform/parse-server#229]
All my models are defined like so:

```javascript
var School = Parse.Object.extend("School", 
{ // Instance methods
    doSomething: function() {}
},
{ // Class methods
});
```

I construct my queries like so:

```javascript
var query = new Parse.Query(School);
query.equalTo(...);
query.first().then(function(s) {
    console.dir(s);
    s.doSomething();
});
```

In my cloud code running on the Parse backend, this query returns an instance of my `School` subclass, and I can invoke `doSomething()` on it.

In the same code running on parse-server, the query returns what looks like an abstract object, and invoking `doSomething()` fails with `School.doSomething is not a function`.

The output of `console.dir(s)` is:

```javascript
ParseObject {
  _objCount: 0,
  className: 'School',
  id: 'kC9xAgytAM' }
```

Is there something I need to do to make parse-server use my subclasses when returning objects from queries, or is this a bug?

**Comment by bourquep** [comment]
Some additional info: if do the same query in a separate client node process (using the latest JS Parse SDK and connecting to my localhost parse server), I do get back a `ParseObjectSubclass`, and I am able to call `doSomething()` on the returned object.

So this only happens when performing a query from Cloud Code hosted in parse-backend.

**Comment by bourquep** [comment]
If I import the "real" (?) Parse SDK in my Cloud Code module, and use that import's `Query` class, then I get back the intended result (a `ParseObjectSubclass`).

However, for some reason, I cannot simply do:

```javascript
var Parse = require('parse/node').Parse;
```

Because this gives this runtime error: `Parse.Cloud.define is not a function`.

So I have to do this:

```javascript
var ParseSDK = require('parse/node').Parse;
ParseSDK.initialize('redacted', 'redacted');
ParseSDK.serverURL = 'http://localhost:5000/parse'

var query = new ParseSDK.Query(School);
```

But this doesn't feel right at all...

**Comment by bourquep** [comment]
I have moved all my business logic functions into a separate module, which exports functions that are called by my Cloud Functions.

This allows me to `require('parse/node')` without errors.

However, whenever I try to use the Parse module (e.g. perform a query), I get this error:

>You need to call Parse.initialize before using Parse.

Which leads me to believing that if I do have to call `Parse.initialize`, it means that whenever I run a query _from within cloud code_ it performs an HTTP request to my parse-server to actually run the query... Is that the case?

I'm a little confused about how the Parse SDK behaves when used within Cloud Code...

**Comment by maysale01** [comment]
Yes, Cloud Code is essentially just functions that are being called without any special context. If you're using the parse/node library from Cloud Code it's going to behave as it would in any other context. What you're probably wanting to do is access the ParseServer context from the req parameter passed in.

**Comment by bourquep** [comment]
>access the ParseServer context from the req parameter passed in

Care to elaborate on this? The only context that I see is:

```javascript
{
    params: req.body || {},
    master: req.auth && req.auth.isMaster,
    user: req.auth && req.auth.user,
}
```

**Comment by bourquep** [comment]
I have just updated to the latest HEAD (by doing `npm install --save git+git@github.com:ParsePlatform/parse-server.git`), and all of these issues went away:

- Doing a Query from within a Cloud Function properly returns a parse object subclass
- I no longer need to call `Parse.initialize` when using the Parse SDK

Looks like commit a65f2d13abdc9d4663d61308f426dd517491c9ee might be involved in resolving these issues.

**Comment by maysale01** [comment]
@bourquep Currently the ParseServer context isn't be passed in to the req. I have done it in a few forks of mine, but haven't merged in with this branch. I'm not sure what exactly changed for your code to start working. If the Parse global was being initialized in `index.js` before your cloud code gets included via `require()` it should've already been working.

**Comment by bourquep** [comment]
Well, not sure why it was not working and why it is now, but one thing's for sure is all I did was update parse-server to the latest HEAD (I was initially using v2.0.6).

**Comment by gfpacheco** [comment]
Hi, I also can't get my custom subclass when `fetch`ing, `find`ing or even `createWithoutData`ing outside Parse Cloud Code.

Using bourquep's example, when I call `s.doSomething` inside Parse Cloud Code everything runs just fine. When calling it from simple express route handler it doesn't.

Any ideas of why it doesn't work? And what should I do to make it work (besides moving to Cloud Code).
