### ISSUE TITLE
Transfer live data to new Parse Server

### ISSUE THREAD

**Issue by dcdspace** [ParsePlatform/parse-server#230]
After I have my own Parse Server up and running, how do I sync that back up with the live app on the App Store? I get it that I snapshot the database to migrate it over to MongoLab, but what about all the changes that occur from that time up until the new version is ready? How do I ensure no data is lost from the snapshot date until when the user downloads the new version? Thanks.

**Comment by christianmarth** [comment]
From https://parse.com/docs/server/guide#migrating


> The tool first takes a snapshot of your existing data and transfers it to MongoDB. Next, it will pause to allow manual verification, while continuing to keep things in sync with writes that are coming in from your live app. While you are in this state, your app continues to read and write from your Parse hosted database.
> 
> Connect to your Mongo instance and browse through the collections in the newly created database. Check the collection counts and do a few spot checks to ensure that your data was migrated successfully.
> 
> Once you're satisfied, you can finalize the transfer in the migration UI and your app will be using the new MongoDB instance. At this point, your app is still hitting api.parse.com, but is using your MongoDB instance. You will need to administrate your database instance yourself, including maintaining indexes and scaling up.

Basically once you've finalised the migration in the parse.com UI all new data hitting the parse API will be written to your MongoDB instance, not the hosted parse database.
