### ISSUE TITLE
PFFile limit

### ISSUE THREAD

**Issue by alexrmacleod** [ParsePlatform/parse-server#2302]
I am planning to make an iOS app that will have 5  - 10 min videos. However I noticed that PFFiles has a 20mb limit. Is there anyway to use parse server and get around this limitation? 

Also what if I started with the standard GridStoreAdapter. Then at some point in to future I needed to store PFFiles larger than 20mb. How would I get around this? what sort of issues would I be facing?

**Comment by flovilmart** [comment]
You can set the maxUploadSize option when you initialize parse-server to a larger value. 

As for the rest of the questions, please use stackoverflow as this is not an issue with parse-server.
