### ISSUE TITLE
Push in afterSave Function return success But never send out !

### ISSUE THREAD

**Issue by lifeisfunny** [ParsePlatform/parse-server#2307]
Well I am back again with same issue i had 3 days ago  !
i tried both syntax for push notification ,The function Keep return success , But server never send the push notification ! I am on Parse -server 2.1.16

**Comment by lifeisfunny** [comment]
my verbose have no POST /parse/push pops up  , So can we this time digging little bit more before we blame on the type of syntax or style we writing ??? Please

**Comment by lifeisfunny** [comment]
Ites funny that if i  set time out , some times it may work

**Comment by lifeisfunny** [comment]
Solved ,  ITs my local test machine

**Comment by natanrolnik** [comment]
@lifeisfunny please close the issue if it's solved
