### ISSUE TITLE
File type migration

### ISSUE THREAD

**Issue by aksonov** [ParsePlatform/parse-server#2310]
After migration of my db to parse server i've found that File type was not migrated at all (_Product table). As the result iOS app returns 403 error when i've tried to call `getData` method, how to get it?
```
{
    "_id": "6hCSsc4Nvs",
    "productIdentifier": "com.aksonov.tests.4",
    "icon": "tfss-084db875-a183-441b-9583-5237fdf8d549-0.plist",
    "subtitle": "test",
    "title": "test",
    "order": 4,
    "downloadName": "tfss-481b0948-7e5d-4eb0-aa57-b474a653a219-Husband0.plist",
    "_created_at": {
        "$date": "2014-08-22T05:59:41.458Z"
    },
    "_updated_at": {
        "$date": "2014-08-22T05:59:41.458Z"
    },
    "download": {
        "__type": "File",
        "name": "tfss-481b0948-7e5d-4eb0-aa57-b474a653a219-Husband0.plist",
        "url": "http://files.parsetfss.com/341c3c18-3aea-4b39-8d71-235afe12ecdf/tfss-481b0948-7e5d-4eb0-aa57-b474a653a219-Husband0.plist"
    }
}
```

**Comment by natanrolnik** [comment]
@aksonov isn't it the last value of the object you posted, in the `download` property?

**Comment by aksonov** [comment]
It is value within mlab database. It refers to hosted parse server, that is wrong, right? Also iOS parse client cannot download it - 403 error (maybe because appid is custom, not hosted one)

**Comment by hramos** [comment]
This is expected, Files are not stored in the database itself in Parse.com hosted apps (see #8).
