### ISSUE TITLE
Persistent "Invalid Session error code 101" when trying to afterSave on an anonymous user 

### ISSUE THREAD

**Issue by LiamInJapan** [ParsePlatform/parse-server#2312]
Hi there,

Thanks for a great system!

I was recently trying to add custom data to an anonymous user with cloud code via an afterSave callback, and I started getting a weird "Invalid Session error code 101" in the iOS client code.

Once this issue happened once, it seemed impossible to get rid of, until I deleted the build off my device, deleted derived data and restarted xcode.

I think I managed to track it down to not calling `Parse.Cloud.useMasterKey();`. However, the weird part about it was, once it happened once, it would continue to happen regardless of how I changed my code on either the server or client-side, until I took the remedial steps above.

### Steps to reproduce

1. Setup an afterSave in cloud code without useMasterKey e.g.

`

Parse.Cloud.afterSave(Parse.User, function(request, response) 
{
	var user = request.object;

	Parse.Cloud.run("createExtraData", {},
	{
		success: function(result) 
		{
			user.set("extraData", result);
			user.save();	
  		},
  		error: function(error) 
  		{
  			response.failure("failed to create extraData");
  		}
	});
});

`

2. Create anonymous user on iOS-side so above cloud code data gets called. Witness a 101 invalid session error in the xcode console

3. Add `Parse.Cloud.useMasterKey();` to the top of afterSave and deploy

4. Run a code path that creates an anonymous user on the iOS-side again. In my case, just deleting the app and re-running it was enough. Witness the 101 error again.

5. Delete app, clean project, delete derived data, restart xcode. Run a code path that creates an anonymous user again, and witness the 101 error not happen.

### Environment Setup

- **Server**
- **Database**
  - Still using Hosted Version

Many Thanks!

**Comment by noder199** [comment]
https://github.com/ParsePlatform/parse-server/issues/2252

**Comment by flovilmart** [comment]
You should not use Parse.Cloud.useMasterKey() in cloud code but pass {useMasterKey: true} to your options

**Comment by flovilmart** [comment]
Another question @LiamInJapan , you mention you run on Hosted Version. This repository is only for parse-server issues, once you've migrated your servers to the open source version of parse.

Feel free to reopen the issue if I'm mistaken, but there isn't anything we can do from there.
