### ISSUE TITLE
Migrate files from GridStore to S3

### ISSUE THREAD

**Issue by ckarmy** [ParsePlatform/parse-server#2315]
Hi! It's possible to migrate the files from GridStore to S3Adapter?

Or maybe work with the both adapters?

Thanks!

**Comment by JeremyPlease** [comment]
You could use [parse-files-utils](/parse-server-modules/parse-files-utils) to transfer the files. Parse Server doesn't currently allow multiple file adapters.

**Comment by ckarmy** [comment]
THANKS!

**Comment by a4arpan** [comment]
Hi 

Maybe too late to ask but I have a self-hosted parse instance and all files are stored on grid currently. How can I move them to s3 now and start using s3 for new uploads? Can I leave earlier uploaded file on the grid and new files on s3 or do I have to move all old files as well to s3 if yes how can I  move them to s3?

Thanks in advance
Arpan

**Comment by montymxb** [comment]
@a4arpan you can only have on file adapter on parse server at a time. As a result you will be accessing/saving to grid store or to S3 entirely, no in-betweens.

With this being said, I recently helped someone with a migration to a hosted solution from their own setup. To migrate the files across we ended up keeping the original parse server up to have access to those files. From there we utilized an SDK to request from the old parse server, and then save them to the new one; updating related parse objects along the way. Not the most _elegant_ solution, but it worked in that case w/ 1000~ files or so. If you have significantly more that might be an issue for you.

A better solution would be to have them moved directly from grid store into the new file adapter storage mechanism. Maybe the above mention parse-file-utils does this, but it hasn't been updated in some time.
