### ISSUE TITLE
cannot set the server URL in Unity SDK (v1.7.0)

### ISSUE THREAD

**Issue by ngjohn** [ParsePlatform/parse-server#232]
Hi, 
I am using Unity for development, and I downloaded the Unity sdk (v1.7.0)...
I dun know howto setup/change the 'server URL' in the sdk, 
can anyone give me some hints !!

Thank a lot.

**Comment by huang1196** [comment]
+1

**Comment by richardjrossiii** [comment]
There's an open issue on the .NET SDK itself to track this: https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/166. It will be fixed by the next release.
