### ISSUE TITLE
authData.anonymous === null strikes again

### ISSUE THREAD

**Issue by yuzeh** [ParsePlatform/parse-server#2321]
We've been having issues with null authData values since migrating our customers to our own parse-server.

Things that we thought would have fixed the issue:
- https://github.com/ParsePlatform/parse-server/commit/1b8e613dfb6f114878779e1012a33973fa273c2e
- https://github.com/ParsePlatform/parse-server/commit/5ba7bad5074b343bd43492d6c877f64bdf48d572

There may be a couple more but I'm beginning to realize that the core of this issue is that *we're allowing null authData* values to be written to the database.

That, along with the fact that there's no filtering on the query side, leads to clients getting null values in user.authData.

(Probably Android should deal with this, because it doesn't seem like a big deal in iOS-land, but that's the topic of another discussion?)

In any case, #2320 should fix this (partially) by not letting the nulls leak out of the parse-server. We may want to stop writing nulls as well.

**Comment by flovilmart** [comment]
> we're allowing null authData values to be written to the database.

Why don't we don't allow that?

**Comment by yuzeh** [comment]
> Why don't we don't allow that?

If your question is asking about the current state of affairs, I think the current protocol (or at the Android implementation of it) is part of it: https://github.com/ParsePlatform/Parse-SDK-Android/blob/7d908f3d1cbed3c89addfac49419c6c2f1859d62/Parse/src/main/java/com/parse/ParseUser.java#L432

If your question is a suggestion, I totally agree!

**Comment by hramos** [comment]
@yuzeh should we close this now that #2320 was merged in?

**Comment by yuzeh** [comment]
That's fine with me.
