### ISSUE TITLE
Parse server is not responding after several days working well

### ISSUE THREAD

**Issue by afterlastangel** [ParsePlatform/parse-server#2325]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [x] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.

- [x] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases

- [x] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.

- [x] You have filled out every section below. Issues without sufficient information are more likely to be closed.

--

### Issue Description

We have a parse server running on Google Compute Engine, with mlab database. It worked well when we start. But after about 2 weeks, the parse server does not response for the API call. We need to restart the parse-server instance by supervisord in order to make it works again. Our work around is setting up a monitor and trigger restart when ever the server is not responding 

Describe your issue in as much detail as possible.

The node JS process is still working, we still have the log debug:

> ^[[36mverbose^[[39m: PUT /1/

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

It's suddenly stop working, I don't know the step to reproduce

#### Expected Results

Response the result

#### Actual Outcome

The API does not response anything 
for - /1/classes/_Installation
and - /1/push
The request would be timeout.

#### What is working

/1/events/AppOpened

#### How to make it works again

Restart the parse-server nodeJs server

### Environment Setup

- **Server**
  - parse-server version: 2.2.16
  - Operating System:     Debian GNU/Linux 8.4
  - Hardware:             Google Cloud Instance 
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Google

- **Database**
  - MongoDB version: 3.0
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mlab

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

classes/_Installation/BXgIfbp8jQ { host: 'Filtered',
>   'x-real-ip': 'Filtered',
>   'x-forwarded-for': 'Filtered',
>   connection: 'close',
>   'content-length': '169',
>   'accept-encoding': 'gzip',
>   'cf-ipcountry': 'VN',
>   'cf-ray': '2c4b85914c5f3433-HKG',
>   'x-forwarded-proto': 'http',
>   'cf-visitor': '{"scheme":"http"}',
>   'x-parse-app-display-version': '1.1.1298.089eeb9',
>   'x-parse-installation-id': '6793bd62-b899-48ff-bb76-a763f9231092',
>   'user-agent': 'Parse Android SDK 1.13.0 (Filtered) API Level 23',
>   'x-parse-os-version': '6.0',
>   'x-parse-app-build-version': '1010001298',
>   'content-type': 'application/json',
>   'x-parse-client-key': 'Filtered',
>   'x-parse-client-version': 'a1.13.0',
>   'x-parse-application-id': 'Filtered',
>   'cf-connecting-ip': 'Filterd' } {
>   "pushType": "gcm",
>   "GCMSenderId": "Filtered",
>   "deviceToken": "|ID|5|:Filtered",
>   "appVersion": "1.1.1298.089eeb9",
>   "objectId": "BXgIfbp8jQ"
> }
> 
> 

> ^[[36mverbose^[[39m: POST /1/push { host: 'Filtered',
>   'x-real-ip': 'Filtered',
>   'x-forwarded-for': 'Filtered',
>   connection: 'close',
>   'content-length': '299',
>   'accept-encoding': 'gzip',
>   'cf-ipcountry': 'VN',
>   'cf-ray': '2c4b710e9f6132a7-HKG',
>   'x-forwarded-proto': 'https',
>   'cf-visitor': '{"scheme":"https"}',
>   'user-agent': 'curl/7.43.0',
>   accept: '*/*',
>   'x-parse-application-id': 'Filtered',
>   'x-parse-rest-api-key': 'Filtered',
>   'x-parse-master-key': 'Filtered',
>   'content-type': 'application/json',
>   'cf-connecting-ip': 'Filtered' } {
>   "channels": [
>     "tkn-BXgIfbp8jQ"
>   ],
>   "deviceType": [
>     "ios",
>     "android",
>     "winphone",
>     "winrt"
>   ],
>   "data": {
>     "alert": "This is parse using our API domain",
>     "badge": "Increment",
>     "sound": "",
>     "title": "This is parse using our API domain",
>     "uri": ""
>   }
> }
> 
>

**Comment by bohemima** [comment]
Probably because of lost connection to the mongo database

**Comment by afterlastangel** [comment]
@bohemima Thank you, we think that is the parse of problem, we are going to create a self hosted mongodb for our staging environment. The problem does not happen on our production with self hosted mongodb, I will go back when have monitor result

**Comment by flovilmart** [comment]
There will be a fix in the next version for mongodb lost connections that should probably solve that issue.

**Comment by hramos** [comment]
I'm going to close this for now, feel free to reopen if this is not solved yet.
