### ISSUE TITLE
Pointers in $in queries throw: Uncaught internal server error [ReferenceError: atom is not defined] 

### ISSUE THREAD

**Issue by ogonzalezadell** [ParsePlatform/parse-server#2326]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [x] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.

- [x] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases

- [x] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.

- [ ] You have filled out every section below. Issues without sufficient information are more likely to be closed. [Mising how to reproduce it, I do not know how]

--

### Issue Description

Parse-server not resolving properly $in queries when using pointers (REST). It throws Uncaught internal server error [ReferenceError: atom is not defined] 

#### Expected Results

The server should return the _Posts_ that cointain one of the _User_ array.
It works properly on parse.com without changing anything just the url.

#### Actual Outcome

Internal server error.

### Environment Setup

- **Server**
  - parse-server version: 2.2.16
  - Operating System:     RHEL 6.4 ( CENT OS Linux )
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): CSC BizCloud Remote server

- **Database**
  - MongoDB version: 3.0.11
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost (the same server)

### Logs/Trace

`2016-07-08T07:15:10.308Z - Uncaught internal server error. [ReferenceError: atom is not defined] ReferenceError: atom is not defined
    at /home/user/parse-server/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:499:78
    at Array.map (native)
    at transformConstraint (/home/user/parse-server/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:496:29)
    at transformQueryKeyValue (/home/user/parse-server/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:193:7)
    at transformWhere (/home/user/parse-server/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoTransform.js:215:15)
    at MongoStorageAdapter.find (/home/user/parse-server/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:412:59)
    at /home/user/parse-server/node_modules/parse-server/lib/Controllers/DatabaseController.js:923:36
    at run (/home/user/parse-server/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /home/user/parse-server/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/home/user/parse-server/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)`

Failing in a complex query "URL" where we try to find posts where the post.user (pointer) is $in an array (of pointers of type user) users [Note: I use REST Services, not the SDK, the decoded url below is the url that the error from server gives back to my app]:

` domain.com/parse/classes/Post?include=user,user.region,user.dptArea&limit=100&order=-createdAt&where[user][$in][][__type]=Pointer&where[user][$in][][className]=_User&where[user][$in][][objectId]=4dyTOMTLZP&where[user][$in][][__type]=Pointer&where[user][$in][][className]=_User&where[user][$in][][objectId]=1fZ3gzNivG`

Also parsing the error I get:` Error code 1`, `error message (null)`, probably because it is a internal server error.

**Comment by flovilmart** [comment]
It seems to be a problem with the way you encode your query parameters, check https://www.npmjs.com/package/qs or it's equivalent for your usage.
