### ISSUE TITLE
mLab upgrade of mongo version to 3.0 and 3.2 in September

### ISSUE THREAD

**Issue by brianyyz** [ParsePlatform/parse-server#2328]
This is more a question / discussion point so if it belong elsewhere just let me know. :-)
Received this email from mLab this morning and would like to get a steer on whether it poses a problem to the parse-server-example deployments that are using Heroku and mLab.

You are receiving this email because you have one or more mLab deployments in the "bmacdonaldyyz" mLab account that will be affected by upcoming maintenance.

"MongoDB 3.2 is now generally available on mLab, so we are in the process of making it the default release version for all new mLab deployments. We are also taking steps to discontinue our support for MongoDB 2.6.

To this end, on Tuesday, September 27, we will start a four-day maintenance window to upgrade all free Sandbox databases running MongoDB 3.0 to MongoDB 3.2. In addition, we will upgrade all for-pay Shared databases running MongoDB 2.6 to MongoDB 3.0. Dedicated plan deployments will not be impacted."

Thanks...Brian

**Comment by flovilmart** [comment]
parse-server is compatible with most versions of mongoDB and we expressively test on 2.6.11, 3.0.8 and 3.2.6, and we're planing to keep it on moving forward.

**Comment by yuzeh** [comment]
can we update the documentation so that this is noted? https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#database

**Comment by acinader** [comment]
Yup.  Will do.

**Comment by flovilmart** [comment]
@acinader, i updated already :)

**Comment by acinader** [comment]
:)
