### ISSUE TITLE
How to configure webhooks from stripe to parse server

### ISSUE THREAD

**Issue by cyboolo** [ParsePlatform/parse-server#234]
Hi,

Before migration this webhook configured on stripe dashboard worked perfectly:

`https://<**myParseapp**>:javascript-key=<**myJSkey**>@api.parse.com/functions/new_invoice`

Now, when I try to do the same with my parse server on heroku:

`https://<**myParseapp**>:javascript-key=<**myJSkey**>@something.herokuapp.com/parse/functions/new_invoice`

I got error "403 unauthorized" when I test this webhooks from stripe dashboard.

How could I fix that please?

**Comment by xwizi** [comment]
Have you checked your keys are set-up correctly? 

A workaround:

in index.js (if you used the demo app or in your express routes)

```
// exposes a new api route that can be used in stripe  //yourdomain/api/stripe
app.get('/api/stripe', function(req, res) {

Parse.Cloud.run("new_invoice",req.body[0],
{ 
 success:function(e){...},
 error:function(e){..}
});

};
```

**Comment by cyboolo** [comment]
Thank you for your help, I could find a solution by doing these modifications:

You must have in your code:
```
var stripe = require('stripe')('your live or test stripe key');
var Parse = require('parse').Parse;
var Parse = require('parse/node').Parse;
var bodyParser = require('body-parser');
```
then add:
`app.use( bodyParser.json() );`

and finally the code to receive webhook and launch function from cloud code:
```
app.post('/stripe', function(req, res){
  
Parse.initialize("appId", "JsKey"); 
Parse.Cloud.run('hello',{}, {
success: function(obj) { res.send(obj); },
error: function(error) {
res.status(500);
res.send(error);
}
});
  
});
```
In webhook testing mode on stripe I get the response from my cloud code function, in that case "hello world!"

**Comment by otymartin** [comment]
@cyboolo hi so are webhooks working for you with parse-server and cloudcode?

**Comment by paulrolfe** [comment]
Just making this a little clearer for people still having trouble. Also this express doc was super helpful for me. https://expressjs.com/en/api.html#req

I was using a webhook with twilio.
```js
// index.js
var hooks = require('./cloud/hooks');
var bodyParser = require('body-parser');
//...
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true })); // for parsing application/x-www-form-urlencoded

app.post('/receiveSMS', function(req, res) {
  console.log("RECEVIED SMS FROM: " + req.body.From);
  console.log("Body: " + req.body.Body);
  var passedRequest = {"params": req.body}; // That's how my receiveSMS function expects it. You may not need this.
  hooks.receiveSMS(passedRequest, {
    success: function(obj) {
      res.status(200).send(obj);
    },
    error: function(error) {
      res.status(500).send(error);
    }
  });
});
```

**Comment by kamalbrowswire** [comment]
Hi 
I am new in parse-server and i have to create webhook for a class.I can't understand what is the **Webhook URL**   and where to use.

**Comment by lxknvlk** [comment]
None of the approaches worked for me. What did work is this:

////yourdomain/api/stripe?param1=2&param2=true, all params are in req.query
app.get('/api/stripe', function(req, res) {	
	Parse.Cloud.run("stripeWebHook", req.query,{
	 success:function(e){
	 	res.status(200).send(e);
	 },
	 error:function(e){
	 	res.status(-1).send(e);
	 }
	});
});
