### ISSUE TITLE
In Parse Dashboard email verification field in User collection is not displaying data.

### ISSUE THREAD

**Issue by SrinathReddyKolanu** [ParsePlatform/parse-server#2344]
We are using email verification for a new user and the user is getting email verification links to their Email.

Here the problem is when the user is created, as we have set email verification field to true, we are unable to see the same in parse dashboard User collection. In User collection it shows as an empty space for email verification field but when the same if we call through REST service we can find the email verification data as true/false.

Conclusion-

In parse dashboard in User collection email verification field is not showing data. It is showing empty or undefined. But using REST service we are getting the data. Dashboard having some issue with displaying **emailverification** field.

**Comment by flovilmart** [comment]
Please open on the https://github.com/parseplatform/parse-dashboard repository
