### ISSUE TITLE
Pass User Object to Cloud Code

### ISSUE THREAD

**Issue by greggmojica** [ParsePlatform/parse-server#2349]
Can an object be sent from the javascript sdk to cloud code?  If so, then how could I go abouts sending a user object to cloud code?   I realize I can query for the object and then update the cloud code but is there another way?

When I run my cloud code function it says "Parse Objects not allowed here".

**Comment by flovilmart** [comment]
I'm not sure we support parse objects sent to cloud code, not sent back from cloud code, try sending it as a JSON and creating it back when you have it in cloud code.

**Comment by ranhsd** [comment]
Like @flovilmart you cannot send objects to cloud code but what you can do is to send the objectId and if you need all the object then you can query it from the database (by the objectId) and if you don't need the all other fields of the object then you can create a new object of the same type and set only the id to the objectId that was sent to the cloud code function.

**Comment by greggmojica** [comment]
Thanks guys! I did that :)
