### ISSUE TITLE
Push notification not working.

### ISSUE THREAD

**Issue by ksingh65** [ParsePlatform/parse-server#2359]
Hi

I have migrated parse server code to aws, running properly except push notification.

I have added cloud code afterSave method including masterKey method.

Now whenever I am saving a item from iOS app, this method is getting called, but no push notification is getting for device, when i checked server log its showing an error:

ERR! parse-server-push-adapter APNS cannot find vaild connection for 
/node_modules/parse-server/lib/ParseServer.js:327
            throw err;
            ^

Error: wrong tag
    at Error (native)
    at Object.createSecureContext (_tls_common.js:132:17)
    at Object.TLSSocket._init.ssl.onclienthello.ssl.oncertcb.exports.connect (_tls_wrap.js:972:23)

Can you please let us know what extra setting we need to add?

**Comment by ranhsd** [comment]
Hi, did you go through the guide here:  [https://github.com/ParsePlatform/parse-server/wiki/Push](url) and create .p12 certificate and use it in your code? also please make sure you generate the right certificate (either sandbox or production). 
it will also be nice if you can paste some code (the code where you configure the push and also the afterSave method code)

**Comment by flovilmart** [comment]
DId you follow the push guide on the wiki?

**Comment by flovilmart** [comment]
This seems to be an error with the push adapter which is provided as a separate module. Please report the issue on this repository https://github.com/parse-server-modules/parse-server-push-adapter
