### ISSUE TITLE
_Session row keeps increasing, Same user login.

### ISSUE THREAD

**Issue by ngjohn** [ParsePlatform/parse-server#237]
Hi,

After I setup my self hosted parse-server,
With some simple function testing, I try to login a user again & again (without logout),
I found that the _Session table in mongodb keep increase, +1 per login.
this was not happen in Parse-hosted version. is it a bug?
or I need to make some special configuration to correct this issue?

Thanks.

**Comment by gfosco** [comment]
One user can definitely have many sessions on hosted parse, but your client may send an installation id which allows it to be merged.  The logic for de-duplicating sessions may not be entirely correct, but I would need more information.  What client SDK are you using and what are the differences between rows?

**Comment by ngjohn** [comment]
Hi, Fosco,

thanks for your reply.

I am developing a Unity project (with Parse-hosted), and my experience is that everytime the same user 'Login' at the same device (without logout logic), the _Session table row keeps unchange (I suppose the old session record of this user is merged/replaced with the new one...) I didn't send any installation id at all.

But after I hosted parse-server myself, for some reason, I use .Net sdk (v1.7.0) with Visual Studio, I try the same logic code, same user login at same device multiple times, I found that the server keep adding new session to _Session table, and I can see many rows of the same user. ( with different session token , createAt, expiresAt...)

one of the row looks like 
```
{
    "_id": "QAP7fyLXTW",
    "_session_token": "r:e35029903c1b391ae37d39fa74f1a9fe",
    "_p_user": "_User$7O0DqnQwA0",
    "createdWith": {
        "action": "login",
        "authProvider": "password"
    },
    "restricted": false,
    "expiresAt": {
        "$date": "2017-02-04T08:18:02.991Z"
    },
    "installationId": "bafcb7ba-f5b2-4c9b-a478-b3cb5a5b1622",
    "_updated_at": {
        "$date": "2016-02-04T08:18:02.991Z"
    },
    "_created_at": {
        "$date": "2016-02-04T08:18:02.991Z"
    }
}
```

**Comment by gfosco** [comment]
This is likely to be related to #672, and I'll close this one.. Installation de-duplication may not be built quite right, and I think stephentuso might track it down.
