### ISSUE TITLE
Name conflict issue

### ISSUE THREAD

**Issue by zh-wowtv** [ParsePlatform/parse-server#2379]
I have an application with server and client. They are sharing the same package.json:

 ```
 "dependencies": {
    "art": "~0.10.1",
    "babel-cli": "~6.10.1",
    "babel-relay-plugin": "~0.9.1",
    "crc32": "~0.2.2",
    "express": "~4.14.0",
    "express-graphql": "~0.5.3",
    "graphql-relay": "~0.4.2",
    "immutable": "~3.8.1",
    "moment": "~2.13.0",
    "parse": "~1.8.2",
    "parse-dashboard": "~1.0.8",
    "parse-server": "~2.2.6",
 }
```

But when I run the app by ```react-native run-ios```, I got the following error message:

> Failed to build DependencyGraph: @providesModule naming collision:
>   Duplicate module name: parse
>   Paths: /Users/myname/Projects/app/node_modules/parse/package.json collides with /Users/myname/Projects/app/node_modules/parse-server/node_modules/parse/package.json
> 

How to fix the issue? Thanks.

**Comment by zhouhao27** [comment]
Actually it has nothing to do with my client side code. I still got the same problem if I remove ```"parse"``` from my package.json and clear everything and rebuild.

**Comment by zh-wowtv** [comment]
Actually remove parse and reinstall fixed the problem.
