### ISSUE TITLE
Run parse-server as a service in EC2 AWS linux 

### ISSUE THREAD

**Issue by zh-wowtv** [ParsePlatform/parse-server#2382]
I installed parse-server on my AWS Linux EC2. I can run it through:

> npm start

But the problem is it will quit when I close my SSH. Is there any sample on how to run it as a service? Thanks.

**Comment by cleever** [comment]
I recommend you to use PM2

**Comment by zh-wowtv** [comment]
@cleever Sorry, don't get you. What is PM2?

**Comment by LamourBt** [comment]
you could either pm2 or forever, they are daemon script that let you app run on your server forever (even though you are connect)

**Comment by cleever** [comment]
@zh-wowtv 

http://pm2.keymetrics.io/
https://github.com/Unitech/PM2/

"pm2" is a full feature process manager for node.

"forever" aim to run your application continuously. Is an option, but I do not recommend for production environment.

https://github.com/foreverjs/forever

**Comment by zh-wowtv** [comment]
Thanks. I'll go through the document. Thanks. @cleever

**Comment by zh-wowtv** [comment]
Package.json:

```
  "scripts": {
    "server": "VERBOSE=1 nodemon ./server.js --exec babel-node",
  },

```

My mongodb is started as a service. Everything's fine if I use the following command to start my parse-server:

> npm run server

But when I start by pm2. It seems the database is not connected. Because I can't see any data in my dashboard.

> pm2 start myapp

I created my pm2 app like this:

> pm2 start myapp.sh

Inside myapp.sh:

`npm run server`

Any idea? Thanks.
