### ISSUE TITLE
Parse.Cloud.useMasterKey() unavailable - is that accurate?

### ISSUE THREAD

**Issue by AndrewLane** [ParsePlatform/parse-server#2385]
The wiki at https://github.com/ParsePlatform/parse-server/wiki/Compatibility-with-Hosted-Parse says "Parse.Cloud.useMasterKey() is not available in Parse Server Cloud Code.".  However, I'm able to call that function just fine and it seems to have the desired effect.  Is the wiki just out of date or am I doing something wrong?

**Comment by flovilmart** [comment]
You should not use it, given the shared state of the Parse JS SDK in node and particularly on parse-server any subsequent calls may be run as master and that may have unintended side effects.

**Comment by AndrewLane** [comment]
thank you
