### ISSUE TITLE
Parse.com and parse-server running in tandem

### ISSUE THREAD

**Issue by shivangagarwal** [ParsePlatform/parse-server#2394]
Hi,

This is not a issue with Parse-server. Just need a clarification of a few things. To give you some context: We have multiple apps (~30) which are running on parse and using the same database (AWS hosted mongodb). We are now migrating the cloud code to the parse-server. The question that i had:

- When we update the parseURL, all the clients will not call our parse-server as update will happen in the latest release. So parse.com and parse-server will be calling and writing to the same database in parallel. Will the writing from two different versions of parse (parse.com and parse-server) will have any issues like data inconsistency or corruption?

Thanks,
Shivang

**Comment by steven-supersolid** [comment]
There should be no problems as far as data is concerned. We (and others) diverted just a subset of users before transitioning fully, so have the same app running on both hosts and using the same database.
