### ISSUE TITLE
Implement Janrain Capture and Janrain Engage auth provider

### ISSUE THREAD

**Issue by AndrewLane** [ParsePlatform/parse-server#2398]
### Implement Janrain Capture and Janrain Engage auth provider

This would be an addition to parse server to allow for authentication using Janrain.  Janrain provides an Engage product as well as a Capture product, so there will be separate auth providers for each.  It would be similar to Twitter, Facebook, etc. which are already implemented.

I will be submitting a PR but I wanted to submit this issue first for any necessary discussion.

**Comment by AndrewLane** [comment]
Pull request added: https://github.com/ParsePlatform/parse-server/pull/2436

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.13](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.13)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)
