### ISSUE TITLE
Dockerize platform for multi-cloud deployment and easy management

### ISSUE THREAD

**Issue by Telemakhos** [ParsePlatform/parse-server#24]
It would be great to have a dockerized solution, a standard docker-compose file with the necessary containers and services (Node/Express API, MongoDB, PUSH, etc) and provide some examples of deployment for several clouds. Examples:

- Deployment to [AWS Beanstalk](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker_ecs.html)
- Deployment and autoescaling via [Tutum](https://www.tutum.co/) (AWS, Google Cloud, Digital Ocean) 
- Deployment to [Heroku](https://devcenter.heroku.com/articles/docker)
-  Deployment to [Google App Engine](https://cloud.google.com/appengine/docs/managed-vms/)

The goal should be getting an open platform easy to deploy, scale and manage.

Thoughts?

**Comment by kingmatusevich** [comment]
Have you seen the docker container we are working in? Looks like what you need: https://github.com/instainer/parse-server-docker

**Comment by Telemakhos** [comment]
Mmm I've just seen it... Installing mongo on the same container is a big **anti-pattern** and considered bad practice... docker containers should be stateless and you should persist the data to volumes...

**Comment by kingmatusevich** [comment]
Prepare a pull request maybe? I'm just getting started with Docker, and I'm sure @tahaozket could use the help.

**Comment by tahaozket** [comment]
@Telemakhos you are right, but it is a simple image for showing how it works. I should prepare another separate docker image for production usecase.

**Comment by gfosco** [comment]
Open to adding more of these to the wiki, and publicizing any good guides...  We're also working with some cloud providers.
