### ISSUE TITLE
serverURL invernal vs external 

### ISSUE THREAD

**Issue by ronnno** [ParsePlatform/parse-server#2412]
When setting up ParseServer in Heroku I notice that each cloud code function making requests against Parse Query or Object to access the database is using serverURL to access the same parse server via REST API.

I'm setting serverURL to the external address of the servers. It was my understanding that is required for some functions to work. But this causes each such internal request to route back to the load balancer and often reach a different node.

I would like to prevent this inefficient behaviour. before trying work arounds like setting hosts file entries - is there a way to configure the server to use localhost for internal Query and Object.save calls?

**Comment by flovilmart** [comment]
You should point the serverURL To the localhost, and not the public URLs. There is publicServerURL for that purpose

>
>
>
>
>

**Comment by ronnno** [comment]
Thanks,
I tried that now and it works fine only on my dev env (`heroku local`). When deployed to Heroku no data comes back and I see errors in the logs:
>Jul 27 17:26:18 milestonepod app/web.1:  [ ParseError { code: undefined, message: undefined }, 
>Jul 27 17:26:18 milestonepod app/web.1:    ParseError { code: undefined, message: undefined }, 
>...

my code is:

`var port = process.env.PORT || 1337;`
`var publicServerURL = process.env.SERVER_URL || 'http://devserver:1337/1'; // devserver is defined as localhost in hosts file on dev env`
`var serverURL = "http://localhost:" + port + "/1";`
...
`  var api = new ParseServer({`
...
`    publicServerURL: publicServerURL,`
`    serverURL: serverURL,`
...
`}`
`var httpServer = require('http').createServer(app);`
`  httpServer.listen(port, function () {...`

In Heroku I'm using an SSL plug in. That is the only difference.

**Comment by pan83** [comment]
@ronnno could you please post an example of how you did this on heroku? Did you set a standard port? I use sslify and I was wondering if I can access localhost through SSL...

**Comment by ronnno** [comment]
Hi,

I'm using Heroku SSL add-on which strips SSL for me - so that requests come into the normal http port (which I set by looking at $PORT as usual).

In order to force clients to access me using HTTPS and not HTTP, I'm looking at each requests headers and block HTTP requests except in the host was localhost (which means it came from inside Heroku) or if it was a request for a file - which I choose to allow http access at the moment:

```
  var forceSSL = function (req, res, next) {
    // if the request arrives from the outside, and it was not received in https, and it's not a file request - block it
    if (req.headers['host'] != internalHostHeader && // this cond could also be tested if we require x-forwarded-proto to be defined - since on access from localhost it's not.  but this is more explicit 
        req.headers['x-forwarded-proto'] !== 'https' &&
        !req.path.startsWith(filePathPrefix)) {
      return res.status(403).send({message: 'SSL required'});
    }
    // otherwise, let it pass through
    return next();
  };

// set the handler in our express app:
var sslOnly = process.env.SSL_ONLY || false;
var mountPath = process.env.PARSE_MOUNT || '/1';
var serverURL = "http://localhost:" + port + mountPath; 
var internalHostHeader = "localhost:" + port; // must match the host header in serverURL
var publicServerURL = process.env.SERVER_URL || serverURL;
var appId = process.env.APP_ID;
var port = process.env.PORT || 1337;
var filePathPrefix = mountPath + "/files/" + appId + "/";

  if (sslOnly) app.use(forceSSL); 
```

**Comment by pan83** [comment]
Thank you @ronnno. I'll try to do something similar on my setup.
