### ISSUE TITLE
Getting unauthorized error while deploying cloud code

### ISSUE THREAD

**Issue by ankushmittal87** [ParsePlatform/parse-server#2416]
Hi Team,

I have managed to setup parse server locally. But after changing the "application and master key" in global.json when I tried to deploy my code locally. I got the below error. 

D:\Users\mabhalla\Desktop\Parse Server\BidHub\BidHub-CloudCode-master>parse deploy
Uploading source files
Deploy failed with error:
unauthorized
Will retry in 0 seconds.

Uploading source files
Sorry, deploy failed again with same error.
Will retry in 1 seconds.

Uploading source files
unauthorized

Please assist.

Thank you in anticipation,
Ankush Mittal

**Comment by hramos** [comment]
The parse CLI is only meant to be used with Parse.com hosted apps. If you're using Parse Server, your Cloud Code is loaded from the file specified by the `cloud` param (usually ./cloud/main.js).

**Comment by ankushmittal87** [comment]
Thank you for your reply.

I shall be thankful if you can provide more information on it. I want to explain my problem again.

I actually want to deploy [BidHub code](https://github.com/HubSpot/BidHub-CloudCode) onto local parse server. 

I managed to deploy successfully on parse.com and able to see my populated data at my client side(iPhone and android application).

Thank you,
Ankush MIttal
