### ISSUE TITLE
Dynamic Parse server Instance

### ISSUE THREAD

**Issue by aknoormohamed** [ParsePlatform/parse-server#2419]
i need dynamically create parse server instance like back4app

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.13](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.13)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)
