### ISSUE TITLE
How can I keep using Parse Dashboard by setting up my own parse Server and MongoDB?

### ISSUE THREAD

**Issue by vikasr111** [ParsePlatform/parse-server#242]
Sad to see Parse go as it is very critical part of my product. One thing I loved about Parse is its dashboard. I am more comfortable in creating a table from the dashboard or adding a few data directly from the dashboard itself. I saw this paragraph on Github about the dashboard but couldn't understand much.
> 
"Parse server does not include a web-based dashboard, which is where class-level permissions have always been configured. If you migrate an app from Parse, you'll see the format for CLPs in the SCHEMA collection. There is also a setPermissions method on the Schema class, which you can see used in the unit-tests in Schema.spec.js You can also set up an app on Parse, providing the connection string for your mongo database, and continue to use the dashboard on Parse.com."

I'm not sure how will the dashboard work after setting up my own Parse server. Can somebody help me understand how can I keep using dashboard on parse.com, as explained in above para.

**Comment by francocorreasosa** [comment]
That's not possible, a WebUI for your own parse-server will be released in a few months. But for now, you can manage the data in your MongoDB Database with the existing Parse Dashboard. The only thing you need to do is migrate the data from Parse Database to MongoDB and the Parse API will store the changes on it.

**Comment by gfosco** [comment]
You can create an app on Parse and provide the mongo connection string, then you can continue using the web dashboard... However, #3 is in the works and it won't be long before a self hosted dashboard is available.

**Comment by vikasr111** [comment]
Thanks for clarifying @francocorreasosa and @gfosco. Can't wait to see the self hosted dashboard :+1:

**Comment by krishnakumarcitrus** [comment]
Our own local parse dashboard.
http://blog.parse.com/announcements/introducing-the-parse-server-dashboard/
