### ISSUE TITLE
[Feature Request] add cloudCodeKey for cloud code only access

### ISSUE THREAD

**Issue by smassin** [ParsePlatform/parse-server#2440]
The idea behind this feature is to have a key that only has access to cloud code functions.

Why? So that you can protect all other routes from being publicly available and to force all users actions through cloud code which gives the developer more control over what is and isn't allowed.

I know CLPs can have a similar effect but I would prefer if an outside user didn't even get that close to the database. Client side Javascript is just too insecure and the files API allows people to just upload whatever they want unrestricted.

**Comment by hramos** [comment]
We don't typically track feature requests here in the issue tracker. Perhaps you may want to send a PR?

**Comment by RafaRuiz** [comment]
This could be a solution for #3067 maybe.

This has come to me after successfully get some delicate data from Parse hosted websites and apps (even though ACLs and CLPs were set).

**Comment by RafaRuiz** [comment]
@smassin take a look to #3067, there's a workaround
