### ISSUE TITLE
Tons of requests come in after moving to the self-hosted Parse server

### ISSUE THREAD

**Issue by shiguoning** [ParsePlatform/parse-server#2441]
Hello, please help! 
We have a mobile game using Parse server to store users' game data. There are about 900K user records in the User table now. Early in this year, we have migrated the database to mLab, and we set the limit to 80req/sec 4 jobs in the account setting of Parse.

1 month ago, we followed the guide and set up the new Parse server based on the parse-server-example on AWS with a Elastic Beanstalk machine of c4.xlarge and 8 instances, niginx proxy. then we released an update for iOS users to point to the new server. The AWS console shows it handles around 2000 req/min, everything seems well in the last month, even queries are faster than before. Couple days ago, we had to move our Android users to the new server due to the deadline of July 28. So we released an update for the Android users and point them to the new server too. 1 day later, the server was down, and the monitoring showed there were over 300,000 req/min. I don't know where did so many requests come from.

I downloaded the logs, the nodejs.log repeats this error:
**[31merror[39m: error getting auth for sessionToken MongoError: connection 2 to ds013230-a1.hwm35.fleet.mlab.com:13230 timed out
at Function.MongoError.create (/var/app/current/node_modules/parse-server/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:29:11)
at TLSSocket. (/var/app/current/node_modules/parse-server/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:161:20)
at TLSSocket.g (events.js:260:16)
at emitNone (events.js:67:13)
at TLSSocket.emit (events.js:166:7)
at TLSSocket.Socket._onTimeout (net.js:326:8)
at _runOnTimeout (timers.js:524:11)
at _makeTimerTimeout (timers.js:515:3)
at Timer.unrefTimeout (timers.js:584:5)**

While the nginx's access.log repeats 499 or 500 error for every connection. The error.log says **1024 worker_connections are not enough**. Only 0.5% of them return 200. But after I increased the worker connections to be 20480 for every instance, most requests were still failed.

Then I switched nginx to apache. It's a little better that the number of requests reduced to around 30,000 req/min, and 2000 requests return 200 per minute, others return 502 or 400.

I am very confused, why there are so many requests if I use nginx? Why 80req/sec (4800req/min) is enough to handle all requests by the Parse hosted server, but most requests are failed on our self-hosted server? 

And I sent an email to mLab support, this is the reply:
Two things:

**(1) Try increasing your connectTimeoutMS to 30sec by adding this setting to your connection string:
https://docs.mongodb.com/manual/reference/connection-string/#urioption.connectTimeoutMS
(2) If your process is exiting it is because you are not catching the exception to your connect call. Based on your stack trace it is not clear if the process is exiting. Are you sure it is exiting? That is you have to start the Parse Server again?**

Could anyone give me some idea about this? Thank you!

**Comment by dominichackett** [comment]
If you have any middleware functions they make sure they are not running recursively.  I noticed this as my error.

**Comment by flovilmart** [comment]
Not sure what your problem is, if you're doing heavy cloud code, all requests go back to HTTP, so you may wanna make sure everything's taken care of on that side. There is an **experimental** improvement coming up with #2316 that will skip the HTTP calls for all Cloud Code queries.

This may be included in 2.2.19 that is upcoming.
