### ISSUE TITLE
Expired Session Token handling

### ISSUE THREAD

**Issue by neophob** [ParsePlatform/parse-server#2450]
I run a query on the parse server to verify that the current (client) user session is valid. I did some tests with a really short session time of 10s. After the session is expired I still can login and query the Session table:

`ParseObjectSubclass { className: '_Session', _objCount: 1, id: 'VFtoOLOgNM' }`

However if I want to run a cloud function I see this (expected) error: `{"err":{"code":209,"message":"Session token is expired."},"function":"getFirmwareV1"}`

Question: when querying a table with an expired user session, shouldn't parse server deny this?

I'm running Parse 2.2.16

**Comment by hramos** [comment]
Not necessarily, because tables can have publicly readable objects and therefore do not require a valid session to be passed in.

If you're still able to read protected objects with an expired session, please open an issue with repro steps.
