### ISSUE TITLE
Elasticbean deployment problem

### ISSUE THREAD

**Issue by zh-wowtv** [ParsePlatform/parse-server#2464]
I followed the guide to deploy a parse-server at Elasticbean. It's running (with green icon). But I got:

> 502 Bad Gateway

In my log, I saw:

> Parse-server is running on port 1337

Also:

> [error] 4610#0: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 202.73.41.198, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8081/", host: "myapp-dev.ap-southeast-1.elasticbeanstalk.com"

What could be the reason? Thanks.

**Comment by rkand4** [comment]
I am facing the same issue. Did you find the reason for this. For me what's happening is it sends HTTP 500 errors after some time of deployment. Initially it works fine for 10-15 minutes and the server starts to send HTTP 500 errors.

**Comment by zh-wowtv** [comment]
I didn't use Elasticbean finally because it seems to be too "transparent". What I did is to install to EC2 directly and use PM2 to manage my process.
