### ISSUE TITLE
Data format not correct with Parse.ACL Master Key Only

### ISSUE THREAD

**Issue by jeffhuangtw** [ParsePlatform/parse-server#2465]
Data format not correct with Parse.ACL Master Key Only

### Steps to reproduce
Create new Object without public read and public write by user
Mini-code to reproduce this issue
```javascript
var Report = Parse.Object.extend("Report");

var report = new Report();

report.set('name', 'Test ACL');

var acl = new Parse.ACL();

acl.setPublicReadAccess(false);

acl.setPublicWriteAccess(false);

report.setACL(acl);

return report.save(null, {useMasterKey: true});
```

#### Expected Results

The new Report object can only access by Master Key.
And the raw data format in MongoDB should be as follow:
`
{
    "_id": "74jBa49O8P",
    "name": "Test ACL",
    "_wperm": [],
    "_rperm": [],
    "_acl": {},
    "_created_at": {
        "$date": "2016-08-05T07:29:56.172Z"
    },
    "_updated_at": {
        "$date": "2016-08-05T07:29:56.172Z"
    }
}
`

#### Actual Outcome
The new Report object has Public Read and Public Write (viewed by dashboard)
The raw data format in MongoDB miss the key "_acl"
`
{
    "_id": "74jBa49O8P",
    "name": "Test ACL",
    "_wperm": [],
    "_rperm": [],
    "_created_at": {
        "$date": "2016-08-05T07:29:56.172Z"
    },
    "_updated_at": {
        "$date": "2016-08-05T07:29:56.172Z"
    }
}
`

### Environment Setup

- **Server**
  - parse-server version: 2.2.17
  - Operating System:  MacOS Darwin Kernel Version 15.5.0
  - Hardware:            Mac Pro
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost

- **Database**
  - MongoDB version: mongod version: 3.0.12

**Comment by hramos** [comment]
Thanks for the clear description of the issue! I'd also expect the `_acl` key to be set to `{}` in this case.

Can you do one more check? See if the same issue appears when the object is created using the REST API. This would help us determine if the issue is on the JavaScript SDK itself, or on Parse Server.

**Comment by jeffhuangtw** [comment]
Testing with 3 REST API cases:

- Create with no ACL

`
curl -X POST \
-H "X-Parse-Application-Id: APPLICATION_ID" \
-H "Content-Type: application/json" \
-d '{"name": "Test No ACL"}' \
http://localhost:1337/parse/classes/Report
`

result: pass, the same as parse.com
database raw data:`
{
    "_id": "8Mal54rq2l",
    "name": "Test No ACL",
    "_created_at": {
        "$date": "2016-08-10T01:58:22.325Z"
    },
    "_updated_at": {
        "$date": "2016-08-10T01:58:22.325Z"
    }
}`

- Create with Master only(empty) ACL

`
curl -X POST \
-H "X-Parse-Application-Id: APPLICATION_ID" \
-H "Content-Type: application/json" \
-d '{"name": "Test Master ACL with REST", "ACL":{}}' \
http://localhost:1337/parse/classes/Report
`

result: failed, missing "_acl" key
database raw data:`
{
    "_id": "9iCmRh87vC",
    "name": "Test Master ACL with REST",
    "_wperm": [],
    "_rperm": [],
    "_created_at": {
        "$date": "2016-08-10T01:58:25.133Z"
    },
    "_updated_at": {
        "$date": "2016-08-10T01:58:25.133Z"
    }
}
`

- Create with User ACL

`
curl -X POST \
-H "X-Parse-Application-Id: APPLICATION_ID" \
-H "Content-Type: application/json" \
-d '{"name": "Test User ACL with REST", "ACL": {"gcZeooLouz": { "read": true, "write": true}}}' \
http://localhost:1337/parse/classes/Report
`

result:  pass, the same as parse.com
database raw data:`
{
    "_id": "NTvke6rjli",
    "name": "Test User ACL with REST",
    "_wperm": [
        "gcZeooLouz"
    ],
    "_rperm": [
        "gcZeooLouz"
    ],
    "_acl": {
        "gcZeooLouz": {
            "w": true,
            "r": true
        }
    },
    "_created_at": {
        "$date": "2016-08-10T01:58:28.087Z"
    },
    "_updated_at": {
        "$date": "2016-08-10T01:58:28.087Z"
    }
}
`

**Comment by flovilmart** [comment]
Awesome @jeffhuangtw, do you think you xan work on a fix or I can try to find some time for it.

**Comment by jeffhuangtw** [comment]
I may try to fix it, just need some time to be familiar with parse server.

**Comment by flovilmart** [comment]
Ok, getting familiar with the code base is not a bad thing :)

**Comment by flovilmart** [comment]
I believe the culprit line is there: https://github.com/ParsePlatform/parse-server/blob/master/src/Adapters/Storage/Mongo/MongoTransform.js#L356

I'll try to push a fix + regression test this morning.

**Comment by jeffhuangtw** [comment]
@flovilmart I tried to fix it yesterday, but it seems break some test cases, so I am not so sure if I fix it with the right way. Not sure if I fix the test cases will cause more bugs.
I will wait your pull request and add some new test cases.
