### ISSUE TITLE
Already set VERBOSE=1, but no error in the log though 99% requests are failed! 

### ISSUE THREAD

**Issue by shiguoning** [ParsePlatform/parse-server#2467]
Hello, I am running our self-hosted Parse server on AWS Elastic Beanstalk. There are about 20,000 req/min, but most of them ( near 99%) are failed with code 400. I got the logs, the nginx error.log said:

**[error] 18925#0: *93 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.31.21.5, server: , request: "POST /parse/classes/xxx HTTP/1.1", upstream: "http://127.0.0.1:8081/parse/classes/xxx", host: "xxx.us-east-1.elasticbeanstalk.com"**

access.log:
**[05/Aug/2016:11:01:36 +0000] "POST /parse/classes/xxx HTTP/1.1" 400 44 "-" "Parse Android SDK 1.13.0**
sometimes the request is successfully processed, and responds code 200:
**[05/Aug/2016:11:01:37 +0000] "POST /parse/classes/xxx HTTP/1.1" 200 14 "-" "Parse Android SDK 1.13.0**

I want to see what's going on with the Parse server, and set **VERBOS=1**, but the log files parse-server.err.[date] and parse-server.info.[date] only contained a few lines, most of them are:

**{"error":{"code":101,"message":"Object not found."},"level":"error","message":"Error generating response. ParseError { code: 101, message: 'Object not found.' }","timestamp":"2016-08-05T06:17:07.150Z"}**

Nothing more about why it failed nearly every time processing the POST or GET requests. The mongodb hosted on mLab is good because the Parse hosted server still works well while the self-hosted Parse server fails 99% requests, please help me locate the problem. 
Thank you!

**Comment by joeyslack** [comment]
The logging leaves a lot desired.

Until I fixed some critical errors in my code, I was not seeing what I wanted in logging. Try running your JS through a linter to detect issues you might have first.

My guess is that you aren't returning responses, or there is a critical error on your cloud calls.

**Comment by flovilmart** [comment]
@joeyslack, we welcome contributions that would improve logging :)

**Comment by joeyslack** [comment]
@flovilmart Working on it :) Customizing my logging for my project at the moment, I hope to share the final result once I've got a good solution.

**Comment by flovilmart** [comment]
Awesome! Thanks!

**Comment by flovilmart** [comment]
20000 requests per minute is about 350 req/seconds, how many servers are running on elastic beanstalk? It likely your scaling don't keep up with the request flow.
