### ISSUE TITLE
File URLs saved as 'http' instead of 'https'

### ISSUE THREAD

**Issue by tarekskr** [ParsePlatform/parse-server#2470]
All Parse 'File' URLs seem to be saved as http instead of https. For instance, my user's profilePicture link is stored as follows: "http://my-app.herokuapp.com/parse/files/BO01W5X7iHft27BSeFu6AuXcdEAEKpXzangdCM2P/95717dbc7897fd7580b784b502cc1787_file.bin"

This potential bug causes issues with iOS 9's App Transport Security, amongst others.

### Environment Setup

- **Server**
  - parse-server version: 2.2.17
  - Localhost or remote server? Heroku

- **Database**
  - Storage engine:  AWS S3
  - Localhost or remote server? mLab

**Comment by skinp** [comment]
@tarekskr the URL is actually build using the serverURL option that you specify when building a ParseServer object. Just use https in that serverURL option and you should be good...

Since you're using AWS S3, you could also use either the baseUrl or directAccess options to force usage of https.

**Comment by tarekskr** [comment]
@skinp Thank you very much for your reply. 

My 'serverURL' option does indeed use a 'https' URL, so I am still not sure why Parse Server builds the wrong one. 

I couldn't find any documentation describing 'baseUrl', would you kindly point me to any? Thanks again!

**Comment by MartinHerman** [comment]
@tarekskr there is one option you have to pass when configuring the ParseServer object. It's pretty vaguely mentioned here: https://github.com/ParsePlatform/parse-server/wiki/Configuring-File-Adapters

You should set `publicServerURL` to the same as `serverUrl` - that will be used as the base url for Parse Files.

I had the same issue, it went away after I configured this.

**Comment by tarekskr** [comment]
Will do! Thank you so much @MartinHerman
