### ISSUE TITLE
TypeError: Parse.Cloud.httpRequest is not a function

### ISSUE THREAD

**Issue by akshit-zaveri** [ParsePlatform/parse-server#2474]
Trying to call 3rd party API using cloud function (previously cloud job). But, keep running into the error mentioned as above.

**### Steps to reproduce**

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1. Deploy Parse-Server to Heroku. Tested everything from Parse dashboard to MongoDB. It works fine with the existing iOS/Android apps.
2. Migrate cloud job to job.js file.
3. From terminal, run `heroku run bash`. After successful connection, run `node ./cloud/job.js`

**job.js file**
 #!/usr/bin/env node
 var Parse = require('parse/node');
 Parse.initialize(process.env.APP_ID, process.env.JS_KEY, process.env.MASTER_KEY);
 Parse.serverURL = process.env.SERVER_URL;
 // Parse.Cloud.useMasterKey();

function testAPI() {
    var params = {
        method: "GET",
        url: "API_URL",
        params: {
        }
    };
    Parse.Cloud.httpRequest(params).then(function(httpResponse) {
        var postsNew = [];
        var posts = JSON.parse(httpResponse.text).response.posts;
        console.log("Response posts: " + posts.length);
        return postsNew;
    });
}
testAPI();

**#### Expected Results**

The code should run and data should be printed in log.

**#### Actual Outcome**

`$ node ./cloud/job.js
/app/cloud/job.js:20
    Parse.Cloud.httpRequest(params).then(function(httpResponse) {
                ^

TypeError: Parse.Cloud.httpRequest is not a function
    at testAPI (/app/cloud/job.js:20:17)
    at Object.<anonymous> (/app/cloud/job.js:34:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3`

### Environment Setup

- **Server**
  - parse-server version: 2.1.12
  - Operating System:     HOW TO GET THIS?
  - Hardware:             HOW TO GET THIS?
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

- **Database**
  - MongoDB version: 3.0.12
  - Storage engine:  AWS us-east-1
  - Hardware:        HOW TO GET THIS?
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

**Comment by bohemima** [comment]
I'd suggest using the"request" npm module directly.

**Comment by akshit-zaveri** [comment]
How do i do that? i am an iOS dev. So always lots of confusion with NodeJS code.

**Comment by bohemima** [comment]
https://github.com/request/request

It should be pretty straightforward from that.

**Comment by steven-supersolid** [comment]
Also please note that Parse.Cloud.httpRequest is only available inside a cloud code function whereas you are running client-side as evidenced by calling Parse.initialize().

**Comment by jeremypiednoel** [comment]
Thanks guys, found my answer here :)
