### ISSUE TITLE
Missing Push Configration

### ISSUE THREAD

**Issue by ankushmittal87** [ParsePlatform/parse-server#2487]
Hi ,

I managed to setup parse server locally and it is working fine with mongoDB. 

After successful entry into my database, needs to send push notification to all users for current status. But Parse.push.send is giving me error saying "Missing Push Configuration".

I suspect that I need to add some configuration of needs to setup something for parse push notification. I am new to this server thing so I might be doing very silly mistake.

Below is my parse push code.

`// Fire the push.
                                                Parse.Push.send({
                                                  where: query,
                                                  data: {
                                                    alert: identity + " bid $" + currentBid.get("amt") + " on " + item.get("name") + ". Surely you won't stand for this.", // People like sassy apps.
                                                    itemname: item.get("name"),
                                                    personname: identity,
                                                    itemid: item.id,
                                                    sound: "default",
                                                    amt: currentBid.get("amt"),
                                                    email: currentBid.get("email")
                                                  }
                                                }, {useMasterKey : true} ,  {
                                                  success: function() {
                                                    console.log("Pushed successfully.")
                                                  },
                                                  error: function(error) {
                                                    console.error("Push failed: " +error)
                                                  }
                                                } );
 `

Error is :- Error generating response. ParseError { code: 115, message: 'Missing push configuration' } code=115, message=Missing push configuration

**Comment by flovilmart** [comment]
Please refer to the push configuration pages https://github.com/ParsePlatform/parse-server/wiki/Push

**Comment by grantespo** [comment]
That link is not clear. I followed everything on it and am still getting the error.
