### ISSUE TITLE
Facebook login returning "unauthorized"

### ISSUE THREAD

**Issue by chuckurbis** [ParsePlatform/parse-server#249]
I've been trying to hook up Facebook login via an iPhone app. I have set the FACEBOOK_APP_ID on my Heroku deploy and even echoing it out to the log so I know that is being set. 

My iPhone app has all there correct information in the plist file. 

For some reason though, when I go through the connect process using, PFFacebookUtils.logInInBackgroundWithReadPermissions, the app always returns:

> unauthorized (Code: 0, Version: 1.12.0)

I'm not sure where to begin tracking this error down. I don't see anything in the log files either. 

Any help would be greatly appreciated. Thank you.

**Comment by francocorreasosa** [comment]
Did you set the facebookAppIds in the parse-server?
Related to #82

**Comment by chuckurbis** [comment]
No, I haven't. Is that part of the 
```
var api = new ParseServer({
   ...
});
```
Code? 
I didn't see that in the docs. IS that now the official way to do it and if so do i still need to set the env var FACEBOOK_APP_ID? 

Thank you.

**Comment by gfosco** [comment]
It is in the readme, you can pass in an array of facebook app ids: https://github.com/ParsePlatform/parse-server/blob/master/README.md

You no longer need to set the environment variable.

Let me know if you have any other issues!

**Comment by chuckurbis** [comment]
I'm actually still seeing the issue. This is what my code looks like 

```
var api = new ParseServer({
  databaseURI: databaseUri ,
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || '...',
  masterKey: process.env.MASTER_KEY || '...',
  clientKey: '...', 
  javascriptKey: '...',
  facebookAppIds: ['1677777875569507']
});
```

Is there something I'm missing with that?

**Comment by nathan-charles** [comment]
I'm still experiencing the same issue with Facebook login.

```
var api = new ParseServer({
	databaseURI		: "...",
	cloud			: "...",
	appId 			: "...",
	masterKey 		: "...",
	facebookAppIds 	: ["742406752547323"],
	filesAdapter 	: new S3Adapter(
		"...",
		".../",
		{
			bucket 			: "...",
			bucketPrefix	: "files/",
			directAccess	: true
		}
	)
});
```

**Comment by chuckurbis** [comment]
Figured out a why this was still not working. If I called Parse.setApplicationId and Parse.initializeWithConfiguration this error would still happen. Also note that if you use the local datastore, that needs to be set in the configuration block as well.

**Comment by nathan-charles** [comment]
I'm not calling Parse.setApplicationId in my code it has been commented out since I migrated. I'm getting the following error.

`Permission denied for this action. (Code: 101, Version: 1.12.0)`

**Comment by penultimate-labs** [comment]
I believe there's a bug in 2.1.0 with the RestWrite.js -> facebook.js data path. The validateAppId function in facebook.js assumes a passing of the literal access_token (String) but what's actually passed is an authData structure within which lives a key called "access_token".. so facebook.js should actually be trying to append access_token.access_token to the graph request, and not just access_token. More appropriately, the access_token argument of facebook.js:validateAppId should be renamed to authData and subsequently authData.access_token for the string builder contained within. As it is for validateAuthData.

**Comment by drew-gross** [comment]
cc @flovilmart

**Comment by flovilmart** [comment]
@penultimate-labs you're definitely right! The validateAppId should match the mockFacebook() in the test suite.

**Comment by thphuc** [comment]
@chuckurbis Can you share me how to fix this?

**Comment by tobernguyen** [comment]
have this issue been resolved?

**Comment by flovilmart** [comment]
Did you update to the latest version?

**Comment by tobernguyen** [comment]
Yes I did. The above error is when I use parse@2.1.6

**Comment by flovilmart** [comment]
Then Permission denied for this action is a Class Level Permission error. Did you set any CLP on _User? Can you provide the logs your get when running in VERBOSE=1

**Comment by tobernguyen** [comment]
My CLP on _User
![screen shot 2016-03-14 at 11 49 38 pm](https://cloud.githubusercontent.com/assets/10015525/13752039/7e4572cc-ea3f-11e5-9078-39f9efd57532.png)

Btw, I'm doing test with VERBOSE=1, will update when ready.

**Comment by flovilmart** [comment]
This would be the addFiled permission that would block I believe

**Comment by tobernguyen** [comment]
@flovilmart perfect! It works flawlessly. Do you still need the log when running in VERBOSE=1

**Comment by flovilmart** [comment]
I'd like to understand why it blocked you from linking the user, did you add extra fields to the _user object before linking?

**Comment by tobernguyen** [comment]
I do nothing on client side but I have the hook `afterSave` on _User on cloud code. I add some fields to **new User** only. But the weird thing is that I couldn't log in as a new user as well as existed user.

**Comment by flovilmart** [comment]
Ok, so we have an issue with the addFields permission.

**Comment by aguyngueran** [comment]
I just wanted to confirm that parse-server v2.2.14 denies to log in via Facebook (even for the existing accounts) if the "addFields" permission is not enabled on _User class.
