### ISSUE TITLE
disable input/result logs in 2.2.17

### ISSUE THREAD

**Issue by benishak** [ParsePlatform/parse-server#2490]
# Env
Parse Server 2.2.17

# problem
now 2.2.17 shows such logs in the console

info: beforeSave triggered for _User
```
Input: { ... }
Results: [{ .... }, .... ]
```

Verbose mode is off

**Comment by flovilmart** [comment]
in 2.2.18 there will be the logLevel options as well as silent option so you can disable completely console logging.

Otherwise start your server with `> /dev/null` to prevent any logs to be written
