### ISSUE TITLE
ParseError {   code: 107,   message: 'Received an error with invalid JSON from Parse: Cannot POST /parse/1 /push\n' }

### ISSUE THREAD

**Issue by Manpreet1322** [ParsePlatform/parse-server#2492]
I got this error in console, when I am trying to send push using migrated parse server URL, its working fine without parse.serverURL. I already used this url as serverUrl: http://localhost:1337/parse

Is there any migration problem?

**Comment by Manpreet1322** [comment]
I got this error in console, when I am trying to send push using migrated parse server URL, its working fine without parse.serverURL.

Is there any migration problem?

**Comment by ranhsd** [comment]
If you use parse server you should POST your request to the following URL :

http://localhost:1337/parse/push

**Comment by Manpreet1322** [comment]
Thank you for your reply:

I am using this code for parse push:

var query = new Parse.Query(Parse.Installation);
        query.equalTo('userObjectId', '--');

        Parse.Push.send({
            where: query,
            data: {
              alert: 'Testing .....',
              badge: 1,
              sound: 'default'
            }
          }, {
            useMasterKey: true,
            success: function() {
              console.log('Push sent!');
            },
            error: function(error) {
              console.log('There was a problem :(');
            }
          });

But it always return the above error.

**Comment by Manpreet1322** [comment]
I just update parse sdk version and its started working.
