### ISSUE TITLE
$in filter not available on Nodechef

### ISSUE THREAD

**Issue by Francesca85** [ParsePlatform/parse-server#2497]
Hi all,
we are migrating our apps from Parse to Nodechef server with self-hosted DBs on Object Rocket and we are experiencing some troubles in sending targeted push through the Nodechef Dashboard 
(We are unable to send any kind of push via Rest API for which we opened a dedicated issue)

We are currently using this kind of json with Parse:
{
 "expiration_time": "2016-04-02T21:44:46.000Z",
 "where": {
  "deviceType": "ios",
  "push_12": {
   "$in": ["item1", "item5", "item9", "item13", "item38"]
  }
 },
 "data": "{\"badge\":\"increment\",\"alert\":\"Text of the push notification\",\"sound\":\"default\",\"o\":\"201322\"}"
}

where "push_12" is a column of the installation class, in order to target devices that subscribed to  ANY OF those items.

Well, it just seem impossible to reproduce the same targeting through Nodechef dashboard because there is no equivalent to the "contains any of" filter we find on Parse.

If we use the "contains" operator from the dashboard we can't specify any string and indeed what we see form Chrome debugger is that the payload sent is the same as if we don't use any filter at all:

{"where":{"deviceType":{"$in":["ios","android"]}},"data":{"alert":"text of the alert","badge":"increment","o":"mondo-594092","sound":"default"},"_ApplicationId":"applicationid","_ClientVersion":"js1.6.14","_MasterKey":"masterkey","_InstallationId":"56205783-4f18-7427-919a-6e03ed80443a"}

While if we use the operator "contains string" we can specify a string but the payload sent doesn't correspond to what is currently generated from Parse:
{"where":{"push_12":"A|JUV|goal, A|EMP|goal, 201322|goal|20160726","deviceType":{"$in":["ios","android"]}},"data":{"alert":"Juventus-Empoli: MANDZUKIC!!!! JUVENTUS-EMPOLI 1-0!!!!","badge":"increment","o":"mondo-594092","sound":"default"},"_ApplicationId":"oVguKJeAj8sihSC8Q7SnVwHMGQoiZuRxq6p0C3c7","_ClientVersion":"js1.6.14","_MasterKey":"FBW3VyhGybnKvXP9ddhfcKV2xzSswHWrhI3CbStZ","_InstallationId":"56205783-4f18-7427-919a-6e03ed80443a"}

We would expect an "$in" for the "push_12" as is set for device type,

Any clues?

Thanks,

Francesca

**Comment by hramos** [comment]
The Parse Server REST API for push notifications should work in a similar manner to Parse.com hosted apps. It looks like this is something you might want to bring up with NodeChef directly. Closing as we're using this issue tracker for Parse Server issues.
