### ISSUE TITLE
At run "npm run dashboard"

### ISSUE THREAD

**Issue by braulioromero** [ParsePlatform/parse-server#2498]
npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "dashboard"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! parse-dashboard@1.0.15 dashboard: `node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --progress --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the parse-dashboard@1.0.15 dashboard script 'node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --progress --watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parse-dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --progress --watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parse-dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parse-dashboard
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/parse-dashboard/npm-debug.log

Any help, thanks I think I have the latest versions of npm and nodejs

**Comment by hramos** [comment]
You may want to open the issue against [parse-dashboard](/parseplatform/parse-dashboard). This repo is for Parse Server.
