### ISSUE TITLE
Parse server limitation

### ISSUE THREAD

**Issue by birdkingz** [ParsePlatform/parse-server#25]
Hi, I would like to know if we host on our own server. Does all the limitations that Parse mentioned still apply?
For example:
- Limit request per sec
- Maximum of 10,000 for query result

**Comment by Telemakhos** [comment]
Your server, your limits... :grin:

**Comment by jamesyu** [comment]
There are no limits applied by Parse Server itself. But of course, there are limits to what your infrastructure can serve. Also, you would want to limit the query so the client isn't waiting a long time to receive data, which might degrade UX.

@Telemakhos has it right though: it's really up to *you* to set your limits!
