### ISSUE TITLE
Make Logging More Useful

### ISSUE THREAD

**Issue by acinader** [ParsePlatform/parse-server#2501]
With regard to logging of hooks and functions:

1. The amount of data that is being logged with each hook invocation can be enormous in our application.

2. Structured data is being stuck into the message as a string and then also being included in metadata

I suggest that in FunctionsRouter.js and triggers.js removing the stringified params, results and errors from the message and just leaving them as objects in the meta info object that is also being passed to the logger.

Add the user if it exists to the meta info.  

Additionally, add a truncate logs config option that will prevent the logged meta info from going deeper than one level (i.e. if an array of 10 stories is returned, replace contained objects with just the objectId and not the whole object and its contents).

Seeking input here. If there's some agreement that this would be a useful change, I'll cook it up and submit a pr.

**Comment by jpv123** [comment]
I think this is a really good idea. The big ammount of info that is currently logging on the server is just giving me a headache and not any useful. I would love to make a PR about this but unfortunately I don't have the knowledge to do so

@acinader could you please help with this?

**Comment by flovilmart** [comment]
@acinader we just merged #2478 that adds a ton of changed in the logging infrastructure

**Comment by acinader** [comment]
Thanks @flovilmart.  What do you think of my suggestion?   I'd also add an option to truncate text at a limit.

**Comment by flovilmart** [comment]
>  suggest that in FunctionsRouter.js and triggers.js removing the stringified params, results and errors 

This was to match parse.com implementation of logging, some people were pissed that there was no logs on hooks invocations, I don't want to go back there :)

> Add the user if it exists to the meta info.

Agreed, that won't reduce the volume though :)

> Additionally, add a truncate logs config option that will prevent the logged meta info from going deeper than one level

Why not, but the response should be meaningful too. I would suggest to playing around with different options / solutions, and provide the result logs in the PR :)

**Comment by acinader** [comment]
The truncation is what parse.com does now... in any event, yes output and unit test goodness will be part of the pr ;).  Thinking it through now and will try and get started next week.

**Comment by flovilmart** [comment]
Awesome, it maybe can be part of the loggerController :)
