### ISSUE TITLE
Unable to save an object that has a Pointer<_User> column

### ISSUE THREAD

**Issue by bourquep** [ParsePlatform/parse-server#2504]
### Issue Description

In my Parse database, I have a class that has a column of `Pointer<_User>` type.

In a Cloud Code function, when trying to save a new instance of this object after setting it's `user` attribute to a freshly signed-up `Parse.User` object, I get this error:

```
ParseError {
  code: 111,
  message: 'schema mismatch for GoogleAuth.user; expected Pointer but got Object' }
```

The Cloud Function has been running without any issues on `api.parse.com` for a year, and it was running fine on `parse-server` version 2.2.7. 

It stopped working when I upgraded parse-server from v2.2.7 to v2.2.16.

### Steps to reproduce

* Have a class that has a `user` attribute of type `Pointer<_User>`
* Have a Cloud Function that does:

```javascript
Parse.User.signUp(username, password).then(function(user) {
    if (user)
    {
        googleAuth = new model.GoogleAuth();
        googleAuth.set('googleIdToken', idToken);
        googleAuth.set('googleId', googleId);
        googleAuth.set('googleEmail', googleEmail);
        googleAuth.set('user', user);
        googleAuth.setACL(restrictedAcl);

        return googleAuth.save(null, {useMasterKey: true});
    }
});
```

#### Expected Results

A new instance of `GoogleAuth` should be saved to the database, with a pointer to the signed-up user in its `user` column.

#### Actual Outcome

Error when saving the `GoogleAuth` object:

```
ParseError {
  code: 111,
  message: 'schema mismatch for GoogleAuth.user; expected Pointer but got Object' }
```

### Environment Setup

- **Server**
  - parse-server version: 2.2.16 and 2.2.17
  - Operating System:     Amazon Linux 4.4.14-24.50.amzn1.x86_64
  - Hardware:             Amazon `m3.medium` EC2 instance managed by Elastic Beanstalk
  - Localhost or remote server? AWS Elastic Beanstalk

- **Database**
  - MongoDB version: 3.0.9
  - Storage engine:  MMAPv1
  - Hardware:        mLab sandbox database
  - Localhost or remote server? mLab

**Comment by kwstasna** [comment]
That's because you don't define to your cloud code that the `user` is a pointer.
https://www.parse.com/questions/save-a-string-in-a-as-a-pointer-in-cloud-code

**Comment by bourquep** [comment]
I don't follow you. In my schema, `user` is defined as a pointer to a `_User` class. And I set it to a `user` that is returned from `signUp`.

**Comment by kwstasna** [comment]
Try to save the object id of the user.

**Comment by flovilmart** [comment]
I recommend you don't use login and signup in CloudCode. You should use something like:

let user = new Parse.User();
user.save({
username: '',
password: ''}, {useMasterKey: true}).then(function() {
 // do something with the user.

});
