### ISSUE TITLE
Your data export for creakfast failed

### ISSUE THREAD

**Issue by keremsertan** [ParsePlatform/parse-server#2505]
when i try to export my app files parse send me an email and say "Your data export for creakfast failed". 

Hi there,

Unfortunately, there was an issue with your data export. Please try again by going to your app's settings page and clicking the export button.

We apologize for this inconvenience. If this issue persists, please let us know. Replies to this email are not monitored.

Cheers,
Team Parse

**Comment by bohemima** [comment]
Hey, please open a issue at the Facebook bug tracker, this repository is for the open-source parse-server.
