### ISSUE TITLE
Does parse server code include push notifications systems.

### ISSUE THREAD

**Issue by rajkotraja** [ParsePlatform/parse-server#251]
Till now, parse has been providing me notifications solutions, but now as it is closing down, i need to migrate to some other solution.
Will setting up a parse server on my own server (VPS or dedicated) solve the issue and would i be able to operate with as simplicity as i used to with parse service and dashboard.
Does parse server code include push notifications system and UI.

Do let me know so it can clear my doubts about the parse server code and its migration capabilities, thank you

**Comment by natanrolnik** [comment]
Push is coming really soon to parse-server, but it hasn't been implemented already.
It's worth waiting to check it out, and if it's not, take a look at OneSignal, PushWoosh, or other providers.
If it answers your questions, close this issue :smile:

**Comment by gfosco** [comment]
Should be active within 1 week.  Parts of it are being added in currently open pull requests.  Hang in there! :santa:
