### ISSUE TITLE
Can't connect to MongoDB from localhost after renewing SSL cert

### ISSUE THREAD

**Issue by Kinzi** [ParsePlatform/parse-server#2512]
Hi,

when I run my server on localhost and run a request to the db on Digital Ocean I get this error in the Terminal:

`error: Uncaught internal server error. { [MongoError: certificate has expired] name: 'MongoError', message: 'certificate has expired' } Error: certificate has expired
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1017:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
    at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)`

The code is the same as on my server (no problems there) and also used to work from localhost without a problem.

The only thing that changed since it last worked is that I renewed my let's encrypt certificate.

I found this issue here: https://github.com/ParsePlatform/parse-server/issues/1026

But since everything worked well before renewing the SSL cert I was wondering if there is anything else I could do about it then pointing to the cert in index.js? 

Thanks for your help!

### Environment Setup

- **Server**
  - parse-server version: 2.2.10
  - Operating System:     OSX
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: v3.0.12
  - Localhost or remote server?: Digital Ocean

**Comment by Kinzi** [comment]
OK. Solved it. SSL Cert was not properly setup.

**Comment by faruktoptas** [comment]
I faced the same problem. The problem is that when i renew letsencrypt certificate it generated **fullchain2.pem,privkey2.pem** files. But I copy generated the mongodb.pem file with this command (with old certificates):
sudo cat /etc/letsencrypt/archive/example.com/{**fullchain1.pem,privkey1.pem**} | sudo tee /etc/ssl/mongo.pem

Don't forget to use new certificate files.
