### ISSUE TITLE
Doc for getting parse-server up and running using mlab and hyperdev?

### ISSUE THREAD

**Issue by AndrewLane** [ParsePlatform/parse-server#2514]
Hello,

I was able to get parse-server up and running by importing the parse-server-example repo into the HyperDev tool and pointing it at a free mlab database.  I thought documenting this process might be great for onboarding, as someone could try out parse server without installing a single thing.  Thoughts?  I'd be willing to write up the documentation...perhaps add it just as markdown documentation that could be linked from the main documentation?

https://mlab.com
https://hyperdev.com

**Comment by hramos** [comment]
The guide would be appreciated. We've been collecting all of these in the wiki: https://github.com/ParsePlatform/parse-server/wiki

**Comment by AndrewLane** [comment]
@hramos  OK.  Since doing a pull request on the wiki repo isn't supported, I "manually" forked it and added some proposed documentation here.  So, consider this my pull request :-).

https://github.com/AndrewLane/parse-server-wiki/commit/2f72c4bf26c9717888dfd7cc9ad707ca84b005f4

https://github.com/AndrewLane/parse-server-wiki/blob/master/Running-Parse-Server-with-HyperDev-and-mLab.md

**Comment by AndrewLane** [comment]
@hramos Also added this commit that adds a document for getting Parse Dashboard up and running on HyperDev, but that kind of doc should be here, in the parse-dashboard repo, or both?

https://github.com/AndrewLane/parse-server-wiki/commit/fb0276101a85fcf095fae70fbf81da55b88e49f7

**Comment by flovilmart** [comment]
I'lol try to merge and push

**Comment by flovilmart** [comment]
Merged!
