### ISSUE TITLE
JSON text did not start with array or object and option to allow fragments not set.

### ISSUE THREAD

**Issue by shawn458** [ParsePlatform/parse-server#2517]
#### Problem

I am getting the following response when I try to call [PFCloud callFunctionInBackground:] in my iOS app.

`Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.`

My configuration in the AppDelegate looks like:
`[Parse initializeWithConfiguration:[ParseClientConfiguration configurationWithBlock:^(id<ParseMutableClientConfiguration> configuration) {
        configuration.applicationId = @"MY0PjsEc4aLZaWWoiYPnb4cju4VoKN7zyR41FPnR";
        configuration.server = @"https://myappname.herokuapp.com/parse";
    }]];`

The interesting thing is Parse.Cloud.beforeSave function works as expected. Only when I am requested data back this issue appears.

### Environment Setup

- **Server**
  - parse-server version: 2.2.17
  - npm version: 3.8.6
  - node version: 4.3
  - parse-dashbboard version: 1.0.15
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

- **Database**
  - MongoDB version: 3.0.9
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

Any help is appreciated

**Comment by shawn458** [comment]
Information from the log:

`2016-08-14T18:26:39.200Z - REQUEST for [GET] /parse/scriptlog?level=info&n=100: {}
2016-08-14T18:26:38.413Z - RESPONSE from [GET] /parse/scriptlog?level=error&n=100: {
  "response": []
}
2016-08-14T18:26:38.409Z - REQUEST for [GET] /parse/scriptlog?level=error&n=100: {}
2016-08-14T18:26:29.580Z - RESPONSE from [GET] /parse/scriptlog?level=info&n=100: {
  "response": [
    {
      "method": "GET",
      "url": "/parse/scriptlog?level=info&n=100",
      "headers": {
        "host": "myapp.herokuapp.com",
        "connection": "close",
        "origin": "https://myapp.herokuapp.com",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36",
        "content-type": "text/plain",
        "accept": "*/*",
        "referer": "https://myapp.herokuapp.com/dashboard/apps/myapp/logs/info",
        "accept-encoding": "gzip, deflate, br",
        "accept-language": "en-US,en;q=0.8",
        "x-request-id": "19c43ba7-27df-457d-ad91-328b9d39b55d",
        "x-forwarded-for": "66.25.23.106",
        "x-forwarded-proto": "https",
        "x-forwarded-port": "443",
        "via": "1.1 vegur",
        "connect-time": "1",
        "x-request-start": "1471199189519",
        "total-route-time": "0",
        "content-length": "218"
      },
      "body": {},
      "level": "verbose",
      "message": "REQUEST for [GET] /parse/scriptlog?level=info&n=100: {}",
      "timestamp": "2016-08-14T18:26:29.562Z"
    },
    {
      "method": "POST",
      "url": "/parse/functions/GetUserList",
      "headers": {
        "host": "myapp.herokuapp.com",
        "connection": "close",
        "accept": "*/*",
        "x-parse-session-token": "r:5c56c9af7c9c9291b219f9ddef09e2fd",
        "x-parse-application-id": "MY0PjsEc4aLZaWWoiYPnb4cju4VoKN7zyR41FPnR",
        "x-parse-installation-id": "0cb4e8c9-1a07-4cf7-9c1f-ba360fe15f36",
        "x-parse-os-version": "9.3 (15G31)",
        "accept-language": "en-us",
        "accept-encoding": "gzip, deflate",
        "x-parse-client-version": "i1.14.2",
        "user-agent": "MyApp/1 CFNetwork/758.3.15 Darwin/15.6.0",
        "x-parse-app-build-version": "1",
        "x-parse-app-display-version": "1.0",
        "x-request-id": "5594dac1-721e-4782-b328-9da7f14cd998",
        "x-forwarded-for": "66.25.23.106",
        "x-forwarded-proto": "https",
        "x-forwarded-port": "443",
        "via": "1.1 vegur",
        "connect-time": "1",
        "x-request-start": "1471198467541",
        "total-route-time": "0",
        "content-length": "0"
      },
      "body": {},
      "level": "verbose",
      "message": "REQUEST for [POST] /parse/functions/GetUserList: {}",
      "timestamp": "2016-08-14T18:14:27.628Z"
    }
  ]
}
2016-08-14T18:26:29.562Z - REQUEST for [GET] /parse/scriptlog?level=info&n=100: {}
2016-08-14T18:14:27.628Z - REQUEST for [POST] /parse/functions/GetUserList: {}`

**Comment by shawn458** [comment]
I played around with this more and I am able to run a simple hello world cloud function. I get the
'Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.'
when I run any function that returns something.

Here is the cloud code I am calling:
'Parse.Cloud.define('test', function(request, response) {
	var query = new Parse.Query('TestClass');

	query.find({
		success: function(results) {
			response.success(results);
		}, error: function(theerror) {
			response.error('user lookup failed: %@', error);
			console.log(theerror);
		}
	});	
});'

**Comment by shawn458** [comment]
Turns out I just wrote the Cloud Code wrong. Closing.

**Comment by wellkeptbeauty** [comment]
Parse.Cloud.define("test", function(request, response) {
    var query = new Parse.Query("Classname");

    query.find({
        success: function(results) {
            response.success(results);
                        console.log(results);

        }, error: function(theerror) {
            response.error("user lookup failed: %@", error);
            console.log(theerror);
        }
    }); 
});

here is  my cloud code , when i am calling this cloud code from application following error shows


error:Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
