### ISSUE TITLE
MongoDB + RocksDB recommended readahead setting

### ISSUE THREAD

**Issue by asdf01** [ParsePlatform/parse-server#2521]
Hey Guys

Looking at this ec2 config guide: 
https://docs.mongodb.com/ecosystem/platforms/amazon-ec2/
It suggests to set the read ahead setting to 32 blocks / 16kb.  But I'm guessing this recommendation is only relevant to ebs backed storage.  

But with mongodb on the rocksdb storage engine writing to a striped instance storage ssd based array recommended here: 
https://github.com/ParsePlatform/parse-server/wiki/MongoRocks
the disk access characteristics are completely different is that right?  

What is the recommended ra setting for this setup?  Thanks.

**Comment by flovilmart** [comment]
@asdf01 thanks for the question, but you'd probably want to open that on the MongoRocks repository / ask it on stackoverflow / serverfault as our competences don't cover those specifics.
