### ISSUE TITLE
Concerns about Write Concern

### ISSUE THREAD

**Issue by asdf01** [ParsePlatform/parse-server#2522]
Hey Guys

What is everyone setting their write concern value to?  

I got a bit concerned when I read this:
> acknowledge write operations after applying the write in memory

https://docs.mongodb.com/manual/reference/write-concern/

We're running a rocksdb engine with aws instance storage based ssd raid array.  The rocksdb page doesn't go into details:
https://github.com/ParsePlatform/parse-server/wiki/MongoRocks
but I'm guess when the instance dies, we lose any data that hasn't been replicated to the secondary nodes in the replica set. 

Based on this, I'm guessing I should be setting my write concern value to 2 instead of the default 1.  I'm guessing this allows us to leverage the performance benefits of the rocksdb storage engine while still preserving some level of data durability when the aws instance inevitably dies.  

Are there any known issues with these write concern thingys?  e.g.
- are they known for blocking for no apparent reason causing writes to fail to the application layer? 
- do they slow down the performance of the primary by a lot?
- do people in parse land actually care about this or is loss of data just something users of nosql databases just put up with for the sake of better performance?  

Thanks.

**Comment by flovilmart** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Parse Server.

This questions is highly specific to MongoRocks, you should probably ask it on a dedicated forum where the MongoRocks/MongoDB community will be more active
