### ISSUE TITLE
Incorrect date format returned via cloud code

### ISSUE THREAD

**Issue by tanmays** [ParsePlatform/parse-server#2524]
I'm not sure whether this issue belongs to parse-server or dashboard. Please let me know if its in the wrong place.

I am facing an issue where in dates for custom date type records is returned in format: 

```
"deliveredAt": {
            "__type": "Date",
            "iso": "2016-08-15T07:14:49.383Z"
          }
```

While default date types such as createdAt and updatedAt are returned correctly in format

```
"createdAt": "2016-08-15T07:14:46.393Z",
"updatedAt": "2016-08-15T07:17:30.770Z"
```

In the first example `deliveredAt` column was created via Parse-Dashboard. On checking the schema its as follows: 

```
{
    "_id": "xxxClassNameHerexxx",
    "objectId": "string",
    "updatedAt": "string",
    "createdAt": "string",
    "deliveredAt": "date",
}
```

It looks like the object type for default dates is `string` whereas when you create a date type column via Dashboard its type is set to `date`

**My setup:** 

parse-server 2.2.17
parse-dashboard 1.0.15
All results are returned via cloud code

**Comment by bohemima** [comment]
The { "__type": "Date" } variant is correct, the various SDKs then handles it and converts it to the language Data-class. createdAt/updatedAt as Strings is probably because of some legacy code.

**Comment by hramos** [comment]
What @bohemima said - this is for legacy reasons, as this is the way the Parse.com API behaved.
