### ISSUE TITLE
Version 2.2.17 is breaking webpack + babel transpiled cloud code.

### ISSUE THREAD

**Issue by 5amfung** [ParsePlatform/parse-server#2529]
### Issue Description

I have been using version 2.2.16 and transpiled cloud code using webpack and babel.  However updating parse-server to version 2.2.17,  I would get the following error when I start up parse-server.  Even a simple `hello` cloud function wouldn't work.  It seems that something is changed in 2.2.17 such that the cloud functions are load differently and affected how transpiled code is loaded.  Any help would be very much appreciated.

```
to be executed: node index.js 
/Users/foo/src/foo-parse-server/cloud/main.js:75
	_node2.default.Cloud.define('hello', function (req, res) {

TypeError: _node2.default.Cloud.define is not a function
    at Object.<anonymous> (/Users/foo/src/foo-parse-server/cloud/main.js:75:23)
    at __webpack_require__ (/Users/foo/src/foo-parse-server/cloud/main.js:20:30)
    at /Users/foo/src/foo-parse-server/cloud/main.js:40:18
    at Object.<anonymous> (/Users/foo/src/foo-parse-server/cloud/main.js:43:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at new ParseServer (/Users/foo/src/foo-parse-server/node_modules/parse-server/lib/ParseServer.js:268:9)
    at new _ParseServer (/Users/foo/src/foo-parse-ser
```

### Steps to reproduce

This is how I transpile the cloud code from `src/` to `cloud/`.
```
$ node_modules/.bin/webpack --progress --show-modules
```

This is what I have in `webpack.config.js`.
```
var path = require('path');
var nodeExternals = require('webpack-node-externals');

module.exports = {
    target: 'node',  // Ignore built-in modules like path, fs, etc
    externals: [ nodeExternals() ],  // Ignore node_module.
    entry: './src/main.js',
    output: {
        path: './cloud/',
        filename: 'main.js'
    },
    module: {
        loaders: [
            {
                exclude: /node_modules/,
                loader: 'babel-loader'
            }
        ]
    }
};
```

In terms of versions of webpack and babel, I'm using these.  I don't think these matter because it worked in parse-server version 2.2.16.
```
    "babel-core": "~6.11.4",
    "babel-loader": "~6.2.4",
    "babel-preset-es2015": "~6.9.0"
    "webpack": "~1.13.1",
    "webpack-node-externals": "~1.3.3"
```

#### Expected Results

parse-server should run without any error.

#### Actual Outcome

See description above.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.17
  - Operating System: Mac 10.11.6
  - Hardware: iMac
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost

- **Database**
  - MongoDB version:  mlab
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [FILL THIS OUT]

### Logs/Trace

See description above.

**Comment by osolano** [comment]
I also have this same issue with the latest update! Any suggestions to fixing this?

**Comment by flovilmart** [comment]
seems that web pack is transpiring Parse to `_node2.default`, that won't work... It needs to be just `Parse` as it's defined in the global scope.

**Comment by srameshr** [comment]
@5amfung Did you figure this out? Can you please share the workflow of how you are transpiling ES6 code?
Im using ES6 + ES7 code and it works locally because my node version is 8.3. When I deploy to AWS it breaks.

**Comment by vshy108** [comment]
I faced same problem when I installed parse-server 2.7.4 with parse 1.9.2. The problem solved after I installed the parse with the one work with parse-server 2.7.4 which is 1.11.1.
