### ISSUE TITLE
Migration Timeline

### ISSUE THREAD

**Issue by talkaboutdesign** [ParsePlatform/parse-server#253]
What the hell is this? 4 Months on empty database? 

<img width="757" alt="screen shot 2016-02-04 at 8 24 49 pm" src="https://cloud.githubusercontent.com/assets/2926534/12835359/7bb7b280-cb7d-11e5-9e65-9879998ba279.png">

**Comment by drew-gross** [comment]
This just means your job is still in the queue (we are getting higher volume than expected). If you still see this issue after a few days, please contact support with your migration ID at parse.com/help

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-server/releases/tag/5.0.0)
