### ISSUE TITLE
_User.authData should not store tokens that expire

### ISSUE THREAD

**Issue by steven-supersolid** [ParsePlatform/parse-server#2532]
version: 2.2.17 (all versions)

Steps to reproduce
1. Create a _User with a Google id_token which typically has a 1 hour expiration
2. Wait until the token expires
3. Add valid Facebook authData to the _User and save
4. Save will fail because the entire authData is checked, including the expired Google id_token

I think the access_token property of authData really only needs to be checked when updated authData is supplied and there is little point storing this in the database.

**Comment by flovilmart** [comment]
Can you provide the logs when running with VERBOSE=1?

**Comment by steven-supersolid** [comment]
I'll set something up but may take a couple of days. It may not be an issue for most people because creating a user is fine. We didn't see this on parse.com because there the only option is to link with Facebook and to reproduce requires support for multiple authData providers.

I can probably put in a PR too, thinking of changing RestWrite.validateAuthData() and transformUser().

**Comment by flovilmart** [comment]
I don't see in the current code that we're re-validating stored  token. So you may put a test together first?

**Comment by steven-supersolid** [comment]
I've identified the issue in our application code - when linking, authData should only contain the additional provider info, not existing provider.

We were doing:
```
var authData = user.get('authData');
authData[provider] = additionalAuthData;
user.set('authData');
user.save();
```
The correct method is:
```
var authData = {};
authData[provider] = additionalAuthData;
user.set('authData');
user.save();
```
This is consistent with the REST docs.

However, I would still like us to consider not storing access_token in authData as a feature request.

**Comment by flovilmart** [comment]
He access token can be useful if you need to run calls against the service. I won't move to remove it as it may be in use by many.

**Comment by steven-supersolid** [comment]
The token we are storing for google authentication is currently the id_token which doesn't give access to APIs. The token also expires after 1 hour. Apple authentication uses a similar token (which is also quite verbose).

However, it makes sense that we shouldn't remove existing functionality.
