### ISSUE TITLE
Two chained Parse.Object.saveAll() results in last objects NOT having their properties available

### ISSUE THREAD

**Issue by MobileVet** [ParsePlatform/parse-server#2535]
### Issue Description

If I chain together 2 saveAlls, I would expect to be able to access the objects saved in the second call.  However, strangely, those objects do not respond to `object.get("property")` instead returning undefined.

### Steps to reproduce

1. `Parse.Object.saveAll(obj)`
2. `.then(Parse.Object.saveAll(otherObjs)`
3. `.then(function(otherObjs) {});`

#### Expected Results

I should be able to call **.get("property")** on one of the objects returned.  This works fine if I don't chain the saveAlls but instead move the first one elsewhere in the code.

#### Actual Outcome

```
  function something() {
    var logs = new Array();
    var receipts = new Array();

    // fill the arrays with valid Parse.Objects

    return Parse.Object.saveAll(logs,{sessionToken: token})
            .then(Parse.Object.saveAll(receipts,{sessionToken: token}));

  }).then(function(receipts) {
    console.log(receipts[0].id);                          // will print valid objectId if length > 0
    console.log(receipts[0].get("property");    // prints UNDEFINED, despite 'property' being valid
    console.log(JSON.stringify(receipts[0]));   // prints out the object like I would expect
  });
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.1.15
  - Operating System:     OS X 10.11.6
  - Hardware:                   MBP
  - Localhost or remote server? Localhost

**Comment by hramos** [comment]
Hmm, if JSON.stringify() shows that the object has the data you'd expect it to have, then it seems like this may be a Parse JavaScript SDK issue given that the server is returning the necessary data.  If you agree, can you submit the issue to [the Parse JS SDK repo](/parseplatform/parse-js-sdk)?

**Comment by MobileVet** [comment]
Hmm, good call.  
Moving to: https://github.com/ParsePlatform/Parse-SDK-JS/issues/331
