### ISSUE TITLE
High response time from Installation Query

### ISSUE THREAD

**Issue by miracle7** [ParsePlatform/parse-server#2537]
- [X] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.

- [X] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases

- [X] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.

- [X] You have filled out every section below. Issues without sufficient information are more likely to be closed.

--

### Issue Description

Our Parse-Server app is experiencing very poor response times, seemingly due to a large amount of Installations being queried with the following:
`{"$or":[{"deviceToken":"<val>"},{"installationId":"<val>"}]}`

![image](https://cloud.githubusercontent.com/assets/5317556/17723904/10e3698e-6481-11e6-8496-77d175bb4b1e.png)

I don't have that particular query in my code, so it seems that it is something parse is calling internally. @flovilmart is this related to the changes you made to Installation queries recently?

On our production server there are about 300,000 Installation objects, and probably a lot more to come when we get featured on the play store next week, so I am worried what this will do to the application.

Based on the metrics from Heroku, NewRelic and mLab (posted below) I don't think it is just a matter of requiring a beefier plan or more dynos, since no limits are really being hit.

If anyone could advise me as to what I can do to further diagnose this problem and improve response times / scalability of the app I would really appreciate it, since at the moment it is looking pretty hopeless.

### Steps to reproduce

Run Parse-Server app with 300k Installations connecting with dot net SDK (Unity).

#### Expected Results

Response times below 500ms on average.

#### Actual Outcome

High response times (in the thousands).

### Environment Setup

- **Server**
  - parse-server version: 2.2.17
  - Heroku
  - 1x Standard Dyno

- **Database**
  - MongoDB version: 2.1.18
  - mLab
  - Dedicated Cluster M1

### Logs/Trace

I am not seeing any specific logs that are suspicious, apart from the occasional error: 

> error: Error generating response. ParseError { 
Aug 16 18:56:03 torque-prod app/web.1:    code: 135, 
Aug 16 18:56:03 torque-prod app/web.1:    message: 'at least one ID field (deviceToken, installationId) must be specified in this operation' } code=135, message=at least one ID field (deviceToken, installationId) must be specified in this operation

 which seems like it may be related based on query mLab has flagged as being slow (deviceToken or installationId).

Here are some screenshots of various metric software, hopefully someone else can dig out more information from this than I have been able to:

**Heroku**
![image](https://cloud.githubusercontent.com/assets/5317556/17724416/3ad44bba-6485-11e6-84b7-3c66324a5df2.png)

**NewRelic**

_Overview:_
![image](https://cloud.githubusercontent.com/assets/5317556/17723888/dfda267a-6480-11e6-97b9-6670813d3ed7.png)

_Transactions:_
![image](https://cloud.githubusercontent.com/assets/5317556/17724070/41326b52-6482-11e6-9a5e-e3a2afde57d3.png)

_Transaction Trace:_
![image](https://cloud.githubusercontent.com/assets/5317556/17724082/69ffecbc-6482-11e6-9a15-4f3a58dc809b.png)

**mLab**

![image](https://cloud.githubusercontent.com/assets/5317556/17724517/0cf37094-6486-11e6-8ccf-379974faf35a.png)

**Comment by flovilmart** [comment]
Try indexing each columns independently, see how it goes. That should help given those aren't indexed by default.

Mongo should also have some tools to go deeper and see the #of scanned documents. When indexed, that should be pretty fast as it's an OR query.

@TylerBrock may have more answers than me regarding mongo indexes optimizations.

You're right, I've updated some code related to installationID / device token resolution to run in only one query instead of 3 consecutive ones. There may be more optimization to look for here.

**Comment by miracle7** [comment]
@flovilmart seperate indexes worked, thank you so much! :D

Down from 1500ms average to 50ms :)

![image](https://cloud.githubusercontent.com/assets/5317556/17725563/b8028822-648f-11e6-89a9-4b2f046f90b1.png)

**Comment by flovilmart** [comment]
Nice.

**Comment by flovilmart** [comment]
Nice.

**Comment by caltv** [comment]
@miracle7  I'm having the exact same problem, saving / updating an installation object is taking upto 8 seconds. Could you share the changes you made to the indexes? Thanks!
