### ISSUE TITLE
Twitter Login failing on Parse Server, working on Parse Endpoint. 

### ISSUE THREAD

**Issue by JustK2** [ParsePlatform/parse-server#2542]
Hi, 

We are running Parse Server (node.js), AWS, MongoDB or Mlab and attempting a Twitter Oauth. When connecting to Parse Server instance on AWS we get the following:

[;[fg153,102,51;2016-08-17 18:21:14:251 1moment debug development[main] D OMLoginViewController.m:189 | signed in as r1moment
[;2016-08-17 18:21:14.605 1moment debug development[3650:1359145] [Error]: Twitter auth is invalid for this user. (Code: 101, Version: 1.14.0)
[fg255,0,0;2016-08-17 18:21:14:662 1moment debug development[main] E OMLoginViewController.m:205 | error: Twitter auth is invalid for this user.

So Twitter returned a valid session, no error, but when that auth is passed to Parse, it fails. If we run the same code, but set the end point back to Parse.com server it works fine. 

Please advise. 

Thanks.
KB.

**Comment by flovilmart** [comment]
Can you provide the parse-server logs running with VERBOSE=1? Do

**Comment by JustK2** [comment]
Yes, we are working on this - please standby.

**Comment by batkov** [comment]
Hi,
I'm working on "after login" issue in my proj, so I'm logging in few times in a minute.
I did login 5 times, than got 3-4 times error described here.
In few minutes everything started working again.

**Comment by flovilmart** [comment]
@batkov can you provide the logs when running with VERBOSE=1 on Parse-server?

**Comment by JustK2** [comment]
Ours is working now...if @batkov is okay you can close this one.

**Comment by flovilmart** [comment]
@JustK2 how did you resolve your issue?

**Comment by JustK2** [comment]
We had a space in our config file. :/
