### ISSUE TITLE
iOS - ParseError: Session Invalid

### ISSUE THREAD

**Issue by DrBeak1** [ParsePlatform/parse-server#2543]
Today I'm seeing a lot of `session invalid` errors. Are session tokens now set to expire at a given point? Logging out and back in fixes the issue, but I remember this wasn't the case previously. 

ios pod: 1.12.0
parse-server: 2.2.17

**Comment by DrBeak1** [comment]
Ah - I'm guessing this is related to legacy tokens ... is there a way to set tokens to never expire?

**Comment by flovilmart** [comment]
If you're still using legacy session tokens, (not starting with 'r:') this is not supported on parse-server.

We strongly enforce invalid session tokens sent to parse-server so you don't end up in a situation where you can't access your ACL protected data without any feedback.
