### ISSUE TITLE
Error code 2. The service is currently unavailable.

### ISSUE THREAD

**Issue by johnturnham** [ParsePlatform/parse-server#2555]
Using saveAll within a Parse Job to insert a batch of new objects into a remote mLab DB fails randomly with error object {"code":2,"message":"the service is currently unavailable"}. This error arose when when saving 6,000 new objects from this Job.

In an attempt to diagnose the issue, I separated the 6,000 objects into batches of objects and used saveAll on each batch. I've tested with batches as small as 10 objects and as many as 250 objects. Although the result is the same, this provided more information...

Most of these batches would be processed successfully, while one or more batches would occasionally fail with this message. Sometimes none fail. As a whole, the save process only succeeds without failure only about 50% of the time. The batches which fail seem completely random, even when using identical input (in this case, a CSV file) for each attempt.

The folks at mLab have investigated on their end for network connectivity issues, failed connection pooling, and other server resource limits. They've been very responsive and helpful. So far, there is no indication of issue on their end. We've tried reproducing this issue against a different, dedicated database cluster with more horsepower and yet the problem remains.

The error object described above appears to be an Internal Error Code originating from within Parse, although no specific details are available to troubleshoot this error code.

### Steps to reproduce

The code below retrieves a CSV file, parses it, then creates objects for inserting. However, another Parse user has reproduced this issue 8 months ago and requested assistance with it via StackOverflow. Their code is much simpler, yet it still produces the error (accessible here: http://stackoverflow.com/questions/33932963/parse-com-background-job-fail-the-service-is-currently-unavailable )

My code is as follows...

1. Option #1: Save all records in one saveAll.
Parse.Cloud.job("V2_JobProcessStaticCouponCampaign", function(request, status) {
    Parse.Cloud.useMasterKey();
    var query = new Parse.Query("Campaigns");
    query.get(request.params.campaignId, {
        success: function(group) {
            if(group.get("IsScheduledForLoading")) {
                var uploadedFileURL = group.get("UploadedFileURL");
                return Parse.Cloud.httpRequest({
                    method: "GET",
                    url: uploadedFileURL

                }).then(
                    function (result) {
                        var newCustomerCoupons = [];
                        var C_Customers = Parse.Object.extend("C_Customers");
                        var isHeaderValid = false;
                        var intValidRowNumberCount = 0;
                        var arrayLinesInFile = result.text.split("\r\n");
                        var intLinesInFile = arrayLinesInFile.length;
                        var field1, field2, field3;
                        if (intLinesInFile > 0) {
                            for (intRows = 0; intRows < intLinesInFile; intRows++) {

                                var row = arrayLinesInFile[intRows].split(",");
                                field1 = (typeof row[0] === "undefined" ? "" : row[0].replace(/ /g, "").replace(/\"/g, ""));
                                field2 = (typeof row[1] === "undefined" ? "" : row[1].replace(/ /g, "").replace(/\"/g, ""));
                                field3 = (typeof row[2] === "undefined" ? "" : row[2].replace(/ /g, "").replace(/\"/g, "").replace("$", ""));

                                if(intRows === 0){  //Validate header format
                                    if(field1.toLowerCase() === "cellphone" &&
                                        (field2.toLowerCase() === "memberid" || field2.toLowerCase() === "playerid") &&
                                        (field3.toLowerCase() === "value" || field3.toLowerCase() === "fp")){
                                        isHeaderValid = true;
                                    }
                                    else{
                                        throw new Error("Header format is incorrect.");
                                    }
                                }
                                else{
                                    if(!field1 && !field2 && !field3){} // row is completely empty, do not process it.
                                    else{
                                        if(isHeaderValid){
                                            var customer = new C_Customers();
                                            customer.set("CellPhoneNumber", field1);
                                            customer.set("MemberID", field2);
                                            customer.set("OfferAmount", field3);
                                            customer.set("Pointer_MemberOfCampaign", group);
                                            customer.set("OrderNumber", intRows);
                                            newCustomerCoupons.push(customer);
                                            intValidRowNumberCount++;
                                        }
                                    }
                                }
                            }
                        }
                        var result = {
                            coupons: newCustomerCoupons
                        };
                        return result;
                    }).then(
                    function (result)
                    {
                        try{
                            /* Attempted this approach for async saving */
                            Parse.Object.saveAll(result.coupons);
                            status.success("**All data loaded successfully!");

                            /* Also attempted this approach for sync saving */
                            return Parse.Object.saveAll(result.coupons).then(
                                function (list) {
                                    status.success("**All data loaded successfully!");
                                },
                                function (error) {
                                    //TODO: log error for visibility in UI
                                    status.error("Error in SaveAll: " + JSON.stringify(error));
                                }
                            );
                        }
                        catch(error){
                            status.error("Error in SaveAll: " + JSON.stringify(error));
                        }
                    },
                    function(error) {
                        status.error("Error in SaveAll: " + JSON.stringify(error));
                    }
                );
            }
        },
        error: function(error) {
            status.error("Error in SaveAll: " + JSON.stringify(error));
        }
    });
});

2. Option #2: Save objects in small batches.
Parse.Cloud.job("V3_JobProcessStaticCouponCampaign", function(request, status) {
    Parse.Cloud.useMasterKey();
    var _group = "";
    var query = new Parse.Query("Campaigns");
    query.get(request.params.campaignId)
        .then(function(group) {
            if (group.get("IsScheduledForLoading") && !group.get("IsLoaded")) {
                _group = group;
                return _group;
            }
            else{
                var err = "Aborted processing of Group " + group.id + ". It isn't scheduled for loading or is already loaded.";
                return Parse.Promise.error(new Error(err));
            }
        })
        .then(function(group){
            var uploadedFileURL = _group.get("UploadedFileURL");
            return Parse.Cloud.httpRequest({
                method: "GET",
                url: uploadedFileURL
            });
        })
        .then(function (result) {
            var batches = [];
            var newCustomerCoupons = [];
            var C_Customers = Parse.Object.extend("C_Customers");
            var isHeaderValid = false;
            var intValidRowNumberCount = 0;
            var arrayLinesInFile = result.text.split("\r\n");
            var intLinesInFile = arrayLinesInFile.length;
            var field1, field2, field3;
            if (intLinesInFile > 0) {
                for (intRows = 0; intRows < intLinesInFile; intRows++) {
                    if (intRows > 0 && intRows % 250 === 0){
                        batches.push(newCustomerCoupons);
                        newCustomerCoupons = [];
                    }

                    var row = arrayLinesInFile[intRows].split(",");
                    field1 = (typeof row[0] === "undefined" ? "" : row[0].replace(/ /g, "").replace(/\"/g, ""));
                    field2 = (typeof row[1] === "undefined" ? "" : row[1].replace(/ /g, "").replace(/\"/g, ""));
                    field3 = (typeof row[2] === "undefined" ? "" : row[2].replace(/ /g, "").replace(/\"/g, "").replace("$", ""));

                    if (intRows === 0) {  //Validate header format
                        if (field1.toLowerCase() === "cellphone" &&
                            field2.toLowerCase() === "memberid" &&
                            field3.toLowerCase() === "value") {
                            isHeaderValid = true;
                        }
                        else {
                            return Parse.Promise.error(new Error("Header format is incorrect."));
                        }
                    }
                    else {
                        if (!field1 && !field2 && !field3) {} // row is completely empty, do not process it.
                        else {
                            if (isHeaderValid) {
                                var customer = new C_Customers();
                                customer.set("CellPhoneNumber", field1);
                                customer.set("MemberID", field2);
                                customer.set("OfferAmount", field3);
                                customer.set("Pointer_MemberOfCampaign", _group);
                                customer.set("OrderNumber", intRows);

                                newCustomerCoupons.push(customer);
                                intValidRowNumberCount++;
                            }
                        }
                    }
                }
            }

            batches.push(newCustomerCoupons);

            var result = {
                couponBatches: batches
            };
            return result;
        })
        .then(function(result){
            function saveBatches(batches) {
                if (batches.length === 0) { return Parse.Promise.as(); }
                var nextBatch = batches[0];
                return Parse.Object.saveAll(nextBatch).then(function() {
                    var remainingBatches = batches.slice(1, batches.length);
                    return saveBatches(remainingBatches);
                });
            }
            return saveBatches(result.couponBatches).then(function() {
                _group.set("IsLoaded", true);
                _group.set("ReinvestmentSum", result.metaData.sum);
                _group.set("LoadingStatus", "Step 5) Displaying Data...");
                _group.save(null, {
                    success: function (log) {
                        return Parse.Promise.as("Chain success!");
                    },
                    error: function (log, error) {
                        return Parse.Promise.as("Chain error!");
                    }
                });
            }, function(error) {
                return Parse.Promise.error(new Error("Batches failed."));
            });
        })
        .then(function(success){
            status.success("**All data loaded successfully!");
        },
        function (error) {
            status.error("Error in Job: " + JSON.stringify(error));

        }
    );
});

#### Expected Results

Objects should be saved to the DB without issue.

#### Actual Outcome

Process occasionally fails with error object {"code":2,"message":"the service is currently unavailable"}

### Environment Setup

- **Server**
  - parse-server version: Hosted on Parse.com (running in production mode w/ 600req/sec.)
  - Operating System:    Hosted on Parse.com (DB migrated to mLab)
  - Hardware:             Hosted on Parse.com (DB migrated to mLab)
  - Localhost or remote server?: Hosted on Parse.com (DB migrated to mLab)

- **Database**
  - MongoDB version: 3.2.8
  - Storage engine:  Unknown.
  - Hardware:        Reproduced on Shared Cluster and Dedicated Cluster.
  - Localhost or remote server? mLab

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

Is this available on the Parse hosted environment? If so, where?

**Comment by flovilmart** [comment]
Your issue is on parse.com please refer to the support available at http://parse.com/help

**Comment by johnturnham** [comment]
Where? I've looked everywhere for this issue and a resolution.

Please provide a link.

**Comment by flovilmart** [comment]
There is a contact us button right in the middle of the page.

**Comment by johnturnham** [comment]
That button points me here, to GitHub.

**Comment by flovilmart** [comment]
![capture d ecran 2016-08-19 a 18 14 03](https://cloud.githubusercontent.com/assets/364568/17825778/c7653d1e-6638-11e6-82c3-ee9d2d3f8c4d.png)

Select your app and then continue to Facebook bug reporting tool

**Comment by johnturnham** [comment]
Hi flovimart,

I've submitted this request to the "Facebook for developers" area that you've suggested but 1) haven't received any confirmation response since submitting it days ago and 2) can't find my report anywhere in that site.

It seems that I need to now register my app for use with Facebook to have any visibility into the status of the bug I submitted. However, I have no interest in registering my app for Facebook integration.

Can you please advise as to how I can get a status on this ticket, so the Parse issues can be resolved?

Thanks.

**Comment by flovilmart** [comment]
I'm not working with Facebook nor Parse, just contributing to the open source part.
