### ISSUE TITLE
req.log.info & req.log.error missing (cloud code)

### ISSUE THREAD

**Issue by gimdongwoo** [ParsePlatform/parse-server#2566]
This probably occurs because,
https://github.com/ParsePlatform/parse-server/pull/2478

When using req.log.info or req.log.error on Cloud code, occurs problem.

It has been stated specification.
https://github.com/ParsePlatform/parse-server/blob/master/spec/CloudCodeLogger.spec.js

What's wrong?

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.18
  - Operating System:     64bit Amazon Linux 2016.03 v2.1.3 running Node.js
  - Hardware:             t2.small
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): AWS EB

- **Database**
  - MongoDB version: 3.0.12
  - Storage engine:  -
  - Hardware:        M1
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

**Comment by flovilmart** [comment]
What problem is occurring? The functions are not exposed?

**Comment by flovilmart** [comment]
@gimdongwoo what is exposed on the object req.log? can you log it?

**Comment by flovilmart** [comment]
@gimdongwoo we're planning on issuing a release soon, can you give us a heads up if that's and issue, what's the object you see exposed in req.log etc... ?

**Comment by gimdongwoo** [comment]
@flovilmart I'm so sorry.
Response is too late.
I'm on vacation, last week.
ASAP, I will add screen shot related this problem.
