### ISSUE TITLE
How to create an instance of ParseServer, and mount it on a new or existing Express website?

### ISSUE THREAD

**Issue by huang1196** [ParsePlatform/parse-server#257]
No clue about it.
I've searched for some tutorial, most of them are "git clone https://github.com/ParsePlatform/parse-server-example", modify mongo_uri, masterkey blabla, then npm install & npm start. I tried it and it runs successfully.
While I have no idea about how to create an instance from this parse-server project. (I think parse-server-exmaple is an instance of ParseServer, right?)

**Comment by maysale01** [comment]
The example is pretty concise, you can use it in an existing server like so:

`npm install --save parse-server`

```javascript
import { ParseServer } from 'parse-server';

app.use('/parse', new ParseServer({
    databaseURI: process.env.MONGODB_URL,
    cloud: path.resolve("./dist", "cloud.js"),
    appId: 'myAppId',
    masterKey: 'mySecretMasterKey',
    fileKey: 'optionalFileKey'
});
```

**Comment by gfosco** [comment]
I would refer to you the parse-server-example repo, or the various guides from Heroku and Digital Ocean available on the wiki.
