### ISSUE TITLE
How to debug a sudden influx of “Request timed out” as of Aug 24/16

### ISSUE THREAD

**Issue by tzabian** [ParsePlatform/parse-server#2581]
I know this isn't a Parse support forum but as we're in the process of migrating to self-hosted (and have a code freeze on anything Parse hosted) and have hit some pretty massive issues in sudden timeouts.

We run at around 130 req/sec (well below our quota of 190) and as of yesterday have seen a sudden spike in time outs (see below). This has been on and off and is drastically impacting the performance of our app.

There have been zero changes to our cloud code or server setup or any of our apps. We are in the process of migrating out in a month and are in desperate need of some help. This is happening almost every second.

![parse_log_1](https://cloud.githubusercontent.com/assets/155341/17949696/bc5ebf5c-6a67-11e6-93df-9bc1e7838ec3.jpg)
![parse_log_2](https://cloud.githubusercontent.com/assets/155341/17949697/bc6351ac-6a67-11e6-88f9-56aac340cf14.jpg)

@hramos any idea if there have been any maintenance work done on Parse? I have a strong feeling this is something to do with our parse app (as this has happened in the past pre-retirement notice and someone at Parse/FB was able to fix it). Thanks in advance.

**Comment by hramos** [comment]
It's best if you file this as a bug with the Parse bug tracker, we don't want to encourage the use of this issue tracker for non-Parse Server support.

**Comment by tzabian** [comment]
@hramos where is this Parse bug tracker. Ever since you guys switched your support from hosted Parse to self-hosted Parse, it seems anything to do with the prior has vanished off the internet. Thanks

**Comment by hramos** [comment]
It's linked to from the Help page: https://parse.com/help
