### ISSUE TITLE
Error on Socket - LiveQuery Error (Cannot Connect)

### ISSUE THREAD

**Issue by greggmojica** [ParsePlatform/parse-server#2582]
Hi everyone - 
I'm attempting to use livequery (using the js sdk) in my parse-server app hosted on AWS using SSL. I've attempted to connect and each time I get the following error:

<pre>
WebSocket connection to 'ws://XXXXXXXXX.XXXXXXXXXXXXX.com/parse' failed: Error during WebSocket handshake: Unexpected response code: 403
error on socket
</pre>

My livequery js code is quite simple:
<pre>
let query = new Parse.Query('XXXXXXX');
query.equalTo('XXX', 'XXXXXXXXX');
let subscription = query.subscribe();
subscription.on('create', (obj) => {
     console.log(obj);
}); 
</pre>

I'm not sure what I'm doing wrong exactly but if someone could point me in the right direction it'd be greatly appreciated! @hramos

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

**Comment by ChrisHawley** [comment]
@greggmojica I had a similar problem -- changing the protocols on my ELB seemed to do the trick.
The following is what I added to my elastic beanstalk env.yaml:
```
  aws:elb:listener:443:
    ListenerProtocol: SSL
    InstanceProtocol: TCP
```

**Comment by greggmojica** [comment]
@ChrisHawley did you create this env.yaml file (I don't have it in my config). I do have an app.yaml file.

**Comment by greggmojica** [comment]
@hramos 

Environment Setup - AWS Beanstalk
parse-server version :2.2.2
Operating System: Linux
Hardware: Amazon Linux
Localhost or remote server? AWS

MongoDB version: 3.0.12
Hardware: mLab Dedicated Instance
Localhost or remote server? mLab

Expected to Connect to Socket, fails and throws error ```WebSocket connection to 'ws://XXXXXXXXX.XXXXXXXXXXXXX.com/parse' failed: Error during WebSocket handshake: Unexpected response code: 403
error on socket```

**Comment by ChrisHawley** [comment]
@greggmojica Yea, I created env.yaml manually.  I think it's a way to pass additional config params into your ECS environment without going through the AWS Console UI. (http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environment-cfg-manifest.html)

Is websockets the only thing that's giving you trouble?  Are you able to connect `parse-dashboard` to your deployed environment for ordinary (non-LiveQuery) requests?

**Comment by greggmojica** [comment]
Hey @ChrisHawley I did add the env.yml file but no luck. I'm getting this error now:
```WebSocket connection to 'ws://xxxxxxx.xxxxxxxxxxxx.com/parse' failed: Error during WebSocket handshake: Unexpected response code: 301``` Did you have anything else in your env file?  Thoughts?

@hramos - I'd appreciate your input! Thanks!

**Comment by ChrisHawley** [comment]
@greggmojica Did you set up the InstancePort on your ELB?  I think 9091 is default, so:
```
  aws:elb:listener:443:
    ListenerProtocol: SSL
    InstanceProtocol: TCP
    InstancePort: 9091
```

**Comment by greggmojica** [comment]
Just updated the env.yaml file and I get this error again: ```WebSocket connection to 'ws://beanstalk.gradology.com/parse' failed: Error during WebSocket handshake: Unexpected response code: 403```. No luck :(

**Comment by lifeisfunny** [comment]
Very clear that is the load balancer issue.  Currently aws does not supporting ws and wss redirections.  Plus , you need to set stickiness on the header redirection to pass token to live query server.

**Comment by greggmojica** [comment]
@lifeisfunny can you please give me more detailed info regarding this? I called AWS support and they are really not sure.

**Comment by hramos** [comment]
@greggmojica your Parse Server version, 2.2.2, was released on March 23 and therefore is very far behind the [latest release](https://github.com/ParsePlatform/parse-server/releases) as of this writing (2.2.18).

As it happens we can't provide a lot of support for troubleshooting individual deployments here in the issue tracker, so I'll need to close this issue out.

**Comment by core2root** [comment]
hi i have the same ptoblem here and i dont understand where to addt he env.yaml file

**Comment by anhduca4** [comment]
hi i have the same ptoblem here can you help me

**Comment by THEDOWNCOUNTRY** [comment]
I have the same roblem with livequery

**Comment by flovilmart** [comment]
@THEDOWNCOUNTRY can you please open a new issue filling the issue template so we can properly address it?
