### ISSUE TITLE
"Ducpliate key error" on anonymous user signup

### ISSUE THREAD

**Issue by erez213** [ParsePlatform/parse-server#259]
Hi,

When I use this code from the Android SDK:
`ParseAnonymousUtils.logIn(new LogInCallback() {..});`

I get this error on my nodeJS server:
https://i.gyazo.com/b1f0195ffa2eea64590b8e3759b1444b.png

On the PHP SDK it works.

**Comment by gfosco** [comment]
Please re-open if you are still experiencing this with 2.0.8+. Thanks
