### ISSUE TITLE
Delete files

### ISSUE THREAD

**Issue by ckarmy** [ParsePlatform/parse-server#2591]
Hi,
I need to delete my unused files. How can Achieve this with the Javascript SDK?

I really need to do this on my app. It's possible with parse-server? Before there was a button "Clean Up Files"...

Thanks!!!!!

**Comment by joeyslack** [comment]
You will have to manually do it.

**Comment by ckarmy** [comment]
@joeyslack how can I get the list of all files? Including the unused files?

Do yo know where can I find a example?

Thanks a los!

**Comment by chrisfoulds** [comment]
The old parse service had a feature for this, has anyone managed to replicate this ?

**Comment by natario1** [comment]
You can get inspiration from https://github.com/parse-server-modules/parse-files-utils , which does a different thing but is a good starting point. I think this feature would be a great parse-server module.
