### ISSUE TITLE
Wrong results returned from whereNotContainedIn() method

### ISSUE THREAD

**Issue by mik-dass** [ParsePlatform/parse-server#2592]
I am trying to create a query to find posts which are not liked by the logged in user. I create the array containing all the objectIds of posts not liked by the user.Then I perform a query like this

     var votes = new Parse.Query(Votes); votes.equalTo("user_id", request.params.user_id);
    votes.find({
    success: function(results) {
     var ids = results.map(function(obj) {
     return obj.get('question').id;
    });
    var questions = new Parse.Query(Questions);
    questions.notContainedIn('objectId', ids);
    questions.find({
      success: function(results) {
          response.success(results);
      }
     });
    } 
    });

Problem is the data returned contains wrong results.I even tried the api console and did a rest api query like

       'where={"objectId":$nin["HFAxSAyVbN","Xn8EYwbeUZ","qYfgZqaCG8"] }'

The results contained many Json objects including the objects with the above objectId's. One of the results was

     {
        "aspectRatio": 0.709,
        "createdAt": "2016-01-30T05:55:55.732Z",
        "likes": 13,
        "objectId": "Xn8EYwbeUZ",
        "postAuthor": {
            "__type": "Pointer",
            "className": "_User",
            "objectId": "OfBgyVDqpS"
        },
        "postFile": {
            "__type": "File",
            "name": "tfss-0ca1766d-b53f-4c34-8479-0034cc2e60d7-tfss-93d860c5-e60a-42bc-b948-0c965c6b4136-post.jpeg",
            "url": "http://files.parsetfss.com/b406a736-2819-4a49-9bd7-c8729bf4c562/tfss-0ca1766d-b53f-4c34-8479-0034cc2e60d7-tfss-93d860c5-e60a-42bc-b948-0c965c6b4136-post.jpeg"
        },
        "postFile_THUMBNAIL": {
            "__type": "File",
            "name": "tfss-81f5ff66-eead-4f65-bc48-347b93a21fa9-tfss-38fdbd7b-2f59-4a54-9ef4-ae7124441e96-thumbnail.jpeg",
            "url": "http://files.parsetfss.com/b406a736-2819-4a49-9bd7-c8729bf4c562/tfss-81f5ff66-eead-4f65-bc48-347b93a21fa9-tfss-38fdbd7b-2f59-4a54-9ef4-ae7124441e96-thumbnail.jpeg"
        },
        "story": "Awesome burger... Looks delicious...☺☺☺",
        "story_LOWERCASE": "awesome burger... looks delicious...☺☺☺",
        "type": "image",
        "updatedAt": "2016-08-22T18:05:37.716Z"
    },

This above objectId is mentioned in the above rest api query.So the query is giving me wrong results from the class . Please check this issue and tell me what's wrong.

**Comment by flovilmart** [comment]
This seems to be a bug.

**Comment by mik-dass** [comment]
@flovilmart I am actually using the api.parse.com servers and found this bizarre bug or whatever. I know this place is only for parse-server bugs but I think it might still exist in the parse-server .Earlier such a query used to work because I have encountered many people and examples who have made the $nin query and successfully got back the desired results. So I believe something in the recent updates broke this functionality. Please check and let me know if there is a workaround to the problem.

**Comment by flovilmart** [comment]
Parse.com don't use parse-server at all, until you reproduce that error on Parse-server, i'I'll close that issue

**Comment by mik-dass** [comment]
@flovilmart Please tell me where I should report this issue .... :)

**Comment by flovilmart** [comment]
On https://parse.com/help
