### ISSUE TITLE
Query Performance in Parse Server

### ISSUE THREAD

**Issue by Npmorales** [ParsePlatform/parse-server#2593]
### Issue Description

We are testing our new Parse Server on AWS EC2 and we are surprised for the poor performance obtained. Our mongodb platform is really close to our parse-servers. There aren't any slow queries in our mongodb (80 ms is slow to us).We have un ELB with only one instance behind. 

We have observed that the performance depends on the concurrence of requests and the number of registers returned.

A request for ParseServer that sends a query to MongoDB(less than 1 ms)  can take between 0,6 and 13 seconds . 

Is this a normal behavior ? Any way to improvement it?

### Steps to reproduce

A test with Jmeter: 100 threads sending the same query during 10 secods.
POST https://MyDomain.com:1337/parse/classes/Clips

POST data: {"where":"{\"category\":4}","order":"-score","limit":"300","_method":"GET"}

If we limit the results to one field we achieve to do the response smaller but we don't obtain an important improvement, while if we limit the number of registers returned the improvement is much bigger.

####  Results
While Mongodb is 3% CPU, any query more than 1 ms, Parse Server is 100% CPU and some request more than 12 seconds.
![image](https://cloud.githubusercontent.com/assets/19958239/17990397/abceee72-6b35-11e6-80e2-11ba5294f07b.png)

#### Mongo Query:
This query takes less than 1ms as you can see next:

2016-08-26T01:35:34.502+0200 I COMMAND  [conn2019] command cgib.Clips 
command: find { find: "Clips", filter: { category: 6, _rperm: { $in: [ null, "*", "C9ER5qY9cW" ] } }, sort: { score: -1 }, limit: 300 } 

planSummary: IXSCAN { category: 1, score: -1 } cursorid:49322158526 keysExamined:101 docsExamined:101 keyUpdates:0 
writeConflicts:0 numYields:1 nreturned:101 reslen:74986 locks:{ Global: { acquireCount: { r: 4 } }, 
Database: { acquireCount: { r: 2 } }, Collection: { acquireCount: { r: 2 } } } protocol:op_query 0ms

### Environment Setup

- **Server**
  
  - parse-server version: 2.2.17
  -  Operating System: ubuntu 14.04
  -  Hardware: AWS EC2 c4.large

- **Database**

  - MongoDB version: 3.0
  - Storage engine: WiredTiger
  - Hardware: AWS EC2 m4.large

**Comment by flovilmart** [comment]
Not sure what normal behavior would be. Did you try with a lower concurrency? Nodejs is single threaded, with a single event loop, clobbering 100 threads for 10s is likely to be problematic. 

Did you run some tests with the `ab` tool with a concurrency of 30-50? We have a setup on google app engine, and we limit the rps to 50/instance before triggering auto scaling, without leveraging multi cores through pm2 or cluster

**Comment by Npmorales** [comment]
Actually, since a AWS EC2 c4.large has two cores, we have two parser-server process. One listen on port 1338 and the other listen on port 1339. The c4.large run an haproxy listen on port 1337 and distributes requests between this local ports.

Here the results with ab :

**_Test 1 Concurrency Level:      50_**

```
Time taken for tests:   41.511 seconds
Complete requests:      500
Failed requests:        0
Total transferred:      131166000 bytes
Total body sent:        383500
HTML transferred:       130903000 bytes
Requests per second:    12.04 [#/sec] (mean)
Time per request:       4151.103 [ms] (mean)
Time per request:       83.022 [ms] (mean, across all concurrent requests)
Transfer rate:          3085.73 [Kbytes/sec] received
                        9.02 kb/s sent
                        3094.75 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        4   12  24.6      4      97
Processing:   729 3949 830.0   4027    6139
Waiting:      725 3944 829.9   4021    6134
Total:        804 3961 817.6   4037    6143

Percentage of the requests served within a certain time (ms)
  50%   4037
  66%   4250
  75%   4318
  80%   4439
  90%   4719
  95%   4928
  98%   5837
  99%   5998
 100%   6143 (longest request)

```

**_Test 2  Concurrency Level:      100_**

```
**Concurrency Level:      100**
Time taken for tests:   41.453 seconds
Complete requests:      500
Failed requests:        0
Total transferred:      131166000 bytes
Total body sent:        383500
HTML transferred:       130903000 bytes
Requests per second:    12.06 [#/sec] (mean)
Time per request:       8290.677 [ms] (mean)
Time per request:       82.907 [ms] (mean, across all concurrent requests)
Transfer rate:          3090.02 [Kbytes/sec] received
                        9.03 kb/s sent
                        3099.05 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        4   43  78.8      4     226
Processing:   223 7493 1777.4   7980   12181
Waiting:      219 7489 1777.5   7976   12177
Total:        406 7537 1722.1   7986   12185

Percentage of the requests served within a certain time (ms)
  50%   7986
  66%   8279
  75%   8438
  80%   8482
  90%   8725
  95%   9000
  98%   9348
  99%   9856
 100%  12185 (longest request)
```

**Comment by flovilmart** [comment]
So it's about 83ms / request.

**Comment by Npmorales** [comment]
But the 50 % of the requests takes more than 4 seconds to be served even limiting the concurrence to 50 . That not seems to be a good performance.

However if we limit the result to 100 instead 300 , the throughput improves a lot . Is normal that Parse Server suffers so much for the number of lines to return in a simple query?

Next , you can see that the same test (lines limit= 100 , concurrency=100) offers much better results that  l=300 c=50

```
Concurrency Level:      100
Time taken for tests:   15.304 seconds
Complete requests:      500
Failed requests:        0
Total transferred:      43788000 bytes
Total body sent:        383500
HTML transferred:       43525500 bytes
Requests per second:    32.67 [#/sec] (mean)
Time per request:       3060.740 [ms] (mean)
Time per request:       30.607 [ms] (mean, across all concurrent requests)
Transfer rate:          2794.21 [Kbytes/sec] received
                        24.47 kb/s sent
                        2818.68 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        4   38  69.1      4     199
Processing:   993 2780 550.6   2697    3927
Waiting:      992 2779 550.6   2695    3926
Total:        997 2818 554.2   2708    4126

Percentage of the requests served within a certain time (ms)
  50%   2708
  66%   2790
  75%   3103
  80%   3433
  90%   3586
  95%   3759
  98%   3887
  99%   4032
 100%   4126 (longest request)
```

**Comment by flovilmart** [comment]
> you can see that the same test (lines limit= 100 , concurrency=100) offers much better results that l=300 c=50

Less data to transfer, less time to process...

@TylerBrock, you achieved a very nice performance on a quite simple setup. 

Also, I'm not sure if complaining about performance is very productive here, I'm running more than 400rps sustained with < 50ms response times. 

@Npmorales If you want to tackle overall performance of parse-server, feel free to work on it, that will always be welcome.
