### ISSUE TITLE
ParseSever LiveQuery: expressjs call save but get error "Can not find subscriptions under this class XXX"

### ISSUE THREAD

**Issue by uluru-phatnguyen** [ParsePlatform/parse-server#2594]
**Step 1: Build parser-server config in index.js**
```js
var api = new ParseServer({
  databaseURI: 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'myAppId',
  masterKey: process.env.MASTER_KEY || '', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',  // Don't forget to change to https if needed
  liveQuery: {
    classNames: ['XXX'] // List of classes to support for query subscriptions
  },
  // ....
});

var port = process.env.PORT || 1337;
var httpServer = require('http').createServer(app);
httpServer.listen(port, function() {
    console.log('server running on port ' + port + '.');
});

// This will enable the Live Query real-time server
ParseServer.createLiveQueryServer(httpServer);
```

**Step 2: Build webapp by expressjs framework**

Call api (above server) to update data of XXX via ParseQuery.

But i always get bug logs from server "Can not find subscriptions under this class XXX"

https://github.com/ParsePlatform/parse-server/blob/master/src/LiveQuery/ParseLiveQueryServer.js#L154-L158

I don't know how to fix, If have any solution pls tell me.

**Comment by flovilmart** [comment]
Do you have a client subscribed to those updates?

**Comment by flavionegrao** [comment]
Maybe changing the log level to debug would be more more appropriated?

```javascript
// ParseLiveQueryServer.js (_onAfterSave and _onAfterSave)

   var classSubscriptions = this.subscriptions.get(className);
      if (typeof classSubscriptions === 'undefined') {
        _logger2.default.error('Can not find subscriptions under this class ' + className);
        return;
      }
```
I believe the situation is a class is being tracked by the Live Query Server, but no client is subscribed to it.

**this.subscription** 
ParseLiveQueryServer
clientId:0
clients:Map[0]
keyPairs:Map[0]
parseWebSocketServer:ParseWebSocketServer
sessionTokenCache:SessionTokenCache
subscriber:Subscriber
subscriptions:Map[0]
__proto__:ParseLiveQueryServer

**Comment by flovilmart** [comment]
That would make sense. Do you mind opening a pull request for that fix? 

https://github.com/ParsePlatform/parse-server/blob/master/src/LiveQuery/ParseLiveQueryServer.js#L111

https://github.com/ParsePlatform/parse-server/blob/master/src/LiveQuery/ParseLiveQueryServer.js#L156

And probably other places in this module

**Comment by flavionegrao** [comment]
sure thing

**Comment by flovilmart** [comment]
Thanks @flavionegrao ! Let's close that one as it will be part of next release.
