### ISSUE TITLE
/GET/apps/   for requestPasswordrest on Azure not routing correctly? 

### ISSUE THREAD

**Issue by sinclas** [ParsePlatform/parse-server#2599]
Hi,

I have parse server running in Azure.  I got the password rest through MailGun running and sending emails to me for the password reset.  The URL that gets sent on the bottom is well formed but when I click on the link, i get the following error:
Cannot GET /apps/17b0bdad-8afd-4ce0-be28-a17023fb11f8/request_password_reset?token=Cz38Gb4inP1T00wOzFPMIvlmx&username=xyz%40mac.com

I have been working on this for a day and have no idea why this is happening.  Has anyone gotten this to work on Azure.   Seems like nothing for this.customPages routes correctly through express.  Not expecting a silver bullet response, but maybe some street smart ideas on how to figure this out would be great!  Thanks, s

**Comment by flovilmart** [comment]
Can your run with VERBOSE=1 set and provide the logs?

**Comment by sinclas** [comment]
HI,

I have VERBOSE on in the Azure console.  I FTP’d to the folders and not sure which ones are applicable.

**Comment by flovilmart** [comment]
I'm not expert with Azure, do you have access to the logs?

**Comment by sinclas** [comment]
Yes,  I have the logs,  not sure which log.  There are IIS, Application, HTTP, etc..  nothing too compelling in these.   Is there some place I should be looking for Express errors?

**Comment by flovilmart** [comment]
The parse-server logs, if you have them, there may be something in there about that 404. Also, can you post your config/initialization code, there may be something there too

**Comment by sinclas** [comment]
This is the web.config:  
`var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var ParseDashboard = require('parse-dashboard');
var parseServerConfig = require('parse-server-azure-config');
var url = require('url');
var config = parseServerConfig(__dirname);
// Modify config as necessary before initializing parse server & dashboard

var app = express();

//app.get('/', function (req, res) {
//  res.send('Hello World!');
//  console.info('info');
//});

app.use('/public', express.static(__dirname + '/public'));
app.use('/parse', new ParseServer(config.server));
app.use('/parse-dashboard', ParseDashboard(config.dashboard, true));

app.listen(process.env.PORT || url.parse(config.server.serverURL).port, function () {
  console.log('Parse Server running at ${config.server.serverURL}');
});`

**Comment by sinclas** [comment]
Parse-Server Logs:

{"level":"error","message":"Uncaught internal server error. [Error: Can't set headers after they are sent.] Error: Can't set headers after they are sent.\n    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)\n    at expressInit (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\middleware\\init.js:23:42)\n    at Layer.handle [as handle_request] (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:312:13)\n    at D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:280:7\n    at Function.process_params (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:330:12)\n    at next (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:271:10)\n    at query (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\middleware\\query.js:44:5)\n    at Layer.handle [as handle_request] (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:312:13)","timestamp":"2016-08-27T16:09:32.215Z"}
{"level":"error","message":"Uncaught internal server error. [Error: Can't set headers after they are sent.] Error: Can't set headers after they are sent.\n    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)\n    at expressInit (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\middleware\\init.js:23:42)\n    at Layer.handle [as handle_request] (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:312:13)\n    at D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:280:7\n    at Function.process_params (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:330:12)\n    at next (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:271:10)\n    at query (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\middleware\\query.js:44:5)\n    at Layer.handle [as handle_request] (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:312:13)","timestamp":"2016-08-27T16:09:32.278Z"}
{"level":"error","message":"Uncaught internal server error. [Error: Can't set headers after they are sent.] Error: Can't set headers after they are sent.\n    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)\n    at expressInit (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\middleware\\init.js:23:42)\n    at Layer.handle [as handle_request] (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:312:13)\n    at D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:280:7\n    at Function.process_params (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:330:12)\n    at next (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:271:10)\n    at query (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\middleware\\query.js:44:5)\n    at Layer.handle [as handle_request] (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:312:13)","timestamp":"2016-08-27T16:09:39.151Z"}
{"level":"error","message":"Uncaught internal server error. [Error: Can't set headers after they are sent.] Error: Can't set headers after they are sent.\n    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)\n    at expressInit (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\middleware\\init.js:23:42)\n    at Layer.handle [as handle_request] (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:312:13)\n    at D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:280:7\n    at Function.process_params (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:330:12)\n    at next (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:271:10)\n    at query (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\middleware\\query.js:44:5)\n    at Layer.handle [as handle_request] (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (D:\\home\\site\\wwwroot\\node_modules\\express\\lib\\router\\index.js:312:13)","timestamp":"2016-08-27T16:09:39.168Z"}
{"level":"verbose","message":"POST /parse/requestPasswordReset { 'cache-control': 'no-cache',\n  connection: 'keep-alive',\n  'content-length': '27',\n  'content-type': 'application/json',\n  host: 'bounteparse1.azurewebsites.net',\n  'max-forwards': '10',\n  'x-parse-application-id': '16b0bdad-8afd-4ce0-be28-a18012fb11f8',\n  'x-parse-client-version': 'net-xamarin-ios1.7.0.0',\n  'x-parse-installation-id': '28c8a411-5de7-4110-90bd-9ff0ca7d9cd7',\n  'x-parse-app-build-version': '1.0',\n  'x-parse-app-display-version': '1.0',\n  'x-parse-os-version': '9.3',\n  'x-parse-windows-key': '49145a53-e027-4a3a-b13a-030ef45e9f58',\n  'x-liveupgrade': '1',\n  'x-arr-log-id': '0fb6edf1-a1ec-4d57-96ff-a1b3078a0a2e',\n  'disguised-host': 'bounteparse1.azurewebsites.net',\n  'x-site-deployment-id': 'bounteparse1',\n  'was-default-hostname': 'bounteparse1.azurewebsites.net',\n  'x-original-url': '/parse/requestPasswordReset',\n  'x-forwarded-for': '67.176.128.202:60886',\n  'x-arr-ssl': '2048|256|C=US, S=Washington, L=Redmond, O=Microsoft Corporation, OU=Microsoft IT, CN=Microsoft IT SSL SHA2|CN=*.azurewebsites.net' } {\n  \"email\": \"Sinclas@mac.com\"\n}","timestamp":"2016-08-27T20:48:56.756Z"}
{"code":205,"message":"error:","level":"verbose","timestamp":"2016-08-27T20:48:56.788Z"}

**Comment by sinclas** [comment]
Found it!

In the parse config, there are references to URLs by Key and function.  The function will return a string URI that basically takes the publicServerURL and adds the paths to specific html, etc.  The problem is when they ported this from GIT to Azure, there is a missing part to the path.  look at the following before and after.  the after works.   Open your source editor in Azure (Monoco) and Search for "request_password_reset".  You'll find it in the parse config file (Config.js).  **Look at all the Keys in that file and make sure they have the changes below.  I only list the request_password_rest for this example.   This worked for me! Might be different for other environments.  If "this.publicServerURL" already has "/parse/" in it, this wouldn't be necessary. I am not knowledgable or comfortable enough to be changing the publicServerURL yet.

**BEFORE**(Broken):
key: 'requestResetPasswordURL',
    get: function get() {
      return this.publicServerURL + **'/apps/'** + this.applicationId + '/request_password_reset';
    }

**AFTER** (Solution)
key: 'requestResetPasswordURL',
    get: function get() {
      return this.publicServerURL + **'/parse/apps/'** + this.applicationId + '/request_password_reset';
    }

**Comment by flovilmart** [comment]
Instead of changing the code of parse-server you should provide the full publicServerURL in your configuration, where you specify your application id and master key.
