### ISSUE TITLE
How to create data schema for new app if parse-server doesn't support schema API?

### ISSUE THREAD

**Issue by 5amfung** [ParsePlatform/parse-server#26]
According to the [migration guide](https://www.parse.com/docs/server/guide#migrating), schema API is not supported.  So what's the best way to create the schema for data?  I guess I have to create the schema directly in mongodb.  Is my understanding correct?

**Comment by wagnercsfilho** [comment]
+1

**Comment by kingmatusevich** [comment]
Hopefully when the webUI gets implemented this will be part of it. https://github.com/ParsePlatform/parse-server/issues/3

**Comment by gfosco** [comment]
One of the cool things about Parse is that you can have the schema automatically created as you add data.  This was the first method, before the data browser.  This works, and the schema is stored in the _SCHEMA class.  Once you see some records there, the format is simple enough.  We should document the format in the wiki.

**Comment by kingmatusevich** [comment]
@gfosco Awesome
