### ISSUE TITLE
User setPassword cause Object not found

### ISSUE THREAD

**Issue by flessard** [ParsePlatform/parse-server#260]
If i try to change the password for a user, i always got Object not found error after save user object.
This is my code i user in cloud code function.

`
var query = new Parse.Query(Parse.User);
    query.equalTo("email", request.params.email);

    return query.first().then(function(user) {
        if (user && user.get('resetPasswordCode') === request.params.code) {
            user.set('resetPasswordCode', '');
            //if comment this line, work fine
            user.setPassword(request.params.password);
            return user.save();
        } else {
            return Parse.Promise.error(new FOLO.Error(FOLO.Error.RESET_PASSWORD_EMAIL_NOT_FOUND, "No account found with that email address."));
        }
    }).then(function() {
        response.success(FOLO.Response());
    }, function(error) {
        response.error(error);
    });
`

**Comment by Tibabal** [comment]
You need to call Parse.Cloud.useMasterKey() to update an user which is not logged in

**Comment by flessard** [comment]
Yes i call it. I just include a part of my code where don't include the header where i call Parse.Cloud.useMasterKey().

**Comment by gfosco** [comment]
Try `return user.save(null, { useMasterKey: true });`

**Comment by flessard** [comment]
@gfosco nice, is working. Thanks for your help !

**Comment by Tibabal** [comment]
Why didn't `Parse.Cloud.useMasterKey()` worked in your case ?

**Comment by flessard** [comment]
yeah good question. Why @gfosco ?

**Comment by drew-gross** [comment]
`useMasterKey`is a function that modifies global variables. On parse.com, this is fine, because a new JavaScript environment is created for every function call, but in a Node.js environment, global variables can affect other requests that are in progress. `useMasterKey`, along with `Parse.User.current()`, are just two things that fundamentally can't exist in a Node.js based version of Cloud Code.

**Comment by flessard** [comment]
Ok thanks @drew-gross !

**Comment by Tibabal** [comment]
That should be explicitly told in Parse Migration Guide - 3. Cloud Code.
This could break many apps that are using Parse.Cloud.useMasterKey instead of {useMasterKey : true}
