### ISSUE TITLE
How is everyone going about implementing scheduled jobs / cloud jobs?

### ISSUE THREAD

**Issue by asdf01** [ParsePlatform/parse-server#2602]
Hey Guys

According to the [migration guide](https://github.com/ParsePlatform/parse-server/wiki/Compatibility-with-Hosted-Parse) we could use something like [Kue](https://github.com/Automattic/kue) and [Kue-UI](https://github.com/stonecircle/kue-ui) to emulate the parse.com scheduled jobs functionality.  

I haven't implemented Kue or Kue-ui, but looking at the guides, it doesn't look like it provides anywhere close to the same level of functionality as the existing parse.com scheduled jobs.  Is this observation correct?  Has someone implemented this?  Is it true that jobs have to be scheduled through Kue in javascript and Kue-ui only provides a summary of the current status of the jobs and new schedules can't be added through Kue-ui?

Has anyone tried to achieve the same outcome with something like Jenkins?  So this is what I had in mind:
- each job would still be defined in the cloud code Parse.Cloud.job("job01", function(request, response) {));
- modify parse-server slightly to expose job at a similar url to existing cloud functions e.g. /parse/jobs/job01 (this might exist in parse already, i don't know)
- create a new jenkins job do a curl at that url
- define a cron like schedule for that jenkins job from within the jenkins web ui

I can see the benefits being:
- little to no coding
- setting up jenkins sounds like much less work then setting up kue, redis and kue-ui
- existing cloud job / definitions stay exactly the same
- schedule and manually trigger jobs through the jenkins web ui

The only thing that the current parse.com schedule jobs / cloud jobs can do that the jenkins based solution can't is being able to select a job name to create a new schedule for from a drop down list.  

Am I missing something?  How is everyone else going about this?  Thanks.

**Comment by flovilmart** [comment]
See #2560

**Comment by asdf01** [comment]
Hi @flovilmart 

Thanks for adding the /jobs endpoint to parse-server.  I haven't gotten your changes to parse-server and parse-dashboard running yet so I don't know exactly what's included.  But from what I can see from [your comments](https://github.com/ParsePlatform/parse-server/pull/2560):
> Jobs need an external scheduler.

The scheduling part is still outside the scope of the solution you provided is that right?  We would still need to fill that gap with either kue or Jenkins is that right?

**Comment by flovilmart** [comment]
Yes, you would need to have a cron like scheduler on a server that would trigger those jobs.

**Comment by asdf01** [comment]
Hi @flovilmart

> Yes, you would need to have a cron like scheduler 

Thanks for confirming that.  

Can you leave this ticket open.  There were a few other parts to my original query.  What I still don't know is whether Kue-UI allows you to create new schedules for jobs or whether those need to be created in Kue and Kue-UI is just for viewing the status.  Maybe you know the answer to this...  Thanks.

**Comment by flovilmart** [comment]
That would be for another platform than here.

This is not a support group for implementation details, but to report issues and bugs. As this request don't fall in either category, we'll keep it closed.
