### ISSUE TITLE
PostgresStorageAdapter not support collectionPrefix？

### ISSUE THREAD

**Issue by rendongsc** [ParsePlatform/parse-server#2603]
._collectionPrefix  has been defined, but not used.

**Comment by flovilmart** [comment]
Yup, it's not used yet, PR are welcome :)

**Comment by flovilmart** [comment]
@rendongsc do you want to work on the PG adapter?

**Comment by rendongsc** [comment]
@flovilmart  yes, and hope to provide collectionPrefix support.
thanks!

**Comment by flovilmart** [comment]
Awesome! Thanks for your commitment! Can't wait to get that PR in. 

Look at the .travis.yml build matrix, we use an env variable to switch on the tests against the postegres DB. Note also that postgis extensions should be enabled for the geopoints tests.
