### ISSUE TITLE
Request timeout with a Cloud Function that returns large JSON payload

### ISSUE THREAD

**Issue by bourquep** [ParsePlatform/parse-server#261]
I have a Cloud Function that returns a large JSON payload (~1 meg), and which worked fine until updating to v2.0.7, but now leads to a HTTP request timeout (30s) error.

Reverting commit 36675a9598f7b493bb966ab5edbe37b28c307d03 makes it work again.

Looks like `Parse._encode` is doing some heavy processing on the JSON payload and is hanging my request.

**Comment by laullon** [comment]
Yes, I know... 

I'm looking for other to correct the ParseObject JSON

Take a look of this bug: https://github.com/ParsePlatform/parse-server/issues/112
and tha bug on parse-ha-sdk linked on it.

**Comment by gfosco** [comment]
@bourquep Was this something which worked on hosted Parse or something new?.   Maybe we could add a raw response method (if the response isn't parse objects)?

**Comment by bourquep** [comment]
Yes, it was working fine on hosted Parse. I have a lot of Cloud Functions that return "custom" JSON (array of non-Parse objects), and it's always been running smoothly on hosted Parse.

I could live with a raw response method if there is no other way.

**Comment by bourquep** [comment]
But if `Parse._encode()` is indeed doing a lot of data processing, it would probably cause request timeouts for cloud functions that return a large array of Parse objects, no? So it might be worthwhile fixing the root of the problem?

**Comment by laullon** [comment]
Can you measure the time of Parse._encode with your payload?

**Comment by bourquep** [comment]
Sure! I might only have time to do it next week though.

**Comment by laullon** [comment]
@gfosco can you please take a look of this https://github.com/ParsePlatform/Parse-SDK-JS/issues/199 ?

I still think the promblem is on the parse-SDK-JS...

**Comment by gfosco** [comment]
Any chance we can get a payload example to process, @bourquep ?

**Comment by gfosco** [comment]
Going to close this.. If you can reproduce and provide more details with 2.1.3+ please create a new issue.  Thanks.
