### ISSUE TITLE
parse not updating from 1.4.0 

### ISSUE THREAD

**Issue by thealmogg** [ParsePlatform/parse-server#2611]
- [X ] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.

- [X ] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases

- [ X] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.

- [X ] You have filled out every section below. Issues without sufficient information are more likely to be closed.

--

### Issue Description

[DELETE EVERYTHING ABOVE THIS LINE BEFORE SUBMITTING YOUR ISSUE]

Describe your issue in as much detail as possible.

After installing parsק-server-example on [DigitalOcean](https://www.digitalocean.com/community/tutorials/how-to-run-parse-server-on-ubuntu-14-04) droplets server - can't update parse version.
current on package.json =   "version": "1.4.0",
when trying to update, git says all up to date.

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1. tried to delete and install 55 times
2. tried to update as mentioned in the git readme
3. tried to git the parse-server source - no success.

#### Expected Results

parse dashboard says that parse server is out of date

#### Actual Outcome

can't update

### Environment Setup

- DigitalOcean
  - parse-server version (Be specific! Don't say 'latest'.) : 1.4.0
  - Operating System:    ubuntu 14.04.05 X64bit
  - Hardware:         512MB cpu, 20gb disk
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Digital Ocean

- **Database**
  - MongoDB version: 3.0.12
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Digital Ocean

**Comment by flovilmart** [comment]
Not relevant to this repository as it seems to be either parse-server-example or digital océan. 

Issues are meant to be opened for bugs and unexpected behaviors only, not general support and usage of node, npm or deployment providers
