### ISSUE TITLE
Different errors assigned to the same code 209

### ISSUE THREAD

**Issue by courteouselk** [ParsePlatform/parse-server#2626]
If I do `PFSession.getCurrentSession()` right after the call to `PFUser.logOut()` then I receive `[Error]: Session token required. (Code: 209, Version: 1.14.2)`.

After checking the documentation I see another kind of error assigned to the same code 209, that is, `InvalidSessionToken` with description:

> The device’s session token is no longer valid. The application should ask the user to log in again.

The "problem" is, I got into present situation after doing exactly that, that is logging the user out after I receive another kind of 209 error, namely "Invalid session token".

IMO, the "session token required" state should have a different error code, not colliding with "invalid session token".  **Is this something by-design or a bug?**

I use Parse Server version 2.2.18 with Parse-SDK-iOS-OSX version 1.4.2.

**Comment by hramos** [comment]
This is by design, the 209 error code indicates that a valid session token was not found. This can be either due to a token that has been invalidated, or due to a lack of a session token (as is the case after logging out).
