### ISSUE TITLE
130 Could not store file - Parse server not saving Image PFFIile 

### ISSUE THREAD

**Issue by takomborerwa** [ParsePlatform/parse-server#2629]
Right, so I'm using parse server with Heroku and mongo db and am writing in Objective-C. Its the 'parse server example' created with the purple Heroku button.  So I can save some images but not others. They are all PNGs and less than a 200KB in size.

 I get the I get the following error

' [Error]: Could not store file. (Code: 130, Version: 1.14.2)' 

The following is the code that I use to save the image 

`NSData *imageData = UIImagePNGRepresentation(chosenImage);`
` PFFile *imageFile = [PFFile fileWithName:@"storeProfilePhoto.png" data:imageData];`
`[self.store setObject:imageFile forKey:@"storeProfilePhoto"];`
`[self.store saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {...`

I have tried using the content type after reading posts in the issues tab of this project

`imageFile = [PFFile fileWithName:@"storeProfilePhoto.png" data:imageData contentType:@"image/png"]`

The version of parse server that I'm using is from 2-3 weeks ago (early - mid august 16).

Can you help me please?

**Comment by natanrolnik** [comment]
@takomborerwa did you configure a File Adapter? If not, did you read the [Wiki about it](https://github.com/ParsePlatform/parse-server/wiki/Configuring-File-Adapters)? The default "Deploy to Heroku" button doesn't have any File Adapter set up. Please consider closing this issue as File Storage is tested and works fine if correctly configured.

**Comment by takomborerwa** [comment]
Hi @natanrolnik. Thanks for the link. Ive been reading the wiki. The wiki suggests that the GridStoreAdapter is default and requires no additional setup. The other adapters would be used for AWS and GS. The following post also suggests the previous point to be so

https://github.com/ParsePlatform/parse-server/issues/1027

I am using Heroku + MongoDB with the parse-server-example project. 

My code successfully saves some images, but not others which is peculiar.

Below is a link to a 1 min video that shows two failed uploads to the DB and one successful upload

https://www.youtube.com/watch?v=VDvs5hWuAMY&feature=youtu.be

Can you help me please?

**Comment by takomborerwa** [comment]
Right problem solved. So I realised that there the images that were uploading were smaller than the ones being upload. The issue was that I was on the verge of exceeding my database sandbox storage and so I was unable to upload the larger files.

**Comment by natanrolnik** [comment]
@takomborerwa right, my bad. I'm glad you found the reason. Besides this reason, using the `GridStoreAdapter` is not the best solution - I definitely suggest you configuring S3 or GS.

**Comment by wellkeptbeauty** [comment]
@takomborerwa 
I am using Heroku + MongoDB with the parse-server-example project.

images are not stored and we can not get the previous images which was already in the parse.

**Comment by wellkeptbeauty** [comment]
@takomborerwa  @NatanRolnik  unsupported URL (Code: 100, Version: 1.14.2) 
when i am getting this error for downloading images from mongoldb+heroku after migration.
please could you suggest how to resolve this problem

**Comment by greggmojica** [comment]
+1
