### ISSUE TITLE
[Question] scalabality and features of parse

### ISSUE THREAD

**Issue by deada92** [ParsePlatform/parse-server#2642]
Hello everyone,
I would like to hear your opinion on a subject: im currently at the planning phase of a new project I have. I'm thinking atm about the backend solution I should use and I'm not really sure which one.
I'm a really big fan of parse because I really love their sdks. I tested parse server when it came out but I'm not sure how things work at the moment. I'm thinking specific about social login, complex queries, pointers and cloud code.

Many use aws but I don't know how people use it in the app development space. I have the feeling that parse server has many features like storage adapters etc. but I feel its like put in the shadow and normal user like me dont really know what are the pros or cons of using another adapter.

With all this things in my head i dont want to ignore the scale factor. How can I implement a scaled parse server infrastructure?

Can you guys share your parse backend solutions with the technology that you use?

**Comment by flovilmart** [comment]
It is designed to scale properly horizontally. But it doesn't scale by itself.

**Comment by deada92** [comment]
do u have like a way how to setup multiple parse server as one?

**Comment by flovilmart** [comment]
You can run different processes, on the same machine, listening to different ports. But as it is today, and likely to be in the future, we can't support multiple applications in the same node process due to the memory sharing of the JS SDK

**Comment by deada92** [comment]
Well what I mean was how can setup a parse server cluster for one application... but anyway I think I should use Heroku with MongoLab Plugin. As far as I understood they manage all the scaling and load balancing of parse server. I would say its a good solution.

Would u agree?

**Comment by flovilmart** [comment]
It is a gréât solution to get started. I personally use app engine, but when it will be time to another infrastructure, you'll know why :)

**Comment by ssssssssssss** [comment]
I'm really interested in LiveQuery, but it needs more configurations to run cluster properly (say Redis). And currently, I can't find a mechanism to hookup our own cloud code logic for LiveQuery. Is there any plan to support live query hooks or even extending LiveQuery specification?

**Comment by flovilmart** [comment]
@ssssssssssss there are not any plan that I know of, we move forward with what matters the most in the community.
