### ISSUE TITLE
deleted all servers  on my machine only npm is installed still i got this issue please help me.

### ISSUE THREAD

**Issue by mohit-guptaa** [ParsePlatform/parse-server#2643]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart reactapp@1.0.0
6 info start reactapp@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info reactapp@1.0.0 Failed to exec start script
9 verbose stack Error: reactapp@1.0.0 start: `webpack-dev-server --hot`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid reactapp@1.0.0
11 verbose cwd C:\Users\mohit\Desktop\reactapp
12 error Windows_NT 10.0.10586
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.5.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error reactapp@1.0.0 start: `webpack-dev-server --hot`
17 error Exit status 1
18 error Failed at the reactapp@1.0.0 start script 'webpack-dev-server --hot'.
18 error This is most likely a problem with the reactapp package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     webpack-dev-server --hot
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs reactapp
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls reactapp
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by flovilmart** [comment]
From the logs:

error This is most likely a problem with the reactapp package

**Comment by flovilmart** [comment]
Also we don't use webpack or anything else like that. This issue don't seem to be related to parse-server

**Comment by mohit-guptaa** [comment]
Thanx 
when I downloaded the plugins there is no error shown by prompt and after that when I write (npm start ) it shows these errors
+
I done yesterday on other system it works properly but in my system it's not 
Can u provide me steps for solve this problem or other steps for making environment to run a react js or provide me suitable link ...

**Comment by flovilmart** [comment]
This is a problem that is completely unrelated with that project, and I won't be able to provide any help on that matter. You should ask on stackoverflow instead.

**Comment by mohit-guptaa** [comment]
Ok thanx..
