### ISSUE TITLE
info logs being saved in parse-server.err.*.log

### ISSUE THREAD

**Issue by benishak** [ParsePlatform/parse-server#2644]
# Env
Parse Server 2.2.17 on AWS with PM2 and NGINX CentOS 7.x

# Problem
since 2.2.17, we started see some logs when `after/beforesave` triggers, these are somehow logged to `parse-server.err.*.log`  instead `parse-server.info.*.log` files!

Because we watch `parse-server.err.*.log` with PM2 but ignore `info` and `verbose` pm2 restart node everytime   `after/beforesave` triggers

**Comment by flovilmart** [comment]
You should stop watching the logs folders altogether. you can specify a [custom path to the logsFolder](https://github.com/ParsePlatform/parse-server/blob/master/src/ParseServer.js#L103).

**Comment by cleever** [comment]
@flovilmart 
It's seem related
https://github.com/ParsePlatform/parse-server/issues/2639

**Comment by benishak** [comment]
Yeah the problem is not about were files are stored in which directory but it is about the info logs are being saved in error logs and interpreted as errors! I don't want to ignore error logs

**Comment by flovilmart** [comment]
Yep it's related but pm2 should not restart when a log is writte, so it's best to log in a folder that is not in the pm2 scope. Actually, pm2 should not monitor at all the files in that folder... that seems a pretty big security issue.

**Comment by benishak** [comment]
Security issue ? Can you explain how?
It is useful to monitor error logs, so when tgere is error in some modules or functions within cloud code that makes the node process exit, we can know about it and pm2 start the node again.

**Comment by flovilmart** [comment]
File upload + bad express configuration + server arbitrary code execution. 

An error logged in the log file should not restart the server... When an app logs an error, does it restart? If we wanted to exit on error, we would throw an exception and effectively crash the server. 

Yes #2639 is a problem (a regression), but what you're describing is just weird. You can stick to it, but I've never seen that before and still don't believe it's a good idea to restart a server based on the fact that an error is logged.

You should probably look into a way of centralizing your logs and trigger alerts when some error occur.

Also, note that any non 200 response are logged so:
object not found will restart your server, invalid session token will restart etc... Not sure you want that...

**Comment by benishak** [comment]
hey that's why only error must go to error logs, because that file were only storing error in kind of "Unexpected syntax" or "Exceptions" or "Undefined variables" but now store everything!

```
aftersave trigger for object { ... object data ... } 
```
This is clearly not an error!!

why should I have info.log and err.log with same log message?!

**Comment by flovilmart** [comment]
I'm not arguing about the fact that for some reason, info logs are into the error log, that's the issue #2639.

I'm just saying that having a server restart on an line written in the error log is not a great idea. Then you can just dismiss what I think, or better provide a fix for the issue instead of waiting for someone else to do it.

Having a process manager that watch when the process crashes that's OK, but there is no need to restart if an error is logged... After all that's your setup, but we won't stop writing to the error log just so your server is not rebooting all the times...

When nginx writes to the error_log do you think it restarts?

**Comment by benishak** [comment]
And that's what im talking about! info and verbouse should not be logged as error. My issue is similar to #2639. I will fix it but my time is tight and thought will be faster to inform the community. In production we actually muted some logs and the app crashes only in cases when an error or exception was thrown. But in development we keep logging and we don't prefer to ignore error.log so developer are aware of bugs.

nginx error are not monitored by pm2 and should not be monitored. It makes no sense.
I give you a good example when it is useful to monitor parse error.log:
Because we are sharding sometime mongoclient return error when a replicaset is doing election. For somehow parse here keep connection and stop working. To make parse reconnect again you must restart. This kind of error actually doesn't cause the app to crash but is only logged to err.log. if i ignore err.log pm2 won't restart the app

**Comment by flovilmart** [comment]
That would be nice to fix that mongo election bug too.

**Comment by flovilmart** [comment]
@benishak See #2647
