### ISSUE TITLE
TypeError: Parse.Cloud.define is not a function

### ISSUE THREAD

**Issue by sraveh** [ParsePlatform/parse-server#265]
After I upgrade to version 2.0.7 parse-server can't start and throws TypeError: Parse.Cloud.define is not a function

Everything works correctly when I downgrade back 2.0.6

Simon

**Comment by gfosco** [comment]
By any chance are you defining/requiring Parse at the top of your cloud code file?  It should be global and it is mutated, so requiring it again can remove the Cloud definitions.

**Comment by sraveh** [comment]
Yes, and removing the required statement did solve the issue, but I'm now getting ParseError { code: undefined, message: 'unauthorized' } regardless if I provide the session token or not. This happens even in cloud code that does not require any user to be authenticate.

I added the require statement to solve the issue reported by evblurbs in https://github.com/ParsePlatform/parse-server/issues/188

**Comment by sraveh** [comment]
The second error was due to misconfiguration of serverURL

**Comment by wladneto** [comment]
Thanks!
