### ISSUE TITLE
[Discussion] Select fields does not propagate to the Mongo Layer 

### ISSUE THREAD

**Issue by shivangagarwal** [ParsePlatform/parse-server#2653]
Hi,

Is there a specific reason as to why the select fields are not propagated to the Database Controller layer and further passed on to Mongo? Currently all the fields are fetched from Mongo and then sliced at the parse-server level, but we can just pass the select fields to the Mongo itself. By adding these changes, the queries are much much faster. 

Let me know if i am missing something. If this is fine, i can provide with a PR.

**Comment by flovilmart** [comment]
No specific reason. Go ahead! I believe you can also do the same for $dontSelect.

Just one note, we're trying to move forward with the PG adapter as well, so that change should be also propagated to the PG adapter.

**Comment by flovilmart** [comment]
Closing has it's been merged to master and released to 2.2.22
