### ISSUE TITLE
Trigger a counter on ParseRelation update (discussion)

### ISSUE THREAD

**Issue by Toofoo** [ParsePlatform/parse-server#2655]
Is it possible to persist a dedicated counter on each ParseRelation, that could be automatically incremented/decremented every time an item is added or removed from the ParseRelation?

This would avoid to call a "count" query or to implement a dedicated client or cloud code to increment the number of items in a ParseRelation (which sometimes force to give write access on the counter for all the users).

**Comment by flovilmart** [comment]
You should use a beforeSave or an afterSave trigger to update that count.
