### ISSUE TITLE
Allow Cloud Code functions to be RESTfully called with other HTTP methods

### ISSUE THREAD

**Issue by vincentonderwaater** [ParsePlatform/parse-server#2659]
Right now, Cloud Code functions can be only called with a `POST` to `/parse/functions/` and setting the right headers. I suggest that `GET`, `PUT` and `PATCH` be also allowed so the API is truly RESTful. This is useful for interacting with Parse DB for clients that can't have the Parse SDK installed.

**Comment by flovilmart** [comment]
Actually any other semantic than POST don't make sense as there is some data that is expected to run during a Cloud Function. 

Without the SDK, that's quite easy to call a POST method instead of a GET, I don't really see the benefits.

What would you see behind  `GET`, `PUT` and `PATCH`.

**Comment by hramos** [comment]
Agree with @flovilmart. Cloud functions are a special case, where the client is posting data to the server.
