### ISSUE TITLE
Is it safe to empty the _PushStatus collection/class?

### ISSUE THREAD

**Issue by benishak** [ParsePlatform/parse-server#2665]
Is it safe to empty the _PushStatus collection/class?

**Comment by flovilmart** [comment]
yes, it is, it's just storing the history of your sent pushes

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.20](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.20)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.5.0](https://github.com/parse-community/parse-server/releases/tag/6.5.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)
