### ISSUE TITLE
Crash if logout is made to not existing user

### ISSUE THREAD

**Issue by jpv123** [ParsePlatform/parse-server#2667]
Not sure if this is happening to anyone but it just happened to me. If I have a user in the cache accessible with PFUser.currentUser(), I remove the user via Parse Dashboard and then do a PFUser.logOut(), the app gots a message saying 

[Error]: invalid session token (Code: 209, Version: 1.14.2)

And the server automatically crashes. I need to do a Heroku Restart to get the server working again. 
### Steps to reproduce
1. Create a new user in Parse
2. Login in the app with that user
3. Remove the user of the server via Parse Dashboard
4. On the app make a Logout
#### Expected Results

There should be just the error 209 and the server should still working normally
#### Actual Outcome

The server just crashes and I need to do a Heroku Restart to get it up again. No error message displayed. It just doesn't work
### Environment Setup
- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.18
  - Operating System:     Heroku (Not sure which operating system is)
  - Hardware:            Once again Heroku
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku
- **Database**
  - MongoDB version: 3.0.10
  - Operating System:  mLab
  - Hardware:  mLab
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): mLab
    ### Logs/Trace

I'm not getting any logs with the error. Not sure if I need to do anything else. All my cloud code functions just starts failing

**Comment by hramos** [comment]
Can you try running with VERBOSE=1? You can run the server locally and try to reproduce the issue there, if you're unable to grab the logs from Heroku.

**Comment by jpv123** [comment]
I enabled the Verbose Mode, however when I run the Logout function I'm only getting

at=info method=POST path="/parse/logout" host=myapp.herokuapp.com request_id=454c2bca-f8db-48e1-862e-c1d6dd08.... fwd="---.--.--.--" dyno=web.1 connect=0ms service=31ms status=400 bytes=535
2016-09-07T23:54:50.643333+00:00 app[web.1]: [object Object]

Any ideas?
