### ISSUE TITLE
Parse-server returns all users when login with facebook

### ISSUE THREAD

**Issue by dan-merlea** [ParsePlatform/parse-server#2670]
### Issue Description

I moved from parse to parse server and the facebook login returns me all users instead of the logged one. I thought it's something wrong in my app, but I tried with a different implementation by just changing the keys and server url and it's the same. The problem must be either in the parse server or in the way I'm using it.

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1. One way to reproduce was even with PFLogInViewController
```
PFLogInViewController *controller = [[PFLogInViewController alloc] init];
    controller.fields = (PFLogInFieldsUsernameAndPassword | PFLogInFieldsFacebook | PFLogInFieldsDismissButton);
    [self presentViewController:controller animated:YES completion:nil];
```
By placing a break at line 340
2. Or with 
```
[PFFacebookUtils logInInBackgroundWithReadPermissions:permissionsArray block:^(PFUser * _Nullable user, NSError * _Nullable error) {
        if (!error) {
            if (user) {
                completion(YES, user.isNew, nil);
            } else {
                completion(NO, NO, nil);
            }
        } else {
            completion(NO, NO, error);
        }
    }];
```
3. The app works great with normal parse.

#### Expected Results

```
<UserModel: 0x7bec89c0, objectId: gQenEgueiD, localId: (null)> {
    ACL = "<PFACL: 0x7beb1330>";
    email = "xxx@yahoo.com";
    firstName = xx;
    lastName = xx;
    username = xxx;
    ........
}

```
#### Actual Outcome

```
<UserModel: 0x79034bd0, objectId: new, localId: (null)> {
    results =     (
                {
            about = "xxxx";
            address = xxx;
            age = 24;
            createdAt = "2016-01-25T16:26:31.549Z";
            email = "xxxx@yahoo.com";
            facebookLinked = 1;
            firstName = xxxx;
            gender = male;
            hasUnits = 1;
            lastName = xxx;
            newsletters = 1;
            notifications = 1;
            objectId = G734HJbW6t;
            phone = xxxx;
            public = 1;
            publicPhone = 1;
            thumb = "users/G734HJbW6t/thumb.png?_ts=1470083786";
            updatedAt = "2016-09-07T20:12:37.226Z";
            username = "xxxx@yahoo.com";
        },
                {
            ACL =             {
                "*" =                 {
                    read = 1;
                };
                FI9UWHnXnn =                 {
                    read = 1;
                    write = 1;
                };
            };
            about = "xxxx";
            admin = 1;
            createdAt = "2016-04-04T11:26:34.060Z";
            email = "xxxx@yahoo.com";
            firstName = xxxx;
            hasUnits = 1;
            lastName = xxxx;
            newsletters = 0;
            notifications = 0;
            objectId = FI9UWHnXnn;
            phone = xxxx;
            public = 1;
            publicEmail = 1;
            publicName = 1;
            publicPhone = 1;
            thumb = "users/FI9UWHnXnn/thumb.png?_ts=1470052994";
            updatedAt = "2016-08-02T13:10:44.307Z";
            username = "xxxx@yahoo.com";
        },
                {
            ACL =             {
                "*" =                 {
                    read = 1;
                };
                4evIWegJCs =                 {
                    read = 1;
                    write = 1;
                };
            };
            createdAt = "2016-04-06T17:07:45.997Z";
            email = "xxxx@yahoo.com";
            firstName = xxx;
            lastName = xxx;
            newsletters = 1;
            notifications = 1;
            objectId = 4evIWegJCs;
            phone = xxxx;
            public = 1;
            thumb = "placeholders/default.png";
            updatedAt = "2016-04-06T17:07:45.997Z";
            username = "xxxx@yahoo.com";
        },
                {
            ACL =             {
                "*" =                 {
                    read = 1;
                };
                QGLh9ZnJOq =                 {
                    read = 1;
                    write = 1;
                };
            };
            createdAt = "2016-04-20T20:36:34.749Z";
            email = "xxx@xxxx.io";
            hasUnits = 1;
            newsletters = 1;
            notifications = 1;
            objectId = QGLh9ZnJOq;
            public = 1;
            publicName = 1;
            thumb = "placeholders/default.png";
            updatedAt = "2016-04-27T17:40:59.507Z";
            username = "xxx@xxx.io";
        },
                {
            ACL =             {
                "*" =                 {
                    read = 1;
                };
                oYaEVpyjfE =                 {
                    read = 1;
                    write = 1;
                };
            };
            createdAt = "2016-04-23T16:01:49.624Z";
            email = "xxxx@gmail.com";
            hasUnits = 0;
            newsletters = 1;
            notifications = 1;
            objectId = oYaEVpyjfE;
            public = 1;
            publicName = 1;
            thumb = "placeholders/default.png";
            updatedAt = "2016-04-27T17:40:59.390Z";
            username = "xxx@gmail.com";
        },
                {
            ACL =             {
                "*" =                 {
                    read = 1;
                };
                5vzcYuENXi =                 {
                    read = 1;
                    write = 1;
                };
            };
            createdAt = "2016-05-03T10:39:34.348Z";
            email = "xxxx@yahoo.com";
            hasUnits = 1;
            newsletters = 1;
            notifications = 1;
            objectId = 5vzcYuENXi;
            public = 1;
            thumb = "placeholders/default.png";
            updatedAt = "2016-05-03T14:32:52.874Z";
            username = "xxxx@yahoo.com";
        }
]
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.18
  - Operating System:     ubuntu 14.04
  - Hardware:  1GB Memory, 1 Core Processor
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): digital ocean

- **Database**
  - MongoDB version: 3.0.9
  - Storage engine: mmapv1
  - Hardware:  1GB Memory, 1 Core Processor
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): digital ocean

### Logs/Trace

In the logs folder I don't have any error / info about this problem.

**Comment by flovilmart** [comment]
I'lll have a look.

**Comment by flovilmart** [comment]
@dan-merlea can you run with VERBOSE=1 and provide the trace of request/responses relevant to those calls? That would greatly help isolate the issue. I tried to reproduce with the JS SDK and the master branch, but that doesn't seem to cause problems.

**Comment by dan-merlea** [comment]
Sure. Just to know I found this issue just on iOS SDK. I also have a PHP website linked to the same server and it works.

I runned with verbose 1 and I have this:

verbose: REQUEST for [GET] /parse/users: {} method=GET, url=/parse/users, x-real-ip=213.233.85.105, x-forwarded-for=213.233.85.105, x-nginx-proxy=true, host=tourismfeed.com, connection=close, x-parse-app-display-version=1.0, x-parse-application-id=qbfJd7BJDxEge6ecEWymzLgd5EJkwoDYV6RsZzJD, accept=*/*, accept-language=en-us, x-parse-os-version=9.3 (15F34), x-parse-client-key=, user-agent=GeoTrip/1 CFNetwork/758.3.15 Darwin/15.5.0, x-parse-app-build-version=1, x-parse-client-version=i1.14.2, x-parse-installation-id=f24ab31e-0288-4b72-aefb-36327a8c16c7, accept-encoding=gzip, deflate, 
verbose: RESPONSE from [GET] /parse/users: {
  "response": {
    "results": [
      {
        ......
      }
   ]
  }
}

In the results are all the users.. I won't paste them again..

**Comment by flovilmart** [comment]
This is very very odd that you get that when trying to use the Facebook linking. No POST or PUT request?

**Comment by dan-merlea** [comment]
No.. This is all. Maybe I am doing something wrong and I don't notice.
But as I said I tried even with Parse controller and it's the same

```
PFLogInViewController *controller = [[PFLogInViewController alloc] init];
controller.fields = (PFLogInFieldsUsernameAndPassword | PFLogInFieldsFacebook | PFLogInFieldsDismissButton);
[self presentViewController:controller animated:YES completion:nil];
```

**Comment by flovilmart** [comment]
This is definitely odd. I believe there is a way to trace the requests generated by the iOS SDK. Could you try that out? You say it's working correctly on Parse.com.

**Comment by dan-merlea** [comment]
Sure. Tell me what to do. Yes, with parse.com works good

**Comment by dan-merlea** [comment]
2016-09-09 15:26:15.354 GeoTrip[40252:27080219] URL : http://myserver.com/api/users
2016-09-09 15:26:15.354 GeoTrip[40252:27080219] Method : POST
2016-09-09 15:26:15.354 GeoTrip[40252:27080219] Headers : {
    "Content-Type" = "application/json; charset=utf-8";
    "X-Parse-Installation-Id" = "myId";
}
2016-09-09 15:26:15.355 GeoTrip[40252:27080219] Request Body : {"authData":{"facebook":{"id":"MY_FACEBOOK_ID","access_token":"MY_ACCESS_TOKEN","expiration_date":"2016-11-08T06:20:30.601Z"}}}
2016-09-09 15:26:15.728 GeoTrip[40252:27078972] URL : https://tourismfeed.com/api/users
2016-09-09 15:26:15.728 GeoTrip[40252:27078972] Status Code : 200
2016-09-09 15:26:15.728 GeoTrip[40252:27078972] Headers : {
    "Access-Control-Allow-Headers" = "X-Parse-Master-Key, X-Parse-REST-API-Key, X-Parse-Javascript-Key, X-Parse-Application-Id, X-Parse-Client-Version, X-Parse-Session-Token, X-Requested-With, X-Parse-Revocable-Session, Content-Type";
    "Access-Control-Allow-Methods" = "GET,PUT,POST,DELETE,OPTIONS";
    "Access-Control-Allow-Origin" = "*";
    Connection = "keep-alive";
    "Content-Length" = 10515;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Fri, 09 Sep 2016 12:26:15 GMT";
    Etag = "W/\"2913-65zLMRPSX8VdM2uUeCAx5A\"";
    Server = "nginx/1.4.6 (Ubuntu)";
    "X-Powered-By" = Express;
}
2016-09-09 15:26:15.729 GeoTrip[40252:27078972] Response Body : {"results": ALL_USERS

**Comment by flovilmart** [comment]
Alright thanks I'll debug that, seems that the POST gets interpolated into a GET. I'll keep you posted with my findings

**Comment by flovilmart** [comment]
For the username based logging, can you attach the server trace?

**Comment by dan-merlea** [comment]
verbose: REQUEST for [GET] /parse/login: {} method=GET, url=/parse/login, x-real-ip=213.233.85.105, x-forwarded-for=213.233.85.105, x-nginx-proxy=true, host=myserver.com, connection=close, x-parse-app-display-version=1.0, x-parse-application-id=APP_ID, accept=*/*, accept-language=en-us, x-parse-os-version=9.3 (15F34), x-parse-client-key=, user-agent=GeoTrip/1 CFNetwork/758.3.15 Darwin/15.5.0, x-parse-app-build-version=1, x-parse-client-version=i1.14.2, x-parse-installation-id=PARSE_INSTALLATION_ID, accept-encoding=gzip, deflate, 
error: Error handling request: ParseError { code: 200, message: 'username is required.' } code=200, message=username is required.
[object Object]

**Comment by flovilmart** [comment]
@dan-merlea  I'm running some tests locally and I'm not able to reproduce this issue.

It would seem that ALL your requests incoming to parse server are re-written as GET (instead of being proper POST requests). 

I see there is a `x-nginx-proxy=true` in all your requests, by any chance, would there be a line in your nginx config  that would rewrite all the methods to GET? Maybe for another purpose but affecting the parse-server route?

**Comment by dan-merlea** [comment]
I'll take a look, but all the requests coming from the PHP SDK works fine.

**Comment by dan-merlea** [comment]
I've used this tutorial: https://www.digitalocean.com/community/tutorials/how-to-migrate-a-parse-app-to-parse-server-on-ubuntu-14-04

**Comment by flovilmart** [comment]
Yeah, that's very very odd indeed. Did you try running parse-server locally and point your client SDK to your local server (localhost won't work, you'll need the full IP address from your dev machine so the simulator can reach your parse-server)

**Comment by dan-merlea** [comment]
I will try this weekend and reply until monday.

**Comment by flovilmart** [comment]
I'll run more tests on my side as well, I really don't get what's going on.

**Comment by dan-merlea** [comment]
No way... it was a dummy mistake of mine.. It looks like I was requesting on http instead of https and all my requests were transformed into GET ones. 

I guess you can close this one now. Thanks for your time

**Comment by flovilmart** [comment]
Glad you found a resolution!
