### ISSUE TITLE
Schema updates are made BEFORE cloud code beforeSave triggers are invoked

### ISSUE THREAD

**Issue by AndrewLane** [ParsePlatform/parse-server#2672]
Let's say you have a class called Foo and you have a business rule that says that no client is allowed to write data to a property called "secret".  So, you create a 

```
Parse.Cloud.beforeSave
```

method and inspect

```
request.object.attributes
```

and then call response.error if "secret" is found.  In this case, since the request has been rejected, you would not expect any schema updates to be made.  However, in this scenario, the schema gets updated and "secret" is added to the schema (if it's not already there) with whatever data type the bad request had for it.

My understanding of the code is that the reason for this is because, in RestWrite.prototype.execute, 

```
_this.validateSchema();
```

is called before 

```
_this.runBeforeTrigger()
```

I don't really know if this is considered a bug or not to most people, but at least I consider it a bug.  I'm just wondering if fixing it seems easy or possible.

**Comment by flovilmart** [comment]
Actually, it is done there: https://github.com/ParsePlatform/parse-server/blob/master/src/RestWrite.js#L179

Do you notice the behaviour you depict?

**Comment by AndrewLane** [comment]
Thanks for the quick fix!

**Comment by flovilmart** [comment]
@AndrewLane that as easy to fix and also a quite major issue.
