### ISSUE TITLE
Add SashiDo to your wiki on Community links

### ISSUE THREAD

**Issue by pivanov** [ParsePlatform/parse-server#2673]
Hey gusy,

**[SashiDo.io](http://www.sashido.io)** is a Parse Server Hosting Provider.
We takes care for the server management, so you can focus on your apps. As easy as before.

What You'll Enjoy:
- [x] 14 Days Free Trial.
- [x] Free Parse Migration in a Click.
- [x] Free File Migration in a Click.
- [x] Free Migration from any Parse Server without any down time! _([contact us](mailto:support@sashido.io))_
- [x] Auto-Scaling.
- [x] 24/7 Support.
- [x] Database Optimization.
- [x] Multi-Geo Coverage. _(currently EU region, US and Australia regions are coming)_
- [x] Advanced Cloud Code.
- [x] Static Web Site Hosting.
- [x] NodeJS App Hosting.
- [x] You can use your own Domain + SSL certificate for your end point. _([contact us](mailto:support@sashido.io))_
- [x] Free Private GitHub Repository.
- [x] Beautiful & Lightning Fast Dashboard.
- [x] Push Notifications.
- [x] Background Jobs. _(coming on 15.09.2016)_
- [x] Advanced Logs. _(coming on 15.09.2016)_
- [x] Webhooks. _(coming on 15.09.2016)_
- [x] API Console.
- [x] Social Logins.
- [x] Email Integration.
- [x] Global Configs.

... and we will not stop here :) we have more Features and Surprises for you!
Stay tuned :) [www.SashiDo.io ](http://www.sashido.io/)

Happy Coding & Viva La Open Source,
SashiDo Team

**Comment by mignev** [comment]
+1

**Comment by kdankov** [comment]
+1

These guys are awesome!

**Comment by flovilmart** [comment]
@pivanov can you give me a one liner as you want to see it in the community links? (I definitely can't put all there in there )

**Comment by pivanov** [comment]
Hey @flovilmart thanks in advanced. Here is the oneliner:

[SashiDo](https://www.sashido.io) - Affordable managed Parse Server hosting with care! Migration in a click. Auto Scaling. Simple and flexible pricing

**Comment by flovilmart** [comment]
Done! Thanks @pivanov

**Comment by pacogvillaran** [comment]
+1 
Very active and helpful!
