### ISSUE TITLE
Max CPU and possible crash when requesting logs

### ISSUE THREAD

**Issue by all-iver** [ParsePlatform/parse-server#2675]
### Issue Description

Using parse-server 2.2.17 or 2.2.18 and parse-dashboard 1.0.18, when I go to the Info or Error logs in the dashboard, nodejs spikes CPU and may eventually crash.

### Steps to reproduce

1. Install parse-server 2.2.18 and parse-dashboard 1.0.18, use verbose=1 for parse-server.
2. Presumably have a moderately large DB to get started.
3. Browse around for a bit and check the logs a few times.

#### Expected Results

Logs show up in a timely manner.

#### Actual Outcome

Nodejs CPU spikes, logs are ridiculously large and appear to get larger every time you check them - it appears that the logging operation itself is being logged, so each request will contain the full contents of the last request as well as the current request.  Particularly when using parse-dashboard, it is not helpful that the results of browsing around in the dashboard are also logged so that any actual user requests are buried under huge amounts of dashboard logging.  Using my production db the logs are apparently so large that nodejs crashes and restarts when I try to look at them.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.17 or 2.2.18
  - Operating System:     Mac or Linux
  - Hardware:             Macbook Pro or AWS ec2 instance
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): AWS or localhost

- **Database**
  - MongoDB version: not sure (mLab)
  - Storage engine:  not sure (mLab)
  - Hardware:        not sure (mLab)
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

### Logs/Trace

verbose: REQUEST for [GET] /parse/scriptlog?level=error&n=100: {} method=GET, url=/parse/scriptlog?level=error&n=100, host=localhost:1337, connection=keep-alive, content-length=148, cache-control=max-age=0, origin=http://localhost:4040, user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36, content-type=text/plain, accept=*/*, referer=http://localhost:4040/apps/Redacted%20App/logs/error, accept-encoding=gzip, deflate, accept-language=en-US,en;q=0.8,

**Comment by flovilmart** [comment]
You should not use VERBOSE=1 in production that's only meant for debugging purposes when you face an issue. The info logs should contain enough informations.

**Comment by all-iver** [comment]
I see...thanks for the info.  I removed VERBOSE and had some other problems but those should probably be discussed elsewhere.  Gonna close this issue then unless you are concerned about the verbose mode CPU spiking.

**Comment by flovilmart** [comment]
@all-iver having VERBOSE=1 and getting the logs from parse-dashboard is making it all recursive (fetch the logs and write them at the same time) which is not great I agree, but VERBOSE should not be run in production, only when you're debugging a particular issue locally.
