### ISSUE TITLE
Parse Server as of release 2.2.15 creates initial _User and _Index collections that prevent migration from facebook. 

### ISSUE THREAD

**Issue by jeacott1** [ParsePlatform/parse-server#2676]
Parse Server as of release 2.2.15 creates initial _User and _Index collections that prevent migration from facebook. 
in order for migrations to be available the mongoDb must be empty.

the code was first introduced here:
https://github.com/ParsePlatform/parse-server/blob/d599fdd4feccf93be56acd3fa5a3307aac187803/src/ParseServer.js#L200

and now lives here: 
https://github.com/ParsePlatform/parse-server/blob/master/src/Controllers/DatabaseController.js#L895

is this change really required?

**Comment by flovilmart** [comment]
If you're planning to do a migration, you should have an empty database, you're right, so you should shut down your parse-server or point it to another DB, run your migration and then point back to the right database. Does that help?

**Comment by jeacott1** [comment]
not really. we are trying to stand up a hosted service, and since 2.2.15 this makes things very difficult.

**Comment by flovilmart** [comment]
The parse-server should only connect to mongoDB AFTER the migration is completed. Is that really something you can't do?

**Comment by jeacott1** [comment]
our flow is: 
user signs up, gets redirected to dashboard. 
user creates app from dashboard. 
dashboard talks to app (at this point we're broken because mongo is populated).  
User finds mongo url in dashboard settings and migrates.

all very clean, within the dashboard, and very similar with the historical parse flow.

**Comment by flovilmart** [comment]
I believe you'll need to find another flow, work around that or provide a PR that will still ensure people that deploy to their own infrastructure the functionality that is currently in place.
