### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by ryancrawcour** [ParsePlatform/parse-server#268]
as this is now open source and people are contributing PRs, could we please have a test suite in the repo too so that we can test changes against a known / comprehensive suite of tests.

**Comment by drew-gross** [comment]
We have a test suite! Clone the repo and run `npm test`. The tests are run on every PR as well, and we have checks to make sure the code coverage doesn't decrease. Check out an example here: https://codecov.io/github/ParsePlatform/parse-server?ref=05fb117aac1c2833d43bd7b284442e63b8f52580

We would also be super excited to see PRs adding more tests to existing features!

**Comment by ryancrawcour** [comment]
Thanks!
