### ISSUE TITLE
Parse always includes "_rperm" in the Query

### ISSUE THREAD

**Issue by benishak** [ParsePlatform/parse-server#2682]
# Env

Parse Server 2.2.17
# Problem

I don't know if this is an issue or not but after I enable Profiling (level 1) on MongoDB to check slow queries, I saw that alomost all queries are including `_rperm` 

`'queryMask': '{"$query":{"_rperm":{"$in":[]},"approved":"<val>"}}',`

Although this class is public read, and the `_rperm` is being passed empty (by Parse Server? by SDK ?),
The same result can be obtained by

`'queryMask': '{"$query":{"approved":"<val>"}}',`

and in the SDK (here iOS) we don't pass any ACL argument to the query, and the queried class is public read

**\- why is this an issue?**
because this would make the obvious `{"approved": 1}` index like this completely useless and must create this index `{"approved": 1, "_rperm": 1}` instead

**Comment by flovilmart** [comment]
@benishak can you work on a PR for that?

**Comment by benishak** [comment]
@flovilmart yes I will. I will update the DatabaseController

**Comment by flovilmart** [comment]
@benishak did you make any progress on that?

**Comment by flovilmart** [comment]
@benishak ping?%

**Comment by flovilmart** [comment]
Although this class is public read  yeah but ACL's per object can say the opposite, as remember ACL override the CLP. There is no way to know ahead of time how to optimize that.
