### ISSUE TITLE
CloudCode POST Returns error " { code: 141, message: 500 }"

### ISSUE THREAD

**Issue by pjainusr** [ParsePlatform/parse-server#2687]
- Issue Description

I am using Parse hosting services now since parse.com is going to retire. Following cloudcode function when requested makes call to third party api for creating a record and returns json response with success or error

===== cloud code ======
Parse.Cloud.define("createCode", function(request, response) {

    var baseEVUrl = "https://external.baseline.url.com";

    var params = JSON.stringify({
      "createCodeRequest": {
            "User"         : "username",
            "Password"     : "password"
        }
      });

    Parse.Cloud.httpRequest({
      url: baseEVUrl+"/getCode",
      method: 'POST',
      header:{
          'Content-Type': 'application/json'
      },
      body:params,
      success: function (httpResponse) {
          response.success(httpResponse.text);
      },
      error: function (httpResponse) {
          response.error(httpResponse.status);
        }
    });
});

===== cloud code ends ======

I see error on cloud code request

========= Error =========
 [object Object] 
[31merror[39m: Error generating response. ParseError { code: 141, message: 500 } code=141, message=500 
Error: {"code":141,"message":500} functionName=createCode, code=141, message=500, , user=undefined 
Input: {} 
[31merror[39m: Failed running cloud function createCode for user undefined with:

========= Error Msg Ends =========

Same code runs fine under cloudcode on Parse.com but not on n chef hosted parse ( .18 version latest )

any thought, what could be going wrong?

**Comment by mutex007** [comment]
Hey can you try setting gzip: true on the request. Some misbehaving HTTP servers return gzipped compressed content although there is no accept-encoding header.

**Comment by pjainaernow** [comment]
Thanks @mutex007 for suggestion. Tried, but no luck.
Same code works on parse.com but not on open source parse hosted by node chef. 

If i remove stringify, it seems to think its successful but httpResponse.text shows the error.

**Comment by flovilmart** [comment]
Try to run it locally with VERBOSE=1 in order to identify the error.

**Comment by pjainusr** [comment]
@flovilmart i have got local setup of mongodb, parse server and dashboard but can't figure out how to get CLI binary and/or point parse cli to local server. looking in, if u have pointer, let me know.

**Comment by mutex007** [comment]
You can enable verbose logging on NodeChef from App actions  > Server settings > verbose logging

**Comment by pjainusr** [comment]
Got local setup working but same error. With verbose no additional info locally or on node chef server.

**Comment by flovilmart** [comment]
Is the content of the httpResponse.text a proper string?

**Comment by pjainusr** [comment]
Yes, json response is alright. Same code works on parse.com cloudcode and also under postman

**Comment by flovilmart** [comment]
but is it a string or a JSON object... Parse.Cloud.httpRequest on parse-server is not the same implementation as the one on parse.com

**Comment by pjainusr** [comment]
@flovilmart , its JSON object in response.

**Comment by pjainusr** [comment]
It turns out to be typo with "header" , it should have been headers ( s at the end )

**Comment by wellkeptbeauty** [comment]
Error: {"code":141,"message":"movie lookup failed"} functionName=All, code=141, message=movie lookup failed, , user=BnwdN3U0iI
2017-04-28T07:15:01.139041+00:00 app[web.1]: [31merror[39m: Error generating response. ParseError { code: 141, message: 'movie lookup failed' } code=141, message=movie lookup failed
2017-04-28T07:15:01.141656+00:00 app[web.1]: [object Object]

**Comment by flovilmart** [comment]
Seems to be an error with your code inside the function.

**Comment by wellkeptbeauty** [comment]
Parse.Cloud.define('people', function(request, status)  
{
    console.log('Parse.serverURL: ' + Parse.serverURL);

  var query=new Parse.Query("MyCollection");
  
 query.find().then(function (res) 
    {
     console.log("after query is "+res);
      
    for(var i=0;i<res.length;i++)
    {
    var id=res[i].get('PExpirationDate');
    console.log("inner query is "+res[i].get('PExpirationDate'));
   
    }

  status.success("final result " + res);
  
    }, function (error) {
      status.error(error);
        
    });
 });

this is my cloud code
