### ISSUE TITLE
Get user in cloud function

### ISSUE THREAD

**Issue by flessard** [ParsePlatform/parse-server#269]
How i can get the user made the request in cloud function ? 
i try request.user but is always null.

Is possible in parse-server to get this information ?

**Comment by drew-gross** [comment]
`request.user` in the correct way, if it is null that could indicate that there is no user logged in to your app. Could you check that you have a logged in user, and if you still have issues, respond with some detailed reproduction steps?

**Comment by flessard** [comment]
Yes i have user logged. 

I just call a cloud function from my web app using javascript SDK js1.6.14.

**Comment by gfosco** [comment]
Can you capture the request being made to the server?  One way is to run the server with an environment variable set, `VERBOSE=1`  In this case it sounds like the session token may not be present.

**Comment by flessard** [comment]
Voilà !

POST / folo / functions / getUserRole {
    host: '127.0.0.1:5000',
    connection: 'keep-alive',
    'content-length': '324',
    origin: 'http://folo.local',
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36',
    'content-type': 'text/plain',
    accept: '*/*',
    referer: 'http://folo.local/dashboard/',
    'accept-encoding': 'gzip, deflate',
    'accept-language': 'en,en-US;q=0.8,en-GB;q=0.6,fr;q=0.4'
} {
    "u": {
        "__type": "Pointer",
        "className": "_User",
        "objectId": "IDuau99xWH"
    }
}

**Comment by flessard** [comment]
I think the problem is in [getAuthForSessionToken](https://github.com/ParsePlatform/parse-server/blob/master/Auth.js#L45). 

This function try to find  { _session_token: 'FLA7Pe97OV3i4iJr6vUL6jG2H' } in _Session but if i look in mongodb, the _session_token value are r:c39672e4452befe818218c0f040c7edf.

BTW, if no session are found, is not supposed to return session expire error ? 
I got a Object not found error.

**Comment by flessard** [comment]
@gfosco  I found the problem. In _User collection a field _session_token is present and if you fetch the user data form server, this field override the sessionToken saved in your browser.

If you don't fetch the user, all request to server contain the right sessionToken and if you fetch the user data from the server, all next requests will contain the bad sessionToken come form the _session_token in user data fetched.

**Comment by flessard** [comment]
Any follow up for this bug ?

**Comment by Tibabal** [comment]
+1, parse-server is not really usable in most cases without request.user returning client's user

**Comment by flessard** [comment]
@gfosco. Bug still present in 2.0.8...

**Comment by flessard** [comment]
fix whit #373
