### ISSUE TITLE
[Error]: Facebook auth is invalid for this user. (Code: 101, Version: 1.12.0)

### ISSUE THREAD

**Issue by caltv** [ParsePlatform/parse-server#2690]
There is an issue with iOS 10 and PFFacebookUtils linkUserInBackground, I get the error below after the Facebook SDK passes the FBSDKAccessToken 

`[Error]: Facebook auth is invalid for this user. (Code: 101, Version: 1.12.0)`

**Comment by flovilmart** [comment]
If it's working on iOS 9 that's likely an issue with your configuration on your iPhone app. Can you provide the server logs when running with VERBOSE=1 and check if all the parameters are correctly set?

**Comment by flovilmart** [comment]
Did you see that comment here? https://github.com/ParsePlatform/parse-server/issues/2104#issuecomment-245652891

**Comment by flovilmart** [comment]
@caltv you should probably post that issue on the https://github.com/ParsePlatform/Parse-SDK-iOS-OSX
