### ISSUE TITLE
Cannot migrate to another mongo database after changing connection string

### ISSUE THREAD

**Issue by deeDude** [ParsePlatform/parse-server#2694]
A while ago I migrated my database to Nodechef hosted mongo database. But now I do not have an account on Nodechef anymore and I wanted to migrate my Parse app to another Parse service hosting service. The problem is that now I can't seem to migrate the database again to another mongo db. On my app's parse dashboard it says "Migration complete", and I dont see any option to migrate my database again to another database even if I change the connection string...

How can I do a second migration of my Parse app's database?

**Comment by flovilmart** [comment]
You should reach to nodechef to recover your data.
