### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by tamermorsy** [ParsePlatform/parse-server#2695]
We still need an answer regarding push notifications. We have not received an answer on how to users can send notifications to one another.

PLEASE HELP.

**Comment by bohemima** [comment]
Hi, please use stackoverflow.com for general questions about how to implement something and keep this place for actual bugs and/or feature requests.

**Comment by tamermorsy** [comment]
This is an actual feature request because the team from Parse said they are still not sure what to do. Many of my friends reached out to ask.

**Comment by bohemima** [comment]
Push notifications have been available in parse-server since 2.0.8 (2/11/2016). If you have trouble implementing them please see the wiki I linked above or ask a question at for example stackoverflow.com

**Comment by flovilmart** [comment]
Client push notifications is disabled, you should implement it through a cloud function.

**Comment by JustK2** [comment]
@flovilmart  -- Do you have a sample of how the Cloud functions that would mimic the native Parse functionality?? This is what we need to be open source. We have implemented the "broadcast" type of Push successfully but that does not meet our needs. We need to mimic the action available in Parse as follows: User X likes User Y's Object Z. We are happy to implement in Cloud but appreciate some sort of guide as NOT having to writing all this code is why we chose the Parse product initially. Please reopen bug.

**Comment by flovilmart** [comment]
Parse.com deprecated client sending push a while ago, the code should be pretty much the same as the original code, I won't reopen the issue as it's not a bug but an implementation detail.
We don't discuss implementations details here, it's better suited over stackoverflow.

**Comment by JustK2** [comment]
[Stack question here ](http://stackoverflow.com/questions/39552110/parse-migration-client-to-client-push-notifications)- I've never implemented this or seen the current cloud code associated with our legacy Parse app. If you could please provide a sample that would be great. 

Thanks.
