### ISSUE TITLE
MongoDB's ObjectID Auto generation and Parse's _id Collision

### ISSUE THREAD

**Issue by paligiannis** [ParsePlatform/parse-server#2697]
I have my parse server up and running. Everything works fine.

**BUT** when it comes to import data from PhalconPHP framework mLab generates a new ObjectID("somevalue") that it is not readable from Parse and not editable in parse GUI dashboard. (says that the object is missing but i can see id, i can't only modify it)

If someone has ideas I would appreciate it. Thank you!

**Comment by flovilmart** [comment]
That seems to be a problem with your framework. We don't support importing large batches of data. If you want to create new objects that are compatible with parse, you should use one of the ParseSDK or the REST API, but never create the objects yourself in the DB.

If you still want to create the object in the DB manually, you should set the _id property to a pseudo random 10 character string with uppercase, lowercase and numbers.
