### ISSUE TITLE
Cross Domain Issue

### ISSUE THREAD

**Issue by dvanwinkle** [ParsePlatform/parse-server#2702]
@flovilmart Seems like [this change](https://github.com/ParsePlatform/parse-server/commit/ac348f5c4fd6996a1d95723062013412dde3c00e#diff-fd794f727e5f1cd4aa9c54051208b6c9R276) is causing me some issues.

I am using code similar to [this](https://github.com/ParsePlatform/parse-server#parse-server--express). Is there something that needs added to this now in regards to Cross Origin?

The dashboard cannot even access the API, although, the parse.com dashboard can.

Thanks.

**Comment by dvanwinkle** [comment]
Exact code if it helps: https://github.com/krushtech/parse-server-docker/blob/master/src/server.js

**Comment by dvanwinkle** [comment]
@flovilmart @drew-gross Any ideas on this?

**Comment by flovilmart** [comment]
Can you try 2.2.21?

**Comment by dvanwinkle** [comment]
@flovilmart Of course, but, this is a production app with over 1,000 requests per second. Is that released code or is it still in testing?

**Comment by flovilmart** [comment]
It's released, so it's supposedly working. Like any other project, you should probably deploy on a staging environment before deploying at large to all of your users and report back if the issue is still there.

**Comment by dvanwinkle** [comment]
@flovilmart this is fixed in 21. Thanks!

**Comment by flovilmart** [comment]
:+1:
