### ISSUE TITLE
Adding password-less authentication (phone-number or email)

### ISSUE THREAD

**Issue by xcarpentier** [ParsePlatform/parse-server#2707]

**Comment by flovilmart** [comment]
You can probably use digits and the Oauth options to achieve the phone number based login.

**Comment by xcarpentier** [comment]
Ok, and after that I can link this to parse-server, I guess ?

**Comment by flovilmart** [comment]
Yes, use the account liking, I believe digits would work with the Twitter Oauth,  or a custom Oauth adapter of your craft.
