### ISSUE TITLE
Elasticsearch database adapter

### ISSUE THREAD

**Issue by xcarpentier** [ParsePlatform/parse-server#2708]

**Comment by flovilmart** [comment]
Elastic search is a search engine, not sure how it would interact with parse-server. Can you explain what you had in mind?

**Comment by xcarpentier** [comment]
Hello @flovilmart, thanks for your feedback.

Yes, ElasticSearch is a search engine but it's Document-oriented database too, like mongo-db.

And (for me) parse-server can querying into ES like into mongo-db, No ? (not full-text search, but key-value search as Document-oriented database)

But with ES with can do more : auto-sharding, full-text search, bind it to kibana (ELK: data mining, ...)

Regards,

**Comment by flovilmart** [comment]
Feel free to work on it, but this is unlikely something that we'll officially integrate with the Main codebase. We're focusing on finishing the Postgres adapter and it could be a source of inspiration for that one too.

**Comment by Code-Crash** [comment]
Hi @xcarpentier, Any update on the same? have you implemented the "Elastic Search Adapter" for the parse-server?

Thanks.

**Comment by xcarpentier** [comment]
@Code-Crash why are you interested on it?
I've not yet created a repo for that but I think I will this year.

**Comment by victorx98** [comment]
@jcguarinpenaranda 
Great! Do you have detailed readme on what it can do and how can we use it? Thanks
