### ISSUE TITLE
Security of data

### ISSUE THREAD

**Issue by antonfire** [ParsePlatform/parse-server#2712]
Describe your issue in as much detail as possible.

I would like to confirm I've not missed anything here and that I have understood the process properly and as such my data is secure.

My setup:

All class level permissions have read and write disabled for public in class level permissions.
No other class level permissions are granted.
No data is requested client side, all data is returned through cloud code functions.
I have not set ACLs or roles.

When looking at classes, individual objects ACLs are set to 'Public read + write' (does this matter as class level permissions are not granted?).

When I try to access the data in the API console in the dashboard (both class and individual objects) it returns 'Permission denied for action find on class activeAccounts' unless the Masterkey switch is turned on. (Seems good).

I only want data to be accessed from cloud code where I am using the master key.

It seems that my data is secure. Have I achieved this or am I missing something fundamental?

**Comment by flovilmart** [comment]
As you describe it, everything is ok for me. The class level permissions take precedence over acl's and the behavior seems to be what you expect and what's to be expected

**Comment by antonfire** [comment]
Thanks for putting my mind at rest, I appreciate it.
