### ISSUE TITLE
Access to _Roles is denied when not master

### ISSUE THREAD

**Issue by montymxb** [ParsePlatform/parse-server#273]
I see that enforceRoleSecurity in rest.js denies non-master access to the _Role collection by default. I agree that this is a valid security concern that justifies locking down, but the original Parse API did allow clients access to this without using the master key. 

I think this is something that could be considered to be allowed in the future, if anything just to adhere closely to the original spec. Perhaps a server configuration option that would collectively restrict or allow access to collections such as _Role? Something like this could restrict access by default as well. I'm curious what the community thinks of this and whether this is something we should address or not.

**Comment by gfosco** [comment]
This difference exists because in hosted Parse, the REST API key had additional permissions over the public client keys.  I do not think it is a good idea for anything but an administrator to edit the roles, and so in parse-server where client keys are irrelevant the master key is required.  Is there a use-case where it makes sense for clients to have any visibility or access to roles?  In those cases I would recommend using a cloud function to abstract and validate that functionality.

**Comment by montymxb** [comment]
I see. It is noteworthy to mention that this functionality was present when using the javascript API key, and I imagine it was probably present with others too. However having a cloud code abstraction does do the trick nicely in a secure manner. I just wanted to verify that the potential methods of access for Roles have been decisively changed from that of the original. Overall I am good with it!

**Comment by swapnilgt** [comment]
I have a use case where my system has `SchoolA` and `SchoolB` who can host their course content and there are students who can subscribe to these schools and then take their lessons. On completing a lesson, I save an entry to a class (say, `LessonClass`) in the parse-server. I want these entries to be read only by the respective school moderators and the student who made the entry. I was thinking of handling these using `roles`. I was thinking of creating `moderator-roles` for each school and then giving the respective school roles read + write permissions over each entry of `LessonClass` which corresponds to a lesson offered from their school + read access to the user (the student in this case). Is there a better way to do this?
