### ISSUE TITLE
request.user undefined in afterDelete hook

### ISSUE THREAD

**Issue by majidhassan** [ParsePlatform/parse-server#2741]
I have two classes: Parent and Child. On the beforeDelete hook for Parent I delete all Child instances related to that parent:

``` javascript
Parse.Cloud.beforeDelete("Parent", function(request, response) {
    Parse.Object.destroyAll(request.object.get("children"), { // children is a list of Child instances
        success: function() {
            response.success();
        },
        error: function(error) {
            response.error(error);
        },
        sessionToken: request.user.getSessionToken(),
        useMasterKey: request.master
    });
});
```

Then I have an afterDelete for the Child class. In that afterDelete I get an undefined `request.user`. I also tried using beforeDelete just in case the problem was with the afterDelete.

I'm using parse-server 2.2.18.

Any ideas what's wrong?

**Comment by sitemart** [comment]
Why not use promises?

**Comment by majidhassan** [comment]
@sitemart It's possible to rewrite it using promises, but the current implementation should be working.

**Comment by mmazzarolo** [comment]
Having a similiar issue: calling `Parse.Object.destroyAll(..., { sessionToken: mysessiontoken })` inside a CloudCode function doesn't propagate the the user to the `afterDelete` Trigger.

Parse-Server 2.2.18

**Comment by flovilmart** [comment]
Prioritized for next release
