### ISSUE TITLE
/parse/requestPasswordReset returns 500

### ISSUE THREAD

**Issue by bourquep** [ParsePlatform/parse-server#2744]
### Issue Description

On my production parse-server environment, when users use the _Forgot my password_ function, parse-server started to return 500 a few weeks ago.

At first, it was intermittent but now it seems like every request to `/parse/requestPasswordReset` fails with 500.

On my development environment, which is an exact replica of my prod environment, those calls complete successfully.

A month ago, this was working fine on both environments. I haven't updated my `parse-server` version, nor have I made significant code changes to the backend. Also, if it was a code change that introduced this, I would observe this 500 result in both dev and prod environments methink.

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1. Using either Parse iOS SDK v1.13.0 or Parse JS SDK v1.9.0, call the `Parse.User.requestPasswordReset()` function.
2. Observe that the `/parse/requestPasswordReset` endpoint returns 500

### Environment Setup

- **Server**
  - parse-server version : 2.2.16
  - Operating System:     4.4.14-24.50.amzn1.x86_64
  - Hardware:             EC2 m4.xlarge
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): AWS

- **Database**
  - MongoDB version: 3.0.9
  - Storage engine:  MMAPv1
  - Hardware:        mLab Standard M2 (3.7 GB RAM, 60 GB SSD storage)
  - Localhost or remote server? mLab

### Logs/Trace

```
Uncaught internal server error. [TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined] TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Object.Promise [as sendPasswordResetEmail] (/var/app/current/node_modules/parse-server-mandrill-adapter/index.js:96:43)
    at /var/app/current/node_modules/parse-server/lib/Controllers/UserController.js:181:26
    at run (/var/app/current/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:87:22)
    at /var/app/current/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/var/app/current/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
```

**Comment by flovilmart** [comment]
The error is in `parse-server-mandrill-adapter/index.js:96:43` so you should probably contact the repository manager for that.

**Comment by kitab15** [comment]
@bourquep We are having this same issue, using version parse-server@2.2.16 and parse-server-mandrill-adapter@1.2.1 . Did you find how to solve this issue?

**Comment by bourquep** [comment]
Yes, the problem was introduced by `parse-server-mandrill-adapter` v1.2. The "fix" was to pin this module to v1.1.1 in `package.json`.

**Comment by kitab15** [comment]
@bourquep Thank you for your quick response! Based on it we figure out that the v1.2.1 also fix the issue!

**Comment by flovilmart** [comment]
That doesn't fix the issue, contact the repository manager, and let him know their latest implementation is not working correctly!

**Comment by valdezm** [comment]
https://github.com/ParsePlatform/parse-server/blob/5d9dbea07b6fcc3c9a33eacb7c68d0021551d60c/src/Controllers/UserController.js#L175

I can help anyone and am thinking about hosting an app that will provide the form to reset passwords.. Email me at dev@valdezm.com for more information. 

Sucks that this wasn't specified anywhere

**Comment by riksof-abdulrauf** [comment]
Hi @valdezm , @flovilmart @bourquep 
We are using APIs of [api.parse.buddy.com](url) in our iOS app, we moved our database from parse to buddy.com
I getting same error in reset password call
![parsereset](https://cloud.githubusercontent.com/assets/5626513/23854333/d3fa7f68-0812-11e7-8bd9-94d03791b174.png)

How can we fix it ?

**Comment by flovilmart** [comment]
You should probably contact buddy.com
