### ISSUE TITLE
MailAdapter design

### ISSUE THREAD

**Issue by drew-gross** [ParsePlatform/parse-server#275]
Hey, we are super excited to see everybody jumping to help with email verification! Since so many people are working on this, I thought it would be a good idea to get everyone working on it together to discuss what the API should look like. We want to have the smallest API possible to reduce the burden on implementers of the interface, while still being enough to satisfy the needs of Parse.

We also want to open the door for implementers of the MailAdapter interface to bring some new innovations to the table, such as customizing the emails content based on fields on the Parse.User object.

I think the ideal interface for a MailAdapter to expose would be a small handful of functions: `sendEmailVerificationEmail(user, link)` to send the email on signup, and `sendPasswordResetEmail(user, link)` for password resets. We could also ask the MailAdapter provider to provide the 4 user facing page templates with some other functions such as `generateChooseNewPasswordPage(user)`, `generatePasswordChangedPage(user)`, `generateEmailVerifiedPage(user)` and `generateInvalidLinkPage(user)`.

To kick off the conversation about what else we might want from this interface, here some ideas to discuss:

A `sendPasswordResetSuccess(user)` function. A lot of services will email you when you change your password, as a defense against hacking. Maybe the Parse server should also do this.

Should the user facing pages generation be mandatory? We could provide defaults, or choose not to.

Should we think of a way to expose the MailAdapter in Cloud Code? That would increase the burden on the implementer of MailAdapter, as they would have to create a very general purpose interface, but it could also be very useful.

Parse.com implements user facing pages by asking you to provide a link to a template. Should we re-use that concept? It would aid in transitioning off of Parse.com.

Do we want to give the MailAdapter any other information to work with? Like a Parse.Installation object, maybe? We could even give the adapter the full power of the Parse JS SDK, so it can add some features like the ability to write to the user object, so it can, for example, save when the password was last reset. Of course, any MailAdapter can accept data in it's constructor that lets it do that anyway, but we could make it easier.

I'll leave the 3 PRs working on email verification open, and we can take the best ideas from those 3 PRs, plus what we can come up with here.

@taylorstine @jamiechapman @maysale01 @gfosco @nlutsenko @lucianmat @flovilmart

**Comment by flovilmart** [comment]
Top of my mind and architercturally speaking:

Mail requests should be stored in separated objects, leaving just emailVerified in _User.

We should pass the full Parse.User object to the methods, that would allow external implementation to have a better control, tracking of sends etc.. Installation seem irrelevant at that point as it is unlikely to be linked to a particular User.

**Comment by flovilmart** [comment]
The question about the templates begets a bigger question. What is the use case of parse-server? Standalone or as a module. Personally, I'd go the standalone approach, to replicate, and isolate the concerns. 

Going the standalone approach, implies that the templates should be provided by configuration. Do we want to go that way?

**Comment by drew-gross** [comment]
I agree with the standalone approach and having the templates provided by choosing a configuration (ie. by choosing a MailAdapter) having the configuration be done in JS at the time of MailAdapter instantiation could be very powerful, and let the power users do awesome things by using an advanced MailAdapter, while also letting the beginner developers get started with a simple MailAdapter that chooses most of the defaults automatically.

Storing mail requests in a separate object is a great idea, but enabling that by default would cause backwards compatibility issues due to existing apps potentially already having data in that place. Making it possible for an advanced MailAdapter that stores requests wherever the user wants sounds like a good idea though.

**Comment by maysale01** [comment]
I personally believe that email handling and template rendering are beyond the scope of the Parse Server project, as most of the value will come from composing it with other Express middleware as opposed to running a standalone server. We could effectively plug this whole issue by [adding some CloudCode mechanism](https://github.com/maysale01/parse-server/tree/add-triggers-for-mail-events) to hook into.

However, if the consensus is to include some default mailing ability, here is an approach that keeps things flexible https://gist.github.com/maysale01/5390485e676ee3745960. 

Sidebar, logic for a `shouldSendUserConfirmation` shouldn't be baked directly into `RestWrite.js` (or at least not in the `runDatabaseOperation` method), rather there should be a step in the handler flow where a model is validated against some configurable constraints. Possibly a system defined afterSave trigger for '_User' that checks configuration to see if email verification is required, a validator service, or model classes with static validate methods.

**Comment by flovilmart** [comment]
Also, for the whole modularization of the project, we should be able to pass a module name, from configuration or command line in order to load a 3rd party adapter when it makes sense.
In this scenario, we could decouple the main package from the adapters, providing base adapters, but letting anyone who wants a sendgrid adapter use that one without actually requiring any code besides the configuration.

**Comment by flovilmart** [comment]
The mail adapter should also provide a simple `send` method that would take standard parameters.

**Comment by drew-gross** [comment]
That seems reasonable, they would really need to implement that in order to make the other functions anyway.

**Comment by corbanb** [comment]
Are there any ideas on when this will be merged in for us to start working off of? Seems like its gone quite here for a little bit.

**Comment by flovilmart** [comment]
@corbanb there are multiple concerns about the mail sending architecture and actually adapter architecture in general: in #290.

**Comment by rendragon83** [comment]
Is this still being worked on or ready? I have been going through all the conversations about this and it looks like all of the other ones have been closed except this one.

**Comment by jamiechapman** [comment]
@rendragon83 not sure, not much discussion has happened for a couple of weeks regarding this side of things.  I guess we probably need to reach a decision soon so we can ensure that password resets etc are working for standalone API server(s).

**Comment by taylorstine** [comment]
Let's hop on the green button express with one of these two https://github.com/ParsePlatform/parse-server/pull/250 https://github.com/ParsePlatform/parse-server/pull/583

**Comment by corbanb** [comment]
+1

**Comment by maruthi-wal** [comment]
Hello Everyone..
If any one did the password reset functionality, Please provide me the steps??

I need to implement this feature with my local parse server. 

Thanks,
Maruthi.

**Comment by drew-gross** [comment]
Hey, @maruthi-wal, Parse Server 2.1.4 has experimental support for sending password reset emails. Because it's still experimental, it's not documented and could change in the next version. I wouldn't recommend using it in production just yet, but if you want to help us test the feature before marking it as non-experimental, you can set `verifyUserEmails: true` in your Parse Config, and add an email adapter such as our SimpleMailgunAdapter.

**Comment by dcdspace** [comment]
I use Sendgrid with custom email templates for transactional email via cloud code, so would I be able to send password reset/email verification emails using Sendgrid as oppose to Mailgun? It would be great if I could simply access the url to the reset page and pop that in my email HTML. Thanks!

**Comment by drew-gross** [comment]
That is coming and will be possible by the time password reset becomes non-experimental

**Comment by 432player** [comment]
### Verification and reset emails not working since migrating my Parse app's MongoDB
I've completed step 1 of my Parse migration by moving to my own MongoDB server. Everything is working fine except emails sent by Parse.com. Again, I've only migrated the DB so the cloud code (and Parse REST API) are still being hosted by Parse.com.

Clicking on any email verification or password reset email link ends with the "Invalid Link" error page. I've confirmed the token and username in the emails are correct.

My only thought is the Parse.com hosted email verification handler is not able to communicate with the external MongoDB server I migrated to (but the the Parse.com REST API is working fine so that doesn't make sense).

### A CLUE THOUGH:
I've noticed that the reset link sent to my email worked **fine before the migration**, and a minute after the migration it creates a new link with a new **_perishable_token** in the mongoDB and is the same in the new link sent in the email but is an **Invalid Link**. And the funny part is the link **before** the migration to mongoDB STILL WORKS. It's like the old **_perishable_token** before the migration is somehow cached in the Parse server and allows me to even reset the password as many times as I like (each time same old token before the migration) but the new tokens being generated are not being checked in the request_password_reset Rest API function I guess.

Any ideas? Is this happening to anyone else?

**Comment by flovilmart** [comment]
@432player how did you configure parse-server?

**Comment by 432player** [comment]
The Parse Server is still running on Parse.com. We havent migrated to our own Parse-Server. We've migrated only the DB to our mLab mongoDB

**Comment by flovilmart** [comment]
So that seems unrelated to this issue, as it's a migration problem and you're not running parse-server at all

**Comment by 432player** [comment]
True, but we tried asking this everywhere and no one seems to have anything to say about this. This problem is apparently happening in the request_password_reset and without migrating to our own Parse-Server there seems nothing we can do about it. But we still want to remain a while in Parse before migrating the whole service. So I believe this is a bug in the Parse Rest API and with a lot of hope that someone will recognise this issue to allow us to remain on Parse.com a while longer. The new _perishable_tokens are not being checked correctly when the mongoDB is self hosted.

**Comment by silvermana** [comment]
@flovilmart @432player +1.  I'm having the same issue.  I'm close to launching the app I've been working on, and wanted to only migrate the MongoDB for now (as was suggested by the timeline in Parse's migration guide).

If I remove all my custom email templates it works fine.  So I agree with @432player that this is a Parse.com API bug, or a bug in the email templates.

**Comment by mahabubakram** [comment]
Thanks @drew-gross and @flovilmart  for the support. As I am using the mandrill for email service. I am waiting for the custom email provider and also for the password reset. Hopefully next version will come with a nice wiki on it. As its quite crucial.

**Comment by corbanb** [comment]
@drew-gross where can I find info on the mail adapters? I'd like to start testing here with `verifyUserEmails: true` and the mail adapter if possible.

**Comment by drew-gross** [comment]
We don't have any documentation because the feature is still experimental. To test, you can import our SimpleMailgunAdapter, initialize it with fromAddress and mailgun info, and pass it in your server initialization in the emailAdapter parameter, as well as using the verifyUserEmails option

**Comment by 432player** [comment]
Hi @drew-gross , we would like to turn on the email verifications option on the Parse-Server.
We have a SimpleMailgunAdapter running and working well with the reset password.
I tried adding the verifyUserEmails: true to the ParseServer Init but it didn't do the trick.
var api = new ParseServer({
...
  verifyUserEmails: true,
  emailAdapter: simpleMailgunAdapter,
...
});

any ideas on why this is not working?
by the way we're running npm 2.1.6
Thanks

**Comment by drew-gross** [comment]
Thanks for testing experimental features! Can you be more specific about what isn't working? Do you receive an email with no link? Do you receive a link that doesn't set emailVerified to true? Does any email get sent at all? (check you mailgun logs)

**Comment by 432player** [comment]
Hey @drew-gross thanks for the rapid reply, we're experiencing no email being sent at all.
For the reset password we do get emails and they reset the password.
But on signup we do not receive an email at all for verification even when verifyUserEmails: true, is set to true.
Thanks

**Comment by drew-gross** [comment]
Can you try opening the SimpleMailGunAdapter file and adding a `console.log` statement inside the `sendEmail` function to see if it is getting called? Also, do you have any `beforeSave` or `afterSave` on the `_User`? If so, could you try removing them and seeing if that changes anything?

**Comment by 432player** [comment]
Very strange, I was just about to test what you said and suddenly it is now working.
I'm not really sure how to approach this now. 
Perhaps it needed a while to jump start. I've tested this twice now and all is working. 
I've added the verifyUserEmails: true about an hour ago.

**Comment by thamer898** [comment]
Hello @flovilmart @drew-gross 

Do you have any tutorial how to configure Reset user password using parse version 2.1.6 ?

Regards

**Comment by gowridev** [comment]
How to integrate SMTP server for email validation functionality in parse server?

**Comment by hshinde** [comment]
@432player Did you find an answer to your problem? I am facing the same issue.

**Comment by 432player** [comment]
Hi @hshinde it worked for but I'm not really sure how.
Just make sure your Parse server version is above 2.1.4 and add verifyUserEmails: true at the init of ther server

**Comment by andresgarza** [comment]
@hshinde / @432player The [README](https://github.com/ParsePlatform/parse-server/blob/master/README.md) was recently updated with basic instructions on how to setup the email adapter.

**Comment by ChrisGrant** [comment]
Is it possible to use the MailAdapter in CloudCode? I can't see an obvious place where it is exposed.

**Comment by hshinde** [comment]
@432player thanks.
My bad. I did not elaborate the issue. I am facing the original problem where we have migrated the database to MongoDB and still using Parse.com server.
It seems you had to migrate your Parse server to make the email verification work. I will try that approach too. But I was still wondering whether there is any solution to make it work with Parse.com servers.

**Comment by drew-gross** [comment]
@ChrisGrant It's currently not exposed by Parse Server but you can just `require` the sendgrid or mailgun package in your Cloud Code, initialize it according to it's docs, and then send email with it.

**Comment by ChrisGrant** [comment]
@drew-gross thanks. Are there any plans to do so? It'd be more convenient than having to initialize it twice in my opinion. I can open another issue if you think it's worth it?

**Comment by drew-gross** [comment]
I think it's an interesting idea, but there are some big open questions about how it would work. Mailgun, for example, requires that you provide a fromAddress to send any email. This is provided in the initialization of the adapter, which means that it can't be changed if you send email from Cloud Code - but I'm sure people would want to change it. If we start adding a top of options to the email adapter, though, it gets harder to implement, and also makes it harder to swap different email adapters in and out easily. Lots of tradeoffs to consider. Opening an issue to discuss might be a good idea, yes.

**Comment by jcguarinpenaranda** [comment]
Hello. So, is the email verification working by now?

**Comment by hshinde** [comment]
yes, we have tested it with Mandrill. It's working without any issue.

**Comment by flovilmart** [comment]
It should be working by now.

Follow the documentation in the wiki if you have any doubts.

**Comment by artonragsdale** [comment]
I'm no longer on that project so I'm not certain, but I believe it was
fixed.

**Comment by alarrosa14** [comment]
For those looking for custom templates for password reset and verification emails, go to [parse-server-mandrill-adapter](https://github.com/back4app/parse-server-mandrill-adapter/). You can now use Mandrill templates using that adapter.

**Comment by rowntreerob** [comment]
FWIW : native parse-server && std-parse-mailgun-adapter working fine in localhost / express testing..

mongo connected to DEV instance on mLab's cloud ( NOT localhost/mongo )

Details of node config ( using heroku's $HOME/proj/.env ) to inject local env...

```
env:
DATABASE_URI=mongodb://me:34@ds0.mlab.com:13931/beacontst
SERVER_URL=http://localhost:1337/parse
PUBLIC_SERVER_URL=http://localhost:1337/parse
```

```
index.js:
new ParseServer({
  databaseURI: databaseUri || 'mongodb:..',
  serverURL: process.env.SERVER_URL || 'https://mighty-id-65221.herokuapp.com/parse',
  verifyUserEmails: true,
  publicServerURL: process.env.PUBLIC_SERVER_URL || 'https://mighty-id-65221.herokuapp.com/parse',
  emailAdapter: {
  module: 'parse-server-simple-mailgun-adapter',
  options: {
    fromAddress: 'no-reply@yayatv.tv',
    domain: 'sandbox2babd8b07fca4fe81e.mailgun.org',
    apiKey: 'key-f16d78'
  }
```

**Comment by gowridev** [comment]
Can we send mail invites using cloud code which uses mail adapter? If possible,could you share sample cloud code?

**Comment by majidhassan** [comment]
@gowridev I'm not sure what exactly you meant with "send mail invites". But I send regular emails using the Mailgun adapter. Here's some sample code:

```javascript
var Mailgun = require("mailgun-js")({apiKey: mailgun_apikey, domain: mailgun_domain});

function mailgunSend(data, promise) {
    Mailgun.messages().send(data, function (error, body) {
        if (error) {
            promise.reject(error);
        }
        else {
            promise.resolve();
        }
    });
}

var promise = new Parse.Promise();

var data = {
    from: "Some Email <no-reply@somedomain.com>",
    to: "receiver@somedomain.com",
    subject: "Hello",
    html: "<html><body>Hello</body></html>"
};

mailgunSend(data, promise);
```

Env:
parse-server-mailgun@2.1.12
parse-server@2.2.25-beta.1

**Comment by valdezm** [comment]
So, my understanding is that the mail adapters work, but there aren't any specification on how to create the form for password resets and  MOST IMPORTANTLY, where that form should post back to, which endpoint?

REALLY?...

**Comment by flovilmart** [comment]
There is a default form for password resets, as long as you provide a mail adapter, this will work

**Comment by valdezm** [comment]
Awesome, yeah I see that now, Thanks @flovilmart I appreciate it! My mistake was that I didn't set the following correctly:
  publicServerURL: 'https://example.com/parse',

That really should be specified more accurately to be:
  publicServerURL: 'https://thestandaloneparseserverURL.com/parse',

I thought it was just what the companies website was, not the actual endpoint that has the form which exists on the ParseServer through that project....


Appreciate your help though, much appreciated!

**Comment by funkenstrahlen** [comment]
The parse server guide still says mail verification is not available.

> This is not supported out of the box. But, you can use a beforeSave to send out emails using a provider like Mailgun and add logic for verification. Subscribe to this issue to be notified if email verification support is added to Parse Server.
https://parseplatform.github.io/docs/parse-server/guide/

This should be updated.

**Comment by Neilpoulin** [comment]
Hi, I have a custom email adapter that uses Amazon's SES for sending emails, and it has been working great for months for password resets. I now want to implement email verification, but am having trouble getting the email to trigger. 

I saw one comment from @drew-gross about commenting out any beforeSave or afterSave triggers on the _User object, and tried it. That got the mail to trigger and work as expected. However, I'm hoping that I don't need to remove any before/afterSave hooks to get this feature working. Does anyone have any thoughts on how to get verification emails to send out when using other beforeSave triggers?

**Comment by flovilmart** [comment]
Can you open a specific issue so I can have a look?

**Comment by acinader** [comment]
@Neilpoulin any interest in open sourcing you're ses adapter?  that would be useful for the community.

**Comment by Neilpoulin** [comment]
@flovilmart, sure thing, i'll get a separate issue opened to track this specifically.

@acinader, I think that's a great idea. I'll start working on breaking it out into a standalone module. 

Thanks for the responses!

**Comment by flovilmart** [comment]
@Neilpoulin sorry for the late response. Did you open another issue or found what you were looking for?

**Comment by BenBenz** [comment]
Mail verification and password reset are available or not ?

**Comment by flovilmart** [comment]
Yes they should be, all endpoints are available, configured when your provide a mail adapter.

**Comment by BenBenz** [comment]
Because it tried to add this to my ParseServer configuration in index.js

    verifyUserEmails: true,
    publicServerURL: process.env.SERVER_URL || 'http://localhost:1337/parse',
    appName: 'Parse App',
    emailAdapter: {
        module: 'parse-server-simple-mailgun-adapter',
        options: {
            fromAddress: 'MYMAIL',
            domain: 'MYDOMAIN.mailgun.org',
            apiKey: 'APIKEY',
        }
    },

And when I reset a password I have this error  (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Forbidden

**Comment by BenBenz** [comment]
I need to add another module ? in package.json

**Comment by flovilmart** [comment]
Can you provide the logs when running with VERBOSE=1?

**Comment by albaqawi** [comment]
hi @flovilmart and @drew-gross I am following your works here and trying not to drown as I am very new to Swift3 and Heroku/Parse backend..... as many others I want to enable the reset password feature call within parse with (requestPasswordResetForEmailInBackground:block:) 

I have my Heroku hosted on node.js platform and not sure what I need to do, as I see many recommend to use mailgun....

the close to a complete answer is @FeleciaGente in post https://github.com/parse-community/parse-server/issues/1063

and I am waiting for @flovilmart response on it...

I really appreciate if you can guide me to a step by step tutorial or how to guide. 

thanks

**Comment by fadwafb** [comment]
Do anyone used the simple-parse-smtp-adapter? because it's not working for me, i didn't get any e-mail.

**Comment by flovilmart** [comment]
@fadwafb reach out to to maintainer of this adapter. We don’t maintain it.

**Comment by fadwafb** [comment]
Thank you so much @flovilmart for the answer, so can i use the SendGrid adapter? if not tell which adapters are working?

**Comment by flovilmart** [comment]
I think so, all adapters on the parse-server modules org should be properly functional.

**Comment by Abderezai** [comment]
something is wrong with the simple mail adapter. I tried using my mailgun credentials on an older project that was runing parse + mailgun and the mail was sent no problem. On this new project those credentials are not working.
    "express": "^4.13.4",
    "kerberos": "~0.0.x",
    "parse": "1.10.0",
    "parse-dashboard": "~1.1.0",
    "parse-server": "2.5.3"

error:
'An appName, publicServerURL, and emailAdapter are required for password reset and email verification functionality.' }

Parse options:
  **appName: 'Example App',
  serverURL: process.env.SERVER_URL,
  publicServerUrl: process.env.SERVER_URL,
  emailAdapter: {
    module: 'parse-server-simple-mailgun-adapter',
    options: {
      fromAddress: 'noreply@example.com',
      domain: 'mailgun.example.com',
      apiKey: 'key-####',
    }**

**Comment by flovilmart** [comment]
@Abderezai  publicServerUrl seems to have a typo

**Comment by Abderezai** [comment]
Thank you man. And damn dyslexia.
Is there an editor out there that would catch something like.

**Comment by Nes-si** [comment]
Do you have any plans to update docs? Isn't it time?
http://docs.parseplatform.org/parse-server/guide/#welcome-emails-and-email-verification

**Comment by flovilmart** [comment]
@nes-si feel free to open a PR.

**Comment by kishanio** [comment]
I wonder why is this issue such a big hassle and gets into mail adapters? 

Simplest way i can think right now,

1. Somehow i should be able to call a function and generate a verification link via. cloud code. 
2. I'll use the link to be sent across using any email adapter i like via. cloud code. 
3. Parse config parameters should have a user defined field i.e. `postEmailVerification`. This can be a link or cloud code function.
4. Upon verification click after setting verified to true the link uses `postEmailVerification` field to either call a cloud code function or redirect.

or more simpler than this,

1. Give me an option to override emailVerified via. cloud-code. 

Privacy should be the responsibility of humans when a platform can be used in so many ways it shouldn't itself identify with features advocating privacy.
