### ISSUE TITLE
[Please mark as closed] Unable to ensure uniqueness for usernames & Unable to ensure uniqueness for user email addresses

### ISSUE THREAD

**Issue by craffenoux** [ParsePlatform/parse-server#2751]
**FIXED -> I FORGOT TO SET ?replicaSet=**
_Please mark as closed!_

### Issue Description

I'm setting up a parse server in local on my MBP. I did set up the index.js as following: 

```
var api = new ParseServer({
  databaseURI: 'mongodb://*****:*****@*****.mongo.objectrocket.com:*****,*****.mongo.objectrocket.com:**********.mongo.objectrocket.com:*****/db_name?ssl=true?',
  cloud: __dirname + '/cloud/main.js',
  appId: '*****',
  masterKey: *****',
  serverURL: 'http://localhost:1337/parse' 
});

```
When I start the server running `npm start` i have the following warnings :
`Unable to ensure uniqueness for usernames` & `Unable to ensure uniqueness for user email addresses`
_The complete output is below._

_The DB is linked to Parse.com after a successful migration._

### Steps to reproduce

1. npm install worked well
2. set up everyting in index.js with a mongodb database hosted on ObjectRockect
3. npm start

#### Expected Results

I want to connect my local parser-server to my hosted mongdb database and be able to use the test page (for example) at localhost:1337/test.

#### Outcome
No connection is made and i have 2 warnings.

### Environment Setup

- **Server**
  - parse-server version : 2.2.21
  - Operating System:  OSX 10.11.6
  - Hardware:  MacBook Pro (Retina, 15-inch, Mid 2015)  
  - Localhost or remote server?: Local

- **Database**
  - MongoDB version: 3.0.11
  - Storage engine: mongodb_jumbo_replica_set
  - Hardware: NC
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): ObjectRocket

### Logs/Trace

Terminal output : http://pastebin.com/AsCN5Xye

**Comment by polo2244** [comment]
@craffenoux  may i know how did you solve this ?
I have the same problem using replica set from Atlas. The URI that i am using is: 

```
mongodb://USER:PASSWORD@
cluster.....-shard-00-00-d..j.mongodb.net:27017,
cluster.....-shard-00-01-d..j.mongodb.net:27017,
cluster.....-shard-00-02-d..j.mongodb.net:27017/DATABASENAME?
ssl=false&replicaSet=cluster.....-shard-0
&authSource=admin
```

I get this error:
```
parse-server-example running on port 8081.
[32minfo[39m: Parse LiveQuery Server starts running
[33mwarn[39m: Unable to ensure uniqueness for usernames:  MongoError: no valid replicaset members found
    at Timeout._onTimeout (/var/app/current/node_modules/mongodb-core/lib/topologies/replset.js:660:33)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
[33mwarn[39m: Unable to ensure uniqueness for user email addresses:  MongoError: no valid replicaset members found
    at Timeout._onTimeout (/var/app/current/node_modules/mongodb-core/lib/topologies/replset.js:660:33)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
(node:6760) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): MongoError: no valid replicaset members found
(node:6760) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): MongoError: no valid replicaset members found
```

**Comment by flovilmart** [comment]
Can you connect with that URL right with the nodejs mongodb driver?

**Comment by natanrolnik** [comment]
@polo2244 I'm using MongoDB Atlas also and the latest version of parse-server works fine (way older version didn't).
I had the exact same error before (`MongoError: no valid replicaset members found`) updating parse-server

**Comment by Code-Crash** [comment]
Hi Guys,

Wanted to inform you, as @flovilmart suggested, it's problem with ```mongodb``` driver version, so I did cloned parse-server@2.2.23 version and updated the ```mongodb``` driver from 2.2.10 to 2.2.12, and pushed to bitbucket repository and doing ```npm install``` from the same repository for parse-server and it's working fine.

If anyone still using parse server older version (or in middle of migration), I can share the bitbucket repository link to use the parse server, which is compatible with ```mongodb``` driver 2.2.12.
