### ISSUE TITLE
Error querying nested includes of null pointers

### ISSUE THREAD

**Issue by doender** [ParsePlatform/parse-server#2752]
Using parse-server 2.2.21, I found a problem when including nested fields of an array of null pointers. For example, if I have an object like `{'list': [null, null, null]}` and then query with include `list.field` I get:

```
error: Uncaught internal server error. [TypeError: Cannot read property 'field' of null] TypeError: Cannot read property 'field' of null
    at findPointers (/usr/lib/node_modules/parse-server/lib/RestQuery.js:810:25)

```

**Comment by flovilmart** [comment]
I'll have a look.
