### ISSUE TITLE
`request.user` on cloud code is `undefined` with iOS 10

### ISSUE THREAD

**Issue by mohdabdurraafay** [ParsePlatform/parse-server#2753]
We just updated our iOS codebase to iOS 10 as base SDK with Xcode 8 with Parse iOS SDK version '1.13.0' and Server version 2.2.17.

Is this issue with parse-server or iOS SDK needs an update with the iOS 10?

**Comment by idefen1** [comment]
Apple rejected my latest app, says not compatible with IPv6 wifi? Please help =*(

**Comment by joeyslack** [comment]
@idefen1 Just happened to me. Hosted on Heroku, and it might be an issue with them. Where are you hosted?

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

**Comment by mohdabdurraafay** [comment]
**Issue Description**

We just updated our iOS codebase to iOS 10 as base SDK with Xcode 8 with Parse iOS SDK version '1.14.2' and Server version 2.2.17. We observed that the cloud functions aren't having the `user` object in the `request` payload on the server which is being made by the iOS 10 compatible app. 

**Steps to reproduce**

- Update your Mac with the latest Xcode 8.
- Then update iOS app codebase to Swift 2.3.
- If your Parse SDK isn't 1.14.2, then please update that as well.
- Now run the app and see your cloud functions on the server has `user` object missing.

**Expected Results**

These cloud functions should have the original payload with the user objects invoke in them.

**Actual Outcome**

There's no `user` object in the request payload.

**Environment Setup**

_Server_

parse-server version (Be specific! Don't say 'latest'.) : v2.2.17
Operating System: Heroku (cedar)
Hardware: Heroku
Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroic
Database

MongoDB version:  3.0.12 (MMAPv1)
Storage engine: MMAPv1
Hardware: mLab
Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

**Logs/Trace**

You can turn on additional logging by configuring VERBOSE=1 in your environment.

**Comment by hramos** [comment]
Are there any logs? e.g. an example of what the cloud function logs when it is called by an iOS 9 device vs an iOS 10 device? In any case, it sounds like this may be a SDK issue and not a Parse Server issue. You may want to open the issue against the iOS SDK's repo if you can reproduce this issue.
