### ISSUE TITLE
I want to add config in the push.

### ISSUE THREAD

**Issue by parseserverpush** [ParsePlatform/parse-server#2758]
I want to add config in the push. like "GET". it is "limit" and "skip".

curl -X POST \
-H "X-Parse-Application-Id: xx" \
-H "X-Parse-Master-Key: yy" \
-H "Content-Type: application/json" \
 _**-G \
  --data-urlencode 'limit=10' \
  --data-urlencode 'skip=400' \**_
-d '{
  "where": {

    }, "data":{"data":{xxxx}}
}'\  http://localhost:1234/parse/push

Thanks All

**Comment by flovilmart** [comment]
You can set skip and limit when building the query for the push notification, it should work correctly.

**Comment by parseserverpush** [comment]
Can you get me an example ? Thanks.

**Comment by flovilmart** [comment]
```
curl -X POST \
-H "X-Parse-Application-Id: xx" \
-H "X-Parse-Master-Key: yy" \
-H "Content-Type: application/json" \
-G \
--data-urlencode 'limit=10' \
--data-urlencode 'skip=400' \
-d '{
"limit": 10,
"skip": 20,
"where": {

}, "data":{"data":{xxxx}}
}'\ http://localhost:1234/parse/push
```

That should work I believe

**Comment by parseserverpush** [comment]
It is incorrect . i have been tried .

curl -X POST \
-H "X-Parse-Application-Id: xx" \
-H "X-Parse-Master-Key: yy" \
-H "Content-Type: application/json" \
-d '{
"limit": 2,
"skip": 1,
  "where": {
  }, "data":{"data":{xxxx}}
}'\  http://localhost:1234/parse/push

and 

curl -X POST \
-H "X-Parse-Application-Id: xx" \
-H "X-Parse-Master-Key: yy" \
-H "Content-Type: application/json" \
-G \
--data-urlencode 'limit=2' \
--data-urlencode 'skip=1' \
-d '{
"limit": 2,
"skip": 1,
  "where": {
  }, "data":{"data":{xxxx}}
}'\  http://localhost:1234/parse/push

it is not limit and skip. :(. 

Thanks.

**Comment by flovilmart** [comment]
Hum ok, I'll reopen.

**Comment by parseserverpush** [comment]
@flovilmart  Can you help me please?. Thanks.

**Comment by flovilmart** [comment]
That would require a pull request.

**Comment by parseserverpush** [comment]
:(
