### ISSUE TITLE
mLab updating MongoDB to 3.2.X for all sandbox and shared cluster instances

### ISSUE THREAD

**Issue by JacobJT** [ParsePlatform/parse-server#2769]
### Issue Description

Describe your issue in as much detail as possible.

mLab has sent out the following notice that they are upgrading their shared clusters and sandbox DBs to MongoDB 3.2.x.  

> Hello from mLab,

> As a reminder, MongoDB 3.2 is now generally available on mLab, so we are in the process of making it the default release version for all new mLab deployments. We are also taking steps to discontinue our support for MongoDB 2.6. We first notified you about this on July 19.
> 
> **To this end, on Tuesday, September 27, we will start a four-day maintenance window to upgrade all free Sandbox databases running MongoDB 3.0 to MongoDB 3.2.** In addition, we will upgrade all for-pay Shared databases running MongoDB 2.6 to MongoDB 3.0 (reminders sent separately). Dedicated plan deployments will not be impacted.
> 
> Key details about this maintenance window
> 
> This four-day maintenance window starts Tuesday, September 27 at 10:00 am PDT / 5:00 pm UTC (convert to your timezone).
> Sandbox and Shared Single-node databases will be unavailable for approximately five minutes at some point during this four-day window. Highly-available Shared Cluster databases will experience no downtime from this maintenance, just failovers.
> You must ensure that your free Sandbox databases running 3.0 meet the upgrade requirements for 3.2.
> You must ensure that your for-pay Shared plan databases running 2.6 meet the upgrade requirements for 3.0 which includes a list of MongoDB 3.0-compatible drivers. If you do not upgrade your app to a 3.0-compatible driver before this upgrade, you may be unable to connect to your deployment.
> No other configuration changes will be necessary on your end.

The Parse-Server guide lists either MongoDB 2.6.x or 3.0.x as prerequisites.

If Parse-Server is not 3.2.x compatible, all apps (and test DBs) will need to be moved to single node plans which start at $180 / mo, and may be out of the question for many developers.

Either the parse-server guide is outdated, and should be updated to reflect that parse-server is compatible with MongoDB 3.2.x, or steps should be taken to make parse-server compatible with MongoDB 3.2.x

**Comment by flovilmart** [comment]
parse is compatible with 3.2.x for a while now, it's part of the test suite. I update the documentation.
