### ISSUE TITLE
Add a Wiki section/page describing new features in parse-server

### ISSUE THREAD

**Issue by codebreach** [ParsePlatform/parse-server#2770]
I don't have access to the wiki but feel this would be super useful. Below is my stab at it (which is probably be missing stuff). I can move it over to a blog or something if you dont want to put it in the wiki :)

# New Features in parse-server
These features are not available in Hosted Parse and never will be. We recommend you only use these after a full migration is complete and you start serving production traffic from parse-server.

## Hooks: beforeFind (Since 2.2.21)
This allows you to modify the Query to be run for each request by specifying a `beforeFind` hook:
```es6
Parse.Cloud.beforeFind('MyObject', (req) => {
  let q = req.query;
  let otherQuery = new Parse.Query('MyObject');
  otherQuery.equalTo('forced', true);
  return Parse.Query.or(q, otherQuery);
});
```

## Account Lockout Policy (Since 2.2.19)
To use, please specify following in the options to the `ParseServer` constructor call:
```js
// account lockout policy setting (OPTIONAL) - defaults to undefined
// if the account lockout policy is set and there are more than `threshold` number of failed login attempts then the `login` api call returns error code `Parse.Error.OBJECT_NOT_FOUND` with error message `Your account is locked due to multiple failed login attempts. Please try again after <duration> minute(s)`. After `duration` minutes of no login attempts, the application will allow the user to try login again.
accountLockout: {
  duration: 5, // duration policy setting determines the number of minutes that a locked-out account remains locked out before automatically becoming unlocked. Set it to a value greater than 0 and less than 100000.
  threshold: 3, // threshold policy setting determines the number of failed sign-in attempts that will cause a user account to be locked. Set it to an integer value greater than 0 and less than 1000. 
},
```

## Pointer Permissions (Since 2.2.8)
See ??

## Class Level Permissions: Require Authentication (Since 2.2.x)
See https://github.com/ParsePlatform/parse-server/wiki/NEW:-Class-Level-Permission:-requireAuthentication

## Live Query (Since 2.2.0)
See ??

**Comment by bohemima** [comment]
Excellent initiative!

**Comment by flovilmart** [comment]
We're in the process to reduce the content on the wiki, and expand the on in the docs repository. The two main benefits are

- better layout
- anyone can make a PR, which is not currently possible on GitHub wikis.

**Comment by acinader** [comment]
@flovilmart have you got an example repo that does docs in the way you're suggesting?  I could migrate some, but would like a blueprint :)

**Comment by flovilmart** [comment]
here: https://github.com/ParsePlatform/docs

**Comment by hramos** [comment]
The wiki is being moved to http://parseplatform.github.io/docs/parse-server/guide/, please open a PR against the docs repo.

Feel free to open an issue against me to remove the wiki and redirect to http://parseplatform.github.io/docs/parse-server/guide/, it's on my todo list.

**Comment by codebreach** [comment]
Thanks for all the pointers guys! I will move this over to the docs repo :)
