### ISSUE TITLE
I migrated app database but still have 30 request constraint

### ISSUE THREAD

**Issue by hisham2007** [ParsePlatform/parse-server#2773]
Dears,
 I use parse.com and I read that if I migrated database out of Parse, I will have more than 30 request per second. I didn't find this after migration . also background jobs are not working as good as before.

I started migration but the new service provider I migrated to is not as good as Parse so I need sometime to fully migrate.

Please advise.
Hisham

**Comment by flovilmart** [comment]
There is no limitation about the number of requests per seconds, but the performance will highly depend upon the infrastructure you're running, the server, the indexes on the database etc...

**Comment by hisham2007** [comment]
Forgive me this doesnt answer my question. I am not talking about open source parse server. I am talking about Parse.com.  I just migrated database only. I still have 30 request limit in parse.com

I searched for support on parse.com and they redirected me here so I raised my issue here

**Comment by flovilmart** [comment]
As long as you're running on api.parse.com you'll have that limitation.

**Comment by hisham2007** [comment]
no. Parse.com displayed an ad banner to encourage developers to migrate database and said your limit will increase to 600

**Comment by flovilmart** [comment]
I'm not sure parse.com has in mind but that's highly unlikely that migrating the DB will increate your throughput without replacing your servers as well. Also, the suggested deadline to migrate away from parse.com was upon July 28th. I suggest you move as fast as you can to parse-server
