### ISSUE TITLE
2nd migration of parse server failed to retrieve files from parse backend 

### ISSUE THREAD

**Issue by jagazee** [ParsePlatform/parse-server#2776]
**1st:** Migrated the parse server to aws using ElasticBeanStalk while  backend was mLab from the beginning of the project.Since no adapter was included, all the image files were stored on parse backend, while data in mLab.(e.g server_url: htt://parseserver-123 -env-xxx/parse)
**2nd:** For some reason the ec2 instance for parse server got terminated and we had to do one more round of migration.(e.g server_url: htt://parseserver-456 -env-xxx/parse)
We used the same appId,master_key and file_key.All the data, push notifications etc are being retrieved perfect except the image files located still on parse backend.

```
_NSLocalizedDescription = "Could not store file.";
    code = 130;
    error = "Could not store file.";
    temporary = 0;_
```

### Steps to reproduce

1. Migrate parse to aws using ebs and backend as mLab for data only.Image files to be on parse S3 
2. make sure you are able to access the image file.(At this working condition,unfortunately ec2 instance got terminated )
3. Migrate parse to aws using ebs and backend as mLab for data only.Image files to be on parse S3.

NOW files are not accessible but data is

#### Expected Results

Image files should be retrieved vis new server to client app, since file_key is set on server along with other keys.

#### Actual Outcome

```
_NSLocalizedDescription = "Could not store file.";
    code = 130;
    error = "Could not store file.";
    temporary = 0;_
```

### Environment Setup

- package.json for details:

```
{
  "name": "parse-server-example",
  "version": "1.4.0",
  "description": "An example Parse API server using the parse-server module",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/ParsePlatform/parse-server-example"
  },
  "license": "MIT",
  "dependencies": {
    "express": "~4.11.x",
    "kerberos": "~0.0.x",
    "parse": "~1.8.0",
    "parse-server": "~2.2.2"
  },
  "scripts": {
    "start": "node index.js"
  },
  "engines": {
    "node": ">=4.3"
  }
}
```

====================
index.js already has file_key set.
===================
  -remote server? (AWS, mLab)

This had turned CRITICAL to us and prod is at stand still.

**Comment by hramos** [comment]
For migration issues, it's best to open an issue with the [Parse team directly](https://parse.com/help). This issue tracker is specifically for tracking issues affecting the use of Parse Server.
