### ISSUE TITLE
How would Parse Push work on Doze mode

### ISSUE THREAD

**Issue by JongSeok-Kim** [ParsePlatform/parse-server#2778]
With Android M's Doze Mode, according to their doc, it will shut off network connectivity etc if left unused, how would the Parse push work? 
Is Parse Push setting itself as high priority GCM?
https://developer.android.com/preview/features/power-mgmt.html

**Comment by flovilmart** [comment]
I should be s'en the a s high priority. Also note that the push adapters are not on that repository and follow different development tracks. Feel free to open another issue on https://github.com/Parse-server-modules/parse-server-push-adapter
