### ISSUE TITLE
Error `installationId may not be changed in this operation` on `2.2.22` when update installation object

### ISSUE THREAD

**Issue by yingliangzhang** [ParsePlatform/parse-server#2780]
Describe your issue in as much detail as possible.

After updating to Parse-Server `2.2.22`, my previously working code on `2.2.21` that just to update the `user` pointer on an `installation` object is not working anymore. Got following error:
```
error: Error generating response. ParseError {
  code: 136,
  message: 'installationId may not be changed in this operation' } code=136, message=installationId may not be changed in this operation
error: Failed running cloud function addUserToInstallation for user FA9IMj9eDx with:
  Input: {"installationId":"4bb1e0ac-1224-4d99-ae7b-619778834e5f","userId":"FA9IMj9eDx"}

  Error: {"code":141,"message":{"code":136,"message":"installationId may not be changed in this operation"}} functionName=addUserToInstallation, code=141, code=136, message=installationId may not be changed in this operation, installationId=4bb1e0ac-1224-4d99-ae7b-619778834e5f, userId=FA9IMj9eDx, user=FA9IMj9eDx
```

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1. Query an installation object by `installationId`:
```
const installationQuery = new Parse.Query(Parse.Installation);
installationQuery.equalTo('installationId', installationId);
installationQuery.first({ useMasterKey: true }).then((installation) => {

}, response.error);
```
2. Update the user pointer on the object and call `save`:
```
installationQuery.first({ useMasterKey: true }).then((installation) => {
    installation.set('user', user);
    installation.save(null, { useMasterKey: true }).then(response.success, response.error);
}, response.error);
```

#### Expected Results

`installation` object updated with the user pointer successfully

#### Actual Outcome

```
error: Error generating response. ParseError {
  code: 141,
  message:
   ParseError {
     code: 136,
     message: 'installationId may not be changed in this operation' } } code=141, code=136, message=installationId may not be changed in this operation
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : [`2.2.22`]
  - Operating System:     [`ubuntu/trusty64`]
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [`vagrant 1.8.5`]

- **Database**
  - MongoDB version: [`MongoDB 3.2.8`]
  - Storage engine:  [`mmapv1 `]
  - Hardware:        [`1GB Disk`]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [`compose.io`]

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

[Not Necessary]

**Comment by flovilmart** [comment]
Thanks for reporting the issue, I'll do my best to provide a fix ASAP.

**Comment by cleever** [comment]
Same case here.

**Comment by nil8tor** [comment]
Ditto

**Comment by brianyyz** [comment]
+1

**Comment by cleever** [comment]
@flovilmart Thank your for the pr.

Do you have any ETA to 2.2.23?

In my use case, I use to save the User pointer in this object to send push notification. (same case of @yingliangzhang)
Now, none of my recent installations is receiving push because of this,

**Comment by flovilmart** [comment]
In the meantime you should downgrade to the latest stable version for you

**Comment by cleever** [comment]
@flovilmart I've already done. ;)
