### ISSUE TITLE
Push Functionality on Parse Dashboard Does Not Appear to be Working

### ISSUE THREAD

**Issue by universalqa** [ParsePlatform/parse-server#2787]
Our configurations have not changed for our Android dev app. However, somehow we are no longer  able to send push notifications to our devices from Parse's dashboard. 

### Steps to reproduce

1. First, I confirm that all the registration information is present in the Parse database table for my app install:

{
	"channels": ["Breaking", "XXXXXX", "XXXXXX"],
	"localeIdentifier": "en-US",
	"appVersion": "1.X.XX.0",
	"deviceType": "android",
	"appIdentifier": "com.XXXXXXXXXX.droid.XX",
	"installationId": "042292b8-e6c0-44af-86e3-XXXXXXXX",
	"parseVersion": "1.13.0",
	"appName": "XXXXXX",
	"timeZone": "America\/New_York"
}

2. I access the URL below:
https://dashboard.parse.com/apps/yourapp/push
3. Fill out the form on the page to send a push notification to all devices 
4. Once I confirm the reach of my message which appears as the following below, I then send off the push message.

"This notification will be sent to 3578 devices. It will be sent immediately. "

#### Expected Results

The push message is received on my Android device

#### Actual Outcome

None of my Android devices receive a push notification. Attached delivery report appears inaccurate since there did not appear to be any 'Successful Deliveries' on any of our Android devices.

### Environment Setup

- **Server**
NA
- **Database**
NA
### Logs/Trace
NA 

[FILL THIS OUT]
<img width="848" alt="deliveryreport" src="https://cloud.githubusercontent.com/assets/22453086/18847450/4da39d30-83f8-11e6-8f6f-8850ce619296.png">

**Comment by hramos** [comment]
Based on your Environment Setup, it seems like you're not using Parse Server. We're only tracking Parse Server issues in this repo. You can file bug reports for parse.com issues at parse.com/help.

I still highly recommend that you migrate to Parse Server or another solution as time is running out.
