### ISSUE TITLE
Help to understand parse-files-utils.

### ISSUE THREAD

**Issue by MattiaConfalonieri** [ParsePlatform/parse-server#2789]
Hi, i need to transfer my parse hosted file,  now there is a solution:
the utility parse-files-utils, but i really don't understand how to use it.

I really don't understand which filesAdapter i have to use? 
In my parse server i use mongo db and i save file inside it, i don't have a s3 or gcs account?

I don't understand what i have to do now! 
Need i to put the old file in a new s3 or gcs space instead put it together with the new file parse server uploaded?

Please help me to understand.

Thanks very much
Mattia

**Comment by flovilmart** [comment]
Please open on the relevant repository

**Comment by MattiaConfalonieri** [comment]
i have do that but the relevant repository seems abandoned.
