### ISSUE TITLE
Error setting Mongo URI

### ISSUE THREAD

**Issue by cspnanda** [ParsePlatform/parse-server#279]
I am trying to set mongoDBURI. When I do 

$ heroku config:set DATABASE_URI='mongodb://user:pass@server1.mongolab.com:53745,server2:53745/dbname?replicaSet=rs-xxx&ssl=true'

the app gets internal server error. Log shows

$ heroku logs

2016-02-06T05:12:28.806681+00:00 app[web.1]: Uncaught internal server error. [Error: Invalid mongoURI: mongodb://user:pass@server1.mongolab.com:53745,server2:53745/dbname?replicaSet=rs-xxx&ssl=true] 

But when I do

$ heroku config:set DATABASE_URI='mongodb://user:pass@server1.mongolab.com:53745/dbname'
everything works fine. Any thoughts ?

**Comment by drew-gross** [comment]
Thanks, we are aware of this issue and have some discussion in #148

**Comment by talkaboutdesign** [comment]
Same issue here.

**Comment by gfosco** [comment]
There has been some changes made to uri validation.  Please re-open if you're still having a problem.  Thanks.
