### ISSUE TITLE
Can I use compound unique index in parse? 

### ISSUE THREAD

**Issue by jimmyzzzzzzz** [ParsePlatform/parse-server#2790]
According to https://www.parse.com/questions/unique-fields--2 I thought unique key was not possible. Now I'm hosting Parse with Mongodb on my own server and I can easily create compound unique indexes in mongodb. Can I safely enable this feature in my production database?

**Comment by steven-supersolid** [comment]
The parse question/answer is from a while ago and refers to setting a unique index via code, which is still not possible.

You can of course set unique indexes at the database level which will cause an error when updating but that should be safely caught by parse-server and returned as a parse error.

I do this in production and parse-server enforces some unique indexes on _User so it seems safe enough, but my advice is to try this in dev first for your specific use case.
