### ISSUE TITLE
Parse Carthage updates error 

### ISSUE THREAD

**Issue by arikog** [ParsePlatform/parse-server#2793]
Describe your issue in as much detail as possible.

In efforts to migrate my server, I was trying to update my Parse framework to the latest version. I didn't use Carthage when I first built the app to get the Parse framework, however, for this update, I decided to use Carthage. Using the instructions given for using Carthage, I added the necessary code to my Cartfile and ran "carthage update" successfully. Before adding the new Parse framework into my app, I deleted the the old framework from the app and added the new one. When I tried running the app, I got a lot of errors. One such error was: "include of non-modular header inside framework module 'Parse.PFAnonymousUtils' for "#import <Bolts/BFTask.h>"

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1. Filled out the Cartfile with "github "ParsePlatform/Parse-SDK-iOS-OSX""
2. Ran "carthage update"
3. Deleted the original Parse framework 
4. Dragged the new Parse framework into "Link Binary With Libraries" 
5. Ran the app 

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 1.14.2
  - Operating System:   OS 10.11.6
  - Hardware:           
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [FILL THIS OUT]

- **Database**
  - MongoDB version: [FILL THIS OUT]
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [FILL THIS OUT]

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

<img width="882" alt="screen shot 2016-09-27 at 4 40 20 pm" src="https://cloud.githubusercontent.com/assets/16949026/18896056/661a49c8-84d3-11e6-87e6-f5207ce14c63.png">

**Comment by flovilmart** [comment]
Unrelated to parse-server. Please open on the iOS repository
