### ISSUE TITLE
How to contribute my parse-server-module?

### ISSUE THREAD

**Issue by zh-wowtv** [ParsePlatform/parse-server#2794]
I'd like to know how to contribute my own adapters such as mailer, push notification to parse-server community? What should I do?

For example, I have an mail adapter:

https://github.com/zhouhao27/parse-server-simple-nodemailer-adapter

How am I supposed to contribute it ? Thanks.

**Comment by flovilmart** [comment]
Thanks for creating those modules! We are striving to make the parse community stronger and your modules are doing just that!

Just release them on NPM, add the proper keywords and you'll be good to go! If you want to get them added to the wiki, please provide all package names as well as a short description of the modules!
