### ISSUE TITLE
Will parse-server work with the parse frontend js sdk?

### ISSUE THREAD

**Issue by Kinzi** [ParsePlatform/parse-server#28]
i.e. will the methods described here: https://parse.com/docs/js/guide#objects still work or do we need REST API calls?

**Comment by kingmatusevich** [comment]
The SDKs will work, as fair as they've said. You will simply have to point the SDK to your sever address. Look into this issue: https://github.com/ParsePlatform/parse-server/issues/13#issuecomment-176582460

**Comment by gfosco** [comment]
Yes and in fact it depends on the JavaScript SDK and uses some of its methods.  It exposes Parse as a global.

**Comment by Kinzi** [comment]
Great. Thanks!
