### ISSUE TITLE
How to get notification when parse server down.

### ISSUE THREAD

**Issue by w3care25** [ParsePlatform/parse-server#2805]
It There any way to send Email notification or any other notitfication to admin whever parse server is down?
@daaku @wasnotrice @subtleGradient @gdeglin @javache

**Comment by skinp** [comment]
@w3care25 what you want is called "Monitoring". There's literally 1000s of ways to monitor a web application and 100s of different services and products that can help you do that.

At Parse, we used a mix of pingdom.com and Nagios to email us when some parts of our system was down...

Although it could also be as simple as a cron job on another server that does a simple curl request and emails you if the curl fails or doesn't return what you expect. It all depends of what you budget, time commitment, HA requirements, knowledge/skill set, etc. are...
