### ISSUE TITLE
[Feature Request] iOS 10 Push Notification allow to attach image

### ISSUE THREAD

**Issue by benishak** [ParsePlatform/parse-server#2807]
now we can only modify the `alert` attribute
```
{
    "aps": { 
      "alert": { 
        "title": "Pusher's Native Push Notifications API", 
        "subtitle": "Bringing you iOS 10 support!", 
        "body": "Now add more content to your Push Notifications!"
        }, 
        "mutable-content": 1,
        "category": "pusher"
      },
    "data": {
      "attachment-url": "https://pusher.com/static_logos/320x320.png"
    }
}
```

will be nice to modify the `data` attribute to include image or video ...

check this out
https://blog.pusher.com/how-to-send-ios-10-notifications-using-the-push-notifications-api/

**Comment by FridaySG** [comment]
This would have to a feature added via the iOS SDK would it not? And even then, you could just accept the data and generate a rich notification locally within the application itself (without modifying the SDK). 

Correct me if I'm wrong, but if all it does is generate the rich notification by loading the media from the "attachment-url" key, then technically it's possible with the Parse-Server/Local SDK's as is.

**Comment by benishak** [comment]
how can I add the `data` attribute? because we send push from server using NodeJS SDK with `Parse.Push.send` which allow us to pass the `alert` object or anything under `aps`.

**Comment by benishak** [comment]
I actually had to open this in the SDK repo not here. sorry my mistake

**Comment by benishak** [comment]
i think no change is required at all, the client must handle by pulling the attached image or video, this can be done easily
