### ISSUE TITLE
Unable to access parseFile in android.

### ISSUE THREAD

**Issue by johncarter778888** [ParsePlatform/parse-server#2808]
### Issue Description

[ I am using local parse server and mongodb database]
### Steps to reproduce
1. [access image file from android device]
#### Expected Results

[I want access Image File Stored in mongodb database]
#### Actual Outcome

[Image file in android device]
### Environment Setup
- **Server**
  - parse-server version (2.2]
  - Operating System:     [cent OS]
  - Hardware:             [Dont know]
  - Localhost or remote server? (remote server]
- **Database**
  - MongoDB version: [3.0]
  - Storage engine:  [-]
  - Hardware:        [-]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [remote server]
### Logs/Trace

10-01 08:01:05.515 9441-9441/com.pgdior.unipune W/System.err: com.parse.ParseException: Download from S3 failed. Not Found
10-01 08:01:05.540 9441-9441/com.pgdior.unipune W/System.err:     at com.parse.ParseAWSRequest.onResponseAsync(ParseAWSRequest.java:43)
10-01 08:01:05.540 9441-9441/com.pgdior.unipune W/System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:137)
10-01 08:01:05.540 9441-9441/com.pgdior.unipune W/System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:133)
10-01 08:01:05.540 9441-9441/com.pgdior.unipune W/System.err:     at bolts.Task$15.run(Task.java:917)
10-01 08:01:05.540 9441-9441/com.pgdior.unipune W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
10-01 08:01:05.540 9441-9441/com.pgdior.unipune W/System.err:     at bolts.Task.completeAfterTask(Task.java:908)
10-01 08:01:05.540 9441-9441/com.pgdior.unipune W/System.err:     at bolts.Task.continueWithTask(Task.java:715)
10-01 08:01:05.540 9441-9441/com.pgdior.unipune W/System.err:     at bolts.Task.continueWithTask(Task.java:726)
10-01 08:01:05.540 9441-9441/com.pgdior.unipune W/System.err:     at bolts.Task$13.then(Task.java:818)
10-01 08:01:05.540 9441-9441/com.pgdior.unipune W/System.err:     at bolts.Task$13.then(Task.java:806)
10-01 08:01:05.540 9441-9441/com.pgdior.unipune W/System.err:     at bolts.Task$15.run(Task.java:917)
10-01 08:01:05.540 9441-9441/com.pgdior.unipune W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
10-01 08:01:05.540 9441-9441/com.pgdior.unipune W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
10-01 08:01:05.540 9441-9441/com.pgdior.unipune W/System.err:     at java.lang.Thread.run(Thread.java:856)

**Comment by johncarter778888** [comment]
images accessible from api.parse.com but it give error from local parse server.

**Comment by kwstasna** [comment]
On silly question... in  your index.js file have you setted up the parameter `fileKey` ?

**Comment by johncarter778888** [comment]
yes....i alredy set fileKey  in index.js........................................but i dont know how to use fileKey in android

**Comment by johncarter778888** [comment]
com.parse.ParseException: Download from S3 failed. Not Found

i am not using amazon  cloude ....still this is showing me s3 failed error

and i used filekey in index.js

**Comment by kwstasna** [comment]
There is no connection to your android app with the fileKey.
Could you please paste here your index.js WITHOUT your master key etc so we can see what you have done?

Also one thing. When you change something to your index.js i think you have to stop the npm and start it again :)

**Comment by johncarter778888** [comment]
this is index.js file ...errased ip address port number .,,....and keys


var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var path = require('path');

var databaseUri = process.env.DATABASE_URI || 'mongodb://(ipaddress):(port)/PuneUniversity';

if (!databaseUri) {
  console.log('DATABASE_URI not specified, falling back to localhost.');
}

var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://(ipaddress):(port)/PuneUniversity',
  cloud: './cloud/main.js',
  appId:  'appid here',
  masterKey: 'master key', //Add your master key here. Keep it secret!
  fileKey: 'file key',
  clientKey: 'client key',
  serverURL: 'http://(ipaddress):(port)/parse',  // Don't forget to change to https if needed

**Comment by johncarter778888** [comment]
tnx....problem solved.
