### ISSUE TITLE
deviceToken Null.

### ISSUE THREAD

**Issue by parseserverpush** [ParsePlatform/parse-server#2818]
I have build project with xcode 8 and device ios 10. In database it dont info device . example "deviceToken " , ""

<img width="240" alt="screen shot 2016-10-04 at 10 07 16" src="https://cloud.githubusercontent.com/assets/19681442/19061388/881adf46-8a1a-11e6-9c6e-d3224a9a92a6.png">

**Comment by flovilmart** [comment]
did you register for push notifications correctly on the client? Can you share the client code as well as the logs when the _Installation object is getting saved?

**Comment by parseserverpush** [comment]
Yes. It it bug when build xcode 8. xcode 7 ok.
