### ISSUE TITLE
Deploying changes to index.js

### ISSUE THREAD

**Issue by LarryCollett** [ParsePlatform/parse-server#2819]
Hey guys,

When I make a change to index.js (or any other file for that matter) how to I restart the index.js on AWS to update the code. Right now I'm making changes to main.js for cloud code, but I'm still receiving the error - Domain=Parse Code=141 "Invalid function." UserInfo={code=141, temporary=0, error=Invalid function., NSLocalizedDescription=Invalid function.}. Thanks in advance.

**Comment by acinader** [comment]
You'll need to restart node. The specifics of how you do that depends on your deployment.
