### ISSUE TITLE
RethinkDB Adapter

### ISSUE THREAD

**Issue by francocorreasosa** [ParsePlatform/parse-server#282]
How many people is interested in a RethinkDB (rethinkdb.com) adapter for Parse?

**Comment by deontologician** [comment]
I am :)

I took a look at making an adapter, but it looks like the validation code is heavily dependent on Mongo, and goes around the adapter interface. That would need to be cleanly separated a bit more before it would be easy to write an adapter

**Comment by drew-gross** [comment]
Making it easier to use different databases is on our roadmap, and will probably be my top priority after finishing the open source dashboard.

**Comment by gfosco** [comment]
Work is being done on a proper database adapter interface, and once that's out there, it'll be easier to discuss and build out adapters for other systems..  Going to close this for now.  Thanks.
