### ISSUE TITLE
change language to email verification, password recovery (both: email and web)

### ISSUE THREAD

**Issue by otmezger** [ParsePlatform/parse-server#2820]
Hi, we are using parse-server with heroku. Is there a possibility to **change the language** of:

- email-verification email template
- password reset email template 
- web templates for email verification and password reset. 

Is there any kind of templates for this outside parse-server core? 

thanks. 

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.22
  - Operating System:    heroku
  - Hardware:           unknown
  - Localhost or remote server? heroku

- **Database**
  - MongoDB version: mLab 3.2.7
  - Storage engine:  unknown 
  - Hardware:        unknown 
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

**Comment by hramos** [comment]
The templates are in parse-server itself, you can edit them in your own version of the server. AFAICT there hasn't been any work to remove these from core. Closing as this is more of a question rather than an issue.
