### ISSUE TITLE
Frequently timeout Error ⁠⁠⁠⁠{"code":124,"message":"Request timed out"}﻿⁠⁠⁠⁠

### ISSUE THREAD

**Issue by navjotjova** [ParsePlatform/parse-server#2825]
On every parse server request I got "⁠⁠⁠⁠{"code":124,"message":"Request timed out"}﻿⁠⁠⁠⁠".
(without migration)

Is this issue arise with anyone else.
blocker issue.
Please help if anyone knows the solution.

**Comment by flovilmart** [comment]
What do you mean without migration?

**Comment by navjotjova** [comment]
I have not migrated yet. I am still using parseapp.com. Since 5 to 6 hours we are facing this issue on 3/5 request.

**Comment by neowill2013** [comment]
I'm also getting the same issue since morning.

**Comment by navjotjova** [comment]
@flovilmart  
Is this issue from parse side?

**Comment by flovilmart** [comment]
Yeah it's likely to be. If you haven't migrated this repository is not where you should report issues. Also, note that you should probably run your migration to parse-server ASAP.
