### ISSUE TITLE
Problem to import data from parse.com to parse.server hosted in Openshift

### ISSUE THREAD

**Issue by zh-wowtv** [ParsePlatform/parse-server#2826]
I setup my parse server and mongodb in openshift which is working fine. I'd like to import old data from my parse.com application.

What I did:

1. Export data from my parse.com application. For example, here is the json file (Product.json) I exported:

{ "results": [
	{
        "createdAt": "2014-10-31T04:15:07.880Z",
        "difficulty": 2,
        "downloaded": 187,
        "file": {
            "__type": "File",
            "name": "01.zip",
            "url": "http://parse.com/1343.zip"
        },
        "free": true,
        "language": "en",
        "objectId": "04KFsk8IZu",
        "updatedAt": "2016-10-01T21:13:20.783Z",
        "version": 1
    },
	{
        "createdAt": "2014-10-31T03:40:23.835Z",
        "difficulty": 2,
        "downloaded": 11,
        "file": {
            "__type": "File",
            "name": "002.zip",
            "url": "http://files.parsetfss.com/002.zip"
        },
        "free": false,
        "language": "en",
        "objectId": "V5HqIK06Hu",
        "updatedAt": "2016-02-10T21:22:10.373Z",
        "version": 1
    }
] }

2. Run `rhc port-forward -a {myapp}` to get the port number, for example, mine is 60125
3. Run mongoimport command in my local machine

> mongoimport --host 127.0.0.1 --port 60125 --collection Product --db parse-server --file Product.json 

### Result:

```
2016-10-05T14:33:47.992+0800	connected to: 127.0.0.1:60691
2016-10-05T14:33:48.687+0800	imported 1 document
```

#### Expected Results

There should be two documents imported.

#### Actual Outcome

Only one document imported. 

```
{
    "_id" : ObjectId("57f4aa5f7ad4637e936f0191"),
    "results" : [ 
        {
            "createdAt" : "2014-10-31T04:15:07.880Z",
            "difficulty" : 2,
            "downloaded" : 187,
            "file" : {
                "__type" : "File",
                "name" : "001.zip",
                "url" : "http://files.parsetfss.com/001.zip"
            },
            "free" : true,
            "language" : "en",
            "objectId" : "04KFsk8IZu",
            "updatedAt" : "2016-10-01T21:13:20.783Z",
            "version" : 1
        }, 
        {
            "createdAt" : "2014-11-04T03:49:31.342Z",
            "difficulty" : 4,
            "downloaded" : 248,
            "file" : {
                "__type" : "File",
                "name" : "002.zip",
                "url" : "http://files.parsetfss.com/002.zip"
            },
            "free" : true,
            "language" : "en",
            "objectId" : "1JEpDepSX7",
            "updatedAt" : "2016-10-01T21:13:15.585Z",
            "version" : 1
        }
    ]
}

```

That means the format of json is not correct for **mongoimport**. I have two questions:

1. What is the correct format of json?
2. Will the import function implemented in Parse-Dashboard?

Thanks

**Comment by hramos** [comment]
I highly recommend using the Parse database migration tool. Closing as we're using the tracker for parse-server issues.

**Comment by zh-wowtv** [comment]
@hramos I used the Parse database migration tool. But it doesn't work for me. Please refer to https://github.com/ParsePlatform/parse-dashboard/issues/550#issuecomment-252679393. Thanks.
