### ISSUE TITLE
Parse server does not escape spaces in PFFile URL

### ISSUE THREAD

**Issue by zingano** [ParsePlatform/parse-server#2828]
### Issue Description

PFFile URL has non-escaped spaces, and then cannot be downloaded.
### Steps to reproduce

Use this code on a Mac OS X app running against the latest open source SDK to create a PFFile and examine its URL once created:

```
NSString* adminAppFilename = @"My Test File With Spaces";
    PFFile* adminImageFile = [PFFile fileWithName:adminAppFilename data:fileContents];
    [adminImageFile saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
        if (error) {
            consoleText = [NSString stringWithFormat:@"ERROR - create file with error - %@",error];
            [self.testConsoleView setString:consoleText];
        }
        else {
            NSLog(@"Uploaded test file - url is %@",adminImageFile.url);
        }
    }];
```

Running against parse.com the PFFile.url is 
https://files.parsetfss.com/<snip>-My%20Test%20File%20With%20Spaces

Running against Parse Server the PFFile.ur is
https://snip.s3.amazonaws.com/<snip>_My Test File With Spaces.bin
#### Expected Results

Parse Server URL should be escaped
#### Actual Outcome

Parse Server URL is not escaped
### Environment Setup
- **Server**
  - parse-server version 2.2.21
  - Operating System:  
  - Hardware:            Heroku 2x dyno
  - Localhost or remote server? Heroku
- **Database**
  - MongoDB version: 3.0.12
  - Storage engine:  MMAPv1
  - Hardware:       Dedicated cluster
  - Localhost or remote server? mLab

**Comment by dstarke** [comment]
I think this may actually be a bug in the file adapter. It isn't clear to me why, but several FileAdapter implementations fail to escape file names when generating URLs for direct access, even though they do it correctly when direct access is turned off. I filed a bug and a PR against parse-server-azure-storage for a similar issue, and it sounds like there needs to be a similar change to parse-server-s3-adapter.

You may be able to work around this by turning off direct access in your file adapter configuration.

**Comment by davimacedo** [comment]
I've just checked this issue and it is related to each FileAdapter implementation.

GridStoreAdapter does not seem to have this problem.

I've just sent a PR to solve it for S3Adapter:
https://github.com/parse-server-modules/parse-server-s3-adapter/pull/30

@flovilmart since it is not an issue of current repository, you should close it. It should be open in each FileAdapter respository.

**Comment by flovilmart** [comment]
Thanks!
