### ISSUE TITLE
Parse Server app structure

### ISSUE THREAD

**Issue by AmbroiseCollon** [ParsePlatform/parse-server#2831]
My app is getting pretty big on the server side. All the main logic is on cloud code basically, organised by classes. I find it now a bit messy and I'm looking for a better app structure.

I have a very clean MVC on the iOS side with all my models subclassing PFObject. And I wish I had something similar to organise my app on the server side.

I hope this makes sense and I would love to share file structures with anyone interested in this topic.

**Comment by flovilmart** [comment]
Not sure how we can help here. That's a general question about building nodejs/express apps. It all depends on your coding style, philosophy, etc... Maybe better suited on stackoverflow.

If you look at the code we have in the repo, we sliced Routers and Controllers, have a few pure prototypical objects like RestQuery and RestWrite, use a mix of factories and Classes etc...
