### ISSUE TITLE
Pointing to custom choose_password.html file results in {"error":"unauthorized"}

### ISSUE THREAD

**Issue by MobileVet** [ParsePlatform/parse-server#2842]
### Issue Description

On clicking on the 'reset password' link that is emailed, the user is forwarded on to a path in the Parse server that doesn't appear to have permissions set properly.

### Steps to reproduce

1. Setup *customPages* option on server setup (see below)
2. Request a password reset
3. Click on the link in the email:
`https://ourserver.com/apps/reimbursed/request_password_reset?token=OU8125150deadbeef&username=jim%40apple.com`
4. Notice that the browser is forwarded to the following address:
`https://ourserver.com/public/choose_password.html?token= OU8125150deadbeef&id=appID&username=jim%40apple.com&app=AppName`
5. Browser displays error:
`{"error":"unauthorized"}`

#### Expected Results

User should see the appropriate custom password reset html file.

### Environment Setup

Server options:
```
      emailAdapter : {
        module : 'parse-server-simple-mailgun-adapter',
        options : {
          apiKey: config.MAILGUN_API_KEY,
          domain: config.MAILGUN_DOMAIN,
          fromAddress: 'no-reply@ourserver.com'}
      },
      customPages: {
        invalidLink: config.PARSE_PUBLIC_SERVER_URL + 'public/invalid_link.html',
        verifyEmailSuccess: config.PARSE_PUBLIC_SERVER_URL + 'public/verify_email_success.html',
        choosePassword: config.PARSE_PUBLIC_SERVER_URL + 'public/choose_password.html',
        passwordResetSuccess: config.PARSE_PUBLIC_SERVER_URL + 'public/password_reset_sucess.html'
      }
```

- **Server**
  - parse-server version: 2.2.15
  - Operating System:     Ubuntu / Node.js / Express
  - Hardware:             Bare metal
  - Localhost or remote server? remote server

**Comment by natanrolnik** [comment]
@mobilevet if you put any other file in the `/public` directory, can it be accessed? If not, maybe you need to allow express to use the folder like [`express.use(...)`](https://expressjs.com/en/starter/static-files.html)

**Comment by MobileVet** [comment]
@natanrolnik Think you are right.  I was able to get the files to render locally if I directly navigate to them by adding
```
app.get('/public/*', function(req, res) {
	res.sendFile(req.url, {root: __dirname});
});
```
Unfortunately that doesn't work for URL encoded parameters that are passed along to the `choose_password.html` doc. 

I am very new to express, so any tips you could provide on pulling out the parameters and passing them to the rendered page would be greatly appreciated.

**Comment by flovilmart** [comment]
@MobileVet you can probably access the query parameters with `req.query`, then through a tempting library inject them into your pages.

**Comment by MobileVet** [comment]
@flovilmart Thanks for taking a look at this ticket.  Is it expected that we have to pull out the parameters manually?  How does this work on the included documents within Parse?

**Comment by flovilmart** [comment]
This is how we do it here: https://github.com/ParsePlatform/parse-server/blob/ad707457be13f177e4a0dc481c990ddbd2df8d80/src/Routers/PublicAPIRouter.js

**Comment by MobileVet** [comment]
Thanks @flovilmart

**Comment by flovilmart** [comment]
Specifically, for the choose password page, look into the views folder, we inject the query parameters into the page via client side JavaScript
