### ISSUE TITLE
[wiki] initialize example needs small update

### ISSUE THREAD

**Issue by drewrothstein** [ParsePlatform/parse-server#2849]
### Issue Description

On: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide

Under: "Using Parse SDKs with Parse Server"

Swift code needs to change from:
```
Parse.initializeWithConfiguration(configuration)
```

to:
```
Parse.initialize(with: configuration)
```

**Comment by flovilmart** [comment]
Thanks for the tip! Just updated it!
