### ISSUE TITLE
Parse.Relation fetching related object data

### ISSUE THREAD

**Issue by rohit-romley** [ParsePlatform/parse-server#2850]
http://stackoverflow.com/questions/39955488/parse-relation-fetching-related-object-data

I have a Class called commonWall and it is related to User class.

I have a column of type 'relation' to User in class commonWall named clubbedUsers.

I want to get the list of related users. What would be the appropriated code for that?

Below is my code.. but it is not working... it returns

{"_type":"Relation","className":"User"}
no object id for the relationship is returned..

```
var CommonWall = Parse.Object.extend("CommonWall");

    var q = new Parse.Query("CommonWall");
        q.include("clubbedUsers");
        q.limit(10);
        q.equalTo("heading","- 30%");
        q.find()
        .then((responseData) => {
            let listviewDataArray = JSON.parse(JSON.stringify(responseData));
            // console.warn(JSON.stringify(responseData));
            // console.warn(JSON.stringify(Parse.User.current().id));

            for (var i = listviewDataArray.length - 1; i >= 0; i--) {
              console.warn(JSON.stringify(responseData[i].relation("clubbedUsers")));
              responseData[i].relation("clubbedUsers").query().each()
              //if(userRelation !== "undefined")
              // userRelation.find()
              .then((responseData1) => {
                console.warn(JSON.stringify(responseData1));
              });
            }
          resolve(listviewDataArray);
          })
        .catch(function(error) {
            console.warn(error)
            reject({status: 'could not refresh wall!'});
          });
```

**Comment by flovilmart** [comment]
Check the documentation about relations here:

http://parseplatform.github.io/docs/js/guide/#using-parse-relations

and about the [each method](https://parseplatform.github.io/Parse-SDK-JS/api/classes/Parse.Query.html#methods_each)
That would somewhat look like:
```
let query = new Parse.Query('CommonWall');
query.find().then(function(results) {
   var result = results[0];
   result.relation('clubbedUsers').query().each(function(relatedObject) {
      console.log(relatedObject);
   });
});
```

**Comment by haroonKhan-10p** [comment]
@flovilmart can you please tell what is I am missing here:
const user = await Parse.User.logIn(req.params.email, req.params.password);
const userRoleQuery = user.relation(Parse.Role).query();
const role = userRoleQuery.find()  // role is undefined

my relations and collections   look like: 
![relations](https://user-images.githubusercontent.com/29393510/35610150-0fc9f226-0682-11e8-9b5f-a4a730490f30.png)


![collections](https://user-images.githubusercontent.com/29393510/35610168-1aeb5a46-0682-11e8-8e39-5a4886931b4f.png)

**Comment by akaipham** [comment]
@haroonKhan-10p Since `user.relation(Parse.Role).query()` returns only Parse.Query, you need to call `.find()` to fetch the object. Reference here:
> http://parseplatform.org/Parse-SDK-JS/api/v1.11.1/Parse.Relation.html#query

**Comment by flovilmart** [comment]
@haroonKhan-10p if you're attempting to get the roles for a particular user this is how you should make the query:

```js
const query = new Parse.Query(Parse.Role)
query.equalTo('users', user)
const roles = await query.find();
```
