### ISSUE TITLE
My MasterKeys have been compromised.

### ISSUE THREAD

**Issue by beckandbeckllc** [ParsePlatform/parse-server#2852]
Can someone please help me reset my Masterkeys for my parse apps? I have looked everywhere and cannot find the solution.

**Comment by hramos** [comment]
If you're using Parse Server, you can change the master key during initialization (check out the README, as it depends on how Parse Server is being used).

If you're using hosted parse.com, this is not the right place to get support. You can try https://parse.com/help

**Comment by beckandbeckllc** [comment]
Can you please give me a support email that I can contact?

**Comment by hramos** [comment]
Visit https://parse.com/help for support.

**Comment by hramos** [comment]
Visit https://parse.com/help for support. If all you need is to reset your master keys, you can do so yourself by logging in to your Parse.com Dashboard.

**Comment by beckandbeckllc** [comment]
Can you please tell me how to reset it exactly? I don't see the option to do so?

I would greatly appreciate it!

**Comment by cleever** [comment]
@beckandbeckllc What is your environment? 

if it is a self hosted parse server from this repo, you could change at config or start level:

https://github.com/ParsePlatform/parse-server#running-parse-server-locally
https://github.com/ParsePlatform/parse-server#configuration

If it is on parse.com, you can change it at parse.com dashboard:
App Settings->Security & Keys.

**Comment by beckandbeckllc** [comment]
We recently ported from parse.com and are hosting mongo and the parse open source with another hosting company.

In this case, how would we change the masterkey? I tried on parse.com but remembered it's not hosted there.... can you please outline exactly how to change the master key in my case?

Would greatly appreciate the help!

**Comment by cleever** [comment]
Which hosting company is that?
Please, provide all the information required by the issue template:

"- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : [FILL THIS OUT]
  - Operating System:     [FILL THIS OUT]
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [FILL THIS OUT]


Don't you have access to your server and config files? (ssh... etc)

**Comment by beckandbeckllc** [comment]
We are hosting with Webair on a dedicated server. They only manage Linux CentOS.  I don’t know the answers to the other questions. The hosting team is not familiar with Parse, so if you could describe what files to edit, and how to change the masterkey/reflect the changes in code and mobile apps, I would greatly appreciate it!

**Comment by cleever** [comment]
In this case you can send the readme https://github.com/ParsePlatform/parse-server/blob/master/README.md to the hosting team.

All the information that they need is there.

Basically, they need to set env variables, or edit index.js (if the key is hardcoded), or restart with parse --masterKey NEW_MASTER_KEY param. 
...Depending of their setup.

This task should be easy by managed hosting team.
