### ISSUE TITLE
cannot disable cloud code logs

### ISSUE THREAD

**Issue by benishak** [ParsePlatform/parse-server#2855]
# Env 
Parse Server 2.2.22

# Problem
I want to disable these logs

```
info: afterSave triggered for .... 
```

I try this

```
loggerAdapter: {
        module: "parse-server/lib/Adapters/Logger/WinstonLoggerAdapter",
        options: {
            level: config.DEBUG ? "info" : "error"
        }
    },
```

and try also this

`console.info = function(){}`

but these logs still appear in the console `pm2 logs`

**Comment by acinader** [comment]
hi @benishak 

The key is ```logLevel``` not ```level```

I'll look at where to add this in the documentation.  I'm going to close this, but re-open if it doesn't solve for you.

**Comment by acinader** [comment]
and now that I've looked into it a little more, here's a better answer:

Winston is expecting logLevel, but parse-server uses just level.  Confusing :(.

So if you want to use the default logger, which you are, and you just want to adjust the log level, you can do it by simply setting the `level` key in your config and not even bothering with the `loggerAdapter` key.

**Comment by benishak** [comment]
this doesn't work I tried

`level : `

and
```
loggerAdapter: {
        options: {
            level: config.DEBUG ? "info" : "error"
        }
    },
```

actually I got an error when not defining the module

**Comment by acinader** [comment]
@benishak if you use 

```
loggerAdapter: {
        module: "parse-server/lib/Adapters/Logger/WinstonLoggerAdapter",
        options: {
            logLevel: config.DEBUG ? "info" : "error"
        }
    },
```

note that it is ```logLevel``` no ```level``` it should work.

Also  if you replace your whole ```loggerAdapter: { }```... with just ```level: "error:```

it should also work.  I have tested both.

**Comment by camdagr8** [comment]
Thanks for this.. it was driving me mad seeing the data for each cloud function when I wanted to see it for one particular function.

**Comment by QB3L** [comment]
@acinader this is a pretty old issue but the logLevel at the top level of the config is good and important enough information to put on the front page

**Comment by flovilmart** [comment]
You can pass it in the constructor: https://github.com/parse-community/parse-server/blob/master/src/ParseServer.js#L103

**Comment by QB3L** [comment]
Was thinking about putting it on README I meant. Sorry for the ambiguity.

**Comment by flovilmart** [comment]
There's nothing that prevents you from doing it
