### ISSUE TITLE
Create a project to track the status of support for Postgres

### ISSUE THREAD

**Issue by kulshekhar** [ParsePlatform/parse-server#2857]
Now that we can create and manage projects on Github, it might be helpful to create one in this repo for completing Postgres support. This way people willing to contribute code can see what's already done and what we can work on to help out.

**Comment by flovilmart** [comment]
I've added the Postgres support project:

https://github.com/ParsePlatform/parse-server/projects/2

Please file issues in the original issue tracker and I'll add those to the project to help tracking.

**Comment by kulshekhar** [comment]
Thanks @flovilmart 

By original issue tracker, are you referring to #20? Or do you just mean that we should continue creating postgres related issues in the normal manner using Github Issues?

**Comment by flovilmart** [comment]
I mean file issues normally! :)
