### ISSUE TITLE
server restart on  some of save _Installation request 

### ISSUE THREAD

**Issue by oazya500** [ParsePlatform/parse-server#2858]
server restart on  some of save _Installation request 

server restart every 10 minute at most

0|msegate  | info: beforeSave triggered for _Installation for user undefined:
0|msegate  |   Input: {"channels":{"__op":"AddUnique","objects":["MostShared"]},"pushType":"gcm","localeIdentifier":"ar-AE","appVersion":"1.123","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"9f445903-ed34-4cbb-a4fb-6d863b12322f","parseVersion":"1.13.1","appName":"هدهد","timeZone":"Asia/Riyadh"}
0|msegate  |   Result: {"object":{"channels":{"__op":"AddUnique","objects":["MostShared"]},"pushType":"gcm","localeIdentifier":"ar-AE","appVersion":"1.123","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"9f445903-ed34-4cbb-a4fb-6d863b12322f","parseVersion":"1.13.1","appName":"هدهد","timeZone":"Asia/Riyadh"}} className=_Installation, triggerType=beforeSave, user=undefined
0|msegate  | info: beforeSave triggered for _Installation for user undefined:
0|msegate  |   Input: {"channels":["MostShared"],"pushType":"gcm","localeIdentifier":"ar-AE","appVersion":"1.123","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"9f445903-ed34-4cbb-a4fb-6d863b12322f","parseVersion":"1.13.1","appName":"هدهد","timeZone":"Asia/Riyadh","createdAt":"2016-10-11T14:27:33.849Z","updatedAt":"2016-10-11T14:27:33.849Z","deviceToken":"APA91bGMgCTEqfyQclS_tEY5rKRY30tC5roHaCqMt9mALs3EU1uRllCQw_nAtY4LbVYpJ6N3oYVxDV-VH7ZWrks-4-_BDe1OnZ3imQNMvyuRhyGlFl5q1uFkNTHtYTYHJe3iSKYdnxOj","objectId":"dpkoo2Ecn5"}
0|msegate  |   Result: {"object":{"pushType":"gcm","deviceToken":"APA91bGMgCTEqfyQclS_tEY5rKRY30tC5roHaCqMt9mALs3EU1uRllCQw_nAtY4LbVYpJ6N3oYVxDV-VH7ZWrks-4-_BDe1OnZ3imQNMvyuRhyGlFl5q1uFkNTHtYTYHJe3iSKYdnxOj"}} className=_Installation, triggerType=beforeSave, user=undefined

# **_## /////////////////// server has error and restart
0|msegate  | ParseError { code: 101, message: 'Object not found.' }
0|msegate  | DATABASE_URI not specified, falling back to localhost._**
0|msegate  | info: beforeSave triggered for _Installation for user undefined:
0|msegate  |   Input: {"channels":["MostShared"],"pushType":"gcm","localeIdentifier":"ar-AE","appVersion":"1.123","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"9f445903-ed34-4cbb-a4fb-6d863b12322f","parseVersion":"1.13.1","appName":"هدهد","timeZone":"Asia/Riyadh","createdAt":"2016-10-11T14:27:33.849Z","updatedAt":"2016-10-11T14:27:34.678Z","deviceToken":"APA91bGMgCTEqfyQclS_tEY5rKRY30tC5roHaCqMt9mALs3EU1uRllCQw_nAtY4LbVYpJ6N3oYVxDV-VH7ZWrks-4-_BDe1OnZ3imQNMvyuRhyGlFl5q1uFkNTHtYTYHJe3iSKYdnxOj","SERIAL":"4d0**********","android_id":"*******","objectId":"dpkoo2Ecn5"}
0|msegate  |   Result: {"object":{"SERIAL":"4d0**********","android_id":"*********"}} className=_Installation, triggerType=beforeSave, user=undefined
0|msegate  | info: beforeSave triggered for _Installation for user gmV8prq1Vb:
0|msegate  |   Input: {"channels":["MostShared"],"pushType":"gcm","localeIdentifier":"ar-AE","appVersion":"1.123","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"9f445903-ed34-4cbb-a4fb-6d863b12322f","parseVersion":"1.13.1","appName":"هدهد","timeZone":"Asia/Riyadh","createdAt":"2016-10-11T14:27:33.849Z","updatedAt":"2016-10-11T14:27:37.072Z","deviceToken":"APA91bGMgCTEqfyQclS_tEY5rKRY30tC5roHaCqMt9mALs3EU1uRllCQw_nAtY4LbVYpJ6N3oYVxDV-VH7ZWrks-4-_BDe1OnZ3imQNMvyuRhyGlFl5q1uFkNTHtYTYHJe3iSKYdnxOj","SERIAL":"4d0**********","android_id":"********","User":{"__type":"Pointer","className":"_User","objectId":"gmV8prq1Vb"},"objectId":"dpkoo2Ecn5"}
0|msegate  |   Result: {"object":{"User":{"__type":"Pointer","className":"_User","objectId":"gmV8prq1Vb"},"SERIAL":"4d0**********","android_id":"*********"}} className=_Installation, triggerType=beforeSave, user=gmV8prq1Vb
0|msegate  | info: beforeSave triggered for _Installation for user gmV8prq1Vb:
0|msegate  |   Input: {"channels":["MostShared"],"pushType":"gcm","localeIdentifier":"ar-AE","appVersion":"1.123","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"9f445903-ed34-4cbb-a4fb-6d863b12322f","parseVersion":"1.13.1","appName":"هدهد","timeZone":"Asia/Riyadh","createdAt":"2016-10-11T14:27:33.849Z","updatedAt":"2016-10-11T14:31:41.954Z","deviceToken":"APA91bGMgCTEqfyQclS_tEY5rKRY30tC5roHaCqMt9mALs3EU1uRllCQw_nAtY4LbVYpJ6N3oYVxDV-VH7ZWrks-4-_BDe1OnZ3imQNMvyuRhyGlFl5q1uFkNTHtYTYHJe3iSKYdnxOj","SERIAL":"4d0**********","android_id":"*********","User":{"__type":"Pointer","className":"_User","objectId":"gmV8prq1Vb"},"objectId":"dpkoo2Ecn5"}
0|msegate  |   Result: {"object":{"User":{"__type":"Pointer","className":"_User","objectId":"gmV8prq1Vb"},"SERIAL":"4d0**********","android_id":"*********"}} className=_Installation, triggerType=beforeSave, user=gmV8prq1Vb
.
.
.
.
.
0|msegate  | info: beforeSave triggered for _Installation for user undefined:
0|msegate  |   Input: {"appName":"هدهد","appVersion":"1.120","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"49e22908-76ac-441e-94e4-8d89ea65ab0c","pushType":"gcm","channels":{"__op":"AddUnique","objects":["MostShared"]},"timeZone":"Asia/Riyadh","localeIdentifier":"ar-AE","parseVersion":"1.13.1"}
0|msegate  |   Result: {"object":{"channels":{"__op":"AddUnique","objects":["MostShared"]},"appName":"هدهد","appVersion":"1.120","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"49e22908-76ac-441e-94e4-8d89ea65ab0c","pushType":"gcm","timeZone":"Asia/Riyadh","localeIdentifier":"ar-AE","parseVersion":"1.13.1"}} className=_Installation, triggerType=beforeSave, user=undefined
0|msegate  | info: beforeSave triggered for _Installation for user undefined:
0|msegate  |   Input: {"channels":["MostShared"],"appName":"هدهد","appVersion":"1.120","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"49e22908-76ac-441e-94e4-8d89ea65ab0c","pushType":"gcm","timeZone":"Asia/Riyadh","localeIdentifier":"ar-AE","parseVersion":"1.13.1","createdAt":"2016-10-11T14:36:12.429Z","updatedAt":"2016-10-11T14:36:12.429Z","deviceToken":"APA91bFYI4aEqikKaHLLw-1OCbd3XYi5l-MTOa5-liqFZ_ZiFj5zlOysfMo0UOScqJDjcPaH8aTGKSL6Ks2fmzb5XTx5SuKrTPYsOYsmPP2BVqYpT6WPQbd4D4gU4okatvVODO6V-XID","objectId":"jbZcZXA3yL"}
0|msegate  |   Result: {"object":{"pushType":"gcm","deviceToken":"APA91bFYI4aEqikKaHLLw-1OCbd3XYi5l-MTOa5-liqFZ_ZiFj5zlOysfMo0UOScqJDjcPaH8aTGKSL6Ks2fmzb5XTx5SuKrTPYsOYsmPP2BVqYpT6WPQbd4D4gU4okatvVODO6V-XID"}} className=_Installation, triggerType=beforeSave, user=undefined

# **_## /////////////////// server has error and restart
0|msegate  | ParseError { code: 101, message: 'Object not found.' }
0|msegate  | DATABASE_URI not specified, falling back to localhost.**_
0|msegate  | info: beforeSave triggered for _Installation for user undefined:
0|msegate  |   Input: {"channels":["MostShared"],"appName":"هدهد","appVersion":"1.120","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"49e22908-76ac-441e-94e4-8d89ea65ab0c","pushType":"gcm","timeZone":"Asia/Riyadh","localeIdentifier":"ar-AE","parseVersion":"1.13.1","createdAt":"2016-10-11T14:36:12.429Z","updatedAt":"2016-10-11T14:36:13.797Z","deviceToken":"APA91bFYI4aEqikKaHLLw-1OCbd3XYi5l-MTOa5-liqFZ_ZiFj5zlOysfMo0UOScqJDjcPaH8aTGKSL6Ks2fmzb5XTx5SuKrTPYsOYsmPP2BVqYpT6WPQbd4D4gU4okatvVODO6V-XID","objectId":"jbZcZXA3yL"}
0|msegate  |   Result: {"object":{"pushType":"gcm","deviceToken":"APA91bFYI4aEqikKaHLLw-1OCbd3XYi5l-MTOa5-liqFZ_ZiFj5zlOysfMo0UOScqJDjcPaH8aTGKSL6Ks2fmzb5XTx5SuKrTPYsOYsmPP2BVqYpT6WPQbd4D4gU4okatvVODO6V-XID"}} className=_Installation, triggerType=beforeSave, user=undefined
0|msegate  | info: beforeSave triggered for _Installation for user undefined:
0|msegate  |   Input: {"channels":["MostShared"],"appName":"هدهد","appVersion":"1.120","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"49e22908-76ac-441e-94e4-8d89ea65ab0c","pushType":"gcm","timeZone":"Asia/Riyadh","localeIdentifier":"ar-AE","parseVersion":"1.13.1","createdAt":"2016-10-11T14:36:12.429Z","updatedAt":"2016-10-11T14:36:17.157Z","deviceToken":"APA91bFYI4aEqikKaHLLw-1OCbd3XYi5l-MTOa5-liqFZ_ZiFj5zlOysfMo0UOScqJDjcPaH8aTGKSL6Ks2fmzb5XTx5SuKrTPYsOYsmPP2BVqYpT6WPQbd4D4gU4okatvVODO6V-XID","android_id":"*********","SERIAL":"4d0**********","objectId":"jbZcZXA3yL"}
0|msegate  |   Result: {"object":{"android_id":"*********","SERIAL":"4d0**********"}} className=_Installation, triggerType=beforeSave, user=undefined

**Comment by oazya500** [comment]
cloud code function 

Parse.Cloud.beforeSave(Parse.Installation, function(request, response) {
                 response.success();
});

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

**Comment by oazya500** [comment]
Describe your issue in as much detail as possible.

server restart on some of save _Installation request

server restart every 10 minute at most

Server

parse-server version (Be specific! Don't say 'latest'.) : 2.2.22 and 2.2.21
Operating System: centos 6
Hardware: VPS
Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): mesbahey.com
Database

MongoDB version: v3.0.12
Storage engine: { "name" : "mmapv1" }
Hardware: VPS
Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mesbahey.com
Logs/Trace

0|msegate | info: beforeSave triggered for _Installation for user undefined:
0|msegate | Input: {"channels":{"__op":"AddUnique","objects":["MostShared"]},"pushType":"gcm","localeIdentifier":"ar-AE","appVersion":"1.123","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"9f445903-ed34-4cbb-a4fb-6d863b12322f","parseVersion":"1.13.1","appName":"هدهد","timeZone":"Asia/Riyadh"}
0|msegate | Result: {"object":{"channels":{"__op":"AddUnique","objects":["MostShared"]},"pushType":"gcm","localeIdentifier":"ar-AE","appVersion":"1.123","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"9f445903-ed34-4cbb-a4fb-6d863b12322f","parseVersion":"1.13.1","appName":"هدهد","timeZone":"Asia/Riyadh"}} className=_Installation, triggerType=beforeSave, user=undefined
0|msegate | info: beforeSave triggered for _Installation for user undefined:
0|msegate | Input: {"channels":["MostShared"],"pushType":"gcm","localeIdentifier":"ar-AE","appVersion":"1.123","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"9f445903-ed34-4cbb-a4fb-6d863b12322f","parseVersion":"1.13.1","appName":"هدهد","timeZone":"Asia/Riyadh","createdAt":"2016-10-11T14:27:33.849Z","updatedAt":"2016-10-11T14:27:33.849Z","deviceToken":"APA91bGMgCTEqfyQclS_tEY5rKRY30tC5roHaCqMt9mALs3EU1uRllCQw_nAtY4LbVYpJ6N3oYVxDV-VH7ZWrks-4-_BDe1OnZ3imQNMvyuRhyGlFl5q1uFkNTHtYTYHJe3iSKYdnxOj","objectId":"dpkoo2Ecn5"}
0|msegate | Result: {"object":{"pushType":"gcm","deviceToken":"APA91bGMgCTEqfyQclS_tEY5rKRY30tC5roHaCqMt9mALs3EU1uRllCQw_nAtY4LbVYpJ6N3oYVxDV-VH7ZWrks-4-_BDe1OnZ3imQNMvyuRhyGlFl5q1uFkNTHtYTYHJe3iSKYdnxOj"}} className=_Installation, triggerType=beforeSave, user=undefined

**_## /////////////////// server has error and restart

0|msegate | ParseError { code: 101, message: 'Object not found.' }
0|msegate | DATABASE_URI not specified, falling back to localhost._**
0|msegate | info: beforeSave triggered for _Installation for user undefined:
0|msegate | Input: {"channels":["MostShared"],"pushType":"gcm","localeIdentifier":"ar-AE","appVersion":"1.123","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"9f445903-ed34-4cbb-a4fb-6d863b12322f","parseVersion":"1.13.1","appName":"هدهد","timeZone":"Asia/Riyadh","createdAt":"2016-10-11T14:27:33.849Z","updatedAt":"2016-10-11T14:27:34.678Z","deviceToken":"APA91bGMgCTEqfyQclS_tEY5rKRY30tC5roHaCqMt9mALs3EU1uRllCQw_nAtY4LbVYpJ6N3oYVxDV-VH7ZWrks-4-_BDe1OnZ3imQNMvyuRhyGlFl5q1uFkNTHtYTYHJe3iSKYdnxOj","SERIAL":"4d0*******","android_id":"*","objectId":"dpkoo2Ecn5"}
0|msegate | Result: {"object":{"SERIAL":"4d0****","android_id":"***"}} className=_Installation, triggerType=beforeSave, user=undefined
0|msegate | info: beforeSave triggered for _Installation for user gmV8prq1Vb:
0|msegate | Input: {"channels":["MostShared"],"pushType":"gcm","localeIdentifier":"ar-AE","appVersion":"1.123","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"9f445903-ed34-4cbb-a4fb-6d863b12322f","parseVersion":"1.13.1","appName":"هدهد","timeZone":"Asia/Riyadh","createdAt":"2016-10-11T14:27:33.849Z","updatedAt":"2016-10-11T14:27:37.072Z","deviceToken":"APA91bGMgCTEqfyQclS_tEY5rKRY30tC5roHaCqMt9mALs3EU1uRllCQw_nAtY4LbVYpJ6N3oYVxDV-VH7ZWrks-4-_BDe1OnZ3imQNMvyuRhyGlFl5q1uFkNTHtYTYHJe3iSKYdnxOj","SERIAL":"4d0****","android_id":"**","User":{"__type":"Pointer","className":"_User","objectId":"gmV8prq1Vb"},"objectId":"dpkoo2Ecn5"}
0|msegate | Result: {"object":{"User":{"__type":"Pointer","className":"_User","objectId":"gmV8prq1Vb"},"SERIAL":"4d0****","android_id":"***"}} className=_Installation, triggerType=beforeSave, user=gmV8prq1Vb
0|msegate | info: beforeSave triggered for _Installation for user gmV8prq1Vb:
0|msegate | Input: {"channels":["MostShared"],"pushType":"gcm","localeIdentifier":"ar-AE","appVersion":"1.123","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"9f445903-ed34-4cbb-a4fb-6d863b12322f","parseVersion":"1.13.1","appName":"هدهد","timeZone":"Asia/Riyadh","createdAt":"2016-10-11T14:27:33.849Z","updatedAt":"2016-10-11T14:31:41.954Z","deviceToken":"APA91bGMgCTEqfyQclS_tEY5rKRY30tC5roHaCqMt9mALs3EU1uRllCQw_nAtY4LbVYpJ6N3oYVxDV-VH7ZWrks-4-_BDe1OnZ3imQNMvyuRhyGlFl5q1uFkNTHtYTYHJe3iSKYdnxOj","SERIAL":"4d0****","android_id":"***","User":{"__type":"Pointer","className":"_User","objectId":"gmV8prq1Vb"},"objectId":"dpkoo2Ecn5"}
0|msegate | Result: {"object":{"User":{"__type":"Pointer","className":"_User","objectId":"gmV8prq1Vb"},"SERIAL":"4d0****","android_id":"******"}} className=_Installation, triggerType=beforeSave, user=gmV8prq1Vb
.
.
.
.
.
0|msegate | info: beforeSave triggered for _Installation for user undefined:
0|msegate | Input: {"appName":"هدهد","appVersion":"1.120","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"49e22908-76ac-441e-94e4-8d89ea65ab0c","pushType":"gcm","channels":{"__op":"AddUnique","objects":["MostShared"]},"timeZone":"Asia/Riyadh","localeIdentifier":"ar-AE","parseVersion":"1.13.1"}
0|msegate | Result: {"object":{"channels":{"__op":"AddUnique","objects":["MostShared"]},"appName":"هدهد","appVersion":"1.120","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"49e22908-76ac-441e-94e4-8d89ea65ab0c","pushType":"gcm","timeZone":"Asia/Riyadh","localeIdentifier":"ar-AE","parseVersion":"1.13.1"}} className=_Installation, triggerType=beforeSave, user=undefined
0|msegate | info: beforeSave triggered for _Installation for user undefined:
0|msegate | Input: {"channels":["MostShared"],"appName":"هدهد","appVersion":"1.120","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"49e22908-76ac-441e-94e4-8d89ea65ab0c","pushType":"gcm","timeZone":"Asia/Riyadh","localeIdentifier":"ar-AE","parseVersion":"1.13.1","createdAt":"2016-10-11T14:36:12.429Z","updatedAt":"2016-10-11T14:36:12.429Z","deviceToken":"APA91bFYI4aEqikKaHLLw-1OCbd3XYi5l-MTOa5-liqFZ_ZiFj5zlOysfMo0UOScqJDjcPaH8aTGKSL6Ks2fmzb5XTx5SuKrTPYsOYsmPP2BVqYpT6WPQbd4D4gU4okatvVODO6V-XID","objectId":"jbZcZXA3yL"}
0|msegate | Result: {"object":{"pushType":"gcm","deviceToken":"APA91bFYI4aEqikKaHLLw-1OCbd3XYi5l-MTOa5-liqFZ_ZiFj5zlOysfMo0UOScqJDjcPaH8aTGKSL6Ks2fmzb5XTx5SuKrTPYsOYsmPP2BVqYpT6WPQbd4D4gU4okatvVODO6V-XID"}} className=_Installation, triggerType=beforeSave, user=undefined

**_## /////////////////// server has error and restart

0|msegate | ParseError { code: 101, message: 'Object not found.' }
0|msegate | DATABASE_URI not specified, falling back to localhost._
0|msegate | info: beforeSave triggered for _Installation for user undefined:
0|msegate | Input: {"channels":["MostShared"],"appName":"هدهد","appVersion":"1.120","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"49e22908-76ac-441e-94e4-8d89ea65ab0c","pushType":"gcm","timeZone":"Asia/Riyadh","localeIdentifier":"ar-AE","parseVersion":"1.13.1","createdAt":"2016-10-11T14:36:12.429Z","updatedAt":"2016-10-11T14:36:13.797Z","deviceToken":"APA91bFYI4aEqikKaHLLw-1OCbd3XYi5l-MTOa5-liqFZ_ZiFj5zlOysfMo0UOScqJDjcPaH8aTGKSL6Ks2fmzb5XTx5SuKrTPYsOYsmPP2BVqYpT6WPQbd4D4gU4okatvVODO6V-XID","objectId":"jbZcZXA3yL"}
0|msegate | Result: {"object":{"pushType":"gcm","deviceToken":"APA91bFYI4aEqikKaHLLw-1OCbd3XYi5l-MTOa5-liqFZ_ZiFj5zlOysfMo0UOScqJDjcPaH8aTGKSL6Ks2fmzb5XTx5SuKrTPYsOYsmPP2BVqYpT6WPQbd4D4gU4okatvVODO6V-XID"}} className=_Installation, triggerType=beforeSave, user=undefined
0|msegate | info: beforeSave triggered for _Installation for user undefined:
0|msegate | Input: {"channels":["MostShared"],"appName":"هدهد","appVersion":"1.120","deviceType":"android","appIdentifier":"com.msbahi_os.msegatey","installationId":"49e22908-76ac-441e-94e4-8d89ea65ab0c","pushType":"gcm","timeZone":"Asia/Riyadh","localeIdentifier":"ar-AE","parseVersion":"1.13.1","createdAt":"2016-10-11T14:36:12.429Z","updatedAt":"2016-10-11T14:36:17.157Z","deviceToken":"APA91bFYI4aEqikKaHLLw-1OCbd3XYi5l-MTOa5-liqFZ_ZiFj5zlOysfMo0UOScqJDjcPaH8aTGKSL6Ks2fmzb5XTx5SuKrTPYsOYsmPP2BVqYpT6WPQbd4D4gU4okatvVODO6V-XID","android_id":"****","SERIAL":"4d0****","objectId":"jbZcZXA3yL"}
0|msegate | Result: {"object":{"android_id":"***","SERIAL":"4d0*******"}} className=_Installation, triggerType=beforeSave, user=undefined

**Comment by oazya500** [comment]
affter update my all my npm now server not restart but show this error insted

 You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
   [object Object]
