### ISSUE TITLE
From where i can find my "Access Key ID" and "Secrete Access Key" to download File from parse?

### ISSUE THREAD

**Issue by SatishMotif** [ParsePlatform/parse-server#2860]
I need to download the files from the following S3 bucket:
https://files.parsetfss.com/0844782c-8340-41f3-8ff6-2bd0c1a39eaa/
 
The bucket was created by Parse.com, who hosts my Parse site, to store the files of my site.
 
The access key is kept by Parse.com, hence I am not able to access the file bucket directly.
·         Could you please provide a link for me to download the files?
·         Or could you please provide a "Access Key ID" and "Secrete Access Key" pair, by which I can use a client tool to logon to the bucket and download the files?

I have also reported other issue related to file migration but nobody is replying, below is the link:
https://github.com/ParsePlatform/parse-server/issues/2781

Somebody please help, its urgent!

**Comment by kulshekhar** [comment]
Isn't it possible to download it from the dashboard?

**Comment by SatishMotif** [comment]
@kulshekhar there are thousands of file in my DB and I cannot download it one by one.

**Comment by kulshekhar** [comment]
What I was driving at was that if you can access the files from the dashboard, you could probably write a small script to go through all your records and download/transfer the files.

**Comment by SatishMotif** [comment]
Okay thanks @kulshekhar, can you tell me wat kind of script will be useful here?

**Comment by flovilmart** [comment]
Have a look here: https://github.com/parse-server-modules/parse-files-utils

This project will lookup all your files mapped in your objects, and download/transfer them depending the configuration. For further issues in the parse-file-utils project, please open them on that repository

**Comment by SatishMotif** [comment]
Hey @flovilmart, it really feels great to hear someone from parse. Thanks a lot.
Can you please reply about below post too? As I am waiting for last 15 days for someone from parse to take a look.
https://github.com/ParsePlatform/parse-server/issues/2781

And yes let me tell you that i have given that issue as a reference for this post but that is not the same so kindly try to give an answer on that context only.

**Comment by flovilmart** [comment]
@SatishMotif I am not from Parse. but glad to help.
