### ISSUE TITLE
Does hosted parse server lock reads from Parse.com

### ISSUE THREAD

**Issue by pushparajsamant** [ParsePlatform/parse-server#2865]
I have just completed migrating our database from parse.com to Nodechef. Everything was working fine when the API calls were only from Parse.com. My current Production App is hitting Parse.com and the data is now being read from Nodechef. 

To complete the migration process I started building the Parse Server on Nodechef. I completed all the necessary changes required in cloud code. Now I have a beta app pointing to a hosted Parse Server.

During testing I edited a Parse object using the Beta App. Now this Parse Object was initially created by Parse.com API. Once I edited this object this object successfully it is now only accessible from Nodechef and my production App is not able to read this data. The Nodechef app continues reading writing without any issue. 

In response to a query on the class from Parse.com SDK I get a 200 with {"code":1,"error":"internal error"} as response.

So my question is, is it a expected result ? That objects created/edited in the same database by Hosted Parse Server will be rendered locked for read/write from Parse.com.

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1. Migrate the database out of Parse.com to Self Hosted MongoDB.
2. Create a object using Parse.com connected to the Self Hosted MongoDB.
3. Edit the same object from your own Self Hosted Parse Server.
4. Try reading the object from Parse.com.

The thing is not only the Javascript SDK but the Parse.com dashboard is also not able to filter the object. 

#### Expected Results

Expected the updates to objects work both ways until migration was complete.

#### Actual Outcome

Object is locked and cannot read the object even from Parse.com Dashboard. 

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.16
  - Operating System:    Nodechef 
  - Hardware:            Cloud Server
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Nodechef

- **Database**
  - MongoDB version: Nodechef Mongo DB
  - Storage engine:  
  - Hardware:       
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Nodechef

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

**Comment by hramos** [comment]
It's not expected behavior. The issue tracker is not the best place to troubleshoot individual deployments however. We can reopen if a specific issue in Parse Server is identified.

**Comment by pushparajsamant** [comment]
Thanks Hector, Thats what I was trying to find out whether its a expected behaviour in parse server.
