### ISSUE TITLE
In-App-Purchase compatibility (PFPurchase)

### ISSUE THREAD

**Issue by iOSassou** [ParsePlatform/parse-server#2866]
From the [Compatibility with Hosted Parse](https://github.com/ParsePlatform/parse-server/wiki/Compatibility-with-Hosted-Parse) page, In-App Purchase is not supported, but I found some merged PR about it.

I have an iOS app that makes consummable and non-consumable purchases using [PFPurchase buyProduct:] and restores via [PFPurchase restore].

Are these features supported by Parse Server?

**Comment by hramos** [comment]
I suggest pinging the author of the PR to make sure they update the docs as well if needed.

**Comment by iOSassou** [comment]
@flovilmart Hi, any chance you can confirm this please? The PR is https://github.com/ParsePlatform/parse-server/pull/515

**Comment by flovilmart** [comment]
I implemented that PR a while ago to the best of my knowledge and apple documentation about IAP purchase validation. You should probably try with sandboxed IAP's and make sure the product validation is working as expected.

**Comment by iOSassou** [comment]
Great, I'll give it a try next week. Thank you for the reply

**Comment by Apptation** [comment]
note: I gave PFPurchase on iOS a try with an auto-renewable IAP and set all the required columns in the Product table.

The iOS SDK spits out the error when running the "downloadAssetForTransaction":
[Error]: The receipt is invalid. (Code: 144, Version: 1.14.2)

I'm assuming this is because the receipt validation doesn't work for renewable subscriptions, and that the way to implement proper receipt validation is to use cloud code.. ?

Thanks

Chris

**Comment by flovilmart** [comment]
can you run with VERBOSE=1 to have more logs understanding why the receipt is not valid?

**Comment by Apptation** [comment]
yep - I will try that today, and will let you know how it goes.  Thanks

**Comment by Cliffordwh** [comment]
is there any documentation on PFPurchase?  and the implementation?

**Comment by Cliffordwh** [comment]
Can confirm that standard IAP works! I managed to get this all working. ( Sandbox )

**Comment by flovilmart** [comment]
So the auto renewable IAP is not working right?

**Comment by Cliffordwh** [comment]
Haven't tested, Will do that shortly! I though id first draft some documentation from start to end on the implementation for swift3. Could we then use that on the wiki?

**Comment by flovilmart** [comment]
Probably on the docs repo would be better. We're moving the docs there so the wiki holds implementation details, guidelines etc...

**Comment by Cliffordwh** [comment]
Thanks!

**Comment by flovilmart** [comment]
here: https://github.com/parseplatform/docs

That's in markdown, so very easy :)
