### ISSUE TITLE
Push Notification Logs

### ISSUE THREAD

**Issue by irfanfadilah** [ParsePlatform/parse-server#2867]
What's log message for successfully sent Push Notifications..?

I sent some notifications through cURL while watching/tailing the logs and it's returning `{ result: true }`, but the logs didn't show anything..

ParseServer: version 2.2.12
Push Notifications: APNS and GCM

**Comment by flovilmart** [comment]
Push notifications are sent asynchronously but their status should be stored in the `_PushStatus` collection
