### ISSUE TITLE
Allow configuration options for Postgres

### ISSUE THREAD

**Issue by kulshekhar** [ParsePlatform/parse-server#2872]
The current implementation of the Postgres adapter establishes a connection using the default settings. It would be helpful if we could customize the options available in the Postgres driver. As things stand, there are two sets of options that can be configured:

- The [initialization options](https://github.com/vitaly-t/pg-promise/wiki/Connection-Syntax#configuration-object) for the `pg-promise` wrapper
- The [options](https://github.com/brianc/node-postgres/blob/master/lib/defaults.js) for the `node-postgres` instance available via `pgp.pg.defaults.OPTION_NAME`

To implement this, parse server can accept them individually as command line parameters/environment variable (the existing `--databaseOptions` option and a new option). 

Alternatively, they can be combined into the existing `--databaseOptions` option with the convention that this option have a structure similar to:

```json
{
  "pgpOptions": { },
  "pgOptions": { }
}
```

Of course, the keys could have more descriptive names. If we can decide on the preferable approach and the naming convention, I could take a stab at implementing this.

**Comment by flovilmart** [comment]
we have similar options for the mongodb adapter, I'll let you knock a first implementation.
I'd put both options hashes in the same databaseOptions wrapped for the sake of simplicity. What do you think?

**Comment by kulshekhar** [comment]
Yeah, that would be my preferred way of implementing it as well. I'll get started with this then

**Comment by flovilmart** [comment]
@kulshekhar awesome that you're picking that up! Did you get a chance to test the adapter with a simple configuration?

**Comment by kulshekhar** [comment]
I was able to create a class and fields using parse dashboard, if that's what you mean. I haven't done much else so far

**Comment by flovilmart** [comment]
Awesome!

**Comment by kulshekhar** [comment]
It seems that the following format for the options would be more user-friendly:

```json
{
  "host": "",
  "port": "",
  "...": "",
  "pgOptions": {}
}
```

This would have all the options offered by `pg-promise` at the first level. All the options offered by `node-postgres` could be under the `pgOptions` hash. 

This is how I'm currently implementing it. Let me know if you want me to change this.

**Comment by flovilmart** [comment]
That looks good :)

**Comment by rendongsc** [comment]
@flovilmart 
databaseOptions can by PostgresConfigParser.getDatabaseOptionsFromURI.
replace  ParseServer config databaseOptions for  pg initialization options.

```
var api = new ParseServer({
  databaseURI: databaseUri || 'postgres://Test:123@localhost:5432/Test',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'myAppId',
  masterKey: process.env.MASTER_KEY || '', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',  // Don't forget to change to https if needed
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  },
  databaseOptions: {
    connect: function (client, dc, isFresh) {      
      if (isFresh) {       
        client.query('SET search_path = cust');
      }
    }
  }
});
```
**PostgresClient.js**
```

const parser = require('./PostgresConfigParser');

export function createClient(uri, databaseOptions) {
  let dbOptions = {};
  databaseOptions = databaseOptions || {};

  if (uri) {
    dbOptions = parser.getDatabaseOptionsFromURI(uri);
  }

  let pgp = require('pg-promise')(databaseOptions);

  const client = pgp(dbOptions);

  if (dbOptions.pgOptions) {
    for (const key in dbOptions.pgOptions) {
      client.pg.defaults[key] = dbOptions.pgOptions[key];
    }
  }

  return client;
}

```

**Comment by flovilmart** [comment]
@rendongsc I'm not sure what you mean. Is that an issue for you?

**Comment by rendongsc** [comment]
yes, it's about the use of databaseOptions
