### ISSUE TITLE
Include pointer data with Parse.User.logIn method

### ISSUE THREAD

**Issue by tanmays** [ParsePlatform/parse-server#288]
Parse previously didn't have any way to get all pointer data a User class might have on login, unnecessarily requiring an additional call to get full pointer objects. 

It would be great if the login (or any future social login) methods would have ability to return full pointer objects or at least have an optional `include` parameter to selectively get those pointers.

**Comment by gfosco** [comment]
This would be very cool, and a great example of why I think Parse will only get better in open source.  I'm sure others will have opinions on just how it should be implemented... It might also be useful if a query could choose to include *all* pointer columns listed in the schema.

**Comment by gfosco** [comment]
Well, no one has picked up this enhancement, so I'm going to close the issue.  It will still be welcome as a pull request to add this functionality.  Thanks. :+1:
