### ISSUE TITLE
Custom UI in dashboard

### ISSUE THREAD

**Issue by nirajmchauhan** [ParsePlatform/parse-server#2881]
Hi,

Is there any way to have custom screens in Parse dashboard. I have setup Kue for background jobs, its working fine but I would also like to trigger it manually from some UI, previously their was an option in dashboard. 
Can I still achieve it by writing some code?

**Comment by hramos** [comment]
There's a separate repo for the Dashboard over at https://github.com/ParsePlatform/parse-dashboard. Closing as this is not reporting an issue with Parse Server.
