### ISSUE TITLE
logInWithUsernameInBackground() locks up and generates an assertd[6900] error??

### ISSUE THREAD

**Issue by mprogers** [ParsePlatform/parse-server#2884]
Created a simple iOS program to demonstrate parse. When calling loginWithUsernameInBackground() in a simple IBAction, tapping the button causes the program to freeze, apparently within the loginWithUsernameInBackground().

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1. Launch program (see attached)
2. Tap on login button
3. Watch it crash, with the login button appearing that it is still 

I can't attach the file, but here is the code in question:

 @IBAction func login(sender: AnyObject) {
        print(emailTF.text)
        print(passwordTF.text)
        PFUser.logInWithUsernameInBackground(emailTF.text!, password: passwordTF.text!, block:{(user, error) -> Void in
            if error != nil{
                print(error)
            }
            else {
                // Everything went alright here
                self.displayAlertWithTitle("Success!", message:"Login successful")
                
            }
        }
        )
        print("We are done")
    }

The first two print() statements execute ... the second is never reached. There is an assertd message in the iOS simulator logs.

#### Expected Results

loginWithUsernameInBackground() shouldn't lock up
#### Actual Outcome

It does.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 
  - Operating System:     iOS 9.3
  - Hardware:             iPhone 6Plus
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): back4app.com

- **Database**
  - MongoDB version: N/A
  - Storage engine:  N/A
  - Hardware:        N/A
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): N/A

### Logs/Trace

Oct 18 14:43:40 theviewahvalous assertiond[6900]: assertion failed: 16A323 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1

**Comment by hramos** [comment]
As described, this does not appear to be an issue with Parse Server. You may want to open an issue against the iOS SDK instead: https://github.com/ParsePlatform/Parse-SDK-iOS-OSX

**Comment by mprogers** [comment]
Oops, thanks hramos, I will do that!
