### ISSUE TITLE
How do I handle installation when app is deleted?

### ISSUE THREAD

**Issue by jimmyzzzzzzz** [ParsePlatform/parse-server#2889]
I receive error when I'm trying to send push notification to a device that uninstalled my app 
`ERR! parse-server-push-adapter APNS cannot find vaild connection for 6796a7bd62d261228e1f5e643272e68b7b4ac299650e9413c87ba5e41c08fe8`
I want to record uninstallation event and delete the corresponding  entry from Installation class when this happens. How can I catch this error?

```
Parse.Push.send({
  where: query, 
  data: {
    alert: alert,
  }
}, {
  useMasterKey: true,
  success: function() {
    console.log("success");
  },
  error: function(error) {
    console.log("error");
  }
});
```

I thought I could catch it in the error function, but `console.log("error");` was never executed when this happened.

**Comment by alexblack** [comment]
+1

**Comment by flovilmart** [comment]
On iOS there is no mean to know when the app is deleted, I'm not sure about android.

As for devices tokens, there was some discussions about marking invalid tokens.
