### ISSUE TITLE
hoypido

### ISSUE THREAD

**Issue by nparziale** [ParsePlatform/parse-server#2890]
guys my main app is down, but all others are working fine, i need someway to contact you in order to get this fixed.

please help me out asap with this

**Comment by nparziale** [comment]
if the dashboard loads, it shows "temporary error" whener i click on a collection

**Comment by gateway** [comment]
you should probably provide some log data and turn on VERBOSE to 1 .. dont think you will get an answer with this type of post w/o more details

**Comment by flovilmart** [comment]
If you app is still on parse.com, you should contact the parse team on https://parse.com/help. if you parse-server app is down, you should check with your hosting, deployments etc... and report back when you have more informations.
