### ISSUE TITLE
AfterSave action on Parse.User object runs indefinitely

### ISSUE THREAD

**Issue by florianbepunkt** [ParsePlatform/parse-server#2891]
I have the following code in my main.js from our example parse server repo

```
Parse.Cloud.afterSave(Parse.User, function(request) {

	var UserQueryData = Parse.Object.extend('UserQueryData');
	var userQueryData = new UserQueryData();

	userQueryData.set('user', request.object);

	userQueryData.save(null, {
		success: function(userQueryData) {
			request.object.set('userQueryData', userQueryData);
			request.object.save(null, {
				useMasterKey: true,
				error: function(error) {
					console.error('Error while writing userQueryData pointer to Parse.User object');
				}
			});
		},
		error: function(error) {
			// define error messages here
			console.error('Error while creating userQueryData');
		}
	})

});
```

what happens is, that as long as the server runs it writes row after row to userQueryData class. So basically it never stops.

Is this a bug or do I need to somehow "end" my cloud function. haven't seen something in the docs about this.

**Comment by flovilmart** [comment]
`request.object.save` this is the problem, calling `save` on the object that it's getting it's afterSave will trigger an afterSave again. You should check that the object don't have the key you're supposedly setting in after save.

someting like:

```
// abort early if data is set...
if (request.object.get('userQueryData')) {
  return
}
```

**Comment by florianbepunkt** [comment]
wow, that was fast and helpful. thank you.

**Comment by flovilmart** [comment]
np!
