### ISSUE TITLE
send session token via email

### ISSUE THREAD

**Issue by oallouch** [ParsePlatform/parse-server#2897]
Hi,
I'd like to create new users using Cloud Code with only an email and send them a link with the session token via email, telling them to update their default password.
Is it doable ? (or the right place to ask this)

Thx in advance,
Olivier Allouch (not in Montreal to kick some Firebase ass :) )

**Comment by flovilmart** [comment]
That's completely doable with a new Parse.Session object that you would manually write. 
But you don't need to to do that actually, just create the user with a random password and send the password reset email would work.

**Comment by oallouch** [comment]
Thx a lot !
Merci Florent. You're the best.

**Comment by oallouch** [comment]
Just a follow up if someone reaches this issue:
I've used a flag in Parse.User to differentiate an invite from a password request and I've used a custom email adapter.
`"use strict";
const SimpleMailgunAdapter = require("parse-server-simple-mailgun-adapter");

class CustomEmailAdapter {
  constructor(options) {
    this._mailgunAdapter = SimpleMailgunAdapter(options);
  }

  sendMail(mail) {
    return this._mailgunAdapter.sendMail(mail);
  }

  /**
   * @param options contains appName, link and user
   */
  sendPasswordResetEmail(options) {
    let emailObj;
    if (options.user.get("brandNew")) {
      emailObj = this._inviteEmail(options);
    } else {
      emailObj = this._resetPasswordEmail(options);
    }
    this.sendMail(emailObj);
  }

  _inviteEmail({link, user, appName, }) {
    let text = "Hi,\n\n" +
        "You've been invited to use " + appName + ".\n\n" +
        "" +
        "To set your password, click the link:\n" + link;
    let to = user.get("email") || user.get('username');
    let subject =  'Invitation for ' + appName;
    return { text, to, subject };
  }

  /** taken UserController */
  _resetPasswordEmail({link, user, appName, }) {
    let text = "Hi,\n\n" +
        "You requested to reset your password for " + appName + ".\n\n" +
        "" +
        "Click here to reset it:\n" + link;
    let to = user.get("email") || user.get('username');
    let subject =  'Password Reset for ' + appName;
    return { text, to, subject };
  }
}

module.exports = CustomEmailAdapter;
`
In index.js:

  emailAdapter: new CustomEmailAdapter({
    fromAddress: "xxxxxx@xxxxxx.com",
    domain: "xxxxxxxxxx",
    apiKey: "key-xxxxxxxxxxxxxxxxxxxxxxx",
  })

Then I remove the flag when the user first logs in or click the password reset link.

**Comment by flovilmart** [comment]
That is indeed a very nice usage of a custom adapter!

**Comment by oallouch** [comment]
Yes, it's THE entry point for email customization/internalization .
It should be documented.
It should even be splitted in 2: "sendMail" on 1 side (with the mailgun config), and "sendPasswordResetEmail and sendVerificationEmail" on the other side (with the email content logic).

Anyway, it works. I'm happy. Love

**Comment by flovilmart** [comment]
It's kinda documented through the wiki (that it's extensible via adapters) but you're right, examples of extending adapters are missing. 

If you'd like, you could do a small blog post about it, then we could reference it from the Wiki :)

**Comment by rjpalermo1** [comment]
Olivier, 

I'm having a hell of a time getting the default `parse-server-simple-mailgun-adapter` to work so looking for hints here and ran across this.

Can you help me understand a little better the use case here?  It may be the better solution for me.  As I currently understand....

1.  You just ask your users for an email address to register.
2.  After entering the email address, your code does a normal parse user registration using email for username, a random generated password and you add a BOOL=1 for new object `brandNew`
3.  You wrote the cloud-code above and modified your index.js that will send an email to the user based on the value of `brandNew`

So, if assumption correct...

1.  I can do this also - just require the name of the file above in my main.js?
2. This is mailgun...do you think it work with a custom adapter if I changed the vars to map to the custom adapter accordingly (ie, you have `let to =` and `let subject =`).?
3.  Did you put any customPages or custom HTML in for the password reset and validation that would force min chars or anything like that?

Ideally, if I assumed the use case correctly this will work out well for my app.  If I assumed Use case wrong, can you give a quick brief on how this works in your app?

Thank you in advance if you can reply...

**Comment by oallouch** [comment]
I only customized the email (and added a flag in Parse.User), I didn't change anything in the password changing process (the HTML is in the view folder in parse-server btw).
When the password is set, no trigger is called. (note for @flovilmart : that would have been great)
So, I had to remove the flag in several places (at login and when the reset link is clicked), otherwise the wrong email would have been sent.

**Comment by flovilmart** [comment]
> When the password is set, no trigger is called. (note for @flovilmart : that would have been great)

what do you suggest?

**Comment by oallouch** [comment]
@flovilmart  UserController's updatePassword removes _perishable_token .It would have been great if Parse.User's beforeSave trigger could have been called, so that I could remove my temporary stuff.

**Comment by flovilmart** [comment]
Yeah, we don't call it on purpose as it's an internal thing...  But we could
