### ISSUE TITLE
UsersRouter uses get rather than post for handleLogIn

### ISSUE THREAD

**Issue by altreze** [ParsePlatform/parse-server#2898]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [x ] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.

- [x ] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases

- [x ] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.

--

### Issue Description

I wanted to do authentication using User class in parse-server.
But it seems the route is only accessible using GET method and not post method.

```
curl -X GET -H "X-Parse-Application-Id: appID" "http://localhost:1337/parse/login"
```

I am posting down here the portion of code that seems having problem:

Describe your issue in as much detail as possible.

```
  mountRoutes() {
    this.route('GET', '/users', req => { return this.handleFind(req); });
    this.route('POST', '/users', req => { return this.handleCreate(req); });
    this.route('GET', '/users/me', req => { return this.handleMe(req); });
    this.route('GET', '/users/:objectId', req => { return this.handleGet(req); });
    this.route('PUT', '/users/:objectId', req => { return this.handleUpdate(req); });
    this.route('DELETE', '/users/:objectId', req => { return this.handleDelete(req); });
    this.route('GET', '/login', req => { return this.handleLogIn(req); });
    this.route('POST', '/logout', req => { return this.handleLogOut(req); });
    this.route('POST', '/requestPasswordReset', req => { return this.handleResetRequest(req); })
  }
```

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1. try authenticating using curl -X GET -H "X-Parse-Application-Id: appID" "http://localhost:1337/parse/login"
2. no places where to send username and password

#### Expected Results

[Login]

#### Actual Outcome

[message=bad or missing username]

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : [2.2.23]
  - Operating System:     [ Win 10]
  - Hardware:             [doesn't matter]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [Localhost]

- **Database**
  - MongoDB version: [3.2.10]
  - Storage engine:  [WiredTiger]
  - Hardware:        [doesn't matter]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [Localhost]

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

[error: Error generating response. ParseError { code: 200, message: 'bad or missing username' } code=200, message=bad or missing username]

**Comment by flovilmart** [comment]
See the REST documentation:

```
curl -X GET \
  -H "X-Parse-Application-Id: ${APPLICATION_ID}" \
  -H "X-Parse-REST-API-Key: ${REST_API_KEY}" \
  -H "X-Parse-Revocable-Session: 1" \
  -G \
  --data-urlencode 'username=cooldude6' \
  --data-urlencode 'password=p_n7!-e8' \
  https://localhost:1337/parse/login
```

http://parseplatform.github.io/docs/rest/guide/#logging-in

**Comment by altreze** [comment]
@flovilmart : Are there any special motivations to choose GET method for login using --data-urlencode rather than POST ?

**Comment by flovilmart** [comment]
It's been like that as far as I can recall on Parse.com. This is also semantically correct as the data you pass is not there to create anything.

**Comment by kulshekhar** [comment]
It can still cause security issues though:

- Password will be stored in server logs (which is obviously bad)
- History caches in browsers
([ref](http://stackoverflow.com/a/323286/3931609))

It would be a good if parse server, at the very least, allowed login via POSTing (even if it doesn't disallow the GET method)

**Comment by flovilmart** [comment]
In the browser, you're supposedly using the JS SDK that would send all requests as POST requests.

https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/RESTController.js#L164

I'd like to note that the passwords are supposedly stripped out of the parse log, if they aren't please open an issue.

**Comment by kulshekhar** [comment]
Is the behavior different from parse.com? I ask because I remember not being able to use POST to perform a login with the hosted service.

I also just tested it via the API console on the parse.com dashboard and couldn't login using POST. Following are the details of this request:

Method: `POST`
Endpoint: `login`
User master key: `No`
Run as: `-`
Query parameters: `{"username":"u","password":"p"}` (also tried with `username=u1&password=p`)

Result:

```json
{
    "error": "method not allowed"
}
```

This works when using the GET method and modifying the query params to `username=u&password=p`

Moreover, this would still be an issue if parse server was behind another server (nginx, load balancer, etc).

**Comment by flovilmart** [comment]
This is the exact same behavior as parse.com

And yes that can be a problem if your nginx logs query Params
