### ISSUE TITLE
ParseFile

### ISSUE THREAD

**Issue by verygreenboi** [ParsePlatform/parse-server#29]
What would be the strategy for storing files as Parse will not be hosting files anymore? Would this be a blessing in disguise? Can we now be able to host files larger than the 10mb limit in ParseFile if we implemented ParseFile ourselves?

**Comment by johnrufusj** [comment]
Im also interested in how ParseFile (current Files) will be handled.  I haven't yet wrapped my head around a clear migration path for this...

**Comment by wagnercsfilho** [comment]
I understood that the files are saved directly to mongodb

**Comment by verygreenboi** [comment]
@wagnercsfilho I thought they were pushed up to s3.

**Comment by GabrielMSharp** [comment]
https://github.com/ParsePlatform/parse-server/issues/8 This seems to suggest using Parse Server will point to old files (Which are on s3, not saved on the db), and I suppose future uploads should use ones own storage/s3 account.

**Comment by wagnercsfilho** [comment]
But parse the code server are pointing to mongo using Mongo ( GridStore ) in GridStoreAdapter. [GridStoreAdapter](https://github.com/ParsePlatform/parse-server/blob/7f5d744ce2eea774a10ab0a8c47bd587941c7775/GridStoreAdapter.js#L6)

**Comment by gfosco** [comment]
New file uploads are using GridStore by default, and if you migrated data from Parse the old files stay on the Parse S3 bucket.  We'll figure out the best approach for moving old files, if there is a way.

**Comment by amoran** [comment]
How difficult would it be to build an adapter for S3 so that developers can use their own buckets?
