### ISSUE TITLE
Sending emails from Cloud Code through AWS SES

### ISSUE THREAD

**Issue by devgeek27** [ParsePlatform/parse-server#2900]
Hi everyone

We have setup our Parse Server to use AWS SES as an email engine using that component: https://www.npmjs.com/package/parse-server-amazon-ses-adapter. 
It works perfectly fine.

Now the question is how can we send emails from the Cloud Code? Is it possible to use the node component inside cloud code?

Thank you in advance.

**Comment by flovilmart** [comment]
You can use the original sender from cloud code, or the adapter, just use:

```
let SESAdapter = require('parse-server-amazon-ses-adapter');
let options = {
         from: "Your Name <noreply@yourdomain.com>",
         accessKeyId: "Your AWS IAM Access Key ID",
         secretAccessKey: "Your AWS IAM Secret Access Key",
         region: "Your AWS Region"
      }
let mailSender = new SESAdapter(options);

mailSender.sendMail({
  to: "demo@email.com",
  subject: "Subject",
  text: "Hello world"
});
```
