### ISSUE TITLE
How do I cancel my Parse account?

### ISSUE THREAD

**Issue by ricksmith1138** [ParsePlatform/parse-server#2904]
Hi Parse

Can you please let me know how I can cancel my Parse account? I can find no way to do it through my account/billing settings.

Many thanks
Rick Smith
rick.smith@channel5.com

**Comment by cherukumilli** [comment]
@ricksmith1138 
I think this is the wrong forum for a question like this. Can you please check out  http://Parse.com/help and ask your question there?

**Comment by ricksmith1138** [comment]
@cherukumilli / @flovilmart - There is no option on http://parse.com/help for me to submit a question. Everything I try just leads me back to GIthub. 

Please direct me to the relevant URL, or provide a phone number I can call.

Many thanks
Rick Smith
rick.smith@channel5.com
