### ISSUE TITLE
When do we migrate Parse files on S3?

### ISSUE THREAD

**Issue by Code-Crash** [ParsePlatform/parse-server#2905]
Hi There,

We are currently migrating develop app to AWS. We have migrated data to mLab but we also migrated parse files to S3. Now, migration progress is not showing finalize enable. Could you please help us?

**Comment by skinp** [comment]
I'm confused about this "Now, migration progress is not showing finalize enable"... Is the data fully migrated to mLab?

Once that's done, use https://github.com/parse-server-modules/parse-files-utils to migrate your files.
