### ISSUE TITLE
python REST API connection failure

### ISSUE THREAD

**Issue by abhishekmishra07** [ParsePlatform/parse-server#2908]
I am trying to access my parse-server from a python code as below 

`import json,httplib
import urllib

connection = httplib.HTTPSConnection("domain.com/mount_path",port)
connection.connect()
connection.request('GET', '/classes/className?%s' % params, '', {
       "X-Parse-Application-Id": "####",
       "X-Parse-REST-API-Key": "####",
     })

result = json.loads(connection.getresponse().read())
print(result)`

The error received is 
 **File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known**

Any pointers please.

**Comment by kitaecc** [comment]
import json,httplib
connection = httplib.HTTPSConnection('domain.com', PORT)
connection.connect()
connection.request('GET', '/mount_path/classes/GameScore', '', { // mount_path
       "X-Parse-Application-Id": "${APPLICATION_ID}",
       "X-Parse-REST-API-Key": "${REST_API_KEY}"
     })
result = json.loads(connection.getresponse().read())
print result

are you testing curl?

**Comment by abhishekmishra07** [comment]
Issue resolve with ParsePy
