### ISSUE TITLE
Parse Cloud Jobs

### ISSUE THREAD

**Issue by nirajmchauhan** [ParsePlatform/parse-server#2909]
I just updated the npm package for parse-dashboard and it gives support for `Parse.Cloud.job`. I created following cloud job 

```
Parse.Cloud.job("CloudJobTesting", function(request, status) {
	console.log('Running....');
	status.success('Job completed successfully');	
});
```

Triggered the above job from parse-dashboard and  it worked.

So does it mean that, we can schedule cloud jobs without using `kue` or other scheduler?

**Comment by flovilmart** [comment]
You cannot schedule them without a queue or another cron! You can run them from parse-dashboard.
