### ISSUE TITLE
android  query.whereEqualTo ("Active",true) doesn't work

### ISSUE THREAD

**Issue by sabirmgd** [ParsePlatform/parse-server#2916]
when I try to filter my table using whereEqualTo  ("Active",true) ,, (which is for Boolean field , it doesn't work and returns 0 rows, I googled the issue and I found some other people also have it, the work around is to query all the rows and then filter them but that is not efficient. anyone has an efficient solution for this ?

**Comment by flovilmart** [comment]
Can you reopen je issue when it's filled correctly with the issue template?
