### ISSUE TITLE
am not able to pass more than 10 pointer object in containedIn using dotnet c#

### ISSUE THREAD

**Issue by ramukallepalli** [ParsePlatform/parse-server#2918]
am not able to pass more than 10 pointer object in containedIn using dotnet c#

below query am using to get details,
var objHotelPrice = await ParseObject.GetQuery("classnameDetails")
                    .WhereContainedIn("Hotelpointer", objectsHotelsDetails)
                    .WhereGreaterThanOrEqualTo("Checkin", checkin).WhereLessThanOrEqualTo("Checkout", checkout).Limit(1000).FindAsync();

if i pass more than 10 array of pointer object to "Hotelpointer"  field am getting following 
error:
An exception of type 'Parse.ParseException' occurred in mscorlib.dll but was not handled in user code

Additional information: "Invalid response from server"

**Comment by bohemima** [comment]
Run the server with VERBOSE logging and paste whatever the server has to say about it here to help debugging.

**Comment by hramos** [comment]
This sounds like a Parse dotNET SDK issue, unrelated to Parse Server.

**Comment by ramukallepalli** [comment]
IIS configuration issue.
Setting "maxQueryString" to higher value resolved the issue.
