### ISSUE TITLE
request.user is "undefined" in the "beforeSave" function in the Cloud code

### ISSUE THREAD

**Issue by grassland-curing-cfa** [ParsePlatform/parse-server#2929]
In my ParseServer migrated into the Heroko + mLab stack,

I have a beforeSave function set for a custom "OBSERVATION" Class as below.

```
Parse.Cloud.beforeSave("OBSERVATION", function(request, response) {
    ... ...
    var currUser = request.user;
    console.log(request);
    console.log("*** User objectId: " + currUser.id + "; " + currUser.getSessionToken());
    ... ...
});
```

I want to get the user name triggering the Save event. According to the Parse JavaScript SDK Reference, a "BeforeSaveRequest" takes a <Parse.User> as a member, which represents the User triggering the "Save" event.

However, this is always "undefined" for me. Is there anything I missed or did wrong?

**Comment by flovilmart** [comment]
Can you please reopen the issue with the complete issue template filled?
