### ISSUE TITLE
Cloud Function Calling results in "JSON text did not start with array or object" Error

### ISSUE THREAD

**Issue by georgesjam** [ParsePlatform/parse-server#2936]
When i try to call Cloud Function from iOS
`[PFCloud callFunctionInBackground:@"test" withParameters:@{} block:^(id object, NSError* error){
    }];`

I get this error 
`Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}`
even if the cloud function being called does not exist.

The Cloud Function that i am calling is simple :
`Parse.Cloud.define('test', function (request, response) {
     response.error('This is a test error message');
});`

Running ParseSDK **Version 1.14.2** on iOS (latest)
Running Parse-Server **Version 2.2.23** (latest) on Heroku

Other actions on iOS like saving and retrieving objects works fine.
Also i am successfully being able to add and delete object using /dashboard from
the web browser, so it shouldn't be a server problem since everything works fine.

**Comment by flovilmart** [comment]
Does it work when your return an object instead of a string?

**Comment by georgesjam** [comment]
Figured it out. 
It turned out that there was a problem with a cloud code functions that was miswritten
and somehow resulted in this error.
I fixed the function and everything is working now.

Closing this issue ...

**Comment by irfanabdulkhaliq** [comment]
what wass error
