### ISSUE TITLE
Suggestion: before/after get triggers

### ISSUE THREAD

**Issue by jonas-db** [ParsePlatform/parse-server#2937]
Hello, 

what follows is a suggestion to introduce a "before/after get trigger" in the cloud code and is backed up by the following use case:

Assume that we want to know the amount of views of a blog post, so everytime a blog post is fetched with a GET request, the amount of views should be updated.

If i'm correct, there are two ways to solve this problem:

- create a cloud function, which you call instead of querying a collection
- after the fetch request, save the object again with the counter increased

While the first one is acceptable, the second is not. Although, I think the cloud code is meant for custom code and does not support a way to simulate the after get trigger, but only the before get trigger. Also in terms of consistency, I want to create normal queries and not call some custom function, which is why I propose the suggestion of before/after triggers of get requests. This is similar to the exisiting triggers and provides a uniform way to have triggers for GET/POST/DELETE requests.

Remarks/thoughts/use cases?

**Comment by natanrolnik** [comment]
@jonas-db have you seen the 2.2.20 release notes? @flovilmart added a `beforeFind` handler, so I think that's pretty much what you need: https://github.com/ParsePlatform/parse-server/blob/master/CHANGELOG.md#2220

**Comment by jonas-db** [comment]
@natanrolnik Indeed, I didn't see it. That solves the problem, thanks. I'm not sure if there are actual use cases for the "afterFind", so I will let this open to further discuss, and if not this can be closed.

**Comment by natanrolnik** [comment]
Discussions are being moved to [Parse-Evolution](https://github.com/parse-server-modules/parse-evolution). Please close here and open a proposal there.
