### ISSUE TITLE
afterDelete hook (on about to be deleted object) not being called from afterDelete hook?

### ISSUE THREAD

**Issue by maqen** [ParsePlatform/parse-server#2939]
I get code that deletes a child object on afterDelete

I also have a hook for afterDelete on the _child_ for a _child child_ but that don't seems to be called?

```javascript
Parse.Cloud.afterDelete('Grandparent', (request) => {
  var query = new Parse.Query('Parent');
  query.equalTo('grandparent', request.object.id);
  query.find().then((parents) => {
    return Parse.Object.destroyAll(parents, {useMasterKey: true});
  }).then(() => console.log('Removed all parents'));
});

Parse.Cloud.afterDelete('Parent', (request) => {
  var query = new Parse.Query('Child');
  query.equalTo('parent', request.object.id);
  query.find().then((children) => {
    return Parse.Object.destroyAll(children, {useMasterKey: true});
  }).then(() => console.log('Removed all children'));
});
```

_Removed all children_ will never be called?

**Comment by flovilmart** [comment]
Seems that you are using the wrong variable. `parents` vs `connectors`

**Comment by maqen** [comment]
@flovilmart thanks for spotting the example typo

Looking through logs there are not actual calls for **DELETE** on _Child_ only _Parent_

**Comment by flovilmart** [comment]
how are you monitoring the logs? on a local server? output of you process?

**Comment by maqen** [comment]
Local server using `verbose` in setting up `ParseServer`

**Comment by flovilmart** [comment]
can you provide the full logs of this transaction? (

**Comment by maqen** [comment]
So my error was passing `request.object.id` instead of `request.object` as this is a _pointer_ field

Sorry for the inconvenience and thanks @flovilmart for trying to help out
