### ISSUE TITLE
Current Best Practice Versions to Support Parse Server?

### ISSUE THREAD

**Issue by adonoho** [ParsePlatform/parse-server#2940]
Many Parse developers are not node.js or JavaScript developers. Hence, a list of the preferred deployment versions is useful. Specifically, this is not a minimum required version list.

In my case, my cloud code changed very rarely. As a result, I want to buy into the highest long term support versions of each component possible. This will, hopefully, provide me with the lowest server churn possible. I think other Parse developers have similar goals to mine. Hence, what are those versions?

Here is the result of my research:
Node.js: latest:boron == v6.9.1
MongoDB: v3.2.10
express.js: v4.14.0
Parse SDK: v1.9.2
Parse Server: v2.2.23
Kerberos: v0.0.21

Please check the above list for freshness. Thank you.

Anon,
Andrew

P.S. BTW, I am always nervous when I see large unrelated crypto libraries brought into projects. What is Kerberos doing in the above list? (I put it there because parse-server-example has it.) If Parse Server only uses a small part of it, for say, bcrypt, then perhaps we should just get a smaller library?

**Comment by flovilmart** [comment]
Kerberos is part of mongodb. 

You should always run the latest known stable version of the modules. 

ON parse-server we fix the dependencies to make sure we don't introduce a breaking change through a 3rd party dependency. Pinning your dependencies is up to you. 

As we try to release a new version every two weeks, you check for the changelogs, and update your setup accordingly. Bug fixes occur frequently, and stability/performance improvements are also pushed on every releases.

**Comment by adonoho** [comment]
Thank you. 

It is a good operational practice to pin the versions of one's production servers. In my experience, I update production servers for security fixes or newly needed features.

Reading the above tells me I can drop Kerberos from my package.json.  If MongoDB needs it, it can specify it. Do you want a pull request against parse-server-example?

As of today, current stable releases are:
Node.js: latest:boron == v6.9.1
MongoDB: v3.2.10
express.js: v4.14.0
Parse JS SDK: v1.9.2
Parse Server: v2.2.23

**Comment by flovilmart** [comment]
If you wish.
