### ISSUE TITLE
Experiencing a significant performance problem

### ISSUE THREAD

**Issue by alexblack** [ParsePlatform/parse-server#2943]
Hi, we'll look at posting some more thorough steps to reproduce and details, but, right now we're experiencing some major issues, and any insights or suggestions would be helpful.

It looks like an update in our mobile app is causing a lot more requests to hit our parse-server, and our deployment at Heroku is not standing up, requests are taking 30s to respond.

New relic analysis seems to indicate that 80% of the time is spent in [handleParseHeaders](https://github.com/ParsePlatform/parse-server/blob/ad707457be13f177e4a0dc481c990ddbd2df8d80/src/middlewares.js#L14)

We're also seeing more errors than normal out of one of our cloud functions, a `beforeSave` trigger.  We are working change things in our app to minimize this, but, in the meantime we're still in bad spot.

Details:
1. Parse-server `2.2.23` (also tried rolling back to `2.2.22`, no change)
2. Database is Mongo, at mLab, no visible change in metrics there, it looks good to me
3. Deployed at Heroku, on (4) 2x dynos
4. Using node express

![screenshot 2016-10-26 11 47 00](https://cloud.githubusercontent.com/assets/148930/19740047/17530478-9b72-11e6-9ddd-4d972be9bd90.png)

**Comment by alexblack** [comment]
![screen_shot_2016-10-27_at_7 49 58_am](https://cloud.githubusercontent.com/assets/148930/19740164/8ad9df5c-9b72-11e6-868e-f1eab611a18f.png)

**Comment by flovilmart** [comment]
Looks like it's stalling on your mongodb command, Not sure how it's related to parse-server's code. That is likely to be a deployment scaling problem. Look at your indexes, slow queries, mongodb configurations etc... 

Not sure how we can help you fix that. Not sure either there is anything to fix in parse-server.

**Comment by alexblack** [comment]
Thanks for the input, we'll look at Mongo!

**Comment by alexblack** [comment]
Thanks for the fast response @flovilmart , very helpful. 👍

**Comment by alexblack** [comment]
It *was* mongo, we added an index to a new class we'd created, and the problem has gone away.

**Comment by flovilmart** [comment]
As expected
