### ISSUE TITLE
self hosted migrated to self hosted

### ISSUE THREAD

**Issue by jeffreyjackson** [ParsePlatform/parse-server#2950]
Looking to create a development instance of a self hosted parse server in production.  Are there any methods or tools to assist in this?  Also interested in export/import of objects

**Comment by flovilmart** [comment]
To import/export objects for dev instances, you better use a mongodump, or the mongo Interface. Going through thé SDK would ultimately regenerate new objectId.

Then running a développement instance is pretty much the same as a production one, just use a separate database.

**Comment by apersaud** [comment]
If you are interested in migrating your Parse files from the hosted platform to your S3 bucket, we have made a tool we have finished using publicly available: https://github.com/modernistik/parse-file-migration .

Hope it helps.
