### ISSUE TITLE
Advice on memory when running Parse Server inside a container?

### ISSUE THREAD

**Issue by AndrewLane** [ParsePlatform/parse-server#2973]
Sorry if an issue wasn't the appropriate place to ask this, but I couldn't think of anything better.  We are targeting running Parse Server in a Docker container, specifically with AWS's Elastic Beanstalk.  In that configuration we need to configure the max memory for the container (specifically, ```containerDefinitions.memory``` in our ```Dockerrun.aws.json``` file).  Any recommendation for what to set that value to in PROD?  1GB plenty?  Or does it depend on the workload?

**Comment by flovilmart** [comment]
1Gb should be plenty, the parse-server should take about 200/250Mb of RAM. If you see RAM spikes (above 700Mb), you should probably recycle the server

**Comment by alexblack** [comment]
Here's what our memory usage looks like over the last 72 hours on Heroku.  We're running (4) 2x dynos (1gb ram).  Heroku restarts dynos every 24 hours afaik.

<img width="1234" alt="screenshot 2016-11-02 11 30 57" src="https://cloud.githubusercontent.com/assets/148930/19942120/db93e74e-a0ef-11e6-8fe0-801f62eba7dc.png">

**Comment by noder199** [comment]
Why does the RAM usage vary so much? Because of cache? Will parse-server crash if not enough RAM is granted for things like caching or will it simply slow down/cache less?

**Comment by alexblack** [comment]
I think the RAM usage of our instances vary based on usage, we have peak usage times in our app.
