### ISSUE TITLE
Crypto module on api.parse.com generates different values

### ISSUE THREAD

**Issue by doender** [ParsePlatform/parse-server#2978]
On api.parse.com, I use the following code to generate a hash:

```
crypto.pbkdf2Sync(secret, salt, 100, 16, 'sha512').toString('hex');
```

Somehow these values are different on our server using parse-server. Does anybody know what version of `crypto` api.parse.com uses?

**Comment by flovilmart** [comment]
Did you find your answer?

**Comment by doender** [comment]
@flovilmart Yep, somehow api.parse.com is using an outdated version of the crypto library and the digest algorithm is hardcoded to `sha1` (so the parameter in the code above doesn't do anything). When we changed `sha512` to `sha1` in our new cloud code everything worked again. Luckily the security risks for these generated hashes aren't too high...
