### ISSUE TITLE
Question: Multiple DB Functions (PostGis->MongoDb)?

### ISSUE THREAD

**Issue by nitrag** [ParsePlatform/parse-server#298]
Hi Folks, before now this wasn't possible and I had to have two databases/servers/APIs. One for Parse and one for my PostGis server.

My PostGis stuff is very small (25mb) and I can't see it ever growing over 500mb. I think MongoDB supports GIS functions? What if I wanted to store the data in Parse's MongoDB? Would it play well together? Could I restructure the PostGis tables as a Parse class but have an additional field for the geometry? I don't need to access the geometry from Parse but it would be very helpful to maintain/access the other fields/columns instead of managing the same data two places.

Please tell me which options are possible:
1. Store the data in MongoDB in it's own table (only need to manage one database)
2. Store the data in MongoDB as a Parse Class + have Parse SDK's be able to read/write all fields except geometry

I understand I'll have to rewrite my Django Postgis API to read MongoDB table.

**Comment by drew-gross** [comment]
Those are both possible however MongoDB's support for geometry queries is only OK, and certainly not as good as PostGIS. I'd recommend checking if your queries will be possible and performant in MongoDB before investing in a migration off of PostGIS.

**Comment by nitrag** [comment]
@drew-gross Thanks Drew! Really appreciate the guidance.
