### ISSUE TITLE
Batch request error when trying to delete one or many Parse objects

### ISSUE THREAD

**Issue by fcoufour** [ParsePlatform/parse-server#2980]
With a reverse proxy configuration, deleting one or many rows of Parse object throws an exception

### Steps to reproduce

1. Select one or many rows to delete on Parse Dashboard
2. Click "Edit"
3. Click "Delete this / these row(s)"

This can also be reproduced doing the resulting batch request:

curl 'https://api.mydomain.com/batch' --data-binary '{"requests":[{"method":"DELETE","path":"/classes/\<className\>/\<objectId\>","body":{}}],"_ApplicationId":"\<APPLICATION_ID\>","_MasterKey":"\<MASTER_KEY\>"'

#### Expected Results

Object deleted / batch response 200 OK

#### Actual Outcome

Object NOT deleted / batch response 400 Bad Request

### Environment Setup

- **Server**
  - parse-dashboard version: 1.0.19
  - parse-server version: 2.2.24
  - Operating System: Ubuntu Server 
  - Hardware: 1 Core CPU / 512MB RAM
  - Localhost or remote server?: Digital Ocean

- **Database**
  - MongoDB version: 3.2.10
  - Storage engine: MongoRocks
  - Hardware: the same
  - Localhost or remote server?: Digital Ocean

**Important: I use Nginx as a reverse proxy**
- Parse Dashboard: https://dashboard.mydomain.com --> http://localhost:4040/
- Parse Server: https://api.mydomain.com --> http://localhost:1337/parse

### Logs/Trace

The content of the response to the POST https://api.mydomain.com/batch request is the following: {"code":107,"error":"cannot route batch path /classes/\<className\>/\<objectId\>"}.

The value of some of the batch.js file variables are in my case:
- apiPrefixLength=6
- apiPrefix=/parse
- req.originalUrl=/parse/batch
- batchPath=/batch
- restRequest.path=/classes/\<className\>/\<objectId\>

The exception is thrown because of restRequest.path.slice(0, apiPrefixLength) != apiPrefix (line 34).

When I manually modify the batch subrequest to change the path accordingly, it works as expected:

    "requests": [
        {
            "method": "DELETE",
            "path": "/parse/classes/<className>/<objectId>",
            "body": {}
        }
    ]

_Does the current batch.js implementation is supposed to work with a reverse proxy configuration?
If yes, do I have to set a particular option or an environment variable for Parse Server or Parse Dashboard?_

**Comment by flovilmart** [comment]
What did you set as serverURL in your configuration?

**Comment by fcoufour** [comment]
Hey Florent! No serverURL and it doesn't seem to make any difference regarding the batch requests if I set one to the localhost URL (http://localhost:1337/parse).

**Comment by flovilmart** [comment]
Yeah, the issue is that your public server URL ( https://api.mydomain.com) doesn't 'need' a path to access the parse-server. Two options for you here in the meantime:

1. make parse-server available on https://api.mydomain.com/parse instead of /
2. make the local server listen on '/' so you have https://api.mydomain.com/ -> http://localhost:1337/

We'll see if we can apply a clean fix for that.

**Comment by fcoufour** [comment]
Thanks Florent. I had those 2 possibilities in mind as well.
Are the serverURL or publicServerURL config options not supposed to be used for such internal requests?

**Comment by flovilmart** [comment]
publicServerURL is when you need to send email, or generate links for the files.
serverURL is for internal calls. What you have now, is problematic as the paths don't match between the public and the private.

**Comment by fcoufour** [comment]
I chose option number 2 as temporary solution and no surprises, batch requests are now working well in Parse Dashboard.

serverURL is not crystal clear for me. What is considered as internal calls?
Does it take a default value because this is not a requirement according to the readme? On the other hand, in the ParseServer.js file, we're supposed to supply a value:
`serverURL = requiredParameter('You must provide a serverURL!'),`

**Comment by flovilmart** [comment]
> serverURL is not crystal clear for me.

Is used for communication between cloud code and parse-server, this provides the loopback as cloud code is using HTTP to communicate with parse-server, and is not making direct calls in the code.

**Comment by flovilmart** [comment]
In your case, providing serverURL and publicServerURL won't help much as, serverURL would be:

`http://localhost:1337/parse` and publicServerURL would be`https://api.mydomain.com`. 

The dashboard is generating the batch request with paths as building a request to `https://api.mydomain.com`, we could use the publicServerURL if set, in order to see what URL we should route to, but that seems dangerous.
