### ISSUE TITLE
100% of The Requests Are Erroring with HTTP 4xx

### ISSUE THREAD

**Issue by JunJia** [ParsePlatform/parse-server#2987]
I have met with an issue that the server have 100% of the requests erroring with HTTP 4xx once we released the new application to public which switched the server from Parse hosted to AWS hosted.

I have ParseServer installed on AWS Elastic Beanstalk and data migrated to mLab.

### Environment Setup

- **Server**
  - parse-server version : 1.13.1
  - Operating System: 64bit Amazon Linux 2016.03 v2.1.3 running Node.js
  - Hardware: t2.medium
  - Localhost or remote server? : AWS

- **Database**
  - MongoDB version: 3.0.11
  - Storage engine:  SSD block storage 300GB
  - Hardware: RAM 7.5GB, 
  - Localhost or remote server? : mLab

### Logs/Trace

In log/nginx/access.log

172.31.58.102 - - [25/Oct/2016:02:29:59 +0000] "POST /parse/classes/PlannerDataSource HTTP/1.1" 400 44 "-" "Parse Android SDK 1.13.1 (com.appxy.planner/35) API Level 23" "147.4.36.65"

There are full of such above kind of messages in the log file.

In log/nginx/error.log

2016/10/28 01:28:22 [error] 3841#0: *15291429 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.31.56.205, server: , request: "POST /parse/classes/PlannerDataSource HTTP/1.1", upstream: "http://127.0.0.1:8081/parse/classes/PlannerDataSource", host: "plannerpro-master.us-east-1.elasticbeanstalk.com"
2016/10/28 01:28:22 [error] 3840#0: *15283650 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.31.13.185, server: , request: "POST /parse/classes/PlannerDataSource HTTP/1.1", upstream: "http://127.0.0.1:8081/parse/classes/PlannerDataSource", host: "plannerpro-master.us-east-1.elasticbeanstalk.com"

There are two kinds of error 3840 and 3841 appear in the error.log. I searched for these errors through all the closed issues and find there a solution for cloud code syntax error, but we do not use any cloud code. The only js file existing is the default main.js which prints 'hi'. 

Any solution for this?

**Comment by hramos** [comment]
I'm afraid provider-specific deployment issues are out of scope for GitHub.
