### ISSUE TITLE
Parse Server & ParseTwitterUtils

### ISSUE THREAD

**Issue by talkaboutdesign** [ParsePlatform/parse-server#299]
Will this continue to work once I migrate to parse server?

**Comment by ay8s** [comment]
As far as I'm aware this is being worked on within https://github.com/ParsePlatform/parse-server/pull/247 and should be backwards compatible while opening it up to other OAuth providers.

**Comment by flovilmart** [comment]
@ay8s yes, it's fully working under the current unit tests that cover login, linking under the current API as well as the REST calls, pending a review and a merge

**Comment by drew-gross** [comment]
The PR that implements Generic OAuth has been merged and will be available in the next release.
