### ISSUE TITLE
web aplication page content of logged in users mixed up with another logged in user

### ISSUE THREAD

**Issue by highelf** [ParsePlatform/parse-server#2990]
page content of logged in users mixed up with another logged in user

### Environment Setup

- **Server**
aws ec2 instance
nginx as proxy  
pm2 started index.js  
expressjs website  
below library for my project
"aws-ses-mail": "^2.1.1",
"body-parser": "^1.15.2",
"cookie-parser": "^1.4.3",
"ejs": "^1.0.0",
"express": "~4.11.x",
"express-ejs-layouts": "^2.2.0",
"express-session": "^1.14.1",
"kerberos": "~0.0.x",
"mandrill": "^0.1.0",
"moment": "^2.14.1",
"parse": "~1.8.0",
"passport": "^0.3.2",
"passport-parse": "0.0.5",
"underscore": "^1.8.3"

**Comment by flovilmart** [comment]
do you use Parse.User.current() ?

**Comment by highelf** [comment]
No , I use passport and save token in paspport session

**Comment by flovilmart** [comment]
That's unrelated to parse. Server, if seems the culprit would be passport-Parse. For implementation related questions please use stackoverflow.
