### ISSUE TITLE
Running an express server from within cloud code

### ISSUE THREAD

**Issue by mrnocreativity** [ParsePlatform/parse-server#2993]
In Parse.com I have several apps that start an express server from within the cloud code. In those express routes, I can get to the request.user object upon every page request.

With the new setup for Parse Server, the express server runs fully independent from the Parse server and the Parse API is served as middleware from a endpoint in the express server. That removes the possibility to capture the request.user. So forcing 'logged in' sessions seems to no longer be possible from a simple webpage request.

I have been trying to move things around but I seem to be unable to make this work.
Is this no longer possible? 
I just don't want to be dependent on client-side JS to make my app work. I'd like to use the Parse Server as my core backend and generate complete pages.

Am I overlooking a way of getting the request.user from an express request? Or am I doing something wrong when setting up cloud code from the parse server?

**Comment by ronaldo-getreveel** [comment]
Hi @mrnocreativity . 

I think you are looking to the same solution as I'm. 
Check this issue #2985

**Comment by mrnocreativity** [comment]
Hi @ronaldo-getreveel,

That looks exactly to be the solution, however, I hoped to be able to rely on the Parse Internals to do this by itself (like it did when the express server was hosted in the cloude code running on old parse.com).

I guess this will be it then :)
Thanks!

**Comment by mi3e** [comment]
Have an express middleware function that grabs the x-parse-session-token header from the request.
Then have it do a get request to https://your-parse-server-url.com/users/me with the same x-parse-session-token header. 
If the session is valid (checks user is logged on, not expired etc etc) you'll get back a 200 and the user object in the response which can be parsed into an object using Parse.Object.fromJSON(response.body);
