### ISSUE TITLE
Basic Auth

### ISSUE THREAD

**Issue by greggmojica** [ParsePlatform/parse-server#2997]
Hello,
I tried adding Http basic auth (username and password) on my server but immediately when I did so I got the following errors. Does anyone know a workaround to this?

Failed to load resource: the server responded with a status of 504 (GATEWAY_TIMEOUT)
parse.js:15 POST https://xxxxx.xxxxxxxxx.com/parse/functions/xxxxxxxx 504 (GATEWAY_TIMEOUT)c @ parse.js:15

**Comment by flovilmart** [comment]
Can you please re-open an issue with the issue template filled up completely?
