### ISSUE TITLE
Add Web Dashboard

### ISSUE THREAD

**Issue by markrey** [ParsePlatform/parse-server#3]
Would it be possible for Parse team to Opeansource WebUI component ? 
Or publish concept diagram on how it should be working so community can build one ?

It is very difficult to manage / edit data ( which was one of the core competency of Parse ) and to create authorization over data.

**Comment by laurentf** [comment]
Completely agree about the UI component, would be really nice and would make the migration easier!

**Comment by nunuh89** [comment]
that'd be really nice.

**Comment by sethx** [comment]
+1 to that!

**Comment by gfosco** [comment]
We're going to work on that, totally agree it is super valuable.   For the time being, you can create an app on Parse with your mongo connection string and continue to use the Parse.com dashboard.

**Comment by sunshineo** [comment]
+1

**Comment by kevinjpetersen** [comment]
+1

**Comment by fishead1116** [comment]
+1

**Comment by vandersongold** [comment]
+1

**Comment by chanil1218** [comment]
+1
I do love with Parse's dashboard so far!
I will sincerely hope for it.

**Comment by flavionegrao** [comment]
+1

**Comment by cdiscrete** [comment]
+1

**Comment by yuki-takeichi** [comment]
+1

**Comment by visualsayed** [comment]
+1

**Comment by timtutt** [comment]
+1

**Comment by jaysonng** [comment]
Once WebUI is available, someone should develop inline uploading of files/photos.

Glad to know Parse is working on it. :+1:

**Comment by meilers** [comment]
+1

**Comment by Harsha93** [comment]
+1

**Comment by flessard** [comment]
+1

**Comment by thanhliem89dn** [comment]
+1

**Comment by haranicle** [comment]
+1

**Comment by tugusuke** [comment]
+!

**Comment by kiyotakagoto** [comment]
+1

**Comment by kyokutyo** [comment]
+1

**Comment by tetsuyanh** [comment]
+1

**Comment by hiroyuki-seto** [comment]
+1

**Comment by wahkiz** [comment]
+1

**Comment by travistrue2008** [comment]
+1

**Comment by kingmatusevich** [comment]
+1

**Comment by songnob** [comment]
+1

**Comment by bacrossland** [comment]
:+1:

**Comment by mikevilla** [comment]
🙏

**Comment by chavanshashank** [comment]
+1

**Comment by shahabhameed** [comment]
+1

**Comment by gfosco** [comment]
Locking this for now, it's something we are trying to do.

**Comment by drew-gross** [comment]
https://github.com/ParsePlatform/parse-dashboard
