### ISSUE TITLE
Parse.User.logIn only works with {useMasterKey: true} as option

### ISSUE THREAD

**Issue by Tibabal** [ParsePlatform/parse-server#300]
Hi,

When using `Parse.User.logIn(username, password)` I get 

`error: ParseError {
  code: 141,
  message: ParseError { code: undefined, message: 'unauthorized' } }`

using VERBOSE=1.

To get it to work, I need to use  `Parse.User.logIn(username, password, {useMasterKey : true})` which wasn't the case using CloudCode. It doesn't seem to make sens neither to need to use the master key in order to be able to login.

**Comment by maysale01** [comment]
Working for me using the REST API. Which SDK are you using and can you run a logger on your server to see the request headers and body?

**Comment by Tibabal** [comment]
I just wrote a sample method to test this:

```
Parse.Cloud.define("testLogin", function(request, response)
{
    var login = "login";
    var password = "password";

    var user = new Parse.User();
    user.setUsername(login);
    user.setPassword(password);

    return user.save().then(function(savedUser)
    {
        console.log("User saved, trying to login");
        return Parse.User.logIn(login, password)
    }).then(function(user)
    {
        console.log("User logged with token "+user.getSessionToken());
        return user.destroy();
    }).then(function()
    {
        response.success();
    }, function(error)
    {
        console.error("Error login :"+JSON.stringify(error));
        return user.destroy().then(function(){
            response.error(error);
        });
    });
});
```

Output:

```
POST /parse/functions/testLogin { host: 'hostname:port,
  'x-parse-client-version': 'i1.12.0',
  accept: '*/*',
  'x-parse-application-id': 'my application ID',
  'x-parse-client-key': 'my client key,
  'x-parse-installation-id': 'my installation ID',
  'accept-language': 'fr-fr',
  'x-parse-os-version': '9.2 (15B42)',
  'accept-encoding': 'gzip, deflate',
  'content-type': 'application/json; charset=utf-8',
  'content-length': '2',
  'user-agent': 'my client agent',
  connection: 'keep-alive',
  'x-parse-app-build-version': '4',
  'x-parse-app-display-version': '1.0' } {}

User saved, trying to login
Error login :{"message":"unauthorized"}
```

**Comment by ktmatzdorf** [comment]
You have to call before
`Parse.Cloud.useMasterKey()`

**Comment by Tibabal** [comment]
@ktmatzdorf Parse.Cloud.useMasterKey() mustn't be used with Parse-Server as it modifies global variables and can lead to unpredictable result such as the master key being used in another undesired method call.
Furthermore, the issue is during the Parse.User.logIn, which doesn't has to be used with the masterKey.
