### ISSUE TITLE
Repeated updates to the same "object-type" field don't always succeed

### ISSUE THREAD

**Issue by wookiem** [ParsePlatform/parse-server#3004]
### Issue Description

Repeated updates to the same "object-type" field within the same Parse object does not always result in actual updates to the Parse database.  

Parse server logs always show success, however direct observation of database (either using parse-dashboard or inspecting database records at mlabs) show that this is not true.

### Steps to reproduce

1. Run React code below
2. Click on "Save Object to Parse"
3. Observe verbose output from parse-server (see logs)
4. Confirm whether update recorded in Parse database using parse-dashboard
5. Repeat steps 2 - 4 three more times

```
`import React, { Component } from 'react';
import {render} from 'react-dom';
import Parse from 'parse';

var objectIndex = 0;
var objectArray = [
		{
			"color": "Green", 
			"selection": {value: "tint",label: "One"}
    },
		{
			"color": "Green", 
			"selection": {value: "tint",label: "Two"}
    },  	
		{
			"color": "Green", 
			"selection": {value: "tint",label: "Three"}
    },  	
		{
			"color": "Green", 
			"selection": {value: "tint",label: "Four"}
    }
];

export default class App extends Component {

  saveToParse() {
  	let Item = Parse.Object.extend("Item");
		let item = new Item();
		
  	item.id = 'Q8t0uSnvKn';
		item.set('description', objectArray[objectIndex], {
			error: function(description, error) {
				console.log("error: ", error);
			}
		});
		objectIndex++;
		
		item.save(null, {
			sessionToken: "r:5103b1fe3dd6f96b89a33fb902936d2e",
			success: function(item) {
				console.log("success");
			},
			error: function(item, error) {
				console.log("error");
			}
		});
  }
	
  render() {
  	 	
    return (
    	<div onClick={this.saveToParse}>
  	    Save Object to Parse
			</div>
    );
  }
}`
```

#### Expected Results

1. Pass 1:  expect "Item" field to contain {"color": "Green", "selection": {value: "tint",label: "One"}}
2. Pass 2: expect "Item" field to contain {"color": "Green", "selection": {value: "tint",label: "Two"}}
3. Pass 3: expect "Item" field to contain {"color": "Green", "selection": {value: "tint",label: "Three"}}
4. Pass 4: expect "Item" field to contain {"color": "Green", "selection": {value: "tint",label: "Four"}}

#### Actual Outcome

1. Pass 1:  expect "Item" field to contain {"color":"Green","selection":{"value":"tint","label":"One"}}
2. Pass 2: expect "Item" field to contain {"color":"Green","selection":{"value":"tint","label":"Two"}}
3. Pass 3: expect "Item" field to contain {"color":"Green","selection":{"value":"tint","label":"Three"}}
4. Pass 4: expect "Item" field to contain {"color":"Green","selection":{"value":"tint","label":"Three"}}

Note: Repeated runs will result in different outcomes

### Environment Setup

- **Server**
  - parse-server version: 2.2.24 (also confirmed same behavior with 2.2.22 and 2.2.14)
  - Operating System: MAC OS 10.11.6
  - Hardware: iMac (21.5-inch, Mid 2011)
  - Localhost or remote server? Localhost

- **Database**
  - MongoDB version: 3.2.9
  - Storage engine:  Unknown
  - Hardware:        mlab Sandbox plan
  - Localhost or remote server? mLab

### Logs/Trace

verbose: REQUEST for [PUT] /parse/classes/Item/Q8t0uSnvKn: {
  "description": {
    "color": "Green",
    "selection": {
      "value": "tint",
      "label": "One"
    }
  }
} method=PUT, url=/parse/classes/Item/Q8t0uSnvKn, host=192.168.0.16:1337, connection=keep-alive, content-length=259, origin=http://localhost:3002, user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36, content-type=text/plain, accept=*/*, referer=http://localhost:3002/, accept-encoding=gzip, deflate, accept-language=en-US,en;q=0.8, color=Green, value=tint, label=One
verbose: RESPONSE from [PUT] /parse/classes/Item/Q8t0uSnvKn: {
  "response": {
    "updatedAt": "2016-11-03T18:09:48.563Z"
  }
} updatedAt=2016-11-03T18:09:48.563Z

verbose: REQUEST for [PUT] /parse/classes/Item/Q8t0uSnvKn: {
  "description": {
    "color": "Green",
    "selection": {
      "value": "tint",
      "label": "Two"
    }
  }
} method=PUT, url=/parse/classes/Item/Q8t0uSnvKn, host=localhost:1337, connection=keep-alive, content-length=263, origin=http://0.0.0.0:4040, user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36, content-type=text/plain, accept=*/*, referer=http://0.0.0.0:4040/apps/idpractice/browser/Item, accept-encoding=gzip, deflate, br, accept-language=en-US,en;q=0.8, color=Green, value=tint, label=Two
verbose: RESPONSE from [PUT] /parse/classes/Item/Q8t0uSnvKn: {
  "response": {
    "updatedAt": "2016-11-03T18:15:48.576Z"
  }
} updatedAt=2016-11-03T18:15:48.576Z

verbose: REQUEST for [PUT] /parse/classes/Item/Q8t0uSnvKn: {
  "description": {
    "color": "Green",
    "selection": {
      "value": "tint",
      "label": "Three"
    }
  }
} method=PUT, url=/parse/classes/Item/Q8t0uSnvKn, host=192.168.0.16:1337, connection=keep-alive, content-length=261, origin=http://localhost:3002, user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36, content-type=text/plain, accept=*/*, referer=http://localhost:3002/, accept-encoding=gzip, deflate, accept-language=en-US,en;q=0.8, color=Green, value=tint, label=Three
verbose: RESPONSE from [PUT] /parse/classes/Item/Q8t0uSnvKn: {
  "response": {
    "updatedAt": "2016-11-03T18:17:41.611Z"
  }
} updatedAt=2016-11-03T18:17:41.611Z

verbose: REQUEST for [PUT] /parse/classes/Item/Q8t0uSnvKn: {
  "description": {
    "color": "Green",
    "selection": {
      "value": "tint",
      "label": "Four"
    }
  }
} method=PUT, url=/parse/classes/Item/Q8t0uSnvKn, host=192.168.0.16:1337, connection=keep-alive, content-length=260, origin=http://localhost:3002, user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36, content-type=text/plain, accept=*/*, referer=http://localhost:3002/, accept-encoding=gzip, deflate, accept-language=en-US,en;q=0.8, color=Green, value=tint, label=Four
verbose: RESPONSE from [PUT] /parse/classes/Item/Q8t0uSnvKn: {
  "response": {
    "updatedAt": "2016-11-03T18:18:29.394Z"
  }
} updatedAt=2016-11-03T18:18:29.394Z

**Comment by steven-supersolid** [comment]
Can you turn on database profiling with `db.setProfilingLevel(2)`, then do `db.system.profile.find()` afterwards as that will show what is getting stored? You will need shell access to the database.

**Comment by wookiem** [comment]
@steven-supersolid here's the captured log file:

[db_log.txt](https://github.com/ParsePlatform/parse-server/files/570382/db_log.txt)

**Comment by wookiem** [comment]
I found the source of the issue...  I use parse-dashboard to verify updates by double-clicking on the field in question.  This puts parse-dashboard in "edit cell" mode.  If I then go back to my app and trigger the next update, without first exiting "edit cell" mode, then when I click on "refresh" in parse-dashboard, it auto-saves the contents of the "edit cell" before retrieving the contents of the field from the database.  

I'm marking this issue as closed.

**Comment by wookiem** [comment]
I found the source of the issue...  I use parse-dashboard to verify updates by double-clicking on the field in question.  This puts parse-dashboard in "edit cell" mode.  If I then go back to my app and trigger the next update, without first exiting "edit cell" mode, then when I click on "refresh" in parse-dashboard, it auto-saves the contents of the "edit cell" before retrieving the contents of the field from the database.  

I'm marking this issue as closed.

**Comment by wookiem** [comment]
I found the source of the issue...  I use parse-dashboard to verify updates by double-clicking on the field in question.  This puts parse-dashboard in "edit cell" mode.  If I then go back to my app and trigger the next update, without first exiting "edit cell" mode, then when I click on "refresh" in parse-dashboard, it auto-saves the contents of the "edit cell" before retrieving the contents of the field from the database.  

I'm marking this issue as closed.

**Comment by steven-supersolid** [comment]
Ah that might be a bug in parse-dashboard. If you have time, would you mind trying with parse.com on the old dashboard and beta dashboard and opening a bug on parse-dashboard if the behaviour doesn't match?

It seems really wrong to be doing that to me.

**Comment by wookiem** [comment]
Ok, just played around with parse.com...

Both parse.com's dashboard and parse-dashboard will auto-save a field under edit upon clicking on the refresh button.   

However, parse.com's dashboard differs from parse-dashboard in that it will auto-save when you focus on a different browser tab or on a different MacOS application.  In the case of parse-dashboard, you remain in "edit cell" mode.

In my specific scenario, I would not have had this issue if I were using parse.com's dashboard since the act of switching to another browser tab (I was debugging iOS simulator in a separate chrome browser tab) would have exited "edit cell" mode. 

I'll submit an issue on parse-dashboard to request changing behavior to follow parse.com in this regard.

**Comment by steven-supersolid** [comment]
Great, thanks for taking the time to investigate :)

BTW, did you try the old dashboard on parse.com or the new/beta one? I've noticed that the beta one has some of the same bugs as parse-dashboard.

**Comment by wookiem** [comment]
Good point -- I was using the old parse.com dashboard.  

The new/beta dashboard differs from the old parse.com dashboard (and parse-dashboard) in that it completely removes the refresh button.  However, just like parse-dashboard, you remain in "edit cell" mode when you switch to another tab or focus on a different application.

I did confirm that once you enter "edit cell" mode in the dashboard and then switch to your App to cause some action, then go back to dashboard, you will auto-save the "edit cell" upon selecting any other area within the dashboard window.
