### ISSUE TITLE
Undefined Parse.User.current() for Cloud functions

### ISSUE THREAD

**Issue by laullon** [ParsePlatform/parse-server#301]
Hi,

`Parse.User.current()` doesn't get setup for Cloud functions.

I had tired to put `Parse.User.become(sessionToken)` on `Auth.js` `getAuthForSessionToken` but it throw a exception:
`[Error: It is not memory-safe to become a user in a server environment]`

**Comment by gfosco** [comment]
In a Node environment, it's not safe to use Parse.User.current, or become methods.  You can pass a sessionToken to queries or saves to perform an operation as a user.

i.e.

```
query.find({ sessionToken: myToken }).then(....);
obj.save(null, { sessionToken: myToken }).then(....);
```

You can access the user making the request in the request.user object.

**Comment by laullon** [comment]
I understand that, but my problem is that I have a lot of functions that relay on current user, and it works on the hosted version....

Is the `sessionToken ` global?

At least, this should be on the README.md under "Not supported".

**Comment by drew-gross** [comment]
No, any global state would be shared between requests in Node.js, which wasn't the case on parse.com. You will have to update your Cloud Code. Good point about the readme, though, I will update it.
