### ISSUE TITLE
Inconsistent 502 Bad Gateway responses only when VERBOSE mode is on

### ISSUE THREAD

**Issue by fcoufour** [ParsePlatform/parse-server#3010]
When and only when VERBOSE mode is on, a request can get a 502 Bad Gateway response or a 200 OK a few seconds after or before the first request.

### Steps to reproduce

1. Activate VERBOSE mode on parse-server via the verbose config option
2. Make the same query many times

#### Expected Results

Response 200 OK

#### Actual Outcome

Response 502 Bad Gateway

### Environment Setup

- **Server**
  - parse-dashboard version: 1.0.19
  - parse-server version: 2.2.24
  - Operating System: Ubuntu Server 
  - Hardware: 1 Core CPU / 512MB RAM
  - Localhost or remote server?: Digital Ocean

- **Database**
  - MongoDB version: 3.2.10
  - Storage engine: MongoRocks
  - Hardware: the same
  - Localhost or remote server?: Digital Ocean

**Important: I use Nginx as a reverse proxy**
- Parse Dashboard: https://dashboard.mydomain.com --> http://localhost:4040/
- Parse Server: https://api.mydomain.com --> http://localhost:1337/

### Logs/Trace

Here are some obfuscated examples from the iOS SDK:

POST /classes/ClassName1
{"where":{"field1":{"$in":[{"__type":"Pointer","className":"ClassName2","objectId":"<objectId>"},{"__type":"Pointer","className":"ClassName2","objectId":"<objectId>"}]},"user":{"__type":"Pointer","className":"_User","objectId":"<objectId>"}},"_method":"GET"}

POST /classes/ClassName2
{"include":"field1","order":"field2","_method":"GET","where":{"field3":false}}

POST /classes/ClassName3
{"include":"field1,field2,field3","order":"field4","_method":"GET","where":{"field3":{"$all":[{"__type":"Pointer","className":"_User","objectId":"<objectId>"}]},"field5":{"$ne":true}}}

It doesn't seem to be related to the kind of request but the only common characteristic is the WHERE clause.

_Any help would be appreciated_ 😃

**Comment by fcoufour** [comment]
This issue wasn't caused by Parser Server but by the PM2 process manager.
I followed the Digital Ocean migration guide (https://www.digitalocean.com/community/tutorials/how-to-migrate-a-parse-app-to-parse-server-on-ubuntu-14-04) where PM2 was watching for any change in the CWD directory to restart the process.
During restart, Parse Server was unreachable and the responses were 502 Bad Gateway.

To avoid that, we can totally disable this behaviour (watch: false) or just ignore the logs and hidden PM2 directories via ignore_watch.

**Comment by hubertott** [comment]
Life saver!

I was seeing PM2 restarting the threads at an unreasonably high rate, but I didn't put the two together. But it makes complete sense that a POST request being restarted would severe the connection to NGINX and cause it to return a 502.
