### ISSUE TITLE
No request possible in an afterSave trigger

### ISSUE THREAD

**Issue by fcoufour** [ParsePlatform/parse-server#3012]
We can't make any request in an afterSave trigger.

### Steps to reproduce

1. Declare an afterSave trigger in your Cloud Code
2. Include a request (fetch, get, first or find). For example:
```
Parse.Cloud.afterSave("ClassName", function(request) {
  var object = request.object;
  var otherObject = object.get("otherObject");
  console.log("otherObjectId=" + otherObject.id); // LOGGED
  return otherObject.fetch().then(function(otherObject) {
    console.log("field1=" + otherObject.get("field1")); // DOES NOT LOG ANYTHING
  });
});
```

3. Trigger it by saving the object

#### Expected Results

The request is successful or error and the object is saved

#### Actual Outcome

The object is saved

### Environment Setup

- **Server**
  - parse-dashboard version: 1.0.19
  - parse-server version: 2.2.24
  - Operating System: Ubuntu Server 
  - Hardware: 1 Core CPU / 512MB RAM
  - Localhost or remote server?: Digital Ocean

- **Database**
  - MongoDB version: 3.2.10
  - Storage engine: MongoRocks
  - Hardware: the same
  - Localhost or remote server?: Digital Ocean

**Important: I use Nginx as a reverse proxy**
- Parse Dashboard: https://dashboard.mydomain.com --> http://localhost:4040/
- Parse Server: https://api.mydomain.com --> http://localhost:1337/

### Logs/Trace

`0|parse-se | info: afterSave triggered for ClassName for user <userId>`

I tried the legacy notation success / error and the Promise notation. Nothing is logged in response and the object is well saved.

The source code was working on Parse.com and there are no error in the Parse Server log file.

The same requests made in a beforeSave trigger are working.

_Has anyone experienced the same thing?_

**Comment by flovilmart** [comment]
afterSave never had response.success/response.error.

**Comment by fcoufour** [comment]
Hi Florent! This is not what I say here.
If I try to make a request inside an afterSave trigger, the request is not made or the Promise is never resolved.

**Comment by flovilmart** [comment]
Without code it's pretty tough to figure out what's wrong...

**Comment by fcoufour** [comment]
Indeed, I edited the issue to make things clearer.

**Comment by flovilmart** [comment]
you should probably add an error handler....

``` 
return otherObject.fetch().then(function(otherObject) {
    console.log("field1=" + otherObject.get("field1")); // DOES NOT LOG ANYTHING
 }, function(error) {
    console.log("SOMETHING WRONG HAPPENED!!!!!! (and I'm pretty sure I'll be called)")
});
```

Note that returning the promise will make the afterSave call wait for the promise to resolve.

**Comment by fcoufour** [comment]
I simplified the code to debug and to make it more easily understood. Sure there is an error handler in the whole trigger source code.

Maybe I should have written something like "I'm a bit too confident for an error handler" 😛 . Nothing is logged except otherObjectId like before.

I appreciate your last remark but how the promises works is pretty clear to me.

Florent, do you currently have projects with requests successfully made inside an afterSave trigger with the last version of Parse Server?

**Comment by flovilmart** [comment]
There are unit tests that confirm that this behaviour should be working. Otherwise, please create a unit test and test against the test suite.

also can you check that `typeof otherObject.fetch === 'function'` ?

**Comment by frederoni** [comment]
Multiple requests that works with the latest version of parse-server:
<details>
```javascript

Parse.Cloud.afterSave("MyClass", (req, res) => {

    var decision = req.object;
    var user = null;
    var opponent = null;

    // Fetch current user
    req.user.fetch().then( (currentUser) => {

        user = currentUser;
        var token = req.user.getSessionToken();
        var searchId = req.object.get('search').id;

        var searchQuery = new Parse.Query("Search");
        searchQuery.equalTo("objectId", searchId);

        // Find the associated search object
        searchQuery.first({ sessionToken: token }).then( (search) => {

            // Figure out the opponent
            var creatorId = search.get('creator').id;
            var participantId = search.get('participant').id;
            var opponentId = (creatorId == user.id) ? participantId : creatorId;

            var opponentQuery = new Parse.Query(Parse.User);
            opponentQuery.equalTo("objectId", opponentId);

            return opponentQuery.first();

        }).then( (currentOpponent) => {

            // Find the opponents corresponding decision
            opponent = currentOpponent;
            var decisionQuery = new Parse.Query("Decision");
            decisionQuery.equalTo("user", opponent);
            decisionQuery.equalTo("search", req.object.get('search'));
            decisionQuery.equalTo("item", req.object.get('item'));
            decisionQuery.equalTo("positive", true);

            return decisionQuery.first();

        }).then( (decision) => {

            // Do we have a match?
            if (decision !== undefined) {
                decision.set('seenByOpponent', true).save();

                // Send push to opponent
                var installationQuery = new Parse.Query(Parse.Installation);
                installationQuery.equalTo("user", opponent);

                var message = "MESSAGE";

                Parse.Push.send({
                    where: installationQuery,
                    data: {alert: message}
                }, {useMasterKey: true}).then(() => {
                    res.success()
                }, (error) => {
                    res.error(error);
                });

            } else {
                res.success();
            }
        });
    });
});

```
</details>

**Comment by flovilmart** [comment]
Just quickly added that unit test:

```
  fit('test afterSave can fetch embedded objects', function(done) {
    var triggerTime = 0;
    // Register a mock afterSave hook
    Parse.Cloud.afterSave('GameScore', function(req, res) {
      var object = req.object;
      expect(object instanceof Parse.Object).toBeTruthy();
      return object.get('otherObject').fetch().then((other) => {
        console.log(other);
        triggerTime = 1;
      }, (err) => {
        console.error(err);
      });
    });

    var obj = new Parse.Object('GameScore');
    var obj2 = new Parse.Object('OtherObject');
    obj2.save().then(() => {
      obj.set('foo', 'bar');
      obj.set('otherObject', obj2);
      return obj.save();
    }).then(function() {
      // Make sure the checking has been triggered
      expect(triggerTime).toBe(1);
      done();
    }, function(error) {
      fail(error);
      done();
    });
  });
```

And that's correctly passing...

**Comment by fcoufour** [comment]
Ok, thanks guys. There should be something wrong by my side. I'll keep you updated.

**Comment by fcoufour** [comment]
This issue wasn't caused by Parser Server but by the PM2 process manager.
I followed the Digital Ocean migration guide (https://www.digitalocean.com/community/tutorials/how-to-migrate-a-parse-app-to-parse-server-on-ubuntu-14-04) where PM2 was watching for any change in the CWD directory to restart the process.
During restart, Parse Server was unreachable and was not logging anything.

To avoid that, we can totally disable this behaviour (watch: false) or just ignore the logs and hidden PM2 directories via ignore_watch.

Nota bene: in a Parse trigger, it seems that you don't even have to write a return statement to make it wait for a promise resolution. The behaviour is the same on Parse.com.
