### ISSUE TITLE
ParseObject.unset not work

### ISSUE THREAD

**Issue by osricwong** [ParsePlatform/parse-server#3013]
Hi, 
the `unset` method is working on parse.com but it is not working on self hosting.

if the database stored `title` = abc, the value is unchanged still be `abc` after the following code is ran.

```
var query = new Parse.Query("Comment");
  query.equalTo("objectId", request.params.objectId);
  query.first({
      success: function(object) {
          object.unset('title');
          return object.save();  },
      error: function(error) {
        alert("Error: " + error.code + " " + error.message);
  }
```

**Comment by alexblack** [comment]
Its possible maybe save is failing? You should pass it success, error, and capture the result.

**Comment by osricwong** [comment]
I had tried to modify other fields at the same time, the `name` field is saved but `title` is remained the previous value.

```
var query = new Parse.Query("Comment");
  query.equalTo("objectId", request.params.objectId);
  query.first({
      success: function(object) {
          object.set('name', 'abc');
          object.unset('title');
          return object.save();  },
      error: function(error) {
        alert("Error: " + error.code + " " + error.message);
  }
```

**Comment by osricwong** [comment]
Sorry, it's my fault
i checked that the problem from the Parse dashboard, and the value is updated on db

**Comment by yoshiboarder** [comment]
@osricwong  Hi I have a exactly same problem.. What is your fault? could you let me know?

**Comment by osricwong** [comment]
Hi, @ShawnBaek 
sorry for miss your message
In my situation, all values are updated on database successfully and the Parse dashboard only cannot display the up-to-dated information on screen, 

I just refresh my browser / press `Enter` on browser address bar to refresh. :)

**Comment by MikeNatty** [comment]
Damn. Yeah wasted a good chunk of time on this. 
Confirming the issue is Parse Browser - the provided "refresh" button does not update the unset field. 
Refreshing the WEB browser updates the deleted field. Far out.

**Comment by to83** [comment]
Same here! Spent half day on this analyzing why it does not unset any objects/values.

**Comment by flovilmart** [comment]
Did you open the issue on the dashboard repository?

**Comment by to83** [comment]
No. I was considering it though. First finishing my implementation/current task ;)
