### ISSUE TITLE
Error generating response. ParseError {   code: 141,   message:     ParseError {      code: 107,      message: 'Received an error with invalid JSON from Parse: Cannot POST /push\n' } }

### ISSUE THREAD

**Issue by tanujgirish** [ParsePlatform/parse-server#3026]
I have a feeling there is something wrong with the Parse SDK, I have posted this question on SO, http://stackoverflow.com/questions/40481087/push-notifications-not-sending-due-to-json-error-in-server

**Comment by natanrolnik** [comment]
@tanujgirish link shows page not found

**Comment by tanujgirish** [comment]
@natanrolnik sorry I updated the link

**Comment by natanrolnik** [comment]
@tanujgirish please close the issue and get the help from StackOverflow; If you find it's a bug in Parse Server, then you can reopen it and describe how to reproduce it.
