### ISSUE TITLE
Parse Performace Question is better many tables or many registers

### ISSUE THREAD

**Issue by ailtonjapaitpaeva** [ParsePlatform/parse-server#3035]
Hi guys, I am using parse for my backend app. So i have almost 50k of registers to save on parser and i will expect more 100k. I can split this data in many tables as i want. like  Profile table with 150k of registers or ProfileCompany1 ... ProfileCompanyN. So for performace with one is the best?

**Comment by flovilmart** [comment]
We have 2 millions installations objects, properly indexed, you don't need to create additional tables.
