### ISSUE TITLE
Cloud Code security

### ISSUE THREAD

**Issue by oallouch** [ParsePlatform/parse-server#3045]
Hi everyone,

Does a Cloud Code beforeSave function gets the request.user rights when doing a Query ?
Seems like it doesn't.
If so, I can add useMasterKey everywhere, but I'd just want to know.

Thx a lot in advance,
Olivier Allouch

**Comment by bohemima** [comment]
You should manually set the "sessionToken" for the current user when doing find/get/save from CloudCode -- See https://github.com/ParsePlatform/parse-server/wiki/Compatibility-with-Hosted-Parse#no-current-user

**Comment by oallouch** [comment]
Whaoo... I obviously knew about the "deprecated" Parse.User.current(), but not about the sessionToken thing !
The wiki should definitely be merged with the official docs. Maybe they wait until Parse.com is shut down.
Anyway, you just won a beer for your next trip to Paris.
Thx, man.

Olivier

**Comment by oallouch** [comment]
Ho, now I see it in the API, next to useMasterKey
