### ISSUE TITLE
SyntaxError: Unexpected token P

### ISSUE THREAD

**Issue by mman** [ParsePlatform/parse-server#3049]
Describe your issue in as much detail as possible.

I have couple of parse servers in production running successfully (latest stable version) with latest stable client SDK and serving some cloud code, user management, and push notifications. Nothing complex all rather basic tutorial style app.

From time to time, say every 100k requests I get this error message in the log:

```
Nov 13 17:21:05 docker/4c7a42b53766[1181]: SyntaxError: Unexpected token P
Nov 13 17:21:05 docker/4c7a42b53766[1181]:     at parse (/parse/node_modules/body-parser/lib/types/json.js:83:15)
Nov 13 17:21:05 docker/4c7a42b53766[1181]:     at /parse/node_modules/body-parser/lib/read.js:116:18
Nov 13 17:21:05 docker/4c7a42b53766[1181]:     at invokeCallback (/parse/node_modules/raw-body/index.js:262:16)
Nov 13 17:21:05 docker/4c7a42b53766[1181]:     at done (/parse/node_modules/raw-body/index.js:251:7)
Nov 13 17:21:05 docker/4c7a42b53766[1181]:     at IncomingMessage.onEnd (/parse/node_modules/raw-body/index.js:307:7)
Nov 13 17:21:05 docker/4c7a42b53766[1181]:     at emitNone (events.js:86:13)
Nov 13 17:21:05 docker/4c7a42b53766[1181]:     at IncomingMessage.emit (events.js:185:7)
Nov 13 17:21:05 docker/4c7a42b53766[1181]:     at endReadableNT (_stream_readable.js:934:12)
Nov 13 17:21:05 docker/4c7a42b53766[1181]:     at _combinedTickCallback (internal/process/next_tick.js:74:11)
Nov 13 17:21:05 docker/4c7a42b53766[1181]:     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Turning on VERBOSE=1 did not reveal anything, the message does not appear to be connected to the requests that are processed...

Could you please help me understand how to debug this further and where it might be coming from?

thanks,
Martin

**Comment by bohemima** [comment]
Probably random internet traffic hitting one of your endpoints that expected JSON as input but instead found "something else".
