### ISSUE TITLE
Migrating more than one parse app on single mongoDB 

### ISSUE THREAD

**Issue by OmarAliSaid** [ParsePlatform/parse-server#3055]
We are working on developing a service like parse.com. 
What we have done so far is building the parse server with shared mongoDB that uses user name prefix. 
Now our users can create new apps and use parse sdk and it's all good. 
We have been thinking to add migration feature to our service so that users can migrate from parse to our new platform. 
The question is, how could we do it since we are hosting a single mongoDB for the whole platform , ??

**Comment by flovilmart** [comment]
You should reach out to parse.com/help.

We don't provide support for such tools

**Comment by OmarAliSaid** [comment]
OK I will :) .. just if you can answer ( is it possible or not ) I will be more than happy :)

**Comment by flovilmart** [comment]
If i didnt answer it's because I can't

**Comment by OmarAliSaid** [comment]
I don't have Parse account , is another way to contact them ? 
Email or something
