### ISSUE TITLE
Fields name 'description' print/return whole object

### ISSUE THREAD

**Issue by rjpalermo1** [ParsePlatform/parse-server#3057]
### Issue Description

[DELETE EVERYTHING ABOVE THIS LINE BEFORE SUBMITTING YOUR ISSUE]

Describe your issue in as much detail as possible.

Returning any class with a column named `description` in the object prints the whole object when querying the column `description`

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1.  Created a TEST class in my Parse-Server with items `idKey` `name` `description`  
2.  Created an object in TEST class `idKey`=`11111` : `name` = `Testing Description Bug` : `description` = `This description should print when queried without printing whole object.`  
3.  Added this query to an IBOutlet in my iOS app that request print of `description` field only:  
```
		PFQuery *q1 = [PFQuery queryWithClassName:@"TEST"];
		[q1 whereKey:@"idKey" equalTo:@"11111"];
		[q1 findObjectsInBackgroundWithBlock:^(NSArray * _Nullable objects, NSError * _Nullable error) {
			
			NSLog(@"TEST DESCRIPTION BUG %@", [objects[0]valueForKeyPath:@"description"]);
			
		}];
```

4.  Run the method

#### Expected Results

NSLog response:

```
TEST DESCRIPTION BUG This description should print when queried without printing whole object
```

#### Actual Outcome

NSLog response:

```
TEST DESCRIPTION BUG <TEST: 0x7b86b180, objectId: hG1KmlGzds, localId: (null)> {
    description = "This description should print when queried without printing whole object.";
    idKey = 11111;
    name = "Testing Description Bug";
}
```

When I change my NSLog print log to the name or idKey field I get the appropriate response:

```
		PFQuery *q1 = [PFQuery queryWithClassName:@"TEST"];
		[q1 whereKey:@"idKey" equalTo:@"11111"];
		[q1 findObjectsInBackgroundWithBlock:^(NSArray * _Nullable objects, NSError * _Nullable error) {
			
			NSLog(@"TEST DESCRIPTION BUG %@", [objects[0]valueForKeyPath:@"name"]);
			
		}];


Console Log:

TEST DESCRIPTION BUG Testing Description Bug
```

### Environment Setup

- **Server**
  - parse-server version 2.2.24
  - Operating System:  Ubuntu 16.04 LTE up to date
  - Hardware:    
  - Localhost or remote server? Remote - own datacenter

- **Database**
  - MongoDB version: 3.2.10
  - Storage engine:  NA
  - Hardware:  
  - Localhost or remote server? Remote from Parse Server - own datacenter

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

[FILL THIS OUT]

**Comment by hramos** [comment]
This doesn't seem like a server-side issue. You may want to open this as an issue on the Parse iOS SDK itself.
