### ISSUE TITLE
cloud code beforeSave trigger for ALL collections?

### ISSUE THREAD

**Issue by AndrewLane** [ParsePlatform/parse-server#3058]
The syntax for cloud code beforeSave trigger functions requires you to specify the collection name.  If I'd like to have some cloud code run before saving ANY kind of objects from any collection, is that possible?  I basically want some wildcard syntax or something like this:

```
Parse.Cloud.beforeSave("*", function(request, response) {
```

My use case is that I need to restrict certain users from writing to certain collections, and that list of restricted collections might be large or need to be configurable.

**Comment by flovilmart** [comment]
you can pretty much do:

```
["ClassA", "ClassB"].forEach(function(className) {
   Parse.Cloud.beforeSave(className, function(req, res) {

   });
});
```

> My use case is that I need to restrict certain users from writing to certain collections

There are class level permissions for that.
