### ISSUE TITLE
Possibility of not triggering AfterSave or BeforeSave

### ISSUE THREAD

**Issue by guireg** [ParsePlatform/parse-server#3059]
### Issue Description
Hi Parse community,

I'm facing some issues with child object update. We have a complex permission with groups and multi-tenants software. When I update a parent object, I have to update some informations on child objects.

However, users are not always allow to modify child objects so it's mandatory to update the child object with {useMasterKey:true} option.

For some updates, I need AfterSave and BeforeSave triggers to fire but for other updates, I don't need them. Causing useless overload.

Is it possible to have another Parse.Object.save option as {useMasterKey:true} like {fireBeforeSave:true} and {fireAfterSave:true} only usable with MasterKey option to true ?

Or another more flexible system like passing a JSON parameter to Parse.Object.Save method that will be passed to beforeSave and afterSave triggers ?

Cheers,

Guireg

**Comment by flovilmart** [comment]
There is no overhead in running the the before save call as the declared function is called directly, you can just have an if statement in it and return early in the case you don't want to process the trigger.
