### ISSUE TITLE
Before Save check if Object is new

### ISSUE THREAD

**Issue by talkaboutdesign** [ParsePlatform/parse-server#306]
I used to be able to check like this: 

` if (request.object.id == null) {
}`

Now this doesn't work. In parse server objects come with object.id already.

**Comment by talkaboutdesign** [comment]
FYI, added logging to cloud code. It says object is not new. That it already exists. 

`2016-02-08T22:41:18.808979+00:00 app[web.1]: CALLING BEFORE SAVE.
2016-02-08T22:41:18.809080+00:00 app[web.1]: New object: false
2016-02-08T22:41:18.785676+00:00 app[web.1]: Object ID: MYSoqNB5YK`

**Comment by gateway** [comment]
What about using .isNew ?  I have yet to test any cloud code fyi..

`if (request.object.isNew()) `

**Comment by talkaboutdesign** [comment]
Yes. Same result.

**Comment by anthonysg** [comment]
Sounds like issue #107 .

**Comment by drew-gross** [comment]
Closing as duplicate of #107
