### ISSUE TITLE
Firebase authentication for parse-server

### ISSUE THREAD

**Issue by ranhsd** [ParsePlatform/parse-server#3065]
Hi , 
wanted to know if it is possible to use [Firebase authentication](https://firebase.google.com/docs/auth/) in order to authenticate my parse-server users. 
I know that parse-server provide oauth adapter but do you think i can create such adapter to work with Firebase authentication? 
I think that if it will be possible it can really be awesome because Firebase auth service cover the following: 

1. Basic authentication
2. Social login (google, facebook .. etc.)
3. Real time chat - you can use firebase real time chat because the user is actually a Firebase user

The Firebase auth is a service of Google cloud platform and since i am running all my services there (and very happy with it :) ) I was thinking also to use Firebase identity .

I did some research about this service and found that maybe it is possible to use the **admin** service but i am not 100% and that's why i need some inputs from you guys. You can read more about the Firebase admin service in here: https://firebase.google.com/docs/auth/admin/

Thanks in advanced!

**Comment by ranhsd** [comment]
Hi , I've created the ability to login to parse server with your Firebase user. What i did is to create an oauth adapter which does that. This oauth adapter depends on [this](https://www.npmjs.com/package/firebase-admin) node module. If someone would like to use it please let me know and i will try to upload it to my github or to [parse-server-modules](https://github.com/parse-server-modules) repository (with the help of @flovilmart :) )

**Comment by hramos** [comment]
I'm not sure this belongs here in Issues as it's not a bug.

**Comment by mockitor** [comment]
Hi @ranhsd, i want to authenticate parse users against firebase auth system (parse auth system acts as a bridge to firebase auth system???). how did you implement this kind of functionality.
