### ISSUE TITLE
Custom error code from parse cloud code?

### ISSUE THREAD

**Issue by yaaminu** [ParsePlatform/parse-server#3072]
I was wondering if it's possible to respond with custom error code from cloud code. I have to always be parsing error messages and ferreting for error codes in  ```ParseException.getMessage()```. If it were possible to just allow cloud code to customize error codes instead of always **141**, that would be great.

**Comment by alexblack** [comment]
I discovered you can do this!

```
response.error(1000, "Custom error")
```

**Comment by yaaminu** [comment]
great

**Comment by shkatulo** [comment]
Is there some way to customize error code with new asynchronous cloud code in Parse 3?
