### ISSUE TITLE
Push Notification Status sent but pushes sent 0 although working when tried on onesignal dashboard

### ISSUE THREAD

**Issue by jjdp** [ParsePlatform/parse-server#3076]
My app is on react-native.

The notification does not reach the device. Both the parse dashboard and cloud code outputs sent/success. The pushes sent just stays on 0. However when i tried to send a message through the one signal dashboard, the device receives it. I have not tried yet REST though i doubt this will make a difference.

I have tried both the default parse adapter and the one signal adapter. My _Installation class also has the saved device and through the adapter it sends the user to one signal.

Here is my config through express.

```
var express = require("express");
var ParseServer = require("parse-server").ParseServer;
var OneSignalPushAdapter = require("parse-server-onesignal-push-adapter");
var app = express();
var oneSignalPushAdapter = new OneSignalPushAdapter({
	oneSignalAppId: omitted,
	oneSignalApiKey: omitted,
});

var api = new ParseServer({
	databaseURI: "mongodb://localhost/sclubber",

	appId: omitted,
	appName: omitted,
	masterKey: omitted,

	cloud: "./cloud/main.js",

	serverURL: omitted,
	publicServerURL: omitted,

	liveQuery: {
		classNames: ["Chat"]
	},

	push: {
		adapter: oneSignalPushAdapter,
	},

	logLevel: "VERBOSE"
});

// Serve the Parse API on the /parse URL prefix
app.use("/parse", api);

// Initialize a LiveQuery server instance, app is the express app of your Parse Server
var httpServer = require("http").createServer(app);
httpServer.listen(1337);
ParseServer.createLiveQueryServer(httpServer);

```

Here is also what i set on my installation if that helps:

```
installationObject.set('installationId', iid);
installationObject.set('deviceToken', device.pushToken);
installationObject.set('user', Parse.User.current().id);
installationObject.set('localeIdentifier', DeviceInfo.getDeviceLocale());
installationObject.set('deviceType', DeviceInfo.getModel());
installationObject.set('timeZone', DeviceInfo.getTimezone());
installationObject.set('pushType', Platform.OS === 'android' ? 'android' : 'ios');
```

I get my iid with `Parse._getInstallationId().then((iid)`. I also tried instead of iid I used the device.userId from [https://github.com/geektimecoil/react-native-onesignal](url). The `pushToken` is also from there.

### Environment Setup

- **Server**
  - parse-server version 2.2.24
  - Localhost or remote server? Digital Ocean

- **Database**
  - Localhost or remote server? Digital Ocean

**Comment by flovilmart** [comment]
The one signal adapter don't report the status for the push sending as their http API don't report that when sending the push. You should probably use the one signal dashboard to track those statuses.

**Comment by jjdp** [comment]
i am using push on the parse server dashboard though. it doesnt send to the device

**Comment by flovilmart** [comment]
Can you fill the full issue template then with logs etc...

**Comment by jjdp** [comment]
turns out the pushtype shouldn't be set to anything. i made a mistake of setting this instead of device type.
please close
