### ISSUE TITLE
Parse.File location retrieved is different from what is saved on the server

### ISSUE THREAD

**Issue by rosarioconti** [ParsePlatform/parse-server#308]
Note 
 I have moved recently from parse to heroku with mongolab 
 I'm running Parse version 2.0.3 (heroku doesnt let me install any version after 2.0.4, 2.0.4 doesnt run but install )
 I'm aware I should run at least 2.0.7 but not sure if this is fixed so I/m asking you to check 

Steps to reproduce:
1. Save a Parse File (an image in my case)
2. Return the url from the file 

Results:
  http://files.parse.com / myapidecrypted / f39283984902380942_myfilename.jpg

Expected:
  Here I'm not sure at this point what should I get 

 is it http://myapp.herokuapp.com/1/files/myfilename.jpg   or something different ?    (this is what I get when I save the file via javascript client sdk )

Thanks in advance for checking this

**Comment by omairvaiyani** [comment]
+1 I'm facing the same hurdle. In my case, the localhost ParseServer results in 
http://localhost:[port]/[parse-mount]/ [appId] / [file-name.extension]

**Comment by rosarioconti** [comment]
Yeah, I solved that too, hacking actually the url, stripping out the "http://files.parse.com / myapidecrypted  and replacing with my info : " http://myapp.herokuapp.com/1/files/myapidecrypted/f39283984902380942_myfilename.jpg"
Done.
 Case close until they have an official fix.

You cna do the same, via web and via ios/android etc.

**Comment by occurrentarts** [comment]
Just want to note ( for anyone landing here with this problem ) that there was an official fix in v2.1.0
