### ISSUE TITLE
Reimplement Parse Frame URL

### ISSUE THREAD

**Issue by lenart** [ParsePlatform/parse-server#3090]
There is no easy way to reimplement what was known as "Parse Frame URL" that was used to mask Parse.com URLs on user-facing pages. 

This URL was used for displaying pages dealing with password reset (and email confirmation which we're not using). Because the current setup already works (with parse.com) we'd like to keep the same functionality since we already solved the styling issues on the destination page that displays content within an IFRAME.

The link itself is constructed in `parse-server/lib/Controllers/UserController.js:185` but I'm not sure how I could prepend the Frame URL and send the link as params. Something like:

```javascript
var link = _this3.config.parseFrameURL + '?link=' + _this3.config.requestResetPasswordURL + 'token=' + token + '&username=' + username;
```

**Comment by lenart** [comment]
Here's a quick (but hacky) implementation of what I was talking about:

```js
  // parse-server/lib/Controllers/UserController.js
  // call to setPasswordResetToken() around line 182

        if (_this3.config.parseFrameURL) {
          var strippedResetLink = _this3.config.requestResetPasswordURL.replace(_this3.config.publicServerURL, '');
          var link = _this3.config.parseFrameURL + '?link=' + encodeURIComponent(strippedResetLink) + '&token=' + token + '&username=' + username;
        } else {
          var link = _this3.config.requestResetPasswordURL + '?token=' + token + '&username=' + username;
        }
```

**Comment by flovilmart** [comment]
did you try setting publicServerURL ?

**Comment by lenart** [comment]
To be honest it just feels like an important variable which I didn't want to change because I want a single functionality changed. I still want the server to be used/accessible on my-parse-server.com but to send password reset links pointing to different domain (eg. my-website.com). I'll see if changing `publicServerURL ` could do the trick.

**Comment by flovilmart** [comment]
ok in your case you want different domains for your links right? I belive this is a valid feature request.
Can you make a PR for it?

**Comment by lenart** [comment]
I'll prepare a PR with the code above but keep in mind I'm not a node ninja ;)

**Comment by flovilmart** [comment]
No need to be a ninja! You identified the issue and have a workaround :) I'll help you along the way with the PR open.
