### ISSUE TITLE
Does documentdb work with parse-server by simply changing the connection string?

### ISSUE THREAD

**Issue by noder199** [ParsePlatform/parse-server#3093]
Just curious, has anyone tested to see whether parse-server works with documentdb out of the box?

https://docs.microsoft.com/en-us/azure/documentdb/documentdb-protocol-mongodb#

https://docs.microsoft.com/en-us/azure/documentdb/documentdb-connect-mongodb-account

**Comment by flovilmart** [comment]
If MFST says it works, that should work! They announced running parse on azure + documentDB in a blog post just after the release of the project. Do you have doubts? Or have issues with documentDB?

**Comment by noder199** [comment]
Just curious of any first hand experiences, that is good to hear that it should work. It is also in preview, so I am curious of any mishappenings folks may have had.

**Comment by flovilmart** [comment]
The best way to know is to try for yourself :)

**Comment by jeveloper** [comment]
would be great to know :)

**Comment by kulshekhar** [comment]
I tested it with the emulator and it seemed to work. I got the dashboard up, signed a few users and did basic queries

**Comment by srameshr** [comment]
YAY! I am moving from Atlas to DocumentDB and this is a sigh of relief!

**Comment by mtrezza** [comment]
A note of caution. AWS DocumentDB does not have the same features as MongoDB. You may want to compare the features to see whether DocumentDB fits your use case.

**Comment by zivchen** [comment]
@srameshr have you migrated to DocumentDB? is it working?

**Comment by srameshr** [comment]
I used getporter.dev to create a auto scaling Mongo instance and it's
running great and I don't need to worry about porting
