### ISSUE TITLE
iOS device doesn't receive the push from my dashboard

### ISSUE THREAD

**Issue by xiekw2010** [ParsePlatform/parse-server#3094]
### Issue Description

1. I follow the instruction https://github.com/ParsePlatform/parse-server/wiki/Push to setup my parse server 

![image](https://cloud.githubusercontent.com/assets/1814071/20519412/dba0ef9a-b0dd-11e6-83bb-87f4c5b89b05.png)

2. I follow the instruction https://github.com/ParsePlatform/PushTutorial/blob/master/iOS/README.md#1-creating-the-ssl-certificate to setup my iOS code

3. The log in dashboard

![image](https://cloud.githubusercontent.com/assets/1814071/20519750/19298b5a-b0df-11e6-9337-c93de5a5f607.png)

There was a warning about: 'warning: error while sending push'

I don't know where is going wrong.

iOS device doesn't receive the push form my dashboard.

- iOS version: 10.1.1
- device: iphone 7 plus

### Environment Setup

- **Server**
  - parse-server version  : 2.2.13
  - Operating System:    unbuntu 
  - Remote server? : Aliyun

- **Database**
  - MongoDB version: 3.2.9
  - Storage engine:  wiredTiger
  - Remote server? : Aliyun

### Logs/Trace

I set the VERBOSE=1 to get this log

![image](https://cloud.githubusercontent.com/assets/1814071/20519750/19298b5a-b0df-11e6-9337-c93de5a5f607.png)

**Comment by kitaecc** [comment]
use distribution certificate

**Comment by flovilmart** [comment]
You should probably run with VERBOSE=1 and probably check the documentation of node apn as this is the underlying module that sends the push notifications
