### ISSUE TITLE
File path

### ISSUE THREAD

**Issue by srameshr** [ParsePlatform/parse-server#3096]
I am trying to access a file which resides at ```/my_folder/my_text.txt```.
```
var filePath = "/my_folder/my_text.txt"; // I have tried both relative and absolute path.
fs.readFile(filePath, (err, data) => {      
});
```

Every time I try to run, I get ENONET error.
```
/Users/parse/node_modules/parse-server/lib/ParseServer.js:425
            throw err;
            ^

Error: ENOENT: no such file or directory, open '/my_folder/my_text.txt'
    at Error (native)
```

How should I open this file from parse server?

**Comment by flovilmart** [comment]
Not sure how this is relevant to parse-server

**Comment by srameshr** [comment]
@flovilmart I'm at loss. The same thing works on a regular node server running on my local machine. Once I move this to the parse platform it fails to work on both relative and absolute path for the file.

**Comment by srameshr** [comment]
Got it! The folder has to be referenced from / not cloud.
