### ISSUE TITLE
How long the Open-Source codes will be available for us?

### ISSUE THREAD

**Issue by Morbix** [ParsePlatform/parse-server#31]
How long the Open-Source codes will be available for us?

**Comment by sierrafayad** [comment]
I think this repo is going to stay here so we could keep working on it.

**Comment by gfosco** [comment]
I see no reason for it to ever disappear, and look forward to building on it with all of you.

**Comment by Morbix** [comment]
Nice, thank you guys @gfosco @sierrafayad
