### ISSUE TITLE
Reset password page not shown in iOS mobile browser

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/parse-server#3110]
My parse server is running in port 8080 in my domain in AWS.It works well for me and some other users. But some of my clients claimed that they got the following error message in iOS devices when they're trying to reset password and click the link in their emails:

> Cannot connect to this website

> Can't find www.mydomain.com DNS

And after they click refresh, they can see the reset password page. 

I have no clue at all what could be the cause. Can anybody help? Thanks.

**Comment by zh-wowtv** [comment]
Nobody encounter the same issue? My parse version is 2.2.17.

**Comment by hramos** [comment]
We'd need more information, a clear list of repro steps would help. The latest version is 2.2.25, it'd be great to know if this still happens there.
