### ISSUE TITLE
Revocable session token and Rest Call ->  the ":" char create problems.

### ISSUE THREAD

**Issue by drcrck** [ParsePlatform/parse-server#3112]
Hi!
I use Delphi component library for parse, that's a parse REST api wrapper. 
it permit to use parse app in Delphi like other native language.

With usage revocable session token (now mandatory) we found a problem. every call is , in low level library, encoded to http standard chars, included the header part of command. 
it results in a changing of session token string.
example : this  :  r:f8cc89290f8b5faca26aecb4f4e4d52f
is converted in this : r**%3A**f8cc89290f8b5faca26aecb4f4e4d52f

and parse always return 209 error , session token invalid. 

maybe , before unvalidate session token, can parse server try do decode it  ? 
i open a ticket to Embarcadero too, with same request :) 

thank you

- **Server**
  - parse-server version 2.2.17 and 2.2.23
  - Localhost or remote server? Azure and local vm

**Comment by flovilmart** [comment]
That's an issue in your client library.  It decodes the headers wrong. We don't have any issues with the official parse client libraries
