### ISSUE TITLE
Wiki community link file migration tool

### ISSUE THREAD

**Issue by MaxenceDupressoir** [ParsePlatform/parse-server#3116]
Hi guys, I know this is not a proper issue but I don't really where to post it.

At Meetic we made a small tool, in PHP, that migrate files from parse.com to a private AWS S3 bucket and updates files names in your private mongoDB.

I think this can useful for someone out here and it be found here : https://github.com/Meetic/parse-files-migration-tool.

I also think this could be a "good" link to add to wiki community link list.

Regards

**Comment by flovilmart** [comment]
Probably we could add it to the docs :)

**Comment by flovilmart** [comment]
What would be the tableName here: https://github.com/Meetic/parse-files-migration-tool/blob/master/src/ParseServerMigration/Console/PictureRepository.php#L188

**Comment by MaxenceDupressoir** [comment]
Hi,
The "table name" here is the mongoDB collection name that you had files links saved to.

**Comment by flovilmart** [comment]
Yeah but usually that table doesn't exist or is not a single table.

**Comment by MaxenceDupressoir** [comment]
Ok I get the point.
Expected workflow is to migrate S.A.A.S parse DB to your own private mongoDB instance and then run the tool. 
If you have several file location to migrate you can run the tool as many time as you collections you want to migrate just by editing your configuration.

Ill add a part on readme.md about the parse data migration requirement.

**Comment by hramos** [comment]
Closing as a non-issue, feel free to continue commenting here to coordinate though.

**Comment by MaxenceDupressoir** [comment]
@flovilmart So is everything ok for you ?

**Comment by flovilmart** [comment]
I'll add it :)

**Comment by MaxenceDupressoir** [comment]
Greats thanks ! Feel free to point out if everything is not crystal clear for you.

**Comment by flovilmart** [comment]
here: https://github.com/ParsePlatform/parse-server/wiki/Files-Migration

**Comment by MaxenceDupressoir** [comment]
Great! I didn't see that there was an existing tool :D
