### ISSUE TITLE
Select few fields from included object.

### ISSUE THREAD

**Issue by srameshr** [ParsePlatform/parse-server#3118]
Is it possible now? [Here is a detailed description](https://parse.com/questions/parsequery-selectkeys-on-included-objects).
Not sure if this has to be raised here or JS SDK repo.

**Comment by flovilmart** [comment]
Yes it should be possible, use the dot notation 'object.key'

**Comment by srameshr** [comment]
Does not work. I tried
```
query.include('createdBy');
query.select('createdBy.name', 'createdBy.age'); // 

// Even this fails.
query.include('createdBy');
query.select('createdBy.name');
query.select('createdBy.age'); 

```

Both syntaxes fail with ```NullPointerException```

**Comment by flovilmart** [comment]
Add select('createdBy') ?

**Comment by srameshr** [comment]
@flovilmart 

Yup, that worked.

**Comment by flovilmart** [comment]
There's no back propagation of select keys. Known issue, probably could be solved

**Comment by emkman** [comment]
@flovilmart even if we do the subquery manually with it's own select parameters, is it possible to take the results and put them back in the parent object before returning the results? In hosted Parse this always led to "Unsaved Pointer" serialization errors. After using Parse for many years, select keys on includes would be my biggest feature request for parse-server.

**Comment by emkman** [comment]
Also this issue leads me to believe this behavior does work now: https://github.com/ParsePlatform/parse-server/issues/1567
so I am fairly unclear on its state.

**Comment by flovilmart** [comment]
Not sure I follow. The select() work, besides the tiny bug that requires you to select all components of the path, but again that could be easily fixed. (Working on a PR now)

**Comment by emkman** [comment]
So after the PR you will be able to select a subset of keys from the included object?

**Comment by flovilmart** [comment]
See: https://github.com/ParsePlatform/parse-server/issues/3185

It's already possible, to select parts of the nested object, but you have to explicitly call include.

**Comment by emkman** [comment]
Oh awesome, thank you!
