### ISSUE TITLE
Adding multiple Hooks for the same class

### ISSUE THREAD

**Issue by timpler** [ParsePlatform/parse-server#3123]
How to reproduce

1. Add two (or more) `beforeSave` hooks for the same `class`:

```
Parse.Cloud.beforeSave('TestClass', (req, res) => {
  console.log('Test');
  res.success();
});

Parse.Cloud.beforeSave('TestClass', (req, res) => {
  console.log('Test 2');
  res.success();
});
```

2. Save some object of this class

Expected outcome:
Two console logs - `Test` and `Test2`

Actual outcome:
Only one console log of last added hook - `Test2`

So is it not possible to have multiple hooks for the same object?

**Comment by jonas-db** [comment]
Why would you like to do that anyways?

**Comment by timpler** [comment]
@jonas-db - Why old 'event' is deleted when I add new one? It's like removing all click events on page, when adding new one.

I add beforeSave event from more than one place in my codebase.

**Comment by flovilmart** [comment]
Those are not events, but hooks. Only the last one will be processed.

**Comment by flovilmart** [comment]
And no, this is not possible also, that prevents aweful side effects as you can't really guarantee the order of execution
