### ISSUE TITLE
Cloud code deployment

### ISSUE THREAD

**Issue by ranhsd** [ParsePlatform/parse-server#3124]
Hi, 
I have some question on cloud code deployment. 
Currently all my cloud code functions are located under the **/cloud** folder of my parse-server project. In order to update my cloud code in production i required to redeploy my parse server again.
I wanted to know if there is an option to decouple the cloud code deployment from the parse-server backend deployment so when i redeploy cloud code the only thing that i will need to do is to restart my node without redeploy the whole thing again?

Maybe we can run cloud code on another server in order to achieve this behaviour and then the change the cloud code path inside the parse-server project to point to external resource or maybe there is a better solution for that... 

My parse server runs on docker container inside kubernetes cluster hosted on google container engine so each time i want to deploy the solution i need to: rebuild all the docker images again, push the latest version into the docker registry, update my kubernetes .yml files (if required) and deploy. 

Thanks in advanced for any help!

**Comment by flovilmart** [comment]
@woyorus what do you suggest? We have a similar setup.

**Comment by ranhsd** [comment]
Hi , its not a suggestion its a question :) it is possible to decouple the cloud code from parse-server deployment?

**Comment by ranhsd** [comment]
Hi @flovilmart , wanted to know if technically it is possible with the current version of parse-server?

**Comment by woyorus** [comment]
Hey there! Have you tried to attach your Cloud Code as a volume? For example, something like `docker run -v /my/cloud/code:/parse-server/cloud:ro parseplatform/parse-server:2.2.25-beta.1` would work. Then you'll have to update your Cloud Code in /my/cloud/code on your host and `docker restart` your container.
In Kubernetes, for example, you can use a ConfigMap to store your CloudCode and then attach it as a volume.

**Comment by ranhsd** [comment]
Hi @woyorus , thanks for your response.. 
I use Kubernetes to create secrets to some key files (e.g. push notification, google cloud keys etc.) and it works well. So if i will use the same approach for cloud code and create a volume and provide the path to the file it will work? I am asking because this means that parse-server will need to load the cloud code from a remote location .. 

If it is possible then i think that the following should be done: 

1. The same steps you described (ConfigMap, Volume etc.)
2. Create env variable that will point to the path where the cloud code file(s) exists.

What do you think?

thanks !

**Comment by woyorus** [comment]
Yeah you definitely can use secrets for that too. Just to recap:

1. Create a Secret/ConfigMap with your CloudCode files
2. In your container spec attach a volume from your Secret/ConfigMap
3. Use `PARSE_SERVER_CLOUD_CODE_MAIN` env variable to point to your Cloud Code entrypoint

Hope that helps!

**Comment by hramos** [comment]
#resolved

**Comment by ranhsd** [comment]
Hi @woyorus, @flovilmart 
I tried to do what you suggested above (to create configmap and volume..)
the problem is that it works only if you do not need any other modules inside your cloud code which is not my case.. 
in my cloud code i use other node modules and when i try to run parse-server on k8s with the setup that you suggested i get an error **"Cannot find module ..."**
after debug it a bit i think that the problem is with the path of the node_modules because they are located under the root_folder/node_modules folder and not under my volume..

**Comment by woyorus** [comment]
Hi @ranhsd!

Indeed there's no support yet for external dependencies in cloud code with the Dockerized app. I can suggest you to build your own image using Dockerfile in the parse-server root, simply adding dependencies that you need into `package.json` beforehand. I believe that may solve your problem in a quick and dirty way. 

I for sure agree that this is not the way to go, so I suggest opening a separate issue for that, and hopefully we can figure out the best way to enable custom cloud code deps.

@flovilmart what do you think?

**Comment by ranhsd** [comment]
hi @woyorus thanks for your response.. 
i managed to solve it by changing the path .. anyway i regarding the cloud code deployment i really think we should find a better way to deploy the cloud code from dev --> test --> to production and maybe also to be able to run CI in the middle of the process in order to make sure that everything is working as expected.. 
I am heavy consumer of cloud code and i am sure that other developers and organisation are also write a lot of business logic via cloud especially when now you can reuse **any npm module**  that you want so i think cloud code should get more attention. Maybe we can provide some CLI that will deploy cloud code or something similar..
