### ISSUE TITLE
Error Domain=NSCocoaErrorDomain Code=3840

### ISSUE THREAD

**Issue by mkaya93** [ParsePlatform/parse-server#3126]
- [x] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.

- [x] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases

- [x] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.

- [x] You have filled out every section below. Issues without sufficient information are more likely to be closed.

--

I am getting this error when I'm trying to save object with big size image. 

`Optional(Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.})`

This is my code.

```
let object = PFObject(className: "Events")
        object.setObject(event!.title!, forKey: "title")
        object.setObject(event!.subTitle, forKey: "subtitle")
        object.setObject(event!.eventUser!, forKey: "eventAdmin")
        object.setObject(event!.locationGeoPoint!, forKey: "locationGeoPoint")
        object.setObject(event!.locationName!, forKey: "locationName")
        object.setObject(event!.venue?.foursquareId, forKey: "foursquareId")
        object.setObject(event!.eventStartDate!, forKey: "eventStartDate")
        object.setObject(event!.eventStartTime!, forKey: "eventStartTime")
        object.setObject(event!.whoIsPaying!, forKey: "whoIsPaying")
        object.setObject(event!.eventEndDate, forKey: "eventEndDate")
        object.setObject(event!.eventEndTime!, forKey: "eventEndTime")
        object.setObject(event!.eventCapacity, forKey: "eventCapactiy")
        object.setObject(event!.eventCategory, forKey: "eventCategory")
        object.setObject(event!.venue!.address, forKey: "eventAddress")
        object.setObject(self.descriptionTextField.text!, forKey: "subtitle")
        let fileData = UIImageJPEGRepresentation(event!.settedEventImage!, 0.6)
        let image = PFFile(data: fileData!, contentType: "image/jpeg")
        object.setObject(image, forKey: "eventImage")
        
        var relation = object.relation(forKey: "participants")
        relation.add(currentUser!)
       object.saveInBackground()
```

My parse server is working on Amazon Elastic BeansTalk.

**Comment by hramos** [comment]
Can you provide a curl command that reproduces this issue reliably on the latest Parse Server version?

**Comment by PunkStarStudios** [comment]
This fails:
curl -X POST \
  -H "X-Parse-Application-Id: MyAPI" \
  -H "X-Parse-REST-API-Key: MyRest" \
  -H "Content-Type: image/jpg" \
  --data-binary '@1.jpg' \
  https://myserver.com/parse/files/1.jpg

This works
curl -X POST \
  -H "X-Parse-Application-Id: MyAPPId" \
  -H "X-Parse-REST-API-Key:MyRestAPI" \
  -H "Content-Type: image/jpg" \
  --data-binary '@1.jpg' \
  http://myserver.com:1337/parse/files/1.jpg

**Comment by flovilmart** [comment]
probably because `myserver.com` doesn't respond on port 80.  What's the error?

**Comment by PunkStarStudios** [comment]
Hey there.
:)

On 80 it responds with the standard nginx place holder.
"Welcome to nginx!

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx.”

**Comment by flovilmart** [comment]
So that's an issue with your nginx configuration, not an issue with parse-server.

**Comment by PunkStarStudios** [comment]
I was afraid of that.
Everything else is working fine… just posting of files via https…
Is there a sample nginx sites file somewhere configured for parse-server?
The sample I have (which still needed tweaking to work) obviously is not sufficient ;P

**Comment by flovilmart** [comment]
From there, it's a question that's more likely to be answered on stackoverflow, as it's not specific to parse-server but nginx and express apps
