### ISSUE TITLE
Is disabling the Cache (Using NullCacheAdapter) affect performance?

### ISSUE THREAD

**Issue by benishak** [ParsePlatform/parse-server#3129]
Parse is caching some stuffs like user roles and sessions.
I believe because the default cache doesn't have a limit, makes it continuously increase in size.

We want to disable it, but if that could affect performance we can use a RedisCache or ImMemoryCache where we can set a cache size limit.

**Comment by flovilmart** [comment]
That could indeed affect performance, but replacing it with a LRU cache would be nice! indeed LRU cache is already available in the project.

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.
