### ISSUE TITLE
Parse-server restarts when i run a cloud define. 

### ISSUE THREAD

**Issue by Cliffordwh** [ParsePlatform/parse-server#3136]
Describe your issue in as much detail as possible.

Im testing with the hello cloud function, when i post to it using postman or via the client IOS side. The parse-server reboots after success. 

When it post i receive success, but when viewing the pm2 logs a termination signal received. 
`pm2 logs 0` 

Is this normal for parse-server using `pm2`? 

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

just a standard postman post to a cloud function!  Parse servers starts with PM2. 

#### Expected Results

```
 info: Ran cloud function hello for user undefined with:
1|parse-se |   Input: {"reportRelation":"#####","emailTo":"test@gmail.com"}
1|parse-se |   Result: "Hello" functionName=hello, reportRelation=dWtPb0CFXM, emailTo=test@gmail.com, user=undefined
```

#### Actual Outcome

```
 info: Ran cloud function hello for user undefined with:
1|parse-se |   Input: {"reportRelation":"#####","emailTo":"test@gmail.com"}
1|parse-se |   Result: "Hello" functionName=hello, reportRelation=###, emailTo=test@gmail.com, user=undefined
1|parse-se | Termination signal received. Shutting down.


 [23325] parse-server running on http://localhost:1337/
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : [2.2.25]
  - Operating System:     [Ubuntu]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [Self Hosting]

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

**Comment by Cliffordwh** [comment]
Quick fix is actually to move away from PM2. Personally its useless!  Going to quickly add VERBOSE 1 to see if i can find more details.

**Comment by Cliffordwh** [comment]
My config as follows. Seems no other info from VERBOSE 1 being on!
```
{
  "apps" : [{
    "name"        : "parse-server",
    "script"      : "/usr/bin/parse-server",
    "watch"       : true,
    "merge_logs"  : true,
    "cwd"         : "/home/parse",
    "env": {
      "VERBOSE": "1",
      "PARSE_SERVER_CLOUD_CODE_MAIN": "/home/parse/cloud/main.js",
      "PARSE_SERVER_DATABASE_URI": "mongodb://###",
      "PARSE_SERVER_APPLICATION_ID": "#####",
      "PARSE_SERVER_MASTER_KEY": "#####",
      "PARSE_SERVER_FILE_KEY": "####",
      "PARSE_SERVER_JAVASCRIPT_KEY": "####",
      "PARSE_SERVER_REST_API_KEY": "####",
      "PARSE_SERVER_CLIENT_KEY": "###",
      "PARSE_SERVER_MOUNT_PATH" : "/",
      "PARSE_SERVER_FILES_ADAPTER" : "parse-server-s3-adapter",
      "S3_ACCESS_KEY" : "###",
      "S3_SECRET_KEY"  : "####",
      "S3_BUCKET" : "####",
      "S3_SIGNATURE_VERSION" :"v4",
      "PARSE_SERVER_FACEBOOK_APP_IDS" : "",
      "S3_DIRECT_ACCESS" : true,
      "PARSE_SERVER_APP_NAME" : "##" ,
      "PARSE_PUBLIC_SERVER_URL" : "####",
      "PARSE_SERVER_PUSH" :  {"adapter" : "parse-server-onesignal-push-adapter",
                                             "oneSignalAppId": "###",
                                             "oneSignalApiKey": "####",
                             },
     "PARSE_SERVER_EMAIL_ADAPTER" : {
           "module": "parse-server-simple-mailgun-adapter",
                  "options": {
                  "fromAddress": "###",
                  "domain": "###",
                  "apiKey": "###",
                   }
      },
    }
  }]
}
```

**Comment by Cliffordwh** [comment]
Just saw, that even in the parse-dashbaord. I'f i just click around, after every request the parse-server restarts.  mmmmm that cant be normal!

**Comment by Cliffordwh** [comment]
Seem to be a problem with node.js. removed and installed now all is perfect!

**Comment by Sanlusfa** [comment]
I met this problem recently - "**Ran cloud function, then restart.**"

In my case, finally, found the reason is:
When run cloud function, /logs/parse-server.info.201x-0x-0x will be written some info.
If PM2 env is "watch" : true, when add/remove any files or change file content, PM2 will restart the server.

Solution:
remove "watch" : true
And just watch and ingore_watch specefic folder or file I need.
example:
"watch" : ["parse-server/index.js","parse-server/cloud"],
"ignore_watch": ["logs","node_modules"],
"watch_options": {
   "followSymlinks": false
}
ref: http://pm2.keymetrics.io/docs/usage/watch-and-restart/

Of course, pm2 restart:
$ pm2 delete all
$ pm2 start ecosystem.json

**Comment by bitfinity** [comment]
Sanlusfa, thanks for the suggestions. Helped a lot. One thing, for me "ignore_watch" should be "logs/*"

**Comment by bitfinity** [comment]
Can I also comment that this is really dumb. This cost me a lot of time. There's no reason the server should restart by default if something writes to the logs.

**Comment by bitfinity** [comment]
This should not be closed. The watch configuration of true should be modified to not include logs.

**Comment by flovilmart** [comment]
@bitfinity, we don't provide a pm2 config with Parse-server, not sure why you insist on reopening

**Comment by bitfinity** [comment]
@flovilmart, the server has a "watch" configuration element right? The "watch" configuration element's default behavior is to restart the server if the server log files change. So if in your cloud code, you write console.log("something") the server will restart. If you think that behavior is fine and what people expect, then by all means keep the issue closed. I think that behavior is horrible myself, and will lead people to have unexpected problems and take a while to figure out, if ever, what is going on. It's a shame to have the performance of parse-server, which people are working hard to maintain, and then have a misleading configuration element like this that restarts the server all the time when log files change.

**Comment by bitfinity** [comment]
@flovilmart  I could be wrong, and I understand that the configuration is not i the code, but the elements that can be configured I assume are in the code, and the behavior of that configuration - i.e. "watch: true" behavior restarting the server when the log files change (watching the wrong files).

**Comment by flovilmart** [comment]
There is no watch in parse-server

**Comment by Sanlusfa** [comment]
For this "watch:true" issue, perhaps, I could provide something I exped.

The "watch" function is provided by "PM2", Parse-Server can do less.
Parse-server logs should be keep written to record system info.

This over-watch might be caused by "PM2" version.
Year ago, I use PM2(1 year ago version) to watch Parse-Server, everything is OK.
Recently, I use PM2(latest version) to watch Parse-Server, PM2 watched too much.
If use Others(ex. Forever) to watch Parse-Server, everything is fine.
