### ISSUE TITLE
Parse LiveQuery not working on Digitalocean

### ISSUE THREAD

**Issue by aalshaikh** [ParsePlatform/parse-server#3142]
I am running Parse server on Digitalocean with liveQuery every time when the application trying to connect to websockets i got this error:

WebSocket connection to 'ws://xxx.xxxx.com/api' failed: Error during WebSocket handshake: Unexpected response code: 403

Everything else is working fine in my app just livequery not working and when i am trying to run the application and parse server locally it's working fine and live working fine on locally.

My index.js for parse is:

var app = new ParseServer({
  databaseURI: databaseUri || database.url,
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || appid,
  masterKey: process.env.MASTER_KEY || masterkey,
  serverURL: process.env.SERVER_URL || serverurl,
  javascriptKey: jsKey,
  restAPIKey: restapi,
  facebookAppIds: fbid,
  liveQuery: {
    classNames: ["conversations", "messages"]
  },
});

var port = process.env.PORT || 80;
var httpServer = require('http').createServer(app);
httpServer.listen(port, function() {
    console.log('parse-server-example running on port ' + port + '.');
});

// This will enable the Live Query real-time server
ParseServer.createLiveQueryServer(httpServer);

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.24
  - Operating System:      Ubuntu 14.04.4 x64
  - Hardware:            DELL with hardware RAID, 32-64GB
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Digital Ocean

**Comment by hramos** [comment]
If you can drill this down to a particular issue with Parse Server, please open a new issue. We're unable to troubleshooting individual deployments.
