### ISSUE TITLE
Query array of values - Removing objectId (type string ) from array of strings

### ISSUE THREAD

**Issue by hecomp** [ParsePlatform/parse-server#3144]
Hi, 

I'm hosting Parse server on Heroku. My issue is when I'm removing an objectId from array of strings. I have a cart column (array) on JobFeed class. I query the following:

$http( {
  method: 'PUT',
  url: 'https://myserver/1/classes/JobFeed/' + jobId,
  data: {
    cart: {
      __op: 'Remove', 
      objects: [ service.objectId]
    }
  }
});

It returns JobFeed with the objctId still on the array.

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.
