### ISSUE TITLE
ParseConfig with A/B Testing

### ISSUE THREAD

**Issue by supercharger** [ParsePlatform/parse-server#3148]
The SDK's [ParseConfig documentation](https://parseplatform.github.io/Parse-SDK-iOS-OSX/api/Classes/PFConfig.html) claims remote configs with A/B Testing feature. But I don't see support for configs A/B testing in the parse-server or the Dashboard.

Can you please let us know if this feature is implemented ( need doc on how to use it ) or if not the SDK documentation needs to be updated.

**Comment by flovilmart** [comment]
You don't A/B test your config, but you could store in your config for ex:

experiment1 = { a: "some value", b: "other value" }

Then in the clients read the values for those experiments.

**Comment by supercharger** [comment]
I didn't mean A/B testing configs. I want to use configs for A/B testings, based on user segmentation/bucket these configs to change.

The docs doesn't give any indication how to use it, But https://parseplatform.github.io/Parse-SDK-iOS-OSX/api/Classes/PFConfig.html says I can use this for A/B testing.

From the client, I read the PFConfig, I will always get the same value, how to make this specific to experiment ?

**Comment by flovilmart** [comment]
You can use the config as I explained above, then you'll need to assign your users to buckets/segments somewhere else.

It is said you can use it for A/B testing but it's not an A/B testing framework.

**Comment by supercharger** [comment]
>> You don't A/B test your config, but you could store in your config for ex:
>> experiment1 = { a: "some value", b: "other value" }

Is there a way to associate "experiment1" to "user1" and "experiment2" to "user2", Is that supported parse ?

The Parse push notification supports user segmentation, it would be nice if this feature can be implemented too.

**Comment by flovilmart** [comment]
You can simply have a new column in the user table or a function that transforms the objectId into the correct experiment... I dunno, there are zillions of ways of doing that.

> Parse push notification supports user segmentation,

When you assign a user property to the _Installation itself, yes.

As it's not an issue with parse-server but more of a question, I suggest that you go ahead on stackoverflow for implementation details.

**Comment by supercharger** [comment]
Yes, Thanks.

**Comment by supercharger** [comment]
But, I think it is a valuable feature to support remote configs with explicit A/B testing.

**Comment by flovilmart** [comment]
Go ahead an open a pull request with that feature then :)

**Comment by supercharger** [comment]
Yes, will be evaluating that, if I can do that in the time constraints.
FYI, Basically I am talking about this feature, https://firebase.google.com/docs/remote-config/

**Comment by flovilmart** [comment]
So you can assign per _Installation object... Closing the convo as it's not going anywhere.
