### ISSUE TITLE
user.signUp() not creating a session when PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS =1

### ISSUE THREAD

**Issue by listingboat** [ParsePlatform/parse-server#3152]
Environment:
- Node.js 7.2
- parse-server 2.2.25

In our cloud code, we are having an issue with the Parse.User signup() call not creating a sessionToken for the user post call when we enabled the `PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS` option.

This works:

```
Parse.Cloud.useMasterKey();

var user = new Parse.User();
user.set('username', form_data.userEmail);   
user.set('email', form_data.userEmail); 
user.set('password', form_data.password1);    // sets user's password

user.signUp().then(function(user) {
  // Valid Session Token
  var sessionToken = user.getSessionToken();
});
```

Since we have to refactor all calls to Parse.Cloud.useMasterKey() and pass it as an option, we set `PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS=1`, and refactored to this and now this fails:

```
var user = new Parse.User();
user.set('username', form_data.userEmail);   
user.set('email', form_data.userEmail); 
user.set('password', form_data.password1);    // sets user's password

user.signUp(null, {useMasterKey: true}).then(function(user) {
  // sessionToken = undefined
  var sessionToken = user.getSessionToken();
});
```

**Comment by flovilmart** [comment]
That's actually an expected behaviour, as with the `PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS=1` the installationId doesn't exist (it's cloud code, not a client).

The session tokens are tied to installations, therefore it's not possible to call the signup method that way. If you signup users serverside, you should probably not forward the session token.

**Comment by listingboat** [comment]
So, our app is a web app that calls controllers on the backend.  Registration is done through a form post to one of these Node controllers.

It sounds like this needs to be refactored to call signUp through the REST API from the client side.  Or, On registration return, call the login REST API.

Is that correct?

**Comment by flovilmart** [comment]
correct, also, I could have a look for a way to pass the installationID when signingUp the user in order to impersonate the current client's installationId so you can have a session token as well.

**Comment by listingboat** [comment]
A way to pass the installationID would make things simpler.  Thank you.

**Comment by flovilmart** [comment]
Can you try passing installationId alongside masterKey, that should actually work correctly.

**Comment by listingboat** [comment]
To be clear, installationId is Application Id?

**Comment by flovilmart** [comment]
no, the installationId from the user that made the request

**Comment by listingboat** [comment]
Since there is no user during our registration process, would this be the objectId of a user with the correct ACL?

**Comment by flovilmart** [comment]
the InstallationID associated with the request.

**Comment by listingboat** [comment]
So, I am completely unaware of what an Installation is.  Reading up on it it appears to be an id for an app installation on a device.  This is a pure web app, so there are no installations.

**Comment by flovilmart** [comment]
Yes there is installationId attached to each client.

**Comment by listingboat** [comment]
We don't have clients.  It's a pure web application.  There are no clients calling the Parse API.  Only backend Node.js code calling the Parse API.

**Comment by steven-supersolid** [comment]
If you were using the JS SDK then an installationId is generated and persisted: https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/InstallationController.js

I guess without direct access this is still happening but on the server, and you never know or care about the installationId.

If this is the case then a workaround would be to generate your own installationId using the same code.

**Comment by listingboat** [comment]
By creating a new Parse Installation object?

**Comment by flovilmart** [comment]
No, I doesn't require that

**Comment by listingboat** [comment]
Still very confused.  So what do I pass for installationId?

**Comment by flovilmart** [comment]
there should be a installationId property on the request object itself.

**Comment by listingboat** [comment]
There isn't.  The request path is a simple form post ajax request.  The path to Parse is:
ajax.post -> Node Route -> Node Controller -> Parse Javascript API

**Comment by flovilmart** [comment]
in you cloud code function:

It's set there: https://github.com/ParsePlatform/parse-server/blob/master/src/Routers/FunctionsRouter.js#L112

**Comment by flovilmart** [comment]
But you're right if you're not using the JS SDK you won't have an installation ID, therefore you need you clients to login once they signed up. I'm not sure why you would let the people signup through cloud code where you could block the signup in _User beforeSave

**Comment by listingboat** [comment]
Got it.  Logging in post registration works.  Thank you for your time on this.  I know our situation is not ordinary here.

**Comment by pewh** [comment]
Hello, I'm try to signUp via cloud code. I'm confused where I can put installationId. I've try this but `installlationId` cannot be passed to session.

```
    const newUser = await Parse.User.signUp(username, password, {
      name,
      phoneNumber: username,
      balance: 0,
    }, {
      installationId: installation.installationId,
      useMasterKey: true,
    })
```

**Comment by flovilmart** [comment]
Are you using PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS =1 ? Also, can you provide the verbose logs ?

**Comment by pewh** [comment]
@flovilmart I don't use `PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS=1`. When I use `PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS`, the sessionToken is empty.

And yes, I get correct `installationId`. I already inspect value `installation.installationId` using debugger.

By the way, it's working well on `Parse.User.logIn`. It shows correct behavior on session installationId, but no for Parse.User.signUp.

Here is the log:

```
info: Ran cloud function registerThenLoginMember for user undefined with:
  Input: {  
   "token":"XXX",
   "name":"Gg",
   "gender":"male",
   "installation":{  
      "installationId":"fd150a57-ed21-2752-be4b-b34930c153e4",
      "deviceBrand":"Xiaomi",
      "deviceModel":"HM NOTE 1W",
      "systemName":"Android",
      "systemVersion":"4.4.2",
      "deviceLocale":"en-US",
      "deviceCountry":"US",
      "isEmulator":false,
      "isTablet":false,
      "appVersion":"0.0.4.4",
      "timeZone":"Asia/Jakarta",
      "deviceToken":"fK42xhwSIGU:APA91bGCSEFkSdK5nWMX97MQ61Yh1zjrC0h4XvzgdCWIALYcN5XqudWZGOanKTLK_2Gd2a_ou_-pjl72rnjTd1hwkggGM4C_M4v67XwjAxAdZphRnjQCNx2QKP_RQ-BRFuehIbvhmKfL",
      "deviceType":"android"
   }
}
  Result: {"currentUser":{"name":"Gg","phoneNumber":"YYY","balance":0,"username":"YYY","createdAt":"2017-07-03T04:50:15.701Z","updatedAt":"2017-07-03T04:50:15.701Z","objectId":"bArtfV7eLH"},"currentRole":"Admin","sessionToken":"Qwd2BgpXFSsEUFt/VlxYFnoKBVsuVQxQFXwGU19/BglRQw=="} functionName=registerThenLoginMember, token=XXX, name=Gg, gender=male, installationId=fd150a57-ed21-2752-be4b-b34930c153e4, deviceBrand=Xiaomi, deviceModel=HM NOTE 1W, systemName=Android, systemVersion=4.4.2, deviceLocale=en-US, deviceCountry=US, isEmulator=false, isTablet=false, appVersion=0.0.4.4, timeZone=Asia/Jakarta, deviceToken=fK42xhwSIGU:APA91bGCSEFkSdK5nWMX97MQ61Yh1zjrC0h4XvzgdCWIALYcN5XqudWZGOanKTLK_2Gd2a_ou_-pjl72rnjTd1hwkggGM4C_M4v67XwjAxAdZphRnjQCNx2QKP_RQ-BRFuehIbvhmKfL, deviceType=android, user=undefined

```

**Comment by pewh** [comment]
For now, what I can do is force user to logout after signup, then login again to update correct installationId in _Session.Very weird :/

**Comment by pewh** [comment]
My project case now has changed. Client need refactor login/register process with twilio SMS verification. So, `register -> logout -> login` process make no sense again because it will send 2x SMS verification and affect twilio credit. I hope somebody look this issue, because I didn't know why this bug is happen.

Thanks.

**Comment by flovilmart** [comment]
If you’re not using the experimental direct access, this should be opened as a new issue as this issue was closed 6 months ago as solved

**Comment by pewh** [comment]
I couldn't test Parse version used by OP because I use postgresql and it only able run on new version. I guess there's a bug on version I've used. I just guess. Maybe somebody can test snippet which I'd post above, to make a proof if this error is happen.

**Comment by flovilmart** [comment]
Again, your issue is unrelated to the issue that’s described here and closed. Please open a new issue by filling the issue template correctly.
