### ISSUE TITLE
Parse test suite queries

### ISSUE THREAD

**Issue by rnagpal** [ParsePlatform/parse-server#316]
I'm getting started running this Parse test suite and had couple of queries:

1. Is there a difference between running the tests via "npm test" or "jasmine" from the root folder?
2. Will these tests run against a Mongo server that has SSL enabled?
3. Do these tests require me to start a parse server or they run against only mongodb server when I run they through "jasmine"?

**Comment by drew-gross** [comment]
1. Running from npm-test will also build the code coverage report
2. no
3. Nope `npm test` or using `jasmine` will both run a server within the tests.
