### ISSUE TITLE
Parse doesn't clear fs.chunks after a upload

### ISSUE THREAD

**Issue by hydex86** [ParsePlatform/parse-server#3161]
Hi, I'm using parse-server in Heroku + mlab. 

My client app uploads files to the server. Yesterday my client app was receiving an error 130 when saving a file to the server. I started to investigate and I found there was a collection called fs.chunks with 1 Gb of data, but the collection who stores files only had 50 Mb. 

I think fs.chunks uploaded should be deleted after the save process completes successfully, isn't it? Which is the best way to manage this?

**Comment by flovilmart** [comment]
Not sure about that, but the memory error you mention is real :)

**Comment by yangkghjh** [comment]
The collection fs.chunks is where the files binary saved.And the fs.files collection save same file info.The collection who stores files just store the file names.

**Comment by hydex86** [comment]
Thanks @yangkghjh , you're right. I close this issue

**Comment by flovilmart** [comment]
@yangkghjh @hydex86 that doesn't explain the memory retention issue, is it in the express middleware then&

**Comment by hydex86** [comment]
@flovilmart which memory retention issue are you talking about? Not sure if you found anything ese thanks to this :)

**Comment by flovilmart** [comment]
`I started to investigate and I found there was a collection called fs.chunks with 1 Gb of data, but the collection who stores files only had 50 Mb.`

The collection is in the database right? so that's not the process memory but the database?

**Comment by hydex86** [comment]
As @yangkghjh I was wrong. Data stored in fs.chunks are real files. The collection where I store the PFFiles would be pointers to those fs.chunks.
