### ISSUE TITLE
[Improvement] Refactor oauth into auth, make it all adapters

### ISSUE THREAD

**Issue by flovilmart** [ParsePlatform/parse-server#3175]
The oauth architecture has been a bit overlooked and begs for a refactor into a proper adapter architecture.

What needs to be done:

- deprecate `oauth` options (warn in the console), replace by `auth`
- Provide the vanilla / empty adapter
- let `auth` hash behave like other adapters:

### Known / provided methods
- verify that the hash in the map is an existing adapter
- load the existing adapter with the value passed from the options

### Unknown providers
- the key in the hash is not a provided method
- use the adapter loader mechanism

For 2.3.0, the oauth will be deprecated, introducing the `auth` option, for 2.4.0, the oauth option will be completely removed.

**Comment by flovilmart** [comment]
Closing as implemented in 2.3.0

**Comment by nitrag** [comment]
FYI: Broken links at bottom of page.

https://github.com/ParsePlatform/parse-server/wiki/OAuth--and-Custom-Authentication

**Comment by flovilmart** [comment]
Thanks @nitrag, just fixed those!

**Comment by Fedeorlandau** [comment]
@flovilmart Hi, how are you? Is there any example of how to migrate parseServerOptions.oauth into auth?
Thanks!

**Comment by flovilmart** [comment]
There's no need to migrate, just replace...
