### ISSUE TITLE
S3 Adapter Error: S3Adapter requires option '${key}' or env. variable ${env}

### ISSUE THREAD

**Issue by bhallaheemanshu** [ParsePlatform/parse-server#3182]
My node.js application and using s3adapter for fileadapter but getting error in S3 adapter parameter 'bucket_name'. I have done setting Environment variable on Heroku and environment variables are also declared in .env file. Files of code is shown below -

**Contents of .ENV Files**

S3_ACCESS_KEY=REDACTED
S3_SECRET_KEY=REDACTED

S3_BUCKET_NAME=ovote
DATABASE_URI='REDACTED'

**My App.js Code:**

// Example express application adding the parse-server module to expose Parse
// compatible API routes.

var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var S3Adapter = require('parse-server').S3Adapter;

var path = require('path');
var cors = require('cors');

var corsOptions = {
  origin: "https://ovote.parseapp.com"
}

var databaseUri = process.env.DATABASE_URI || process.env.MONGODB_URI;

if (!databaseUri) {
  console.log('DATABASE_URI not specified, falling back to localhost.');
}

var api = new ParseServer({
  databaseURI: databaseUri || 'REDACTED',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/xxxx/xxxxx/main.js',
  appId: process.env.APP_ID || 'xxxx-xxxx',
  masterKey: process.env.MASTER_KEY || 'xxxxx-xx-xxxxx', //Add your master key here. Keep it secret!
  clientKey: process.env.CLIENT_KEY || 'xxxxx-xx-xxxxx', //Add your client key here. Keep it secret!
  fileKey: process.env.PARSE_FILE_KEY || 'xxxxx-xxxxxxx',
  serverURL: process.env.SERVER_URL || 'https://xxxx-server.herokuapp.com/parse',  // Don't forget to change to https if needed
  publicServerURL: process.env.SERVER_URL || 'https://xxxxx-server.herokuapp.com/parse',
  // Your apps name. This will appear in the subject and body of the emails that are sent.
  appName: 'appname',
  // The email adapter
  emailAdapter: {
    module: 'parse-server-simple-mailgun-adapter',
    options: {
      // The address that your emails come from
      fromAddress: process.env.MAILGUN_ADDRESS,
      // Your domain from mailgun.com
      domain: process.env.MAILGUN_DOMAIN,
      // Your API key from mailgun.com
      apiKey: process.env.MAILGUN_API_KEY,
    }
  },
  filesAdapter: new S3Adapter(
    process.env.S3_ACCESS_KEY,
    process.env.S3_SECRET_KEY,
    "ovote",
    {directAccess: true, bucketPrefix : 'prod/'}
  ),
  push: {
    android: {
      senderId: 'xxxxxxxxxxxx', // The Sender ID of GCM
      apiKey: 'server-key' // The Server API Key of GCM
    },
    ios: [
      {
        pfx: 'push/ios_prod.p12', // Prod PFX or P12
        bundleId: 'com.xxxx.ovote',
        production: true // Prod
      },
      {
        pfx: 'push/ios_dev.p12', // Dev PFX or P12
        bundleId: 'com.xxxx.ovote',
        production: false // Dev
      }
    ]
  },
  facebookAppIds : 'xxxxxxxxxxxx',
  oauth: { facebook: { appIds: 'xxxx' }}
});

var apiDev = new ParseServer({
  databaseURI: process.env.DATABASE_URI_DEV || 'REDACTED',
  cloud: process.env.CLOUD_CODE_MAIN_DEV || __dirname + '/cloud/dev/main.js',
  appId: process.env.APP_ID_DEV || 'xxxxx-xxx-xxxxx',
  masterKey: process.env.MASTER_KEY_DEV || 'xxxxx-dev-mk-xxxxxx', //Add your master key here. Keep it secret!
  clientKey: process.env.CLIENT_KEY_DEV || 'xxxxx-dev-ck-xxxxxx', //Add your master key here. Keep it secret!
  fileKey: process.env.PARSE_FILE_KEY_DEV || 'xxxxx-dev-xxxxxxx',
  serverURL: process.env.SERVER_URL_DEV || 'https://xxxxx-server.herokuapp.com/dev/parse',  // Don't forget to change to https if needed
  publicServerURL: process.env.SERVER_URL_DEV || 'https://xxxxx-server.herokuapp.com/dev/parse',
  // Your apps name. This will appear in the subject and body of the emails that are sent.
  appName: 'appname',
  // The email adapter
  emailAdapter: {
    module: 'parse-server-simple-mailgun-adapter',
    options: {
      // The address that your emails come from
      fromAddress: process.env.MAILGUN_ADDRESS,
      // Your domain from mailgun.com
      domain: process.env.MAILGUN_DOMAIN,
      // Your API key from mailgun.com
      apiKey: process.env.MAILGUN_API_KEY,
    }
  },
  filesAdapter: new S3Adapter(
    process.env.S3_ACCESS_KEY,
    process.env.S3_SECRET_KEY,
    process.env.S3_BUCKET_NAME,
    {directAccess: true, bucketPrefix : 'dev/'}
  ),
  push: {
    android: {
      senderId: 'xxxxx', // The Sender ID of GCM
      apiKey: 'xxxxx' // The Server API Key 
    },
    ios: [
      {
        pfx: 'push/ios_prod.p12', // Prod PFX or P12
        bundleId: 'com.xxxxx.ovote',
        production: true // Prod
      },
      {
        pfx: 'push/ios_dev.p12', // Dev PFX or P12
        bundleId: 'com.xxxxx.ovote',
        production: false // Dev
      }
    ]
  },
  facebookAppIds : 'xxxxxx',
  oauth: { facebook: { appIds: 'xxxxxxxx' }}
});

// Client-keys like the javascript key or the .NET key are not necessary with parse-server
// If you wish you require them, you can set them as options in the initialization above:
// javascriptKey, restAPIKey, dotNetKey, clientKey

var app = express();

bodyParser = require('body-parser');
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

// Serve static assets from the /public folder
app.use('/public', express.static(path.join(__dirname, '/public')));

// Serve the Parse API on the /parse URL prefix
var mountPath = process.env.PARSE_MOUNT || '/parse';
app.use(mountPath, api);

// Serve the Parse Dev API on the /parsedev URL prefix
var devMountPath = process.env.PARSE_MOUNT || '/dev/parse';
app.use(devMountPath, apiDev);

// Parse Server plays nicely with the rest of your Web Routes
app.get('/', function(req, res) {
  res.status(200).send('Welcome to oVote Parse Server!');
});

var SmsManagerDev = require('./cloud/dev/sms/SmsManager');
var SmsManagerProd = require('./cloud/prod/sms/SmsManager');

app.get('/sms_bridge_prod', function(req, res) {

      SmsManagerProd.smsBridge(req, res);

  });
app.get('/sms_bridge_dev', function(req, res) {

      SmsManagerDev.smsBridge(req, res);

  });

app.post('/sendPush', cors(corsOptions), function(req, res) {
  Parse.Cloud.run('sendPushNotif', {
    notifText: req.body.notifText,
    notifObjectIds: req.body.notifObjectIds
  }, {
    success: function(data) {
      res.status(200).send(data);
    },
    error: function(err) {
      res.status(500).send(err);
    }
  });

});

var port = process.env.PORT || 1337;
var httpServer = require('http').createServer(app);
httpServer.listen(port, function() {
    console.log('parse-server-example running on port ' + port + '.');
});

// This will enable the Live Query real-time server
//ParseServer.createLiveQueryServer(httpServer);
```
**Error:**

```
$ node index.js

F:\ovote-web\node_modules\parse-server-s3-adapter\lib\optionsFromArguments.js:8
    throw `S3Adapter requires option '${key}' or env. variable ${env}`;
    ^
 S3Adapter requires option 'bucket' or env. variable S3_BUCKET
```

**Comment by skinp** [comment]
@bhallaheemanshu you leaked a lot of credentials in there. I redacted them, but you should rotate the S3 keys and your Mongo password.

**Comment by flovilmart** [comment]
thanks @skinp

**Comment by acinader** [comment]
@bhallaheemanshu your constructor:

your adapter constructor isn't valid.  This should work:
```
filesAdapter: new S3Adapter({
  accessKey: process.env.S3_ACCESS_KEY,
  secretKey: process.env.S3_SECRET_KEY,
  bucket: "ovote" },
  {directAccess: true, bucketPrefix : 'prod/'}
),
```

If you want to understand the many ways you can configure the adapter, looking at the tests is a good place:  https://github.com/parse-server-modules/parse-server-s3-adapter/blob/master/spec/test.spec.js

**Comment by bhallaheemanshu** [comment]
@skinp Thanks 

@acinader Thanks for code suggestion i am going to check it

**Comment by bhallaheemanshu** [comment]
@acinader 

Immediately after updating that code i didn't got S3 adapter error but getting below one regarding APNS

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
F:\ovote-web\node_modules\parse-server-push-adapter\lib\ParsePushAdapter.js:80
          throw _iteratorError;
          ^

TypeError: _apn2.default.Connection is not a function
    at _loop (F:\ovote-web\node_modules\parse-server-push-adapter\lib\APNS.js:62:18)
    at new APNS (F:\ovote-web\node_modules\parse-server-push-adapter\lib\APNS.js:113:7)
    at new ParsePushAdapter (F:\ovote-web\node_modules\parse-server-push-adapter\lib\ParsePushAdapter.js:63:40)
    at loadAdapter (F:\ovote-web\node_modules\parse-server\lib\Adapters\AdapterLoader.js:20:16)
    at loadAdapter (F:\ovote-web\node_modules\parse-server\lib\Adapters\AdapterLoader.js:13:12)
    at new ParseServer (F:\ovote-web\node_modules\parse-server\lib\ParseServer.js:273:64)
    at new _ParseServer (F:\ovote-web\node_modules\parse-server\lib\index.js:46:16)
    at Object.<anonymous> (F:\ovote-web\index.js:21:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
 npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by flovilmart** [comment]
What did you run?

**Comment by bhallaheemanshu** [comment]
node index.js

**Comment by flovilmart** [comment]
The issue you're seeing is with the push adapter.

**Comment by bhallaheemanshu** [comment]
ok i need to check with push adapter
