### ISSUE TITLE
Status API

### ISSUE THREAD

**Issue by Vortec4800** [ParsePlatform/parse-server#3184]
This is a feature request for an API call that can be made on the server that checks basic server health. Something like

`https://server.myapp.com:1337/parse/status`

That could return

`{"status": "healthy"}`

as long as it had a connection to the Mongo DB and everything was looking good. Does something like this already exist? I can take a stab at developing the route myself if someone could point me in the direction as to where in the code I can check for a healthy database, and any suggestions on other server health stuff that could be checked our presented.

**Comment by flovilmart** [comment]
Such endpoint has already been added under /health it returns 200 if running

**Comment by Vortec4800** [comment]
Ah I see, looks like this was just added in the last version, and I haven't updated yet. Thanks for the heads-up.

**Comment by flovilmart** [comment]
ON that note, if you want to report more in-depth infos, any PR would be appreciated :)
