### ISSUE TITLE
Time difference between Parse Server and clients (createdAt value)

### ISSUE THREAD

**Issue by iOSassou** [ParsePlatform/parse-server#3187]
I’ve finally migrated my production app to Parse Server 2.2.23 (hosted on NodeChef) and today I found one big issue:
I noticed a time difference between Parse Server and all the clients. When I create an object and save it, the “createdAt” date value is always approximately 40 seconds behind.

I did some testing and I’ve also received several reports from users that confirm this issue:
1) When they send a message at let’s say 3:15pm, the timestamp will say 3.14pm.
2) In Parse Dashboard and for any class, if I add a row manually (“Add Row” button + enter random values), the “createdAt” date is not correct
3) If I manually switch back to Hosted Parse, the bug is not present

This is a serious issue since my app is a messaging app and notifications are sent or dismissed based on the createdAt value.

Do you think it’s a Parse Server bug or a NodeChef issue with my deployment?

**Comment by flovilmart** [comment]
That's a likely a problem with nodechef server clocks

**Comment by iOSassou** [comment]
That's what I thought. I sent them an email for support, but I wanted to open an issue here just in case.

Thank you for your quick response
