### ISSUE TITLE
includeKey (iOS) or include(parse-dashboard): in query does not return object data

### ISSUE THREAD

**Issue by Droppix** [ParsePlatform/parse-server#3189]
Hello,

I try use "includeKey" (iOS) or/and api console (parse-dashboard) with "include", and then query does not return object data, but only PFRelation.

` 
PFQuery *wineQuery = [PFQuery queryWithClassName:@"WinesCellar2"];
 [wineQuery includeKey:@"wine"];
 
[wineQuery findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) {
        if (!error) {
    	     PFObject *obj = objects[0];
             NSLog(@"results: %@", obj);
  	}
 }];
`

<WinesCellar2: 0x6080002b93e0, objectId: Y9BRhhExpt, localId: (null)> {
    ACL = "<PFACL: 0x618000628ee0>";
    notes = "";
    quantity = 5;
    wine = "<PFRelation: 0x608000627080, 0x0.(null) -> Wines>";
}

version parse-server: 2.2.25
version parse-dashboard : 1.0.21
version parse iOS SDK : 1.14.2

Any idea?

Thanks

**Comment by flovilmart** [comment]
Include work on pointers fields, not relations. For relations you need to query the object of the relation.
