### ISSUE TITLE
clientKey is creating new columns for an existing class

### ISSUE THREAD

**Issue by venkataramanab** [ParsePlatform/parse-server#3190]
I just need to avoid new column creation by clientKey,
I tried `allowClientClassCreation = false` but it works only with new classes,
Is there any other way to avoid clients creating new columns in my existing classes ??

**Comment by flovilmart** [comment]
Use Class Level Permissions `addField`

http://parseplatform.github.io/docs/macos/guide/#class-level-permissions

**Comment by venkataramanab** [comment]
Thankyou @flovilmart 
i have another issue related to this,
writing the data to class by just ignoring the add field error,
i don't need to allow user to create new column but the remaining data present in object to be created as new row
