### ISSUE TITLE
`matchesKeyInQuery` returns 107 error when matching against an array

### ISSUE THREAD

**Issue by dpoetzsch** [ParsePlatform/parse-server#3195]
I want to use `matchesKeyInQuery` to check if the value of a key is in an array-typed column of the result of another column (similar to using `equalTo` to check if a value is contained in the array).

For example, I want to find all posts, where the author is in a group.

### Steps to reproduce

```javascript
it("should match a key in an array", function(done) {
  var AuthorObject = Parse.Object.extend("Author");
  var GroupObject = Parse.Object.extend("Group");
  var PostObject = Parse.Object.extend("Post");

  return new AuthorObject().save().then((user) => {
    const post = new PostObject({
      author: user
    });

    const group = new GroupObject({
      members: [user],
    });

    return Parse.Promise.when(post.save(), group.save());
  }).then((p) => {
    return new Parse.Query(PostObject)
      .matchesKeyInQuery("author", "members", new Parse.Query(GroupObject))
      .find()
      .then(r => {
        expect(r.length).toEqual(1);
        expect(r[0].id).toEqual(p.id);
        done();
      }, done.fail);
  });
});
```

#### Expected Results

The query returns the previously created `post`.

#### Actual Outcome

```
{"code":107,"message":"bad atom: [object Object]"}
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.25
  - Operating System:     Linux
  - Localhost or remote server? Local

- **Database**
  - MongoDB version: 3.2.11
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

**Comment by flovilmart** [comment]
We'll have a look before next release

**Comment by flovilmart** [comment]
Thanks for the detailed reproduction! Do you want to try to fix it?

**Comment by dpoetzsch** [comment]
At the moment I'm on a pretty tight schedule, maybe I'll manage to have a look at it on the weekend.

**Comment by flovilmart** [comment]
@dpoetzsch I managed to get some time to fix it! It's gonna be part of the next release :)
