### ISSUE TITLE
Internal error creating User with Facebook

### ISSUE THREAD

**Issue by nuborian** [ParsePlatform/parse-server#3203]
Hey,

i am creating a new user, linked to Facebook - So far no problem.

Now i want to add some fields along the registration, in my case username, first_name, last_name.

Error:
I don't know why, but it's only possible (for me) to include 2 addional fields - but not all 3. If i try all together i always receive an interal server error "500" from Parse.

Any idea what this is about?

**Comment by flovilmart** [comment]
Run the server with VERBOSE=1 and provide the logs please!

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.
