### ISSUE TITLE
can't login with Facebook anymore after 2.3.0 upgrade

### ISSUE THREAD

**Issue by markuswinkler** [ParsePlatform/parse-server#3208]
Describe your issue in as much detail as possible.

replaced 
`facebookAppIds: "myID"`
with 
`auth: { facebook: { appIds: ["myID" ] } }` 
and facebook login fails now with
`code=252, message=This authentication method is unsupported.`

worked before like a charm.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.0
  - Operating System:     Mac OS Sierra / NodeJS 6.9.1
  - Localhost or remote server? Localhost

**Comment by flovilmart** [comment]
Can you provide the logs please?

**Comment by flovilmart** [comment]
I found the issue, stay put :)

**Comment by flovilmart** [comment]
@markuswinkler this will be addressed with the mentioned PR, and I'll release soon 2.3.1 to make sure this issue don't stay there too long. Thanks for reporting

**Comment by markuswinkler** [comment]
great! Thank you for the quick fix! :)

**Comment by flovilmart** [comment]
Sorry for the inconvenience.

**Comment by flovilmart** [comment]
@markuswinkler can you tell me if pointing parse-server to "parseplatform/parse-server#latest", if all's good I'll release 2.3.1 ASAP!
Thanks man!

**Comment by markuswinkler** [comment]
works!

**Comment by flovilmart** [comment]
Awesome thanks!

**Comment by benitech** [comment]
@flovilmart 

what is the new setting for google oAuth?  earlier usage of oauth: {google: "true"} gives the following error after upgrading parse-server.

error: Error generating response. { Error: Cannot find module 'true'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at loadAdapter (/node_modules/parse-server/lib/Adapters/AdapterLoader.js:27:15)
at /node_modules/parse-server/lib/Adapters/Auth/index.js:78:57
at loadAuthAdapter (/node_modules/parse-server/lib/Adapters/Auth/index.js:86:7)
at Object.getValidatorForProvider (/node_modules/parse-server/lib/Adapters/Auth/index.js:111:28)
at /node_modules/parse-server/lib/RestWrite.js:263:58 code: 'MODULE_NOT_FOUND' } code=MODULE_NOT_FOUND

**Comment by flovilmart** [comment]
can you try no specifying anything? It should work as is.

**Comment by benitech** [comment]
removing oauth: {google: "true"} worked.

**Comment by flovilmart** [comment]
@benitech awesome!
