### ISSUE TITLE
Swift 3 Parse on Heroku login

### ISSUE THREAD

**Issue by alessandrogregotech** [ParsePlatform/parse-server#3209]
I have just started creating my new app with Parse SDK pointing to Parse Server deployed on Heroku and MongoDB. I am using Xcode and Swift 3. I cannot figure out how to set up my login page as teh ios guides for login state only: 
> Of course, after you allow users to sign up, you need to let them log in to their account in the future. To do this, you can use the class method logInWithUsernameInBackground:password: .

How can I login then?
![screen shot 2016-12-08 at 09 49 11](https://cloud.githubusercontent.com/assets/22665957/21003430/a1dc0ed4-bd2b-11e6-9eea-29661064c6f8.png)

**Comment by flovilmart** [comment]
Everything is described here:

http://parseplatform.github.io/docs/ios/guide/#users
