### ISSUE TITLE
create after attempt to login fails

### ISSUE THREAD

**Issue by kostiag** [ParsePlatform/parse-server#3210]
Code below fails. Replacing post with get will fail the same way. First get works fine. Doing only a single post without preceding get works as well.

Apache reports:
[Thu Dec 08 13:28:05.884330 2016] [proxy:error] [pid 1150] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:1337 (127.0.0.1) failed
[Thu Dec 08 13:28:05.884366 2016] [proxy_http:error] [pid 1150] [client 54.183.204.205:48418] AH01114: HTTP: failed to make connection to backend: 127.0.0.1

```javascript
`request.get({
     url: SERVER_NAME + '/parse/login',
     qs: {
      username: username,
      password: PARSE_USER_PASSWORD
      },
      headers: {
      'X-Parse-Application-Id': PARSE_APP_ID,
      'X-Parse-REST-API-Key': PARSE_API_KEY
     }
 },
 function (err, response, body) {
    //all good
 }
 // Not found. Likely the user doesn’t exist, we provision one
   if(response.statusCode === 404) {
    request.post({
    url: SERVER_NAME + '/parse/users',
    json: {
    username: username,
    password: PARSE_USER_PASSWORD,
    email: email,
    emailVerified: true
 },
 headers: {
   'X-Parse-Application-Id': PARSE_APP_ID,
   'X-Parse-REST-API-Key': PARSE_API_KEY,
   'Content-Type': 'application/json'
 }
 },
 function (err, response, body) {
   if (err) return callback(err);
   // user created, add sessionToken to user profile
   if (response.statusCode === 201) {
     return; 
 }
 **// GETtING** 
 **"<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>503 Service Unavailable</title>\n</head><body>\n<h1>Service Unavailable</h1>\n<p>The server is temporarily unable to service your\nrequest due to maintenance downtime or capacity\nproblems. Please try again later.</p>\n</body></html>\n"**
 return callback(new Error("The user provisioning returned an unknown error. Body: " +  JSON.stringify(body)));
 });
 }`
```

**Comment by flovilmart** [comment]
Looks like your sever shuts down. 

```
connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:1337 
```

Or that your SERVER_NAME is not properly configured

**Comment by kostiag** [comment]
well how would you explain that if I make a single call it works? This eliminates server name issue - I think. Shutdown after 1st call is possible but that means some kind of critical error with parse server, no?
 How can I trouble shoot this?

**Comment by flovilmart** [comment]
When opening an issue, there is an issue template, please fill it in, and reopen an issue will *All* relevant information.

**Comment by kostiag** [comment]
FIGURED IT OUT! permission on log file creation were throwing and error that was causing server to shut down and miss the second call. Thank you.
