### ISSUE TITLE
PFKeychainStore failed to set object for key 'currentUser', with error: -34018

### ISSUE THREAD

**Issue by alessandrogregotech** [ParsePlatform/parse-server#3212]
My Swift 3 app is connected to Parse-Server deployed on Heroku and MongoDB
I am getting this error continuosly in my app : 
> PFKeychainStore failed to set object for key 'currentUser', with error: -34018
![screen shot 2016-12-08 at 18 12 42](https://cloud.githubusercontent.com/assets/22665957/21019802/1ebf44a2-bd72-11e6-98fd-e923a2d31471.png)

I am trying to look for the current user in order not to make the user log in every time.
I am getting the eroor every time I press the log out button to see if my function works.

**Comment by flovilmart** [comment]
This is an issue with the iOS SDK, please refer to that repository.

Also, enable the keychain sharing entitlements as per:

See here: https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/1060
