### ISSUE TITLE
Parse-server 2.3.0 failing to start!

### ISSUE THREAD

**Issue by Cliffordwh** [ParsePlatform/parse-server#3215]
Describe your issue in as much detail as possible.

Upgraded to new version of parse. failing with :

`|parse-se | facebookAppIds is deprecated, please use { auth:          {facebook:            { appIds: [] }           }        }      }`

My ecosystem does not reference facebookAppIds at all or the ENV for it. 

```
{
  "apps" : [{
    "name"        : "parse-server",
    "script"      : "/usr/bin/parse-server",
    "watch"       : true,
    "merge_logs"  : true,
    "cwd"         : "/home/parse",
    "env": {
      "VERBOSE": "1",
      "PARSE_SERVER_CLOUD_CODE_MAIN": "/home/parse/cloud/main.js",
      "PARSE_SERVER_DATABASE_URI": "mongodb://###",
      "PARSE_SERVER_APPLICATION_ID": "#####",
      "PARSE_SERVER_MASTER_KEY": "#####",
      "PARSE_SERVER_FILE_KEY": "####",
      "PARSE_SERVER_JAVASCRIPT_KEY": "####",
      "PARSE_SERVER_REST_API_KEY": "####",
      "PARSE_SERVER_CLIENT_KEY": "###",
      "PARSE_SERVER_MOUNT_PATH" : "/",
      "PARSE_SERVER_FILES_ADAPTER" : "parse-server-s3-adapter",
      "S3_ACCESS_KEY" : "###",
      "S3_SECRET_KEY"  : "####",
      "S3_BUCKET" : "####",
      "S3_SIGNATURE_VERSION" :"v4",
      "S3_DIRECT_ACCESS" : true,
      "PARSE_SERVER_APP_NAME" : "##" ,
      "PARSE_PUBLIC_SERVER_URL" : "####",
      "PARSE_SERVER_PUSH" :  {"adapter" : "parse-server-onesignal-push-adapter",
                                             "oneSignalAppId": "###",
                                             "oneSignalApiKey": "####",
                             },
     "PARSE_SERVER_EMAIL_ADAPTER" : {
           "module": "parse-server-simple-mailgun-adapter",
                  "options": {
                  "fromAddress": "###",
                  "domain": "###",
                  "apiKey": "###",
                   }
      },
    }
  }]
}
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) :2.30
  - Operating System:     Ubuntu

**Comment by acinader** [comment]
@Cliffordwh there was a big in 2.3.0.  2.3.1 has been published to npm.  can you upgrade ad try again and see if that fixes?

**Comment by Cliffordwh** [comment]
@acinader  2.3.0 is the latest version on NPM at the moment!

**Comment by flovilmart** [comment]
also, 2.3.0 should not throw if really the option is not here:

```
/bin/parse-server --appId hellp --masterKey world
appId: hellp
masterKey: ***REDACTED***
port: 1337
host: 0.0.0.0
mountPath: /parse
maxUploadSize: 20mb
userSensitiveFields: email
serverURL: http://localhost:1337/parse

[34276] parse-server running on http://localhost:1337/parse
```

**Comment by Cliffordwh** [comment]
Will test 2.3.1! was just pushed.

**Comment by Cliffordwh** [comment]
same error on 2.3.1 Reverted back to 2.2.25 and all started well.

**Comment by flovilmart** [comment]
I guess you have a dangling environment variable or something else... I have no issue starting the server here.

**Comment by Cliffordwh** [comment]
Fresh copy locally works on 2.3.1!

**Comment by flovilmart** [comment]
so you have something that's off on your server which is good, as you were setting environments variables you are not aware of

**Comment by Cliffordwh** [comment]
@flovilmart could be the case. Will close this for now and dig in there.  Just out of interest, how would i set the new auth moving forward in the json above?  `PARSE_SERVER_AUTH_PROVIDERS`

**Comment by flovilmart** [comment]
Yes, exactly
