### ISSUE TITLE
Push Notification - Two apps using same Parse Serve

### ISSUE THREAD

**Issue by allen8300** [ParsePlatform/parse-server#3217]
My two apps (a free app and a pro app)point to the same parse database.
While only one app can send push notification successfully.

I have read everything on the Parse support / help pages and it appears that I am doing the right thing but failed.I have tried the way in  [https://github.com/ParsePlatform/parse-server/issues/2188](url)
But didn't work.

My p12 files' path are:
![screen shot 2016-12-08 at 6 05 13 pm](https://cloud.githubusercontent.com/assets/1751906/21048204/00a75ee6-be49-11e6-80a2-ccf4b174fcdc.png)

My cloud code in index.js are:
push: {
ios: [
{
pfx: __dirname +'/push_certs/DevPushLoveAgainPro.p12', // Dev PFX or P12
bundleId: 'com.app1',
production: false // Dev
},
{
pfx: __dirname +'/push_certs/ApplePushLoveAgainPro.p12', // Prod PFX or P12
bundleId: 'com.app1',
production: true // Prod
},
{
pfx: __dirname +'/push_certs/DevPushLoveAgainFree.p12', // Prod PFX or P12
bundleId: 'com.app2',
production: false // Prod
},
{
pfx: __dirname +'/push_certs/ApplePushLoveAgainFree.p12', // Prod PFX or P12
bundleId: 'com.app2',
production: true // Prod
}
]
}

**Comment by flovilmart** [comment]
can you re open the issue filling the issue template completely please?

**Comment by allen8300** [comment]
@flovilmart ,
 yes, thanks so much.  Created: [https://github.com/ParsePlatform/parse-server/issues/3219](url)

**Comment by allen8300** [comment]
@flovilmart , hello?

**Comment by flovilmart** [comment]
I haven't had time to look into it, but your new issue is again missing server logs etc... that doesn't help.

**Comment by allen8300** [comment]
Ok, thanks so much.

But can you let me know whether it's feasible that two apps sharing same parse db and notification can work in both apps ?

If feasible, can you point out the key points for me directly?

**Comment by flovilmart** [comment]
This issue is closed, ca you keep the conversation on the proper issue please?
