### ISSUE TITLE
Push Notification - Two apps sharing the same Parse Serve

### ISSUE THREAD

**Issue by allen8300** [ParsePlatform/parse-server#3219]
### Issue Description

My two apps (a free app and a pro app) point to the same parse database.

#### Expected Results
I want Push Notifications working in both two apps.

#### Actual Outcome
While for now, only one app can send push notification successfully.

### Steps to reproduce
Besides sending notifications by my apps, I also tried to send push by dashboard.
The result is same, only one app works, another fails to get the notification.
 
### Environment Setup
I'm trying the way in https://github.com/ParsePlatform/parse-server/issues/2188.
I also refer to following two links:
https://www.parse.com/questions/push-to-multiple-apps
http://stackoverflow.com/questions/37077737/multiple-apps-in-a-single-parse-server

But  all didn't work.

Thanks so much for helping out.

**Comment by flovilmart** [comment]
Can you provide the server logs, and init options as well as environment, version etc... i.e.: everything requested in the issue template?

**Comment by allen8300** [comment]
Thanks so much for replying. I'll try to collect more info later.

But before that,  can you simply let me know whether it's feasible that notification can work in both two apps  as well as sharing same parse db ?

If feasible, can you simply point out the key points for me directly to implement it ?

**Comment by maximeloizeau** [comment]
We successfully send pushes to different app environments (dev, staging, live) which have their own bundle id and certificates. So I don't see why you wouldn't be able to push to differents apps.

You just need to configure an array of credentials as shown in the linked issue.

**Comment by allen8300** [comment]
@maximeloizeau , thanks so much for replying.
I understand that it's feasible. And I also understand that I need to configure credentials.
Any other key points that I need to check to implement it?

**Comment by maximeloizeau** [comment]
Not really, just remember to register for push in the app.

And if you get any issues, start the server with the environment variable `DEBUG=apn*`

**Comment by allen8300** [comment]
@maximeloizeau , thanks so much for your reply. 
So how's it when it comes to SaShiDo?

**Comment by maximeloizeau** [comment]
It will be a bit different, you will configure it from their dashboard.
https://blog.sashido.io/how-to-set-up-ios-push-notifications-in-sashido/
