### ISSUE TITLE
Adding the APNs certificate, .p12, into server directory makes server crash

### ISSUE THREAD

**Issue by jolaroux** [ParsePlatform/parse-server#3227]
I'm trying to add the APNs function into my parse server, but whenever I put the code in, Heroku says Application Error and it won't load. This also happened when I had the server running locally.

Here is my index.js file, with XXX's being sensitive data. The XXX'd out parts work.

`var api = new ParseServer({`
`databaseURI: databaseUri || 'XXX',`
`cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',`
`appId: process.env.APP_ID || 'XXX',`
`masterKey: process.env.MASTER_KEY || 'XXX', //Add your master key here. Keep it secret!`
`serverURL: process.env.SERVER_URL || 'XXX',  // Don't forget to change to https if needed`
`liveQuery: {`
`classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions`
`}`
`push: {`
 `   ios: {`
  `      pfx: '/certs/lafcert.p12', // the path and filename to the .p12 file you exported earlier. `
   `     bundleId: 'XXX', // The bundle identifier associated with your app`
    `    production: false // Specifies which environment to connect to: Production (if true) or Sandbox`
    `}`
`}`
`});`

And here is my file directory, which I'm pushing to Heroku.

https://imgur.com/a/ZDm6N

Am I doing something wrong with the code? The Path and filename are correct, the bundle ID is correct, and production is false. However, the server won't run when I put that code in

**Comment by flovilmart** [comment]
What is the error?

**Comment by jolaroux** [comment]
This is the error that I'm getting:
http://imgur.com/a/lOIHO

**Comment by jolaroux** [comment]
When I run the server locally, these are the errors that I'm getting: 
http://imgur.com/a/F7a8N

**Comment by jolaroux** [comment]
I think I fixed it! I was missing a damn comma before the `push: {}` info
