### ISSUE TITLE
Insufficient Auth when Deleting a User According to Role-Level Permissions

### ISSUE THREAD

**Issue by matthewcarroll** [ParsePlatform/parse-server#3228]
### Issue Description

Hello,

I'm trying to use role-level permissions to manage users via the REST api, but having
an issue when a user tries to delete a user to which it has write access. The steps to reproduce are:

### Steps to reproduce

1. Create a regular user:

`curl -X POST 
  -H "X-Parse-Application-Id: appid" 
  -H "X-Parse-Revocable-Session: 1" 
  -H "Content-Type: application/json" 
  -d '{
  "username": "regular",
  "password": "ok",
  "ACL": {
    "*": {
      "read": false
    },
    "role:Manager": {
      "read": true,
      "write": true
    }
  }
}' 
http://localhost.:1337/parse/users
`

response:
`{
  "objectId": "TRajUEy59H",
  "createdAt": "2016-12-10T22:19:20.684Z",
  "sessionToken": "r:24450fb5f116bc287321774f1062b32a"
}`

2. Create a manager user:

`curl -X POST 
  -H "X-Parse-Application-Id: appid" 
  -H "X-Parse-Revocable-Session: 1" 
  -H "Content-Type: application/json" 
  -d '{
  "username": "manager",
  "password": "ok"
}' 
http://localhost.:1337/parse/users
`

response:
`{
  "objectId": "GBxQ2zCi4j",
  "createdAt": "2016-12-10T22:19:50.039Z",
  "sessionToken": "r:b5a27139fb16a7fc78fa6cdcab4469ce"
}`

3. Create a manager role and add a manager to it. The manager's object id is added with "objectId": "GBxQ2zCi4j":

`curl -X POST 
  -H "X-Parse-Application-Id: appid" 
  -H "Content-Type: application/json" 
  -d '{
        "name": "Manager",
        "ACL": {
          "*": {
            "read": true
          }
        },
        "users": {
          "__op": "AddRelation",
          "objects": [
            {
              "__type": "Pointer",
              "className": "_User",
              "objectId": "GBxQ2zCi4j"
            }
          ]
        }
      }' 
http://localhost.:1337/parse/roles
`

response:
`{
  "objectId": "IhVDMdNtrx",
  "createdAt": "2016-12-10T22:21:13.425Z"
}`

4. Have the manager user delete the regular user. The manager's token set in the X-Parse-Session-Token and the regular user's object id is appended to the path:

`curl -v -X DELETE 
  -H "X-Parse-Application-Id: appid" 
  -H "X-Parse-Session-Token: r:b5a27139fb16a7fc78fa6cdcab4469ce" 
http://localhost.:1337/parse/users/TRajUEy59H
`

response:
Cannot DELETE /parse/user/TRajUEy59H

#### Expected Results

The user with the Manager role is able to delete the regular user. 

#### Actual Outcome

A 404.

If I create the regular user above with a publically readable ACL, 
the response when the manager user tries to delete the regular user is a 400:

`{
  "code": 206,
  "error": "insufficient auth to delete user"
}`

### Environment Setup

- **Server**
  - parse-server: 2.3.1
  - node v6.9.2
  - macOS 10.12.1  

- **Database**
  - MongoDB version: mongodb v3.4.0
  - Localhost 

### Logs/Trace

`verbose: REQUEST for [DELETE] /parse/users/TRajUEy59H: {} method=DELETE, url=/parse/users/TRajUEy59H, host=localhost:1337, user-agent=curl/7.49.1, accept=*/*, x-parse-application-id=appid, x-parse-session-token=r:b5a27139fb16a7fc78fa6cdcab4469ce, `

`error: Error handling request: ParseError { code: 206, message: 'insufficient auth to delete user' } code=206, message=insufficient auth to delete user
[object Object]
`

**Comment by flovilmart** [comment]
The error you're seeing is totally normal and enforced by the code itself to prevent deleting users.

Only the user itself or the masterKey can delete the user.

See: [rest.del](https://github.com/ParsePlatform/parse-server/blob/master/src/rest.js#L42) and [Auth.couldUpdateUserId](https://github.com/ParsePlatform/parse-server/blob/master/src/Auth.js#L22)
