### ISSUE TITLE
Error 3840 for Parse logout/login calls

### ISSUE THREAD

**Issue by nehloo** [ParsePlatform/parse-server#3230]
I got Parse Server 2.2.22 running on AWS with Bitnami.

Every other Parse calls work perfect, but I'm getting this following error 3840 only when attempting to login a user with [PFUser logInWithUsernameInBackground].

```
error	NSError *	domain: @"NSCocoaErrorDomain" - code: 3840	0x000060800045bd20
@"NSDebugDescription" : @"JSON text did not start with array or object and option to allow fragments not set."
```

Monitoring the network, I'm getting these responses from my Parse server for the log in call:

```
URL:		http://myserver/parse/login
Response Code:	503 Service Unavailable
```

According to this issue on GitHub https://github.com/ParsePlatform/parse-server/issues/1855 it appears that this is related to the MongoDB version and it's a timeout issue, and they managed to fix it by editing this:

```
package.json
Edit dependency: "mongodb": "2.1.18"
```

But there is no "package.json" with this kind of config on Bitnami Parse Server, so I can't figure out what the similar fix would be for a Bitnami stack.

My MongoDB version is:

```
bitnami@ip-:/opt/bitnami/apps/parse/htdocs/logs$ mongod --version
db version v3.0.9
git version: 20d60d3491908f1ae252fe452300de3978a040c7
```

---

ATTEMPTED SOLUTION HAS FAILED:

I temporarily switched back to the original server "https://api.parse.com/1" and I was able to figure out what the error really was about:

```
@"code" : 137
@"error" : @"Only one session is allowed per user/installation pair"
```

So, it looks like a PFSession issue.

Therefore, I tried to logout the user with "PFUser logOutInBackgroundWithBlock", and clear the current session before I log them back in.

But while "https://api.parse.com/1" doesn't return any error during PFUser logout/login, my own server at "http://myserver/parse/login" with Parse Server 2.2.22 still returns this error invariably, for both "PFUser logOutInBackgroundWithBlock" and "PFUser logInWithUsernameInBackground":

```
error	NSError *	domain: @"NSCocoaErrorDomain" - code: 3840
@"NSDebugDescription" : @"JSON text did not start with array or object and option to allow fragments not set."
```

### Environment Setup

- **Server**
  - parse-server version 2.2.22
  - Operating System:     Linux on AWS
  - Hardware:             AWS
  - Localhost or remote server? AWS

- **Database**
  - MongoDB version: 3.0.9
  - Storage engine:  AWS
  - Hardware:        AWS
  - Localhost or remote server? AWS

Not sure what's going on. Had anybody else encountered this error 3840 on your own Parse Server during login/logout?

**Comment by flovilmart** [comment]
can you run the server with VERBOSE=1?

**Comment by nehloo** [comment]
Good call. If I start the server with "VERBOSE=1 node /opt/bitnami/apps/parse/htdocs/server.js" everything works very well, as expected. No more errors for "PFUser logOutInBackgroundWithBlock" and "PFUser logInWithUsernameInBackground".

But when I start the server with "sudo /opt/bitnami/ctlscript.sh restart parse" as usual (like I did for my previous notes above), the errors appear again for "PFUser logOutInBackgroundWithBlock" and "PFUser logInWithUsernameInBackground".

Since "server.js" is the very same for both ways of starting the server, I wonder if there is something else that "sudo /opt/bitnami/ctlscript.sh restart parse" does that drives the server to fail the login and logout calls. Any ideas?

**Comment by flovilmart** [comment]
Not really, you should probably look into the bitnami startup script and see what'/ going on there. As you mentioned everything is OK when running directly their server script, I'm closing that issue as it's on bitnami's side

**Comment by nehloo** [comment]
Final solution for others who may run Parse Server on AWS with Bitnami. Apparently, it was a issue with permissions on the "logs" folder. Fixed it with this:

`sudo chown daemon:daemon -R /opt/bitnami/apps/parse/htdocs/logs`
