### ISSUE TITLE
Setup CLP only allow to access by logged in users in Dashboard

### ISSUE THREAD

**Issue by zh-wowtv** [ParsePlatform/parse-server#3234]
I read [this](https://github.com/ParsePlatform/parse-server/issues/2759) . It recommends to do so in Cloud code or Client code. But I'm wondering if it's possible to do this in Dashboard?

**Comment by flovilmart** [comment]
It's not implemented in the dashboard yet.

**Comment by zh-wowtv** [comment]
Sorry, don't understand. That means anybody can access object in parse-server?

**Comment by flovilmart** [comment]
That depends upon your ACL,but yes. Visit the security section of the docs, everything'/ explained
