### ISSUE TITLE
LiveQuery not working in openshift

### ISSUE THREAD

**Issue by zh-wowtv** [ParsePlatform/parse-server#3243]
### Issue Description

I setup parse-server in OpenShift. It works fine except the LiveQuery doesn't work. The error message in the console of my browser:

> WebSocket connection to 'wss://mydomain.com/parse' failed: Error during WebSocket handshake: Unexpected response code: 403

The code for the server should be fine because I can run it locally without problem.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.1
  - Operating System:     OSX 10.12
  - Hardware:             Macbook Pro
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Openshift

- **Database**
  - MongoDB version: 3.7
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Openshift

Any idea? Thanks.

**Comment by zh-wowtv** [comment]
I notice my local call to websocket is something like **ws://**, but the call to openshift is **wss://**. Is this because I'm using https ?

**Comment by samarthagarwal** [comment]
Are you using Live Queries without an SDK? Can you share more information about how can I use Live Queries in my JS App without using the JS SDK. I am using REST for normal queries.

**Comment by zh-wowtv** [comment]
I'm using JS SDK. I don't think REST is possible for live query.
