### ISSUE TITLE
Any way to use Live Queries using REST 

### ISSUE THREAD

**Issue by samarthagarwal** [ParsePlatform/parse-server#3245]
Hi,

I am using Parse REST API in my Ionic 2 (using TypeScript) App because I could not find the proper modules and thus could not use the Parse Module in Angular 2 without giving errors. So, is there a way to use Live Queries using the REST calls?

**Comment by natanrolnik** [comment]
Hey @samarthagarwal, Live Queries require an open socket connection to work, so by definition they won't work using REST calls. [Read this for more.](https://www.pubnub.com/blog/2015-01-05-websockets-vs-rest-api-understanding-the-difference/). An ugly and bad for performance solution would be polling your Parse Server via REST API, but that's not recommended.

Have you tried using the [Parse JS SDK](https://github.com/parseplatform/parse-sdk-js), that supports Live Queries? If so, what's the error?

**Comment by ciekawy** [comment]
what if you don't want to depend on the Parse SDK?

**Comment by dplewis** [comment]
@ciekawy Its doable. If a LiveQuery sdk didn't exist you would do the following:

1. Find a good websocket or open connection library
2. Follow [Parse LiveQuery Protocol Specification](https://github.com/parse-community/parse-server/wiki/Parse-LiveQuery-Protocol-Specification)
3. Handle your own responses

You can connect with REST but you can't receive anything as the connection would close.

**Comment by ciekawy** [comment]
Thanks! thats exactly what I started guessing toward. Parse LiveQuery Protocol relays share a lot common with REST API as for query syntax.
