### ISSUE TITLE
request.installationId not set

### ISSUE THREAD

**Issue by steven-supersolid** [ParsePlatform/parse-server#325]
It seems installationId is not available in the request object in Cloud Code.

Example code:
`Parse.Cloud.define('GetInstallationId', function(request, response) {
	response.success('installationId ' + request.installationId);
});`

Calling locally using parse-server:
`curl \
  -H "X-Parse-Application-Id: XXX" \
  -H "X-Parse-Installation-Id: a" \
  -H "Content-Type: application/json" \
  -d '{}' \
  http://localhost:1337/parse/functions/GetInstallationId`

{"result":"installationId undefined"}

Calling on parse.com:
`curl \
  -H "X-Parse-Application-Id: XXX" \
  -H "X-Parse-REST-API-Key: YYY" \
  -H "X-Parse-Installation-Id: a" \
  -H "Content-Type: application/json" \
  -d '{}' \
  https://api.parse.com/1/functions/GetInstallationId`

{"result":"installationId a"}

**Comment by steven-supersolid** [comment]
I think this could be fixed in functions.handleCloudFunction(req)

      var request = {
        params: req.body || {},
        master: req.auth && req.auth.isMaster,
        user: req.auth && req.auth.user,
        installationId: req.info.installationId
      };

Will try and test once my setup is complete.

**Comment by steven-supersolid** [comment]
PR #338

**Comment by gfosco** [comment]
Merged 238. :+1:
