### ISSUE TITLE
How to create white label URLS in parse server ?

### ISSUE THREAD

**Issue by gowridev** [ParsePlatform/parse-server#3257]
How to create white label URLS in parse server (as this option is present in parse.com, Hosting and mails in App settings section) ?

**Comment by lenart** [comment]
Are you referring to Frame URL? See #3267 if that's what you're looking for.

P.S. Why did you leave the instructions in the comments?

**Comment by gowridev** [comment]
Thanks @lenart . I thought, i can't post comments without instructions set  (just updated the post)

**Comment by gowridev** [comment]
@lenart  could you please share sample "http://myserver.com/handle-parse-iframe" file . I am unable to navigate to the choose_password page and share user_managemet.html file , the one you are using. 

I have attached two files. which on i am supposed to use it.

[user_management.html.zip](https://github.com/ParsePlatform/parse-server/files/723384/user_management.html.zip)
[user_management_OLD.html.zip](https://github.com/ParsePlatform/parse-server/files/723385/user_management_OLD.html.zip)
