### ISSUE TITLE
Sign up Rest api is not working

### ISSUE THREAD

**Issue by swapneshran** [ParsePlatform/parse-server#3259]
After hitting the Sign Up  rest api is not working . User value is not getting inserted inside User class. It is getting created in another calss named User. 
It worked after chaning the classes name **users** to **_User**

### Steps to reproduce

1.  I am using postman plugin to make the ap call to 
http://localhost:1337/parse/classes/users

Out put 

#### Expected Results

Output: {"objectId":"678DcnvNX5","createdAt":"2016-12-20T09:21:10.623Z","sessionToken":"r:0815e33f1e9eb909b1a36ef19300ea6b"}

#### Actual Outcome

Output: {"objectId":"h2ZATO0HP0","createdAt":"2016-12-20T09:19:19.974Z"}

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.1
  - Operating System:     Windows
  - Hardware:            Core 2 Duo, RAM 8GB
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost

- **Database**
  - MongoDB version:  v3.4.0
  - Storage engine: wiredTiger
  - Hardware:       Core 2 Duo, RAM 8GB
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

**Comment by bohemima** [comment]
The REST Api Guide says you should POST to /users, not /classes/users - ignore the /1 and api.parse.com parts.

> To sign up a new user, send a POST request to the users root. You may add any additional fields. For example, to create a user with a specific phone number:
> 
> 
> curl -X POST \
>   -H "X-Parse-Application-Id: ${APPLICATION_ID}" \
>   -H "X-Parse-REST-API-Key: ${REST_API_KEY}" \
>   -H "X-Parse-Revocable-Session: 1" \
>   -H "Content-Type: application/json" \
>   -d '{"username":"cooldude6","password":"p_n7!-e8","phone":"415-392-0202"}' \
>   https://api.parse.com/1/users

**Comment by swapneshran** [comment]
My Bad.It worked fine.After removing classes.

Thanks And Regards
Swapnesh
