### ISSUE TITLE
Can't stream video from pffile - iOS

### ISSUE THREAD

**Issue by Liquicit** [ParsePlatform/parse-server#326]
I can save pffile's completely fine to heroku using mongoLab. I make sure to set the content MIME type as "video/mp4". 

However, when I retreive the PFFile's url, I can't stream the video from iOS using AVPlayerViewControlle.

The AVPlayerViewController just shows a crossed out play button!?

I consulted the mongoLab help team and they said it would be something to do with the parse server or possibly heroku!? 

If I use the EXACT same code but swap from my heroku server running parse server to the NORMAL parse server ( the one that is shutting down ) I can stream video perfectly fine on iOS.

Can someone else please try streaming a video from a heroku parse server using mongoLab / mongoDB to store data?

Thanks.

**Comment by rosarioconti** [comment]
Once you change the server url, the file get saved on that server (heroku in this case).
 but it tries to download from the original files.parse.com server location where the file is not there. 
At least from what I tried so far debugging it.
 I'm trying to fix myself but I guess someone should have a fix soon for this.

**Comment by gateway** [comment]
btw prob a good idea to push video files in the future to s3 bucket instead of storing these files in a database.  You can enable s3 no as a file adaptor.

**Comment by rosarioconti** [comment]
Try this :
https://github.com/ParsePlatform/parse-server/issues/308

**Comment by gfosco** [comment]
There's been a lot of changes to the files functionality.  Can you please re-open and provide more information if you're still experiencing this issue?  Thanks.

**Comment by indiandragon** [comment]
[Solved] The solution is given by @Bragegs here - https://github.com/ParsePlatform/parse-server/issues/1440#issuecomment-212815625 . In short, parse-server doesn't seem to be supporting streaming of audio/video and @Bragegs code enables it. I hope it get's PR and parse team looks into it.

**Comment by manishsangwan** [comment]
Does not work for S3Adapter.

**Comment by flovilmart** [comment]
Should work with S3 if you configure direct access

**Comment by manishsangwan** [comment]
I have already enabled direct access in S3Adapter configurations.

> filesAdapter: new S3Adapter(
>         settings.s3AccessKey,
>         settings.s3SecretKey,
>         settings.s3BucketName,
>         settings.s3RegionName,
>         {directAccess: true}
>     )
