### ISSUE TITLE
Triggering particular function inside afterSave

### ISSUE THREAD

**Issue by srameshr** [ParsePlatform/parse-server#3268]
### Issue Description

How do I trigger a particular function inside ```afterSave``` for a given collection.

As of now I manually set a column called ```updateType```  and then inside the afterSave block I check for the value of ```updateType``` on the request object.

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

**In Parse.Cloud.define()**
```
  var query = new MyCollection();
  query.set("updateType", "update-1");
  query.save();
```

**In Parse.Cloud.afterSave()**

```
Parse.Cloud.afterSave('MyNewCollection', function(request, response) {
  function a() {
  }

  function b() {
  }

  if(request.updateType === 'updated-1') {
    a(); // Call function a
  }
});
```

Is there any other way to do this. Any option that lets me choose what block of code should be executed inside ```afterSave``` after a collection had been saved.

#### Expected Results

NONE

#### Actual Outcome

NONE

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.0
  - Operating System:     MAC OSX 10.11.16 EL Capitan
  - Hardware: 
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost

- **Database**
  - MongoDB version: db version v3.0.12
  - Storage engine:  Default storage
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Localhost

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

[FILL THIS OUT]

**Comment by natanrolnik** [comment]
@srameshr have you tried moving the `function a()` declaration outside of `Parse.Cloud.afterSave`?

**Comment by srameshr** [comment]
@natanrolnik Sorry, I dont understand how would that help. My point is, is there any way to pass some data from ```Collection.save()``` so that it appears in ```afterSave```'s ```request``` object.

As I have pointed out earlier, I am creating a column called ```updateType``` in my collection and setting it to some value each time on ```Collection.save()```.

**Comment by natanrolnik** [comment]
@srameshr Yes, there is, and this is the exact reason why the `beforeSave` and `afterSave` hooks exist.

You can do:

`var myObject = request.object;` to access the object;

And then `var updateType = myObject.get("updateType")`;

You can [read the docs here](http://parseplatform.github.io/docs/cloudcode/guide/#beforesave-triggers) for more examples.

**Comment by natanrolnik** [comment]
I also recommend reading the [JavaScript SDK guide](http://parseplatform.github.io/docs/js/guide/).

**Comment by srameshr** [comment]
@natanrolnik Tried that. It does not work the way I want. I am trying to set a property on request object in ```beforeSave``` and also trying to access the same property on the request object in ```afterSave```. It gives out ```undefined```

**Comment by natanrolnik** [comment]
Can you post some of your code?

**Comment by srameshr** [comment]
@natanrolnik Never mind. Setting a column called ```updateType``` makes more sense to my use case.

**Comment by natanrolnik** [comment]
So it's working now?

**Comment by srameshr** [comment]
Not with the beforeSave method.

**Comment by natanrolnik** [comment]
So could you give some extra information? What are you trying, what are the logs you see (when running with `VERBOSE=1`)?

**Comment by srameshr** [comment]
I will. Give me sometime.

**Comment by srameshr** [comment]
@natanrolnik Here is what I am trying to achieve:
Consider ```User``` class. Now I have 3 parse ```define``` functions that modify and save the ```User``` collection.
```
Parse.Cloud.define('one', (request, response) => {
  // do some manipulation and save user object
})

Parse.Cloud.define('two', (request, response) => {
  // do some manipulation and save user object again
})

Parse.Cloud.define('three', (request, response) => {
  // do some manipulation and save user object again
})
```

Now the ```afterSave``` block

```
Parse.Cloud.afterSave(Parse.User, () => {

  // After save has 3 different functions which has to be run, based on which Parse.Cloud.define() function was called.

  function one() {}
  function two() {}
  function three(){}
  
  if( Parse.Cloud.define('one') was called ) {
    one() 
  }
  if( Parse.Cloud.define('two') was called ) {
    two() //
  }
  // So on
    
});
```

Now, ```afterSave``` will be triggered after all the ``` Parse.Cloud.define``` blocks. How do I identify, which ```Parse.Cloud.define``` block triggered the ```afterSave``` inside the ```afterSave``` so that I can invoke the right function.
