### ISSUE TITLE
Network Error on migration from Parse.com

### ISSUE THREAD

**Issue by rhymes** [ParsePlatform/parse-server#3269]
Hi, we are trying to migrate away a development DB we've forgot to migrate earlier but the migration tool in the Dashboard returns us the following error:

![screen shot 2016-12-21 at 2 19 48 pm](https://cloud.githubusercontent.com/assets/146201/21392115/b5e502a6-c78e-11e6-9c08-826c58d7c476.png)

We're using a Sandbox plan (in AWS US East) from mlab.com for this migration.

We've successfully migrated many app databases (10+) in the past to mLab following the migration guide so I'm not sure what's going on.

Any input would be greatly appreciated.

**Comment by fredrik-sogaard** [comment]
I'm seeing this as well with our migration to mLabs. I see this in the console: 
![image 2016-12-21 at 3 34 02 pm](https://cloud.githubusercontent.com/assets/764318/21393548/2efb54c8-c795-11e6-90af-11784bb09f88.png)

**Comment by fredrik-sogaard** [comment]
Tried it now and everything looks to be running as i should. Guess it was temporary error.

**Comment by rhymes** [comment]
@fredrik-sogaard same here, I'm going to close this.
