### ISSUE TITLE
Please Update Parse-SDK-Android

### ISSUE THREAD

**Issue by sashakhail** [ParsePlatform/parse-server#3275]
Respectable Sir / Team

Please update your Parse Android SDK instead of updating server so contentiously. This SDK is not much stable, It gives okhttp errors, Okhttp and parseokhttp conflicts means its behavior is intermittent, Whenever I download file with http or https its give me java.net.UnknownHostException exception or other error some thing like okhttp, and other time same code and same file / same URL works fine, means it behavior is intermittent.

Please Do something and especially at least respond.
Thanks
SashaKhail

**Comment by natanrolnik** [comment]
Hi @sashakhail.

The Android SDK is also open source - https://github.com/ParsePlatform/Parse-SDK-Android
If you have a specific and reproducible issue, please open over there. Or even better - propose a fix in a Pull Request!
