### ISSUE TITLE
Parse -PHP -SDK

### ISSUE THREAD

**Issue by soniurvashi11** [ParsePlatform/parse-server#3277]
I have a PHP Website which is using Parse -PHP SDK.
May I have steps/understanding, what changes i need to do in the project itself?
I have migrated my db already to mongolab.What I need to do next?

**Comment by natanrolnik** [comment]
Hey @soniurvashi11, I would recommend you going over the [Migration Guide](https://parse.com/migration) and the [Parse Server Guide](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide).

If you already migrated the DB to mLab, the next steps are deploying your own Parse Server instance, and then changing the Server URL on the PHP SDK to point to your new server.
