### ISSUE TITLE
how do i get the source code so that i can modify the max file size from 20mb to 40mb?

### ISSUE THREAD

**Issue by pupoo** [ParsePlatform/parse-server#3278]
how do i get to the source code so that this can be modified?

**Comment by greggmojica** [comment]
What do you need to modify? Image uploads?

**Comment by pupoo** [comment]
I was just looking at making the maximum file size that the server can hold be larger than 20MB.  i have some audio files that ti want to store on the server that will be downloaded by user and played in the app.

at the moment 20MB per file is the most i can upload through the dashboard.

**Comment by greggmojica** [comment]
So you are trying to upload the file? Files uploaded through the server must edit the nginx file limit.

**Comment by pupoo** [comment]
Yeah just manual uploading, there should be no need to programatically uploading such large files.

i am unsure what this nginx file is or how to get to it.  I have the bitnami server running on amazon ec2 and haven’t come across that browsing through the contents with the SSH.

**Comment by greggmojica** [comment]
http://stackoverflow.com/questions/4947107/nginx-upload-client-max-body-size-issue

**Comment by pupoo** [comment]
thank you!

**Comment by natanrolnik** [comment]
@pupoo was your issue solved? Can we close it?

**Comment by pupoo** [comment]
i was offered a solution but i do not think it will work for my current set up.  Currently using bitnami parse server on AQS ec2 so there does not seem to be a way of modifying these config files.  when logging into the server via ssh the only config file that is available is server.js and this can not be modified without crashing the server.

**Comment by natanrolnik** [comment]
@pupoo I recommend you one of the following things:

Checking if you are able to change the [`maxUploadSize`](https://github.com/ParsePlatform/parse-server/blob/master/src/ParseServer.js#L119) in the server initialization. Usually it's done in the server.js or index.js file. If it crashes the server, probably you need to stop, modify and start it again. I think you can check their docs here: https://docs.bitnami.com/aws/apps/parse/

If you want more customization, and they are not able to provide you a good answer on how to modify that property, I suggest you to deploy your own instance of Parse Server directly on EC2 or Heroku, for example. This way you can customize it according to your needs and have a better control. Take a look at the [Parse Server Example ](https://github.com/parseplatform/parse-server-example) project.

As this is not a issue in Parse Server itself - `maxUploadSize` works as expected - I'm closing this issue, but feel free to add the solution you found as it may help other people that decided to use bitnami.
