### ISSUE TITLE
A migrated app just got hacked

### ISSUE THREAD

**Issue by ajamaica** [ParsePlatform/parse-server#3279]
When you enable the migration from parse using your mongo-url please create a user protected for that simple db. Also create a ssl conection to parse and be sure to disable the remote access when the migration is fully done. 

I recommend to use a automatic bot detection (like the one build in cloudfare), the server was unsupervised and I see all the logs that they use for the attack. Also change the port of the connection it may help a little. 

And please do not share the mongourl in anywebsite.

**Comment by natanrolnik** [comment]
Thanks, @ajamaica 
If you want, feel free to open a PR in the docs with your recommendations.
