### ISSUE TITLE
Parse-SDK-JS & MongoDB

### ISSUE THREAD

**Issue by laullon** [ParsePlatform/parse-server#328]
Hi,

Parse-SDK-JS (used on Cloud Functions) use the REST-API to access the Parse-Server by HTTP in order to get the data from the DB, and that looks an unnecessary detour to me, so...

Is there any plan to make Parse-SDK-JS connect the DB directly? or
Is there any plan to replace Parse-SDK-JS by something like Parse-SDK-MongoDB ?

**Comment by drew-gross** [comment]
No, we don't have anything like that in the works. I think the use case would be pretty small, as JS in the browser won't be able to use this anyway. We are also attempting to move away from being tied to mongo, and this would tie us even more to mongo.
