### ISSUE TITLE
Bypass ACL using LiveQuery

### ISSUE THREAD

**Issue by greggmojica** [ParsePlatform/parse-server#3280]
Someone posted this on StackOverflow. I have the same question: Can we bypass ACL using the masterKey in LiveQuery and if so how?

http://stackoverflow.com/questions/40880566/does-livequery-support-use-masterkey-to-bypass-acl-permission

**Comment by greggmojica** [comment]
@flovilmart Any ideas?

**Comment by MiLeung** [comment]
Would like to know if possible as well.

**Comment by rostopira** [comment]
Why it's closed?

**Comment by davimacedo** [comment]
Yes. It is possible to use the `useMasterKey` flag when using live query.
