### ISSUE TITLE
Will Parse.push work after shuttdown ?

### ISSUE THREAD

**Issue by jigneshk** [ParsePlatform/parse-server#3288]
Hello Team,

I have migrated my app from parse.com to parse server on my own server.

For push notification I have used parse.push as per the instruction given in following link.

https://github.com/ParsePlatform/parse-server/wiki/Push

Will it work after 28th January 2017 ? or I need to use some other option ?

Please let me know as soon as possible.

Thanks
Jignesh

**Comment by natanrolnik** [comment]
Hey @jigneshk 
If you are using any one of the Parse Server push adapters, and you can send push notifications from your own Parse Server instance, then you don't need to worry about the shutdown in regards to push.

**Comment by Heman6886** [comment]
I Have Setup the Whole Server and Database too and Library is redirection to my new server too but i want to know will it even after shutdown
