### ISSUE TITLE
Updating the documentation.

### ISSUE THREAD

**Issue by okaris** [ParsePlatform/parse-server#329]
I believe the documentation in the ReadMe file needs to be updated as new features are added and the existing are changed. I see a lot of people, including myself, wondering how to use the new Push feature added, or how to use S3 as the default file storage. I feel bad not being able to contribute but just giving opinion from the outside. Also is there a way to know who is working on what and what else needs working on, so maybe I can find something to help with. Please do keep up the good work!

**Comment by maysale01** [comment]
@okaris I think the S3Adapter was merged a bit prematurely as there is currently no test coverage.I wouldn't feel comfortable using it in production. Push support is still open: https://github.com/ParsePlatform/parse-server/pull/311. I think if you're looking to run this in any kind of customer facing environment at the moment you need to be prepared to get your hands dirty. But, I agree there should be some running road map and versioning planning.

**Comment by gateway** [comment]
+1

**Comment by rogerhu** [comment]
Added documentation here. :)https://github.com/codepath/android_guides/wiki/Configuring-a-Parse-Server

https://github.com/codepath/android_guides/wiki/Configuring-a-Parse-Server#support-push-notifications

**Comment by drew-gross** [comment]
We also haven't published a new version on NPM containing a lot of these changes. We'll make sure to better document these things before pushing version 2.0.8
