### ISSUE TITLE
npm start fails on Heroku (but not locally) due to module EventEmitterPubSub

### ISSUE THREAD

**Issue by johnnyg563** [ParsePlatform/parse-server#3291]
### Issue Description

My Parse Server works locally on my computer but when I deploy to Heroku the build looks to succeed but running the server fails because it can't find the module EventEmitterPubSub.  I have posted the logs below.   I've tried starting from scratch a few times now with Heroku and not sure what gives.

### Logs/Trace
<pre>
parse-server-example@1.4.0 start /app

node index.js

module.js:471
    throw err;
    ^

Error: Cannot find module '../Adapters/PubSub/EventEmitterPubSub'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object. (/app/node_modules/parse-server/lib/LiveQuery/ParsePubSub.js:10:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 3.13.0-105-generic
npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! parse-server-example@1.4.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parse-server-example@1.4.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parse-server-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js</pre>

**Comment by johnnyg563** [comment]
Appears it was an issue with the initial install and then was getting cached.

Ran again with <pre>NODE_MODULES_CACHE=false</pre> and it worked.

**Comment by umrgit123** [comment]
Thank you so much johnnyg563.  Looked all over. Your solution worked. Thanks again!!

**Comment by codesculpture** [comment]
I done this in heroku settings config var but it dint worked
![Screenshot (134)](https://user-images.githubusercontent.com/63452117/120796267-41671280-c558-11eb-83eb-87a84e62658c.png)
