### ISSUE TITLE
Parser version 2.2.23 breaks var Parse = require('parse/node') in cloud code

### ISSUE THREAD

**Issue by mmarshak** [ParsePlatform/parse-server#3294]
I have in my main.js in the cloud directory the following statement - 
 var Parse = require('parse/node') in order that jslint with "use strict" will not complain that Parse is not define in Parse.Cloud.define(...).

With Parse server version 2.2.22 and lower it works fine, but with Parse server 2.2.23 and up I get the following error -

/Users/mmarshak/Projects/GoPapaya-Parse-Server/cloud/main.js:14
Parse.Cloud.define('hello', function(req, res) {
            ^

TypeError: Parse.Cloud.define is not a function.

I looked at the definition of parse/node and it is -
module.exports = require('./lib/node/Parse.js');

The Parse server lib directory does not have a node library at all.

**Comment by mmarshak** [comment]
I did a directory compare between 2.2.22 and 2.2.23 and it seems that with 2.2.23 Parser-server module include its node_modules the parse module, before that it did not include it. It was part of node_module of the root (of where index.js of express is located).

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.
