### ISSUE TITLE
Schema Attack

### ISSUE THREAD

**Issue by tcha-tcho** [ParsePlatform/parse-server#3295]
Hi!

Totally newbie's issue:

As creation of columns is automatic, what could we do to prevent our system of allow users to do this?

```javascript
        var GameScore = Parse.Object.extend("GameScore");
        var gameScore = new GameScore();
        for (var i = 0; i < 1000000; i++) {
          gameScore.set("x"+i, 1);
        }
        gameScore.save();
```
It's good that we have 'allowClientClassCreation' to play around. But I'm really concern about this issue. I don't know Parse as much as I would like, it has been only a week with the code, but it seems to be something painful to remove those columns from the system later on. And I think, probably, to have so many columns inside our Schema could potentially slow down the entire server.

I'm trying to make this code to sync a schema.json with server schema, but {__op: "Delete"} and creating fields is not responding as told in the REST API.

https://github.com/tcha-tcho/parse-sync-schemas

Well, thank you folks!
Tcha-Tcho

**Comment by bohemima** [comment]
Using CLP's

http://parseplatform.github.io/docs/ios/guide/#security
![screen shot 2016-12-29 at 14 06 50](https://cloud.githubusercontent.com/assets/195410/21544541/183c2ffa-cdd0-11e6-9c5b-7149524424c2.png)

**Comment by natanrolnik** [comment]
Pasting here for the record what @bohemima linked to:

> The second level of security is at the schema and data level. Enforcing security measures at this level will restrict how and when client applications can access and create data on Parse. When you first begin developing your Parse application, all of the defaults are set so that you can be a more productive developer. For example:
>
> * A client application can create new classes on Parse
> * A client application can add fields to classes
> * A client application can modify or query for objects on Parse
>
> ...
>
> Once you are confident that you have the right classes and relationships between classes in your app, you should begin to lock it down by doing the following:
> ...
> You can configure the client’s ability to perform each of the following operations for the selected class:
> ...
> 
> **Add fields**: Parse classes have schemas that are inferred when objects are created. While you’re developing your app, this is great, because you can add a new field to your object without having to make any changes on the backend. But once you ship your app, it’s very rare to need to add new fields to your classes automatically. You should pretty much always turn off this permission for all of your classes when you submit your app to the public.

With the [Parse Dashboard](https://github.com/parseplatform/parse-dashboard), it's very simple to do it. Just edit the Class Level Permissions, and disable the _Add Field_ checkbox.
