### ISSUE TITLE
Checklist for successful Parse migration by SashiDo 

### ISSUE THREAD

**Issue by parsegroundapps** [ParsePlatform/parse-server#3296]
Hey guys,

Check [our](https://www.sashido.io/) [checklist for successful migration](https://blog.sashido.io/checklist-for-successful-parse-migration-by-sashido/) from Parse.com or any Parse Server.

Feel free to ask question here or PM [@pivanov](http://parse-opensource.sapp.io/) at slack [#parseopensource](http://parse-opensource.sapp.io/)

Happy Holidays and Happy Coding :)
[SashiDo](https://www.sashido.io/) Team

**Comment by natanrolnik** [comment]
Good resource, @pivanov. Thanks for sharing. 

I'm closing it to keep the focus of the issues purely on issues. 

Maybe a PR for docs or adding it to the wiki is a better alternative.

**Comment by pivanov** [comment]
Hey,
Can you add the link to the Wiki? I think it will be useful.
