### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by oscarafuentes** [ParsePlatform/parse-server#3297]
I'd like to reach out to the Parse team with a security issue I found on the server. I would rather not publicly post it as an issue to this repository, but I can't find another way to reach out. If there is a private alternative, please let me know. Otherwise, I have no why of reaching out.

**Comment by flovilmart** [comment]
Reach out to me directly: florent(at)flovilmart(dot)com

**Comment by flovilmart** [comment]
@oscarafuentes, still haven't received your mail. We take security seriously. And would be able to provide a fix ASAP.
