### ISSUE TITLE
Certificate pinning / LetsEncrypt

### ISSUE THREAD

**Issue by kingmatusevich** [ParsePlatform/parse-server#33]
I think the SDKs should be updated with the capability to pin our server side certificates (presumably self signed), and thus it verifying the authenticity of the server upon connecting, while making it less of a need for some use cases to go without acquiring a signed certificate, at least during the transition. 
Optionally the server could integrate with lets encrypt, that could be a viable alternative.

**Comment by gfosco** [comment]
Pinning on the client SDKs would be a good feature request to open on those repos, but I'd love to see some possible LetsEncrypt involvement or parallel module for the server.

**Comment by kingmatusevich** [comment]
Pinning would be very useful for some small deployment / internal cases in which a static IP is used instead of a full-blown domain, I'll open the feature request in the SDKs.

**Comment by tatocaster** [comment]
LetsEncrypt :+1:

**Comment by kingmatusevich** [comment]
Feature requests in every SDK I could find, let me know If I missed any other: 
https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/799, https://github.com/ParsePlatform/Parse-SDK-Android/issues/378, https://github.com/ParsePlatform/parse-php-sdk/issues/218, https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/168, https://github.com/ParsePlatform/parse-cloud-express/issues/15, https://github.com/ParsePlatform/Parse-SDK-Arduino/issues/7

**Comment by gfosco** [comment]
Going to close this for now.. It would make a nice example project if someone wants to build it.
