### ISSUE TITLE
Uncaught exception at parse server

### ISSUE THREAD

**Issue by rizwanmindcrew12** [ParsePlatform/parse-server#3300]
Hello All, 

i am getting this error from parse server.

 Uncaught exception 'Parse\ParseException' with message 'Permission denied for action find on class Appointment.

I am using parse framework in PHP. Can anyone please tell me how to set action permission on classes.

Thanks.
Rizwan

**Comment by araskin** [comment]
You need to use the Parse Dashboard ( https://github.com/ParsePlatform/parse-dashboard ).

Once you have it running, you can see all your classes and set the permissions (click on Security)
