### ISSUE TITLE
Parse - "Missing push configuration" error on Heroku dashboard

### ISSUE THREAD

**Issue by grantespo** [ParsePlatform/parse-server#3305]
I'm trying to implement push notifications in my android app. However, I am not sure why I am getting this error.

I did some research and saw that I had to configure stuff in index.js. But because I deployed to Heroku, my project doesn't contain an index.js file.

 All I was able to to was to get an "Installation" class on my parse-server. But this installation doesn't send as a notification.

**Comment by rvitorper** [comment]
Hey there,

Did you deploy to heroic using their guide? If so, you can configure using heroku's [Config Vars](https://devcenter.heroku.com/articles/deploying-a-parse-server-to-heroku#configuring-your-parse-server-with-config-vars).

Let me know if it went alright

Kind Regards,
Ramon

**Comment by grantespo** [comment]
I deployed to heroku by pushing the purple button @ https://github.com/ParsePlatform/parse-server-example. 

I created my app and everything works, my only problem is trying to implement push notifications because I can't find an index.js file in my android studio project. Without index.js. I can't even use mailgun either.

I understand where to view/change my config variables. But how/where do I use them to implement push notifications?

@rvitorper

**Comment by rvitorper** [comment]
Hi again,

It is a great idea to use parse-server-example: a very easy setup, isn't it? There are, though, a few details you might want to pay attention: every configuration necessary you should pass as a Config Var from Heroku.
 
Knowing that you already understand that, I'll give you a nice tip that will help you with that. At the directory of the parse-server, there is a folder known as 'src', which inside is another folder named 'cli', which inside there exists another one named 'definitions'. Inside this last folder lies a file named 'parse-server.js' - or you can just click [here](https://github.com/ParsePlatform/parse-server/blob/master/src/cli/definitions/parse-server.js). 

The purpose of this file is to map configuration parameters to Config Vars names. So, in your case you need to provide a parameter named "PARSE_SERVER_PUSH". This has to be a stringified JSON in this format:
```
{
    "android": {
        "senderId": "Your GCM sender ID",
        "apiKey": "Your API key"
    },
    "ios": {
        "pfx": "path to P12 file",
        "passphrase": "optional password here",
        "bundleId": "bundleID here",
        "production": <true or false here>
    }
}
```
Make the json in a single line and feed that to your Config Vars and you should be set. In case you are having some trouble setting up some certificates from Google, [this](https://developers.google.com/cloud-messaging/android/client) page might help. You'll find a way to find the GCM sender ID and the API Key.

Hope it helps,
Ramon

**Comment by grantespo** [comment]
My project doesn't contain "parse-server-example:" thus, doesn't contain anything called 'parse-server.js'
![screen shot 2017-01-04 at 8 28 38 pm](https://cloud.githubusercontent.com/assets/19721824/21665939/98648a92-d2bc-11e6-9e3c-f56021251a41.png)

Can I copy the file from [here](https://github.com/ParsePlatform/parse-server/blob/master/src/cli/definitions/parse-server.js) into my project directly?  @rvitorper

**Comment by rvitorper** [comment]
Hey,
I just updated the answer, for the last one I got wrong. This one will require though that you have done GitHub integration with Heroku

@grantespo

**Comment by grantespo** [comment]
Thank You for your quick replies,

1) How/Where do I redeploy to my dyno? 

![screen shot 2017-01-04 at 9 04 10 pm](https://cloud.githubusercontent.com/assets/19721824/21666719/81be94b8-d2c1-11e6-96df-dc82d25d8270.png)

2) How do I get to the file where I add the parameter?

PLEASE explain everything clearly STEP BY STEP to fix my issue because I am new to Heroku @rvitorper

**Comment by natanrolnik** [comment]
Since this is not an issue with Parse Server itself, I'm closing this issue. Feel free to keep getting help from @rvitorper and other contributors in this thread.

**Comment by rvitorper** [comment]
Hi there,

Hope the modifying index.js and pushing to GitHub part went alright.

At Heroku, go to the Deploy tab:

![screenshot1](https://cloud.githubusercontent.com/assets/7038285/21682806/a0a4bff2-d33d-11e6-9e8f-ce4b4d754ca4.png)

Then, scroll down and locate Manual deploy. Select the branch you're working with and click Deploy Branch:

![screenshot2](https://cloud.githubusercontent.com/assets/7038285/21682862/ea6a32fc-d33d-11e6-91ee-6c9f60b30043.png)

Any problems, let me know @grantespo 

Ramon

**Comment by grantespo** [comment]
Hello, I don't see "Manual Deploy", 
![screen shot 2017-01-06 at 3 06 31 am](https://cloud.githubusercontent.com/assets/19721824/21711467/3c770d66-d3bd-11e6-9e52-73c523bcf005.png)

At the bottom of the attached picture, it hints "repo-name". Do I put something in there? What exactly do I put?  
Is there a way I can private chat you to figure this out? Because All I need to do is implement these push notifications so I can publish my app.

@rvitorper

**Comment by grantespo** [comment]
I just want to send Push Notifications, can you tell me how step by step? I don't know how to get into my cloud code. I don't where my cloud code is. And I don't know what to put in my cloud code to make push notifications works. Can you please tell me everything step by step? There is no clear documentation on this. @rvitorper

**Comment by rvitorper** [comment]
Hi again,

You didn't integrate with GitHub, that's why it didn't work. In case you don't want to have so much trouble dealing with a Parse Server, you can use a BaaS solution, such as the ones described in [this article](https://medium.com/data-in-motion/alternatives-to-parse-7f33b87dbd9b#.cida26t5o). However, if you want to use parse-server, please remember to integrate your GitHub with Heroku.

Ramon
