### ISSUE TITLE
Error while updating parse server to 2.3.1

### ISSUE THREAD

**Issue by manishsangwan** [ParsePlatform/parse-server#3310]
I am moving from version 2.2.24 to 2.3.1  I get following error while updating. i get **node-pre-gyp ERR**

```
npm WARN deprecated mongodb@2.2.10: Please use 2.2.16 or higher due to a regression in updateOne/Many upsertedId return value

> bcrypt@1.0.1 install /opt/upkeep/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.1/bcrypt_lib-v1.0.1-node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.1 and node@6.2.2 (node-v48 ABI) (falling back to source compile with node-gyp) 
make: Entering directory `/opt/upkeep/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
  COPY Release/bcrypt_lib.node
  COPY /opt/upkeep/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory `/opt/upkeep/node_modules/bcrypt/build'
- pkginfo@0.3.1 node_modules/pkginfo

```
I am using amazon ec2 instance with ubuntu 14.04 os. node version is 6.2.2
What is cause of these errors? Do i need to install some system package manually. How can i remove these warnings and errors?

**Comment by bohemima** [comment]
> (falling back to source compile with node-gyp) 

Everything should run as normal, bcrypt was compiled successfully according to the log.

**Comment by jeveloper** [comment]
Ideally mongoDb lib should get an update, it has issues with NodeJS 5,6,7

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.
