### ISSUE TITLE
Support Apple's APNS Token Authentication

### ISSUE THREAD

**Issue by EricNetsch** [ParsePlatform/parse-server#3315]
I would like to start using Apple's new push notification authentication protocol instead of using traditional certs. Is this possible with parse-server yet? This would be a fantastic addition to the platform to simplify push certificate management. 

> Provider Authentication Tokens
> 
> To securely connect to APNs, you can use provider authentication tokens or provider certificates. This section describes connections using tokens.
> 
> The provider API supports the JSON Web Token (JWT) specification, letting you pass statements and metadata, called claims, to APNs, along with each push notification. For details, refer to the specification at https://tools.ietf.org/html/rfc7519. For additional information about JWT, along with a list of available libraries for generating signed JWTs, see https://jwt.io
> 
> A provider authentication token is a JSON object that you construct, whose header must include:
> 
> The encryption algorithm (alg) you use to encrypt the token
> A 10-character key identifier (kid) key, obtained from your developer account
> The claims payload of the token must include:
> 
> The issuer (iss) registered claim key, whose value is your 10-character Team ID, obtained from your developer account
> The issued at (iat) registered claim key, whose value indicates the time at which the token was generated, in terms of the number of seconds since Epoch, in UTC
> After you create the token, you must sign it with a private key. You must then encrypt the token using the Elliptic Curve Digital Signature Algorithm (ECDSA) with the P-256 curve and the SHA-256 hash algorithm. Specify the value ES256 in the algorithm header key (alg). For information on how to configure your token, search Xcode help for the phrase “Configure push notifications.”
> 
> A decoded JWT provider authentication token for APNs has the following format:
> 
> {
>     "alg": "ES256",
>     "kid": "ABC123DEFG"
> }
> {
>     "iss": "DEF123GHIJ",
>     "iat": 1437179036
>  }
> NOTE
> 
> APNs supports only provider authentication tokens that are signed with the ES256 algorithm. Unsecured JWTs, or JWTs signed with other algorithms, are rejected, and your provider server receives the InvalidProviderToken (403) response.
> 
> To ensure security, APNs requires new tokens to be generated periodically. A new token has an updated issued at claim key, whose value indicates the time the token was generated. If the timestamp for token issue is not within the last hour, APNs rejects subsequent push messages, returning an ExpiredProviderToken (403) error.

https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html

Please advise on any existing solutions/ implementations.

**Comment by EricNetsch** [comment]
@flovilmart @hramos

**Comment by natanrolnik** [comment]
@EricNetsch I'm closing this issue as push related features/improvements should go to the default Push Adapters repo, a dependency of this project.
Opened here: parse-server-modules/parse-server-push-adapter#50

**Comment by EricNetsch** [comment]
@natanrolnik Got it thanks!
