### ISSUE TITLE
Best solution: Heroku / Digital Ocean / Back4App 

### ISSUE THREAD

**Issue by delarcomarta** [ParsePlatform/parse-server#3316]
Hi guys.

I write this issue because I need your help. I have 3 apps with Parse and I changed a app to Heroku but I found the problems with Cloud Code (I need to run jobs) and I can't to sleep the server 6 hours. I need a solution free because I do these apps in my free time. In the future, if the users like the apps, I would like to invest money in them.

The solution that I think is better to me is Back4App (because it is free and has all services) but I didn't find too many people using it. I'm afraid, that once parse disappears, they begin to add high prices to the service or stop maintaining it.

Does Anyone use Back4App? Could you write me about your options? 

Thanks you (:

Best regards,

**Comment by rvitorper** [comment]
Hi there,

This is definitely a nice time to migrate, and Back4App surely is a nice alternative. The limits are nicely high for the free plan(10 req/s, 1 GB of DB and 5 GB of storage, plus 50k reqs per month). Also, the support is great - just use the chat that is in the site and the dashboard, even heard a few stories that there was a guy that said he was 'addicted to the support'.

There are also the docs that are being written - updated in a daily basis. The docs implement sample apps using the functionalities that exist in the Parse API and there are some more in-depth examples, such as a simple messenger.

I tried to implement a Parse Server on Heroku and found that the biggest problem was to monitor it, which I could not do daily and might be your case. On Back4App, the team is monitoring daily - I even saw people calling late at night, like 2 am, and the founders were there ready to help.

I'd give it a try, but I am sure that you will like it. Contact me if you need help :)

Kind Regards,
Ramon

**Comment by natanrolnik** [comment]
@delarcomarta Besides Back4App, you could also take a look at Sashido.io - both have good services, free plans, and are contributing back to the community.
