### ISSUE TITLE
Impact of the new unique indexes on the _User table for parse-server 2.3.0+

### ISSUE THREAD

**Issue by asdf01** [ParsePlatform/parse-server#3324]
Hello parse-server elders

Thanks for looking into this issue.

I upgraded to 2.3.0, then to 2.3.1 and noticed this [2.3.0 guide](https://github.com/ParsePlatform/parse-server/blob/master/2.3.0.md).  I thought I had to get those unique indexes created otherwise my parse-server wouldn't work.  

I can see that the [parse-server code does try to create those unique indexes](https://github.com/ParsePlatform/parse-server/blob/master/src/Controllers/DatabaseController.js#L893) on startup.  On some of my database, it seems to be able to do it where the data allows it, on some it quietly fails without any mention in the logs.  Is that the expected behaviour?  

I can see the error handlers in [MongoStorageAdapter](https://github.com/ParsePlatform/parse-server/blob/master/src/Adapters/Storage/Mongo/MongoStorageAdapter.js#L361) and [DatabaseController](https://github.com/ParsePlatform/parse-server/blob/master/src/Controllers/DatabaseController.js#L894) but they don't seem to be called when the existing data is not unique.  

My main question for you guys is whether I actually need to do anything when upgrading to 2.3.0+.  From the wording in the [upgrade guide](https://github.com/ParsePlatform/parse-server/blob/master/2.3.0.md) it sounds like the javascript code based uniqueness check has been or will be removed and replaced with an index based uniqueness check.  

However looking at the code, it looks like the javascript based [username](https://github.com/ParsePlatform/parse-server/blob/master/src/RestWrite.js#L403) and [email](https://github.com/ParsePlatform/parse-server/blob/master/src/RestWrite.js#L424) checks are still there.

I don't mean to be difficult and go against the advice of creating these indexes, but it seems to be an impossible task for us to analyse and fix all the username and email issues that we have across our numerous databases.  So I would like to avoid it if it's not going to cause us any issues.  

Does this index based approach mean that you guys are going to be removing the javascript based check some time in the future?  Do you guys know of any issues with using 2.3.0+ without those indexes?  

Thanks

**Comment by alexblack** [comment]
+1

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.
