### ISSUE TITLE
PFQuery pointing to PFUser object failing to fetch data.

### ISSUE THREAD

**Issue by HackShitUp** [ParsePlatform/parse-server#3325]
The below code fetches the user's object from Parse Class (soon to be MongoDB Collection) titled "Newsfeeds" where an object can hold a pointer to the PFUser class. The following code's query FETCHES the user's objects but cannot recognize the subscript syntax and in turn, DOES NOT append the user's object to the PFObject array:

`
// Query Current User's Friends
func queryFriends() {

    let fFriends = PFQuery(className: "FriendMe")
    fFriends.whereKey("endFriend", equalTo: PFUser.current()!)
    fFriends.whereKey("frontFriend", notEqualTo: PFUser.current()!)
    
    let eFriends = PFQuery(className: "FriendMe")
    eFriends.whereKey("frontFriend", equalTo: PFUser.current()!)
    eFriends.whereKey("endFriend", notEqualTo: PFUser.current()!)
    
    let friends = PFQuery.orQuery(withSubqueries: [eFriends, fFriends])
    friends.includeKeys(["frontFriend", "endFriend"])
    friends.whereKey("isFriends", equalTo: true)
    friends.findObjectsInBackground(block: { (
        objects: [PFObject]?, error: Error?) in
        if error == nil {
            
            // Clear array
            self.friends.removeAll(keepingCapacity: false)
            
            // First, append Current User
            self.friends.append(PFUser.current()!)
            
            for object in objects! {
                
                if object["frontFriend"] as! PFUser == PFUser.current()! {
                    self.friends.append(object["endFriend"] as! PFUser)
                }
                
                if object["endFriend"] as! PFUser == PFUser.current()! {
                    self.friends.append(object["frontFriend"] as! PFUser)
                }
            }
            
            //
            // ISSUE: 
            // CANNOT APPEND FRIENDS; PFUser PFObjects
            // Which in turn, cannot fetch the correct posts in the news feeds for the following
            // .whereKey("byUser", containedIn: self.friends) 
            //
            print("Friends Count: \(self.friends.count)")
            print("\nFRIENDS DATA:\n\(self.friends)\n")
            
            // Newsfeeds
            let newsfeeds = PFQuery(className: "Newsfeeds")
            newsfeeds.includeKeys(["byUser","pointObject","toUser"])
            newsfeeds.whereKey("contentType", containedIn: self.friendsType)
            newsfeeds.whereKey("byUser", containedIn: self.friends)
            newsfeeds.order(byDescending: "createdAt")
            newsfeeds.limit = self.page
            newsfeeds.findObjectsInBackground(block: {
                (objects: [PFObject]?, error: Error?) in
                if error == nil {
                    
                    // Dismiss
                    SVProgressHUD.dismiss()
                    
                    // Clear array
                    self.friendsContent.removeAll(keepingCapacity: false)
                    
                    for object in objects! {
                        self.friendsContent.append(object)
                    }
                    
                    
                    // Set DZN
                    if self.friendsContent.count == 0 {
                        self.tableView!.emptyDataSetSource = self
                        self.tableView!.emptyDataSetDelegate = self
                    }
                    
                    
                    print("Friends feed count: \(self.friendsContent.count)")
                    
                } else {
                    print(error?.localizedDescription as Any)
                    
                    
                    // Dismiss
                    SVProgressHUD.dismiss()
                    
                }
                
                // Reload data
                self.tableView!.reloadData()
            })
            
            
        } else {
            print(error?.localizedDescription as Any)
            
            // Dismiss
            SVProgressHUD.dismiss()
        }
    })
    
    
}
`

The terminal outputs the user's object correctly being fetched, and even the terminal output is 100% fine. Why can't it recognize the subscript? I've also tried this with the .object(forKey: "") protocol and it won't work for the current app using Parse.com (I have not yet migrated it; testing it out before I replicate it with the actual data).

**Comment by natanrolnik** [comment]
@HackShitUp is this working when you point the SDK to Parse.com?

**Comment by dstarke** [comment]
When you check whether to append the object, shouldn't you be checking the object ids rather than using an object equality test?

**Comment by HackShitUp** [comment]
@natanrolnik yes it works with Parse.com
@dstarke to minimize the number of queries, I append the object itself to handle some of the user's object's properties later in the app session.

**Comment by HackShitUp** [comment]
@dstarke chiefly because I haven't enabled the local datastore and don't plan to

**Comment by dstarke** [comment]
My point was that `object["frontFriend"] as! PFUser == PFUser.current()!` can return false for two objects which this code probably wants to consider the same. If you are finding things are not getting appended to `self.friends`, that could be why.

**Comment by HackShitUp** [comment]
@dstarke Hmmm why is that? And I've figured out how to fix this but it won't work for the version in the app store that points to Parse.com @natanrolnik. Also, why is it that it won't append the user's objects with the subscript syntax?

**Comment by dstarke** [comment]
I don't think that PFUser or PFObject defines an isEqual() function, which means that `==` tests on the object's identity, which is based on it's memory address. What you want here is a test as to whether the two objects are the same Parse object. It is possible to have two objects that are not identical, but which represent the same parse object. The PFUser object that you get from your query results might not be the exact same one you get from `PFUser.current()`, even if they have the same ID.

**Comment by HackShitUp** [comment]
ANYONE WHO'S READING THIS ISSUE PLEASE DO NOT CLOSE IT

@dstarke Alright I just tested this out, and it looks like the following syntax, before appending it to the array works:

`
if (object.object(forKey: "frontFriend") as! PFUser).objectId! != PFUser.current()!.objectId! {
                        self.friends.append(object.object(forKey: "frontFriend") as! PFUser)
                    } else {
                        self.friends.append(object.object(forKey: "endFriend") as! PFUser)
                    }
`

Thanks @dstarke for the clarity! 
:)
