### ISSUE TITLE
MongoDB node lib update to 2.2.x

### ISSUE THREAD

**Issue by jeveloper** [ParsePlatform/parse-server#3329]
Not a bug necessarily but i went over changelog on mongodb node lib and found a few items:

1.Destroy connection on socket timeout due to newer node versions not closing the socket.
2.If only a single mongos is provided in the seedlist, fix issue where it would be assigned as single standalone server instead of mongos topology 
3. A bunch of bugs were fixed when topology includes replicasets, shards 
4. They improved on stateless detection
5. close event not emits during network issues using single server topology
And MANY more were resolved 

Thank you !

**Comment by flovilmart** [comment]
As you can see, in the open pull requests, the new versions of the mongodb driver are not playing well with our test suite. We need to spend an bit of time on it to make sure everything work as intended with the newest versions of the driver

**Comment by jeveloper** [comment]
Ahhh my bad, i didn't see those. Wonder what has changed , i didn't see "breaking changes "notes in the driver change log

**Comment by jeveloper** [comment]
Yeah i see these guys failed:

1) Parse.Query testing lessThanOrEqualTo queries
  - Expected 6 to equal 8, undefined.
2) Parse.Query testing notEqualTo queries
  - Expected 8 to equal 9, undefined.

**Comment by flovilmart** [comment]
Yup... it's he _Schema updates that are not completing correctly

**Comment by jeveloper** [comment]
Were you thinking making 3.2 a minimum requirement for parse-server , that way you won't have to support differences like that?

**Comment by emkman** [comment]
3.2 as a minimum would be a huge win because then Parse.Query could get join functionality via the `$lookup` operator.

**Comment by jeveloper** [comment]
Given that Parse is shutting down officially within few weeks, migration was complete by everyone who needed to.
@flovilmart  how likely is it to just drop support for 3.0.x , 3.2 has been out for about 2 years i believe.

Thanks @emkman what do you think of those failures on test cases?

**Comment by flovilmart** [comment]
The mongodb version itself is not the problem at hands here. It's unlikely we'll drop support for older mongodb versions UNLESS there is a very good reason.

> Parse.Query could get join functionality via the $lookup operator.

That would be nice, but not in the current focus, actually there is nothing preventing it to happen now, without dropping support of older mongodb  version.

**Comment by jeveloper** [comment]
Thanks for clarification , what is the focus? is there a roadmap for this library 
It seems that having mongo driver follow the updates from MongoDB is pretty important.
Although i did notice postgres support seems to be prevailing

**Comment by flovilmart** [comment]
> It seems that having mongo driver follow the updates from MongoDB is pretty important.

yes it is, but it's even more important to maintain stability in our own project than starting to notice unexpected behaviours.

We haven't had the time to correctly investigate and bump the mongodb package. Feel free to take a look at it.

**Comment by jeveloper** [comment]
I'll try and experiment locally with a modified version

**Comment by madsb** [comment]
Pardon my novice comment, but could support for mongodb 3.2 also result in GeoJSON support while still maintaining backwards compatibility with older mongodb versions? GeoJSON support (especially for making geo queries with polygons) would be absolutely awesome!

**Comment by flovilmart** [comment]
we support mongodb 3.2, that's not the question here. the question is about the driver version, not the database version.
