### ISSUE TITLE
Question: Where can I find step-by-step instructions to save video files?

### ISSUE THREAD

**Issue by HackShitUp** [ParsePlatform/parse-server#3336]
I have about three weeks left to migrate the data and the last two things I have to figure out how to do is to fix OneSignal's push notifications and save video files by hooking up AWS' S3 adapter. I've looked into the a lot of the guides, but I'm very confused. I'm currently using EC2 to host MongoLab but I don't know how to modify the Parse-Server index.js files for these adapters and deploy it to Elastic Beanstalk...

**Comment by natanrolnik** [comment]
Where and how did you deploy your server? Index.js is the starting point, try to find it and modify according to your needs. 

Take a look at [these videos made by Parse back in April](http://blog.parse.com/learn/parse-server-video-series-april-2016/). I suggest you to do it quickly, its already January and you need to give time to your users to update the app.

**Comment by natanrolnik** [comment]
And also take a look at the wiki, specially the [File Adapters section](https://github.com/ParsePlatform/parse-server/wiki/Configuring-File-Adapters). 

The Wiki contains many Step by step tutorials, very well written and comprehensive.
