### ISSUE TITLE
Cloud Function Multiple Called times

### ISSUE THREAD

**Issue by panagorn** [ParsePlatform/parse-server#3340]
Hello i tried to call cloud function with the api from android using the code below and am getting multiple responses.

            ParseCloud.callFunctionInBackground("push", new HashMap<String, Object>(), new FunctionCallback<Object>() {
                @Override
                public void done(Object object, ParseException e) {
    
                }
            });

I also tried to make http request with the code below and i have the same results. How to fix that issue? I am trying to send push notification as you said because we cant send directly from android for security reasons.

    `OkHttpClient client = new OkHttpClient();
        Request request = new Request.Builder()
                .method("POST", RequestBody.create(MediaType.parse("text/x-markdown; charset=utf-8"), jsonObject.toString()))
                .url("http://url/parse/functions/hello")
                .addHeader("X-Parse-Application-Id", "myAppId")
                .addHeader("X-Parse-REST-API-Key", "myApiKey")
                .addHeader("Content-Type", "application/json")
                .build();
        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                if (e != null)
                    e.printStackTrace();
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                Log.e("res", response.message());
            }
        });`

**Comment by bohemima** [comment]
Can you elaborate on "getting multiple responses"? What did you expect to happen, what is happening and also share the actual Cloud Code?

**Comment by natanrolnik** [comment]
@panagorn can you share the Cloud Code functions and the logs on clients?

**Comment by panagorn** [comment]
var query = new Parse.Query(Parse.Installation);
	Parse.Cloud.define('push', function(req, res) {
	  Parse.Push.send({
		  where: query,
		  data:{
			  test:"test"
		  }
	  },{useMasterKey: true})
	  .then(function(){
		  res.status(200).send("ok");
	  },function(err){
		  res.status(200).send(err);
	  });
	});

At the client i get 2 times the ok message. I cant send you more because i started developing my own server side

**Comment by bohemima** [comment]
You should use `res.success()` and `res.error()`

**Comment by panagorn** [comment]
Thank you i can try it on another project

**Comment by MobileDev0702** [comment]
Hi bohemima
I've tried res.success() and res.error().
But same error.
