### ISSUE TITLE
Array of NSDate stored differently in Parse.com and Parse Server

### ISSUE THREAD

**Issue by brbgyn** [ParsePlatform/parse-server#3341]
Hi,

When i migrate my data to a mongoDB database with Parse Server open source, the columns with and Array of NSDate are not migrate as expected.

They are migrated as an Array of NSString containing the date as yyyy-MM-dd'T'HH:mm:ss.SSS'Z'

My app crashes when try to handle this new Array since they are not NSDate anymore, and became NSString.

Here are images to explain what im talking about:

PARSE.COM OLD BROWSER
<img width="726" alt="captura de tela 2017-01-07 as 20 11 51" src="https://cloud.githubusercontent.com/assets/6548984/21745553/99d57124-d515-11e6-9eb6-27a8bbfb2220.png">

PARSE SERVER BROWSER
<img width="451" alt="captura de tela 2017-01-07 as 20 12 02" src="https://cloud.githubusercontent.com/assets/6548984/21745556/9dfa88ac-d515-11e6-9f93-f59af8c833f7.png">

Thank you

**Comment by sschiffli** [comment]
I've noticed the same behavior.  

When looking at the source I think I see a bug in the transformInteriorValue function where it calls [transformInteriorAtom](https://github.com/ParsePlatform/parse-server/blob/master/src/Adapters/Storage/Mongo/MongoTransform.js#L116).  It checks the result against CannotTransform however the [transformInteriorAtom](https://github.com/ParsePlatform/parse-server/blob/master/src/Adapters/Storage/Mongo/MongoTransform.js#L431) function doesn't ever return CannotTransform, making all [this](https://github.com/ParsePlatform/parse-server/blob/master/src/Adapters/Storage/Mongo/MongoTransform.js#L121) code dead.  This fact is confirmed by [codecov](https://codecov.io/gh/ParsePlatform/parse-server/src/6a5c0dd09b460eddac7bb8fdc75b24dd46532119/src/Adapters/Storage/Mongo/MongoTransform.js#L122).

@drew-gross, it looks like you were the last to touch this function.  Do you have any insight?

**Comment by brbgyn** [comment]
Why did you close it ?

**Comment by hramos** [comment]
I closed this for a couple of reasons: 1) you did not fill out the template, and 2) this seems to be a Parse.com=>ParseServer migration issue, which is out of scope for this repo.

If you feel like this is an issue that does need to be addressed in Parse Server, we can reopen if you update the description with all the necessary fields.
