### ISSUE TITLE
Not able to login with facebook when logged in with non-fb user.

### ISSUE THREAD

**Issue by KunalKathrotia** [ParsePlatform/parse-server#3346]
Hello, we are having a problem with requirement where we have to allow user to share an item on facebook profile inside an Android application. It works fine when user is logged in the app with his own facebook credentials, and tries to share the app. we are using the below library to use the facebook capabilities with parse.

`compile 'com.parse:parsefacebookutils-v4-android:1.10.3@aar'` 

But issue begins when a normal parse user is logged in the app, and tries to share item on FB. What we did is if such users tries to share an item on FB and is not logged in through facebook, we initiate the facebook login using the APIs provided by Android Facebook SDK for which we use the below android library for FB.

```
compile('com.facebook.android:facebook-android-sdk:4.7.0') {
        exclude group: 'com.parse.bolts',
                module: 'bolts-android'
    }
```

The problem is it's simply not executing the Facebook callback registered for login due to some kind of weird request code issue. Also asked question on SO about this, but couldn't get enough attention so asking here for help. For reference: 
[Login issue in facebook with parse](
http://stackoverflow.com/questions/41505236/android-facebook-sdk-login-issue-with-parse-sdk) 

Please help if you know anything about this issue. Thanks.

**Comment by natanrolnik** [comment]
Does it work with Parse.com and it's a Parse Server issue, or it doesn't work at all with the hosted Parse.com?

**Comment by KunalKathrotia** [comment]
Yes it works when user is logged in with `ParseFacebookUtils.logInWithReadPermissionsInBackground(...)` in app and he/she tries to share an item.

But when user is already logged in with `ParseUser.logInInBackground(...)` inside app and tries to share an item on facebook we need access token first and since user is already logged in we can not use `ParseFacebookUtils.logInWithReadPermissionsInBackground(...)` again, so instead we try to login with `LoginManager.getInstance().registerCallback(callbackManager, ... )`.

After that it tries to call the `callbackManager.onActivityResult()` but it couldn't as it has some requestCode issues in android which should not be but don't understand why as i mentioned in SO question.

**Comment by natanrolnik** [comment]
I understand. I'll reply in the SO question, as this is the repo of Parse Server, the node.js server, and is not related to the Android SDK (or any client).
We are trying to keep the issues here focused on real issues (bugs and improvements) of the server.
