### ISSUE TITLE
Can We Run More Than One Parse Application Upon Same Server 

### ISSUE THREAD

**Issue by Heman6886** [ParsePlatform/parse-server#3354]
I Want to ask can  i run more than 1 application upon same parse server that is being setup upon Ubuntu or Centos  With Having Different Application Id And Different Master Key , Different Databases and same Dashboard

**Comment by natanrolnik** [comment]
Closing as duplicate of #15 and #1722

**Comment by Heman6886** [comment]
I am using ubuntu server for this
