### ISSUE TITLE
Missing documentation for options of separate live query server

### ISSUE THREAD

**Issue by dpoetzsch** [ParsePlatform/parse-server#3355]
The wiki page for Parse LiveQuery proposes [a setup for a scalable live query](https://github.com/ParsePlatform/parse-server/wiki/Parse-LiveQuery#scalability). However, when separating the live query server from the parse server it is important to specify at least `appId`, `masterKey` and `serverURL`.  If this information is missing the live query server will start up and allow connections but will silently not push any changes to the clients. For me the only way to find that out was to dig through the code. At the moment I could not even find documentation that these additional options exist.

A working setup looks like this:

	var express = require('express');
	var ParseServer = require('parse-server').ParseServer;

	var app = express();

	var port = process.env.PORT;
	var httpServer = require('http').createServer(app);
	httpServer.listen(port, function() {
	    console.log('live query server running on port ' + port + '.');
	});

	ParseServer.createLiveQueryServer(httpServer, {
	    appId: process.env.APP_ID,
	    masterKey: process.env.MASTER_KEY,
	    serverURL: process.env.SERVER_URL,
	    redisURL: process.env.REDIS_URL
	});

I cannot edit the wiki page, but I believe it would be helpful if this information would be integrated into the documentation.

**Comment by flovilmart** [comment]
Updated the wiki:

https://github.com/ParsePlatform/parse-server/wiki/Parse-LiveQuery#scalability

Thanks for reporting 👍
