### ISSUE TITLE
New repository structure results in: cannot find module 'parse-server'

### ISSUE THREAD

**Issue by omairvaiyani** [ParsePlatform/parse-server#336]
Happened once I updated to the latest build:

```
Error: Cannot find module 'parse-server'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```
```
var ParseServer = require('parse-server').ParseServer; // not changed this line
```

**Comment by gfosco** [comment]
can you re-run `npm install` and make sure that's not it?

**Comment by omairvaiyani** [comment]
I did - I think it might be a mistake on my end regarding how I installed the repo. I forked it, and ran ```npm install omairvaiyani/parse-server``` which cloned this repo's master branch. I see that the master branch is different from the latest tag ```2.0.7```, the latter of which works fine.

**Comment by drew-gross** [comment]
Looks like the problem has been found.

**Comment by omairvaiyani** [comment]
Could this be re-opened. I need clarification as I'm new to babel - are we supposed to build the repositories using ```npm build```? Because even on ```2.0.8```, I can't simple use ```require('parse-server')``` without trigger the ```cannot find module``` error.

**Comment by drew-gross** [comment]
Yes you should only need to do `npm install`. If that doesn't work, that is a bug.

**Comment by flovilmart** [comment]
@omairvaiyani `npm build` won't do anything, to trigger a build you have to run `npm run build`

**Comment by gfosco** [comment]
Not clear if there's an issue here and it's getting stale.  If there is a problem with the latest version, please open a new issue.  Thanks.

**Comment by TravisHeaver** [comment]
I am having this issue now as well. If I run: 
npm install parseplatform/parse-server.git#latest --save 
everything works fine. If I run: 
npm install parseplatform/parse-server.git#2.6.5 --save 
I get the same error: Cannot find module 'parse-server'. Changing nothing else about the project
npm install parseplatform/parse-server.git#master --save gives the same error

**Comment by flovilmart** [comment]
The tagged commits are not built in the repo, for using a particular version, just use the npm package

**Comment by TravisHeaver** [comment]
oh, my end goal is to actually build from my own fork... So in that case my best option is to... include all the build files in my fork commit?

**Comment by flovilmart** [comment]
it's up to you, but you should have a look at how we release the latest branch, (in resources/npm-git.sh) if you need something similar.

**Comment by montymxb** [comment]
@TravisHeaver like flovilmart mentioned only what's on npm or in **latest** is pre-built. For everything else you would have to build up the necessary files yourself. You can checkout [npm-git.sh](https://github.com/parse-community/parse-server/blob/master/resources/npm-git.sh) and our [package.json](https://github.com/parse-community/parse-server/blob/master/package.json#L73) for more details.

**Comment by greggmojica** [comment]
Any update here?

**Comment by flovilmart** [comment]
It’s. 2 year old issue that is closed, not sure what update you’re expecting. Please open a new issue
