### ISSUE TITLE
App Settings is not showing in parse-dashboard

### ISSUE THREAD

**Issue by partikles** [ParsePlatform/parse-server#3361]
I can able to launch parse-dashboard with applications in my mac. 

1.Core (Available)
2.Push (Available)

**3.App Settings (Not Available)**

I have enabled email verification in parse server as below but still App Settings is not showing.

verifyUsersEmails: true,
    emailAdapter: {
        module: 'parse-server-simple-mailgun-adapter',
        options: {
            // The address that your emails come from
            fromAddress: 'name@myapp.com',
            // Your domain from mailgun.com
            domain: 'mg.myapp.com',
            // Your API key from mailgun.com
            apiKey: 'maigun_key'
        }
    }

**Comment by natanrolnik** [comment]
That's correct, @partikles. The open source [parse-dashboard](github.com/parseplatfotm/parse-dashboard) doesn't support app settings. As they are initialized with the server, there is no (current) way to switch settings on the go. 

If you think it's a feature worth dealing with, please open a PR in both repos.

**Comment by BillyJohn3** [comment]
Can you point me out how to initialize the settings section with the server?
