### ISSUE TITLE
How do I properly serialize Parse Objects in cloudcode BeforeSave?

### ISSUE THREAD

**Issue by jeacott1** [ParsePlatform/parse-server#3363]
if I have a Numeric field and increment it using the sdk something like
```
...
someTestClassQuery.find().then(function(results) {
 results[0].increment("MyNumericField");
 results[0].save();
```
and I have cloudcode something like:

Parse.Cloud.beforeSave("TestClass", function(request, response) {           
```
var fieldValue=req.object.get('MyNumericField'); //this holds the expected field value, already incremented.

  var jsonBody = {};
  jsonBody.object = req.object.toJSON();
  jsonBody.object.className = req.object.className;

/*at this point,  jsonBody.object has lost its actual current value, and its replaced by an IncrementOp with a value of 1.

var unmarshalled = JSON.parse(jsonBody.object);
this object is not the same as  req.object. 
var fieldValueb=req.object.get('MyNumericField'); returns IncrementOp, not value
*/
```

how should I properly marshall/unmarshall parse objects such that they maintain their integrity?

thanks

**Comment by flovilmart** [comment]
AFAIK That's unfortunately not possible with the current SDK's. The beforeSave has the client 'operations' and not the full values. an afterSave would have the proper values. 

Also, possibly fixable with the internals of the JSSDK, if the operations are stored differently than the values.

**Comment by flovilmart** [comment]
See: https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/ParseObject.js#L418

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.
