### ISSUE TITLE
Secure Connection redirect

### ISSUE THREAD

**Issue by pulse1989** [ParsePlatform/parse-server#3365]
Hey guys, 

I followed this guide to get my parse server up and running:

https://www.digitalocean.com/community/tutorials/how-to-migrate-a-parse-app-to-parse-server-on-ubuntu-14-04

so far so good. The problem now is file storage (or rather file retrieval). I've successfully connected to amazon s3 but the problem now is when i try and load the images into my android app , parse server returns images with 'http://' as the url endpoint. 

my server is using 'https://'. I've read that defining the PARSE_SERVER_URL is used only for the dashboard and doesn't really help my case. i've also tried setting https://localhost internally  on the server but this also doesnt work. 

i'm using nginx that redirects using HTTP response 301 but checking the android sdk shows that redirects are disabled. I've tried using picasso but also found out that this also has redirects disabled. I cloned the android source code and enabled http redirects and https redirects but this still isn't working (sidenote - there is a note in that sdk that says its been disabled and has a link to a possible article but its not available to the public for some reason)...maybe i missed something?

Any idea how I can get parse server to response with https:// in the initial request rather than http?

Thanks

**Comment by bohemima** [comment]
check out the "publicServerURL" configuration variable.

**Comment by pulse1989** [comment]
lol. fixed it. thanks so much!
