### ISSUE TITLE
Feature: Can we send push notification on iOS using token based authentication

### ISSUE THREAD

**Issue by asif13** [ParsePlatform/parse-server#3376]
Do we support the new token based authentication, as discussed here https://eladnava.com/send-push-notifications-to-ios-devices-using-xcode-8-and-swift-3/ .
If not how can I start to integrate it into the current server ?

**Comment by natanrolnik** [comment]
We don't yet.
It's already been reported here #3315 and I've opened the issue in the correct repo. You can read more over here: parse-server-modules/parse-server-push-adapter#50

**Comment by asif13** [comment]
Thanks @natanrolnik .
