### ISSUE TITLE
Conflict of sessions when migrating to Parse Server

### ISSUE THREAD

**Issue by MateusCarvalho** [ParsePlatform/parse-server#3380]
I have migrated the parse service to my own server recently, after migrating the files and the database. I noticed that users who upgraded the application, and were already logged in to the application, are not able to access the application's features because there is a conflict of sessions, since it does not have to log in to the application again and a session has already been started.

I know that if you go into the settings of the application and Erase the data and cache and log in again, it works ok, but how do you make the user to update through Google play sessions are deleted?

**Comment by flovilmart** [comment]
>  because there is a conflict of sessions

What do you mean by that? Can you please fill the issue template and reopen the issue?
