### ISSUE TITLE
Shutdown of parse service- The day after 

### ISSUE THREAD

**Issue by RuthErlanger** [ParsePlatform/parse-server#3382]
As part of the upcoming shutdown, I would like to know please what will be on the 28.1 2017
If I’ll try to access your service  (https://api.parse.com/1/push) will I get 500 response or the service will be down and I will get timeout?

**Comment by codegefluester** [comment]
You will most likely receive an HTTP 500/404, eventually this whole thing might go away and connecting won't be possible at all anymore.

**Comment by skinp** [comment]
You'll be receiving a 410 error for the first few months. After that, there'll be no backends and you'll get a timeout.
