### ISSUE TITLE
File upload using android sdk i/o failure

### ISSUE THREAD

**Issue by ishaan1995** [ParsePlatform/parse-server#339]
The file upload not working when i set up my own parse server.
getting error--->
com.parse.ParseRequest$ParseRequestException: i/o failure
Ignoring header Content-Type because its value was null.

Apart from this,parse server is working properly like  parse object save is working flawlessly except for this file upload part.
Is there a reliable solution to this problem?

**Comment by ishaan1995** [comment]
The problem occurs even for small files of 300-700kb.
Can only upload files of size 30-70kb.(even on localhost i get the i/o error) on my heroku server.

**Comment by gfosco** [comment]
There's been several changes related to files lately, can you try and re-open this if you're still experiencing a problem with 2.1.3+?  Thanks.

**Comment by ishaan1995** [comment]
OK thank you, I'll try and reopen if problem still persists.
