### ISSUE TITLE
Is there a known delay in Push Notifications following App Migration over to Parse Server

### ISSUE THREAD

**Issue by anibalrosado** [ParsePlatform/parse-server#3392]
We migrated our largest and most active website/mobile app this morning and finalized the process on parse.com but we are now not able to send any push notifications to our users. None go through to the installation base.

<img width="1006" alt="screen shot 2017-01-17 at 11 15 23 pm" src="https://cloud.githubusercontent.com/assets/1706864/22050673/e8735a7e-dd0a-11e6-9193-a642cdfe39df.png">

**Comment by flovilmart** [comment]
Can you please fill in the issue template fully with all requested informations? 

Thanks.
