### ISSUE TITLE
Missing data from object

### ISSUE THREAD

**Issue by bogdhy** [ParsePlatform/parse-server#3394]
### Issue Description

Describe your issue in as much detail as possible.

When I am trying to retrieve an Parse.Object from class _User for some reason an attribute is missing when I make the call on parse server hosted on Heroku platform. I tried to get the object using Parse JS SDK, iOS SDK and Rest call, all three having the same result, but when I do the call on a local hosted server which is using the same database, etc. the object has all it's expected attributes. In our case, the attribute in question is "email".

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.2
  - Operating System:    cedar-14
  - Hardware:             -
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

- **Database**
  - MongoDB version: 3.2.11
  - Storage engine:  default
  - Hardware:      -
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc):  mLab

**Comment by NatanRolnik** [comment]
@bogdhy Since #3158, this is not a bug - it's actually a security feature that matches the behavior of Parse.com.
You can read more about it also in #3301 for possible alternatives.
