### ISSUE TITLE
Support for Config

### ISSUE THREAD

**Issue by natanrolnik** [ParsePlatform/parse-server#34]
One of my favorite features of Parse is Config. Well, we definitely can create a custom method, that returns a JSON and etc., but would be amazing to have it working without the need to change code in the Client side. 

What are the reasons that cause Config not to be supported currently? Maybe answering this question will give some direction on how to implement it?

**Comment by flessard** [comment]
+1

**Comment by kingmatusevich** [comment]
+1

**Comment by AdityaShirole** [comment]
+1

**Comment by gfosco** [comment]
The two of us building this didn't put a high value on Config, but we totally understand it is useful.  I think adding support for it will be pretty simple.  I'd venture that this would be a good first PR for someone learning the project.

**Comment by natanrolnik** [comment]
Hey @gfosco, great idea!

I took a look on the SDK to understand what is the endpoint - `PFRESTConfigCommand` generates a GET `config`. Also, noticed that it saves the last config in the MongoDB.

What would be, in your opinion, the correct approach to this?

First, how would we add new parameters or edit existing parameters? Only via REST API, or through some UI similar to what we have today?

Secondly, how do you suggest creating the class that will handle the GET request?

**Comment by gfosco** [comment]
Parse Config only hosts a single endpoint for clients, a GET on /config

Check `analytics.js` and `installations.js` for example route handling.

Sadly, we named something `config.js`.... So, we either have to rename `config.js` which would not be fun, or perhaps handle the /config route in `index.js`.

Then, we need a way to actually set the config values... Perhaps a POST against /config with the master key.  And we should cache the values...

**Comment by theill** [comment]
Gave it a first shot with https://github.com/ParsePlatform/parse-server/pull/283

**Comment by gfosco** [comment]
Merged in #283. :+1:
