### ISSUE TITLE
Rest Api deleting file not working

### ISSUE THREAD

**Issue by ishaan1995** [ParsePlatform/parse-server#340]
While trying to deleta a file using rest api with master key i get response msg-->
cannot delete /parse/files/$myappid/$filename.extension

and on my server i get 404 router error

cURL command -------->

curl -X DELETE \
  -H "X-Parse-Application-Id: $appid" \
  -H "X-Parse-Master-Key: $masterKey" \
  https://server-add/parse/files/...profile.png

or 

curl -X DELETE \
  -H "X-Parse-Application-Id: $appid" \
  -H "X-Parse-Master-Key: $masterKey" \
  https://server-add/parse/files/$myappid/...profile.png

both statments cause the above mentioned response.
Is there a reliable solution to my problem?

**Comment by gfosco** [comment]
Delete is not yet implemented in files.js or the file adapter system.  Definitely useful to add, will mark up-for-grabs for now.

**Comment by ishaan1995** [comment]
so it will be implemented in near future.thanx

**Comment by ishaan1995** [comment]
The file delete is still not working, i have update the parse-server code today, that has the commit for file delete, but still the same error occurs as mentioned above.
It seems as the master key is doing nothing because even if i do not enter the master key, i get that same error--> cannot delete /parse/....

**Comment by nlutsenko** [comment]
Any chance you can provide more details?
We have a full e2e test for it, so without more details it's very hard to diagnose the error.

Also, could you create a new issue for it and link back here?

**Comment by umales** [comment]
The same for me, not working..
