### ISSUE TITLE
Add Query Parse to Wiki´s Community Links section

### ISSUE THREAD

**Issue by pacogvillaran** [ParsePlatform/parse-server#3402]
Hi guys,

[Query Parse ](https://itunes.apple.com/de/app/query-parse/id1170245634?l=en&mt=8) is an app to query your Parse Server-powered app.
It has a smart query builder so you do not have to write code (of any sort) to query your app´s data.
It allows you to write complex queries at your fingertips (subqueries included.)

More operators, data types and time-saver functionalities to come!
Congrats for keeping the best MBaaS alive!

Cheers,
Query Parse Team

**Comment by NatanRolnik** [comment]
Done, @pacogvillaran!
https://github.com/ParsePlatform/parse-server/wiki#ios-resources

Thanks for sending it!

**Comment by pacogvillaran** [comment]
Awesome!
 Thank you! :)
