### ISSUE TITLE
unsupported URL (Code: 100, Version: 1.14.2)

### ISSUE THREAD

**Issue by wellkeptbeauty** [ParsePlatform/parse-server#3416]
unsupported URL (Code: 100, Version: 1.14.2) for downloading images after migration from parse to Mlab+Heroku ,please could you help me out

**Comment by NatanRolnik** [comment]
@wellkeptbeauty can you please fill the issue template, or at least at some helpful information?

**Comment by NatanRolnik** [comment]
Closing due to insufficient information. If you provide us enough data and we see it's a bug in Parse Server, we'll reopen it.

**Comment by hashemp206** [comment]
it seems image names contains invalid characters like white space
