### ISSUE TITLE
Unable to call Parse Cloud functions after hosting on Heroku XMLHttpRequest failed: "Unable to connect to the Parse API"

### ISSUE THREAD

**Issue by willyyang** [ParsePlatform/parse-server#3420]
So I am sure the cloud function works because I am able to hit the function by using curl.
This is what I ran and it works.
```
curl -X POST -H "X-Parse-Application-Id: myAppId" -H "Content-Type: application/json" -d '{}' https://xxxx.herokuapp.com/parse/functions/upsert
```

Here is my client configuration code
```
import Parse from 'parse/react-native';
Parse.initialize('myAppId');
Parse.serverURL = 'https://xxxx.herokuapp.com/parse/';
```

I am getting a ` 100: XMLHttpRequest failed: "Unable to connect to the Parse API"` error most likely due to issues with `https`

Please let me know what I can do to fix this problem. Thanks!

**Comment by NatanRolnik** [comment]
@willyyang how are you initializing the server? Can you share the code? Are you configuring the `serverURL` property?

**Comment by willyyang** [comment]
server is using an environment env set on heroku `https://xxxx.herokuapp.com/parse/`

```
var databaseUri = process.env.DATABASE_URI || process.env.MONGODB_URI;

if (!databaseUri) {
  console.log('DATABASE_URI not specified, falling back to localhost.');
}

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

console.log('serverURL')
console.log(process.env.SERVER_URL)

// Video guide
//https://github.com/ParsePlatform/parse-server
var api = new ParseServer({
  databaseURI: databaseUri || environment.default.databaseURI,
  cloud: process.env.CLOUD_CODE_MAIN || path.join(__dirname, '/cloud/main.js'),
  appId: process.env.APP_ID || environment.default.appId,
  masterKey: process.env.MASTER_KEY || environment.default.masterKey, //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || environment.default.serverURL,  // Don't forget to change to https if needed

  javascriptKey: process.env.JAVASCRIPT_KEY || '',  //** add this line no need to set values, they will be overwritten by heroku config vars
  restAPIKey: process.env.REST_API_KEY || '', //** add this line
  dotNetKey: process.env.DOT_NET_KEY || '', //** add this line
  clientKey: process.env.CLIENT_KEY || '', //** add this line

  liveQuery: {
    classNames: ['Donations', 'ActiveConnections'] // List of classes to support for query subscriptions
  }
});
// Client-keys like the javascript key or the .NET key are not necessary with parse-server
// If you wish you require them, you can set them as options in the initialization above:
// javascriptKey, restAPIKey, dotNetKey, clientKey

var app = express();
app.use(cors());

// Serve static assets from the /public folder
app.use('/public', express.static(path.join(__dirname, '/public')));

// Serve the Parse API on the /parse URL prefix
var mountPath = process.env.PARSE_MOUNT || '/parse';
app.use(mountPath, api);

//Required to receive JSON body from POST
app.use(bodyParser.json()); // support json encoded bodies
app.use(bodyParser.urlencoded({ extended: true })); // support encoded bodies

// Parse Server plays nicely with the rest of your web routes
app.get('/', function(req, res) {
  res.status(200).send('I dream of being a website.  Please star the parse-server repo on GitHub!');
});

// There will be a test page available on the /test path of your server url
// Remove this before launching your app
app.get('/test', function(req, res) {
  res.sendFile(path.join(__dirname, '/public/test.html'));
});

var port = process.env.PORT || 1337;
var httpServer = require('http').createServer(app);
httpServer.listen(port, function() {
    console.log('parse-server-example running on port ' + port + '.');
});

// This will enable the Live Query real-time server
ParseServer.createLiveQueryServer(httpServer);
```

**Comment by willyyang** [comment]
The server is initialized correctly , I believe, since I am able to hit the endpoints using curl commands

**Comment by NatanRolnik** [comment]
When calling from the client, does it work if you add the `clientKey`:
`Parse.initialize('myAppId', 'yourClientKey');`

**Comment by willyyang** [comment]
does not work.

**Comment by NatanRolnik** [comment]
Did you try with `javascriptKey` instead?

**Comment by willyyang** [comment]
I've removed the keys cus they aren't necessary .  And curl still works .

**Comment by NatanRolnik** [comment]
If curl works, there is no reason why the call from React Native won't.

**Comment by willyyang** [comment]
It's because of heroku enabling SSL . There's a bug with this client that
doesn't deal with that.

**Comment by NatanRolnik** [comment]
Can you provide us more information? Which platform and OS are you running React native on? Can you print some logs?
Maybe a sample project?

**Comment by GGross5213** [comment]
+1
I might be experiencing a similar issue. I just updated my parse-server and parse js sdk that is being hosted on Heroku, and now all my cloud code is failing. It works up until I have to query the database for something and then it throws this error ```'XMLHttpRequest failed: "Unable to connect to the Parse API"'```.

**Comment by pzverkov** [comment]
Hi guys,

You can try to use fcm-node:

From Cloud part:

var SERVER_KEY_FCM = 'AIza...';
var FCM = require('fcm-node');
var fcm = new FCM(SERVER_KEY_FCM);

Parse.Cloud.define("CloudPushFCM", function (request, responseTotal) {

    var params = request.params;
    var gcmToken = params.gcmToken;

    var message = { //this may vary according to the message type single recipient, multicast, topic, etc
        to: gcmToken,
     //   collapse_key: 'your_collapse_key',
        priority: "high",

        notification: {
            title: 'Title of your push notification',
            body: 'Body of your push notification',
            icon: 'ic_stat_utn',
            tag: 'tag text'
        },

        data: {  //you can send only notification or only data(or include both)
            my_key: 'my value',
            my_another_key: 'my another value'
        }
    };

    fcm.send(message, function(err, response){
        if(err) responseTotal.error("error with sendPush: " + err);
        else 	responseTotal.success("Push send");
    }, {useMasterKey: true});

});

**Comment by willyyang** [comment]
Hosted on AWS EBS and it works fine. It's an issue with the enabled SSL.

**Comment by willyyang** [comment]
it's causing an issue with this library..

**Comment by GGross5213** [comment]
I think I figured something out. At the top of the main.js in cloud code, I put ```Parse.serverURL = process.env.SERVER_URL```  where SERVER_URL is the heroku url and it seems to work now.

**Comment by johndoehelloworld** [comment]
@GGross5213 : Was the URL https or http? I added the URL in serverURL, and it still doesn't seem to want to work. Any ideas/thoughts?

**Comment by jbschaff** [comment]
@GGross5213 same question as @johndoehelloworld. Would be amazing if you still have it handy!

**Comment by GGross5213** [comment]
@jbschaff @johndoehelloworld I have been looking to see what I did and I am having trouble finding it. I believe the URL was https.

**Comment by jbschaff** [comment]
@GGross5213 thanks, I was able to sort it out. Sent a test notification through cloud code function and was successfully delivered. In Heroku config vars I have SERVER_URL set to: `https://xxxxxxxx.herokuapp.com/parse` and had to modify index.js with: `var https = require('https');` and also `Parse.serverURL = process.env.SERVER_URL;` before `var api = new ParseServer({`. Also set `serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',`.
