### ISSUE TITLE
CLP requireAuthentication typo

### ISSUE THREAD

**Issue by flavionegrao** [ParsePlatform/parse-server#3423]
Hi, there is a small typo with this new feature.
Documentation says: `requireAuthentication` but the server is expecting `requiresAuthentication`

Also change the request from POST to PUT seems to make more sense I think.

https://github.com/ParsePlatform/parse-server/wiki/NEW:-Class-Level-Permission:-requireAuthentication

**Comment by flovilmart** [comment]
Thanks! I updated the wiki!
