### ISSUE TITLE
Users Migrated from Parse to Heroku/Parse-server cant login

### ISSUE THREAD

**Issue by imovertheinternet** [ParsePlatform/parse-server#343]
I migrated everything from parse to mongolabs/heroku/parse-sever. When I try to login with an existing user (pre-migration) I get this error:
{code: 101, error: "Invalid username/password."}
code: 101
error: "Invalid username/password."

So I tried creating a new user to make sure im able to connect and write to the new mongolabs db and everything is talking to each other correctly, and I was able to login perfectly fine with this new user. So for some reason all old users cant login, however all new users can.

**Comment by gfosco** [comment]
Hmm... can you do some additional troubleshooting, perhaps log some details in users.js handleLogIn and try to find out where it's going wrong?  First report of this.

**Comment by imovertheinternet** [comment]
I couldnt figure out the problem. For what its worth, the database i was using was a clone of the database that was created via the parse db migration tool. (So a clone of a clone sort of). I ended up setting the DB var on heroku to point back to the DB that was created from the parse db migration tool. Works better this way anyways cause this db will automatically get updated by parse till I cut the cord. Thanks anyways

**Comment by Atid-Gharbi** [comment]
I have the same problem, users created after migration can login, and migrated users can't. Anyone knows if this has been solved?
