### ISSUE TITLE
FireBase For ios Push

### ISSUE THREAD

**Issue by taylorknopp** [ParsePlatform/parse-server#3430]
We are currently using Firebase with parse server to send Push notifications, and it is working fine. The problem we are having is getting APNS to work for IOS Push Notifications.  I don't believe our problems are related to a server issue, but none the less it isn't working. My question is, does parse server support using firebase for IOS Push Notifications like it does for Android?

**Comment by MartinHerman** [comment]
The real question here is - why would you even need Firebase push, when ParseServer supports notifications on its own.

What is your setup to send push notifications via Parse? Have you checked out this [guide](https://github.com/ParsePlatform/parse-server/wiki/Push)? 

Maybe post some code and explain what exactly you're trying to accomplish...

**Comment by taylorknopp** [comment]
If you look int he guide you just provided me, you can see under step 2 "Configure Parse Server" it asks for API Credentials for both GCM and APNS.
` var server = new ParseServer({
    databaseURI: '...',
    cloud: '...',
    appId: '...',
    masterKey: '...',
    push: {
      android: {
        senderId: '...',
        apiKey: '...'
      },
      ios: {
        pfx: '/file/path/to/XXX.p12',
        passphrase: '', // optional password to your p12/PFX
        bundleId: '',
        production: false
      }
    }
  });`
 Since fire base has replaced GCM we have to use FireBase for Android.   Since FireBase Also sais it can send push notifications to IOS devices, and we are having problems getting APNS working I thought maybe it would be possible to define FireBase credentials instead of APNS credentials for parse server.  something like this...
` var server = new ParseServer({
    databaseURI: '...',
    cloud: '...',
    appId: '...',
    masterKey: '...',
    push: {
      android: {
        senderId: '...',
        apiKey: '...'
      },
      ios: {
         senderId: '...',
        apiKey: '...'
      }
    }
  });`

**Comment by MartinHerman** [comment]
APNS works exactly as described in the wiki I linked above. You have to be more specific about what doesn't work. How are you initialising your ParseServer (the push part specifically)? Have you generated the .p12 files required? How does you iOS app subscribe for push notifications?

Post some of your code and describe the errors.

I have several apps using push notifications, and they work flawlessly - especially in combination with Parse Dashboard.

**Comment by taylorknopp** [comment]
As I have said above, I don;t think the problems with PANS come from something server side.  I don't get any errors on the server. It is client side that is the problem. Our IOS developer is having problems getting his client side app to be able to receive push notifications. But in the really I'm not here asking about APNS in an issue thread on the server which I have stated, I don't think is the issue. All I'm asking is whether it is possible to substitute FireBase for APNS as the push service for parse IOS push notifications.

**Comment by emkman** [comment]
@taylorknopp you can absolutely replace APNS with FireBase for iOS push. You just need a Push Adapter that knows how to speak to the Firebase API. Parse will provide you with the relevant device tokens and payload and you just need to send them to Firebase.

Here is an example adapter that sends Parse pushes to the OneSignal push service via their HTTP API: https://github.com/parse-server-modules/parse-server-onesignal-push-adapter/blob/master/src/OneSignalPushAdapter.js
The patterns would be almost identical for FCM. Here are the FCM HTTP docs: https://firebase.google.com/docs/cloud-messaging/server#implementing-http-connection-server-protocol
and here are some FCM npm modules if you aren't comfortable doing the HTTP calls yourself:
https://www.npmjs.com/package/fcm-push
https://www.npmjs.com/package/fcm-node

**Comment by flovilmart** [comment]
The adapter is already provided actually, it's parse-server-gcm-adapter

**Comment by flovilmart** [comment]
And it would be possible to make it support iOS push I believe

**Comment by hramos** [comment]
I am closing this out as we're trying to cut down on the number of non-issues. This will help us focus on the issues that are actively preventing people from migrating their production apps to Parse Server.

If you plan on opening a new issue, can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)?
