### ISSUE TITLE
Authentication Documentation

### ISSUE THREAD

**Issue by Vortec4800** [ParsePlatform/parse-server#3436]
I've seen references about authenticating users with LinkedIn on the server Wiki, and I see a bunch of Auth adapters included (and one for LinkedIn as well). I also know there are Auth Util libs available for iOS for Facebook and Twitter which are probably the most common, but I don't see instructions on how to use these custom Auth adapters with the iOS SDK to log a user in.

Is there documentation somewhere on this?

**Comment by hramos** [comment]
I am closing this out as we're trying to cut down on the number of non-issues. The docs are hosted at [parseplatform/docs](/parseplatform/docs).
