### ISSUE TITLE
fileAdapter - Google Cloud config not working

### ISSUE THREAD

**Issue by mauriciord** [ParsePlatform/parse-server#3438]
I'm trying to config my fileAdapter for Google Cloud Storage.
I'm using Bitnami with Google Cloud Platform. I've tried with `.json` and `.p12` files, but not working.
Trying to upload directly from Parse Dashboard, but 400 Bad Request.

![kapture 2017-01-26 at 18 25 31](https://cloud.githubusercontent.com/assets/1128701/22349053/2027d2e2-e3f5-11e6-90e7-83d5dc195308.gif)

I'm using as an instance:
```javascript
// ...
const GCSAdapter = require('parse-server-gcs-adapter');

const gcsAdapter = new GCSAdapter(
    'xxxxxxxxxxxx', 
    '/opt/bitnami/apps/parse/htdocs/xxxxx.json', 
    'xxxxxxxxxxxx', {
        bucketPrefix: '',
        directAccess: true
    }
);

const api = new ParseServer({
    databaseURI: 'mongodb://xxxxxxxxx',
    cloud: './node_modules/parse-server/lib/cloud-code/Parse.Cloud.js',
    appId: 'xxxxx',
    masterKey: 'xxxxxxx',
    fileKey: 'xxxxxxxx',
    serverURL: 'https://thoc.com.br/parse',
    filesAdapter: gcsAdapter
});
// ...
```

What can i do ?

**Comment by NatanRolnik** [comment]
@mauriciord my two cents here, maybe it can help you debugging it:

1 - Are you able to read and print to the console the json file?
2 - Can you run the server with `VERBOSE=1` and see the logs?
3 - If you try to upload a file via `curl`, does it succeed or also fails?

Also, not related to the storage adapter, your `cloud` parameter when initializing `ParseServer` is wrong. It shouldn't be `Parse.Cloud.js` from the SDK, but the entry point of your cloud code (for example, a `main.js` file where you add the functions to. Check the [Parse Server example](https://github.com/ParsePlatform/parse-server-example/blob/master/index.js#L16).

**Comment by mauriciord** [comment]
@NatanRolnik it's something with Bitnami, because i used parse-file-utils today on my local machine to migrate all images for the Google Cloud Storage and worked perfectly.
Is it possible to be something with Bitnami ?

**Comment by mauriciord** [comment]
@NatanRolnik if i try to post a file via POSTMAN it's shows me a 502 Bad Gateway

**Comment by mauriciord** [comment]
The `server.js` is configured with gcsAdapter and see the error:

![screen shot 2017-01-31 at 13 18 34](https://cloud.githubusercontent.com/assets/1128701/22470926/f344a310-e7b7-11e6-8bab-f1652183ed01.png)

why i cannot store the file ?

```json
{
  "code": 130,
  "error": "Could not store file."
}
```

If i change to fsAdapter, it works successfully, but not with gcsAdapter.

**Comment by mauriciord** [comment]
It was a Bitnami permission folder, working perfectly now.
Thanks for all

My GcsAdapter working now, this is how i made:

`cd /opt/bitnami/apps/parse`
`sudo mkdir .config`
`sudo chown bitnami:daemon -R .config`
`sudo chmod g+rwx .config`

Now it's working 100%, :grinning::grinning::grinning::grinning::grinning::grinning:
Thanks for all.

**Comment by NatanRolnik** [comment]
Glad you figured it out!
