### ISSUE TITLE
Cloud Code timeout in parse-server

### ISSUE THREAD

**Issue by jasonm1** [ParsePlatform/parse-server#3439]
Describe your issue in as much detail as possible.

I have a Cloud Code beforeSave that can take longer than 3 seconds to complete. Of course, this was impossible on the Parse hosted service, as it had a 3 second timeout, but I don't see why that needs to be the case on parse-server. Can I extend the timeout, and if so, how?

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.2
  - Operating System:     Amazon Linux 2016.09 
  - Hardware:            AWS
  - Localhost or remote server? AWS

- **Database**
  - MongoDB version: 3.0.11
  - Storage engine:  MMAPv1
  - Hardware:        ObjectRocket
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): ObjectRocket

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

 [Error]: The request timed out. (Code: 100, Version: 1.14.2)

**Comment by ethandrower** [comment]
hmm is the response code important to your app?  You could use the trigger to kickoff a cloud job I'd think which doesn't have a timeout

**Comment by flovilmart** [comment]
There is no timeout enforced by parse-server, the only timeout you'll hit will probably be from the http server configuration.

**Comment by JoaoArmandoo** [comment]
Hello flovilmart, I'm having this same problem, can you explain me how to increase the timeout time on the http server you mentioned?
