### ISSUE TITLE
old Logs are gone after deploying new version

### ISSUE THREAD

**Issue by shineall** [ParsePlatform/parse-server#3441]
I am very new person to parse-server. 

I am using default logger on aws beanstalk.
But after deploying new version to beanstalk, old logs are gone on dashboard. 
I cannot see the whole logs and cannot follow the issue.

Is anybody who know "how to store logs permanently or (specific time window ex) 1month)" on aws beanstalk. 

thank you for helping

**Comment by lkraider** [comment]
Check EB docs on logging to S3: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.logging.html

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.
