### ISSUE TITLE
Wiki out of date for Parse PHP SDK

### ISSUE THREAD

**Issue by montymxb** [ParsePlatform/parse-server#3446]
The Parse PHP SDK reference [in the wiki](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#using-parse-sdks-with-parse-server) is currently out of date. A correct call to ```ParseClient::setServerURL``` should take 2 parameters, a ```url``` and a ```mount path```.

It currently is:
```php
ParseClient::initialize('YOUR_APP_ID', 'YOUR_CLIENT_KEY', 'YOUR_MASTER_KEY');
ParseClient::setServerURL('http://localhost:1337/parse');
```

It should be:
```php
ParseClient::initialize('YOUR_APP_ID', 'YOUR_CLIENT_KEY', 'YOUR_MASTER_KEY');
ParseClient::setServerURL('http://localhost:1337', 'parse');
```

If any of the maintainers can make this change it would be much appreciated!

**Comment by mross22** [comment]
I've had really great response times on pull requests for the docs so you might try just submitting a PR yourself to make the change and then one of the owners can approve it.

**Comment by hramos** [comment]
The docs are now hosted at http://parseplatform.github.io/docs/php/guide/. Can you open the issue at the corresponding repo (https://github.com/ParsePlatform/docs), or (even better) send a PR?

**Comment by montymxb** [comment]
@hramos I was wondering about the docs repository, thanks for clarifying. I'll send a PR there when I have a moment.
