### ISSUE TITLE
Webhook for email verification

### ISSUE THREAD

**Issue by Charlesleonius** [ParsePlatform/parse-server#3447]
When a user clicks the email verification link sent by parse there should be some way to create an event in response. I tried implementing this by checking if the emailVerified field became true in the beforesave and aftersave functions but apparently these don't run on verification either! If anyone has a workaround for this please let me know but there should be some way to capture this event.

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.
