### ISSUE TITLE
ParseServer does not delete Session object on logout

### ISSUE THREAD

**Issue by guidesanti** [ParsePlatform/parse-server#346]
I have noticed that the behavior of hosted Parse is to create a new Session object when a user login and delete this object when this user logout from the same device.
When I tested the ParseServer version instead of the hosted Parse I noticed that this behavior is different, the Session object is created on login as expected, but on logout the object is not deleted, so if the user keeps logging in and logging out there will be as many Session objects on DB as the number of times the user login and logout.
Is this the expected behavior or is it a bug on ParseServer?

**Comment by gfosco** [comment]
This is a bug which will be fixed by #254.

**Comment by gfosco** [comment]
Merged fix and this will be in 2.0.8.
