### ISSUE TITLE
Parse is the best what can (I / average developers/the ex parsers) do to help this thing grow?

### ISSUE THREAD

**Issue by alexrmacleod** [ParsePlatform/parse-server#3460]
Recently Bucky Henry from [http://scaphold.io](url) contacted me and asked me about how I'm managing since parse shut down. Below is my response: 

-------- 

Initially I was devastated. I only knew swift.

But after I... 

Taught myself node; JavaScript 

Installed mongodb on a old lap top, followed the parse server YouTube setup tutorial. Ran parse server off the same laptop, learnt about port forwarding, updated my cloud code + my iOS app (www.tipp3d.com). I've never looked back.

Because parse shut down it forced me to get uncomfortable and learn node and js which really improved my app because I've refactored so many of my client side requests into cloud code functions 👊🏻. 

I love parse so much because... yea it lets you leverage an amazing node backend, without having to do boring stuff like messing around with mongoose and manually setting schemas. + push notification + user auth but mainly because it turned me into a better more confident developer. Just simply awesome. And it's even better now it's open source, less restrictions and I can run my server free at home until I get enough users and make money which only then it would make sense to get a droplet at digital ocean for only 5$ a month. Not bad.

Learning react js +  react native ATM...but I'm always gonna use parse server as my go to server side framework. There's simply nothing as good as parse - dashboard for mongodb out there. from my research node + mongodb is the way to go... Or am I wrong? 

Also I'm building out Tipped cross platform. Parse has an android, js and rest api that makes it easy for my devs to get going faster. Like parse has all the tools to build simple social apps, and that's what Tipped is so yea love it.

My only worry is that someday soon people on GitHub might stop maintaining the parse SDKs, then I'm ****ed. But I guess that's the case with any framework one picks.

--------

Anyways since I wrote that I got to thinking, man there must be something we could do to help make parse the obvious choice to newbie developers (me before the parse migration) who only know one client side language. 

Ideas? I have some...

1: Your parse-server-example youtube tutorial was awesome. Perhaps the geniuses who built parse could take it one step further and setup a Udemy.com course that goes through a few simple but awesome apps one could make on each of the parse SDKs, android, ios, maybe even a few react - native apps all running off of parse-server. Surely the facebook react + react-native teams want more people coding in react. Quality Udemy courses is an amazing way to convert new devs onto your frameworks. This would be a good investment because people are lazy, and once you can build something that works one way why learn to do the same thing another way? I'm so lazy i'd rather figure out how to grow parse then learn something like firebase. so yea new devs = long term. 
1.1: Then use the money from the Udemy courses to market parse. or just go on a vacation. you guys deserve one!

- for me I just loved that I could take my old macbook pro that was collecting dust, and turn it into a parse powered web server hooked up to a locally running mongodb. It felt so good knowing I could run my app completely for free. Felt like I was hacking the system lol. Maybe do a Udemy course on that. This one would be unique. heck, I might just do this myself. 

2: Convince Digital ocean/ Heroku, to do a promotional 6month free droplet for Parsers. Then a discounted rate until your droplet reaches a certain amount of traffic. Didn't Heroku have some sort of deal with Parse before it shut down? 

3: Once theres all this Udemy content the parse social channels will have stuff to post about. Perhaps people watching this repo could retweet, share ect... and drive traffic to the Udemy courses. 

Even if only a few read this and it ends at that. I just wanna say thanks for making parse. You guys helped me so much.

**Comment by hramos** [comment]
Thanks for the kind words! Now that the shut down is behind us, we will soon be working with the community to ensure contributors can continue developing Parse Server and the SDKs without us getting in the way. I don't think we will be working on new content or seeking out partnerships ourselves, but as we have seen in the past year, multiple companies have stepped forward to provide hosting solutions for Parse Server users.
