### ISSUE TITLE
Pass auth data to fileadapter

### ISSUE THREAD

**Issue by olheimer** [ParsePlatform/parse-server#3467]
Currently it seems impossible to control fileupload based on user authentication. My (ugly) solution was parsing body in a separate express middleware and evaluate if user may upload images. If not I don't call next() in that middleware. So parse won't run with that fileupload.

My proposal would be to hand over auth data to fileadapter, so fileadapter can decide if a user may upload files.

Or is there any other already existing way?

Thanks!

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.
