### ISSUE TITLE
Saving GeoPoint causing Internal Server Error

### ISSUE THREAD

**Issue by ayon115** [ParsePlatform/parse-server#3468]
### Issue Description

[DELETE EVERYTHING ABOVE THIS LINE BEFORE SUBMITTING YOUR ISSUE]

I am using Parse server 2.3.2 hosted on Azure for a project. Problem is, when I try to save a PFGeopoint object in User Table, it throws a Internal Server Error and the Geopoint never updates.
Here is my Swift Code to save user with a Geopoint object.

    let geopoint = PFGeoPoint(latitude: lat, longitude: lng)
        self.user = PFUser.current()
        self.user["location"] = geopoint
        print("user location save data = \(user)")
        self.user.saveInBackground { (success, error) in
            if error == nil {
                print("user location saved")
            } else {
                print("Error in \(#function) at location saving = \(error?.localizedDescription)")
            }
        }

I have checked the logs and according to Log, it's a MongoError. Logs are at the bottom of this post.

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1. Executing the swift code above 
2. Also, when in Parse Dashboard, if I edit the location (GeoPoint) object for my User, it does not persist. It rolls back to previous saved data. And log files shows the same result above.

#### Expected Results

Successful Save of Geopoint

#### Actual Outcome

The MongoError described above

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.2 , tested with 2.2.26 as well.
  - Operating System:   
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? -  Azure

- **Database**
  - MongoDB version: [FILL THIS OUT]
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [Azure]

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

[FILL THIS OUT]

2017-02-01T08:36:10.057Z - Uncaught internal server error. { MongoError: Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\r\nStack trace: Error: Invalid argument. Query root must be specified.\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\n   at Global code (__.sys.commonUpdate.js:1:2)"]}
ActivityId: d438e7dd-0000-0000-0000-000000000000, Request URI: rntbd://10.100.97.74:14000/apps/14788221-3cce-4a4c-8ac9-d10032fc8509/services/3add1ef1-ae46-43ae-a624-e88260acac96/partitions/01a9ee11-940a-4733-9741-2091924ce187/replicas/131262519911860994p
    at Function.MongoError.create (D:\home\site\wwwroot\node_modules\mongodb-core\lib\error.js:31:11)
    at D:\home\site\wwwroot\node_modules\mongodb-core\lib\connection\pool.js:462:72
    at authenticateStragglers (D:\home\site\wwwroot\node_modules\mongodb-core\lib\connection\pool.js:410:16)
    at Connection.messageHandler (D:\home\site\wwwroot\node_modules\mongodb-core\lib\connection\pool.js:444:5)
    at TLSSocket.<anonymous> (D:\home\site\wwwroot\node_modules\mongodb-core\lib\connection\connection.js:306:22)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:548:20)
  name: 'MongoError',
  message: 'Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\\r\\nStack trace: Error: Invalid argument. Query root must be specified.\\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\\n   at Global code (__.sys.commonUpdate.js:1:2)"]}\r\nActivityId: d438e7dd-0000-0000-0000-000000000000, Request URI: rntbd://10.100.97.74:14000/apps/14788221-3cce-4a4c-8ac9-d10032fc8509/services/3add1ef1-ae46-43ae-a624-e88260acac96/partitions/01a9ee11-940a-4733-9741-2091924ce187/replicas/131262519911860994p',
  _t: 'OKMongoResponse',
  ok: 0,
  code: 2,
  errmsg: 'Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\\r\\nStack trace: Error: Invalid argument. Query root must be specified.\\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\\n   at Global code (__.sys.commonUpdate.js:1:2)"]}\r\nActivityId: d438e7dd-0000-0000-0000-000000000000, Request URI: rntbd://10.100.97.74:14000/apps/14788221-3cce-4a4c-8ac9-d10032fc8509/services/3add1ef1-ae46-43ae-a624-e88260acac96/partitions/01a9ee11-940a-4733-9741-2091924ce187/replicas/131262519911860994p',
  '$err': 'Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\\r\\nStack trace: Error: Invalid argument. Query root must be specified.\\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\\n   at Global code (__.sys.commonUpdate.js:1:2)"]}\r\nActivityId: d438e7dd-0000-0000-0000-000000000000, Request URI: rntbd://10.100.97.74:14000/apps/14788221-3cce-4a4c-8ac9-d10032fc8509/services/3add1ef1-ae46-43ae-a624-e88260acac96/partitions/01a9ee11-940a-4733-9741-2091924ce187/replicas/131262519911860994p' } MongoError: Message: {"Errors":["Encountered exception while executing Javascript. Exception = Error: Invalid argument. Query root must be specified.\r\nStack trace: Error: Invalid argument. Query root must be specified.\n   at commonUpdate (__.sys.commonUpdate.js:2288:17)\n   at __docDbMain (__.sys.commonUpdate.js:4:5)\n   at Global code (__.sys.commonUpdate.js:1:2)"]}
ActivityId: d438e7dd-0000-0000-0000-000000000000, Request URI: rntbd://10.100.97.74:14000/apps/14788221-3cce-4a4c-8ac9-d10032fc8509/services/3add1ef1-ae46-43ae-a624-e88260acac96/partitions/01a9ee11-940a-4733-9741-2091924ce187/replicas/131262519911860994p
    at Function.MongoError.create (D:\home\site\wwwroot\node_modules\mongodb-core\lib\error.js:31:11)
    at D:\home\site\wwwroot\node_modules\mongodb-core\lib\connection\pool.js:462:72
    at authenticateStragglers (D:\home\site\wwwroot\node_modules\mongodb-core\lib\connection\pool.js:410:16)
    at Connection.messageHandler (D:\home\site\wwwroot\node_modules\mongodb-core\lib\connection\pool.js:444:5)
    at TLSSocket.<anonymous> (D:\home\site\wwwroot\node_modules\mongodb-core\lib\connection\connection.js:306:22)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:548:20)

**Comment by NatanRolnik** [comment]
Oh yeah. Another issue related to Azure... See #3462 and parse platform/parse-dashboard#651

**Comment by ayon115** [comment]
Seems like my issue is also solved after the fix from Azure team @NatanRolnik
