### ISSUE TITLE
currentUser caching in Parse-JS-SDK

### ISSUE THREAD

**Issue by maximeloizeau** [ParsePlatform/parse-server#3471]
After having the issue described in #2255, I investigated the possible causes and may have found a bigger one.

I noticed that the Javascript SDK is caching the current user and any other request made after that will use his session token if none is provided. I am not sure if this behaviour can provoke issues but this is good to know if it was not the intended behaviour in the first place.

Regarding the issue #2255, when a user is logging out, parse-server is deleting the cached user and the session row. But the JS-SDK is not notified of that logging out so it keeps the cached user.
Then, if you make an anonymous request (cloud function or anything), it will use the cached session token that is now invalid.

I am doing to do a pull request for that log out issue.

EDIT: I actually thought parse-server was calling Parse.User.logIn() but it isn't. So I am not sure if the best fix is to call Parse.User.logOut()

**Comment by maximeloizeau** [comment]
I was going to submit a pull request that fixes it, temporarily at least, by calling Parse.User.logOut(). But after thought it won't because if you have multiple servers, only one of them will delete the cached user.

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.
