### ISSUE TITLE
should serverURL be required when using parse as middleware?

### ISSUE THREAD

**Issue by taylorstine** [ParsePlatform/parse-server#3472]
serverURL seems like such a strange parameter to add when using parse as middleware.  Why would you need to specify the url on which you're hosting the middleware?  I see in the parse/node code, parse uses this url to make requests to itself to perform things like batch updates.  

Obviously this parameter makes sense when running parse server in stand-alone mode, but I'm having trouble seeing it's purpose in express middleware.  Is there a design decision behind this, or is this just for ease of compatibility with the legacy parse/node implementation? In an ideal situation, would an update be made so that serverURL wouldn't be required if using parse as middleware, and parse server would use it's own internal operators instead of making a request to itself?

**Comment by flovilmart** [comment]
serverURL Is required by cloud code to communicate back to parse-server, there is an experimental direct access flag that uses the internal API's instead of the http API.

**Comment by taylorstine** [comment]
Could you provide a link for reference to where I can set this flag?

**Comment by flovilmart** [comment]
Set PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS=1 as an environment variable.

Note that cloud code should not use Parse.Cloud.useMasterKey() nor Parse.User.current()
