### ISSUE TITLE
[Solution] vkontakte authorization does not work

### ISSUE THREAD

**Issue by VladimirMihalko** [ParsePlatform/parse-server#3474]
### Issue Description

vkontakte authorization does not work

### Environment Setup

- parse-server version: 2.3.2

### Solution

Function vkOAuth2Request in file "parse-server/src/Adapters/Auth/vkontakte.js" does nothing.
I know nothing about JS, but I think it's because of empty Promise.
If you remove the Promise, then the function works correctly.

```
function vkOAuth2Request(params) {
  var promise = new Parse.Promise();
  return promise.then(function(){
    if (!params || !params.appIds || !params.appIds.length || !params.appSecret || !params.appSecret.length) {
      logger.error('Vk Auth', 'Vk auth is not configured. Missing appIds or appSecret.');
      throw new Parse.Error(Parse.Error.OBJECT_NOT_FOUND, 'Vk auth is not configured. Missing appIds or appSecret.');
    }
    return request("oauth.vk.com", "access_token?client_id=" + params.appIds + "&client_secret=" + params.appSecret + "&v=5.59&grant_type=client_credentials")
  })
}

```
Please replace the function with correct version:

```
function vkOAuth2Request(params) {
  if (!params || !params.appIds || !params.appIds.length || !params.appSecret || !params.appSecret.length) {
    logger.error('Vk Auth', 'Vk auth is not configured. Missing appIds or appSecret.');
    throw new Parse.Error(Parse.Error.OBJECT_NOT_FOUND, 'Vk auth is not configured. Missing appIds or appSecret.');
  }
  return request("oauth.vk.com", "access_token?client_id=" + params.appIds + "&client_secret=" + params.appSecret + "&v=5.59&grant_type=client_credentials")
}

```

Sorry, but I can't make pull request.

**Comment by hramos** [comment]
Closing as this is not an issue. Consider making a PR.

**Comment by WilfredR** [comment]
@hramos I just raised the following issue https://github.com/ParsePlatform/parse-server/issues/3581

I'm not sure it's related. 

the `function vkOAuth2Request(params)` might make a Promise to many, and anyhow non of the other auth adapters make a `Parse.Promise`.

I'd love to contribute and solve this, but I simply don't know how. I see something might not be right (and it's not working with me) but I don't know what is the right way (still a noob)

@flovilmart As I remember the coder who fixed this code is an iOS developer and explicitly said not node.js so it's probably worth while to check the chain of `Promise`
