### ISSUE TITLE
Could not able to get ParseFile after migration

### ISSUE THREAD

**Issue by jaydeeppatel292** [ParsePlatform/parse-server#3478]
I have not used ParseFile as Column in ParseClass because in my project files can be stored anywhere so I used string column in parse class to store ParseFile URLs or S3 URLs. 

So whenever I upload through ParseFile I store ParseFile's Url in ParseObject.
 
Like one of my ParseObject stores FilePath as http://files.parsetfss.com/myfilekey/tfss-745bf75d-66b3-4a60-8edf-8a05f8608b3f-filename.mp3

Now after parse shutdown, http://files.parsetfss.com/ is not working so is there any way to get my old ParseFile URLs so that I can change my object's FilePath?

**Comment by NatanRolnik** [comment]
@jaydeeppatel292 you should have downloaded the files, transferred to your storage service of choice, and update the URLs. 
It was clear from the Parse migration guide that the files would be deleted after the shutdown, and we all had enough time to take care of it. I don't think there's anything that can be done now.
