### ISSUE TITLE
Unable to migrate to MongoLab

### ISSUE THREAD

**Issue by Kira2** [ParsePlatform/parse-server#348]
Hi,

I tried to apply the migration guide for one of my application, and this is the message I have when I click on "Finalize" to migrate the database to MongoLab:

"We were unable to commit your migration. Please try again."

Nothing more. I posted this message on the Google group, and I was told to open a bug for migration issue.

This is the first step to migrate my applications and it does not work -_-

Thank for your help.

**Comment by drew-gross** [comment]
Please open an issue using parse.com/help and include your Job ID (visible on the migration page)
