### ISSUE TITLE
Disable record creation with public ACl

### ISSUE THREAD

**Issue by manishsangwan** [ParsePlatform/parse-server#3481]
I have a class where while adding  a record i set acl to user ie neither public read or write. But this class also allows acls with public read and write to be created. When i disable CLP for public create it even disables the creation of record with acl set to user.

**Comment by NatanRolnik** [comment]
@manishsangwan it's not clear what you are trying, and what you are trying to achieve. If CLPs don't allow public writes on a class, objects will be created only with Master Key.  I recommend you to taking a look into the docs regarding [CLPs and ACLs interaction](http://parseplatform.github.io/docs/js/guide/#clp-and-acl-interaction):

> Class-Level Permissions (CLPs) and Access Control Lists (ACLs) are both powerful tools for securing your app, but they don’t always interact exactly how you might expect. They actually represent two separate layers of security that each request has to pass through to return the correct information or make the intended change.

**Comment by manishsangwan** [comment]
thanx @NatanRolnik  will look at it.
