### ISSUE TITLE
Cannot get values through nested pointers from a parse object

### ISSUE THREAD

**Issue by WillTheDistance** [ParsePlatform/parse-server#3482]
### Issue Description

Describe your issue in as much detail as possible.

In cloud code when I try to get value which is nested through pointers, it breaks the script (lines 22, 23 and 24). However in the json response to my post (line 26), all of the values from the pointers are outputted as expected. How do I get a single value from a nested pointer?

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1. Copy this code into cloud ...

`Parse.Cloud.define("example", function (request, response) {

	request.log.info("example");

    var Parent = Parse.Object.extend("Parent");
    var parent = new Parent();
    parent.set("name", "Dave");

    parent.save();

    var Child = Parse.Object.extend("Child");
    var child = new Child();
    child.set("parent", parent);
    child.save();

    var childQuery = new Parse.Query(Child);

    childQuery.include("parent");

    childQuery.find({
    success: function(results) {
        console.log("Got here");
        var nestedPointer = results[0].parent.get('name');
        console.log("Did not get here");

        response.success(results);
    },
    error: function(error) {
        alert("Error: " + error.code + " " + error.message);
    }
    });
}); 

//Getting data from the nested pointer breaks the script

//If lines 22, 23 and 24 are removed the code returns the whole data model including the data we cannot get from the parse object.`

2. Run cloud code (I used postman)

#### Expected Results

console log: "Got here"
console log: "Did not get here"
Child parse object returned
var nestedPointer populated

#### Actual Outcome

console log: "Got here"

(If you remove line 23)

console log: "Got here"
console log: "Did not get here"
Child parse object returned

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : ^2.3.2
  - Operating System:     Windows 10
  - Hardware: AWS EC2
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc):  Localhost

- **Database**
  - MongoDB version: 3.2.x
  - Storage engine:  MMAPv1
  - Hardware: AWS EC2
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Localhost

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

`verbose: Support key pairs Map {}
the-core-v3 running on port 1337.
info: Parse LiveQuery Server starts running
verbose: REQUEST for [POST] /parse/functions/example: {} method=POST, url=/parse/functions/example, host=localhost:1337, connection=keep-alive, content-length=0, origin=chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop, postman-token=5493ddd6-e4ac-c6e3-00d3-8c3beed949b7, cache-control=no-cache, x-parse-master-key=foobarbaz, x-parse-application-id=DinerMojo, user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36, content-type=application/json, accept=*/*, accept-encoding=gzip, deflate, br, accept-language=en-US,en;q=0.8,
info: example
verbose: REQUEST for [GET] /parse/classes/Child: {
  "where": {},
  "include": "parent"
} method=GET, url=/parse/classes/Child, user-agent=node-XMLHttpRequest, Parse/js1.9.2 (NodeJS 6.9.1), accept=*/*, content-type=text/plain, host=localhost:1337, content-length=186, connection=close, , include=parent
verbose: REQUEST for [POST] /parse/classes/Parent: {
  "name": "Dave"
} method=POST, url=/parse/classes/Parent, user-agent=node-XMLHttpRequest, Parse/js1.9.2 (NodeJS 6.9.1), accept=*/*, content-type=text/plain, host=localhost:1337, content-length=154, connection=close, name=Dave
verbose: RESPONSE from [POST] /parse/classes/Parent: {
  "status": 201,
  "response": {
    "objectId": "Zt1dt44Js6",
    "createdAt": "2017-02-06T16:17:05.773Z"
  },
  "location": "http://localhost:1337/parse/classes/Parent/Zt1dt44Js6"
} status=201, objectId=Zt1dt44Js6, createdAt=2017-02-06T16:17:05.773Z, location=http://localhost:1337/parse/classes/Parent/Zt1dt44Js6
verbose: RESPONSE from [GET] /parse/classes/Child: {
  "response": {
    "results": [
      {
        "objectId": "4M5rYKyQCG",
        "parent": {
          "objectId": "32ydrpdE3z",
          "name": "Dave",
          "createdAt": "2017-02-01T16:48:05.577Z",
          "updatedAt": "2017-02-01T16:48:05.733Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-01T16:48:05.756Z",
        "updatedAt": "2017-02-01T16:48:05.756Z"
      },
      {
        "objectId": "yqfzQDy9FK",
        "parent": {
          "objectId": "49k1ZsX9Va",
          "name": "Dave",
          "createdAt": "2017-02-01T16:50:25.948Z",
          "updatedAt": "2017-02-01T16:50:26.028Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-01T16:50:26.070Z",
        "updatedAt": "2017-02-01T16:50:26.070Z"
      },
      {
        "objectId": "7QBBOEmXQV",
        "parent": {
          "objectId": "eNfaQYOQTc",
          "name": "Dave",
          "createdAt": "2017-02-01T16:57:59.349Z",
          "updatedAt": "2017-02-01T16:57:59.417Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-01T16:57:59.450Z",
        "updatedAt": "2017-02-01T16:57:59.450Z"
      },
      {
        "objectId": "QwJwwcldmW",
        "parent": {
          "objectId": "Cjlc33sOO8",
          "name": "Dave",
          "createdAt": "2017-02-01T17:07:39.289Z",
          "updatedAt": "2017-02-01T17:07:39.364Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-01T17:07:39.397Z",
        "updatedAt": "2017-02-01T17:07:39.397Z"
      },
      {
        "objectId": "oeZopdenhF",
        "parent": {
          "objectId": "68TVG2HM3O",
          "name": "Dave",
          "createdAt": "2017-02-01T17:12:31.823Z",
          "updatedAt": "2017-02-01T17:12:31.892Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-01T17:12:31.931Z",
        "updatedAt": "2017-02-01T17:12:31.931Z"
      },
      {
        "objectId": "1GZWOxzf0G",
        "parent": {
          "objectId": "W8i4hoBZi1",
          "name": "Dave",
          "createdAt": "2017-02-01T17:12:59.797Z",
          "updatedAt": "2017-02-01T17:12:59.868Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-01T17:12:59.907Z",
        "updatedAt": "2017-02-01T17:12:59.907Z"
      },
      {
        "objectId": "X9ASQtosYS",
        "parent": {
          "objectId": "d9nrfNbrSl",
          "name": "Dave",
          "createdAt": "2017-02-01T17:16:52.183Z",
          "updatedAt": "2017-02-01T17:16:52.249Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-01T17:16:52.287Z",
        "updatedAt": "2017-02-01T17:16:52.287Z"
      },
      {
        "objectId": "erxDXT1DVp",
        "parent": {
          "objectId": "tNJdieDhmq",
          "name": "Dave",
          "createdAt": "2017-02-01T17:18:57.425Z",
          "updatedAt": "2017-02-01T17:18:57.507Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-01T17:18:57.537Z",
        "updatedAt": "2017-02-01T17:18:57.537Z"
      },
      {
        "objectId": "m99CtLJpDP",
        "parent": {
          "objectId": "z2LaRUQMvo",
          "name": "Dave",
          "createdAt": "2017-02-01T17:21:34.904Z",
          "updatedAt": "2017-02-01T17:21:34.978Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-01T17:21:35.011Z",
        "updatedAt": "2017-02-01T17:21:35.011Z"
      },
      {
        "objectId": "YBBA5kKI9a",
        "parent": {
          "objectId": "4DbiILRFOx",
          "name": "Dave",
          "createdAt": "2017-02-01T17:22:55.366Z",
          "updatedAt": "2017-02-01T17:22:55.438Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-01T17:22:55.474Z",
        "updatedAt": "2017-02-01T17:22:55.474Z"
      },
      {
        "objectId": "xzSYy5pddf",
        "parent": {
          "objectId": "eV0kFNP1UO",
          "name": "Dave",
          "createdAt": "2017-02-02T09:39:09.837Z",
          "updatedAt": "2017-02-02T09:39:09.905Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-02T09:39:09.943Z",
        "updatedAt": "2017-02-02T09:39:09.943Z"
      },
      {
        "objectId": "3WNMYVkwdT",
        "parent": {
          "objectId": "uZzhgBoUNm",
          "name": "Dave",
          "createdAt": "2017-02-02T09:45:48.492Z",
          "updatedAt": "2017-02-02T09:45:48.587Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-02T09:45:48.612Z",
        "updatedAt": "2017-02-02T09:45:48.612Z"
      },
      {
        "objectId": "YCN27YQ4Xe",
        "parent": {
          "objectId": "oYmmHbPQn5",
          "name": "Dave",
          "createdAt": "2017-02-02T09:48:28.482Z",
          "updatedAt": "2017-02-02T09:48:28.605Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-02T09:48:28.640Z",
        "updatedAt": "2017-02-02T09:48:28.640Z"
      },
      {
        "objectId": "EtIxko1Xcd",
        "parent": {
          "objectId": "1fDbrN2hIx",
          "name": "Dave",
          "createdAt": "2017-02-02T09:49:18.298Z",
          "updatedAt": "2017-02-02T09:49:18.394Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-02T09:49:18.421Z",
        "updatedAt": "2017-02-02T09:49:18.421Z"
      },
      {
        "objectId": "Dt1VAPiBrH",
        "parent": {
          "objectId": "cpRi15cBeb",
          "name": "Dave",
          "createdAt": "2017-02-02T09:50:15.239Z",
          "updatedAt": "2017-02-02T09:50:15.329Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-02T09:50:15.352Z",
        "updatedAt": "2017-02-02T09:50:15.352Z"
      },
      {
        "objectId": "MlGaMALZpH",
        "parent": {
          "objectId": "8GR6HJAGTg",
          "name": "Dave",
          "createdAt": "2017-02-02T09:52:02.829Z",
          "updatedAt": "2017-02-02T09:52:02.968Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-02T09:52:02.989Z",
        "updatedAt": "2017-02-02T09:52:02.989Z"
      },
      {
        "objectId": "ljvs9WqOot",
        "parent": {
          "objectId": "BmIAi8zTHD",
          "name": "Dave",
          "createdAt": "2017-02-02T09:52:48.783Z",
          "updatedAt": "2017-02-02T09:52:48.880Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-02T09:52:48.902Z",
        "updatedAt": "2017-02-02T09:52:48.902Z"
      },
      {
        "objectId": "ziKYTRSOoM",
        "parent": {
          "objectId": "rwaL1uv953",
          "name": "Dave",
          "createdAt": "2017-02-02T09:56:20.510Z",
          "updatedAt": "2017-02-02T09:56:20.634Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-02T09:56:20.663Z",
        "updatedAt": "2017-02-02T09:56:20.663Z"
      },
      {
        "objectId": "TMtpCeDmol",
        "parent": {
          "objectId": "hWmBD85hLR",
          "name": "Dave",
          "createdAt": "2017-02-02T09:57:05.559Z",
          "updatedAt": "2017-02-02T09:57:05.656Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-02T09:57:05.683Z",
        "updatedAt": "2017-02-02T09:57:05.683Z"
      },
      {
        "objectId": "CxnbdoOSLJ",
        "parent": {
          "objectId": "Ul64Qc0420",
          "name": "Dave",
          "createdAt": "2017-02-02T09:57:24.568Z",
          "updatedAt": "2017-02-02T09:57:24.671Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-02T09:57:24.693Z",
        "updatedAt": "2017-02-02T09:57:24.693Z"
      },
      {
        "objectId": "tN3eH8HIhS",
        "parent": {
          "objectId": "yRQEGP2VF8",
          "name": "Dave",
          "createdAt": "2017-02-02T09:58:44.366Z",
          "updatedAt": "2017-02-02T09:58:44.461Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-02T09:58:44.484Z",
        "updatedAt": "2017-02-02T09:58:44.484Z"
      },
      {
        "objectId": "BhYaS1Ifps",
        "parent": {
          "objectId": "IYpC9EIai3",
          "name": "Dave",
          "createdAt": "2017-02-02T09:59:36.333Z",
          "updatedAt": "2017-02-02T09:59:36.538Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-02T09:59:36.558Z",
        "updatedAt": "2017-02-02T09:59:36.558Z"
      },
      {
        "objectId": "STx1fef4gZ",
        "parent": {
          "objectId": "WK7TC3Kl71",
          "name": "Dave",
          "createdAt": "2017-02-02T10:00:05.065Z",
          "updatedAt": "2017-02-02T10:00:05.173Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-02T10:00:05.197Z",
        "updatedAt": "2017-02-02T10:00:05.197Z"
      },
      {
        "objectId": "6tFCwoSFst",
        "parent": {
          "objectId": "h9EoR8KZAB",
          "name": "Dave",
          "createdAt": "2017-02-02T10:00:37.289Z",
          "updatedAt": "2017-02-02T10:00:37.474Z",
          "__type": "Object",
          "className": "Parent"
        },
        "createdAt": "2017-02-02T10:00:37.506Z",
        "updatedAt": "2017-02-02T10:00:37.506Z"
      }
    ]
  }
} results=[objectId=4M5rYKyQCG, objectId=32ydrpdE3z, name=Dave, createdAt=2017-02-01T16:48:05.577Z, updatedAt=2017-02-01T16:48:05.733Z, __type=Object, className=Parent, createdAt=2017-02-01T16:48:05.756Z, updatedAt=2017-02-01T16:48:05.756Z, objectId=yqfzQDy9FK, objectId=49k1ZsX9Va, name=Dave, createdAt=2017-02-01T16:50:25.948Z, updatedAt=2017-02-01T16:50:26.028Z, __type=Object, className=Parent, createdAt=2017-02-01T16:50:26.070Z, updatedAt=2017-02-01T16:50:26.070Z, objectId=7QBBOEmXQV, objectId=eNfaQYOQTc, name=Dave, createdAt=2017-02-01T16:57:59.349Z, updatedAt=2017-02-01T16:57:59.417Z, __type=Object, className=Parent, createdAt=2017-02-01T16:57:59.450Z, updatedAt=2017-02-01T16:57:59.450Z, objectId=QwJwwcldmW, objectId=Cjlc33sOO8, name=Dave, createdAt=2017-02-01T17:07:39.289Z, updatedAt=2017-02-01T17:07:39.364Z, __type=Object, className=Parent, createdAt=2017-02-01T17:07:39.397Z, updatedAt=2017-02-01T17:07:39.397Z, objectId=oeZopdenhF, objectId=68TVG2HM3O, name=Dave, createdAt=2017-02-01T17:12:31.823Z, updatedAt=2017-02-01T17:12:31.892Z, __type=Object, className=Parent, createdAt=2017-02-01T17:12:31.931Z, updatedAt=2017-02-01T17:12:31.931Z, objectId=1GZWOxzf0G, objectId=W8i4hoBZi1, name=Dave, createdAt=2017-02-01T17:12:59.797Z, updatedAt=2017-02-01T17:12:59.868Z, __type=Object, className=Parent, createdAt=2017-02-01T17:12:59.907Z, updatedAt=2017-02-01T17:12:59.907Z, objectId=X9ASQtosYS, objectId=d9nrfNbrSl, name=Dave, createdAt=2017-02-01T17:16:52.183Z, updatedAt=2017-02-01T17:16:52.249Z, __type=Object, className=Parent, createdAt=2017-02-01T17:16:52.287Z, updatedAt=2017-02-01T17:16:52.287Z, objectId=erxDXT1DVp, objectId=tNJdieDhmq, name=Dave, createdAt=2017-02-01T17:18:57.425Z, updatedAt=2017-02-01T17:18:57.507Z, __type=Object, className=Parent, createdAt=2017-02-01T17:18:57.537Z, updatedAt=2017-02-01T17:18:57.537Z, objectId=m99CtLJpDP, objectId=z2LaRUQMvo, name=Dave, createdAt=2017-02-01T17:21:34.904Z, updatedAt=2017-02-01T17:21:34.978Z, __type=Object, className=Parent, createdAt=2017-02-01T17:21:35.011Z, updatedAt=2017-02-01T17:21:35.011Z, objectId=YBBA5kKI9a, objectId=4DbiILRFOx, name=Dave, createdAt=2017-02-01T17:22:55.366Z, updatedAt=2017-02-01T17:22:55.438Z, __type=Object, className=Parent, createdAt=2017-02-01T17:22:55.474Z, updatedAt=2017-02-01T17:22:55.474Z, objectId=xzSYy5pddf, objectId=eV0kFNP1UO, name=Dave, createdAt=2017-02-02T09:39:09.837Z, updatedAt=2017-02-02T09:39:09.905Z, __type=Object, className=Parent, createdAt=2017-02-02T09:39:09.943Z, updatedAt=2017-02-02T09:39:09.943Z, objectId=3WNMYVkwdT, objectId=uZzhgBoUNm, name=Dave, createdAt=2017-02-02T09:45:48.492Z, updatedAt=2017-02-02T09:45:48.587Z, __type=Object, className=Parent, createdAt=2017-02-02T09:45:48.612Z, updatedAt=2017-02-02T09:45:48.612Z, objectId=YCN27YQ4Xe, objectId=oYmmHbPQn5, name=Dave, createdAt=2017-02-02T09:48:28.482Z, updatedAt=2017-02-02T09:48:28.605Z, __type=Object, className=Parent, createdAt=2017-02-02T09:48:28.640Z, updatedAt=2017-02-02T09:48:28.640Z, objectId=EtIxko1Xcd, objectId=1fDbrN2hIx, name=Dave, createdAt=2017-02-02T09:49:18.298Z, updatedAt=2017-02-02T09:49:18.394Z, __type=Object, className=Parent, createdAt=2017-02-02T09:49:18.421Z, updatedAt=2017-02-02T09:49:18.421Z, objectId=Dt1VAPiBrH, objectId=cpRi15cBeb, name=Dave, createdAt=2017-02-02T09:50:15.239Z, updatedAt=2017-02-02T09:50:15.329Z, __type=Object, className=Parent, createdAt=2017-02-02T09:50:15.352Z, updatedAt=2017-02-02T09:50:15.352Z, objectId=MlGaMALZpH, objectId=8GR6HJAGTg, name=Dave, createdAt=2017-02-02T09:52:02.829Z, updatedAt=2017-02-02T09:52:02.968Z, __type=Object, className=Parent, createdAt=2017-02-02T09:52:02.989Z, updatedAt=2017-02-02T09:52:02.989Z, objectId=ljvs9WqOot, objectId=BmIAi8zTHD, name=Dave, createdAt=2017-02-02T09:52:48.783Z, updatedAt=2017-02-02T09:52:48.880Z, __type=Object, className=Parent, createdAt=2017-02-02T09:52:48.902Z, updatedAt=2017-02-02T09:52:48.902Z, objectId=ziKYTRSOoM, objectId=rwaL1uv953, name=Dave, createdAt=2017-02-02T09:56:20.510Z, updatedAt=2017-02-02T09:56:20.634Z, __type=Object, className=Parent, createdAt=2017-02-02T09:56:20.663Z, updatedAt=2017-02-02T09:56:20.663Z, objectId=TMtpCeDmol, objectId=hWmBD85hLR, name=Dave, createdAt=2017-02-02T09:57:05.559Z, updatedAt=2017-02-02T09:57:05.656Z, __type=Object, className=Parent, createdAt=2017-02-02T09:57:05.683Z, updatedAt=2017-02-02T09:57:05.683Z, objectId=CxnbdoOSLJ, objectId=Ul64Qc0420, name=Dave, createdAt=2017-02-02T09:57:24.568Z, updatedAt=2017-02-02T09:57:24.671Z, __type=Object, className=Parent, createdAt=2017-02-02T09:57:24.693Z, updatedAt=2017-02-02T09:57:24.693Z, objectId=tN3eH8HIhS, objectId=yRQEGP2VF8, name=Dave, createdAt=2017-02-02T09:58:44.366Z, updatedAt=2017-02-02T09:58:44.461Z, __type=Object, className=Parent, createdAt=2017-02-02T09:58:44.484Z, updatedAt=2017-02-02T09:58:44.484Z, objectId=BhYaS1Ifps, objectId=IYpC9EIai3, name=Dave, createdAt=2017-02-02T09:59:36.333Z, updatedAt=2017-02-02T09:59:36.538Z, __type=Object, className=Parent, createdAt=2017-02-02T09:59:36.558Z, updatedAt=2017-02-02T09:59:36.558Z, objectId=STx1fef4gZ, objectId=WK7TC3Kl71, name=Dave, createdAt=2017-02-02T10:00:05.065Z, updatedAt=2017-02-02T10:00:05.173Z, __type=Object, className=Parent, createdAt=2017-02-02T10:00:05.197Z, updatedAt=2017-02-02T10:00:05.197Z, objectId=6tFCwoSFst, objectId=h9EoR8KZAB, name=Dave, createdAt=2017-02-02T10:00:37.289Z, updatedAt=2017-02-02T10:00:37.474Z, __type=Object, className=Parent, createdAt=2017-02-02T10:00:37.506Z, updatedAt=2017-02-02T10:00:37.506Z]
Got here
verbose: REQUEST for [POST] /parse/batch: {
  "requests": [
    {
      "method": "PUT",
      "body": {},
      "path": "/parse/classes/Parent/Zt1dt44Js6"
    }
  ]
} method=POST, url=/parse/batch, user-agent=node-XMLHttpRequest, Parse/js1.9.2 (NodeJS 6.9.1), accept=*/*, content-type=text/plain, host=localhost:1337, content-length=222, connection=close, requests=[method=PUT, , path=/parse/classes/Parent/Zt1dt44Js6]
verbose: RESPONSE from [POST] /parse/batch: {
  "response": [
    {
      "success": {
        "updatedAt": "2017-02-06T16:17:05.926Z"
      }
    }
  ]
} response=[updatedAt=2017-02-06T16:17:05.926Z]
verbose: REQUEST for [POST] /parse/classes/Child: {
  "parent": {
    "__type": "Pointer",
    "className": "Parent",
    "objectId": "Zt1dt44Js6"
  }
} method=POST, url=/parse/classes/Child, user-agent=node-XMLHttpRequest, Parse/js1.9.2 (NodeJS 6.9.1), accept=*/*, content-type=text/plain, host=localhost:1337, content-length=215, connection=close, __type=Pointer, className=Parent, objectId=Zt1dt44Js6
verbose: RESPONSE from [POST] /parse/classes/Child: {
  "status": 201,
  "response": {
    "objectId": "BtkoqtwnUn",
    "createdAt": "2017-02-06T16:17:05.959Z"
  },
  "location": "http://localhost:1337/parse/classes/Child/BtkoqtwnUn"
} status=201, objectId=BtkoqtwnUn, createdAt=2017-02-06T16:17:05.959Z, location=http://localhost:1337/parse/classes/Child/BtkoqtwnUn`

**Comment by WillTheDistance** [comment]
Ignore the fact that multiple parents are in the output. Its due to the amount of times I have run the script. Should have remembered to clean it up before submitting.

**Comment by flovilmart** [comment]
Can you clean it up?

**Comment by NatanRolnik** [comment]
In the line that you do:
`var nestedPointer = results[0].parent.get('name');`

You should be doing:
`var nestedPointer = results[0].get('parent').get('name');
