### ISSUE TITLE
Logging all requests

### ISSUE THREAD

**Issue by jhamet93** [ParsePlatform/parse-server#3487]
When setting up ElasticSearch for my Parse Server, I discovered very few logs propagating through when my log level was set to info. When taking a closer look at the source code, I found the info level is only used for cloud code triggers and functions. 

I was hoping to use ElasticSearch to be able to analyze the queries that are coming in and possibly even the responses from users using an application running on Parse server.

Would this be a desired feature at all ? I can submit a pull request but was just curious if anyone in the community would be interested in a feature like this.

**Comment by flovilmart** [comment]
Using VERBOSE=1 will log all requests, there are other options to forward the logs to a sink IIRC  @acinader implemented such thing.

**Comment by acinader** [comment]
Hi @jhamet93 take a look at https://www.npmjs.com/package/parse-aws-firehose-logger-adapter

It works like a charm for me. If you want to give it a try and my readme isn't adequate to setup, I'm glad to help to make it easier and update the readme.

As for adding more "info" logging, what do you have in mind?

**Comment by jhamet93** [comment]
@acinader 

So I actually discovered your tool and implemented that pretty easily. I have my VERBOSE environmental variable enabled and set the logger level to info and verbose in my various attempts. My expectation was all the requests that are issued, are sent to AWS firehose which is then streamed to elastic search based on my setup.

I use Heroku at the moment so when I look at the logs, I can see all the requests and responses, however, they're not being streamed to firehose.  However, there are some logs which do get streamed such as the triggers (so I know my setup is at least correct credential wise). I was unsure if there could be something I'm misconfiguring or if that expectation is incorrect.

By the way, thanks for the adapter, it was exactly what I was looking for.

**Comment by acinader** [comment]
@jhamet93 i'd like to help you figure out what is going on.

the first thing that comes to mind is that while verbose may be turned on, it is possible that it isn't turned on for the firehose logging adapter somehow.  You can test that by looking at the level that logged on heroku as well as in elasticsearch.  if all of the logs in elastic search are just info and the ones that you are missing are verbose or debug, that that is likely the problem and we can look at how the adapter is configured and if we need to make a code or documentation change?

if that's not the problem, then finding some specific log messages that are missing where we can track down the source in the source code and then i could make some unit tests around it to understand what is going on?

**Comment by jhamet93** [comment]
@acinader 

I believe I found the issue so I will take this conversation over to your repository.
