### ISSUE TITLE
request.params causing internal server error on Heroku in Cloud functions

### ISSUE THREAD

**Issue by davidsims9t** [ParsePlatform/parse-server#349]
Hello,

I'm attempting to migrate my data away from Parse and I noticed that request.params is causing an internal server error. I have written an example that causes the error.

`Parse.Cloud.define("test", function(request, response) {
  response.success(request.params.test);
});`

**Comment by gfosco** [comment]
What is the error returned?

**Comment by davidsims9t** [comment]
It's an internal server error. Other than that I don't know what the specific error is. Oddly enough it only happens when I post parameter. If I return request.params without any request body I get {}.

**Comment by gateway** [comment]
@davidsims9t nothing in the logs?

**Comment by gfosco** [comment]
I'm assuming this has been fixed.  If there's an issue with 2.1.3+, please open a new one.  Thanks.
