### ISSUE TITLE
Possible to log or at least determine the exact queries that are being run against MongoDB?

### ISSUE THREAD

**Issue by AndrewLane** [ParsePlatform/parse-server#3490]
We are looking into indexing on our MongoDB, so it would be helpful to know what exact queries that Parse Server is running against MongoDB.  Is there any kind of verbose logging that would spit the queries out?  Or any other way to determine the queries being run?  Thanks!

**Comment by acinader** [comment]
look at mongodb docs.  https://docs.mongodb.com/manual/reference/configuration-options/#operationProfiling.slowOpThresholdMs

**Comment by AndrewLane** [comment]
Never even considered doing it directly on Mongo.  Doh!  Thanks!
