### ISSUE TITLE
How do I go about after signing up a user, to get the current user server side?

### ISSUE THREAD

**Issue by farhansyed9** [ParsePlatform/parse-server#3491]
I am aware parse-express-cookie-session doesn't carry over to Parse Server and Parse.User.current isn't carried over as well. 

Im wondering how do I go about after signing up a user server side to then get the current user?

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.
