### ISSUE TITLE
Where and how File are saved ?

### ISSUE THREAD

**Issue by chlebta** [ParsePlatform/parse-server#3492]
Hello, I need to know where and how file are saved into parse ?
Also when exporting data from mongoDB will be possible to export the file without broken it ?

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.
