### ISSUE TITLE
What is "_objCount"?

### ISSUE THREAD

**Issue by farhansyed9** [ParsePlatform/parse-server#3494]
I have a quick question of what is "_objCount" when I log something like this: 

ParseObject { className: 'testClass', _objCount: 12, id: 'euALHDKUWd' }

Whenever I log this object for ex. the "_objCount" would be incremented up by +1. so If i refresh the browser which is firing a Get method for the route "/" and i have a console.log the object, it would get bumped up to 13, and so on up by one.

**Comment by flovilmart** [comment]
https://github.com/ParsePlatform/Parse-SDK-JS/blob/73ccdd3ce5031db81eaed1ffd8523c08efb74b5c/src/ParseObject.js#L63

**Comment by flovilmart** [comment]
That's an internally use value, you should not worry about it

**Comment by farhansyed9** [comment]
@flovilmart thanks for the response. I also had a quick question regarding parse-express-cookie-session module. 

I understand it's outdated at this point with Parse Server. Is something like this an appropriate replacement? http://code.runnable.com/U0tEnHwraXYyp-JG/simple-usage-of-express-session-and-cookie-parser-with-express-for-node-js
