### ISSUE TITLE
Cloud code debugging

### ISSUE THREAD

**Issue by gugmaster** [ParsePlatform/parse-server#3496]
Is it possible to debug cloud code (on a local parse instance)? 
If not I would love to have that. I would love to work on this feature with some guidance from experts.
I think this feature would be interesting for many other developers.

**Comment by flovilmart** [comment]
Just start your node process with --debug and attach a node debugger.

**Comment by gugmaster** [comment]
Thanks for the hint 😀 Is this mentioned somewhere in the docs? If not I can add some documentation on this (maybe on parse-server-example).

**Comment by NatanRolnik** [comment]
@gugmaster Take a look here: https://nodejs.org/api/debugger.html

**Comment by gugmaster** [comment]
@NatanRolnik To me it was not clear how to debug cloud code (I'm not experienced in JS and node JS). But maybe I'm the only one here 😉
