### ISSUE TITLE
Parse Server with Google App Engine

### ISSUE THREAD

**Issue by otymartin** [ParsePlatform/parse-server#35]
I'm thinking of adopting Google App Engine for the backend.

Im therefore wondering if I could use the Parse server code so I don't have to rewrite my app.

**Comment by Tibabal** [comment]
Hi @otymartin, seems this link could help you : https://medium.com/@justinbeckwith/deploying-parse-server-to-google-app-engine-6bc0b7451d50#.1khrfaatd

**Comment by davidaik** [comment]
@Tibabal good tutorial but the reliance on MongoLab discourages me.

**Comment by skinp** [comment]
@davidaik Parse server is not bound to MongoLab. You can use any mongodb provider or roll your want.

**Comment by davidaik** [comment]
@skinp ah yes, I guess you're right.

**Comment by meilers** [comment]
@davidaik what about the reliance discourages you?

**Comment by davidaik** [comment]
@meilers My app relied on Parse for the backend and see what happened. I think that it's better to self-host the database.

**Comment by gfosco** [comment]
Added to the wiki. https://github.com/ParsePlatform/parse-server/wiki#community-links
