### ISSUE TITLE
db data are lost after mongodb-runner is restarted

### ISSUE THREAD

**Issue by xhiza** [ParsePlatform/parse-server#3502]
Hi all,

I'm a new guy using Parse Server, one thing I noticed is that when I shutdown mongodb and I start up the other day, all my tables are gone except User table.
Can someone explain why this is happening.
FYI I'm using parse in my own server, not on mlab and other stuff. 

Thank you

**Comment by flovilmart** [comment]
Mongodb runner is not supposed to be used in production just for testing things out. We should probably have been more clear on that.
