### ISSUE TITLE
Suggestion : Login Hook to detect brute force attack ? 

### ISSUE THREAD

**Issue by simonaberry** [ParsePlatform/parse-server#3505]
Would it be possible to provide  a hook into the login process - particularly if the login failed due to a bad password - so we could implement  some sort of intelligence to block further attempts if we think that someone is trying a brute force attack ?

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

**Comment by simonaberry** [comment]
@hramos - this isn't an issue - just a _feature suggestion_... not sure where to post it as stackoverflow is more for help..?

**Comment by NatanRolnik** [comment]
@simonaberry checkout this repo: https://github.com/parse-server-modules/parse-evolution

Copy the template, try to describe as much as possible your suggestion, and open a PR :)
