### ISSUE TITLE
Documentation about WeChat login

### ISSUE THREAD

**Issue by jiawenzhang** [ParsePlatform/parse-server#3507]
Hi,

Anyone knows where I can find documentation about integrating WeChat login in Parse Server?

Thanks

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.
