### ISSUE TITLE
Bump MongoDB Node driver version to 2.2.23

### ISSUE THREAD

**Issue by chrisckchang** [ParsePlatform/parse-server#3508]
Several bug fixes, will prevent Parse Server from trying to authenticate against replica set arbiter nodes: https://github.com/mongodb/node-mongodb-native/blob/2.2/HISTORY.md#2223-2017-02-13

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.
