### ISSUE TITLE
Parse Cloud always responds "unauthorized"

### ISSUE THREAD

**Issue by leo-one** [ParsePlatform/parse-server#351]
I am receiving {"code":141,"error":"Error: undefined unauthorized"} for any Parse Cloud function, even for the simple "hello" function below ( I receive {"error":"unauthorized"}):

My parser-server is hosted in Heroku and using MongoLab.
My cloud/main.js file:

```
// from https://github.com/ParsePlatform/parse-server/issues/13
var port = process.env.PORT || 1337;
Parse.serverURL = 'https://localhost:' + port + '/parse';

Parse.Cloud.define('hello', function(req, res) {
  res.success('Hi');
});

// Other methods like beforeSave and afterSave ...
```

**Comment by drew-gross** [comment]
Can you run your server with `VERBOSE=1 npm start` and paste whatever the server outputs when you make the request?

**Comment by leo-one** [comment]
I suppose that npm start, in this case, is equivalent to node index.js, with no additional script.
I done it, but there was any log information:

![screen shot 2016-02-10 at 11 13 01 pm](https://cloud.githubusercontent.com/assets/2694753/12967318/df1315bc-d04c-11e5-98b5-dae96b0e1f0b.png)

**Comment by drew-gross** [comment]
Visiting a path in the browser won't work for two reasons 1) POST is the required HTTP methods for cloud functions and 2) The app ID is required to be submitted with the request. Trying with one of our SDKs should work.

**Comment by leo-one** [comment]
I accessed the '/hello' cloud function from Swift SDK and it worked. I did not know about these details.
But it was just a bad oversimplification. I related the real problem in a new issue:
https://github.com/ParsePlatform/parse-server/issues/356
