### ISSUE TITLE
Unable to shard the _User collection because of unique indexes on username and email

### ISSUE THREAD

**Issue by AndrewLane** [ParsePlatform/parse-server#3518]
### Issue Description

We are trying to shard the _User collection in Mongo and running into issues because of unique indexes.

### Steps to reproduce

* Try to shard the _User collection for any Mongo cluster running Parse Server

#### Expected Results

This should hopefully be possible for consumers that have very large data sets and a very large number of users.

#### Actual Outcome

The existence of two unique indexes (one on email and one on username) makes sharding impossible right now.

I hesitate calling this a bug because it's pretty much expected behavior, I think.  However, in our usage of Parse Server, we don't use the email field.  So uniqueness there doesn't matter to us.  Would you accept a PR where we add a configuration that determines whether or not we create a unique index on email?  I'm not sure if doing that would even allow us to shard since the username field would still require a unique index.

**Comment by flovilmart** [comment]
Yes and also, you want to index your database on your shard key with a high entropy. ACL's should be indexed too, otherwise lookups would take forever, scanning your whole database. Not sure if sharding your _User table would yield a significant performance gain (as you'll look ACL indexes).

**Comment by AndrewLane** [comment]
After doing a bit more research, I am finding that username has a unique index on it and that alone (even if the unique index on email were removed) is enough to prevent sharding, since we wouldn't be sharding on the username field.  I think I'll just close this issue as we have not seen a pressing need for sharding the _User collection, yet.  If that need arises, perhaps I will re-open.

**Comment by flovilmart** [comment]
@tbrock may have some tips to ensure high performance of the collections

**Comment by haroot** [comment]
any updates on sharding _User and fs.files (minimal) fs.chunks (important GBs of Data) aka GridFS? 

I was able to do "_id": "hashed" on _User but got the uniqe field on email and username warning
and fs.chunks I was able to do "files_id": "hashed" and import worked and it split 50/50 approx but I couldn't add a new file lol due to the index

**Comment by flovilmart** [comment]
> _Users

Unfortunately we’ll not lift the indexes as they guarantee proper performance and security features

> GridFs

You should not store Gb’s of data files in mongo, probably you should consider a solution based on S3 or proper file storage.
