### ISSUE TITLE
why Information in the database it Delete itself

### ISSUE THREAD

**Issue by yuttakarn** [ParsePlatform/parse-server#3519]
Yesterday has 100 user
today   16 user  why 

sorry i'm not good english

**Comment by yuttakarn** [comment]
Installation
Session
User
Visitors


It is reset By that, I didn't do.

**Comment by flovilmart** [comment]
parse-server itself doesn't reset the informations in your database, where are you running your database?

**Comment by yuttakarn** [comment]
please add skype yuttakarn.insorn@hotmail.com or +66 98 874 7607

**Comment by flovilmart** [comment]
We don't provide usually dedicated support for those kind of issues. It is most likely you improperly run your database or you didn't provide a proper storage.

**Comment by yuttakarn** [comment]
It is reset every 1st day
