### ISSUE TITLE
How to go about logging in user with current user server side in node?

### ISSUE THREAD

**Issue by farhansyed9** [ParsePlatform/parse-server#3520]

**Comment by dstarke** [comment]
I think the current user functionality of the Parse JS SDK is not safe to enable on the server side and can cause unpredictable problems. Instead, you should either use a session token or the master key in your Parse API calls from the server. You can get the session token for a request by calling `getSessionToken()` on the user in `request.user`, and pass it to your API calls in the options hash for that call.

For example:
`query.find({sessionToken: request.user.getSessionToken()});`

**Comment by flovilmart** [comment]
Great answer @dstarke , @farhansyed9 also, in the future, you can expect calling Parse.User.current() would crash the server.

**Comment by farhansyed9** [comment]
Where do I get request.user from? @dstarke

**Comment by farhansyed9** [comment]
The way I am currently doing is to after sign up, log them in, get the session token and put it into a cookie, then do the query.find for the session class to get the User.
