### ISSUE TITLE
Push Notification Setup on Parse Server/iOS App

### ISSUE THREAD

**Issue by kaifucious** [ParsePlatform/parse-server#3521]
### Issue Description

Parse Push notifications send successfully on the mobile client app, but are never delivered to the destination client. Im certain there is step im just missing here, as it worked on Parse.com, but after migrating and setting up with NodeChef and enabling push on both ends, push notifications are not delivered. If there is a guide specifically to set up Parse Server with Client push notification support, Id happily follow it! 👍 

#### Expected Results

I expect a notification to pop up on the destination client device with a message.

#### Actual Outcome

Nothing is delivered

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.2
  - Operating System:  NodeChef
  - Hardware:  Nodechef
  - Localhost or remote server? Nodechef 

- **Database**
  - MongoDB version: 3.2.11
  - Storage engine: 
  - Hardware: 
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): AWS/mLab

### Logs/Trace

**Comment by JeremyPlease** [comment]
Are your sending the push from your iOS app? If so, Parse Server does not support client triggered push notifications. You must use your master key to send push notifications. 

You can also look at the `_PushStatus` collection in your MongoDB to see all push notifications and their statuses.

**Comment by kaifucious** [comment]
I am indeed sending from my app, and ah I see! Is there a guide on how to use the master key to send the notifications?

**Comment by JeremyPlease** [comment]
Check out  
http://parseplatform.github.io/docs/parse-server/guide/#send-push-notifications and  
http://parseplatform.github.io/docs/js/guide/#sending-pushes

Essentially it's just:

```
Parse.Push.send({
  where: installationQuery,
  data: {
    alert: "Testing testing 1... 2... 3..."
  }
}, {
  useMasterKey: true
}).then(function() {
 // success!
}, function(error) {
  // error!
});
```

**Comment by kaifucious** [comment]
Excellent, thanks Jeremy! Closing issue now.
