### ISSUE TITLE
Parse server does not include port number in file urls

### ISSUE THREAD

**Issue by AWDGroup** [ParsePlatform/parse-server#3524]
### Issue Description

Parse server does not include port number in file urls

### Steps to reproduce

run a server on a port other than 80, lets say 8080
add a column with File type
upload a file and see the file url generated by parse, it does not have the port number

#### Expected Results

It should add the port number to the url
Ex. http://someurl.com:8080/parse/file/.......

#### Actual Outcome

right not the url looks like this"
http://someurl.com/parse/file/.......

**Comment by flovilmart** [comment]
You should set the 'publicServerUrl' option to the proper value, include the port if you need

**Comment by AWDGroup** [comment]
Thanks @flovilmart I'll give it a try.
Is this documented anywhere?
