### ISSUE TITLE
Postgres Adapter Files Not Building in 2.3.4

### ISSUE THREAD

**Issue by richard4339** [ParsePlatform/parse-server#3535]
The 2.3.4 will not launch at all: the release doesn't appear to be building the files or folders in the directory the Postgres adapter's SQL folder(s). In https://github.com/ParsePlatform/parse-server/blob/master/src/Adapters/Storage/Postgres/sql/index.js you get to this code:

```
module.exports = {
  array: {
    add: sql('array/add.sql'),
    addUnique: sql('array/add-unique.sql'),
    contains: sql('array/contains.sql'),
    containsAll: sql('array/contains-all.sql'),
    remove: sql('array/remove.sql')
  },
  misc: {
    jsonObjectSetKeys: sql('misc/json-object-set-keys.sql')
  }
};
```
and it errors out. It didn't build anything in the array folder, so it can't find the files.

Actual error:
> /usr/lib/node_modules/parse-server/lib/Adapters/Storage/Postgres/sql/index.js:28
>     throw qf.error;
>     ^
> QueryFileError: Error: ENOENT: no such file or directory, open '/usr/lib/node_modules/parse-server/lib/Adapters/Storage/Postgres/sql/array/add.sql'
>     at QueryFileError.Error (native)
>     at new QueryFileError (/usr/lib/node_modules/parse-server/node_modules/pg-promise/lib/errors/queryFile.js:41:22)
>     at QueryFile.prepare (/usr/lib/node_modules/parse-server/node_modules/pg-promise/lib/queryFile.js:186:21)
>     at new QueryFile (/usr/lib/node_modules/parse-server/node_modules/pg-promise/lib/queryFile.js:256:10)
>     at sql (/usr/lib/node_modules/parse-server/lib/Adapters/Storage/Postgres/sql/index.js:25:12)
>     at Object.<anonymous> (/usr/lib/node_modules/parse-server/lib/Adapters/Storage/Postgres/sql/index.js:8:10)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)

Contents of said sql folder:
> $ ls /usr/lib/node_modules/parse-server/lib/Adapters/Storage/Postgres/sql
> index.js

I figure I should point out that I'm not attempting to use the Postgres adapter. As such, I'm not entirely sure why this module is even being loaded. I'll also point out that simply emptying out that file does appear to resolve the problem for me.

**Comment by flovilmart** [comment]
2.3.5 is on the way, the issue was caused by babel not copying the sql files to the lib folder.

**Comment by richard4339** [comment]
Awesome! Glad it was able to be caught so quickly.

**Comment by flovilmart** [comment]
I was currently deploying to my dev environment and also @NatanRolnik pinged me for the same reason. Sorry for the inconvenience :/
