### ISSUE TITLE
push adapter cant be configured via string config

### ISSUE THREAD

**Issue by jeacott1** [ParsePlatform/parse-server#3544]
simply attempting to set a push adapter: via string config doesnt work.
the adapter is passed the complete push config including the adapter string definition which it rejects as unrecognised. 
eg: expect this to work, but it doesn't.
```
"push": {
    "adapter":"my-different-push-adapter",
  "android": {
    "senderId": "xxx",
    "apiKey": "xxx"
  },
  "ios": [
,{
    "pfx": "/somepath",
    "bundleId": "commybundle",
    "production": false,
  }
  ]
  ,
  "queueOptions": {
    "batchSize": "500"
  }
  }...
```

**Comment by flovilmart** [comment]
What is the error?

**Comment by flovilmart** [comment]
@jeacott1 see: https://github.com/ParsePlatform/parse-server/pull/3545/files#diff-d6ca29dd812c657c7fec3b0e2b3c35d2R122 

It's working as expected, added a test just to make sure.

**Comment by jeacott1** [comment]
the exception is thrown in the adapter itself:
"code 115, Push to adapter,android,ios is not supported"
ref: https://github.com/parse-server-modules/parse-server-push-adapter/blob/master/src/ParsePushAdapter.js#L24

the adapter itself is handed in as part of the options, and thus compared against ios/android/fcm and it fails the validation.

I cannot get this to work from string config without patching server.js or ignoring the input in the adapter which seems wrong.

**Comment by flovilmart** [comment]
Wrap all your options into an options object as described in the docs and test here: https://github.com/ParsePlatform/parse-server/pull/3545/files#diff-d6ca29dd812c657c7fec3b0e2b3c35d2R129

**Comment by jeacott1** [comment]
my config:
``` 
"push": {
    "adapter":"my-custom-push-adapter",
    "options": {
      "android": {...
```
sorry, I still get this:  code 115 "Push to options not supported."

**Comment by flovilmart** [comment]
That's because your push adapter is not correctly configured. Pretty tough to debug forward your custom adapter without more infos about that adapter

**Comment by jeacott1** [comment]
it should be configured differently than above?
my custom adapter could be a clone of the default one in this case.
the exception is thrown because the push adapter itself verifies its own configuration, and 'options' isn't valid. 
parse-server doesn't seem to pass the content of 'options', but rather passes options itself. your test doesn't check that invalid options aren't passed.

ref: https://github.com/parse-server-modules/parse-server-push-adapter/blob/master/src/ParsePushAdapter.js

**Comment by flovilmart** [comment]
And what's the problem with that? Design you adapter to work with parse-server not the other way around. We have at least 4 push adapters that initialize correctly and work correctly. All are external modules. I'm not sure why you can't make one that work given the amount of examples available.

**Comment by jeacott1** [comment]
the problem is that your own official adapter cannot be configured via string config! what kind of example is that?

**Comment by flovilmart** [comment]
Not sure how I can help then

**Comment by jeacott1** [comment]
sorry, I don't follow. 
are you saying that the official adapter is doing the wrong thing? and that an adapter can actually be handed anything at all as options, but it should simply verify the things it is interested in exist, and if anything else is there, it should be ignored?
if that's the case I'd encourage you to modify the official adapter code to do just that.

**Comment by flovilmart** [comment]
I still don't follow you, why do you want me to change things that already work, and for 4 different adapters? 
The push adapters are a bit different from other adapters, and in particular the default one for historic and backwards compatibility reasons. 

This discussion is going nowhere. Open PR's if you believe code can be improved. 

After all that I still have no idea of why that issue was open in the first place. Please consider a more clear explanation with a detail example and filling correctly the issue report

**Comment by jeacott1** [comment]
the official push adapter cant be configured via string config. I thought that was pretty clear.
i guess the 4 other adapters dont validate like the official one does?
the official adapter should be the benchmark no? it cannot be configured as advertised, so either it should change, or the calling code should.  

I agree this is going nowhere. I give up.

**Comment by flovilmart** [comment]
Provide code please, again... for the official adapter, just use the push option, and Parse-server will load the default adapter as stated in the docs, not sure in which context you want to use. Again, the lack of context / code is problematic in your report.

**Comment by jeacott1** [comment]
if I use the official adapter as a template for how things should be done. 
and attempt to load my new copy as an external string configured adapter - it cannot work.  
that sums it up.
 until now it wasn't clear to me whether the official view was that the calling code, or the adapter was at fault. its now clear you believe the adapter impl is at fault. I'd have argued the other way but so be it.

**Comment by flovilmart** [comment]
It's amazing how you always have arguments, and excuses but never provide code examples and whatever is asked.

**Comment by jeacott1** [comment]
I provided a PR, but it broke some tests.
I provided configuration that fails right at the outset. I'm sorry if I wasn't clear enough. I have tried to clarify.
I started this to qualify whether the adapter, or the server code should be fixed. 
in your view its all good already. 

its amazing how rude you can be when I'm just trying to understand proper usage given the reference 'official' plugin. 

I've given up with this. please close this issue. 
I've simply removed my validation step in my adapter and am moving on.

**Comment by flovilmart** [comment]
The issue has been closed for a while as unable to reproduce what you describe with tests.
