### ISSUE TITLE
User class CLP and ACL

### ISSUE THREAD

**Issue by hatpick** [ParsePlatform/parse-server#3550]
Hello,

I have CLP enabled for _User class in a way that only allows Create to public, and obviously, each user has a full access to itself, now when one of these users tries to update a field under itself, it gives: 'Permission denied for action update on class _User.'

From my understanding, ACLs override CLPs, why is that error happening?

Parse-server: 2.3.1

**Comment by flovilmart** [comment]
So, actually this is the opposite:

http://parseplatform.github.io/docs/ios/guide/#clp-and-acl-interaction

**Comment by hatpick** [comment]
Thanks for the link, I followed the original blog post for this.
So to recap, if I don't want public to list my users, (assuming they get the app id and url), I turn off find and get for public, but have create, update and add field checked in CLP?

**Comment by sideshowbandana** [comment]
@hatpick did you end up finding a solution for this? I'm currently trying to lock down the permission levels on a parse server. I'd prefer to only have `public create` enabled, however when creating an account with the ios client library it fails for the same reason you listed above `Permission denied for action update on class _User`
