### ISSUE TITLE
Update installation badge via Rest API does not work

### ISSUE THREAD

**Issue by flavordaaave** [ParsePlatform/parse-server#3555]
### Issue Description

I'm using the Parse REST API to update my installations. All of the properties are updated as expected, except the `badge` property of an installation.

### Steps to reproduce

1) Ensure you have an installation with a badge property set to e.g. 2
2) Send a POST request to http://<yourParseServerBaseUrl>/installations with header `'Content-Type': 'application/json'` and a body
```
{
  installationId: <ID OF THE INSTALLATION TO UPDATE>,
  deviceType: 'ios',
  badge: 10
}
```
3) Server response is:
```
{
  data: {
    updatedAt: '2017-02-22T18:31:03.175Z'
  },
  status: 200
}
```

#### Expected Results

Looking into my MongoDB I expect the `badge` property of the installation to be 10

#### Actual Outcome

The `badge` property of the installation remains unchanged (in this example: 2)

### Environment Setup

- **Server**
  - parse-server version : 2.3.5
  - Operating System:  MAC OS (localhost) Amazon Linux (AWS)
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost and AWS

- **Database**
  - MongoDB version: 3.2.3
  - Storage engine:  wiredtiger
  - Hardware: AWS EC2
  - Localhost or remote server?: localhost & AWS

### Logs/Trace
```
verbose: REQUEST for [POST] /parse/installations: {
  "installationId": "XXX",
  "deviceType": "ios",
  "badge": 10,
  "country": null,
  "city": null
} method=POST, url=/parse/installations, x-parse-application-id=XXX, content-type=application/json, host=localhost:1337, content-length=113, connection=close, installationId=XXX, deviceType=ios, badge=10, country=null, city=null
verbose: RESPONSE from [POST] /parse/installations: {
  "response": {
    "updatedAt": "2017-02-22T18:49:28.889Z"
  }
} updatedAt=2017-02-22T18:49:28.889Z
```

**Comment by flavordaaave** [comment]
Sorry, my fault. I was messing up the ID when updating the installation...

**Comment by flovilmart** [comment]
Haha, glad you found it :)
