### ISSUE TITLE
cloud code support for multiple apps on parse serve?

### ISSUE THREAD

**Issue by majd-kho** [ParsePlatform/parse-server#3558]
I've been looking through all the docs available on https://parseplatform.github.io/ and through past issues, but i am unable to find anything new on whether cloud code is being supported now for multiple apps.

I remember seeing an official statement that cloud code is not supported due to concurrent requests with the js sdk, but i am unable to find that page again. Any one know where I can find that?

Also I could not locate the full API for cloud code ( not sure if there is one).

Thank you

**Comment by natanrolnik** [comment]
Closing as duplicate #15 and #3354
