### ISSUE TITLE
Parse query `near` cannot work with dot

### ISSUE THREAD

**Issue by pewh** [ParsePlatform/parse-server#3561]
### Issue Description

Sort query by distance using dot cause an error in Cloud Code.

### Steps to reproduce

```
const promoQuery = new Parse.Query('Promo')
  .include('vendor')
  .near('vendor.geo', new Parse.GeoPoint(currentGeo)) // this cause an error
```

Where `Promo` object has `vendor`, and `vendor` is a pointer from `Vendor`, which has `geo` property.

#### Expected Results

Sort `Promo` by vendor's geo.

#### Actual Outcome

```
error: undefined code=141, message=undefined
error: operator does not exist: character ->> unknown  
```

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.5
  - Operating System:    ArchLinux
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Localhost

- **Database**
  - PostgresQL version: 9.6
  - Localhost or remote server? Localhost

If `near` doesn't support dot operator, what is the correct way to sort query by geo which inside pointer?

**Comment by emkman** [comment]
This has nothing to do with geopoints. ParseQuery doesn't support querying on subkeys of an include like that. Check out https://parseplatform.github.io/Parse-SDK-JS/api/classes/Parse.Query.html#methods_matchesKeyInQuery for an alternative.

**Comment by pewh** [comment]
Can you give an example (code snippet) using matchesKeyInQuery in my case? I'm trouble on understanding how to use matchesKeyInQuery because my english is not native. Giving example should help me to understanding the usage. Thanks :)

**Comment by emkman** [comment]
I think you actually want `matchesQuery` in this case because it is a pointer. I don't know your schema but my guess is this:
```
const vendorQuery = new Parse.Query('Vendor');
vendorQuery.near('geo', currentGeo); //This finds vendors near the geopoint

const promoQuery = new Parse.Query('Promo');
promoQuery.include('vendor'); //This will include the vendor data but is optional if you only need Promo values
promoQuery.matchesQuery('vendor', vendorQuery); //this finds all Promos where vendor pointer matches results from vendorQuery

**Comment by pewh** [comment]
Hello @emkman, thanks for answer my question. Unfortunately, my use-case has been changed, and I'm curious how to combine `matchesQuery` with something like `DISTINCT` or `UNIQ` in Parse Query. I have > 200 data, so it's expensive to execute 200+ `Parse.Query.find()`. I have post my problem on http://stackoverflow.com/questions/42755795/parse-cloud-code-efficient-way-to-find-a-nearest-child-for-each-parent

Any help is appreciate. Thanks! :beers:
