### ISSUE TITLE
custom OAuth problem AccountKit

### ISSUE THREAD

**Issue by antgar** [ParsePlatform/parse-server#3570]
### Issue Description

When trying to implement custom OAuth module I have this error :"message: 'This authentication method is unsupported.' } code=252, message=This authentication method is unsupported."

### Steps to reproduce
Installing "https://github.com/Angopapo/Parse-Server-phone-number-auth" and initialize custom Auth in Parse-server Constructor like this 
auth: {
      accountkit: {
         module: 'Parse-Server-phone-number-auth',
         appSecret: '7ea98f46b1186c436bc114e09c46dae6'
     },
        facebook: {
            appIds: "522186534630612"
        }
    },

#### Expected Results

Login working

#### Actual Outcome

Error code 252.

### Environment Setup

- **Server**
  - parse-server version 2.3.5
  - Localhost or remote server? Heroku
  - Localhost or remote server? mLab

### Logs/Trace

"authData": {
    "accountKit": {
       "id": "blabla",
      "access_token": "blabla"
     }
  }

Thank you for your help

**Comment by flovilmart** [comment]
Probaly a typo in your constructor (i see accountkit vs accountKit).

You should probably open that issue on the module's repository / contact the maintainer of that module instead of here.
