### ISSUE TITLE
Facebook Login issue when going from 2.2.23 to 2.2.24 (cant even run latest)

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/parse-server#3577]
### Issue Description

Slowly bumping our production server from 2.2.19 to the latest but while going though each
revision and testing our iOS app, Facebook Login stops to work when we go from 2.2.23 to 2.2.24 for some reason and trying anything above that and even in 2.3 branch with the auth parameter doesn't work anymore.

Enabling VERBOSE 1 doesn't show anything in our logs and the only thing we see in iOS console is the following:

Uh oh. The user cancelled the Facebook login.

Error Domain=Parse Code=0 "unauthorized" UserInfo={error=unauthorized, NSLocalizedDescription=unauthorized, temporary=0}

I cant find any documentation saying we need to make any changes in our index.js  

We are using Swift 3.x
iOS AppDelegate settings

![image](https://cloud.githubusercontent.com/assets/519563/23379489/f7fb3240-fceb-11e6-917a-55484bf138ad.png)

Part of index.js

![image](https://cloud.githubusercontent.com/assets/519563/23379563/3febd69a-fcec-11e6-99b0-3053b91177f0.png)

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.23 CANT go further
  - Operating System:    Heroku
  - Hardware:             standard
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

- **Database**
  - MongoDB version: 3.2
  - Storage engine:  tiger
  - Hardware:        heroku
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Mlab

### Logs/Trace

No data seen in logs.

**Comment by steven-supersolid** [comment]
I don't see any client key in your ParseServer constructor. I'm unfamiliar with the iOS SDK but assume it uses that key?

You can test this by seeing if any iOS calls succeed.

Otherwise you can try using different commits between 2.2.23 and 2.2.24 to narrow down the problem.
https://github.com/ParsePlatform/parse-server/compare/2.2.23...2.2.24

**Comment by gateway** [comment]
Nice catch, saved me big time..
