### ISSUE TITLE
Will the dashboard work with other NoSQL databases as well?

### ISSUE THREAD

**Issue by miav** [ParsePlatform/parse-server#359]
Just my two cents here, probably obvious. @gfosco in #3 says he is working on the dashboard. But it probably makes more sense to first modularize parse-server as per #20 to add support for other NoSQL databases. Right?

Same would be for indexes support in #123 , if it is every going to come. Sorry if I'm missing something.

**Comment by bohemima** [comment]
Since the dashboard would use the API (using master key, I guess), it will "automatically" work when the adapters are in place.

If anyone is currently working on the Dashboard, can we opt in to help somewhere?

**Comment by miav** [comment]
@bohemima Thank you, I had not thought of dashboard as a client. Sorry then.
