### ISSUE TITLE
Error while getting started with Postgres

### ISSUE THREAD

**Issue by yogeshwaranManoharan** [ParsePlatform/parse-server#3595]
### Issue Description

 Error While Running requet on parse-server

I started with parse-server and trying to pass postgres uri for Database URI,
eg. parse-server --appId APPLICATION_ID --masterKey MASTER_KEY --databaseURI postgres://user:password@localhost/db_name , it starts without a issue but when i try out a curl request to test it says

error: Uncaught internal server error. Error: invalid schema, expected mongodb

it accepts postgres url while starting but then it works internally with mongo db instead of postgres

### Steps to reproduce

Try a fresh clone and npm install

Set the database uri to postgres://user:password@localhost/db_name and try a curl request to create a object 
eg.
curl -X POST -H "X-Parse-Application-Id: APPLICATION_ID" -H "Content-Type: application/json" -d '{"sce":false}' http://localhost:1337/parse/classes/GameScore

#### Expected Results

{
  "objectId": "some-obj-id",
  "createdAt": "time-stamp"
}

#### Actual Outcome

error: Uncaught internal server error. Error: invalid schema, expected mongodb
at module.exports (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/url_parser.js:20:11)
    at connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:176:16)
    at /home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:101:7
    at new Promise (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/core-js/modules/es6.promise.js:193:7)
    at Function.MongoClient.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:100:12)
    at MongoStorageAdapter.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:84:44)
    at DatabaseController.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:91:23)
    at new DatabaseController (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:81:8)
    at Object.getDatabaseConnection (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/DatabaseAdapter.js:72:26)
    at new HooksController (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/HooksController.js:46:37) Error: invalid schema, expected mongodb
    at module.exports (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/url_parser.js:20:11)
    at connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:176:16)
    at /home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:101:7
    at new Promise (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/core-js/modules/es6.promise.js:193:7)
    at Function.MongoClient.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:100:12)
    at MongoStorageAdapter.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:84:44)
    at DatabaseController.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:91:23)
    at new DatabaseController (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:81:8)
    at Object.getDatabaseConnection (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/DatabaseAdapter.js:72:26)
    at new HooksController (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/HooksController.js:46:37

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.6
  - Operating System:     Ubuntu 14.04
  - Hardware:             Local System
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost

- **Database**
  - MongoDB version: Not MongoDb
  - Postgres  version - 9.6.2
  - Storage engine:  none
  - Hardware:        Local System
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): Localhost

### Logs/Trace

{"level":"error","message":"Uncaught internal server error. Error: invalid schema, expected mongodb\n    at module.exports (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/url_parser.js:20:11)\n    at connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:176:16)\n    at /home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:101:7\n    at new Promise (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/core-js/modules/es6.promise.js:193:7)\n    at Function.MongoClient.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:100:12)\n    at MongoStorageAdapter.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:84:44)\n    at DatabaseController.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:91:23)\n    at new DatabaseController (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:81:8)\n    at Object.getDatabaseConnection (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/DatabaseAdapter.js:72:26)\n    at new HooksController (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/HooksController.js:46:37) Error: invalid schema, expected mongodb\n    at module.exports (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/url_parser.js:20:11)\n    at connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:176:16)\n    at /home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:101:7\n    at new Promise (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/core-js/modules/es6.promise.js:193:7)\n    at Function.MongoClient.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:100:12)\n    at MongoStorageAdapter.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:84:44)\n    at DatabaseController.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:91:23)\n    at new DatabaseController (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:81:8)\n    at Object.getDatabaseConnection (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/DatabaseAdapter.js:72:26)\n    at new HooksController (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/HooksController.js:46:37)","timestamp":"2017-03-04T03:36:55.645Z"}
{"level":"error","message":"Uncaught internal server error. Error: invalid schema, expected mongodb\n    at module.exports (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/url_parser.js:20:11)\n    at connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:176:16)\n    at /home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:101:7\n    at new Promise (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/core-js/modules/es6.promise.js:193:7)\n    at Function.MongoClient.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:100:12)\n    at MongoStorageAdapter.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:84:44)\n    at DatabaseController.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:91:23)\n    at new DatabaseController (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:81:8)\n    at Object.getDatabaseConnection (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/DatabaseAdapter.js:72:26)\n    at new HooksController (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/HooksController.js:46:37) Error: invalid schema, expected mongodb\n    at module.exports (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/url_parser.js:20:11)\n    at connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:176:16)\n    at /home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:101:7\n    at new Promise (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/core-js/modules/es6.promise.js:193:7)\n    at Function.MongoClient.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:100:12)\n    at MongoStorageAdapter.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:84:44)\n    at DatabaseController.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:91:23)\n    at new DatabaseController (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:81:8)\n    at Object.getDatabaseConnection (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/DatabaseAdapter.js:72:26)\n    at new HooksController (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/HooksController.js:46:37)","timestamp":"2017-03-04T03:40:25.598Z"}
{"level":"error","message":"Uncaught internal server error. Error: invalid schema, expected mongodb\n    at module.exports (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/url_parser.js:20:11)\n    at connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:176:16)\n    at /home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:101:7\n    at new Promise (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/core-js/modules/es6.promise.js:193:7)\n    at Function.MongoClient.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:100:12)\n    at MongoStorageAdapter.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:84:44)\n    at DatabaseController.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:91:23)\n    at new DatabaseController (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:81:8)\n    at Object.getDatabaseConnection (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/DatabaseAdapter.js:72:26)\n    at new HooksController (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/HooksController.js:46:37) Error: invalid schema, expected mongodb\n    at module.exports (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/url_parser.js:20:11)\n    at connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:176:16)\n    at /home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:101:7\n    at new Promise (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/core-js/modules/es6.promise.js:193:7)\n    at Function.MongoClient.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:100:12)\n    at MongoStorageAdapter.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:84:44)\n    at DatabaseController.connect (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:91:23)\n    at new DatabaseController (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/DatabaseController.js:81:8)\n    at Object.getDatabaseConnection (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/DatabaseAdapter.js:72:26)\n    at new HooksController (/home/jarvis/.nvm/versions/node/v6.0.0/lib/node_modules/parse-server/lib/Controllers/HooksController.js:46:37)","timestamp":"2017-03-04T03:43:17.253Z"}
#

**Comment by acinader** [comment]
fixed by: #2871
