### ISSUE TITLE
Facebook authentication works without specifying any appIds.

### ISSUE THREAD

**Issue by johanarnor** [ParsePlatform/parse-server#3602]
### Issue Description

I don't know if this is by design or a bug, but Facebook authentication works even though no appIds are configured.

In this function (https://github.com/ParsePlatform/parse-server/blob/master/src/Adapters/Auth/index.js#L47), the authData is first validated followed by the validation of appIds. If appIds are not present, the check will be skipped and the user logged in.

Are there any problems with leaving out the appIds when authenticating with Facebook?

### Steps to reproduce

- Remove all configuration for Facebook appIds (i.e auth, oauth PARSE_SERVER_FACEBOOK_APP_IDS)
- Login with `Parse.User.logInWith('facebook', {authData})` with some valid authData.

#### Expected Results

I don't know if this behaviour is by design or not, but it feels like the login should fail.

#### Actual Outcome

The user is authenticated without errors.

### Environment Setup

- **Server**
  - parse-server version : 2.3.6

**Comment by flovilmart** [comment]
This is by design, and most of the adapters follow that design when they don't need any additional settings for validating access tokens. 

im happy to help if you believe this causes a security issue.
Also, in production, you're encouraged to set your appIds, so only the white listed apps are allowed to login.

**Comment by johanarnor** [comment]
Ok, thanks. I don't really know if it causes a security issue. Was mainly curious if it was by design or not.

**Comment by flovilmart** [comment]
We definitely could be more aggressive with the options, only allowing the ones configured in the options.
