### ISSUE TITLE
Parse-server on heroku returning error code H13 when authenticating a user

### ISSUE THREAD

**Issue by Abel7x** [ParsePlatform/parse-server#361]
I've used the heroku button for the parse server example.All config variables are both in heroku and my php sdk to make it work. But when I try to auth a user on my page it returns an H13 code error "Connection closed without response". 

here's the log from heroku 

`at=error code=H13 desc="Connection closed without response" method=GET path="/parse/login?username=xxx&password=xxx" host=xxxxx.herokuapp.com request_id=7c1035cb-7d2f-4656-9d7f-8b7198c6fc49 fwd="173.236.126.130" dyno=web.1 connect=0ms service=4ms status=503 bytes=0`

**Notes:**
When I do a curl from terminal to auth the user it works fine.
My db is at mongolab, I migrated the data from my app to that database.

Any help would be great. Thanks.

**Comment by gfosco** [comment]
Please try this with new version of the PHP SDK 1.2.0 and ParseServer 2.0.8+ and re-open if you're still having an issue.  Thanks.

https://github.com/parseplatform/parse-php-sdk
