### ISSUE TITLE
RE-deploying Parse-server-example on Heroku

### ISSUE THREAD

**Issue by globyworks** [ParsePlatform/parse-server#362]
Hi,

I have a Heroku setup using the Heroku deploy button. This adds and deploys the parse-server-example on a dyno.
I have connected that git (the parse server example one) to heroku via settings.

By redeploying, am i updating the parse-server code from the official git as well?
If not, how would i go after that?

Thanks,
G

**Comment by gfosco** [comment]
Heroku deploy does re-`npm install`, so it will continue to get the latest released 2.0 version (currently 2.0.7) based on the package.json file.
