### ISSUE TITLE
Logged in User has to force close/clear data of app before seeing saved data to (that user's data)from dashboard

### ISSUE THREAD

**Issue by grantespo** [ParsePlatform/parse-server#3624]
Title says it all. What can I do to allow the users to see changes made to a user column from the dashboard.

**Comment by natanrolnik** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.

Also, if it's a Dashboard bug, please open it in the right repo.
