### ISSUE TITLE
Parse Server livequery on AWS (Websocket error 403)

### ISSUE THREAD

**Issue by lyonlionng** [ParsePlatform/parse-server#3635]
### Issue Description

I am using currently on a project trying to make a chat system using parse server livequery. I am using AWS's Parse Server by Bitnami AMI to create a new instance. And i did the setups exactly as i did on my localhost. However whenever i run my ionic 2 application, it will show the websocket error as shown below. 

![chrome_2017-03-13_16-23-46](https://cloud.githubusercontent.com/assets/14155133/23881296/ad151084-0894-11e7-9c82-9cf83aaa45ec.png)

WebSocket connection to 'ws://ec2-54-169-103-145.ap-southeast-1.compute.amazonaws.com/parse' failed: Error during WebSocket handshake: Unexpected response code: 403

### Steps to reproduce

1. Create a instance of Parse Server by Bitnami
2. Create a new ionic 2 application(any template)
3. run "ionic serve --lab"
4. inspect your console

#### Expected Results

There shouldnt be a websocket error and the livequery will auto reload and show on my chat system.

#### Actual Outcome

It shows the error and whenever i send a text to a user, the other party does not receive and updates until he backs out one screen and went back the same page.

### Environment Setup

- **Server**
  - parse-server version  : 2.3.1
  - Operating System:     Linux and Windows 10
  - Hardware:    dont think this would be a problem...
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): AWS

- **Database**
  - MongoDB version: 3.2.11
  - Storage engine:  MMAPv1
  - Hardware:       nil
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

**Comment by flovilmart** [comment]
Did you configure Parse-server correctly to start the liveQuery server?

**Comment by lyonlionng** [comment]
This is my current server code...

`var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var mailgun = require('mailgun-js');
var app = express();
// Specify the connection string for your mongodb database
// and the location to your Parse cloud code
var api = new ParseServer({
    databaseURI: "xxxxx",
    cloud: "./cloud/main.js",//"./node_modules/parse-server/lib/cloud-code/Parse.Cloud.js",
    appId: "xxxxx",
    masterKey: "xxxxx",
    fileKey: "xxxxx",
    serverURL: 'http://ec2-xxxxx.ap-southeast-1.compute.amazonaws.com:80/parse',

// Subscription for Livequery
    liveQuery: {
	classNames: ["CareRecipient", "Patient", "Message", "ContactList", "ChatMessage"]
    },

// Mailgun Configuration
    emailAdapter: {
    module: 'parse-server-simple-mailgun-adapter',
	options: {
	    fromAddress: "xxxxx",
	    domain: "xxxx.mailgun.org",
	    apiKey: "key-xxxx"
	}
    }
});
// Serve the Parse API on the /parse URL prefix
app.use('/parse', api);

var port = 1337;
app.listen(port, function() {
    console.log('parse-server running on port ' + port);
});

//Parse Dashboard
var ParseDashboard = require('parse-dashboard');
var dashboard = new ParseDashboard({
    apps: [
        {
            appName: "xxx",
            appId: "xxx",
            masterKey: "xxx",
            fileKey: "xxxx",
            production: true,
            serverURL: 'http://ec2-xxx.ap-southeast-1.compute.amazonaws.com:80/parse'
        }
    ]
});

var allowInsecureHTTP = true;

// Serve the Mailgun on /email URL prefix
app.get ('/email', function (req, res){
    res.status(200).send('Email has been sent!');
    var api_key = 'key-xxx';
    var domain = 'xxx.mailgun.org';

    var mailgun = require('mailgun-js')({apiKey: api_key, domain: domain});
	
    var data = {
    from: 'Witzu <postmaster@xxx.mailgun.org>',
    to: 'xxx@gmail.com',
    subject: 'Welcome toxxx!',
    text: 'Please confirm your email! New Mailgun :)'
    };

    mailgun.messages().send(data, function (error, body) {
    console.log(body);
    });
});

// Serve the Parse Dashboard on the /parsedashboard URL prefix
app.use('/', dashboard);

var portdash = 4040;
app.listen(portdash, function() {
    console.log('parse-dashboard running on port ' + portdash);
});
/*var port = 1337;
var httpServer = require('http').createServer(app);
httpServer.listen(port, function() {
    console.log('parse-server running on port ' + port + '.');
});*/
ParseServer.createLiveQueryServer(app);
`

**Comment by flovilmart** [comment]
Are you running on Elastic beanstalk or a naked instance? Are you using ELB? Do you have any server logs when running with VERBOSE=1 ?

**Comment by lyonlionng** [comment]
i used the AWS Parse Server by Bitnami AMI to create a new instance. Could this be the issue? and no im not using ELB. No server logs either...

**Comment by flovilmart** [comment]
I have no idea what that particular image does, it may as it may not.

**Comment by lyonlionng** [comment]
Okay, lets say start from the beginning, i launched the instance and the serve.js was like this:

> var express = require('express');
> var ParseServer = require('parse-server').ParseServer;
> var app = express();
> // Specify the connection string for your mongodb database
> // and the location to your Parse cloud code
> var api = new ParseServer({
>     databaseURI: "mongodb://root:B7cBoeHrFiEx@127.0.0.1:27017/bitnami_parse",
>     cloud: "./node_modules/parse-server/lib/cloud-code/Parse.Cloud.js",
>     appId: "bc88aaa466de5f86f3c33d9a241bd03af1d426b4",
>     masterKey: "b952b217c5410bef5ec80fb42ecea7327d70c64e",
>     fileKey: "2b723ca3a8c4dc353a694f31cb52f85109719da6",
>     serverURL: 'http://ec2-54-179-164-90.ap-southeast-1.compute.amazonaws.com:80/parse'
> });
> // Serve the Parse API on the /parse URL prefix
> app.use('/parse', api);
> 
> var port = 1337;
> app.listen(port, function() {
>     console.log('parse-server running on port ' + port);
> });
> 
> //Parse Dashboard
> var ParseDashboard = require('parse-dashboard');
> var dashboard = new ParseDashboard({
>     apps: [
>         {
>             appName: "My Bitnami Parse API",
>             appId: "bc88aaa466de5f86f3c33d9a241bd03af1d426b4",
>             masterKey: "b952b217c5410bef5ec80fb42ecea7327d70c64e",
>             fileKey: "2b723ca3a8c4dc353a694f31cb52f85109719da6",
>             production: true,
>             serverURL: 'http://ec2-54-179-164-90.ap-southeast-1.compute.amazonaws.com:80/parse'
>         }
>     ],
>     users: [
>         {
>             user: "user",
>             pass: "$2a$10$4YBCdLSGhXaWE2tA8Fe3LueSPYxOFGtz.TsQJzjbBZ/zyL/xdH8N6"
>         }
>     ], useEncryptedPasswords: true
> });
> 
> var allowInsecureHTTP = true;
> 
> // Serve the Parse Dashboard on the /parsedashboard URL prefix
> app.use('/', dashboard);
> 
> var portdash = 4040;
> app.listen(portdash, function() {
>     console.log('parse-dashboard running on port ' + portdash);
> });

What would be the code to enable livequery? (just want to make sure im right)

**Comment by flovilmart** [comment]
From the [docs](http://parseplatform.org/docs/parse-server/guide/#server-setup), you'd need:

``` 
// Initialize a LiveQuery server instance, app is the express app of your Parse Server
let httpServer = require('http').createServer(app);
httpServer.listen(port);
var parseLiveQueryServer = ParseServer.createLiveQueryServer(httpServer);
```

I see also something, you're using twice app with calling listen on 2 different ports. That won't work.

you should have:

```
var serverApp = express();

var api = new ParseServer({...});
serverApp('/parse', api);
var port = 1337;
/*
// !!! Important, this should be removed
// That will prevent proper init from the LQ server
app.listen(port, function() {
console.log('parse-server running on port ' + port);
});
*/

var httpServer = require('http').createServer(serverApp);
httpServer.listen(port);
var parseLiveQueryServer = ParseServer.createLiveQueryServer(httpServer);

var dashboardApp = express();
var ParseDashboard = require('parse-dashboard');
var dashboard = new ParseDashboard({...});
var allowInsecureHTTP = true;

// Serve the Parse Dashboard on the /parsedashboard URL prefix
app.use('/', dashboard);

var portdash = 4040;
app.listen(portdash, function() {
console.log('parse-dashboard running on port ' + portdash);
});
```

**Comment by lyonlionng** [comment]
i have tried your answer but it doesnt work either. If i were to start afresh and not use Bitnami's AMI, will it work? and do you have a guide somewhere to teach me the steps? im kinda new to parse...

**Comment by flovilmart** [comment]
The docs link I provided should give the most information about it. 
I would not recommend you 'start-over' as that may not solve your issue. 

I'm not sure what responds with 403 on your liveQuery client, perhaps missing keys in the JS-SDK.

**Comment by lyonlionng** [comment]
One thing to take note is that if i host it on heroku, it works 100%. Only only AWS the livequery is not working. I am so confused. I have searched many sites regarding issue and have not come to a solution

**Comment by flovilmart** [comment]
So if it works on heroku, that's not an issue with parse-server itself, or your configuration, but with the way you're deployed on AWS.

**Comment by LilMoke** [comment]
I was wondering if anyone has a solution to this issue with AWS.  flovilmart made mention that people have successfully set up live query on AWS, but unfortunately it looks like no-one has shared the details.  If anyone has successfully set this up on AWS would you be so kind as to share the secret?  LOL, but really any help with this issue would be greatly appreciated.  I am getting the same 403 error and have followed the steps in every article I could find on the issue with no luck.

**Comment by dplewis** [comment]
@LilMoke Check out this guide

https://github.com/SoBump/ParseLiveQueryHelp/blob/master/guide.md

**Comment by LilMoke** [comment]
Awesome thanks so much.  I took a quick look and I think it told me my problem.  I was using a classic old balancer and my nginx file was slightly wrong.  Thanks again, I will try it shortly.
