### ISSUE TITLE
'Settings' on dashboard not showing

### ISSUE THREAD

**Issue by BillyJohn3** [ParsePlatform/parse-server#3643]
I need the 'Settings' menu on the dashboard to organize using notifications on our IOS app but it's not showing on the side of the dashboard as expected.

How can I enable it on the dashboard?

Cheers,
Billy

**Comment by natanrolnik** [comment]
Closing as duplicate of #3361
TLDR; notifications are setup in the server initialization, and not configurable via Dashboard.
