### ISSUE TITLE
Multiple cloud functions in main.js

### ISSUE THREAD

**Issue by mginz83** [ParsePlatform/parse-server#3646]
I'm confused with having multiple functions in main.js.

If I have multiple cloud functions, I get a bad Jason response error when I run my code. I'm currently developing for Android with my parse server installed locally.

Should I put each function I need in a separate . js file and then include them in main.js???

Thanks

**Comment by natanrolnik** [comment]
You can have them in separate main.js files, but you don't need to. Check for typos in your current setup.

**Comment by mginz83** [comment]
I can have multiple main.js? Wouldn't that just overwrite the one? Or having multiple .. js files and use include in the main

**Comment by natanrolnik** [comment]
As long as they have different names, they don't overwrite each other.

**Comment by mginz83** [comment]
Yeah, that strange because I could have sworn I have the stars function in there that comes on the example, as well as a new phone or push notifications, and I got errors. I'll try a different function later. Thanks for this.

**Comment by davidju** [comment]
To include other js files in main.js, the code is `require("cloud/filename.js");` right? Because when I do this, the cloud code crashes, even if the other js file is empty.

**Comment by davidju** [comment]
Never mind, issue is resolved. To include other js files it is supposed to be `require("./filename.js");`

**Comment by Edijae** [comment]
@natanrolnik @davidju I have included a file called `Common.js` that contains cloud code in `main.js` I have then tried to call this cloud code in another file called `Controller.js` file but it's not been executed.

`Main.js`

```
let common = require('./Common');
 let controller = require('./Controller');
```

`Controller.js`
```
Parse.Cloud.define("save", async (request) => {
 // other logics here
var params = {"id":"ABCDEF"}
 const result = await Parse.Cloud.run("Update", params);
        console.log("updated summary?+++++++++++++++++++++++++++++++++++++++++++" + result)
})
```
`Common.js`

```
Parse.Cloud.define("Update", async (request) => {
 console.log("Update function called------------")
return true
});
```
`console.log("Update function called------------") is not being executed at all`

**Comment by Skyb0rg** [comment]
> ave included a file called `Common.js` that contains cloud code in `main.js` I have then tried to call this cloud code in another file called `Controller.js` file but it's not been executed.

your Main.js should only include the other files like:

     require("./Controller.js");
     require("./Common.js");
