### ISSUE TITLE
Can't get new version from NPM

### ISSUE THREAD

**Issue by ascholz81** [ParsePlatform/parse-server#3647]
Newest release is not available on NPM.  Please fix.  (no need for bug report form.)

https://www.npmjs.com/package/parse-server

**Comment by flovilmart** [comment]
Thanks for the notification, the CI script failed to upload, just restarted at the instant.

**Comment by flovilmart** [comment]
It should be available now! Thanks

**Comment by ascholz81** [comment]
got it; thanks!
