### ISSUE TITLE
Pin in background

### ISSUE THREAD

**Issue by mginz83** [ParsePlatform/parse-server#3666]
What's the best way to work with pin in background? I need to have faster load speeds so I need to store data locally. But do I call into the server, and if e is null, do I then pin it into the background? When if I am saving information into parse, do I save it into pin during g the save I background?

What's the best way?

I have ListView, gridviews, etc, I just need faster load speeds.

**Comment by flovilmart** [comment]
Unrelated to parse-server please open on the particular repository.
