### ISSUE TITLE
Apple Push notifications not sending.  

### ISSUE THREAD

**Issue by taylorknopp** [ParsePlatform/parse-server#3667]
I am running the example server but I have updated it to Parse-server version 2.3.7 The apple developer I am working with has push notifications working with FireBAse, so we know that our issues are not client side. No matter what I do we can not get push notifications via APNS to send.  I have checked that all the installation data is present including device token and such.For testing, we have tried sending push from a client app using the master key, from a cloud code function I wrote which is working for sending Android push, and from the dashboard. None of those work.  Here is the relevant portion of my index.js
 ```push: {
    android: {
      senderId: 'XXXXXXXX', // The Sender ID of GCM
      apiKey: ' XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' // The Server API Key of GCM
    }
   
    },
ios: {
        pfx: '/Prae-server-example/ParseTutorial cert.p12',
		passphrase: 'PlaceHolderPassphrase', // optional password to your p12/PFX
        bundleId: 'PlaceHolderId',
        production: false
	
      },  
		  


  
});```

**Comment by flovilmart** [comment]
Without more informations, like running the server with VERBOSE=1 and providing the relevant logs we can't help with the issue.

Did you follow step by step the push notification configuration guide?

Closing, please reopen when the issue template is filled correctly.

**Comment by taylorknopp** [comment]
I'm not 100% sure how to set VERBOSE=1?
