### ISSUE TITLE
includeKey with array

### ISSUE THREAD

**Issue by loftyet** [ParsePlatform/parse-server#368]
Here is my use case. My model has an array property 'questions' which is the collection of custom PFObject.
In my PFQuery, I used includeKey in this way: 
[query includeKey:@"questions"];

The same code, while working with the host on Parse.com, I am able to get each question's value in questions.
while deployed to local hosted Parse-server with MongoLab mongo DB, I am not able to get each question's values. My iPhone app crashed and suggested to do "fetchIfNeeded" etc.

**Comment by nlutsenko** [comment]
Just tested this with a customized version of one of our tests, it cleanly passes and has no problems.
I wonder if there is anything else in the query that prevents from pointers being expanded on return.
Any chance you can provide the full query construction that you have?

Test used:
```js
it("include on array", function(done) {
    var child = new TestObject();
    var child2 = new TestObject();
    var parent = new Container();
    child.set("foo", "bar");
    parent.set("child", [child, child2]);
    Parse.Object.saveAll([child, child2, parent], function() {
      var query = new Parse.Query(Container);
      query.include(["child"]);
      query.find({
        success: function(results) {
          equal(results.length, 1);
          var parentAgain = results[0];
          var goodURL = Parse.serverURL;
          Parse.serverURL = "YAAAAAAAAARRRRRGGGGGGGGG";
          console.log(parentAgain.get('child').length);
          var childAgain = parentAgain.get("child")[0];
          console.log(childAgain);
          console.log(parentAgain.get("child")[1]);
          ok(childAgain);
          equal(childAgain.get("foo"), "bar");
          Parse.serverURL = goodURL;
          done();
        }
      });
    });
  });
```

**Comment by loftyet** [comment]
I think this issue was caused by the difference between the schemas of two mongodb collections. In the other word, my Parse.com app has one property that my mongolab db doesn't have. 
Thanks for your attention.
