### ISSUE TITLE
Very slow save operation when using one to many Arrays

### ISSUE THREAD

**Issue by ranhsd** [ParsePlatform/parse-server#3682]
Hi, I'm experience some very strange issue with my parse server installation lately. 
In my **iOS** app i have a user and each user contains list of other users (those users are friends of the logged in user). In order to do that i created a 0...n from User to User this pointer is stored in a fields which called **friends**

When a user logged in to my app i change his presence from offline to online and i noticed that if the user have about 10-20 friends this save operation is **extremely slow** and the CPU on my device is working very very hard (100% and more) during this save operation.  By slow i mean that it takes between 1-2 minutes and sometimes its just get stuck!

I also noticed that if one of the user friends has also some friends (about 10-20) the operation is even slower. 

I wanted to know if someone has experienced such issues before. or maybe someone can provide some hints about his strange issue.

Thanks in advanced.

**Comment by flovilmart** [comment]
Did you implement it with a List or with a relation?

**Comment by ranhsd** [comment]
With a list. Means that the friends column holds an Array 
something like: 

[[{"__type":"Pointer","className":"Friend","objectId":"syozOQRtM5"},
[{"__type":"Pointer","className":"Friend","objectId":"f6s3pjP9ol"},
....
]

**Comment by flovilmart** [comment]
are the operations reaching parse-server or is it slow in the SDK itself?

**Comment by ranhsd** [comment]
It looks like it is related to the SDK itself because i created some sample app in JS and use JS SDK and it works very well there. What do you think? this is a bug in the iOS SDK ?

**Comment by flovilmart** [comment]
Without more infos it's hard to determine.

**Comment by ranhsd** [comment]
Ok. I think i see what the issue is. When i disable the local data store everything work normal. Do you have a clue why? I understand that the object is being pinned to the local data store but why it takes so much time to pin the objects ?

**Comment by flovilmart** [comment]
I'm not sure, feel free to open a PR if you find a proper resolution.

**Comment by flovilmart** [comment]
closing as issue has been isolated into the iOS SDK
