### ISSUE TITLE
Error: No compatible version found: uws@^0.13.0

### ISSUE THREAD

**Issue by camdagr8** [ParsePlatform/parse-server#3685]
When I run: 
```sh 
npm install
```

I get the following errors: 
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: uws@^0.13.0 (node_modules/parse-server/node_modules/uws):
npm WARN notarget SKIPPING OPTIONAL DEPENDENCY: No compatible version found: uws@^0.13.0
npm WARN notarget SKIPPING OPTIONAL DEPENDENCY: Valid install targets:
npm WARN notarget SKIPPING OPTIONAL DEPENDENCY: 0.14.1
npm WARN notarget SKIPPING OPTIONAL DEPENDENCY: 
```

### Environment Setup

- **Server**
  - parse-server version: 2.3.2
  - Operating System: MacOS El Capitan
  - Hardware: MacBook Pro (Retina, 15-inch, Mid 2014)
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost and remote (IBM Bluemix)

```
 "engines": {
    "node": "7.5.0",
    "npm": ">=2.0.0"
  }
```

**Comment by flovilmart** [comment]
This is gonna be solved with next release

**Comment by camdagr8** [comment]
Any ETA on when the next release is?

**Comment by flovilmart** [comment]
probably this week

**Comment by paulovitin** [comment]
👍
