### ISSUE TITLE
useMasterKey in cloudCode not working as expected

### ISSUE THREAD

**Issue by REggar** [ParsePlatform/parse-server#37]
We had some Cloud Code like this in Parse:
```Parse.Cloud.useMasterKey();

Parse.Cloud.define('deleteUser', function (request, response) {`
    var User = Parse.Object.extend('_User');
    var query = new Parse.Query(User);

    query.get(request.params.user).then(function (result) {
        result.destroy();
    }).then(function (results) {
        response.success('User deleted');
    }, function (error) {
        response.error(error);
    })
});
```

It worked fine in Cloud Code however, it seems to be broken in parse-server, on debugging it looks like `Parse.Cloud.useMasterKey();` is not being applied to the options of all ParseObject calls. This is required because the ACL prevents anyone creating additional items in the table.

**Comment by wagnercsfilho** [comment]
#13 In the top of the cloud code file, try:

`Parse.serverURL = 'http://localhost:1337/parse';`

**Comment by REggar** [comment]
No such luck, it's worth adding that I'm getting errors on .save( as well.

**Comment by gfosco** [comment]
Will take a look at this...

**Comment by silvermana** [comment]
+1.  I can't .save() objects in Cloud Code via parse-sever if it requires useMasterKey().  In a beforeSave() function if I return success() early (before I create/save a protected object) it works fine, but if the code to create/save a sub-object runs I get an error:

```ParseError {
       code: 141,
       message: 'User beforeSave error = 2 the service is currently unavailable' }```

**Comment by gfosco** [comment]
Much like how Parse.User.current() is invalid in a node script, because of the global nature, so is Parse.Cloud.useMasterKey(), because it is global and it would cause other requests to use the master key even if it was not intended.

The correct approach is to always pass a `useMasterKey: true` option to saves and queries which need to use the master key.  We are going to document this as soon as possible, but I wanted to get this out to you and be able to close some issues.

In a save call, the options block is the second param:

```
obj.save(null, { useMasterKey: true });
```

In a query, it's the first.

```
q.get({ useMasterKey: true }).then(.......)
q.find({ useMasterKey: true}).then(......)
```

Please update your code to follow this and open a new issue if you have problems.  Thank you!

**Comment by ktmatzdorf** [comment]
Still getting an error. Parse-server is 2.0.7

> Uncaught internal server error. [TypeError: Cannot read property 'isMaster' of undefined] TypeError: Cannot read property 'isMaster' of undefined
>     at RestWrite.runBeforeTrigger.RestWrite.handleAnonymousAuthData.RestWrite.handleFacebookAuthData.RestWrite.transformUser.promise.then.RestWrite.handleSession.RestWrite.handleInstallation.RestWrite.runDatabaseOperation (/home/kai/finc3/parse/parse-server-example/node_modules/parse-server/RestWrite.js:650:17)
>     at /home/kai/finc3/parse/parse-server-example/node_modules/parse-server/RestWrite.js:82:17
>     at process._tickDomainCallback (node.js:425:9)

```
  Parse.Cloud.define('test2', function(request, response) {
    SyncReport = Parse.Object.extend('SyncReport');
    report = new SyncReport;
    report.set('testcolumn', "testentry");
    console.error(report);
    report.save(null, { useMasterKey: true })
    .then(function(user) {
      return responses.success(user);
    }, function(error) {
      console.error(error);
      return response.error(error);
    });
  });
```

**Comment by sivi29y** [comment]
@gfosco  you should move this info to the guide imho.

**Comment by OxyFlax** [comment]
I have the same problem, I tried to use @gfosco answer but I think I did it wrong. Could you help me? I read https://github.com/ParsePlatform/Parse-Server/wiki/Compatibility-with-Hosted-Parse#Cloud-Code too but it doesn't seem to work.

`Parse.Cloud.define("removeFriendRequest", function(request, response) {
  Parse.Cloud.useMasterKey();

  console.log("removeFriendRequest: remove userid: " + request.params.userIdToRemove + " from user: " + request.params.userId);
  var query = new Parse.Query(Parse.User);
  query.equalTo("objectId", request.params.userId);

  // Get the first user which matches the above constraints.
  query.first({
    success: function(anotherUser) {
    	anotherUser.remove("friends", request.params.userIdToRemove);
  		anotherUser.save(null, {
  	    success: function(user) {
  	      response.success("removeFriendRequest updated");
  	    },
  	    error: function(user, error) {
  	      response.error(error);
  	    }
  		});
    }
  });
});

Parse.Cloud.define("addGroupChatCount", function(request, response) {
  Parse.Cloud.useMasterKey();

  console.log("addGroupChatCount: added userid: " + request.params.userId + " for users: " + request.params.userIds + " for weevent: " + request.params.weeventId);
  var GroupMessage = Parse.Object.extend("GroupMessage");
  var query = new Parse.Query(GroupMessage);
  query.containedIn("fromId", request.params.userIds);
  query.equalTo("weeventId", request.params.weeventId);

  // Get the first user which matches the above constraints.
  query.find({ 
    success: function(results) {
      for (var i = 0; i < results.length; i++) {
        var result = results[i];
        result.increment("unreadAmount");
      };
      Parse.Object.saveAll(results, {
        success: function(list){
          response.success("add group chat succeeded");
        },
        error: function(error){
          response.error(error);
        }
      });
    }
  });
});`

**Comment by TheRyanHickman** [comment]
@OxyFlax It would be great if you shared what you did to make your code above work.

**Comment by khanamir** [comment]
@gfosco What should be the syntax for setting `useMasterKey: true` in:

`var query = new Parse.Query(Parse.Installation);
query.containedIn("user", userList);`

because for push notifications, we don't call `find` or `fetch`

**Comment by code-K** [comment]
@gfosco I would also need to know the new syntax about useMasterKey: true if I would like to use it on 
query.equalTo('user', request.object.get("createdBy"));

So for push...

Thanks much for feedback and best regards,
Chris

**Comment by kumarpranav** [comment]
@OxyFlax Can you please post your solution/ fix done?

**Comment by Haraldson** [comment]
I have the same problem as @khanamir – seemingly no way to just set an option?

I need to rewrite this to pass in `{ useMasterKey: true }` somewhere, somehow;

```javascript
Parse.Cloud.useMasterKey();
var installationQuery = new Parse.Query(Parse.Installation);
installationQuery.equalTo('user', user);

Parse.Push.send({
    where: installationQuery,
    data: { ... }
},
{
    // Would passing in `useMasterKey: true` here make the query
    // passed into the `where` above use the master key?

    // useMasterKey: true, ?

    success: function() {},
    error: function() {}
});
```

/cc @OxyFlax

**Comment by flovilmart** [comment]
Alongside success and error, as you commented

**Comment by rawatshailender** [comment]
Parse.Push.send({
    where: installationQuery,
    data: { ... }
},
{
    // Would passing in `useMasterKey: true` here make the query
    // passed into the `where` above use the master key?

    // useMasterKey: true, ?

    success: function() {},
    error: function() {},
    useMasterKey : true
});

**Comment by Heman6886** [comment]
Same Error I am Getting Here ::: ==>


Parse.Cloud.define("assignPasswordToUser", function(request, response){
    var query = new Parse.Query(Parse.User);
    query.equalTo("email", request.params.email);
    query.find({
        success: function(results){
            if (results) {
                Parse.Cloud.useMasterKey();
                var password = request.params.password;
                console.log(results);
                results[0].setPassword(password);
				results[0].save();
                response.success(1);
            };
        },
        error: function(){
            response.error("Error");
        }
    });
});

**Comment by flovilmart** [comment]
Stop using `Parse.Cloud.useMasterKey()` once and for all, use `.save(null, {useMasterKey: true})`

**Comment by Heman6886** [comment]
Parse.Cloud.define("assignPasswordToUser", function(request, response){
    var query = new Parse.Query(Parse.User);
    query.equalTo("email", request.params.email);
    query.find({
        success: function(results){
            if (results) {
              
                var password = request.params.password;
                console.log(results);
                results[0].setPassword(password);
				results[0].save(null, {useMasterKey: true});
                response.success(1);
            };
        },
        error: function(){
            response.error("Error");
        }
    });
});


Using This Gives Me An Error

**Comment by Heman6886** [comment]
error: Failed running cloud function assignPasswordToUser for user undefined with:
  Input: {"username":"9988736886","password":"********"}
  Error: {"code":141,"message":"Object not found."} functionName=assignPasswordToUser, code=141, message=Object not found., username=9988736886, password=hello, user=undefined
error: Error generating response. ParseError { code: 141, message: 'Object not found.' } code=141, message=Object not found.
[object Object]

I Am Getting This Error When Using this Function

Parse.Cloud.define('assignPasswordToUser', function(request, response) {
    new Parse.Query(Parse.User).get(request.params.username, {
        useMasterKey: true,
        success: function(user) {
            username.setPassword(request.params.password);
            username.save(null, {
                useMasterKey: true,
                success: response.success,
                error: function(obj, error) {
                response.error(error.message);
                }
            });
        },
	error: function(obj, error) {
            response.error(error.message);
        }
    });
});

**Comment by flovilmart** [comment]
Parse.Query().get takes an objectId as a parameter not a username

**Comment by ericraio** [comment]
I would just like to add that we were using useMasterKey() method the entire time for a year than out of now where everything started breaking without any code changes, after hours of headbanging I discovered the useMasterKey: true option

What changed for this to break?

**Comment by flovilmart** [comment]
The depreciation notice has been added on Dec 7th: https://github.com/ParsePlatform/parse-server/blob/master/src/cloud-code/Parse.Cloud.js#L64 and https://github.com/ParsePlatform/parse-server/commit/025e7a321886becfe48778c152b01dd0cb3fd492

This should have been deprecated at an earlier date, sorry for the inconvenience.

**Comment by r1cebank** [comment]
I am having trouble finding documentations for the change, the link everyone uses that links to the github wiki no longer works. Can I get the updated url for the documentation for this change? Thanks

**Comment by flovilmart** [comment]
see: http://parseplatform.github.io/docs/parse-server/guide/#cloud-code

**Comment by ZacharyKhan** [comment]
@flovilmart the link you posted is broken and returning a 404.

What about for `destroyAll()`, how do I pass in `useMasterKey:true`?

My example:

```Node.js
     query.find({
         success: function(posts) {
           Parse.Cloud.useMasterKey();
             Parse.Object.destroyAll(posts, {
                 success: function() {
                 }
             })
         }
     });
```

**Comment by flovilmart** [comment]
see: http://docs.parseplatform.org/parse-server/guide/#cloud-code

**Comment by ZacharyKhan** [comment]
@flovilmart thanks for the updated link, but can you answer my question above about the proper use of `useMasterKey:true` within my example?
