### ISSUE TITLE
Login with Facebook: Timeout

### ISSUE THREAD

**Issue by nitrag** [ParsePlatform/parse-server#376]
I'm using the JS SDK. Logging into Facebook works fine when connected to Parse Hosted API. When I switch the serverURL to my parse-server it "times out". I've checked and this is what I'm sending:

```
POST /1/users { host: 'asdf-parse.elasticbeanstalk.com',
...
{
    "authData": {
        "facebook": {
            "id": "xxx",
            "access_token": "xxx",
            "expiration_date": "2016-04-11T18:29:17.100Z"
        }
    },
    "_ApplicationId": "xxx",
    "_JavaScriptKey": "xxx",
    "_ClientVersion": "js1.5.0",
    "_InstallationId": "xxx"
}
```

I've modified the parse-server start script to dump the options so I can verify the parameters being used (ENV variables) are being set correctly. I've 'xxx' for privacy purposes.
```
> parse-server-example@1.0.0 start /var/app/current
> node index.js
{
    "databaseURI": "mongodb://xxx",
    "cloud": "/var/app/current/cloud/main.js",
    "masterKey": "xxx",
    "appId": "xxx",
    "fileKey": "xxx",
    "facebookAppIds": "1548670358725xxx",
    "filesAdapter": {
        ...
    }
}
```

There's no response object. Logging in with a username/password works fine and so do subsequent API requests.

Thanks!

**Comment by gfosco** [comment]
Please try updating to the latest version of parse-server-example (which should then pull the latest parse-server release 2.1.3) when you npm install.. Please re-open if you still experience this issue on the latest version.  Thanks.

**Comment by nitrag** [comment]
@gfosco, I can't explain what exactly but I think it was related to a cloud code beforeSave("Parse.User"). I'm not sure exactly but I think it wasn't throwing an error on a missing module from require()? Dunno.

Can you please tell me, though, I am trying to test Error 207 where the session is invalid in my app to ask them to login again. I have cleared _SESSIONS class and set _perishable_token,_session_token, and auth_date.facebook to "asdf" for my user in an attempt to create an invalid entry which will force parse-server to send Error 207. Yet...I'm still able to make successful API requests. How is this possible?
