### ISSUE TITLE
Parse.Server limitations

### ISSUE THREAD

**Issue by ktmatzdorf** [ParsePlatform/parse-server#381]
I am curious about the parse limitations like
cloud code execution time,
function code execution time,
queries a.s.o
Is a dedicated installation of parse server affected by and if so, how can i change these limits?

**Comment by bohemima** [comment]
There are no limits anymore, with no limits this also means that you can do really stupid stuff in CloudCode and bring down the app. Hopefully there will be some way of settings sensible timeouts in the future

**Comment by drew-gross** [comment]
Thanks for answering! That is correct.
