### ISSUE TITLE
Parse Server Push - Path to certificates

### ISSUE THREAD

**Issue by oyvindvol** [ParsePlatform/parse-server#383]
I am setting up the new Parse Server Push feature on Parse Server hosted on Heroku.

The Wiki says:
`ios: {
    pfx: '/file/path/to/XXX.p12',
    ...
}`

Is it possible to upload the certificates to Heroku somewhere? How do I get them up there, and what will the path to them be like?

**Comment by drew-gross** [comment]
The simplest solution would be to check them in to your repo. If you wish to avoid that for any reason (if, say, your app is open source and lives in a public repo) then the solution will depend on your exact setup and needs. We probably wouldn't be able to help you with that.

**Comment by wangmengyan95** [comment]
Hi @oyvindvol, suppose you certificate is `push.p12`, you can just put that file under your project root's folder(eg. The same folder of `package.json`). The configuration should be `ios: { pfx: 'push.p12'}`.

**Comment by d8815460** [comment]
Why I got this message from Parse Server

> Can not find sender for push type ios, {"where":{"deviceType":{"$in":["ios"]}},"data":{"title":"The Shining","alert":"All work and no play makes Jack a dull boy."}}
Can not find sender for push type android, {"where":{"deviceType":{"$in":["ios"]}},"data":{"title":"The Shining","alert":"All work and no play makes Jack a dull boy."}}


**This is my Push Code:**
`curl -X POST 
     -H "X-Parse-Application-Id: EoAplzLMJaf7ZGSvpJEWvbKz0rEBlR3nKUG9pLww" 
     -H "X-Parse-Master-Key: FssnnvdCbFCjgwS7i8FziDkngfRG4nT8SOQ6z40n" 
     -H "Content-Type: application/json" 
     -d '{ 
           "where": { 
             "deviceType": { 
               "$in": [ 
                 "ios" 
               ] 
             }
           }, 
           "data": { 
             "title": "A special discount for Giants fans", 
             "alert": "Check out our app for a 15% discount!"
           } 
         }'  http://203.77.34.135:3000/parse/push`

and i will got `{"result":true}`

**Comment by connorbode** [comment]
Don't check config into your repo, especially private keys.. 

Apparently you can store the contents in an environment variable on Heroku; I haven't verified yet.  See [this StackOverflow post](http://stackoverflow.com/a/14572535/962996)
