### ISSUE TITLE
request.user.id fails in User afterSave

### ISSUE THREAD

**Issue by jiawenzhang** [ParsePlatform/parse-server#384]
Parse.Cloud.afterSave(Parse.User, function(request) {

Parse.Cloud.useMasterKey();
var userId = request.user.id // this fails
...
})

**Comment by Tibabal** [comment]
Hi @jiawenzhang, this is a known bug, see #373 
By the way, you mustn't use Parse.Cloud.useMasterKey() anymore on parse-server, but {useMasterKey : true} along with each request you want to use it one, [as specified here](https://github.com/ParsePlatform/parse-server#not-supported)

**Comment by drew-gross** [comment]
That is correct. Thanks for helping with the issues!

**Comment by jiawenzhang** [comment]
this is not entirely fixed. if I am creating a new user, request.user.id still fails in afterSave, if it is an existing user, it works.

**Comment by Tibabal** [comment]
You could use request.object.id in _User afterSave hook meanwhile

**Comment by jiawenzhang** [comment]
@Tibabal that works, thanks;

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-alpha.20](https://github.com/parse-community/parse-server/releases/tag/7.0.0-alpha.20)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.5.0](https://github.com/parse-community/parse-server/releases/tag/6.5.0)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/7.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [7.0.0](https://github.com/parse-community/parse-server/releases/tag/7.0.0)
