### ISSUE TITLE
Export files stored on parse.com

### ISSUE THREAD

**Issue by jaydeep82** [ParsePlatform/parse-server#386]
For specific application and specific class/table, could you assist me how to export all files/document stored on parse.com ?

`http://files.parsetfss.com/{fileKey}/tfss-{someFile}-{fileName}`

**Comment by jaydeep82** [comment]
I think parse storing files at following location.

`http://files.parsetfss.com/{fileKey}/tfss-{someKey}-fileName`

**Comment by drew-gross** [comment]
We are working on a solution and will updated #8 as we make progress.
