### ISSUE TITLE
Decoupling Parse Server to Core, Cloud and Push?

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/parse-server#388]
I have to first of all thank everyone that has been working on and contributing the conversion of the parse backend from GO to Node.js 

I have a minor concern since both Parse.com and Iron.io posted articles how they went from I think Ruby with many servers to GO running on one server.  This providing higher scaleability and performance with the switch to GO.

Now that this is being ported over to Node.js I have some minor concerns about the ability to properly scale since I think honestly nobody yet has done any high end benchmarks.  I started some very small benchmarks on free tier Heroku servers see #185 I plan to fire up some bigger servers and mongo clusters over the next week and use New Relic and other tools to monitor the transaction loops.

With cloud code and parse push all running or coupled together with parse server I have a concern that under high load one or many of the parts will start to crumble under the load.  Which right now the solution is to scale your parse servers on Heroku, GCloud, Amazon etc.  

I think this works for the most part but what about decoupling some of the code to run on their own servers which then could be called parse core, parse push and parse cloud for example.  Below is a pretty simple diagram that shows suggest this.  Note this is something I quickly drew and hopefully didn't miss anything.. Figure 1 would be a simple stack, while figure 2 allows for horizontal scaling of both core, push and cloud.

![image](https://cloud.githubusercontent.com/assets/519563/13017358/9884366c-d178-11e5-8f3d-32fe180a34ca.png)

Now I know what everyone is thinking, we want one server to avoid having to deal with multi servers, and hiring dev-ops people to help us make sure everything is running, but my question is under a big load can one parse or a few parse servers handle the core functions, push and cloud?

Now a few things have been thrown out on how to scale parse , one is using pm2 or node.js cluster which for the most part if your server has more cores you can spawn another parse server on another core and define how much memory it should take up.  So if you had 4 cores with lots of memory you could in theory fire up 3 parse servers using x amount of memory and keeping one core for the server.  I'm sure you guys can see the issue if this server goes down your screwed since you do not have any other servers to fall back to to take the traffic.

Also from a previous project I know that servers can only handle so many open connections before they start to refuse or the latency gets quite high.  We had to set a lot of custom sysctrl settings for the flavor of unix we where using to get the best performance out of the server, since it also has default settings.

Any thoughts on this.  I would love to contribute but my node.js skills are not up to par to be pushing new code that could cause bottlenecks in the system vs someone who a node.js expert.

**Comment by flovilmart** [comment]
@gateway parse cloud is getting decoupled in #263 with it's own runner and process.

**Comment by gateway** [comment]
@flovilmart nice, I didn't see that post before so I thought I would make a suggestion as above.  Personally running more than one app seems like a nightmare as to debugging what app is taking up most of the resources so for me and the projects I'm working on I would just spin a brand new stack, just like you might do in a dev, stage, and live type of environment.

I do see the need for the ability to run more than one app but I also see issues with it..

Cheers :beer:

**Comment by flovilmart** [comment]
The multi apps is not intended for production, but for prototypes and to reduce the costs of running those prototypes on a single micro instance/heroku

**Comment by gfosco** [comment]
I think we have just about all the pieces for this now, with push adapters and the hooks API, that a more advanced deployment can be done to spread the load... I have no doubt it will just keep getting better architected for scale as we go.

**Comment by gateway** [comment]
Ill be testing the server this weekend with AWS elastic beanstalk and mongodb cloud.  Ill be using jmeter and blazemeter to ramp up some requests to the servers and hopefully get newrelic to spit out some details on transaction traces.

What are you guys plans on stress testing and making sure we dont have any blocking io, event loops taking to long etc? 

Another thing whats your thoughts on using pm2 (http://pm2.keymetrics.io/) on servers that have many cores and lots of ram?
