### ISSUE TITLE
Disable Client Class Creation

### ISSUE THREAD

**Issue by flavordaaave** [ParsePlatform/parse-server#39]
I'm aware that this it not a big security risk but I just don't want my DB to get spammed with data that I don't need.

**Comment by davidaik** [comment]
+1 Was thinking of posting the same thing

**Comment by NorthMcCormick** [comment]
+1

**Comment by andrewoons** [comment]
+1

**Comment by 5amfung** [comment]
There should be a setting to control either of this or https://github.com/ParsePlatform/parse-server/issues/26.

**Comment by gfosco** [comment]
Agreed, we should add this option.

**Comment by gfosco** [comment]
Less simple than expected.  The Schema class is what creates a new collection, but it isn't passed any of the configuration to hold an option like this.  Still working on a method for this.

**Comment by Morbix** [comment]
+1

**Comment by lucianmat** [comment]
Have worked on this issue, proposed solution will freeze schema (classes and fields) unless NODE_ENV === 'development' or masterkey is used. 
Have submited a PR ... :)

**Comment by drew-gross** [comment]
Added in #684
