### ISSUE TITLE
Parse Server on AWS Elastic Beanstalk 

### ISSUE THREAD

**Issue by json-park** [ParsePlatform/parse-server#394]
Hello~

I was set up Parse Server on AWS Elastic Beanstalk below guide link

http://mobile.awsblog.com/post/TxCD57GZLM2JR/How-to-set-up-Parse-Server-on-AWS-using-AWS-Elastic-Beanstalk

But This is for parse-server-example code.

When do i get official parse-server code on AWS Elastic Beanstalk?

Thank you

**Comment by rogerhu** [comment]
The parse-server-example has a dependency on parse-server (https://github.com/ParsePlatform/parse-server-example/blob/master/package.json#L15).  The index.js (https://github.com/ParsePlatform/parse-server-example/blob/master/index.js) instantiates the Parse server.

**Comment by json-park** [comment]
So I am not need to install the parse-server on AWS Elastic Beanstalk?
Using only the parse-server-example Can I use all the features?

**Comment by rogerhu** [comment]
It gets installed when you do npm install, which is what the one-step deploy will do for you (https://github.com/ParsePlatform/parse-server-example/blob/master/.ebextensions/app.config).  You do not need to install parse-server yourself.

**Comment by json-park** [comment]
Oh I see.
Thank you @rogerhu :)

**Comment by otto1020** [comment]
@json-park 
I was set up Parse Server on AWS Elastic Beanstalk.

But I had some issues.

Please read this comment carefully.

1. click "Deploy to AWS" on http://mobile.awsblog.com/post/TxCD57GZLM2JR/How-to-set-up-Parse-Server-on-AWS-using-AWS-Elastic-Beanstalk
2. select "node.js"
3. select "Upload your own code (advanced configuration)"
4. upload zip file
![untitled copy](https://cloud.githubusercontent.com/assets/16714648/13147152/69753030-d658-11e5-9369-2629dc5b9a02.png)
5. click "configure details"
6. click "create app"
![untitled copy](https://cloud.githubusercontent.com/assets/16714648/13147314/02adb6c8-d659-11e5-9ba7-6ac8399ee47d.png)
7. waiting
8. set Configuration(APP_ID, MASTER_KEY ...)
![untitled copy](https://cloud.githubusercontent.com/assets/16714648/13148512/00130224-d65e-11e5-9c82-4c0398486387.png)
9. click "apply"
10. when I go to server URL, That says "502 Bad Gateway nginx/1.8.0"
![untitled copy](https://cloud.githubusercontent.com/assets/16714648/13148842/43d5bc58-d65f-11e5-9af2-5e2adb2fba7a.png)
![untitled copy](https://cloud.githubusercontent.com/assets/16714648/13148901/7c9caa6a-d65f-11e5-8738-cbfb667f827f.png)

So I can't test parse-server on my app.

index.js is following:

var api = new ParseServer({

   databaseURI: databaseUri || 'mongodb://...',
   cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
   appId: process.env.APP_ID || '5...h',
   masterKey: process.env.MASTER_KEY || 'd...5',
   fileKey: process.env.FILE_KEY || '3...5'

});

I add my cloud code in main.js.

Now, what can I do? or what should I do?

Please help me.

Thanks,

**Comment by mmislam101** [comment]
There may be some answers in the following issue thread:
https://github.com/ParsePlatform/parse-server/issues/916
