### ISSUE TITLE
How to avoid GridStore when saving image through parse

### ISSUE THREAD

**Issue by kittuvenkat** [ParsePlatform/parse-server#395]
By default parse seems to use gridstore to store images. How do I change this default behavior? My images will be small in size and don't really need gridstore. Besides deleting/updating objects with images does not delete old image chunks and they continue to stay in fs.chunks and fs.files. Any suggestions appreciated..

**Comment by drew-gross** [comment]
Currently only gridstore is supported, but we are working on supporting other solutions. You can track progress in #8
