### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by phillfarrugia** [ParsePlatform/parse-server#4]
Receiving the following error message when I tried spinning up a sample Express project and requiring parse-server.

This happens even if all I do is `require('parse-server')`, or if I go ahead and follow the example in the README.md

See this test https://tonicdev.com/npm/parse-server

```SyntaxError: /app/available_modules/1454024179000/parse-server/index.js:145 request(options, (error, response, body) => { ^^ Unexpected token =>```

**Comment by gfosco** [comment]
Ah this should be require('parse-server').ParseServer

**Comment by gfosco** [comment]
Actually... this is ES6 code and perhaps tonicdev does not support it?...

**Comment by phillfarrugia** [comment]
Ah I was on an older version of Node, switched to v4.2.6 and working fine.

Thanks!
