### ISSUE TITLE
Add support for other OAuth Providers

### ISSUE THREAD

**Issue by flavordaaave** [ParsePlatform/parse-server#40]
Ideally it'd be possible to just integrate [Passport](http://passportjs.org) which offers Strategies for nearly every Provider you can think of.

**Comment by wagnercsfilho** [comment]
+1

**Comment by NorthMcCormick** [comment]
+1

**Comment by DiGiCT** [comment]
+1

**Comment by gfosco** [comment]
Similar to #41, this is relatively easy and PR's are welcome.

**Comment by flovilmart** [comment]
Will be fixed by #241
