### ISSUE TITLE
Parse-server install to Dedicated Server Linux

### ISSUE THREAD

**Issue by kwstasna** [ParsePlatform/parse-server#400]
Hello.
I would like some help with parse-server to my own dedicated server which is running on Linux
to be more precise

Linux 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

And i think its CentOS but i'm not sure.
Anyway i have installed through Putty, NodeJS and now i guess i have to install mongodb.
Is there anyone who can make a guide or any video tutorial of how to do it?
Thanks a lot!

**Comment by gateway** [comment]
Check the wiki link above and at the bottom of the page.. 

Also using it on digital ocean ubuntu see this guide https://www.digitalocean.com/community/tutorials/how-to-run-parse-server-on-ubuntu-14-04

**Comment by drew-gross** [comment]
Thanks for the help @gateway!
