### ISSUE TITLE
PushAdapter for Urban Airship

### ISSUE THREAD

**Issue by jashsayani** [ParsePlatform/parse-server#404]
It would be *nice* to have a PushAdapter for Urban Airship, since its a mainstream push management platform and has been in the space for a long time.

**Comment by gfosco** [comment]
Now that there's a push adapter system, it should be pretty straight-forward.  OneSignal already jumped on that with #405, and would be a good example.

**Comment by jashsayani** [comment]
@jarofghosts Is UA planning on an official adapter?

**Comment by mherrick66** [comment]
We're certainly open to it @jashsayani if there is enough interest in that from the Parse community. We created this Parse Importer Tool over the last couple weeks that helps with the data side/migration: https://www.urbanairship.com/blog/announcing-urban-airships-parse-importer-tool

**Comment by jashsayani** [comment]
@mherrick66 I did not know about the Importer Tool, will check it out. I would think that a PushAdapter for UA would definitely be useful for a lot of people (in terms of getting UA users). Currently OpenSignal is the only other provider working on it, so I would expect a fair share pick UA.

**Comment by flovilmart** [comment]
@jashsayani @mherrick66 @gfosco do we want all those adapter in the core code base? Given the context in which Parse is shutting down, I believe for the moment the core code base should focus on code/feature parity and allow extensibility through 3rd party node modules as discussed in #290 an others.

**Comment by flovilmart** [comment]
Implemented here: https://github.com/flovilmart/parse-server-urban-airship

**Comment by jashsayani** [comment]
@flovilmart Thanks. I'll try it out on the weekend.

**Comment by flovilmart** [comment]
@jashsayani wonderful! Don't hesitate to post issues on the repo directly to unclutter this one.

**Comment by edwardyue** [comment]
Any guide for helping to configure UA or Onesignal as PushAdapter?

Is it simple to amend bin/parse-server file?

**Comment by flovilmart** [comment]
check the README, the bin/parse-server hasn't been updated to support push yet.

**Comment by edwardyue** [comment]
i understand the current bin/parse-server, thats why i want to make use of OneSignal.

I got this [Error]: Push adapter is not availabe (Code: 115, Version: 1.12.0) for my iPhone app. any idea to implement the PushAdapter properly?

Thanks!

**Comment by edwardyue** [comment]
I have amended bin/parse-server like below, any comment

  // Make push adapter
  //let pushConfig = args.push;
  //let pushAdapter;
  //if (pushConfig && pushConfig.adapter) {
  //  pushAdapter = pushConfig.adapter;
  //} else if (pushConfig) {
  //  pushAdapter = new ParsePushAdapter(pushConfig)
//  }
  
   pushAdapter = new OneSignalPushAdapter(pushConfig)

**Comment by flovilmart** [comment]
@edwardyue you should not amend the bin/parse-server but have your 'package' with your app, that use parse-server. bin/parse-server is meant to be vanilla and configured only by environment variables.

**Comment by gfosco** [comment]
I'd recommend using the parse-server-example repo for your projects, rather than running the bin script here.. https://github.com/parseplatform/parse-server-example

Closing since the UA adapter is available: https://github.com/flovilmart/parse-server-urban-airship

Now, if we only had a nice place to discover parse-server modules...

**Comment by edwardyue** [comment]
Hi thanks!
Sorry I am new to parse.

Could u show me the steps how to make use of parse-server-example with UA
adapter for push notification?

Thanks

Fosco Marotto <notifications@github.com> 於 2016年2月21日星期日 寫道：

> Closed #404 <https://github.com/ParsePlatform/parse-server/issues/404>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParsePlatform/parse-server/issues/404#event-557776965>
> .
>


-- 
Thanks and Regards,
Edward Chan Woon Yue
