### ISSUE TITLE
How to generate access keys for new apps

### ISSUE THREAD

**Issue by drbarto** [ParsePlatform/parse-server#406]
When migrating an existing app to to my own Parse server, I can re-use the client/JS/etc. keys from the Parse.com dashboard. But how can I generate these keys when starting a fresh app on my server, and are there instructions on how to generate 'good' app IDs and master keys? As long as Parse.com is still up and running, I can use the dashboard for that; but in the long run this doesn't feel right.

**Comment by bohemima** [comment]
You can use any kind of string really, for my local testing I simply use <application name>-application-id and <application name>-master-key for keys.

I'd say, to keep it simple, take the application name, add some extra random characters and create a sha-1 from that. Or any other kind of hashing algoritm.

**Comment by drbarto** [comment]
Ah, I just realized that I can (i.e. have to) pass all these keys to the ParseServer constructur when setting up the server. I was assuming that the client keys were somehow derived from the master key, but obviously that's not the case.

**Comment by pankaj9492** [comment]
Hi, 
I am facing same issues, can anyone tell me the solution of it.

**Comment by bohemima** [comment]
Please read my answer above.

**Comment by atonamy** [comment]
You can use tool something like this https://www.randomlists.com/string
