### ISSUE TITLE
Cross-origin issue on /classes?

### ISSUE THREAD

**Issue by vbabaria** [ParsePlatform/parse-server#408]
get following error...

"_**XMLHttpRequest cannot load http://localhost:1337/parse/classes/Generic. Request header field X-Parse-Application-Id is not allowed by Access-Control-Allow-Headers in preflight response**._"

using below simple restful call fails connecting to parse-server and same code works via parse.com (commented out line below)

any help would be really appreciated - thanks

 $.ajax({
                  type: "GET",
                  //url: "https://api.parse.com/1/classes/Generic",                  // works
                  url: "http://localhost:1337/parse/classes/Generic",              // fails
                  data: "",
                  contentType: "application/json",
                  headers: {
                    "Content-Type": "application/json",
                    "X-Parse-Application-Id":"app key",
                    "X-Parse-REST-API-Key":"rest api key"
                  },
                 success: function(data){
                    console.log(data);
                 }
             });

**Comment by omairvaiyani** [comment]
I recall getting this error until we upgraded to ```2.0.7```. What are you on?

**Comment by vbabaria** [comment]
thanks for the response - using v.2.0.8 of parse-server and still get this error

**Comment by gfosco** [comment]
Can you try this with a bare copy of parse-server-example?  The middlewares are set up to allow cross-origin on these paths, so I'm wondering if you've made a change or otherwise have something configured incorrectly.

**Comment by vbabaria** [comment]
thanks for the update and response

this issue seems to be related to [https://github.com/ParsePlatform/parse-server-example/issues/53](url)

**Comment by drew-gross** [comment]
This issue is fixed in #390. If you don't want to wait for the next release, you can clone the repo and run the master branch.
