### ISSUE TITLE
_dummy collection

### ISSUE THREAD

**Issue by davodesign84** [ParsePlatform/parse-server#409]
Hi all, this is more of a question, than an issue, and probably due to my limited knowledge of MongoDB.

I partially migrated the app to AWS Beanstalk and MongoLab, super simple. However I noticed that there is a "_dummy" collection which keeps growing in disk space, and currently takes as much spaces as the biggest collection in the DB.
What is it for? Can it be cleaned somehow?

![screen shot 2016-02-14 at 14 19 36](https://cloud.githubusercontent.com/assets/749029/13034181/76dc03e6-d326-11e5-8bf4-63703208ed82.png)

**Comment by gfosco** [comment]
Pretty sure this is an artifact of the migration process, which is supposed to be cleaned up when finalized.  Did you finalize the migration through the Parse website?

**Comment by davodesign84** [comment]
Not yet :) I'll follow up once I do. Still need to migrate the old files

**Comment by gfosco** [comment]
The file migration will come later, and you can/should finalize before then.  In the state you're in now, Parse is double-writing data to your mongo and the original parse database.. Finalizing allows your mongo to become the source of truth.

**Comment by davodesign84** [comment]
I see. Would the existing clients still be able to read the legacy files / images?

**Comment by gfosco** [comment]
Yep, hat is why you provide a fileKey to ParseServer, so it then knows how to render the proper Parse S3 urls for files.
