### ISSUE TITLE
Twitter Auth

### ISSUE THREAD

**Issue by swaterfall** [ParsePlatform/parse-server#41]
Any plans to allow login with Twitter again?

**Comment by gfosco** [comment]
It would not be hard to add, following the method used for Facebook login.  

See `facebook.js` and `RestWrite.js`.  

I'll tag this up-for-grabs.

**Comment by shahzeb1** [comment]
Is anyone currently working on this?

If not, I'll fork and get to work. :coffee:

**Comment by billymwlei** [comment]
OP: Is it same way to do the linkedin auth as well?
And Idea what should I get started ?
Thanks

**Comment by nlutsenko** [comment]
There is an ongoing discussion in #241 about this, where the goal is to support everything, not just Twitter or LinkedIn.

**Comment by flovilmart** [comment]
@billymwlei the linked-in support is available in #241 we're finalizing some details about the implementation.

**Comment by gfosco** [comment]
This will land in #247. :+1:

**Comment by sprabs** [comment]
Quick question for you all (since you implemented this). We have two Twitter apps (one our iOS clients are using and one that our Android clients are using). How do we specify two sets of keys in index.js?

**Comment by gfosco** [comment]
It doesn't look like the twitter module supports it... It might be possible to use a 'custom' auth module but provide the twitter module again, but one app would need to use like 'twitter2' as a provider instead of twitter.  Probably best to look at modifying the twitter module.
