### ISSUE TITLE
Registration email 

### ISSUE THREAD

**Issue by rosarioconti** [ParsePlatform/parse-server#417]
I'm trying to register with SignUpViewController , I see the user has been added to the db but I don't get any emails.
Is that something I should implement my self or is it only working with facebook now ? or..

thsnks

**Comment by mikebonilla** [comment]
+1, is there any method on the backend to manage the email interaction (validation, password reset)? Got my server on AWS + mongolab, but I've googled it and didn't find anything..

Thanks.

**Comment by loftyet** [comment]
https://github.com/ParsePlatform/parse-server/issues/350
Apparently we need to implement it on our own now.

**Comment by loftyet** [comment]
https://github.com/ParsePlatform/parse-server/issues/275

**Comment by gfosco** [comment]
The mail adapter approach and the verification functionality are being discussed in #275 and worked on in various open PRs.  Definitely valuable and in the works.
