### ISSUE TITLE
Heroku and Parse Server using cached Cloud code - issue

### ISSUE THREAD

**Issue by rosarioconti** [ParsePlatform/parse-server#418]
Hi guys,

 I have been working on the cloud code for a while now but recently while updating the code I realized that was not updating anymore my code, 
 I can actually see the code on the master repo been uploaded.

I have been doing few things:
 1) heroku repo:purge_cache -a  myappname     and re uploaded the build changes
 2) checking the source on the server after uploading new changes (checking that the change were  actually there in the right master repo) 
    e.g. heroku run bash myappname   
           cat index.js and /cloud/main.js
 3) I have replaced index.js and main.js with empty files and can still execute the code.

Appreciate Any help because I'm unable to do anything 
I can't find any solution.
 thanks

**Comment by gfosco** [comment]
You should be actually deploying to heroku.. If you have the git repo locally and heroku is set up as a remote, you'd commit your changes and run `git push heroku master` and it would re-build everything.
