### ISSUE TITLE
object.dirtyKeys in Parse.Cloud.beforeSave does not return dirty keys

### ISSUE THREAD

**Issue by anthonylai** [ParsePlatform/parse-server#419]
Hi,

  Calling object.dirtyKeys() in the beforeSave trigger for an existing object always returns an empty array with no dirty keys in it.  

  The feature is critical for our application.  Please kindly assist.

  Thanks.
Sincerely,
Anthony

**Comment by Kira2** [comment]
+1 It seems that the isDirty function always returns false also into beforeSave trigger.
Thanks.

**Comment by daviddayag** [comment]
+1 same here.

**Comment by natanrolnik** [comment]
Maybe it's related to #581 ?

**Comment by daviddayag** [comment]
Yes!
Thanks.
Waiting for a fix...

**Comment by nlutsenko** [comment]
Fix incoming in #614 anytime now.
