### ISSUE TITLE
Migration DB Stuck

### ISSUE THREAD

**Issue by talkaboutdesign** [ParsePlatform/parse-server#42]
Was trying to migrate data to MongoLabs and pressed cancel during the process. Typed in wrong url. 

Now I am stuck on this screen and can't retry the process.
<img width="778" alt="screenshot 2016-01-29 12 35 08" src="https://cloud.githubusercontent.com/assets/2926534/12683382/f088708c-c686-11e5-92e3-e8e5c9d8bf47.png">

**Comment by gfosco** [comment]
cc @drew-gross

**Comment by jamesyu** [comment]
yep this is a bug, we're working on it

**Comment by francocorreasosa** [comment]
+1

**Comment by jamiechapman** [comment]
+1, the UI allowed me to retry today — after about 20 minutes of `migrationState=1` (with a 4 month `secondsRemainingStr`) the export eventually failed to state `7` and showed up as cancelled in the web UI.

We're using a mongolab M1 instance with `failIndexKeyToLong` set as suggested in the guide with SSL too.  We have roughly have about 40 million objects stored on Parse, so I'm wondering if the process which 'snapshots' the data is somehow timeout out and thus causing the migration to prematurely cancel itself?

<img width="720" alt="screen shot 2016-01-30 at 14 23 01" src="https://cloud.githubusercontent.com/assets/688026/12696291/54b38d26-c75e-11e5-9d77-faa3d2213460.png">
![migra](https://cloud.githubusercontent.com/assets/688026/12696290/54ac2374-c75e-11e5-9b39-f9278ccf3b49.png)

**Comment by JcMinarro** [comment]
+1

**Comment by talkaboutdesign** [comment]
FYI, mine is stuck on this screen for a day.

<img width="749" alt="screenshot 2016-01-29 21 13 22" src="https://cloud.githubusercontent.com/assets/2926534/12697467/15708f94-c752-11e5-929f-94cf17e494ca.png">

**Comment by JcMinarro** [comment]
It is broken. I have done a new proyect with only 2 installations and 2 users and it does not work.
I am on the smae screen @talkaboutdesign

**Comment by gfosco** [comment]
Ok, sorry about this delay... Checking on the status of this tool internally.

**Comment by aaronrau** [comment]
Hi, I was trying to migrate data to MongoLabs as well but to their **Shared Plan** unfortunately it failed.

Turns out that from their support team, the **Shared Plan** failedIndexKeyToLong is set to **true**.

Is it possible to get an error log from the migration tool to show that my migration is failing due to this setting? MongoLabs is willing to change that parameter.

**Comment by talkaboutdesign** [comment]
Still same after 36 hours.

**Comment by hafizapp** [comment]
How can I re-initiate the migration process?

Now I am stuck on this page. Please help

<img width="848" alt="screen shot 2016-01-31 at 12 06 02 pm" src="https://cloud.githubusercontent.com/assets/1691606/12700581/6413e328-c813-11e5-9d99-2f0769390949.png">

**Comment by francocorreasosa** [comment]
@hafizapp Go to App Settings and start the migration again. It works fine.

**Comment by hafizapp** [comment]
@francocorreasosa  I am really sorry, still it showing this for me. And it don't allow me to start the migration process again.

Thanks
<img width="1149" alt="screen shot 2016-02-01 at 10 49 42 am" src="https://cloud.githubusercontent.com/assets/1691606/12709024/a8a229b4-c8d1-11e5-82ac-1b05a5d47280.png">

**Comment by gloos** [comment]
same here, it just gets stuck

**Comment by hafizapp** [comment]
@francocorreasosa Thank You.

Just noticed. Instead of going migration. You have to go -

App Settings -> Migrate

**Comment by RafaRuiz** [comment]
I'm experiencing something different:

My database got migrated 100% with green ticks to say it was OK. Now my app doesn't work. This morning I was able to load the dashboard, but can't load the database. Now I see an error 500:

![image](https://cloud.githubusercontent.com/assets/6842786/12714199/3269ef9e-c8cb-11e5-9d03-c839e7ffbf6a.png)

and if I see the collections:

![image](https://cloud.githubusercontent.com/assets/6842786/12714211/488db3e6-c8cb-11e5-8e93-b2954ae6c51a.png)

**Comment by tredman** [comment]
@RafaRuiz - in your case there appears to be an authentication error. We are unable to connect to mongo using the credentials that you provided. Can you check the username/password you provided and your mongodb connection string? You can force-change your mongodb connection string under "App Settings" in the Parse dashboard.

**Comment by jamiechapman** [comment]
@tredman could you possible check why our db export is failing too? https://dashboard.parse.com/apps/minecraft-explorer-pro, I asked the nice folk over at mongolab to make sure all my settings are correct and everything seems fine.  Is it a Parse bug or am I doing something wrong?  Thanks!

**Comment by skinp** [comment]
@jamiechapman your particular issue seems to be a known bug with the migration (replicaset not found). We're working on a fix for this.

**Comment by jamiechapman** [comment]
@skinp — thanks so much for the clarification, we've been a bit worried that it was something our end that was at fault.  We'll wait for a fix in that case.  Cheers.

**Comment by tredman** [comment]
@jamiechapman - the fix is live, please try again at your convenience.

**Comment by jamiechapman** [comment]
Perfect, thanks @tredman — started the migration again and I can see objects coming into the database as we speak.

**Comment by jamiechapman** [comment]
@tredman — it started to go horribly wrong, each object had this error:-

```
"Skin": {
        "Name": "Skin",
        "State": 7,
        "StateReason": "EnsureEmpty issue: not authorized on skinstudio to execute command { count: \"Skin\", query: {} }",
        "BatchSize": 1000,
        "ExpectedDocumentsApprox": 1221975
      },
```

I've cancelled the migration and setup a new connection string using the root user instead, but the UI now says `Migration already in progress.` (even though it isn't?).

**Comment by tredman** [comment]
@jamiechapman - the job automatically retried a number of times before it was finally stopped. At the moment, it doesn't appear to be in an in-progress state. Can you please try again? Note that if a previous migration failed, you will need to drop any documents on the destination before beginning a new migration, or it will return an error.

**Comment by jamiechapman** [comment]
Hmm, thats a bit weird @tredman.

1. I've dropped all collections in the database using mongolab.

1. The "Migrate" button is clickable in App Settings.
<img width="682" alt="migr_0" src="https://cloud.githubusercontent.com/assets/688026/12733756/82c93f94-c934-11e5-830e-f1c7917e7df8.png">

2. I entered the connection string again (+ verified it works via another tool), but it says `Migration already in progress`.
![migr_1](https://cloud.githubusercontent.com/assets/688026/12733790/abda350a-c934-11e5-99ff-ff3a713df27d.png)

3. I checked the `/migrations` REST endpoint to see what the deal was and its in state `9`, does that mea anything?  It's weird how the migration still appears to be running but the Web UI is trying to let me start again.
<img width="539" alt="migr_2" src="https://cloud.githubusercontent.com/assets/688026/12733813/d3bf8228-c934-11e5-828a-923ea9afdaf1.png">

**Comment by gloos** [comment]
I confirm I was stuck and I've just tried migrating again but I get a Migration already in progress error.

**Comment by tredman** [comment]
We've identified a UI bug with certain job states. A fix is coming shortly.

**Comment by RafaRuiz** [comment]
@tredman I can't modify the connection string under App Settings, there's no field to change it. I just can click on Migration and it shows the success of migration. What else can I do?

> @RafaRuiz - in your case there appears to be an authentication error. We are unable to connect to mongo using the credentials that you provided. Can you check the username/password you provided and your mongodb connection string? You can force-change your mongodb connection string under "App Settings" in the Parse dashboard.

**Comment by gfosco** [comment]
We discussed this here and basically in order to deal with migration issues, we need you to individually report a bug through parse.com/help.  This allows each of you to get individual support, from a team who can escalate issues, and for us to be able to ask up front for specific information which will help us handle your issue.  We're exposing the 'job id' for the migration in the UI, and that is something you should provide if you're having a problem.  

Going to close this issue.  For problems involving migration, or any issues not specific to parse-server, please visit https://parse.com/help and find the bug icon / "Something wrong?" section to start the bug reporting flow.

**Comment by taijizhu** [comment]
any updates on this?

**Comment by francocorreasosa** [comment]
@taijizhu This was resolved on Feb 3.

**Comment by ibrahim132** [comment]
Also i have the same issue but the migration stuck on "Sync" and i can't finalize the migration.
![screenshot from 2016-04-20 15-12-15](https://cloud.githubusercontent.com/assets/14311615/14675757/2bb294ae-0713-11e6-9608-f4d1a57d2415.png)

**Comment by hramos** [comment]
A migration job stuck in sync usually points to insufficient hardware or high latency between api.parse.com and your target database. 

Please report any migration issues at https://parse.com/help. We'd like to keep the discussion here centered around Parse Server itself.

**Comment by zyg-github** [comment]
I have the same issue(in the sync state above 12 hours), and is there any log that we can know what's the real problem is?
![image](https://cloud.githubusercontent.com/assets/5036024/14704920/b6519d9a-07e9-11e6-9857-ac0ab5d022ff.png)

**Comment by hramos** [comment]
@zyg-github see my answer above.

**Comment by zyg-github** [comment]
@hramos If the problem points to insufficient hardware or high latency between api.parse.com. But why can i get the sync speed so high. 416rows/s befor and 1.71krows/s now?
![image](https://cloud.githubusercontent.com/assets/5036024/14728714/f9fd2b9c-0869-11e6-99cd-f2d24170ec05.png)

**Comment by hramos** [comment]
@zyg-github you inquired about a log with additional information. Contacting us via https://parse.com/help#report with your job id is the best way to get more details on what is wrong with a specific migration.

**Comment by zyg-github** [comment]
@hramos 
![image](https://cloud.githubusercontent.com/assets/5036024/14733391/438d98f2-0895-11e6-9f04-82a0e797772a.png)

**Comment by Treybro** [comment]
I'm currently in the process of migrating a live production mobile application from Parse to Azure using the Migration Tool provided by the good folk at Parse, however I'm getting stuck on the "Sync Phase".

I'm getting all green lines indicating a successful transfer of the data, however when the migration tool is checking for any new writes, it fails with the following error:

["There was a problem with the migration."](http://i.stack.imgur.com/LqRMa.png)

Parse documentation doesn't have any information on the above, so I would appreciate your help!

I'm running my Azure server and Document DB instances on the S3 (Standard: Large) with Auto scaling, and the Document DB implementation is on Pricing Tier S3 (THROUGHPUT (RU/s) 2500)

**Comment by hramos** [comment]
@Treybro see my last three posts in this issue - you'll want to use the Parse bug reporting tool.

**Comment by zyg-github** [comment]
@Treybro  
I also encountered the same problem. You solve the problem yet?
