### ISSUE TITLE
Problem with android installations

### ISSUE THREAD

**Issue by juanber84** [ParsePlatform/parse-server#422]
## REQUEST
```
 curl -X POST \
 -H "X-Parse-Application-Id: myAppId" \
 -H "X-Parse-REST-API-Key: 12345" \
 -H "Content-Type: application/json" \
 -d '{
 "pushType": "gcm",
 "deviceType": "android",
 "GCMSenderId": "............",
 "deviceToken": ".............",
 "channels": []
 }' \
 http://localhost:1337/parse/installations
```
## RESPONSE
```
{
"code":114,
"error":"deviceToken may not be set for deviceType android"
}
```

**Comment by christianmarth** [comment]
You don't need to set the deviceToken for Android, this only applies for iOS APNS, try again with the deviceToken parameter omitted.

**Comment by juanber84** [comment]
So how can i send a push to a unique device without gmc device token?

**Comment by wangmengyan95** [comment]
Hi @juanber84, in android, the installation initialization flow is
1. Parse Android SDK creates an installation and save to Parse
2. Parse Android SDK registers the device with GCM
3. Parse Android SDK gets the deviceToken from GCM and update the existing installation.
Thus, if you do not want to use Android SDK but want to use REST API to create an Android installation,
you need
1. Create a installation without the deviceToken field
2. Update this installation with the deviceToken field

**Comment by juanber84** [comment]
Thanks @wangmengyan95, but can install android devices in 1 step in parse.com.  I think that 2 steps in api is unnecessary.

**Comment by gfosco** [comment]
I believe what wangmengyan95 was saying is that the android SDK does it in 2 operations, in the background.  I'm going to close this issue because the feature does function in parity with api.parse.com, but feel free to submit a PR removing this limitation (and testing it of course).  We can review and discuss if there's any reason to keep it.  Thanks.

**Comment by subodh-malgonde** [comment]
@wangmengyan95 how do I trigger steps 2 and 3? Will the SDK call them automatically after I call the following code in `onCreate` in application.java?

    Parse.initialize(this, "appID", "clientKey");
    ParseInstallation.getCurrentInstallation().saveInBackground();
