### ISSUE TITLE
Uncaught internal server error. bad key in untransform: _lock_row undefined 

### ISSUE THREAD

**Issue by giano** [ParsePlatform/parse-server#423]
I have this error on running Cloud Code events (in this case a beforeSave trigger)

**Comment by giano** [comment]
Closing as related to [https://github.com/ParsePlatform/parse-server/issues/165](https://github.com/ParsePlatform/parse-server/issues/165)

**Comment by giano** [comment]
Still same issue.

**Comment by gfosco** [comment]
Are you trying to save a Parse object with a root-level key of '_lock_row' ?  That's an invalid key name.  A recent PR allowed this type of key name inside an object column on an object, but not as a root level key.  If not, please provide your code and re-open.  Thanks.
