### ISSUE TITLE
related to parse server

### ISSUE THREAD

**Issue by sidkasundra** [ParsePlatform/parse-server#425]
I can't find parseapplication setting..
i need my application id and client key..
when i login in parse using github then it direct redirect to your website.
help me to solve this problem..

**Comment by christianmarth** [comment]
If this is for migrating an existing app go to https://dashboard.parse.com/apps to get your details, if it's for a new app you can create your own string for application-id

**Comment by sidkasundra** [comment]
Ok sir.
Please give me a brief information about how to create my own string for application-id..
sorry for that but i m beginner in android application development.

**Comment by ndnguru** [comment]
I believe you are free to choose any string for the key fields, preferably
randomly generated or cryptographic methods are most suitable.

A quick google search lends this site as a resource for random keys:
http://randomkeygen.com/

On Monday, February 15, 2016, sidkasundra <notifications@github.com> wrote:

> Ok sir.
> Please give me a brief information about how to create my own string for
> application-id..
> sorry for that but i m beginner in android application development.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParsePlatform/parse-server/issues/425#issuecomment-184507897>
> .
>


-- 

Rusil G. Patel
------------------------------
[image: LinkedIn] <https://www.linkedin.com/pub/rusil-g-patel/8/32a/739>
