### ISSUE TITLE
Parse Dashboard

### ISSUE THREAD

**Issue by greggmojica** [ParsePlatform/parse-server#428]
What is the status on the parse dashboard? I have a lot of clients who really like it and are upset it is going away. I do remember reading steered here that you guys were working on it?

**Comment by christianmarth** [comment]
#3

**Comment by adampietrasiak** [comment]
I know #3 is duplicate, but it've been a while and I'd be good to know some update on that :wink:

**Comment by greggmojica** [comment]
Same. #3 was closed over two weeks ago.

**Comment by flovilmart** [comment]
@greggmojica @christianmarth this is likely to be available in a separate repository and #3 is marked as in progress.

**Comment by gfosco** [comment]
Yep.. Stay tuned, follow on in #3.
