### ISSUE TITLE
What's the file key?

### ISSUE THREAD

**Issue by meilers** [ParsePlatform/parse-server#43]
In the migration guide, it says to set the environment variables using the appId, master key and file key. What is the file key? I don't see it in "Security & Keys" in my app's settings.

**Comment by jamesyu** [comment]
I think you might be using the old dashboard. The file key only appears in the new dashboard for your apps: dashboard.parse.com

**Comment by meilers** [comment]
Hmmm I’m on the beta dashboard and I don’t see it:

**Comment by jamesyu** [comment]
Oh whoops you're right, we forgot to enable this! Check again.
