### ISSUE TITLE
Android SDK connection error

### ISSUE THREAD

**Issue by christoandrew** [ParsePlatform/parse-server#431]
Getting error code 100 when trying to connect to the server running locally after specifying server url and also the application id and client key configured on the server.

**Comment by christianmarth** [comment]
Try without the client key

**Comment by christoandrew** [comment]
No luck 
`02-16 15:09:51.903    6815-6868/com.iconasystems.android.authensandroid W/System﹕ Ignoring header X-Parse-Client-Key because its value was null.
02-16 15:09:51.987    6815-6869/com.iconasystems.android.authensandroid V/com.parse.ParseRequest﹕ Request failed. Waiting 2742 milliseconds before attempt #2
02-16 15:09:52.115    6815-6871/com.iconasystems.android.authensandroid W/System﹕ Ignoring header X-Parse-Client-Key because its value was null.
02-16 15:09:52.115    6815-6871/com.iconasystems.android.authensandroid W/System﹕ Ignoring header Content-Type because its value was null.
02-16 15:09:52.131    6815-6872/com.iconasystems.android.authensandroid V/com.parse.ParseRequest﹕ Request failed. Waiting 3442 milliseconds before attempt #2
02-16 15:09:54.019    6815-6873/com.iconasystems.android.authensandroid V/com.parse.GcmRegistrar﹕ Received deviceToken <APA91bGKZDgbgY-7Xtfa31oq4wmOXJtw6hAMYI9Zu3eVYA-TaTFGZkk_1sP9IJiz8RSvUzSoQ01Py0xvwQ7Orv52N7I-JUBplxAjme_IEIyBekTnfILT6yMt-IdCkhAOKc_M1ffYGUsbQW1L3bk1DZQ5IbSV_69QLA> from GCM.
02-16 15:09:54.727    6815-6876/com.iconasystems.android.authensandroid W/System﹕ Ignoring header X-Parse-Client-Key because its value was null.
02-16 15:09:54.743    6815-6877/com.iconasystems.android.authensandroid V/com.parse.ParseRequest﹕ Request failed. Waiting 5484 milliseconds before attempt #3
02-16 15:09:55.579    6815-6878/com.iconasystems.android.authensandroid W/System﹕ Ignoring header X-Parse-Client-Key because its value was null.
02-16 15:09:55.579    6815-6878/com.iconasystems.android.authensandroid W/System﹕ Ignoring header Content-Type because its value was null.
02-16 15:09:55.587    6815-6879/com.iconasystems.android.authensandroid V/com.parse.ParseRequest﹕ Request failed. Waiting 6884 milliseconds before attempt #3
02-16 15:10:00.227    6815-6893/com.iconasystems.android.authensandroid W/System﹕ Ignoring header X-Parse-Client-Key because its value was null.
02-16 15:10:00.243    6815-6894/com.iconasystems.android.authensandroid V/com.parse.ParseRequest﹕ Request failed. Waiting 10968 milliseconds before attempt #4
02-16 15:10:02.479    6815-6895/com.iconasystems.android.authensandroid W/System﹕ Ignoring header X-Parse-Client-Key because its value was null.
02-16 15:10:02.479    6815-6895/com.iconasystems.android.authensandroid W/System﹕ Ignoring header Content-Type because its value was null.
02-16 15:10:02.491    6815-6896/com.iconasystems.android.authensandroid V/com.parse.ParseRequest﹕ Request failed. Waiting 13768 milliseconds before attempt #4
02-16 15:10:11.211    6815-6897/com.iconasystems.android.authensandroid W/System﹕ Ignoring header X-Parse-Client-Key because its value was null.
02-16 15:10:16.259    6815-6900/com.iconasystems.android.authensandroid W/System﹕ Ignoring header X-Parse-Client-Key because its value was null.
02-16 15:10:16.259    6815-6900/com.iconasystems.android.authensandroid W/System﹕ Ignoring header Content-Type because its value was null.
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ com.parse.ParseRequest$ParseRequestException: bad json response
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ at com.parse.ParseRequest.newTemporaryException(ParseRequest.java:290)
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:308)
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ at com.parse.ParseRequest$3.then(ParseRequest.java:137)
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ at com.parse.ParseRequest$3.then(ParseRequest.java:133)
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ at bolts.Task$15.run(Task.java:917)
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ at bolts.Task.completeAfterTask(Task.java:908)
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ at bolts.Task.continueWithTask(Task.java:715)
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ at bolts.Task.continueWithTask(Task.java:726)
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ at bolts.Task$13.then(Task.java:818)
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ at bolts.Task$13.then(Task.java:806)
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ at bolts.Task$15.run(Task.java:917)
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ Caused by: org.json.JSONException: Value Cannot of type java.lang.String cannot be converted to JSONObject
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ at org.json.JSON.typeMismatch(JSON.java:111)
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ at org.json.JSONObject.<init>(JSONObject.java:159)
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ at org.json.JSONObject.<init>(JSONObject.java:172)
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ at com.parse.ParseRESTCommand.onResponseAsync(ParseRESTCommand.java:298)
02-16 15:10:16.275    6815-6815/com.iconasystems.android.authensandroid W/System.err﹕ ... 13 more`

**Comment by leo-one** [comment]
Just out curiosity: does your server declaration have "/" in the end (like below)?

```java
Parse.initialize(new Parse.Configuration.Builder(this)
                .applicationId("APP_ID")
                .clientKey("CLIENT_KEY")
                .server("https://app_real_name.herokuapp.com/parse/")
                .build());
```

**Comment by christoandrew** [comment]
Tried both variations with "/" and without

**Comment by leo-one** [comment]
I get this error when the server does not have "/" in the end.

**Comment by christoandrew** [comment]
When i put "/parse/" i get a TypeError in the server log

**Comment by christoandrew** [comment]
I had an older version of node update fixed issue.
