### ISSUE TITLE
request.user is null in Cloud Code

### ISSUE THREAD

**Issue by aziz92** [ParsePlatform/parse-server#436]
request.user is null in Cloud Code. Session token is being passed in the header.

Any ideas?.

**Comment by flessard** [comment]
@aziz92  Can you check if the session token is passed to the cloud function, begin it by r: ?

**Comment by gfosco** [comment]
Please re-open if you're still having an issue in 2.1.2.  Thanks.

**Comment by Tibabal** [comment]
Hi @gfosco , still having same issue in 2.1.2. To answer @flessard question, session-token doesn't begin by r: in some cases, but I can't seem to identify them precisely.
The only constant case I seem to get is by calling this cloudCode function:

Here is the concerned header:

POST /parse/functions/getContacts { host: 'www.xxx.yyy.zzz:pppp',
  'x-parse-client-version': 'i1.12.0',
  accept: '*/*',
  'x-parse-session-token': 'p3d7cpm3lO....',
  'x-parse-application-id': 'xxxxxx',
  'x-parse-client-key': 'xxxxxx',
  'x-parse-installation-id': 'xxxxx',
  'x-parse-os-version': '9.2.1 (13D15)',
  'accept-language': 'fr-fr',
  'accept-encoding': 'gzip, deflate',
  'content-type': 'application/json; charset=utf-8',
  'content-length': '2391',
  'user-agent': 'DGE/1 CFNetwork/758.2.8 Darwin/15.0.0',
  connection: 'keep-alive',
  'x-parse-app-build-version': '1',
  'x-parse-app-display-version': 'xxxxx' } {}

As a result, request.user is null.

Thanks for helping.

**Comment by aziz92** [comment]
@Tibabal  I am pretty sure this has to be with your (and my) app using the old (non revocable) sessions that do not start with "r:". Basically, getAuthForSessionToken() in Auth.js looks for this session token in _Session collection (because it thinks it's the new revocable session) and if you are using the old sessions, they are stored in the _User collection. 

I solved this by patching Auth.js; I look and see if it's an old session or new session. If it's new, then i just do whatever it already does. If it's old, I query the _User collection.

Here's the gist: https://gist.github.com/aziz92/dc5c8b3e38668361ea59 - It works great for old and new sessions.

I'm not a js programmer so if someone can please take a look and let me know if I did something wrong/weird.

**Comment by Tibabal** [comment]
@aziz92 Thanks for this suggestion, but my app already uses Revocable Sessions, so this shouldn't be the problem

**Comment by aziz92** [comment]
@Tibabal if someone of your sessions don't have r: then your app doesn't 100% use revocable sessions.

**Comment by aziz92** [comment]
@Tibabal some of my sessions have r: and some don't. I converted to Revocable Sessions later on, but not all users' sessions are converted yet.

**Comment by Tibabal** [comment]
@aziz92 I've always been using revocable sessions for that app.
The user on which I'm testing my app one should anyway been using a revocable session, since [PFUser enableRevocableSessionInBackground] is called before Parse initialization.
As documented : `enableRevocableSessionInBackground : Enables revocable sessions and migrates the currentUser session token to use revocable session if needed.`
So even if it weren't using a revocable session, it should be migrated to use one

**Comment by aziz92** [comment]
@Tibabal  I'm pretty sure if you have always been using revocable sessions, then all your sessions should start with r: , not some that do and some that don't.

`enableRevocableSessionInBackground` doesn't work for me with Parse-Server. The session is never migrated.

**Comment by Tibabal** [comment]
@aziz92 I might have found something. I'm loggin my users from cloudCode using Parse.User.logIn. Should Parse.User.enableRevocableSession() be called on cloudCode before calling this ? If so, as cloudCode doesn't use Parse.Initialize, any idea where to put it ?
Furthermore, if if that were the problem, `enableRevocableSessionInBackground ` should be working with parse-server, doesn't it @gfosco ?
