### ISSUE TITLE
Deployment Script Chef / Ansible

### ISSUE THREAD

**Issue by christianmarth** [ParsePlatform/parse-server#437]
Has anyone created a chef or ansible script for deployment and if not is there any value in me creating one for the community?

**Comment by flovilmart** [comment]
Having a recipe on supermarket.chef.io would be lovely!

Create a PR on the README.md to explain how to deploy with chef.

Having and example/blog post to deploy on AWS opsworks would be :+1:

**Comment by christianmarth** [comment]
Okay I'll get started along with a guide to deploy to Opsworks

**Comment by flovilmart** [comment]
@christianmarth Wonderful!

**Comment by gfosco** [comment]
When you've got something, email me at fjm@fb.com and we'll update the wiki with a link.  Thanks.

**Comment by turkenh** [comment]
I created this one: https://github.com/turkenh/ansible-parse
Actually I needed to migrate my game, which is in production, from Parse. 
With the help of the scripts here, I migrated it easily.
Feel free to use it, any feedbacks welcome!
