### ISSUE TITLE
issue in login activity on parse

### ISSUE THREAD

**Issue by sidkasundra** [ParsePlatform/parse-server#441]
hello,
i have been facing issue in login on parse.com site to get my application_id and client_key
but when i login with my google account then it redirect again in login page. :(
Or when i have been use login with GitHub then it directly open GitHub website. 
help me to solve this issue..

**Comment by gfosco** [comment]
Try doing a password reset?  There's an email attached even if you logged in with a linked third party.

If you have issues, please go through https://parse.com/help

Thanks
