### ISSUE TITLE
Idea: ParseException.ErrorCode.Migrated

### ISSUE THREAD

**Issue by rihadavid** [ParsePlatform/parse-server#443]
What if some of us choose some hosting solution that one day will stop its service? Maybe we could avoid the "now, update your client to point to the location of the API" step for next potential migration.

There could be ParseException.ErrorCode.Migrated error, containing the new server url in description of the error and then client app would save the new url to local database and use it for all forthcoming calls to parse server. The previous instance of server would have some "button" to turn it off and point all requests to new server with ParseException.ErrorCode.Migrated.

I think this could save a business for those of us who will choose bad provider.

It's just and idea, I am not able to implement this, but would be nice if someone could.

**Comment by natanrolnik** [comment]
In a similar idea, I wonder what would happen to our users who never update their apps and are stuck pointing to `api.parse.com` - their apps would be broken forever if they don't update it. And believe me, there are people who have 48 as badge in the App Store icon.

Wouldn't it be great if Hosted Parse could, for a specific amount of time, (say, 3-6 months after Jan./17) simply redirect the requests to our new servers, that we would configure the address in the dashboard, for example.

@gfosco @drew-gross do you think it's something possible at all?

**Comment by drew-gross** [comment]
This is something we are considering, especially for our Parse for IoT customers who have api.parse.com baked into their firmware. We are unsure if it will be available to everyone or only to customers who have a specific need.

**Comment by gfosco** [comment]
It's a cool idea, and along with various redirection strategies, we'll no doubt be considering all options.  It is however super important that developers work towards moving to their own API server several months before the sunset date.  I think it's reasonable to migrate your database by the end of April, and release a new app by the end of July.
