### ISSUE TITLE
PFUser become results in 206 in iOS SDK

### ISSUE THREAD

**Issue by edualm** [ParsePlatform/parse-server#444]
Hello,

There appears to be a problem when using PFUser.becomeInBackground(sessionToken) from an iOS app.

All writes to the user object return a "[Error]: cannot modify user <User ID> (Code: 206, Version: 1.12.0)".

Using the REST API with the session token returned by my Cloud Code works (I attempted to edit a field in the user object, and it worked).

If you are unable to reproduce this issue / need code samples, just say.

Thanks for the attention,
Eduardo Almeida

**Comment by aoguzhan** [comment]
same here. i get this error when using `[user saveInBackgroundWithBlock...`] method. And this is the full error:

```
error : {
    NSLocalizedDescription = "cannot modify user jV2QyE2Hpy";
    code = 206;
    error = "cannot modify user jV2QyE2Hpy";
    temporary = 0;
}
```

**Comment by natanrolnik** [comment]
@MegaEduX @aoguzhan  You guys may check #430 that was merged recently and may fix this issue. Try running parse-server pointing to Head instead of the latest release, and check if it solves your problem.

**Comment by MegaEduX** [comment]
@natanrolnik Downloaded latest release from GitHub, build it... The same error still happens.

**Comment by absolutlabs** [comment]
We're facing the same issue with users authenticated through -and only- Facebook : #427 .
What about you ? Did you get this error with username/password too ?

**Comment by MegaEduX** [comment]
@absolutlabs: I am using Digits, using an adapted version for parse-server of this code: https://github.com/felix-dumit/PFUser-Digits/blob/master/user.js

I never tried username/password, as I don't have it setup in my app.

**Comment by myyellowshoe** [comment]
Having a similar issue with the Javascript SDK and Parse Server on Heroku.

**Comment by myyellowshoe** [comment]
It looks like mine was related to using Parse.User.current().fetch() in the Javascript SDK.
Which works, but seems like its messing with the tokens and making me unable to post changes to server.

**Comment by MegaEduX** [comment]
Could be related.

Just tested with the latest commit, still not working.

**Comment by paulfreeman** [comment]
Getting the same error with the latest Parse iOS SDK today

**Comment by gfosco** [comment]
This may have been fixed... please update to 2.1.3 and if you're still having a problem please open a new issue and provide as much information as possible.  Thanks.
