### ISSUE TITLE
Parse GUI

### ISSUE THREAD

**Issue by happschinson** [ParsePlatform/parse-server#446]
Hi!
I got the parse server up and running nicely. Is the backend gui also available for managing my parse database somewhere?

**Comment by douineauromain** [comment]
> You can also set up an app on Parse, providing the connection string for your mongo database, and continue to use the dashboard on Parse.com.

**Comment by happschinson** [comment]
Yeah sure, thanks. 
But as far as i know, it will be closed down in 2017, so i am looking for alternatives

**Comment by douineauromain** [comment]
Right we don't know what will become the Parse Dashboard :(

The most similar tools i've found is https://www.humongous.io/

**Comment by gfosco** [comment]
See #3, the web dashboard is coming.  For now, you can continue to use parse.com if you've migrated or create a new app with your connection string.  Thanks.

**Comment by douineauromain** [comment]
Very cool thanks
