### ISSUE TITLE
Parse Server Push Issue

### ISSUE THREAD

**Issue by d8815460** [ParsePlatform/parse-server#447]
Why I got this message from Parse Server

> Can not find sender for push type ios, {"where":{"deviceType":{"$in":["ios"]}},"data":{"title":"The Shining","alert":"All work and no play makes Jack a dull boy."}}
Can not find sender for push type android, {"where":{"deviceType":{"$in":["ios"]}},"data":{"title":"The Shining","alert":"All work and no play makes Jack a dull boy."}}

**This is my Push Code:**
`curl -X POST 
     -H "X-Parse-Application-Id: EoAplzLMJaf7ZGSvpJEWvbKz0rEBlR3nKUG9pLww" 
     -H "X-Parse-Master-Key: removed" 
     -H "Content-Type: application/json" 
     -d '{ 
           "where": { 
             "deviceType": { 
               "$in": [ 
                 "ios" 
               ] 
             }
           }, 
           "data": { 
             "title": "A special discount for Giants fans", 
             "alert": "Check out our app for a 15% discount!"
           } 
         }'  http://203.77.34.135:3000/parse/push`

and i will got `{"result":true}`

**Comment by gfosco** [comment]
From looking at `ParsePushAdapter.js`, this error occurs when you don't pass in the push configuration to your ParseServer instance.  See the push wiki: https://github.com/ParsePlatform/parse-server/wiki/Push#2-configure-parse-server

**Comment by bohemima** [comment]
You might want to change your masterKey after this and make sure you don't post it again.

**Comment by d8815460** [comment]
@gfosco  I got error about `ParsePushAdapter.js`

```
/www/my-parse-app/node_modules/parse-server/lib/Adapters/Push/ParsePushAdapter.js:46
        throw _iteratorError;
        ＾
```
So, May I pass this?

And My push config is :
> push: {
	adapter: your_adapter
    android: {
      senderId: '', // The Sender ID of GCM
      apiKey: '' // The Server API Key of GCM
    },
	ios: [
      {
        pfx: 'developer.p12', // Dev PFX or P12
        bundleId: 'com.parseapp.helpbuy', 
        production: false // Dev
      }, 
      {
        pfx: 'aps.p12', // Prod PFX or P12
        bundleId: 'com.parseapp.helpbuy',  
        production: true // Prod
      }
    ]
  }

**Comment by wosheesh** [comment]
@d8815460 I had a similar problem. What worked for me was removing the android key from the push config all together:

`  push: {
  	ios: {
  		pfx: 'xxxxx.p12',
  		bundleId: 'com.xxxx.xxxx',
  		production: false
  	}
  }`

also - I don't think you need the "adapter" field.
