### ISSUE TITLE
Engines to >= 4

### ISSUE THREAD

**Issue by tolmasky** [ParsePlatform/parse-server#45]
Was taking a look at this: https://github.com/ParsePlatform/parse-server/issues/4

The reason tonic uses node 0.12 is because the engines variable isn't set in parse-server's package.json. If you set engines: { node: ">= 4" }  then Tonic will appropriately choose node 4 and the syntax error won't happen. Given that the package expects ES6 to be natively present this seems like the right engine. An alternative is to have a pre-publish step that babel-ifies the code so that it can work on any node.

Thanks,

Francisco

**Comment by gfosco** [comment]
Fixed, thanks.  This tag was in the server-example but not here.  :+1:
