### ISSUE TITLE
Parse Keys

### ISSUE THREAD

**Issue by perriera** [ParsePlatform/parse-server#458]
I am curious to know how the app Keys are generated! With Parse.com going down in a year we won't be able to create new Parse apps without the ability to create app Keys. Anyone out there with thoughts on this?

**Comment by jmk2142** [comment]
You generate your own in your configuration of the Parse Server. You can literally make your appKey 'appKey'. It doesn't matter as much now since you're hosting on your own domain and not "sharing" with anyone. Take a look at the Parse Server Example repo. Also, no need for JS keys.

**Comment by perriera** [comment]
hi jm:

I was sort of hoping that what your saying is that case. Given the
sophisticated layout of the generated hashed values, I was wondering if
Parse.com kept some sort of lookup table on the inside to verify the
generated key values. But according to you they are just randomingly
generated hex values.

If this is the case then that takes a huge load of my mind.

Thanks,

Perry


Perry Anderson

--------------------------------------------------------------

Unified Objects, Inc. <http://www.unifiedobjects.com/>

We build beautiful web and mobile apps! <http://hosting.unifiedobjects.com/>

--------------------------------------------------------------

perry@unifiedobjects.com

Tel: 844 440 7400
----------------------------------------
perry.anderson@gmail.com
Check out my professional profile and connect
with me on LinkedIn. http://lnkd.in/5TpErE
----------------------------------------

===================================
