### ISSUE TITLE
`npm start` / `npm run dev` fail with "index.js: SyntaxError: Unexpected token import"

### ISSUE THREAD

**Issue by brennen** [ParsePlatform/parse-server#462]
Seems to happen for both `npm start` and `npm run dev`, even after `npm run build`:

```
/home/brennen/parse-server/src/index.js:14
import { GridStoreAdapter } from './Adapters/Files/GridStoreAdapter';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/brennen/parse-server/bin/parse-server:3:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

I gather that this has to do with the version of `index.js` getting run here not getting transformed by Babel, but after that I'm a bit lost.  I have a couple of other [reports](https://www.digitalocean.com/community/tutorials/how-to-run-parse-server-on-ubuntu-14-04?comment=43591) of this issue, so I think it's tripping up users.

Full debug log here: [npm-debug.txt](https://github.com/ParsePlatform/parse-server/files/134650/npm-debug.txt)

**Comment by omairvaiyani** [comment]
I believe this is related to [Issue 429](https://github.com/ParsePlatform/parse-server/issues/429).

**Comment by peterdotjs** [comment]
Issue I believe is related to this commit: #399. I'm not sure why this was changed. I'll make a PR to update it.

**Comment by peterdotjs** [comment]
@brennen if you pull the latest from master you'll be good to go.

**Comment by brennen** [comment]
Thanks all!

**Comment by zhangwei001** [comment]
i solve this problem  by change  " node ./bin/www"  by  "babel-node ./bin/www" in package.json file ,of  cources npm install some babel  plugins
