### ISSUE TITLE
MongoDB questions

### ISSUE THREAD

**Issue by kenglou** [ParsePlatform/parse-server#473]
If we are using AWS to create our own MongoDB, do we need to have replication/sharding for the database? I'm quite new to MongoDB so I need some guidance. 

Besides that, is that possible that 1 MongoDB can store all the games/applications data? I have 3 games in hand and I wish to put them into the same database to save costs.

**Comment by drew-gross** [comment]
Neither replication nor sharding are mandatory, however the reliability/performance of your system can increase if you use them.

It is possible to have multiple databases on a single MongoDB installation, yes. The database name is the last part of the mongo URL, you just need to change that.
