### ISSUE TITLE
When I deploy Parse server to AWS Elastic Beanstalk.

### ISSUE THREAD

**Issue by otto1020** [ParsePlatform/parse-server#481]
@json-park 
I was set up Parse Server on AWS Elastic Beanstalk.

But I had some issues.

Please read this comment carefully.

1. click "Deploy to AWS" on http://mobile.awsblog.com/post/TxCD57GZLM2JR/How-to-set-up-Parse-Server-on-AWS-using-AWS-Elastic-Beanstalk
2. select "node.js"
3. select "Upload your own code (advanced configuration)"
4. upload zip file
![untitled copy](https://cloud.githubusercontent.com/assets/16714648/13147152/69753030-d658-11e5-9369-2629dc5b9a02.png)
5. click "configure details"
6. click "create app"
![untitled copy](https://cloud.githubusercontent.com/assets/16714648/13147314/02adb6c8-d659-11e5-9ba7-6ac8399ee47d.png)
7. waiting
8. set Configuration(APP_ID, MASTER_KEY ...)
![untitled copy](https://cloud.githubusercontent.com/assets/16714648/13148512/00130224-d65e-11e5-9c82-4c0398486387.png)
9. click "apply"
10. when I go to server URL, That says "502 Bad Gateway nginx/1.8.0"
![untitled copy](https://cloud.githubusercontent.com/assets/16714648/13148842/43d5bc58-d65f-11e5-9af2-5e2adb2fba7a.png)
![untitled copy](https://cloud.githubusercontent.com/assets/16714648/13148901/7c9caa6a-d65f-11e5-8738-cbfb667f827f.png)

So I can't test parse-server on my app.

index.js is following:

var api = new ParseServer({

   databaseURI: databaseUri || 'mongodb://...',
   cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
   appId: process.env.APP_ID || '5...h',
   masterKey: process.env.MASTER_KEY || 'd...5',
   fileKey: process.env.FILE_KEY || '3...5'

});

I add my cloud code in main.js.

Now, what can I do? or what should I do?

Please help me.

Thanks,

**Comment by drew-gross** [comment]
Visiting the server URL is not expected to work as the browser won't include the app ID or any keys. Have you tried using one of our SDKs?

**Comment by otto1020** [comment]
Yes.

I am using the latest SDK.

**Comment by otto1020** [comment]
Then, On mobile app(iOS), what is the value of configuration.server?

[Parse initializeWithConfiguration:[ParseClientConfiguration configurationWithBlock:^(id<ParseMutableClientConfiguration> configuration) {

        configuration.applicationId = @"";
        configuration.clientKey = @"";
        configuration.server = //what is the value
    }]];

**Comment by drew-gross** [comment]
That should be the URL of your Parse Server on AWS

**Comment by otto1020** [comment]
I tested with REST API.
I got the result as following

<html>
    <head>
        <title>502 Bad Gateway</title>
    </head>
    <body bgcolor="white">
        <center>
            <h1>502 Bad Gateway</h1>
        </center>
        <hr>
        <center>nginx/1.8.0</center>

    </body>

</html>

**Comment by drew-gross** [comment]
This seems like it might be an AWS specific issue, I don't think your request is even making it to the Parse Server. Are you sure the Parse Server is turned on and running?

**Comment by otto1020** [comment]
My parse server works fine on my mac.

**Comment by otto1020** [comment]
where is the URL of my Parse Server on AWS?

**Comment by drew-gross** [comment]
If it's working on your mac but not on AWS then it's definitely an AWS specific issue. Your URL is going to depend on your AWS configuration.
