### ISSUE TITLE
Parse.Cloud.useMasterKey whit sessionToken

### ISSUE THREAD

**Issue by flessard** [ParsePlatform/parse-server#487]
In cloud function, if you set Parse.Cloud.useMasterKey() at the begin of your code and at the end of your code you call a other cloud function but you want to run this whit a user session, you need to pass the sessionToken.

```
Parse.Cloud.useMasterKey();

...

return Parse.Cloud.run('getUserRole', data, {
     sessionToken: request.user.getSessionToken()
});
```
Because you have set Parse.Cloud.useMasterKey at the begin of your code, your cloud function you try to run whit user session will run as master.

Why sessionToken does not override the masterKey if present ?

**Comment by gfosco** [comment]
On hosted Parse?  In parse-server, or node in general, Parse.Cloud.useMasterKey is not available... You must pass the sessionToken:token or useMasterKey:true options to the save/query/run calls.

**Comment by flessard** [comment]
In  parse-server. 

In this example, the function getUserRole is run as master even if you pass a sessionToken because useMasterKey is set whit Parse.Cloud.useMasterKey()

In my opinion, if the sessionToken is present, the masterKey will not use.

```
Parse.Cloud.define("setUserRole", function(request, response) {

   Parse.Cloud.useMasterKey();

   ...
   
   return Parse.Cloud.run('getUserRole', data, {
        sessionToken: request.user.getSessionToken()
   });

   ...

});

Parse.Cloud.define("getUserRole", function(request, response) {
   // request.master == true 
  // request.user == undefined, is not supposed to be undefined because sessionToken is passed.
   
})
```
