### ISSUE TITLE
In-App Purchases

### ISSUE THREAD

**Issue by Neilfau** [ParsePlatform/parse-server#488]
Any plans to add In-App Purchases to Parse Server?

**Comment by gfosco** [comment]
No plans to add receipt validation to parse-server from our end, but, totally open to it being added as a community feature.

**Comment by flovilmart** [comment]
@gfosco was there validation before on Parse? That would need to be added into the iOS SDK in that case for convenience don't you think?

**Comment by gfosco** [comment]
Follow on in #134.
