### ISSUE TITLE
Push not sending to ios 

### ISSUE THREAD

**Issue by WEBTEAMKTVU** [ParsePlatform/parse-server#489]
Hi all, 

Our Parses changed two days ago to only send to our Android users. Anyone else experience this? Any idea on a fix - or does anyone have a contact to someone with Parse?

**Comment by rosarioconti** [comment]
What do you mean by 'parses'  , did u mean pushes ?

**Comment by WEBTEAMKTVU** [comment]
Yes - pushes on the Parse platform

**Comment by gfosco** [comment]
Are you talking about hosted Parse.com, or parse-server?

**Comment by WEBTEAMKTVU** [comment]
Parse.com

**Comment by gfosco** [comment]
Please report any issues with hosted parse through https://parse.com/help  find the bug icon.  Thanks.

**Comment by WEBTEAMKTVU** [comment]
I tried that but it says the link is broken

**Comment by gfosco** [comment]
Sorry I guess that one isn't https...   http://parse.com/help

**Comment by WEBTEAMKTVU** [comment]
When I try either - and click on contact us by the bug - I get this error
![broken_link](https://cloud.githubusercontent.com/assets/17323226/13161786/dfe4213a-d654-11e5-850f-bc7ea267d7b5.JPG)
