### ISSUE TITLE
Have a problem using Local Datastore in Android after parse server migration

### ISSUE THREAD

**Issue by slickker** [ParsePlatform/parse-server#490]
I request this issue to parse.com/help.
They said you might report this issue to here.

I try migration to my local parse server.
I succeeded development local parse server.
And my android application connect to this server successfully.

But to use Local Datastore has problem.
I'm using local datastore.
This is my code.

- MyApplication.java
        Parse.enableLocalDatastore(this);

- userProfileDao.java
        try {
            ParseQuery<ParseObject> query = ParseQuery.getQuery(PARSE_OBJECT);
            query.fromLocalDatastore();
            mParseObject = query.getFirst();
        } catch (ParseException e) {
            mParseObject = new ParseObject(PARSE_OBJECT);
        }

In userProfileDao.java,
query.fromLocalDatastore(); <- ERROR.... Caused by: java.lang.IllegalStateException: Method requires Local Datastore. Please refer to `Parse#enableLocalDatastore(Context)`.

Before migration, this is no problem.
Currently, I used Parse SDK version 1.13 and Parse server version 2.1.
Please to solve this problem.

Thanks.

**Comment by drew-gross** [comment]
cc @grantland

**Comment by shevkorn** [comment]
I'm having the same problem, I'm unable to work with local database.

**Comment by arxidon** [comment]
You need to enable the local datastore inside your initialization command, not before like it used to be.

`Parse.initialize(new Parse.Configuration.Builder(this)
                        .applicationId("yourappid")
                        .clientKey("yourclientkey")
                        .server("serverurl")
                        .enableLocalDataStore()
                        .build()
        );`

**Comment by shevkorn** [comment]
thank you, it works. Very appreciated.

**Comment by WanClem** [comment]
Thank you..It worked

**Comment by rakeshmjiyani** [comment]
Work like charm!!

**Comment by umng** [comment]
it works. Thanks

**Comment by SUMIT5321** [comment]
Thanks, its working

**Comment by breidest-tbs** [comment]
Oh well it is the end of 2020 and I had the same issue.
Can someone please update the Android guidelines 
http://docs.parseplatform.org/android/guide/#local-datastore

**Comment by mtrezza** [comment]
Thanks for the reminder @breidest-tbs.

Would you want to open an issue in the [docs repo](https://github.com/parse-community/docs/issues)?
If you want to go even further, we would gladly review your PR for the docs change.
