### ISSUE TITLE
MongoRocks Server Requirement

### ISSUE THREAD

**Issue by kenglou** [ParsePlatform/parse-server#495]
as i read in the wiki on Parse MongoDB is running on MongoRocks. If I want to configure a database for MongoRocks it is recommended to built it in a i2.2xlarge instance with replication. Is that possible that i run configure mongoRocks in hardware lower than the spec of i2.2xlarge but is also IO Optimized Hardware? for example i2.xlarge instance? Or is it possible to use some other general purpose instance to be the instance of the database?

**Comment by drew-gross** [comment]
You can run MongoRocks on lower classes of hardware, certainly. Our recommendation is for achieving higher reliability and performance, but of course is also more expensive.

**Comment by kenglou** [comment]
Is it possible that if we are using some C4.large instance for running MongoRocks?
