### ISSUE TITLE
server-side login

### ISSUE THREAD

**Issue by mchun** [ParsePlatform/parse-server#497]
My app was relying on 'parse-express-cookie-session' offered by Parse to do server-side login, i.e.:

```
  app.post('/login', function(req, res) {
    Parse.User.logIn(req.body.username, req.body.password).then(function(user) {
      res.redirect('/');
    }, function(error) {
      res.render('login', { flash: error.message });
    });
  });

  app.post('/logout', function(req, res) {
    Parse.User.logOut();
    res.redirect('/');
  });
```

I used Parse.User.Current() to check if the user is logged in on server-side.

Now, I replaced the 'parse-express-cookie-session' by 'express-session'. And do the login/logout in this way:

```
  app.post('/login', function(req, res) {
    Parse.User.logIn(req.body.username, req.body.password).then(function(user) {
      req.session.user=user;
      res.redirect('/');
    }, function(error) {
      res.render('login', { flash: error.message });
    });
  });

  app.post('/logout', function(req, res) {
    req.session.user = null;
    res.redirect('/');
  });
```

I then see if the user is logged in by checking req.session.user = null . But I cannot access it inside cloudcode.
Perhaps this is not a right way to do(?) as it is recommended to use req.user, but I have no idea how to make it work, req.user is always null. Any help from you guys? 
It would be great to even have a small sample app offered by Parse showing simple server-side login like Anyimg as there should be similar cases around like me.

**Comment by mchun** [comment]
or server-side login is no longer possible?

**Comment by simonbengtsson** [comment]
What I did was to manually add the features of the `parse-express-cookie-session`. Below is one way of doing it. I probably will change some things such as using `Parse.Cloud.httpRequest` instead of `Parse._request` and using secure cookies before going into production however. An even better way would be to use `jwt` so that you don't have to fetch the user on each page load. Would love to see some implementation with that.

    // Login adds the sessionToken in a cookie
    app.post('/login', function(req, res) {
        Parse.User.logIn(req.body.username, req.body.password).then(function(user) {
            var val = JSON.stringify({sessionToken: user.getSessionToken()});
            var opts = {path: '/', httpOnly: true};
            res.cookie('parse.session', val, opts);
            res.redirect('/');
        }).then(null, function(error) {
            res.clearCookie('parse.session');
            res.render('pages/login', { flash: error.message });
        });
    });

    // Middleware adding current user to `req.user` or redirecting to login if not logged in
    app.use(function (req, res, next) {
        new Parse.Promise.as().then(function() {
            var cookie = JSON.parse(req.cookies['parse.session']);
            return Parse._request('GET', 'users/me', {}, {sessionToken: cookie.sessionToken});
        }).then(function (userData) {
            var query = new Parse.Query('User');
            return query.get(userData.objectId, {useMasterKey: true});
        }).then(function (user) {
            req.user = user;
            next();
        }, function () {
            res.clearCookie('parse.session');
            return res.redirect('/login');
        });
    });

**Comment by mchun** [comment]
I see how you reconstruct the res.user, but in that case, the request.user still seems to be null in cloudcode afterSave trigger function. 

```
Parse.Cloud.afterSave("Comment", function(request) {
   ...
};
```

I can get the userid by using request.object.get('createdBy').objectId inside the trigger function, but I guess its better to stick with request.user as these functions are shared across different clients.

**Comment by simonbengtsson** [comment]
That is a separate issue as parse server is supposed to set the user in that case. I tried it now and it worked. Anyhow, try updating to 2.1.1 as some related fixes was applied in #373. Also make sure you are not making the request with a master key and that you are using a valid session token. You won't get any warnings/errors if the session token is invalid.

**Comment by mchun** [comment]
I tried your code and created a post request using $.post with request cookie : `parse.session=%7B%22sessionToken%22%3A%22r%3A9f8ff4a551392d021759e81c58a3a8f8%22%7D`

But the request.user is still undefined in aftersave trigger function. *I'm already using 2.1.1 parse-server
```
{ triggerName: 'afterSave',
  object: ParseObjectSubclass { className: 'Comment', _objCount: 152, id: 'sSGLWMDJRe' },
  master: false }
```

**Comment by simonbengtsson** [comment]
The code I posted above is a way to replace the `parse-express-cookie-session` middleware and will only work with your server side code, i.e. your expressjs routes. 

For your cloud code (cloud functions, afterSave, beforeSave etc) you need to make the request with the header `X-Parse-Session-Token` to get the `req.user` object. When you said $.post I assume you are using jQuery with the rest api? Is it a reason you are not using the parse js sdk? Anyway, using jQuery with the rest api would look something like this:

```js
$.post({
    url: 'http://localhost:1337/parse/classes/Comment',
    data: JSON.stringify({text: "New comment"}),
    headers: {
        'X-Parse-Application-Id': 'appId',
        'X-Parse-Session-Token': 'r:2bc226c69d8f23b6c4ed906d79a129d3',
        'Content-Type': 'application/json'
    }
});
```

and with the parse js sdk:

```js
var comment = new Parse.Object('Comment');
comment.set('text', 'New comment');
comment.save(null, {sessionToken: "r:2bc226c69d8f23b6c4ed906d79a129d3");
```

**Comment by mchun** [comment]
Hi Simon, thanks very much for your help. Yes, I am using jQuery on client side to minimize the dependency upon Parse JS SDK, but I am not using the rest api directly, i.e.

```
app.post('/c', requireUser, function(req, res){
  var comment = new Comment();
  comment.set("comment",req.body.comment);
  var post = new Post();
  post.id = req.body.postID;
  comment.set("post",post);
  comment.set("createdBy",req.user);
  comment.save(**null,{sessionToken:req.user.sessionToken}**).then(function(comment){
    res.json({comment:comment, parseUser: req.user});
  }, function(error){
    console.log(error);
    res.json({error:error})
  });
});
```

I have just added `null,{sessionToken:req.user.sessionToken}` inside comment.save as above. It is now able to detect req.user inside trigger functions! Thanks to your answer!

**Comment by simonbengtsson** [comment]
Glad to hear you solved it. What do you think of changing the title of this issue to Server-side login (replacing parse-express-cookie-session)? You should probably also close the issue.

**Comment by drew-gross** [comment]
Thanks for helping @simonbengtsson!

**Comment by mchun** [comment]
But what's the problem of using Parse._request instead of Parse.Cloud.httpRequest? And is there any documentation for Parse._request function?

**Comment by simonbengtsson** [comment]
Parse._request is not documented and might potensially be removed in a futute update to the sdk. Post here if you manage to do it, otherwise I will translate it at some point and update the answer.

**Comment by mchun** [comment]
Seems Parse.Cloud.httpRequest can only be executed inside cloudcode?
Otherwise, it always returns 
`[TypeError: Cannot read property 'statusCode' of undefined]`
I also tried Parse.User.become(sessionToken) but with no success.

**Comment by simonbengtsson** [comment]
`Parse.Cloud.httpRequest` should be available everywhere. What code are you using? `Parse.User.become()` is disabled for nodejs environments.

**Comment by mchun** [comment]
Yup, it can be used everywhere.
Figured out the code, need to use full path inside Parse.Cloud.httpRequest, appid and restapikey are also required.
Middleware cookie-session is used to secure the cookie. I guess it should be good for production usage?

```
var cookieSession = require('cookie-session');

app.use(cookieSession({
  name: COOKIE_NAME,
  secret: "SECRET_SIGNING_KEY",
  maxAge: 15724800000
}));

app.use(function (req, res, next) {
    Parse.Cloud.httpRequest({
      url: 'http://localhost:1337/parse/users/me',
      headers: {
        'X-Parse-Application-Id': 'myAppId',
        'X-Parse-REST-API-Key': 'myRestAPIKey',
        'X-Parse-Session-Token': req.session.token
      }
    }).then(function (userData) {
        req.user = Parse.Object.fromJSON(userData.data);
        next();
    }).then(null, function () {
        return res.redirect('/login');
    });
});
```


In login / logout part:
```
  app.post('/login', function(req, res) {
    Parse.User.logIn(req.body.username, req.body.password).then(function(user) {
      req.session.user = user;
      req.session.token = user.getSessionToken();
      res.redirect('/');
    }, function(error) {
      req.session = null;
      res.render('login', { flash: error.message });
    });
  });

  app.post('/logout', function(req, res) {
    req.session = null;
    res.redirect('/');
  });
```

**Comment by lususvir** [comment]
Might be a dumb question, but what is the "name" and "secret"? Do I just make those up? @mchun

**Comment by mchun** [comment]
Name is the name of your cookie.
Secret is the signing key. You may refer to the documentation here.
https://www.npmjs.com/package/cookie-session
And yes, they can be any string.

**Comment by woodardj** [comment]
So just to be totally clear, since I feel like we've covered a few things in this thread… @mchun, your most recent code (https://github.com/ParsePlatform/parse-server/issues/497#issuecomment-190107848) is what you're using for login/session management on the express side of your app?

**Comment by mchun** [comment]
@woodardj , yes. That's my production code. But beware that I am still using parse-server 2.1.6 though I guess there's not much changed.

**Comment by woodardj** [comment]
Thanks @mchun! I ended up piecing the methodology into an authenticating middleware we already had, but this was super useful as a starting point. I am curious though, we had good luck querying `_Session` with the JS/Express SDK directly instead of going to the REST endpoint, is there a reason you went that route?

**Comment by tillifywebb** [comment]
@mchun I have a browser JS app. And an express server running parse on nodechef. I want to be able to sign the user in through the express route, and then ensure they are logged in with a session on the client. RIght now the client does the login. Your code you posted seems to do this? Can you offer any help. In the final code you post are you still using express session module? How are you then logging in the client, do you parse the session token down. Been looking everywhere for help code on this but can onlt find parts, parse session cookie module looks un-supported and can't find the docs. Would really appreciate some help. Thanks

**Comment by lususvir** [comment]
@mchun like @tillifywebb I am also still confused. It would be awesome to see more of your code.

**Comment by manishsangwan** [comment]
I am using `_request() `to fetch user object `Parse.Cloud.httpRequest` return 403. can you please update the answer.

**Comment by lkraider** [comment]
Can we have this in the parse server code?
