### ISSUE TITLE
Deploy multiple Parse-server-example instances on Heroku/AWS?

### ISSUE THREAD

**Issue by grassland-curing-cfa** [ParsePlatform/parse-server#499]
As I have currently multiple Parse applications/databases hosted on Parse.com under my Parse account, will I need to migrate each of them to individual applications on Heroku/AWS, each connected with a MangoDB database? If that is the case, does it mean that I will have to deploy multiple "Parse-server-example" instances to Heroku/AWS?

**Comment by drew-gross** [comment]
That is the default method, yes, but you can also run multiple instances of the Parse Server on the same hardware, but, different ports or different subdomains. If you are willing to run a custom version of the parse server you can also check out #263 by @flovilmart which adds support for multiple apps. That is also where we are discussing how we might potentially officially support multiple apps per server in the future.
