### ISSUE TITLE
Add server logging

### ISSUE THREAD

**Issue by francocorreasosa** [ParsePlatform/parse-server#50]
What about creating .log files? This is needed to understand if the requests are reaching the server, returning 200, etc...

**Comment by gfosco** [comment]
Hoping that #18 will lead to a nice abstracted log adapter and this can be an extension of that.

**Comment by ehfeng** [comment]
Are you thinking of moving to something like winston for this?

**Comment by peterdotjs** [comment]
Once I land #243 basic info and error logging will be supported.
