### ISSUE TITLE
iOS does't receive Push notification from Cloud code

### ISSUE THREAD

**Issue by kjisoo** [ParsePlatform/parse-server#502]
When i send push in cloud code, iOS does't receive push but android very well.
also REST API is working both iOS and Android.

My cloudcode
```
var query = new Parse.Query(Parse.Installation);
  Parse.Push.send({
    where: query,
    data: {
      alert: "Answer",
      sound: "default"
    }
  }, {
    success: function(){
    }, error: function(error){
    }, useMasterKey: true
  });
````

**Comment by kjisoo** [comment]
If set SERVER_RUL in CoreManager.js, It works

**Comment by KudosGuy** [comment]
@kjisoo @drew-gross how did you resolve this issue, I have the same problem, CURL works but cloud code not...

**Comment by kjisoo** [comment]
@KudosGuy Did you define ServerURL? I missed it

**Comment by KudosGuy** [comment]
@kjisoo yeah I did, I guess I just keep digging...

**Comment by otymartin** [comment]
Any answers here?

A lot of us can't get push notifications to work in cloud code.
