### ISSUE TITLE
Query retrieves objects with empty ACL without master key

### ISSUE THREAD

**Issue by xaratt** [ParsePlatform/parse-server#504]
Objects with empty or non-existing ACL presents in ParseQuery::find results.

For example look at this [test](https://github.com/ParsePlatform/parse-php-sdk/blob/master/tests/Parse/ParseQueryTest.php#L2017)
```php
        $obj = ParseObject::create('TestObject');
        $restrictedACL = new ParseACL();
        $obj->setACL($restrictedACL);
        $obj->save();
        $query = new ParseQuery('TestObject');
        $count = $query->count();
```
$count will be 1 after running code with local parse-server and 0 - with api.parse.com.

I mean that problem is [here](https://github.com/ParsePlatform/parse-server/blob/master/src/ExportAdapter.js#L555): this request transforms to mongo query
```js
{'$and': [
    {},
    {'$or': [ 
        {"_rperm" : { "$exists": false }},
        {"_rperm" : { "$in" : ["*"]}}
    ]}
]};
```
which just returns all documents without _rperm field and doesn't care about ACL field.

**Comment by paulfreeman** [comment]
Where are ACL's stored in parse-server?  I can't this in the mongo database I have migrated. 

I am having authorisation errors in cloud code since migrating and assumed it was ACL's but can't figure this out as I can't find out how to add/maintain/remove ACL's in parse-server

**Comment by paulfreeman** [comment]
It does not appear that the ACL field was migrated by the Parse migration process when setting up my test Mongo server. 

Having detected this I am now aware that several other fields appear to be missing from the migrated data.

**Comment by xaratt** [comment]
After few experiments with data export from Parse.com Dashboard I see that records with ACL column "Master key only" would be exported as mongo documents with field "ACL": {}. Records with "Public Read + Write" has no ACL field at all.

I think we need to add backwards compatibility in function transform.js/transformCreate for storing objects:
```js
if (JSON.stringify(restCreate["ACL"]) == "{}") {
    mongoCreate["ACL"] = {};
}
```
and in function ExportAdapter.js/find for retrieving:
```js
if (!isMaster) {
    ...
    var emptyACLCondition = {"ACL" : { "$ne" : {} }};
    mongoWhere = {'$and': [emptyACLCondition, mongoWhere, {'$or': orParts}]};
}
```

**Comment by gfosco** [comment]
Good catch... I have submitted #586 to correct the behavior of ACLs, it will be in 2.1.3.
