### ISSUE TITLE
Local Parse Server throwing 'unauthorised' 403 despite correct keys

### ISSUE THREAD

**Issue by ryderjack** [ParsePlatform/parse-server#508]
I'm setting my keys as described yet still getting 'Unauthorised'. Any ideas why this is?

Here's the snippet where I create the server var:

```
var express = require('express');
var ParseServer = require('parse-server').ParseServer;

var app = express();

var port = process.env.PORT || 1337;

// Specify the connection string for your mongodb database
// and the location to your Parse cloud code
var api = new ParseServer({
  databaseURI: 'mongodb://localhost:27017',
  cloud: '/Users/jack/Desktop/dev/node_modules/parse-server/lib/cloud/main.js', // Provide an absolute path
  appId: 'jack1234',
  masterKey: 'jack1234',
  serverURL: 'http://localhost:' + port + '/parse'
});

// Serve the Parse API on the /parse URL prefix
app.use('/parse', api);

// Hello world
app.get('/', function(req, res) {
  res.status(200).send('Express is running here.');
});

app.listen(port, function() {
  console.log('parse-server-example running on port ' + port + '.');
});
```

Here's a screenshot of the 'Unauthorised' with the headers:

![image](https://cloud.githubusercontent.com/assets/10326229/13179346/6b02dd44-d71b-11e5-8d0c-88078a71c0b1.png)

**Comment by merowinger92** [comment]
Have you tried it without ' ? just jack1234 as keys?

**Comment by ryderjack** [comment]
@merowinger92 I get- "Cannot GET /parse"

**Comment by gfosco** [comment]
`/parse` isn't a route.  `/parse/classes/TestObject` would be a route you can test...

**Comment by ryderjack** [comment]
@gfosco how would you suggest adding an class & object to test?

**Comment by gfosco** [comment]
It happens automatically if you save an object with an sdk or with the rest API, and you can just query against the url even if it doesn't exist.

**Comment by ryderjack** [comment]
``localhost:1337/parse/classes/testObject`` returns ``{"error":"unauthorized"}`` despite the headers being set as per the screenshot above

**Comment by ofirattia** [comment]
I am getting the same message and dont know why.  if not error:unauthorized , I get cannot POST ... or cannot GET, there is something else we need to do ? 
for what this line? cloud: 'parse-server/src/cloud/main.js', // Provide an absolute path

**Comment by ryderjack** [comment]
I uninstalled and starting from the top with the Parse-Sever-example repo https://github.com/ParsePlatform/parse-server-example It must have been a set up issue
