### ISSUE TITLE
Cant migrate my app .it shows estimated time 4 months,my database is too small while i transfer from parse to mongodb running in cloud in digital ocean linux ubuntu droplet

### ISSUE THREAD

**Issue by syampsijk** [ParsePlatform/parse-server#509]
I was trying to migrate database from parse to my mongodb in digital ocean ubuntu droplet without ssh key like mongodb://my ip addres:27017/      .parse warned me about ssh key unsecure and latency is high and which would result in low speed.

the connection was established,and it showed my rows and data migrated but it is stuck at that page and says estimated time 4 months.i believe there is no more data to transfer.I waited for more than 3 hours,also when i cancelled the data isnt migrated to my droplet.Sometimes finalise option comes but cant commit the migration.please help me.
below is screenshot

![migration](https://cloud.githubusercontent.com/assets/14886015/13180931/0e77ad2e-d744-11e5-8040-112d2bd010af.png)
![error](https://cloud.githubusercontent.com/assets/14886015/13180930/0e740e08-d744-11e5-979f-a7101be9e451.png)

**Comment by drew-gross** [comment]
For issues with the migration process please report bugs at parse.com/help

**Comment by syampsijk** [comment]
i have reported in bugs and did see a lot of people complaining about same issue,but i felt like they still have this issue.
