### ISSUE TITLE
Parse S3 VS Amazon S3

### ISSUE THREAD

**Issue by otto1020** [ParsePlatform/parse-server#511]
Is there how to migrate Parse S3 to Amazon S3?

////////////////////////
I am working with Parse Server to release new version of my app.
I am worry about original images.(ex: photos of users, images of chatting history)

Then, Do I need to move them to Amazon S3? or do not I have to do so?

Please help me.

Thanks

**Comment by drew-gross** [comment]
We will have some updated on how to do this sood. Follow [our blog](http://parse.com/blog) to get updates.
