### ISSUE TITLE
webhook migration instruction

### ISSUE THREAD

**Issue by loftyet** [ParsePlatform/parse-server#52]
Do we have any webhook migration instruction? 
based on this example app: https://github.com/ParsePlatform/CloudCode-Express
should I just change the 'https://api.parse.com/1/hooks/triggers' to my heroku app url + /hooks/triggers?

Thanks,

**Comment by gfosco** [comment]
Webhooks isn't supported coming from api.parse.com, but cloud code is supported for writing triggers/functions directly through parse-server.  What was the context in which you wanted to run parse-server and also webhooks?

**Comment by ITpakar** [comment]
@gfosco I have the same issue. Can you tell me how I can write triggers and functions directly through parse-server.

**Comment by DeDuckProject** [comment]
Here's a workaround:
https://github.com/ParsePlatform/parse-server/issues/234
