### ISSUE TITLE
Create Apps Locally

### ISSUE THREAD

**Issue by ofirattia** [ParsePlatform/parse-server#522]
There is option to create app locally instead of migrate apps?
OR the only way is to replicate template of new app and push data ?

Thanks

**Comment by gfosco** [comment]
You can create a new app, absolutely.  Just create your own app Id and master Key, and point it at an empty mongo database. :smile:

**Comment by ofirattia** [comment]
There is rules to create the master key and appId? what about the generation of all API`s Keys?

**Comment by gfosco** [comment]
No rules really, and you don't need to use client keys (rest api key, js key, client key, dot net key) with parse-server.  You can use any string as an appId, even something like 'myApp', and consider the master key a very secure password.
