### ISSUE TITLE
Cannot fetch any data from Cloud Code

### ISSUE THREAD

**Issue by Tux1** [ParsePlatform/parse-server#525]
Hi All,

I use the lastest version 2.1.2. 
I try this simple query :
```
Parse.Cloud.define('toto', function(req, res){
	var query = new Parse.Query('GameScore');
	query.get('2zMIWMFzNd').then(function(bar){
		res.success(bar);
	}, function(err){
		res.error(err);
	});
});
```

And I get this error:

> Received an error with invalid JSON from Parse: Cannot POST /classes/GameScore\n

Obviously, the `id` exists and the inner code works well in non-cloud code environment
Is it a bug ? I have not correctly set up something ?

Thanks

**Comment by gfosco** [comment]
Based on the url it is returning, it sounds like you've set the serverURL property incorrectly to not include the /parse mount point.  It should be /parse/classes/GameScore.

**Comment by thamer898** [comment]
@gfosco Hello

How to allow user to reset password using new parse server ?

Regards

**Comment by Tux1** [comment]
What's a prat i am... You're right. I have forgot '/parse' at the end of my serverURL...
