### ISSUE TITLE
AWS for Parse server and PHP Web App

### ISSUE THREAD

**Issue by eatentree** [ParsePlatform/parse-server#526]
Hi, 

Can I use AWS Elastic Beanstalk which I have setup for Parse server for my php based web application? Essentially what I want is to host php files in root folder and parse server api on {root}/parse?

**Comment by gfosco** [comment]
If you're using **nginx**, you can likely route the root path to your php app, and the /parse path to your ParseServer instance... It would be easier to just keep them separate though, if you're not already experienced with that type of setup.

**Comment by eatentree** [comment]
Thanks. I have created 2 separate instance for web and parse server.
