### ISSUE TITLE
reset user Password

### ISSUE THREAD

**Issue by thamer898** [ParsePlatform/parse-server#527]
Hello

How to allow user to reset his password using New Parse server ?

Regards

**Comment by gfosco** [comment]
It's not implemented yet, the way it worked on Parse with an email and a link.  The mail adapter design is being discussed in #275 and there are several variations being worked on in pull requests ( #187, #191, #250 ).  As soon as it's available we'll announce and blog post, etc.

**Comment by btate** [comment]
Is there any idea of a timeline on this one?  I think this is the last missing piece for us to migrate production.

**Comment by thamer898** [comment]
I agree with you @btate this is important feature should implemented .

**Comment by mahabubakram** [comment]
Are we able now to reset password of the user ?
As currently I am using mandrill for email. So actually I need the way to send reset verification link to the user and perform reset password of that user.

Please let us know the current progress.

**Comment by btate** [comment]
I've been able to get password reset working according to #627.  I think mailgun is the only adapter currently though.

**Comment by thamer898** [comment]
Hello

@btate can you describe the method that you use it to allow user reset password ?

Regards

**Comment by btate** [comment]
The ticket #627 has the configuration details.   You'll need a mailgun account setup.

**Comment by thamer898** [comment]
Hello

okay @btate i have a mailgun account but i need the instructions ?

Regards

**Comment by btate** [comment]
They are all outlined on that ticket.

**Comment by mahabubakram** [comment]
I have not used it but @thamer898 you can follow tanmays instruction.

Here's a short doc in case anyone else wants to try out password reset with mailgun:

In index.js (the paths mentioned below are in reference when using the parse-server-example app, change them to appropriate values when using standalone parse-server)

var SimpleMailgunAdapter = require('parse-server/lib/Adapters/Email/SimpleMailgunAdapter');

var api = new ParseServer({
   databaseURI: 'xxx',
   cloud: 'xxx',
   appId: 'xx',
   appName: 'Your app name here',
   masterKey: 'xxx',
   serverURL: 'xxx',
   publicServerURL: '<same as serverURL>',
   emailAdapter: SimpleMailgunAdapter({
      apiKey: 'key-xxx',
      domain: 'xxx.com',
      fromAddress: 'support@xxx.com',
   }),
   customPages: {
    invalidLink: 'http://yourdomain.com/invalid_link.html',
    verifyEmailSuccess: 'http://yourdomain.com/verify_email_success.html',
    choosePassword: 'http://yourdomain.com/choose_password.html',
    passwordResetSuccess: 'http://yourdomain.com/password_reset_success.html'
  }
});
Using customPages is optional if you want to provide your own hosted pages.

The choose_password file is located in the parse-server/views folder. You need to make 2 changes before uploading it to your web server:

Make sure to add a .html extension to choose_password.
Open choose_password and replace the SERVER_URL with a valid absolute url, this would be same as the serverURL you set in index.js.

And read that thread thoroughly. Though I am waiting for the production of this feature as I am using mandrill now so I need generic provider. Not the mailgun one.

**Comment by thamer898** [comment]
Hello

Thank you @mahabubakram i will try this feature .

Regards

**Comment by Battleaxe19** [comment]
@mahabubakram 

I've followed your process but i'm still running into problems. When I submit my form, I get this error: Trying to send a reset password but no adapter is set.

I've followed instructions on some other threads and installed:
"parse-server-simple-mailgun-adapter": "^1.0.0" 

In app.json I've got this:

"emailAdapter": {
      "module": "parse-server-simple-mailgun-adapter",
      "options": {
        "fromAddress": "parse@example.com",
        "domain": "sandbox81f9087fe60b4abdb7fe21aa37180c9a.mailgun.org",
        "apiKey": "key-3b37bc75295c7a9dfc57479cc1946784"
      }
    }

I'm still getting the error and i'm at a loss of what to try next.
Any ideas would be much appreciated!

Thanks!

**Comment by fherx** [comment]
mailgun is a really bad solutions for password reset if you don't create a pay account, if you are a free user you only can send emails to specific recipients, in other words you need to add manually the emails

**Comment by crislucan** [comment]
Works as per picture below:
![parse_forget_password](https://user-images.githubusercontent.com/830687/28207251-a3d0446e-6891-11e7-9581-ad71f039c51e.png)

**Comment by crislucan** [comment]
<img width="948" alt="image" src="https://user-images.githubusercontent.com/830687/28207282-d3334dbe-6891-11e7-82df-0193eba388bd.png">
