### ISSUE TITLE
Parse server Dashboard

### ISSUE THREAD

**Issue by thamer898** [ParsePlatform/parse-server#528]
Hello

When Parse server will support Admin Dashboard ?

Regards

**Comment by flovilmart** [comment]
@thamer898 see #3 it's in progress and likely to be in a separate repository!

**Comment by thamer898** [comment]
@flovilmart thank you very much but do you now any encryption method for parse server to encrypt files and any folers ?

**Comment by flovilmart** [comment]
What do you mean by that? I don't believe it's in the plans. you can use the beforeSave hooks to encrypt the data you're storing, but you won't be able to execute queries on the values then.
