### ISSUE TITLE
Not able to retrieve the images as uplaoded

### ISSUE THREAD

**Issue by zrehan** [ParsePlatform/parse-server#529]
When using the **files** endpoints to upload the images ,it is successful. But when retrieving it from the link it is not displaying a picture ,it shows a small square with white borders. does anyone know what th issue might me?

**Comment by gfosco** [comment]
What client are you using to upload, and to retrieve?.. what filename (did you provide an extension?)

**Comment by zrehan** [comment]
I am trying it locally on my system and this is my POST request `http://i.stack.imgur.com/XUIkd.jpg`  . and this is the output when I try to retrieve it using the url the POST created `http://i.stack.imgur.com/QqAD8.jpg` @gfosco

**Comment by gfosco** [comment]
Can you show the headers that were sent back?...

**Comment by gfosco** [comment]
Please re-try with 2.1.3 and open a new issue with as much detail as possible if you're still having a problem.  Thanks.
