### ISSUE TITLE
Setting server url on Arduino

### ISSUE THREAD

**Issue by timdiacon** [ParsePlatform/parse-server#531]
The examples given for connecting the parse sdks doesn't include arduino. How do I set the server url when connecting with arduino?

**Comment by gfosco** [comment]
The IOT SDKs and the PPNS push system used in them are currently unsupported.  The Arduino SDK is open source and you can modify it to make the object system work: https://github.com/ParsePlatform/Parse-SDK-Arduino

I'm sure a PR adding the ability to set the server url & path would be welcomed there.
