### ISSUE TITLE
Update Swift Example in wiki  for IOS SDK

### ISSUE THREAD

**Issue by ajaybeniwal** [ParsePlatform/parse-server#537]
Hi Can u update the Swift example in wiki with below example because its difficult to find for beginners

let parseConfiguration = ParseClientConfiguration {
            $0.applicationId = "myAppId"
            $0.clientKey = ""
            $0.server = "http://your_server.com:1337/parse"
        }
 Parse.initializeWithConfiguration(parseConfiguration)

**Comment by nlutsenko** [comment]
Done. Thanks for the suggestion!
Just updated https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide with Swift example.
