### ISSUE TITLE
Imported data through "mongoimport" can't be updated

### ISSUE THREAD

**Issue by francoismarceau29** [ParsePlatform/parse-server#540]
Hi there,

I uploaded a bunch of objects from a CSV using the "mongoimport" command. Using the iOS SDK, I am able to fetch them. When I try to update one of these object, I get the error "Object not found. (Code: 101, Version: 1.12.0)". I am using Parse server 2.1.2

One thing I noticed is that these objects are imported with a format of id:
`"_id": {
        "$oid": "56c525c563069649f14a38d5"
    }`

Instead of:
`"_id": "56c525c563069649f14a38d5"`

I found out that I am able to update records if I remove the $oid format directly in the database.

Is it an expected behavior ?
Thanks

**Comment by drew-gross** [comment]
Yes that is expected, if you insert objects directly into mongo without matching the Parse format, then Parse won't be able to read from the objects.

**Comment by RafaRuiz** [comment]
@drew-gross what would you tell me about this issue ? http://stackoverflow.com/questions/37471863/indexed-data-to-parse-server-through-mongodb-doesnt-get-fetched

I'm able to fetch them without a logical reason... 
- filtering by one string, no results
- filtering by the same string AND date before certain, bingo!
