### ISSUE TITLE
Parse.User.authenticated doesn't work in Cloud Code

### ISSUE THREAD

**Issue by Tux1** [ParsePlatform/parse-server#541]
Maybe you are already aware about this issue that `Parse.User.authenticated()` in Cloud Code returns `false` for every call.

Do you confirm ?

**Comment by gfosco** [comment]
True, there is no concept of a 'current' user in the node environment.  You get the user who made the request in the request object .user property, and can pass the session token to query/save calls to perform operations as a user.  This is mentioned at the bottom of the readme.  Re-open if I'm missing something.. Thanks.
