### ISSUE TITLE
Is there still 1000 limit for queries?

### ISSUE THREAD

**Issue by LtrDan** [ParsePlatform/parse-server#548]
And for matchesQuery specifically...

**Comment by mithleshjs** [comment]
That limit is gone.

**Comment by drew-gross** [comment]
Thanks @mithleshjs!

**Comment by flavordaaave** [comment]
I think this should go into the SDK. At least in the [JS SDK](https://parse.com/docs/js/guide#queries-relational-queries) I couldn't find any info that the limit does not apply for the self-hosted parse-server)

**Comment by subinsebastien** [comment]
This should be added to the documentation as a side note.
