### ISSUE TITLE
Serving Multible Apps per Parse instance 

### ISSUE THREAD

**Issue by mohshaheen** [ParsePlatform/parse-server#551]
Hello, 
i have been using Parse.com to host 3 of my mobile apps , now i knew that i would need to have single Parse Server instance per App .

- so, in terms of hosting (mine will be digital ocean) , how many Parse server instances could run per single VPS ? 
- what is the optimal config to have 3 Parse Server instances run on single VPS ?
- any plan or workaround to have the Parse Server become a multi-tenant (Single Instance for many Apps)?

**Comment by drew-gross** [comment]
@flovilmart is working on some multi-tenant stuff, but it's pretty experimental and there are still a lot of open questions, like what should go in separate process and what shouldn't. 

How many instances you can run on one server will depend on very many variables, including the size of the server, how many queries you are serving, what fraction of them are writes, latency to the DB, etc. running 3 on one server shouldn't be a problem if they are low-traffic, but I'd recommend doing some load testing before moving production apps.

**Comment by aknoormohamed** [comment]
i will dynamically create parse server instance like back4app
