### ISSUE TITLE
Parse Push -> Amazon SNS / SQS?

### ISSUE THREAD

**Issue by gateway** [ParsePlatform/parse-server#553]
I was wondering if anyone is working on a push adaptor to use Amazon SNS (Push notifications, email etc) and Amazon SQS simple queuing service.

https://aws.amazon.com/sns/
http://docs.aws.amazon.com/sns/latest/dg/SNSMobilePush.html
http://docs.aws.amazon.com/sns/latest/dg/SendMessageToSQS.html

**Comment by mohshaheen** [comment]
i would prefer :OpenSignal for push and Mandril/SendGrid for email
however , recently parse has added Push

**Comment by gateway** [comment]
@mohshaheen yea those services are nice, amazon is actually quite good at push, we used it for the last video game I worked on and has the ability to push to almost anything and the price is right, you get 1 million free pushes a month.. 

This was more of who wants to see a SNS push adaptor created (I'm aware push is already implemented for parse server and some other services that work with it)

**Comment by flovilmart** [comment]
@gateway you can start on it. It is likely it will be encouraged that all those adapters are hosted in external packages in order to remove the overhead on the core server.

**Comment by gateway** [comment]
@flovilmart I can look into it, or if someone wants to work with me on it.  I would prefer as mentioned in my post to make sure push is decoupled from the core server stuff.

Also one thing missing is the feedback loop from Apple, I was wondering if anyone was going to work on that since it returns the list of invalid device tokens and we should disable that user token in installation class to avoid spamming apple with invalid tokens.

**Comment by flovilmart** [comment]
@gateway you can wait for PR #549 or get started, publish it on your own repo :)

**Comment by gateway** [comment]
@flovilmart .. How does the current parse push work with queuing up messages to go out at x time.  I could see a huge bottle neck w/o a message que/worker system.

**Comment by flovilmart** [comment]
ParsePushAdapter has it's own mechanics, urban-airship too. I believe there is a scheduling option in SNS.

**Comment by gfosco** [comment]
Now that the push adapter system is out, and others have started to make adapters (OneSignal) I think we can close this..  Preferably an SNS module would exist as a separate npm module to be required and injected.

**Comment by rogerhu** [comment]
Released here:

https://www.npmjs.com/package/parse-server-sns-adapter
