### ISSUE TITLE
object.saveEvantually()=legalArgumentException

### ISSUE THREAD

**Issue by adamofsky** [ParsePlatform/parse-server#556]
When trying to save object in Android
 java.lang.IllegalArgumentException: invalid type for ParseObject: class org.json.JSONObject
saveInBackground() solves problem

**Comment by gfosco** [comment]
Looks like this issue is specific to the android SDK, maybe you can create a more detailed issue on that repository at: https://github.com/ParsePlatform/parse-sdk-android
