### ISSUE TITLE
CLP pointer permissions

### ISSUE THREAD

**Issue by dcdspace** [ParsePlatform/parse-server#557]
Previously before Parse Server, I could specify pointers in a class to be able to have certain permissions on an object through the data browser's CLP settings. Now with Parse Server, that no longer works and I have to allow the public to read/write if I want to access the data. The schema in my mongodb updated with the correct CLP, but it is returning `[Error]: Permission denied for this action.`. 

Here is my schema:

`        "class_permissions": {
            "get": {},
            "find": {},
            "update": {},
            "create": {
                "*": true
            },
            "delete": {},
            "addField": {},
            "readUserFields": [
                "toUser",
                "fromUser"
            ],
            "writeUserFields": [
                "toUser",
                "fromUser"
            ]
        }`

Thanks for the help.

**Comment by drew-gross** [comment]
Pointer permissions aren't supported in Parse Server yet. We're continuing to work towards complete feature parity with Parse.com, but we aren't there yet.

**Comment by mmazzarolo** [comment]
Hi!
Any news about CLP pointer permissions release date? Thanks!

**Comment by drew-gross** [comment]
Pointer Permissions are done and will be part of the next release.
