### ISSUE TITLE
After signup user ,and become the user,cannot alter user data,server return errorcode 206

### ISSUE THREAD

**Issue by ynl** [ParsePlatform/parse-server#559]
After signup user ,and become the user,cannot alter user data,server return errorcode 206.
```
-(void)signUpViewController:(PFSignUpViewController *)signUpController didSignUpUser:(PFUser *)user{
        [PFUser become:user.sessionToken];

}
```

**Comment by simonbengtsson** [comment]
Can you validate the sessionToken sent to the become method? Error 206 indicates that it has not been set.

**Comment by gfosco** [comment]
Closed for lack of response and details.  If you're still having a problem, please open a new issue and provide as many details as possible to try and reproduce.  Thanks.
