### ISSUE TITLE
Notifications, dashboard, analytics.. when?

### ISSUE THREAD

**Issue by rihadavid** [ParsePlatform/parse-server#56]
Parse notifications, dashboard etc. - when could it potentialy become available in this open source? I know it matters how active the community will be, but I have no clue how things work. Is this matter of weeks, few months or a year? Just an estimate, pleeease. It would be very helpful.

**Comment by jamesyu** [comment]
I can't guarantee a specific launch date, but rest assured we are at this very moment working on push notifs (for android and ios) and the dashboard.

Push probably in the next month, and a lite version of the dashboard within two.

**Comment by kingmatusevich** [comment]
Awesome, :+1:

**Comment by alexrmacleod** [comment]
@jamesyu @gfosco you guys rock! I actually can't believe facebook is shutting this down, with no other interest from any other companies, this is a no brainer acquisition for apple or google (maybe even microsoft) imho. They need more apps in their app store which in my eyes is the ultimate driver phone sales. Look at the windows phone. They have a barren app store, as a result no body wants their phones.

**Comment by ChrisSE22** [comment]
One of my apps build using Parse is available for Windows Phone as well as iOS and Android, so I'd love to see PNs for it in self hosted Parse. Looking forward so much to getting it rocking on node.
