### ISSUE TITLE
OAuth Problem with using as REST API

### ISSUE THREAD

**Issue by kkaradag2** [ParsePlatform/parse-server#560]
Hi all,

I have just install parse-server from last version. When I using http://localhost:1337/users on Rest clinet  with this headers;
X-Parse-Application-Id: 123456
X-Parse-REST-API-Key: 123456
X-Parse-Revocable-Session: 1
Content-Type: application/json

and  Payload data like that;

{
  "oauth": {
   "twitter": {
     "consumer_key": "my_twitter_application_consumer_key", 
     "consumer_secret": "my_twitter_application_consumer_scret",
     "auth_token": "My_users_Comes_outh_own_token",
     "auth_token_secret":"My_users_Comes_token_secrets",
     "id": "4186028951"
   }
  }
}

finaly parse server returns;

{
"code": 200
"error": "bad or missing username"
}

----------------------------------------- 0 ---------------------------------------------------------

this code works on parse.com . What is problem ?

**Comment by talkaboutdesign** [comment]
Do you have your OAuth keys entered in Parse Server Config?

**Comment by kkaradag2** [comment]
Yes , I have and configured parse server config. I have also send this via
request header.

**Comment by flovilmart** [comment]
@talkaboutdesign what does your parse server configuration look like?

**Comment by kkaradag2** [comment]
My parse server configuration is like that;


#!/usr/bin/env node
var express = require('express');
var ParseServer = require("../lib/index").ParseServer;

var app = express();

var options = {};
if (process.env.PARSE_SERVER_OPTIONS) {

options = JSON.parse(process.env.PARSE_SERVER_OPTIONS);

} else {
options.databaseURI = 'mongodb://localhost:27017/dev';
options.cloud = process.env.PARSE_SERVER_CLOUD_CODE_MAIN;
options.collectionPrefix = process.env.PARSE_SERVER_COLLECTION_PREFIX;

// Keys and App ID
options.appId = '123456';
options.clientKey = '123456';
options.restAPIKey = '123456';
options.dotNetKey = '123456';
options.javascriptKey = '123456';
options.dotNetKey = '123456';
options.masterKey = '123456';
options.fileKey = '123456';
// Comma separated list of facebook app ids
var facebookAppIds = process.env.PARSE_SERVER_FACEBOOK_APP_IDS;

if (facebookAppIds) {
facebookAppIds = facebookAppIds.split(",");
options.facebookAppIds = facebookAppIds;
}

var oauth = process.env.PARSE_SERVER_OAUTH_PROVIDERS;
if (oauth) {
options.oauth = JSON.parse(oauth);
};
}

var mountPath = process.env.PARSE_SERVER_MOUNT_PATH || "/";
var api = new ParseServer(options);
app.use(mountPath, api);

var port = process.env.PORT || 1337;
app.listen(port, function() {
  console.log('parse-server-example running on http://localhost:'+ port +
mountPath);
});

-------------------------------------------------------------------------------

parse server is working locally. I aim is linking users with twitter
authData via RESt API. (
https://parse.com/docs/rest/guide#users-linking-users)
Normally this  technic is working on parse.com but locally not.


curl -X POST \
  -H "X-Parse-Application-Id: 123456" \
  -H "X-Parse-REST-API-Key: 123456" \
  -H "X-Parse-Revocable-Session: 1" \
  -H "Content-Type: application/json" \
  -d '{
        "authData": {
          "twitter": {
            "id": "12345678",
            "screen_name": "ParseIt",
            "consumer_key": "SaMpLeId3X7eLjjLgWEw",
            "consumer_secret": "SaMpLew55QbMR0vTdtOACfPXa5UdO2THX1JrxZ9s3c",
            "auth_token":
"12345678-SaMpLeTuo3m2avZxh5cjJmIrAfx4ZYyamdofM7IjU",
            "auth_token_secret": "SaMpLeEb13SpRzQ4DAIzutEkCE2LBIm2ZQDsP3WUU"
          }
        }
      }' \
  http://localhost:1337/users

**Comment by flovilmart** [comment]
Kkaradag2 you're not supposed to set your configuration in bin/parse-server.

This is why it's not working correctly.

Please follow the installation instructions again in the README.md

**Comment by kkaradag2** [comment]
All functions is working with current configuration.  For example I try to
create user with REST API

curl -X POST \
  -H "X-Parse-Application-Id: 123456" \
  -H "X-Parse-REST-API-Key: 123456" \
  -H "X-Parse-Revocable-Session: 1" \
  -H "Content-Type: application/json" \
  -d
'{"username":"cooldude6","password":"p_n7!-e8","phone":"415-392-0202"}' \
http://localhost:1337/users

and parse server return acceptable result with sessionID;

{
"objectId": "zr7t9jE4Xb"
"createdAt": "2016-02-23T13:18:46.776Z"
"sessionToken": "r:9ead3b07e2855b4e7a4295670fff1e32"
}


I want to use linking user function. Previously I explain, sent twitter
access_token, screet and register user and retorn a sessionId as like as
parse.com  but if I sent like that data
curl -X POST \
  -H "X-Parse-Application-Id: 123456" \
  -H "X-Parse-REST-API-Key: 123456" \
  -H "X-Parse-Revocable-Session: 1" \
  -H "Content-Type: application/json" \
  -d '{
        "authData": {
          "twitter": {
            "id": "12345678",
            "screen_name": "ParseIt",
            "consumer_key": "SaMpLeId3X7eLjjLgWEw",
            "consumer_secret": "SaMpLew55QbMR0vTdtOACfPXa5UdO2THX1JrxZ9s3c",
            "auth_token":
"12345678-SaMpLeTuo3m2avZxh5cjJmIrAfx4ZYyamdofM7IjU",
            "auth_token_secret": "SaMpLeEb13SpRzQ4DAIzutEkCE2LBIm2ZQDsP3WUU"
          }
        }
      }' \
  http://localhost:1337/users

parse server returns internal server error

    at validateAuthData
(C:\Users\kemal.karadag\AppData\Roaming\npm\node_modules\parse-server\lib\oa
uth\twitter.js:7:16)
    at RestWrite.handleOAuthAuthData
(C:\Users\kemal.karadag\AppData\Roaming\npm\node_modules\parse-
server\lib\RestWrite.js:262:10)
    at RestWrite.validateAuthData
(C:\Users\kemal.karadag\AppData\Roaming\npm\node_modules\parse-ser
ver\lib\RestWrite.js:166:19)
    at
C:\Users\kemal.karadag\AppData\Roaming\npm\node_modules\parse-server\lib\RestWrite.js:80:18
    at process._tickDomainCallback (node.js:407:9)

**Comment by kkaradag2** [comment]
C:\Users\kemal.karadag\AppData\Roaming\npm\node_modules\parse-server\src>node
run.js
parse-server-example running on port 1337.
Uncaught internal server error. [TypeError: Cannot read property
'consumer_key' of undefined] TypeEr
ror: Cannot read property 'consumer_key' of undefined
    at new OAuth
(C:\Users\kemal.karadag\AppData\Roaming\npm\node_modules\parse-server\lib\oauth\OAu
th1Client.js:5:30)
    at validateAuthData
(C:\Users\kemal.karadag\AppData\Roaming\npm\node_modules\parse-server\lib\oa
uth\twitter.js:7:16)
    at RestWrite.handleOAuthAuthData
(C:\Users\kemal.karadag\AppData\Roaming\npm\node_modules\parse-
server\lib\RestWrite.js:262:10)
    at RestWrite.validateAuthData
(C:\Users\kemal.karadag\AppData\Roaming\npm\node_modules\parse-ser
ver\lib\RestWrite.js:166:19)
    at
C:\Users\kemal.karadag\AppData\Roaming\npm\node_modules\parse-server\lib\RestWrite.js:80:18
    at process._tickDomainCallback (node.js:407:9)
Uncaught internal server error. [TypeError: Cannot read property
'consumer_key' of undefined] TypeEr
ror: Cannot read property 'consumer_key' of undefined
    at new OAuth
(C:\Users\kemal.karadag\AppData\Roaming\npm\node_modules\parse-server\lib\oauth\OAu
th1Client.js:5:30)
    at validateAuthData
(C:\Users\kemal.karadag\AppData\Roaming\npm\node_modules\parse-server\lib\oa
uth\twitter.js:7:16)
    at RestWrite.handleOAuthAuthData
(C:\Users\kemal.karadag\AppData\Roaming\npm\node_modules\parse-
server\lib\RestWrite.js:262:10)
    at RestWrite.validateAuthData
(C:\Users\kemal.karadag\AppData\Roaming\npm\node_modules\parse-ser
ver\lib\RestWrite.js:166:19)
    at
C:\Users\kemal.karadag\AppData\Roaming\npm\node_modules\parse-server\lib\RestWrite.js:80:18
    at process._tickDomainCallback (node.js:407:9)

**Comment by flovilmart** [comment]
Please see the OAuth guide here: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#oauth
