### ISSUE TITLE
How to move a cloud code?(Hosting  Run Express in Cloud Code)

### ISSUE THREAD

**Issue by Avatarchik** [ParsePlatform/parse-server#561]
Hi!
main.js
require('./app.js');

app.js
var Country = Parse.Object.extend('Country');
var auth = require('http-auth');

// These two lines are required to initialize Express in Cloud Code.
express = require('express');
app = express();
// Global app configuration section
app.set('views', 'cloud/views'); // Specify the folder to find templates
app.set('view engine', 'ejs'); // Set the template engine

how do I make it work?

**Comment by gfosco** [comment]
Why would you run express in cloud code?  It is kind of backwards, cloud code is running in express... 

Maybe you should check the example project:  https://github.com/parseplatform/parse-server-example
