### ISSUE TITLE
Parse after save and before save not working

### ISSUE THREAD

**Issue by redblinkdevs** [ParsePlatform/parse-server#562]
Hi ,
    I have clone parse server on local server with mongodb database.
    I saved data to from android device.Its working fine.
   But the after save and before save methods in cloud code are not working. . 
 
Thanks
Parminder Ghuman

**Comment by gfosco** [comment]
The before and after save functionality does work and is tested, so you may be doing something incorrectly.  In order to get assistance, you'll need to provide more details, code, and try to do some troubleshooting first.  Please open a new issue when you have more information.  Thanks.
