### ISSUE TITLE
Sending Push Notifications via Cloud - Master key is invalid

### ISSUE THREAD

**Issue by seecahkhing** [ParsePlatform/parse-server#564]
Hi,

I was able to do queries via cloud but unfortunately I can't seem to let the push notification works via my cloud function. This was used to be working with the Parse platform before but after migration I am receiving this error: 
code = 115;
message = "Master key is invalid, you should only use master key to send push";

Push Notification works when I'm using curl on the command line. Below is my code snippet

<img width="413" alt="screen shot 2016-02-22 at 6 47 56 pm" src="https://cloud.githubusercontent.com/assets/213741/13216105/d344bbd6-d994-11e5-9d03-c2928497b570.png">

**Comment by adamofsky** [comment]
I have the same problem in Android and IOS

**Comment by seecahkhing** [comment]
I have tried some advises from this issue as well [ https://github.com/ParsePlatform/parse-server/issues/564](url) to no avail..

**Comment by wangmengyan95** [comment]
Check #401

**Comment by gfosco** [comment]
The code you have posted has 2 issues.  `useMasterKey:true;` is not valid javascript.  It should be passes as a second parameter to Parse.Push.send in an object.

```
return Parse.Push.send({
  where: query,
  data: { ... }
}, { useMasterKey: true });
```

**Comment by maruthi-wal** [comment]
Hello Everyone,

Iam getting **Master key is invalid, you should only use master key to send push**

Please find my cloud code below:

Parse.initialize("appid", "javascriptkey", "masterkey");
var pushQuery = new Parse.Query(Parse.Installation);
Parse.Push.send({
        channels: [ "Giants" ],
        data: {
            alert: "The Mets scored! The game is now tied 1-1.",
			badge: "Increment",
            sound: "cheering.caf",
            title: "Mets Score!"
        }
    },
	{useMasterKey: true}  ,
	{
        success: function () {
            response.success("Push was sent");
			console.log("Push was sent");
        },
        error: function (error) {
            response.error("Could not send push " + error);
			console.log("Could not send push " + error);
        },
		
 });

Please help me on this
Thanks,

**Comment by drew-gross** [comment]
Don't call `Parse.initialize` in your Cloud Code, that is already done from within the server.
