### ISSUE TITLE
Store push notification history / status

### ISSUE THREAD

**Issue by sakinasugra** [ParsePlatform/parse-server#566]
I have migrated my parse app successfully to locally setup parse server. I am able to register the device installation and also am able to send pushes from my device to other devices. But the pushes that I send are not saved either on the parse dashboard under push nor in my mognodb in _PushStatus. I am using iOS and below is the code that I have used:

                  `NSString *post = [NSString stringWithFormat:@"{\"where\": {\"channels\": \"%@\"},\"data\": {\"action\": \"LOGOUT\",\"content-available\": \"1\",\"moduleIdentifier\":\"LOGOUT\",\"nTitle\":\"Password Changed\"}}",@"My_channel"];

                    NSData *postData = [post dataUsingEncoding:NSASCIIStringEncoding allowLossyConversion:YES];

                    NSURL *url = [NSURL URLWithString:@"https://my_localhost_url/parse/push/"];

                    NSMutableURLRequest *request = [NSMutableURLRequest requestWithURL:url];

                    [request setHTTPMethod:@"POST"];

                    [request addValue:@"My_App_Id" forHTTPHeaderField:@"X-Parse-Application-Id"];

                    [request addValue:@"My_Master_Key" forHTTPHeaderField:@"X-Parse-Master-Key"];

                    [request addValue:@"application/json" forHTTPHeaderField:@"Content-Type"];

                    [request setHTTPBody:postData];

                    NSURLResponse *requestResponse;

                    NSError *err;

                    NSData *data = [NSURLConnection sendSynchronousRequest:request returningResponse:&requestResponse error:&err];`

**Comment by flovilmart** [comment]
@sakinasugra there is no tracking of the push sending yet, PR are welcome

**Comment by flovilmart** [comment]
@gfosco was there an API / url scheme that was in place before?

**Comment by flovilmart** [comment]
@sakinasugra can you give the columns/types of _PushStatus?

**Comment by gateway** [comment]
Is this what you guys @flovilmart @gfosco  are talking about? Where is this data stored its not in Core, im assuming this is another internal db for push in the parse.com system? 

![image](https://cloud.githubusercontent.com/assets/519563/13235665/01091592-d974-11e5-871d-7e4e9bfcde7f.png)

**Comment by flovilmart** [comment]
That's what we're talking about. I'm not sure they are migrated when migrating an app. There is maybe more to do here than just scratching the surface of storing the push request results.
That also implies that push adapter implement a common callback for the push server response

**Comment by gateway** [comment]
@flovilmart I would guess this data could be stored in a _Push class however it would be good for someone at parse @gfosco could maybe shed some light on what the schema might look like, also when a user clicks on a text message how do we know when its open, does iOS send something back to parse incrementing a counter?

**Comment by flovilmart** [comment]
That Would be The analytics that are unimplemented as of now ;)

**Comment by sakinasugra** [comment]
@flovilmart when I send a push from the parse website, the push is displayed on the parse website and also in my migrated database ( see the images) 
![screen shot 2016-02-23 at 10 40 38 am](https://cloud.githubusercontent.com/assets/17409857/13242372/142ebbc6-da1a-11e5-9603-0e433315b00f.png)
![screen shot 2016-02-23 at 10 42 43 am](https://cloud.githubusercontent.com/assets/17409857/13242414/6786320e-da1a-11e5-811f-aff4a94d24a1.png)

but when I send the push from my ios app using my code, it does not get logged, either in the parse website nor my migrated database but I receive the notification. 
Is this not implemented yet or I have gone wrong somewhere??

**Comment by drew-gross** [comment]
It hasn't been implemented yet. PRs welcome :)

**Comment by sakinasugra** [comment]
Thank You.

**Comment by JohnMorales** [comment]
@drew-gross I would like to try to take this on

**Comment by flovilmart** [comment]
@JohnMorales stay tuned for the spec !

**Comment by JohnMorales** [comment]
@flovilmart Sounds good, 

On a side note is there a gitter, irc, or slack channel where direction and ideas are discussed? I don't seem to find anywhere discussing how to communicate w/ the project lead and interested parties beyond reading through comments on issues

**Comment by flovilmart** [comment]
We're setting that up!

**Comment by flovilmart** [comment]
@JohnMorales we've uploaded a Gist with the spec for the _PushStatus class here https://gist.github.com/flovilmart/bf64276507d685ae41f6.

Let me know if there are implementation details you're not sure about.

The work will likely to be in the `src/Controllers/PushController.js` and we'll need to add a callback/method to the PushAdapters to get the status of the sent pushes. 

For now, don't worry about all the adapters, we can start by having something functional with ParsePushAdapter.js

Good luck and Thanks!

**Comment by gateway** [comment]
:+1:  for Slack channel

**Comment by JohnMorales** [comment]
@gateway :+1: for the nick

**Comment by flovilmart** [comment]
@JohnMorales did you make any progress on that?

**Comment by JohnMorales** [comment]
Sorry man, I was trying to figure out the overall architecture and was a
bit overwhelmed. It might make more sense for me to pick up something where
I can look at a similar task as a guide.

**Comment by flovilmart** [comment]
No big deal! Was just to know! This a kinda a tricky one is we wanna have delivery etc...

**Comment by gfosco** [comment]
A PushStatus API was added in #1004.
