### ISSUE TITLE
Point subdomain to /parse/files directory 

### ISSUE THREAD

**Issue by eatentree** [ParsePlatform/parse-server#568]
Hi,

I have setup parse server (Node.js server instance) and web app(PHP server instance) successfully to AWS sever. Now I want to point sub domain of my web app to /parse/files directory directly and want to put this sub domain on cloudflare. I want to use this subdomain for content delivery on my web app. 

How can I do this?

Thanks.

**Comment by thewizster** [comment]
Parse server is just running on expressjs. Setup a route on your Parse Server (Expressjs) and point your sub-domain to it. Then reference the sub-domain in your PHP web app.

**Comment by eatentree** [comment]
Hi, 

I do not know expressjs language. Can you provide some code and where to put it? 
I want to point subdomain to http://{aws server}/parse/files

**Comment by gfosco** [comment]
I have to close this because it is not related to parse-server.  You can use various methods for handling your subdomain and perhaps re-writing the URL... Take a look at your domain/DNS provider, or look at nginx as an entry-point to route requests around.. Thanks.
