### ISSUE TITLE
Push Notifications support for OS X, tvOS

### ISSUE THREAD

**Issue by nlutsenko** [ParsePlatform/parse-server#571]
This issue is for tracking an improvement to classic ParsePushAdapter to add support for OS X (which is supported on classic Parse), and tvOS (which is not).

Adding support for these would be very trivial, since we have iOS Push Notifications working, and would require changes to a few things:
- Add support for `osx` and `tvos` deviceTypes to installation
- Add support to ParsePushAdapter and `APNS.js` to accept more than just iOS certificates.
- Add support to ParsePushAdapter and `APNS.js` to send to tvOS, which reuses the same certificate as iOS.

Comment here, subscribe to this issue or send a PR to implement any part of this.

**Comment by flovilmart** [comment]
transferred here: parse-server-modules/parse-server-push-adapter#11
