### ISSUE TITLE
Any chances for app admin dashboard

### ISSUE THREAD

**Issue by adampietrasiak** [ParsePlatform/parse-server#58]
Are there any chances that admin dashboard where all data, acl, classes access etc could be managed?

**Comment by alexrmacleod** [comment]
dashboard and push notifications is so important to keeping this thing going!

**Comment by kingmatusevich** [comment]
they are going to be done, the main developers have said so all over the place. 
e.g. :  https://github.com/ParsePlatform/parse-server/issues/3, https://github.com/ParsePlatform/parse-server/issues/5, and especially https://github.com/ParsePlatform/parse-server/issues/56

**Comment by alexrmacleod** [comment]
@kingmatusevich thanks for that!

**Comment by kingmatusevich** [comment]
@alexrmacleod no problem 😊

**Comment by francocorreasosa** [comment]
Related in #3 #5 #56

**Comment by bagusflyer** [comment]
That's a good news. Thanks.
