### ISSUE TITLE
PushController validateMasterKey always returning false. 

### ISSUE THREAD

**Issue by daviddayag** [ParsePlatform/parse-server#580]
In PishController the method validateMasterKey always fails and so without disabling this check I can't send push notifications.

**Comment by gfosco** [comment]
Where are you sending push from? In parse-server, the master key must always be used, and push should not be sent from clients.

**Comment by daviddayag** [comment]
Yes I'm sending from cloud code. 
I use the method Parse.useMasterKey() before calling the push method.

**Comment by gfosco** [comment]
the useMasterKey method doesn't work in cloud code.  This is mentioned at the bottom of the readme.  The useMasterKey:true option must be passed to the options block of Parse.Push.send:

```
Parse.Push.send({
  where: query,
  data: { ... }
}, { useMasterKey: true });
```

**Comment by anthonysg** [comment]
@gfoscoI Please bring back useMasterKey() so that the original cloud code works. Would probably lessen a whole lot of confusion as well.

**Comment by daviddayag** [comment]
Oh ok, I'm sorry. I might have missed that.  Is this true also for other things like saving objects with specific acl?
How can I save an object I don't have authorization for, if so?

**Comment by gfosco** [comment]
You can pass the useMasterKey option to query and save calls:

```js
object.save(null, { useMasterKey: true }).then(....

query.find({ useMasterKey: true }).then(....
```

**Comment by daviddayag** [comment]
and for count()? 
count({useMasterKey: true})   ?

**Comment by daviddayag** [comment]
also 
saveAll({useMasterKey: true}, objects) ?

**Comment by gfosco** [comment]
The count one looks right, but swap the parameter order for saveAll.

**Comment by daviddayag** [comment]
Ok thanks!
