### ISSUE TITLE
Cloud code: Dirty flag on properties always returnes false.

### ISSUE THREAD

**Issue by daviddayag** [ParsePlatform/parse-server#581]
In Cloud code when using "is dirty" method on a property on any PatseObject, it will always return false. 
The cloud code I'm running is working as expected on parse hosted server, so this is an issue with this code.

**Comment by gateway** [comment]
Probably best to give example code, and if anything shows up in the parse server logs, if not enable VERBOSE = 1 as an environment variable that might spit out more info.

**Comment by daviddayag** [comment]
Nothing special actually. 
Setting a numeric property in the android parse sdk. 
Saving object. 
Before save in cloud code, exec is dirty method on that object, giving that property name ==> returns false. 

As I mentioned, the parse hosted server works as expected. There it'll return true.

**Comment by gfosco** [comment]
There's some work to be done here to match the hosted cloud code functionality.  Some of this was done in parse-cloud-express for webhook usage and just needs to be implemented here.

**Comment by daviddayag** [comment]
Ok thanks! 
Waiting for a fix.

**Comment by daviddayag** [comment]
any ETA on this?

**Comment by nlutsenko** [comment]
No ETA just yet, you are very welcome to jump in and look into ways to fix it, but I am going to tackle this today/tomorrow.

**Comment by nlutsenko** [comment]
Got the working solution for updatedObjects, but looks like we also expose `dirtyKeys()` for created objects - working on the solution right now.

**Comment by daviddayag** [comment]
Hi, is this fixed?

**Comment by nlutsenko** [comment]
Fixed, coming in the next version.

**Comment by xissburg** [comment]
The opposite happens with me. `dirty` seems to be always returning true (in beforeSave) and that's causing problems with my cloud code logic (version 2.1.5).

**Comment by nlutsenko** [comment]
If the object was mutated for a save - it should be `dirty`, since the changes are not yet applied.
This behavior is consistent with parse.com implementation, so I don't think we should change it.
@xissburg, let's try debugging and fixing your logic together, you can open another issue or we can continue here...
