### ISSUE TITLE
iOS Can't download a file that doesn't exist on the server or locally

### ISSUE THREAD

**Issue by dcdspace** [ParsePlatform/parse-server#585]
With Parse Server, when I try and download an image I get the error `Can't download a file that doesn't exist on the server or locally. (Code: 151, Version: 1.12.0)`. This was mentioned in another issue but was not solved. Also if I upload an image with Parse server, I cannot access it in the Parse dashboard and any clients not accessing the database through the new server cannot access it. Is this a bug?

**Comment by michaelbina** [comment]
The issue he mentioned is #766

**Comment by nlutsenko** [comment]
This looks like is fixed already, please let us know if not.
