### ISSUE TITLE
Wrong format of user object saved in MongoDB after pasing thru beforeSave

### ISSUE THREAD

**Issue by mchun** [ParsePlatform/parse-server#589]
This is my code for creating a new post:

```
 app.post('/',requireUser, function(req, res) {
    var parseUserMe = new Parse.User();
    parseUserMe.id = req.user.id;
    var post = new Post();
    post.set("Desc", req.body.Desc);
    post.set("createdBy", parseUserMe);
    post.save().then(function(post) {
      res.json({ id: post.id });
    }, function(error) {
      res.json({ error: error });
    });
  });
```

But inside MongoDB, the createdBy field is saved as 

```
    "_p_createdBy": {
        "score": 59,
        "updatedAt": {
            "$date": "2016-02-23T04:06:29.402Z"
        },
        "objectId": "SPtdQePtm2",
        "__type": "Object",
        "className": "_User"
    },
```
instead of this:

`"_p_createdBy": "_User$SPtdQePtm2",`

which caused the Dashboard to crash and showed the following error on the server:

Uncaught internal server error. [TypeError: mongoObject[key].split is not a function] TypeError: mongoObject[key].split is not a function

**Comment by mchun** [comment]
I am frustrated as the problem only occurs when creating new post. Now I can confirm the problem is related to the beforeSave trigger function. If I commented out the beforeSave function, the format is saved correctly. Below is my beforeSave trigger function:

```
Parse.Cloud.beforeSave("Post", function(request,response) {
  var post=request.object;
  var postAuthor=post.get('createdBy');
  var photo1=request.object.get('photo1')
  Parse.Promise.as().then(function() {
    if (post.get('Category')==="所有 All")
      return Parse.Promise.error('請選擇分類');
    if (post.get('Category')==="書籍/雜誌  Books/Magazines")
      post.set('Category',"書籍/雜誌 Books/Magazines");
    if (post.get('Category')==="竉物用品 Pets")
      post.set('Category',"寵物用品 Pets");
    return Parse.Promise.as();
  }).then(function() {
    if (post.isNew()){
      if (post.get('postType')==="free"){
        postAuthor.increment('score');
        return postAuthor.save(null, {useMasterKey: true});
      }
    }else{
      if (post.get('postType')!==post.get('prevPostType')){
        if (post.get('postType')==='free')
          postAuthor.increment('score');
        else
          postAuthor.increment('score',-1);
        return postAuthor.save(null, {useMasterKey: true});
      }
    }
    return Parse.Promise.as();
  }).then(function(user) {
    post.set('prevPostType',post.get('postType'));
  }).then(function(){
    response.success();
  }, function(error) {
    response.error(error);
  });
});
```

**Comment by gfosco** [comment]
cc @nlutsenko who has been looking in to the triggers recently... Looks like this pointer saved from cloud code isn't being transformed properly.

**Comment by nlutsenko** [comment]
Yup, looks like it - looking into the best way to go about fixing it, but in the meantime - if you save the user before saving the post - it should properly resolve to full object save.

**Comment by nlutsenko** [comment]
Got a test case that fails, that's a good start, it is attached to the fact that we don't collapse objects back into pointers for child objects that could be saved in the middle of running a beforeSave.

**Comment by mchun** [comment]
The problem also occurs when I used a fetched user i.e. req.user instead of parseUserMe.
And moreover, it seems the dirty function is not working inside trigger functions? The fields are always clean.

**Comment by nlutsenko** [comment]
Yup, all of it is going to be fixed by the Pull Request attached to this issue.

**Comment by mchun** [comment]
Thanks so much, you guys are awesome!!
