### ISSUE TITLE
Parse-server crash in heroku

### ISSUE THREAD

**Issue by pccrazy** [ParsePlatform/parse-server#59]
hi , i am trying to follow the migration guide of parse to heroku 
the logs shows that there is something wrong on parse-server index.js and its crashing the app 
i have tried to remove it but the same thing happened again 
here is the screenshot of the log file. 

![screen shot 2016-01-30 at 3 53 21 am](https://cloud.githubusercontent.com/assets/5598959/12691418/10421954-c705-11e5-9978-43cb1e74c30b.png)

**Comment by francocorreasosa** [comment]
You are doing a step wrong, this is not a *parse-server* problem. Hundred of users have deployed to Heroku without problems. Check the tutorial and try again.

**Comment by jpv123** [comment]
@francocorreasosa thats not the way to help. Many of us has never used node.js so be kind.
@pccrazy It seems that your problem is on your index.js. Can you please post it so we can help you?

**Comment by gfosco** [comment]
Node v4.1+ is required, this sounds like an older version.  We updated the package.json to require this after launch, so maybe you just need to pull the latest changes.
