### ISSUE TITLE
var pushQuery = new.Parse.Query(Parse.User) return error

### ISSUE THREAD

**Issue by edwardyue** [ParsePlatform/parse-server#590]
Hi team,

I am testing my cloud code below after parse migration. It just simply return "error". Do I miss anything to setup the cloud code to access my DB? Thanks!

Parse.Cloud.useMasterkey();
var pushQuery = new.Parse.Query(Parse.User);
pushQuery.find({
success : function(results){
       response.success('return ' + results.lenght);
},
error : function(){
          response.error("error");
}
});

Best Regards,
Edward

**Comment by gfosco** [comment]
If you log the actual error it would help you track down the issue.  It's passed in to the error function.

```js
error: function(e) {
  console.log(e);
  response.error('Nope');
}
```

Then you could check the server logs and see what it returned.  It might be there's a class-level permission preventing the find operation on the _User class, and then fixing it by passing the right master key option should help.

From your code I can say that Parse.Cloud.useMasterKey() does not work in a node environment...  I'd rewrite the above code as:

```js

var userQuery = new Parse.Query('_User');
userQuery.find({ useMasterKey: true }).then((results) => {
  response.success('found ' + results.length + ' users.');  
}, (error) => {
  console.log(error);
  response.error
});
```

**Comment by gfosco** [comment]
It's been a while with no response.

If there is a problem with the latest version, please open a new issue.  Thanks.

**Comment by mstephano** [comment]
Hi, I have created a branch from my repo specially for you as an exmaple to Live Query on User object. Check it out: https://github.com/mstephano/parse-server-live-query-with-angular/tree/feature/LiveQueryUser
