### ISSUE TITLE
query.count() returns undefined on locally hosted Parse server

### ISSUE THREAD

**Issue by mmahmood** [ParsePlatform/parse-server#594]
The same code with the same data set is working fine on the parse hosted app. But on my local parse server, it always returns undefined. I haven't changed anything in the code. Am I supposed to?

**Comment by gfosco** [comment]
can you provide the code and any output?

**Comment by mmahmood** [comment]
The query is used to back a grid with pagination and returns the total number of records e.g. showing 5 of 20 (returned value). 

Here's the query being used . I have simplified the query by removing conditions based on filters applied on the grid. Assuming no filters:

exports.getTotalContributions = function(user, doofl){
	var query = new Parse.Query("Contribution");
	query.equalTo("doofl", doofl);
        query.equalTo("donor", user);
	return query.count();
}

This is called using Parse.Promise.when([contributionsJS.getTotalContributions(user, doofl)]). 
The result from this is "undefined" on my local parse server, whereas it is working fine on my test Parse instance. Data set and queries being tested are exactly the same.

The grid was on a  web page backed by express on Parse hosted app. On the Parse server, I have removed the endpoints from /cloud/app.js to parse-server-example/index.js.

**Comment by gfosco** [comment]
What if you called it with:

```js
contributionsJS.getTotalContributions(user, doofl).then((count) => {
  console.log(count);
  // ...
}, (error) {
  console.log(error);
  // ...
});
```

At least lets remove the 'when' construct for troubleshooting purposes and see if any errors are thrown..

**Comment by mmahmood** [comment]
The issue was that Parse.Promise.when([query.count()] was returning an array in response, and I was supposed to get the element at the first index. It was not a number. 

Thanks
