### ISSUE TITLE
Express view not loading on local parse server. Help!

### ISSUE THREAD

**Issue by mmahmood** [ParsePlatform/parse-server#598]
I am using Parse web hosing to host an express app. This is working fine in production too. I'm having issues migrating it to my local parse server. Please tell me what I'm doing wrong:

I have a web page called by /showContributions. This page contains a grid which gets its data from ajax request from /getContributions. This is working fine on Parse hosted app. But on my local parse server, I get the correct response from both links (I've checked logs), but the page doesn't load. There's no Javascript error either. The request just times out after getting data and all from the server and there's nothing on the page.

Parse hosted structure:
Myapp
- cloud
- main.js (required app.js)
- app.js
- routes (folder containing a file handling incoming pages)
- views (contains multiple *.ejs files to render pages)

Code in app.js
_var routes = require('./routes/routes');
app.set('views', './views');  // Specify the folder to find templates
app.set('view engine', 'ejs');    // Set the template engine
app.get('/getContributions', routes.getContributions);
app.get('/showContributions', routes.showContributionsList);_

I modified this as follows in parse server example:
I moved the code in app.js to Parse-server-example/ index.js as follows:

_app.set('views', './cloud/views');  // Specify the folder to find templates
app.set('view engine', 'ejs');    // Set the template engine
var routes = require('./cloud/routes/routes');
app.get('/getContributions', routes.getContributions);
app.get('/showContributions', routes.showContributionsList);_

What am I doing wrong here?

Thanks,
-Mariam

**Comment by simonbengtsson** [comment]
Looks about right. Does it work if you use `parse-server-example` without modifications? If so try one change at a time until something goes wrong and write here with any errors you run into.

**Comment by mmahmood** [comment]
Found the issue. I had not installed ejs. Can someone please update the migration guide with these minor but important details for newbies to node and express, like me. 

Thanks
