### ISSUE TITLE
Integration of parse-anywhere

### ISSUE THREAD

**Issue by flovilmart** [ParsePlatform/parse-server#6]
I've written [parse-anywhere](http://github.com/flovilmart/parse-anywhere) a while ago in order to be able to run cloud code locally.
Recently, I've deployed it through Google App Engine managed VM's in production.

The goal of parse-anywhere was to run the exact same code as you would on parse but locally, before deploying.

All the parse provided modules were re-written, or re-wrapped in order to have 100% compatibility.
Integrating it would be a nice to have for the community and avoid any code rewrite.

**Comment by gfosco** [comment]
Was this using our parse-cloud-express middleware for webhooks?... What would this look like if you added it to parse-server?

**Comment by flovilmart** [comment]
Yes it is, it spawns a subprocess with forever and injects the proper 'environment' and adds all the submodules to the path. I'd need to update a few lines to use the parse-server flavor of the hooks if required.

**Comment by flovilmart** [comment]
Added to parse server, instead of calling `require(options.cloudCodePath)` we'd do something like `require("parse-anywhere")(options.cloudCodePath)`

**Comment by gfosco** [comment]
Any metrics on usage of parse-anywhere?  I was preferring to force adoption of standard node environment & modules (and making it work) over trying to emulate hosted cloud code.

**Comment by flovilmart** [comment]
I totally understand. About 200 install last month. Some people use it frequently to debug their express app locally.

**Comment by gfosco** [comment]
I think parse-anywhere is very cool, and if you'd like to make a branch or a guide on using parse-anywhere with parse-server we can link to it in the Wiki.

**Comment by flovilmart** [comment]
Ok perfect. All the compatible dependencies are there too, most notably parse-image (based on gm). If you want to put that one in the wiki too :)

**Comment by gfosco** [comment]
Added to the wiki a link:  https://github.com/ParsePlatform/parse-server/wiki#community-links
