### ISSUE TITLE
Parse Server + MongoDb Backend on AWS

### ISSUE THREAD

**Issue by NglSR** [ParsePlatform/parse-server#60]
Hello guys, thanks for all the inputs on the other Issues posted. Can someone please indicate how to deploy the backend on AWS. I'm new into dev, my app still in development and hosted on Parse. I have been looking a guide or tutorial online since I got the bad news. Thanks in advance.

**Comment by NglSR** [comment]
here an open source backend: http://www.baasbox.com  I hope is useful... I don't have use it yet.

**Comment by bagusflyer** [comment]
Thanks for your info. But Parse server is also open source now. Why should we use something else we're not familiar. And talking about the cloud service, I'm afraid it will become another parse.com. So my opinion is to trust myself. Maybe host by ourself is better choice.

**Comment by NglSR** [comment]
@bagusflyer thanks.... And sorry for the link above. Do you know the way around deploying Parse Server+Mongodb on AWS?

**Comment by mfkenson** [comment]
ec2?
please refer to https://github.com/ParsePlatform/parse-server-example

**Comment by NglSR** [comment]
@mfkenson Thanks Brother. Lets start cooking.

**Comment by mfkenson** [comment]
@NglSR Under AWS EC2, you can follow the same steps mentioned in "For Local Development".

**Comment by NglSR** [comment]
@mfkenson Thanks men... deployed Node, Phyton and Parse Server on AWS... working on MongoDb.

**Comment by ihomecall** [comment]
NgISR, I am waiting for you or someone else to publish the whole success steps of migrating parse server to AWS EC2.

**Comment by niraj-shah** [comment]
I've created a AWS AMI if anyone wants to use it. It includes MondoDB, NodeJS and the Express example already setup. You just need to edit the /var/www/parse/app.js file with your API keys and run it using ```node app.js```.

The AMI ID is: ```ami-a00cbbd3``` (you can add it [using this guide](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/usingsharedamis-finding.html))

**Comment by JcMinarro** [comment]
Here is a HowTo Step by Step to create a Parse Server on your own Server.
https://medium.com/@jcminarro/run-parse-server-on-your-own-server-using-digitalocean-b2a7d66e1205#.e33bkf4m3

**Comment by gfosco** [comment]
We'll continue working with other providers to create easy ways to launch your own Parse servers and migrate to popular clouds, and we'll blog/tweet/wiki about everything.

**Comment by NglSR** [comment]
@niraj-shah @JcMinarro @gfosco Thanks for the support.... @niraj-shah  can't find the AMI.

**Comment by niraj-shah** [comment]
Sorry @NglSR. I forgot to mention the AMI is located in the Europe Ireland region.

**Comment by NglSR** [comment]
@niraj-shah, thanks... so if I change region can I still find it?

**Comment by niraj-shah** [comment]
No worries @NglSR. Also, if you right click on the AMI name and select "Copy AMI", you can copy it any region you want.

**Comment by NglSR** [comment]
@niraj-shah 
<img width="1064" alt="screen shot 2016-02-01 at 9 17 38 am" src="https://cloud.githubusercontent.com/assets/16966598/12719681/b3d083ce-c8c4-11e5-9665-42a8e2b55a7c.png">

**Comment by christianmarth** [comment]
You may need to launch a new server from the AMI and create a new image from that instance to copy

**Comment by niraj-shah** [comment]
@NglSR Strange! Looks like the AMI can only be created in Europe Ireland. I just tried the Copy AMI option and got the same error.

**Comment by NglSR** [comment]
@niraj-shah @christianmarth Guys, thanks a lot.

<img width="665" alt="screen shot 2016-02-01 at 9 35 26 am" src="https://cloud.githubusercontent.com/assets/16966598/12720165/5244c02c-c8c7-11e5-923f-09842325f1a2.png">
