### ISSUE TITLE
Cloud Code problem when querying with .withinKilometers()

### ISSUE THREAD

**Issue by VIVAnthony** [ParsePlatform/parse-server#607]
I'm having a weird issue with parse-server. I followed the migration step and am hosting the server on AWS Elastic Beanstalk.

The problem I am having is that when ever I create a new anonymous user (with either the Android or iOS SDK's automatic user) and try to call my cloud code function that queries using .withinKilometers(), it returns an empty array. It doesn't cause an error, just returns no results. 

Closing the app and trying again with the recently created user still does not work, however if I re-deploy the same parse-server code and try again with same user it returns the expected results. All my other queries and cloud functions work correctly the first time. Also the function in question works with a new anonymous user without re-deployment if I remove the .withinKilometers() call.

**Comment by drew-gross** [comment]
It could be related to the way we build indexes for geo queries. Can you do some investigation into your database and check if the query only fails when there is no index on your GeoPoint field?

**Comment by VIVAnthony** [comment]
Hey @drew-gross, sorry I am pretty new at managing a database so I'm not 100% what you mean. I am using mongolab as the migration steps suggest.

I did a bit more debugging and I reliezed that even though before calling the function I update and save the new users stored GeoPoint it is still returning the default set (0,0).

I have gone into mongolab and tried adding and removing indexes on the _User's GeoPoint field, but it is still not working.

**Comment by drew-gross** [comment]
We've received some other reports of this issue as well, so it seems to be a real issue. We'll look into it as soon as we can.

**Comment by 432player** [comment]
@drew-gross Hi drew, is the querying of Geo Location working?
We've started QA on our app and found that the distance query not working properly.
Is this a known bug? 
Thank you
:+1:

**Comment by 432player** [comment]
@VIVAnthony Hi Anthony, were you ever able to solve this issue?
@drew-gross , all we need is this issue solved and we will be able to release a first version of our app.
Could you please inform us if there has been any progress on this matter?
In short we're querying objects who also have a location. We're using the query with withinKilometers but it doesn't work and no results come back.
Any reply on this issue will be immensely appreciated.
Cheers

**Comment by VIVAnthony** [comment]
Hey @432player, The problem I was having was not with the withinKilometers() method itself but with a field in the _User table that I was passing to it. That problem as far as I can tell is still a bug, but I am getting around the issue by just passing the Parse GeoPoint as a parameters for my cloud function.

**Comment by drew-gross** [comment]
@432player we have tests that cover `withinKilometers` that work, so I'm not sure what this issue is. Can you post some code that reproduces this issue please?

**Comment by drew-gross** [comment]
@gateway traced this to a bug in mongo version 3.0.6. Use a different version of Mongo or follow the workaround in #1080

**Comment by Vinoy-** [comment]
@drew-gross we are using Mongo 3.0.11 , still we have the same issue, any work around other than cloud code. Cloud code solution will lose backward compatability.

**Comment by krishnakumarcitrus** [comment]
The same issue (querying with .withinKilometers() ) EXIST when using  Mongo 3.0.9 also.
I would also like to know about some other alternative than cloud as using cloud code will require my app users to force update the application.

**Comment by krishnakumarcitrus** [comment]
Mongo 3.0.0 is also having the same issue, are you sure this is issue of mongoDB itself ?
Can you please suggest me a mongoDB version that supports parse location based query ??

**Comment by drew-gross** [comment]
We officially support version 3.0.8 and 2.6.11, and those are the only versions we run our tests against. We will likely add support for version 3.2.5 (or whatever current stable is at the time) eventually. If you want to use other versions of MongoDB, you should expect bugs in those versions of MongoDB to trickle through to Parse Server.

If you want to help with supporting other versions, PRs would be accepted :)

**Comment by krishnakumarcitrus** [comment]
Tried  3.0.8, the same issue still exist. It doesn't seem like an issue of mongoBD version.
`{"code":141,"error":"{\"code\":1,\"message\":\"internal error\"}"}`
This is the error that comes when including `withinMiles` or `withinRadians` or `withinKilometers` .
Any hope ??

**Comment by drew-gross** [comment]
That error is a different issue than the one that this was originally about. Can you open a new issue and include some logs?

**Comment by krishnakumarcitrus** [comment]
Issue solved, see the [link](http://stackoverflow.com/questions/36770263/parse-location-based-query-not-working-after-data-migration)

Thanks @drew-gross
