### ISSUE TITLE
Parse File - Cross Domain 

### ISSUE THREAD

**Issue by edvincandon** [ParsePlatform/parse-server#61]
Started migrating my app to Heroku/MongoLab, only problem is file uploading on localhost.

I always end up having an XMLHttpRequest error when I post a file to my parse-server on heroku. All other requests work fine. 
![screen shot 2016-01-30 at 02 13 19](https://cloud.githubusercontent.com/assets/11134131/12692457/85e0add2-c6f7-11e5-8f1a-6dd2c46d4499.png)

I noticed that in the files.js you commentend` // TODO: do we need to allow crossdomain and method override? 
`
-> Anybody has an idea on how to fix? I've tried setting` res.header('Access-Control-Allow-Origin', '*'); ` in my `app.configure()` but with no luck... Does the parse server have its own middleware for managing headers?

**Comment by edvincandon** [comment]
Temporary fix -

 `app.all('*', function(req, res, next) {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Methods', 'PUT, GET, POST, DELETE, OPTIONS');
  res.header('Access-Control-Allow-Headers', 'Content-Type');
  next();
});`

**Comment by gfosco** [comment]
We have a middleware for this, can just enable it there and consider that TODO answered. ;)
