### ISSUE TITLE
Cloud Code with npm packages

### ISSUE THREAD

**Issue by jpv123** [ParsePlatform/parse-server#613]
Hi everyone. Sorry if this is a really noob question but I just don't know how to proceed.

I want to connect my cloud code with third party modules such as Cloudinary which has an npm module. I know how to install the npm module to my heroku server. What I don't know is how to call this module trough Cloud Code. 
I found an old tutorial for the old Cloud Code where they call the mailgun module like this

`
var client = require('cloud/myMailModule-1.0.0.js')
client.initialize('myDomainName','myApyKey')
`
and then they call the client functions. Does it work now the same way? I'm really lost in this topic since I'm completely new to servers, and node.js

I would really appreciate if someone can point me to the right direction

Thanks in advance, and sorry for my bad english

**Comment by drew-gross** [comment]
The same way should work just fine. If you run into errors, make sure the npm module you are `require` ing is in your `package.json`.
