### ISSUE TITLE
Parse Promise Then Handler Doesn't Crash With Error

### ISSUE THREAD

**Issue by btate** [ParsePlatform/parse-server#615]
When I experience a javascript error in my promise then handler my requests just hang.  No error shows up in the console and the code doesn't return.  

In a promise.then() handler just add this line. 

notarealvar.notarealthing();

The request just hangs.  If you wrap it in a try catch you can see an error.

**Comment by nlutsenko** [comment]
cc @andrewimm

**Comment by andrewimm** [comment]
This is part of the Promises/A+ spec. Thrown exceptions within the execution of a promise are caught by the promise, and passed to the next `error` callback.

If you want to catch the exceptions that have occurred up until a point, just provide an error callback to any `.then()` call. Or, if you want to avoid Promises/A+ compatibility, you can always disable it with `Parse.Promise.disableAPlusCompliant()`

**Comment by btate** [comment]
There is an error callback that just calls response.error(error).  But it was never called so the cloud code method never responded.

**Comment by andrewimm** [comment]
Code sample?

Keep in mind, if you do
```js
someTask().then( onSuccess, onError )
```
the error handler will catch exceptions from `someTask`, but will not catch exceptions from `onSuccess`

**Comment by btate** [comment]
Gotcha.  Yeah it's code in the onSuccess that's failing silently.

**Comment by andrewimm** [comment]
I tend to tack on a final `.fail((e) => ... )` callback to the entire chain to handle the errors in there (`fail(x)` is an alias for `then(null, x)`)
