### ISSUE TITLE
Renaming/Deleting table and fields

### ISSUE THREAD

**Issue by aziz92** [ParsePlatform/parse-server#617]
Is there anything I should know before renaming or deleting tables/fields in parse-server mongo database? Perhaps some configuration I need to update? etc? Please let me know. Thanks.

**Comment by drew-gross** [comment]
Yes. Parse Server expects info in the database to match the info in the _SCHEMA table. The schemas API (https://parse.com/docs/rest/guide#schemas) in Parse Server is in experimental, so you can use it, but doing a test run against a copy of your database first. You can also wait for the upcoming release of the dashboard.
