### ISSUE TITLE
Dealing with old sessions

### ISSUE THREAD

**Issue by aziz92** [ParsePlatform/parse-server#618]
It seems like parse-server only handles new revocable sessions (the one's that start with "r:"). My app didn't migrate to new sessions and so now, in Cloud Code, the request.user is null because of it. 

What are some solutions to this? Has anyone run into this issue?  Please chime in.

**Comment by drew-gross** [comment]
You will have to migrate to the new revocable sessions, we we currently have no plans to work on the old sessions. However, if you would like to work on it we would accept a Pull Request that adds it :)
