### ISSUE TITLE
Official Docker image ?

### ISSUE THREAD

**Issue by didierfranc** [ParsePlatform/parse-server#62]
It should be great to have an official docker image.

Unofficial and working image by @yongjhih :

[Github](https://github.com/didierfranc/docker-parse-server)
[Docker Hub](https://hub.docker.com/r/yongjhih/parse-server/)

I'm running that with official MongoDB, it's very fast and easy, in my opinion the best way to deploy Parse-Server ...

**Comment by didierfranc** [comment]
I made a quick guide to deploy it in minutes, it's in french but it's not so important with **screenshots** 😉

https://medium.com/@DidierFranc/parse-com-ferme-parse-s-ouvre-cd426118fbbd

**Comment by gfosco** [comment]
Added your guide to the community links section of the wiki. :+1:
