### ISSUE TITLE
afterSave error in saving that item

### ISSUE THREAD

**Issue by mahabubakram** [ParsePlatform/parse-server#620]
In the afterSave() of the cloud code whenever I try to save the item with some changes it does not do the changes on that item.

```
Parse.Cloud.afterSave("MyClass", function (request) {
    console.log("AFTER SAVE EXECUTED");
    var myToken = request.object;
    myToken.set("changed", 1);
    myToken.save(null,{
        useMasterKey: true,
        success: function(res){
        },
        error: function(err){
            console.log(err);
        }
    });
```

**Comment by simonbengtsson** [comment]
Updating the same object that triggered the afterSave will create an infinite loop. I tried your code now first in `parse-server` (added a `});` in the end). It simply printed the log messages like crazy in the terminal. As you mentioned before that it worked in parse.com I tried that as well. There I got `request timeout` and eventually `{"code"124,"message":"Too many recursive calls into Cloud Code"}` after a few loops. If you really do have to change a value in the afterSave you could do something like this:.

```js
Parse.Cloud.afterSave("Product", function (request) {
    var isUpdated = user.get('updatedAt').getTime() === user.get('createdAt').getTime();
    if (isUpdated) {
        return;
    }
    
    console.log("AFTER SAVE EXECUTED");
    var myToken = request.object;
    myToken.set("title", "title");
    myToken.save(null, {
        useMasterKey: true,
        success: function () {
            console.log('success');
        },
        error: function (obj, err) {
            console.log(err);
        }
    });
});
```

**Comment by gfosco** [comment]
Yeah, you don't want to save the object in the afterSave... that's one of the reasons you use a beforeSave, to change the object being saved.

**Comment by djkmiles** [comment]
The afterSave hook didn't cause recursion like this with Parse Cloud Code before it was open-sourced. Can I get any agreement this shouldn't happen with this server either?

**Comment by flovilmart** [comment]
> The afterSave hook didn't cause recursion like this with Parse Cloud Code before it was open-sourced. 

Yes it did.

**Comment by djkmiles** [comment]
Ok that's not agreement. I lately migrated a busy system that had push being sent on afterSave trigger and it set a flag [changed during beforeSave] to false so we had full data that a push had been sent.

The value was null, then true, picked up on afterSave, push was sent, then set to false using Parse.Object.save.

So that anecdote aside— the recursion is clearly unnecessary, therefore shouldn't occur. Object.save called with before or after triggers should not activate those triggers during the subsequent looping.

**Comment by flovilmart** [comment]
> So that anecdote aside— the recursion is clearly unnecessary, therefore shouldn't occur. Object.save called with before or after triggers should not activate those triggers during the subsequent looping.

As far as I can remember, it's been like that. 

And anecdotes aside, the save is completely stateless, as well as parse-server so there is no way to know the object went through a beforeSave/afterSave already.
