### ISSUE TITLE
Change of Content-Type in S3Adapter

### ISSUE THREAD

**Issue by mchun** [ParsePlatform/parse-server#628]
Is there any way to change the content-type when using S3Adapter? Images are all being downloaded instead of being viewed.

**Comment by flovilmart** [comment]
can you dump the response headers please?

**Comment by nlutsenko** [comment]
We actually use mime-type magic to reply with a nice and proper content-type, based on the path extension of the filename.
In addition to response headers - can you list a filename that you are downloading?

**Comment by mchun** [comment]
@flovilmart Is this what you want?

```
Access-Control-Allow-Headers:X-Parse-REST-API-Key, X-Parse-Javascript-Key, X-Parse-Application-Id, X-Parse-Client-Version, X-Parse-Session-Token, X-Requested-With, X-Parse-Revocable-Session, Content-Type
Access-Control-Allow-Methods:GET,PUT,POST,DELETE,OPTIONS
Access-Control-Allow-Origin:*
Connection:keep-alive
Content-Length:139
Content-Type:application/json
Date:Thu, 25 Feb 2016 03:34:02 GMT
Location:https://freesthdebugclone.s3.amazonaws.com/8ef9d2eac26f3d59f62142090728ca54_1.jpg
X-Powered-By:Express
```

**Comment by mchun** [comment]
The above file's filename is ustrobot.jpg and I am uploading it via the Parse Javascript SDK as the following:
`Parse.File(current+".jpg", { base64 : data }, "image/jpeg");`

**Comment by nlutsenko** [comment]
Yup, looks like we are overriding the content-type for some reason on replies on files. Sounds like a bug.

**Comment by nlutsenko** [comment]
Will dive deep early tomorrow...

**Comment by flovilmart** [comment]
@nlutsenko I'm on it!

**Comment by flovilmart** [comment]
@mchun should be fixed, try the master or wait for the next release!

**Comment by mchun** [comment]
Yes, working properly now. You are awesome @flovilmart, thanks a lot!

**Comment by flovilmart** [comment]
:tada:

**Comment by mchun** [comment]
um.....i found something...
the photo url is 
http://localhost:1337/parse/files/myAppId/6460437e918fe2719c5dbbd74474bd6c_1.jpg
instead of 
https://bucketname.s3.amazonaws.com/a733ce27cb257422ee70b6414e5afdd4_thumb.jpg
did I set it up wrongly?

**Comment by flovilmart** [comment]
Did you set the directAccess option?

**Comment by mchun** [comment]
Yes. I did not change my code when installing the latest master.
Just rename the existing parse-server folder inside node_modules
git clone parse-server
inside parse-server run npm install
then npm start.
Are these the correct steps?

**Comment by mchun** [comment]
And its strange that I can view the photo via the path http://localhost:1337/parse/files/myAppId/6460437e918fe2719c5dbbd74474bd6c_1.jpg
but I cannot find where the file is located in my computer...

**Comment by flovilmart** [comment]
these are not the correct steps: 

you should update `package.json` with

`parse-server: "parseplatform/parse-server"`

then run npm install.
If you files is hosted on S3, it's gonna be in you S3 bucket, if it's with the gridstore adapter, it's in the mongo database

**Comment by mchun** [comment]
Can install the master from github, but installed 2.1.4 anyway
Still the same result, new photos are being uploaded to gridstore instead of s3
And the paths of existing s3 uploaded photos are with prefix http://localhost:1337/parse/files/myAppId/, thus cant be showed correctly.

I followed the parse wiki on how to configure the s3 adapter, everythings work in 2.1.3 but not 2.1.4... :(
