### ISSUE TITLE
Bug in the get method of Query in cloud code

### ISSUE THREAD

**Issue by daviddayag** [ParsePlatform/parse-server#630]
For some reasons, in cloud code: 
if I get an object by it's ObjectId and then set it to the reference field of other object it duplicates the object put it entirely in the reference field instead of just setting it's reference.

here's my code (user is from request.object, shoutUser is the one i'm getting with query and "get"):

```
var userQuery = new Parse.Query('_User');
                userQuery.get("4GJ9QWcecT", {useMasterKey: true})
                    .then(function (shoutUser) {

                        var RefFollowerUser = Parse.Object.extend("RefFollowerUser");
                        var refFollowerUser = new RefFollowerUser();

                        setACLIfNull(refFollowerUser);

                        refFollowerUser.set("user", shoutUser);

                        refFollowerUser.set("follower", user);

                        return refFollowerUser.save(null, {useMasterKey: true});

                    });
```
So "user" object is set by reference, and "shoutUser" object is copied into the field entirely.
in Parse hosted server it works good, I mean I don't really know how the mongo objects look like, but the ui shows a reference to the user and not the entire json.

**Comment by daviddayag** [comment]
My gut feeling is that somehow the Equals method is different for parse objects than in the Parse hosted server.

**Comment by daviddayag** [comment]
Any progress on this?
If you need any other info please ask.

**Comment by daviddayag** [comment]
Hi guys. Any updates?

**Comment by nlutsenko** [comment]
@daviddayag We had few fixes around this issue in the last update. (specifically #619)
Can you try out 2.1.4 that was released a few hours ago?

Also, were you running 2.1.3 or a different version of a server?

**Comment by daviddayag** [comment]
Hi. 
I upgraded with the last release and now I'm facing different issues.
I keep getting "object not found." Error when trying to login with the android app. 
I checked and saw that this error comes from the database engine in parse-server.

**Comment by daviddayag** [comment]
any idea?

**Comment by daviddayag** [comment]
hi guys, did you get a chance to fix this new issue?

**Comment by flovilmart** [comment]
@daviddayag can you provide the requests logs by starting your server with VERBOSE=1 before the start command?

**Comment by drew-gross** [comment]
No response in many days, closing.

**Comment by daviddayag** [comment]
I Didn't see your response. Sorry. 
Yes I upgraded. 
I couldn't check because of the previous case #923.
