### ISSUE TITLE
MongoDb storage ?

### ISSUE THREAD

**Issue by thamer898** [ParsePlatform/parse-server#631]
How much MongoDb can store data ? on file system storage is it need any extra hard disk space ? how to handle extra data growth in future ?

**Comment by merowinger92** [comment]
Use external storage services like : https://mongolab.com

**Comment by thamer898** [comment]
I have a vps server but i want to know physical path of media files storage ?

**Comment by flovilmart** [comment]
mongoDB can store as much data as there is room on your VPS hard drive. I don,t think there is much overhead in terms of used space.

**Comment by thamer898** [comment]
can i integrate dropbox with mongodb storage ?

**Comment by flovilmart** [comment]
You could create a custom FilesAdapter that would use dropbox as a storage. 

PR and contributions are welcome.

**Comment by thamer898** [comment]
Thanks @flovilmart i just want to know the physical path of monogo db storage to link it with dropbox

**Comment by flovilmart** [comment]
the mongodb storage defaults to 'mongodb://localhost:27017/parse'

**Comment by thamer898** [comment]
great @flovilmart then where the files stored in parse folder ?

**Comment by flovilmart** [comment]
they are stored **in** the database. notice that the 'mongodb://localhost:27017/parse' is a URL passed to the mongodb driver to connect to the database. 
Mongodb itself managed the storage of files, I believe those files can't be accessed through the file system.

**Comment by thamer898** [comment]
okay great info i think that mongodb storage can be accessed by file system like Mysql but we should find a way to find physical location ?

**Comment by flovilmart** [comment]
I'm not sure it's gonna get you anywhere. If you wanna use dropbox, it would be easier to create an adapter for it so all the files are stored to and retrieved from it.

**Comment by thamer898** [comment]
that's hard am not an expert with that i think that will be great if any one can help us with that ?

**Comment by gateway** [comment]
btw if you have a parse app on parse.com you should make sure you have 3-5x more storage, due to compression of data on parse.com  .. I would also recommend storing images, files etc into a s3 bucket (its so freaking cheap).  Until parse works with MondoDB 3.2 which has WiredTiger in it (compresses your data in the db) you should make sure you have enough room on your server and esp room to grow.

**Comment by gfosco** [comment]
We give some guidance in our migration guide: https://github.com/ParsePlatform/parse-server/wiki/Migrating-an-Existing-Parse-App#1-migrate-parse-db-to-self-hosted-mongodb

Most of the available services offer scaling, when you need it.
