### ISSUE TITLE
Error initializing Parse in iOS client code.

### ISSUE THREAD

**Issue by astanton** [ParsePlatform/parse-server#641]
I'm in the middle of the migration process and at the point I'm trying to run my server locally.  I have the server up and running, and can hit it using CURL no problem, even hitting my db on mongolab.

However when I try to initialize Parse in my iOS app, it fails to connect.  My configuration looks like the following (with the real values in there):

```
Parse.initializeWithConfiguration(
  ParseClientConfiguration(block: { (configuration:ParseMutableClientConfiguration) -> Void in
    configuration.applicationId = "appId"
    configuration.clientKey = "clientKey"
     configuration.server = "http://localhost:1337/parse"
   })
)
```

However, whenever I have this line in my appdelegate normal initialization spot, I have the following erorrs in my console because it is failing to connect:

> 2016-02-24 22:45:24.061 TestApp[12580:2788400] [Error]: The operation couldn’t be completed. (NSURLErrorDomain error -1004.) (Code: 100, Version: 1.12.0)
> 2016-02-24 22:45:24.061 TestApp[12580:2788400] [Error]

It then continues to retry but obviously just continues to fail.  Again, I know it's up and running because I can query the database on mongolab running the CURL command and hitting the endpoint with the correct headers passed in.

I have been trying to figure this out all evening and haven't had any luck so I thought I would ask here.

Any ideas?

**Comment by drew-gross** [comment]
Your iOS device can't connect to your `localhost` because `localhost` means the same device (if you tried it on the simulator it would probably work)

Try exposing your `localhost` server through something like ngrok or pagekite.

**Comment by astanton** [comment]
@drew-gross thank you very much that worked.  I saw that step at the very end of the local-server installation, and I didn't know what ngrok was so I figured it was an npm install, and I installed it through npm but figured it was some library that was needed under the hood.  Didn't realize it was tunneling software.

Thanks again!
