### ISSUE TITLE
Query constraint on other query throws "improper usage of $inQuery"

### ISSUE THREAD

**Issue by Tibabal** [ParsePlatform/parse-server#646]
Hi,

Constraints based on results of other query doesn't seem to work in parse-server.
Simple iOS example (working with Parse.com):

    PFQuery *fooQuery = [FooObject query];
    
    PFQuery *barQuery = [BarObject query];
    [barQuery whereKey:@"innerFooObject" matchesQuery:fooQuery];

Throws 

    "Error Domain=Parse Code=102 \"improper usage of $inQuery\"

**Comment by gfosco** [comment]
Seems like we have a test which covers this: https://github.com/ParsePlatform/parse-server/blob/master/spec/ParseQuery.spec.js#L1457

Can you try with the latest version?

**Comment by Tibabal** [comment]
Still having the same problem with 2.1.4

**Comment by gfosco** [comment]
Please re-open if you still have this issue with 2.1.6+.

**Comment by Gagand** [comment]
Where is v 2.1.6+ version for iOS is available?? I'm getting latest v1.12.0 on parse.com(https://parse.com/docs/downloads) and v1.13.0 from github.

Where is v2.1.6 is available?

**Comment by Tibabal** [comment]
It's a parse-server version he was talking about, not parse-ios-sdk
