### ISSUE TITLE
2.0.1 not working

### ISSUE THREAD

**Issue by jpv123** [ParsePlatform/parse-server#65]
Not sure why, but i made this morning a migration to heroic with 2.0.0 and worked fine. Everything was as expected. I try to made everything the same again and the only changed I noted was that 2.0.1 was released. Now, Parse works correctly in localhost but as soon as I upload my code to Heroku I got an error that reads only

Failed at the myapp@0.0.0 start script 'node ./bin/www'.

Any ideas?

**Comment by gfosco** [comment]
Kinda sounds unrelated, the start script in your main project.

**Comment by jpv123** [comment]
This is my package.son

`{
  "name": "retiremax",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "body-parser": "~1.13.2",
    "cookie-parser": "~1.3.5",
    "debug": "^2.2.0",
    "express": "^4.13.4",
    "jade": "~1.11.0",
    "morgan": "~1.6.1",
    "parse-server": "^2.0.1",
    "serve-favicon": "~2.3.0"
  },
  "description": "retiremax server",
  "main": "app.js",
  "devDependencies": {},
  "author": "",
  "license": "ISC"
}
`

and this is my app.js
`var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');

var routes = require('./routes/index');
var users = require('./routes/users');

var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');

// uncomment after placing your favicon in /public
//app.use(favicon(path.join(__dirname, 'public', 'favicon.ico')));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', routes);
app.use('/users', users);

var api = new ParseServer({
  databaseURI: 'mongodb://jpv123:Password1@ds051625.mongolab.com:51625/retiremaxserver',
  cloud: 'parse-server/cloud/main.js', // Provide an absolute path
  appId: 'ABCDE12345678',
  masterKey: 'ABCDE123456789'
});

// Serve the Parse API on the /parse URL prefix
app.use('/parse', api);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

var port = process.env.PORT || 1337;
app.listen(port, function() {
  console.log('parse-server-example running on port ' + port + '.');
});

// error handlers

// development error handler
// will print stacktrace
if (app.get('env') === 'development') {
  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
      message: err.message,
      error: err
    });
  });
}

// production error handler
// no stacktraces leaked to user
app.use(function(err, req, res, next) {
  res.status(err.status || 500);
  res.render('error', {
    message: err.message,
    error: {}
  });
});


module.exports = app;
`

I'm sorry, I'm really new to node.js. Yesterday was my first day =(

**Comment by jpv123** [comment]
I found the problem. For anyone having this issue in the future, the packages.json start value must be like this:
"start": "node app.js"

Thank you for your help
