### ISSUE TITLE
Working fine with postman but not working with previous code

### ISSUE THREAD

**Issue by kapilkarda** [ParsePlatform/parse-server#654]
After migration it is not working when I tried with Postman I have to pass APP ID and Master Key in that but when I tried to work with Parse.initialize and Parse.serve it gives me unauthorized error

Please Help me in that.

**Comment by kapilkarda** [comment]
Even it is not working 
var TestObject = Parse.Object.extend("_User");
var testObject = new TestObject();
testObject.save({foo: "bar"}).then(function(object) {
  alert("yay! it worked");
});

**Comment by simonbengtsson** [comment]
If you are running the latest version of parse server the `unauthorized` error most likely means that the app id or keys are incorrect. Can you double check this? If they are correctly set can you post the request you are making with postman and your parse server config?

**Comment by kapilkarda** [comment]
Thanks @simonbengtsson for your reply,

Yes, I checked both both(Server side and Client Side) APP ID is same but I am still getting unathorized I think I have to pass MasterKey from client side becuase when I tried to call postman where I have to call MasterKey without maskerkey it doesn't work.

**Comment by simonbengtsson** [comment]
Strange! Can you share you server config and the request you are doing?

**Comment by kapilkarda** [comment]
Parse.initialize("APP_ID");
Parse.serverURL = 'https://blanc.herokuapp.com/parse';
var TestObject = Parse.Object.extend("_User");
var testObject = new TestObject();
testObject.save({foo: "bar"}).then(function(object) {
alert("yay! it worked");
});

**Comment by simonbengtsson** [comment]
Looks correct, what about the `parse-server` config?

**Comment by kapilkarda** [comment]
var api = new ParseServer({
  	databaseURI: databaseUri,
  	appId: 'XXXXXXXXXX',
  	masterKey: 'XXXXXXXXXX',
  	clientKey: 'XXXXXXXXXX',
  	serverURL: 'https://blanc.herokuapp.com/parse'
});

**Comment by simonbengtsson** [comment]
Try removing the clientKey.

**Comment by kapilkarda** [comment]
Yes, Its working.

Thank you Very Much @simonbengtsson
