### ISSUE TITLE
TypeError with command line argumens

### ISSUE THREAD

**Issue by vladtamas** [ParsePlatform/parse-server#659]
I'm getting an error when I try to run the application with command line arguments. Below you can find the command and the error:

F:\Work\parse-server>npm start -- --appId MYAPP --masterKey MASTER_KEY --serverURL http://localhost:1337/parse

> parse-server@2.1.3 start F:\Work\parse-server
> node ./bin/parse-server "--appId" "MYAPP" "--masterKey" "MASTER_KEY" "--serverURL" "http://localhost:1337/parse"

F:\Work\parse-server\lib\cli\parse-server.js:73
    options[key] = _commander2.default[key];
                 ^

TypeError: Cannot set property 'appId' of undefined
    at F:\Work\parse-server\lib\cli\parse-server.js:73:18
    at Array.reduce (native)
    at Object.<anonymous> (F:\Work\parse-server\lib\cli\parse-server.js:71:49)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (F:\Work\parse-server\bin\parse-server:2:1)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "--" "--appId" "MYAPP" "--masterKey" "MASTER_KEY" "--ser
verURL" "http://localhost:1337/parse"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! parse-server@2.1.3 start: `node ./bin/parse-server "--appId" "MYAPP" "--masterKey" "MASTER_KEY" "--serverURL" "http://localhost:1337/parse"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the parse-server@2.1.3 start script 'node ./bin/parse-server "--appId" "MYAPP" "--masterKey" "MASTER_KEY" "--serverURL" "http://localhost:1337/parse"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parse-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/parse-server "--appId" "MYAPP" "--masterKey" "MASTER_KEY" "--serverURL" "http://localhost:1337/parse"
npm ERR! You can get their info via:
npm ERR!     npm owner ls parse-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\Work\parse-server\npm-debug.log

**Comment by gfosco** [comment]
Will be fixed in 2.1.4 or you can pull the master copy.  Thanks for the report! :+1:
