### ISSUE TITLE
Parse Server on Pivotal Web Services

### ISSUE THREAD

**Issue by frodenas** [ParsePlatform/parse-server#66]
I'd appreciate it if a collaborator of this repo can add a pointer the [Hosting Parse Server on Pivotal Web Services](https://github.com/cf-platform-eng/pws-parse-server) to the [Wiki Community Links](https://github.com/ParsePlatform/parse-server/wiki#community-links). Thanks!

**Comment by gfosco** [comment]
Done. :+1:

**Comment by frodenas** [comment]
Thanks!
