### ISSUE TITLE
Posting file pointers to REST API

### ISSUE THREAD

**Issue by brandly** [ParsePlatform/parse-server#660]
Hey. We're transitioning onto `parse-server`. We had old code POSTing images to the REST API, immediately followed by POSTing data to another collection, with a pointer to that earlier image file.

When we were fully on Parse, before using `parse-server`, we supplied data like this:

```js
'imageObject': {
  'name': data.name,
  '__type': "File"
}
```

where only a `name` and a `__type` were necessary to define that relationship.

Once we moved to `parse-server`, this code was breaking. It boiled down to [this line](https://github.com/ParsePlatform/parse-server/blob/master/src/Schema.js#L731) which also looks for a `url`. We needed to change out the data we're POSTing to something like this:

```js
'imageObject': {
  'name': data.name,
  'url': data.url,
  '__type': "File"
}
```

Maybe this information could be provided in migration docs, since we didn't see it there.

It might also be worth mentioning that we're now using the `S3Adapter` to store our newly-created files in a bucket.

Thanks for everything! Overall, this migration is going far smoother than we could've expected.

cc @kyleseaman

**Comment by drew-gross** [comment]
I think we could probably just remove the check for the URL. @nlutsenko thoughts?

**Comment by nlutsenko** [comment]
Files are required to have a `url` at the moment of submitting them via REST API.
There are a lot of things that could go wrong when this is not true, like storage mechanisms or `beforeSave/afterSave` hooks. This is true for every single endpoint and is specified in the REST API guide.

All this comes down to the fact that file uniqueness is not enforced by `name`, but it is by `url`, meaning that all files can have duplicate names when they are stored.

This said, we could remove the limitation here, but I would actually recommend moving your file pointers to use a different system of pointers for files, or sticking a URL there might also be the case.

**Comment by drew-gross** [comment]
How would their code have worked on Parse.com then? Would the pointer have just referenced the most recent file with that name?

**Comment by nlutsenko** [comment]
Actually, I take it back - we do enforce uniqueness of files by name, so we might as well remove this restriction. And if we can't serve the file from a URL - then, yeah, that actually is absolutely fine, but to match it closer to api.parse.com - going to remove the restriction.
