### ISSUE TITLE
Can't get cloud code to work in Heroku server

### ISSUE THREAD

**Issue by taufiq-husain** [ParsePlatform/parse-server#664]
I've updated the following file **index.js** with just this part:

```
var api = new ParseServer({
  databaseURI: databaseUri || 'UPDATED-TO-MINE',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'UPDATED-TO-MINE',
  serverURL: process.env.SERVER_URL || 'https://myapp.herokuapp.com/parse',
  masterKey: process.env.MASTER_KEY || 'UPDATED-TO-MINE' //Add your master key here. Keep it secret!
});
```

After that if I even put a simple piece of cloud code in the **main.js** like this (this is all of it btw):

```
// Forgot Password
Parse.Cloud.define("forgot_password", function(request, response) {
	
}
```

The application fails. Any idea what I'm missing? If I take away the above code from the main.js file, the application works with the SWIFT iOS API. I simply can't seem to add any code to the main.js file nor create any meaningful functions there.

All the Heroku settings are up and working btw (that's why the Swift part of the app works). I simply can't use any cloud code functions.

**Comment by astanton** [comment]
Your sample code is missing a closing parenthesis for the opening (.  It's probably just a javascript syntax error.

Add a ) to the end of the code

```
// Forgot Password
Parse.Cloud.define("forgot_password", function(request, response) {

})
```

**Comment by gfosco** [comment]
Checking the server logs would be helpful in this case, it may explain what astanton said, that it's a syntax error.

**Comment by taufiq-husain** [comment]
Thanks. That wasn't the issue until I fixed the "serverurl" part I read from another thread.

**Comment by kukkadapukarhtik** [comment]
Parse.Cloud.define('sendEmail', function(request, response) {
var toUser=request.params.toUser;
var subject = request.params.subject;
var body = request.params.msgBody; 
    var sendgrid = require('sendgrid');
    sendgrid.initialize("username", "password");
           
    sendgrid.sendEmail({
        to: toUser,
        from: 'no-reply@commissionize.com',
        subject: subject,
        html: body
    }, {
    success: function(httpResponse) {
        console.log(httpResponse);
        response.success('Email sent!');
    },
    error: function(httpResponse) {
        console.error(httpResponse);
        response.error('Uh oh, something went wrong');
    }
    });
});


this is my cloud function ,but it is not working it says following eroor
[Error]: {"code":1,"message":"Internal server error."} (Code: 1, Version: 1.12.0)

**Comment by gfosco** [comment]
@kukkadapukarhtik You'll need to examine the server logs to find out the error... This issue is closed and unrelated, please open your own issue when you find more details.
