### ISSUE TITLE
Uncaught internal server error. bad value in untransformObject undefined

### ISSUE THREAD

**Issue by dhavalyours** [ParsePlatform/parse-server#665]
Hi,

I have 6 tables in parse. After migration  GET curl command is not working on one of the tables.
      curl -v -s GET \
        -H "X-Parse-Application-Id: 123" \
        -H "X-Parse-REST-API-Key: 123" \
            http://enterpriseparse.chatflyapp.com/parse/classes/ABC

Curl Response :

* Rebuilt URL to: GET/
* Could not resolve host: GET
* Closing connection 0
*   Trying 54.170.194.194...
* Connected to localhost port 1337 (#1)
> GET /parse/classes/ABC HTTP/1.1
> Host: localhost
> User-Agent: curl/7.43.0
> Accept: */*
> X-Parse-Application-Id:ABC
> X-Parse-REST-API-Key: ABC
> 
< HTTP/1.1 500 Internal Server Error
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET,PUT,POST,DELETE,OPTIONS
< Access-Control-Allow-Headers: X-Parse-REST-API-Key, X-Parse-Javascript-Key, X-Parse-Application-Id, X-Parse-Client-Version, X-Parse-Session-Token, X-Requested-With, X-Parse-Revocable-Session, Content-Type
< Content-Type: application/json
< Content-Length: 45
< ETag: "1759988501"
< Date: Fri, 26 Feb 2016 00:53:22 GMT
< Connection: keep-alive
< 
* Connection #1 to host localhost left intact

At the server end  I get following error :

Uncaught internal server error. bad value in untransformObject undefined

Also i was wondering whether this bug is related to https://github.com/ParsePlatform/parse-server/issues/165

I am using 2.1.3 version of parse server.

**Comment by gfosco** [comment]
We need to figure out what was the bad value... so if you can find the object in class ABC and provide it here, or maybe it will be obvious when looking at it...  In `transform.js` this error can be thrown if it thinks it received an undefined value, a symbol, or a function.

If you have only a few ABC objects, you can do GET queries on the object id URL to get single objects until you find one which fails... The details of that object would be useful in tracking down the error.

**Comment by dhavalyours** [comment]
Hi,

Below are the example objects which are passing and failing

Failing Objects
{
	"_id" : "XXXX",
	"chatflyUserId" : "XXX",
	"appId" : NumberLong("143222257992738511"),
	"_created_at" : ISODate("2015-05-21T15:39:49.678Z"),
	"_updated_at" : ISODate("2015-09-22T09:52:09.434Z"),
	"appStringId" : "XXXX"
}

{
	"_id" : "yyyy",
	"appId" : NumberLong("143153390003853950"),
	"chatflyUserId" : "yyyy",
	"_created_at" : ISODate("2015-05-25T14:01:40.570Z"),
	"_updated_at" : ISODate("2015-09-22T09:47:52.377Z"),
	"appStringId" : "yyyy"
}

{
	"_id" : "aaa",
	"appId" : NumberLong("aaa"),
	"chatflyUserId" : "aaa",
	"_created_at" : ISODate("2015-07-01T13:41:41.158Z"),
	"_updated_at" : ISODate("2015-09-22T09:12:34.254Z"),
	"appStringId" : "aaa"
}

Passing Objects :

{
	"_id" : "zzzz",
	"_created_at" : ISODate("2015-11-04T12:14:09.242Z"),
	"_updated_at" : ISODate("2015-11-04T12:18:19.261Z"),
	"appStringId" : "zzz",
	"profilePicture" : "tfss-25af6a2b-f097-4ef8-827e-88e8742ea340-file",
	"featured" : false,
	"published" : true,
	"screenName" : "XXX XXXÀÉÈÌÎÓÒÙùòóîìèéà50793",
	"description" : "Short xxxx"
}

These objects are working at parse endpoint.

Hope it helps

**Comment by gfosco** [comment]
Were these objects created through the parse api? api.parse.com or parse-server?  In the _SCHEMA collection, what is the schema type for the 'appId' column in this class?...

**Comment by dhavalyours** [comment]
Hi, 

1. These objects were created through parse api  before parse migration happened.
2.  In the parse.com website dashboard, the datatype if appId column is Number
3. I used following command on the table.
db.MyClass.find( {_id: "abc"}  ).pretty();

{
	"_id" : "xyz",
	"appId" : NumberLong("abc"),
	"chatflyUserId" : "aaa",
	"_created_at" : ISODate("2015-07-01T13:41:41.158Z"),
	"_updated_at" : ISODate("2015-09-22T09:12:34.254Z"),
	"appStringId" : "12345"
}


4. Following is result of db['system.indexes'].find()  from which have appId in them mongolab.
{
  "v": 1,
  "key": {
    "_id": 1,
    "appId": 1
  },
  "name": "_id_1_appId_1",
  "ns": "dbName.TableName",
  "background": true
}

{
  "v": 1,
  "key": {
    "_created_at": -1,
    "appId": 1
  },
  "name": "_created_at_-1_appId_1",
  "ns": "dbName.TableName",
  "background": true
}

 
{
  "v": 1,
  "key": {
    "_id": 1,
    "_created_at": -1,
    "appId": 1
  },
  "name": "_id_1__created_at_-1_appId_1",
  "ns": "dbName.TableName",
  "background": true
}
 
{
  "v": 1,
  "key": {
    "_id": 1,
    "appId": -1
  },
  "name": "_id_1_appId_-1",
  "ns": "dbName.TableName",
  "background": true
}

5. Also following is the result of  db.TableName.stats() of the table.

{
  "serverUsed": "XYZ",
  "ns": "dbName.tableName",
  "count": 267,
  "size": 93392,
  "avgObjSize": 349,
  "numExtents": 3,
  "storageSize": 172032,
  "lastExtentSize": 131072,
  "paddingFactor": 1,
  "paddingFactorNote": "paddingFactor is unused and unmaintained in 3.0. It remains hard coded to 1.0 for compatibility only.",
  "userFlags": 1,
  "capped": false,
  "nindexes": 14,
  "indexDetails": {},
  "totalIndexSize": 277984,
  "indexSizes": {
    "_id_": 8176,
    "_created_at_-1": 8176,
    "_created_at_-1_appId_1": 24528,
    "_created_at_-1_chatflyUserId_1": 8176,
    "_created_at_-1_featured_image_1": 24528,
    "_created_at_-1_screenName_1": 24528,
    "_id_1__created_at_-1_appId_1": 24528,
    "_id_1_appId_-1": 24528,
    "_id_1_appId_1": 24528,
    "_id_1_chatflyUserId_1": 24528,
    "_id_1_featured_image_1": 24528,
    "_id_1_screenName_-1": 24528,
    "appStringId_1": 24528,
    "tags_1": 8176
  },
  "ok": 1
}

**Comment by gfosco** [comment]
Sorry I didn't get back to you... Pretty unclear from these logs where the issue is.  It has been a while.  Please re-open this or open a new issue if you're still having trouble.  Thanks.

**Comment by zleman1593** [comment]
@dhavalyours  I am having a similar issue and still trying to figure out how to fix it.  What version of mongoDB were you using when this occurred? I am using 3.2.X and I just realized parse server doesn't recommend that version. Did you identify the cause?

**Comment by zleman1593** [comment]
I noticed that the objects that failed for me failed when interpreting the NumberLong BSON. It appears the same happens for you. I wonder if it is a WiredTiger issue.
