### ISSUE TITLE
How can I set up Parse Cloud Code as a scheduled jobs on Heroku?

### ISSUE THREAD

**Issue by taufiq-husain** [ParsePlatform/parse-server#668]
I know you guys said that you don't support scheduled jobs yet for the parse server but I was wondering if I could have a temporary solution if I want to port the app right away. If I create a function inside **main.js** and I want to call that function every day, how would I go about doing that on Heroku? Can you point me to the right direction?

**Comment by gfosco** [comment]
You can take a look at the heroku scheduler addon: https://devcenter.heroku.com/articles/scheduler

With it, you can run a simple standalone node script (not run a function from main.js) and perform your logic there.
