### ISSUE TITLE
How long does Migration process take?

### ISSUE THREAD

**Issue by talkaboutdesign** [ParsePlatform/parse-server#67]
Been stuck like this for about 10 min.
<img width="749" alt="screenshot 2016-01-29 21 13 22" src="https://cloud.githubusercontent.com/assets/2926534/12692944/2d7b2b24-c6cd-11e5-9d3d-cf44eed24931.png">

**Comment by jpv123** [comment]
I think the migration service is not working =( I'm having the same problem for a few hours now

**Comment by talkaboutdesign** [comment]
Oh well.

**Comment by gfosco** [comment]
Checking on this...

**Comment by gfosco** [comment]
There is a queue, and it's processing things in turn... Looks like everything is okay, but we will look at raising the concurrency.
