### ISSUE TITLE
Suggested Deadline

### ISSUE THREAD

**Issue by kenglou** [ParsePlatform/parse-server#671]
Is the suggested deadline for migrating is just a really suggestion and won't really affect on the service of Parse Backend? Just to clarify since It's a bit early for migrating Database into own hosted one. We might want to do more testing since we are thinking to craft our own DB servers in AWS.

**Comment by drew-gross** [comment]
The deadline is a suggested deadline as we expect that transitioning to the open source Parse Server will be the most difficult part and you should allocate most of the remaining time to that. The Parse.com service will, however, remain fully operational until January of next year.
