### ISSUE TITLE
parse Query return nothing

### ISSUE THREAD

**Issue by mahabubakram** [ParsePlatform/parse-server#676]
```
    Parse = require ('parse/node');

    var Layer2 = Parse.Object.extend("MyTokens_Layer2");

    var query = new Parse.Query(Layer2);
    query.equalTo("name", "Line of Oslo Tunika - paisley");
    query.limit(100);
    console.log(query);
    query.find({
        useMasterKey: true
    }).then(function(obj){
        console.log(obj)
    });
```

In the console log the query is printed but in the promise the objects are not printed. But in the database I have the objects with this "name"

**Comment by gfosco** [comment]
Where are you running this from?  I don't see parse being initialized or the server url set, and if it's in cloud code you shouldn't re-define Parse..   Add an error handler to that promise and log any error:

```
query.find({ useMasterKey: true }).then((results) => {
  console.log(results);
}, (error) => {
  console.log(error);
});
```

**Comment by mahabubakram** [comment]
I am running this:

    ```
query.find({ useMasterKey: true }).then(function(results) {
        console.log(results);
    }, function(error) {
        console.log(error);
    });
```

and in the index.js I have initialized:

```
var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var S3Adapter = require('parse-server').S3Adapter;
var cors = require('cors');

```

**Comment by gfosco** [comment]
Add the error handler I mentioned above and let me know what you get..

**Comment by mahabubakram** [comment]
@gfosco 

Right now my server is crashed. 
1. I have updated the parser server to 2.1.3 in package json
2. and also updated node version to >= 4.3

after that I deploy the server then it crashed. 

And in the crash it says :+1: 

←[36m2016-02-26T11:43:14.075456+00:00 heroku[web.1]:←[0m Starting process with command `npm start`
←[36m2016-02-26T11:43:16.461005+00:00 app[web.1]:←[0m
←[36m2016-02-26T11:43:16.461027+00:00 app[web.1]:←[0m > parse-server-example@1.0.0 start /app
←[36m2016-02-26T11:43:16.461029+00:00 app[web.1]:←[0m > node index.js
←[36m2016-02-26T11:43:16.461030+00:00 app[web.1]:←[0m
←[36m2016-02-26T11:43:18.287736+00:00 app[web.1]:←[0m
←[36m2016-02-26T11:43:18.287780+00:00 app[web.1]:←[0m /app/node_modules/parse-server/lib/requiredParameter.js:8
←[36m2016-02-26T11:43:18.287783+00:00 app[web.1]:←[0m   throw errorMessage;
←[36m2016-02-26T11:43:18.287784+00:00 app[web.1]:←[0m   ^
←[36m2016-02-26T11:43:18.287812+00:00 app[web.1]:←[0m You must provide a serverURL!
←[36m2016-02-26T11:43:18.305651+00:00 app[web.1]:←[0m
←[36m2016-02-26T11:43:18.312689+00:00 app[web.1]:←[0m npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
←[36m2016-02-26T11:43:18.313867+00:00 app[web.1]:←[0m npm ERR! npm  v2.1.18
←[36m2016-02-26T11:43:18.314142+00:00 app[web.1]:←[0m npm ERR! code ELIFECYCLE
←[36m2016-02-26T11:43:18.314342+00:00 app[web.1]:←[0m npm ERR! parse-server-example@1.0.0 start: `node index.js`
←[36m2016-02-26T11:43:18.314980+00:00 app[web.1]:←[0m npm ERR! Failed at the parse-server-example@1.0.0 start script 'node index.js'.
←[36m2016-02-26T11:43:18.315209+00:00 app[web.1]:←[0m npm ERR! This is most likely a problem with the parse-server-example package,
←[36m2016-02-26T11:43:18.316195+00:00 app[web.1]:←[0m npm ERR! Tell the author that this fails on your system:
←[36m2016-02-26T11:43:18.316872+00:00 app[web.1]:←[0m npm ERR!     npm owner ls parse-server-example
←[36m2016-02-26T11:43:18.321549+00:00 app[web.1]:←[0m npm ERR! Please include the following file with any support request:
←[36m2016-02-26T11:43:18.312195+00:00 app[web.1]:←[0m npm ERR! Linux 3.13.0-77-generic
←[36m2016-02-26T11:43:18.312981+00:00 app[web.1]:←[0m npm ERR! node v5.6.0
←[36m2016-02-26T11:43:18.314549+00:00 app[web.1]:←[0m npm ERR! Exit status 1
←[36m2016-02-26T11:43:18.314769+00:00 app[web.1]:←[0m npm ERR!
←[36m2016-02-26T11:43:18.315406+00:00 app[web.1]:←[0m npm ERR! not with npm itself.
←[36m2016-02-26T11:43:18.316493+00:00 app[web.1]:←[0m npm ERR!     node index.js
←[36m2016-02-26T11:43:18.316690+00:00 app[web.1]:←[0m npm ERR! You can get their info via:
←[36m2016-02-26T11:43:18.317061+00:00 app[web.1]:←[0m npm ERR! There is likely additional logging output above.
←[36m2016-02-26T11:43:18.321233+00:00 app[web.1]:←[0m
←[36m2016-02-26T11:43:18.321732+00:00 app[web.1]:←[0m npm ERR!     /app/npm-debug.log
←[36m2016-02-26T11:43:19.162771+00:00 heroku[web.1]:←[0m State changed from starting to crashed
←[36m2016-02-26T11:43:19.150091+00:00 heroku[web.1]:←[0m Process exited with status 1

**Comment by gfosco** [comment]
You must provide a serverURL property in index.js when creating the ParseServer instance.  This should be the heroku address plus the mount, i.e. 

```
... = new ParseServer({
  ...,
  serverURL: 'https://myapp.herokuapp.com/parse'
});
...

**Comment by mahabubakram** [comment]
Thanks @gfosco serverURL is working.

But for the query it still returns nothing.


my code is:

```
    var Layer2 = Parse.Object.extend("MyTokens_Layer2");

    var query = new Parse.Query(Layer2);
    query.equalTo("name", "Line of Oslo Tunika - paisley");
    query.limit(100);
    console.log(query);
    query.find({
        useMasterKey: true,
        success: function(results){
            console.log(results);
        },
        error: function(err){
            console.log(err);
        }

    });
```

And it returns only this:

←[36m2016-02-26T13:41:19.692453+00:00 app[web.1]:←[0m Token Layer 1 before Save executed
←[36m2016-02-26T13:41:19.725183+00:00 app[web.1]:←[0m ParseQuery {
←[36m2016-02-26T13:41:19.725200+00:00 app[web.1]:←[0m   className: 'MyTokens_Layer2',
←[36m2016-02-26T13:41:19.725202+00:00 app[web.1]:←[0m   _where: { name: 'Line of Oslo Tunika - paisley' },
←[36m2016-02-26T13:41:19.725203+00:00 app[web.1]:←[0m   _include: [],
←[36m2016-02-26T13:41:19.725204+00:00 app[web.1]:←[0m   _skip: 0,
←[36m2016-02-26T13:41:19.725204+00:00 app[web.1]:←[0m   _limit: 100,
←[36m2016-02-26T13:41:19.725205+00:00 app[web.1]:←[0m   _extraOptions: {} }
←[36m2016-02-26T13:41:19.710651+00:00 app[web.1]:←[0m afterSave executed for Layer 1

**Comment by gfosco** [comment]
Since this is in a beforeSave, you want to wait for it to finish before continuing... try this:

```
Parse.Cloud.beforeSave('MyTokens_Layer2', function(request, response) {
  // ...
  var query = new Parse.Query('MyTokens_Layer2');
  query.equalTo("name", "Line of Oslo Tunika - paisley");
  query.limit(100);
  query.find({ useMasterKey: true }).then((results) => {
    console.log('query succeeded', results);
    response.success();
  }, (error) => {
    console.log('query failed', error);
    response.error(error);
  });
});
```

**Comment by mahabubakram** [comment]
@gfosco 

I am doing this thing

```
Parse.Cloud.afterSave("MyTokens_Layer1", function (request) {
    console.log("afterSave executed for Layer 1")

    var Layer2 = Parse.Object.extend("MyTokens_Layer2");
    var query = new Parse.Query('MyTokens_Layer2');
    query.equalTo("name", "Line of Oslo Tunika - paisley");
    query.limit(100);
    query.find({ useMasterKey: true }).then(function(results) {
        console.log('query succeeded', results);
    }, function(error) {
        console.log('query failed', error);
    });

});
```

But it only prints afterSave executed for Layer 1. Other than that it prints nothing.

**Comment by mahabubakram** [comment]
thanks now its working. Thanks a lot for the support. Thanks a lot.
