### ISSUE TITLE
Parse Server / IOS - include Key has different results after migration

### ISSUE THREAD

**Issue by spanapaul** [ParsePlatform/parse-server#677]
The following query works prior to migration but not post migration in MongoLabs for selected records only

PFQuery *drillResultsQuery = [GradingDrillResult query];
    [drillResultsQuery whereKey:@"parentEvent" equalTo:self.currentEvent];
    [drillResultsQuery includeKey:@"parentDrill"];               //returns no data in the object
    [drillResultsQuery includeKey:@"parentPerson"];          // works ok
    [drillResultsQuery includeKey:@"parentEventInvite"];   // works ok
    [drillResultsQuery orderByAscending:@"firsttName,lastName,parentDrillType"];

Using the parse data browser the link works ok and also in mongoldb the id appears correct. However, the parentDrill data has 0 data elements when queried via parse server and mongoldb

**Comment by gfosco** [comment]
If you can troubleshoot this further, that would be great.  Run the server with the environment variable VERBOSE=1 and capture the request for the query.

**Comment by jackdewhurst** [comment]
I'm having this problem too, "includeKey" on a PFRelation query returns pointers with no data.

If point back from my Heroku Parse Server instance to parse.com then the same query works fine on the same database.

**Comment by spanapaul** [comment]
My problem turned out to be a data related problem with one record which was created in a previous version. I recreated this record and it worked ok
Paul

**Comment by ryderjack** [comment]
Same problem as @jackdewhurst. Query returns pointers with no data despite using 'includeKey'.

**Comment by drew-gross** [comment]
This issue is getting old, and it seems like some people have solved this issue. If you are still seeing this problem, can you open a new issue and include some consistent repro steps?

**Comment by Raminder123** [comment]
Hello,
After deployment of parse server to heroku....my app is not running successfully.It always gives me the following error.

Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}

Please help me out here

Thanks 
Raminder
