### ISSUE TITLE
How can i add in AWS Beanstalk for S3Adapter?

### ISSUE THREAD

**Issue by json-park** [ParsePlatform/parse-server#681]
I was set up on  AWS Beanstalk

http://mobile.awsblog.com/post/TxCD57GZLM2JR/How-to-set-up-Parse-Server-on-AWS-using-AWS-Elastic-Beanstalk

However I can't find Property Value text boxes on Beanstalk Configuration for S3Adapter

https://github.com/ParsePlatform/parse-server/wiki/Storing-Files-in-AWS-S3#using-the-s3adapter

  "AWS_ACCESS_KEY_ID",
  "AWS_SECRET_ACCESS_KEY",
  "BUCKET_NAME",

Where do I add these?

![1](https://cloud.githubusercontent.com/assets/16973070/13354513/d590b316-dcde-11e5-8f16-962836801b84.png)

**Comment by gfosco** [comment]
These keys, along with identifying that you want to use the S3 Adapter, are set in the javascript source for the application, in the ParseServer constructor.  see the "ADVANCED: Updating and Deploying your code" section of that EB guide, and download the code.  Then see the s3 adapter instructions: https://github.com/ParsePlatform/parse-server/wiki/Storing-Files-in-AWS-S3 and re-deploy your project.
