### ISSUE TITLE
Parse migration only migrating 1000 records

### ISSUE THREAD

**Issue by rs91092** [ParsePlatform/parse-server#685]
I tried to migrate parse db to my mongodb running in ec2 instance , but i can only see 1000 records for a class in my mongo instance. I have 6 classes with 3 clases having more than 1000 records and all of them only show  1000 records. So if anyone can help me out here.

**Comment by gfosco** [comment]
Where are you looking and only seeing 1000?

**Comment by rs91092** [comment]
in my mongodb ......... i am using db.getCollection('clssname').count() --- gives 1000 only

**Comment by gfosco** [comment]
You'll need to open a migration bug from http://parse.com/help  Find the bug icon / contact us link.
