### ISSUE TITLE
Error [13] Timed out when deploying to App Engine

### ISSUE THREAD

**Issue by otymartin** [ParsePlatform/parse-server#687]
I've made several attempts to deploy parse server on app engine using the Medium guide and i can't get passed this error.

`Beginning teardown of remote build environment (this may take a few seconds). Updating module [default]...|Deleted [https://www.googleapis.com/compute/v1/projects/##################]. Updating module [default]...failed. ERROR: (gcloud.preview.app.deploy) Error Response: [13] Timed out when starting VMs. It's possible that the application code is unhealthy. (0/2 ready, 2 still deploying). My-MacBook-Pro-2:appName-server myMacName$`

`Typing the above URL into the browser I get this
[{ "error": { "errors": [ { "domain": "global", "reason": "required", "message": "Login Required", "locationType": "header", "location": "Authorization" } ], "code": 401, "message": "Login Required" } }]`

Fyi when I created my project in google cloud, I specified "USEast" but when I was deploying, I noticied the URL had `us-central1-f`

**Comment by otymartin** [comment]
My cloud code destination was misplaced I fixed it

`cloud: __dirname + '/cloud/main.js',`

**Comment by RaschidGithub** [comment]
So what exactly did you write instead of `__dirname`?

**Comment by otymartin** [comment]
@RaschidGithub I didnt have the __dirname included

**Comment by RaschidGithub** [comment]
I mean, what was the final resulting code line in your case? @otymartin. 
In my script I've still got `cloud: '/cloud/main.js'`, but I don't know what shoul it look like with the dirname included.

**Comment by otymartin** [comment]
@RaschidGithub 
Sorry for the confusion. This should be the final code in your `server.js` file
```javascript
cloud:  __dirname + '/cloud/main.js',
```
Alternatively I notice the latest server released changed the syntax abit.

So in my config.json i have
```javascript
  "CLOUD_PATH": "./cloud/main.js",
```
and in my server.js I have
```javascript
  cloud: nconf.get('CLOUD_PATH') || __dirname + '/cloud/main.js',
```

**Comment by RaschidGithub** [comment]
Great. I'll try that. Thanks :+1:
