### ISSUE TITLE
Parse Array of Pointers Saving Differently

### ISSUE THREAD

**Issue by KevinNuut** [ParsePlatform/parse-server#691]
We have not migrated and are still using a combination of development and production databases on Parse. We have an array of pointers column on our _User class. It used to be that calling Parse.addUnique("students", StudentObj); would save a reference pointer to the students but now the server seems to be populating the array with the full objects of each "student" _User class.

Additionally, this is causing a series of problems because calling "include" on _User for the students array of pointers is now simply returning an assorted array with some rows only having an ObjectID and some having a full (but out of date) object. What happened to the proper reference pointer logic?

**Comment by nlutsenko** [comment]
Are you guys using `beforeSave` by any chance?

**Comment by nlutsenko** [comment]
Also, could you add more details on how you are communicating with the server.
Are you using any SDK, if yes - which platform?

Also, would be amazing if you could provide the version of your Parse Server.

**Comment by KevinNuut** [comment]
We do not use beforeSave. We use the JS SDK (1.5.0) and the iOS SDK (I'll get that version info tomorrow). We have not migrated yet so we are not using the open source Parse Server yet. This seems to exclusively affect the _User class with columns that are arrays of pointers. The same addUnique() technique is being used on other classes we have with arrays of pointers, and they save a reference pointer object as expected. The _User class seems to be auto filling in the objects, even if I pass a stubbed object with just the _id.

**Comment by nlutsenko** [comment]
Do you see the behavior being triggered from JS or iOS?
This sound super strange and since you are not using a Parse Server - I would recommend opening an issue on the relevant repo instead, but we can continue here.

**Comment by gfosco** [comment]
Seconding what Nikita said, if this is not parse-server related, please open an issue on the relevant SDK repo or report a bug through http://parse.com/help

Thanks.
