### ISSUE TITLE
Cannot stream a video from PFFile URL iOS

### ISSUE THREAD

**Issue by Liquicit** [ParsePlatform/parse-server#692]
Hello,

First of all, the code I use to try stream a PFFile video with its URL works %100 fine using Parse, however when I switch to using heroku I cannot stream the PFFile video. 

When using the `AVPlayerViewController` it comes up with a crossed out play button. 

This is an example of what the url looks like from heroku - `http://appname.herokuapp.com/parse/files/appname/a5886e0be65d6fe59cace6c12113572c_file.mp4`

Everything else works fine, saving photos as PFFiles and retrieving them and saving normal PFObjects.

It seems it might be something to do with the PFFile url is not recognised by the parse server api because it expects a different formatted string to the one heroku gives? 

This issue has been here for about 2 months and still no fix. Any help greatly appreciated!

**Comment by nathan-savvy** [comment]
Can you access the URL in your browser?

http://stackoverflow.com/questions/tagged/parse-server is another place you can ask this question.

**Comment by Liquicit** [comment]
Yes I can, I can watch the video using Google Chrome with the exact same link I try to use with heroku and parse server, yet on iOS it doesn't work?

**Comment by dhavalyours** [comment]
Hi,

I tried to access your video link in chrome it is not working.  Also Can you try streaming your video with https link ? Does your iOS project accept http links ? You might need to add some settings in your ios project to accept non-ssl urls.

**Comment by Liquicit** [comment]
Hi, First that is a fake link because the video was a bit of a personal one. Second I know it accepts https because when I use Parse (The one that is closing down, not a custom server) it streams perfectly and is a https link.

**Comment by nlutsenko** [comment]
Can you get us any video with a working link? 
I can test the streaming end of iOS e2e.

**Comment by rosarioconti** [comment]
Is that the correct link with appname ?

**Comment by nlutsenko** [comment]
Doesn't seem to be, that's why I asked for a full link.

**Comment by gfosco** [comment]
Closed for lack of activity.

**Comment by dpaid** [comment]
Hi, 

Same problem here. Parse server on AWS ElasticBeanstalk cannot stream mp4 pffile saved on mongoDB on AWS EC2. Video plays on chrome but does not play on Safari or iOS app. Videos hosted on parse service play with no problem. 

iOS error:

Error Domain=AVFoundationErrorDomain Code=-11850 "Operation Stopped" UserInfo={NSUnderlyingError=0x13fb86740 {Error Domain=NSOSStatusErrorDomain Code=-12939 "(null)"}, NSLocalizedFailureReason=The server is not correctly configured., NSLocalizedDescription=Operation Stopped}

Any help?
Thanks in advance :)

**Comment by dpaid** [comment]
Using the S3 file adapter fixed it!

**Comment by ryanchan002** [comment]
I have the same issue as well :(

We currently are using the S3 adapter, setting the content-type, with no luck.... There is just a gray play button without anything playing. You can stream from a browser fine, but when trying to access it from iOS it's not working

**Comment by indiandragon** [comment]
So, heroku+mlab support doesn't work anymore ? Only choice is to use heroku+S3 ? Doesn't mlab internally uses s3 for storing files. I'm not even sure whether parse-server supports streaming anymore.

**Comment by ryanchan002** [comment]
Not even trying to stream. Our application is fine downloading the content and playing, but still no luck. 

Anyone find any resolution yet?

**Comment by manishsangwan** [comment]
We are having the same issue with iOS.
We are using S3 adapter for file storage and are hosting parse server on amazon ec2 instance and using mlab as database service. the files get saved on s3 bucket and get downloaded but do not stream on iOS.

**Comment by indiandragon** [comment]
@manishsangwan Doesn't stream on iOS app or in iOS safari ? Because it does stream inside iOS app using Parse sdk for us & not in Safari OX/iOS . It streams fine in Chrome & Firefox.  If feasible, can you host a sample file in S3 itself and point to it from parse server instead of mLab; as mLab seems to be the common variable in all these issues.

**Comment by indiandragon** [comment]
[Solved] The solution is given by @Bragegs here - https://github.com/ParsePlatform/parse-server/issues/1440#issuecomment-212815625 . In short, parse-server doesn't seem to be supporting streaming of audio/video and @Bragegs code enables it. I hope it get's PR and parse team looks into it.

**Comment by otymartin** [comment]
@indiandragon  is there a solution for Google cloud storage?

**Comment by manishsangwan** [comment]
The solution is for gridstoreadapter. but  its not working for S3Adapter.

**Comment by flovilmart** [comment]
Use direct access and it should be ok.

**Comment by manishsangwan** [comment]
Can you please expain the direct acces a bit. thanx for the qwik response.

**Comment by manishsangwan** [comment]
this is my configuration
filesAdapter: new S3Adapter(
        settings.s3AccessKey,
        settings.s3SecretKey,
        settings.s3BucketName,
        settings.s3RegionName,
        {directAccess: true}
    )

**Comment by manishsangwan** [comment]
i have already enabled directAccess

**Comment by manishsangwan** [comment]
Whats strange is {directAccess: true} is not working and if i fetch value from environment the direct access is implemented but imaged uploaded earlier return 403.

**Comment by HackShitUp** [comment]
Any news on this? I'm still having difficulty saving videos to AWS hosting MongoDB with Parse Server. Also, I haven't migrated yet -- just testing out with a cloned database from Parse.com (I procrastinate a lot and yea I know I'm kind of fucked).
