### ISSUE TITLE
Support for the SDK's future

### ISSUE THREAD

**Issue by kevinjpetersen** [ParsePlatform/parse-server#7]
Now with the soon to come (1 year) retirement of Parse, what will this mean for SDK's in general? Will you continue to have these available and up-to-date? Will the SDK's and Parse-Server be further developed overtime, or does "Retirement" mean what it means, retirement / complete stop of further development?

**Comment by davidhsv** [comment]
My first thought either...

**Comment by yamill** [comment]
+1

**Comment by Harsha93** [comment]
I am guessing they will be leaving it as it is on this account and people who are interested to maintain it will start contributing. If this is not the case then i don't know how.?

**Comment by icefall** [comment]
+1

**Comment by gfosco** [comment]
The SDKs aren't going anywhere, ever, and will continue to be updated.. not only for bug fixes and security, but there are still some features in the works.  Eventually, I believe we & the community will evolve the Parse server and client SDKs beyond what was previously capable with just Parse.

**Comment by andhieka** [comment]
@gfosco Does the termination of Parse service has anything to do with difficulty of scaling Parse to support more users? I'm still trying to wrap my brain around this sudden announcement.

**Comment by gfosco** [comment]
No, it definitely wasn't about that.  I think it makes sense in a way, financially, and have come to accept it.

**Comment by lacker** [comment]
FWIW, if you are curious about "why", I think this NYT article has the best explanation out there.

http://bits.blogs.nytimes.com/2016/01/28/facebook-to-shut-down-parse-its-platform-for-mobile-developers/

**Comment by andhieka** [comment]
@gfosco @lacker Thanks for enlightening me! :+1:
