### ISSUE TITLE
Parse Cloud Issue

### ISSUE THREAD

**Issue by pazalvin** [ParsePlatform/parse-server#70]
Can someone help me to fix this?

**This is my cloud code:**
var Parse = require('parse/node').Parse;

Parse.Cloud.define('Hello', function(req, res) {
  res.success('Hi');
});

**This is the errror:**
Parse.Cloud.define('Hello', function(req, res) {
            ^
TypeError: Parse.Cloud.define is not a function

**Comment by pazalvin** [comment]
can someone send me their skeleton app so i can follow :p i tried what's in the documentation but same error occurs on my side please help me

**Comment by gfosco** [comment]
In the cloud code file, you shouldn't define Parse, it is set as a global by ParseServer (and it is mutated to add that method.)
