### ISSUE TITLE
Can not set ACL in cloud code for new User

### ISSUE THREAD

**Issue by sanergulec** [ParsePlatform/parse-server#701]
Hello, I try to set the ACL of a new created user that has the read and write permission only by the user. For objects in the other tables I do not have any problem setting the ACL as I am using "beforeSave". But for the user I can not use the "beforeSave" as the user is not created yet. I tried lots of different combinations, but couldn't make it work. The last that I tried is the code below. But it didn't worked either.
Maybe when the "afterSave" function starts in the cloud, the user is not created yet and for this reason the ID can not be set as permission, I don't know. Is there anyone who knows how the set the ACL for a new user only permission to that user? 

```
Parse.Cloud.afterSave(Parse.User, function(req) {

    if (!req.user.existed()) {

    var acl = new Parse.ACL();
    acl.setReadAccess(req.user, true);
    acl.setWriteAccess(req.user, true);
    req.user.setACL(acl);
    req.user.save();

    }
  
});
```

**Comment by Kira2** [comment]
Hi,

You are right, you have to use afterSave to set the permission of the user. But I think the problem is that you try to to use **req.user** instead of **req.object**. Indeed, when you use afterSave on Parse.User class, your user is stored into **req.object**.

Try this, it might work:

```javascript
Parse.Cloud.afterSave(Parse.User, function(req) {

  if (!req.object.existed()) {
    var user = request.object;
    var acl = new Parse.ACL(user);
    user.setACL(acl);
    user.save();
  }
});
```

Hope it helps.

**Comment by stalehard** [comment]
Hi,
I have same problem with self-hosted Parse-server:
After save new Parse.User object I set ACL for this user:

1 variant
```javascript
newUser.signUp(null, { useMasterKey: true })
    .then(
        (user) => {
            let acl = new Parse.ACL(user);                      
            user.setACL(acl);
            user.save();
        },
        (error) => {

        }
    );
```
2 variant
```javascript
newUser.signUp(null, { useMasterKey: true })
    .then(
        (user) => {
            let acl = new Parse.ACL();
            acl.setReadAccess(user.id, true);
            acl.setWriteAccess(user.id, true);
            acl.setPublicReadAccess(false);
            user.setACL(acl);
            user.save();
        },
        (error) => {

        }
    );
```
But in both case in mongoDB i see for this record:
"_id" : "mwlCdr4GtU", "_rperm" : [ "mwlCdr4GtU", "*" ], "_wperm" : [ "mwlCdr4GtU" ]

Why in read permission "*"?

**Comment by flovilmart** [comment]
@stalehard do you still have the issue? (we just released 2.1.6). Also, can you get the result of user.save(), wether it succeeds or fails? Thanks!

**Comment by jsoendermann** [comment]
I have the same problem, my new (anonymous) users are created with an ACL that enables public reads.

With

`Parse.Cloud.afterSave(Parse.User, function(req) {
  console.log('afterSave: ' + JSON.stringify(req.object));

  if (!req.object.existed()) {
    var user = req.object;
    var acl = new Parse.ACL(user);
    user.setACL(acl);
    user.save({useMasterKey: true}).then(function (s) {
      console.log('Success: ' + JSON.stringify(s));
    }, function(e) {
      console.log('Error: '+ JSON.stringify(e));
    })
  }
});`

in my cloud code, I get

`afterSave: {"ACL":{},"authData":{"anonymous":{"id":"64815a5b-b412-4d17-a224-..."}},"username":"bc6416c986b1bba70c0...","createdAt":"2016-03-13T13:39:45.660Z","sessionToken":"r:e073f65614ca...","updatedAt":"2016-03-13T13:39:45.660Z","objectId":"zfom..."}
Error: {"code":206,"message":"cannot modify user zfom..."}`

**Comment by drew-gross** [comment]
@jsoendermann I've attempted to reproduce this issue in #1281, but I wasn't able to reproduce. Can you look at that PR and tell me if you are doing anything differently from how that test works? If not, try updating your server version, your dashboard version, and refreshing the dashboard page. If you still have problems, please open a new issue with the repro steps.

**Comment by haroot** [comment]
Here is what worked for me fo the latest parse. Apparently, by default User rows are open to Public Read...

async function CreateParseUser(username, password, email, phone, isPro) {
  var user = new Parse.User();
  user.set("username", username);
  user.set("password", password);
  user.set("email", email)
  user.set("phone", phone);
  user.set("isPro", isPro);
  await user.signUp(null, {
    success: function(user) {
      // Hooray! Let them use the app now.
      console.log("User created! ", user.id, user);
      let acl = new Parse.ACL();
      acl.setReadAccess(user.id, true);
      acl.setWriteAccess(user.id, true);
      acl.setPublicReadAccess(false);
      user.setACL(acl);
      user.save(null, {useMasterKey: true});
    },
    error: function(user, error) {
      // Show the error message somewhere and let the user try again.
      console.log("Error: " + error.code + " " + error.message);
    }
  });
}
