### ISSUE TITLE
"The data couldn’t be read because it isn’t in the correct format"

### ISSUE THREAD

**Issue by otymartin** [ParsePlatform/parse-server#717]
I'm using Google App Engine and MongoLab.

Why won't this work? :(

<img width="914" alt="screen shot 2016-02-28 at 4 56 26 pm" src="https://cloud.githubusercontent.com/assets/2222881/13382422/467cee00-de42-11e5-995e-19adc851efa0.png">
<img width="923" alt="screen shot 2016-02-28 at 4 56 32 pm" src="https://cloud.githubusercontent.com/assets/2222881/13382423/4a0ca0e2-de42-11e5-9d3c-8f474cd841f6.png">

**Comment by Bashta** [comment]
I am currently facing the same issue with the parse-server deployed to AWS. Any luck with this issue yet?

**Comment by jacobkneal** [comment]
Same :-/ . I'm using Heroku. Occurs first when I call **[PFFacebookUtils logInInBackgroundWithReadPermissions...] ** but previously when I had bypassed login via a cached user, this error was received after every single call to my open source Parse server. (Same code works perfectly on Parse's hosted server.)

**Comment by Bashta** [comment]
I just got around it. It actually in my case it was a problem related with the server not being able to connect to Mongo DB. The error was due to a "!" at the end of the password. After changing the password its working as expected. Tested the user login and creation and its working like a charm. Not sure though how this affected the login/signup process though.

**Comment by gfosco** [comment]
In this case we'd need more information.. Please check the server logs, and if possible, capture the request and response by setting the environment variable VERBOSE=1 and running the server.  If you are still having an issue, please open a new issue and provide as much information as possible.  Thanks.

**Comment by LBKevinSibue** [comment]
I made an app with Parse framework (on iOS) and parse my server hosted on AWS. And I too have the same problem: 'The data couldn't be read beacause it is not in the correct format. "

This error appear for every query.

The only solution I found was to set the version of the parse-server (and its dependencies) to 2.2.10.

Do you have any idea ?

**Comment by flovilmart** [comment]
Like @gfosco mentioned 6 months ago, please provide the logs when running with the VERBOSE=1 environment variable

**Comment by LBKevinSibue** [comment]
It just say 'Error: Cannot find module 'parse-server/lib/Adapters/Logger/FileLoggerAdapter''.
But I don't understand with my app can't have access to my data

[ParseServer - Error.pdf](https://github.com/ParsePlatform/parse-server/files/447369/ParseServer.-.Error.pdf)

**Comment by flovilmart** [comment]
What version are you running? What is your initialization code? It seems that you're either using lan outdated version OR that you're calling `require('parse-server/lib/Adapters/Logger/FileLoggerAdapter')` in app.js.

In any case that's totally unrelated with that issue...

**Comment by LBKevinSibue** [comment]
I know that's why I find it strange.
My version of Parse framework (for iOS) is the 1.12.0
And the server there is the 2.2.10 release. This is the way I found to run my app.

Actually I have a line 'var Logger = require (' parse-server / lib / Adapters / Logger / FileLoggerAdapter ') FileLoggerAdapter;.'

**Comment by flovilmart** [comment]
so yeah, your error is because you have that call and this module don't exist... So... You should remove that line, AND update to 2.2.18.

**Comment by LBKevinSibue** [comment]
I remove the line which contains require of the 'FileLoggerAdapter' and I delete the version of the parse-server but now I have this error:

ReferenceError: Logger is not defined
     at Object. <anonymous> (/var/app/current/app.js:70:32)
     at Module._compile (module.js: 409: 26)
     at Object.Module._extensions..js (module.js: 416: 10)
     at Module.load (module.js: 343: 32)
     at Function.Module._load (module.js: 300: 12)
     at Function.Module.runMain (module.js: 441: 10)
     at startup (node.js: 139: 18)
     node.js at: 968: 3

**Comment by flovilmart** [comment]
Yeah because you probably reference that logger variable somewhere. What do you do with it? With the `app.js` code that would probably be easier...

**Comment by LBKevinSibue** [comment]
Ah yes exact forgot to remove a line.
Thank you all perfectly works again! Thank you !

**Comment by AnkiReddyPolu** [comment]
// Read data from server
    func pollToServerForData()
    {
        let queue = DispatchQueue.global()
        
        queue.async {
            let data = self.client.read(1024*10)
            if let bytes = data {
                if let response = String(bytes: bytes, encoding: .utf8) {
                    print("openSession response Data is : \(response)")
                    
                    // Convert String to Dictionary
                    let jsonDict = self.delegate.convertStringToDictionary(text: response)
                    
                    if let senderType = jsonDict?["sender_type"] as? String {
                        self.senderType = senderType
                        print("senderType is : \(self.senderType!)")
                    }
                    print("Content Type is : \(String(describing: jsonDict?["content_type"]))")
                    
                    guard let contentType = jsonDict?["content_type"] as? String else
                    {
                        return
                    }
                    self.delegate.contentType = contentType
                    if contentType == "connection" {
                        DispatchQueue.main.async {
                            print("Content Type 1 is : \(contentType)")
                            self.delegate.messageReceived(response: jsonDict!)
                        }
                    }

i am getting error in swiftsocket 


The data couldn’t be read because it isn’t in the correct format.
Content Type is : nil
