### ISSUE TITLE
How to integrate Google Analytic with parse server ?

### ISSUE THREAD

**Issue by mohshaheen** [ParsePlatform/parse-server#719]
i am setting up a parse server inHouse
currently i am looking to integrate it with Google analytics , but i donot know , shall i implement the google analytics SDK in the mobile app or can i customize parse server analytics.js  to post the events to the google service 

one other points : how to track push opens ? what custom i would need then ?

**Comment by gateway** [comment]
You might want to check out Flurry for app analytics, its a free service https://developer.yahoo.com/analytics/

**Comment by flovilmart** [comment]
@mohshaheen we'll be opening soon analytics adapters in order to plugin your favorite analytics tool!

**Comment by gfosco** [comment]
One could implement the routes in `analytics.js` and then send the event to another analytics provider... If time is not critical, there's no doubt we'll have analytics adapters in a future version.
