### ISSUE TITLE
Parse Server does not generate objectId, createdAt and updatedAt

### ISSUE THREAD

**Issue by sekharrockz** [ParsePlatform/parse-server#721]

**Comment by bohemima** [comment]
Can you please elaborate on this? How to reproduce, etc.

**Comment by sekharrockz** [comment]
i have my parse-server running in google cloud. I used Android SDK and tried to create a parse object, the response which i got from server did't have objectId and createdAt. so my question here is, do we need to manually generate objectId and createdAt for every new object in the class.?

**Comment by gfosco** [comment]
No, there must be something else wrong.  Parse server does generate and return those values when successful.  Please check the server logs and try to determine what is happening.

**Comment by sekharrockz** [comment]
ok.  Thanks
