### ISSUE TITLE
Incrementing a push notification badge number support coming soon?

### ISSUE THREAD

**Issue by taufiq-husain** [ParsePlatform/parse-server#723]
How can I tell whether the open source server will support something or whether I should implement a solution myself? I noticed that on the detailed docs, it said that Parse server doesn't support iOS badge numbers **yet**. Does this mean it's coming soon? Could I please know when/how I can help to speed this particular part? My project needs to be live on the app store within a week and this part is the only broken part.

I've successfully set up cloud code and fixed up my iOS front-end codes to use the Parse server. Thank you guys so much for everything you're doing with this. Highly appreciate it!

**Comment by flovilmart** [comment]
As per the documentation it seems that the badge is supported: https://github.com/ParsePlatform/parse-server/wiki/Push#api

**Comment by anatolydwnld** [comment]
I think this ticket was about supporting `Increment` as the badge value(https://parse.com/docs/rest/guide#push-notifications-sending-options). Please, re-open.

**Comment by flovilmart** [comment]
Did you try `badge: "increment"` ? It should to the job

**Comment by taufiq-husain** [comment]
You can see in Parse's Push wiki, it says that this hasn't been implemented "yet". Link: https://github.com/ParsePlatform/parse-server/wiki/Push. That's why I was asking if/when/whether it'll ever be implemented...

**Comment by flovilmart** [comment]
Right.

**Comment by anatolydwnld** [comment]
Just to double check, I tested `badge: "increment"`. Didn't work. There doesn't seem to be any mention of this in the source either. The wiki is correct in stating that this feature is not yet implemented.

**Comment by flovilmart** [comment]
PR is pending review

**Comment by taufiq-husain** [comment]
Hi,

I've updated my package.json file to `"parse-server": "~2.1.4"` but the "Increment" push notification feature doesn't seem to work still. I'm using the standard iOS APN system explained here: https://github.com/ParsePlatform/parse-server/wiki/Push. I deployed my code to my Heroku server by updating the package number but the push notification feature still doesn't increment. When I use the `badge: 1` feature which works well but the increment feature doesn't. In fact, if I put the badge as "Increment", the badge doesn't update at all. What am I doing wrong? Did I not update the Parse server properly on Heroku? Do I need to do something more?

Thanks.

**Comment by taufiq-husain** [comment]
I've also updated using the instructions given here: https://github.com/ParsePlatform/parse-server/issues/879

Any ideas why it's not working still @flovilmart ?

**Comment by flovilmart** [comment]
Can you run a query on _Installation to see if the badge value increments correctly? The badge increment is only for iOS devices, (deviceType=ios should be set on _Installation)

**Comment by taufiq-husain** [comment]
I did. The badge is still showing zero.

Here is my package.json:

```
{
  "name": "parse-server-example",
  "version": "1.1.0",
  "description": "An example Parse API server using the parse-server module",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "https://github.com/ParsePlatform/parse-server-example"
  },
  "license": "MIT",
  "dependencies": {
    "express": "~4.2.x",
    "kerberos": "~0.0.x",
    "parse": "~1.6.12",
    "parse-server": "~2.1.4"
  },
  "scripts": {
    "start": "node index.js"
  },
  "engines": {
    "node": ">=4.3"
  }
}
```

I'm using cloud code to send push notifications. As soon as I change the badge value to **"1"**, it works. As soon as I change it `"Increment"`, it stops showing any numbers. It just shows 0 for the receiving user's badge in the `_Installation` row.

**Comment by flovilmart** [comment]
what is the deviceType for your _Installation?

**Comment by taufiq-husain** [comment]
Oh they are all iOS. I updated my previous comment with more info.

**Comment by flovilmart** [comment]
is it iOS or all lowercase string? Could you dump an excerpt of the query result?

**Comment by taufiq-husain** [comment]
Sure:

```
{
    "_id": "ZsLYArrz0e",
    "parseVersion": "1.12.0",
    "deviceToken": "b64e82cfc37f13ccd3e8709473576a8d49e6964f10b11b46179e04935b3af751",
    "badge": 0,
    "deviceType": "ios",
    "installationId": "7d7984e0-ccfe-4f53-b112-2b6bc0b9eeb6",
    "localeIdentifier": "en-US",
    "appIdentifier": "com.polarhills.LOL",
    "timeZone": "America/Los_Angeles",
    "enabled": false,
    "appName": "LOL",
    "username": "[REDACTED]",
    "appVersion": "1.5",
    "_updated_at": {
        "$date": "2016-03-02T06:01:01.268Z"
    },
    "_created_at": {
        "$date": "2016-02-29T22:52:45.274Z"
    }
}
```

**Comment by flovilmart** [comment]
nothing logged ? when you try pushing?

**Comment by taufiq-husain** [comment]
I got something:

```
Taufiqs-MBP:getlolapp Taufiq$ heroku logs --tail -n 50
2016-03-07T18:56:38.132467+00:00 app[web.1]: APNS Connection 0 Notification transmitted to 3d8591f34b26c9bc3ba49cea14f6512224ab4201c9a4481092f6c1991e7b6a1f
2016-03-07T18:56:38.236110+00:00 app[web.1]:   connIndex: 0,
2016-03-07T18:56:38.236112+00:00 app[web.1]:    { aps: 
2016-03-07T18:56:38.236112+00:00 app[web.1]:       { badge: undefined,
2016-03-07T18:56:38.236096+00:00 app[web.1]: APNS Notification caused error: 8 for device  Device {
2016-03-07T18:56:38.236113+00:00 app[web.1]:         sound: undefined,
2016-03-07T18:56:38.236109+00:00 app[web.1]:   token: <Buffer bf e9 20 3e de a8 3f 25 e4 51 6c e3 16 75 47 c3 89 8f c3 b1 35 7e 5f e8 bf bf 42 3b f3 75 8f 82>,
2016-03-07T18:56:38.236110+00:00 app[web.1]:   appIdentifier: 'com.polarhills.LOL' } { encoding: 'utf8',
2016-03-07T18:56:38.236114+00:00 app[web.1]:         'url-args': undefined,
2016-03-07T18:56:38.236111+00:00 app[web.1]:   payload: 
2016-03-07T18:56:38.236114+00:00 app[web.1]:         alert: 'Message from Taufiq Husain 😋',
2016-03-07T18:56:38.236117+00:00 app[web.1]:   retryLimit: -1,
2016-03-07T18:56:38.236118+00:00 app[web.1]:   device: undefined,
2016-03-07T18:56:38.236115+00:00 app[web.1]:         category: undefined } },
2016-03-07T18:56:38.236116+00:00 app[web.1]:   expiry: undefined,
2016-03-07T18:56:38.236117+00:00 app[web.1]:   priority: 10,
2016-03-07T18:56:38.236119+00:00 app[web.1]:   compiled: '{"aps":{"alert":"Message from Taufiq Husain 😋"}}',
2016-03-07T18:56:38.236119+00:00 app[web.1]:   truncateAtWordEnd: false,
2016-03-07T18:56:38.236120+00:00 app[web.1]:   _alert: 'Message from Taufiq Husain 😋' }

```

**Comment by flovilmart** [comment]
so badge is actually undefined.

**Comment by taufiq-husain** [comment]
yeah, I wonder why? I was using the following function:

```
// Push Notifications
Parse.Cloud.define("send_push", function(request, response) {
	var query = new Parse.Query(Parse.User, {useMasterKey:true});
	query.containedIn("username", request.params.receivers);
	query.equalTo("enabled", true);
    Parse.Push.send({
        where: query,
        data: {
            alert: request.params.message,
			badge: "Increment"
        }
    }, 
	{ 
		useMasterKey: true 
	}, 
	{
        success: function() {
			response.success("Push notification sent!");
        },
        error: function(e) {
			response.error("Push notification error! Code: " + e.code + ", Message: " + e.message);
        }
    });
});
```

Why is badge being sent as "undefined"?

**Comment by taufiq-husain** [comment]
Maybe Parse server expects an integer instead of string for the `badge` value? I have no clue why this is not working but `badge: 1` works. @flovilmart

**Comment by flovilmart** [comment]
not sure, we have unit tests to make sure everything is functional, this part is heavily tested through he PushController. 

I just noticed that your push query is on Parse.User, that is maybe the problem now. 
It should be a query on _Installation

**Comment by taufiq-husain** [comment]
I updated the cloud code to the following and it still isn't working (shows the same "undefined" badge error):

```
// Push Notifications
Parse.Cloud.define("send_push", function(request, response) {
	var Installation = Parse.Object.extend("_Installation");
	var query = new Parse.Query(Installation, {useMasterKey:true});
	query.containedIn("username", request.params.receivers);
	query.equalTo("enabled", true);
    Parse.Push.send({
        where: query,
        data: {
            alert: request.params.message,
			badge: "Increment"
        }
    }, 
	{ 
		useMasterKey: true 
	}, 
	{
        success: function() {
			response.success("Push notification sent!");
        },
        error: function(e) {
			response.error("Push notification error! Code: " + e.code + ", Message: " + e.message);
        }
    });
});
```

**Comment by cra5370** [comment]
I'm seeing the same behavior as taufiq in my heroku setup as well - all of my push notifications show up but the badge is never incremented despite having badge: "Increment" in the data parameter. My MongoDB entries for installations show badge count staying at 0. Is there any update on this?

**Comment by taufiq-husain** [comment]
@cra5370 I don't know if you fixed this issue yet but my heroku server started working after updating to the most recent Parse server version. If you used git to set up heroku then follow these steps and it might start working properly:

```
heroku git:clone -a my_app
cd my_app
git submodule add https://github.com/ParsePlatform/parse-server.git
npm link parse-server ./parse-server
cd parse-server
git checkout master
git pull
cd ..
git commit -am “Testing”
git push heroku master
```

Other than that, you should look into the docs furthermore. Amazing guys like @flovilmart and the rest of the Parse team are doing a wonderful job keeping and making Parse great and open source.

**Comment by aliasad106** [comment]
I am facing the same problem I update parse-server to latest and tested locally and it was working fine and show badge for "increment" but when I deployed to AWS Elasticbeanstalk, It doesn't show anything.

**Comment by aliasad106** [comment]
One thing to note is I'm using Docker for deployment. Docker file seems not be updated. :(

**Comment by miighty** [comment]
Hey an progress on this I see m to have the same problem  `badge: "Increment"` doesn't work but I can set the badge via integer. Im super new to node.js and parse. Is there a way to get the badge value and then count that up ?

**Comment by flovilmart** [comment]
What version of parse-server are you running? The increment should be implemented for a while.

**Comment by miighty** [comment]
I belive  I am running 1.2.0, but It's a parse server for Microsoft Azure

**Comment by flovilmart** [comment]
Parse server versions start from 2.0.0, the current version is 2.2.22.

**Comment by miighty** [comment]
Whoops sorry, in that case the version is 2.1.4, which judging by the current version is very old...

**Comment by flovilmart** [comment]
Yes syou should upgrade then!

**Comment by jeacott1** [comment]
someone should probably update the docs to reflect this sometime. 
http://docs.parseplatform.org/parse-server/guide/#api

"Here is the list of sending options we do not support yet:
push_time for scheduled push
Increment badge under data for iOS badge number"

**Comment by flovilmart** [comment]
Yes! Could you do it @jeacott1 ? Push schedule is saved but not run though

**Comment by devKC** [comment]
@flovilmart I am seeing a situation where the iOS badge count is incrementing independent of Installation.badge count. For example, I send a push with `badge: "Increment"` and the badge pops up on iOS as it should. I open the app and the badge disappears and installation.badge is reset to 0, as it is designed. However, after sending another push the iOS badge seems to continuously incrementing (showing 2,3,4,5... rather than 1, which it should be since badge count resets). I suppose I can simply set `badge: 1` but was wondering if you've seen anything like this.
