### ISSUE TITLE
Website and documentations availability after Parse shutdown?

### ISSUE THREAD

**Issue by taufiq-husain** [ParsePlatform/parse-server#724]
I don't know where to ask non-coding related questions but will the Parse documentations and website still be alive after Facebook shuts it down? Does anyone have any mirror sites hosting Parse Docs yet? Thanks.

**Comment by drew-gross** [comment]
The docs are currently available in Markdown format here: https://github.com/ParsePlatform/Docs we are also hoping to keep the Parse.com UI for docs available as well, but we don't have a solution yet.
