### ISSUE TITLE
PFConfig not returning dictionary

### ISSUE THREAD

**Issue by kilabyte** [ParsePlatform/parse-server#726]
CentOS VPS, iOS

After migration any PFConfig calls return "JSON text did not start with array or object and option to allow fragments is not set.- error code 3840". If i point the app back to the main parse instance everything works great and i get the dictionary returned. Is PFConfig not supported with parse-server?

![screen shot 2016-02-29 at 1 31 05 pm](https://cloud.githubusercontent.com/assets/487948/13409649/b4fdd9b0-dee8-11e5-9a22-4cb06321e933.png)

**Comment by gfosco** [comment]
Config is still in an experimental state until tested fully with the coming dashboard release.  You can enable it now by setting the environment variable `PARSE_EXPERIMENTAL_CONFIG_ENABLED=1`

If you've done this and are still having a problem, please re-open.  Thanks!

**Comment by nehloo** [comment]
Is PFConfig still in an experimental state? I'm still getting error 3840 even with PARSE_EXPERIMENTAL_CONFIG_ENABLED=1.
