### ISSUE TITLE
ACL restricted PFQuery returns no results when using parse-server, works when using old Parse.com API

### ISSUE THREAD

**Issue by fyredave** [ParsePlatform/parse-server#728]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

-[X ] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

-[ X] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

-[X ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
AWS Elastic Beanstalk, 64bit Amazon Linux 2015.09 v2.0.8 running Node.js

#### Steps to reproduce
Create Read/Write ACL restricted object using iOS SDK 1.12 then attempt to find it after saving it. 
Example Code: 
PFACL *userACL = [[PFACL alloc] init];
[userACL setPublicReadAccess:false];
[userACL setPublicWriteAccess:false];
[userACL setReadAccess:true forUser:[PFUser currentUser]];
[userACL setWriteAccess:true forUser:[PFUser currentUser]];
[myPFObject setACL:userACL];
[myPFObject saveInBackgroundWithBlock //..]; 

//Success, no error, see object in DB, then later... run PFQuery, no results found when would normally be found before migrating. 

 Query returns successfully with the expected object using Parse.com API but unsuccessfully when using a ParseClientConfiguration set to my server. I suspect the read ACL is not working properly because it returns with no results found even though _rperm and _wperm match the PFUser object ID in MongoDB. Query returns successfully with public read/write permissions set to true as well. 

ACL query works on Android, both Parse.com and self-hosted server.
ACL query only works on iOS on Parse.com, does not work on self-hosted server.

#### Logs/Trace
-------------------------------------
/var/log/nodejs/nodejs.log
-------------------------------------
BUG: the handler did not include a "response" field
BUG: the handler did not include a "response" field
BUG: the handler did not include a "response" field
BUG: the handler did not include a "response" field
BUG: the handler did not include a "response" field
BUG: the handler did not include a "response" field
BUG: the handler did not include a "response" field
BUG: the handler did not include a "response" field
BUG: the handler did not include a "response" field
BUG: the handler did not include a "response" field
BUG: the handler did not include a "response" field
BUG: the handler did not include a "response" field
BUG: the handler did not include a "response" field

**Comment by stalehard** [comment]
I have same problem with self-hosted Parse-server:
After save new Parse.User object I set ACL for this user:

1 variant
```javascript
newUser.signUp(null, { useMasterKey: true })
    .then(
        (user) => {
            let acl = new Parse.ACL(user);                      
            user.setACL(acl);
            user.save();
        },
        (error) => {

        }
    );
```
2 variant
```javascript
newUser.signUp(null, { useMasterKey: true })
    .then(
        (user) => {
            let acl = new Parse.ACL();
            acl.setReadAccess(user.id, true);
            acl.setWriteAccess(user.id, true);
            acl.setPublicReadAccess(false);
            user.setACL(acl);
            user.save();
        },
        (error) => {

        }
    );
```
But in both case in mongoDB i see for this record:
"_id" : "mwlCdr4GtU", "_rperm" : [ "mwlCdr4GtU", "*" ], "_wperm" : [ "mwlCdr4GtU" ]

**Comment by flovilmart** [comment]
I'll have a look

**Comment by flovilmart** [comment]
@stalehard I can't repro your bug check here: https://github.com/ParsePlatform/parse-server/tree/flovilmart.UserACL

**Comment by fyredave** [comment]
Any update on my bug?

**Comment by stalehard** [comment]
@flovilmart  to repro this bug I use this code
```javascript
var newUser = new Parse.User();
newUser.set('username', 'test');
newUser.set('password', '123');

newUser.signUp(null, { useMasterKey: true })
    .then(function(user) {
        var acl = new Parse.ACL();
        acl.setReadAccess(user.id, true);
        acl.setWriteAccess(user.id, true);
        acl.setPublicReadAccess(false);
        user.setACL(acl);
        user.save();
    }, function(err) {
        console.log(err);
    });
```
In mongoDB i see 
"_id" : "RAye8eRxzY", "_rperm" : [ "RAye8eRxzY", "*" ], "_wperm" : [ "RAye8eRxzY" ]
Also i can read full info about this object as any user


I find working variant
```javascript
var newUser = new Parse.User();
newUser.set('username', 'test');
newUser.set('password', '123');
var acl = new Parse.ACL();
newUser.setACL(acl);

newUser.signUp(null, { useMasterKey: true })
    .then(function(user) {
        var acl = new Parse.ACL(user);
        user.setACL(acl);
        user.save(null, { useMasterKey: true });
    }, function(err) {
        console.log(err);
    });

```
In this case all work fine:
"_id" : "SR2AAfmFvd", "_rperm" : [ "SR2AAfmFvd" ], "_wperm" : [ "SR2AAfmFvd" ]

**Comment by flovilmart** [comment]
@stalehard I'll track it deeper

**Comment by fyredave** [comment]
@flovilmart you reference stalehard's issue when you say you aren't able to reproduce. His issue seems separate from mine. Can you please address my issue instead of the comment posted after? This is delaying a major feature release for us and It is not clear if you are unable to reproduce my issue. I know the issue goes away if I use the default API url but it persists if I use parse-server on my AWS deployment.

**Comment by fyredave** [comment]
Our Issue seems resolved with the update to 2.1.5. Leaving this open so you can work with stalehard.

**Comment by flovilmart** [comment]
@fyredave good to know that's solved, I'd rather have @stalehard to open a new issue for that as they are unrelated to keep things tidy. @stalehard can you do that?

**Comment by stalehard** [comment]
@flovilmart ok
