### ISSUE TITLE
S3 Adapter saving content-type?

### ISSUE THREAD

**Issue by nitrag** [ParsePlatform/parse-server#731]
Can you guys check your files stored in S3 Console.... My meta data is showing the file as "application/octet-stream". 

Perhaps the Great @flovilmart could add "ContentType" to the S3 upload sdk to match the ParseFile content-type? ([docs](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property))

```
var image = new Parse.File("photo.jpg", { base64: request.params.image }, "image/jpeg");
```

**Comment by mchun** [comment]
#628

**Comment by flovilmart** [comment]
See #738
