### ISSUE TITLE
Master key is invalid, you should only use master key to send push

### ISSUE THREAD

**Issue by maruthi-wal** [ParsePlatform/parse-server#736]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

-[ ] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

-[ ] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

-[ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

**Comment by maruthi-wal** [comment]
Hello Everyone,

Iam getting Master key is invalid, you should only use master key to send push

Please find my cloud code below:

Parse.initialize("appid", "javascriptkey", "masterkey");
var pushQuery = new Parse.Query(Parse.Installation);
Parse.Push.send({

        channels: [ "Giants" ],
        data: {
            alert: "The Giants Mets 2-3."
        }
    }, { useMasterKey: true });

My index.js code
var api = new ParseServer({
databaseURI: databaseUri,
cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
appId: process.env.APP_ID,
masterKey: process.env.MASTER_KEY,
clientKey: process.env.CLIENT_KEY,
restAPIKey: process.env.REST_API_KEY,
fileKey: process.env.FILE_KEY,
serverURL: 'http://IP/parse',
push: {
ios:
[
{
pfx: __dirname + '/name.p12', // Prod PFX or P12
bundleId: id',

production: false // Prod
},
{
pfx: __dirname + '/name.p12', // Prod PFX or P12
bundleId: 'id',

production: true // Prod
}
]

}
});
Please help me on this
Thanks,

**Comment by flovilmart** [comment]
Did you set your master key in the environment before starting your server? with: `APP_ID= appid MASTER_KEY=masterKey node index.js`

**Comment by maruthi-wal** [comment]
Yes.. Master key and App Id i given.. Please help me on this..

**Comment by mithleshjs** [comment]
Pass the third argument as "true" to .send function.

**Comment by maruthi-wal** [comment]
@mithleshjs I have given  useMasterKey: true. Please check in my code. Still same issue. I tried in all ways still iam getting this error. Could please someone provide me a detailed steps.

**Comment by maruthi-wal** [comment]
Its working for me. Thanks a lot for your suggestions.

My cloude code finally:

Parse.Push.send({
  channels: ['Giants'],
  data: {
    alert: 'The Giants Mets 2-3.',
    badge: 1,
    sound: 'default'
  }
}, {
  success: function() {
    console.log('##### PUSH OK');
  },
  error: function(error) {
    console.log('##### PUSH ERROR');
  },
  useMasterKey: true
});

**Comment by AlecKriebel** [comment]
@maruthi-wal Did you still have to call `Parse.initialize("appid", "javascriptkey", "masterkey");`in the body of your cloud code function?

If you did, did you just copied and pasted the keys in as strings?

**Comment by maruthi-wal** [comment]
@AlecKriebel  Thanks. Its working for me..

**Comment by AlecKriebel** [comment]
@maruthi-wal It is not working for me. Did you still have the initialize call in your Cloud Code. I may need to add it to mine.

Thanks.

**Comment by maruthi-wal** [comment]
@AlecKriebel Yep.. I added Parse.initialize("appid", "javascriptkey", "masterkey"); in my cloud code.

Make sure in index.js as below:
push: {
ios:
[
{
pfx: __dirname + '/name.p12', // Prod PFX or P12
bundleId: id',

production: false 
}
]
}

Production should be false for testing.

**Comment by mahabubakram** [comment]
{ params: { id: '45J1QIaKIi' },
  master: false,
  user: { _objCount: 0, className: '_User', id: '45J1QIaKIi' },
  installationId: '82e1d517-7aac-d887-d02b-e407c3de5e7f' }
##### PUSH OK

APNS Connection 0 Socket Error
APNS Connection 0 Socket Error
APNS Connection 0 Socket Error
APNS Connection 0 Disconnected
APNS Connection 0 Socket Error
APNS Connection 0 Disconnected
APNS Connection 0 Socket Error
APNS Connection 0 Socket Error
APNS Connection 0 Disconnected
APNS Connection 0 Socket Error
APNS Connection 0 Socket Error
APNS Connection 0 Disconnected
APNS Connection 0 Socket Error
APNS Connection 0 Socket Error
APNS Connection 0 Disconnected
APNS Connection 0 Socket Error
APNS Connection 0 Socket Error
APNS Connection 0 Disconnected
APNS Connection 0 Socket Error
APNS Connection 0 Socket Error
APNS Connection 0 Disconnected

how to solve this problem when I send push it performs success but the it also shows these in the console.
