### ISSUE TITLE
parse cloud UNIQUENESS of a table is not working. Can anybody confirm ? 

### ISSUE THREAD

**Issue by sekharrockz** [ParsePlatform/parse-server#737]

**Comment by flovilmart** [comment]
Can you please detail the issue a bit more?

**Comment by sekharrockz** [comment]
My Cloud Code:

**//UNIQUENESS FOR CHAT TABLE...**
Parse.Cloud.beforeSave("test", function(request, response) {
  if (request.object.isNew("username")) {
    if (!request.object.get("username")) {
      console.log("BEFORE-SAVE ERROR...");
      response.error('test must have the username.');
    } else {
      var query = new Parse.Query(Chats);
      query.equalTo("username", request.object.get("username"));
      query.first({
        success: function(object) {
          if (object) {
            console.log("BEFORE-SAVE  ERROR...");
            response.error("A test with this username already exists.");
          } else {
            console.log("BEFORE-SAVE  SUCCESS...");
            response.success();
          }
        },
        error: function(error) {
          console.log("BEFORE-SAVE  ERROR...");
          response.error("Could not validate uniqueness for this test object.");
        }
      });
    }
  } else {
    console.log("BEFORE-SAVE  SUCCESS...");
    response.success();
  }
});


When i add a new object , it says "Could not validate uniqueness for this test object" .  which means request.object.isNew does not work .

**Comment by sekharrockz** [comment]
request.object.isNew is failing

**Comment by gfosco** [comment]
isNew should work for the whole object, but not for a specific key... So that is probably your issue.

```js
if (request.object.isNew()) {
```
