### ISSUE TITLE
PFGeoPoint with integer value returns NULL

### ISSUE THREAD

**Issue by mtrezza** [ParsePlatform/parse-server#745]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

-[x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

-[x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

-[x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
This is a test to migrate an app, so there will be two Parse Servers interacting with the same DB.
Server/Client 1 (released app versions):
Parse Server hosted on Parse.com as of 2016-03-01
Parse iOS SDK 1.8.5

Server/Client 2:
Parse Server 1.12.0
Parse iOS SDK 1.12.0

Common DB (as the data base has already been migrated away from Parse.com):
mongoDB 3.0.9

#### Steps to reproduce
1. On Server/Client 2 save a PFGeoPoint object to a field of type PFGeoPoint with an integer value either for longitude or latitude, e.g.
```
"location": [
        16.7,
        48
    ]
```
2. The Parse hosted dashboard shows `NULL` as value for the location field.
3. When trying to retrieve the location object as PFGeoPoint in iOS with Server/Client 1 an error is thrown in iOS:
`Could not cast value of type 'NSNull' (0x1a0bbb768) to 'PFGeoPoint' (0x1005f6ea8).`
4. Change the integer value to a float by adding `.0` to it and the Parse hosted dashboard will recognize the PFGeoPoint and the retrieval will succeed.

#### Logs/Trace
Error thrown in iOS SDK:
`Could not cast value of type 'NSNull' (0x1a0bbb768) to 'PFGeoPoint' (0x1005f6ea8).`

#### Comment
The probability of a longitude or latitude value being an integer number if practically nil. However, in a development environment it can be an integer while simulating a location.

**Comment by mtrezza** [comment]
This seems to be a bug in the Parse hosted Parse Server version, as no error is thrown when retrieving the location with self-hosted the above mentioned Server/Client 2. This should just be kept in mind for migrating apps. I suggest to close this issue.

**Comment by gfosco** [comment]
Very interesting... The documented format is 2 floats, so this seems rooted in parse-server not enforcing that.  We should fix this, actually, and reject non-float values for geopoints.
