### ISSUE TITLE
Remove python dependency

### ISSUE THREAD

**Issue by radzio** [ParsePlatform/parse-server#75]
Hi!

I'm new to node.js development and I don't know why parse server need Python installed. Is it possible to use Parse server without it? Any bypass it? 

I wan't setup parse-server on openshit but unfortunately I have problems because of python dependency :(

Cheers!

**Comment by cainoeraabele** [comment]
Node.js is built with GYP — cross-platform built tool written in Python. Also some other build steps are implemented in Python. So Python is required for building node from source.

But you also need Python for building native addons.

**Comment by radzio** [comment]
Thank you for your  answer! @cainoeraabele  is it possible to build this native addons on other machine and deploy them on server without python installed?

**Comment by gfosco** [comment]
bcrypt is the issue here which requires python, because it needs to be compiled on the target.  I think you should work on getting python 2.7 running.. don't think we can avoid this dependency.

**Comment by radzio** [comment]
@gfosco  thanks!

**Comment by AndrewLane** [comment]
Is this still true @gfosco?  I was able to run parse-server in Windows 8 without installing Python, and I'm seeing bcrypt hashes in my MongoDB.

**Comment by flovilmart** [comment]
That doesn't seem to be true, we changed the bcrypt libs for native or node versions and a fallback is provided in case the native version can't be built.
