### ISSUE TITLE
Pointers leading to empty objects will stop the queries and show results

### ISSUE THREAD

**Issue by taufiq-husain** [ParsePlatform/parse-server#754]
I'm using Swift and I had a reference of an object (Pointer Relation). When I queried for the rows of the parent object using `includeKey`, it returned all objects but the child object didn't indicate a `nil` object (as it used to in the usual Parse). In this open source server, it seems that object returns even when there isn't any object available but the code breaks when you try to access that child object. I used a **_little hack_** by basically checking if the `createdAt` attribute (which is available for all objects) is nil or not.

I don't know where the issue arises exactly but I'm fairly sure the code breaks in the iOS SDK and probably in other SDKs too. Just letting you guys know that if you see empty results when only one row's child object is pointing to a deleted object doesn't really mean that ALL rows are empty. Something in the SDK is definitely messing up.

**Comment by flovilmart** [comment]
That should be fixed by now by #777
