### ISSUE TITLE
Received an error with invalid JSON from Parse: Cannot POST /classes/_User\n

### ISSUE THREAD

**Issue by otymartin** [ParsePlatform/parse-server#756]
I'm using [PFUser-Digits](https://github.com/felix-dumit/PFUser-Digits) resource to authenticate parse users using Twitter's Digits API.

My parse server is hosted on App Engine with MongoLab database.

I get this error when trying to signup/login

### RESOURCES USED
[**Link to Swift File**](https://github.com/felix-dumit/PFUser-Digits/blob/master/PFUser%2BDigits.swift)
[**Link to Cloud Code handling Authentication**
](https://github.com/felix-dumit/PFUser-Digits/blob/master/user.js)
```swift
2016-03-01 23:59:49.646 Bars[10323:15114219] [Error]: {
    code = 107;
    message = "Received an error with invalid JSON from Parse: Cannot POST /classes/_User\n";
} (Code: 141, Version: 1.12.0)
2016-03-01 23:59:49.647 Bars[10323:15113659] -[__NSCFDictionary length]: unrecognized selector sent to instance 0x7fe0adc33a10```

**Comment by otymartin** [comment]
### SOLVED

In server.js, I neglected adding ``/parse``` in ```javascript serverURL: process.env.SERVER_URL || 'https://projectname.appspot.com/parse```

because I thought it was taken care of here
```javascript app.use(process.env.PARSE_MOUNT_PATH || '/parse', parseServer);```

**Comment by samsalgado** [comment]
Authentication error:
Received an error with invalid JSON from Parse
I am getting this error when authenticating MetaMask with React Native.

**Comment by mtrezza** [comment]
@THEMERLINGROUP I suggest you open a new issue if you are sure this is a Parse Server bug. Otherwise, for help with Parse Platform we recommend our [community forum](https://community.parseplatform.org).
