### ISSUE TITLE
Fosco, do you want one of these hats?

### ISSUE THREAD

**Issue by TylerBrock** [ParsePlatform/parse-server#757]
because... your work on parse-server has been YUGE! Thank you good sir.

![makeparsegreatagain](https://cloud.githubusercontent.com/assets/280807/13451320/d80c6312-dff2-11e5-965d-1aea3942f4f4.jpg)

**Comment by TylerBrock** [comment]
This issue can only be considered "resolved" once the community receives back an image of @gfosco wearing this hat.

**Comment by gfosco** [comment]
Lol yes I want one of those hats!!

**Comment by bohemima** [comment]
Don't forget @flovilmart, @nlutsenko, @drew-gross and most likely a few others :+1:

**Comment by flovilmart** [comment]
Most definitely!

**Comment by nitrag** [comment]
I am nobody and I support this message!

**Comment by lklots** [comment]
![2016-03-02 11 35 52 copy 2](https://cloud.githubusercontent.com/assets/43253/13472975/162c0ff2-e06c-11e5-8f96-055d2490c334.jpg)

**Comment by hramos** [comment]
This thread is *fantastic*.

**Comment by natanrolnik** [comment]
😂

**Comment by flovilmart** [comment]
I need one! do you ship in Canada? Too bad it won't make it in time for the talk I'm giving next tuesday!

**Comment by TylerBrock** [comment]
send me an e-mail at the address in my profile, I'll try to hook it up if they ship to canada

**Comment by flovilmart** [comment]
thanks @TylerBrock

**Comment by gfosco** [comment]
We'll trade you some brand new Parse hoodies, @TylerBrock !

**Comment by nlutsenko** [comment]
Subscribe... 
I didn't wear a hat for such a long time, but would gladly start wearing now if it's this one.
![image](http://replygif.net/i/149.gif)

**Comment by TylerBrock** [comment]
Ok, @flovilmart I added the design to a cart so you (or anyone else) can get one from [here](https://checkout.spreadshirt.com/?basketId=58f417b5-0c43-4c4b-a8f2-630d781f2091&locale=US&lang=us&shopId=93439&continueShoppingLink=https%3A%2F%2Fwww.spreadshirt.com%2Fdesign-your-own-t-shirt-C59). I called to make sure they ship to Canada so you should be able to get one quickly which would be faster than me sending you one.

I've got some for the major parse-server contributors in SF and will **definitely** trade for a hoodie.

I didn't want to set up a store at spreadshirt (as it would increase the price) and we aren't trying to make any money off of this, just enjoy some open source goodness.

**Comment by flovilmart** [comment]
No shipping to Canada unfortunately...

**Comment by TylerBrock** [comment]
I just called them and they confirmed they do, you might have to switch to the Canadian store.

**Comment by flovilmart** [comment]
Insane, their Canadian shop can send anywhere in the world....  Thanks!

**Comment by TylerBrock** [comment]
w00t, wear it proudly my friend.

**Comment by flovilmart** [comment]
I will! when it arrives... seems that it's gonna take longer than passing the mexican border (shipping 30 march)

**Comment by gfosco** [comment]
![image1](https://cloud.githubusercontent.com/assets/406732/13543150/78e50024-e21d-11e5-9e6f-2722b8409f60.png)

Thanks @TylerBrock !!

**Comment by flovilmart** [comment]
![img_0695](https://cloud.githubusercontent.com/assets/364568/13657890/d95a19e0-e640-11e5-9c03-174e86ca0d9e.jpg)

**Comment by flovilmart** [comment]
![img_0694](https://cloud.githubusercontent.com/assets/364568/13657951/45ab564a-e641-11e5-8fad-63e50ad1cf1b.jpg)
