### ISSUE TITLE
How to create new mongodb column with "Pointer" type?

### ISSUE THREAD

**Issue by thphuc** [ParsePlatform/parse-server#758]
As the title said, could you please tell me how to create a new column that is a pointer (point to another collection)? 
(I am using both command line and Robomongo)

**Comment by gfosco** [comment]
The schema is stored in the database, in the _SCHEMA collection, one row per className.

The best way to add a pointer column is just to use any SDK or the REST API to save an object in that column, but you could edit the schema object and add a key value for that column... 

the format would be `"columnName": "*targetClass"`

**Comment by fbomb111** [comment]
Where is the documentation for adding Pointers via REST API?  I see what you provided is the correct end format, but I get a bad request if I try sometime like that via the API.  Even a link would be great as [the Parse docs](http://parseplatform.github.io/docs/rest/guide/#schema) do not cover Pointers or Arrays in the schema.

Neither of these seem to work:

    `{
	    "className": "parentClassName",
	    "fields": {
		    "columnName": {
		    	"type": "*targetKlassName"
		    }
	}
    }

    {
	    "className": "parentClassName",
	    "fields": {
		    "columnName": "*targetKlassName"
	    }
    }`

Thanks!
