### ISSUE TITLE
Parse server don't support embedded sdk anymore?

### ISSUE THREAD

**Issue by evileye2000** [ParsePlatform/parse-server#76]
Parse server needs to api for change server. But, embedded sdk did not support yet.
And, parse server did not support push too.

I want to know the schedule about update sdk and push support.
Please answer me although there is no plan or drop the embedded project.

Thanks

**Comment by wangmengyan95** [comment]
Hi @evileye2000, right now the priority of the team is to support APNS for iOS and GCM for android as soon as possible. We do not have a short plan to support PPNS for embedded push.
