### ISSUE TITLE
Not able to run javascript SDK api's from the parse-server cloud code.

### ISSUE THREAD

**Issue by sekharrockz** [ParsePlatform/parse-server#762]
**Parse.Cloud.beforeSave("test", function(request, response) {
    var GameScore = Parse.Object.extend("GameScore");
    var gameScore = new GameScore();
    gameScore.set("score", 1337);
    gameScore.set("playerName", "Sean Plott");
    gameScore.set("cheatMode", false);
    gameScore.save(null, {
      success: function(gameScore) {
        alert('New object created with objectId: ' + gameScore.id);
        response.success("done");
      },
      error: function(gameScore, error) {
        alert('Failed to create new object, with error code: ' + error.message);
        response.error();
      }
    });
});**

Before save is getting called, but the Game Score object is not getting added,

**Comment by sekharrockz** [comment]
Can anyone reply to this ?

**Comment by drew-gross** [comment]
Can you provide some more information? What are your server settings? What is the response to your request? Have you tried removing the `alert`s?

**Comment by sekharrockz** [comment]
I didt try removing alerts, but still I guess this will not work. Is master key required while using JavaScript SDK API ?

**Comment by drew-gross** [comment]
Inside Cloud Code, the JS SDK is initialized automatically. Outside Cloud Code, you probably should not use the master key without a good reason, and you definitely should not send the master key to your users.

**Comment by sekharrockz** [comment]
How do we need to use masterkey : true while using JavaScript SDK

**Comment by drew-gross** [comment]
You do that in the options of your query.

**Comment by drew-gross** [comment]
No response in many days, closing.
