### ISSUE TITLE
API Create/delete schema is not working

### ISSUE THREAD

**Issue by ntloc592** [ParsePlatform/parse-server#763]
#### Environment Setup
Install Parse Server on Windows enviroment

#### Steps to reproduce
- Call api DELETE:  /schemas/:{className}
==> Result from API: {}, but this schema was not delete
- Call api POST: create schema with className = '_Role'
==> Result: error: 'type Relation needs a class name', code: 135

**Comment by drew-gross** [comment]
The API will respond with {} if you try to delete a non-existent class. Can you verify that you are trying to delete the right class? The create _Role issue sounds like a real issue, I will investigate.

**Comment by ntloc592** [comment]
- Only can delete a schema when this schema has least one instance
- Can not delete if this schema don't has any instance
So when I call API create schema, I don't have any instance for it, and I want to delete this schema, I can't delete

**Comment by drew-gross** [comment]
I've created a new issue for adding _Role via schema in #788. I've tested deleting of schemas and verified that it works only for empty collections. Can you open a new issue for deleting schemas with more specific steps to reproduce? Can you also make sure you are using the most recent version of Parse Server?
