### ISSUE TITLE
npm install error!

### ISSUE THREAD

**Issue by json-park** [ParsePlatform/parse-server#77]
I try "npm install -g parse-server" Amazon Linux AMI

However, an error occurred.

Help me~

> bcrypt@0.8.5 install /home/ec2-user/.nvm/versions/node/v4.1.2/lib/node_modules/parse-server/node_modules/bcrypt
> node-gyp rebuild

make: Entering directory `/home/ec2-user/.nvm/versions/node/v4.1.2/lib/node_modules/parse-server/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
make: g++: Command not found
make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 127
make: Leaving directory `/home/ec2-user/.nvm/versions/node/v4.1.2/lib/node_modules/parse-server/node_modules/bcrypt/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ec2-user/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.10-17.31.amzn1.x86_64
gyp ERR! command "/home/ec2-user/.nvm/versions/node/v4.1.2/bin/node" "/home/ec2-user/.nvm/versions/node/v4.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ec2-user/.nvm/versions/node/v4.1.2/lib/node_modules/parse-server/node_modules/bcrypt
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
/home/ec2-user/.nvm/versions/node/v4.1.2/lib
└── (empty)

npm WARN mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.
npm ERR! Linux 4.1.10-17.31.amzn1.x86_64
npm ERR! argv "/home/ec2-user/.nvm/versions/node/v4.1.2/bin/node" "/home/ec2-user/.nvm/versions/node/v4.1.2/bin/npm" "install" "-g" "parse-server"
npm ERR! node v4.1.2
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.8.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bcrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/npm-debug.log
npm ERR! code 1

**Comment by TJkrusinski** [comment]
You need to install g++/gcc. `sudo yum install gcc`.

**Comment by gfosco** [comment]
cc @jamesyu we can add this note to the guide?

**Comment by json-park** [comment]
@TJkrusinski Thank you TJkrusinski. I had to fix this problem.

**Comment by ryderjack** [comment]
I'm getting the same error, I don't have yum, how else can g++/gcc be installed? @TJkrusinski @gfosco 
Cheers

**Comment by mastercodefu** [comment]
I have the same error installing on windows 2012 r2.
