### ISSUE TITLE
Queries on Relations don't seem to be working

### ISSUE THREAD

**Issue by sprabs** [ParsePlatform/parse-server#782]
I am seeing this error message: **Uncaught internal server error. [TypeError: Cannot read property 'query' of undefined] TypeError: Cannot read property 'query' of undefined**

My code is querying a relation. It doesn't seem to like this. We query relations a lot. Is this a bug with parse-server or is there some modifications that I need to make in order to get this to work? I have not been able to find any information about relations in the migration guides.

**Comment by nathan-savvy** [comment]
https://github.com/ParsePlatform/parse-server/issues/550

**Comment by sprabs** [comment]
Looks like https://github.com/ParsePlatform/parse-server/pull/769 has a potential fix for this. Will it be merged in to the main branch soon?

**Comment by flovilmart** [comment]
Just been merged feel free to test!

**Comment by sprabs** [comment]
@flovilmart Thank you--will do! Do you have a best practices on how to update our parse-server code? I am running this on Elastic Beanstalk.

**Comment by flovilmart** [comment]
It all depends on you installation, you can point your dependency to parseplatform/parse-sever in package.json and then run npm install.

**Comment by flovilmart** [comment]
@sprabs can you give the stack trace with the error?

**Comment by flovilmart** [comment]
Not much activity there, I will assume given the thread that parse-sever 2.1.5 has the proper fix

**Comment by RafaRuiz** [comment]
I'm still getting this randomly.
