### ISSUE TITLE
Any plans to implement Node.js Cluster into parse-server?

### ISSUE THREAD

**Issue by noder199** [ParsePlatform/parse-server#787]
Hello, are there any plans to implement [this](http://www.sitepoint.com/how-to-create-a-node-js-cluster-for-speeding-up-your-apps/) into parse-server? I am new and learning node so this is new stuff to me. An example [here](https://github.com/awslabs/eb-node-express-sample/blob/master/app.js).

**Comment by flovilmart** [comment]
You should not need that for development purposes, and otherwise, I'd recommend using a process manager like pm2 or strong-pm

**Comment by noder199** [comment]
Is this particular [feature](http://pm2.keymetrics.io/docs/usage/cluster-mode/) what you are referring to? Does pm2 grant the sort of scalability that a node cluster provides? Why isn't pm2 already a dependency in the project? Thanks.

**Comment by lacker** [comment]
If you're new to node then don't muck around with clusters yet. Just use something like Heroku in production.

**Comment by flovilmart** [comment]
@noder199 yes this is the feature I'm talking about, but like @lacker says, you should not mess around with that if you're new to node, or system administration or process management. Most of the cloud providers (AWS, heroku, google) provide a safe and proper way to run a node.js server.

**Comment by noder199** [comment]
@flovilmart Alrighty, just to be clear, pm2 is something I use when NOT using a cloud provider? Cloud providers do something equivalent?

**Comment by noder199** [comment]
Alright so just to answer myself in case others are wonderin, pm2 is not needed on services like Heroku or AWS because these platforms handle scaling instances of your server on their own. If you use digital ocean or your own linux machine for your server, then pm2 can basically provide similar functionality to what Heroku/AWS/etc. provide.
