### ISSUE TITLE
Can not delete schemas

### ISSUE THREAD

**Issue by ntloc592** [ParsePlatform/parse-server#789]
Use Parse Server version 2.1.3

1. I create 'test' class via Schema API - CREATE
    - In database, 'test' will insert into _SCHEMA collection
    - 'test' collection has not created
2. I will delete 'test' classs via Schema API - DELETE
    - Result: {},
    - 'test' have not deleted from _SCHEMA collection yet

**Comment by drew-gross** [comment]
Fixed by #802
