### ISSUE TITLE
databaseURI with email and password causes error

### ISSUE THREAD

**Issue by omairvaiyani** [ParsePlatform/parse-server#79]
Just tried setting up a local server and sent a curl request, received this error in console. Before giving more details, is there an obvious mistake that I could have made to cause this?
```
Uncaught internal server error. [Error: Username containing an unescaped at-sign] Error: Username containing an unescaped at-sign
    at module.exports (/Users/omairvaiyani/Documents/github/app-server/node_modules/parse-server/node_modules/mongodb/lib/url_parser.js:61:13)
    at connect (/Users/omairvaiyani/Documents/github/app-server/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:125:16)
    at /Users/omairvaiyani/Documents/github/app-server/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:101:7
    at Function.MongoClient.connect (/Users/omairvaiyani/Documents/github/app-server/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:100:12)
    at /Users/omairvaiyani/Documents/github/app-server/node_modules/parse-server/ExportAdapter.js:38:24
    at process._tickCallback (node.js:368:9)
```

EDIT:
After looking into it, it seems that the way ```ExportAdapter``` connects with ```MongoClient``` doesn't account for authentication with email+password within the ```databaseURI``` parameter. How do we manage this as I haven't seen this in the migration docs?

**Comment by mkpazon** [comment]
I think you should be using the database username and not an email

**Comment by gfosco** [comment]
Yeah I don't think it's valid to have an email address to sign in to mongo, especially since it's constructed like a URL.  protocol://user:pass@server/database.   The @ sign in the email would be misinterpreted as the break between authentication and server address.

**Comment by dsingh09** [comment]
Simply Use "mongodb://username:"+encodeURIComponent("p@ssword")+"@localhost:27017/droom"
