### ISSUE TITLE
File pointer missing when db server is at localhost

### ISSUE THREAD

**Issue by mchun** [ParsePlatform/parse-server#793]
I encountered a strange issue when using cloudcode to generate thumbnail saving to s3 when the database server is hosted locally. The thumbnail field returned is not a properly constructed pointer.

#### Steps to reproduce
When using database server at mlab, everything is fine. The problem only occurs when I change it to the local database server. i.e.,
```
var api = new ParseServer({
  // databaseURI: 'mongodb://login:password@somedatabaseatmlab',
  databaseURI: 'mongodb://localhost:27017/dev',
.....
})
```

This is the cloudcode I used to generate thumbnail as illustrated in #648 :

```
Parse.Cloud.beforeSave("Post", function(req,res) {
  var post=req.object;
  var photo1=req.object.get('photo1')
  Parse.Promise.as().then(function() {
    if (photo1) {
      if (req.object.dirty("photo1")) {
        return Jimp.read(photo1.url())
        .then(function(image){
          return image.resize(300,300);
        }).then(function(resized){
          return new Parse.Promise((resolve,reject)=>{
            resized.getBuffer(Jimp.MIME_JPEG,function(err,buffer){
              if (err) return reject(err);
              var file = new Parse.File('thumb.jpg',{base64:buffer});
              resolve(file.save());
            });
          });
        }).then(function(savedImage){
          post.set('thumbnail',savedImage);
        });
      }
    }
    return Parse.Promise.as();
  }).then(function(){
    res.success();
  }, function(error) {
    console.log(error);
    res.error(error.message);
  });
});

```

I verified the problem as the following:

```
curl -X GET \
  -H "X-Parse-Application-Id: myAppId" \
  -H "X-Parse-REST-API-Key: myRestAPIKey" \
  http://localhost:1337/parse/classes/Post/E4tXBSmVu7
```

#### Logs/Trace
`{"objectId":"E4tXBSmVu7","photo1":{"__type":"File","name":"9aabc4e1b02993265531bb3b3e8598ba_1.jpg","url":"https://freesthdebugclone.s3.amazonaws.com/9aabc4e1b02993265531bb3b3e8598ba_1.jpg"},"thumbnail":"cf63cdf17046ceb2370fb92e2284d8ab_thumb.jpg","updatedAt":"2016-03-03T05:25:43.090Z","createdAt":"2016-03-03T05:25:43.090Z"}`

#### Environment Setup
parse-server 2.1.3

**Comment by gfosco** [comment]
I suggest modifying your beforeSave like this, saving the file object itself rather than the result of the save.. 


```js
Parse.Cloud.beforeSave("Post", (req,res) => {
  var post = req.object;
  var photo1 = req.object.get('photo1');
  var file;
  if (photo1 && req.object.dirty("photo1")) {
    Jimp.read(photo1.url()).then((image) => {
      return image.resize(300,300);
    }).then((resized) => {
      resized.getBuffer(Jimp.MIME_JPEG, (err,buffer) => {
        if (err) {
          res.error(error.message);
          return;
        }
        file = new Parse.File('thumb.jpg', {base64:buffer});
        file.save().then(() => {
          post.set('thumbnail', file);
          res.success();
        }, (e) => {
          res.error(e.message);
        });
      });
    }, (e) => {
      res.error(e.message);
    });
  } else {
    res.success();
  }
});

```

If you have further issues please open a new issue.

**Comment by mchun** [comment]
hi @gfosco, your code works well when the database is hosted externally (@ mlab), but when the database is at localhost, the problem still exists...
*still using 2.1.3 to test as s3adapter is not working on 2.1.4

**Comment by mchun** [comment]
I figured out the problem.
The thumbnail field is missing inside _SCHEMA.
After adding
`    "thumbnail" : "file"`
It works.

I guess it has something to do with the first time creation of a field? The problem does not exist on my mlab db as it was migrated from parse.
