### ISSUE TITLE
com.parse.ParseRequest$ParseRequestException: bad json response

### ISSUE THREAD

**Issue by vineetbindal** [ParsePlatform/parse-server#795]
[Here is someone else reported this earlier](https://github.com/ParsePlatform/Parse-SDK-Android/issues/334)

It looks like I am facing the same issue as above with the newer version of 
Parse API 'com.parse:parse-android:1.13.0'

Downgrading to Parse API 'com.parse:parse-android:1.12.0' doesn't work for me either. I get error in
`.server("http://10.0.2.2:1337/parse")`  in below code.  saying can not resolve method `server(java.lang.string)` 

    Parse.initialize(new Parse.Configuration.Builder(getApplicationContext())
						.applicationId("NjTVO3LsUaJ9QW8MEUDUSs3aYhqmAWq1ErCy9fBp")
						.clientKey(null)
						.server("http://10.0.2.2:1337/parse")
						.build()
		);

Here is my gradle file :

    buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }

    }
    apply plugin: 'com.android.application'
    apply plugin: 'io.fabric'

    repositories {
    jcenter()
    maven { url 'https://maven.fabric.io/public' }
    }

    android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.buddyreminder.app"
        minSdkVersion 16
        targetSdkVersion 23
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
        debug {
            debuggable true
        }
    }
    }

    dependencies {
    compile 'com.android.support:support-v4:23.0.0'
    compile 'com.android.support:appcompat-v7:23.0.0'
    //compile files('libs/Parse-1.13.0.jar')
    compile 'com.parse:parse-android:1.13.0'
    compile 'com.parse.bolts:bolts-android:1.+'
    compile files('libs/simmetrics_jar_v1_6_2_d07_02_07.jar')
    compile('com.digits.sdk.android:digits:1.9.3@aar') {
        transitive = true;
    }

}

**Comment by drew-gross** [comment]
Is this an issue related to Parse Server? Is your app making any requests to Parse Server that are failing? Use [Parse Network Interceptors](https://github.com/ParsePlatform/ParseInterceptors-Android) to find out. If your app isn't making any requests, then try the Android SDK repo.

**Comment by vineetbindal** [comment]
yes its an issue related to parse server. 

I am making this request  : 
    ParseCloud.callFunctionInBackground("SaveNewData", newDataObj,
				new FunctionCallback<String>() {
			@Override
			public void done(String result,
					com.parse.ParseException e) {
				if (e == null) {
					Log.d("New Data Saved : ", result);
					newDataDialog.dismiss();
				}else{
					Log.e("Error:", e.getMessage());
					if(!Utility.checkInternetConnection(getActivity())){
						saveNewDataEventually();
						newReminderDialog.dismiss();
						Toast.makeText(currentActivity.getApplicationContext(), R.string.data_sent_network_error, Toast.LENGTH_LONG).show();
					}
				}
			}
		});

**Comment by drew-gross** [comment]
Can you provide your cloud code?

**Comment by thphuc** [comment]
I got same issue and I fixed it by adding "/" to the end of server. 
"http://10.0.2.2:1337/parse" -> "http://10.0.2.2:1337/parse/"
Hope it will help you

**Comment by vineetbindal** [comment]
Yes, That resolved this issue.

**Comment by mchun** [comment]
I just encountered the same issue, perhaps the wiki guide should be updated?

**Comment by gfosco** [comment]
I updated the wiki this morning to include the trailing slash.

**Comment by mchun** [comment]
👍🏻 thanks a lot

**Comment by jayjac** [comment]
wow thank you guys, I was pulling my remaining hair out on this one!!

**Comment by partikles** [comment]
It works.
