### ISSUE TITLE
Issue saving a Role

### ISSUE THREAD

**Issue by didierfranc** [ParsePlatform/parse-server#80]
Hi, everything seems fine until I try to set ACL and Role.

![capture d ecran 2016-01-30 a 15 19 28](https://cloud.githubusercontent.com/assets/14132464/12696243/746bdb3a-c765-11e5-8d51-ee286f2e86c8.jpg)

**Comment by davidaik** [comment]
+1 We need fully working ACL and CLP.

**Comment by kcedric** [comment]
+1

**Comment by wangmengyan95** [comment]
Hi @didierfranc, is it possible for you to paste the stacktrace of your server?

**Comment by gfosco** [comment]
Roles and ACLs were implemented, and there are test scenarios you can see under the `spec/` folder.  If you can construct a failing test, that would be the most helpful, otherwise try to get the full response from the server and the logs.

**Comment by didierfranc** [comment]
Yes I saw that `spec` samples, I'll check that and post result here.

**Comment by didierfranc** [comment]
Maybe answer is that we can't use as before

```
// Roles are not accessible without the master key, so they are not intended
// for use by clients.  We can manually test them using the master key.
```

https://github.com/ParsePlatform/parse-server/blob/master/spec/ParseRole.spec.js

**Comment by gfosco** [comment]
Well, roles even on hosted parse require the master key.  So this is working as intended.  Initialize with the master key and pass useMasterKey: true in the save call.

**Comment by didierfranc** [comment]
@gfosco The function in first post is part of my installation script to define an admin, user roles ... it runs well with Parse.com not with the new parse-server. 

So everything is fine if I set the **masterkey**

```javascript
Parse.masterKey = 'mymasterkey';
// ...
role.save({}, { useMasterKey: true })
```

**Comment by gfosco** [comment]
I check and you're right, the REST API Key was allowed to affect Roles on hosted Parse... I think it's better here in parse-server to require the master key.

**Comment by ledowong** [comment]
I used very long time to find this post. I think this should be in the README because it is very very important.

For me, my app is a web app using JS SDK. Now **read Role**, **create object** and **save object** are not working.......

For **read Role**, I can just hardcode my username, to check if the loggedIn user is allowed to edit.
However for create/save, it only works with masterKey :(

It doesn't make sense to put the masterKey in JavaScript...
That mean whole thing broken now.

Any workaround? Thanks.

**Comment by ledowong** [comment]
@gfosco

**Comment by didierfranc** [comment]
I opened this thread, I gave the **non solution** of **masterkey** I'm working on a real one

**Comment by aitchkhan** [comment]
+1
