### ISSUE TITLE
Parse Cloud Function never successfully executes my queries...

### ISSUE THREAD

**Issue by fraxool** [ParsePlatform/parse-server#800]
I'm trying to execute this cloud code function : 

```
Parse.Cloud.define('sendPush', function(request, response) {
	
	// request has 2 parameters: params passed by the client and the authorized user
	var userTo = request.params.userTo;
	
	// extract out the channel to send
	var message = request.params.message;
	
	Parse.Cloud.useMasterKey();
	
	// use to custom tweak whatever payload you wish to send
	var query = new Parse.Query(Parse.User);
      	query.equalTo("objectId", userTo);

	  	// Get the first user which matches the above constraints.
      	query.first({
		success: function(quser) {
			response.success('success');
		},
		error: function(err) {
			response.error(userTo + " not found!");
		}
	});
});
```

The function is executed, the parameters are passed. 
`userTo` represents an objectId of an existing user. But everytime I execute this code, it doesn't find the user. I always get the error response code which is "userTo not found!".

I have also tried to execute another query (for example, listing all of the users) and it always ends in the error block...

Am I missing something here? I'm using Heroku.

Thanks,
Axel

**Comment by jiewmeng** [comment]
@fraxool did you fix this issue. I notice for me Parse.Query doesnt appear to work. It gives something like below. If I query via REST api it works, but not otherwise. Why isit trying to POST?

> Received an error with invalid JSON from Parse: Cannot POST /classes/_User
