### ISSUE TITLE
equalTo objectId + equalTo relational field give incorrect result in query

### ISSUE THREAD

**Issue by carmenlau** [ParsePlatform/parse-server#801]
Here is the code snippet:

```
query.equalTo("objectId", "OBJECT_ID");
query.equalTo("users", user);
```

In our data, the expected result should be object with objectId OBJECT_ID.
**Expected result**: object with objectId OBJECT_ID.
**In v2.3.1**: object with objectId different from OBJECT_ID.
**In current master** (c6406b9): return undefined.

**Comment by flovilmart** [comment]
Something similar is tested [here](https://github.com/ParsePlatform/parse-server/pull/769/files#diff-6c3d6b2f723631f5b175561b34cd8b7dR285) with `containedIn`. I'll track it down!

**Comment by carmenlau** [comment]
Thanks a lot @flovilmart . After testing v2.1.4, the problem is still existing. The query return random object with different OBJECT_ID again this time. Let me know if any information cloud help!

**Comment by flovilmart** [comment]
@carmenlau see the test here: https://github.com/ParsePlatform/parse-server/pull/809/files#diff-6c3d6b2f723631f5b175561b34cd8b7dR319

Is that similar to your use case?

**Comment by carmenlau** [comment]
Yes @flovilmart It is similar to my use case! I change the testing query like this and it breaks.

```
query.equalTo("objectId", parent2.id);
query.equalTo("toChilds", childObjects[2]);
```

The expected length of result list should be 1, and the object should be `parent2`. But now the length is 2.

For your refs: https://github.com/carmenlau/parse-server/commit/825f97331b768ed8448f46e15ea13a2bbc8e250c

**Comment by flovilmart** [comment]
I'll look into it!
