### ISSUE TITLE
Difference in Json object returned by Parse Server

### ISSUE THREAD

**Issue by araaku** [ParsePlatform/parse-server#803]
I have migrated a Parse app to AWS by following the migration guide. Server is running fine and data is accessible however my application is not able to process the json response returned by server.
Initially, on Parse.com, the json response returned by server starts as the following:

  

>  "results": [
>       {
>          "Parasha": "פרת משפטים",
>          "color": "#1b3f94",
>          "cover": {
>             "__type": "File",
>             "name": "0db6899cbbb4-dvar_malchut.jpg",
>             "url": "bb4-dvar_malchut.jpg"
>          },
>          "createdAt": "2016-02-28T20:23:53.449Z",
>          "objectId": "FTSc98wrau",
>          "updatedAt": "2016-02-28T22:01:32.156Z"
>       },

But now, the response received from the migrated Parse server starts as following:

> {
>    "results": [
>       {
>          "objectId": "56d5ff8198era17198750fce",
>          "results": [
>             {
>                "Parasha": "פרת משפטים",
>                "backCover": {
>                   "__type": "File",
>                   "name": "tfss-d08252f668-cover-low.jpg",
>                   "url": "e-6f608252f668-cover-low.jpg"
>                },

_Notice the additional **"results": [  and objectId**at the root. _
I could update my app to deal with it but it will be great if this can be fixed from the server end so that I don't need to make changes in my app.
Any help will be appreciated.
Thanks

**Comment by flovilmart** [comment]
It seems to be a pretty serious issue, Can you post the query you're running?

**Comment by araaku** [comment]
Here is the curl request:

curl -X GET -H "X-Parse-Application-Id: <appid>"  http://52.86.108.87:xxx/parse/classes/TestClass

API key parameter is not included in the curl request as it is optional for the migrated server. This command returns all the objects under TestClass but with an additional root node (as mentioned in the original question above). The same request made to Parse.com returns the JSON data as expected.

Thanks.

**Comment by abremner** [comment]
I'm also curious why the query response is different on Parse Server. Previously if I console logged a query response I would get a plain json object. Now if I run the same function the console logs an array of ParseObjectSubclass objects that don't appear to contain anything useful. I can see the correct "results" array in the network response tab, but not sure how to access it?

**Comment by araaku** [comment]
I was using the DB Migration tool to transfer records from Parse.com to the new server. Tried again by first taking the back-up of the database in JSON format and then imported it in to the new server. This fixed the issue.
It is hard to believe that it was due to using db migration tool as it is suggested by parse.com and almost everyone is using it to migrate the db. May be it was something else which was specific to my scenario only.
Closing the issue.

**Comment by madsb** [comment]
I'm reopening this as I see the same thing. I have a Parse Server running on my local machine and the same Parse Server running on AWS Elastic Beanstalk. A Cloud Code function is returning an Parse Object with a child GeoPoint. When running the function on my local machine, the GeoPoint is returned as a plain dictionary:
```
info: Ran cloud function addressLookup for user AoIQv9zeMi with:
  Input: {"address":"stejlehøjen 2","postCode":"","country":"DK"}
  Result: [{"geoPoint":{"_latitude":55.1805494582046,"_longitude":11.8516349334482},"address":"Stejlehøjen 2","postCode":"4700","city":"Næstved","address2":"Pederstrup","formattedAddress":"Stejlehøjen 2, Pederstrup, 4700 Næstved","country":"DK","placeId":"22729a66-a157-44d0-e044-0003ba298018","placeIdSource":"dawa"}] functionName=addressLookup, address=stejlehøjen 2, postCode=, country=DK, user=AoIQv9zeMi
```

– whereas the exact same function running on EB is returning a Parse Geopoint:
```
info: Ran cloud function addressLookup for user 7RvhuvJ14y with:
  Input: {"address":"Stejlehøjen 2","postCode":"","country":"DK"}
  Result: [{"geoPoint":{"__type":"GeoPoint","latitude":55.1805494582046,"longitude":11.8516349334482},"address":"Stejlehøjen 2","postCode":"4700","city":"Næstved","address2":"Pederstrup","formattedAddress":"Stejlehøjen 2, Pederstrup, 4700 Næstved","country":"DK","placeId":"22729a66-a157-44d0-e044-0003ba298018","placeIdSource":"dawa"}] functionName=addressLookup, address=Stejlehøjen 2, postCode=, country=DK, user=7RvhuvJ14y
```

The cloud code function looks like this:
```
var Home = Parse.Object.extend("Home");
exports.parseDAWAAddress = function(json) {
  var home = new Home();

  var adgangsadresse = json.adgangsadresse;
  if (!adgangsadresse) { return null; }

  var adgangspunkt = adgangsadresse.adgangspunkt;
  var postnummer = adgangsadresse.postnummer;
  var vejstykke = adgangsadresse.vejstykke;
  if (!adgangspunkt || !postnummer || !vejstykke) { return null; }

  var vejnavn = vejstykke.navn;
  if (!vejnavn) { return null; }
  
  var addressString = vejnavn
  if (vejnavn) {
    addressString = vejnavn;

    var husnr = adgangsadresse.husnr;
    var etage = json.etage;
    var door = json["dør"];

    if (husnr) {
      addressString += " " + husnr;
    }

    if (etage) {
      addressString += ", " + etage;
    }

    if (door) {
      addressString += " " + door;
    }
  }

  var lat = adgangsadresse.adgangspunkt.koordinater[1];
  var lon = adgangsadresse.adgangspunkt.koordinater[0];
  var geoPoint = new Parse.GeoPoint(lat, lon);

  home.set("geoPoint", geoPoint);
  home.set("address", addressString);
  home.set("postCode", postnummer.nr);
  home.set("city", postnummer.navn);

  var address2 = adgangsadresse.supplerendebynavn;
  if (address2) {
    home.set("address2", address2);
  }

  var formattedAddress = json.adressebetegnelse;
  if (formattedAddress) {
    home.set("formattedAddress", formattedAddress);
  }
  
  home.set("country", "DK");
  home.set("placeId", json.id);
  home.set("placeIdSource", "dawa");
  
  return home;
}
```
