### ISSUE TITLE
data type (response) changing when migrating to parse server 

### ISSUE THREAD

**Issue by MuseerAnsari** [ParsePlatform/parse-server#806]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

-[ ] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

-[ ] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

-[ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

**Comment by MuseerAnsari** [comment]
Result (response) after query From old server (originally parse server)
Array (
  Dictioanry1{},
  Dictioanry2{},
  Dictioanry3{},
  .
  .
  .

)

And from  new server after same Query 

Array (
   Dictionary{
      Array(
           Dictioanry1{},
           Dictioanry2{},
           Dictioanry3{},
           .
           .
           .
      )
  },
)

**Comment by flovilmart** [comment]
What version of parse-server are you running? What is your query?

**Comment by flovilmart** [comment]
Duplicate from #803

**Comment by MuseerAnsari** [comment]
i am using PARSE_VERSION @"1.12.0"
and my query is when i am fetching data from parse server then its structure is diffrent
