### ISSUE TITLE
Receiving support? 

### ISSUE THREAD

**Issue by Francolpm** [ParsePlatform/parse-server#808]
Hi! This isn't a issue but I didn't know where to ask!
Are you accepting donations or supports? Because I want to give some of money to parse-server, but there is no donate button o something like that.
I don't trying to spam you, but I want to invite you to beerpay.io, a simple platform to monetize open source projects, like parse-server. 
I know that the open source is free, but it's okay if someone want to contribute in other way.

Thanks for this work!

**Comment by gfosco** [comment]
The interest is very much appreciated, but I don't think we're able to accept donations at this time.

We're super happy to receive issues and pull requests, though. :smile:
