### ISSUE TITLE
open source parse sever with .NET SDK - JSON error when user registers or saving object

### ISSUE THREAD

**Issue by haighis** [ParsePlatform/parse-server#81]
Hello,

When using the parse server with .NET SDK (under xamarin) I get the same error back regardless to whether I am trying to register a new user or save an object. 

I built this app before parse server was open sourced, etc.  When I revert my parse client to use parse.com hosted parse server everything works fine, where I can register/login and save objects.

Are there still bugs that need to be worked out in parse server or  client SDK's?

Thanks,

John Haigh

**Comment by francocorreasosa** [comment]
The same happens in iOS SDK. See #49

**Comment by gfosco** [comment]
If there is any more information you can provide, server logs, errors, etc, this would be helpful.

**Comment by cristiursachi** [comment]
@haighis I had a similar problem, be sure you put at the end of URL the last ''\'' , example:
`
ParseClient.Configuration config = new ParseClient.Configuration();
config.Server = @"http://localhost:1337/parse/";
config.ApplicationId = "your_appId";
ParseClient.Initialize(config);
`
if you would let only: "config.Server = @"http://localhost:1337/parse"; then you have that JSON invalid error.
For a detailed "how to" on Windows you can take a look here: https://medium.com/@cristi_ursachi/installing-your-own-parse-server-on-windows-b2c7a2498d19#.g0sxg63er

**Comment by jhaigh** [comment]
This issue that I reported isn't really an issue with parse server. The issue was as @cristiursachi indicated where I I didn't have a trailing forward slash ```http://localhost:1337/parse/```.

**Comment by gfosco** [comment]
Closing this and it will be addressed in the dot-net repo: https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/166
