### ISSUE TITLE
"Unable to connect to the Parse API" error thrown when trying to call a Cloud function with a Parse Query.

### ISSUE THREAD

**Issue by guptasachin25** [ParsePlatform/parse-server#817]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

-[X] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

-[X] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

-[X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Running Parse Server on Localhost.
Downloaded code from Amazon Elastic Beanstalk

#### Steps to reproduce
Running any cloud function with a query. Normal cloud function works well. Called using node script. 

#### Logs/Trace

I found other issue https://github.com/ParsePlatform/parse-server/issues/651#event-567422582 which is currently closed. However, even after following the steps and setting up serverURL problem doesn't resolve. XHR failed with status 0.

**Comment by guptasachin25** [comment]
@gfosco you worked on previous issues. Can you help resolve this one.

**Comment by gfosco** [comment]
Can you provide the code for your function? (or the whole cloud code file...)

**Comment by gfosco** [comment]
Discussed over email, problem is the script is overwriting the Parse global which definitely breaks everything.

**Comment by w3care25** [comment]
I am using self hosted parse-server and not able to use cloud functions since I have enabled HTTPS, if I revert it back to HTTP it works as expected.

Also he problem is only with those cloud function which have Parse.Query, if i create a function simply return "Hello" as response it works on both HTTP and HTTPS.

I am getting following error message when run a cloud function which have Parse.Query code.

{
"code": 141,
"error": "XMLHttpRequest failed: \"Unable to connect to the Parse API\"--100"
}

can anyone tell me how can I fix this?

**Comment by chandanthakur** [comment]
I am also facing the same issue. Any pointers with that ? w3care25, did you end up fixing it ?

**Comment by ckarmy** [comment]
> I am using self hosted parse-server and not able to use cloud functions since I have enabled HTTPS, if I revert it back to HTTP it works as expected.

Also he problem is only with those cloud function which have Parse.Query, if i create a function simply return "Hello" as response it works on both HTTP and HTTPS.

I am getting following error message when run a cloud function which have Parse.Query code.

I have the same problem!! Any way to solve this??

**Comment by jova-dev** [comment]
+1

**Comment by w3care25** [comment]
@chandanthakur You need to add  process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"; in you instance file of parse server if you are running into similar issue

**Comment by w3care25** [comment]
@ckarmy You need to create an instance with SSL something like below:

_var privateKey = fs.readFileSync( 'path to ssl key ( .key ) file' );
var certificate = fs.readFileSync( 'path to ssl crt ( .crt ) file' );
var  cabundles = fs.readFileSync( 'path to ssl cabundle ( .cabundle ) file');

https.createServer({
    key: privateKey,
    cert: certificate,
    ca: cabundles
}, app).listen(port);_

Don't forgot to add **var https = require('https');**

**Comment by willyyang** [comment]
@w3care25 adding in the `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"` line still doesn't fix it. Any other ideas? thanks.

**Comment by w3care25** [comment]
If you have configured everythigng correctly. You may need to restart your server after adding this line.

If you  are still having this after  server restart, Could you please share you instance file code ( after replcing your confidential credentails with dummy details)?

**Comment by willyyang** [comment]
@w3care25 I have restarted the server but I am still getting the same results.

```
// SERVER_URL is set to https://APPNAME.herokuapp.com/parse through Config Variables
// MONGODB_URI is set through Config Variables

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

var databaseUri = process.env.DATABASE_URI || process.env.MONGODB_URI;

if (!databaseUri) {
  console.log('DATABASE_URI not specified, falling back to localhost.');
}

var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'xxx',
  masterKey: process.env.MASTER_KEY || 'xxx', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',  // Don't forget to change to https if needed
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  }
});

var app = express();
app.use('/public', express.static(path.join(__dirname, '/public')));
var mountPath = process.env.PARSE_MOUNT || '/parse';
app.use(mountPath, api);

//Required to receive JSON body from POST
app.use(bodyParser.json()); // support json encoded bodies
app.use(bodyParser.urlencoded({ extended: true })); // support encoded bodies

// Parse Server plays nicely with the rest of your web routes
app.get('/', function(req, res) {
  res.status(200).send('I dream of being a website.  Please star the parse-server repo on GitHub!');
});

// This will enable the Live Query real-time server
var port = process.env.PORT || 1337;
var httpServer = require('http').createServer(app);
httpServer.listen(port, function() {
    console.log('parse-server-example running on port ' + port + '.');
});
ParseServer.createLiveQueryServer(httpServer);
```

Hitting the sample `hello` function works but all of mine return the `XMLHttpRequest failed: \"Unable to connect to the Parse API\"--100` error. 

Thank you very much for your help.

**Comment by w3care25** [comment]
backup you instance file and try following code

`var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var app = express();
var fs = require('fs');

var api = new ParseServer({
  databaseURI: 'mongodb://localhost:27017/dev', // Connection string for your MongoDB database
  cloud: '/home/myApp/cloud/main.js', // Absolute path to your Cloud Code
  appId: 'myAppId',
  masterKey: 'myMasterKey', // Keep this key secret!
  fileKey: 'optionalFileKey',
  serverURL: 'http://localhost:1337/parse' // Don't forget to change to https if needed
});


  process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
// Serve the Parse API on the /parse URL prefix
app.use('/parse', api);

app.listen(1337, function() {
  console.log('parse-server-example running on port 1337.');
});`

Make sure you are not accessing you sever with https (SSL enabled). If you need to access your server   with https then you will have to add following 
`var https = require('https');

var privateKey = fs.readFileSync( 'path to ssl.key' );
var certificate = fs.readFileSync( 'path to ssl.crt' );
var  cabundles = fs.readFileSync( 'path to ssl.cabundle');


https.createServer({
    key: privateKey,
    cert: certificate,
    ca: cabundles
}, app).listen(1337);
`

and remove 

`app.listen(1337, function() {
  console.log('parse-server-example running on port 1337.');
});``

**Comment by willyyang** [comment]
@w3care25 Im hosting this on heroku. Wouldn't `serverURL: 'http://localhost:1337/parse'` and `databaseURI: 'mongodb://localhost:27017/dev'` point to my local ?

**Comment by w3care25** [comment]
You can use Heroku credentials here

**Comment by w3care25** [comment]
@willyyang were you able to fix your issue ?

**Comment by willyyang** [comment]
@w3care25 I'm looking for another alternative still because I don't to buy a certificate
