### ISSUE TITLE
Unable to login with Facebook

### ISSUE THREAD

**Issue by mkpazon** [ParsePlatform/parse-server#82]
I keep on getting the following response when trying to login with Facebook
{code: 101, error: "Facebook auth is invalid for this user."}

Pointing to the parse.com hosted parse-server, everything works. Switching to my local parse-server does not work.

I am currently using Android for my app.

**Comment by onedaylove** [comment]
I'm having the same issue. Using iOS and Facebook's SDK is installed properly.

**Comment by francocorreasosa** [comment]
Same thing. Related to #49 and #81.

**Comment by francocorreasosa** [comment]
Same thing. Related to #49 and #81.

**Comment by gfosco** [comment]
Did you set the FACEBOOK_APP_ID environment variable?

**Comment by onedaylove** [comment]
@gfosco Where is that located? Parse-Server? The app code itself?

**Comment by moana2** [comment]
Hi, you need to set the FACEBOOK_APP_ID
Like this :
heroku config:set FACEBOOK_APP_ID=*********

**Comment by onedaylove** [comment]
@moana2 I'm not using heroku. I'm using Digital Ocean.

**Comment by gfosco** [comment]
then it is

```
export FACEBOOK_APP_ID=*****
```

**Comment by francocorreasosa** [comment]
@gfosco can I pass the FB app ID as a ParseServer parameter? I use more than one app in the server.

**Comment by gfosco** [comment]
I made a change here in #86..

**Comment by gfosco** [comment]
Merged, will tag a new release shortly

**Comment by mkpazon** [comment]
Getting this error **appIds.contains is not a function**.

Changing facebook.js contains to indexOf worked.
if (data && appIds.indexOf(data.id) != 1) {

**Comment by mkpazon** [comment]
Getting a **appIds.contains is not a function**

Changing facebook.js _contains_ to _indexOf_ seems to work

if (data && appIds.indexOf(data.id) != -1) {
   return;
}

**Comment by gfosco** [comment]
Ok, made that change and tagged 2.0.3

**Comment by francocorreasosa** [comment]
Great @gfosco. Made my day

**Comment by sdalai** [comment]
I have latest SDK and parse server locally installed. Facebook authentication was not configured during first parse server installation. 
Subsequently I am added Facebook authentication by adding following in new ParseServer block in app.js
oauth: { facebook: { appIds: '35594027127xxxx'  }}

I am using for IOS app.

I got error {code: 101, error: "Facebook auth is invalid for this user."}.

However when pointing to hosted parse server everything works fine.

facebook.js  seems to be ok as per earlier post

**Comment by rsweny** [comment]
To @sdalai, circa v2.1.6, check that the class level permissions on _User are all set to allowed (for me I had field creation turned off). Also for your appIds param, try removing the quotes so it is a real number.

**Comment by AlecKriebel** [comment]
@rsweny How do you change class level permissions?

**Comment by rsweny** [comment]
In the Parse dashboard "Core" section click on the Security button in the top row. From that screen there is also an advanced toggle to see all the options.

**Comment by rsweny** [comment]
Actually this may need to have been done before you migrated.. post-migration may have to either deploy your own local Parse Dashboard or you may have to edit the _SCHEMA table manually.

**Comment by Baby-Sittor** [comment]
Hi there, it doesn't work with AWS. Can you help ?

**Comment by michalumni** [comment]
Yeah, please advise on AWS how to get parse server working with facebook integration.

**Comment by jenrique7** [comment]
+1 Cannot log in or link an account with FB anymore. Any update on this?

**Comment by gateway** [comment]
Btw, just saw this thread and running into the same issue on Heroku..

```
2016-08-22T21:37:45.224619+00:00 app[web.1]:       "access_token": "EAANjrpgib6ABABUE...",
2016-08-22T21:37:45.271795+00:00 app[web.1]: error: Uncaught internal server error. Failed to validate this access token with Facebook. undefined
2016-08-22T21:37:45.270803+00:00 app[web.1]: error: Error generating response. 'Failed to validate this access token with Facebook.' error=Failed to validate this access token with Facebook.
2016-08-22T21:37:45.224619+00:00 app[web.1]:       "expiration_date": "2016-10-21T17:20:42.036Z"
2016-08-22T21:37:45.298670+00:00 app[web.1]: Failed to validate this access token with Facebook.
```

We are using the latest iOS SDK and latest parse server 2.2.18

I have this in my index.js

```
  databaseURI: databaseUri || 'xxx',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'xxx',
  facebookAppIds: ['123456789'],
  masterKey: process.env.MASTER_KEY || '',
  restAPIKeY: process.env.RESTAPI_KEY || '',
  serverURL: process.env.SERVER_URL || 'https://xxx',  // Don't forget to change to https if needed
  fileKey: process.env.FILE_KEY || 'xxx',
  filesAdapter: new S3Adapter(
    process.env.AWS_ACCESS_KEY || 'xxx',
    process.env.AWS_SECRET_ACCESS_KEY || 'xxx',
    "bucket",
    {directAccess: true}
  ),
  push: {
    ios: [
      {
        pfx: 'xxxx', // Prod PFX or P12
        bundleId: 'xxx',
        production: true // Prod
      }
    ]
  }  
});
```

Any ideas?

**Comment by ginofarisano** [comment]
Hi everyone,
I have installed parse server on heroku but I can not login with facebook.

This is my configuration:

var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'myAppId',
  masterKey: process.env.MASTER_KEY || '', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',  // Don't forget to change to https if needed
  facebookAppIds: [process.env.FACEBOOK_APP_ID],
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  }
});

I set my FACEBOOK_APP_ID on heroku.

The message that I get on the android app is:

08-23 18:01:29.970 15226-15226/com.ginofarisano.jointandem W/ParseLoginFragment: Facebook login failed, exception: com.parse.ParseException: Errore di accesso: Si è verificato un errore durante l'accesso a questa applicazione. Riprova più tardi.

Help me, thanks and sorry for my english.

**Comment by gateway** [comment]
Have you tried this

facebookAppIds: ['id'],

or 

facebookAppIds: [id],

first?

**Comment by ginofarisano** [comment]
Yes,

I tried

facebookAppIds: [process.env.FACEBOOK_APP_ID]

AND 

facebookAppIds: [175378669534591]

AND

facebookAppIds: ['175378669534591']


AND

facebookAppIds: ["175378669534591"]

:-(

I do not know how to fix this.

Gino.

**Comment by gateway** [comment]
@ginofarisano as you can see im also having issues so we are in the same boat.. :(

**Comment by gateway** [comment]
@ginofarisano did you depoly the parse server example via Heroku button? If you did, I would suggest not doing that and deploying the parse server example code via command line

**Comment by ginofarisano** [comment]
Hi @gateway,
thanks to help me. Anyway I have installed parse with the heroku button.

If nobody help me I think that I will not use Parse for my app. Have you got any alternatives?

Gino.

**Comment by flovilmart** [comment]
Instead of setting facebookAppIds, try setting `oauth: { facebook: { appIds: ['myappid] }}`

**Comment by okipol88** [comment]
+1
Getting the same error but for Android everything works as expected.
Perhaps the origin of this issue is different?

**Comment by johnlev** [comment]
What is happening with this? I am having the same issue, although with a different error message:

`Error Domain=com.facebook.sdk Code=2 "com.facebook.sdk:UserLoginCancelled" UserInfo={com.facebook.sdk:ErrorLoginFailedReason=com.facebook.sdk:UserLoginCancelled, NSLocalizedFailureReason=com.facebook.sdk:UserLoginCancelled, com.facebook.sdk:ErrorSessionKey=<FBSession: 0x608000360840, state: FBSessionStateClosedLoginFailed, loginHandler: 0x0, appID: 1609731982664894, urlSchemeSuffix: , tokenCachingStrategy:<PFFacebookTokenCachingStrategy: 0x610000231ee0>, expirationDate: (null), refreshDate: (null), attemptedRefreshDate: 0000-12-30 00:00:00 +0000, permissions:(null)>}`

I am using a Heroku server and have set my FACEBOOK_APP_ID environment variable. Any movement on this?

**Comment by flovilmart** [comment]
Your error seems to be a facebook SDK error, not a parse-server error.

**Comment by bmhdev** [comment]
I have the same issue as johnlev...my Facebook ID is in but it always shows User Canceled as the user doesn't come back

**Comment by Andriiklymiuk** [comment]
Have somebody resolved this issue?

**Comment by itacolomymariano** [comment]
I'm run behind of the same problem, somebody did solved this?
