### ISSUE TITLE
Cannot Connect to Parse Server via Android 

### ISSUE THREAD

**Issue by calhouncole** [ParsePlatform/parse-server#822]
I'm currently running Parse-Server 2.1.4 (same problem persists on 2.1.3) and my configuration is:

```
var parse_api = new ParseServer({
  databaseURI: process.env.MONGOLAB_URI || 'xxxxxxx',
  cloud: './cloud/main.js',
  appId: 'xxxxxxx',
  fileKey: 'xxxxxxx',
  masterKey: 'xxxxxxx',
  serverURL: process.env.PARSE_SERVER_URL || 'http://www.xxxxx.com/parse'
});

app.use('/parse', parse_api);

```

I'm unable to connect to this parse-server via my android client (I'm using parse-android:1.13.0). My configuration is:
```

        Parse.initialize(new Parse.Configuration.Builder(this)
                .applicationId(xxxxxx)
                .clientKey("unused")
                .server("http://www.xxxxx.com/parse/")
                .enableLocalDataStore()


                .build()
        );
```

Oddly enough, my iOS client (parse SDK 1.12.0) connects just fine to the same parse-server via the below configuration:

```
        Parse.initializeWithConfiguration(ParseClientConfiguration(block: {(configuration: ParseMutableClientConfiguration) -> Void in
            configuration.applicationId = "xxxxxx"
            configuration.clientKey = "unused"
            configuration.server = "http://www.xxxxxx.com/parse"
            configuration.localDatastoreEnabled = true
        }))
```

Any idea why I am able to connect  via iOS but not Android? From what I've seen, my Android client is implementing the standard configurations.

**Comment by ronaldo-getreveel** [comment]
UP! Same error here. 

It seems to be a url request replacement error. I analyzed the network interceptor and its replacing:
`
http://server.com:1337/parse  to http://server.com:1337/`

Is removing the "parse" path while placing the requests and the response is 404.

**Comment by ofermeroz** [comment]
@ronaldo-getreveel is correct, as a workaround I've modified the configuration.server address, adding another /parse to the path and it worked:

```
Parse.initialize(new Parse.Configuration.Builder(this)
                .applicationId("APP_ID")
                .clientKey("CLIENT_ID")
                .server("http://MY_PARSE_SERVER.com/parse/parse")
                        .build()
        );
```

**Comment by gfosco** [comment]
Interesting... cc @richardjrossiii or @grantland, any ideas?

**Comment by ronaldo-getreveel** [comment]
For Android simply add an extra slash in the server's url and it will works. 

`http://MY_PARSE_SERVER.com/parse**/**`

**Comment by gfosco** [comment]
I didn't catch the trailing slash was missing...Yeah, it is required and this is known.

**Comment by willyyang** [comment]
Did you guys get it to work with by adding `parse/` ? I'm having a hard time getting this to work on android.
