### ISSUE TITLE
Parse Sign Up Error

### ISSUE THREAD

**Issue by benc555** [ParsePlatform/parse-server#824]
#### Environment Setup
iOS 9.2 -- Parse SDK - Latest Release
Facebook Integration Enabled

#### Steps to reproduce
Any time I try to enter information on the PFLoginViewController (Sign Up, or Forgot Password), I get an error saying "The data couldn't be read because it's in the incorrect format."

Not sure if it's related, but it also won't let us Log In with Facebook (the button just does nothing)

#### Logs/Trace

This appears in console upon the app launch:

[Error]: Failed to run command eventually with error: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}
Error: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.} [NSDebugDescription: JSON text did not start with array or object and option to allow fragments not set.]

**Comment by benc555** [comment]
Forgot to update Parse API URL.

**Comment by midgyb** [comment]
I am having the same problem. Where did you forget to update the API URL?

**Comment by davimacedo** [comment]
@midgyb I think he had forgotten to do it: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#deploying-parse-server#using-parse-sdks-with-parse-server

**Comment by angirasg** [comment]
i am having same issue..WHat is the fix ?
