### ISSUE TITLE
Parse Error Code 1

### ISSUE THREAD

**Issue by benc555** [ParsePlatform/parse-server#825]
#### Environment Setup
Latest Parse SDK with Facebook integration enabled in iOS project with 9.2.

#### Steps to reproduce
Trying to call anything to Parse results in the error below.

#### Logs/Trace

2016-03-04 01:03:04.655 hoosout-swift[13875:2916629] [Error]: {"code":1,"message":"Internal server error."} (Code: 1, Version: 1.12.0)
Error: Error Domain=Parse Code=1 "{"code":1,"message":"Internal server error."}" UserInfo={error={"code":1,"message":"Internal server error."}, NSLocalizedDescription={"code":1,"message":"Internal server error."}, code=1} [error: {"code":1,"message":"Internal server error."}, NSLocalizedDescription: {"code":1,"message":"Internal server error."}, code: 1]
2016-03-04 01:03:07.361 hoosout-swift[13875:2916620] [Error]: {"code":1,"message":"Internal server error."} (Code: 1, Version: 1.12.0)
Error: Error Domain=Parse Code=1 "{"code":1,"message":"Internal server error."}" UserInfo={error={"code":1,"message":"Internal server error."}, NSLocalizedDescription={"code":1,"message":"Internal server error."}, code=1} [error: {"code":1,"message":"Internal server error."}, NSLocalizedDescription: {"code":1,"message":"Internal server error."}, code: 1]

**Comment by thphuc** [comment]
ParseUser can login but when I try to get a list of user, I get the same issue

**Comment by thphuc** [comment]
I just noted that if I query 1 record (using getFirst()), I can get the result. But if I query all (using find()), the result is empty

**Comment by thphuc** [comment]
I just fixed this by update to parse server 2.1.4 and DELETE TABLES: _User, _Session, _Schema

**Comment by benc555** [comment]
@thphuc Are you on Heroku/AWS? If so, how did you update the auto-deploy?

**Comment by thphuc** [comment]
I am using Digital Ocean with Linux droplet.

**Comment by gfosco** [comment]
When an internal server error occurs, according to `src/middlewares.js` line 181, additional information and a stack trace is sent to the console logs.  Please check the logs and open a more specific issue if you're still having problems.  Thanks.
