### ISSUE TITLE
Push Notification delivery - is there a limit going thru heroku server?

### ISSUE THREAD

**Issue by rosarionakkocom** [ParsePlatform/parse-server#829]
Since I'm about to test and send a different amount of push notifications to ios and android devices,
 I was wondering if there was a limit using parse on the heroku server.
I understand this is going directly to apns and gcm using parse, am I correct ?
if so
 is there a maximum of pushes that the server can handle ?  

 e.g. 
   1 milion pushes will be delivered in a minute ? 
 (we all understand this can't be completely true but approximately I was looking for an answer or if there was some problem right now that I didn't find yet in the issue list )

  Thank you

---------------
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

-[yes ] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

-[ yes] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

-[  yes] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

 heroku

**Comment by flovilmart** [comment]
parse-server will try to deliver the pushes right away when you send the request. It is possible that the memory explodes, that APNS takes it for a DDoS attack. 
For now we don't have scheduling or a queue for sending push notifications. So I would be careful about sending lots and lots of pushes.

**Comment by Samigos** [comment]
But there's no need of a paging implementation, right? parse-server will take care of the total number of installations?
