### ISSUE TITLE
Migration tool not avalaible for Mongodb 3.2 ( only 3.0 )

### ISSUE THREAD

**Issue by stodeo** [ParsePlatform/parse-server#83]
Hello,
I try to migrate my data to mongo from the app settings but is it possible with mongo 3.2 ? ( When i try i get an error saying that it is only avalaible for mongo 3.0 )
Is it planning to get tool working with mongo 3.2 ?
Thanks

**Comment by skinp** [comment]
@stodeo we only run Mongo 2.6 and 3.0 internally and haven't tested with 3.2. That said, I guess I could change the error to a warning instead. Migration and running on 3.2 would be unsupported though...

**Comment by jeveloper** [comment]
I have a feeling because of the different storage engines (tigershark vs rocksdb)
@stodeo  did you try to run mongo3.2 as a backend db for your parse project?
thanks

**Comment by stodeo** [comment]
@jeveloper  i had to go back to Mongo 3.0 as i was unable to connect Parse server with 3.2

**Comment by jeveloper** [comment]
@skinp mentioned changing that to warning and not an error, i'm conflicted, based on documentation it appears that 3.2 will work, but im not sure if migration to it will not work from parse.com or its implied that if you run parse server on your own it doesn't matter which engine is used.

**Comment by munimisu** [comment]
I have been trying for last 1 week to migrate my parse DB to selfhosted mongoDB 3.2. Keep getting connection error. I will downgrade and try to install 3.0.

**Comment by jeveloper** [comment]
@munimisu  from parse.com you will not be able to move to 3.2 
move to 3.0 and from there do backup/restore to 3.2 and you're fine 

move your app to self hosted parse-server

**Comment by chrisckchang** [comment]
@skinp @gfosco, any plans to make the migration tool compatible with 3.2? We (mLab) are in the process of making it the default release version for all new deployments. If there are no plans to support migrations to 3.2 I'll update our docs and let our support team know.
