### ISSUE TITLE
Cloud Code Deployment

### ISSUE THREAD

**Issue by ball1008** [ParsePlatform/parse-server#830]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

-[ x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

-[ x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

-[ x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Heroic button deployment

#### Steps to reproduce
I have deployed one of my Parse apps to Horoku and MLabs.  My client code is hitting the parse server on my Horoku account.  Everything seems to be working except my cloud code.  I have read the docs but it is not clear to me how I move my cloud code into my parse server on Horoku and how I see it after I deploy.  The parse CLI tool does allow deployment to Heroku but it forces me to link my Parse account to Horoku.  But if Parse goes away next year, that seems to be an issue.

**Comment by drew-gross** [comment]
You will need to do a git clone of your heroku repository. Then you will be able to add your cloud code the repo, and push it back to heroku.
