### ISSUE TITLE
Parse S3 File Access with No Credentials

### ISSUE THREAD

**Issue by nkranes** [ParsePlatform/parse-server#832]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

-[X] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

-[X] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

-[X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
AWS, Parse 2.1.4, using S3 File Adapter

#### Steps to reproduce
Upload file through parse.  Url is returned.

Hit new file through Parse (directAccess: false) with no credentials and it returns properly.  I believe in previous versions this request required Parse credentials.  Is this by design?

**Comment by Cliffordwh** [comment]
@nkranes I think it is. I noticed that too.  

Just out of curiosity where did you set the credentials for the S3Adaptor?. Im using a config  JSON file to run with pm2 but cant seem to configure it now with 2.1.4.

**Comment by flovilmart** [comment]
@Cliffordwh for now we don't have a support for those env variables :(

**Comment by Cliffordwh** [comment]
OOOo makes sense. Where could i then hard code a quick fix to get it to work. in 2.1.3 i managed to just code it into `/usr/bin/parse-server`

**Comment by flovilmart** [comment]
I'm on it!

**Comment by nkranes** [comment]
@Cliffordwh I don't use env vars.  My config looks like:
var api = new ParseServer({
  databaseURI: 'mongodb://localhost:27017/dev',
  cloud: {path}'
  appId: 'myAppId',
  masterKey: 'myMasterKey', // Keep this key secret!
  fileKey: 'optionalFileKey',
  serverURL: 'http://localhost:' + port, // Don't forget to change to https if needed
  allowClientClassCreation: 'false',
  filesAdapter: new S3Adapter(
    '{access_key}',
    '{secret_key}',
    '{bucket_name}',
    { directAccess: false}
  ),
});

**Comment by Cliffordwh** [comment]
@nkranes Thanks. Was just informed it wont work yet with env.

**Comment by nkranes** [comment]
So @flovilmart , is open S3 file access through Parse intentionally open?

**Comment by nkranes** [comment]
@Cliffordwh - yeah, @flovilmart types faster than I do. :)

**Comment by Cliffordwh** [comment]
@flovilmart  Thanks for that. So is it save to run  ` "PARSE_SERVER_FILES_ADAPTER" : "S3Adapter",` in my config with the other env's?

Cause that didnt work for me/.

**Comment by flovilmart** [comment]
Hat would need to be the full path to the module I believe

**Comment by flovilmart** [comment]
like parse-server/Adapters/Files/S3Adapter

**Comment by gfosco** [comment]
If I understand the issue correctly, this is the intended behavior of files.  If you have a file URL, you have access to the file.  This is also how it worked on Parse.com.

**Comment by chderen** [comment]
@gfosco so there is no real difference between directAccess true or false. if the file url is known, the file is accessible. i am right?
