### ISSUE TITLE
push notification error in APNS Connection

### ISSUE THREAD

**Issue by mahabubakram** [ParsePlatform/parse-server#834]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

-[X] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

-[X] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

-[X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

What I want to do 
1. I want to send push notification to my iOS client devices.

What I did:

I have stored my certificates in my server and also coded the way. 
https://github.com/ParsePlatform/parse-server/issues/736

Push works: sometimes.

But sometime push fails.

My push send code:

    Parse.Push.send(
        {
            channels: ["user_" + request.params.id],
            data:
            {
                alert: 'Sending push notification'
            }
        },
        {
            success: function() {
                console.log('##### PUSH OK');
                response.success("Push Success");
            },
            error: function(error) {
                console.log('##### PUSH ERROR');
                response.error("Push error");
            },
            useMasterKey: true
        });

Problem:

Always I get success. But sometime push appears in my device and sometime it does not.

and also My console log is in the server always like this:

```
{ params: { id: '45J1QIaKIi' },
  master: false,
  user: { _objCount: 0, className: '_User', id: '45J1QIaKIi' },
  installationId: '82e1d517-7aac-d887-d02b-e407c3de5e7f' }
##### PUSH OK

APNS Connection 0 Socket Error
APNS Connection 0 Socket Error
APNS Connection 0 Socket Error
APNS Connection 0 Disconnected
APNS Connection 0 Socket Error
APNS Connection 0 Disconnected
APNS Connection 0 Socket Error
APNS Connection 0 Socket Error
APNS Connection 0 Disconnected
APNS Connection 0 Socket Error
APNS Connection 0 Socket Error
APNS Connection 0 Disconnected
APNS Connection 0 Socket Error
APNS Connection 0 Socket Error
APNS Connection 0 Disconnected
APNS Connection 0 Socket Error
APNS Connection 0 Socket Error
APNS Connection 0 Disconnected
APNS Connection 0 Socket Error
APNS Connection 0 Socket Error
APNS Connection 0 Disconnected
```

How to solve this.

**Comment by flovilmart** [comment]
Can you isolate the case that work and the case that don't?
