### ISSUE TITLE
User.get('username') undefined in afterSave Cloud function

### ISSUE THREAD

**Issue by flavordaaave** [ParsePlatform/parse-server#836]
#### Environment Setup
Version 2.1.4

#### Steps to reproduce
Cloud function:
```
Parse.Cloud.afterSave('_User', function(request, response) {
  Parse.Cloud.useMasterKey();
  console.log(request.object.get('username'));
}
```
#### Logs/Trace
When signing up a new user this returns `undefined`

**Comment by sdf611097** [comment]
2.1.4 afterSave for _User does not fetch full data.
But this issue seems have been resolved with latest code.

**Comment by flavordaaave** [comment]
Still undefined in 2.1.5

**Comment by flovilmart** [comment]
Check with 2.1.6 that's just out?

**Comment by sdf611097** [comment]
2.1.6 is not work, I'm finding my code is base on which commit.
I can get username when after save user on my env.

**Comment by sdf611097** [comment]
my base is bd89338b39d384ab795ab39659b705be90ca7d2f
It not up-to-date, but it's work. Sorry

**Comment by sdf611097** [comment]
in 
RestWrite.prototype.runAfterTrigger

add blow line, it will work
updatedObject._finishFetch(this.data);

I'm not sure why _finishFetch is gone

**Comment by flovilmart** [comment]
_finishFetch has been replaced by updatedObject.set(Parse._decode(undefined, this.data));

Not sure why?

@nlutsenko ?

**Comment by sdf611097** [comment]
seems updatedObject.set(Parse._decode(undefined, this.data)) not get the full data of user

the data before triggers.maybeRunTrigger(triggers.Types.afterSave, this.auth, updatedObject, originalObject, this.config.applicationId);  

updatedObject { createdAt: '2016-03-12T03:26:43.661Z',
  sessionToken: 'r:69b9aa23572345a69f21725d5dfb2b29',
  updatedAt: '2016-03-12T03:26:43.661Z',
  objectId: 'TvaH7oXI9p' }
originalObject undefined

print by
 console.log('updatedObject',updatedObject.toJSON());
 console.log('originalObject',originalObject);

_finishFetch will get username but npm test failed

miscellaneous afterSave flattens custom operations
  Message:
    Expected IncrementOp({ _amount: 1 }) to equal 1.
  Stack:
    Error: Expected IncrementOp({ _amount: 1 }) to equal 1.
        at ParseAPI.spec.js:756:36
        at triggers.js:161:5
        at new Promise (/Users/ChunTingLin/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:197:7)
        at Object.maybeRunTrigger (triggers.js:152:10)


Hope this info is useful

**Comment by flovilmart** [comment]
The fetch occurs earlier, for some reason, all the data is properly set before going into the trigger, but for some reason, the get() is not properly performed.

**Comment by flovilmart** [comment]
I found the error. Proposing a fix soon
