### ISSUE TITLE
Add Adminca to wiki community links

### ISSUE THREAD

**Issue by JordanVincent** [ParsePlatform/parse-server#838]
At Adminca, we created a data browser for Parse Server. It could be very useful for anyone looking for a free admin panel before the dashboard is released. Would it be possible to add it to the wiki under community links? Thanks!
http://adminca.com

**Comment by gfosco** [comment]
Done, added the wiki link. :+1: 

The real dashboard is released now though: http://blog.parse.com/announcements/introducing-the-parse-server-dashboard/

**Comment by JordanVincent** [comment]
Thank you very much!

Indeed, and I believe it can be used in combination.
