### ISSUE TITLE
Increase ParseObject Size & Limit Parameter

### ISSUE THREAD

**Issue by mithleshjs** [ParsePlatform/parse-server#84]
Can we increase number of objects returned in a single result set from 1000 to some higher value and Parse Object size from 128 K to some higher value ?

**Comment by gfosco** [comment]
That's one of the benefits of parse-server.  These limits don't exist.  There's currently no query limit (but we should probably still set the default to 100 for compatibility.)  There's also no enforced limit on object size, but database people would still likely recommend you to keep them as small as possible for performance.

**Comment by sanergulec** [comment]
Hello gfosco, while saying "there is currently no limit" do you mean when we use parse server in AWS by clicking the deploy option, the parse server that is deployed has no limits like 10mb file, 120kb object etc. So if we need these limits for performance issues, should we add them by ourself? Or are they existing currently but we can remove them?

**Comment by flovilmart** [comment]
The 10mb file upload is managed by the option maxUploadSize, you can set it to whatever value you want.

For the 120k limit was a limit imposed by Parse, please refer to mongodb documentation for more information: https://docs.mongodb.org/manual/reference/limits/

**Comment by pupoo** [comment]
How do i change the maxUpload size?  i can see the line in the filesrouters.js source file in the sample project but can locate the file when looking through the bitnami server via have SSH.

**Comment by sayoojvalsan-demandmedia** [comment]
I  tweaked maxUploadSize, but still not able to upload large files like 100Mb. I am using Google cloud storage as File adapter.

**Comment by pupoo** [comment]
Where did you tweak maxupload size? I tried server.js but not available.  I think maybe I need to set up server on mondodb to get al features

**Comment by grantespo** [comment]
Where is maxupload size?

**Comment by pupoo** [comment]
index.js

**Comment by HelaBela** [comment]
Hi, 
it's a good question - how to increase the upload size on Parse? I still dont understand how to do that. @pupoo suggests index.js , in Parse Dashboard or AWS ? How and where to access that? Also I found on Parse documentation that : "We recommend against creating more than 64 fields on a single Parse Object to ensure that we can build effective indexes for your queries." Well if that is the case, maybe it is a bad idea to change the limit but how to upload a picture then ? A random pic on my phone is bigger than the limit. Or would you suggest a different server for apps like instagram ?

**Comment by flovilmart** [comment]
The limit to upload a picture can be set upon initialization of parse-server with the maxFileSize parameter. The 64 columns recommendation don’t apply anymore.

**Comment by HelaBela** [comment]
thanks for a quick reply. I initialize the parse-server using AWS and Bitnami. Once I have Bitnami on the terminal I type : cd apps/parse/htdocs and once I am at htdocs I type vi server.js and that's when I get keys I use in Android Studio. On which stage exactly I could set the limit? I am quite new to this topic, sorry if my question seems trivial

**Comment by redroostertech** [comment]
Here is a link to find where to adjust the maxUploadSize .

https://serverfault.com/questions/786728/parse-server-upload-size-limit-more-than-100mb

**Comment by comming-soon-official** [comment]
im uploading Datasets to my ec2 instance using file adapter to parseserver its about 2GB but im getting error only what is maximum limit ??
