### ISSUE TITLE
cloud code returns files @ "files.parse.com" even for new uploads.

### ISSUE THREAD

**Issue by occurrentarts** [ParsePlatform/parse-server#842]
#### Environment Setup

Built off one-click deployment to aws elastic beanstalk + mLabs.

#### Steps to reproduce

1. Create an object which includes a file ( image ) and save it to Parse-Server.

2. In parse client ( iOS in my case ) return object from cloud code.

3. View object's file's url.

Parse-Server always returns objects with files from files.parse.com
This is obviously inaccurate because you recently created the file, so you will probably get a 403 error.

**Comment by gfosco** [comment]
What is the 'name' key on this file object?  It should only attempt to build a files.parsetfss.com url if it starts with tfss-..

**Comment by occurrentarts** [comment]
it just starts with a timecode, not tfss.
And even stranger, it doesn't hand back files.parsetfss.com in this situation, it hands back files at files.parse.com

In case anyone else is encountering this, here's a band-aid i use to catch the urls with this issue and point them back at my server instead:

`var image_locations = new Array(sorted_results.length);
					
					for(var i = 0; i < sorted_results.length; i++){
				
						var post = sorted_results[i];
			
						//add this to the array
						var image = post.get("image");
						var url = image.url();
						
						image_locations[i] = url.replace("files.parse.com/my-file-key/", "my-server.us-east-1.elasticbeanstalk.com/parse/files/my-app-id/");
								
						image._url = image_locations[i];		
								
						//var pointer = new Post();
						//pointer.id = thisPost.id;
				
					}
								
					//return array of posts
					response.success({posts:sorted_results,locations:image_locations});//`

**Comment by occurrentarts** [comment]
this was a bug which seems to have been fixed in 2.1.0 as noted in line 18:
https://github.com/ParsePlatform/parse-server/commit/52c4c4b9e944bed3d5da9c51ae8391f1748b21ab
