### ISSUE TITLE
Parse Server doesn't return sessionToken on Parse.User.current().fetch() on JS SDK

### ISSUE THREAD

**Issue by tobernguyen** [ParsePlatform/parse-server#845]
In my Facebook application, when I call `Parse.User.current().fetch()`, Parse Server won't return `sessionToken` for that user as Parse API do. After that JS SDK will save that response (without sessionToken) into localStorage, which made all request after that not include sessionToken.

In my case, after call `Parse.User.current().fetch()`, I cannot call any cloud function because cloud code will check if the request is called by a logged-in user.

I have added two images, one is call fetch current user via Parse API, and one via Parse Server, 2 servers connected to the same database.

**Response from Parse API**
![response from parse com](https://cloud.githubusercontent.com/assets/10015525/13545753/536d37fc-e2c8-11e5-834d-1e9cb93c28aa.png)

**Response from Parse Server** (missing `sessionToken`)
![response from parse server](https://cloud.githubusercontent.com/assets/10015525/13545756/7b01ce9a-e2c8-11e5-9ca7-d9db952cbbb5.png)

**Comment by tobernguyen** [comment]
After a long time research, I figured out that this error is caused by this #852

**Comment by gfosco** [comment]
Fixed by 857, will be in next release.  :+1:
