### ISSUE TITLE
Unable to Login using JavaScript / REST API

### ISSUE THREAD

**Issue by rudymacias** [ParsePlatform/parse-server#85]
Both ways trying to login returns

{"code":1,"message":"Internal server error."}

Set up server with Heroku and the logs state:

2016-01-30T22:23:30.852720+00:00 app[web.1]: Uncaught internal server error. bad obj: undefined undefined

Any help would be appreciated!

**Comment by gfosco** [comment]
This error is being thrown here: https://github.com/ParsePlatform/parse-server/blob/7f5d744ce2eea774a10ab0a8c47bd587941c7775/Schema.js#L294

Can you provide the result from the _SCHEMA collection in mongo for the _User class?

**Comment by rudymacias** [comment]
{
    "_id": "_User",
    "group": "string",
    "status": "string",
    "firstName": "string",
    "lastName": "string",
    "email": "string",
    "username": "string",
    "password": "string",
    "updatedAt": "string",
    "createdAt": "string",
    "objectId": "string"
}

**Comment by gfosco** [comment]
Ok, that doesn't tell us much.  Can you provide the login code you're using?  If you can, set the environment variable VERBOSE=1 and capture that log as well.

**Comment by rudymacias** [comment]
Sorry ok here is the curl request:

curl -X GET \
  -H "X-Parse-Application-Id: myAppId" \
  -H "X-Parse-REST-API-Key: myRestAPIKey" \
  -H "X-Parse-Revocable-Session: 1" \
  -G \
  --data-urlencode 'username=test@yahoo.com' \
  --data-urlencode 'password=12345678' \
https://intense-bayou-17052.herokuapp.com/parse/login

Heroku LOG:

2016-01-31T00:29:11.502181+00:00 app[web.1]: Uncaught internal server error. bad obj: undefined undefined
2016-01-31T00:29:11.513905+00:00 heroku[router]: at=info method=GET path="/parse/login?username=test%40yahoo.com&password=12345678" host=intense-bayou-17052.herokuapp.com request_id=2de8daf8-cbc5-4d47-9d50-ca085c599a22 fwd="75.1.114.162" dyno=web.1 connect=0ms service=1541ms status=500 bytes=358

**Comment by cainoeraabele** [comment]
in my case the problem is here : https://github.com/ParsePlatform/parse-server/blob/7f5d744ce2eea774a10ab0a8c47bd587941c7775/users.js#L71

in the user.js file 
when try to validate the schema, req.info.installationId was undefined.
For now i have deleted that line and everything working good

**Comment by rudymacias** [comment]
@cainoeraabele Thanks! Yes that worked for me too, OH and also, not sure if my JS App or the Parse Server was in fault, but the Schema for Session had "expiresAt" as "number" so that also thru errors. Changing that to "string" corrected the issue. I'm able to Login finally YEAH!

**Comment by gfosco** [comment]
I think we've got these covered in 2.0.4... Open new issues if you have problems.  Thanks.
