### ISSUE TITLE
request.user is undefined after v2.1.4

### ISSUE THREAD

**Issue by tanmays** [ParsePlatform/parse-server#851]
Hello,

Ever since upgrading to 2.1.4, `request.user` is undefined in Cloud Code functions even after passing a valid session token. Prior to this release everything used to work well. 

Here's an example: 

Console log:

```
POST /parse/functions/GetBookmarks { host: '6115ba6a.ngrok.io',
  'content-type': 'application/json',
  'content-length': '0',
  'x-parse-session-token': 'r:<session-token-removed>',
  accept: '*/*',
  'user-agent': 'Pinglar/0.2 (iPhone; iOS 9.0.1; Scale/2.00)',
  'x-parse-application-id': 'xxx',
  'accept-language': 'en;q=1',
  'accept-encoding': 'gzip, deflate',
  'x-forwarded-proto': 'https',
  'x-forwarded-for': 'xxx.88.191.58' } {}
User is: undefined
```

Cloud Code:

```
Parse.Cloud.define("GetBookmarks", function(request, response) {

  var LinksSaved = Parse.Object.extend("LinksSaved");

  console.log("User is: " + JSON.stringify(request.user));

  var query = new Parse.Query(LinksSaved);
  query.equalTo("user", request.user);
  query.include("user");

  query.find({
      success: function(bookmarks) {
        response.success(bookmarks);
      },
      error: function(error) { // query error
        console.log("Unable to fetch bookmarks: "+ JSON.stringify(error));
        response.error(error);
      }
  });

});
```

**Comment by tobernguyen** [comment]
@tanmays you may want to have a look on my issue reported here #852 . I think it is related to your problem because I also experienced it too. 

Please have a look and try to produce my issue to see if it is the reason of this your issue. Thanks.

**Comment by tobernguyen** [comment]
What login method do you use?

**Comment by tanmays** [comment]
@tobernguyen You're right. I tested it a bit more and can confirm the issue you are facing. It only happens when using social login. (Twitter in my case)

**Comment by tobernguyen** [comment]
I just created a pull request to resolve that issue. Have a look here: #857

**Comment by tanmays** [comment]
@tobernguyen thanks! Will check it out :+1:

**Comment by gfosco** [comment]
Fixed by 857 and will be in the next release.  Sorry for the inconvenience!
