### ISSUE TITLE
Parse Web Dashboard

### ISSUE THREAD

**Issue by thamer898** [ParsePlatform/parse-server#854]
Hello

When the Parse dashboard will be available for parse server ?

Regards

**Comment by tobernguyen** [comment]
https://github.com/ParsePlatform/parse-dashboard

**Comment by thamer898** [comment]
Hello @tobernguyen 

How to update my existing parse server to get the updates ? 

Regards

**Comment by flovilmart** [comment]
the parse-dashboard is a separate project so you have to run it independently

**Comment by thamer898** [comment]
Hello

great how to get parse version number also how to update existing parse server ?

Regards
