### ISSUE TITLE
Error when using Parse.Query

### ISSUE THREAD

**Issue by jiewmeng** [ParsePlatform/parse-server#860]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [X ] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [ X] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [X ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

- Local Node and MongoDB
- Tried both Node 4.2.2 and 5.7.0

#### Steps to reproduce

- Clone parse server example
- Add cloud function

```js
Parse.Cloud.define('test', function(req, res) {
	var query = new Parse.Query(Parse.User);
	query.count()
		.then(count => res.success(count))
		.fail(err => res.error(err.message));
})
```

- Call cloud function via POSTMAN

```json
{
  "code": 141,
  "error": "Received an error with invalid JSON from Parse: Cannot POST /classes/_User\n"
}
```

#### Logs/Trace

**Comment by drew-gross** [comment]
It looks like you forgot to include your parse mount point in URL when you initialized your SDK.

**Comment by jiewmeng** [comment]
@drew-gross Ok fixed that. Maybe the example app should have it set. I was thinking the devs of parse server intended for the severURL to omit the parse mount point
