### ISSUE TITLE
Updating attributes in beforeSave not working

### ISSUE THREAD

**Issue by jiewmeng** [ParsePlatform/parse-server#866]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [X] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [X] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

- Localhost
- Node 5.7
- MongoDB 3.2.3

#### Steps to reproduce

In main.js add

- define a test class
- define before save for it to update 1 attribute
- define a cloud function that you can use to try this via Postman or something
- I expect the beforeSave to set/update an attribute but its not happening ... 

```javascript
var Testing1 = Parse.Object.extend('Testing1');

Parse.Cloud.beforeSave('Testing1', function(req, res) {
	var obj = req.object;
	console.log('In b4 save Testing1', obj.toJSON());

	obj.set('override', Date.now());
	res.success(obj);
});

Parse.Cloud.define('test', function(req, res) {
	var t1 = new Testing1({ name: 'X' });

	t1.save()
		.then(o => {
			console.log('After saving', o.toJSON());
			res.success(o);
		})
		.fail(err => res.error(err.message));
})
```

The result: 

```json
{
  "result": {
    "name": "X",
    "createdAt": "2016-03-06T10:22:20.041Z",
    "updatedAt": "2016-03-06T10:22:20.041Z",
    "objectId": "eyw0agyTof",
    "__type": "Object",
    "className": "Testing1"
  }
}
```

`override` attribute not set as expected

**Comment by gfosco** [comment]
I was just working on this and submitted #865 to correct this for an older issue. :+1: It will be fixed in the next release.

**Comment by jiewmeng** [comment]
@gfosco awesome

**Comment by btate** [comment]
Any timeline on the next release with this fix?

**Comment by mmazzarolo** [comment]
+1, any info? Still having this issue on `"parse-server": "^2.1.5",`

**Comment by brian473** [comment]
I still seem to have this problem on version 2.2.4. Am I doing something wrong here? My code looks identical to the example @jiewmeng provided.

**Comment by flavionegrao** [comment]
I am using version 2.2.7 and seems that after you changed the request.object your have to call `response.success()` rather than `response.success(request.object)`

**Comment by mmarshak** [comment]
@ flovilmart , @gfosco , it seems that @flavionegrao  solution works. It seems that if in the beforeSave I add a new field to the object being save and call response.success("some string) then the new field is not being added to the object being saved, but if I do response.success() it does add the filed?
