### ISSUE TITLE
Using parse-server master branch

### ISSUE THREAD

**Issue by jiewmeng** [ParsePlatform/parse-server#868]
Since some fixes on master might not be available on the NPM package, I wonder how can I use parse server from github. I tried

    npm install --save ParsePlatform/parse-server

But I get 

    Error: Cannot find module 'parse-server'

When parse server is required. I noticed in node_modules, lib is empty.

**Comment by gfosco** [comment]
I think this is a duplicate of #700 which @drew-gross is looking in to.
