### ISSUE TITLE
Set limit on nested queries

### ISSUE THREAD

**Issue by mtrezza** [ParsePlatform/parse-server#870]
The current Parse Server limits the number of nested queries to 3, i.e. nesting with `whereKey(..., matchesKey: ..., inQuery: ...)`.

1. What is the reason for this limit? Was it for performance control or merely a pricing aspect since Parse.com priced on number of queries and with nesting one would get "3 queries for the price of 1".

2. Where is this controlled in Parse Server?
3. Would it be reasonable to be able to individually set this limit on the Parse Server?

**Comment by flovilmart** [comment]
You can try to use more than 3 nested queries, I don't believe there is such hard coded implementation in this implementation

**Comment by mtrezza** [comment]
Sorry, you are right, Parse Server doesn't have that limitation, only Parse.com has. I mixed up the connections in my test.
