### ISSUE TITLE
Relations are now bidirectional, unlike at parse.com

### ISSUE THREAD

**Issue by derickito** [ParsePlatform/parse-server#871]
#### Environment Setup
I'm running Node 4.3, Mongo 3.0.9 in DigitalOcean

#### Steps to reproduce
If a user has a like relation of type User and user A likes user B and you query user B's like relation for user A it returns true, which it's supposed to return false, since user B hasn't liked user A.
This is the way relations worked for my app in parse.com. Am I doing something wrong?

**Comment by flovilmart** [comment]
That would help to have more informations about that problem a test case, example etc...

**Comment by drew-gross** [comment]
I've added a test that checks for this in #1283, which passes. If you are doing something differently in your code and is not behaving how you expect, please open a new issue and include your code that is failing.
