### ISSUE TITLE
How to update Heroku parser-server with latest code from github?

### ISSUE THREAD

**Issue by astanton** [ParsePlatform/parse-server#879]
Sorry but this may be a really dumb question and I googled but had no luck, but I am not sure how to update my Heroku parse-server with the latest code on github.  I used the "1 button push" installation on Heroku, so I'm not even sure which version they installed at the time (nor how to find out).

I'd like to get the latest code base because it appears a fix for an issue holding me back has been made.

https://github.com/ParsePlatform/parse-server/pull/773

Which I am having this exact issue someone posted here:

https://github.com/ParsePlatform/parse-server/issues/783

I tried updating the version in my package.json to 2.1.4 (it was 2.1.2) and pushed it but it appears I'm still getting the same error as the guy in #783 so I didn't think it actually worked.

The latest code on github has that change so I'm just wondering how I can update my parse-server code on there, thanks!

**Comment by gfosco** [comment]
To clone the project you've deployed with the heroku button, you use the Heroku Toolbelt, the command line tool: https://toolbelt.heroku.com/

They explain how to use it to clone a deployed app: https://devcenter.heroku.com/articles/git-clone-heroku-app

Updating the example and running on master is not trivial... I tried it and this is what it took:

* Cloned the project from heroku
* Changed directory to the project folder
* Cloned parse-server: git clone git@github.com:ParsePlatform/parse-server.git
* Changed directory to `parse-server/`
* Ran `rm -rf .git` and `rm .gitignore`
* Ran `npm install` and then `npm run build`
* Changed directory back to the project folder
* Edited `package.json` to change the `parse-server` dependency from a version number to `file:./parse-server/`
* Edited `.gitignore` and removed `node_modules` from it.
* ran `npm install`
* ran `npm start`

I verified this works locally, and then did the git add, commit, push to send it to heroku.. 

Probably better to just wait for 2.1.5, it should be out Monday or Tuesday.

**Comment by flovilmart** [comment]
There is an easier way:

- clone project from heroku
- in project folder
- git submodule add  git@github.com:ParsePlatform/parse-server.git
- npm link parse-server ./parse-server

You should be good to go.

When it comes to update your submodule, 

``` 
# change to the submodule directory
cd parse-server

# checkout desired branch
git checkout master

# update
git pull

# get back to your project root
cd ..

# now the submodules are in the state you want, so
git commit -am "Pulled last version of parse-server"
```

**Comment by astanton** [comment]
Thanks I updated but it appears to not have solved the issue I had, I'll open a new issue explaining it in more details.

**Comment by ashish-naik** [comment]
Hi, 

I followed steps you have mentioned. i encountered errors when running step 2 so ran with sudo and it worked. 
but **git push heroku master** fails with below log. I tried everything i could find on stackverflow.com etc but nothing worked. tried deleting keys from Heroku account, generated new keys, login, logout from Heroku. All effort failed. I am new to Node, Heroku etc so finding even more difficult to solve.

please help. What could be wrong? My directory structure is as below:

app name
   |- node_modules
   |- parse-server
   |- package.json
   
Counting objects: 4590, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4184/4184), done.
Writing objects: 100% (4590/4590), 3.36 MiB | 79.00 KiB/s, done.
Total 4590 (delta 943), reused 0 (delta 0)
remote: Git submodules detected, installing:
remote: Submodule 'parse-server' (git@github.com:ParsePlatform/parse-server.git) registered for path 'parse-server'
remote: Cloning into 'parse-server'...
remote: Host key verification failed.
remote: fatal: Could not read from remote repository.
remote:
remote: Please make sure you have the correct access rights
remote: and the repository exists.
remote: Clone of 'git@github.com:ParsePlatform/parse-server.git' into submodule path 'parse-server' failed
remote:
remote: !	Push rejected, submodule install failed
remote:
To https://git.heroku.com/appname.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/appname.git'

**Comment by ksngits** [comment]
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:ParsePlatform/parse-server.git' into submodule path 'parse-server' failed

am i missing something
