### ISSUE TITLE
Parse.Cloud.httpRequest fails if body is not a string

### ISSUE THREAD

**Issue by natanrolnik** [ParsePlatform/parse-server#88]
Hey Fosco!

In one of my objects, I had a `afterSave` hook where I do a http post to another Parse app.
However, the `body` parameter passed is an object, not a string, and this causes the app to throw an exception:

```
_http_outgoing.js:430
    throw new TypeError('first argument must be a string or Buffer');
    ^
```

I looked into it, and locally was able to solve it in a easy way. When defining `Parse.Cloud.httpRequest` in `index.js`, line 145 I added:

```
if (typeof options.body === 'object') {
      options.body = JSON.stringify(options.body);
}
```

It simply converts the object to a string if it's necessary. Is this a correct fix? If so, I can open a PR.

**Comment by gfosco** [comment]
Please open the PR.  Yeah, it looks like the 'request' module we use only supports a string body.

**Comment by natanrolnik** [comment]
But it works fine when running it in the Parse hosted Cloud Code

**Comment by gfosco** [comment]
Because Parse hosted cloud code doesn't use node or the 'request' module... It's a v8 engine with some node-like properties, but mostly custom built.

**Comment by natanrolnik** [comment]
I see... Ok, will add it soon. Thanks!

**Comment by natanrolnik** [comment]
Small JS question: if options.body was not defined, is this code I suggested still safe?

**Comment by gfosco** [comment]
Should be, yeah.
