### ISSUE TITLE
Valid Parse.User.current() immediately after Parse.User.logOut()

### ISSUE THREAD

**Issue by andresgarza** [ParsePlatform/parse-server#882]
Retrieving the current user immediately after logging out still returns a valid User:

```
Parse.User.logOut();
Parse.User.current(); // returns previous User
```

I'm not entirely sure whether this is intended or not, as the code for `logout` does use `currentUserAsync`, but the documentation in the Developers Guide does imply that the current user should be null immediately after calling `logOut`:

<img width="624" alt="screen shot 2016-03-07 at 12 27 19 am" src="https://cloud.githubusercontent.com/assets/154718/13562209/791009ec-e3fb-11e5-9106-28b08908e0c8.png">

**Comment by otymartin** [comment]
I'm having the same problem in iOS.
`PFUser.currentUser()` still persists after running the following method..
```swift
PFUser.currentUser.logout()
```

**Comment by andresgarza** [comment]
I apologize, I meant to file this issue in the Parse-SDK-JS repo. Self-closing.

**Comment by andresgarza** [comment]
https://github.com/ParsePlatform/Parse-SDK-JS/issues/219
