### ISSUE TITLE
About production apps

### ISSUE THREAD

**Issue by uch71109** [ParsePlatform/parse-server#884]
Hi,

    I saw parse migration guide https://github.com/ParsePlatform/parse-server/wiki/Migrating-an-Existing-Parse-App 
    said that "If you haven't migrated your database by April 28, we will assume your app is low priority, 
    and we will de-prioritize its traffic to focus on production apps."
    
    My question is that does "production apps" mean the toggle option in setting dashboard as attached?
    
![default](https://cloud.githubusercontent.com/assets/7931376/13563848/472a0b8c-e480-11e5-8576-0515cbbb2ef4.jpg)

**Comment by gfosco** [comment]
The dashboard setting is really just a signal.  A way of telling us this isn't a test app or a toy, it's something you consider a serious app in production use.  

As to the migration verbiage, we're considering another signal...  The database migration is pretty quick and easy, so if you haven't migrated by 4/28, it tells us that you don't really value the application.  It's encouragement, to not put it off till the last minute.
