### ISSUE TITLE
New MailAdapter seems to be crashing on AZURE

### ISSUE THREAD

**Issue by mllobere** [ParsePlatform/parse-server#885]
I tried to update the parse-server to 2.1.4 but when deploying to AZURE, it seems to have an issue : 

> Failed to stat file 'D:/home/site/repository/node_modules/parse-server/node_modules/mailgun-js/node_modules/proxy-agent/node_modules/pac-proxy-agent/node_modules/pac-resolver/node_modules/degenerator/node_modules/escodegen/node_modules/source-map/lib/source-map/source-map-consumer.js': The data area passed to a system call is too small.\r\n

I am not sure if this is Azure fault or mailgun or anything else ? Maybe this do not even belong to parse-server ? 
@2.1.0 deploys correctly. Haven't try 2.1.1/2.1.2/2.1.3

**Comment by gfosco** [comment]
Looks like the first reference there is the mailgun module, which was added in 2.1.4.  Not sure why Azure is having a problem (though that chain of directories is suspiciously long.)

**Comment by flovilmart** [comment]
It's deployed on an azure windows server, it's totally possible we don't put some paths correctly.

@mllobere can you deploy on azure over ubuntu or debian?

**Comment by mllobere** [comment]
I am not sure how to deploy a web app (AZURE) on ubuntu or debian.

However, I have updated npm to the latest version (3.8.2) and everything is working ok now.  I was using 2.10.1 for some reasons... I guess the flat module installation feature of npm3 is fixing issue of long chain of directories.
