### ISSUE TITLE
Extra queries to _SCHEMA

### ISSUE THREAD

**Issue by steven-supersolid** [ParsePlatform/parse-server#896]
I've tested running some simple operations using parse.com and using parse-server on Heroku, using the same Parse application and database on mLab. I enabled profiling level 2 and performed the following:

**Query on _User**
parse.com:
`{ "op" : "query", "ns" : "myapp._User", "query" : { "$query" : { "_id" : "1" }...`

parse-server:
`{ "op" : "query", "ns" : "myapp._SCHEMA", "query" : {  }...`
`{ "op" : "query", "ns" : "myapp._User", "query" : { "$query" : { "_id" : "1" }...`

So there is an extra query on _SCHEMA each time.

**Save Inventory (custom class)**
parse.com:
`{ "op" : "command", "ns" : "myapp.$cmd", "command" : { "findAndModify" : "Inventory", "query" : { "_id" : "rtWGOfh6bo" }...`

parse-server:
`{ "op" : "query", "ns" : "myapp._SCHEMA", "query" : {  }...`
`{ "op" : "query", "ns" : "myapp._SCHEMA", "query" : {  }...`
`{ "op" : "command", "ns" : "myapp.$cmd", "command" : { "findandmodify" : "Inventory", "query" : { "_id" : "i3fwQlIeeB" }...`

This is querying _SCHEMA twice for each call.

My use case is to query Inventory, modify and then save so this actually performs a total of 3 _SCHEMA queries. During a previous test I also noticed additional queries to _Role but those were not present in this recent test, possibly due to a change in parse-server. Each query to _Role also incurred an additional query to _SCHEMA so I'll repeat the test.

If some of the additional queries to _SCHEMA could be avoided, particularly the double query on save then it may improve the max request/second. Even better would be to add an option to disable queries on _SCHEMA because my application code already knows what the schema is.

**Comment by drew-gross** [comment]
Fixed by #919

**Comment by steven-supersolid** [comment]
I've added some trace statements and found this unrelated to the mentioned PR. Please can this be re-opened @drew-gross?

Find object:
```
Trace: loadSchema
    at DatabaseController.loadSchema (Controllers\DatabaseController.js:74:10)
    at DatabaseController.find (Controllers\DatabaseController.js:649:15)
    at RestQuery.runFind (RestQuery.js:492:31)
    at RestQuery.js:184:18
```

This seems to be a limitation of the library - the schema needs to be read each time there is a rest request.

Save object:
```
Trace: loadSchema
    at DatabaseController.loadSchema (Controllers\DatabaseController.js:74:10)
    at DatabaseController.validateObject (Controllers\DatabaseController.js:120:15)
    at RestWrite.validateSchema (RestWrite.js:144:31)
    at RestWrite.js:75:18

Trace: loadSchema
    at DatabaseController.loadSchema (Controllers\DatabaseController.js:74:10)
    at DatabaseController.update (Controllers\DatabaseController.js:160:15)
    at RestWrite.runDatabaseOperation (RestWrite.js:752:33)
    at RestWrite.js:91:18
```

Potentially once the schema has been loaded in RestWrite.validateSchema it could be passed as an optional parameter to DatabaseController.update.

**Comment by drew-gross** [comment]
Sure, we will keep working on this.

**Comment by Marco129** [comment]
Probably is the problem near [L63](https://github.com/ParsePlatform/parse-server/blob/master/src/Controllers/DatabaseController.js#L63) and [L74](https://github.com/ParsePlatform/parse-server/blob/master/src/Controllers/DatabaseController.js#L74) in DatabaseController.js.
The `schemaPromise` is never save

**Comment by flovilmart** [comment]
We could definitely keep a cache in memory of the _Schemas

**Comment by flovilmart** [comment]
We've added a schema cache a while ago, closing. Feel free to reopen if the issue persist.
