### ISSUE TITLE
Role security for classes

### ISSUE THREAD

**Issue by vladtamas** [ParsePlatform/parse-server#899]
Hi,

How can I create users with roles that can access only specific classes?

**Comment by flovilmart** [comment]
Look into class level permissions.

you should issue a PUT request to:

http://YOUR_PARSE-SERVER/parse/schemas/:className

with the headers
{
 'X-Parse-Application-Id': 'ApplicationID',
 'X-Parse-Master-Key': 'masterKey'
}

json body: 
```
{
classLevelPermissions: {
   'find': {
      'role:my_role': true // Only the users from my_role will be able to find objects
   }
}
} 
```

other permissions include: 'find', 'create', 'get', 'update', 'delete', 'addField'

**Comment by TomKremer** [comment]
Hello,

I have a similar issue related to role security. After migration I get error code 119 (Clients aren't allowed to perform the find operation on the role collection.). Schema class level permissions are set correctly.
I also curl'd your answer, does not look to update the schema.

Any other ideas on why this is failing?
Thank you


Failing query (/parse/classes/_Role)
`{"where":{},"_method":"GET","_ApplicationId":"XXX","_JavaScriptKey":"XXX","_ClientVersion":"js1.6.14","_InstallationId":"ea0b8339-1e78-2baa-876e-4879df402170","_SessionToken":"r:381ae97b7baf64e6f2128c0a78e0afe7"}
`

Schema extract:
`{
    "_id": "_Role",
    "_metadata": {
        "class_permissions": {
            "get": {
                "*": true,
                "500SCa81oI": true
            },
            "find": {
                "500SCa81oI": true,
                "*": true
            },
            "update": {
                "500SCa81oI": true
            },
            "create": {
                "500SCa81oI": true
            },
            "delete": {
                "500SCa81oI": true
            },
            "addField": {
                "500SCa81oI": true
            },
            "readUserFields": [],
            "writeUserFields": []
        }
    },
    "name": "string",
    "users": "relation<_User>",
    "roles": "relation<_Role>"
}`

**Comment by flovilmart** [comment]
The error you're seeing is unrelated to CLP. This is an hard coded security feature

**Comment by poojanjhaveri** [comment]
@TomKremer were you able to solve the issue ? I have a similar error

**Comment by TomKremer** [comment]
Yes it is hard coded. Found it in src/rest.js
`// Disallowing access to the _Role collection except by master key
function enforceRoleSecurity(method, className, auth) {
  if (className === '_Role' && !auth.isMaster) {
    throw new Parse.Error(Parse.Error.OPERATION_FORBIDDEN,
                          'Clients aren\'t allowed to perform the ' +
                          method + ' operation on the role collection.');
  }
  if (method === 'delete' && className === '_Installation' && !auth.isMaster) {
    throw new Parse.Error(Parse.Error.OPERATION_FORBIDDEN,
                          'Clients aren\'t allowed to perform the ' +
                          'delete operation on the installation collection.');

  }
}`

**Comment by drew-gross** [comment]
I'm going to close this and open a new issue to discuss the implications of this potential API change.
