### ISSUE TITLE
docker image for parse-server

### ISSUE THREAD

**Issue by tahaozket** [ParsePlatform/parse-server#9]
Hi,

I created a simple docker image for parse-server. 
https://hub.docker.com/r/instainer/parse-server

It quickly runs parse-server on express inside docker container.

You can test it from here;
http://instainer.com/?deploy=instainer/parse-server

**Comment by kingmatusevich** [comment]
:+1:

**Comment by kingmatusevich** [comment]
Does your image include a mongo server? that would be a great thing to add.

**Comment by blackxored** [comment]
where's the source?

**Comment by jaysonng** [comment]
Hello! This is the first time ive heard of docker. how would this change the migration process?

**Comment by tahaozket** [comment]
@kingmatusevich yes, it does!

@blackxored you can find it from here; https://gist.github.com/tahaozket/1f1603051ce57a62f81b

**Comment by kingmatusevich** [comment]
it doesn't seem the mongodb is being exposed outside the container, which is a problem given that during the migration process we are supposed to connect to our new mongodb from parse servers.

**Comment by tahaozket** [comment]
@kingmatusevich ah sorry, you are right! I will update it to expose MongoDB ports.

**Comment by kingmatusevich** [comment]
great 😊  excellent work

**Comment by kingmatusevich** [comment]
We could probably work in embedding in this docker solution some node GCM library (works both on iOS and Android, so, pretty cross platform), and then use that to bridge the missing notification feature. Should be pretty easy to implement. This library seems pretty good: https://github.com/ToothlessGear/node-gcm

**Comment by kingmatusevich** [comment]
Just a though, also, while you are exporting mongodb, maybe you can make it so during the startup process you print a mongodb connection string to the docker console such that you make integrating with current parse servers a breeze.

**Comment by gfosco** [comment]
Added this to the wiki: https://github.com/ParsePlatform/parse-server/wiki#community-links

**Comment by blackxored** [comment]
@tahaozket Thanks! I really think you should create a repo for it for people (including myself) to contribute. For instance, installing mongodb from repos is a history we all know, having options to configure server entirely in a 12-factor way, setting `NODE_ENV` (it's Express after all isn't it), and few more issues/features, including Dockerfile improvements.

**Comment by kingmatusevich** [comment]
I agree, this should be a repo.

**Comment by kingmatusevich** [comment]
@tahaozket has been gracious and ported it into a repo: https://github.com/instainer/parse-server-docker

**Comment by blackxored** [comment]
:+1: Thanks! Expect PRs from me very soon

**Comment by tahaozket** [comment]
@kingmatusevich @blackxored thanks!

**Comment by kingmatusevich** [comment]
:+1:
