### ISSUE TITLE
New npm version

### ISSUE THREAD

**Issue by dcdspace** [ParsePlatform/parse-server#906]
When can we expect the next version of the server to be released on npm, as a lot has been fixed and it is important for my apps to have these new updates. Thanks.

**Comment by Cliffordwh** [comment]
I need this too.

**Comment by DimitrK** [comment]
I would welcome that as well.

**Comment by tobernguyen** [comment]
Yes me too. After my pull request got merged, I to visit the repo every day to check if there is a new release so I can start to migrate my production code.

**Comment by gfosco** [comment]
2.1.5 has just been published.  :+1:

**Comment by DrBeak1** [comment]
:+1:
