### ISSUE TITLE
Damn god! Still no usable Unity sdk!

### ISSUE THREAD

**Issue by huang1196** [ParsePlatform/parse-server#907]
I've been waiting for more than one month. Can someone reply to the post?
https://github.com/ParsePlatform/Parse-SDK-dotNET/issues/166

I cannot proceed our migration cuz no usable unity sdk. And no one tell us how to compile the source code to Unity dll & no updated reply.

**Comment by flovilmart** [comment]
you don't need to rush your migration to parse-server! there is still plenty of time for that!
