### ISSUE TITLE
Unable to insert an pointer object  when sending a data through android

### ISSUE THREAD

**Issue by jalasureshreddy666** [ParsePlatform/parse-server#913]
Hello,

In mongoDb we have Class/Collection that has a column which stores parse pointer.While migrating the data from parse to our mongodb the column is taking the data(i.e Parse pointer) and storing it.

When we try to send the parse pointer through android code it is not inserting that pointer in that column  instead it is creating a new column (like.. _p_columnname) where it store the data(i.e parsePointer) in this form:  columnName$objectId$othercolumnValues...

Please help us understand how to insert the parse pointer  into mongodb using Android parse 

we are using  MongodDB, Node.js, express.js, and Parse-server

Thanks

**Comment by flovilmart** [comment]
@jalasureshreddy666 this completely normal, this is to optimize the queries. Your data should be here, and you should be able to query it from the android SDK.
