### ISSUE TITLE
Is "password restore" working in current release?

### ISSUE THREAD

**Issue by dron247** [ParsePlatform/parse-server#914]
Is this feature implemented and just not documented yet and i have to implement it in different manner(via cloud code for example)? Or this feature still in progress?

Log from heroku:
`2016-03-08T12:10:53.176183+00:00 heroku[router]: at=info method=POST path="/parse/requestPasswordReset" host=testapp.herokuapp.com request_id=06ab9600-3db4-48f1-9fc6-0343df4d02a2 fwd="176.114.189.249" dyno=web.1 connect=0ms service=4ms status=500 bytes=531

2016-03-08T12:10:53.159950+00:00 app[web.1]: Uncaught internal server error. Trying to send a reset password but no adapter is set undefined`

index.js:
`
var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'myAppId',
  masterKey: process.env.MASTER_KEY || '', //Add your master key here. Keep it secret!
  serverURL: process.env.SERVER_URL || 'http://localhost:1337',  // Don't forget to change to https if needed
  mailConfig: {
    service: 'mailgun',
    apiKey: process.env.MAILGUN_API_KEY,
    domain: process.env.MAILGUN_DOMAIN,
    fromAddress: process.env.MAIL_FROM_ADDRESS
  }
});
`

in client(android) I call it via ParseUser.requestPasswordResetInBackground

**Comment by dron247** [comment]
I had changed mailConfig to
```
emailAdapter: SimpleMailgunAdapter({
    apiKey: process.env.MAILGUN_API_KEY,
    domain: process.env.MAILGUN_DOMAIN,
    fromAddress: process.env.MAIL_FROM_ADDRESS
  })
```

now i have
`2016-03-08T13:02:30.065165+00:00 heroku[router]: at=info method=POST path="/parse/requestPasswordReset" host=testapp.herokuapp.com request_id=bddac224-d839-4088-9138-5d17e965442b fwd="176.114.189.249" dyno=web.1 connect=1ms service=89ms status=200 bytes=468`
in logs, but i have no email

**Comment by tanmays** [comment]
It's probably because the current release v2.1.4 doesn't include `views` and `public_html` folders. Wait for `parse-server` release v2.1.5. 

If you added them in manually, check logs over at mailgun.com

**Comment by dron247** [comment]
@tanmays ok thanks
