### ISSUE TITLE
Access Denied for old files on Parse - even directly from Parse.com's Dashboard

### ISSUE THREAD

**Issue by omairvaiyani** [ParsePlatform/parse-server#915]
This may not be the right place to put this issue, but I thought there might be some others experiencing the same problem.

My old files, that were uploaded prior to migration, show the following error when I visit the url:

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>57C1A7AFD5BAFFAA</RequestId>
<HostId>
HtcYMu498vz0aCaaiI/CS7MPGp/8xBm+L6H7pbaNxKVbOqWPGmNtzxkGiND0pJ1g4N0wUlun9FQ=
</HostId>
</Error>
```

The link structure is ```http://files.parsetfss.com/<file-key>/tfss-79d63a74-54a2-4027-841a-c4bb4e30cf81-Dentistry.png```

I double checked on ```https://dashboard.parse.com/apps/<app-name>/settings/keys``` to see if the  ```fileKey``` matches - and it does. New uploads directly from the dashboard work fine - even though the url structure is identical. Any ideas?

**Comment by drew-gross** [comment]
That doesn't sound like an issue with Parse Server. Can you file a bug report on parse.com/help?

**Comment by threegoblins** [comment]
I have almost exactly this same problem, is there any way I can see the follow up or get more information on how to resolve this please?
My files have started showing this error after updating via my parse-server instance.

**Comment by poojanjhaveri** [comment]
Were you guys able to solve this issue ? I am running into the same problem.

**Comment by threegoblins** [comment]
Sorry I forget how now, although since then I have moved to using a hosted provider (instead of managing it myself) so that might have been it!
