### ISSUE TITLE
Add back{4}app to your wiki on Community links

### ISSUE THREAD

**Issue by alyssoncm** [ParsePlatform/parse-server#918]
back{4}app released an automatic migration wizard for Parse users on its platform. 
back{4}app is the hub for backend and APIs. Just focus on creating amazing user experiences and forget about complex infrastructure. You can build and host APIs for the web, mobile and IoT apps, working up to 80% faster. back{4}app uses Parse Open Source framework to make it happen. 
**http://www.back4app.com**
Now we already have Parse Server and Database (with cloud codes and push) running and the next release will be your dashboard. I believe that the parse is a very powerful tool that will continue to be continuously improved by the open source community. We are eager to contribute new features.
**http://blog.back4app.com/2016/03/01/quick-wizard-migration/**

**Comment by davimacedo** [comment]
+1

**Comment by alexvenom** [comment]
+1

**Comment by brunopicinin** [comment]
+1

**Comment by abnertcj** [comment]
+1

**Comment by julioctcampos** [comment]
+1

**Comment by adrianodsq** [comment]
+1

**Comment by AyrtonAlves** [comment]
+1

**Comment by alponline** [comment]
+1

**Comment by mtrezza** [comment]
While I am sure that a list of hosted **commercial** Parse Server providers would be beneficial to many programmers who don't want to deal with setting up a Parse Server, I am not sure if the git repo should be used as a commercial advertising channel.

However, such a list should also include
http://www.parseground.com
http://parse-hosting.oursky.com

And maybe also providers who offer migration tools for non-Parse environments:
http://www.backendless.com
http://www.backand.com
http://www.shephertz.com

**Comment by alyssoncm** [comment]
Have you checked this list?
https://github.com/ParsePlatform/parse-server/wiki

**Comment by seijiakiyama** [comment]
+1

**Comment by mtrezza** [comment]
@alyssoncm Yes. The list contains infrastructure providers to run an open-source Parse Server. It is not a list of commercial Parse-mBaaS providers, e.g. https://github.com/relatedcode/ParseAlternatives

**Comment by alyssoncm** [comment]
I'm not sure about that.

**Comment by mtrezza** [comment]
@alyssoncm If there are mBaaS providers on the list then they should be removed from the wiki of Parse Server. Thanks for pointing this out.

**Comment by alyssoncm** [comment]
ok.

**Comment by davimacedo** [comment]
@mtrezza back{4}app is also an infrastructure provider to run open-source Parse Server. The difference is that back4app host not only the server or the database, but the complete solution. So the users are able to easily host their parse app with minimum effort, almost no changes in the frontend and without worrying about servers like it was in parse.com.

**Comment by davimacedo** [comment]
Moreover the solutions in https://github.com/ParsePlatform/parse-server/wiki are also commercial and does not allow complete and easy hosting of all app like back{4}app does.

**Comment by Knana** [comment]
It doesn't seem like your solution is ready when you compare to providers like, for example, NodeChef (https://www.nodechef.com/parse-server). I think when it's ready you should be added to the community links.

**Comment by walhs** [comment]
+1

**Comment by davimacedo** [comment]
@knana back{4}app is actually the unique solution that allow completely and easy migration of existent parse apps and also the creation of new ones. More than 1K apps were migrated and are nicely running in our servers.

**Comment by gfosco** [comment]
Sure.. added the link to the wiki.
