### ISSUE TITLE
Problem to save parse file to an object

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/parse-server#927]
Here is the code to upload an base64 image data to my parse server:

        var parseFile = new Parse.File("mythumbnail", { base64: base64ImgData });
        var Post = Parse.Object.extend("Post");
        var post = new Post();
        post.set("title",title);
        post.set("thumbnail",parseFile);     
        post.save(null,{
            success: data => {
              alert('saved data');
        },
        error: (data,error) => {
              alert(error.message);
        }
  
But got the following error message:

![screen shot 2016-03-07 at 6 41 16 pm](https://cloud.githubusercontent.com/assets/8099731/13622715/9380aa8e-e5db-11e5-9a1a-f9927a0721db.png)

Any idea? Thanks.

P.S.: There is no post collection in Mongodb before it's created by my code.

**Comment by gfosco** [comment]
Take a look in the _SCHEMA collection, find the row for your Post class, and remove the 'thumbnail' key or replace the value with 'file'.  Is it possible the collection previously existed and a string was stored there?

**Comment by zhouhao27** [comment]
I deleted everything in database and start from scratch. It works. But this doesn't work:

> var parseFile = new Parse.File("thumbnail-image.jpg", image, "image/jpg");

The error message is: 

> Cannot create a Parse.File with that data.

**Comment by flovilmart** [comment]
I'll check it out

**Comment by flovilmart** [comment]
Are you using by any chance Parse.Cloud.httpRequest?

**Comment by zhouhao27** [comment]
No. The image data is from a cordova plugin. I got the image from photolibrary or from a camera.

**Comment by zhouhao27** [comment]
Another question is how to create a Parse.File object based on my file local path (I got the file path from another cordova plugin. The path is in my mobile local file system.)

**Comment by flovilmart** [comment]
This seems to be a JS SDK error, please update your SDK to the latests version and also see the documentation here for files: http://www.parse.com/docs/js/api/classes/Parse.File.html
