### ISSUE TITLE
push notification with IOS

### ISSUE THREAD

**Issue by vineetbindal** [ParsePlatform/parse-server#928]
we are able to generate a certificate by following [these](https://github.com/ParsePlatform/PushTutorial/blob/master/iOS/README.md#1-creating-the-ssl-certificate) steps. 

We get a parseapp.cer file. But where do i get the below three details? 

pfx: '', // The filename of private key and certificate in PFX or PKCS12 format from disk
cert: '', // If not using the .p12 format, the path to the certificate PEM to load from disk
key: '', // If not using the .p12 format, the path to the private key PEM to load from disk

**Comment by gfosco** [comment]
In step 7 under https://github.com/ParsePlatform/PushTutorial/blob/master/iOS/README.md#12-configuring-your-app-id-for-push-notifications it has you export a .p12 file, which contains both the cert and the key.  You only need to provide the full path to the p12 file in the `pfx` key.
