### ISSUE TITLE
Cloud function doesn't return Parse.Object

### ISSUE THREAD

**Issue by Tux1** [ParsePlatform/parse-server#93]
Hi,
I am moving to my own Parse Server thanks to your guide and your release.

I just have question on Cloud Function. 
I have got some functions returning Parse.Object. When I use the Parse backend, I get Parse.Object (extended or not). When I use my own server, Cloud function returns regular JS object instead of Parse.Object.
Is it the correct behavior or that's a bug ?

Thanks !

**Comment by natanrolnik** [comment]
Should be pretty simple to solve I imagine. 
@gfosco is there any PR already taking care of this? If not, could you give us some direction? Is this related to [here](https://github.com/ParsePlatform/parse-server/blob/master/functions.js#L38)?

**Comment by gfosco** [comment]
Please re-open if you're still experiencing this issue on 2.1.2.

**Comment by Tux1** [comment]
when I try a simple function: 
```
Parse.Cloud.define('toto', function(req, res){
	var query = new Parse.Query('Bar');
	query.get('0176rS9mpi').then(function(bar){
          res.success(bar)
}, function(err){
res.success(err)
});
});
```

I get : 
```
{
  "result": {
    "code": 107,
    "message": "Received an error with invalid JSON from Parse: Cannot POST /classes/Bar\n"
  }
}
```
