### ISSUE TITLE
Is there a database template for new Parse-Server App?

### ISSUE THREAD

**Issue by kenglou** [ParsePlatform/parse-server#930]
as titled.
I'm thinking if I want to use the Parse-Server as one of my app's backend, after i configure everything by pulling the Parse-Server-Example and Parse-Dashboard and done. I found that my database is empty.
Is there any basic template for parse database creation?

Thank you.

**Comment by gfosco** [comment]
That's one of the cool things about Parse, you don't need to seed a database.  Just start using it, sign up a user, save some Parse Objects.  Use the dashboard if you want to set up classes and columns first, but most people just start using it.
