### ISSUE TITLE
$inQuery is not supported in Parse.Push.send

### ISSUE THREAD

**Issue by carmenlau** [ParsePlatform/parse-server#931]
When using `matchesQuery` in `Parse.Push.send` where option, the push will fail silently. After checking, found that following error will be thrown in `PushController` when updating badge in `badgeUpdate` function.

```
{ name: 'MongoError',
  message: 'unknown operator: $inQuery',
  stack: undefined,
  driver: true,
  index: 0,
  code: 2,
  errmsg: 'unknown operator: $inQuery' }
```

**Comment by flovilmart** [comment]
@carmenlau can you give me the query so I can add a test and work on a fix
