### ISSUE TITLE
IOS SSL Problem OSX/iOS

### ISSUE THREAD

**Issue by PunkStarStudios** [ParsePlatform/parse-server#937]
REST servie seems to be running fine. But trying to go in through the SDK in ios (version 12) using this code results in an error.

    [Parse initializeWithConfiguration:[ParseClientConfiguration configurationWithBlock:^(id<ParseMutableClientConfiguration>  _Nonnull configuration) {
        configuration.applicationId = @"myapplicationid";
        configuration.clientKey = @"myclientkey";
        configuration.server = @"http://example.com:1337/parse/";
    }]];

Error - The resource could not be loaded because the App Transport Security policy requires the use of a secure connection. (Code: 100, Version: 1.12.0)

So I went through the pains of settings up SSL and setting the server to 
configuration.server = @"https://example.com/parse/classes/members";

OSX still fails (but with a null error)
Doing a REST request via curl to HTTP://example.com:1337/parse works fine
But a rest request via curl to HTPS://example.com/parse/classes/members
come back with 
"Cannot GET /classes/Members/"

It would see that disabling SSL on the ios/osx is the bandaid approach that could work here ... and I'd be willing to do that - if I could figure it out - otherwise - I am at a stand still.

Anyone get SSL working fine on an ubuntu 14.04 parse server for SDK requests?

**Comment by gfosco** [comment]
Above, did you mean to set `configuration.server = @"https://example.com:port/parse";` without classes/members?

**Comment by Cliffordwh** [comment]
@PunkStarStudios yes i have it working fine.  So if i understand correctly you can not call any classes on the HTTPS?

**Comment by PunkStarStudios** [comment]
Ooops gfosco - ya sorry - miss pasted up top - It should have read ->
But a rest request via curl to HTPS://example.com/parse/

And CLiffordwh - I am pretty damn sure you're right - I think it's an nginx problem. Tearing my hair out a it with it.
The /etc/nginx/sites-enabled/default file looks like ->
server {
    listen 80;
    listen [::]:80 default_server ipv6only=on;
    return 301 https://$host$request_uri;
}

# HTTPS - serve HTML from /usr/share/nginx/html, proxy requests to /parse/
# through to Parse Server
server {
        listen 443;
        server_name example.com;

        #root /usr/share/nginx/html;
        root /var/www/parse;
        index index.html index.htm;

        ssl on;
        # Use certificate and key provided by Let's Encrypt:
        ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';

        # Pass requests for /parse/ to Parse Server instance at localhost:1337
        location /parse/ {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://localhost:1337/;
                proxy_ssl_session_reuse off;
                proxy_set_header Host $http_host;
                proxy_redirect off;
        }
        location / {
                try_files $uri $uri/ =404;
        }
}

That's just the latest rendition of the file above. I've gone through too many attempts to count them all.

example.com would be replaced with the domain name that I have an SSL certifcate on.
/var/www/parse/ is the location I have the parse server code (which is working fine under http)

**Comment by Cliffordwh** [comment]
@PunkStarStudios looks right. Can i ask you to test something quick. Is the site available at HTPS://example.com/parse/parse/ ?

cause then i might know whats wrong.

**Comment by PunkStarStudios** [comment]
Actually - in my latest nginx config file - I already had the root set to /var/www

huh.
So maybe I just have to change the location thingy?
Anyhow - interested in hearing your thought @Cliffordwh - I'm sure there may be "wrong" ways to fix this so I'd love your input.

**Comment by Cliffordwh** [comment]
@PunkStarStudios  100%  just remove /parse from the default mount and you will be good to go. Had the same prob!

All the best

**Comment by Cliffordwh** [comment]
@PunkStarStudios lol, 100% Glad you came right!

Topic closed!

**Comment by cyring** [comment]
Ive crossed the same issue, also solved by replacing /parse by / in the nginx location declaration. 
Thanks guys for the tips

**Comment by davidbilly** [comment]
@cyring you also can modified index.js file :  
var mountPath = process.env.PARSE_MOUNT || '/parse'; 
to 
var mountPath = process.env.PARSE_MOUNT || '/'; 

and keep that nginx location /parse/ { ... }

this works for me :D

**Comment by cyring** [comment]
@davidbilly :+1: for the tip
Will it run fine with 2 servers such as Parse and its Dashboard ?
So far, [in this post](https://github.com/ParsePlatform/parse-dashboard/issues/64), my working configuration files.

**Comment by davidbilly** [comment]
@cyring 
For Dashboard i can access but it's return blank page.
error : Uncaught SyntaxError: Unexpected token < 
Still fixing, no idea what happen :( 

i need location / { ... } for deny access :( only allow /parse and /dashboard 
Any idea on this?
