### ISSUE TITLE
can't seek in audio

### ISSUE THREAD

**Issue by occurrentarts** [ParsePlatform/parse-server#938]
Using Elastic Beanstalk + MongoLabs using the default GridStoreAdaptor.

For Legacy files ( files.parsetfss.com ) I'm able to seek to different places in the file:
http://files.parsetfss.com/e0a8e22b-7a69-489a-9de7-01d63f0336c0/tfss-d51309dc-8501-4b5e-94b7-d58878347123-64_Worlds_Fair.mp3

But for files uploaded after migration, I'm unable to get the duration of the clip or seek to different places in the file, even in the browser:
http://cosimo-server.us-east-1.elasticbeanstalk.com/parse/files/VD7BXQBfHKNdz0RBFdH3c22a4stYADM87AATw9bJ/a578a74497236ef9c875c9c27fef7646_TinyPieces.mp3

the audio just restarts every time i try.  I assume this has to do with the headers for the file not including an "Accepts-Range"?

Is anyone else able to scrub through their media?  
Would switching to the s3 adaptor solve this issue?

**Comment by occurrentarts** [comment]
i can confirm that files uploaded to s3 using the s3adaptor do not suffer from this issue.
so perhaps this is a bug with the GridStoreAdaptor?

**Comment by gfosco** [comment]
I don't think it's a bug, just that it doesn't support the same access methods as an S3 bucket.  The only way to get a file out of GridStore is all at once, from the start.  GridStore wouldn't really be a wise or recommended solution for production apps anyway, but it's not bad for development and testing.  S3 is highly recommended, though.

**Comment by EricNetsch** [comment]
@gfosco 
Confirming this issue using the GCS Adapter. This is a bug and this issue should not be closed. My files seek/ buffer fine on googles side but not as PFfiles. We wasted a ton of time migrating one of our audio apps. Is there any recommended fix for GCS Adapter ??

**Comment by flovilmart** [comment]
Please open on the GCS adapter then. Did you enable direct access so your URL's go directly to the Google Cloud instead of the parse-server?

**Comment by EricNetsch** [comment]
I will submit this under GCS Adapter repo. Direct access works but there is an authentication block. Thanks for the prompt response
