### ISSUE TITLE
Database migration allowed IP's

### ISSUE THREAD

**Issue by lkraider** [ParsePlatform/parse-server#940]
I am performing the database migration while keeping the hosted Parse.com servers for now.

I need to know what are the valid IP's that Parse will access the database from so they are allowed from the firewall rules.

Running the initial migration showed originating IP as [54.85.228.36]. Is allowing this one enough? Is there an IP list available somewhere?

**Comment by drew-gross** [comment]
Hey, since this is an issue with the migration process and not Parse Server, can you go through [parse.com/help](url) please?
