### ISSUE TITLE
is there any file to introduce parse-server's architecture?

### ISSUE THREAD

**Issue by oblank** [ParsePlatform/parse-server#945]
I want to learn and extend parse-server for some reason, but a little confused to how to begin. if there is some wiki about parse-server's architecture, it will help me so much. 
thx.

**Comment by natanrolnik** [comment]
Yes @oblank - in the [wiki](https://github.com/ParsePlatform/parse-server/wiki) you can find more information.
For general instructions on how to deploy Parse Server, you can take a look [here](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide). If you want to know more on how the architecture works, read the [Development Guide](https://github.com/ParsePlatform/parse-server/wiki/Development-Guide).

**Comment by oblank** [comment]
thx @natanrolnik
