### ISSUE TITLE
using parse-1.6.14.js in chrome app

### ISSUE THREAD

**Issue by jitsingh89** [ParsePlatform/parse-server#948]
I am using parse-1.6.14.js library in my chrome app, but i am not able to save user info using parse.user object. 
This is my code:-

> var user = new Parse.User();
    user.set("username", "username");
    user.set("password", "pass");
    user.set("email", "eamil@gmail.com");  
    user.signUp(null, {
      success: function(user) {
        console.log("Save parse call");
        // Hooray! Let them use the app now.
      },
      error: function(user, error) {
        // Show the error message somewhere and let the user try again.
        alert("Error: " + error.code + " " + error.message);
      }
    });

I am getting this error in my console.

Uncaught TypeError: Cannot read property 'getItem' of undefined      parse-1.6.14.js

**Comment by flovilmart** [comment]
where is that `getItem` call? Can you provide a screenshot of the full call stack? Also please update to latest version 1.7.1
