### ISSUE TITLE
add env variables to the push adapter?

### ISSUE THREAD

**Issue by Cliffordwh** [ParsePlatform/parse-server#949]
Hi Guys

Is is possible to add ENV variables to the push adapter?   (Like we have just done for the S3 adapter in version 2.1.5)

or is this already available?   PARSE_SERVER_PUSH?

Trying to set it in a json config with little success. Im not using the parse-server-example so i don't make use of a index.js initializer. 

Making use of the oneSignalPushAdapter.

**Comment by flovilmart** [comment]
you can configure with a PARSE_SERVER_PUSH or --push 
we expect the contents to be a string that can be parsed as a JSON.

in the JSON:

{
   module: full/path/to/OSPushAdapter,
   options: {
   // one signal options
   }
}

then JSON.stringify(pushOptions)
PARSE_SERVER_PUSH="<stringified options>"

**Comment by Cliffordwh** [comment]
@flovilmart Thanks , so i understand correctly in my ecosystem.json file I can set this full string in the PARSE_SERVER_PUSH="" ?

**Comment by flovilmart** [comment]
That *should* work :) Let me know. BE careful with the path to the pushAdapter, this is tricky.

**Comment by flovilmart** [comment]
```
npm start -- --appId app --masterKey master --push '{"adapter": "./Push/OneSignalPushAdapter"}'

> parse-server@2.1.6 start /Users/florent/src/Parse/parse-server
> node ./bin/parse-server "--appId" "app" "--masterKey" "master" "--push" "{\"adapter\": \"./Push/OneSignalPushAdapter\"}"


/Users/florent/src/Parse/parse-server/lib/Adapters/Push/OneSignalPushAdapter.js:49
      throw "Trying to initialize OneSignalPushAdapter without oneSignalAppId or oneSignalApiKey";
      ^
Trying to initialize OneSignalPushAdapter without oneSignalAppId or oneSignalApiKey
```

**Comment by KudosGuy** [comment]
how do you write it in PUSH_SERVER_PUSH, I amalso not using index.js and I need to use this env var in my ecosystem but the parse is ignoring it so when I am trying to send Push it tells me It cannot find a sender...

**Comment by flovilmart** [comment]
PARSE_SERVER_PUSH is an environment variable, just set it to the stringified JSON

**Comment by KudosGuy** [comment]
I did this and it doesnt work 	"PARSE_SERVER_PUSH": "'ios': [ { 'pfx': '/home/parse/dev_cert.p12', 'bundleId': 'SomeID', 'production': false },{ 'pfx': '/home/parse/production_cert.p12', 'bundleId': 'SomeID', 'production': true }]"

**Comment by flovilmart** [comment]
The value you just set is not a valid JSON, `PARSE_SERVER_PUSH='{"ios": [] }'`

**Comment by KudosGuy** [comment]
it doesnt work too, parse is ignoring the PARSE_SERVER_PUSH
{
    "apps" : [{
    "name"        : "parse-wrapper",
    "script"      : "/usr/bin/parse-server",
    "watch"       : true,
    "merge_logs"  : true,
    "cwd"         : "/home/parse",
    "env": {
      "PARSE_SERVER_CLOUD_CODE_MAIN": "/home/parse/cloud/main.js",
      "PARSE_SERVER_DATABASE_URI": "mongodb:...",
      "PARSE_SERVER_APPLICATION_ID": "id",
      "PARSE_SERVER_MASTER_KEY": "master",
	PARSE_SERVER_PUSH="{'ios': [ { 'pfx': '/home/parse/dev_cert.p12', 'bundleId': 'someID', 'production': false },{ 'pfx': '/home/parse/production_cert.p12', 'bundleId': 'someID', 'production': true }] }"
 	}
    }]
}

**Comment by flovilmart** [comment]
Your configuration is malformed!

```
{
"apps" : [{
"name" : "parse-wrapper",
"script" : "/usr/bin/parse-server",
"watch" : true,
"merge_logs" : true,
"cwd" : "/home/parse",
"env": {
"PARSE_SERVER_CLOUD_CODE_MAIN": "/home/parse/cloud/main.js",
"PARSE_SERVER_DATABASE_URI": "mongodb:...",
"PARSE_SERVER_APPLICATION_ID": "id",
"PARSE_SERVER_MASTER_KEY": "master",
"PARSE_SERVER_PUSH": "{'ios': [ { 'pfx': '/home/parse/dev_cert.p12', 'bundleId': 'someID', 'production': false },{ 'pfx': '/home/parse/production_cert.p12', 'bundleId': 'someID', 'production': true }] }"
}
}]
}
```

**Comment by KudosGuy** [comment]
it doesnt work for me.... it keeps telling me in log that it cant find sender for push type..... I tried that on parse 2.1.4 and now on 2.1.6...

**Comment by flovilmart** [comment]
Try to do it in a development environment, without pm2

**Comment by Cliffordwh** [comment]
@KudosGuy did you have any luck with this? Trying both OneSignal and the default with little success.

**Comment by KudosGuy** [comment]
no, I tried like 10 times to start the server with parse-server jsonconfig.json or npm start parse-server and many more and nothing worked, I would report it as a bug and maybe we can get more attention to this, but if you will install parse-server-example you will have the index.js and it is working there, but i really dont know why they are these two versions...

**Comment by Cliffordwh** [comment]
I can confirm PARSE_SERVER_PUSH certainly does work.  I got it to select the adapter ( OneSignal ) but struggling to pass the variables through. But i'm giving it a bash now.

**Comment by KudosGuy** [comment]
@Cliffordwh could you show me the syntax you used for PARSE_SERVER_PUSH?

**Comment by Cliffordwh** [comment]
Options tho, doesn't seem to work for me.   I'm getting Trying to initialize OneSignalPushAdapter without oneSignalAppId or oneSignalApiKey
```

   "PARSE_SERVER_PUSH" :  {"adapter" : "./Push/OneSignalPushAdapter",
                                 "options" : {
                                             "oneSignalAppId": "appid",
                                             "oneSignalApiKey": "apikey"
                                             }
                             }
```

**Comment by KudosGuy** [comment]
I got it running that I hardcoded it in **/usr/lib/node_modules/parse-server/lib/cli/cli-definitions.js**
   
    "push": {
    env: "PARSE_SERVER_PUSH",
    help: "Configuration for push, as stringified JSON. See https://github.com/$",
    default: {
                ios: {
                        pfx: "/home/parse/dev_cert.p12",
                        bundleId: "someApp",
                        production: false
                        }
        }
  }

**Comment by Cliffordwh** [comment]
Glad you got it working. I ended up coding in env's variables for the options too.

**Comment by flovilmart** [comment]
Guys, this is not how it should be configured

**Comment by KudosGuy** [comment]
@flovilmart could you extend your response why? because for me it is the only solution for now... becasue when I add in my ecosystem.json PARSE_SERVER_PUSH it is never initialized, I can see that in log... but with my solution in cli-definitions.js it loads it on startup fine...

**Comment by flovilmart** [comment]
Because the cli-definitions files is not supposed to be edited, as this file will be updated with npm when you update parse-server. There is either a bug when parsing/loading that environment variable, or, you're not providing a valid JSON or any other reason that make it fail. Locally, I can properly load the oneSignal adapter with that method.

**Comment by Cliffordwh** [comment]
@flovilmart i agree. I've done so, but can you pass the options through?

**Comment by flovilmart** [comment]
I just tested again and ```export PARSE_SERVER_PUSH='{"ios":{"pfx":"/home/parse/dev_cert.p12","bundleId":"someApp","production":false}}'``` is working correctly as expected.

For the one signal push adapter, the correct JSON would be:

```"PARSE_SERVER_PUSH" :  {"adapter" : "./Push/OneSignalPushAdapter",
                                             "oneSignalAppId": "appid",
                                             "oneSignalApiKey": "apikey"
}```

**Comment by Cliffordwh** [comment]
@flovilmart Thanks, i see it doesn't use "options". Makes sense now.

**Comment by flovilmart** [comment]
@Cliffordwh this is actually a bug in the adapter loader that don't pass the .options for the push as it's been originally structured differently than other adapter options.

**Comment by KudosGuy** [comment]
fyi... you were right it didnt work becasue of the pm2, even though I reloaded and restarted the parse server via pm2 command it didnt load the new file config but some cached version so It never initialized the push so the PARSE_SERVER_PUSH works good, my mistake

**Comment by notiles** [comment]
Hello all, did any one succeed to launch push with pm2 ?

I launch that with pm2 :

`{
  "apps" : [{
    "name"        : "parse-wrapper",
    "script"      : "/usr/bin/parse-server",
    "watch"       : true,
    "merge_logs"  : true,
    "cwd"         : "/home/parse",
    "env": {
      "PARSE_SERVER_CLOUD_CODE_MAIN": "/home/parse/cloud/main.js",
      "PARSE_SERVER_DATABASE_URI": "mongodb://*******",
      "PARSE_SERVER_APPLICATION_ID": "********",
      "PARSE_SERVER_MASTER_KEY": "**********",
      "PARSE_SERVER_CLIENT_KEY": "*********",
      "PARSE_SERVER_JAVASCRIPT_KEY": "*********",
      "PARSE_SERVER_FILE_KEY": "**********",
      "PARSE_SERVER_PUSH":{ "ios": [ { "pfx": "/home/parse/***.p12", "bundleId": "***", "production": false },{"pfx": "*******", "bundleId": "********", "production": true } ] }
    }
  }]
}`

**Comment by mianfaisal111** [comment]
Hi [flovilmart](https://github.com/flovilmart);
Can you provide me with a solution? I'm using this code for my Parse Cloud configuration. The server responds correctly when integrated with Android, but when I integrate iOS in my config.json file, my Parse server goes down. Could you please guide me on this issue?
Thanks

{
  "appId": "",
  "masterKey": "",
  "readOnlyMasterKey": "",
  "serverURL": "",
  "cloud": "./cloud/main.js",
  "databaseURI": "",
  "auth": {
    "restAPIKey": ""
  },
  "port": ,
  "startLiveQueryServer": true,
  "liveQuery": {
    "classNames": ["Installation", "Role", "Session", "User", "device"]
  },
  "push": {
    "android": {
      "senderId": "",
      "apiKey": ""
    },
    "ios": {
      "token": {
        "key": "/path/name.p8",
        "keyId": "",
        "teamId": ""
      },
      "topic": "",
      "production": true
    }
  }
}
