### ISSUE TITLE
Password reset doesn't work with user beforesave

### ISSUE THREAD

**Issue by carmenlau** [ParsePlatform/parse-server#951]
Update password in reset password page will redirect to *Successfully updated your password!* page. But the password is not updated properly.

The request object in user before save is empty.

Let me know if any information could help!

**Comment by flovilmart** [comment]
This feature is still experimental, that would be nice to have more information about your configuration, the options you passed to ParseServer etc...

**Comment by carmenlau** [comment]
Thanks @flovilmart Please find the information below and hope they are helpful.

#### Configuration

```
var api = new ParseServer({
  appName: "",
  databaseURI: databaseUri || '',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || '',
  masterKey: process.env.MASTER_KEY || '',
  serverURL: process.env.SERVER_URL || '',
  fileKey: process.env.FILE_KEY || '',
  filesAdapter: new S3Adapter(
    process.env.AWS_ACCESS_KEY_ID || ''
    process.env.AWS_SECRET_ACCESS_KEY || '',
    process.env.BUCKET_NAME || '',
    { directAccess: true }
  ),
  push: {
    ios: {
      pfx: process.env.APN_P12_FILE_PATH || '',
      bundleId: process.env.APN_BUNDLE_ID || '',
      production: process.env.APN_PRODUCTION || false
    }
  },
  publicServerURL: process.env.SERVER_URL || '',
  emailAdapter: SimpleMailgunAdapter({
    apiKey: '',
    domain: '',
    fromAddress: 'support@testing.com',
  })
});
```

#### Testing steps

1. Request reset password
1. Got reset password email
1. Follow the link to reset password
1. See the *Successfully updated your password!* page
1. Login again, but the password was not changed

When we test on step 3, reset password fail inside our user before save function. We validate the username in the user before save function, but `request.object.getUsername()` is empty during reset password.

We tried remove the validation logic and changed to the following. Reset password still doesn't work.
```
Parse.Cloud.beforeSave(Parse.User, function(request, response) {
    response.success();
});
```

The reset password works again, after I completely remove the user before save function.

#### Parse server version

v2.1.5

**Comment by flovilmart** [comment]
Looks like it's fixed.

**Comment by iamroberthood** [comment]
Does this work as it did before, where a password reset website was built in, or does it need to be written? I've implemented this, and pointed it towards my heroku parse app, but it can't load the address. For reference, here is the address t's going to: http://myapp.herokuapp.com/apps/oom7uqiVMrB7qfAMnhAoPHgX7WUms73ulXCX5jf9/request_password_reset?token=fJHwAqrh9ep9D6MoCKtytHcIh&username=myemail%40gmail.com
