### ISSUE TITLE
Session token are in _User collection instead of _Session collection

### ISSUE THREAD

**Issue by douineauromain** [ParsePlatform/parse-server#953]
Hello,

#### Environment Setup
Before migration 
![image](https://cloud.githubusercontent.com/assets/8361263/13670506/acfcba8a-e6ca-11e5-84d9-ab56922a3f70.png)

#### Steps to reproduce
Call /parse/users/me

#### Logs/Trace
"invalid session" error

I've checked the mongoDB, and session token of users are in the _User collection, but i've seen parse-server search tokens in _Session collection.

How can i resolve this ?
Thanks

**Comment by flovilmart** [comment]
parse-server don't support non revocable sessions. Your have too transition your users to revocable sessions, following the parse documentation

**Comment by gfosco** [comment]
This is correct.  Parse implemented revocable session tokens more than a year ago, and when building parse-server we decided not to support both.  If you haven't upgraded to revocable tokens, your users will just need to re-login.  Sorry for the inconvenience.
