### ISSUE TITLE
Parse and OneSignal register for Notifications deviceToken and OneSignal's GCM registrationId incompatible

### ISSUE THREAD

**Issue by 432player** [ParsePlatform/parse-server#954]
Hey guys,

We have our own Parse-Server running, using it for an Android & IPhone app.
We are also using Parse Cloud Code and the OneSignalAdapter for the Push Notifications.

To register the Android device to OneSignal we must use their SDK and register the device.
The first installation worked fine and both Tokens (in the Parse Installation Table and the Token returned from OneSignal) were compatible and the pushes arrived as expected.

The moment we uninstalled the app from the Android device and reinstalled it for some reason both Tokens from the Parse _installation table (deviceToken) and the Token returned from OneSignal were different and no more pushes reached the device.

This also happens on a couple of Android devices so we believe this issue is consistent.

We wanted to solve this issue by saving the deviceToken we receive from OneSignal and save it into the deviceToken field in the Parse _installation table. BUT, the deviceToken field in the Parse _installation table is a Readonly field (from client side).  

Right now our solution is to save the deviceToken through a CloudCode function that we've written and that works for us :)

For those who have insight on this we would love some advice.

Cheers!

**Comment by gdeglin** [comment]
Yes, GCM tokens may be automatically unregistered for an app after it is uninstalled. For this reason, OneSignal requests a new registration token once the app is re-installed and the old token may stop functioning.

Note that in rare cases OneSignal may also change a device's token even if your app has not been opened. This will occur if GCM replies with a Canonical ID response to a notification. 

In either case, updating the _Installation for that device with the latest GCM token each time your app is opened is a good idea.
