### ISSUE TITLE
is it include JavaScript SDK? 

### ISSUE THREAD

**Issue by edwardyue** [ParsePlatform/parse-server#955]
I would like to create html to call cloud code and I found that I need to replace the following in my html

<script src="//www.parsecdn.com/js/parse-1.6.14.min.js"></script>

Is this parse-server included this SDK? if no, how can I install in the same parse-server?

Thanks for advise!

**Comment by hramos** [comment]
Parse-Server is not included in the Parse JavaScript SDK. They're too different things, although they can work together (e.g. clients using the JS SDK can read from and write to a Parse-Server).
