### ISSUE TITLE
S3Adapter is not defined!

### ISSUE THREAD

**Issue by ckarmy** [ParsePlatform/parse-server#961]
## **I'm trying to connect my parse-server with my S3 bucket but I get this error when I start my server:**
`filesAdapter: new S3Adapter(
                    ^

ReferenceError: S3Adapter is not defined
    at Object.<anonymous> (/var/www/pdv/index.js:19:21)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3`

## **And index.js looks like:**

var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var S3Adapter = require('parse-server/S3Adapter');

var databaseUri = 'mongodb://adminpdv:UJ4R85d#9w#mGo@198.199.67.13:27017/pdv';

if (!databaseUri) {
  console.log('DATABASE_URI not specified, falling back to localhost.');
}

var api = new ParseServer({
  databaseURI: 'xxxx',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: 'xxxx',
  masterKey: 'xxxx', //Add your master key here. Keep it secret!
  serverURL: 'http://localhost:1338/parse', // Don't forget to change to https if needed
  filesAdapter: new S3Adapter(
    "xxx",
    "xxx",
    "MyBucketName",
    {directAccess: true}
  ), 
  fileKey: '355dcc56-8b0b-4e27-9459-8df882118f2c'
});

var app = express();

// Serve the Parse API on the /parse URL prefix
var mountPath = process.env.PARSE_MOUNT || '/parse';
app.use(mountPath, api);

// Parse Server plays nicely with the rest of your web routes
app.get('/', function(req, res) {
  res.status(200).send('I dream of being a web site.');
});

var port = 1338;
app.listen(port, function() {
    console.log('parse-server-example running on port ' + port + '.');
});
How can solve this? 

THANKS!!!!

**Comment by weengo** [comment]
On your index.js, line 3, replace with this, and run again

`var S3Adapter = require('parse-server').S3Adapter;`

**Comment by gfosco** [comment]
^ what he said. :)
