### ISSUE TITLE
Login via Facebook with new user fails

### ISSUE THREAD

**Issue by jkunzika** [ParsePlatform/parse-server#963]
#### Environment Setup
![image](https://cloud.githubusercontent.com/assets/3926848/13681636/2c687d1c-e6cc-11e5-8862-f3287855026f.png)

I have also set up Parse Server with my Facebook App Id and it works with logging in existing users.

#### Steps to reproduce
Login via Facebook on Android with new user (user that had not signed up before data/server migration).

#### Logs/Trace
W/ParseLoginFragment: Facebook login failed, exception: com.parse.ParseRequest$ParseRequestException: {"message":"Received an error with invalid JSON from Parse: Cannot POST \/classes\/_User\/local0\n","code":107}

So, I am able to login using my Android app using a Facebook account that was already signed up before I migrated to Parse Server, but when I created a new test Facebook account to login with, it gives me this error and doesn't allow me to login with new users.

Is there any way I can resolve this?

Thanks.

**Comment by flovilmart** [comment]
odd thing that your user has an ID local0 @wangmengyan95 ? is that Android specific?

**Comment by arpit529** [comment]
i am having similar issue when login on iOS app with new user. existing user can login in but gets log out if app is killed.

**Comment by flovilmart** [comment]
Are you still experiencing the issue? The issue is getting pretty old, can you update to 2.2.4 and let us know if you still experience a problem?

Feel free to re-open then.
