### ISSUE TITLE
REST API URL equivalent

### ISSUE THREAD

**Issue by poojanjhaveri** [ParsePlatform/parse-server#965]
How do I use the REST API equivalent for Parse Server. 

For eg.
<app_Id>p:javascript-key=<Javascript_key>@api.parse.com/1/classes
How do I make this work with Parse Server ?

Tried <app_Id>p:javascript-key=<Javascript_key>@<AWS EB URL>/parse/1/classes
This does not work.

**Comment by Cliffordwh** [comment]
@poojanjhaveri Have you set up the path client side to your server?  are you making use of parse-1.6.14.min.js ? It can be configured then there.  You will also need to pass YOUR_APP_ID. 

Remove the 1 and run yourdomain.com/classes

**Comment by flovilmart** [comment]
I don't belive we support basic auth passed as that at the moment.
You need to set the request headers : {
  X-Parse-Application-Id: 'appId',
  X-Parse-Javascript-Key: 'javascriptKey'
}

**Comment by poojanjhaveri** [comment]
@Cliffordwh  : Thanks removing 1 worked.
