### ISSUE TITLE
Push: GCM Canonical IDs

### ISSUE THREAD

**Issue by Dynogic** [ParsePlatform/parse-server#966]
Hi there,

I noticed that the GCM Push does not support canonical IDs yet. https://developers.google.com/cloud-messaging/registration#canonical-ids

Any idea to when it'll be implemented? Its very scary pushing current code into production when there could be possibilities of duplicate messages or complete push notification failure (the latter being a rare event where Google decides to change registration IDs. Quote from GCM docs: "If the registration token expires (for example, Google might decide to refresh registration tokens, or the APNS token has expired for iOS devices).")

Thanks,
Jake.

**Comment by wangmengyan95** [comment]
Hi @Dynogic, if you are using `Parse-SDK-Android`, we have the client dedupe logic, you do not need to worry about it too much. We will add the `Canonical ID` support to remove the invalid registration ID later.

**Comment by flovilmart** [comment]
@Dynogic , @wangmengyan95 I moved that issue to the proper repository now that we split the dependencies https://github.com/parse-server-modules/parse-server-push-adapter/issues/12
