### ISSUE TITLE
Returned datetime is not the same to online parse server

### ISSUE THREAD

**Issue by huang1196** [ParsePlatform/parse-server#967]
After the user login, our server returns a datetime to the client.
    `var timestamp = new Date(Date.now());`

Our client parse the datetime by:
   `DateTime timeStamp = DateTime.Parse(t.Result["ts"].ToString());`

For my local parse server, the datetime format  recieved by client is:
  `"2016-03-11T04:49:52.507Z"`

While for the online parse server, the datetime format recieved by client is:
 ` "3/11/2016 04:49:52 AM"`

If we convert the string to datetime, the 1st string will be converted to local time while the 2nd is utc time.
  `Debug.Log (DateTime.Parse("2016-03-11T04:49:52.507Z") + "  :  " + DateTime.Parse("3/11/2016 04:49:52 AM"));`
the result is:
    `3/11/2016 12:49:52 PM  :  3/11/2016 4:49:52 AM`

Even if we should not use the method DateTime.Parse(), but why online parse-server's datetime is different to local parse-server's?  Shouldn't them be the same?

**Comment by hramos** [comment]
Parse Cloud Code and parse-server Cloud Code are two different environments, and there are bound to be some small differences between the two. You can use your favorite DateTime string manipulation JavaScript library to work around this. 

I'm closing this as we expect that some developers will need to update their Cloud Code when migrating to parse-server, and we are not considering minor differences like these as issues in parse-server.
