### ISSUE TITLE
How to upload file to parse server from my ionic application?

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/parse-server#968]
I need to upload image, audio, video files to my parse server. There is no problem to upload image through **cordova-camera** plugin. What I did:

1. Get image data through the plugin by setting the option to Camera.DestinationType.DATA_URL
2. Create Parse.File like this

`parseFile = new Parse.File(thumbnailName, {base64 : image});`

But for audio, video file, I'm using cordova media capture plugin which return a mediaFile object:

```
    mediaFile.name = pluginResult[i].name;
    mediaFile.localURL = pluginResult[i].localURL || pluginResult[i].fullPath;
    mediaFile.fullPath = pluginResult[i].fullPath;
    mediaFile.type = pluginResult[i].type;
    mediaFile.lastModifiedDate = pluginResult[i].lastModifiedDate;
    mediaFile.size = pluginResult[i].size;

```

which only include a local path instead of base 64 data. How should I upload to parse server? Any suggestions thanks.

**Comment by Cliffordwh** [comment]
@zhouhao27 You need to make use of the cordova-plugin-file-transfer. This will allow audio and video.

**Comment by zhouhao27** [comment]
Thanks. By referring to the document, the cordova-plugin-file-transfer:

```
var options = new FileUploadOptions();
options.fileKey = "file";
options.fileName = fileURL.substr(fileURL.lastIndexOf('/') + 1);
options.mimeType = "text/plain";

var ft = new FileTransfer();
ft.upload(fileURL, encodeURI("http://some.server.com/upload.php"), win, fail, options);

```

Not very sure what is the url for parse-server for uploading files. Any suggestion?

**Comment by Cliffordwh** [comment]
Well i guess there is many ways to do it with that plugin or with parse it self. Something like this could work. ( excuse errors, haven't validated this. ) Depends i guess on the approach you taking as a developer.

```
var ParseFile = new Parse.File("recording.wav", file);
                    console.log(ParseFile + "    var Parsefile is here")
                    ParseFile.save().then(function() 
                    {
                        var recording = new Parse.Object("Recordings");
                        console.log(recording)
                        /*Set variables */
                        recording.set("recording", ParseFile);
                 
                       /*Save to server */
                        recording.save({
                            success: function(recording) {
                                alert("Recordings saved successfully");
                            },
                            error: function(recording, error){
                                alert("Recordings save failure, error = " + error + " error msg: " + error.message);
                            }
                        });
                    },function(error) {
                        alert("File save failure");
                    });
              }

**Comment by Cliffordwh** [comment]
@zhouhao27 you would need to make use of cordova-plugin-media-capture to capture the audio or video with example above.

**Comment by zhouhao27** [comment]
@Cliffordwh Yes, I use **cordova-plugin-media-capture** to capture the audio or video. In your example, the problem is I don't know what is the **file**:

 `new Parse.File("recording.wav", file);`

Based on my understanding, the **file** should be a base64 string. But the result of **cordova-plugin-media-capture** is a local file path.

In the **cordova-plugin-file-transfer** example, I don't know what the url of parse for uploading is.

**Comment by Cliffordwh** [comment]
The file is the true path to where you are storing it. If you making use of local storage and not sqlite. Then something like this is what it would look like (once again not validated and needs to go into your function):


            var path = audioData[0].fullPath;
            window.localStorage['tmpRecord'] = path;
            window.requestFileSystem(LocalFileSystem.TEMPORARY, 0, gotFile, fail);

           function gotFile(fileSystem) {
                fileSystem.root.getFile(audioData[0].name, {create : true}, gotFileEntry, fail);
           }

           function gotFileEntry(fileEntry) {
                fileEntry.file(gotFile, fail);
            }

            function gotFile(file){
                saveToParse(file);
            }

Then you can write a function and save it to parse ( `file` will now be filled ).  Please remember this is just a quick idea. Validations , options and other functions you might need to add. But in theory something like the above should work.

**Comment by zhouhao27** [comment]
@Cliffordwh Based on your answer, my understanding is:

1. Get the file path through the **cordova-plugin-media-capture**
2. Save to a temp storage (but is this necessary?)
3. Read the file into **file** object
4. Save the **file** object into parse

Am I right? 

Once again, thanks.

**Comment by Cliffordwh** [comment]
@zhouhao27 Yes. 

No, temp storage is not needed.

**Comment by zhouhao27** [comment]
@Cliffordwh Ok, I thought this is used to save to temp storage:

`window.localStorage['tmpRecord']` = path;

It's to save the path only. I guess the **window.requestFileSystem** is used to read file and return a **file** object. Maybe it's the same as what **<input type="file">** does.

**Comment by Cliffordwh** [comment]
100%

**Comment by zhouhao27** [comment]
It's pretty close now. I'm able to read a html file from ApplicationDirectory and save to parse server:

  ```
upload(path,type,name) {
  var gotFile = (fileEntry) => {
      fileEntry.file((file) => {
        var reader = new FileReader();
        reader.onloadend = (e) => {

          var parseFile = new Parse.File(name,{base64:reader.result});
          var Post = new Parse.Object.extend('Post');
          var post = new Post();
          post.set('file',parseFile);
          post.save(null,{
            success: (data) => {
              alert('saved');
            }, 
            error: (err) => {
              alert(err.message);
            }
          })
        }
        reader.readAsDataURL(file);
      });

    var fail = (error) => {
      alert(error.message);
    }
    window.resolveLocalFileSystemURL(cordova.file.applicationDirectory + "www/index.html", gotFile, fail);
}
```

The above mentioned code is reading html file from applicaitonDirectory. And I'll saved it to parse server. This works fine.

But when I get the path, type, name of audio from cordova-media-plugin, the reader.result is **undefined**.

The code is all the same except the last statement:

`window.resolveLocalFileSystemURL(path, gotFile, fail);`

Any idea? Thanks.

**Comment by zhouhao27** [comment]
Finally, got it work by referring to this:

http://stackoverflow.com/questions/29192327/get-base64-of-audio-data-from-cordova-capture
