### ISSUE TITLE
res.render doesn't work for my cloud code

### ISSUE THREAD

**Issue by zhouhao27** [ParsePlatform/parse-server#970]
My file structure is:

> server.js
> cloud 
> >  |--- main.js
> >  |--- views
> > >    |--- hello.ejs

My server.js:

```
var express = require('express')
var ParseServer = require('parse-server').ParseServer
var app = express()
var config = require('./config.json')[app.get('env')]
var bodyParser = require('body-parser')

app.set('views', 'cloud/views');  // Specify the folder to find templates
app.set('view engine', 'ejs');    // Set the template engine
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())

var api = new ParseServer({
  databaseURI:  config.dbUrl,
  cloud:        __dirname + '/cloud/main.js',
  appId:        config.appId,
  masterKey:    config.masterId, 
  fileKey:      'optionalFileKey',
  serverURL:    config.serverUrl
})

app.use('/parse', api)

app.listen(config.port, function() {
  console.log('parse-server-example running on port ' + config.port + '.');
})
```

My cloud code:

```
Parse.Cloud.define('hello',(req,res) => {
  res.render('hello',{message:'Great!'})
});

```

But I got the following error message:

> Uncaught internal server error. [TypeError: res.render is not a function] TypeError: res.render is not a function

What's wrong with my code? Thanks.

**Comment by gfosco** [comment]
res.render is not something which works in cloud code.  You respond to function by calling `res.success(something)` with a string or an object which is received by the client parse SDK.

You can configure other routes in index.js for web browser usage, where you can render html.

**Comment by zhouhao27** [comment]
But it still doesn't work. I've changed my server.js by adding the following line:

```
app.get('/hello',(req,res) => {
  res.render('hello',{message:'hello'})
})

```

I got an error message:

> Error: Cannot find module 'ejs'
>    at Function.Module._resolveFilename (module.js:326:15)
>    at Function.Module._load (module.js:277:25)
>    at Module.require (module.js:354:17)
>    at require (internal/module.js:12:17)
>    at new View (/usr/local/lib/node_modules/express/lib/view.js:78:30)
>    at EventEmitter.render (/usr/local/lib/node_modules/express/lib/application.js:569:12)
>    at ServerResponse.render (/usr/local/lib/node_modules/express/lib/response.js:961:7)
>    at /Users/zhouhao/Projects/WOWSocial/app/server.parse/server.js:30:7
>    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/express/lib/router/layer.js:95:5)
>    at next (/usr/local/lib/node_modules/express/lib/router/route.js:131:13)

**P.S.: **The ejs is installed through npm in my project already.

**Comment by zhouhao27** [comment]
Got it works by referring to parse-server example. I only changed the package.json:

```
  "dependencies": {
    "body-parser": "^1.15.0",
    "ejs": "^2.4.1",
    "express": "^4.13.4",
    "parse-server": "^2.1.5",
    "kerberos": "~0.0.x",
    "parse": "~1.6.12"    
  },

```

Maybe **parse** and **kerberos** are the key.
