### ISSUE TITLE
requestPasswordResetForEmailInBackground error

### ISSUE THREAD

**Issue by kenjiIdo** [ParsePlatform/parse-server#972]
Hi Dear,
I found the issue when i use forgot password (below function) in PFLoginViewController.

[PFUser requestPasswordResetForEmailInBackground:emailstr block:^(BOOL success, NSError *error) {
        if (success) {
            NSString *title = DFLocalizedString(@"Password Reset",
                                                @"Password reset success alert title in PFLogInViewController.");
            NSString *message = [NSString stringWithFormat:DFLocalizedString(@"An email with reset instructions has been sent to '%@'.",
                                                                             @"Password reset message in PFLogInViewController"), email];
            [DFUIInputAlertView presentAlertInViewController:self withTitle:title message:message];
        } else {
            NSString *title = DFLocalizedString(@"Password Reset Failed",
                                                @"Password reset error alert title in PFLogInViewController.");
            [DFUIInputAlertView presentAlertInViewController:self withTitle:title error:error];
        }
    }];

Alert message: "Password Reset Failed"
Error : {"code":1,"message":"Internal server error."} (Code: 1, Version: 1.12.0)

I used "parse server" version 2.1.5
please help me.

**Comment by flovilmart** [comment]
Did you configure the reset email properly on parse-server. note that this feature is experimental and that we didn't document how to configure it. Please see #627 for more informations
