### ISSUE TITLE
Question of previous usage and possible feature with parse-server

### ISSUE THREAD

**Issue by footcow** [ParsePlatform/parse-server#977]
Hi,

Sorry this is not an issue, but a simple question.
We used to create via API our apps dynamicaly and we had something like 100 apps on our accounts.

If I install a parse-server, I have done the migration of one of our app. OK, perfect, but for this I run an instance of parse-server with a command line like :
`npm start -- --appId foo --masterKey MyMasterKey --serverURL http://localhost:1337/parse --databaseURI mongodb://localhost:27017/foo`

Like this I can access through the API to my foo database perfect with a command like :
`curl -H "X-Parse-Application-Id: foo" http://tappublisher.fr:1337/parse/classes/Location`

Now I want to add the other apps we have ...
And I'm a little stalled here ... 
Will we have to launch an instance of parse-server for each app ?
How can I get a server configuration comparable to the parse.com one, where I'm able to create dynamicaly as many app as I need ? 
Is this possible ?

Hope I'm clear in my request, and hope somebody will be able to give me an answer.
Cheer,

**Comment by flovilmart** [comment]
We don't support multiple apps for the moment on a single parse-server, I've tried to make it happen but cloud code support is too complex for many reasons, and I closed my PR. You could start from here. But we can't guarantee stability nor support for that as you'd be on your own with that development https://github.com/ParsePlatform/parse-server/pull/263

Contributions are always welcome if you crack it!

Right now, your best options are to run multiple parse-server processes on different port, with specific database configurations for each.
As for app creation you could write a script.
