### ISSUE TITLE
Can Parse Server take advantage of every dyno type on heroku?

### ISSUE THREAD

**Issue by mtrezza** [ParsePlatform/parse-server#982]
Heroku offers various _dyno_ types for deploying a Parse Server.

When scaling the dyno for more performance, can Parse Server and the underlying frameworks actually take advantage of all dyno types and resources or are there certain limitations why it would not make sense to scale to specific dyno types? I'm thinking about CPU cores, RAM, etc.

**Comment by flovilmart** [comment]
As parse-server is an express server any scaling strategy that applies to express, also applies to parse-server. 

Hope that helps
