### ISSUE TITLE
Password reset link not working for usernames with "+"

### ISSUE THREAD

**Issue by w4-sjcho** [ParsePlatform/parse-server#993]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Ran https://github.com/ParsePlatform/parse-server-example with changes for email adapter on AWS Elastic Beanstalk.

#### Steps to reproduce
1. Request for password reset for any existing user with username that contains "+".
2. In the password reset email, when the user click the link, "+" gets translated into space.

#### Logs/Trace
n/a

https://github.com/ParsePlatform/parse-server/blob/master/views/choose_password#L152
https://github.com/ParsePlatform/parse-server/blob/master/views/choose_password#L163

Seems choose_password is changing '+' in usernames to ' '. If I change ' ' back to '+' using the browser's dom inspector, changing password works.

**Comment by gfosco** [comment]
Will be fixed very soon by #1001.
