### ISSUE TITLE
"Server not reachable: server version too low"

### ISSUE THREAD

**Issue by r2DoesInc** [ParsePlatform/parse-server#994]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ x] You're running version >=2.1.4 of Parse Server.

- [x ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

I had this working earlier today, but was unable to get my cloud code to show. I started playing with the parser-server-example, and since then, I have been getting this error.

**"Server not reachable: server version too low"**

#### Environment Setup
parse-server@2.1.6
parse-dashboard@2.0.0 
node v4.3.2

#### Steps to reproduce
fresh clone of server and dashboard
configure to point to my instances
load web ui

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

Nothing in dashboard or server logs.

In the dashboard web ui it shows, 
"Server not reachable: server version too low"

**Comment by peturh** [comment]
I had the same issue. I have the parse-server running on same server as parse-dashboard. 

When I change my serverURL in the config to  http://www.mydomain.com/parse it just started to work.
